### ISSUE TITLE
Should we do some less braindead JSON schema?

### ISSUE THREAD

**Issue by elhigu** [Vincit/objection.js#1]
Would it be a good idea to actually write own extended schema, which could be more consistent about nullables and required etc. fields?

Is there any reasonable alternatives? Here was one article to consider: http://gilesbowkett.blogspot.fi/2015/01/why-panda-strike-wrote-fastest-json.html

If we could extend e.g. https://github.com/pandastrike/jsck to support our favor of syntax?

**Comment by koskimas** [comment]
Yes it would!

Couple of things that annoy me the most are related to the nullability. If `null` is one of the accepted types for a property, other constraints like `format` and `enum` are still checked against the null value! This is **cking retarded. Because of this we need to do things like:

```js
{
  type: 'object',
  properties: {
    dateTime: {anyOf: [{type: 'null'}, {type: 'string', format: 'date-time'}]}
  }
}
```

When in fact we just want to say

```js
{
  type: 'object',
  properties: {
    dateTime: {type: 'string', format: 'date-time', nullable: true}
  }
}
```

I think the schema should still remain 100% compatible with JSON schema, so some kind of superset is needed. Should we just add a transformation pass that converts our `nullable` into the `oneOf` format?

I also liked the `required: true` property of the JSON schema v3 more than the `require: ['prop1', 'prop2']` in v4. We could also support that.

One more thing we should support is setting the default values defined in `default`. So for example:

```js
{
  type: 'object',
  properties: {
    num: {type: 'number', default: 42}
  }
}
```

whould set the value of `num` property when the `num` property is missing.

**Comment by elhigu** [comment]
Superset which converts to json schema sounds good approach.

**Comment by kimmobrunfeldt** [comment]
Some options:
* Hapi's validation library: https://github.com/hapijs/joi
* Waterline's(Sails.js) validation library: https://github.com/hapijs/joi

**Comment by fiddur** [comment]
`null` could also be considered as "property missing".

On `insert` and `fromJson`, you leave out the property, and the schema will validate correctly if you haven't set the property as `required`.

On `update` though, it would have to check the `null` and just make sure that it is not `required`.

In my experience, adding `null` as a valid value in a JSON Schema is a bad idea; it already has the logic to say if the property is required, and the purpose of `null` in SQL is to state that there is no value.

**Comment by fiddur** [comment]
@koskimas If you want v3 validation, just override `$validate` with a v3-validator instead.

I think the standard should be the latest working draft, not a mixup with older versions.

**Comment by delaneyj** [comment]
Have you looked at https://github.com/epoberezkin/ajv as it looks like it provides most of what you are looking for.

**Comment by alphanso** [comment]
I believe we should de-couple ORM and validation framework. Objection.js should provide only provide hooks to enable custom validation.

**Comment by elhigu** [comment]
@alphanso I kind of agree. Though it is really convenient to have one official preferred choise, so that users doesnt have to make that choice by them selves.

**Comment by alphanso** [comment]
@elhigu Unless broader community adopts a solution widely like Express. I can't trust completely official choice and have to dig deep to answer following questions :- 
- how it works?
- Does it meet all project requirement now and in foreseeable future?

So it doesn't lessen the burden in most cases for a new user. Personally, I will prefer documentation detailing all reasonable frameworks and some kind of benchmark between them. After that recommendation to use one will go a long way. 

P.S Many objectionJS user may not like official choice. Afterall, they chose it over bookshelf which is more official and closer to knex.

**Comment by koskimas** [comment]
I agree that validation and the ORM stuff are two different concern and could be decoupled. But then again so are query building and connection pooling, but knex does them both. My point is that people like this kind of "batteries included" libraries to get started fast. 

Objection does provide validation hooks and even has [an example](http://vincit.github.io/objection.js/#custom-validation) in the documentation. The interface that needs to be overridden is not the cleanest though and I will provide better hooks at some point in the near future.

**Comment by elhigu** [comment]
@alphanso sorry, I was answering from my phone earlier, so I didn't want to get to details in my earlier message... btw. I have always had feeling that express actually implements a bit too little, since I always have to require body-parser etc. when I use it (like probably 99.9% of all users who uses express).

You can always choose not to use the validator that is coming with objection, so having default doesn't make much difference if you really like to choose to use different validator.

Good thing about having official / standard choice is that when people are looking code made by others that uses objection.js the code will look familiar. Also it will be easier to get started with when all the objection.js examples / documentation refer to that default validator to provide some "best practises" how to implement stuff. 

Also in JavaScript community it really is a problem that there are 101 libraries doing essentially the same thing. It takes great effort and lots of time to choose from them. By giving standard choice there is one problem less to solve for the user. If you trust developers of objection.js enough to provide your ORM it should be ok to trust their judgement of providing good enough validator to start with :)

**Comment by alphanso** [comment]
@koskimas @elhigu Thanks for super-fast response. It does make sense when you gave me knex and express example. I am currently opting for joi. 

I was just hoping for a schema validator which accepts module name like krakenjs middleware configuration. If you guys write a schema validator, please consider this as a probable feature.

**Comment by apkoponen** [comment]
I've managed to get over some of the braindeadness of JSON schema by composing the schemas as modules This makes it easy to reference other schemas (using `$ref`s is PITA) and makes it possible to utilize utility functions for some consepts (such as nullability)

E.g.

```
const bazSchema = require('./bazSchema');

module.exports = {
  type: 'object',
  title: 'Foo',
  description: 'Foo bar baz',
  properties: {
    ...
    bar: nullable(bazSchema),
    ...
  },
```
```
function nullable(schema) {
  return {
    title: 'Nullable ' + (schema.title || ''),
    description: 'String or ' + (schema.description || '') + '.',
    oneOf: [
      {
        title: 'Null',
        description: 'Null value.',
        type: 'null'
      },
      schema
    ]
  }
}
```

**Comment by kapouer** [comment]
It is now trivial to support setting default values: `useDefaults` option from ajv does just that.
Shouldn't it be always on now ?

**Comment by koskimas** [comment]
Objection has supported default values in `jsonSchema` since V0.1.0. Are you having trouble with them?

**Comment by koskimas** [comment]
I just read my own comment from the top 😄 I quess the default values were added a little later, but they are supported now.

**Comment by kapouer** [comment]
Well i was mistaken as well, but reading about `useDefaults: "shared"` is interesting. I'm trying to figure if it means it's possible to squarely pass a function (typically, to set a default date-time).

**Comment by fl0w** [comment]
There's a few ways to solve this, but until we can add a macro via keyword (not yet supported, PR in progress) you'd need to either adding a lifecycle hook ($beforeInsert, $beforeUpdate) or to extend with a CustomQueryBuilder that does this for you by default on specific properties.

**Comment by elhigu** [comment]
I'll close this for now, since the schema validator has been already changed. 

If there are more annoyances or if some of the comments from this thread should still be implemented those specific things could be added as separate github issues.

**Comment by vahe-nikoghosyan** [comment]
```
  static get jsonSchema() {
    return {
      type: "object",
      required: ["firstName"],

      properties: {
        id: { type: "integer" },
        firstName: { type: "string", maxLength: 50, nullable: true }, //nullable
        lastName: { type: "string", maxLength: 50, nullable: true },
        avatar_url: { type: "string", nullable: true, default: "" },
        address: {
          type: "object",
          properties: {
            street: { type: "string", nullable: true }, 
            city: { type: "string", nullable: true },
            zipCode: { type: "string", nullable: true },
          },
        },
      },
    };
  }
```
