### ISSUE TITLE
"forEachChildExpression" does not fail fast

### ISSUE THREAD

**Issue by kibertoad** [Vincit/objection.js#1002]
`objection/lib/queryBuilder/RelationExpression.js`
`forEachChildExpression`

Imagine case where we have 
```
allRelations = {
   childPages
}
```
and deeper down we have
```
node.$relation === 'child_pages'
```

Then we do
```
const relation = allRelations[node.$relation] || null;
```

Currently this will result in null being passed further, which typically will result in non-trivial to debug error deeper down. Are there any valid cases where null is an acceptable resolution outcome? 

Current effect of this is that during .relate operation on misnamed relationships you get
`TypeError: Cannot read property 'relatedModelClass' of null\n    at forEachExpr (/Users/igor.savin/WebstormProjects/core-services/node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:483:46)\n    at RelationExpression.forEachChildExpression`

**Comment by kibertoad** [comment]
@koskimas I can create PR with reproduction test or fail-fast logic if you think that either makes sense :)

**Comment by kibertoad** [comment]
@koskimas Any opinion on this part? Does it behave as intended?..

**Comment by koskimas** [comment]
Sorry for the radio silence. I'd be happy to merge a PR for the fail-fast logic.
