### ISSUE TITLE
Custom join in relationMapping?

### ISSUE THREAD

**Issue by rivertam** [Vincit/objection.js#1004]
Hi! Is it possible to do a custom join with a relationMapping? That is to say, if I have a device that opens a session and then sends updates throughout its session that are just timestamped, is it possible to do a join like this (not sure if this is even valid SQL but it's this idea):

```sql
SELECT * FROM sessions JOIN updates
ON updates.timestamp < COALESCE(sessions.end, NOW()) AND updates.timestamp > sessions.begin;
```

and then for `sessions` to have a `relatedQuery` of `updates`?

**Comment by koskimas** [comment]
There's no way to do that in `relationMappings`.

This should work for the `raw` join:

```js
      const { raw } = require('objection')

      ...

      const extantSessions = await Session.query()
        .join('updates', joinBuilder => {
          joinBuilder.on('updates.deviceId', '=', 'deviceId')
            .andOn('updates.created_at', '>', 'start')
            .andOn('updates.created_at', '<', raw('COALESCE(end, NOW())'));
        })
        .toString();
```
