### ISSUE TITLE
$afterGet being called on upsertGraph

### ISSUE THREAD

**Issue by danmo** [Vincit/objection.js#1005]
Hi, it seems $afterGet is fired on upsertGraph, which breaks the entire upsert operation due to validation errors. on $afterGet I'm massaging the eagerly loaded data a little.

Any idea on how this can be prevented?

**Comment by danmo** [comment]
Documentation does say _This method is not called for insert, update or delete operations_ but this doesn't cover graph upserts I believe.

**Comment by koskimas** [comment]
`upsertGraph` fetches the current state of the graph from the database to be able to figure out which items need to be updated/inserted/deleted.

**Comment by danmo** [comment]
any way to detect the operation while inside the $afterGet call so I can skip data mutation?

**Comment by danmo** [comment]
ahh, I have the queryContext. Lemme check if I can determine the operation by checking it.
