### ISSUE TITLE
1.2.0 changes ManyToMany/HasOneThrough join SQL

### ISSUE THREAD

**Issue by heisian** [Vincit/objection.js#1007]
Postgres 10.4
Objection 1.2.0
Node 10.6.0
Yarn 1.3.2

* [1.2.0/1.1.10 Diff](https://github.com/Vincit/objection.js/compare/aeb38192d359ac8c857a2af326b2310ce696f2a0...258c0a71aa575b2d3787e09bfc4ddc5a7acdb043#diff-076a3b0067156f4b86723b31bf9e5cb5L75)

Objection 1.2.0 generates different SQL than Objection 1.1.10, and this seems by design:
![screen shot 2018-07-19 at 4 02 41 pm](https://user-images.githubusercontent.com/4141828/42974702-3250a36a-8b6d-11e8-94d9-756dc750d460.png)

The change, however, causes `ManyToManyRelation` and `HasOneThrough`'s `$relatedQuery` and `$loadRelated` queries to have invalid syntax.

Objection 1.1.10 sample query:
``` SQL
SELECT     "policy"."documents".*, 
           "policy"."policy_attachables"."attachable_type" AS "attachable_type", 
           "policy"."policy_attachables"."attachable_id"   AS "attachable_id", 
           "policy"."policy_attachables"."policy_type"     AS "policy_type", 
           "policy"."policy_attachables"."policy_id"       AS "objectiontmpjoin0" 
FROM       "policy"."documents" 
INNER JOIN "policy"."policy_attachables"
ON         "policy"."documents"."id" = "policy"."policy_attachables"."attachable_id" 
WHERE      "policy"."policy_attachables"."policy_id" IN (?) 
AND        "policy_type" = ? 
AND        "attachable_type" = ? limit ?
```

Objection 1.2.0 sample query:
```SQL
SELECT     "policy"."documents".*, 
           "policy"."policy_attachables"."attachable_type" AS "attachable_type", 
           "policy"."policy_attachables"."attachable_id"   AS "attachable_id", 
           "policy"."policy_attachables"."policy_type"     AS "policy_type", 
           "policy"."policy_attachables"."policy_id"       AS "objectiontmpjoin0" 
FROM       "policy"."documents" 
INNER JOIN "policy"."policy_attachables" AS "policy.policy_attachables" 
ON         "policy"."documents"."id" = "policy"."policy_attachables"."attachable_id" 
WHERE      "policy"."policy_attachables"."policy_id" IN (?) 
AND        "policy_type" = ? 
AND        "attachable_type" = ? limit ?
```

The 1.2.0 version contains invalid syntax and causes this error:
```
- invalid reference TO FROM-clause entry FOR TABLE "policy_attachables"
```

Sample `relationMapping`:
```node
      return {
        ManyToManyRelation,
        modelClass: TermPolicy,
        filter: {
          attachableType: 'Document',
          policyType: 'TermPolicy',
        },
        beforeInsert(model) {
          model.attachableType = 'Document'
          model.policyType = 'TermPolicy'
        },
        join: {
          from: `documents.id`,
          through: {
            from: 'policy.policyAttachables.attachableId',
            to: 'policy.policyAttachables.policyId',
          },
          to: `termPolicies.id`,
        },
      }
    }
```

This change may or may not only affect relations with `through` - unconfirmed.

**Comment by koskimas** [comment]
Seems to be related to using postgres schemas. Unfortunately those things are not well tested, so there may easily br changes

**Comment by heisian** [comment]
For now, we've version-locked to 1.1.10, and will start looking at additional tests surrounding Postgres schemas to account for our use-case. This might also be a good opportunity to discuss/enact progress on #922.

**Comment by koskimas** [comment]
I'm fixing this now. You should be aware though that all this stuff may break at some point if knex decides to dump the rest of their support for schemas. Or even if they accidentally remove it since there are no tests for this stuff in knex. It's simply not a feature in their book.

**Comment by heisian** [comment]
@koskimas Wow, thank you!

.. as well as the warning about `knex` too.

I previously thought that `withSchema` was not flexible enough for multi-schema joins, but testing in the node REPL, this works:

```node
const res = await knex(
  knex.ref('identities').withSchema('identity')
).join(
  db.knex.ref('users').withSchema('auth'),
  'identities.userId',
  'users.id'
).limit(1)
```

So theoretically, Objection should be able to use the `tableName`/`schemaName` static getters instead of prefixing a `tableName` with the schema, right?

**Comment by heisian** [comment]
@koskimas The changes post-1.2.0 are still affecting the query:
```sql
SELECT     "auth"."addresses".*, 
           "policy"."policy_attachables"."attachable_type"   AS "attachable_type", 
           "policy"."policy_attachables"."attachable_id"     AS "attachable_id", 
           "policy"."policy_attachables"."policy_type"       AS "policy_type", 
           "policy"."policy_attachables"."contact_info_type" AS "contact_info_type", 
           "policy"."policy_attachables"."policy_id"         AS "objectiontmpjoin0" 
FROM       "auth"."addresses" 
INNER JOIN "policy"."policy_attachables" AS "policy.policy_attachables" 
ON         "auth"."addresses"."id" = "policy"."policy_attachables"."attachable_id" 
WHERE      "policy"."policy_attachables"."policy_id" IN ($1) 
AND        "policy_type" = $2 
AND        "attachable_type" = $3 
AND        "contact_info_type" = $4
- invalid reference to FROM-clause entry FOR TABLE "policy_attachables"
```

We do plan to move away from the schemas, however, since it's dialect-specific and not widely supported/tested. So, I'm not formally requesting a fix, just wanting to let you know about it.

thanks!
