### ISSUE TITLE
1.2.0 breaks modelPaths array

### ISSUE THREAD

**Issue by Klemensas** [Vincit/objection.js#1009]
[This change](https://github.com/Vincit/objection.js/commit/e220e51374a439b8b5dfd82b85f08b49d37ece32#diff-6fd5bd119d64cc5ce13d771f3c392228L43) makes it throw if any folder is missing the model file thus breaking path array use case.

To reproduce use relative path for your models `modelClass` and set your `modelPaths` to an array of different folders.

**Comment by koskimas** [comment]
@Klemensas The master branch contains a fix for this now. Could you test if that fixes your problems?

**Comment by Klemensas** [comment]
Yeah that fixes it, thanks!

**Comment by koskimas** [comment]
Great! I'll release a new version today.
