### ISSUE TITLE
Multiple Picks not working

### ISSUE THREAD

**Issue by bryanbrunt** [Vincit/objection.js#1010]
This query only returns the Game models. The Player model data isn't returned at all:

const retVal = await Game.query()
                    .where('is_completed', false)
                    .orderBy('id')                    
                    .eager('players')
                    .pick(Game, ['id'])
                    .pick(Player, ['username', 'user_id']);

This query returns all fields from the Game model, and the only the Picked (username, user_id) fields from the Player model:

const retVal = await Game.query()
                    .where('is_completed', false)
                    .orderBy('id')                    
                    .eager('players')                    
                    .pick(Player, ['username', 'user_id']);

**Comment by heisian** [comment]
I know the documentation says different, but try this:
```node
const retVal = await Game.query()
  .where('is_completed', false)
  .orderBy('id')
  .eager('players')
  .modifyEager('players', builder => {
    builder.pick(Player, ['username', 'user_id']);
  })
  .pick(Game, ['id'])
```

**Comment by bryanbrunt** [comment]
My models are pretty straightforward. Oh, I singularized the relationship "players" to "player".

const Model = require('objection').Model;
const Player = require('./Player');

class Game extends Model {
    static get tableName() {
        return 'game';
    }

    static get relationMappings() {
        return {
            player: {
                relation: Model.HasManyRelation,
                modelClass: __dirname + '/Player',
                join: {
                    from: 'game.id',
                    to: 'player.game_id'
                }
            }
        }
    }
}

module.exports = Game;

'use strict';

const Model = require('objection').Model;

class Player extends Model {
    static get tableName() {
        return 'player';
    }

    static get relationMappings() {
        return {
            user: {
                relation: Model.BelongsToOneRelation,
                modelClass: __dirname + '/User',
                join: {
                    from: 'player.user_id',
                    to: 'user.id'
                }
            },
            game: {
                relation: Model.BelongsToOneRelation,
                modelClass: __dirname + '/Game',
                join: {
                    from: 'player.game_id',
                    to: 'game.id'
                }
            }
        }
    }
}

module.exports = Player;

**Comment by koskimas** [comment]
You need to also pickup The relation property `players`

**Comment by bryanbrunt** [comment]
How do I pick the relation property players? Isn't that what this does:

.eager('players')
.pick(Game, ['id'])
.pick(Player, ['username', 'user_id']);

I'm following the example from the documentation. But it isn't working.

Person
  .query()
  .eager('pets')
  .pick(Person, ['id', 'firstName'])
  .pick(Animal, ['id', 'name']);
