### ISSUE TITLE
[Question] "Duplicate relation in a relation expression"

### ISSUE THREAD

**Issue by chrismpettyjohn** [Vincit/objection.js#1013]
Raw Warning 
`Duplicate relation "guilds" in a relation expression. You should use "a.[b, c]" instead of "[a.b, a.c]". This will cause an error in objection 2.0`

Can somebody explain what this is ?

**Comment by koskimas** [comment]
I cannot explain it better than that error message. `a` is the duplicate relation in the error message.

**Comment by tclaff** [comment]
I know it is a bit late, but but please check if you have the duplication within you eager() option. We had the same issue for `model.query().select("...").eager(something, a, a.b)`
