### ISSUE TITLE
Error behavior when root model is not found during upsertGraph()

### ISSUE THREAD

**Issue by devinivy** [Vincit/objection.js#1019]
Currently when the root model is not found during a graph upsert, a generic error is thrown.  It seems like it may be appropriate to throw a `NotFoundError` instead.

I realize there are some complexities, i.e. defining what should happen when `insertMissing` is `true`, how it might interact with `throwIfNotFound()`, and how to deal with relations that are not found (versus the root).  My suggestion would be to simply throw a `NotFoundError` any time `upsertGraph()` currently throw a generic error due to a missing record, and that `throwIfNotFound()` shouldn't be used with `upsertGraph()` due to its overlap in meaning with `insertMissing`.  This may also be an opportunity to provide some structured information about which record was not found on the error itself.

**Comment by koskimas** [comment]
Seems reasonable. Let's do that.

**Comment by vladshcherbin** [comment]
Would love to see this feature too, to achieve something similar to this:

```js
Model.query(trx).findOne({ id }).throwIfNotFound().upsertGraph(input)
```
