### ISSUE TITLE
Any plans for a .d.ts file for TypeScript projects?

### ISSUE THREAD

**Issue by dotDeeka** [Vincit/objection.js#102]
First off this is a great project, it wraps knex just enough.

I am using this project in a project written in TypeScript. Is there a definition file or plans to create a definition file for the Objection.js library? Thanks.

**Comment by koskimas** [comment]
We are using typescript in one of our projects at Vincit, and we have written some typings for that project, but we are not any good at it :smile:. If you have, or want to write, the typings I would be happy to accept a pull request.

**Comment by dotDeeka** [comment]
Ha, I am not any good at it either. I've started one here https://github.com/dotDeeka/objection-d-ts that I can reference in my project. If I actually get it right I will certainly submit a PR for it.

**Comment by albertkim** [comment]
Hoping to use this in a Typescript project one day, will keep an eye on this issue! Would go along well with the amazing documentation so far.

**Comment by zam6ak** [comment]
The typings, if and when added should be referenced from project.json
see: http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html


also this may be of interest:
https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Comment by juhoojala** [comment]
Thanks for this great project! 

Any progress on this issue?

**Comment by koskimas** [comment]
Not on my part. @dotDeeka ?

**Comment by dotDeeka** [comment]
No not really @koskimas . I have that repo in my account I've been using, I'm pretty sure its no where near complete. If anyone out there is interested in trying to make it more complete I'd certainly accept a PR, or even give what I have to someone if they're serious about owning it?

**Comment by danieloprado** [comment]
+1

**Comment by 4nxiety** [comment]
Hello,

is there some new news about it?

**Comment by elhigu** [comment]
@4nxiety There hasn't been anyone willing to own that part and keep updating typings when project evolves.

**Comment by 4nxiety** [comment]
oh damn :/

**Comment by mceachen** [comment]
@dotDeeka, @koskimas: my PR that adds typings, #239, is ready for review.

**Comment by mceachen** [comment]
Fixed by #255

**Comment by dotDeeka** [comment]
Awesome @mceachen, thanks for stepping up on this.

**Comment by mceachen** [comment]
#272 is merged to master. @koskimas can you close this issue?

**Comment by dotDeeka** [comment]
Any chance we'll get this as part of 0.7 ?
