### ISSUE TITLE
knexSnakeCaseMappers for `camelCase1`

### ISSUE THREAD

**Issue by dwoowb** [Vincit/objection.js#1025]
Hi,

Just want to say I appreciate your efforts on this library and I have enjoyed using it thus far!

I have a use case for conversion for a variable like `camelCase1` to write to my DB as `camel_case_1`, however, I'm noticing that the [current implementation of `snakeCase`](https://github.com/Vincit/objection.js/blob/bec56d75a1ba3bc3cb2f55d0dcdcc99a7b482edf/lib/utils/identifierMapping.js#L19) converts said variable from `camelCase1` to `camel_case1`.

I tried out the [lodash implementation of snakeCase](https://lodash.com/docs/4.17.10#snakeCase) which gives me the desired result. Another option that would elicit the desired effect for me would be changing [the conditional here](https://github.com/Vincit/objection.js/blob/bec56d75a1ba3bc3cb2f55d0dcdcc99a7b482edf/lib/utils/identifierMapping.js#L41) from:
```
if (char === upperChar && upperChar !== lowerChar) { ... }
```
to:
```
if (char === upperChar) { ... }
```
But of course I am not entirely sure of the use cases you have run into and are trying to support on your end.

I tried playing around with configuring `knexSnakeCaseMappers` but realized that `knexIdentifierMappers` (which is where I would pass in my own choice of camel/snakeCase functions) is not being exported.

Please let me know what you think, I'd be more than happy to discuss and open a PR based on our conversation!

**Comment by heisian** [comment]
@dwoowb seems like a good idea.
The current `knexSnakeCaseMappers` implementation goes like:
```
1.  If the current character is not an underscore,
    and the previous character is not an underscore,
    the character is pushed to the stack.

2.  If the current character is not an underscore,
    and the previous character *is* an underscore,
    the character is uppercased and pushed to the stack.

3.  If the current character *is* an underscore, it is ignored.
```
Adding conditions to handle numbers could work. I would wait to see what @koskimas thinks first, though!

**Comment by koskimas** [comment]
I can add a config parameter for this. We need to use this special function instead of for example the lodash functions so that things like joinEager work correctly.

**Comment by dwoowb** [comment]
@heisian @koskimas thanks for the quick response! That makes sense @koskimas, yeah that would be great.

Just to make sure I'm on the same page as you, two questions.

Would this mean I would be able to configure `knexSnakeCaseMappers` to use the snake/camelCase functions of my choosing like lodash for instance?

Two, if functionality like `joinEager` relies on the current implementation of `snakeCase` would that mean passing in lodash's `_.snakeCase` potentially break the `joinEager` functionality?

**Comment by koskimas** [comment]
@dwoowb You cannot use the lodash version because it behaves in undesired ways with aliases objection uses internally. I can add an option like `underscoreBeforeNumbers: true`. You would be able to use it like this:

```js
knexSnakeCaseMappers({
  underscoreBeforeNumbers: true
})
```

Would that work?

**Comment by dwoowb** [comment]
Gotcha, yes I think that would fit my use case nicely! Thank you :)

**Comment by dwoowb** [comment]
@koskimas not intending to pressure you at all (as it hasn't even been a week yet) but do you have any rough ETA on this? Also, if you'd like to allow me to take a crack at it, it'd be my pleasure :)

**Comment by koskimas** [comment]
@dwoowb sorry for the delay. I'll try to fix this during the nex week.

**Comment by dwoowb** [comment]
Hi @koskimas, do you have any updates on this? Please let me know if I can help in any way 😃

**Comment by koskimas** [comment]
@dwoowb I finally found time to fix it. I'll release 1.2.6 in a couple of hours with this fix.

**Comment by koskimas** [comment]
1.2.6 is now released. Give it a go and let me know if it works as you'd expect.

**Comment by dwoowb** [comment]
@koskimas that works perfectly, thank you!
