### ISSUE TITLE
Convert the where and andWhere to a where object

### ISSUE THREAD

**Issue by alaarihan** [Vincit/objection.js#1029]
Hi,
I really like this ORM but I think it's very useful if you made the where to be an array like
```
where: {
age: {op: '>', value: 40},
age: {op: '<', value: 60},
firstName: 'Jennifer'
}
```

instead of
```
.where('age', '>', 40)
.andWhere('age', '<', 60)
.andWhere('firstName', 'Jennifer')
```

I think that way above is better for building the query.

**Comment by koskimas** [comment]
@alaarihan Objection uses the `knex` API for the lower level query building methods like this. I don't think objection should add it's own API for things that can already be easily done with the knex API.
