### ISSUE TITLE
$beforeDelete only works for instance deletes

### ISSUE THREAD

**Issue by ozum** [Vincit/objection.js#1030]
Hi,

As indicated in documents `Model#$beforeDelete` only works for instance deletes:

> ...only called for instance deletes started with $query() method.

On the other hand `$beforeUpdate` and `$beforeInsert` works with `query()` too.

Is this on purpose? Could you please add `beforeDelete` support for query methods too?

I'm checking user app privilege before deletion, but cannot trigger it with `beforeDelete`.

Kind Regards,

**Comment by koskimas** [comment]
`$beforeDelete` is an instance method and the model instance is only available when deleting an instance using `$query`. With the static `query` we would need to first fetch the elements and that's something that objection will never do. Consider this query:

```js
Person.query().delete().where('age', '<', 100)
```

With a database of one million people, that would delete something like 990000 rows. If we fetch all of them from the database, it would be pretty stupid :smile: 

With insert and update the method is called for the (partial) model instance given as an argument.

**Comment by ozum** [comment]
@koskimas thanks for the fast response. I'm not sure I understand. Could you please clarify why `$beforeUpdate` (with `query()`) is not fetching millions of rows whereas `$beforeDelete` fetches?

I'm asking, because I may doing something wrong putting my authorization code in `$beforeUpdate()` then. I assumed rows are not fetched as per document:

> ... the updated values. The old values are never fetched from the database implicitly. For non-instance queries the opt.old object is undefined

Please take this as a feature request considering my assumption:
If this is possible for update, isn't it possible to implement it for the `$beforeDelete`?

Many thanks,

**Comment by koskimas** [comment]
When you call

```js
Person.query().update({foo: 'bar'})
```

or

```js
Person.query().patch({foo: 'bar'})
```

or

```js
Person.query().insert({foo: 'bar'})
``` 

the hook is called for the `{foo: 'bar'}` object after it has been turned into a model instance. This is not possible for delete.

**Comment by ozum** [comment]
I see. I will appreciate your help, if you could advise then:

I'm developing an objection plugin following best practices suggested in doc.

My plugin checks user privileges and threw if user does not have insert/update/delete privilege according to db operation (fetched from context).

I put this check in `$beforeInsert`, `$beforeUpdate` and `$beforeDelete`. Where to put this logic to catch non-allowed delete operation using `query()`?

**Comment by koskimas** [comment]
You can override the `QueryBuilder` and add a `runBefore` hook in the constructor that uses the `isInsert`, `isDelete`, `isFind` etc. methods to detect the type of the query. You can't access the model instance there unfortunately. If you need to do permission checks based on model properties, that's never going to be 100% possible. The user can always write more and more `raw` queries, subqueries etc. that you can't hook into properly.

**Comment by ozum** [comment]
Thanks for your help @koskimas. That would solve my case.

**Comment by ozum** [comment]
By the way what is `result` parameter is used in `runBefore` function? I couldn't figure it out from doc.

**Comment by koskimas** [comment]
You can pass data from one runBerfore hook to another using it. The initial value is undefined.
