### ISSUE TITLE
QueryBuilder#withRaw was broken by a change in Knex

### ISSUE THREAD

**Issue by jordansexton** [Vincit/objection.js#1035]
After updating to the latest Knex, I discovered that https://github.com/Vincit/objection.js/pull/483 is broken by the removal of the private `withRaw` method in Knex: https://github.com/tgriesser/knex/pull/2298/commits/94d4c8aa6fbce7015cce3c029a19e81b75818e6a

It looks like it might be possible to fix this relatively easy by delegating Objection's `withRaw` to `withWrapped` internally, keeping Objection's API the same. I'll test this out and submit a PR if so.

**Comment by koskimas** [comment]
This should be fixed, but immediately deprecated since the method doesn't exist in knex. Isn't withRaw(...) the same as with(raw(...))?

**Comment by jordansexton** [comment]
Yeah, `with(alias, raw(...))` works the same as it did before. 

However, `with` also allowed calling with [a Raw instance and bindings](https://github.com/tgriesser/knex/commit/7d18837404d5f958ff5ec9f85bb6a10ccc380538#diff-2ee33e306d47d27f6349fbefe16e28e0L82) (confusingly, since Raw instances could/should already have bound params).

`withRaw` allowed calling with [a SQL string and bindings](https://github.com/tgriesser/knex/commit/7d18837404d5f958ff5ec9f85bb6a10ccc380538#diff-2ee33e306d47d27f6349fbefe16e28e0L90) to compose a Raw instance.

Should the fix support this usage? It's easier if it doesn't, since it can just delegate to `withWrapped`, but the TS definition includes it.

https://github.com/Vincit/objection.js/blob/master/typings/objection/index.d.ts#L1130-L1134

```typescript
interface WithRaw<QM extends Model, RM, RV> {
    (alias: string, raw: Raw): QueryBuilder<QM, RM, RV>;
    join: knex.JoinClause;
    (alias: string, sql: string, bindings?: any): QueryBuilder<QM, RM, RV>;
}
```

Also, I'm not very familiar with TypeScript, so I don't know what the `join: knex.JoinClause;` line does.
