### ISSUE TITLE
TypeScript: 'patch' input type does not allow 'Raw' values

### ISSUE THREAD

**Issue by xsc** [Vincit/objection.js#1036]
`patch` takes `Partial<T>` which expects a subset of `T`. This means it does not allow for any `Raw` values in the corresponding objects, unless they are defined within `T`.

Based on the definition of `Partial<T>`

```ts
type Partial<T> = { [P in keyof T]?: T[P] }
```

I suggest the following for `patch` and `update`:

```ts
type Update<T> = { [P in keyof T]?: T[P] | Raw}
```

Does that sound reasonable?

**Comment by koskimas** [comment]
Passing a `raw` to the `patch` or `update` method isn't possible with objection.

**Comment by xsc** [comment]
@koskimas Thanks for your response! Note that the [`patch`](https://vincit.github.io/objection.js/#patch) documentation offers the following example:

```js
const {ref, raw} = require('objection');

await Person
  .query()
  .patch({
    age: Person.query().avg('age'),
    // You can use knex.raw instead of `raw()` if
    // you prefer.
    firstName: raw("'Jenni' || 'fer'"),
    oldLastName: ref('lastName'),
    // This updates a value nested deep inside a
    // json column `detailsJsonColumn`.
    'detailsJsonColumn:address.street': 'Elm street'
  });
```

So, do you mean that it's not possible with TypeScript? Because if so, yes, that's what I'd like to change.

Or are you referring to the hypothetical case of `Person.query().patch(raw(...))` (which is not what I'm concerned about)?

Anyhow, looking at the above example the type for `patch` should probably be even more extensive, allowing subqueries and references in addition to raw values. Not sure how to handle JSON columns, though.

I think this should be reopened.

**Comment by koskimas** [comment]
Whoop, sorry. I misinterpeted the typing. Yes that typing should be fixed.
