### ISSUE TITLE
Find entities by relation ids in objection.js

### ISSUE THREAD

**Issue by khotey** [Vincit/objection.js#1037]
I have products and they related to categories

```
    categories: {
          relation: Model.ManyToManyRelation,
          modelClass: `${__dirname}/../../categories/models/category`,
          join: {
            from: 'products.id',
            through: {
              from: 'categories_products.productId',
              to: 'categories_products.categoryId',
            },
            to: 'categories.id',
          },
        },
```

How can I build query to find products by categories ids, without fetch categories than fetch products ids in relation table, is there a way to pass `whereIn({ catagories: [123, 15] })`, or something like that ?

**Comment by koskimas** [comment]
I don't know if I fully understood what you want, but this should get you `Products` that have one of the given categories:

```js
await Product
  .query()
  .whereExists(Product.relatedQuery('categories').whereIn('id', [123, 15]))
```
