### ISSUE TITLE
Property 'castTo'  does not exist type error

### ISSUE THREAD

**Issue by demisx** [Vincit/objection.js#1039]
I am seeing the following type error when chaining `.castTo()`:

![screen shot 2018-08-13 at 9 20 31 am](https://user-images.githubusercontent.com/4452412/44044351-2fc275f8-9eda-11e8-8467-6ddb1cf91b97.gif)

![screen shot 2018-08-13 at 9 20 22 am](https://user-images.githubusercontent.com/4452412/44044355-3322fd58-9eda-11e8-970e-62eb93ecae81.gif)

**Comment by koskimas** [comment]
It's probably missing. I'll add it at some point. PR's are always welcome too.

**Comment by demisx** [comment]
Sorry, I am new to TypeScript and I am afraid that I don't yet posses enough knowledge to properly add this missing type. However, I can take a stab if you don't mind commenting and correcting it if my changes are less than perfect. Whatever is the most efficient.
