### ISSUE TITLE
Error inserting binary field

### ISSUE THREAD

**Issue by aspyatkin** [Vincit/objection.js#104]
Hello, I've run into a problem while inserting binary fields in table using `objection.js`.

My application uses `MySQL` and the table I'm trying to insert a record that contains `VARBINARY (4)` field. I'm trying to insert `Buffer` field in the table (exactly 4 bytes), but it ends up with an error.

I've created a [sample repository](https://github.com/aspyatkin/objection.js-weird-bug) which contains a small extract from the app I'm building, and error log. From the log it turns out the data is somehow corrupted. That seems weird, because I know this library is based on `Knex`, and the same operation in `Knex` works without errors.

**Comment by koskimas** [comment]
This seems like a clear bug. Thanks for the sample repository! I'll fix this for the 0.5.0 release. I'll probably make an alpha/rc release soon that contains a fix for this. I'll keep you posted.

**Comment by koskimas** [comment]
Fixed in 0.5.0-rc.1. Run `npm install objection@next` to install.
