### ISSUE TITLE
Unsigned Integer Casting As String

### ISSUE THREAD

**Issue by abramjstamper** [Vincit/objection.js#1041]
I'm currently using:
```js
"knex": "^0.15.2",
"objection": "^1.2.2",
"pg": "^7.4.3",
```

I'm having an issue with the type of the variable not matching the type in the database. When I'm iterating through the array, I want to access the percent (unsigned integer in db). However, in the array, it's a string, not an unsigned integer. I'm not sure what this issue is being caused by since my type in the db is unsigned int. Is this expected behavior? I'm not sure if this is an objection issue, knex issue, postgres issue, or my code. Any guidance would be appreciated. Below I have shown an example below, along with the schema.

Here's the code:
```js
const [component] =
            await Promise.all([
              await Component
                .query()
                .where('foreign_id', request.params.foreign_id)
                .orderBy('timestamp'),
              ...]);
for (let i = 0; i < component.length; i++) {
    console.log(component[i].percent);          // string
    console.log(Number.parseInt(component[i].percent));    //integer 
}

```

Here's the schema (knex migration):
```js
    knex.schema.createTable('Component', t => {
      t.increments('id');
      t.string('component_name');
      t.integer('percent').unsigned();
      t.string('foreign_id');
      t.foreign('foreign_id').references('id').inTable('OTHER_TABLE');
      t.timestamp('timestamp');
    }),
```

**Comment by kibertoad** [comment]
99% that this is a PostgreSQL driver thing, check out https://github.com/brianc/node-postgres/issues/811
If you are super sure that your values are never going to overflow js numeric range, you can use custom mapper for the type.

**Comment by koskimas** [comment]
@kibertoad is right.

**Comment by abramjstamper** [comment]
Thanks for the assistance! I will check it out.
