### ISSUE TITLE
How to read current field value during upsert?

### ISSUE THREAD

**Issue by booboothefool** [Vincit/objection.js#1043]
Am trying to do something like:
```
const input = 32

MyModel
  .query()
  .upsertGraph({
    id: 1,
    eggs: this.eggs + input,
  })
```

**Comment by koskimas** [comment]
`eggs: raw('eggs + ?', input)`

**Comment by booboothefool** [comment]
@koskimas Thank you! This works great when updating, but when inserting for the first time, it validation errors on the column eggs. Any advice?

**Comment by booboothefool** [comment]
@koskimas Is it possible to do something like this on a single upsert?

```
eggs: if insert => input, else if update => raw('eggs + ?', input)
```

Maybe I just need:
```
eggs: raw('some complicated check exists query to handle both cases', input)
```

Thoughts?
