### ISSUE TITLE
Error: knex: Required configuration option 'client' is missing.

### ISSUE THREAD

**Issue by ngprnk** [Vincit/objection.js#1044]
my configuration looks like this 

require('dotenv').load();
const pg = require('pg');
module.exports = {
  client: 'pg',
  connection: process.env.DATABASE_URL,
};

Command i ran :  knex migrate:latest --knexfile ./src/models

**Comment by kibertoad** [comment]
https://github.com/Vincit/objection.js/blob/master/examples/express-es6/knexfile.js

check out an example

**Comment by koskimas** [comment]
Seems like a knex related issue to me.
