### ISSUE TITLE
`modifyEager` on multiple level relation

### ISSUE THREAD

**Issue by joaonice** [Vincit/objection.js#1046]
Hi there! 

I'm trying to do something like this:

```js
.modifyEager('children.movies', builder => {
   console.log(builder.modelClass()); 
});
```

The result of the `console.log` it's only the `movies` class. It's possible, in some way, to iterate throw all the levels of the relation (children AND movies)?

**Comment by koskimas** [comment]
Hi,

it's not possible to easily access the other model classes in `modifyEager`. I cannot come up with a good reason to do that though. What are you trying to do?

**Comment by joaonice** [comment]
I'm dealing with translations and I need to translate the children relations (Join the translation tables). With the example above, I'm getting the translated `movies` fields but not the `children`

**Comment by koskimas** [comment]
You can do this:

```js
.modifyEager('children', builder => {
   console.log(builder.modelClass()); 
})
.modifyEager('children.movies', builder => {
   console.log(builder.modelClass()); 
})
```

**Comment by joaonice** [comment]
That could be a solution but all the process is being handled in a dynamic way. `modifyEager` is being called like this:

```js
.modifyEager('[children, children.movies]', builder => {
   console.log(builder.modelClass()); 
})
```

Maybe if I parse the `[children, children.movies]` string and iterate throw all the relations. I'll give it a try!

**Comment by joaonice** [comment]
Yeah, that works! Thanks @koskimas
