### ISSUE TITLE
trying to do a count query with joinEager is not returning any result

### ISSUE THREAD

**Issue by capaj** [Vincit/objection.js#1048]
I've got this query:

![image](https://user-images.githubusercontent.com/1305378/44553882-46ec6880-a72f-11e8-9151-123f98bbef63.png)

when this query is resolved from knex, it is
```
[{count: 3}]
```
But after this query runs objection's `onRawResult` method, it's result is changed to an empty array.

Objection 1.2.2 with Postgre.

**Comment by capaj** [comment]
I was able to put in a small hackfix by doing
```js
    if (builder._operations.find(({ name }) => name === 'count')) {
      return rows
    }
```
inside `onRawResult`.

If I am able to reproduce it in tests I might open a PR fix.

**Comment by koskimas** [comment]
Use joinRelation instead of joinEager

**Comment by koskimas** [comment]
It should be obvious. Why would you eager load and then ignore all the eager loaded relations?
