### ISSUE TITLE
How can I update two tables at same time?

### ISSUE THREAD

**Issue by starlightslo** [Vincit/objection.js#105]
I have two tables (users, user_profiles).
**users:**
- id
- username
- email

**user_profiles:**
- user_id (users.id)
- first_name
- last_name
- language

I use this command to update but get the error:
`UserModel.query().where('users.username', username).where('user_profiles.language', selectedLanguage).update(updateStructure)`

error:
`error: update "users" set "email" = $1, "first_name" = $2, "last_name" = $3 where "users"."username" = $4 - missing FROM-clause entry for table "user_profiles"`

How can I update the email, first_name and last_name using one query?
Is it possible? Thank you.

**Comment by koskimas** [comment]
I'm pretty sure this isn't possible using any of the supported databases (mysql, postgres or sqlite). You need to make two separate updates. objection.js doesn't do magic like this under the hood.

For the `.where('user_profiles.language')` to work in the query you need to make a join. For example:

```js
UserModel
  .query()
  .join('user_profiles', 'user_profiles.user_id', 'users.id')
  .where('users.username', username)
  .where('user_profiles.language', selectedLanguage)
```

**Comment by starlightslo** [comment]
Hi koskimas,

Thank you for your explanation, I know how to join two tables, I just want to know if I can combine two updates, it would improve the performance.
I find the same discussion from stackoverflow: http://stackoverflow.com/questions/2044467/how-to-update-two-tables-in-one-statement-in-sql-server-2005

Thank you again.

**Comment by keivansahebdelfard** [comment]
here is my code :

```
UPDATE t1 
SET t1.CodeSherkat = t2.Code
FROM mains as t1, sherkats as t2
WHERE t1.NameSherkat=t2.[Name]
```
