### ISSUE TITLE
Union doesn't respect alias

### ISSUE THREAD

**Issue by drew-r** [Vincit/objection.js#1050]
I'm finding that for a query with a `relatedQuery` subselect unioned to another, the nested related query does not respect the table alias:
```
Foo.query()
.alias('f')
.select({ 
    sub: Foo.relatedQuery('bar').select('fieldA').union(Foo.relatedQuery('baz').select('fieldB'))
})
```

produces

```
select 
    "f".*, 
    (
        select "fieldA" from "bar" where "bar"."fooId" = "f"."id" 
        union 
        select "fieldB" from "baz" where "baz"."fooId" = "foo"."id"
    ) 
from "foo" as "f"      
```

Giving 
```
[2018-08-29 16:13:16] [42P01] ERROR: invalid reference to FROM-clause entry for table "foo"
[2018-08-29 16:13:16] Hint: Perhaps you meant to reference the table alias "f".
```
on 1.2.5

**Comment by koskimas** [comment]
`relatedQuery` always uses the parent query's alias map. If it always used the root query's map, it would fail in other cases. You can use [aliasFor](http://vincit.github.io/objection.js/#aliasfor) as a workaround.
