### ISSUE TITLE
Relationship: AND WHERE 

### ISSUE THREAD

**Issue by chrismpettyjohn** [Vincit/objection.js#1055]
Is it possible to have an additional WHERE statement on a relationship?  Intended behavior is to only get the comments that has a parent_id of this.id AND parent_type of status

A modifyEager is what I am looking for, however inside of the model itself vs on the query builder
https://vincit.github.io/objection.js/#modifyeager

**Comment by koskimas** [comment]
See the relation mapping docs. You can add a `filter` for the mappings.

**Comment by koskimas** [comment]
http://vincit.github.io/objection.js/#relationmappings
