### ISSUE TITLE
Question: queryBuilder.isRelate()

### ISSUE THREAD

**Issue by ozum** [Vincit/objection.js#1056]
Hi,

I need to get information about relate operation.

Assume there are two db tables (A and B) which is joined through (AB):
A --< AB >-- B

`queryBuilder.isRelate()` gets whether operation is a relate.
`queryBuilder.modelClass()` gets model we are acting on. (A in this example)

How can I get related models? (AB and B in this example)

Kind regards,

**Comment by koskimas** [comment]
If you know the relation you are working on, you can use `queryBuilder.getRelations()[relationName])` and there you'll find the classes, but I'm quessing you don't know the relation name. You could override `$relatedQuery` to store the relation name to context using `mergeContext` and fetch it there?

**Comment by ozum** [comment]
In my particular case, query is not written by me. I don't know relation name.

**If I understand proposed solution correctly**, I cannot be sure that developer who has written query, is using `$relatedQuery`.

Maybe explaining my use case would be better:

I'm trying to develop an authorization plugin for `objection.js`, and plan to limit/allow a query whether user has privilege to access tables in given query. I can easily get main table via `queryBuilder.modelClass().tableName`. I also need to get list of other tables (ie. join, eager, sub select etc.).

**Comment by koskimas** [comment]
You can only call `relate` for $relatedQuery. There is no way isRelate is true for any other query than $rwlatedQuery

**Comment by koskimas** [comment]
What would that mean? Objection allows all kinds of raw queries, subqueries, deeply nested subqueries mixed with raw and nested joins, etc. Its impossible to detect all situations. This kind of API would either be super simple, forcing you to write majority of the code, or it would fail **a lot**.

**Comment by ozum** [comment]
Especially considering `raw` and other possible methods, I'm aware of that it is impossible to cover all situations. Target of my plugin is to support what objection supports.

> ... is it possible to add relation introspection to roadmap for next major version of objection.js 

I mean, I'll be grateful whatever is possible **and feasible for objection team**, if any (i.e. just for eager and/or join or nothing if it is not feasible). I can limit features of plugin, and document which objection methods are supported.

**Comment by koskimas** [comment]
I'm thinking about adding some kind of simple introspection API in 2.0, but that will be very limited and basicllly just open a possibility for people to write plugins like this. Objection probably won't provide much functionality for these things as it would become an endless mess of issues, misunderstandings and feature requests.

**Comment by ozum** [comment]
Even supporting most common ones would be great. Thanks.
