### ISSUE TITLE
[Feature Request] Auto optimize "duplicate relation ... in a relation expression"

### ISSUE THREAD

**Issue by ozum** [Vincit/objection.js#1058]
As explained in #1013, using same relation more than once, raises a warning. Maybe providing duplicate relations produces sub-optimal queries or there is another solid reason.

**Feature Request**

It would be great if objection.js could optimize expression by converting `a.b, a.c` into `a.[b, c]` internally.

**Reasoning**

I usually provide end user option to choose relations limiting with allowEager. For example in a query:

`/endpoint-url?embed=[a.b, a.c]`
or
`/endpoint-url?embed=a.b&embed=a.c`

However it is harder to explain average user to use `a.[b, c]` instead of `a.b, a.c`. Also it is a convenience even for experienced developers.

Thank you,

**Comment by koskimas** [comment]
You can use the mergeEager method.

**Comment by koskimas** [comment]
You van also cook something up using the object representation of eager expressions

**Comment by ozum** [comment]
If I understand correctly, using `mergeEager` for `/endpoint-url?embed=[a.b, a.c]`:

Something like (just written here, may have errors)
```js
const eagers = request.query.embed.replace(/^\\[/).replace(/\\]$/).split(',');
let result = model.query();
eagers.forEach(eager => {
  result = result.mergeEager(eager);
})
```

instead of 

```js
const result = model.query().eager(request.query.embed);
```

**Comment by koskimas** [comment]
Merging, as you requested initially, may be problematic when using filters or recursion: It isn't immediately clear what happens in cases like these:

```js
.eager('[a.^, a.b]')
```

```js
.eager('[a(someFilter), a(someOtherFilter).b]')
```

Then again, it's not clear with `mergeEager` either, but in that case it's at least clear that you are merging expressions to each other.

**Comment by koskimas** [comment]
If you don't mind your query parameters and url's being long and unreadable, you could send JSON.stringified object expressions. I don't know if you have noticed, but objection supports object expressions like this:

```js
.eager({
  a: {
    b: true,
    c: true
  }
})
```

with object's it shouldn't be unclear to any javascript developer.

**Comment by ozum** [comment]
Thanks for detailed answers.
