### ISSUE TITLE
parseJson like option for ManyToManyRelation.join.through

### ISSUE THREAD

**Issue by rosendi** [Vincit/objection.js#1060]
From https://github.com/Vincit/objection.js/issues/779 $parseJson is the correct place to add a field beforeValidation. ManyToManyRelation has only the beforeInsert hook for a join table, but it's invoked after the validation cycle. If I want to add some fields to the join table and pass them through validation, how should I do that? 

Currently I do:

```
through: {
  modelClass: Membership,
  from: `${Membership.tableName}.objectId`,
  to: `${Membership.tableName}.memberId`,

  beforeInsert(model) {
    model.memberType = User.modelName;
    model.objectType = Project.modelName;
  },
},
```
but it "inserts" after validation.

**Comment by koskimas** [comment]
Can't you use the `parseJson` hook of the `Memebership` model?

**Comment by koskimas** [comment]
Oh, you want to do that per relation?

**Comment by koskimas** [comment]
The validation in objection is thought of something that is done only for the values coming from "the outside world". So if your property is always added in some hook, don't add it to jsonSchema. The validation isn't supposed to guard from your programming mistakes, but from invalid user input.

**Comment by koskimas** [comment]
You can use database constraints to guard you from inserting invalid stuff to the db.

**Comment by rosendi** [comment]
> Oh, you want to do that per relation?

Yes, per relation.

> The validation isn't supposed to guard from your programming mistakes, but from invalid user input.

That's true, but on the one hand I set that fields (memberType, objectType) in the relation declaration, like in the example above. But on the other hand I also have a public api method where a user could choose the relation type from the enum. Of course I could move the validation logic to the controller, but may be where should be a way to keep that in the model?
