### ISSUE TITLE
Question: Can we filter upsertGraph?

### ISSUE THREAD

**Issue by ozum** [Vincit/objection.js#1061]
Hi,

I can filter eager queries using `modifyEager`. For example, I can limit user to only query active items. (If user does not add `item` to eager query, modifyEager is ignored, which I think is an excellent feature of objection.js)

```js
const result = model
  .query()
  .allowEager("[items, suggestedItems]")
  .eager(request.query.embed)
  .modifyEager("items", builder => builder.where({ isActive: true }));
```

Is it possible to filter `upsertGraph`? or what could be most convenient way?

For example I want to limit a query to only insert and update active items if user added `items` eagerly. (`where item.isActive = true`)

```js
const result = model.query()
  .allowUpsert("[items]")
  .upsertGraph({ id: request.params.id, ...request.payload }, { relate: true, unrelate: true });
```

Creating another relation in model like `activeItems` could be a solution, but I don't prefer, because it adds another relation name to document, explain etc.

Kind Regards,

**Comment by koskimas** [comment]
Unfortunately there's nothing like that. Can't you simply filter the items array before calling upsertGraph?

**Comment by ozum** [comment]
I mean, I would like to modify, if possible, `insert` and `update` SQL queries generated by `upsertGraph` with some arbitrary `where` conditions.

**Comment by ozum** [comment]
👍 No :) I mean just `update`.

**Comment by ozum** [comment]
In case of `upsertGraph`, adding `where` to `select` and `update` queries.

**Comment by koskimas** [comment]
Similar issue appeared concerning filters for delete's. I could add something like this:

```js
SomeModel.query()
  .upsertGraph(graph, {
    modifyUpdate(builder) {
      builder.where('whatEver', 42)
    },

    modifyDelete(builder) {
      ...
    }
  })
```

**Comment by kibertoad** [comment]
@koskimas That would actually be quite useful!

**Comment by ozum** [comment]
Yes, that would be useful. I don't know about `insertGraph` yet, but if it has similar queries, it could be added to it too, for consistency.

**Comment by koskimas** [comment]
We need to be able to specify modifiers per relation (even deeply nested ones). Specifying global modifiers for all updates/deletes is not very useful in general. Currently other options are specified using lists of relation paths like this:

```js
{
  relate: ['foo.bar', 'foo.bar.baz']
}
```

I think we need to use an object or a list of objects here:

```js
{
  modifyUpdate: {
    ['foo.bar'](builder) {

    },

    ['foo.bar.baz'](builder) {

    }
  }
}
```

A shorthand would be offered for specifying global modifier (like in the original example).

This got me thinking if the format of the upsertGraph options should be completely changed. It bugs me that this would add another way to specify options (the object) and we would need to support that for the other options too for consistency..

Something like this could maybe work as the new option format:

```js
{
  foo: {
    bar: {
      $relate: true,
      $noDelete: true,
      $modify(builder) {
        builder.where('whatEver', true)
      } 
    }
  }
}
```

Global options would still work in the root level. This is another issue though.

**Comment by ozum** [comment]
My vote is for the first one, even both syntaxes seem good and differ only as a matter of subjective taste. So it could be better to get some more opinions.

Second one is more organized and allows static analysis of code. However, first one, in my opinion, allows a human to see what is allowed and what is not (delete, relate etc.) much easier, because it is not expanded like a horizontal pyramid.

For example, I can get what is going on easier with following:

```js
const options = {
  unrelate: ['pets', 'movies.reviews'],
  relate: ['movies'],
  noDelete: ['movies'],
  modifyUpdate: {
    'movies': (builder) => {}
    'movies.reviews': (builder) => {}
  }
};
```

Thank you @koskimas for the effort you put in objection.js

**Comment by koskimas** [comment]
Actually let's not implement this. `upsertGraph` is so full of bugs still that I don't want to complicate it further.
