### ISSUE TITLE
Update data in the junction table in a many-to-many relation with UpsertGraph

### ISSUE THREAD

**Issue by almahdi-chihaoui** [Vincit/objection.js#1062]
Using upsertGraph, we can relate or unrelate an existing model to another model or update data in those two models, but, is there a way to update data in the join table in the case of many-to-many relation?
Thanks.

**Comment by koskimas** [comment]
Yes, look up `extra` properties from the docs.

**Comment by mike-kelly** [comment]
I am having problems with this same scenario.

Projects have Cards, many to many, and there is an order of Cards per Project. I store the order and visibility of Cards as extras in the join table for Projects.

Card model:

```
const { BaseModel } = require('./base');

class Card extends BaseModel {

  static get tableName() {
    return 'cards';
  }

  static get namedFilters() {
    return {
      idOnly: builder => builder.select('cards.id')
    };
  }

  static get relationMappings() {
    const Tag = require('./tag');
    const Project = require('./project');
    const { PluginInstance } = require('./plugin');

    return {
      tags: {
        relation: BaseModel.ManyToManyRelation,
        modelClass: Tag,
        join: {
          from: 'cards.id',
          through: {
            // cards_tags is the join table
            from: 'cards_tags.card_id',
            to: 'cards_tags.tag_id'
          },
          to: 'tags.id'
        }
      },

      plugin_instances: {
        relation: BaseModel.ManyToManyRelation,
        modelClass: PluginInstance,
        join: {
          from: 'cards.id',
          through: {
            from: 'cards_plugin_instances.card_id',
            to: 'cards_plugin_instances.plugin_instance_id'
          },
          to: 'plugin_instances.id'
        }
      },

      projects: {
        relation: BaseModel.ManyToManyRelation,
        modelClass: Project,
        join: {
          from: 'cards.id',
          through: {
            from: 'cards_projects.card_id',
            to: 'cards_projects.project_id',
            extra: ['is_visible', 'order']
          },
          to: 'projects.id'
        }
      }
    };
  };

}

module.exports = Card;
```

This is my query to update a card:
```
/*
 * UPDATE a card with id specified
 */
router.put('/:id', function (req, res) {

  const options = {
    // Enable `relate` functionality for relations.
    relate: ['projects', 'tags', 'plugin_instances'],
    noDelete: ['projects', 'tags', 'plugin_instances']
  };

  Card
    .query()
    .upsertGraph(req.body)
    .then((updatedCard) => {
      console.log('updated card');
      res.send(updatedCard.toJSON());
    })
    .catch((error) => {
      console.log(error);
    }, options);

});
```

I want to update `order` and `is_visible` in `cards_projects` for card with id==1. When `req.body` looks likes this:
```
{
  "id": 1,
  "projects": [
    {
      "id": 1,
      "title": "First project",
      "subtitle": "Project subtitle",
      "tCreated": "2018-09-17T08:28:26.713Z",
      "tModified": "2018-09-17T09:25:36.205Z",
      "tAccessed": "2018-09-17T08:28:26.713Z",
      "isVisible": true,
      "order": 0
    }
  ]
}

```
I get the following error when attempting to update:
```
update "projects" set "title" = $1, "subtitle" = $2, "t_created" = $3, "t_modified" = $4, "t_accessed" = $5, "is_visible" = $6 where "projects"."id" in (select "projects"."id" from "projects" inner join "cards_projects" on "projects"."id" = "cards_projects"."project_id" where "cards_projects"."card_id" in ($7) and "projects"."id" = $8) - column "is_visible" of relation "projects" does not exist
```

**Comment by koskimas** [comment]
@mike-kelly You are using `snakeCaseMappers()` right? `extra`s need to be property names and not column names. So `extra: ['isVisible', 'order']` should work.

**Comment by koskimas** [comment]
I just realised that the documentation talks about `columns` and not properties. And they probably should be property names since everything else in the relationMappings is defined as column names... Well see if the above suggestion works and I'll at least update the docs.

**Comment by koskimas** [comment]
Nope, ignore my two previous messages. They should be defined as columns just like you did.

**Comment by mike-kelly** [comment]
> You are using snakeCaseMappers() right?

No, I am doing this in BaseModel:

```
class BaseModel extends Model {

  $formatDatabaseJson(json) {
    json = super.$formatDatabaseJson(json);

    return _.mapKeys(json, function(value, key) {
      return _.snakeCase(key);
    });
  }

  $parseDatabaseJson(json) {
    json = _.mapKeys(json, function(value, key) {
      return _.camelCase(key);
    });

    return super.$parseDatabaseJson(json);
  }

  $beforeInsert() {
    this.tCreated = new Date().toISOString();
  }

  $beforeUpdate() {
    this.tModified = new Date().toISOString();
  }
}
```

If I use `extra: ['isVisible', 'order']` I get errors when retrieving cards:
`error: column projects_join.isVisible does not exist`

**Comment by koskimas** [comment]
@mike-kelly Could you create a reproduction using the `reproduction-template.js` file in the objection repo root? I have tests for this case and it should work. Your setup probably has something different going on that's causing this.

**Comment by mike-kelly** [comment]
Sure. Is the above equivalent to using `snakeCaseMappers()`? Should I try switching to that approach first?

**Comment by koskimas** [comment]
It's not strictly equivalent, but it should work in most cases (your way could break with some joinEager queries and joinRelation queries).

**Comment by mike-kelly** [comment]
I switched to using `snakeCaseMappers()` and it's working now :)
Thanks for the rapid reply!

**Comment by koskimas** [comment]
@mike-kelly I think I got it: you don't have a model for the join table right? If you do this:

```js
class CardsProjects extends BaseModel {
  static get tableName() {
    return 'cards_projects';
  }
}

class CardsPluginInstances extends BaseModel {
  static get tableName() {
    return 'cards_plugin_instances';
  }
}
```

and then 

```js
      projects: {
        relation: BaseModel.ManyToManyRelation,
        modelClass: Project,
        join: {
          from: 'cards.id',
          through: {
            modelClass: CardsProjects,
            from: 'cards_projects.card_id',
            to: 'cards_projects.project_id',
            extra: ['is_visible', 'order']
          },
          to: 'projects.id'
        }
      }
```

it should work even with your original `snake_case` mapping. Actually you should probably do this even now that you are using `snakeCaseMappers()`.

**Comment by mike-kelly** [comment]
OK, I'll do that. However, as I have set `snakeCaseMappers` in knex rather than objection, I presume I should I be defining the extra as: `extra: ['isVisible', 'order']` 
That is what's working for me at the moment.

**Comment by koskimas** [comment]
@mike-kelly If you use the `knexSnakeCaseMappers` you need to specify **everything** in camel case, not just the extras. So `cards_projects.project_id` becomes `cardsProjects.projectId` etc.
