### ISSUE TITLE
Looking for review of my model's custom json parsing

### ISSUE THREAD

**Issue by mitchellporter** [Vincit/objection.js#1064]
I have multiple areas throughout my app where I'm receiving json from an external service and need to insert a new model instance using that json. Before inserting I need to do a few simple things with this json like check for null values, change some numbers to strings, and rename some values before inserting into the database since the column names are different from the json keys.

Rather than duplicating this code across many different areas I wanted to consolidate it in one place inside the model.

Here is how I have implemented this so far using `$parseJson`:

```
const Model = require('objection').Model;

class Customer extends Model {

  static get tableName() {
    return 'customers';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: ['service_id', 'first_name', 'orders_count', 'total_spent'],
      properties: {
        id: { type: 'integer' },
        service_id: { type: 'string', minLength: 1, maxLength: 255 },
        email: { type: 'string', minLength: 0, maxLength: 255 },
        first_name: { type: 'string', minLength: 1, maxLength: 255 },
        last_name: { type: 'string', minLength: 0, maxLength: 255 },
        orders_count: { type: 'integer' },
        total_spent: { type: 'string', minLength: 1, maxLength: 255 }
      }
    };
  }

  $parseJson(json, opt) {

    // Remember to call the super class's implementation.
    json = super.$parseJson(finalJson);

    // Do your conversion here.
    
    const { id, email, first_name, last_name, orders_count, total_spent } = json;
    
    // These values should always be available
    const finalJson = { service_id: id.toString(), orders_count, total_spent };
    
    // Check for null values
    if (email) finalJson.email = email;
    if (first_name) finalJson.first_name = first_name;
    if (last_name) finalJson.last_name = last_name;

    return json;
  }
}

module.exports = Customer;
```

Is this the correct / best practice way to handle this, or should I be using something else like `$fromJson` or `$formatJson`? You guys have built a lot of functionality and before implementing this across all of my models I want to make sure I'm doing this correctly.

Thanks.

**Comment by koskimas** [comment]
Looks good except that you cannot assume any property yo exist in `json`. The function is used internally and can be called with an object with any property missing.

**Comment by koskimas** [comment]
Oh, sorry. That hook is not called internally. The method seems fine.

**Comment by koskimas** [comment]
And yes, that's the correct place. fromJson is not a hook and formatJson is called when a model is serialized back to json.

**Comment by mitchellporter** [comment]
Thank you @koskimas!
