### ISSUE TITLE
What is best way to write date based complex query in objection. 

### ISSUE THREAD

**Issue by mayankparihar1988** [Vincit/objection.js#1066]
SELECT Max("currNumber")
              FROM "test"."Mytable"
              WHERE date_part('year',"createDate") = date_part('year',current_date);

I am looking following Postgresql query to convert in objection.

**Comment by kibertoad** [comment]
Objection doesn't provide any additional tools over what Knex.js already has for date manipulation, and even Knex is unlikely to help you with something that specific. I suspect that .whereRaw is your best bet here.

**Comment by mayankparihar1988** [comment]
Is there any way to execute raw sql query through knex.

**Comment by koskimas** [comment]
A simple search through the docs should answer that question. But here you go

```js
const  { raw } = require('objection')

...

await MyTable
  .query()
  .where(raw(`date_part('year', "createDate") = date_part('year', ?)`, current_date))
```

**Comment by kibertoad** [comment]
@koskimas Any meaningful difference between .where(raw()) and .whereRaw()?

**Comment by mayankparihar1988** [comment]
Thanks a lot @koskimas I am very new to programming :) . Thanks for help.
