### ISSUE TITLE
Question about reliability of accessing parent property inside $parseJson when using insertGraph

### ISSUE THREAD

**Issue by mitchellporter** [Vincit/objection.js#1070]
I have two models `Orders` and `Line items`. Each order can have many line items. I've setup the relation mappings and calling `insertGraph` on the `Order` model is working perfectly. This data is coming from an external service, so in the case of `Line Items`, I'd like to have the table use both our own internal id's and the external service's id's when referencing the parent `Order`. I noticed that when doing an `insertGraph` on `Order`, in the Line Item model's `$parseJson`, the `opt` param contains the parent order's external id that I'd like to store on the line item.

It's available inside the `opt` param's `cache` key. I'm assuming there isn't a better way to do this at the model's `relationMappings` level? If not, I just want to make sure I can rely on that data to always be in the `cache` key of the `opt` param inside line item's `$parseJson`?

As always thanks for the help.

**Comment by koskimas** [comment]
The cache is a private implementation detail an can be renamed or removed at any given time. You shouldn't use it. Only documented things should be used.

Unfortunately there is no other way to do this out of the box either.

**Comment by mitchellporter** [comment]
As always thanks for the fast reply and info @koskimas cheers!
