### ISSUE TITLE
deleteById(id[]) does not work in Postgres

### ISSUE THREAD

**Issue by escobar5** [Vincit/objection.js#1071]
When using `Model.query().deleteById([1,2,3])` in a postgres database, I get the following error:

> Error: both cols and values must have same dimensions
>       at WhereCompositeOperation.build (/Users/escobar5/Projects/intrena/intrena-admin/server/node_modules/objection/lib/queryBuilder/operations/WhereCompositeOperation.js:27:13)

Objection v1.2.6

**Comment by koskimas** [comment]
deleteById takes one id

**Comment by kibertoad** [comment]
@koskimas Then we should fix documentation, because it claims arrays are supported as well: http://vincit.github.io/objection.js/#deletebyid

**Comment by koskimas** [comment]
The documentation clearly states that arrays are supported as *composite keys*

**Comment by escobar5** [comment]
@koskimas My fault, didn't read composite keys. Thanks.
