### ISSUE TITLE
Question: How can I delete from the middle table of a Many-to-Many relationship

### ISSUE THREAD

**Issue by escobar5** [Vincit/objection.js#1072]
Hi, I have this case:

> Books (id, name)
> UserBooks (book.id, user.id)
> User (id, name)
> 

I would like to delete a book from a user, I have defined a model for Book, and a model for User, each with a ManyToMany relationship though UserBooks, is there a way I can delete the UserBook from the User model without querying the user first?

I'm aware of `unrelate`, but I have to query the User first, then use $relatedQuery to delete the UserBooks.

Thanks

**Comment by koskimas** [comment]
You can create a model for the `UserBooks` table and simply delete rows from that.

**Comment by koskimas** [comment]
For example:

```js
UserBooks.query().delete().where('userId', 1)
```

or 

```js
UserBooks.query().delete().where('userId', 636).andWhere('bookId', 123)
```

**Comment by devinivy** [comment]
If you're set on not utilizing the junction model, there is a way to do this with `fromJson()` and `$relatedQuery()`.

```js
const article = Article.fromJson({ id }, { skipValidation: true });

await article.$relatedQuery('favoritedBy', txn).unrelate().where({ id: currentUserId });
```
(from [here](https://github.com/devinivy/hapipal-realworld-example-app/blob/master/lib/services/article.js#L150-L152))
