### ISSUE TITLE
Model#raw does not handle RawBuilders and ReferenceBuilders

### ISSUE THREAD

**Issue by olavim** [Vincit/objection.js#1077]
`Model.raw` works differently from the `raw` helper function. With `raw` I can do the following:

```
const query = Movie.query().debug()
  .where(raw('?? = ?', [ref('id'), 1])) // Find movies with id = 1
  .then(() => {})

/* debug output:
{ 
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: 'f44e58c4-76af-43d2-8227-f504999beac9',
  sql: 'select "movies".* from "movies" where "id" = ?' 
}
*/
```

SQL is fine.

With `Movie.raw`, however, I get gibberish:

```
Movie.query().debug()
  .where(Movie.raw('?? = ?', [ref('id'), 1]))
  .then(() => {})

/* debug output:
{ 
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: 'eb69c0b7-b0e8-48b9-818d-3dd600276df2',
  sql: 'select "movies".* from "movies" where "id" as "_expr", "id" as "columnName",  as "access" as "_reference", "id" as "_column",  as "_table",  as "_cast", "false" as "_toJson",  as "_as" = ?' 
}
*/
```

Having identical behaviour is important when developing plugins/mixins. I don't want to have an additional dependency on objection, which is why I need to use `Model.raw` instead of the helper function.

I have worked around this in my code by calling `.toKnexRaw` (when it exists) on values passed to `Model.raw`:

```
const colRef = ref('id').toKnexRaw(Movie.knex());
Movie.query().debug()
  .where(Movie.raw('?? = ?', [colRef, 1]))
  .then(() => {})

/* debug output:
{ 
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '4e60177e-645b-4dc5-9e37-b3f27b3f852c',
  sql: 'select "movies".* from "movies" where "id" = ?' 
}
*/
```

**Comment by olavim** [comment]
@koskimas well, my situation is perhaps a bit special. We use a package that wraps together PostgreSQL-related utilities, such as a connection helper that sets up a knex client and injects it into the objection base model (`Model.knex(knex)`). Said package also exports objection.

Now, as our projects grow, we eventually depend on packages that have their own dependencies on objection. Let's call our wrapper package `lib-postgres`. Now an example folder structure in one of our projects could be something like this:

```
|-- index.js
|-- package.json
\-- node_modules/
    |-- lib-postgres/
    |   \-- node_modules/
    |       \-- objection@1.2.6
    |-- my-objection-plugin@1.0.0
    |-- needs-objection@1.0.0
    \-- objection@0.9.4
```

Now, as you can see, here I have two different versions of objection in my `node_modules`. One is required by our `lib-postgres`, and the other is required by some `needs-objection` package.

Also, in this case, here I have an objection plugin `my-objection-plugin`, which has a peer dependency on objection >=0.9.

In my project I would then have something like this:

```
const {objection, setupConnection} = require('lib-postgres');
const mixin = require('my-objection-plugin');
const {Model} = objection;

class Person extends mixin(Model) {
  static get tableName() {
    return 'people';
  }
}

// Sets up a knex client and injects knex to Model
setupConnection({host: 'localhost', user: 'test'});

Person.query()
  .crazyWhackFunctionFromMixin(`let's go`)
  .then(() => {});
```

Now this plugin, `my-objection-plugin`, does something that requires it to use objection's `raw` helper:

```
const {raw} = require('objection');
```

But wait, here we have a problem. The plugin imported the helper from objection which is a peer dependency, but from the wrong version. My project uses objection v1.x, while my plugin just imported the `raw` helper from objection v0.9.4, since the older version is in my project's `node_modules` root.

And since the implementation of `raw` is different in these two versions, I probably get problems. In this case, I get the following error:

```
TypeError: knex.raw is not a function
```

**Comment by koskimas** [comment]
Yeah, that setup is a bit special. You should try to avoid having multiple versions of objection in the same project. They may not work together in all situations.

Model.raw now uses objection.raw in the master. I'll release 1.3.0 in an hour or so.
