### ISSUE TITLE
querybuilder result as json instead on ModelClass

### ISSUE THREAD

**Issue by krishnans** [Vincit/objection.js#1078]
Is it possible to configure QueryBuilder to return plain JSON from db instead of ModelClass instance ?

**Comment by koskimas** [comment]
No, that's not possible. Why do you want to do that?

**Comment by krishnans** [comment]
I just wanted to  return plain JSON to client.  I was wondering about the performance implication in creating model objects from JSON returned by db and then converting it back to JSON before returning it to client

**Comment by koskimas** [comment]
The performance drop is very minimal. Something like a couple of microseconds per conversion.
