### ISSUE TITLE
Add returning trick to relations in insertGraph / upsertGraph

### ISSUE THREAD

**Issue by vladshcherbin** [Vincit/objection.js#1079]
It would be great to have a way to return relation data in this methods, similar to how `returning *` trick works. Currently it's applied only to root query, relation queries return just an `id`.

This is useful when you want to return all model data without using another select queries.

**Comment by koskimas** [comment]
As I mentioned in gitter, I don't think this should be added to objection. `returning` only works on positgres (and oracle maybe?) and implementing this yourself is just a couple of lines.

```js
function deepReturningAll(builder) {
  builder.mergeContext({
    onBuild(builder => {
      if (builder.isInsert()) {
        builder.returning('*');
      }
    })
  })
}

...

LeatherType.query(trx).insertGraph(input).modify(deepReturningAll)
```

**Comment by kibertoad** [comment]
Could it be added to recipes then?

**Comment by koskimas** [comment]
@kibertoad Feel free to add it there

**Comment by vladshcherbin** [comment]
@koskimas returning trick is mentioned in many places in the docs and is very useful, I'm using it everywhere and love it. 

If adding it to graphs is that easy, why not add it as a method so users don't need to copy-paste it from project to project?

**Comment by koskimas** [comment]
I see this becoming another `snakeCase = true` conversation with you @vladshcherbin. Not going that road this time.
