### ISSUE TITLE
Self-joins

### ISSUE THREAD

**Issue by alphanso** [Vincit/objection.js#108]
Hi,

Does this framework support self-joins? If yes, how can I go about doing this?

Thanks for your work

**Comment by koskimas** [comment]
You should be able to do something like this:

```js
Person
    .query()
    .select('*')
    .from(Person.raw('"Person" as a, "Person" as b'))
    .whereRef('a.firstName', '=', 'b.lastName')
    .debug()
```

afaik, knex doesn't have a prettier way to do this and hence neither does objection. Let me know if this works.

**Comment by alphanso** [comment]
Thanks. This works really well. Closing the issue.

Also, you are doing a great job with this ORM. :)
