### ISSUE TITLE
Modified upsertGraph with deepReturningAll does not have all fields after relation update

### ISSUE THREAD

**Issue by vladshcherbin** [Vincit/objection.js#1080]
When using `upsertGraph` with `deepReturningAll` trick from https://github.com/Vincit/objection.js/issues/1079#issuecomment-422766504, not all fields are present if related item was updated.

Example

LeatherType has many LeatherTypeColors

Models

```js
class LeatherType extends BaseModel {
  static tableName = 'leather_types'

  static relationMappings = {
    colors: {
      relation: BaseModel.HasManyRelation,
      modelClass: LeatherTypeColor,
      join: {
        from: 'leather_types.id',
        to: 'leather_type_colors.leather_type_id'
      }
    }
  }
}

class LeatherTypeColor extends BaseModel {
  static tableName = 'leather_type_colors'
}

class BaseModel extends Model {
  static columnNameMappers = snakeCaseMappers()

  static useLimitInFirst = true

  async $beforeInsert(queryContext) {
    await super.$beforeInsert(queryContext)

    const date = new Date().toISOString()

    this.created_at = date
    this.updated_at = date
  }

  async $beforeUpdate(opt, queryContext) {
    await super.$beforeUpdate(opt, queryContext)

    this.updated_at = new Date().toISOString()
  }
}

export default DbErrors(BaseModel)
```

`deepReturningAll` function

```js
function deepReturningAll(builder) {
  builder.mergeContext({
    onBuild: (queryBuilder) => {
      if (queryBuilder.isInsert() || queryBuilder.isUpdate()) {
        queryBuilder.returning('*')
      }
    }
  })
}
```

---

1) Basic `insertGraph`

```js
const leatherType = await LeatherType.query()
  .insertGraph({
    title: 'sample title',
    slug: 'sample slug'
  })
```

Result

![screen shot 2018-09-19 at 20 22 26](https://user-images.githubusercontent.com/6711845/45770996-9baad280-bc4c-11e8-9abb-ac65a67c6073.png)

**Works**

---

2) Modified `insertGraph` with `deepReturningAll`

```js
const leatherType = await LeatherType.query()
  .insertGraph({
    title: 'sample title 1',
    slug: 'sample slug 1'
  })
  .modify(deepReturningAll)
```

Result

![screen shot 2018-09-19 at 20 25 35](https://user-images.githubusercontent.com/6711845/45771073-cd239e00-bc4c-11e8-9899-79b8bbb84a86.png)

**Works**

---

3) Modified `insertGraph` with `deepReturningAll` and inserted related color

```js
const leatherType = await LeatherType.query()
  .insertGraph({
    title: 'sample title 2',
    slug: 'sample slug 2',
    colors: [
      {
        title: 'red',
        slug: 'red'
      }
    ]
  })
  .modify(deepReturningAll)
```

Result

![screen shot 2018-09-19 at 20 26 49](https://user-images.githubusercontent.com/6711845/45771218-36a3ac80-bc4d-11e8-9dc8-9a2be4e1ac11.png)

**Works**

---

4) Modified `upsertGraph` with `deepReturningAll`

Updating the last example (adding one more color and updating another one)

```js
const leatherType = await LeatherType.query()
  .upsertGraph({
    id: 81,
    title: 'sample title 2-1',
    slug: 'sample slug 2-1',
    colors: [
      {
        title: 'yellow',
        slug: 'yellow'
      },
      {
        id: 67,
        title: 'blue',
        slug: 'blue'
      }
    ]
  })
  .modify(deepReturningAll)
```

Result

![screen shot 2018-09-19 at 20 30 52](https://user-images.githubusercontent.com/6711845/45771265-563ad500-bc4d-11e8-808e-938033779d23.png)

**Half works**, inserted color is fully returned back while updated one is not.

Running last sql query gives all info:

![screen shot 2018-09-19 at 20 31 20](https://user-images.githubusercontent.com/6711845/45771286-62bf2d80-bc4d-11e8-8c8c-9b8ff3e8e267.png)

Any idea why this is happening?

objection - 1.2.6
node - 10.8.0

**Comment by koskimas** [comment]
Updates are not inserts, so you need to check isUpdate too.

**Comment by koskimas** [comment]
Oh, sorry you did that. I'll look into this at some point.

**Comment by vladshcherbin** [comment]
@koskimas thank you 😉
