### ISSUE TITLE
join multiple table in relationship mapping

### ISSUE THREAD

**Issue by dncahyo** [Vincit/objection.js#1081]
I might be missing something in API, but is there a way to join multiple table in relationship mapping? 

I have two table that connected by two join tables, is there a way I can join that so I can see the result in eager query ex Person.query().eager('pets') ?

**Comment by koskimas** [comment]
There is no way to create a relation through two join tables if that's what you mean?

**Comment by z1haze** [comment]
any chance on getting this functionality? I think a valid use case is below:

a user has a many to many relationship with the roles through the roles_users table
a role has a many to many relationship with the roles_permissions table

a relation is needed to get a user's permissions, but we need to go through 2 tables to get them. Any suggestions?

**Comment by z1haze** [comment]
Also if you just load the the relationship of the eager relationship, the system does not know how to parse the model.
```js
const user = await User.query().findById('350695800453726209').withGraphFetched('roles.[permissions]');
console.log(user.roles);

//
[
  Role {
    discord_role_id: '605297409504837634',
    role_name: 'FaT-Programming',
    color: '2ECC71',
    created_at: 2020-10-28T23:16:27.208Z,
    updated_at: 2020-10-28T23:16:27.208Z,
    permissions: [ [Permission] ]
  }
]
```
