### ISSUE TITLE
one of the identifier columns [id] is null or undefined

### ISSUE THREAD

**Issue by itzikbenh** [Vincit/objection.js#1082]
Hey, not sure what's wrong here. I get this error when I call the `isEmailUnique()` method.
I have this model:
```js
class User extends Model {
    static get tableName() {
        return 'users';
    }

    static get idColumn() {
        return 'id';
    }

    async isEmailUnique(email) {
        return await this.$query()
            .where('email', email)
            .count('id');
    }
}
```
In another file I require and run:
```js
const user = new User();
const count = await User.isEmailUnique('email@gmail.com');
```

**Comment by itzikbenh** [comment]
If I have to guess, it wants an ID of an actual user probably. I guess I'll have to just rely on plain query builder here.

**Comment by koskimas** [comment]
You are correct.

**Comment by koskimas** [comment]
The `$query()` is always a query for the instance for which you call the method. So it always adds a `whereComposite(ModelClass.idcolumn, this.$id())` to the query. The error message should be improved though. I'll add a separate issue for that.

**Comment by koskimas** [comment]
You can make the function static, there is no need for it to be an instance method.

```js
    static async isEmailUnique(email) {
        return await this.query()
            .where('email', email)
            .count('id');
    }
```

**Comment by itzikbenh** [comment]
Thank you very much :)

**Comment by zerubeus** [comment]
I have the same issue how do you solve this ?

**Comment by zerubeus** [comment]
> You can make the function static, there is no need for it to be an instance method.
> 
> ```js
>     static async isEmailUnique(email) {
>         return await this.query()
>             .where('email', email)
>             .count('id');
>     }
> ```

You can't use this in a static method, I'm a bit confused...

**Comment by itzikbenh** [comment]
I did like he said, works fine. You can use `this` in a static method - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static

Here's the static method - https://github.com/itzikbenh/Express-Vue-Auth/blob/master/models/User.js#L53

And here I also catch the error in case of a race condition - https://github.com/itzikbenh/Express-Vue-Auth/blob/master/controllers/user.js#L52

**Comment by zerubeus** [comment]
Thank you, this was helpful

**Comment by jkalandarov** [comment]
Hi,

I've run into the same issue and can't resolve it. Please, look at my detailed question posted and StackOverflow:
https://stackoverflow.com/questions/72607415/one-of-the-identifier-columns-id-is-null-or-undefined-in-objection-js

Thanks in advance!
