### ISSUE TITLE
Question: Constants / variables in joins

### ISSUE THREAD

**Issue by jmich** [Vincit/objection.js#1086]
Hi, I have a relation table between to other tables and I want to be able to join through that table, but in the same time filter on the relation table.

E.g. the good old movie example:
I want to query the movies of a person, but only the ones he/she is in progress of viewing.
That status is on the relation table, so I want to be able to filter on that like this

`class Person extends Model {
  static tableName = 'persons';

  moviesInProgress: {
		  relation: Model.ManyToManyRelation,
		  modelClass: Movie,
		  join: {
			from: ['persons.id', '{"InProgress"}'],  // just added pseudo code which breaks
			through: {
			  from: ['persons_movies.actorId', 'persons_movies.viewingStatus'],
			  to: 'persons_movies.movieId'
			},
			to: 'movies.id'
		  }
		}
}
`

If I use "persons.id" twice instead, the query comes out fine, just with the wrong bindings of course.

So the question is if you can guide me to a way to solve this?

Thanks :-)
Jesper

**Comment by koskimas** [comment]
You can add
```js
modify: builder => builder.where('viewingStatus', 'inProgress')
```

to the relation mapping.

**Comment by allochi** [comment]
Hi, I tried this, and it's not working for me, the field is in joining table `persons_movies`? I have different models completely, but I will set an example using the same model here.

Say I have `persons --> persons_movies(user_id, movie_id, rating) -->movies`.

I tried
```javascript
static get relationMappings() {
    return {
      ratedMovies: {
        relation: Model.ManyToManyRelation,
        modelClass: Movie,
        join: {
          from: "person.id",
          through: {
            from: "persons_movies.article_id",
            to: "persons_movies.category_id"
          },
          modify: builder => builder.where("persons_movies.rating", ">", 3), // outside through
          to: "movies.id"
        }
      }
    };
  }
```
and tried
```javascript
static get relationMappings() {
    return {
      ratedMovies: {
        relation: Model.ManyToManyRelation,
        modelClass: Movie,
        join: {
          from: "person.id",
          through: {
            from: "persons_movies.article_id",
            to: "persons_movies.category_id",
          modify: builder => builder.where("persons_movies.rating", ">", 3) // inside through ( not according to docs)
          },
          to: "movies.id"
        }
      }
    };
  }
```

I'm evaluating `Objection.js` to replace my current ORM, and so far it's GREAT, but I have many many-to-many relationships with extra fields in join tables, and I need to know if I can handle it in `Objection.js`

Help is appreciated, thanks in advance!

**Comment by allochi** [comment]
Ok, I found out that I need to have `modify` before `join`, otherwise it won't work, so this will work

```javascript
ratedMovies: {
  relation: Model.ManyToManyRelation,
  modelClass: Movie,
  modify: builder => builder.where("persons_movies.rating", ">", 3), // <- this must come before `join`
  join: {
    from: "person.id",
    through: {
      from: "persons_movies.article_id",
      to: "persons_movies.category_id",
    },
    to: "movies.id"
  }
}
```

So far my experience with `Objection.js` is positive, thanks a lot.
