### ISSUE TITLE
LoadRelated / Eager produce unnecessary sql query when foreign key is absent

### ISSUE THREAD

**Issue by vladshcherbin** [Vincit/objection.js#1088]
When using `loadRelated` and when there is no foreign key to related table, there is an unnecessary weird sql query.

Here is the example:

Category has many Products (HasManyRelation / BelongsToOneRelation)

```js
class Category extends BaseModel {
  static tableName = 'categories'
}

class Product extends BaseModel {
  static tableName = 'products'

  static relationMappings = {
    category: {
      relation: BaseModel.BelongsToOneRelation,
      modelClass: Category,
      join: {
        from: 'products.category_id',
        to: 'categories.id'
      }
    }
  }
}
```

Queries

```js
const product = await Product.loadRelated({ categoryId: 1, title: 'Milk' }, 'category')
```

Here product has category with `id = 1`, which exists in `categories` table and it's fetched correctly. Here is the result:

![screen shot 2018-09-23 at 06 29 57](https://user-images.githubusercontent.com/6711845/45923877-63c8b700-befa-11e8-96b9-b1585146f028.png)

---

```js
const product = await Product.loadRelated({ categoryId: 10, title: 'Milk' }, 'category')
```

Here product has category with `id = 10`, which does not exist in `categories` table and it's fetched correctly. Here is the result:

![screen shot 2018-09-23 at 06 30 29](https://user-images.githubusercontent.com/6711845/45923884-95da1900-befa-11e8-8308-97ef7fab8436.png)

---

```js
const product = await Product.loadRelated({ title: 'Milk' }, 'category')
```

Here product does not have foreign key for category, but it still tries to fetch it from database table with a weird query. Here is the result:

![screen shot 2018-09-23 at 06 30 55](https://user-images.githubusercontent.com/6711845/45923896-c752e480-befa-11e8-985f-37036bb7ddda.png)

---

I expect it to check data for foreign key before fetching. Is this a bug or is it supposed to work this way? 

objection - 1.2.6
pg - 7.4.3
node - 10.8.0

**Comment by vladshcherbin** [comment]
Same thing happens with `eager` method.

Here is a fetched product with `categoryId = null` and second query to `categories` table is produced.

```js
const product = await Product.query().findOne({ id: 28 }).eager('category').debug()
```

Here is result with `debug`:

![screen shot 2018-09-23 at 06 51 47](https://user-images.githubusercontent.com/6711845/45924016-b0fa5800-befd-11e8-9ac2-9b292a6ea23b.png)

**Comment by koskimas** [comment]
Seems like a bug. Thanks for bringing this up.

knex adds the `where 1 = 0` statement when `whereIn` is given an empty array. Objection's shouldn't run the query at all in that case.

**Comment by koskimas** [comment]
Does this happen if `categoryId` is actually `null`? In your examples, it is `undefined`.

**Comment by vladshcherbin** [comment]
@koskimas yep, in the first message (with loadRelated) it's undefined while in the second one (with eager) it's returned from database and is null, you can see it in the screenshot.

Thank you for a quick fix 😉
