### ISSUE TITLE
Few questions about Objection usage

### ISSUE THREAD

**Issue by mxs42** [Vincit/objection.js#1090]
I'm currently considering switching to Objection from TypeORM and I got a few questions because things somewhat different there.
**First:** can I use ORM-like update? For example,
```
    const like = await LikeModel.query().findById(131);
    if (like) {
        like.power = 2;
        await LikeModel.query().update(like);
    }
```
I expect it to execute UPDATE only for record that is specified in `like` object. I understand that it's not designed to work this way so I guess I should either add `where` or use `patchAndFetchById`. Is it right?
If so, is there a way to ignore specific fields (`id` in my case) when updating? I would like to go further and ignore fields that were not actually updated but I guess it will require writing more complex wrapper.

**Second:** how can I ignore fields that don't exist in database? 
I use $afterGet hook to perform some computing after fetching data from database and set results to object fields but these fields don't exist in database. I know about `pickJsonSchemaProperties` but it's too verbose for me and I don't need any data validation. 
I currently implemented ignoring fields starting with `_` using $formatDatabaseJson, is it correct?

**Third:** Objection (and underlying Knex) doesn't work with JSON fields, right?
I had to also implement serialization in $formatDatabaseJson.
```
    $formatDatabaseJson(json: object) {
        json = super.$formatDatabaseJson(json);

        for (const key in json) {
            if (json.hasOwnProperty(key)) {
                if (key[0] == '_') {
                    delete json[key];
                }
                else {
                    const val = json[key];

                    if(_.isArray(val) || _.isPlainObject(val)) {
                        json[key] = JSON.stringify(val);
                    }
                }
            }
        }

        return json;
    }
```

**One more question:** to get count of rows (scalar value) it seems like I have to write such a query:
`await LikeModel.query().count("* as c").pluck("c").where("id", "<", 200).first()`
There is no shorthand? 

Sorry if I ask something that exist in docs already, I read documentation and search for related issues there and had no direct answers.
I mean, switching ORM will require rewriting big amount of code and I try to get familiar with Objection first to make a decision.

**Comment by kibertoad** [comment]
>  is there a way to ignore specific fields (id in my case) when updating?

Id is used by Objection to figure out which entity you are actually updating, you don't need to exclude it.

> Objection (and underlying Knex) doesn't work with JSON fields, right?

No, it supports JSON data type just fine on DBs that support it (MySQL, PostgreSQL). Simple `Model.query().insert(modelInstance)` should work fine for entities that include object data (example JsonSchema for such field would be `payload: { type: ['object', 'null'] },`)

**Comment by kibertoad** [comment]
@mxs42 Btw, I'm curious, what made you switch from TypeORM? Is it still buggy? Or is it about performance issues?

**Comment by kibertoad** [comment]
> it doesn't work otherwise

Can you share error that you are getting? Also which DB and what column type are you using?

**Comment by mxs42** [comment]
> 
> 
> > it doesn't work otherwise
> 
> Can you share error that you are getting? Also which DB and what column type are you using?

```
export class TestModel extends BaseModel {
    static tableName = "test";

    array: string[] = [];
    data: any = {};

    // static jsonSchema = {
    //     type: "object",
    //     required: ["array", "data"],
    //     properties: {
    //         array: {type: "object"},
    //         data: {type: "object"},
    //     }
    // };
}
```
```
    const test = new TestModel();
    await TestModel.query().insert(test);
    // (node:20592) UnhandledPromiseRejectionWarning: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', '2018-09-25 14:12:53.317', )' at line 1
```
```
console.dir(TestModel.query().insert(test).toSql());
//'insert into `test` (`array`, `data`) values (, {})'
```

**Comment by kibertoad** [comment]
@mxs42 Judging by what you have pasted, JSON is not a problem, array is.

**Comment by koskimas** [comment]
> can I use ORM-like update?

Yes, but in a query-builder-like way :smile: 

```js
    const like = await LikeModel.query().findById(131);
    if (like) {
        like.power = 2;
        await like.$query().patch()
    }
```

> how can I ignore fields that don't exist in database?

For example by implementing the `$formatDatabaseJson` method

```js
class SomeModel extends Model {
  $formatDatabaseJson(json) {
    delete json.someField
    delete json.anotherField
    return super.$formatDatabaseJson(json)
  }
}
```

If that's too verbose, you can create a shared base class that removes the fields based on some static class property (for example).

> Objection (and underlying Knex) doesn't work with JSON fields, right?

Objection does. You can implement the `static jsonAttribues = ['objectAttr', 'arrayAttr', 'whatever']` getter if you don't want to use `jsonSchema`.

>  to get count of rows (scalar value)

This should work

```js
await LikeModel.query().where("id", "<", 200).resultSize()
```

**Comment by mxs42** [comment]
> Yes, but in a query-builder-like way 😄

It works but I believe typings are wrong for this case.
`patch(modelOrObject: PartialUpdate<QM>): QueryBuilderYieldingCount<QM, RM>;`
modelOrObject isn't optional there, seems like a bug.

**Comment by koskimas** [comment]
Oh, that's true. It should be optional. Could you create an issue for that bug as a reminder. I'll fix it soon.
