### ISSUE TITLE
Typings: make modelOrObject optional for QueryBuilder

### ISSUE THREAD

**Issue by mxs42** [Vincit/objection.js#1092]
Currently typings don't allow usage of `instance.$query().update()` and other methods due to non-optional parameter 
`update(modelOrObject: PartialUpdate<QM>): QueryBuilderYieldingCount<QM, RM>;`

It should be marked as optional.

**Comment by stefanvanherwijnen** [comment]
@koskimas 
Any news on this issue? Currently the update() method fails in TypeScript.

**Comment by koskimas** [comment]
Nope. Feel free to create a PR.

**Comment by koskimas** [comment]
Fixed in v2.0 branch.
