### ISSUE TITLE
updateAndFetchById returns incorrect values

### ISSUE THREAD

**Issue by sarneeh** [Vincit/objection.js#1093]
Consider this schema:

```js
  await knex.schema
    .createTable('users', table => {
      table
        .uuid('id')
        .primary()
      table.string('email');
      table.string('password');
    })
    .createTable('roles', table => {
      table
        .uuid('id')
        .primary()
      table.string('name');
    })
    .createTable('users_roles', table => {
      table
        .uuid('id')
        .primary()
      table
        .uuid('userId')
        .references('id')
        .inTable('users')
        .onDelete('CASCADE');
      table
        .uuid('roleId')
        .references('id')
        .inTable('roles')
        .onDelete('CASCADE');
    });
```

Now, let's say this is the status of the database:

**users**
```js
{ id: 1, name: 'John' }
```

**roles**
```js
{ id: 1, name: 'user' }
```

**users_roles**
```js
{ id: 1, user_id: 1, role_id: 1 }
```

Now, when I do:

```js
// Let's assume that I'm putting the `roles` field here by accident, not by purpose
User.query().updateAndFetchById(1, {
    name: 'John',
    roles: ['admin']
});
```

It returns:

```js
{
    name: 'John',
    roles: ['admin']
}
```

But why? The roles didn't get updated on the table. Am I missing something?

**Comment by koskimas** [comment]
`updateAndFetchById` doesn't update relations or handle them in any way. It's just sql update followed by sql select. Use debug() function to see the generated sql.

**Comment by sarneeh** [comment]
@koskimas I guess I didn't explain in propertly 😛 I know that `update` methods do not update relations. The thing is that after doing `updateAndFetchById ` the table did not get updated (expected), but it returns something that's not actually present in the database.

**Comment by koskimas** [comment]
Oh, ok :smile: That's weird. I'll have to see what's going on there.

**Comment by koskimas** [comment]
`updateAndFetchById` assigns the fetched values to the input and returns that object. This is probably not ideal, but I cannot change this before 2.0 since it's a breaking change. I'm not completely sure if this even should be changed. If you don't want that, you can simply update and fetch separately.
