### ISSUE TITLE
Inserting in a table having json array and text array results in "missing dimension value error"

### ISSUE THREAD

**Issue by nitish-vahan** [Vincit/objection.js#1096]
```  static get jsonSchema() {   
 static get jsonSchema() {
        return {
            type: 'object',
            required: [
                'channels'
            ],
            properties: {
                id: {type: 'string', format: 'uuid'},
                channels: { type: 'array', items: { type: 'string', enum: enums.campaignChannels }}
                requirements: {
                    type: 'array',
                    items: {
                        type: 'object',
                        required: ['requirement','hardRequirement'],
                        properties: {
                            requirement: {type: 'string', enum: enums.jobRequirements},
                            hardRequirement: {type: 'boolean'}
                        }
                    }
                }
            }
        };
    }
    ```

This is my schema which has text arrays ( channels) and also json array ( requirements), when i validate the schema, it return valid but inserting into the array results in "missing dimension value" error. 
this is my error stack trace 

"error: missing dimension value
    at Connection.parseE (/home/nitish/vahan/JobFinder/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/nitish/vahan/JobFinder/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/nitish/vahan/JobFinder/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:277:12)
    at readableAddChunk (_stream_readable.js:262:11)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onread (net.js:638:20)
From previous event:
    at Client_PG._query (/home/nitish/vahan/JobFinder/node_modules/knex/lib/dialects/postgres/index.js:260:12)
    at Client_PG.query (/home/nitish/vahan/JobFinder/node_modules/knex/lib/client.js:202:17)
    at Runner.<anonymous> (/home/nitish/vahan/JobFinder/node_modules/knex/lib/runner.js:146:36)
From previous event:
    at /home/nitish/vahan/JobFinder/node_modules/knex/lib/runner.js:48:21
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Runner.run (/home/nitish/vahan/JobFinder/node_modules/knex/lib/runner.js:34:31)
    at Builder.Target.then (/home/nitish/vahan/JobFinder/node_modules/knex/lib/interface.js:20:43)"

**Comment by koskimas** [comment]
Please read [this](http://vincit.github.io/objection.js/#issues) and update your issue.

**Comment by koskimas** [comment]
What I need is a way to reproduce this. Your schema does work when I try it out.

**Comment by nitish-vahan** [comment]
This is the query i got using the .toString() method on the query -
'''insert into "campaigns" ("address", "benefits", "callToAction", "channels", "city", "companyId", "contactPhoneNumber", "documents", "googleMapsLink", "jobCommitmentType", "jobTitle", "languages", "pinCode", "requirements", "salary", "timings", "title") values ('U27/5 Dlf Phase 3', '230000', 'We will call you', '["Whatsapp","Facebook Messenger"]', 'Delhi', 'bfc77565-f609-4f91-bdf2-d2b5f4330af0', '7799081425', 'asdadas', 'faaf', 'Part-time', '12', '["English","Kannada","Telugu","Malayalam"]', '122002', '[{"requirement":"Driver''s License","hardRequirement":true}]', '12222', '00:10', 'asadasdasdasd') returning "id"''' 
Below mentioned is the object try to save - 
'''{
    "title": "heyy",
    "city": "Bengaluru",
    "jobTitle": "12",
    "salary": "1222",
    "benefits": "230000",
    "jobCommitmentType": "Full-time",
    "documents": "asdasdsa",
    "contactPhoneNumber": "7799081425",
    "address": "U27/5 Dlf Phase 3",
    "pinCode": "122002",
    "callToAction": "We will call you",
    "timings": "00:10",
    "googleMapsLink": "faaf",
    "channels": [
        "Whatsapp",
        "Facebook Messenger"
    ],
    "requirements": [
        {
            "requirement": "Driver's License",
            "hardRequirement": true
        },
        {
            "requirement": "Bike",
            "hardRequirement": true
        }
    ],
    "languages": [
        "English",
        "Hindi",
        "Kannada",
        "Tamil",
        "Telugu",
        "Malayalam",
        "Bengali",
        "Marathi",
        "Arabic",
        "Bahasa"
    ],
    "companyId": "bfc77565-f609-4f91-bdf2-d2b5f4330af0"
}''' 


as i mentioned, requirements is a json array and languages and channels are text arrays

**Comment by koskimas** [comment]
By text array you mean postgres `text[]` type?

**Comment by nitish-vahan** [comment]
Yes text[] and json[]

**Comment by koskimas** [comment]
Ok, that's not directly supported. All arrays and objects are assumed to have a `json`, `jsonb` or `text` type in the database (objection doesn't know the type of the column in the db). 

You should convert your `json[]` type to just `jsonb` or `json`. There's no reason to have a `json[]` property since JSON itself has an array type.

You can probably make the `text[]` type work by implementing the `$formatDatabaseJson` method for your model (or a shared base class model):

```js
class YourModel extends Model {
  $formatDatabaseJson(json) {
    if (json.languages) {
      json.languages = lit(json.languages).asArray()
    }

    return super.$formatDatabaseJson(json)
}
```

**Comment by belwalshubham** [comment]
@koskimas I get the same error, but the approach is correctly worked in my case.  I don't find it in the objection.js ? can anyone help me here ? I am using postgres here 

here is my migration
`data TEXT[] NOT NULL`
here is my schema type 
 `data: { type: 'array', items: { type: 'string' } }`
 
 but when I pass the data: {yes} 
 then it gives me this error 
 ```
 malformed array literal: "["yes"]"
"[" must introduce explicitly-specified array dimensions.
```

**Comment by infinite-system** [comment]
This worked for me for basic array in the latest Objection.js 3.14:

```ts
 static get jsonSchema() {
        return {
            type: 'object',
            properties: {
              id: { type: 'string' },
              project_contact_type: {
                type: 'array',
                items: {
                  type: 'string'
                }
              }
        }
}
```

$formatDatabaseJson(json: any): Pojo {
    json = super.$formatDatabaseJson(json);
    if (this.project_contact_type) {
      const jsonArray = JSON.stringify(this.project_contact_type);
      json.project_contact_type =
        '{' + jsonArray.substring(1, jsonArray.length - 1) + '}';
    }
    return json;
}
  ```
  
  See: https://vincit.github.io/objection.js/api/model/instance-methods.html#formatdatabasejson
