### ISSUE TITLE
Unrelate relation on delete

### ISSUE THREAD

**Issue by danmo** [Vincit/objection.js#1099]
This question might sound trivial for some but it has bugged me for the past hours.

How does one remove relations when deleting an entry.

Example:
We have a `Film` entity which has a youtubeData 'HasOneRelation' relation
```
      youtubeData: {
        relation: Schwifty.Model.HasOneRelation,
        modelClass: VehicleYoutubeData,
        join: {
          from: 'films.id',
          to: 'films_youtubedata.film_id',
        },
      }
```

Now we want to delete a film and it's youtubeData relation:

```
  Film
    .query()
    .delete()
    .where({ title: 'Silicon Valley' });
```
Above will fail because the film_id is correctly still referenced in the films_youtubedata table.

Tried the following with no luck!
```await Model
      .query()
      .findById({ id })
      .$relatedQuery('youtubeData')
      .unrelate();
```

**Comment by koskimas** [comment]
You should do this in the db (migrations) using either `onDelete('CASCADE')`  or `onDelete('SET NULL')` for the film_id.

**Comment by yarnball** [comment]
@koskimas I am also stuck on this issue- I tried you suggestion without luck:
```
table.string('uniqID')
        .unsigned()
        .references('user_uniqID')
        .inTable('task')
        .onDelete('CASCADE')
```

Could you give an example?

My migrations look like this:
```
knex.schema.createTable('user', table => {
      table.increments('id').primary()
      table.string('username')
      table.string('uniqID')
    })
```
```
knex.schema.createTable('task', table => {
      table.increments('id').primary()
      table.string('title')
      table.string('user_uniqID').references('user.uniqID')
    })
```

**Comment by vladshcherbin** [comment]
@yarnball here is an example from my app (user - user_tokens). When user is removed, his tokens should also be removed:

```js
// users
exports.up = knex => (
  knex.schema.createTable('users', (table) => {
    table.increments('id')
    table.string('username', 20).notNullable().unique()
  })
)

// user_tokens
exports.up = knex => (
  knex.schema.createTable('user_tokens', (table) => {
    table.increments('id')
    table.integer('user_id').notNullable().index()
      .references('id').inTable('users').onUpdate('CASCADE').onDelete('CASCADE')
    table.text('token').notNullable().unique()
  })
)
```

This works for a PostgreSQL database. Hope it helps you :)

**Comment by yarnball** [comment]
@vladshcherbin thanks so much for the response. I still haven't had any success! Is it because I'm using `sqlite`?

Notice that in task, I have `references('uniqID')` (not `id`) as you had it. Is there something I'm doing wrong there?

Here's what I have:
```
knex.schema.createTable('user', table => {
      table.increments('id').primary()
      table.string('username')
      table.string('uniqID')
    })
```
And, the Task:
```
knex.schema.createTable('task', table => {
      table.increments('id').primary()
      table.string('title')
      table.string('user_uniqID').notNullable().index()
      .references('uniqID').inTable('users').onUpdate('CASCADE').onDelete('CASCADE')
    })
```

**Comment by vladshcherbin** [comment]
@yarnball you have wrong table name here (user vs users):

- knex.schema.createTable('user', ...
- .references('uniqID').inTable('users')

You also need unique index on `table.string('uniqID')`.

This one works:

```js
knex.schema.createTable('user', (table) => {
  table.increments('id').primary()
  table.string('username')
  table.string('uniqID').unique()
})

knex.schema.createTable('task', (table) => {
  table.increments('id').primary()
  table.string('title')
  table.string('user_uniqID').notNullable().index()
    .references('uniqID').inTable('user').onUpdate('CASCADE').onDelete('CASCADE')
})
```

**Comment by yarnball** [comment]
Thx.

Your method seems to work (PostgreSQL- not SQ Lite).

However, it now gives me this warning with my seeds. Any ideas why?
`insert or update on table "task" violates foreign key constraint "task_user_uniqid_foreign" `

**Comment by vladshcherbin** [comment]
@yarnball I think this is because it tries to insert tasks before users.

Maybe you have separate files like `seeds/tasks.js`, `seeds/users.js`. They are executed in alphabetical order - tasks before users.

**Comment by vladshcherbin** [comment]
@yarnball I've tried it in a single file and it works:

```js
exports.seed = async (knex) => {
  await knex('user').del().then(() => (
    knex('user').insert([
      { username: 'AB', uniqID: 'abc' },
      { username: 'XY', uniqID: 'xyz' }
    ])
  ))

  await knex('task').del().then(() => (
    knex('task').insert([
      { title: 'Foo', user_uniqID: 'xyz' },
      { title: 'Bar', user_uniqID: 'abc' }
    ])
  ))
}
```

**Comment by yarnball** [comment]
You're right, it is about it being in a **single file**.

They have to be in single file- with `user` first. If `task` is first- I get the same error. Something worth.

Thanks so much for your advice. Any tips on this working inside of `sqlite`?

**Comment by vladshcherbin** [comment]
@yarnball can't help you with `sqlite` as I don't have any experience using it. 🤷‍♂️

**Comment by yarnball** [comment]
@vladshcherbin As my model gets more complex, I keep having the issue saying:

`insert or update on table "task" violates foreign key constraint "task_user_uniqid_foreign"`

This happens when both seeding and migrations. The only way I can get them to work, is to put them in one single file, in the correct order.

Only seems to happen with PostgreSQL...

Any suggestions?

**Comment by vladshcherbin** [comment]
@yarnball as for seeds/migrations, here is [seeds cli doc](https://knexjs.org/#Seeds-CLI) which has this:

> Seed files are executed in alphabetical order. Unlike migrations, every seed file will be executed when you run the command. You should design your seed files to reset tables as needed before inserting data.

So, you should make them alphabetically right or use a single file. You can also insert data in migrations so that it will maintain the right order. Can't think of any better solution.

**Comment by yarnball** [comment]
@vladshcherbin disregard the seeds for now- migrations has the same issue.

Migration works fine with SQ Lite, but it is Postgres has an issue where the migrations MUST be in certain order, or they will fail. Is this expected behaviour?

migrate1.js
```
knex.schema.createTable('user', table => {
      table.increments('id').primary()
      table.string('username')
      table.string('code')
      table.string('uniqID').unique()
    }),
```

migrate2.js
```
knex.schema.createTable('task', table => {
      table.increments('id').primary()
      table.string('title')
      table.string('body')
      table.string('uniqID').unique()
      table.string('colour_uniqID').references('colour.uniqID')
      table.string('user_uniqID').references('user.uniqID'
    })
```

migrate3.js
```
knex.schema.createTable("colour", table => {
      table.increments("id").primary()
      table.string("name")
      table.string("uniqID").unique()
    })
```

**Comment by vladshcherbin** [comment]
@yarnball yes, migrations are usually created using cli:

```
yarn knex migrate:make create_tasks_table
```

This will create a file with a filename similar to this: `20181224154300_create_tasks_table`. It has a timestamp in it and will be executed in the order it was created.
