### ISSUE TITLE
Notes why objection is different to bookshelf for FAQ

### ISSUE THREAD

**Issue by elhigu** [Vincit/objection.js#11]
This question has come up few times, I wrote here some of my thoughts people who know better may correct me where I'm wrong:

> _pi: So what does objection.js do differently than bookshelf.js which is also based on knex?
> 
> khoker: I've been partial to Bookshelf for recent projects (like Objection, also built on Knex). I see a lot of similarities, but I think I might be missing the obvious "wow that looks so much easier" vibe.
> Anyone happen to see something that is annoying in Bookshelf that Objection might prove a solid alternative for?

One big difference is that `Objection.js` is not built following `Backbone`'s Model / Collections style, which I personally don't find really nice to play with. My biased feeling is that `Objection.js` has a nicer and cleaner syntax. One does not have to ponder when to use model and when collections and all map, find, etc. operations can be done with `lodash` or with methods that `bluebird` offers for promises. Self updating collection idea works better in frontend world. Also `Objection.js` avoid using events for passing information what is happening unlike `Backbone` models. 

`Objection.js` syntax to describe model properties, validation and relations is declarative.

Schema for validating DB input data uses standard JSON schema. 

`Objection.js` eagering syntax is more permissive with recursive eagering (I suppose bookshelf does not have it).

'Objection.js' APIs has also been coded in a way to help IDE's autocompletion to work, so if you are write `modelInstance.$query().` system knows that hey you got `QueryBuilder` as a return value and gives you a list of available methods and their documentation. `Objection.js` avoids using syntax where one writes `.allMightyFilter({ dogsName : { gt: 1} })` which is basically impossible to make work with autocomplete.

EDIT 6.1.2017:

To sum up some additional features, that has been implemented during last 1.5 years.

* Development has been active and supported by Vincit (https://www.vincit.fi/en/) (however direction of development is community driven)
* Now in addition to eager fetching data through relations one can also insert and upsert nested model hierarchy to database with single query-command.
* Table / Column JSON field references were promoted to first class citizens so  after #270 they can be passed to all APIs and references has also support for declaring additional casting / as for them `ref('table.column:jsonattribute.wat[0].etc').castNumber().as('etc')` or `ref('id')` which would have required `knex.raw('??', ['id'])` earlier.
* Support for postgresql JSONB operations including `jsonb_set` generation when patching single values inside jsonb column
* Eager fetching data through relations can be done with join or multiple selects (performance depends a lot case by case)
* Typings for typescript
* Improvements to Model's lifetime hooks and additional query context for passing some data for example session to multiple queries done by nested inserts or other more complex operations http://vincit.github.io/objection.js/#context

**Comment by kimmobrunfeldt** [comment]
I especially agree with the first point. The Backbone collection/model style in an ORM running in the backend is a bit weird. Good job with the moron.js! I'll try it in my current project :)

**Comment by elhigu** [comment]
One more difference which is currently under development will be extra APIs in QueryBuilder to make queries to PostgreSQL  jsonb columns. e.g. 
```javascript
.whereJsonSupersetOf("Persons.additionalJsonAttrsColumn:details.phoneNumbers", ['+358405551231234'])
```
which would check if certain phone number is found from user details etc. 

In this case `Person` table could have e.g. following json in `additionalJsonAttrsColumn`

```json
{ 
  "details": {
    "phoneNumbers": ["+5216425193182", "+358401231234", "+1239874567"]
  }
}

**Comment by delaneyj** [comment]
It would be great if this was part of the Introduction in the docs.  If felt using bookshelf for the last year that something felt cumbersome.  Didn't know the backbone style was the major culprit (and extensible was harder).  Objection.js seems like a clear start and embraces es7 stuff which is great.

**Comment by ozum** [comment]
Someone please correct me if I'm wrong with this.

AFAIK, bookshelf does not generate join queries for related tables. It asks DB with more than one queries to fetch results, even using withRelated and eager load.

This was the reason I'm not using bookshelf.js, although I find knex.js one of the most elegant db libraries of node.js world.

For example:

```sql
SELECT * FROM person WHERE id = 1;
SELECT * FROM pet WHERE pet.owner_id = 1;
```

instead of 

```sql
SELECT * FROM pet
INNER JOIN person ON pet.owner_id = person.id
```

**Comment by fl0w** [comment]
My personal experience thus far, which might be a bullet of interest:
The support for [composite keys](http://vincit.github.io/objection.js/#composite-keys) in objection.js really simplifies the labour, code and flow of a multi-tenant application.

**Comment by santiagovazquez** [comment]
I'm currently using bookshelfjs in production for a year now and I'm thinking of moving to objectionjs because of two things:
- JSON schema validation
- Transaction management (no need to pass the transaction object throw objects)

**Comment by elhigu** [comment]
I updated some major features to description, please ping me if I forgot anything important.

**Comment by koskimas** [comment]
I think this can now be closed. It's pretty outdated in every way.
