### ISSUE TITLE
Model.knex(...) fails when models are loaded from a separate project

### ISSUE THREAD

**Issue by jimsimon** [Vincit/objection.js#1104]
my-model.mjs in project A:
```javascript
export default class MyModel extends Model {
  ...
}
```

index.mjs in project B:
```javascript
import Knex from 'knex'
import objection from 'objection'
import { MyModel } from 'projectA'

const knex = Knex(...)
const { Model } = objection

Model.knex(knex)

await MyModel.query()
```

Error:
```
Error: no database connection available for a query. You need to bind the model class or the query to a knex instance.
```

Any models that are defined inside projectB are working fine, so it's just an issue with models coming from other packages.  Is there any way to work around this other than adding `MyModel.knex(knex)` as well?

**Comment by koskimas** [comment]
That's the way node modules work. There's nothing objection could do better here. You should avoid mixing multiple objection instances together.

**Comment by jimsimon** [comment]
@kibertoad It looks like having Objection as a peerDependency works perfectly, thanks!

**Comment by jimsimon** [comment]
As a side note to anyone using lerna that runs into this.  I had to use lerna's "hoist" option to get everything to resolve properly once I made Objection a peer dependency in the equivalent of "projectA" above.
