### ISSUE TITLE
Update Typescript optional field with upsertGraph

### ISSUE THREAD

**Issue by Nebulis** [Vincit/objection.js#1106]
Hi,

I have a model which looks like the typescript example:

```typescript
export default class Movie extends Model {
  readonly id!: number;
  name?: string;
```

I'm wondering how to handle the case when you want to set the `name` to NULL using `upsertGraph`? From what I observed:
- when inserting and by using `useNullAsDefault` you can omit the field which will be inserted as NULL
- when updating, undefined value are ignored by `knex`
- you can't update using null value as Typescript will complain about it:
`Movie.query().upsertGraphAndFetch({...country, name: null});` produces `Type null is not assignable to type string | undefined`

To overcome this I could eventually change the type of name to:
- name: string | null
- name? string | null
But I'm not fond of this as it can lead to some kind of inconsistency (sometimes using `?`, sometimes using `| null`)

I know the issue is not due to `Objection` (undefined value are ignored by `knex`), however I was wondering if there is something we could add in the library to overcome this (am I the only one having this issue ?).

Thanks for your feedback.

**Comment by LeartS** [comment]
> am I the only one having this issue ?

Hey, we're at least 2! Quite a big issue, from what I see basically it's not possible to set a nullable column to null using objection in typescript, unless you set the property as `type | null` in the model definition.

**Comment by koskimas** [comment]
If you can set the value to null, then the type `type | null` is correct.

**Comment by jcyh0120** [comment]
I am facing this problem, too!
Here's the error message when upsertGraph of a nullable type relation in model.
( I use the koa-ts Person model as example)

`Type '{ firstname: string; }' is not assignable to type 'Expression<Person | null | undefined>'.`

```typescript
export default class Person extends Model {
  id!: number
  firstName!: string
  lastName!: string
  age!: number

  pets?: Animal[]
  movies?: Movie[]
  children?: Person[]
  parent?: Person | null // <--- make the parent nullable
}
```

```typescript
// This one shows the error above.
const upsertGraph1 = await Person.query(trx)
        .upsertGraph({ id: 123, parent: { firstname: "hello" } })

// This one works using upsert to unrelate a relation model
const upsertGraph2 = await Person.query(trx)
        .upsertGraph({ id: 123, parent: null })
```

How should we define the relation type which is nullable when using objection?
It seems that `parent?:Parent` or `parent?:Parent | null` both had conditions that doesn't fit in typescript.
