### ISSUE TITLE
Async hooks (beforeInsert, beforeUpdate...)

### ISSUE THREAD

**Issue by yachaka** [Vincit/objection.js#111]
Is there any way to perform async operations in hooks ? It's a pretty big feature.

**Comment by koskimas** [comment]
The hooks are asyn. Simply return a promise from them. First sentence in the [documentation](http://vincit.github.io/objection.js/#_s_beforeupdate) :wink:

**Comment by yachaka** [comment]
I guess I'm kind of an idiot on this one then lol !
I'm closing, and thanks.
