### ISSUE TITLE
Is there any way to support this kind of 'hasMany' relationship.

### ISSUE THREAD

**Issue by leopku** [Vincit/objection.js#1111]
Hi guys, I am new to this great project. 

I have a `hasMany` relationship as follow:

Table A:

|   id  |  ids_of_b  | 
| --- | --- |
|  1   | 1,2,3    |

Table B:

|   id  |  name  | 
| --- | --- |
|  1   | b1    |
| 2 | b2 |
| 3 | b3 |

Is there some way to define relationships like this:

```js
class A extends Model {
  static get relationMappings() {
    return {
      hasManyB: {
        relation: Model.hasManyRelation,
        modelClass: B,
        join: {
          from: ids_of_b => ids_of_b.split(','),
          to: 'id'
        }
      }
    }
  }
}
```
Many thanks for any suggestion.

**Comment by koskimas** [comment]
Unfortunately no.
