### ISSUE TITLE
Update BelongsToOneRelation using upsertGraph without id?

### ISSUE THREAD

**Issue by mindnektar** [Vincit/objection.js#1112]
Hi!

Is it possible to update a BelongsToOneRelation using upsertGraph without passing an id? As in, update if one exists and insert if it doesn't? If this is not possible, what would the recommended alternative be?

Example:

```
SomeModel.query().upsertGraph({
    id: 'some-id',
    someRelation: {
        someKey: someValue,
    },
});
```

Since someRelation is a BelongsToOneRelation, either there is one representation in the database or there isn't. I wish upsertGraph to update the relation if there is one and insert it if there isn't.

Thanks for any help!

**Comment by koskimas** [comment]
It's not currently possible. How would upsertGraph differentiate the situation where the user want's to insert a new item when there's no id, from your situation? We would need to add a new configuration option. Something like `updateOneToOneIfExists`. Seems awfully specific. I'm open for adding such option if more people come here and give thumbs up for this.

If all you do is update a single 1-1 relation, how about this:

```js
const something = await SomeModel
  .query()
  .findById('some-id')
  .joinEager('someRelation');

await something.$query().patch(obj)

if (something.someRelation) {
  await something.$relatedQuery('someRelation').patch(obj.someRelation)
} else {
  await something.$relatedQuery('someRelation').insert(obj.someRelation)
}
```

Definitely easier to understand than:

```js
SomeModel.query().upsertGraph({
    id: 'some-id',
    someRelation: {
        someKey: someValue,
    },
}, {
  updateOneToOneIfExists: ['someRelation']
);
```

**Comment by mindnektar** [comment]
Yeah, I figured it was gonna be like this. In most cases so far, my API has the luxury of being able to just grab the graphql variables and pass them to `upsertGraph` as they are. Your solution is fine of course, but it's a lot more verbose and requires me to explicitly specify the relation(s). My particular use case is more along the lines of this:

```
SomeModel.query().upsertGraph({
    id: 'some-id',
    someRelation: {
        someKey: someValue,
        someNestedRelation: {
            someOtherKey: someOtherValue,
        },
    },
});
```

I guess I could try to write a wrapper function for cases like these, though I still wouldn't mind an `updateOneToOneIfExists` option personally. :) Thanks for your help!

**Comment by mindnektar** [comment]
For anyone who ran into the same problem, this is my current solution. In short: I'm overriding `upsertGraph` and `upsertGraphAndFetch` and adding id keys to any nested object in the passed graph that does not have an ID and that is a `BelongsToOneRelation`. It only adds the id if there is a representation in the database. If there isn't, no id is added and `upsertGraph` will go ahead and insert.

```
const { Model, QueryBuilder } = require('objection');

const convertNodesWithoutIdToRelationExpression = graph => (
    Object.entries(graph).reduce((result, [key, value]) => {
        if (typeof value === 'object' && !value.id) {
            const subs = convertNodesWithoutIdToRelationExpression(value);

            return [
                ...result,
                subs.length > 0 ? `${key}.[${subs}]` : key,
            ];
        }

        return result;
    }, [])
);

const populateGraphWithIds = (graph, instance) => (
    Object.entries(graph).reduce((result, [key, value]) => {
        if (typeof value === 'object'
            && !value.id
            && instance[key]
            && instance.constructor.getRelations()[key] instanceof Model.BelongsToOneRelation
        ) {
            return {
                ...result,
                [key]: {
                    id: instance[key].id,
                    ...populateGraphWithIds(value, instance[key]),
                },
            };
        }

        return { ...result, [key]: value };
    }, {})
);

module.exports = class CustomQueryBuilder extends QueryBuilder {
    async transformGraphForBelongsToOneRelations(graph) {
        const relations = convertNodesWithoutIdToRelationExpression(graph);

        if (relations.length > 0) {
            const instance = await this.modelClass().query().findById(graph.id);
            await instance.$loadRelated(`[${relations}]`);
            return populateGraphWithIds(graph, instance);
        }

        return graph;
    }

    // @overrides super.upsertGraph
    async upsertGraph(graph, options) {
        return super.upsertGraph(
            this.transformGraphForBelongsToOneRelations(graph),
            options,
        );
    }

    // @overrides super.upsertGraphAndFetch
    async upsertGraphAndFetch(graph, options) {
        return super.upsertGraphAndFetch(
            this.transformGraphForBelongsToOneRelations(graph),
            options,
        );
    }
};
```

**Comment by koskimas** [comment]
There doesn't seem to be much interest for this feature. Closing for now.
