### ISSUE TITLE
Please add "who uses" page to the faq/web page.

### ISSUE THREAD

**Issue by bryanbrunt** [Vincit/objection.js#1113]
I suppose this would be a docs, enhancement request. 

Could you add a page on http://vincit.github.io/objection.js/ that lists the projects that use objection.js?

It would be a promotional benefit to be able to see the companies that use objection. Also, if there are github projects that use objection, those projects could be listed.

Sequelize has a similar page here:

http://docs.sequelizejs.com/manual/faq/whos-using.html

I'm interested if there are any games out there that use objection.js. My project is a game.

I'd like to write an open source game template that people would be able to build upon.  Obviously the template would use objection.js, but the template would make use of many other node libraries that I've found useful like agenda, socket.io, etc.

**Comment by douggr** [comment]
While this is not in docs (yet?), they kindly provided this [pinned issue](https://github.com/Vincit/objection.js/issues/1069).

**Comment by koskimas** [comment]
Done.
