### ISSUE TITLE
fn is not a true shortcut for Model.knex().fn.

### ISSUE THREAD

**Issue by mastermatt** [Vincit/objection.js#1115]
I was thrown for a loop today when I couldn't use `MyModel.fn.now()`, but I could use `MyModel.knex().fn.now()` and the [docs](http://vincit.github.io/objection.js/#fn) say that it's just a shortcut.

The issue is that in [`Model#fn`](https://github.com/Vincit/objection.js/blame/master/lib/model/Model.js#L505) is a static method while in [`knex`](https://github.com/tgriesser/knex/blob/d4a3387c56c0ec93ad554074a514d4300cea64ef/src/util/make-knex.js#L116-L121) it's a getter.

The solution for me is to use `MyModel.fn().now()`.

I think `Model#fn` should be made a getter as well, but at the very least the docs should be updated to be less ambiguous.

**Comment by koskimas** [comment]
Weird, that's been there since v0.1 and no one has brought this up before. I'll update the docs. We can't really change the method before 2.0 because it's a breaking change.

**Comment by mastermatt** [comment]
Can this issue be linked under the [2.0](https://github.com/Vincit/objection.js/projects/1) project? I've never used GH projects, not sure myself.

**Comment by koskimas** [comment]
Fixed by #1119
