### ISSUE TITLE
resultSize returns a string

### ISSUE THREAD

**Issue by mastermatt** [Vincit/objection.js#1116]
This may be related to the driver, I was using mysql when I came across this, but in my case calling `resultSize` on a query builder is returning a string. Considering the [fallback in the method](https://github.com/Vincit/objection.js/blob/master/lib/queryBuilder/QueryBuilder.js#L525) is to return the number `0`, I think this is a bug. 

To compound the issue for me, the [TS typing](https://github.com/Vincit/objection.js/blob/master/typings/objection/index.d.ts#L849) shows it returns a `Promise<number>`.

If passing the value through `parseInt` would not be considered backwards breaking, I'd be happy to open a PR.

**Comment by koskimas** [comment]
I can't think of a realistic situation where adding `parseInt` would break code. Calling `parseInt` or `parseFloat` again works etc. I'd merge a PR.
