### ISSUE TITLE
$beforeDelete

### ISSUE THREAD

**Issue by gerhardsletten** [Vincit/objection.js#112]
How to handle stuff that needs to be done before a model gets deleted?

**Comment by koskimas** [comment]
Currently there is no hook for that. I could consider adding it if other people also vote for this.

**Comment by yachaka** [comment]
That would be nice!
This would open up the way for handling cascade deletes.

**Comment by gerhardsletten** [comment]
Other use-cases is:

- Remove 'linked' binaries when the model is deleted
- If your model contains a cached summary of related models
- Other cache invalidation stuff

**Comment by jmealo** [comment]
Before lifecycle functions are added; it's might be a good idea to design the life cycle to make sure it works cohesively.
