### ISSUE TITLE
Support a catch-all modifier hook

### ISSUE THREAD

**Issue by lehni** [Vincit/objection.js#1120]
I'd like to propose to add a way for a model class to provide a catch-all modifier for the case when a requested modifier isn't defined / found. Something along these lines:

```js
class MyModel extends Model {
  ...

  static modifierNotFound(builder, modifier) {
    // Do something with the modifier and the query, and return the builder if it was
    // handled, nullish otherwise, indicating Objection should still throw an error.
    const { properties } = this.getJsonSchema()
    if (properties && modifier in properties) {
      return builder.select(modifier)
    }
  }
}
```

Optionally it could also just return a boolean.

I think this could open the door to many more creative uses of eager expressions and modifiers, and would be a pretty great feature that could be added with very little overhead. I'd be happy to create a PR for it.

@koskimas what do you think?

**Comment by koskimas** [comment]
Yes, let's do it! A PR would be great!

**Comment by lehni** [comment]
Very cool! Do you like the naming?

**Comment by lehni** [comment]
I think returning boolean is cleaner probably?

**Comment by koskimas** [comment]
I would have probably just added a default implementation that throws the error and overriding the method would automatically cause no error to be thrown. Boolean is fine too.

**Comment by lehni** [comment]
I can do that, yes! But what if my overriding implementation doesn't handle a given modifier and would like to throw the sam error?

I was thinking yesterday after doing this that instead of directly handling it, it could return a function if a given modifier should be handled.

**Comment by koskimas** [comment]
In that case it can delegate to the default implementation `super.noModifierFound(builder, modifier)`. Why would it return a function?

**Comment by lehni** [comment]
I can do that, yes! But what if my overriding implementation doesn't handle a given modifier and would like to throw the sam error?

I was thinking yesterday after doing this that instead of directly handling it, it could return a function if a given modifier should be handled.

**Comment by lehni** [comment]
Because it wouldn't necessarily receive the `builder` then, just the modifier, and somebody could do their own `modifier` store, similar to `modifiers` which are also functions... Just a thought for more flexibility. and you're right, delegation would solve that. I change it.

**Comment by lehni** [comment]
I've rewritten this now as discussed. I needed to move `ModifierNotFoundError` to model and things got a bit more complicated in result. I'm not sure I've done everything how you would address it. PTAL.
