### ISSUE TITLE
Error when using joinEager

### ISSUE THREAD

**Issue by isanimu** [Vincit/objection.js#1128]
Please see my [gist](https://gist.github.com/isanimu/17eb1cbff8b25010e213eb050a670a5c).

I'm working on multiple MySQL databases. For the sake of simplicity I created two databases:
1. Master
2. Detail

The models that you'll see in the gist `Product` & `Sales` are also just for the sake of simplicity.

I don't want to use `bindKnex()` method because it cannot solve my problem when doing query using `eager` and `graph` API.

Then I saw that by prefixing the model's tableName property's value with the database name should solve the problem. 

```
static get tableName() { return `myDb.myTable`; }
```

So, I just want to use a single `Knex` connection because it would make it simple. That's why if you see in `db.js` file, `main` DB is using `information_schema` which will be used by `Model` class.

```
const { main } = require(`./db`);

Model.knex(main);
```

When doing insertGraph it works.

```
const Product = require(`./product.js`);

(async () => {
  const result = (
    await Product
      .query()
      .insertGraphAndFetch([
        {
          id: 1,
          name: `Blaah`,
          sales: [{
            id: 1,
            qty: 1,
          }],
        },
      ])
  );
  
  console.log(result);
})();
```

But the problem is when doing joinEager:

```
const result = (
  await Product
    .query()
    .eagerOptions({ joinOperation: `innerJoin` })
    .joinEager({
      sales: true,
    })
);
```

I got this exception:
```
TypeError: Cannot read property 'length' of undefined
    at createModel (.../node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:643:32)
    at RelationJoinBuilder.rowsToTree (.../node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:122:19)
    at JoinEagerOperation.onRawResult (.../node_modules/objection/lib/queryBuilder/operations/eager/JoinEagerOperation.js:41:29)
    at promise.then.result (.../node_modules/objection/lib/queryBuilder/QueryBuilder.js:1181:45)
```

Currently the only workaround is to set the `Knex` connection for each models.
```
const { master, detail } = require(`./db`);

Product.knex(master);
Sales.knex(detail);
```
Which actually the thing that I want it to avoid because I just want to use a single `Knex` connection. The reason is because most DBMS support this as long the databases are in the same instance. This is something that can be done by using raw SQL but was never easy when using ORM.

I wish that the case could be solved with simple code like this:
```
Product
  .query()
  .withSchema(`master`)
  .eager({
    sales: {
      $schema: `detail`,
    },
  });
```
Using **$schema** as part of the `RelationExpression`.

`MySQL version: 5.6.0`
`Objection version: 1.4.0`
`Node.js version: 11.0.0`
`OS version: macOS 10.14`

**Comment by koskimas** [comment]
Your gist is full of errors. `relationMappings` must me a static getter. The transaction is never used, etc. Could you provide a gist that I can run?

**Comment by isanimu** [comment]
> Your gist is full of errors. `relationMappings` must be a static getter. The transaction is never used, etc. Could you provide a gist that I can run?

@koskimas Sorry about that. I've fixed it. Please try again.

**Comment by isanimu** [comment]
In my gist I also found that if I don't comment the case 2 before running case 3 it will still throws the same exception as before.

**Comment by koskimas** [comment]
You should never mix two connections like this:

```js
      Product.knex(master);
      Sales.knex(detail);
```

This will break so many things.

The problem here seems to be that `joinEager` needs to fetch the table metadata and it doesn't get it through the `main` knex since that database doesn't contain the needed tables.

You can bypass the metadata fetching by overriding the [tableMetadata](http://vincit.github.io/objection.js/#tablemetadata) method. Something like this:

```js

const { Model } = require(`objection`);

class Product extends Model {
  static get schemaName() {
    return `master`;
  }
  
  static get tableName() {
    return `${this.schemaName}.product`;
  }

  static get tableMetadata() {
    return {
      columns: ['id', 'name']
    };
  }
  
  static get relationMappings() {
    const Sales = require(`./sales`);
    
    return {
      sales: {
        relation: Model.HasManyRelation,
        modelClass: Sales,
        join: {
          from: `${Product.tableName}.id`,
          to: `${Sales.tableName}.productId`,
        },
      },
    };
  }
}

module.exports = Product;
```

You need to do this for each Model.

You may still run into other problems because the way you have prefixed the table name using the database name. It's not tested in objection very well.

**Comment by koskimas** [comment]
@isanimu Were you able to solve this?

**Comment by isanimu** [comment]
> @isanimu Were you able to solve this?

Yes, I was able to solve the problem using the solution you've provided.

But `tableMetadata` should be a function instead of a property.

Thanks.
