### ISSUE TITLE
It inheritance is possible ?

### ISSUE THREAD

**Issue by dawadam** [Vincit/objection.js#1130]
Hi,
I search the documentation, I do not find my happiness on one point.
I do not know if it is an existing feature or not, in doubt, I ask here.
Is it possible to make inheritance?

I have these 3 tables :

STEP
- id
- name
- time
- discr

STEP_WORK
- id
- work_field

STEP_FUN
- id
- fun_field

The data in the STEP_WORK and STEP_FUN table are incomplete without those in STEP.
The "discr" field makes it possible to discriminate between STEP_WORK and STEP_FUN
The 'id' field have the same value for a STEP_WORK table and its corresponding STEP table and for a STEP_FUN table and its corresponding STEP table.

How to retrieve for example the list of STEP_WORK with the additional information contained in STEP?
I'm doing it using a BelongsToOneRelation relationship, but the end object looks like:

```
{
  id: 1,
  work_field: 'development',
  step: {
    id: 1,
    name: 'robert',
    time: 123456789,
    discr: 'work'
  }
}
```

While it should look like:

```
{
  id: 1,
  work_field: 'development',
  name: 'robert',
  time: 123456789
}
```

**Comment by koskimas** [comment]
You can use `joinRelation`:

```js
Work.query()
  .select('*')
  .joinRelation('work')
```

You can create a `modifier` that calls those functions if want to save some lines of code.

There is no way to automatically do this for each query though...

**Comment by dawadam** [comment]
Thanks for the answer.
Is it possible to use this function without selecting anything with * ?
Because if not in some cases there will be big unnecessary requests.

**Comment by dawadam** [comment]
Hi,
joinRelation work nice, but is like an old school request.
When we use this method, we lose the benefits of the model, such as $ afterGet for example.
Is it not possible to have both?

**Comment by rkingon** [comment]
@koskimas I love ObjectionJS, it's really great! I am struggling a little on this lack of inheritance as well. Having a "type" column (sti / mti) is extremely common and supported across all major ORMs. 

Here is a scenario:
```
PostModel
TextPostModel extends PostModel
ImagePostModel extends PostModel
VideoPostMOdel extends PostModel
```

One Table (Posts) -- Single table inheritance, has columns: title, body, imageSrc, videoSrc

Validations: Post requires `title` (all), Text requires `body`, Image requires `imageSrc`, Video requires `videoSrc`
Methods: Text may have an `except` method, image my have a `generateThumb` method, etc.

As you can see, they behave differently and have uniqueness about them, but are all "Posts"

This is a pretty rough example, obviously, but used so often and in our current implementation we are battling this same mythology. 

I feel like defining the `PostModel` we can have a type map that assigns the classes based on type.
```
Types {
  video: require('./VideoPostModel'),
  image: require('./ImagePostModel'),
  ...
}
```

after queries, rather than creating instances of just Post model, it maps the types and rather creates the extended Class.

This would be super useful and this weekend I don't mind taking a peek at the code to see if I could help contribute in any way... Figured it best to discuss with you though before. Let me know your thoughts!

**Comment by rkingon** [comment]
+1

**Comment by kennethacohen** [comment]
@rkingon realize this is "ancient" - just curious if you ended up landing on a good path for working with inheritance. I have a very similar setup to the example you provided.

**Comment by rkingon** [comment]
I came up with a lil something... was a bit ago. For reference, I was on Objection `1.6.11`

First, a plugin that gives it the ability to handle this "discriminator" functionality. (Please note, this is not fully tested across every use case in Objection, so you may need to further customize it to fit your needs. This was all I needed to do to prove concept for my internal team).

```js
function DiscriminatorModel (Model) {
	return class extends Model {
		static getDiscriminatorClass (json) {
			if(this.discriminatorMappings) {
				const discriminatorValue = json[this.discriminatorColumn]
				const discriminatorClass = this.discriminatorMappings[discriminatorValue]
				return discriminatorClass
			} else {
				return this
			}
		}

		static fromJson(json, options) {
			const discriminatorClass = this.getDiscriminatorClass(json)
			const model = new discriminatorClass()
			model.$setJson(json || {}, options)
			return model
		}

		static fromDatabaseJson(json) {
			return this.fromJson(json)
		}
	}
}
```

Create a `PostModel`, which extends `DiscriminatorModel` -- `discriminatorColumn` is the property that will be used to discriminate (ie: type). `discriminatorMappings` is your reference to the relevant models. (See option 1 of https://vincit.github.io/objection.js/guide/relations.html#require-loops) on why we use require here
```js
// Note: I usually like to create a BaseModel that includes all my relevant plugins, then extends that
class PostModel extends DiscriminatorModel(Model) {} {

	static tableName = 'posts'
	static discriminatorColumn = 'type'

	static get discriminatorMappings () {
		return {
			'text': require('./TextPostModel'),
			'video': require('./VideoPostModel'),
			'image': require('./ImagePostModel')
		}
	}

}
```

Create each Typed Model...
```js
class TextPostModel extends PostModel {}
class VideoPostModel extends PostModel {}
class ImagePostModel extends PostModel {}
```

I hope this helps! Use this as a base, but not the bible ;) -- It was just a prototype

**Comment by 0gust1** [comment]
We're also facing the same type of problematic, with the added complexity of a typescript codebase.
We're using objection 2.2.3. (thanks for this lib !)

I'm curious of the current @koskimas's opinions and hints about this topic. Is @rkingon solution worth digging (thanks for it by the way) ?

Any help appreciated :)

**Comment by rkingon** [comment]
@0gust1 we are using it in production without any hiccups. it's been rather great, tbh

**Comment by 0gust1** [comment]
🙇 Many thanks for the feedback !

**Comment by kasvith** [comment]
Im also curios about this

**Comment by Warkanlock** [comment]
Is this yet not possible?
