### ISSUE TITLE
Sub queries does not use/support columnNameMappers

### ISSUE THREAD

**Issue by kamote** [Vincit/objection.js#1131]
Our models have a custom columnNameMapper that convert date values into a timestamp and other custom operations

It works on simple queries
```
user.query().where('createdAt', '>', '2018-01-01 10:20:20') 
-->  select "users".* from "users" where "createdAt" = 1514802020000 
```
However it does not work properly on subqueries
```
model.query()
  .where((builder) => {
    builder.where('createdAt', '2018-01-01 10:20:20')
      .orWhere('createdAt', '>', '2018-01-01 10:20:20');
  })
```

Actual Query
```
select "users".* from "users" 
where ("createdAt" = '2018-01-01 10:20:20' or "createdAt" > '2018-01-01 10:20:20')
```

Expected Query
```
select "users".* from "users" 
where ("createdAt" = 1514802020000 or "createdAt" > 1514802020000)
```

**Comment by kamote** [comment]
@koskimas I think this issue also applies to column names.

Normal query and uses `columnNameMapper` 

```
const query = models.card.query()
              .where('isCorpCard', false)

select `cards`.* from `cards` where `is_corp_card` = 0
```

Model query with **builder** functions and it does not use `columnNameMapper`
```
models.card.query().where(builder => {
  builder.where('isCorpCard', false);
});

select `cards`.* from `cards` where (`isCorpCard` = false);
```

**Comment by kamote** [comment]
We have a custom query builder

```
class CustomQueryBuilder extends QueryBuilder {
  constructor(modelClass) {
    super(modelClass);
  }

  where() {...}
}
```

```
models.card.query().where(builder => {
  builder.where('isCorpCard', false);
});
```
`builder.where` is not calling `CustomQueryBuilder.where`

**Comment by koskimas** [comment]
Ok, that explains things :smile: In that case it's weird that your overridden `where` methods are not used in the nested queries. I'll see if I could improve this.

**Comment by kamote** [comment]
@koskimas Alright! :smile:

Yep I dig little bit and end up of this line

https://github.com/Vincit/objection.js/blob/master/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js#L136-L143

so for example

```
models.card.query().where(builder => {
  builder.where('isCorpCard', false);
});
```
Its like the function `func` now bind to `QueryBuilderBase` instead of  the extended `QueryBuilder`

Also tried changing code `convertQueryBuilderFunction` like trial and error and end up endless loop :bowtie:
```
function convertQueryBuilderFunction(knexQueryBuilder, func, builder) {
  const convertedQueryBuilder = builder.clone();

  convertedQueryBuilder.subqueryOf(builder);
  func.call(convertedQueryBuilder, convertedQueryBuilder);
  convertedQueryBuilder.buildInto(knexQueryBuilder);
}
```

Btw here a gist for our custom query builder https://gist.github.com/kamote/a97fe37908b6a031c5b3bf25fed1c6aa#file-custom-query-builder-js-L110-L135

Our entire codebase already using sequelize then we are moving towards  knex/objection.js due to `oracle` support. 
In that gist jsonSchema handle the `field` or column overrider. We cant simply use knex's wrapIdentifier  and postProcessResponse since our code databases does not store "camelCase" only or "UPPERCASE" only column we have a mixed :sweat_smile: so leverage `jsonSchema` for that.
Also in the gist we are doing some conversion of values as well, for example 
- convert all boolean into number vise versa (good for oracle) oracle doe not have boolean
- convert all dates to timestamp vise versa (oracle only) handling dates for oracle is hard

**Comment by kamote** [comment]
@koskimas I'ved manage to fix this issue using this code.

```
class CustomQueryBuilder extends QueryBuilder {
  constructor(modelClass) {
    super(modelClass);
  }

  _whereOverride(method, prop, ...args) {
    // Functions: and Grouped Chain:
    if (_.isFunction(prop)) {
      const builder = this.clone();

      builder.clearWhere();
      builder.clearSelect();

      prop.call(builder, builder);

      const knexBuilder =  builder.build();
      const compiledSQL = knexBuilder.toSQL('where');

      const fixedMethod = method === 'whereNot' || method === 'orWhereNot'
        ? method.replace('Not', '')
        : method;

      const knexWrappedFunction = function knexWrappedFunction() {
        return this[`${fixedMethod}Raw`].apply(this, [compiledSQL.sql.slice(6), compiledSQL.bindings]);
      };

      return super[method].call(this, knexWrappedFunction);
    }

    const modelClass = this.modelClass();

    // Object Syntax:
    // .where({
    //   first_name: 'Test',
    //   last_name:  'User'
    // })
    if (_.isPlainObject(prop)) {
      return super[method].call(
        this,
        modelClass.columnNameMappers.format(prop)
      );
    }

    // Operator:
    // .where('id', '>', 1)
    if (args.length > 1) {
      const fomatted = formatter(modelClass, prop, args[1]);

      return super[method].call(this, fomatted[0], args[0], fomatted[1]);
    }

    // Key, Value:
    // .where('id', 1)
    const fomatted = formatter(modelClass, prop, args);

    return super[method].call(this, fomatted[0], fomatted[1]);
  }

  where(prop, ...args) {
    return this._whereOverride.apply(this, ['where', prop, ...args]);
  }

  orWhere(prop, ...args) {
    return this._whereOverride.apply(this, ['orWhere', prop, ...args]);
  }
}
```

We can now close this issue if you want, thanks for the help!.

However this issue can be still consider as feature request since `builder` here still not bound to `CustomQueryBuilder` which will be bound to `QueryBuilderBase ` on compile/build time https://github.com/Vincit/objection.js/blob/master/lib/queryBuilder/operations/ObjectionToKnexConvertingOperation.js#L136-L143

```
models.card.query().where(builder => {
  builder.where('isCorpCard', false);
});
```
