### ISSUE TITLE
Query by array fields

### ISSUE THREAD

**Issue by alex-mironov** [Vincit/objection.js#1133]
Not really an issue, rather clarification about documentation. 

How to query by array fields?

With such model, I would expect it to work like:
```
  ....
    .query()
    .whereJsonHasAny('country_list', 'US')
```

model:
```
  ....
        countryList: {
          type: 'array',
          default: [],
          items: {
            type: 'string'
          }
        }
```
Is it possible?

**Comment by hroland** [comment]
I think it might be more relevant to ask this on the [knex repo](https://github.com/tgriesser/knex)

**Comment by alex-mironov** [comment]
buy the `whereJsonHasAny` is part of objection API, not knex

**Comment by alex-mironov** [comment]
I have also found this issue, not sure if it's valid or not, could someone please clarify? https://github.com/Vincit/objection.js/issues/943
