### ISSUE TITLE
Feature request: Make knex a adapter

### ISSUE THREAD

**Issue by stoffern** [Vincit/objection.js#1134]
Porting knex to be used as a adapter will make it easier to implement other ORMs or database integrations. I think this is fairly possible set that the Models are so well defined.

**Comment by elhigu** [comment]
Could you elaborate a bit more what do you mean?

Objection is pretty tightly coupled with knex APIs, so I suppose you could already just create your knex-api clone for your favorite database? 

Also knex allows you to create your own dialects as a separate packages which may use any database underneath, so knex in it self is a kind of adapter...

**Comment by stoffern** [comment]
I was more thinking about making functions like findOne, findMany etc called form the ORM or database adapter attached. This would make it simple to just move from knex/SQL over to noSQL and other database types.

**Comment by elhigu** [comment]
I still don't understand what do you mean exactly. Which parts should be called through adapter? Objection is probably not the tool you would like to use for abstracting between nosql / sql databases and that is actually against the core idea why objection was created in the first place.

**Comment by koskimas** [comment]
As @elhigu said, knex is tightly coupled with knex. The minimal adapter interface would be knex's interface, period.

**Comment by stoffern** [comment]
👍
