### ISSUE TITLE
Specify Schema on Base Model

### ISSUE THREAD

**Issue by abramjstamper** [Vincit/objection.js#1135]
I tried to implement what was discussed in this [issue](https://github.com/Vincit/objection.js/issues/85). However, it does not appear to resolve my issue. I only have one schema with using Postgres. I was trying to set it as the default on my BaseModel class so that I wouldn't have to specify a schema in every model. However, I'm thinking what was done in that issue is out of date, and I didn't seen anywhere in the documentation for Objection where it was specified how to set a schema. I only saw information for the query builder with Knex `.withSchema()`. Any assistance would be appreciated!

```js
const { Model, snakeCaseMappers } = require('objection');
const Objection = require('objection');
const { DbErrors } = require('objection-db-errors');

class DefaultSchemaQueryBuilder extends Objection.QueryBuilder {
  constructor(modelClass) {
    super(modelClass);
    if (modelClass.defaultSchema) {
      this.withSchema(modelClass.defaultSchema);
    }
  }
}

Model.QueryBuilder = DefaultSchemaQueryBuilder;
Model.RelatedQueryBuilder = DefaultSchemaQueryBuilder;

export default class BaseModel extends DbErrors(Model) {

  $beforeInsert() {
    const date = new Date().toISOString();
    this.createdAt = date;
    this.updatedAt = date;
  }


  $beforeUpdate() {
    this.updatedAt = new Date().toISOString();;
  }

  static get defaultSchema() {
    return 'my_db_schema';
  }

  static columnNameMappers = snakeCaseMappers();
}
```

I'm using versions:
```js
{
    "knex": "^0.15.2",
    "objection": "^1.2.2",
    "objection-db-errors": "^1.0.0",
    "objection-soft-delete": "^1.0.5",
    "pg": "^7.4.3",
}
```

**Comment by abramjstamper** [comment]
Issue was resolved by using Knex's searchPath item in the configuration file. If you're looking to set Objection/Knex to use a specific schema, check out [this link](https://knexjs.org/#Installation-client), and implement the `searchPath` array for your schema.

**Comment by stephanoparaskeva** [comment]
I have a similar schema, attempting to do a similar thing but I cannot seem to understand what to do. My schema is as follows:

```javascript
lass BaseModel extends Model {
    async $beforeUpdate(opt, queryContext) {
        await super.$beforeUpdate(opt, queryContext);
        this.updatedAt = new Date().toISOString();
    }

    static get jsonSchema() {
        return {
            type: 'object',
            properties: {
                updatedAt: {
                    type: 'string',
                    format: 'date-time',
                    default: new Date().toISOString(),
                },
                createdAt: {
                    type: 'string',
                    format: 'date-time',
                    default: new Date().toISOString(),
                },
            },
        };
    }
}

module.exports = {
    knex,
    BaseModel,
    Model,
};
```

I simply want to inherit this schema (extend) in my other models and carry on my day. What am I doing wrong?
