### ISSUE TITLE
Having trouble with eager filter that filters the parent query

### ISSUE THREAD

**Issue by booboothefool** [Vincit/objection.js#1136]
```
profile
---
id

persona
---
id | profile_id

swipe
---
id | persona_1_id | persona_2_id
```

How would I eager "get the profiles that do not have a persona.id listed under swipe.persona_2_id"?

Attempt:
```
const profile = await Profile
  .query()
  .joinEager('persona')
  .filterEager('persona', builder => builder.leftJoin('swipe', 'persona.persona.id', 'swipe.persona_2_id').whereNull('swipe.persona_2_id'))
```
^ This returns the correct personas that passed the filter, but all profiles still get returned. I would like a profile not to be returned at all if the eager persona did not pass the filter.

**Comment by koskimas** [comment]
Do you have a `ManyToMany` relationship defined from `persona` to other `persona` through `swipe`? If you don't, create one.  Let's assume the relation name is `swipes`. Then you can simply say

```js
const profile = await Profile
  .query()
  .joinEager('persona.swipes')
  .whereNotNull('persona:swipes.id')
```

Another solution is to use inner join instead of the default left join:

```js
const profile = await Profile
  .query()
  .joinEager('persona.swipes')
  .eagerOptions({ joinOperation: 'innerJoin' })
```

Here's another solution using normal eager and `joinRelation`:

```js
const profile = await Profile
  .query()
  .innerJoinRelation('persona.swipes')
  .eager('persona') // Only add this if you also want to fetch the nested `persona`.
```

If you don't want to create a relationship, here's one more option

```js
const { ref } = require('objection')

const profile = await Profile
  .query()
  .joinEager('persona')
  .whereNotExists(Swipe.query().where('persona_2_id', ref('persona.id')))
```

Or if you dont have a model for `Swipe`

```js
const profile = await Profile
  .query()
  .joinEager('persona')
  .whereNotExists(knex('swipe').where('persona_2_id', knex.ref('persona.id')))
```

**Comment by booboothefool** [comment]
Hi @koskimas I really appreciate the suggestions! I tried the first two, however they do not show what I expect. 

In `Persona` I have defined the relation:
```
            swipes: {
                relation: Model.ManyToManyRelation,
                modelClass: this,  // Persona model class
                join: {
                    from: 'persona.id',
                    through: {
                        from: 'swipe.persona_1_id',
                        to: 'swipe.persona_2_id',
                    },
                    to: 'persona.id',
                },
            },
```

In this case both
```
const profile = await Profile
  .query()
  .joinEager('persona.swipes')
  .whereNotNull('persona:swipes.id')

const profile = await Profile
  .query()
  .joinEager('persona.swipes')
  .eagerOptions({ joinOperation: 'innerJoin' })
```

return profiles whether or not they have a persona.id listed under swipe.persona_2_id.

**Comment by booboothefool** [comment]
Aha! The 4th suggestion:
```
const { ref } = require('objection')

const profile = await Profile
  .query()
  .joinEager('persona')
  .whereNotExists(Swipe.query().where('persona_2_id', ref('persona.id')))
```

Seems to work and do exactly what I want, but the others do not. I appreciate it! 👍

**Comment by koskimas** [comment]
You probably need to use the reverse relation (swap `through.from` with `through.to`) of `swipes` to make the first three work.
