### ISSUE TITLE
Error when using JoinEagerAlgorithm strategy : Oracle 12.1

### ISSUE THREAD

**Issue by goyatajay** [Vincit/objection.js#1138]
Getting "ORA-00972: identifier is too long" issue when using JoinEagerAlgorithm strategy. One of the column in child table is having column length as 30. Query generated has below aliasing created - 

ParentTable.query().where('PARENT_ID','1')
  .eagerAlgorithm(shareClassObj.JoinEagerAlgorithm)
  .eager('[ChildTable as c]');

 select c.COLUMN_NAME_WITH_30_CHARACHTER c:COLUMN_NAME_WITH_30_CHARACHTER 
FROM TABLE_1
LEFT JOIN CHILD_TABLE c
ON c.CODE   = TABLE_1.CODE.

Code works fine with default strategy but that cause multiple hits on Database.

**Comment by koskimas** [comment]
If you don't need to refer to the joined tables or columns explicitly, you can use `.eagerOptions({ minimize: true })` which minimizes the names. If you do need to refer to them, then you are currently out of luck. (you can use the minimized names, but the code will make zero sense to readers).

So Oracle has a 30 char limit for identifiers? That's... an interesting limit :smile:

**Comment by goyatajay** [comment]
No luck with eagerOptions({ minimize: true }) as it will still create an short alias for joined tables.BTW I don't need to refer to the joined tables or columns explicitly. What i need is the complete model object of the parent table entity with child objects.

**Comment by koskimas** [comment]
> as it will still create an short alias for joined tables

What do you mean by that?

**Comment by goyatajay** [comment]
Aliases are created with naming conventions as '_t1'/'_t3' for child tables with above option, 
Can we provide aliasing to each column in Model classes  , so that complete size with alias in select query  is less than 30 by providing a shorter name to column (similar to hibernate). Or framework have a mapping of column names to some smaller self maintained aliases instead of complete column name  by querying table metadata.

**Comment by koskimas** [comment]
So the column name is not minimized? Is that what you are saying?

**Comment by koskimas** [comment]
If you are not filtering by nested relations, why are you using the join based eager? The default eager algorithm has a better performance in most cases since the queries themselves are super simple. The query time is not a factor in simple eager queries (assuming you have indexes for foreign keys). Join based eager needs to move a huge amount of data from the db to the node app, which will fast become the performance bottleneck.

**Comment by goyatajay** [comment]
problem here is , 13 tables are joined with a nested depth of 4. No of to and fro in this case is huge. What I was expected to get all data in a single query .. can we somehow minimize the column name by giving alias at Model level..

**Comment by koskimas** [comment]
With that kind of deep nesting, you are definitely going to get better performance by not using the `JoinEagerAlgorithm` at all. The default algorithm doesn't have this problem.
