### ISSUE TITLE
model.query().insert() doesn't accepts camelcase.

### ISSUE THREAD

**Issue by ritwickdey** [Vincit/objection.js#1140]
In User Model: 
```
 static columnNameMappers = snakeCaseMappers();
```

Query:

```js

try {
  const user = await User.query().insert(firstName, lastName});
  res.send({ user, message: 'User profile is created' });
} catch (error) {
  return next(new HttpError(400, error.message));
}
```

I'm getting error 
`
"first_name: is a required property, last_name: is a required property"
`

If I change to `await User.query().insert(first_name: firstName, last_name: lastName});`. It works

**Comment by ritwickdey** [comment]
Also, one strange thing happening that if I use `.sql()`. I'm getting query like this `'select "user".* from "user"' `

**Comment by koskimas** [comment]
You have defined your jsonSchema using snake_case, so obviously it doesn't accept camel case.

**Comment by koskimas** [comment]
`jsonSchema` is *not* the database schema, but the "input" schema for creating model instances.

**Comment by ritwickdey** [comment]
After trying a lot I added these two lines 

 $parseJson(json, opt) { // De-Camelize key when creates Model Object
    return super.$parseJson(decamelizeKeys(json), opt);
  }

  $formatJson(json) { //Camelize key for  Model -> Json
    return camelizeKeys(super.$formatJson(json));
  }

**Comment by ritwickdey** [comment]
Hi @koskimas, thanks for reply.. I found the issue.. It was typo in Model Json Schema like an idiot.  I typed the required property as snake case.

![image](https://user-images.githubusercontent.com/18099464/48310666-5a81cf80-e5b8-11e8-900f-d14747e80c94.png)
