### ISSUE TITLE
Eager query debug print differs from real executed query

### ISSUE THREAD

**Issue by ataube** [Vincit/objection.js#115]
Somehow it seems like, executing an eager query produces wrong console debug print statements compared to the real executed query on the database. For example: 
```javascript
import { Model } from 'objection';
import CalculationValue from './CalculationValue';

export default class CalculationRate extends Model {
  static tableName = 'calculation_rates';
  static relationMappings = {
    values: {
      relation: Model.OneToManyRelation,
      modelClass: CalculationValue,
      filter: { type: 'RATE' },
      join: {
        from: 'calculation_rates.id',
        to: 'calculation_values.calcable_id',
      },
    },
  };
}

CalculationRate.query().eager('values').then(...);

//console output
{ method: 'select',
  options: {},
  bindings: [],
  sql: 'select * from "calculation_rates"' }
{ method: 'select',
  options: {},
  bindings: [ 1, 'RATE' ],
  sql: 'select * from "calculation_values" where "calculation_values"."calcable_id" in (?) and "type" = ?' }

// executed query in the db (postgres) => SELECT * FROM   pg_stat_activity;
"select * from "calculation_values" where "calculation_values"."calcable_id" in ($1) and "type" = $2"
```
I am wondering if the first console log statement gets executed or not because this would be really expensive on a large dataset. Can you validate what statements get executed, maybe it's just a bug in the console log output? I'm also not sure if the `pg_stat_activity` lookup is the right why to validate this issue. 

thanks
Andreas

**Comment by koskimas** [comment]
The console output is correct. Your query actually does fetch all `CalculateRate` rows from the database and then all related `CalculateValues` for each of the result rows. You don't constraint the `CalculationRate` query in any way, so all row are fetched. Maybe you have misunderstood what the `eager` method does? What do you want to achieve?

**Comment by ataube** [comment]
Hey - thanks for the quick feedback. My goal was to fetch all CalculationRates with their values. So the code was actually doing what I wanted. I expected this would be possible with a single query which was the thing I misunderstood here. 

Maybe it would help to improve the eager docs a little bit, at least referencing the N+1 problem for further reading. What do you think?

**Comment by koskimas** [comment]
This could be done with a single query using joins, but the eager query system doesn't use joins. The docs could be improved a lot, but I never seem to find time to do that 😄.

I wrote a [blog post](https://www.vincit.fi/en/blog/nested-eager-loading-and-inserts-with-objection-js/) about the eager queries a while back though. I'll add a link to the blog post in the docs.
