### ISSUE TITLE
feature request: support anonymous functions as model references

### ISSUE THREAD

**Issue by capaj** [Vincit/objection.js#1150]
currently there are only two ways of specifying a model relation class. Either we import the class up top and supply it directly as a value or we use a string value. Using a model path as a string let's us escape cyclic dependency issue.
I'd like to have another way to solve the cyclic dependecny problem-using an inline function. 
So instead of:
```js
pets: {
        relation: Model.HasManyRelation,
        modelClass: path.join(__dirname, './AnimalModel'),
        join: {
          from: 'persons.id',
          to: 'animals.ownerId'
        }
      },
```

I could write:
```js
import AnimalModel from './AnimalModel'

pets: {
        relation: Model.HasManyRelation,
        modelClass: () => AnimalModel,
        join: {
          from: 'persons.id',
          to: 'animals.ownerId'
        }
      },
```

This way of defining dependecies works much better with ES6 tooling and editors-because when inspecting the second way in my editor I can just CTRL+click on the `AnimalModel` and read on about it. I don't have to manually navigate there by name.
Also when I move or rename the file VScode is able to fix the path automatically. Not so if I use the `path.join(__dirname, './AnimalModel')`

**Comment by capaj** [comment]
looking at how that code is needed to support the string paths:
https://github.com/Vincit/objection.js/blob/0eb7587f8312c1d5ea596b2369eb60a1750532cb/lib/utils/resolveModel.js#L54-L90
wouldn't it be easier for objection.js 2.0.0 to only support those inline functions and direct values?

That way objection.js can stay oblivious to all of this cruft that is modules and their exports.

**Comment by koskimas** [comment]
You can already define the whole `relationMappings` as a getter or an anonymous function:

```js
static relationMappings = () => ({
  pets: {
    ..
  }
})
```

which solves the same problem (when babel is used).

**Comment by koskimas** [comment]
The anonymous function/getter only solves the problem with Babel (and maybe ES6 modules, but I seriously doubt that) but not with require. It only works with `Babel` because of this:

```js
// Pet.js
import Person from './Person'
export default Pet extends Model {}

// Person.js
import Pet from './Pet'

export default class Person extends Model {
  static relationMappings = () => ({
    pets: {
      modelClass: Pet
    }
  })
}
```

gets transpiled into somthing like:

```js
// Pet.js
const _PersonModule = require('./Person')
module.exports.default = Pet extends Model {}

// Person.js
const _PetModule = require('./Pet')

module.exports.default = Person extends Model {
  static relationMappings = () => ({
    pets: {
      modelClass: _PetModule.default
    }
  })
}
```

It only works because `_PetModule` stays the same even when you have a circular dependency and the model is accessed through that module using `_PetModule.default`. Same goes with named exports and Babel. Using `require`, you still end up with `Pet` being an empty object:

```js
const Person = require('./Person')
// Pet.js
module.exports = Pet extends Model {}

// Person.js

// This is an empty in case of a circular dependency, because by the time
// this require is done, the `Pet` class has not been assigned yet.
const Pet  = require('./Pet')

module.exports.default = Person extends Model {
  static relationMappings = () => ({
    pets: {
      modelClass: Pet
    }
  })
}
```
