### ISSUE TITLE
Expression to recursively eager with additional relationships

### ISSUE THREAD

**Issue by Aerlin** [Vincit/objection.js#1153]
I have a Comment model with relationships for User (BelongsToOneRelation) and replies (HasManyRelation). I'd like to eager replies with each reply having a User object attached.  

At the moment I'm using `[user, replies.[user, replies.[user]]]` expression to retrieve 2 replies deep. Is it possible to eager recursively (replies.^) with each having its own eagered (user) object attached?

**Comment by koskimas** [comment]
Unfortunately no. You can only use `.^` for a single relation. You can pretty easily create a helper for this though. Have you noticed the relation expression object notation?

Your relation expression using the object notation would be:
(is there a typo, or does `replies` really have a `replies` relation?

```js
{
  user: true,
  replies: {
    user: true,
    replies: {
      user: true
    }
  }
}
```

Your helper could be something as simple as this:

```js
function nestedReplies(depth) {
  if (depth === 0) return {}

  return {
    user: true,
    replies: nestedReplies(depth - 1)
  }
}
```

```js
User.query()
  .eager({
    commments: nestedReplies(3)
  })
```

**Comment by Aerlin** [comment]
Thank you koskimas. I was not aware of the object notation, it appears to be working. 

Another question though. How do I include a modifiers/filters into the object? Previously I was using `[user, replies(limitFilter)]`, with limitFilter modifier calling `builder.orderBy("createdAt").limit(3);` to limit replies to 3. I'm uncertain how to do that with a object notifier now.
