### ISSUE TITLE
Is there any way to ignore conflicts when using upsertGraph?

### ISSUE THREAD

**Issue by abhyuditjain** [Vincit/objection.js#1160]
I have unique constraints in a table that belongs to one. Is there any way to ignore conflicts and insert?

**Comment by koskimas** [comment]
Could you be more specific? An example would help.

**Comment by abhyuditjain** [comment]
Flight has many FlightSchedules. Flight schedules has a unique constraint on (flight_id, departue_time and arrival_time).

So if the flight graph is like:

```
{
    id: 1,
    flightSchedules: [
        {
            departureTime: "xyz",
            arrivalTime: "xyz",
            flightId: 1
        }
    ]
}
```

And if I try to insert the same graph again, it gives a conflict error, as I have a unique constraint on (flight_id, departure_time, arrival_time)

Docs suggest that if I supply `id` in the object to be inserted, then they will be updated, but that will be cumbersome as I'll have to fetch all the schedules and then merge them with new ones and then upsertGraph.

Is there any way to ignore conflict errors so that I don't have to fetch already existing schedules?

**Comment by koskimas** [comment]
Unfortunately there's no easy way to do that. You could be able to use [onError](https://vincit.github.io/objection.js/#onerror) combined with the `objection-db-errors` plugin's `UniqueViolationError`.
