### ISSUE TITLE
upsertGraphAndFetch doesn't work with modifyEager

### ISSUE THREAD

**Issue by austinthetaco** [Vincit/objection.js#1161]
I have 3 tables:
- User
• UID

- Photos 
• id
• key
• resource location

- users_photos (pivot table)
• UID
• photo id
• sort_index (extra integer that's been defined in the model)

The upsert'ing of the graph is working correctly, however i want to make sure the photos are sorted by `sort_index`. I'm not able to use `.modifyEager()` on the fetched data (it doesn't change the fetched results) and I don't see any info on how i would go about that. The only documentation on `upsertGraphAndFetch` is 

> Exactly like upsertGraph but also fetches the graph from the db after the upsert operation.

which doesn't really provide me the details on how to modify the results.

**Comment by koskimas** [comment]
modifyEager cannot be used with upsertGraphAndFetch.
