### ISSUE TITLE
Requesting update for objection@next

### ISSUE THREAD

**Issue by jyanyuk** [Vincit/objection.js#1163]
We're looking to make use of the row-level locking option for upsertGraph that was implemented in [a8992dc](https://github.com/Vincit/objection.js/commit/a8992dca4f1ed6a236f64aa5cc801e2ffc766cfe) (mentioned in #1127).

**Comment by koskimas** [comment]
I've released 1.5.0-rc.1. Note that it the `upsertGraph` was completely rewritten for it internally, so you can run into bugs. The `upsertGraph` test set is not perfect yet. Please let me know if you run into bugs in your `upsertGraph` code.
