### ISSUE TITLE
Not deleting associations (NxN) when empty array not provided at all

### ISSUE THREAD

**Issue by itfy** [Vincit/objection.js#1165]
Hello,

I would like to ask if this is expected behaviour.

I have NxN relation (join table: StudentCourseScheduleClass):

CourseScheduleClass - StudentCourseScheduleClass - Student

CourseScheduleClass.students is an array of Student objects.

If the object CourseScheduleClass has no member with name "students", then the relations are not deleted from the table StudentCourseScheduleClass  when I use upsertGraph function. If I provide empty array, then the relations are removed nicely.

I tried to specify relations also in option object for the upsertGraph function, but it did not help. 

Regards
Michal

**Comment by koskimas** [comment]
Yes, this is expected.
