### ISSUE TITLE
Setting jsonb property with default values

### ISSUE THREAD

**Issue by mashaalmemon** [Vincit/objection.js#1166]
Hi There,

I'm looking for assistance on best practices.

Lets assume I have a jsonb field called user_data.

That field in the database contains json with  the following properties:

```
{
"first_name": "bob",
"last_name": "smith"
}
```

I've decided that I'd like to have a "middle_name" field as well and I'd like there to be a default value for the new property:

```
{
"first_name": "bob",
"middle_name": "",
"last_name": "smith"
}
```

Is there a prescribed method by which:
* New fields created will always have the `"middle_name"` property, and if it's not set explicitly it is set to ""
* Existing fields created, when read, will be augmented with the `"middle_name"` property and set to ""

I searched past queries and couldn't find an appropriate answer but if there is one perhaps you can point me to it. I see the many functions for models prefixed with `$` but I'm not clear which one might be appropriate for my use case. Thanks in advance.

**Comment by koskimas** [comment]
If you use `jsonSchema` you could maybe use the builtin `default` property, but that may cause some unexpected issues when updating rows without providing a value for `middle_name`: it gets set the default value and any value in the database gets overwritten.

Another option is to set that value in `$beforeInsert`.
