### ISSUE TITLE
The execution order of the upsertGraph

### ISSUE THREAD

**Issue by almahdi-chihaoui** [Vincit/objection.js#1167]
Hi guys, I am trying to use upsertGraph() in our application and I've noticed that it execute insert request then the update, the problem here is we have a trigger that validate the data in the targeted table, in our case to make sure that some ranges don't overlap. So, when the input data contain a new object (to be inserted) that have a range that overlap with an old one , and another object that contain that old one but modified to avoid the overlap, the upsertGraph would fail in this case. So is there any way to change the order of operations made by the upsertGraph, and to execute update first?
Thanks.

**Comment by koskimas** [comment]
Unfortunately no. Maybe you shouldn't be using upsertGraph in this case?
