### ISSUE TITLE
$query().upsertGraph() uses old instance values

### ISSUE THREAD

**Issue by sarneeh** [Vincit/objection.js#1168]
The title actually says it all. Consider this example:

```js
const person = await Person.findById({ id: 1 });
// > console.log(person);
// > { id: 1, name: "John" }
await person.$query().upsertGraph({ id: 1, name: 'Steve' }).debug();
// > { method: 'update', bindings: ['John', 1], sql: 'update "persons" set "name" = ? where "persons"."id" = ?' }
```

As you can notice - the `upsertGraph` doesn't take the new model into consideration and it just uses the old one. Am I missing something?

**Comment by koskimas** [comment]
`upsertGraph` is only meaningful when used with `query()`. This issue is covered by https://github.com/Vincit/objection.js/issues/933

**Comment by sarneeh** [comment]
@koskimas Thanks for clarifying this up 😄
