### ISSUE TITLE
Question: a TS compatible way to use #id and #ref in graph insert/upsert

### ISSUE THREAD

**Issue by capaj** [Vincit/objection.js#1169]
we're writing our tests in typescript and it doesn't like `#ref` when doing graph upsert/insert.

![image](https://user-images.githubusercontent.com/1305378/49866345-c77ec400-fe07-11e8-828b-64e8e61297e9.png)

Does anyone know a way to solve this? Maybe I could define `#ref` on the class itself, but I am really unsure how that would work with private fields proposal when it gets to typescript. So I would prefer another solution.

**Comment by koskimas** [comment]
Dunno. I don't use typescript. The typings have been provided by the community. This probably isn't the best place to get an answer to this question. Pull requests are always welcome if you want to offer a way.
