### ISSUE TITLE
How to pre-validate changes made with `upsertGraph`

### ISSUE THREAD

**Issue by sarneeh** [Vincit/objection.js#1170]
Just a simple question, I don't think there's an example needed here.

So because `upsertGraph` doesn't work with instance `$query()` and I don't have the reference to the old instance in `$beforeUpdate` - do I just need to manually run validation logic just before running the `upsertGraph` method?

The only other way I can think of is to do things that `upsertGraph` does manually (mostly relating/unrelating and inserting missing entities) and at the end (updating root entity values) just call `patch`.

I would very appreciate any recommendations/thoughts on this topic.

**Comment by koskimas** [comment]
You could always override the `upserGraph` method and call your validators there.
