### ISSUE TITLE
no permission to install from github

### ISSUE THREAD

**Issue by terraswat** [Vincit/objection.js#1172]
$git clone git@github.com:Vincit/objection.js.git objection
Cloning into 'objection'...

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$

**Comment by koskimas** [comment]
You need to have an ssh key installed in github or alternatively use the `https` protocol. This has absolutely nothing to do with objection.
