### ISSUE TITLE
Throw if unknown properties are found in relation mappings

### ISSUE THREAD

**Issue by koskimas** [Vincit/objection.js#1179]
Typos seem to be a common mistake. Stuff like `extras` instead of `extra`.

**Comment by koskimas** [comment]
@sambP `extras` is the plural of `extra`, so no, nothing confusing there.

Many other props don't exist in the `relations` section. If I add all features there, the section becomes a wall of text no one reads. The `relations ` section is a simple introduction section to the most commonly used things.

You should always check the [API docs](http://vincit.github.io/objection.js/#relationmappings) for these things. There the `extra` property is clearly documentad.

**Comment by sambP** [comment]
You are right, I only wanted to describe why I thought it is extras and not extra...

**Comment by koskimas** [comment]
This didn't get included in 2.0. I'm closing this as it has been inactive. To anyone reading this: Feel free to open if you wish this to be added to 3.0.
