### ISSUE TITLE
Compiling ajv jsonSchema doesnt throw errors

### ISSUE THREAD

**Issue by adefrutoscasado** [Vincit/objection.js#1182]
Hi!, when using the following schema with an invalid type on 'date' property
```
  static get jsonSchema() {
    return {
      type: 'object',
      required: ['firstName', 'lastName'],

      properties: {
        id: { type: 'integer' },
        parentId: { type: ['integer', 'null'] },
        firstName: { type: 'string', minLength: 1, maxLength: 255 },
        lastName: { type: 'string', minLength: 1, maxLength: 255 },
        date: {type: 'unexisting-type'},
        age: { type: 'number' },
      }
    };
  }
```
No errors are returned, I get success even inserting an object like this:
```
{
    "firstName":"sample",
    "lastName":"sample",
    "date":"2018-12-21 10:20"
}

```
I tested in a minimal JSFiddle example and it does return an error at compile time (AJV v6.6.2) https://jsfiddle.net/ads80y5j/

Im testing Objection in a modified version of https://github.com/Vincit/objection.js/blob/master/examples/express-es6/models/Person.js

I have a big app with many models using 'date-time' as type and now I realice its not a valid type but I couldnt detect it :( 
So Im missing something?

**Comment by koskimas** [comment]
@adefrutoscasado It may be because of the options we pass to Ajv when we create it. You can override those options by overriding the [createValidator](http://vincit.github.io/objection.js/#custom-validation) method.

**Comment by adefrutoscasado** [comment]
I think wrong schemas can be a common mistake so throwing an error would make sense for me.

Thanks! And thanks for such an amazing ORM!

**Comment by koskimas** [comment]
Thanks! :heart: 

If you find a workaround until 2.0, could you post it here?

**Comment by adefrutoscasado** [comment]
Not sure if theres a better approach but extending the Objection Model using [Custom Validation](https://vincit.github.io/objection.js/#custom-validation) worked for me:

```
const {Model, AjvValidator} = require('objection')

class ValidatedModel extends Model {
  static createValidator() {
    return new AjvValidator({
      onCreateAjv: (ajv) => {
        // Here you can modify the `Ajv` instance.
      },
      options: {
        allErrors: true,
        validateSchema: true,
        ownProperties: true,
        v5: true
      }
    })
  }
}

module.exports = ValidatedModel
```
Then when creating your own models, extend from this custom ValidatedModel:

```
const ValidatedModel = require('./ValidatedObjection.js')

class Person extends ValidatedModel {

  static get jsonSchema() {
    return {
      type: 'object',
      properties: {
        id: {type: 'integer'},
        user_id: {type: ['integer', 'null'], default: null, maxLength: 11},
        user_agent: {type: ['string', 'null'], default: null, maxLength: 500},
        ip: {type: ['string', 'null'], default: null, maxLength: 255},
        fingerPrint: {type: ['integer', 'null'], default: null, maxLength: 20},
        date: {type: 'unexisting-type'},
      },
      additionalProperties: false
    }
  }
```
Then, invalid schema errors will be thrown at AJV compile time:
`schema is invalid: data.properties['date'].type should be equal to one of the allowed values`

**Comment by phormio** [comment]
In the `options` property that is passed to the `AjvValidator` constructor, I would suggest setting [`strictKeywords`](https://github.com/epoberezkin/ajv/tree/v6.10.0#strict-mode-options) to `true`.  Also, I prefer to set [`format`](https://github.com/epoberezkin/ajv/tree/v6.10.0#validation-and-reporting-options) to `full`.

**Comment by koskimas** [comment]
This didn't get into 2.0 unfortunately. Luckily you can always provide your own options for the validator by overriding it as shown above.
