### ISSUE TITLE
Suggestion: "locked" querybuilders

### ISSUE THREAD

**Issue by xanf** [Vincit/objection.js#1188]
Hi! Thank you for awesome library, it really saves me a lot :)

Last few days I was solving a complex task when my "model" is actually split accross two tables (better don't know why) and I was playing around querybuilder hooks, trying to "hook" additional eagers, selects, where here & there and observing results.

After reading execute - build - ... flow I soon discovered that it was sometimes too late to do some operations (query was already building and (for example) my eager expression was already parsed and covnerted to operations0.

What I suggest is (maybe private) API to "lock" query builder so it will throw on operations which will not have effect anymore at this point. Since executing query starts with cloning it will not affect normal usage but will dramatically save time for people, trying to hack something weird. I assume that may be different locks in effect:
- eager locks
- locks for certain type of `operations`
- etc.

I can build a prototype and PR for this, but I would like to hear your input on this

**Comment by koskimas** [comment]
Hi!

I think we need to add something like this for objection v2 that will have a new static model hook API. The query builder will be passed to the hooks, so people will start to call all kinds of methods for it in the hooks and these problems will become much more usual.

This could actually be one of the few cases where `Proxy` might be useful. I certainly don't want to add a bunch of lock related code all around the `QueryBuilder` class (and it's parent classes).

We could have locking helper like this

```js
const lockedBuilder = lock(builder, [
  'eager',
  'joinEager',
])
```

We should make as many method calls possible in the `before` hooks as we can though. I'll see what I come up with while working on the hooks.

**Comment by xanf** [comment]
Thank you, that makes sense
