### ISSUE TITLE
modify() method throws exception

### ISSUE THREAD

**Issue by ozum** [Vincit/objection.js#119]
Hi,

Knex has a `modify` method, which allows modification of query, in QueryBuilder. According to `objection` doc, `query()` method returns a QueryBuilder object, which has all methods of Knex Query Builder.

However, when I try to access `modify()` from objection.js it throws exception. As an example for an `Org` model:

`Org.query().modify(myFunction)`;
`TypeError: Org.query(...).modify is not a function`

From [Knex doc](http://knexjs.org/#Builder-modify):
```js
var withUserName = function(queryBuilder, foreignKey) {
  queryBuilder
    .leftJoin('users', foreignKey, 'users.id')
    .select('users.user_name');
};

knex
  .table('articles')
  .select('title', 'body')
  .modify(withUserName, 'articles_user.id')
  .then(function(article) {
    console.log(article.user_name);
  });
```

Best Regards,

**Comment by koskimas** [comment]
Hi,

thanks for bringing this up. I'll add the method asap.

**Comment by ozum** [comment]
Thank you for the fast response. I thought I can create a PR, but couldn't find how to add a method to objection's query builder.

Another related issue is I also cannot access other properties of query builder such as `client`. Although it is an internal method of query method, I use it to determine db engine as `.client.config.client`.

To cure root problem, is it possible to make objection's query builder fully compatible with knex' query builder?

**Comment by koskimas** [comment]
I don't think it's a good idea to try to duplicate the private undocumented features as they may change any time in the future. You can access the knex instance like this:

```
let queryBuilder = Org.query()...
queryBuilder.modelClass().knex().client.config.client
```

**Comment by ozum** [comment]
You are right, I can't insist on private attributes.

I created PR #120. If it is OK with you, could you please merge, I want to continue with official repository in my project.

Best Regards,
