### ISSUE TITLE
[Docs] Create query in two steps

### ISSUE THREAD

**Issue by LeDivinBueno** [Vincit/objection.js#1191]
Hi,

I have a question about making a query in two steps. This is working for me, but I want to be sure this is a legal thing to do. The idea is to prepare a query, edit it under some conditions, and execute it after.
```
// Only query available books
var books = Book
    .query()
    .where('available', '=', '1');

// If user want additionnal filter
if(userWantToFilterTitle) {
    // Filter by title
    books = books.where('title', '=', bookTitle);
}

// Call the query for real
books = await books;
```

If this is a legal thing, don't you think it should be in the documentation ?

Thanks for your work and time,

**Comment by kibertoad** [comment]
It is perfectly legal, but isn't that the whole purpose of fluent pattern? What happens when you call

```
    .query()
    .where('available', '=', '1');
```
is that each of these functions return you the same books instance, so it is entirely equivalent to

```
var books = Book.query();
books..where('available', '=', '1');
```

Note that 
```
books = books.where('title', '=', bookTitle);
```

is redundant, just `books.where('title', '=', bookTitle);` should be enough. Query building mutates query builder.

**Comment by LeDivinBueno** [comment]
Thanks for the fast answer.

What do you mean by "fluent pattern" ?

Ok, what I understand is that I can write this :

```
// Only query available books
// (No real optimisation here ?)
var books = Book.query();
books.where('available', '=', '1');

// If user want additionnal filter
if(userWantToFilterTitle) {
    // Filter by title
    // Faster here
    books.where('title', '=', bookTitle);
}

// Call the query for real
books = await books;
```

**Comment by kibertoad** [comment]
https://en.wikipedia.org/wiki/Fluent_interface
But in this case it is more of a classic builder - https://en.wikipedia.org/wiki/Builder_pattern

You can, but I would recommend against it, it is a bad practice to change variable to suddenly be of entirely different type, so `books = await books` is not a recommended approach. I would suggest something more along the lines of `const books = await builder`.

**Comment by koskimas** [comment]
As @kibertoad said, this

```js
x = x.foo().bar()
```

is exactly equivalent to

```js
x = x.foo()
x = x.bar()
```

no matter what `x`, `foo` and `bar` do. This is a very basic thing in the javascript language, and there should be no need to write this in the docs.

**Comment by koskimas** [comment]
What could be said in the docs is that all query builder methods mutate the query instead of returning a copy, so you don't even need to "propagate" the return value.

**Comment by LeDivinBueno** [comment]
You're right, but what I suggested to write in the docs was just a little exemple of "if you want to edit your query before sending it to the database, do this", in the "query exemples" section. Because you can't write something like
```
// Trigger warning : sh***y code juste to show the error
// Only query available books
var books = await Book
    .query()
    .where('available', '=', '1')
if(userWantToFilterTitle) {
    .where('title', '=', bookTitle);
}
    .where('price', '>', '42');
```
so you have to split it in multiple steps by using ```await``` later.

Thanks,
