### ISSUE TITLE
Left join in nested relation

### ISSUE THREAD

**Issue by abhyuditjain** [Vincit/objection.js#1192]
I have the following models:

https://gist.github.com/abhyuditjain/339feb34f892950fbc2e0f8459ea1a9a

I am trying to do an inner join and a left join on a nested relation but I am not able to perform this. The gist has the query.

How can I do this?

**Comment by koskimas** [comment]
You need to use the `leftJoin` method for the nested join. There's no way to combine different join types for different levels in `joinRelation`.

**Comment by koskimas** [comment]
https://knexjs.org/#Builder-leftJoin
