### ISSUE TITLE
model_a.relationMappings.model_b: join: relation name and join property 'model_a cannot have the same name. If you cannot change one or the other, you can use $parseDatabaseJson and $formatDatabaseJson methods to convert the column name.

### ISSUE THREAD

**Issue by chubu-xappia** [Vincit/objection.js#1193]
### **Model Etapa__c**
`
import { Model } from 'objection';
import path from 'path';

class  Etapa__c  extends  Model  {
    static tableName = 'Etapa__c';

    static get idColumn() {
          return 'Id';
      }
  
    static relationMappings = {   
        Concurso__c: {
            relation: Model.BelongsToOneRelation,
            modelClass: path.join(__dirname, '/Concurso__c'),
            join: {
                from: 'Etapa__c.Concurso__c',
                to: 'Concurso__c.Id'
            }
        }
     }
}

export default Etapa__c;`

### **Model Concurso__c**

`
class   Concurso__c   extends Model   {
    static  tableName ='Concurso__c';

    static get idColumn() {
        return 'Id';
    }
  
    static relationMappings = {
        Etapa__c: {
          relation: Model.HasManyRelation,
          modelClass: path.join(__dirname, '/Etapa__c'),
          join: {
            from: 'Concurso__c.Id',
            to: 'Etapa__c.Concurso__c_id'
          }
        }
      }
}

export default Concurso__c;
`

### **Error**
**When i'm gonna to insert  in my db--> `model.query().insert({object})` i'm getting this error:**

> Error: Etapa__c.relationMappings.Concurso__c: join: relation name and join property 'Concurso__c' cannot have the same name. If you cannot change one or the other, you can use $parseDatabaseJson and $formatDatabaseJson methods to convert the column name.

**NOTE****  I can't rename the table names and the table fields.

**Comment by koskimas** [comment]
The error says it all.
