### ISSUE TITLE
#dbRef not working when relation manytomany and id is a string

### ISSUE THREAD

**Issue by joneldiablo** [Vincit/objection.js#1194]
I'm trying to insert a row with a relation many to many but the object related already exist, 
I have this error:
`ValidationError: agreements[0].agreement_layout_id: is a required property\n    at Function.createValidationError`
so, objectionjs is trying to create a new row instead only make the relation,
```js
let user = {
      '#id': 'user',
      firstname: data.firstname,
      lastname: data.lastname,
      name: fullName(),
      emailid: data.email,
      password: cryptionService.password(data, 10),
      type: [{
        '#dbRef': data.code
      }]
    }
```

**Comment by koskimas** [comment]
You have specified `agreement_layout_id` as a required property in your jsonSchema.

**Comment by koskimas** [comment]
Hmm.. Actually, objection should probably validate those `#dbRef` instances the same way `patch` is validated and ignore required properties.

**Comment by joneldiablo** [comment]
you are fast, thanks!
emmm 
yes, I have that specification, but I won't create new row of 'type' also I wont modify just create the relation

**Comment by koskimas** [comment]
Yeah, I think there's room for improvement here on objection's side. I'll write a test to make sure I know what's going on and get back to you.

**Comment by koskimas** [comment]
Just to make sure, `data.code` contains a value of the primary key of `type` model?

**Comment by joneldiablo** [comment]
yes

**Comment by koskimas** [comment]
Could you try to install `npm install objection@next` to see if the problem still remains?

**Comment by joneldiablo** [comment]
it works

**Comment by koskimas** [comment]
Awesome. I'll still write a test case to that this doesn't break later. 1.5 is just around the corner. In the meanwhile, you should be able to use the current RC version thorough objection@next. All tests always work for the `next` versions too, so it's usually really stable. Let me know if there are some other bugs with the `next` version. I rewrote the insert/upsertGraph code from scratch.

**Comment by joneldiablo** [comment]
Hi! its me again, sorry. I have this problem now: 

```
{
...
      type: {
        '#id': 'userTypeRel',
        '#dbRef': (data.code || data.type)
      },
      agreements: [{
        '#id': 'agreement',
        body: agreementBody,
        path: md5(JSON.stringify(agreementBody)) + '.pdf',
        agreement_layout_id: 1//'#ref{userTypeRel.agreement_layout_id}'
      }],
...
}
```
using knex.on('query') I can see that the "type" relation is doing after the "agreements" relation, so if I try to use '#ref{userTypeRel.agreement_layout_id}' instead of the hardcoded 1, the query throws the required error because agreement_layout_id its required, so '#id': 'userTypeRel' not exist at these moment, how can I order the query?
