### ISSUE TITLE
Mixing eager algorithms in a single query

### ISSUE THREAD

**Issue by jacobpgn** [Vincit/objection.js#1199]
Hey there! Thanks for Objection 😄 

As a feature request, it could be great to use multiple eager algorithms in a query in order to handle a number of joins in the fewest possible queries while preserving result limits.

The goal is to apply `JoinEagerAlgorithm` to `BelongsToOne`/`HasOne` associations, and `WhereInEagerAlgorithm` to my `HasMany` relations.

As a simple example, with the relations:
1. `User` 1 - 1 `Package`
2. `User` 1 - 1 `Contract`
3. `User` 1 - 1 `UserSettings`
4. `User` 1 - n `Widgets`

it'd help me greatly to do something like:
```js
User.query()
    .mergeJoinEager("[package, contract, userSettings]")
    .mergeEager("[widgets]");
```

and issue 2 queries to the database as opposed to 5 with the default `WhereInEagerAlgorithm` or losing the ability to `limit` if using `JoinEagerAlgorithm` for a single query (in my real-world case this'd actually be 6 queries instead of 18 – a meaningful impact on performance!)

Apologies if this is already possible and I've somehow missed it! Have a great weekend :v:

**Comment by koskimas** [comment]
There's no way to do that like you suggested, but this performs the same amount of queries:

```js
const users = await User.query()
    .mergeJoinEager("[package, contract, userSettings]")

await User.loadRelated(users, 'widgets')
```
