### ISSUE TITLE
possible relation upsertGraph bug as of 1.5.0

### ISSUE THREAD

**Issue by tuurbo** [Vincit/objection.js#1201]
1.4.0 would include cart_id key automatically
1.5.0 doesnt

```
const userCart = await Cart.query()
    .where('user_id', 10)
    .eager('items')
    .first();

await userCart
    .$relatedQuery('items')
    .upsertGraph([{
        // cart_id: 1 <--- set automatically by objection in 1.4.0
        product_id: 100,
        quantity: 2,
    }]);
```

```
export default class Cart extends BaseModel {
    static tableName = 'cart';

    id: number;
    user_id: number;
    items: CartItem[];

    static relationMappings = (): RelationMappings => ({
        items: {
            relation: Model.HasManyRelation,
            modelClass: CartItem,
            join: {
                from: 'cart.id',
                to: 'cart_item.cart_id',
            },
        },
    })
}

export default class CartItem extends BaseModel {
    static tableName = 'cart_item';

    id: number;
    cart_id: number;
    product_id: number;
    quantity: number;
}

```

**Comment by koskimas** [comment]
`upsertGraph` is not supposed to work like that. If it did work previously, it was a bug/accidental feature. There's [this issue](https://github.com/Vincit/objection.js/issues/933) that will cause this scenario to throw in the future.

**Comment by tuurbo** [comment]
Ok thanks for quick reply

**Comment by capaj** [comment]
@koskimas it would be nice to highlight this in the docs for upsertGraph. I was always under the impression it's similar to how inserts work as demonstrated in the docs:
![image](https://user-images.githubusercontent.com/1305378/51572850-3e978580-1ea7-11e9-8f65-4feddff793a4.png)

**Comment by koskimas** [comment]
That's what this issue is for https://github.com/Vincit/objection.js/issues/933

**Comment by capaj** [comment]
that might explain a bug or two actually :pensive:
