### ISSUE TITLE
Subqueries break upgrading from 1.4.0 to 1.5.3

### ISSUE THREAD

**Issue by nazar** [Vincit/objection.js#1205]
Greetings,

Subqueries using `.with` are no longer working as expected when I upgrade from `1.4.0` to `1.5.3`.

```javascript
  return Model
    .query()
    .with(
      'pager_subquery',
      query
    )
    .count()
    .from('pager_subquery')
    .first();
```

The above code takes a `query`, which is an objection model `.query()` and uses it to construct a subquery using `.with` to return a basic row count.

Under `1.4.0`, the following correct SQL is generated:

```sql
with "pager_subquery" as (select "posts".* from "posts" where "posts"."postable_id" in ($1) and "postable_type" = $2 and "posts"."deleted_at" is null order by "stats"#>'{scores,low}' desc) select count(*) from "pager_subquery"
```

Under `1.5.3`, the following incorrect SQL is generated:

```
with "pager_subquery" as (select "pager_subquery".* from "pager_subquery" where "pager_subquery"."postable_id" in ($1) and "postable_type" = $2 and "posts"."deleted_at" is null order by "stats"#>'{scores,low}' desc) select count(*) from "pager_subquery"
```

It appears that under `1.5.3`, the original `query` object loses its model `tablename` and/or is overridden by the `.from('pager_subquery')` method call.

I had a look through the change log and couldn't find anything that indicates that this behaviour has changed.

Is this a bug or has Objection changed this behaviour? If the latter, any hints or clues would appreciated.

Libraries:

* knex: `0.16.3`
* pg: `7.8.0`
* db: Postgres 10.5

**Comment by koskimas** [comment]
This i probably a bug in objection. I'm on vacation for three weeks. I'll look into this after I'm back

**Comment by nazar** [comment]
Thank you for this @koskimas! And super thanks for objection.js - words cannot describe how much I ❤️it and how pleasurable it is to use.

**Comment by koskimas** [comment]
objection 1.6 is now released with a fix for this issue.
