### ISSUE TITLE
fullOuterJoinRelation broken after V1.5.3 upgrade

### ISSUE THREAD

**Issue by mayerlench** [Vincit/objection.js#1206]
**Error**
After upgrading from 1.3 to 1.5.3 my fullOuterJoinRelation started to give an error of "e { error: syntax error at or near "outer" 

**The SQL Output using .toSql()**
I decided to output the sql for both 1.3 and 1.5.3 and below are the differences in syntax output
**V1.3** - full outer join "item" as "child" on "child"."_parentId" = "item"."id" where "item"."_parentId"
**V1.5.3** - outer join "children" as"child" where "item"."_parentId"

It seems that the 1.5.3 broke the fullOuterJoinRelation function as its not actually joining and is missing the "full" keyword which is required (outer keyword is optional)

**Comment by koskimas** [comment]
This i probably a bug in objection. I'm on vacation for three weeks. I'll look into this after I'm back.

**Comment by koskimas** [comment]
@mayerlench I released 1.6.0-rc.1. You can install it using `npm install objection@next`. Could you try it out to see if your issues are now resolved?

**Comment by koskimas** [comment]
objection 1.6 is now released with a fix for this issue.
