### ISSUE TITLE
What is the recommended way to calculate hasNextPage?

### ISSUE THREAD

**Issue by booboothefool** [Vincit/objection.js#1208]
I am having trouble making sense of the result lengths that come back to calculate whether there is another page to fetch (for infinite scrolling).

```
const res = await Chat.query()
  .joinEager('[chatPersona, persona.[avatar, photo], lastMessage]')
  .where('chatPersona.persona_id', personaId)
  .orderBy('lastMessage.created_at', 'DESC')
  .page(page, pageSize);
```

For example passing in:
```
page = 1
pageSize = 300
```
will return something like:
```
res.results.length = 27
res.total = 1598
```
I tried this but it's not correct in some cases:
```
hasNextPage = (page + 1) * pageSize < res.total
```

**Comment by booboothefool** [comment]
I think I figured it out... seems like the `persona.photo` was included to count all of the photos in the total. Once I removed that eager join, it brought the total from 1598 down to a more accurate 399, which I could accurately calculate hasNextPage against.

**Comment by koskimas** [comment]
Paging doesn't really work with joinEager because of the way SQL joins work. Try to execute the generated sql for example using psql and youll see how the result dataset is the cartesian product of all the joined datasets.
