### ISSUE TITLE
Allow to specify two alternative columns in to section of HasManyRelation

### ISSUE THREAD

**Issue by jakubgs** [Vincit/objection.js#1209]
I see no option of how to specify a 1-2 relation when one of the tables contains two keys from another table.
Schema:
![filediffs](https://user-images.githubusercontent.com/2212681/51804592-4ff3df80-2263-11e9-924f-630dac253964.png)
```sql
CREATE TABLE files (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  name       VARCHAR(255) NOT NULL,
  url        VARCHAR(255) NOT NULL,
);

CREATE TABLE IF NOT EXISTS diffs (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  status     VARCHAR(20),
  eastFileId INTEGER REFERENCES builds(id),
  westFileId INTEGER REFERENCES builds(id)
);
```
How would I create such a relation in Objection.js? As far as I can tell there is no easy way of doing this.

I tried doing something like this:
```javascript
class File extends Model {
    static get relationMappings() {
    return {
      diffs: {
        relation: Model.HasManyRelation,
        modelClass: 'Diff',
        join: {
          from: 'files.id',
          to: ['diffs.eastFileId', 'diffs.westFileId'],
        },
      },
    }
  }
}
```
But it does not work as intended.

**Comment by koskimas** [comment]
Unfortunately that's not possible and would be difficult to add.
