### ISSUE TITLE
joinRelation method without alias

### ISSUE THREAD

**Issue by ozum** [Vincit/objection.js#121]
Hi,

I need help to create a join sql query using only relation name just like `joinRelation` method in 0.5.0, but without aliasing table name. How can I do that?

I used other alternatives, but:
* Eager methods embeds related data in parent data.
* joinRelation (0.5.0) adds alias.
* innerJoin needs join details, which is already defined in relation mappings.

Is there a method already available, which I miss? If not, how about adding an option object to `joinRelation`

```js
{
    // true: adds alias,
    // false: uses original table name
    // string: uses given custom alias.
    alias: true, 
}
```

**Comment by koskimas** [comment]
There is no method available for this. Your suggestion is good! Let's do that.

**Comment by ozum** [comment]
That's great. Thanks.
