### ISSUE TITLE
How to insert based on lookup table non-integer id value?

### ISSUE THREAD

**Issue by booboothefool** [Vincit/objection.js#1212]
```
person
---
id(pk) name

person_pets
---
id(pk) person_id(fk) pet_type_id(fk)

pet
---
id(pk) type
---
1 DOG
2 CAT
...
```

```
insertGraph([{
    name: 'John'
    pets: [{ id: 1 }],
}])
```
works great

But is there a way I can insert:
```
insertGraph([{
    name: 'John'
    pets: [{ type: 'DOG' }],
}])
```

Where 'DOG' will be transformed and inserted with the proper key 'DOG' => 1?

```
person
---
id(pk) name
---
1 John

person_pets
---
id(pk) person_id(fk) pet_type_id(fk)
---
1 1 1
```

Reason being is when the insertion happens it only knows about the type, so was wondering if I could link them on the fly and insert with that human-readable value. Or would I have to just do another await to look up and map types => ids prior to inserting?

**Comment by ntraylor1985** [comment]
I am looking for a solution to this as well, if there is a way to achieve this I think it could be very useful.

**Comment by koskimas** [comment]
Why don't you simply make the `type` the primary key since it seems to be an unique string? If you do that (and define it using `idColumn` for `pet`) everything works the way you want automatically.

If you really need to have both `id` and `type`, you could maybe implement the `$formatDatabaseJson` method for `Pet` model to make the conversion in javascript:

```js
const typeToId = {
  DOG: 1,
  CAT: 2
}

class Pet extends Model {
  $formatDatabaseJson(json) {
    json =  super.$formaDatabaseJson(json)

    if (json.type) {
      json.id = typeToId[json.type]
    }

    return json
  }
}
```

**Comment by koskimas** [comment]
If you don't want to hardcode the `typeToId` map in code, you can probably use a subquery:

```js
class Pet extends Model {
  $formatDatabaseJson(json) {
    json =  super.$formaDatabaseJson(json)

    if (json.type) {
      // NOTE: Don't add `await` here. This get's compiled into the SQL as a subquery and is
      // executed as a part of the update/insert query (basically no overhead)l
      json.id = Pet.query().select('id').where('type', json.type')
    }

    return json
  }
}
```

**Comment by booboothefool** [comment]
@koskimas Thanks, both of those solutions work well!

Kind of unrelated, but as a newbie I read it's a good rule of thumb to have those auto-incrementing integer ids as primary keys. I have a ton of lookup tables that look like (id[pk], type) like that. And yes, in all cases, type is a unique string. Would you tend to just go with (type[pk])?
