### ISSUE TITLE
joinRelation not joining on patch

### ISSUE THREAD

**Issue by mayerlench** [Vincit/objection.js#1213]
V1.5.3

joinRelation is not joining when trying to patch a model.
This may be related to [Issue 1206](https://github.com/Vincit/objection.js/issues/1206) which i opened.
Just wanted to keep you posted in case its not

I used a joinRelation('car') on a carDetail model so that i can update carDetail only for a specific car.personId.  

Below is the SQL i logged. As you can see it didnt join but performs a WHERE on what it thinks it joined

`UPDATE "carDetail" SET "color" = 'Red' WHERE "car"."personId" = 5`

**Comment by devinivy** [comment]
You should be able to use a subquery to get a similar effect.

**Comment by koskimas** [comment]
@mayerlench You can use `relatedQuery` as a sub query like this:

```js
CarDetail.query().patch({color: 'RED'}).whereExists(
  CarDetail.relatedQuery('car').where('personId', 1235)
)
```

**Comment by ne0c0de** [comment]
Actually update in a single query is possible in native postgresql as you can see from:

http://www.postgresqltutorial.com/postgresql-update-join/

Also it's possible on normal SQL too: https://www.javatpoint.com/sql-update-with-join

is there a way to do it on objectionjs without a subquery?

**Comment by maxkoryukov** [comment]
It should be **opened**, right?

**Comment by ianwalter** [comment]
I've run into this again after a while. I think it's not intuitive for developers to think of writing a subquery even if the query optimizer optimizes it correctly. This has led to developers on my team dropping down to raw SQL and not using the model relationships which is a shame because I think that using the relationships makes the code much more readable.

**Comment by rcrogers** [comment]
@mayerlench This report should not be closed

**Comment by atomdmac** [comment]
I'm currently using version 2.1.2 and seeing this issue.  If I use `.select()` as the main "action" then the query works as expected.  If I change `.select()` to `patch`, I get this error:

```
ERROR:  missing FROM-clause entry for table "Parent" at character 120
```

Code:
```javascript
class Child extends Model {
  static get tableName() {
    return 'Child';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: ['name'],
      properties: {
        id: { type: 'integer' },
        name: { type: 'string' },
        parentId: { type: 'integer' },
      },
    };
  }

  static get relationMappings() {
    const Parent = require('./Parent');

    return {
      Parent: {
        relation: Model.HasOneRelation,
        modelClass: Catalog,
        join: {
          from: 'Child.catalogId',
          to: 'Parent.id',
        },
      },
    };
  }
}

class Parent extends Model {
  static get tableName() {
    return 'Parent';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: ['name'],
      properties: {
        id: { type: 'integer' },
      },
    };
  }

  static get relationMappings() {
    return {
      children: {
        relation: Model.HasManyRelation,
        modelClass: Child,
        join: {
          to: 'Parent.id',
          from: 'Child.parentId',
        },
      },
    };
  }
}

const itemsAffected = await CatalogItem.query()
    .patch({ name: 'A New Name' })
    .withGraphJoined('Parent')
    .where({
      'Child.id': 1,
      'Parent.id': 1,
    });
```

**Comment by koskimas** [comment]
Join is not supported for update and delete on postures. What the link above describes is achieves the same result, but it's not a join. Any of the join methods should only add joins (SQL that has a join keyword in it) and definitely shouldn't produce an `update set from` query.

**Comment by atomdmac** [comment]
@koskimas Ah, my mistake.  Re-reading the thread, it looks like there isn't a way to create an `update set from` query in `Objection.js`.  I just tried out the sub-query form that you suggested, though, and it seems to work fine.  Sorry for the confusion.

**Comment by koskimas** [comment]
Yep, knex doesn't support `update set from` and therefore neither does objection. It would be a good addition though, but it needs to be added to knex first unfortunately.

**Comment by awais-shafiq** [comment]
Any solution to this yet?
