### ISSUE TITLE
How to filter results by multiple relation values?

### ISSUE THREAD

**Issue by Aerlin** [Vincit/objection.js#1218]
Objection version 1.5.3.

I have a project with Article and Article_Tag models. 

```
class Article extends Model {
	static get relationMappings() {
		tags: {
			relation: Model.HasManyRelation,
			modelClass: require("./Article_Tag"),
			join: {
				from: 'articles.id',
				to: 'article_tags.article_id'
			}
		}
	}
}
```

Example of query
```
const Article = require('../models/Article.js')(app);
Article.query()
.joinRelation('[tags]')
.eager('[tags]')
.then(function(results) {
	console.log("results: " + JSON.stringify( results , null, "\t"));
});

Results: [
	{
		"id": 1,
		"tags": [
			{
					"id": 1,
					"article_id": 1,
					"tag": "news"
			}
		]
	},
	{
		"id": 2,
		"tags": [
			{
					"id": 2,
					"article_id": 2,
					"tag": "news"
			},
			{
					"id": 3,
					"article_id": 2,
					"tag": "weather"
			}
		]
	},
	{
		"id": 3,
		"tags": [
			{
					"id": 4,
					"article_id": 3,
					"tag": "weather"
			}
		]
	}
]
```

I can retrieve articles of a single tag (`.where("tags.tag", "news")`), but if I query multiple tags (`.where("tags.tag", "news").andWhere('tags.tag', "weather")`) I get no results.  
I tried `.whereIn("tags.tag", ["news", "weather"])` but it returned articles with either tag instead of both.

How can I build a query to filter articles matching multiple tags?

**Comment by koskimas** [comment]
You can use `joinEager` instead of `joinRelation` + `eager`

**Comment by Aerlin** [comment]
Good tip

**Comment by koskimas** [comment]
Great!

**Comment by Aerlin** [comment]
@koskimas So is it possible to filter results by multiple relation values then? Because joinEager didn't help at all.

**Comment by koskimas** [comment]
Oh, that wasn't the goal. Ok, then I have no Idea what you mean. Could you copy paste the wanted result here?
