### ISSUE TITLE
Clean query state

### ISSUE THREAD

**Issue by xyluet** [Vincit/objection.js#1219]
I found a strange like below 

```js
const query = Model.query();

(async () => {
  await query.where({ id: 1 });
  console.log(await query.where({ id: 2 }));
})();
```

# expected
will generate `select * from table where id = 2`

# actual
last state generate `select * from table where id = 1 and id = 2`

Is there any way to get clean query state?

**Comment by devinivy** [comment]
Here's a decent way to achieve this,
```js
const query = Model.query();

(async () => {
  await query.clone().where({ id: 1 });
  console.log(await query.clone().where({ id: 2 }));
})();
```

**Comment by xyluet** [comment]
Thank you. This is what I'm looking for.

closed by https://vincit.github.io/objection.js/#clone
