### ISSUE TITLE
eager queries for BelongsToOne and HasOne

### ISSUE THREAD

**Issue by ozum** [Vincit/objection.js#122]
Hi,

objection.js executes more than one query for `BelongsToOne` and `HasOne` relations. Those types of relations are guaranteed to relate one record to only one record in other table.

IMHO executing a single `join` sql query for those would perform better for following reasons:

* Single query instead of multiple queries.
* For large query results `in` performs poorly compared to join. (Assume 10.000 rows.)
* They perform similar for small query results.

`SELECT * FROM "user"`
`SELECT * FROM "organization" WHERE "organization"."id" IN (?, ?, .... 10.000 times ... , ?)`

Please consider joins for `BelongsToOne` and `HasOne` relations.

Best Regards,

**Comment by koskimas** [comment]
This has been discussed in multiple issues before and it isn't as simple as this. I agree with what you are saying, but using joins would be a real pain in the ass for reasons I have yet found time to write about in issue #73. The explanation would be a 1000 word essay :D. Believe me, I have considered this. 

This could be doable if we only used joins for one-to-one relations, as you suggest, but it would still cause other problems. For example, consider how `filterEager` method should be implemented if we used joins? Anyways let's continue this discussion in #73.
