### ISSUE TITLE
Automatically add "id".Must appear in the GROUP BY clause or be used in an aggregate function.

### ISSUE THREAD

**Issue by DenWebDeveloper** [Vincit/objection.js#1220]
Error:  tests.id must appear in the GROUP BY clause or be used in an aggregate function
```javascript
NetworkEnterprise
    .query()
    .eager('enterprise.tests.questions')
    .modifyEager('enterprise.tests', builder => {
        builder.count().groupBy('enterprise_id')
    })
```
Debug mode displays:
```javascript
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 3, 4 ],
  __knexQueryUid: 'fef46671-55e5-4497-b6fb-c8ec74748d56',
  sql:
   'select "tests"."enterprise_id", count(*), "tests"."id" from "tests" where "tests"."enterprise_id" in (?, ?) group by "enterprise_id"' }
```
If you excute native SQL `select "tests"."enterprise_id", count(*)  from "tests" where "tests"."enterprise_id" in (?, ?) group by "enterprise_id"` without "tests"."id" then everything works  good
How to make the objection.js do not  automatically add "tests"."id"? Because it causes an error. I tried `builder.select(raw('enterprise_id')).count().groupBy('enterprise_id')` but it did not help

**Comment by koskimas** [comment]
The id must be selected or the eagering is impossible. You cannot do what you're trying here unfortunately.

**Comment by mir1198yusuf** [comment]
@koskimas  i am facing this issue in `leftJoinRelated`, automatically id column of joined table is added causing issue with group by, same error as in issue title
