### ISSUE TITLE
user.$relatedQuery('children').insert(obj) fails but [obj] works

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#1221]
Hi,
https://github.com/pageboard/server/commit/365d948e79825868e0c0438854b868c2e2d7d488
makes me wonder what am i doing wrong, or is this even a bug.

using objection@1.6 but that was happening with 1.5 too.

**Comment by koskimas** [comment]
Could you try to reproduce that? I have no idea what could be causing something like that.

**Comment by kapouer** [comment]
Flu causes that.

**Comment by kapouer** [comment]
Funny, cause it was an avatar of #891: the parent_id was missing and it failed silently.
