### ISSUE TITLE
UpsertGraph api clarification

### ISSUE THREAD

**Issue by joziahg** [Vincit/objection.js#1222]
Hey all having an issue with the GraphUpsert method, It is inserting the card correctly and inserting one user relation, however it doesnt give that relation an Id and thus it cannot insert subsequent or multiple user relations. I think I will have to use the '#ref' feature but the documentation isn't entirely clear on how that works. Additionally, my models automatically generate timestamps and uuids before the insert, so that's why you don't see an id in the insert method. Wonder if we could specify models for map tables in the graph insert/upsert methods. Any thoughts welcome.

`const users = args.users.map(cardUser => ({ id: cardUser }))`

users array looks like [...userId]

`const newProjectCard = await ProjectEvidenceCard.query().upsertGraphAndFetch({ cardAction: args.cardAction, users }, { relate: true, insertMissing: true })`

**Comment by koskimas** [comment]
Sorry, but I don't know what you mean by "not giving an id" and" or "inserting subsequent or multiple user relations". You need to provide a working example that I can  run if you want me to help you with this one. `upsertGraph` is super complex, and without knowing exactly what you mean, I'll just end up giving wrong advice.

Do you really need to use upsertGraph at all though? If you end up giving the same amount of options as data, it may not be the right tool for the job :smile:

**Comment by joziahg** [comment]
Sure thing. It may very well be the case that graphUpsert isnt the right option, I also looked at graphInsert.

These are the arguments:
`{ projectId: '685985b0-f3f7-11e8-8eb2-f2801f1b9fd1',
  schoolId: '64c695de-f3f5-11e8-8eb2-f2801f1b9fd1',
  cardAction: 'asdfsafdasdf',
  timeBox: 'asdfsdf',
  cardColor: '#795548',
  users:
   [ 'f0aaa72e-f3f6-11e8-8eb2-f2801f1b9fd1',
     'f0aaa49a-f3f6-11e8-8eb2-f2801f1b9fd1',
     'f0aaa878-f3f6-11e8-8eb2-f2801f1b9fd1' ] }`

The method creates a row in the ProjectEvidenceCard Table, this is correct,
`id: '3fa3c960-3474-11e9-853b-ef3b7db5e80f', created_at: '2019-02-19 18:29:10', updated_at: NULL, project_id: '685985b0-f3f7-11e8-8eb2-f2801f1b9fd1', school_id: '64c695de-f3f5-11e8-8eb2-f2801f1b9fd1', card_action: 'asdfsafdasdf', timebox: 'asdfsdf', card_color: '#795548', position_vertical: NULL, position_horizontal: '0', notes: NULL, archive: '0'
`

Then creates a single row in the ProjectEvidenceCardUserMap table, notice the id is an empty string,
`id: '', created_at: NULL, updated_at: NULL, card_id: '3fa3c960-3474-11e9-853b-ef3b7db5e80f', user_id: 'f0aaa72e-f3f6-11e8-8eb2-f2801f1b9fd1'
`

When I pass multiple userIds it will throw a duplicate primary key error, as the id on the first row inserted is an empty string. I think it is functioning properly, the only problem being it doesn't generate an Id for the id column on the map table.

Full graphql resolver file: 
```
const isAuthenticatedResolver = require('../../../core/authenticationResolver')
const { createError } = require('apollo-errors')
const ProjectEvidenceCard = require('../../../../../models/ProjectEvidenceCard')

const BlankName = createError('BlankName', {
  message: 'A new card has to have a name. Cmon shawn you know this.'
})

const createProjectCard = isAuthenticatedResolver.createResolver(
  async (root, args, { user }, info) => {
    // TODO calculate how many cards in in the list and add this card accordingly
    if (args.cardName === '') throw new BlankName()
    const users = await args.users.map(cardUser => ({ id: cardUser }))
    const newProjectCard = await ProjectEvidenceCard.query().upsertGraphAndFetch({ cardAction: args.cardAction, timeBox: args.timeBox, projectId: args.projectId, schoolId: args.schoolId, notes: args.notes, positionHorizontal: 0, positionVertical: args.positionVertical, cardColor: args.cardColor, archive: false, users }, { relate: true, insertMissing: true })
    return newProjectCard
  }
)

module.exports = createProjectCard
```

BaseModel: 
```
const { Model, snakeCaseMappers } = require('objection')
const uuidv1 = require('uuid/v1')

class BaseModel extends Model {
  static get columnNameMappers () {
    return snakeCaseMappers()
  }

  $beforeInsert () {
    this.created_at = new Date().toISOString().slice(0, 19).replace('T', ' ')
    this.id = uuidv1()
  }

  $beforeUpdate () {
    this.updated_at = new Date().toISOString().slice(0, 19).replace('T', ' ')
  }
}

module.exports = { BaseModel }
```

ProjectEvidenceCard model:
```
const { BaseModel } = require('./BaseModel')

class ProjectEvidenceCard extends BaseModel {
  static get tableName () {
    return 'project_evidence_cards'
  }

  static get relationMappings () {
    const School = require('./School')
    const Project = require('./Project')
    const User = require('./User')
    return {
      school: {
        relation: BaseModel.BelongsToOneRelation,
        modelClass: School,
        join: {
          from: 'project_evidence_cards.school_id',
          to: 'schools.id'
        }
      },
      project: {
        relation: BaseModel.BelongsToOneRelation,
        modelClass: Project,
        join: {
          from: 'project_evidence_cards.project_id',
          to: 'projects.id'
        }
      },
      users: {
        relation: BaseModel.ManyToManyRelation,
        modelClass: User,
        join: {
          from: 'project_evidence_cards.id',
          through: {
            from: 'project_evidence_cards_users_map.card_id',
            to: 'project_evidence_cards_users_map.user_id'
          },
          to: 'users.id'
        }
      }
    }
  }
}

module.exports = ProjectEvidenceCard
```

**Comment by koskimas** [comment]
I cannot run that :wink:

**Comment by joziahg** [comment]
Alrighty, lets try this again haha. Data structure has been simplified for brevity.
Assuming this db structure:
```
exports.up = async function (knex, Promise) {
  await knex.schema.createTable('users', function (table) {
    table.uuid('id').notNullable().primary()
    table.timestamps()
    table.string('name').notNullable()
  })
  await knex.schema.createTable('project_evidence_cards', function (table) {
    table.uuid('id').notNullable().primary()
    table.timestamps()
    table.string('card_action')
    table.string('time_box')
  })
  await knex.schema.createTable('project_evidence_cards_users_map', function (table) { // map table to hold which users are on which cards. users can be on multiple cards, cards can have multiple users
    table.uuid('id').notNullable().primary()
    table.timestamps()
    table.uuid('card_id').notNullable()
    table.foreign('card_id').references('id').inTable('project_evidence_cards')
    table.uuid('user_id').notNullable()
    table.foreign('user_id').references('id').inTable('users')
  })
}

exports.down = async function (knex, Promise) {
  await knex.schema.dropTableIfExists('users')
  await knex.schema.dropTableIfExists('project_evidence_cards')
  await knex.schema.dropTableIfExists('project_evidence_cards_users_map')
}
```
These users already exist:
```
  users: [{
    id: 'f8b375ac-35f2-11e9-b210-d663bd873d93',
    name: 'Someone'
  }, {
    id: '69cd3ec4-35f0-11e9-b210-d663bd873d93',
    name: 'Someone Else'
  }]

```
I want to insert a new card and relate the existing users to that card:
```
ProjectEvidenceCard
.query()
.upsertGraphAndFetch({
id: 'f8b37a20-35f2-11e9-b210-d663bd873d93', 
cardAction: 'Do the thing', 
timeBox: '40 minutes', 
archive: false, 
users: [ { id: 'f8b375ac-35f2-11e9-b210-d663bd873d93' }, { id: 'f8b378a4-35f2-11e9-b210-d663bd873d93' } ] 
}, { relate: true, insertMissing: true })
```
When I run the above upsertGraph, it first inserts the card, second inserts one user-card relation in the map table, and finally throws a duplicate Primary Key error on the map table. This is due to the inserted row on the map table not having a Primary Key. E.g:
```
id: '', created_at: NULL, updated_at: NULL, card_id: 'f8b37a20-35f2-11e9-b210-d663bd873d93', user_id: 'f8b375ac-35f2-11e9-b210-d663bd873d93'
```
If I pass in a single userId the insert doesn't throw a duplicate Primary key error on the map table because it only inserts one row, even though that row is missing a Primary key id.
My end goal and the problem I am facing, is to have a proper primary key generated when a row is inserted into the map table via upsertGraph. Hopefully I explained the problem a bit better, I am probably using the wrong method to begin with haha, if so hopefully you can point me in the write direction.

**Comment by koskimas** [comment]
I'm sorry, I should have been more clear. I need to be able to run your code using a command like `node your-reproduction.js`

I started to write such a file based the stuff you posted, and after spending 15 minutes on this, I noticed that you haven't provided most of the models needed to create the reproduction.

I'm not trying to be rude or nitpicky. This is my spare time I'm using to help you and I'm not ready to spend hours of it. So please provide an example I can actually debug. You can use the `reproduction-template.js` file in objection repo root as a starting point.

**Comment by koskimas** [comment]
Since I already wrote most of it, it would be enough if you provide the missing models (Project, User, School (maybe)) and other missing things that are referenced.

**Comment by joziahg** [comment]
No worries, this is my first issue ever so I am not terribly experienced, and I appreciate your patience. You might put a reference to the reproduction-template on the docs in the issues section, because I did not know it existed. I wrote up a quick gist; https://gist.github.com/joziahg/153d7c08ff0ab8054095e4a204fa23c7

**Comment by koskimas** [comment]
Thanks for the gist!

It fails because you have added an `uuid` primary key for `projectEvidenceCardsUsersMap` and that is not generated anywhere. Do you really need a primary key for the pivot table? If so, could you just use an autoincrementing integer as a primary key? You could also make the database generate an unique uuid in the database.

**Comment by joziahg** [comment]
I see, I wonder if upsertGraph could use the id column specified in the model M2M relation.

For instance, I defined that users relates to cards with the userId column through projectEvidenceCardsUserMap table. 
```javascript
class ProjectEvidenceCard extends Model {
  static get tableName () {
    return 'projectEvidenceCards'
  }

  static get relationMappings () {
    return {
      users: {
        relation: Model.ManyToManyRelation,
        modelClass: User,
        join: {
          from: 'projectEvidenceCards.id',
          through: {
            from: 'projectEvidenceCardsUsersMap.cardId',
            to: 'projectEvidenceCardsUsersMap.userId' // upsertGraph could use this instead of 'id'
          },
          to: 'users.id'
        }
      }
    }
  }
}
```

Maybe I should be able to graph insert it like this:
```javascript
  await ProjectEvidenceCard.query().upsertGraph({
    id: '4c992c32-36b8-11e9-b210-d663bd873d93',
    cardAction: 'Do a thing',
    users: [
      {
        id: '09610ff0-36bf-11e9-b210-d663bd873d93', // this becomes the actual map table Primary key
        userId: '2b25fb2c-3e90-11e9-b210-d663bd873d93', // this becomes the relation id
        name: 'A Person'
      }
    ]
  }, { relate: true, insertMissing: true })
```

Thoughts?

**Comment by koskimas** [comment]
It's not about upsertGraph using things or not. There's just a column that never gets a value from anywhere. This has nothing to do with upsertGraph or even objection. Your reproduction was just broken.

**Comment by koskimas** [comment]
Remove the id altogether from the database and things should work.

**Comment by koskimas** [comment]
Or replace it with an autoincrementing one

**Comment by koskimas** [comment]
Just to make sure you understand what I mean, I'm talking about this
```js
    .createTable('projectEvidenceCardsUsersMap', table => {
      table.uuid('id').notNullable().primary() // <--- THIS! This is never given a value since it isn't generated automatically
      table.uuid('cardId').notNullable()
      table.foreign('cardId').references('id').inTable('projectEvidenceCards')
      table.uuid('userId').notNullable()
      table.foreign('userId').references('id').inTable('users')
    })
```

**Comment by koskimas** [comment]
Or instruct the database to generate the id using `defaultTo(knex.raw('some_function_to_generate_uuid()'))`

**Comment by joziahg** [comment]
Yes you are right, and I have replaced it with an auto increment PK. However I still think the docs for upsertGraph is confusing when dealing with M2M relations. I guess my thinking process is this:
```javascript
  await ProjectEvidenceCard.query().upsertGraph({ // Parent object to be inserted.
    id: '4c992c32-36b8-11e9-b210-d663bd873d93', // I specify the PK id here
    cardAction: 'Do a thing', // and all the other fields
    users: [
      {  // So when it comes to this object I guess I am looking at it as a map table object rather than a User object.
        id: '09610ff0-36bf-11e9-b210-d663bd873d93', // In my mind this should the PK for the map table.
        userId: '2b25fb2c-3e90-11e9-b210-d663bd873d93', // And this should be PK of the user object I want to relate.
        name: 'A Person'
      }
    ]
  }, { relate: true, insertMissing: true })
```
I guess I was looking at it as if the objects supplied to the array of objects to be related, in this example users, were rows to be inserted into a map table rather than user objects to be related. I appreciate the help and clarification, you can close this issue now.
