### ISSUE TITLE
Inserting graph with an empty relation no longer works.

### ISSUE THREAD

**Issue by mastermatt** [Vincit/objection.js#1227]
I'm not positive if this a bug/regression or if I've been doing it wrong and need guidance on what the "right way" is. But I do have code that breaks when I attempt to upgrade to at least 1.5.0 where 46d937055a6f3374223a8ee56349ca7c5eabb6e0 as added.

Simplified example:
```js
await Person.query().upsertGraph({
  firstName: 'Jennifer',
  lastName: 'Aniston',
  parent: {}, // BelongsToOneRelation
});
```
In my case I'm dealing with a one-to-one for polymorphic attributes, but that shouldn't matter here.
What use to happen was two INSERTs would fire off, one for the primary object and one for the relationship. For the second, it would only insert the ID of the new primary object (plus any defaults).
However, as of 1.5, only the first INSERT is executed.

Regression or is there a better way to insert an "empty" relation in a graph?

**Comment by koskimas** [comment]
Inserting an empty item should work, so this is a bug. I'll fix this asap. Thanks for bringing this up!

**Comment by koskimas** [comment]
@mastermatt I wrote a test and I'm not able to reproduce this. Both objects get inserted in my tests.

**Comment by koskimas** [comment]
I'm afraid I'll need a reproduction for this one from you.

**Comment by mastermatt** [comment]
Here is a reproduction with the classes I'm working with pared down to just the attributes that map to columns and the one relationship that matters.

#### Payment Model
```ts
export default class PaymentTest extends Model {
  public static tableName = "payments";
  public static relationMappings: RelationMappings = {
    credit_card: {
      relation: Model.HasOneRelation,
      modelClass: "PaymentCreditCardTest",
      join: {
        from: "payments.id",
        to: "payment_credit_cards.id",
      },
    },
  };

  public readonly id!: number;
  public commerce_customer_id!: number;
  public organization_id!: number | null;

  public currency!: string;
  public currency_amount!: string;
  public currency_exchange_rate!: string;
  public requested_currency!: string;
  public requested_currency_amount!: string;
  public requested_currency_exchange_rate!: string;
  public usd_amount!: string;

  public site_id!: number;
  public payment_status_id!: number | null;

  public payment_id_external!: string | null;
  public payment_id_external_source_id!: number | null;
  public payment_method_id!: number;
  public merchant_account_id!: number;

  public gateway_reference_id!: string;

  public create_time!: Date;

  public credit_card!: Partial<PaymentCreditCardTest>;
}
```

#### Credit Card Model
```ts
export default class PaymentCreditCardTest extends Model {
  public static tableName = "payment_credit_cards";

  public readonly id!: number;
  public type_id!: number;
  public bin!: string | null;
  public last_four!: string | null;
  public exp_month!: string | null;
  public exp_year!: string | null;
}
```

#### elsewhere, something like this fires
```ts
const paymentData = { 
  commerce_customer_id: 17000001,
  organization_id: 133000000,
  site_id: 1,
  requested_currency: 'USD',
  requested_currency_amount: '100',
  currency: 'USD',
  currency_amount: '100',
  usd_amount: '100',
  requested_currency_exchange_rate: '1',
  currency_exchange_rate: '1',
  payment_id_external: 'abc',
  payment_id_external_source_id: 65,
  payment_method_id: 1,
  merchant_account_id: 163,
  credit_card: {},
};

await PaymentTest.query().upsertGraph(paymentData);
```
note, in this example `insertGraph` could just as easily be used, by in my real world logic the payment may already exist and `paymentData` would include an `id`.

#### v 1.5+ Debug logs the one INSERT while awaiting for the upsert
```js
{ 
  method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 17000001, 'USD', '100', '1', 163, 133000000, 'abc', 65, 1, 'USD', '100', '1', 1, '100' ],
  __knexQueryUid: 'a87ca5e6-daaa-4215-b323-2208d60791c9',
  sql: 'insert into `payments` (`commerce_customer_id`, `currency`, `currency_amount`, `currency_exchange_rate`, `merchant_account_id`, `organization_id`, `payment_id_external`, `payment_id_external_source_id`, `payment_method_id`, `requested_currency`, `requested_currency_amount`, `requested_currency_exchange_rate`, `site_id`, `usd_amount`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' 
}
```

#### v1.4.0 Debug logs show both the INSERTs
```js
{
  method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 17000001, 'USD', '100', '1', 163, 133000000, 'abc', 65, 1, 'USD', '100', '1', 1, '100' ],
  __knexQueryUid: 'c3e18b90-1281-4f52-9120-1965022ff904',
  sql: 'insert into `payments` (`commerce_customer_id`, `currency`, `currency_amount`, `currency_exchange_rate`, `merchant_account_id`, `organization_id`, `payment_id_external`, `payment_id_external_source_id`, `payment_method_id`, `requested_currency`, `requested_currency_amount`, `requested_currency_exchange_rate`, `site_id`, `usd_amount`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
}
{ 
  method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '9ccf9316-8be5-4d79-8413-6a7e78fb0812',
  sql: 'insert into `payment_credit_cards` (`id`) values (?)' 
}
```

**Comment by koskimas** [comment]
For the record, that's not a reproduction. That's a bunch of code that maybe produces the bug if someone writes a shit ton of code around it so that it works. But I saw that the relationship is a `HasOneRelation` instead of `BelongsToOne` as you originally said. I'll try my test with a `HasOneRelation`.

**Comment by koskimas** [comment]
I tried that with a `HasOneRelation` and it also works. So at least this isn't completely broken, but rather some detail in your setup is causing this.

If you want me to debug this further, I need a piece of code I can run with one single command, that reproduces the bug.

**Comment by koskimas** [comment]
Your mapping is from primary key to primary key. Are you sure that's what you want?

```
      join: {
        from: "payments.id",
        to: "payment_credit_cards.id",
      }
```

That could be causing it somehow.

**Comment by koskimas** [comment]
Yeah, it's related to primary key -> primary key relationships. I was able to reproduce this now. Fix will come soon.

**Comment by mastermatt** [comment]
That did the trick, thanks.
