### ISSUE TITLE
findOne and limit

### ISSUE THREAD

**Issue by nicosierra** [Vincit/objection.js#1230]
Hi there,

When performing the debug of a findOne query, I don't see any limits being applied to the statement.
Why was this preferred rather than applying explicitly such filter in the query?

Thanks!

**Comment by koskimas** [comment]
https://vincit.github.io/objection.js/#uselimitinfirst

**Comment by nicosierra** [comment]
🤦‍♂️ there it was.
thanks!

**Comment by koskimas** [comment]
Not that easy to find. I should probably link to it from `findOne`, `first` etc. documentation
