### ISSUE TITLE
.whereJsonSubsetOf

### ISSUE THREAD

**Issue by mecrowell** [Vincit/objection.js#1231]
trying to use .whereJsonSubsetOf, however it will not work on a text array. Any ideas on how to do this?

**Comment by koskimas** [comment]
Whay do you mean by text array? Is the column you are testing against a text array, as in `text[]`? If so, this only works with `json` or `jsonb` columns. If you mean the value you are testing against the column is an array of text, it should work. Could you provide the failing code?

**Comment by mecrowell** [comment]
yes to the first question...
i'm trying to match a logged in users roles [apps, users, charges] to roles column on a table and returning the rows that match in the query
i had it working with whereJsonSubsetOf when it was JsonB but need to change the data type to text[]

.whereJsonSubsetOf('table.roles', 'auth.roles')

**Comment by koskimas** [comment]
Yeah, `where**Json**SubsetOf` only works on json columns. You can however use the postgres' many operators directly. In this case I guess this should work

```js
await User
  .query()
  .where('roles', '@>', lit(['apps', 'charges']).asArray())
```

`lit(['apps', 'charges']).asArray()` is just a shorthand for `raw("ARRAY['apps', 'charges']")`.

**Comment by koskimas** [comment]
https://www.postgresql.org/docs/9.1/functions-array.html

**Comment by mecrowell** [comment]
forgive me, because I'm *very* new to sql, but would the first value 'roles' be the auth.roles which is an array and then the match to the table column be the lit([roles]).asArray()?

**Comment by koskimas** [comment]
The first value `'roles'` would be a string that points to the column of the `User` model's table. The argument passed to the `lit` function would be the array of roles to test.

**Comment by koskimas** [comment]
You can chain `.debug()` to any query to see the generated SQL. That's usually helpful when trying to understand what objection does.

**Comment by koskimas** [comment]
This

```js
await User
  .query()
  .where('roles', '@>', lit(['apps', 'charges']).asArray())
```

means

```
Give me all users whose 'roles' column contains the strings 'apps' and 'charges'
```

**Comment by mecrowell** [comment]
thanks for your help

**Comment by koskimas** [comment]
You're welcome :bowing_man:
