### ISSUE TITLE
.eager() M-M get everything where at least one children matches the criteria

### ISSUE THREAD

**Issue by forbi** [Vincit/objection.js#1232]
I Have this models: 

```javascript
class Warehouse extends Model {
  static get tableName() {
    return "Warehouses";
  }
  static relationMappings = {
    Members: {
      relation: Model.ManyToManyRelation,
      modelClass: User,
      join: {
        from: "Warehouses.id",
        through: {
          from: "WarehouseMembers.WarehouseId",
          to: "WarehouseMembers.UserId"
        },
        to: "Users.id"
      }
    }
  };
}
```

I woul like to get for example all the Warehouses and its members, where at leat one of members (Users) has the name "Pepe"

```javascript
await Warehouse.query()
      .where({ id: 1 })
      .eager("[Members(onlyPepe)]", {
        onlyPepe: builder => {
          builder.where("name", "Pepe");
        }
       });
```

I tried the above query, but I only shows that the warehouse 1 has one member (the one that matches), but I fact the warehouse has two members. How can I include them? :pray: 

```javascript
[ 
  Warehouse {
    id: 1,
    name: 'Felix the cat',
    address: 'Blanco 1299 local 5',
    Members: [ [User] ] 
  } 
]
```

**Comment by koskimas** [comment]
This should work:

```js
await Warehouse.query()
      .whereExists(Warehouse.relatedQuery('Members').where('name', 'Pepe'))
      .eager('Members')
```

That's a pure SQL approach. `Warehouse.relatedQuery` simply takes care of doing all relevant joins so that you don't have to do them by hand. You can chain `.debug` to main query to see what kind of SQL gets generated.

**Comment by forbi** [comment]
@koskimas Thanks a lot man. You have no idea how much I struggled to do something like that with *sequelize*.

**Comment by koskimas** [comment]
:bowing_man:

**Comment by forbi** [comment]
@koskimas Mate, one last question (for now 🙄 ), I can't figure out the way to relate two existing values into an m-m table.

For example, I have the warehouse (id: 1), and the user (id: 1), how can I relate (and unrelate) them in the "WarehouseMembers" table?
