### ISSUE TITLE
`jsonAttributes` should report wrong JSON

### ISSUE THREAD

**Issue by bato3** [Vincit/objection.js#1234]
I migrated data from sqlite to mysql and some JSON data was corrupted during this operation.

I believe that (especially in the development environment) at least a warning should be issued about this situation.

```js
class FileAlt extends Model {
  static get tableName() { return 'file_alts';}
  static get idColumn() {
    return 'file_alt_id';
  }
  static get jsonAttributes() {
    return [ 'mediainfo_dump'];
  }
}
```

More complex example code in https://github.com/Vincit/objection.js/issues/1233

**Comment by koskimas** [comment]
What?

**Comment by bato3** [comment]
It don't gave me any message

**Comment by koskimas** [comment]
Oh, that's true! I can't really change the default. It would be a breaking change. I could add a flag that throws by default, but you could just as easily just create a migration file that fixes those issues in your db.

**Comment by bato3** [comment]
(Not durring mugration, during `.query().first()`)

I think `throw` may be too much, but `console.warn` should not cause problems in default configuration.

https://github.com/Vincit/objection.js/blob/master/lib/model/modelJsonAttributes.js#L19-L21 and
