### ISSUE TITLE
querying a many-to-many relationship?

### ISSUE THREAD

**Issue by SuttonKyle** [Vincit/objection.js#1235]
Hi, so I have two tables, users and chats, with a many-to-many relationship.  I'm trying to create a query to get the chats for a certain user, and I want to be able to search a user's chats by the name of other users in the chat.  My query currently looks something like this:
```
const chats = await Chat.query()
    .skipUndefined()
    .whereExists(
      User.query()
        .skipUndefined()
        .findById(obj.id),
      User.query().where(raw('lower("name")'), 'like', `%${substrLower}%`),
    )
    .where('chatType', filter.chatType)
    .limit(limit)
    .offset(offset)
```
Unfortunately, this is returning all chats, instead of just the user's chats.  I imagine this is because I should be including a reference back to the chat inside the whereExists statements (if I'm reading the docs correctly), but obviously this would lead to an infinite recursion.  Is there some elegant way to accomplish this?

**Comment by koskimas** [comment]
This should do it:

```js
const chats = await Chat.query()
    .skipUndefined()
    .whereExists(
      Chat.relatedQuery('users').where('id', obj.id)
    )
    .whereExists(
      Chat.relatedQuery('users').where(raw('lower("name")'), 'like', `%${substrLower}%`)
    )
    .where('chatType', filter.chatType)
    .limit(limit)
    .offset(offset)
```

This example assumes that the many-to-many relationship in `Chat` is named `users`.

**Comment by koskimas** [comment]
And you can create references back to parent query from sub query. Subqueries are not actually executed as separate queries, but built into the parent query's SQL. See what kind of SQL gets generated for that by chaining `.debug()` to the query.
