### ISSUE TITLE
Merge same values in query result

### ISSUE THREAD

**Issue by auelx** [Vincit/objection.js#1236]
Is there a way in Objection to merge same values in query result? The current JSON result I get is: 

    {
        "id": 1,
        "full_name": "John Smith",
        "ordered_date": "2019-02-14T08:39:04.000Z",
        "destination": "xxxxxxxx",
        "contact": "xxxxxxxx",
        "status": 0,
        "service_fee": 20,
        "items": [
            {
                "merchant_name": "Shop1",
                "address": "xxxxxxx",
                "order_items": [
                    {
                        "name": "Product1",
                        "size": null,
                        "quantity": 1,
                        "price": 100
                    }
                ]
            },
            {
                "merchant_name": "Shop1",
                "address": "xxxxxxx",
                "order_items": [
                    {
                        "name": "Product2",
                        "size": null,
                        "quantity": 1,
                        "price": 75
                    }
                ]
            },
            {
                "merchant_name": "Shop2",
                "address": "xxxxxx",
                "order_items": [
                    {
                        "name": "Product3",
                        "size": "Regular",
                        "quantity": 1,
                        "price": 99
                    }
                ]
            }
        ]
    }

but my target output is like this:

    {
        "id": 1,
        "full_name": "John Smith",
        "ordered_date": "2019-02-14T08:39:04.000Z",
        "destination": "xxxxxxxx",
        "contact": "xxxxxxxx",
        "status": 0,
        "service_fee": 20,
        "items": [
            {
                "merchant_name": "Shop1",
                "address": "xxxxxxx",
                "order_items": [
                    {
                        "name": "Product1",
                        "size": null,
                        "quantity": 1,
                        "price": 100
                    },
                    {
                        "name": "Product2",
                        "size": null,
                        "quantity": 1,
                        "price": 75
                    }
                ]
            },
            {
                "merchant_name": "Shop2",
                "address": "xxxxxx",
                "order_items": [
                    {
                        "name": "Product3",
                        "size": "Regular",
                        "quantity": 1,
                        "price": 99
                    }
                ]
            }
        ]
    }

here my code: 

```javascript
try {
    let result = await Order
        .query()
        .innerJoinRelation('customers')
        .select('orders.id', 'customers.full_name', 'orders.ordered_date', 'orders.destination', 'customers.contact', 'orders.status', 'orders.service_fee')
        .where("status", "<>", 3)
        .eager("items(selectMerchants)", {
            selectMerchants: (builder) => {
                builder
                    .innerJoinRelation('merchant')
                    .select('merchant.name AS merchant_name', 'merchant.address')
                    .eager('order_items(selectOrderItems)',  {
                        selectOrderItems: (builder) => {
                            builder
                                .leftJoin('variations', 'order_details.variation_id', 'variations.id')
                                .innerJoin('products', 'order_details.product_id', 'products.id')
                                .select('products.name', 'variations.name AS size', 'order_details.quantity', 'order_details.price')
                        }
                    })
                    .orderBy('merchant.id')
            }
        })
        .throwIfNotFound()
        .debug(true);
    return res.send(result);
}catch(e) {
    next(e);
}
```

**Comment by koskimas** [comment]
Those duplicats appear because of joins you do. So write your query without joins is the answer. You can probably leverage subqueries. Another solution is to use aggregations or `select distinct`. This is not really related to objection, but SQL instead.

I'd suggest you read up on how joins work and how their results are returned by database engines.

**Comment by koskimas** [comment]
Also those nested eagers are probably not a good idea. You can simply create one `eager` expression and use multiple filters.

**Comment by auelx** [comment]
Thank you for your response. I agree with you about the duplicates was cause of my `innerJoinRelation('merchant')` however I needed that join in order to link `order_details` and `merchants` via `products` table. I tried using `select distinct` but the fact that the generated SQL statement include foreign keys of both parents which doesn't affect the result due to id's are unique most of the time. Is there a way to remove both or just one of those foreign key in select statement?

**Comment by brookmg** [comment]
@auelx you found a fix for this?
