### ISSUE TITLE
Add afterInsert method to relationMappings

### ISSUE THREAD

**Issue by jrbarnard** [Vincit/objection.js#1239]
There is currently a beforeInsert method (https://vincit.github.io/objection.js/#relationmappings), it would be great to be able to do afterInsert hooks too.

I reckon the same syntax and function props are fine, keeping it optionally async too.

Could we also add before/after for detaching?
I'm happy to look at implementing if there is interest?

Cheers

**Comment by koskimas** [comment]
Can you provide me use case for this?

Implementing this would be pretty difficult because it would need to work with `$relatedQuery`, `insertGraph` and `upsertGraph`.

**Comment by jrbarnard** [comment]
I think my use case at the time was I was handling order on a pivot.

So I wanted to update the column order after a newly inserted pivot entry was added, in the end I used context + beforeInsert to work out the next order & iterate it to set before inserting, I think this negated my need for afterInsert.

I can't however update the ordering on the detaching of an entry, I currently just end up with gaps (not the end of the world, but would be nice to trigger events based on detaching & update the ordering).

Same goes for beforeUpdate / afterUpdate, that would be useful for potentially setting an updated_at timestamp on the pivot.

I think initially a beforeUpdate and beforeDetach method would be most useful, after methods I don't have a usecase for I can't get around currently.

**Comment by koskimas** [comment]
If you only need this stuff for the pivot, you can create a model class for the pivot table, and provide it using `through.modelClass` property in your relation mappings. You can implement all those methods for the pivot table model.

**Comment by koskimas** [comment]
Let me know if that works out for you.

**Comment by jrbarnard** [comment]
@koskimas Cheers, I didn't realise that existed, I couldn't find it referenced in the docs?

**Comment by koskimas** [comment]
It's there in the API reference too. http://vincit.github.io/objection.js/#relationmappings
