### ISSUE TITLE
modify and queryBuilder

### ISSUE THREAD

**Issue by ozum** [Vincit/objection.js#124]
Hi,

I'm testing v0.5.0-rc.2.

Added `modify` method works as expected for knex' methods such as `innerJoin`, `where` etc.. However it is not working for objection's methods such as `innerJoinRelation`, `eager` and others:

```js

function modifierKnex(queryBuilder) {
    queryBuilder.innerJoin(...);
}

function modifierObjection(queryBuilder) {
    queryBuilder.innerJoinRelation(...);
}

AppUser.query().modify(modifierKnex)
    .then((data) => { } )
    .catch(err => console.log(err));

AppUser.query().modify(modifierObjection)
    .then((data) => { } )
    .catch(err => console.log(err));
```

Thanks,

**Comment by koskimas** [comment]
You're right. My implementation for it was an enormous brainfart. I'll fix this right away.
