### ISSUE TITLE
QUESTION: Is there a way to trigger .returning('*') instead of .returning(getIdColumn)? 

### ISSUE THREAD

**Issue by douggr** [Vincit/objection.js#1240]
If not, it'd be great to have a static method/attribute for that in update and insert operations perhaps?

P.S.: Thank you for this library!

**Comment by koskimas** [comment]
Yes, you can trigger that simply by calling it

```js
Person.query().insert(person).returning('*')
```

**Comment by koskimas** [comment]
Oh, you probably mean triggering that automatically for all updates/inserts? This should work, but it's not very concise:

```js
class CustomQueryBuilder extends Model.QueryBuilder {
  execute(...args) {
    if (this.isInsert()) {
      this.returning('*')
    }
  
    return super.execute(...args)
  }
}

class BaseModel extends Model {
  static get QueryBuilder() {
    return CustomQueryBuilder
  }
}

class Person extends BaseModel {

}
```

**Comment by douggr** [comment]
Yup, I found objection.js while using Knex for a long time now ;) I'm just to lazy to call `.returning` every time I do any insert/update.

I meant, it would be nice if we had an attribute or static method to overwrite the defaults in [InsertOperation.onBuildKnex](https://github.com/Vincit/objection.js/blob/8b795831114d3c3790908c30d4d864c29b12e576/lib/queryBuilder/operations/InsertOperation.js#L40-L45) for instance.

```ts
onBuildKnex(knexBuilder, builder) {
  if (!isSqlite(builder.knex()) && !builder.has(/returning/)) {
    knexBuilder.returning(builder.modelClass().getReturningExpr()); // here's the change
  }
}
```

And maybe the default `getReturningExpr()` returning `getIdColumn()`.

**Comment by koskimas** [comment]
I don't add stuff to the public interface lightly because whatever is made public, will be tested and maintained from there on. Features also add code and complexity which makes development slower.

If we were to support this particular case, it would be through a more generic feature, such as a static `beforeInsert` hook (which is coming in 2.0 by the way):
```js
class Person extends Model {
  beforeInsert({ query ) {
    query.returnin('*')
  }
}
```

As I mentioned before, I won't add a specific method, or a property for this.

**Comment by douggr** [comment]
Got you, makes sense. Thanks for the thoughts :)

- EOF
