### ISSUE TITLE
objection-gen, it generates random test data for models

### ISSUE THREAD

**Issue by ludbek** [Vincit/objection.js#1243]
I recently created a package for objection.js which generates random test data for models.
Sharing it here in the hope fellow devs will find it useful and save some time while writing tests.

Features
- generates fake data for a model and related models
- cleans dirty tables

[objection-gen](https://github.com/ludbek/objection-gen)

**Comment by koskimas** [comment]
@ludbek Seems like a nice project. This is probably not the best place to advertise something. People mostly only look at issues they are struggling with. You could try posting in reddit /r/node.
