### ISSUE TITLE
promise was created in a handler but was not returned (express route)

### ISSUE THREAD

**Issue by bato3** [Vincit/objection.js#1246]
It seems to be an Objection error, because express says it's not them. 
https://github.com/expressjs/express/issues/3257 https://github.com/expressjs/express/issues/3777

(And besides, I can not get this error by `new Promise(r=>{setTimeout(()=>r('foo')},10)})`)

This code displays a warning (Node 8)

```
(node:12684) Warning: a promise was created in a handler at .\node_modules\express\lib\router\index.js:317:13 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (.\node_modules\bluebird\js\release\method.js:29:9)
```

```js
router.get('/t1', (req, res) => {
    return User.query().findById(1).then(u=>{
      return res.send(u)
    })
})
```

And this is OK:

```js
router.get('/t2', async (req, res) => {
  let u = await User.query().findById(1)
  return res.send(u)
})
```

I know that I can mute this by `set BLUEBIRD_W_FORGOTTEN_RETURN = 0` or `express-promise-router`
But I would prefer not to use such tricks - to give me a serious error is not hidden.

**Comment by koskimas** [comment]
Cannot reproduce. If you want me to look into this further, please provide a full reproduction I can run with a single command.

**Comment by koskimas** [comment]
I'd guess this is caused by you returning `res.send(u)`. No need to return that. It's not async.

**Comment by bato3** [comment]
I did more tests and was guilty is `objection` in `passport.deserializeUser`

```js
app.use(passport.session());
//...
passport.deserializeUser(async function(user, cb) {
    //*
    return User.query().findById(user.user_id).then(function(u) {
        cb(null, u.toPassport());
    }).catch(function(err) {
        console.error(err);
        cb(null, false, {error: 'err'});
    });
    return 
    /*/
   try {
       let u = await User.query().findById(user.user_id)
       if(u && u.user_id > 0)
        return cb(null, u.toPassport());
   } catch (err) {}
   cb(null, false, {error: 'error'});
   //*/
});
//where toPassport is defined as:

  toPassport() {
    return {
      user_id:    this.user_id,
      username:   this.username,
      role:       this.role,
      transfer:   (this.transfer),
      time_check: new Date().getTime()
    }
  }
```

**Comment by koskimas** [comment]
Yeah, not objections fault.

**Comment by koskimas** [comment]
If you yourself write code that creates promises inside `then` but return nothing, how is that objection's fault? Just fix your own code.

**Comment by koskimas** [comment]
Also, why don't you just use `async`/`await`? There are no such problems with that because it wraps all promises to native promises.
