### ISSUE TITLE
Objection Model - Insert is returning auto generated number primary key value as String

### ISSUE THREAD

**Issue by jagjotwwt** [Vincit/objection.js#1247]
Using Objection Model to insert a row in oracle db table is returning auto generated primary key as 'String' value. Expecting it to return number type value.

Note: findById using same model is returning correct type of value i.e. number.

Database : Oracle
Data Type of the Primary Key in DDL
   "APPOINTMENT_HEADER_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY

Code Snippet for insert 

    async  insertAppointment() {
      let appointmentJson = {
        facilityCode: 'TN1',
        organizationCode: '40',
        appointmentType: 'OB',
        appointmentStartDatetime: '2019-03-10T00:56:41.000Z',
        appointmentEndDatetime: '2019-03-10T00:56:52.000Z',
        appointmentCurrentStage: 'CREATED',
        carrierName: 'TUPS2',
        createdBy: 99853,
        lastUpdatedBy: 99853
      }
      let appointment = Appointments.fromJson(appointmentJson)
      let result = await **Appointments.insert(appointment)**
      return result
    }
snippet for $formatDatabaseJson and $parseDatabaseJson
```
  static get idColumn() {
    return 'APPOINTMENT_HEADER_ID'
  }
  static get jsonSchema() {
    return {
      type: 'object',
      required: ['facilityCode', 'organizationCode', 'appointmentType', 'appointmentStartDatetime', 'appointmentEndDatetime', 'carrierName'],
      properties: Object.assign(super.baseProperties, {
        appointmentHeaderId: {type: 'number', readOnly: true},
        facilityCode: {type: 'string'},
        organizationCode: {type: 'string'},
        appointmentType: {type: 'string'},
        appointmentStartDatetime: {type: 'string', format: 'date-time'},
        appointmentEndDatetime: {type: 'string', format: 'date-time'},
        appointmentCurrentStage: {type: 'string'},
        carrierName: {type: 'string'},
        createdBy: {type: 'number'},
        lastUpdatedBy: {type: 'number'}
      })
    }
  }
  $formatDatabaseJson(json) {
    json = super.$formatDatabaseJson(json)
    if (this.constructor.jsonSchema) {
      _.forIn(this.constructor.jsonSchema.properties, (value, key) => {
        if (value.type.includes('boolean') && json[key] !== null && json[key] !== undefined) {
          json[key] = (json[key] ? 'Y' : 'N')
        }
      })
    }
    json = _.mapKeys(json, (value, key) => {
      return _.snakeCase(key).toUpperCase()
    })
    return json
  }

  $parseDatabaseJson(json) {
    json = _.mapKeys(json, function (value, key) {
      return _.camelCase(key)
    })
    if (this.constructor.jsonSchema) {
      _.forIn(this.constructor.jsonSchema.properties, (value, key) => {
        if (value.type.includes('boolean') && json[key] !== null && json[key] !== undefined) {
          json[key] = (json[key] == 'Y')
        }
      })
    }
    return super.$parseDatabaseJson(json)
  }
```

Using
```
  "knex": "^0.12.7",
  "objection": "^0.8.7",
```

**Comment by koskimas** [comment]
Expected

**Comment by jagjotwwt** [comment]
Thank you for the prompt reply. I was wondering how is findById returning value as of number type in this case? 
I tried to do parseInt in $parseDatabaseJson but id do not allow to change the value of primary key.
I am using     
   "oracledb": "^2.3.0",

**Comment by koskimas** [comment]
You can change whatever you want in `parseDatabaseJson`. Objection in no way prohibits you from changing a primary key. I have no idea why oracle would return the id as a number in some cases and as a string in others, but that's oracle's problem. By the way, you are using an ancient version of objection. The most recent version is 1.6.X

**Comment by jagjotwwt** [comment]
Thank you. I have updated to use 1.6.0.
Just wanted to bring into you notice that I am getting an error while trying to change value of ID column in parseDatabaseJson
Error Snippet:
```
  Error: Appointments.$parseDatabaseJson probably changes the value of the id column `APPOINTMENT_HEADER_ID` which is a no-no.
    idColumnToIdProperty (node_modules/objection/lib/model/modelColPropMap.js:35:11)
    getIdProperty (node_modules/objection/lib/model/Model.js:628:12)
    Function.getIdProperty (node_modules/objection/lib/model/Model.js:395:57)
    getId (node_modules/objection/lib/model/modelId.js:61:36)
    Appointments.$id (node_modules/objection/lib/model/modelId.js:7:12)
    Appointments.$id (node_modules/objection/lib/model/Model.js:69:16)
    InsertOperation.onAfter1 (node_modules/objection/lib/queryBuilder/operations/InsertOperation.js:105:20)
    Object.<anonymous> (node_modules/objection/lib/queryBuilder/QueryBuilder.js:1167:26)

```

**Comment by koskimas** [comment]
Oh, I didn't remember that assertion. I don't know if there is any reason to have it anymore. I'll see if it could be removed.

**Comment by koskimas** [comment]
@jagjotwwt You can't be getting that error in 1.6.0. That assertion code is still in the repo, but it's never executed.
