### ISSUE TITLE
Model.insert/patch/update returns "duplicated" properties. Maybe bug?

### ISSUE THREAD

**Issue by douggr** [Vincit/objection.js#1248]
When you call `.[insert/patch/update](options).returning("*")`, objection returns both table's column name and the alias as in `created_at => createdAt`. Is that the expected behavior?

Example bellow:

```ts
const APP_KNEX_DEFAULTS = {
  // ...
  wrapIdentifier: (value, origImpl) => {
    return knexSnakeCaseMappers().wrapIdentifier(value, origImpl);
  },
};

// and connect... then...

class User extends Model {
  static tableName = "user";

  createdAt!: Date; // created_at in DB
  id!: string;
  username?: string;
}

User
  .query()
  .insert({
    username: "foo",
  })
  .returning("*")
  .then(insertedModel => console.log(insertedModel));
```

I'd expect `insertedModel.toJson()` to be:
```json
{
  "createdAt": "2019-03-10T06:13:40.598Z",
  "id": "1",
  "username": "foo"
}

```

but I've got: 
```json
{
  "created_at": "2019-03-10T06:13:40.598Z", // <= I think this is not supposed to be here
  "createdAt": "2019-03-10T06:13:40.598Z",
  "id": "1",
  "username": "foo"
}
```

**Comment by koskimas** [comment]
Cannot reproduce.

**Comment by koskimas** [comment]
This is very inefficient by the way:

```js
  wrapIdentifier: (value, origImpl) => {
    return knexSnakeCaseMappers().wrapIdentifier(value, origImpl);
  },
```

This creates a new set of mapper functions, caches, etc. each time `wrapIdentifier` is called, which can be hundreds or thousands of times per query.

**Comment by douggr** [comment]
> This is very inefficient by the way:
> 
> ```js
>   wrapIdentifier: (value, origImpl) => {
>     return knexSnakeCaseMappers().wrapIdentifier(value, origImpl);
>   },
> ```
> 
> This creates a new set of mapper functions, caches, etc. each time `wrapIdentifier` is called, which can be hundreds or thousands of times per query.

I see, is there a proper/better way to map `table.column_name` to `Model.columnName`?

**Comment by koskimas** [comment]
Yes, there are couple of ways well documented in the docs.

**Comment by koskimas** [comment]
And my point was just to NOT call `knexSnakeCaseMappers()` inside `wrapIdentifier`. Call it outside of it and only use it inside.

**Comment by koskimas** [comment]
But, anyway, the original bug is in your code, not in objection.

**Comment by koskimas** [comment]
https://vincit.github.io/objection.js/#snake-case-to-camel-case-conversion

**Comment by douggr** [comment]
> But, anyway, the original bug is in your code, not in objection.

Yup, my fault!

Changing from this original call:

```ts
  wrapIdentifier: (value, origImpl) => {
    return knexSnakeCaseMappers().wrapIdentifier(value, origImpl);
  },
```

into this:
```ts
  ...knexSnakeCaseMappers(),
```

it worked like a charm.

Thank you!

**Comment by douggr** [comment]
> Yes, there are couple of ways well documented in the docs.

Yes, indeed! Your docs are actually very clean and concise, this was totally a early dawn/coffeless braincrash.

Thank you again.
