### ISSUE TITLE
Removing relation id on eager

### ISSUE THREAD

**Issue by mrtijn** [Vincit/objection.js#1249]
Hi,

i am trying to replace the relation id with the relation result when querying. Probably a pretty easy 
 & common scenario, but i can't seem to get it working. I created a relationmapping on the item model to match it with the location id. I get the right location, but i don't want the location_id to show up in the result. I tried a few different joins but non with the right result.
The scenario is now is;

table `item`:
```
name                 
description        
location_id         
```    
query:
```
 Item
 .query()
 .eager('location');
```
result now: 
```
name                 
description        
location_id         
location <Object>
```    

what i want to achieve:
```
name                 
description        
location <Object>        
```

**Comment by koskimas** [comment]
There's no built-in feature that does this. Why do you want to get rid of the id?

**Comment by koskimas** [comment]
One option is to implement the `$formatJson` hook and delete `location_id` there:

```js
class Item extends Model {
  $formatJson(json) {
    json = super.$formatJson(json)
    delete json.location_id
    return json
  }
}
```

**Comment by MarcusCemes** [comment]
> There's no built-in feature that does this. Why do you want to get rid of the id?

I'm still new, excuse me if there's a more correct way of doing this. It adds a superfluous forein key property in the returned model. The foreign key column should only be used when joining in the database.

```ts
Film.query().findById(id).eager("thumbnails");
```

The `film_id` column for this OneToMany relation is redundant in the query:

![image](https://user-images.githubusercontent.com/20288819/63957761-53fe0f00-ca89-11e9-89fa-dd8dbaacee92.png)

Creating a JSON filter is overkill imo.

**Comment by mordof** [comment]
@MarcusCemes In your situation it may only be necessary in the join details, however there's many cases where it's beneficial to have that information included. The way knex/Objection work here as well is simply to return what is in the database.

If you want to have it so that the relation ids aren't returned from the database, you can manage the selected items to prevent it from coming through as well. 

Is there a specific reason you're against having the relation id in the results?

**Comment by MarcusCemes** [comment]
Understood, no concrete reason, just trying to make the API look clean.

Explicitly listing the SELECT columns sounds like a good solution, I'm just worried about forgetting to update it if I make future changes to the models.

**Comment by mordof** [comment]
We've got a bunch of things working in tandem to handle the data.  A mapper package which takes some data, and a describing object of how to map over it/restructure it/clean it up. A decorator for our models called `@ApiField()` which dictates what fields we want shown to the api output by default. Then at the end of the router action, a function called `getApiFields(Model)` which simply looks at the model (and its relationships) to give that describing object of what should go through, then that mapper package trims everything out.

We're looking to open source these at some point so it's easier for others to accomplish the same idea. Overall it provides an easy way to tell the API output what the results should look like without much effort after the initial definitions using the decorators.

**Comment by mordof** [comment]
It's similar to using a json schema, or some form of function to iterate over any amount of nested data, and clean it up so the API output is exactly what you want.

**Comment by MarcusCemes** [comment]
Thank you for sharing your practical experience!

That seems like a very good solution to the problem and is probably a much safer approach than passing the database object straight to the client. However, in my case, it would be a gross overcomplication of a small scale API. For now, I will settle for simple iteration over the attached relations and  `delete`ing foreign key properties.
