### ISSUE TITLE
Nested insert fails, when json schema has { additionalProperties: false }

### ISSUE THREAD

**Issue by elhigu** [Vincit/objection.js#125]
Looks like `#id` variables are also validated

```
 1) Nested populator simple nested sample data:
     Error: {
  "#id": "Additional properties not allowed"
}
```

**Comment by koskimas** [comment]
The `#id` properties are removed from the models by setting them to `undefined`. You can change this to `delete` by overriding the `omitImpl` method of a model:

```js
class BaseModel extends Model {
  static omitImpl(obj, key) {
    delete obj[key];
  }
}
```

**Comment by elhigu** [comment]
got it working with `omitImpl` 👍

**Comment by koskimas** [comment]
I'll change the default `omitImpl` to use delete. Setting to undefined is just a stupid premature optimization without any real data.
