### ISSUE TITLE
HasOneThroughRelation multiple through possibility

### ISSUE THREAD

**Issue by fatkhanfauzi** [Vincit/objection.js#1250]
Hi, thanks for this cool package.

can we have multiple through for HasOneThroughRelation ?

i need something like:
`select "branches".* from "branches" inner join "clusters" on "branches"."id" = "clusters"."branch_id" inner join "plans" on "plans"."cluster_id" = "clusters"."id" inner join "request_orders" on "request_orders"."plan_id" = "plans"."id"`

is it possible to do something like this:
```
      branch: {
        relation: Model.HasOneThroughRelation,
        modelClass: Branch,
        join: {
          from: 'request_orders.plan_id',
          through: {
            from: 'clusters.id',
            through: {
              from: 'plans.id',
              to: 'plans.cluster_id',
            },
            to: 'clusters.branch_id',
          },
          to: 'branches.id',
        },
```

if so, could you please let me know which part is wrong ?
thanks

**Comment by koskimas** [comment]
That's not possible I'm afraid.

**Comment by fatkhanfauzi** [comment]
I'm using objection-find package an use the provided query from there.
Do you have suggestion to achieve that?

**Comment by koskimas** [comment]
You can simply join through those two relations

```js
await RequestOrder
  .query()
  .joinRelation('clusters.plans')
```

**Comment by fatkhanfauzi** [comment]
Alright, i need to create the custom builder for objection-find then.
Thanks.
