### ISSUE TITLE
knex provides options method on query builder, not accessible via objection

### ISSUE THREAD

**Issue by tmeinders** [Vincit/objection.js#126]
I'm probably doing something a bit unorthodox with my joins, but I'm attempting to get back nested tables in my response, which I can set with knex('table').options( {nestTables: true }) but I cannot accomplish through the objection QueryBuilder.

I think the objection QueryBuilder is supposed to expose all knex methods, but options isn't available. Is there a quick fix for this with the current version of the code or does QueryBuilder need to be modified to apply this method?

**Comment by koskimas** [comment]
The goal is to provide a superset of the knex query methods, but sometimes methods are added to knex and for some reason they don't magically appear to objection before an update :wink:. You can install an 0.5.0 RC version using `npm install objection@next` that has the `options` method.

**Comment by tmeinders** [comment]
Thanks. I appreciate the good work. I didn't notice it in the very recent commit history.
