### ISSUE TITLE
Is it possible to specify the corresponding column name for each property of a model?

### ISSUE THREAD

**Issue by marlon-bain** [Vincit/objection.js#1260]
If not, does this essentially mean our DB model properties have to match code model properties (up to casing)?

**Comment by marlon-bain** [comment]
Nevermind, I found this: https://vincit.github.io/objection.js/#columnnamemappers

It seems to do what I require.

**Comment by harobed** [comment]
> https://vincit.github.io/objection.js/#columnnamemappers

`#columnnamemappers` anchor didn't exists ?

**Comment by marlon-bain** [comment]
The documentation website changed. It's now at https://vincit.github.io/objection.js/api/model/static-properties.html#static-columnnamemappers

**Comment by marlon-bain** [comment]
The documentation website changed. It's now at https://vincit.github.io/objection.js/api/model/static-properties.html#static-columnnamemappers
