### ISSUE TITLE
Extending page function

### ISSUE THREAD

**Issue by rickysullivan** [Vincit/objection.js#1262]
I've created a custom paging plugin. I'm trying to get the results from the query into my plugin's `customPagination` method.

```
CommsLog.query()
    .where({
        Client: `${encodeURIComponent(request.params.client)}`
    })
    .customPagination()
    .throwIfNotFound();

```

**Comment by koskimas** [comment]
Sorry, I once again clicked the wrong button. I was meant to leave a comment.

I can't do anything with this report. You provide no information about what the `customPagination` method. What's the implementation, what does it do currently, and what do you want it to do.

**Comment by rickysullivan** [comment]
I was very vague in my question. I was rushing out the door after a frustrating afternoon. I was under the impression plugins could alter the query result. I'm still new to Objection.js.

I basically want to add meta data  to my paginated results.

```
{
    "results": [
        ...
    ],
    "total": 252,
    "page": 6,
    "links": {
        "firstPage": "/comms-log?page=0&pageSize=10",
        "prevPage": "/comms-log?page=5&pageSize=10",
        "nextPage": "/comms-log?page=7&pageSize=10",
        "lastPage": "/comms-log?page=26&pageSize=10",
    }
}
```

Basically returning a [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS#Example) like result.

After thinking about this, I could probably just map over my query results.

**Comment by koskimas** [comment]
Yeah, still no code :smile: All I can say is that custom functions do work.

**Comment by rickysullivan** [comment]
That's cool. I never asked for you to build anything. What I was looking for was some guidance for a way to edit the results of a query before returning them. I figured it out, `runAfter` was what I was looking for.

```
module.exports = Model => {
  class CustomPaginationQueryBuilder extends Model.QueryBuilder {
    hyperPage(page, pageSize) {
      return super.page(page, pageSize).runAfter(
        ({ results, total }) => {
            return { 
                //custom paginated results object
            }
        })
    }
  }

  return class extends Model {
    static get QueryBuilder() {
      return CustomPaginationQueryBuilder;
    }
  };
};

```

```
UserAction.query()
  .where({
    Client: request.params.client
  })
  .hyperPage(request.query.page, request.query.pageSize)
  .orderBy(
    request.query.orderBy || "ACTIONTIME",
    request.query.sortOrder || "desc"
  );
