### ISSUE TITLE
Plugins not working with class inheritance?

### ISSUE THREAD

**Issue by calvinl** [Vincit/objection.js#1263]
Hi, 

I've been at this for awhile so I'm posting this to make sure it's not a bug on Objection.js's side.

I have a `Base` class where I've created a custom validator:

```js
import { Model } from 'objection';
import YupValidator from './YupValidator';

export default class Base extends Model {
  static modelPaths = [__dirname];

  static createValidator() {
    return new YupValidator();
  }
}
```

From there, I have a User class that extends Base, along with some mixins:

```js
const MixinModel = Unique({ fields: ['email'], identifiers: ['id'] })(Base);

class User extends MixinModel {
  static tableName = 'users';
  someMethod() {
    return "Hello";
  }
}
```

Then, I have a 3rd class that extends User:

```js
class Admin extends User {

}
```

This all seems to work and I can access the instance methods I've inherited from the User class in instances of my Admin class. 

Problem is, the plugins I've added to User don't seem to be active in the Admin class. In this particular example, I'm using [objection-unique](https://github.com/seegno/objection-unique/) which validates fields for uniqueness. I would've expected creating a new Admin user (that's using the same table as User) would throw an error when trying to create one with the same username, however, instead of getting an error from the plugin, I get an error from the database (unique key error). If I remove the unique key constraint in the database, it goes through just fine, leading me to believe that the plugin isn't being passed along to the extended model Admin. 

Am I doing something wrong?

**Comment by koskimas** [comment]
Did you override any hooks like `$beforeInsert`? objection-unique implements it's stuff by overriding the hooks and if you override them and don't call `super`, you break the plugin.

I hope you are also aware that `objection-unique` in no way guarantees the uniqueness? It only creates a `select` query in a before hook and checks if items exists and then continue if they don't . It's trivial to create a concurrent situation where this breaks. You should catch the database unique violation error and use that instead. That's the correct way to guarantee uniqueness. You can use the `objection-db-errors` plugin to catch the error using a nicer API.

**Comment by calvinl** [comment]
Thanks for @koskimas. I was definitely missing a `super`. 🤦‍♂️
