### ISSUE TITLE
upsertGraph with relation over composite key does not work properly anymore

### ISSUE THREAD

**Issue by falkenhawk** [Vincit/objection.js#1265]
It looks like a regression sneaked in in v1.6.4. When upserting a graph with a model + relation with composite key, the values for foreign columns are not carried over from the base model. Instead they are NULL, which breaks and throws an error (of course only if columns are NOT NULL, otherwise the records would be inserted, but probably not related).

It worked until v1.6.3.

Please find the reproduction template attached:
[reproduction-template.zip](https://github.com/Vincit/objection.js/files/3017733/reproduction-template.zip)

**Comment by koskimas** [comment]
Jesus christ this fucking upsertGraph.. I'll remove the whole fucking thing one day. I'll try to find time to fix this within the next month.

**Comment by falkenhawk** [comment]
@koskimas nooo please don't remove it, I know you are kind of regretting adding this because of all the headaches it sometimes causes, but it's really a brilliant feature :) Thank you, I will stick with 1.6.3 for now

**Comment by koskimas** [comment]
Yeah, I thing we are stuck with it :smile: It's just that no matter how many tests I write, there's always some way to use it that I haven't considered and it breaks

**Comment by koskimas** [comment]
Thanks for the reproduction by the way. Sorry for lashing out like this. Having a bad day :grimacing:

**Comment by koskimas** [comment]
The fix was really easy this time. A new version coming up.

**Comment by flipace** [comment]
@koskimas i can't thank you enough. can we buy you a beer?

**Comment by koskimas** [comment]
Thanks, but I'm also the person who broke it :smile:

**Comment by koskimas** [comment]
1.6.6 is now released
