### ISSUE TITLE
Support for graph upserts with repeated items?

### ISSUE THREAD

**Issue by locpd** [Vincit/objection.js#1268]
I have two models: Movie and Person. I'm using ManyToManyRelation on Movie model like this:

```
class Movie extends Model {
  ...
  static relationMappings = {
    crew: {
      relation: Model.ManyToManyRelation,
      modelClass: Person,
      join: {
        from: 'movie.id',
        to: 'person.id',
        through: {
          from: 'movie_person.movieId',
          to: 'movie_person.personId',
          extra: ['job']
        }
      }
    }
  }
}
```
The `job` extra property specifies the job that a person takes in a movie. The thing is, a person can have different jobs in a movie, e.g. 'director', 'writer', 'producer', 'editor'...

However if I run this:
```
Movie.query().upsertGraph({
    id: 1,
    crew: [{
      id: 3,
      job: 'director'
    }, {
      id: 3, // notice person #3 is repeated here with a different job
      job: 'producer'
    }]
  }, {
    relate: true,
    unrelate: true
  })
```
there will be two rows inserted to movie_person, both with the same data, namely:
movie_id: 1
person_id: 3
job: 'producer'

Is there any way to correctly insert repeated related items with different extra properties, or is this simply not supported?

**Comment by koskimas** [comment]
1. You can use `#ref` and `#id` so that you only have the id once
2. You can create a relation for the pivot table of the m2m relation and insert the join rows there instead of relating the relation itself.
3. Don't use upsertGraph.
