### ISSUE TITLE
'opt.old' returns current 'this' instead of previous values when using upsertGraph

### ISSUE THREAD

**Issue by adefrutoscasado** [Vincit/objection.js#1269]
I have just found out the complexity behind this beautiful method in other reported issues. So Im not sure if Im wrong.

Im testing in the [express-es6](https://github.com/Vincit/objection.js/tree/master/examples/express-es6) example of Objection.js. I added a log for `$beforeUpdate()` in [Person](https://github.com/Vincit/objection.js/blob/master/examples/express-es6/models/Person.js) model to check the value of `opt.old`.

```
async $beforeUpdate(opt, queryContext) {
  await super.$beforeUpdate(opt, queryContext);
  console.log('beforeUpdate')
  console.log(opt.old)
}
```

The method that call the `upsertGraph` is (no changes):

```
Person.query(trx)
  // For security reasons, limit the relations that can be upserted.
  .allowUpsert('[pets, children.[pets, movies], movies, parent]')
  .upsertGraph(graph)
```

The problem is here, after creating a new Person (correctly):

```
POST localhost:8641/persons

{
  "firstName": "firstValue",
  "lastName": "firstValue"
}
```
When using upsertGraph endoint:

```
PATCH localhost:8641/persons/1/upsert

{
  "firstName": "secondValue",
  "lastName": "secondValue"
}
```

The value of `opt.old` is the current data being submited (`this`) instead of previous one:
```
PATCH /persons/1 200 33.155 ms - 124
beforeUpdate
Person { firstName: 'secondValue', lastName: 'secondValue', id: 1 }
```
Is it correct? Or Im missing something?

**Comment by koskimas** [comment]
Given this query:

```js
const person = await Person.query().findById(id)
await person.$query().patch({ foo: 'bar' })
```

`opt.old` in `$beforeUpdate` would just be the `person` and `this` would be the `{ foo: 'bar' }` object (converted into a model instance).

`upsertGraph` and the normal `query().patch()` don't fetch the rows before they update them. Consider this query:

```js
Person.query().patch({ foo: 'bar' }).where('firstName', 'Jennifer' })
```

If objection fetched the model instances to populate `opt.old`, what would happen if the query affected a million rows? Objection would fetch a million rows and that would destroy the performance.

Therefore `opt.old` is only available in very specific situations.
