### ISSUE TITLE
Inserts failing with bindTransaction query

### ISSUE THREAD

**Issue by tmeinders** [Vincit/objection.js#127]
I am seeing this error after bumping up to the 0.5 rc:

Error: model is already an instance of another Model
       at Function.ensureModel

It appears it is failing the check with the AnonymousModelSubclass generated when using bindTransaction. If we use Person.bindTransaction(trx).query().forUpdate().insert(personInstance)

It will fail on the personInstance being an instance of Person and query (from Person) being an instance of AnonymousModelSubclass.

**Comment by koskimas** [comment]
Thanks for reporting this. The check in the ensureModel is actually pretty useless. I'll remove it and publish a new RC version today (Finnish time).
