### ISSUE TITLE
virtual attributes are not serialized to JSON when returned in koa middleware

### ISSUE THREAD

**Issue by capaj** [Vincit/objection.js#1270]
we had this working correctly in 1.6.3, but after upgrading to 1.6.6 we lost all virtual attributes in the JSON we get back from the API

**Comment by koskimas** [comment]
Let's try this again, this time with some information. There are tests for virtual attributes. They all pass.

**Comment by capaj** [comment]
I have this model: 
![image](https://user-images.githubusercontent.com/1305378/55337668-6c004100-549f-11e9-9d21-5c1b8fe5b6e3.png)
and calling toJSON produces same result in both 1.6.3 and 1.6.6:
![image](https://user-images.githubusercontent.com/1305378/55337344-c3ea7800-549e-11e9-8d71-1a8d3f94b6b7.png)
logs:
![image](https://user-images.githubusercontent.com/1305378/55337361-cd73e000-549e-11e9-9b28-fbffe3624ac7.png)

but I when I return this in koa middleware, the virtual attributes are not included-this is the payload I get for 1.6.3
![image](https://user-images.githubusercontent.com/1305378/55337791-9ce07600-549f-11e9-9f6e-a8c54cee22af.png)

this is the payload I get for 1.6.6
![image](https://user-images.githubusercontent.com/1305378/55337939-e335d500-549f-11e9-8f32-9f5527398138.png)

no other dependency has changed in my stack.

**Comment by koskimas** [comment]
If `toJSON()` works as expected, how could this be objection's fault? Unless koa somehow passes in an object with `{ virtuals: [] }` or `{ virtuals: false }` to `toJSON`. I'm afraid I'll need a reproduction for this. There's a test case for nested virtuals too and it works.

**Comment by koskimas** [comment]
If not a reproduction, at least I'll need something more to work with so that I can reproduce this.

**Comment by capaj** [comment]
I'll close this for now and reopen only if I can add a unit test.

**Comment by koskimas** [comment]
Found the bug. Sorry about this. I'm releasing 1.6.7 right now.
