### ISSUE TITLE
Question: Is there a way to acces data which were inserted in the $afterInsert or $beforeInsert hook?

### ISSUE THREAD

**Issue by capaj** [Vincit/objection.js#1273]
as per title

**Comment by koskimas** [comment]
No idea what that means. Please spend some time writing these issues. I'm not a mind reader. Code examples are always nice.

**Comment by capaj** [comment]
Right. I was looking for the parameters passed to the query builder.

Like if I do:
```
Usermodel.query().insert({name: "Jesus"})
```

Can I get the `{name: "Jesus"}` param in the $afterInsert anyhow?

I could look at this, but `this `might have virtuals and other props I am not interested in.

**Comment by koskimas** [comment]
You should use `this`. Virtuals are not yet added at that point.
