### ISSUE TITLE
How do I insert into a table that references key from another table?

### ISSUE THREAD

**Issue by ankurkaushal360** [Vincit/objection.js#1275]
Let's say I have a table called `Person` that has a relation mapping like this:

```
static get relationMappings () {
    return {
      address: {
        relation: Entity.BelongsToOneRelation,
        modelClass: Address,
        join: {
          from: 'Person.AddressId',
          to: 'Address.AddressId'
        }
      }
  } 
```

When I try to insert into `Person` like this (keep in mind, `Person` can have only one address, idea is we can add family members to an address):

```
 await Person
        .query()
        .insert(person)
```

It can't find the `AddressId` & query fails with `ER_NO_DEFAULT_FOR_FIELD: Field 'AddressId' doesn't have a default value`. How do I `insert` into `Person` only but still relate to an existing `Address`?

**Comment by koskimas** [comment]
Just give value to the foreign key or use insetrGraph.

**Comment by ankurkaushal360** [comment]
`Just give value to the foreign key`: Sorry, what do you mean by that?

**Comment by koskimas** [comment]
Your problem is that the foreign key `AddressId` doesn't have a value. Well give it a value :smile: 

```js
person.AddressId = theIdOfTheAddressYouWantToRelate

await Person
        .query()
        .insert(person)
```

**Comment by koskimas** [comment]
Another option is not make the `AddressId` nullable. Now you have made it non-nullable so obviously you have to provide a value on insert.

**Comment by ankurkaushal360** [comment]
You're right. Also, if I were to use `insertGraph` how would I avoid inserts into `Address`?

**Comment by koskimas** [comment]
Use the `relate` option. But no need to use `insertGraph` here.

**Comment by ankurkaushal360** [comment]
Yeah that would be unnecessary for an `insert` like this. I really with we had some sort of mechanism to automatically detect foreign keys. Thank you for the prompt reply 👍

**Comment by koskimas** [comment]
What do you mean? That mechanism is on the db. No sense in trying to impement that in code.

**Comment by koskimas** [comment]
You even got an error with a near-perfect message describing the problem. You just didn't understand it.

**Comment by ankurkaushal360** [comment]
Sorry, I meant if objection filled out the foreign key since we have a relationship mapping defined.

**Comment by koskimas** [comment]
So `person` you are inserting has an `address` object with an id? In that case that's not a single row so SQL `insert` cannot work there. The object you are inserting is in fact a graph and you need to use `insertGraph`.

```js
await Person
  .query()
  .insertGraph(person, { relate: ['address'] })
```

that should do the trick.

**Comment by koskimas** [comment]
Objection cannot fill out those foreign keys automatically because sometimes people don't want that and it would be misleading, if not a bug, if objection did that. At least it would be very confusing.

You can modify your model to work like this if you want. For example like this:

```js
class Person extends Model {
  $beforeInsert(ctx) {
    if (this.address) {
      this.AddressId = this.address.id
    }
    return super.$beforeInsert(ctx)
  }
}
```
