### ISSUE TITLE
Allow relate but disallow creation of related record in upsertGraph

### ISSUE THREAD

**Issue by sebinbabu** [Vincit/objection.js#1276]
How do I allow the insertion of related IDs (using relate, referencing existing records) but disallow the creation of a record without ID (i.e. without an id / relation record doesn't exist in db), using upsertGraph?

**Comment by koskimas** [comment]
I have no idea what this means. Please create a new issue with some examples.

**Comment by koskimas** [comment]
Maybe `{ related: true, noInsert: true }`
