### ISSUE TITLE
Typings for modifyEager do not reflect documentation

### ISSUE THREAD

**Issue by willsoto** [Vincit/objection.js#1277]
It looks like the typings for [`modifyEager`](https://vincit.github.io/objection.js/#modifyeager) are slightly out of date when compared with the documentation. [According to the docs](https://vincit.github.io/objection.js/#modifiers), the following is allowed:

```ts
Person
  .query()
  .eager('[movies.actors, pets]')
  .modifyEager('movies', ['goodMovies', 'orderByName'])
  .modifyEager('pets', 'dogs')
```

Notice the second argument to `modifyEager` can also be `string | string[]`

TypeScript raises an error when it is used like this:

```
error TS2345: Argument of type 'string[]' is not assignable to parameter of type '(builder: QueryBuilder<Model, Model[], Model[]>) => void'.
  Type 'string[]' provides no match for the signature '(builder: QueryBuilder<Model, Model[], Model[]>): void'.

11       .modifyEager('movies', ['goodMovies', 'orderByName']);
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The code runs just fine when using `string | string[]`

---

If this issue is valid, I am happy to open a PR to correct the typings.

**Comment by koskimas** [comment]
Yep, this is a valid issue. A PR would be highly appreciated!
