### ISSUE TITLE
Missing typings for modifiers

### ISSUE THREAD

**Issue by willsoto** [Vincit/objection.js#1278]
Would it be possible to add typings for [`Model.modifiers`](https://vincit.github.io/objection.js/#modifiers)? They seem to be missing at the moment.

They could be something like:

```ts
export interface Modifiers {
   [name: string]: (builder: QueryBuilder<Model>) => QueryBuilder<Model>;
}

// ...

export class Model {
  static modifiers: Modifiers;
}
```

I'm not sure if the types can be narrowed somehow to only point to the "current" model...

---

If this issue is valid, I am happy to open a PR to correct the typings.

**Comment by koskimas** [comment]
`modifiers` used to be called `namedFilters`. Is there types for those? You could just copy the types. Anyway, a PR would be great!

**Comment by willsoto** [comment]
[This](https://github.com/Vincit/objection.js/blob/master/typings/objection/index.d.ts#L305-L311) is the closest thing I found. It seems close, but I don't believe the return value should be `void`. I feel like it should return a `QueryBuilder`, right?

**Comment by koskimas** [comment]
The return value is in fact void. All query builder methods mutate the builder.
