### ISSUE TITLE
insertGraph manipulation on the server with typescript

### ISSUE THREAD

**Issue by Stephane-Peyroutet** [Vincit/objection.js#1279]
Hi,

I'm not sure if this question/issue is related to Objection or Typescript, but here it is :

I'm trying to get back the id created after an insertGraph on the server side.
Here is an excerpt from the example/express-ts/api.ts file.
```
router.post('/persons', async (req, res) => {
    const graph = req.body;
    const insertedGraph = await transaction(Person.knex(), trx => {
      return (
        Person.query(trx)
          // For security reasons, limit the relations that can be inserted.
          .allowInsert('[pets, children.[pets, movies], movies, parent]')
          .insertGraph(graph)
      );
    });

    res.send(insertedGraph);
  });
```
At this point, just before or after res.send(), what would be the best way to get the 'id' of the newly created object on the server.
In Typescript, the returned value is treated as a Person[] whereas it's an object and I currently define insertedGraph as any in order to access the id.

Is there any way to modify or cast the returned value ?
Is there a better way to access/manipulate the insertedGraph value ?

**Comment by koskimas** [comment]
The typings should be improved. The output is `Person` if the input is an object, and `Person[]` if the input is an array.

**Comment by cliedeman** [comment]
The typings look good.

body is probably any and needs to be narrowed. 
Something like

`const graph: Partial<Person> = req.body;`

should work

**Comment by koskimas** [comment]
Oh, ok. Thanks @cliedeman!
