### ISSUE TITLE
Simple where clause on relation

### ISSUE THREAD

**Issue by roux1max** [Vincit/objection.js#1289]
Hi there !

First of all, thanks for your work ! I've been using Objection for a few days now and I still can't figure a way to create a "simple" query with a where clause on a relation table. Maybe I'm just dumb (that's a possibility).

So here is my use case. I have a User table and a Role table. My User table has a BelongsToOneRelation with the Role table named "role". And I just want to retrieve one User matching a dynamic first filter and a second filter on its Role.

Here is the query I built (it seems kind of an overkill):
```javascript
// filter can be something like { username: 'toto' }
User.query()
  .whereExists(User.relatedQuery('role').where('slug', 'admin'))
  .andWhere(filter)
  .eager('role')
  .first()
```

Any info on that would be appreciated.

Thanks !

**Comment by koskimas** [comment]
That should actually work. I don't know why it doesn't. What are you getting as a result? Is it nothing or are you getting the wrong user? This should work and we need to figure out why it doesn't.

Here's another way to do that query using joins.

```js
User.query()
  .joinRelation('role')
  .where('role.slug', 'admin')
  .andWhere(filter)
  .eager('role')
  .first()
```

**Comment by koskimas** [comment]
Actually that could be simplified to

```js
User.query()
  .joinEager('role')
  .where('role.slug', 'admin')
  .where(filter)
  .first()
```

**Comment by koskimas** [comment]
Even less lines, but probably not simpler :smile: 

```js
User.query()
  .joinEager('role')
  .findOne({ ...filter, slug: 'admin'})
```

**Comment by roux1max** [comment]
@koskimas No no the current query works great but just seemed reaaaaaallly complicated for a simple select. Thanks for the tips, I did'nt explore the `joinEager()`, should have!

Issue closed ^^

**Comment by koskimas** [comment]
Oh, ok. Objection is more like a query builder. There's rarely any magic to how things are done. Usually it's just SQL wrapped in some helpers. So many times the first thing to do is to think how this could be done in plain SQL, and then try to find how to express that query using objection's helpers. In this case this way of thinking could have lead you to `joinEager`.

**Comment by radiumrasheed** [comment]
> Oh, ok. Objection is more like a query builder. There's rarely any magic to how things are done. Usually it's just SQL wrapped in some helpers. So many times the first thing to do is to think how this could be done in plain SQL, and then try to find how to express that query using objection's helpers. In this case, that way of thinking could have lead you to `joinEager`.

my SQL skills are poor 😢`.. that's why I run towards **objection.js**
_now no running away_
