### ISSUE TITLE
Default transformation before query

### ISSUE THREAD

**Issue by appedemic** [Vincit/objection.js#129]
Is it possible to define a default parse/format for a field at query level? I have two practical cases. One is a table with a binary field 'image' where I always want a base64 representation of the field. Now every time I query the model I need to do:

```
Model.query().select(Model.raw("encode(image, 'base64') AS image")
```

Another case is when using together with PostGIS and I want to store a position. At Model level I always want a {latitude, longitude} representation. Now every time I query the model I have to do:

```
Model.query().select(Model.raw("st_asgeojson(position) AS position"))
```

Is there a way to make this field conversion default for a specific field? Similar to $parseJSON/$formatJSON but then before the query gets executed?

**Comment by koskimas** [comment]
Check out [`$formatDatabaseJson`](http://vincit.github.io/objection.js/#_s_formatdatabasejson) and [`$parseDatabaseJson`](http://vincit.github.io/objection.js/#_s_parsedatabasejson) methods.

**Comment by appedemic** [comment]
The problem for me is that $parseDatabaseJson is performed after the query and not before.

In the case of the image, I already get a Buffer object, I want PostgreSQL to convert to base64 before it even gets to Objection.

Especially with the second example, the represtentation for a geometry is a long hash and nodeJS doesn't have the knowledge to convert it into latitude/longitude so it has to be done by PostgreSQL before returning the result.

**Comment by elhigu** [comment]
You could probably use postgresql views to implement automatic conversion in database side (http://www.postgresql.org/docs/current/static/sql-createview.html).

Other way might be to use some `onBuild` hook to rewrite `.select()` part of builder in case if certain columns are queried... I don't know how that would be exactly possible implemented...

**Comment by koskimas** [comment]
There is no easy way to do what you want in objection. Any such transformation would need to be done in knex since knex doesn't provide any AST tree or other that we could transform in objection.

You could of course override the select method for the query builder of that model, but its uuuglyyyyh:

```js
const _ = require('lodash');
const objection = require('objection');

const selectArgMap = {
  image: "encode(image, 'base64') AS image",
  position: "st_asgeojson(position) AS position"
};

class CustomQueryBuilder extends objection.QueryBuilder {
  select() {
    return super.select.apply(this, _.map(arguments, arg => {
      return selectArgMap[arg] ? Model.raw(selectArgMap[arg]) : arg;
    }));
  }
}

YourModel.QueryBuilder = CustomQueryBuilder;
YourModel.RelatedQueryBuilder = CustomQueryBuilder;
```

You should probably solve this on the database level as @elhigu suggested.

**Comment by koskimas** [comment]
And if you want to always select everything, you could do this:

```js
const objection = require('objection');

class CustomQueryBuilder extends objection.QueryBuilder {
  constructor(...args) {
    super(...args);
    this.onBuild(builder => {
      // This method is called each time a query is executed.
      builder.select('... do your selection here ...');
    });
  }
}

YourModel.QueryBuilder = CustomQueryBuilder;
YourModel.RelatedQueryBuilder = CustomQueryBuilder;
```

**Comment by appedemic** [comment]
Thanks for the suggestions. A custom query builder would work but it quickly becomes ugly having to deal with a lot of different cases of select that need to be transformed. I'm going to try to solve this with a view
