### ISSUE TITLE
Question: Enforce a JSON schema throug related table

### ISSUE THREAD

**Issue by luismaldonadov** [Vincit/objection.js#1290]
Hello community, I'm implementing an interesting solution that I will be explaining here.

**A** table holds the JSON schema definition in a column for what I call  ProductType, and **B** table holds the values for that reference schema, right now I can access A table through B by a foreign key and later on validate the schema client side , also what I will implement to validate the schemas server side is this [See: is_jsonb_vaalid](https://github.com/furstenheim/is_jsonb_valid) on an UPDATE/INSERT trigger. 

My question is, is there a way to enforce this schema validation in objection.js? One thing to note is that **A** table that contains schemas are generated dynamically and I don't hold the static reference for any of those schemas.

Thanks in advance!

**Comment by koskimas** [comment]
Nope, but this doesn't seem like something an ORM should do. Can't you just register before update and before insert triggers that run the validation?

**Comment by luismaldonadov** [comment]
Yes, is_jsonb_valid does exactly that. Thanks for letting me know that this is out of an ORM scope. 

Thank you.

**Comment by koskimas** [comment]
Oh, sorry I missed the trigger part of your first message. I'm confused, why do you need ORM support for if the validation is done in the db? You can install those triggers using knex migrations (the recommended way to handle schema with objection). What else does this require from an ORM?

**Comment by koskimas** [comment]
@luismaldonadov Could you explain this to me? What would you like objection to handle here?

**Comment by luismaldonadov** [comment]
What I thought is to handle the validation before it translates to a query to the server but it thinks it is to complex to handle like this, unnecessary complexity, and it could be handled server-side so it is not like i can't handle it, just a step before the query.
