### ISSUE TITLE
Question: How do I model this query? (fetching list of contacts of a child)

### ISSUE THREAD

**Issue by sebinbabu** [Vincit/objection.js#1295]
Here's are the relations:
users: id(PK), parentId(FK => users.id)
contacts: id(PK), userId(FK => users.id)

User.children is a HasMany relationship from User.id to User.parentId
User.contacts is a HasMany relationship from User.id to Contact.userId

User.query().eager('[contacts, children.contacts]`); gets me all the contacts of the User and its children, but it's in a hierarchical manner. 

How do I write an Objection.js query to get all contacts of a relation including those of the children, as a single linear result, so that i can use LIMIT and OFFSET too as well?

**Comment by koskimas** [comment]
Here's one way

```js
const contacts = await Contact.query()
  .joinRelation('user.parent')
  .where('user.id', userId)
  .orWhere('user:parent.id', userId')
```

**Comment by sebinbabu** [comment]
Thanks a lot for this, it works.
Is the same possible with an instance of the User model?

**Comment by koskimas** [comment]
This is possbible of course

```js
const user = await User.query().findById(userId)
user.contacts = await Contact.query()
  .joinRelation('user.parent')
  .where('user.id', user.id)
  .orWhere('user:parent.id', user.id)
```

but that's probably not what you mean. Could you elaborate?
