### ISSUE TITLE
When does upsertGraph attempt to insert a model, as opposed to relate to it?

### ISSUE THREAD

**Issue by GreatSchool2** [Vincit/objection.js#1299]
Hi, I was curious as to why upserting this object with `relate: true`:

```javascript
{
   "status":"1",
   "identifier":"Team",
   "users":[
      {
         "id":89,
         "login_name":"person@website.ca",
         "role":{
            "id":2,
            "display_name":"Disc Jockey",
            "name":"dj"
         },
         "team_admin":false
      },
      {
         "id":2,
         "login_name":"person2@website.ca",
         "role":{
            "id":1,
            "display_name":"Admin",
            "name":"admin"
         },
         "team_admin":true
      }
   ]
}
```

generates queries that insert the "users" rather than relates to them. 

I know that in the absence of a reproduction, your ability to diagnose the specific issue is limited. I was just wondering why the presence of the "id" property doesn't automatically prevent insertions. 

Team relations, for reference:
```javascript
  static get relationMappings() {
    return {
      users: {
        relation: DatabaseModel.ManyToManyRelation,
        modelClass: User,
        join: {
          from: 'team.id',
          through: {
            from: 'team_membership.team_id',
            to: 'team_membership.user_id',
            extra: ['team_admin']
          },
          to: 'users.id'
        }
      },
    };
  }
```

If there is no explanation for it within the objections framework, I'll continue to hunt for the cause within my own code rather than check the documentation, but I did want to inquire here quickly. Thank you.

**Comment by koskimas** [comment]
If you aren't using `insertMissing: true`, I don't think this should generate any inserts other than the root (assuming `identifier` isn't the primary key, or is it?) and the pivot table rows. There could be a bug here. Could you try to reproduce this using the `reproduction-template.js` file or some other method?

**Comment by koskimas** [comment]
@GreatSchool2 Did you solve this?

**Comment by GreatSchool2** [comment]
Yeah, the issue had to do with how IDs are detected on an object. I traced the logic to:

https://github.com/Vincit/objection.js/blob/32a90c1c1e1ab808fa4562635417006a53ccfc36/lib/model/modelColPropMap.js#L5

and observed that since my constructors (which took an optional `copy` argument that defaulted to an empty object) were just assigning `this.id = copy.id`, the `id` property never showed up in the difference. I also had implemented my own `$parseDatabaseJson` which used these constructors.

**Comment by koskimas** [comment]
Oh, ok. Objection doesn't really use constructors for anything. If you want, you can override and use the `fromJson` static method instead.
