### ISSUE TITLE
Allow list for innerJoinRelation?

### ISSUE THREAD

**Issue by ozum** [Vincit/objection.js#130]
Hi,

There is `allowEager` for `eager`. Is there or will be there `allowInnerJoinRelation` for `innerJoinRelation` (v0.5.0)?

Thanks,

**Comment by koskimas** [comment]
Hi,

if we go down this road, soon we'll have `allowWhere`, `allowSelect`, `allowOrderBy` etc. Since the possible values to the `innerJoinRelation` are simple scalars, it is easy enough to do this ad-hoc.

So sorry, I don't think this will happen.
