### ISSUE TITLE
Is there way to change how fields from eager add to the main query?

### ISSUE THREAD

**Issue by onufriievkyrylo** [Vincit/objection.js#1300]
I need to change selected column from the eager like this
```js
raw(`case when ${context.userId} = "Posts"."userId" then ?? else ?? end`, [
    'user.fullName',
    raw('regexp_replace(??, \'[^^]\\m(\\w)\\w*\', \' \\1\', \'g\')', ['user.fullName'])
]).as('user:fullName')
```
But when I add this raw to the .select it selected before default select from eager. Is there some way to change order or replace select that added by eager. I couldn't do that with eager modifiers beause i need access to the main query here `Posts.userId`

**Comment by onufriievkyrylo** [comment]
Maybe JOIN LATERAL for eager could help me. But I don't know how to make eager use LATERAL

**Comment by koskimas** [comment]
The selects are added to `eager` in the order you add them.

**Comment by onufriievkyrylo** [comment]
My problem is about relation between eager join subquery and main query. I have my chain of modifiers in my joined relation like that `[user(short), location(full), images, invited(short)]` and I want to replace one of of columns which selected in user with raw I show before. I couldn't do that with modifiers of joined model because it's depends on main query `${context.userId} = "Posts"."userId"`. So i try to replace it added the raw to the main query but it always added before columns from the eager.
```sql
select "Post"."id",
case when 2 = "Posts"."userId"
  then "user"."fullName"
  else regexp_replace("user"."fullName", '[^^]\\m(\\w)\\w*', ' \\1', 'g')
end as "user:fullName",
"user"."id" as "user:id",
"user"."fullName" as "user:fullName" ...
```
so is no possible to override the column selection.
Maybe can you advice some workaround or some possibility to change the order of selections?

**Comment by koskimas** [comment]
So you are using `joinEager`? Could you post the actual code and model definitions here so that I have something to work with. The best option would be if you could create a reproduction I can debug. There's a `reproduction-template.js` file in the repo root you could use as a starting point.

Without knowing exactly what you are doing and how you have set up objection, I could suggest using `joinRelation` with the normal `eager` instead of `joinEager`. I could try to improve `joinEager` to work in this case, but for that, I need a full reproduction.

**Comment by koskimas** [comment]
I'll try to guess:

You originally tried this

```
Post.query().joinEager('users(short)', {
  short: query => {
    query.select(
      raw(`case when ${context.userId} = "Posts"."userId" then ?? else ?? end`, [
        'Users.fullName',
        raw('regexp_replace(??, \'[^^]\\m(\\w)\\w*\', \' \\1\', \'g\')', ['Users.fullName'])
      ]).as('fullName')
    )
  }
})
```

?

In that case, why are you using `Posts.userId` instead of `Users.id` which is the same value when you are joining. Simply replace `Posts.userId` by `Users.id` in that query and it should work.
