### ISSUE TITLE
Relation expression of a many to many relationship + filter/modifier + eager other relation

### ISSUE THREAD

**Issue by rodrigosanchezg8** [Vincit/objection.js#1301]
Hello,
First of all, keep up the good work, i hope to introduce objection js to my production server soon and many people in my company will be using it. That's why i post this: I want to learn a lot about Objection js and do things as best as possible.

I have a problem using an eager relation expression on a many to many relation + filter with a modifier + eager a relation of the many to many table.

I have the following relationship in the model "phase"

```
joinSiblings: {
    relation: this.HasManyRelation,
    modelClass: __dirname + '/phases-siblings';
    join: {
        from: 'phases_siblings.phaseId',
        to: 'phases.id'
    }
},
```

"joinSiblings" represents the model class, phases_siblings, which is the many to many join table between phases and phases. phases_siblings has the "type" attribute, also phaseId and linkedPhaseId. In this example a phase can have many sibling phases, where i only set the phases_siblings type as "preceeding" or "incoming".

In the phases_siblings objection model, i also created the proper BelongsToOne relationship to the phases:

```
phase: {
    relation: this.BelongsToOneRelation,
    modelClass: __dirname + '/phase',
    join: {
        from: 'phases_siblings.phaseId',
        to: 'phases.id'
    }
},
linkedPhase: {
    relation: this.BelongsToOneRelation,
    modelClass: __dirname + '/phase',
    join: {
        from: 'phases_siblings.linkedPhaseId',
        to: 'phases.id'
    }
}
```

I created some modifiers in the same phases_siblings model to filter the type attribute:

```
static get modifiers() {
    return {
        preceding: builder => builder.where('phases_siblings.type', 'preceding'),
        incoming: builder => builder.where('phases_siblings.type', 'incoming'),
    }
}
```

By mapping the many to many relationships this way and by using the modifier, i can make an eager relation expression like 
`joinSiblings(incoming).linkedPhase` or `joinSiblings(preceding).linkedPhase`
This would be useful to filter the join table and bring a relationship in it.

However this results in an error:

> code: 'ER_NONUNIQ_TABLE',
> errno: 1066,
> sqlMessage: "Not unique table/alias: 'joinSiblings'",
> sqlState: '42000',

Of course, because it's using the same join table twice. But i can't write alias to the join table if i am also eagering its linkedPhase relation. That's the problem.
Hence i can't use the same relation (joinSiblings) for two modifiers. I have to duplicate the joinSiblings relations on the model, and use one for the  "incoming" value and other relationship for the "preceding" value. But what if it was not only "incoming" and "preceding" but many other values in the join table "type" atttribute? I'd have to make as many relations as those values so i don't get duplicated join tables on the query?

It'd be great to use some expressions like this:

`joinSiblings(incoming) as incomingSiblings, incomingSiblings.linkedPhase, joinSiblings(preceding) as precedingSiblings, precedingSiblings.linkedPhase`

This way i can use a modifier for the join table, alias the join table, and eager a relation of the aliased join table in order not to get a duplicated table/alias.
The later relation expression currently results in:

> 'RelationDoesNotExistError: unknown relation "incomingSiblings" in a relation expression',

Could a relation expression like that be implementeed in the future? 
Or is there another approach i am missing for this rather than creating a whole view? 
(I am avoiding views because IMHO this should be able to be done with proper use of Objection js relations)

I hope i was very clear explaining the issue.
Thanks!

**Comment by koskimas** [comment]
Are you using `joinEager` or `eagerAlgorithm(Model.JoinEagerAlgorithm)` instead of the normal `eager`? You shouldn't run into these problems with the normal `eager`. Is there a particular reason for using the `joinEager`?

Have you tried modelling the `type` as an [extra](https://vincit.github.io/objection.js/recipes/extra-properties.html#join-table-extra-properties) property? That way you don't need to create the relationship through `joinSiblings`, but you can create a `ManyToManyRelation` straight to `linkedPhases` and you can still use those modifiers.

**Comment by rodrigosanchezg8** [comment]
You've saved me of keeping redundant relations in my model.
I never thought of changing the eager algoritm. I like to use JoinEager Algorithm as the default one specifying it in `defaultEagerAlgorithm` because it's only one query using Joins, and i've always tought it's the best and cleaner way (ofc not the easiest one) to do complex queries. What are your toughts on this? When is it better to use WhereIn, when is it better to use Joins?

It'd be good to mention using the default WhereInEagerAlgorithm in cases where the `extra` properties are needed, because it seems that using JoinEagerAlgorithm an unknown column error is thrown.

For further reference, this is how i did it:

Relation:
```
siblings: {
    relation: this.ManyToManyRelation,
    modelClass: this,
    join: {
        from: this.tableName + '.id',
        through: {
            from: 'phases_siblings.phaseId',
            to: 'phases_siblings.linkedPhaseId',
            extra: ['type', 'phaseId', 'linkedPhaseId']
        },
        to: this.tableName + '.id'
    }
},
```

Query:
```
return await this.query()
    .eagerAlgorithm(Model.WhereInEagerAlgorithm)
    .eager('[requirements, ' +
    ' siblings(ofTypeIncoming, ofId) as incomingPhases,' +
    ' siblings(ofTypePreceding, ofId) as precedingPhases]', {
    ofTypeIncoming: builder => builder.where('type', 'incoming'),
    ofTypePreceding: builder => builder.where('type', 'preceding'),
        ofId: builder => builder.where('phaseId', id)
    })
    .findById(id);
```

The join table JS model is no longer needed with this approach.

BTW: I think the old docs about Polymorphic relations were not added to the new ones.

Thank You @koskimas

**Comment by koskimas** [comment]
> It'd be good to mention in the docs to use the default WhereInEagerAlgorithm in cases where the extra properties are needed, because it seems that using JoinEagerAlgorithm an unknown column error is thrown.

That's [been a known bug](https://github.com/Vincit/objection.js/issues/837) for a while and I haven't found an elegant way to solve it. I could mention it in the docs for the time being.

> BTW: I think the old docs about Polymorphic relations were not added to the new ones.

Oh, thanks for pointing that out. Maybe I've missed other recipes too :smile:

**Comment by koskimas** [comment]
By the way, I don't know if you prefer to write the eager expression that way, but you can use multiline strings too. Something like this:

```js
return await this.query()
    .eagerAlgorithm(Model.WhereInEagerAlgorithm)
    .eager(`[
      requirements, 
      siblings(ofTypeIncoming, ofId) as incomingPhases, 
      siblings(ofTypePreceding, ofId) as precedingPhases
    ]`, {
      ofTypeIncoming: builder => builder.where('type', 'incoming'),
      ofTypePreceding: builder => builder.where('type', 'preceding'),
      ofId: builder => builder.where('phaseId', id)
    })
    .findById(id);
```

**Comment by rodrigosanchezg8** [comment]
Thanks! i didn't know that can be done, it's way better.

**Comment by koskimas** [comment]
You can also use the object notation:

```js
return await this.query()
    .eagerAlgorithm(Model.WhereInEagerAlgorithm)
    .eager({
      requirements: true,

      incomingPhases: {
        $relation: 'siblings',
        $modify: ['ofTypeIncoming', 'ofId']
      },

      precedingPhases: {
        $relation: 'siblings',
        $modify: ['ofTypePreceding', 'ofId']
      }
    }, {
      ofTypeIncoming: builder => builder.where('type', 'incoming'),
      ofTypePreceding: builder => builder.where('type', 'preceding'),
      ofId: builder => builder.where('phaseId', id)
    })
    .findById(id);
```
