### ISSUE TITLE
how to run multi tenant deployment

### ISSUE THREAD

**Issue by suryacaprice** [Vincit/objection.js#1303]
I have a seperate db for every client . Ex : Client 1 has db1 and client 2 has db2 and the db username and password is different for each clinet which is maintained in the tenant db . How do i automate the migration process ex : when i want to create a table in all the client databased or insert a data in all client data based . How to automate them ?

**Comment by koskimas** [comment]
You should ask those questions in some other forum. They are not really related to objection itself. Objection doesn't even handle migration, but delegates it to `knex`.
