### ISSUE TITLE
pg | JoinEagerAlgorithm "ambiguous" error on 2 joins to id field

### ISSUE THREAD

**Issue by oranoran** [Vincit/objection.js#1304]
I have a RootModel with ah Child model and a GrandChild model.
All of them are related via id fields (root.id=child.root_id, child.id=grandchild.child_id).
Trying to eagerly fetch both Children and Grandchildren when querying for RootModel.
This works well with ```WhereInEagerAlgorithm```, but fails with ```JoinEagerAlgorithm```.

Note that I also have a "date1" field which appears in both the child and grandchild. When fixing the issue with "ambigous" id field, need to make sure it doesn't fail similarly on non-ID fields with the same name.

Code:
```JavaScript
 RootModel.query(trx)
    .select('id', 'rootField')
    .where(createQuery())
    .eagerAlgorithm(Model.JoinEagerAlgorithm)
    .eager(
    '[children(childFields).grandChildren(grandChildFields)]', {
      childFields: builder => {
        builder.select('id', 'childNumber', 'date1');
      },
      grandChildFields: builder => {
        builder.select('id', 'grandchildNumber', 'date1');
      },
    });
```

Result:
```
error: column reference "id" is ambiguous
    at buildKnexQuery (...node_modules/objection/lib/queryBuilder/QueryBuilder.js:1359:63)
```

**Comment by koskimas** [comment]
That happens because the `id` is in fact ambiguous. You can see the generated SQL by chaining `debug()` to the query. You can fix this by making the column unambiguous by mentioning the table

```js
 RootModel.query(trx)
    .select('nameOfTheRootTablw.id', 'rootField')
    .where(createQuery())
    .eagerAlgorithm(Model.JoinEagerAlgorithm)
    .eager(
    '[children(childFields).grandChildren(grandChildFields)]', {
      childFields: builder => {
        builder.select('id', 'childNumber', 'date1');
      },
      grandChildFields: builder => {
        builder.select('id', 'grandchildNumber', 'date1');
      },
    });
```

**Comment by oranoran** [comment]
Thanks!

But since the query is starting out with a specific model class, I think it
would be nice for the query builder to figure out on its own that by
default fields in the root select clause should come from the table
associated with that class.

Otherwise, we end up re-stating the model-table relationship in the query,
and violating the DRY principle.

**Comment by koskimas** [comment]
Not really. You need to be explicit when you write SQL. Objection is more a query builder than an ORM. Calling the select method doesn't mean "select fields for this model'. It means "add select statement to this query". You can add subqueries, references to other tables, whatever SQL and the database allow as the values. Defaulting to the model's table would make it work different from SQL. Besides, that would be a huge breaking change at this point of the project.

**Comment by sripberger** [comment]
> Not really. You need to be explicit when you write SQL. Objection is more a query builder than an ORM. Calling the select method doesn't mean "select fields for this model'. It means "add a select statement to this query". You can add subqueries, references to other tables, whatever SQL and the database allow as the values. Defaulting to the model's table would make it work different from SQL. Besides, that would be a huge breaking change at this point of the project.

I'm not *necessarily* disagreeing with this sentiment, but I would be interested in hearing what the difference is between this situation and using filter functions to select fields from joined tables during eager loading.

For example, the following does not require me to explicitly state any table names for disambiguation purposes:

```js
Person.query().joinEager('[parent(parentFilter), children(childFilter)]', {
	parentFilter(qry) {
		return qry.select('firstName', 'lastName');
	},
	childFilter(qry) {
		return qry.select('firstName', 'lastName');
	},
});
```

Only when I want fields from the original table is this necessary, and only when using a `joinEager`.
