### ISSUE TITLE
QueryBuilderOperationSupport doesn't use QueryBuilderContext defined by QueryBuilder

### ISSUE THREAD

**Issue by jordansexton** [Vincit/objection.js#1305]
Related: #506 

`QueryBuilderOperationSupport` has its own static getters for `QueryBuilderContext` and `QueryBuilderUserContext`. These don't use the overridden context defined by the `QueryBuilder` subclass.

https://github.com/Vincit/objection.js/blob/1a191b5f155816a33e35b662c7eb903fceadafb3/lib/queryBuilder/QueryBuilderOperationSupport.js#L41-L47

Is there a way to make this class use the overridden context constructors?

**Comment by koskimas** [comment]
This is all private implementation you shouldn't be using. It may change even between patch versions.

**Comment by jordansexton** [comment]
That's fair. I'm guilty of using a couple of private APIs of Objection, `childQueryOf` being a notable one 😅
