### ISSUE TITLE
Documenting relationships with JSdoc and intellisense hinting [ help wanted ]

### ISSUE THREAD

**Issue by Mash12** [Vincit/objection.js#1307]
Using VS Code.
As relationships are needed to be described in `relationMappings` static method, **intellisense** does not show relationships as model properties. Is there any way to hint **intellisense** about the relationships and their types? Also how to document relationships correctly?

**Comment by koskimas** [comment]
I haven't used `JSdoc` in ages, but IIRC there was a way to document properties for a class even without defining them. At least you can always add a constructor and define them there. Have you considerd using typescript? VSCode works really well with typescript.
