### ISSUE TITLE
Minor mistake in docs

### ISSUE THREAD

**Issue by phormio** [Vincit/objection.js#1310]
The documentation for `Model#$transaction` refers to the static method `knex`, which appears to be a mistake.  See:

https://vincit.github.io/objection.js/api/model/instance-methods.html#transaction

**Comment by koskimas** [comment]
Nope, they are one and the same.

**Comment by koskimas** [comment]
Those functions are pretty useless and can even be misleading. They are simply implemented like this:

```js
$transaction() {
  return this.constructor.knex();
}
```
