### ISSUE TITLE
Best way to eager innerJoin + eager leftJoin relations

### ISSUE THREAD

**Issue by rodrigosanchezg8** [Vincit/objection.js#1312]
So far we indicate the eager join type on eagerOptions joinOperation. In the following example from the docs, with InnerJoin, the person must have pets and children to be fetched.

````
const people = await Person
  .query()
  .eagerOptions({joinOperation: 'innerJoin'})
  .eager('[pets, children]')
````

 However, what if we want to eager those relations using innerJoin on children and leftJoin with pets? What's the best way to do that?

**Comment by koskimas** [comment]
You can usually just use leftJoin and add some additional conditions. For example `leftJoin` + `whereNotNull(someForeignKey)` usually gets the job done. Unfortunately there's no way to use two different join types with `joinEager`. You can mix `innerJoinRelation` and `leftJoinRelation` if you don't need to actually fetch the nested items. You can also use `joinRelation` with the normal `eager` method (WhereInEagerAlgorithm).
