### ISSUE TITLE
Having whereIn deal with limits of only 1000 elements in an IN list, for Oracle.

### ISSUE THREAD

**Issue by nwolfman** [Vincit/objection.js#1314]
This is causing me to have to use the NaiveEagerAlgorithm instead of the WhereInEagerAlgorithm which is of course quite a lot slower.

**Comment by koskimas** [comment]
So oracle has a limit of 1000 elements in a `WHERE IN` statement? Is is a limit for lists in general or just `WHERE IN`? Or is it a limit for query parameters? Is this documented somewhere? I'll fix this so that the queries are automatically split to chunks of 1000 ids, but I just want to be sure about the limit.

**Comment by koskimas** [comment]
Oh and I'll only fix the `WhereInEagerAlgorithm`. `whereIn` should still only create one query.

**Comment by nwolfman** [comment]
This is in all IN clauses that have an explicit list.  So SQL like col1 in ('fred','mary',....)

**Comment by koskimas** [comment]
I won't change `whereIn` to create a group of `OR IN` expressions. `whereIn` is a query builder method that should create a single `WHERE IN` statement. I can fix this for internal stuff people have no control over, like eager.

**Comment by nwolfman** [comment]
I see your point on leaving the whereIn statements as users can do the chunking themselves.  However to push my reasoning (and if you disagree then fine) is that an user of the whereIn statements expects (as you did) for it to take an array of any length and it is just that Oracle Corp in their "infinite" wisdom put a limit on their semantics.

Either way, thanks for picking this up in the WhereInEagerAlgorithm, as that I can't code around.

**Comment by koskimas** [comment]
I didn't expect `whereIn` to take an array of any length. All databases have these limits. Most of the limits are high enough that they are rarely hit. Usually the limit is set for the total amount of parameters in a query.

Objection is a query builder for the most part. When you call a method like `whereIn` you get a `WHERE IN` statement, as simple as that. The point is to be in control of the generated SQL. In this particular case, chaining `where (foo in (...) or  foo in (...))` could work in most cases, but I don't know oracle or other dialects well enough to be sure that it wouldn't produce unexpected results in some case.

**Comment by nwolfman** [comment]
All makes sense and is reasonable.  For Oracle you can chain them forever, however you're right who knows what each DB does and Oracle should have a much higher limit.  Oracle used to limit at 256 originally for some reason.

**Comment by nwolfman** [comment]
Silly question, is this done?  Or is there a PR I could look at?

**Comment by koskimas** [comment]
I'll close this when it's done.

**Comment by nwolfman** [comment]
Thank you.
