### ISSUE TITLE
Range doesn't work in SQL server in WITH queries

### ISSUE THREAD

**Issue by fer22f** [Vincit/objection.js#1315]
In queries that have `with`,

```sql
select count(*) from (
  with a as (select * from ...),
  select * from ...
) as temp
```

doesn't work in SQL Server because (annoyingly) [it doesn't support it in subqueries](https://modern-sql.com/feature/with#sm-feature-with). One solution is that when `with` is detect in the subquery, it could merge it and be run like this:
```sql
with a as (select * from ...),
temp as (select * from ...)
select count(*) from temp
```

But I don't know if it's a bug of major notoriety. My workaround is avoiding `range` and implementing my own for my complex queries (which are a few).

**Comment by koskimas** [comment]
Rewriting the queries like that seems scary. Will that work in all possible cases? I'd rather not fix this bug because it can have unexpected consequences with some complex queries I can't even think of.

**Comment by fer22f** [comment]
It will definitely not work if someone names a query they have `temp`, which is actually rather likely. Just unfortunate that SQL Server is stupid here along with Db2.
