### ISSUE TITLE
Using dynamic imports?

### ISSUE THREAD

**Issue by johncmunson** [Vincit/objection.js#1317]
Are there any issues with using dynamic imports, as opposed to node's `require`? Both methods are "lazy", but `require` is synchronous, whereas `import` is async (returns a promise).

With require...
```
static get relationMappings() {
  const Animal = require('./Animal')

  return {
    pets: {
      relation: Model.HasManyRelation,
      modelClass: Animal,
      join: {
        from: 'persons.id',
        to: 'animals.ownerId'
      }
    }
  }
}
```

With dynamic import...
```
static get relationMappings() {
  const Animal = import('./Animal').then(animal => animal)

  return {
    pets: {
      relation: Model.HasManyRelation,
      modelClass: Animal,
      join: {
        from: 'persons.id',
        to: 'animals.ownerId'
      }
    }
  }
}
```

**Comment by koskimas** [comment]
Objection doesn't support async relation mappings, and it's not feasible to add support for it. It would change a lot of other code async as a consequence. You need to use `require` or some of the other ways to prevent require loops.
