### ISSUE TITLE
Could we enhance the oracle support to allow inserts of collections?

### ISSUE THREAD

**Issue by nwolfman** [Vincit/objection.js#1318]
When I did this I got that it was only supported in postgres. 

So having a collection and doing  (following is pseudo code, not working code)
let listOfPeople  = [{first: 'Fred', last: 'Flinstone'},{first: 'Barney', last: 'Rubble'}]

People.query.Insert(listOfPeople)

**Comment by koskimas** [comment]
So it's possible to insert multiple rows using a single query with oracle? And oracle returns the identifier of each inserted row?

**Comment by nwolfman** [comment]
Yes, and there are two ways.
https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/INSERT.html#GUID-903F8043-0254-4EE9-ACC1-CB8AC0AF3423 has all the insert syntax

1) This would be straight code.
INSERT ALL
  INTO mytable (column1, column2, column_n) VALUES (expr1, expr2, expr_n)
  INTO mytable (column1, column2, column_n) VALUES (expr1, expr2, expr_n)
  INTO mytable (column1, column2, column_n) VALUES (expr1, expr2, expr_n)
SELECT * FROM dual;
From https://www.techonthenet.com/oracle/questions/insert_rows.php

2) would be to use array binding, not sure how this would work in knex or js, however have used in java (and it's variants) with great success.  The following link might help with this, know the examples are in pl/sql, however hoping.
https://docs.oracle.com/en/database/oracle/oracle-database/12.2/lnpls/plsql-optimization-and-tuning.html#GUID-6D4A1425-64DD-4723-8AAE-87B0A51A2854

**Comment by koskimas** [comment]
Does knex support batch insert with oracle? If not, this should be first implemented there.

**Comment by nwolfman** [comment]
I think the answer is yes.  Still need to validate 100%
https://github.com/tgriesser/knex/issues/3182
