### ISSUE TITLE
.then() executing query

### ISSUE THREAD

**Issue by jstans** [Vincit/objection.js#132]
Unlike with normal promises, it seems the .then exposed on the QueryBuilder will cause the query to be executed again. So if you find yourself using .then() more than once you will find you are inadvertently running more queries than you sholuld be.

This is especially noticible in unit tests, where using something like shouldjs to check the eventual properties will call the same .then method causing the query to repeat.

Is this expected behaviour? Should I be pulling out the underlying promise to solve these issues?

**Comment by koskimas** [comment]
You should't think a `QueryBuilder` as a promise but as a [thenable](https://promisesaplus.com/). The query builder only exposes a `then` method so that it can be used like a thenable when needed, but it is only turned into a promise after the query builder's `then` is called.

```js
let promise = builder.then();
```

**Comment by jstans** [comment]
Thanks for the quick response. I realised that the Promise was being returned after the first then() shortly after posting; I for some reason thought it was a wrapped promise (or thenable - thanks for the symantics) all the way down.

So to solve this in my case I should be doing something similar to:

let promise = Person.query().insert({name: 'Bill'}).then()
promise.should.eventually.be.a.Number
promise.then(function() {
  // more logic
})

I guess it just feels slightly unnattural and potentially confusing at first, but the only alternatives would be adding a final .execute() method (effectively exactly what the .then is doing just more readable) or making the insert method's return the promise preventing further chaining. I guess neither being a great solution.

This can be marked as closed though, thanks again!

**Comment by koskimas** [comment]
Adding an `execute()` alias for `then()` for these cases is not actually a bad idea. It makes the code more readable. I'll add the method for 0.5.0 release. I'll leave this open, as a reminder for me to add the method.

**Comment by koskimas** [comment]
Fixed in 0.5.0.
