### ISSUE TITLE
Allow inserts of collections in MS SQL

### ISSUE THREAD

**Issue by fer22f** [Vincit/objection.js#1320]
Inspired by #1318, I think we could also make this happen. It looks like `knex` supports `returning` in MS SQL since forever via this syntax:

```sql
INSERT INTO test (name) OUTPUT inserted.id
VALUES ('hello world'), ('very nice'), ('amazing')
```

It returns a table with the ids in order. Is there any reason MS SQL isn't supported? It should be a quick fix.

---

I will experiment with lifting the restrictions, the problem should really be in creating tests.

**Comment by koskimas** [comment]
I have never used oracle or mssql, and there are no tests for those in objection so I have paid very little attention to these dialects. The first thing would be to add tests for both. I've tried a couple of times with very bad results (something like 3000/3800 tests failing). Even setting up the db the same way as for other databases was a huge pain in the ass. Foreign key constraints don't seem to work at all on mssql?

**Comment by koskimas** [comment]
Fixed in master

**Comment by fer22f** [comment]
:o thanks
