### ISSUE TITLE
loadRelated doesn't work

### ISSUE THREAD

**Issue by onufriievkyrylo** [Vincit/objection.js#1322]
I just simply trying to load users list for each of selected chats like that:
```js
export default class Chat extends Model {
static tableName = 'Chats'
static relationMappings = {
    users: {
      relation: Model.ManyToManyRelation,
      modelClass: 'User',
      join: {
        from: 'Chats.id',
        through: {
          from: 'ChatToUsers.chatId',
          to: 'ChatToUsers.userId'
        },
        to: 'Users.id'
      }
    },
    messages: {
      relation: Model.HasManyRelation,
      modelClass: 'Message',
      join: {
        from: 'Chats.id',
        to: 'Messages.chatId'
      }
    }
  }
}
```
```js
const chats = await Chat.query();
Chat.loadRelated(chats, 'users');
```
But this doesn't work. Even not make a sql in debug logs.

**Comment by koskimas** [comment]
Yes it does work. Feel free to try to create a reproduction. I assure you, you will fail

**Comment by devinivy** [comment]
I believe you need to await your call in order to trigger the queries: `await Chat.loadRelated(chats, 'users')`.

**Comment by onufriievkyrylo** [comment]
@koskimas @devinivy yes, I forgot `await` in this example, but with `await` it doesn't work too.

**Comment by onufriievkyrylo** [comment]
I just realize why happened. I have `defaultEagerAlgorithm` setted to `Model.JoinEagerAlgorithm`, but in internaly loadRelated use just `eager` method, so I modify my call like that:
```js
await Chat.loadRelated(chats, 'users').eagerAlgorithm(Model.WhereInEagerAlgorithm);
```
I think this is not expected behavior.
