### ISSUE TITLE
$relatedQuery and upsertGraph won't populate relation ids

### ISSUE THREAD

**Issue by flipace** [Vincit/objection.js#1323]
We just encountered an issue which seems to have been introduced with the rewrite in https://github.com/Vincit/objection.js/commit/8ecb54363757b2f614410d3754ac0d3fbc0f87ea where, when using `SomeParent.$relatedQuery('relation').upsertGraph(...)` the upserted entries won't receive the appropriate relation key.

You can find a test case for this issue here:
https://github.com/flipace/objection.js/commit/32921f0495e4fb5d31e8cd40993227bf104890a8

I checked this with 1.4.0 and there it worked fine 🙉 
It broke with the large upsertGraph rewrite, so all versions starting with 1.5.0-rc1 have this issue.

Maybe the changes which have been made to fix this: https://github.com/Vincit/objection.js/issues/1265 have to be added at some other place(s) as well?

Sorry for opening the box of upsertGraph again 🙈 - 🍫🍺🍻🥂🍷🥃🍸🍹🍾

**Comment by flipace** [comment]
after some further digging, i found that apparently the required relation is never passed here. so for other operations, it utilizes the `delegate` and then the patched _insertOperationFactory etc which ensure the proper relation to be set - this doesn't happen for the graphupserts though.

**Comment by koskimas** [comment]
updertGraph only works with the static `query` method. It used to partially work with other query methods by accident.

**Comment by koskimas** [comment]
https://github.com/Vincit/objection.js/issues/933

**Comment by flipace** [comment]
@koskimas okay - in that case, we'll adapt our code - thanks!
