### ISSUE TITLE
Json keys no longer updating

### ISSUE THREAD

**Issue by thejuan** [Vincit/objection.js#1324]
The fix for https://github.com/Vincit/objection.js/issues/1089 is a breaking change for us and I'm trying to work out whether we have been misusing the system or whether there is a bug.

Our use case is that we have a data dump field on most tables that we normalise onto the model

modelClass.columnNameToPropertyName always returns null and so the paths are empty in the call to jsonb_set

Repo:
```
const { Model } = require("objection");
const _ = require("lodash");

class Example extends Model {
  static get tableName() {
    return "example";
  }

  // From Database
  $parseDatabaseJson(json) {
    json.availabilityRequirements = _.get(json, "data.availabilityRequirements");
    return json;
  }

  // On database insert
  $formatDatabaseJson(json) {
    if (_.has(json, "availabilityRequirements")) {
      json[`data:availabilityRequirements`] = json["availabilityRequirements"];
      delete json["availabilityRequirements"];
    }
    return json;
  }
}

describe("Problem", () => {
  it("should set inner properties", () => {
    expect(
      Example.query()
        .patch({ availabilityRequirements: "some" })
        .toString(),
    ).toEqual(`update "example" set "data" = jsonb_set("data", '{availabilityRequirements}', '"some"', true)`);
  });
});

```

**Comment by thejuan** [comment]
update "example" set "data" = jsonb_set("data", '{}', '"some"', true)

**Comment by thejuan** [comment]
columnNameToPropertyName returns null for the prop name when generating the statement. 

After formatDatabaseName is called why do we need to map a col to a prop name ?

**Comment by koskimas** [comment]
> After formatDatabaseName is called why do we need to map a col to a prop name ?

See #1089

**Comment by koskimas** [comment]
I haven't considered that use case. It worked before by accident. `$formatDatabaseJson` isn't the best place to do that. Could you use `beforeInsert` and `beforeUpdate` instead?

**Comment by thejuan** [comment]
Its a large change for us. The docs for https://vincit.github.io/objection.js/api/model/instance-methods.html#formatdatabasejson are pretty clear that this method is put it into database format.
Once it's in db format it doesn't make sense to be converting column names again.

As you said here https://github.com/Vincit/objection.js/issues/1089#issuecomment-424233375
Objection touching the json field keys is a bug?

An easy fix for us is columnNameToPropertyName shouldn't return null ever, just return the unmodified key

**Comment by thejuan** [comment]
Can you elaborate on why this was closed? Why is $formatDatabaseJson the wrong place for this?
