### ISSUE TITLE
Calling instance.$query().upsertGraph() crashes objection

### ISSUE THREAD

**Issue by codeheroics** [Vincit/objection.js#1330]
Hi,

I'm trying to update Objection from v1.4.0 to v1.6.7 and am running into crashes.

For any object I instantiate using Objection, calls to `object.$query().upsertGraph()` always crash, sending me ValidationErrors like this one: `ValidationError: expected value "undefined" to be an instance of Employer`. I tried removing all validation from my models to the minimum to ensure the error wasn't on my side and am quite sure it is not.

I was able to track that this issue was introduced between v1.5.0-rc3 and v1.5.0-rc4, precisely in this commit : 5e47be71 which closed issue #1187.

I understand the commit was supposed to give more explicit errors when data given in `upsertGraph` and `insertGraph` calls was not correct, however since as the added code crashes a feature which previously worked correctly for me, I suspect it is an unwanted side-effect.

More precisely in the code, the following check was added in the consructor:
```js
class GraphUpsert {
  constructor({ rootModelClass, objects, upsertOptions }) {
    checkCanBeConvertedToModels(rootModelClass, objects);
```

When I try debugging, I can see that `objects`'s value is `undefined`, which means that the crash originates from this next chunk of code:

```js
function checkCanBeConvertedToModels(modelClass, objects) {
  asArray(objects).forEach(obj => {
    if (!isObject(obj)) {
      throw createNotModelError(modelClass, obj);
    }
  });
}
```

As without this validation my code works correctly (and data is updated correctly), I'd say this is where the error is located. Is this check not supposed to be run only for calls to `Model.query().upsertGraph({ someNewData })`?

Thanks for the help, and for the great project! :slightly_smiling_face:

**Comment by koskimas** [comment]
upsertGraph only works with the static query method. https://github.com/Vincit/objection.js/issues/933

**Comment by codeheroics** [comment]
Thanks for the quick answer.

That's definitely a big change which breaks previously working code, shouldn't it have prompted a major version release?

**Comment by koskimas** [comment]
It was never officially supported. It worked before by accident.

**Comment by sfabriece** [comment]
@koskimas I hadn't updated to the latest version of objection because this issue is not well documented. Wouldn't it make sense to add a small migration guide to the changelog for 1.5.0?
