### ISSUE TITLE
Model property name clashes with json keys if using different formats

### ISSUE THREAD

**Issue by thejuan** [Vincit/objection.js#1331]
Changes for https://github.com/Vincit/objection.js/issues/1089 mean that we can't have a property on the model that matches a key on a json field, but uses a different naming standard.

If we update the issue example to include a property with the same name as a json key it continues to alter the json key when it shouldn't. Example below.

I'd suggest modifying keyMapper to split on : and only map the left-handside

```
 TestModel.query()
        .patch({
          firstName: "Sue",
          "jsonColumn:[0][first_name]": "John",
        })


// Database output
{
  first_name: "Sue",
  json_column: '[{"firstName": "John"}]' 
}

```

**Comment by thejuan** [comment]
Was on wrong version. :)

**Comment by thejuan** [comment]
Happy to submit PR for change to keyMapper function

**Comment by koskimas** [comment]
We cannot change the keyMapper. The keys are handled that way because `:` is used as a separator with `joinEager` nested relations too. That's a design flaw I'd like to address in objection 2.0. I'll probably revert #1089 because it's causing more problems than it's fixing.

**Comment by koskimas** [comment]
Fix for 1089 has been reverted. The next patch release will contain the fix.
