### ISSUE TITLE
UpsertGraphAndFetch doesn't update when model has a constructor which sets default properties

### ISSUE THREAD

**Issue by erezmus** [Vincit/objection.js#1333]
When a Model has constructor that sets default properties, calling upsertGraphAndFetch doesn't seem to update the field to a value that matches the default value.

I've created an example in a repo here:
https://github.com/erezmus/objection-upsert-graph-and-fetch-bug

In the example, the constructor sets the `comment` field to null as a default. After inserting an entry with the `comment` field set to 'hello', it tries to update it to null with `upsertGraphAndFetch`  but that doesn't seem to do it.

**Comment by koskimas** [comment]
Override fromJson instead of the constructor. Objection doesn't use constructors (except for constructing empty objects of course)
