### ISSUE TITLE
Postgres: fetch part of a jsonb document while keeping his structure

### ISSUE THREAD

**Issue by maxmousse** [Vincit/objection.js#1337]
Hello everybody,

I'm new to objection and I'm really enjoying the json API to work with Postgres jsonb type!
However, there is a problem I can not solve so here I am to ask you a bit of help.

I am working on a small CMS project that can manage several languages. Here is the structure of the posts table:
`{
  id: primary key,
  status: enum,
  createdAt: date,
  updatedAt: date,
  content: jsonb
}`

The structure of content is one key per translation, for exemple: 
`{
  fr: {
  },
  en: {
  },
}`

What I am trying to achieve is to get posts with only one selected language in the content column. So I tried the next:
`Tag.query().select(... ref('tags.content:fr)).where('myCondition');`
Doing this way I don't have a proper name for the selected column, and using `as` I am not able to keep the key `fr` embeded in the `content` document.

So here is my question: is there a way in Objection to select only a part of the `content` document while keeping his structure in the same time?

Thank you in advance for your help!!

**Comment by koskimas** [comment]
There's no shortcut, but you can create a helper like this:

```js
function selectLang(lang) {
  return raw(
    'json_build_object(?, ??) as content',
    [
      lang,
      ref(`tags.content:${lang}`)  
    ]
  )
}
```

https://www.postgresql.org/docs/9.5/functions-json.htm

```js
Tag.query().select(... selectLang('fr')).where('myCondition');
```

**Comment by maxmousse** [comment]
Thanks very much for your help! That is what I was looking for!
