### ISSUE TITLE
Document QueryBuilder toKnexQuery

### ISSUE THREAD

**Issue by Tapppi** [Vincit/objection.js#1340]
We have our own plugin for postgres `ON CONFLICT DO ...`, and in it is necessary to use `QueryBuilder.toKnexQuery()` (previously `QueryBuilder.build()`). The name change broke stuff for us, since apparently that isn't considered public API (it is not documented).

Could you document the method so that it doesn't change without major version change? 😄 At least for this usecase, where we need the actual SQL knex would build, we haven't found another way to do it and it wasn't nice to debug the error after doing a "safe" upgrade.

**Comment by koskimas** [comment]
Sorry but no. It's not part of the public API and you shouldn't be using it in the first place. I don't want to lock that part of the API down.
