### ISSUE TITLE
Typing - QueryBuilderYieldingCount on query().count()

### ISSUE THREAD

**Issue by JonathanBruce** [Vincit/objection.js#1346]
In a typescript environment an objection object that runs a query that chains into a `count` call returns <Model, Model[], Model[]> as its enumerated types.

Examining some other method definitions for query builder I see they return `QueryBuilderYieldingCount`

Shouldn't this also be the return type of the count method since we're getting a number/string type response?

**Comment by koskimas** [comment]
Actually, by default you get a result like this from `count`

```js
[{ 'count(*)': 21352}]
```

The name of the key even depends on the database driver. It's kind of a POS API, but it's the same as in knex, and that's why we haven't changed that. You can use the `resultSize` method instead.
