### ISSUE TITLE
ManyToMany through table with condition

### ISSUE THREAD

**Issue by keepcosmos** [Vincit/objection.js#1348]
First of all, thanks for contributing an awesome library <3.  I am just moving to objection from sequelize. I'm very happy with objection now. 

But problem is, I don't know how to add conditions to ManyToMany "through table".
I have deleted_at column on the through table. I want to add default condition for rejecting unrelated(actually updated(marked) deleted_at column) relation. something like this,

```js
products: {
  relation: Base.ManyToManyRelation,
  modelClass: Product,
  join: {
    from: 'product_models.id',
    to: 'products.id',
    through: {
      from: 'product_product_models.product_model_id',
      to: 'product_product_models.product_id',
      filter: (builder) => builder.whereNull('ProductProductModel.deletedAt')
    }
  }
}
```

Is it possible?

**Comment by keepcosmos** [comment]
I solved my self, It was filter! thanks

**Comment by needfulthing** [comment]
So your example above works? It does not work for me in objection@3.0.1 - "filter" seems to be ignored. And shouldn't it be

`filter: (builder) => builder.whereNull('product_product_models.deletedAt')`

?

**Comment by needfulthing** [comment]
That should work:

```
products: {
  relation: Base.ManyToManyRelation,
  modelClass: Product,
  join: {
    from: 'product_models.id',
    to: 'products.id',
    through: {
      from: 'product_product_models.product_model_id',
      to: 'product_product_models.product_id',
    }
  },
  filter: (builder) => builder.whereNull('product_product_models.deletedAt')
}
```
