### ISSUE TITLE
$relatedQuery().insert() with extra columns - unexpected merging properties on modelClass

### ISSUE THREAD

**Issue by the-vampiire** [Vincit/objection.js#1349]
after a lot of tinkering and digging further into the code / docs here is my understanding

if i set the `relation.join.through.extra` property then running the query below will:
- apply `relationData` to the table defined by the `relation.modelClass`
- apply `extraData` to the table defined in `relation.join.through`
- return a relation model instance **with `extraData` properties merged onto it**

```js
source.$relatedQuery(relation).insert({ ...relationData, ...extraData})
```

pros
- easy to insert relation and extra data from one call on the source model instance

cons
- merges `extraData` onto the relation instance returned
- eager fetching / loading related will also **merge `extraData` onto the relation model instances**

**question**
- can i enable `relation.join.through.extra` for the purposes of inserting
  - if i remove `extra` then i get an error on inserting because it thinks `extraData` belongs on the relation table instead of the join table
- can i disable `extraData` from being merged onto the returned relation instance during insert or fetch

**alternative feature request**
- a way to alias or bundle the extra properties added to the relation model instance so they are not at the same level as its column properties? (example below)

**current**
```js
// extra: ['extra1', 'extra2']
// insert or fetch relation

Relation {
  ...ownProperties, // columns on the related table
// extra properties on the join table are merged 
  extra1,
  extra2,
}
```

**alias / bundle**
```js
// extra: { name: "bundled", columns: ['extra1', 'extra2'] }
// insert or fetch relation

Relation {
  ...ownProperties, // columns on the related table
// extra properties on the join table are bundled
  bundled: {
    extra1,
    extra2,
  }
}
```

## original post

**unexpected behavior**
when i insert a student and add the extra fields the returned object is behaving unexpectedly
- the result has Student properties merged at the same level as the Payment (extra) properties
  - **is there a way to disable this or describe a nested property for them to go in?**
- running `result instance of Student` i get `false`
  - but `result.constructor.name` is `"Student"`
  - **EDIT**: using the edited workaround (at the end) `instanceof Student` is `true`

relations
- Course m2m Student through Payment
- Payment extra fields: payment_type, amount, invoice_date, payment_date

**use case**
insert a student, set values for the extra (join table) columns, return the student object
- either just the student object itself (withoutt extra join table properties merged onto it)
- or the student object with the joint table properties as an object in a property called "payments"

query
```js
return course.$relatedQuery("students").insert({
  ...studentData,
  amount: course.price,
  payment_type: paymentType,
  invoice_date: new Date().toISOString(),
});
```

the returned object:

```js
Student {
  firstName: 'Vamp',
  lastName: 'Vamp',
  email: 'vamp@vamp.com',
  company: 'Vamp',
  location: {
    city: "Salem",
    state: "MA",
    country: "USA"
  },
// these are Payment extra properties
  amount: 1695,
  payment_type: 'credit',
  invoice_date: '2019-05-27T20:21:37.773Z',
  created_at: '2019-05-27T20:21:37.797Z',
// is this the student ID?
  id: 47
}
```

## edit
i solved it by doing this instead

```js
static async registerStudent(registrationData) {
  const { paymentType, courseId, ...studentData } = registrationData;

  // ensures the course is valid for registration
  const course = await this.validateCourseId(courseId);

  const student = await Student.query().insert(studentData);

  await course.$relatedQuery("payments").insert({
    paymentType,
    amount: course.price,
    student_id: student.id,
    invoiceDate: new Date().toISOString(),
  });

  return student;
}
```

is there a better way to do this?

**Comment by the-vampiire** [comment]
**Course**

```js
class Course extends TimestampsBase {
  static get tableName() {
    return "courses";
  }
// removed unrelated for brevity

  static async registerStudent(registrationData) {
    const { paymentType, courseId, ...studentData } = registrationData;

    // ensures the course is valid for registration
    const course = await this.validateCourseId(courseId);

    return course.$relatedQuery("students").insert({
      ...studentData,
      amount: course.price,
      payment_type: paymentType,
      invoice_date: new Date().toISOString(),
    }); // expect new Student object (without extra properties merged onto it)
  }

  static get jsonSchema() {
    return schemas.types.course;
  }

  static get relationMappings() {
    return {
      payments: {
        modelClass: "Payment",
        relation: Model.HasManyRelation,
        join: {
          from: "courses.id",
          to: "payments.course_id",
        },
      },
      students: {
        modelClass: "Student",
        relation: Model.ManyToManyRelation,
        join: {
          from: "courses.id",
          to: "students.id",
          through: {
            from: "payments.course_id",
            to: "payments.student_id",
            extra: ["payment_type", "amount", "invoice_date", "payment_date"],
          },
        },
      },
    };
  }
}
```

**Student**
```js
class Student extends TimestampsBase {
  static get tableName() {
    return "students";
  }

  static get jsonSchema() {
    return schemas.types.student;
  }

  static get relationMappings() {
    return {
      payments: {
        modelClass: "Payment",
        relation: Model.HasManyRelation,
        join: {
          from: "students.id",
          to: "payments.student_id",
        },
      },
      courses: {
        modelClass: "Course",
        relation: Model.ManyToManyRelation,
        join: {
          from: "students.id",
          to: "courses.id",
          through: {
            from: "payments.student_id",
            to: "payments.course_id",
// is there a way to not have to duplicate this in Course and Student?
            extra: ["payment_type", "amount", "invoice_date", "payment_date"],
          },
        },
      },
    };
  }
}
```

**Payment**
```js
class Payment extends TimestampsBase {
  static get tableName() {
    return "payments";
  }

  static get jsonSchema() {
    return schemas.types.payment;
  }

  static get relationMappings() {
    return {
      course: {
        modelClass: "Course",
        relation: Model.BelongsToOneRelation,
        join: {
          from: "payments.course_id",
          to: "courses.id",
        },
      },
      student: {
        modelClass: "Student",
        relation: Model.BelongsToOneRelation,
        join: {
          from: "payments.student_id",
          to: "students.id",
        },
      },
    };
  }
}
```

**Comment by koskimas** [comment]
The whole point of `extra` properties is that they get joined with the related model. Everything here works as expected.

**Comment by the-vampiire** [comment]
@koskimas is there a way to use the `extra` property for the purposes of inserting but not have the properties added to the related model?
