### ISSUE TITLE
Eager loading filter querybuilder modelclass

### ISSUE THREAD

**Issue by anyong** [Vincit/objection.js#135]
The builder passed to an eager loading filter is a plain old `QueryBuilder` object, not the QueryBuilder class for the model being loaded. I noticed this when a custom QueryBuilder method threw an error inside of a filter.

**Comment by koskimas** [comment]
Thanks for reporting this. I'll take a look at this soon.

**Comment by koskimas** [comment]
This is fixed in 0.5.0

**Comment by koskimas** [comment]
No it isn't 😄 Will fix this in 0.5.2
