### ISSUE TITLE
No update on upsertGraph with M2M relations and extra

### ISSUE THREAD

**Issue by anthonyG78** [Vincit/objection.js#1352]
Hello,
Yep... I'm trying to use `upsertGraph` with `ManyToManyRelation` and `extra` columns in order to update a data with his relations. Upsert works perfectly on the primary data, related insertion, related deletion but it doesn't on related update.

### Models
Here are Profiles, Endpoints and the ProfilesEndpoints relations
```javascript
const { Model } = require('objection');

class ProfilesModel extends Model {
  static get tableName() {
    return 'profiles';
  }

  static get dbRefProp() {
    return `#ref_${this.tableName}`;
  }

  static get idColumn() {
    return 'profile_id';
  }

  static get relationMappings() {
    return {
      endpoints: {
        relation: this.ManyToManyRelation,
        modelClass: EndpointsModel,
        join: {
          from: 'profiles.profile_id',
          through: {
            from: 'profiles_endpoints.profile_id',
            to: 'profiles_endpoints.endpoint_id',
            extra: ['profile_endpoint_read', 'profile_endpoint_write']
          },
          to: `endpoints.endpoint_id`
        },
      }
    }
}
```
```javascript
class EndpointsModel extends Model {
  static get tableName() {
    return 'endpoints';
  }

  static get dbRefProp() {
    return `#ref_${this.tableName}`;
  }

  static get idColumn() {
    return 'endpoint_id';
  } 
}
```
```javascript
class ProfilesEndpointsModel extends Model {
  static get tableName() {
    return 'profiles_endpoints';
  }
}
```

### Queries
First, Profile update Ok, endpoints insertions OK
```javascript
const profile = {
  "profile_id": 118,
  "profile_name": "Psychologies",
  "endpoints": [
    {
      "endpoint_id": 1,
      // extra columns
      "profile_endpoint_read": 0,
      "profile_endpoint_write": 0,
    }
  ]
}
await ProfilesModel.query().upsertGraph(profile, {
  relate: true,
  unrelate: true,
  noUpdate: ['endpoints'],
})
```

Profile Update OK, endpoints update **not OK**
```javascript
const profile = {
  "profile_id": 118,
  "profile_name": "Psychologies 2",
  "endpoints": [
    {
      "#ref_endpoints": 1,
      // extra columns
      "profile_endpoint_read": 1,
      "profile_endpoint_write": 1,
    }
  ]
}
await ProfilesModel.query().upsertGraph(profile, {
  relate: true,
  unrelate: true,
  noUpdate: ['endpoints'],
})
```

Profile Update OK, endpoints deletion OK
```javascript
const profile = {
  "profile_id": 118,
  "profile_name": "Psychologies 3",
  "endpoints": []
}
await ProfilesModel.query().upsertGraph(profile, {
  relate: true,
  unrelate: true,
  noUpdate: ['endpoints'],
})
```

### Note
Something strange that I've noticed, when `upsertGraph` do a `SELECT` in order to compare the existing relations with the new ones, `extra` columns are missing on the query.
Extra columns `profile_endpoint_read` and `profile_endpoint_write` are missing. Can `upsertGraph` do the proper comparison without them in order to decide to update? 
```sql
select `profiles_endpoints`.`profile_id` as `objectiontmpjoin0`, `endpoints`.`endpoint_id` 
from `endpoints` 
inner join `profiles_endpoints` on `endpoints`.`endpoint_id` = `profiles_endpoints`.`endpoint_id` 
where `profiles_endpoints`.`profile_id` in (118)
```
But when I make a query `SELECT` myself, the `extra` columns works perfectly. 

------------

Is this something that I'm doing wrong or an issue with this case?
Thank you :)

**Comment by koskimas** [comment]
You have desabled the update using the noUpdate option.

**Comment by anthonyG78** [comment]
Thx for your fast reply, that make sens...
I thought that `noUpdate` options was exclusive for the related entity and not for the relation itself. 
In my case with `noUpdate: ['endpoints']`, I supposed that Endpoints will not be updated but ProfilesEndpoints will.
So, I think that delete all relations before upsert (not the related entities!) will imitate the expected behavior: delete & insert again the relations ≈ update.
