### ISSUE TITLE
upsertGraph "no reference found" error

### ISSUE THREAD

**Issue by stevo2588** [Vincit/objection.js#1357]
Hi, I'm running into an issue with upsertGraph and `#ref`. Here's the snippet:

```
  await Animal.query().insertGraph({
    name: 'Grumpy',
    species: 'cat',
  });

  await Person.query().insertGraph({
    firstName: 'Gary',
    lastName: 'Lawrence',
  });

  const gLaw = await Person.query().findOne({ firstName: 'Gary' });
  const gCat = await Animal.query().findOne({ name: 'Grumpy' });

  await Person.query().upsertGraph({
    firstName: 'Jennifer',
    lastName: 'Lawrence',

    parent: {
      id: gLaw.id,

      pet: { '#ref': 'grumpyCat' },
    },
    pet: {
        id: gCat.id,
        '#id': 'grumpyCat'
    }
  }, { noDelete: true, relate: true });
```
Full reproduction here: https://gist.github.com/stevo2588/92967b6a105a069c090e71d5f7eb35c9

My expectation is that the upsert will insert a new person and relate the pet to the person and their parent, but instead I get "no reference found". Am I doing something wrong or is this usage of `#ref` unsupported? Thanks!

**Comment by koskimas** [comment]
Yeah, this is a known corner case that doesn't work. It's caused by a `#ref` being on a subgraph of a related item, while the `#id` is outside the subgraph. Unfortunately this would be horrible to fix.
