### ISSUE TITLE
after patch individual json field, ref string mapped object

### ISSUE THREAD

**Issue by keepcosmos** [Vincit/objection.js#1361]
After patch a json field, ex) ` post.$query().patch({ 'jsonFields:subnode': 1 })`

`jsonFields:subnode` is mapped as a object property.

like,
```
Post {
  jsonFields: {
    subnode: 1
  },
  'jsonFields:subnode`: 1
}
```

is it bug? or expected?

**Comment by koskimas** [comment]
That's a bug.
