### ISSUE TITLE
Q: What I should set to `idColumn` if the table doesn't have `id` collumn

### ISSUE THREAD

**Issue by TheMisir** [Vincit/objection.js#1369]
I have a table like that:

product_id | category_id
--|--
2|5
2|4
3|4

... which doesn't contain `id` column. When I querying that table using `Objection.Model` I get an error: "**`insert into "product_category" ("category_id", "product_id") values ($1, $2) returning "id" - column "id" does not exist`**"

Then I added this code to my model.

```js
static get idColumn() {
    return ['product_id', 'category_id'];
}
```

Now I get an error like that: **`You should only pass objects to $setJson method. $setJson method was given an invalid value 6`**

I don't know how to fix that :/ Help me plz. Thanks 😊

**Comment by koskimas** [comment]
That's a many-to-many pivot table right? And that error is coming from a `$relatedQuery` or an `insertGraph` or `upsertGraph` call when a relation is being inserted? You need to register that model class for the many-to-many relation using `modelClass` like this

```js
static get relationMappings() {
  return {
    theFailingRelation: {
      ...,
      join: {
        ...
        through: {
          ...
          modelClass: TheJoinTableModelClass
        }
      }
    }
}
    }
  }
}
```

In the future, please provide more information so that I don't have to spend time quessing what you may be doing.

**Comment by TheMisir** [comment]
Yes, thanks. I'm sorry to waste your time. Do you have a [BMC](https://www.buymeacoffee.com) link? I want to support the project.

**Comment by koskimas** [comment]
Thanks for asking but I don't have a BMC. I'm happy to help. You just get the help faster if the issue has more information :slightly_smiling_face:

**Comment by anup-a** [comment]
@koskimas 

I'm facing similar issue even though I have defined modelClass ..
```js
      ...
      post_likes: {
        relation: Model.ManyToManyRelation,
        modelClass: __dirname + '/user.model',
        join: {
          from: 'posts.id',
          through: {
            modelClass: __dirname + '/post_likes.model',
            from: 'post_likes.post_id',
            to: 'post_likes.user_id',
          },
          to: 'users.id',
        },
      },
     ...
```
This is my PostLike Model, 
```js
export class PostLike extends Model {
  static get tableName() {
    return 'post_likes'
  }

  static get relationMappings() {
    return {
      post: {
        relation: Model.BelongsToOneRelation,
        modelClass: __dirname + './post.model',
        join: {
          from: 'post_likes.post_id',
          to: 'posts.id',
        },
      },
      user: {
        relation: Model.BelongsToOneRelation,
        modelClass: __dirname + './user.model',

        join: {
          from: 'post_likes.user_id',
          to: 'users.id',
        },
      },
    }
  }
}
```

I'm getting error id\" - column \"id\" does not exist, when 
```js
    await PostLike.query().insert({
      post_id: pid,
      user_id: userId,
    })
```
