### ISSUE TITLE
Feature request: Finding a model by a field on a related model (similar to filter)

### ISSUE THREAD

**Issue by anyong** [Vincit/objection.js#137]
I have a number of models with slug fields that are essentially just pretty (human-readable) IDs, but I always keep a separate primary key field on the table as well. I do a lot of queries like this:

```sql
select * from part_manufacturers pm
join parts p on p.id = pm.part_id
join manufacturers m on m.id = pm.manufacturer_id
where p.slug = 'some_slug'
and m.slug = 'another_slug';
```

If I had the IDs, I could simply do `select * from pm where part_id = X and manufacturer_id = Y`. The reason I'm not using filters is because I don't actually want the `parts` or `manufacturers` rows, just the rows from `part_manufacturers`.

It would be great if there was a way to query like this:

```js
PartManufacturer
.query()
.whereRelated('parts', {slug: 'part_slug'})
.whereRelated('manufacturers', {slug: 'mfr_slug'});
```

`whereRelated` would take 2 arguments, the first being the `relationMappings` key, and the second being either an object (for a `where` query), or a function that takes the `QueryBuilder,` similar to a filter.

What do you think?

**Comment by koskimas** [comment]
There is a `joinRelated` method coming in 0.5.0. You can already use it by installing `objection@next`. It allows you to do this:

```js
PartManufacturer
.query()
.joinRelated('parts')
.joinRelated('manufacturers')
.where('parts.slug', 'part_slug')
.where('manufacturers.slug', 'mfr_slug')
```
