### ISSUE TITLE
Many to many relationship with it's own ID

### ISSUE THREAD

**Issue by gabrieeel** [Vincit/objection.js#1371]
Hi, I've been looking for an answer to this but couldn't find any in the issues listed here.

I have a many to many table that has it's own primary key (not a composite key).
The tables are:

Account table (accountid, clientname, etc)
Client table (clientid, clientname, etc)
And the ClientAccountAccess table (id, clientid, accountid).

When I have to relate a client to an account this is the code I use:
client.$relatedQuery('accounts').relate(accountId)

This inserts a row in the ClientAccountAccess table with the correct values in the clientid and accountid columns, but with an empty id.

How can I set this ID, the primary Key of the table?

**Comment by koskimas** [comment]
Hi,

Is there are reason you didn't make that `id` autoincrementing? You should do that if there is no specific reason not to.

If you want to generate a new id for each row automatically, you can create model for the `ClientAccountAccess` table and implement a `$beforeInsert` hook for it. You need to register that model class for each relation that uses it using something like this:

```js
static relationMappings = {
  accounts: {
    ...
    join: {
      ...
      through: {
        ...
        modelClass: ClientAccountAccess  
      }
    }
  }
}
```

Another option is to define the `id` as an `extra` field for the relation and then you can say::

```js
client.$relatedQuery('accounts').relate({ accountId, id: 234324 })
```
