### ISSUE TITLE
Add Model#$loadRelatedUnlessLoaded to cut down on queries

### ISSUE THREAD

**Issue by phormio** [Vincit/objection.js#1375]
Could you add a instance method to the `Model` class, to be called `$loadRelatedUnlessLoaded`.  It would be like `Model#$loadRelated` but wouldn't load any data already in the object.

To see why this is useful, consider the following function.

```js
async function f(user) {
  const u = user.$clone();
  await u.$loadRelatedUnlessLoaded('favouriteBook.author');
  // Do something with u.favouriteBook.author
}
```

I want to be able to pass a `User` object to `f` without having to care about which relations have been loaded.  But if I call `$loadRelated` in `f`, then the application is doing unnecessary work if the data has already been loaded.

`$loadRelatedUnlessLoaded` may not be a good name; feel free to think of a better one.

**Comment by koskimas** [comment]
I think we could add this after 2.0 through an option like

```js
this.$fetchGraph('favouriteBook.author', { skipLoaded: true })
```

**Comment by koskimas** [comment]
This will work starting from 2.0.4:

```js
instance.$fetchGraph('favouriteBook.author', { skipFetched: true })
```
