### ISSUE TITLE
getting targetValue.replace is not a function TypeError for upsertGraph

### ISSUE THREAD

**Issue by deconstructionalism** [Vincit/objection.js#1378]
I am unable to use the `"#ref{}"` syntax to apply the root resource ID to various nested relations as integer data. According to the docs, this should be possible by using `"#ref{}"` in a string without any surrounding characters, which will avoid casting it to String when the references are resolved before the upsert. However, when I run the following to upsert new data, I get a TypeError.

```bash
TypeError: targetValue.replace is not a function
    at GraphInsertAction._resolvePropertyReferenceNode (/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:126:54)
    at GraphInsertAction._resolveDependency (/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:81:12)
    at GraphInsertAction._resolveDependencies (/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:71:16)
    at GraphInsertAction._beforeInsert (/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:55:10)
    at GraphInsertAction._insertBatch (/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:49:17)
    at promiseUtils.map.batch (/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:31:52)
```

```js
// materialTypeId, content, name, courseId, and unitId are defined in this scope

const upsertData = {
  '#id': 'newMaterial',
  course_id: courseId,
  unit_id: unitId,
  material_type_id: materialTypeId,
  [materialType]: {
    id: '#ref{newMaterial.id}',
    name,
    chunk: {
      content,
      gradable_id: "#ref{newMaterial.id}",
      material_type_id: materialTypeId,
    }
  }
}

const material = await Material.query(trx)
                               .upsertGraphAndFetch(upsertData, { insertMissing: true })

```

**Comment by deconstructionalism** [comment]
I should mention that the `materialType` models have class table inheritance with respect to the `Material` table and share the same primary key. Perhaps this is contributing to the issue? One of the `materialType` tables is `Lesson`. Here is the relation between `Lesson` and `Material`:

**`Material.js`**
```js
 static get relationMappings() {
    return {
      lesson: {
        relation: Model.HasOneRelation,
        modelClass: __dirname + '/Lesson.js',
        join: {
          from: 'materials.id',
          to: 'lessons.id'
        }
      }
  }
}
```

**`Lesson.js`**
```js
  static get relationMappings() {
    return {
      material: {
        relation: Model.BelongsToOneRelation,
        modelClass: __dirname + '/Material.js',
        join: {
          from: 'lessons.material_id',
          to: 'materials.id'
        }
      }
  }
}
```

**Comment by koskimas** [comment]
Could you write a single file I can easily run and debug? You can use the reproduction_template.js file as a starting point. I was not able to reproduce this.

**Comment by deconstructionalism** [comment]
Thanks for the speedy reply! I think I've actually fixed the issue, but if you still want a reproduction in order to study it, let me know and I'll make one. I appreciate the effort and thoroughness you've put into Objection.

So, what made everything work was to simply leave out the references entirely. I had to make sure that the `id`'s matching up was not a simple consequence of two `_seq` tables happening to be on the same max index, but it appears that it actually just works due to the "magic" of the upsert. Am I wrong about this, or does what I said make sense with respect to the following code working. You also need to see the `chunk` relation to fully understand what I'm getting at.

```js

const upsertData = {
  course_id: courseId,
  unit_id: unitId,
  material_type_id: materialTypeId,
  [materialType]: {
    name,
    chunk: {
      content,
      material_type_id: materialTypeId,
    }
  }
}

```
**`Lesson.js`**
```js
static get relationMappings() {
    return {
      material: {
        relation: Model.BelongsToOneRelation,
        modelClass: __dirname + '/Material.js',
        join: {
          from: 'lessons.id',
          to: 'materials.id'
        }
      },
      chunk: {
        relation: Model.HasOneRelation,
        modelClass: __dirname + '/Chunk.js',
        filter: queryBuilder => queryBuilder.where('material_type_id', 1),
        join: {
          from: 'lessons.id',
          to: 'chunks.gradable_id'
        }
      }
    }
  }
```

**Comment by koskimas** [comment]
Great that you got that working. No need for a reproduction anymore, but thanks for offering to do that :+1:
