### ISSUE TITLE
$relatedQuery.relate attempts to update related object

### ISSUE THREAD

**Issue by kernelpaste** [Vincit/objection.js#1379]
This is my query:

```javascript
  async updateSnailOwner(snailId: number, userId: number): Promise<any> {
    const snail = await SnailEntity.query().findById(snailId);
    await snail.$relatedQuery('owner').relate(userId).debug();
  },
```

and here's the relation:

```javascript
      owner: {
        relation: DatabaseModel.HasOneRelation,
        modelClass: UserEntity,
        join: {
          from: 'snails.run_by',
          to: `users.id`
        }
      },
```

The query fails because this is the first SQL it runs:

```
'update `users` set `status` = '1', `id` = null, `modified_on` = '3:14 PM' where `users`.`id` in (3)'
```

It seems that the `UserEntity` constructor is being called with an empty object first. I'm not sure why that's happening. Internally, all I'm expecting is a lookup of the ID of the related object, and then a patch on the foreign key of the main object. There doesn't seem any need to touch the related object in the database (the `modified_on` key is added in the `$beforeUpdate` hook).

**Comment by koskimas** [comment]
Cannot reproduce.

**Comment by koskimas** [comment]
https://vincit.github.io/objection.js/guide/contributing.html#issues

**Comment by koskimas** [comment]
Actually I just noticed that the relation is wrong. It should be

```js
      owner: {
        relation: DatabaseModel.BelongsToOneRelation,
        modelClass: UserEntity,
        join: {
          from: 'snails.run_by',
          to: `users.id`
        }
      },
```
