### ISSUE TITLE
BeforeGet method?

### ISSUE THREAD

**Issue by rafaljanicki** [Vincit/objection.js#138]
Hello,

I am aware of the `$parseDatabaseJson` method, but I need to operate on relations before returning the object (e.g. copy some fields from the relation to the base object). As far as I know, it's not possible to achieve currently, so adding (or modifying) a method that allows to transform the object before returning would save some work.

Thanks

**Comment by rafaljanicki** [comment]
@koskimas do you have any update on this?

Another issue I have is that I can't hide the related entity id in response. E.g. current response:
~~~~
Id: $id,
RelatedEntityId: $id,
RelatedEntity: {}
~~~~

If I delete the RelatedEntityId column in $parseDatabaseJson, I get an error `[Error: Entity.$parseDatabaseJson probably transforms the value of the column RelatedEntityId. This is a no-no because RelatedEntityId is needed in the relation Entity.RelatedEntity]`

**Comment by koskimas** [comment]
I'll probably add `$afterGet` hook in addition to `$afterDelete` at some point, but I don't have time to do this right now. Maybe you can solve your problem by overriding `$toJson` method? It is called when the model is serialized. For example by `JSON.stringify`.

**Comment by rafaljanicki** [comment]
It'd actually break my integration with AWS API Gateway, so I can't do this.

Do you plan to release any minor v4 versions? Maybe I can do a PR for this?

**Comment by rafaljanicki** [comment]
Sorry, forgot to mention @koskimas

**Comment by koskimas** [comment]
The next released version will be 0.5.0 as soon as I find time to do it. The 0.5.0-rc.5 is basically the release version, so you can pretty safely start using it. 0.5.0 is pretty much a rewrite of the codebase, so any PR for the 0.4.0 would have to be rewritten for 0.5.0. PR for the 0.5.0 version is welcome!

**Comment by heisian** [comment]
@koskimas Is there any similar hook or workaround for a `$beforeGet` currently?

i.e., my main use case is to intercept find queries and return cached data from redis instead of querying the database.

**Comment by lehni** [comment]
@koskimas has outlined his plan about this on Gitter recently: [September 24, 2018 5:25 PM](https://gitter.im/Vincit/objection.js?at=5ba901f7b4990c30ee0100fa)
