### ISSUE TITLE
How to REPL with `Objection.js`?

### ISSUE THREAD

**Issue by stoplion** [Vincit/objection.js#1381]
Coming from a Rails background and I so far love `objection.js` but I miss the repl with `Rails/ActiveRecord`. Is there a way to use Objection in my app via a repl to do various CRUD activities. Thanks.

**Comment by devinivy** [comment]
I use objection via the CLI as a regular part of my dev workflow via the [hpal](https://github.com/hapipal/hpal) CLI and [hpal-debug](https://github.com/hapipal/hpal-debug).  It's based on hapijs, but you could have a simple setup that allows you to use the REPL for model debugging purposes without using hapi for your actual web server.

**Comment by mordof** [comment]
@stoplion  This is how I've set up my repl:

```typescript
import { connect, Model } from 'my-objection';
import config from 'custom-app-config';
import * as repl from 'repl';
const replHistory = require('repl.history');

(async () => {
  // my connect function takes 3 args. all config options for 1, a second bool for whether to use
  // snakeCaseMapper or not, and a third for the connection name it's connecting as.
  //
  // I didn't like the idea of running the migrations with the ability to use snakeCaseMapper,
  // as I wanted them to feel "closer to the database"... so this is how i've done it.
  const migrationConnection = await connect(config.database, false, 'migrations');
  const knex = await connect(config.database, true);

  Model.knex(knex);

  await migrationConnection.migrate.latest();
  await migrationConnection.destroy();

  const replServer = repl.start('gca => ');
  replHistory(replServer, '.repl-history');

  replServer.context.knex = knex;
})();
```

I have this script as a `yarn repl` command.  once in the repl, you can import the models you wish to use. If you're using node 10, it's nice to use --experimental-repl-await flag, which allows you to do this at the root level of the repl:

`await MyModel.query()` to fiddle with stuff conveniently.

I think it's node 11, or 12, which has proper support for repl await at root level without the flag.

**Comment by mordof** [comment]
the package `my-objection` is a separate package I've made which contains all of my models, connection helpers, etc.
`custom-app-config` is another private package which helps with loading environment configuration.

Unfortunately I can't share those, but since you're already using objection, the pattern shouldn't be any different from what you're doing elsewhere.
