### ISSUE TITLE
Querying all records yields an error when primary key is type UUID

### ISSUE THREAD

**Issue by joonashak** [Vincit/objection.js#1388]
I'm trying to get all rows from the table `members` which is set-up like so (in migrations):

```
knex.schema.createTable('members', (table) => {
        table.uuid('id').notNullable().primary();
        // rest of cols...
})
```

When I try to get all rows from this table by `await Member.query();`, the operation fails. I'm using PostgreSQL, and the error from db is:

```
{
    "message": "select \"members\".* from \"members\" where \"members\".\"id\" = $1 - invalid input syntax for type uuid: \"all\"",
    "type": "UnknownError",
    "data": {}
}
```

`pg`'s debug ouput:

```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'all' ],
  __knexQueryUid: 'c7518928-a704-4b10-9b87-3fbe7d309628',
  sql: 'select "members".* from "members" where "members"."id" = ?' }
```
I suppose I need to change the binding but can't find a way to do so. How should I go about this? Also, I'm not certain that this is an objection.js issue, but figured I'd start here.

Thanks in advance!

**Comment by koskimas** [comment]
That query isn't generated by the code `Member.query()`. `Member.query()` simply generates `select "members".* from members` without any `where` clauses.
