### ISSUE TITLE
Temporal Data Tables support

### ISSUE THREAD

**Issue by strarsis** [Vincit/objection.js#1393]
Can objection.js also support [Temporal Data Tables](https://mariadb.com/kb/en/library/temporal-data-tables/)?
I want to versionize records so I can query them (grouped) by datetime stamp/transaction.

**Comment by xbabinec** [comment]
I have recently discovered this feature of MariaDB but sadly I couldn't find any javascript ORM framework which would support temporal tables, so we were forced to do versioning using custom validFrom/validTo fields in tables and doing ugly UPDATE - > INSERT flow. 

Support in objection.js would be great.

**Comment by koskimas** [comment]
If that's a feature only MariaDB supports, it will not be added to objection. You are more than welcome to create a plugin and I'd happily add it to the documention.
