### ISSUE TITLE
ValidationError when using fromJson and boolean

### ISSUE THREAD

**Issue by xbabinec** [Vincit/objection.js#1394]
I have Model class defined as following:
```
class Person extends Model  {

  static get jsonSchema() {
    return {
      type: 'object',

      properties: {
        id: { type: 'integer' },
        customFlag: { type: 'boolean' },
      }
    };
  }
```
and JSON prepared for creating instance
```
const person = {
    id: 100,
    customFlag: 1
};
```
When I create instance of this class using `Person.fromJson(person)` objection gives me `ValidationError: customFlag: should be boolean`

Is this intended behaviour? Are 1 and 0 not considered as boolean types?

**Comment by koskimas** [comment]
Boolean is a boolean. Number is a number.
