### ISSUE TITLE
typing - transaction with 8 arguments causes typescript to report error

### ISSUE THREAD

**Issue by sfabriece** [Vincit/objection.js#1395]
I get `Expected 2-6 arguments, but got 8.` from the typescript compiler when creating a transaction with 8 arguments including the callback.

``` js
await transaction(
  Model1,
  Model2,
  Model3,
  Model4,
  Model5,
  Model6,
  Model7,
  async (
    ModelTx1,
    ModelTx2,
    ModelTx3,
    ModelTx4,
    ModelTx5,
    ModelTx6,
    ModelTx7
  ) => { });
```

**Comment by koskimas** [comment]
I'd suggest using the one-argument version if you have that many models in a transaction. You probably have other problems too at that point. If you really want to use the model binding pattern, you can do it like this:

```js
await transaction(Model1.knex(), tx => {
  const ModelTx1 = Model1.bindKnex(tx)
  const ModelTx2 = Model2.bindKnex(tx)
  ...
})
```

**Comment by sfabriece** [comment]
Can you elaborate on what you mean by `You probably have other problems too at that point`?
