### ISSUE TITLE
Using cursors with Objection

### ISSUE THREAD

**Issue by sarneeh** [Vincit/objection.js#1396]
I've been struggling a while to make `objection` work with PostgreSQL cursors. Unfortunately with no results. It works fine just with `knex` and raw queries, but I'd like it to integrate somehow with `objection` queries (handle relationships etc.)

Did anyone succeeded with using cursors in line with `objection`?

**Comment by elhigu** [comment]
Probably impossible, afaik those cannot be used directly in knex either.

**Comment by koskimas** [comment]
This doesn't seem to be getting answers. I'm closing now. You should try the gitter chat, reddit, stackoverflow or something.
