### ISSUE TITLE
Transactions help

### ISSUE THREAD

**Issue by anyong** [Vincit/objection.js#140]
This is kind of a knex question, but since I'm using objection and the `transaction.start` wrapper has slightly different syntax than `knex.transaction`, I figured it's better to ask here. I'm trying to do this as the docs, but it seems like I'm dropping transactions occasionally and then my knex pool fills up and connections start to time out when they can't get a connection.

```js
let trx;

return Promise.try(() => {
  return transaction.start();
}).then(trxObj => {
  trx = trxObj;
  // do a bunch of stuff with transactoin here
  return Foo.bindTransaction(trx). //..
}).then(() => {
  // more stuff with transaction
  return Bar.bindTransaction(trx) // ...
}).then(() => {
  // transaction queries complete
  return trx.commit();
}).then(() => {
  // no more transaction needed
  return Baz.query(). // ...
}).catch(() => {
  return trx.rollback();
})
```

I also have some methods inside of the above transactions that look like this:

```js
class Foo extends Model {
  static aMethod (trx) { // trx passed in from outer method call.
    return Promise.try(() => {
      return Foo.bindTransaction(trx).query() // ...
    });
  }
}
```

and these will get called from the first chain, like

```js
Foo.aMethod(trx);
```

Is there a better way to do this? For instance, should I be using a new `transaction.start()` call in every method that is part of a transaction, and let the database figure out the hierarchy? If I did that, would the outer transaction get rolled back if any inner transactions fail?

Also, is there any better way to debug transactions to see which calls are causing the transactions to hang (i.e., are not calling `commit` or `rollback`)? I think I've got both `commit` and `rollback` exactly once for every call to `transaction.start`, but maybe I'm missing something else.

Thanks.

**Comment by koskimas** [comment]
@elhigu Is the knex master and could probably answer this question better.

You shouldn't start multiple transactions if a single transaction is what you need. I cannot see anything wrong with your code that would cause leaked transactions.

**Comment by elhigu** [comment]
@anyong It would be helpful if you could provide complete example which breaks your transactions. I don't see much wrong in your code example which you have sent so far... 

How are you passing knex connection to `transaction.start()`? In objection examples one passes some model, which is bound to knex connection as a parameter to `start()` method.

here is example from objection docs:

```js
objection.transaction.start(Person).then(function (transaction) {
  trx = transaction;
  return Person
    .bindTransaction(trx)
    .query()
    .insert({firstName: 'Jennifer', lastName: 'Lawrence'});
...
```

**Comment by koskimas** [comment]
@anyong Did you solve this problem? Can I close this issue?
