### ISSUE TITLE
Aggregate with join shouldn't select columns

### ISSUE THREAD

**Issue by BrendanBall** [Vincit/objection.js#1400]
Hi, I'm currently trying to do some aggregate queries that involve joining for filtering. The joining all works fine, but the problem is the moment you add the join, it selects all columns including the aggregate, which breaks the query (it doesn't literally break on sqlite, it returns incorrect data, but it does break in mysql). 
I can't find any way of telling the query not to select those columns. I know I can use knex straight, but then I have to redefine all the joins, and ideally I can just make use of the existing relations in objection.
query:
```javascript
  const catPeople = await Person.query()
    .joinEager('pets')
    .count({ count: '*' })
    .where('pets.species', 'cat')

  const expectedResult = Object.assign(new Person(), { count: 1 })
  chai.expect(catPeople[0]).to.equal(expectedResult);
```
output:
```
  actual:
   Person {
     count: 1,
     id: 1,
     parentId: null,
     firstName: 'Jennifer',
     lastName: 'Lawrence',
     age: null,
     address: null,
     pets: [ [Animal] ] },
  expected: Person { count: 1 } 
```
[full pastebin](https://pastebin.com/HmTvdgVC)

Is there an easy way to do this, or should I just take the hit with a manual knex query?

EDIT: I previously tried `.select({})` but that broke the query, doing `.select('')` mostly works, except it still returns the relation:
```
  actual: Person { count: 1, pets: [ [Animal] ] },
  expected: Person { count: 1 } }
```
So I think that'll still be broken on mysql

**Comment by koskimas** [comment]
Use joinRelation. Don't eager load.

**Comment by koskimas** [comment]
```js
  const catPeople = await Person.query()
    .joinEager('pets')
    .count({ count: '*' })
    .where('pets.species', 'cat')

  const expectedResult = Object.assign(new Person(), { count: 1 })
  chai.expect(catPeople[0]).to.equal(expectedResult);
```
