### ISSUE TITLE
Using relation alias without parent:child

### ISSUE THREAD

**Issue by DenisBessa** [Vincit/objection.js#1403]
I am using the the method 
```
.joinRelation(`
  [parent as pr
    .[child as cd]
  ]
`)
```

which returns me the relation 

```
inner join 
  [parent] as [pr] 
on
  [pr].[attr] = [notRelevantTable].[attr] 
inner join 
  [child] as [pr:cd] 
on
  [pr:cd].[attr] = [pr].[attr]
```

Is it possible to get the CHILD (cd) alias without the PARENT alias (:pr)?

EDIT:
It's important to me, because I am dealling with really deep nested relations. With this kind of pattern things can get really messy really quickly.

**Comment by koskimas** [comment]
Unfortunately no, but you can always use the normal join methods inherited from knex methods to build your custom joins.
