### ISSUE TITLE
Question: Fetching related object in list query

### ISSUE THREAD

**Issue by greentag** [Vincit/objection.js#1404]
Hi.
I am tying to get list of objects with nested(BelongsToOneRelation) rows.
For example we have Book and Author. Book has author_id(BelongsToOneRelation)  field. I want  to get list of books with author like this:
```
[
    {
        name: "The Whale", 
        author: {name: "Herman Melville", age: ...}, 
        ...
    },
    {
        name: "Another book", 
        author: {name: "Another author", age: ...}, 
        ...
    },
]
```

Thank you in advance 😃.

**Comment by koskimas** [comment]
```js
await Book.query().eager('author')
```

This is the very first example in the eager loading documentation and in several other places. This is also very well explained in the example projects. In the future, I suggest checking out the documentation first before opening an issue.

**Comment by koskimas** [comment]
https://vincit.github.io/objection.js/guide/query-examples.html#eager-loading
https://vincit.github.io/objection.js/api/query-builder/eager-methods.html#eager

**Comment by greentag** [comment]
> ```js
> await Book.query().eager('author')
> ```
> 
> This is the very first example in the eager loading documentation and in several other places. This is also very well explained in the example projects. In the future, I suggest checking out the documentation first before opening an issue.

First of all, thank you for fast response 😃.
Sure, I checked it out before opening  this issue. I just expected to get bit different sql. Now objection is generating sql like `select books.* from books;` and additional query to get authors instead of query like this `select books.id, books.name, authors.id as author__id, authors.name as author___name from books join authors on author.id = books.author_id`.

Anyway, thank you for awesome orm 😃.

**Comment by koskimas** [comment]
`joinEager` uses joins to fetch the related objects. The multi-query version is more performant most if the time.
