### ISSUE TITLE
Upsert function for objection

### ISSUE THREAD

**Issue by parker789** [Vincit/objection.js#1406]
Just as the title says. Is there a way I can call an `upsert()` type function on a QueryBuilder? I'd like to be able to call this function and pass in a model object where an id could exist. If the id exists, I'd like it to perform an update on that specific row in the db. If the id does not exist, it'd perform an insert. 

I don't want to use upsertGraph() here as I have no intentions of updating relational data

**Comment by koskimas** [comment]
There's no upsert method. See the custom query builder recipe.

**Comment by RavenHursT** [comment]
> There's no upsert method. See the custom query builder recipe.

Where is this said "recipe"?
