### ISSUE TITLE
WhereInEagerAlgorithm exclude parent record if child condition fails

### ISSUE THREAD

**Issue by parker789** [Vincit/objection.js#1411]
This is just an example, but follows my use case. Lets assume I have a data model of Students, which each belong to a single School.

I'd like to fetch all Students where certain criteria is met, as well as certain criteria against the School... ie something like this:

```
let rows = await Students.query()
  .eager("[school(schoolSelect)]", {
    schoolSelect: builder => {
      builder.where("School.name", "like", "%University%");
    })
  .select("Student.name")
  .where("Student.is_enrolled", "=", "Y");
```

The issue I'm seeing is that all students where `is_enrolled = 'Y'` will be fetched and returned by the query, but `school` will be set to `null` where the eagerModifier condition is not met. Is there a way to run this code so that if the eagerModifier condition is not met, it will actually remove that parent object from the results?

I'm actually refactoring code we previously had which used the `JoinEagerAlgorithm` and all of the where conditions were actually within the main parent query, but the `WhereIn` provides substantial performance improvements, and I'm wondering if its possible to get my expected results using `WhereIn`

**Comment by koskimas** [comment]
You can leverage subqueries and `Model.relatedQuery` like this:

```js
let rows = await Students.query()
  .eager('school')
  .whereExists(Students.relatedQuery('school').where("School.name", "like", "%University%"))
  .select("Student.name")
  .where("Student.is_enrolled", "=", "Y");
```

or join the school. Joining a single 1-1 relation is super fast. `JoinEagerAlgorithm` becomes slow if you load multiple m2m and 1-m relations.

```js
let rows = await Students.query()
  .eager('school')
  .joinRelation('school')
  .select("Student.name")
  .where("Student.is_enrolled", "=", "Y")
  .where("school.name", "like", "%University%")
```

**Comment by parker789** [comment]
Ah awesome! 

Thanks.. yeah this example is much less complicated than the main query I'm running. There are 7-8 joins occurring though which slows things down a lot

**Comment by koskimas** [comment]
And actually the joins are not the slow part. The database engine can optimize them. The slowness comes from eager loading using joins. When joins are used to eager load relations, the data is transferred from the database engine to node in this super inefficient "cartesian product" format that ends up duplicating data exponentially the more m2m and 1-m relations you have in the relation expression. Especially if you have non-nested "parallel" m2m and 1-m relations.

You can safely use joins using the various `join*` methods. It's just the eager loading using joins that gets slow in some cases. But note that using joins for anything other than 1-1 relations, you get the same flat "cartesian product" data structure that contains aloooooot of duplicate rows and stuff if you are not careful.
