### ISSUE TITLE
Objection.js is awesome 😍

### ISSUE THREAD

**Issue by filipjnc** [Vincit/objection.js#1413]
Not an issue but rather a compliment. You guys have smashed it with objective.js + knex. I find it a thousand miles better, more useful and reliable in production than all the ORMs from the Node.js world (I come from Sequelize and TypeORM). 
- The docs are clear and have enough practical examples to get started.
- InsertGraph and UpsertGraph are smart and work wonders.
Love it.

Big props to the team and please don’t let it die.

PS. I read the “Contribution” section from the docs but there was no mention of ways to donate. I think many of us would happily do it.

Can be closed.

**Comment by venelin-mihaylov** [comment]
I am also interested in donating some money. The library is indeed great, and I would like to make a small contribution to its development.

**Comment by koskimas** [comment]
Thanks for the compliments! It's really nice to hear them!

Thanks for offering to donate money, but I don't like to mix open source and money. They don't work well together :slightly_smiling_face:
