### ISSUE TITLE
Consider adding non-fetching equivalents of all QueryBuilder#*AndFetchById() methods

### ISSUE THREAD

**Issue by lehni** [Vincit/objection.js#1415]
For example, it could be nice to be able to do `query.patchById(object)` instead of `query.findById(object.id).patch(object)`

**Comment by koskimas** [comment]
Maybe. Let's see if this gets :+1: by other people.

**Comment by mordof** [comment]
@lehni  is `Model.query().patchById(object)` equivalent to `Model.query().patch(<object minus id column(s)>).where(object[<grab id column(s) of model>])`?

**Comment by lehni** [comment]
@mordof Yes, I'd imagine that's what it should be doing. And it should support composite keys as well

**Comment by koskimas** [comment]
There doesn't seem to be much interest for this. Closing.

**Comment by lehni** [comment]
Well, I don't know if that counts as a poll? I guess we'd have to ask on Gitter to get some community feedback?
