### ISSUE TITLE
Serialization error on transaction commit is not thrown 

### ISSUE THREAD

**Issue by schuma7** [Vincit/objection.js#1416]
I’m trying to run two transactions with serializable isolation level concurrently using the following code snippet:

```
import { transaction, Transaction, Model } from 'objection';
import Knex from 'knex';

const knex = Knex({
  client: 'pg',
  version: '11.2',
  debug: false,
  connection: {
    ...
  },
});

class TestModel extends Model {
  public static readonly tableName = ‘test_table’;

  public readonly id!: number;
  public value!: string;
}

const sleep = (timeoutMs: number): Promise<void> =>
  new Promise((resolve) => setTimeout(resolve, timeoutMs));

const executeInTransaction = async (callback) => {
  let trx: Transaction | undefined;

  try {
    trx = await transaction.start(knex);

    await trx.raw(
      `set transaction isolation level serializable;`,
    );

    await callback(trx)

    await trx.commit();

    console.log('SUCCESS');
  } catch(e) {
    console.error('ERROR', e);

    if (trx) {
      await trx.rollback();
    }
  }
}

async function run() {
  const tx1 = executeInTransaction(async (trx) => {
    await TestModel.query(trx)
      .findById('2')
      .patch({
        value: 'change 2',
      });

    await sleep(3000);
  });

  const tx2 = executeInTransaction(async (trx) => {
    await TestModel.query(trx)
      .findById('3')
      .patch({
        value: 'change 3',
      });

    await sleep(3000);
  });

  await Promise.all([tx1, tx2]);
}

run();
```

As you can see I’m trying to update two separate rows on the same table. In my test scenario this table just has 3 rows. Executing this snippet on the “postgres:11.2” docker image yields the following output:

```
SUCCESS
SUCCESS
```

However, the docker logs for the postgres instance show:

```
postgres           | 2019-07-24 08:26:42.042 UTC [6212] ERROR:  could not serialize access due to read/write dependencies among transactions
postgres           | 2019-07-24 08:26:42.042 UTC [6212] DETAIL:  Reason code: Canceled on identification as a pivot, during commit attempt.
postgres           | 2019-07-24 08:26:42.042 UTC [6212] HINT:  The transaction might succeed if retried.
postgres           | 2019-07-24 08:26:42.042 UTC [6212] STATEMENT:  COMMIT;
```

So it logs two SUCCESS messages instead of one SUCCESS for the first one and one ERROR for the second transaction which gets rolled back.

When trying to update the same row by using the same id in both update queries, the library correctly throws a serialization error:

```
SUCCESS
ERROR { error: could not serialize access due to concurrent update
    at Connection.parseE (/Users/user/pg-test/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/Users/user/pg-test/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/Users/user/pg-test/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)```
```

Please note that for the second scenario where an error is thrown the postgres logs show that the error occurs on the update statement itself while in the first case where the error gets swallowed it happens on the commit.

I’m using the following versions:
node: 10.5.0
node-postgres: 7.11.0
objection: 1.6.9
Postgres: 11.2

I've discovered the following workaround for the time being:
- replace ```await trx.commit();``` with ```await trx.raw('COMMIT');```
- replace ```await trx.rollback();``` with ```await trx.raw('ROLLBACK');```

It'd be great if you could let me know, if this is a viable temporary fix or whether you see any potential issues that could arise by not using the transaction's commit and rollback methods?

**Comment by koskimas** [comment]
Objection delegates all transaction related stuff to knex. You should probably ask this in knex's github. To me it seems very weird that `await trx.commit()` doesn't work, while `await trx.raw('COMMIT');` works. They execute the exact same SQL.

**Comment by schuma7** [comment]
@koskimas  Thanks for your quick response, I'll try to recreate it using Knex and post it there.

In the meanwhile could you please just let me know if you see any potential side-effects using the ```await trx.raw('COMMIT');``` workaround?

**Comment by koskimas** [comment]
No I don't. It should work just the same afaik.

**Comment by schuma7** [comment]
@koskimas fyi, using the raw commits and rollbacks is not working, since it triggers "TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. " errors. The reason most likely being that the connection is not properly released.

I guess it's up to Knex to fix this issue...

**Comment by kibertoad** [comment]
@schuma7 Which knex version are you using? There were significant improvements in transaction rollback error handling lately, you might want to check 0.19.1

**Comment by schuma7** [comment]
@kibertoad I was indeed using an older version (0.16.5). However, I've just upgraded to 0.19.1 and the issue persists, serialization errors on commit are not thrown by Knex.

**Comment by kibertoad** [comment]
@schuma7 full reproduction code without objection would be greatly appreciated then.

**Comment by schuma7** [comment]
As requested, I've created an issue on the Knex Github: https://github.com/tgriesser/knex/issues/3370
