### ISSUE TITLE
MSSQL inserts fail on table with trigger

### ISSUE THREAD

**Issue by cludwig28** [Vincit/objection.js#1418]
Inserts on a table with a trigger fail because the `OUTPUT` clause does not include an `INTO`. I am currently working on a project where we are using triggers to track database changes in SQL Server. The triggers are a relatively new addition and completely broke the functionality our api. After investigating we discovered that the insert is failing because of the `OUTPUT` clause in the sql generated by the query builder does not use `INTO`.

```
[1563975875] ERROR (13578 on ubuntu-vbox): 
    Error: RequestError: insert into [tablename] ([field0], [field1], [field2]) output inserted.[auto_id] values (@p0, @p1, @p2) - The target table 'tablename' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.
```

We have been unable to find a workaround for the issue.

**Comment by koskimas** [comment]
Unfortunately I've never used MSSQL and there are zero tests for it in objection. Someone else needs to fix this.

**Comment by cludwig28** [comment]
I think I may have come up with a solution, but it doesn't apply to objection, it applies to knex.js. I can't say for certain whether or not there are code implications in objection.js, but reforming the sql statements on inserts to create a temp table to insert the output into, then returning the insert values by selecting them out of the temp table seems to resolve the issue, but this is totally in the knex query builder. I plan to open an issue in the knex.js repo. Thanks.

**Comment by liuxiaofeng1981** [comment]
Hi guys, I'm using knex.js and I'm having exactly the same issue with the following code using knex query builder: 

  let result = await db('products')
    .returning(['productId', 'productCode'])
    .insert({...})

products table has a trigger as the error reflected:
RequestError: The target table 'xxx' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.

@cludwig28 have you got any luck with the issue raised for knex.js? May I ask if you have any workaround on this?

Appreciate helps and tips!

**Comment by cludwig28** [comment]
We actually forked knex and wrote a fix for it. It's up on npm at https://www.npmjs.com/package/knex-navistone. I didn't get the opportunity to open a trouble ticket on the knex repo and our fix is completely unsupported, but it works.

**Comment by liuxiaofeng1981** [comment]
@cludwig28 Thanks for sharing that. Umm, that sounds like a bit extreme in our case.. I'm currently doing this with MSSQL as a workaround since the only thing is not working for me is just returning method: 

let result = await db('products').insert({...})
let productId = await db.raw('select @@identity as productId')

Does anyone see any problem with this approach?

**Comment by mcbarlowe** [comment]
In case anyone comes across this like me, this issue has been fixed in `knex` https://github.com/knex/knex/pull/4152
