### ISSUE TITLE
upsertGraph BelongsToOne unrelate error with composite keys

### ISSUE THREAD

**Issue by jaekwak02** [Vincit/objection.js#1419]
Version: `v1.6.8`
Driver: `pg`
Problem / Question: unrelating a BelongsToOne relation where the idColumn and join are defined using composite keys throws an error. AFAIK other operations using this setup works, therefore I am not sure if this scenario simply isn't supported, or if this is a bug.

![Screen Shot 2019-07-23 at 5 19 35 PM](https://user-images.githubusercontent.com/28743660/61751500-1d3c2700-ad6e-11e9-8422-2978bebd4bcf.png)

### Models:
```
class ChildModel extends Model {
  static get tableName() { return "child"; }
  static get idColumn() { return ["client_id", "id"]; }
}

class ParentModel extends Model {
  static get tableName() { return "parent"; }
  static get idColumn() { return ["client_id", "id"]; }

  static get relationMappings() {
    return {
      child: {
        relation: Model.BelongsToOneRelation,
        modelClass: ChildModel,
        join: {
          from: ["parent.client_id", "parent.child_id"],
          to: ["child.client_id", "child.id"],
        }
      }
    };
  }
}
```

### My upsertGraph method:
```
const upsert = async obj => 
  transaction(ParentModel.knex(), async trx => {
    return await ParentModel.query(trx)
      .allowUpsert("child")
      .allowEager("child")
      .upsertGraphAndFetch(obj, {
        relate: ["child"],
        unrelate: ["child"],
        noUpdate: ["child"],
        noInsert: ["child"]
      });
  });
```

### Initial Data in DB:
```
parent = {
  client_id: 1,
  id: 1,
  child_id: null
}

child = {
  client_id: 1,
  id: 1
}
```

### Step 1: Test no change in parent - Works fine
```
const newParent = {
  client_id: 1,
  id: 1,
  child: null
}

upsert(newParent)

outputs { client_id: 1, id: 1, client_id: null, child: null }
```

### Step 2: Test relating child to parent - Works fine
```
const newParent = {
  client_id: 1,
  id: 1,
  child: {
    client_id: 1,
    id: 1
  }
}

upsert(newParent)

outputs { client_id: 1, id: 1, client_id: 1, child: { client_id: 1, id: 1 }}
```

### Step 3: Unrelate child - **Throws an error**
```
const newParent = {
  client_id: 1,
  id: 1,
  child: null
}

upsert(newParent)

Error: one of the identifier columns [client_id, id] is null or undefined. \
Have you specified the correct identifier column for the model \
'ParentModel' using the 'idColumn' property?
```

**Debug log for queries in Step 3:**
```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 1 ],
  __knexQueryUid: '811c69e4-da33-456e-a401-b88319b9af4a',
  sql:
   'select "parent"."client_id", "parent"."id", "parent"."child_id" from "parent" where ("parent"."client_id", "parent"."id") in ((?, ?))' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 1 ],
  __knexQueryUid: '3dcaffef-c5f0-4e45-bc61-581c177bc23d',
  sql:
   'select "child"."client_id", "child"."id" from "child" where ("child"."client_id", "child"."id") in ((?, ?))' }
```

As far as I've been using and testing this, the idColumn and join columns *seem* to work for everything else. I was able to work around this particular issue by just replacing the composite key  with the primary key `id`... but I'm wondering if getting an error here is expected behavior or not.

**Comment by koskimas** [comment]
First of all thanks for the excellent issue! I wish they all were this clear and thorough :100: 

This seems to be a clear bug, but I don't know how easy it would be to fix. Anyway, I won't have time to try to fix this in the near future, as I'm getting the 2.0 release ready.

Have you considered not using `upsertGraph` at all? It seems to be more trouble than it's worth. I will be discouraging its usage in 2.0 docs and the whole function will probably get less time/bugfixes from me. I think adding the whole method to objection was a mistake on my part.

**Comment by jaekwak02** [comment]
No problem, it was mostly to make sure myself that I wasn't using the library wrong 👍 

Everything is dandy when I'm just using just the `id` as the primary column.

I personally love using `upsertGraph`. I think it's super flexible and has solved a lot of problems for me, but I can imagine it's hard to work on due to the complexity of it. The only trouble I've had with it so far is learning how all the options work (it took some time and trial and error) and this one issue.

What method would you suggest for inserting/updating graphs without using `upsertGraph`? Maybe using `insertGraph` and handling updates to graphs manually?

**Comment by koskimas** [comment]
`upsertGraph` can be useful when used "right", but often people see it as some sort of silver bullet for converting relational database into mongo and they use it for absolutely everything. The user really needs to understand the SQL behind it to use it right.

I like to just do the extra work and use `$relatedQuery`, `relatedQuery` etc. simple tools to write the needed queries. I use `upsertGraph` for simple things like upserting a single relation with a parent. In that case it's simple to understand and maintain. As soon as you start passing 100 options to it, it becomes impossible to understand for anyone.

**Comment by jaekwak02** [comment]
I see your point. I agree using simple tools to handle the job would be less magical and more transparent 👍 

Should I leave this issue open till the bug eventually gets handled?

**Comment by koskimas** [comment]
Yes, let's leave this open.
