### ISSUE TITLE
Capture inserts in a join table from a Many to Many relationship.

### ISSUE THREAD

**Issue by lestairon** [Vincit/objection.js#1421]
Hi,
I'd like to know if theres some sort of $beforeInsert but for join tables.

Imagine i have three models `User`, `Post` and `Likes`. With likes being a join table for a many to many relationship between User and Post.

Now, if an User can only like once a post. I'd have to do an extra query to check if that user has liked that post before. Then create the new like.

The query I'm using to create the new like is:
```js
const post = await Post.query().findById(postId)
await post.$relatedQuery("likes").relate(user.id)
```

Or I'd be helpful to have a Unique validation for m:n rows.

I'd appreciate your feedback.

**Comment by koskimas** [comment]
The correct way to do that is to add a database constraint that only allows unique `userId` + `postId` pairs in `Likes` table. Doing it using a separate query will fail when there are concurrent operations running. But if you really want to use a `$beforeInsert` hook, you can add a `$beforeInsert` hook for `Likes` model and specify it in the `relationMappings.join.through`. You can also add a `beforeInsert` hook for the `relationMappings.join.through` object.

https://vincit.github.io/objection.js/api/types/#type-relationthrough

**Comment by koskimas** [comment]
Here's how you'd add the composite constraint in the join table

https://github.com/tgriesser/knex/issues/32

**Comment by lestairon** [comment]
Thanks for the reply.
I made a mistake in my post. There's no `Like` Model. It's just a table for the relationship.
