### ISSUE TITLE
Base model class imported from npm dependency triggers error

### ISSUE THREAD

**Issue by schuma7** [Vincit/objection.js#1422]
I have two models A and B with A having a Model.HasManyRelation mapping to B. Both models inherit from a BaseModel class which is imported from a "common" project. When trying to query model A I receive the following error message:

```Relation's owner is not a subclass of Model\n    at HasManyRelation.createError```

The error is not caused by any circular dependencies, since everything works as soon as I copy the BaseModel over into the project instead of using the imported one from the npm dependency.

One workaround I've found is to export the objection Model class from the "common" npm dependency, import it in my main project and use it for ```Model.HasManyRelation```. However, this seems to be a bit of a hacky approach.

Is there a cleaner way of solving this issue?

**Comment by koskimas** [comment]
Don't add objection as dependency in the "common" project. You now have two copies of objection and the base class inherits from a class that objection doesn't detect as objection's model, because it's from a different copy.

**Comment by schuma7** [comment]
Thanks for the quick response and the pointer to peer deps!
