### ISSUE TITLE
[Typescript] Correctly infer what fields are returned after select() query

### ISSUE THREAD

**Issue by jovinbm** [Vincit/objection.js#1424]
In `knex`, if I have an interface like the following
```
interface IUser {
  id: number;
  first_name: number;
  last_name: number
}
```
and I do a `select()` query like so 
```
const users = await knex<IUser>('user')
.select(['id'])
```
the type of `users` will correctly be inferred to as `Pick<IUser, "id">[]`.  If the `IUser` interface above was an objection Model of something like a `User` class and and I do a `select()` query like so
```
const users= await User.query()
.select(['id'])
```
the type of `users` still in the end is still `User` with all the other fields that have been defined in the class. Is it possible to replicate the behavior from `knex`?

My environment:
`node: 12`
`knex: 0.19.1`
`objection: 1.6.9`

**Comment by koskimas** [comment]
Unfortunately this will be too difficult. We are rewriting the typings in the `new-typings` branch. Feel free to try implementing this so that it works in all possible situations. I will personally give you 1000$ if you succeed :smile:

**Comment by jovinbm** [comment]
Haha, I actually tried working on it for a while before posting the issue, it is tricky to do. I'll keep working on it and post here if I find a good solution. Thank you for the quick reply.

**Comment by mordof** [comment]
I'd imagine it would look something like this (completely untested): 
```typescript
<A extends (keyof M)[], QB extends AnyQueryBuilder, M = QB['ModelType']>select(this: QB, args: A): Pick<M, A>;
```

Noting that the pattern of grabbing `QB` from `this` is not currently the pattern in `new-typings`, however it's a pattern i'm testing out currently in my version of that branch.

Another very important note here is that this has 2 very strong implications. 
1. Currently Objection models do not *need* fields to be listed inside the model, however if the `select` type gets changed to this, fields that aren't in the model won't be supported (would require an overload to handle different cases).
2. fields that aren't _selectable_, but are found as keys inside the model. This one, in my opinion, is the more problematic one. In my opinion, types should reflect how things will function during runtime. If a field would cause an error (e.g. doesn't exist in the database), types shouldn't allow it to be used. Obviously this can be taken with a grain of salt, but every case which bends that causes less confidence in types, and more reliance on runtime verification.  At this time, I'm not sure of a good way to isolate the keys of a model relating to database fields, from everything else, without using something like a decorator (or additional property, similar to `jsonAttributes`).

**Comment by mordof** [comment]
... except right after writing this, I'm realizing I put the `Pick` as the return type. that's 100% wrong... it needs to be a query builder, with the Pick as the return type.

That's a challenge we've been trying to deal with for other purposes quite a bit, and haven't found any viable solution yet. Honestly if you find a way to do that well - I'd be pretty thrilled too.

**Comment by mordof** [comment]
So there you have it. the 3 complications for this particular feature.  #2 (as written in the first comment) i've seen several other places just not care that some of the fields aren't correct, which saddens me, but makes it easier to handle

**Comment by mandaputtra** [comment]
Hi, any update on this? I also tried to work on this. But damn soo hard haha. I'd better return `any` for now lol
