### ISSUE TITLE
Inheriting/merging modifiers from a BaseModel

### ISSUE THREAD

**Issue by o8e** [Vincit/objection.js#1426]
Is it possible to have a bunch of generic `modifiers` on a BaseModel, and then have _local_ `modifiers` on each Model? I assumed it would merge them, or first look on the Model and then go up the chain to the BaseModel, but it seems to just throw an error?

**Comment by o8e** [comment]
So, it seems I can get round this by having an object of modifiers and merging them myself. Kind of would be good to get some inheritance going here, but maybe this isn't possible (not 100% sure how the whole extends thing works).

```
import { modifiers } from '@utils/query'
...
  static get modifiers() {
    return {
      ...modifiers,
      successful(query: QueryBuilder<CompanionResponse>) {
        return query.where('success', '=', true)
      },
...
```

**Comment by koskimas** [comment]
You should be able to do this:

```js
class SomeClass extends BaseModel {
  static modifiers = {
    ...BaseModel.modifiers,
    successful(query: QueryBuilder<CompanionResponse>) {
      return query.where('success', '=', true)
    }
  }
}
```

or if you want to use getters:

```js
class SomeClass extends BaseModel {
  static get modifiers() {
    return {
      ...BaseModel.modifiers,
      successful(query: QueryBuilder<CompanionResponse>) {
        return query.where('success', '=', true)
      }
  }
}
```

or if you want to inherit from the super class, no matter what it is:

```js
class SomeClass extends BaseModel {
  static get modifiers() {
    return {
      ...super.modifiers,
      successful(query: QueryBuilder<CompanionResponse>) {
        return query.where('success', '=', true)
      }
  }
}
```
