### ISSUE TITLE
How can I define read-only SQL Formula columns?

### ISSUE THREAD

**Issue by zsf3** [Vincit/objection.js#1427]
First of all, thank you very much for creating such an awesome library. It has made my life 100 times easier. Objection.js is the top class ORM having a marvelous support for joins. Thanks again for being so much helpful to the community. :1st_place_medal:  

Now my question: How can I add virtual attributes with SQL formula like following:

    class Employee extends Model {
        static get tableName() {
            return 'employees';
        }

        static get virtualAttributes() {
            return ['fullName'];
        }

        fullName() {
            return `CONCAT(first_name, ' ', last_name)`;
        }
    } 

I have a use case where I need few virtual attributes, but I need to perform calculation on db level so that I can use joins and columns of joined tables.

I tried to achieve above mentioned use-case via following code:

    const emps = await Employee.query(db).select([
        'employees.*', 
        knex.raw(`CONCAT(first_name, ' ', last_name) as fullName`)
    ]);

But then I have another use case where `Employee` class has a self-join for `supervisor` property. I also need the `fullName` column along with `supervisor` join. 

Any thoughts on how can I achieve this?

**Comment by koskimas** [comment]
Thanks :beers: : 

There's no way to do that using virtual attributes, but you can create a modifier. Something like this:

```js
const { Model, raw } = require('objection')

class Employee extends Model {
    static get modifiers() {
      return {
        selectFullName: query => {
          query.select(raw('concat(first_name, ' ', 'last_name').as('fullName'))
        }
      }
    }
} 
```

Then you can use it in a query like this:

```js
const emps = await Employee
  .query(db)
  .modify('selectFullName')
  .select('whatever')
```

Selects are additive. Does this help?

**Comment by zsf3** [comment]
That helps a lot. Thanks.

I am now stuck in my 2nd use case: Using this modifier with joined tables. 

```javascript
const emps = await Employee
    .query(db)
    .eager('[supervisor(selectFullName)]')
    .modify('selectFullName')
    .eagerAlgorithm(Model.JoinEagerAlgorithm)
    .select('employees.*')
```
Questions:
1. Selects are not working as additive here, I have to add `select('employees.*')`. Otherwise the query only returns `id` and `fullName` from `employee` and same from `supervisor` join. How do I get all the columns of table along with formula columns specified in modifiers?

Here is the generated SQL:
```SQL
SELECT    
	concat(first_name, ' ', last_name) AS `fullname`,
	`employees`.`id`                     AS `id`,
	`supervisor`.`fullname`              AS `SUPERVISOR:fullname`,
	`supervisor`.`id`                    AS `SUPERVISOR:id`
FROM    `employees`
LEFT JOIN
(
	SELECT 
		concat(first_name, ' ', last_name) AS `fullname`,
		`employees`.`id`
	FROM    `employees`
) AS `supervisor`
ON        `supervisor`.`id` = `employees`.`supervisor_id`
```
 
2. How do I tell objection to bring all columns of `supervisor`?


I have following package.json:

```json
{
 ...
 "dependencies": {
    "knex": "0.18.0-next4",
    "mysql": "2.16.0",
    "objection": "1.6.9"
  }
}
```

**Comment by zsf3** [comment]
Also, I have something like custom fields having formulas which I have to add in modifiers of different models dynamically on the fly. I will try, but I am not sure if it will work correctly for different tenants.

**Comment by koskimas** [comment]
They are additive, but the default is `employees.*`. As soon as you select anything, you need to select everything you want. would something like this work?

```js
const { Model, raw } = require('objection')

class Employee extends Model {
  static get modifiers() {
    return {
      selectAll: query => {
        return query.select('empoyees.*')
      },

      selectFullName: query => {
        query.select(raw(`concat(first_name, ' ', last_name)`).as('fullName'))
      }
    }
  }
} 
```

```js
const emps = await Employee
    .query(db)
    .eager('[supervisor(selectFullName, selectAll)]')
    .modify(['selectFullName', 'selectAll'])
    .eagerAlgorithm(Model.JoinEagerAlgorithm)
```

Also are you sure you want to use `JoinEagerAlgorithm` here? The default algorithm is a lot safer choice if you don't explicitly need joins, which you don't seem to use here.

**Comment by koskimas** [comment]
You can add the `select('employees.*')` to the `selectFullName` modifier too if you want.

**Comment by zsf3** [comment]
That works like a charm. Thanks again :smile: 

Since I am using dynamic joins and custom fields with formula for multi-tenancy, I may have a lot of related tables. If I don't use `JoinEagerAlgorithm`, then many queries will be executed to fetch a single record. 

What do you suggest?

**Comment by koskimas** [comment]
If you have multiple one-to-one relations, `JoinEagerAlgorithm` can be a good choice and will improve performance. As soon as you join multiple 1-m or m-n relations, the performance can be orders of magnitude worse than with the default algorithm. The default doesn't create a query for each item separately, but one query per node in the relation graph. If you fetch one item with multiple 1-1 relations, it will create a single query per item though :smile: You can read more [here](https://www.vincit.fi/blog/nested-eager-loading-and-inserts-with-objection-js/)

You can keep using `JoinEagerAlgorithm` but keep in mind that in some cases it can lead to horrible performance.
