### ISSUE TITLE
Issue with onbuild for soft delete

### ISSUE THREAD

**Issue by dtam** [Vincit/objection.js#1429]
We have three models.

- programs
- users
- contests

programs have many users
programs have many contests

We have a soft delete as suggested [here](https://github.com/Vincit/objection.js/issues/88) but when we go to query through relationships the joinRelationship api we don't know what builder props we can use to add the deletedAt filter for the program:users relation. see the query and its sql below. 

```js
Contest
    .query()
    .joinRelation('[program.[users]]')
    .where('program:users.id', userID)
```

```sql
select "contests".* 
from "contests" 
inner join (
  select "programs".* 
  from "programs" 
  where "programs"."deletedAt" is null
) as "program" 
on "program"."id" = "contests"."programID" 
inner join "programs_users" as "program:users_join" 
on "program:users_join"."programID" = "program"."id" 
inner join (
  select "users".* 
  from "users" 
  where "users"."deletedAt" is null
) as "program:users" 
on "program:users_join"."userID" = "program:users"."id" 
where "contests"."deletedAt" is null 
and "program:users"."id" = ? 
```

For now we can manually add it to each of these queries via 
.where('program:users.deletedAt', '=', null)
but it'd be great if there was a way to do this in 1 place via the query builder

**Comment by koskimas** [comment]
One way is to create a `notDeleted` [modifier](https://vincit.github.io/objection.js/api/model/static-properties.html#static-modifiers) and then use it like this:

```js
Contest
    .query()
    .joinRelation('program(notDeleted).users(notDeleted)]')
    .where('program:users.id', userID)
```
