### ISSUE TITLE
[docs, recipes]: snake_case to camelCase conversion add note for consistency with using knex CLI migrations / seeds

### ISSUE THREAD

**Issue by the-vampiire** [Vincit/objection.js#1430]
i am using the `knexSnakeCaseMappers` for my models. but when i run my seed files using `knex` (some of which use models in their logic) it was not recognizing the conversion.

i finally figured out that in your `knexfile.*` you need to add the `knexSnakeCaseMappers` into the config as well. since this is the file that knex loads when executing seeds and migrations.

what do you think about adding a short note to the [snake_case to camelCase recipe doc](https://github.com/Vincit/objection.js/blob/master/doc/recipes/snake-case-to-camel-case-conversion.md) mentioning this?

here is my knexfile for reference, the `knexSnakeCaseMappers` needs to be spread into the config object (the same way it is spread into the knex config instance for the objection models)

**knexfile.js**
```js
const { knexSnakeCaseMappers } = require("objection");

const seeds = { directory: "./src/db/seeds" };

const config = {
  client: "postgresql",

  migrations: {
    tableName: "knex_migrations",
    directory: "./src/db/migrations",
    // stub: "./migration.stub", // custom migration template
  },

  connection: {
    host: process.env.DB_HOST,
    user: process.env.DB_USER,
    database: process.env.DB_NAME,
    password: process.env.DB_PASSWORD,
  },

  pool: {
    // min: 2,
    // max: 10,
  },
  // mape snake_case to camelCase
  ...knexSnakeCaseMappers(),
};

module.exports = {
  production: config,
  test: { ...config, seeds },
  development: { ...config, seeds },
};
```

**Comment by the-vampiire** [comment]
as an aside another note that might be useful to add to the recipes has to do with using objection models within a seed or migration file:

- you must re-initialize the `knex` instance on the models to be used by providing it the `knex` instance from the seed / migration **not** from your objection model knex
- otherwise there seems to be a competition between the seed / migration knex instance (loaded from `knexfile` config and that of the models themselves
- this was really hard to debug because it wasnt documented anywhere (that i could find at least)
- here is an example of what i mean

```js
exports.seed = async (knex) => {
// provide the seed / migration knex instance into each model being used
  Course.knex(knex);
  CourseLocation.knex(knex);

  await Course.query().del();
  await CourseLocation.query()
    .del()
    .debug();

  return createLocationsAndCourses(courseMocks);
};
```

**Comment by koskimas** [comment]
Since `knexSnakeCaseMappers()` is an addition to knex config, I think it should be fairly obvious that all knex configs need to have that added for it to work.

**Comment by mordof** [comment]
It's not a good idea to use models in your seeds or migrations. For that reason, I also personally intentionally do not use the snake case mapper for either of those.

The reasoning: Your seeds/migrations are written to be executed within the context of a current state of the application (e.g. the second migration you've ever made should stay the second migration executed). Meanwhile your models do not maintain any form of time-based context.

That means if the 6th migration you make changes a specific model you're using in the 2nd migration, you now have logic problems because the model is no longer correct to facilitate the change in the 2nd migration.

**Comment by the-vampiire** [comment]
> Since `knexSnakeCaseMappers()` is an addition to knex config, I think it should be fairly obvious that all knex configs need to have that added for it to work. Why would you expect some configs to magically install `knexSnakeCaseMappers()`?

thats fair. i didnt expect them to do anything magical lol. the confusion had more to do with how migrations and seeds use their own `knex` instance bound to the `knexfile` config (expected) that conflicts with the objection model `knex` instance (unexpected).

what i was suggesting was adding a note to that recipe that if a model is used in a `knex` driven seed  / migration then you need to add the snake case mappers to the `knexfile` _in addition to_ youre model `knex` config to maintain consistency.

**Comment by the-vampiire** [comment]
> It's not a good idea to use models in your seeds or migrations. For that reason, I also personally intentionally do not use the snake case mapper for either of those.
> 
> The reasoning: Your seeds/migrations are written to be executed within the context of a current state of the application (e.g. the second migration you've ever made should stay the second migration executed). Meanwhile your models do not maintain any form of time-based context.
> 
> That means if the 6th migration you make changes a specific model you're using in the 2nd migration, you now have logic problems because the model is no longer correct to facilitate the change in the 2nd migration.

great points wrt migrations. i actually encountered this when writing a `down` that relied on the models to migrate data between tables. for exactly the reasons you explained it was a hot mess!

but i disagree wrt seeds. maybe i am using them wrong but seeds for me are bound to the current state of the app. because they are used for integration tests / staging environment deployments. so they _should_ be up to date between the model and the state of the db when being executed.

**Comment by mordof** [comment]
> but i disagree wrt seeds. maybe i am using them wrong but seeds for me are always bound to the current state of the app. they dont have a chronological order like migrations and should be refactored as the state changes because they are used for integration tests / staging environment deployments. imo they should be up to date between the model and the state of the db when being executed.

true - all depends on the strategy your seeds take. I've seen some projects include seed updates/modifications in their migrations before too. Looks like knex by default does them all at once though, so yeah that's a bit of a different point.

In that case, if the style of seeds you're using matches, then may as well use the same connection setup your application uses.

**Comment by the-vampiire** [comment]
> In that case, if the style of seeds you're using matches, then may as well use the same connection setup your application uses.

there are two issues at play here:

1. unexpected / undocumented: the knex CLI and the objection models have conflicting connections to the db _even if they have identical configurations_. i have not found any way to have the knex CLI use the objection connection or vice versa
2. building on 1, recipe documentation: when using the snakecase mappers it would be nice to know that if you use objection models in a seed file you should not forget to add the snakecase mappers to the knexfile config. **and that you must reinitialize your models with the knexfile config instance.**

this is what this issue is about. when executing seeds through `knex seed:run [--specific <seed name.ext>]` it will use the config defined in the `knexfile.ext`. this is completely expected behavior.

the problem is that when you use an objection model within that seed the model tries (succeeds?) in making its _own_ connection as well. i havent seen any documentation on how to either get the knex CLI to use the objection model connection or vice versa. so you end up with some strange undocumented behavior where anything the model tries to execute just hangs up. i eventually debugged this using `debug()` and a timeout + exit on timeout. 

anyways sorry to waste your time guys. i was just suggesting adding a few lines of documentation to help someone else who might run into this issue - nothing to be changed in the lib itself. this closed issue can serve as the documentation. cheers

**Comment by mordof** [comment]
Oh, right. I don't use any of those CLI utils - I have one cli package I make that runs all of the necessary commands. It also imports my primary database connection setup, and hooks all the models onto it. I'm not a fan of using multiple different cli utils - so I combine them all into one like that, and add my own commands/helpers.
