### ISSUE TITLE
Organizing TypeScript tests

### ISSUE THREAD

**Issue by willsoto** [Vincit/objection.js#1431]
As I was working on adding more types, I felt like the current `example.ts` "dumping ground" is not really ideal for ensuring that the types are correct and that there are as few regressions as possible.

I would like to spend some time refactoring that to have better visibility into:

- Existing test coverage with TS
- What hasn't been tested
- Example usage that TS users can reference when they run into issues (even potentially as a guide to best practices regarding Custom Query Builders, etc)

Here is the quick view of what I have in mind:

```
├── custom-query-builder
├── joins
├── mixins
├── query-examples
│   ├── basic-queries
│   │   ├── delete.ts
│   │   ├── find.ts
│   │   ├── insert.ts
│   │   └── update.ts
│   └── relation-queries
├── transactions
└── where
```

I see it as a bit of a mix between going through the docs and ensuring that at least all the documented cases are covered while also making sure the basic operators are covered (all the possible ways to join, all the possible where clauses, etc)

Does this seem reasonable? Very much open to feedback on this.

cc/ @mordof

**Comment by koskimas** [comment]
Makes a lot of sense! Something like [dtslint](https://github.com/microsoft/dtslint) could also be useful.

**Comment by mordof** [comment]
I very much agree with how you feel about the current state of the types as well.

About the only thing I'd like to pick on from what you said is this:
> Existing test coverage with TS

This could mean two things, and I want to confirm...
does this mean that you want to change the normal javascript tests over to being typescript?
or does this mean you want to clarify the typescript type tests  in a clean way that's not just in the example file.

If it's the latter, I'm also on board with that. If it's the former, I don't think that's worth working on at this point in time.

**Comment by mordof** [comment]
A part about the examples/documentation... I'm wondering, can we have that in a different section compared to the typescript "tests", a location that we can actually include in official documentation generation for the page? Having a single root folder for everything typescript feels a bit yucky if we're handling tests, and example cases separated

**Comment by willsoto** [comment]
Yes, it's the latter. I'd like to clarify the type tests in a clean way so we can visually grep what is covered.

> A part about the examples/documentation... I'm wondering, can we have that in a different section compared to the typescript "tests", a location that we can actually include in official documentation generation for the page?

I'd personally love to have a TS recipes section or even just links in the docs that point people towards the type tests. For example, when I was writing a custom query builder in TS, it would have been great to have a dedicated page for that instead of having to endlessly dig and google for patterns. I basically spent most of time piecing together how people typed their custom query builders...

**Comment by willsoto** [comment]
@mordof do you have anything in the works? Do you mind if I just start this out and get something in place so others can work on it?

**Comment by mordof** [comment]
@willsoto  this endeavor doesn't actually split up/drastically change the type definitions themselves correct? It's focused on the types/examples/documentation of ts? If that's the case, then go for it. I'm currently focused on the mixin types, and then afterwards pulling in whatever updates/additions have been added to new-typings and getting that finished up.

**Comment by willsoto** [comment]
That is correct. It shouldn't change the type definitions at all. I'll go ahead and start working on something this week then 👍
