### ISSUE TITLE
Typescript Error handling is not Working

### ISSUE THREAD

**Issue by aramkumar06** [Vincit/objection.js#1432]
https://vincit.github.io/objection.js/recipes/error-handling.html#examples this reference is not properly working  for https://github.com/Vincit/objection.js/tree/master/examples/express-ts 

I am getting error result
Status:500
{
  "type": "UnknownError",
  "data": {}
}

Experted: in status 500
{
  "code": "ER_BAD_DB_ERROR",
  "errno": 1049,
  "sqlState": "42000",
  "sqlMessage": "Unknown database 'interviw'"
}

Code:
App.ts
import {errorHandler} from './lib/error-handler';
const app = express()
  .use(bodyParser.json())
  .use(express.urlencoded())
  .use(cors())
  .use(morgan('dev'))
  .use(router)
  .set('json spaces', 2)
  .use(errorHandler)

error-handler.ts
import {ValidationError,NotFoundError} from 'objection';
import {  DBError,
    ConstraintViolationError,
    UniqueViolationError,
    NotNullViolationError,
    ForeignKeyViolationError,
    CheckViolationError,
    DataError} from 'objection-db-errors' ;
import {  Response } from 'express';
export let errorHandler = (err:any, res:Response) =>{
    if (err instanceof ValidationError) {
        switch (err.type) {
          case 'ModelValidation':
            res.status(400).send({
              message: err.message,
              type: err.type,
              data: err.data
            });
            break;
          case 'RelationExpression':
            res.status(400).send({
              message: err.message,
              type: 'RelationExpression',
              data: {}
            });
            break;
          case 'UnallowedRelation':
            res.status(400).send({
              message: err.message,
              type: err.type,
              data: {}
            });
            break;
          case 'InvalidGraph':
            res.status(400).send({
              message: err.message,
              type: err.type,
              data: {}
            });
            break;
          default:
            res.status(400).send({
              message: err.message,
              type: 'UnknownValidationError',
              data: {}
            });
            break;
        }
      } else if (err instanceof NotFoundError) {
        res.status(404).send({
          message: err.message,
          type: 'NotFound',
          data: {}
        });
      } else if (err instanceof UniqueViolationError) {
        res.status(409).send({
          message: err.message,
          type: 'UniqueViolation',
          data: {
            columns: err.columns,
            table: err.table,
            constraint: err.constraint
          }
        });
      } else if (err instanceof NotNullViolationError) {
        res.status(400).send({
          message: err.message,
          type: 'NotNullViolation',
          data: {
            column: err.column,
            table: err.table,
          }
        });
      } else if (err instanceof ForeignKeyViolationError) {
        res.status(409).send({
          message: err.message,
          type: 'ForeignKeyViolation',
          data: {
            table: err.table,
            constraint: err.constraint
          }
        });
      } else if (err instanceof CheckViolationError) {
        res.status(400).send({
          message: err.message,
          type: 'CheckViolation',
          data: {
            table: err.table,
            constraint: err.constraint
          }
        });
      } else if (err instanceof DataError) {
        res.status(400).send({
          message: err.message,
          type: 'InvalidData',
          data: {}
        });
      } else if (err instanceof DBError) {
        res.status(500).send({
          message: err.message,
          type: 'UnknownDatabaseError',
          data: {}
        });
      } else {
          
        
        res.status(500).send({
          message: err.message,
          type: 'UnknownError',
          data: {}
        });
      }
}

**Comment by aramkumar06** [comment]
i am checked Typesript error handling not working

**Comment by Sent1ence** [comment]
Have anyone found a solution for this? I can't seem to get this to work.

**Comment by elhigu** [comment]
Seems to work. Invalid database connection configuration results to UnknownError result.
