### ISSUE TITLE
Ability to set default property to result of relation.

### ISSUE THREAD

**Issue by lossless1** [Vincit/objection.js#1434]
Hello, 

I have a problem related to getting related data from the database and set as a result if null something else.
For example. `A` has a relation with `B` and `B` don't have any `id` to connect with `A`, but anyway connected to `A` and have `default` value `null` overwise, I will get some data of `object` or `array`.
How I can change this default `null` value of relation data?

**Comment by koskimas** [comment]
Sorry I don' understand. Could you write an example?

**Comment by koskimas** [comment]
Okay, I'll try to guess. So in case a relation has items in it, you still want to get some value in the relation when you eager-load stuff?

Something like this:

```js
const personWithNoParent = await Person.query().eager('parent')
console.log(personWithNoParent.parent) // { some: 'default value' }
``` 

One way to achieve this is to override the `toJSON` method:

```js
class Person extends Model {
  toJSON(...args) {
    const json = super.toJSON(...args)
    if (!json.parent) {
      json.parent = { some: 'default value' }
    }
    return json
  }
}
```

Note that this only sets the default value when you send the model instance over the wire. The default value doesn't exist on the model instance after the query.
