### ISSUE TITLE
Wrong return type for `findById` passed with composite key

### ISSUE THREAD

**Issue by ronyclau** [Vincit/objection.js#1435]
# Type of issue
Bug in TS type definition

# Description / Steps to reproduce
In the TS type definition of `QueryBuilderBase`, only these two [overloads of `findById`](https://github.com/Vincit/objection.js/blob/master/typings/objection/index.d.ts#L734-L735) are present:

```typescript
{
  // ...
  findById(id: Id): QueryBuilderYieldingOneOrNone<QM>;
  findById(idOrIds: IdOrIds): this;
  // ...
}
```

Let's say a model has a composite primary key, the following use case would trigger a compile-time error due to the incorrect overload:
```typescript
class SomeModel extends objection.Model {
  static idColumn = ['idField1', 'idField2']

  // ...
}

SomeModel.query()
  .findById([1, 100])
  .then((model: SomeModel | undefined) => {
    //   ^^^^^ error TS2740
  });
```

In the above case, the only eligible overload is
```typescript
findById(idOrIds: IdOrIds): this;
```

`await`-ing / `.then()` on the return type of this overload only yields `SomeModel[]`.

# Expected result
The code should compile.

# Actual result
```
error TS2740: Type 'SomeModel[]' is missing the following properties from type 'SomeModel': id, type, articles, $beforeInsert, and 31 more.
```

**Comment by koskimas** [comment]
Thanks! PR is merged now.
