### ISSUE TITLE
How to map many-to-many relationship with more than two tables?

### ISSUE THREAD

**Issue by cerberusv2px** [Vincit/objection.js#1438]
Suppose I have a table A,B and C. and make a pivot table ABC with columns a_id, b_id, c_id.
How to map this type of relationship using objection?

**Comment by koskimas** [comment]
Just like with two tables? If you want more info, please provide more details of what your're after.

**Comment by koskimas** [comment]
We can continue the discussion here even though I closed this.

**Comment by cerberusv2px** [comment]
> Just like with two tables? If you want more info, please provide more details of what your're after.

Yes @koskimas just like we do in two tables. Something like this
`join: {
          from: 'a.id',
          through: {
            from: 'ab.a_id',
            to: 'ab.b_id'
          },
          to: 'b.id'
        }`

But I want relation between 3 tables (abc) just like above

**Comment by koskimas** [comment]
That doesn't make any sense. How would you want it to work with fetches? Inserts? Deletes? Joins? Anyway, it's not possible

**Comment by cerberusv2px** [comment]
So you are telling me you have not worked with a table which references to three different tables?
Something like this: https://dba.stackexchange.com/questions/158586/how-to-implement-many-to-many-relation-between-three-table

**Comment by koskimas** [comment]
I'm telling you, you're not providing enough information. I have no idea what you mean.

If you want us to take a look at this, please read [these instructions](https://vincit.github.io/objection.js/guide/contributing.html#issues) on how to create issues.

**Comment by koskimas** [comment]
The example you linked is just a bunch of normal many-to-many relationships between the three tables. So as I said, you'd implement them just like you would with two tables:

```js
class A extends Model {
  static relationMappings: {
    b: {
      join: {
        from: 'a.id',
        though: {
          from: 'abc.a_id',
          to: 'abc.b_id'
        },
        to: 'b.id'
      }
    },
    c: {
      join: {
        from: 'a.id',
        though: {
          from: 'abc.a_id',
          to: 'abc.c_id'
        },
        to: 'c.id'
      }
    }
  }
}
```

and so on. If that's not what you're after, please provide more information and examples.

**Comment by koskimas** [comment]
Another option is to create a `HasManyRelation` to the junction table from all `a`, `b` and `c` and then `BelongsToOne` relations to the other two. Something like:

```js
class ABC extends Model {
  static relationMappings = {
    a: {
      relation: Model.BelongsToOneRelation,
      modelClass: A,
      join: {
        from: 'abc.a_id',
        to: 'a.id'
      }
    },

    b: {
      relation: Model.BelongsToOneRelation,
      modelClass: B,
      join: {
        from: 'abc.b_id',
        to: 'b.id'
      }
    },

    c: {
      relation: Model.BelongsToOneRelation,
      modelClass: C,
      join: {
        from: 'abc.c_id',
        to: 'c.id'
      }
    }
  }
}

class A extends Model {
  static relationMappings = {
    abc: {
      relation: Model.HasManyRelation,
      modelClass: ABC,
      join: {
        from: 'A.id',
        to: 'abc.a_id'
      }
    }
  }
}
```

**Comment by cerberusv2px** [comment]
Ok. I will try these solutions and will share if there are any issues. Thank you for your time :)

**Comment by koskimas** [comment]
This might also be useful https://vincit.github.io/objection.js/recipes/ternary-relationships.html#ternary-relationships
