### ISSUE TITLE
upsertNode in context/hooks

### ISSUE THREAD

**Issue by venelin-mihaylov** [Vincit/objection.js#1439]
I want to accumulate all operations carried out by graphUpsert() for audit purposes.
- table, 
- insert/update/patch values, 
- operation, 
- parentNode (table), // for relations
- parentPrimaryKey // for relations

I am looking at the source code of GraphInsert,GraphPatch,GraphDelete.
I hacked the objection code to merge the current node with the QueryBuilder context, but that's not nice.
Is there another way?

**Comment by koskimas** [comment]
There's no way to do that using the public API unfortunately.
