### ISSUE TITLE
How to construct chained joins?

### ISSUE THREAD

**Issue by ozum** [Vincit/objection.js#144]
Hi,

Using v0.5.0-rc.5. How can I create chained joins using `innerJoinRelation()`?

```js
// For example: country -----< city ------< district

Country.
    query()
    .eager('city')
    .eager('city.district')
    .then((result) => {})

// By looking above code, I wrote code below. However it does not work.
Country.
    query()
    .innerJoinRelation('city')
    .innerJoinRelation('city.district')
    .then((result) => {})
```

Best Regards,

**Comment by koskimas** [comment]
Not possible at the moment using those methods. `*JoinRelated` are just shortcuts for the knex join methods. You can do this manually by building the query using knex methods.

**Comment by koskimas** [comment]
This is basically a duplicate of #73. That issue basically requests the same feature in a different form.

**Comment by ozum** [comment]
Yes it seems similar to #73, which I also think `belongs to` `eager`'s should use joins instead of second query, but I think this issue is different. Both requests are similar by implementation, but different by their results.

Eager queries results are cascaded (object inside attribute of another object), on the other hand `innerJoinRelation`'s result is single dimensional. They are both useful for different purposes.
