### ISSUE TITLE
Select from multiple rows

### ISSUE THREAD

**Issue by PiedPieper** [Vincit/objection.js#1441]
Title says it all. Is this possible w/ objection or do I need to use knex?

**Comment by koskimas** [comment]
```js
const result = await Person.query().select('id')
```
This selects the id from every result row. This probably isn't what you mean though. So the title doesn't say it all 😀

**Comment by PiedPieper** [comment]
Oops! I meant  select from multiple tables

**Comment by koskimas** [comment]
You can join other tables using any of the join methods. You can search for `join` in the docs and you'll get a bunch of options to choose from. The knex join methods work and objection also has the `joinRelation` method family that's quite powerful. You can also use the `from` method to select from multiple tables. You need to read knex docs for that one. You van also use common table expressions (CTE) using the `with` method. Consult the kex docs also with that method.

**Comment by PiedPieper** [comment]
Ok, so rather than select 2 use a join. If I want to select 2 tables i need to use knex

**Comment by koskimas** [comment]
No you don't need to use knex. I just provided you two ways to select multiple tables, in addition to using joins.
