### ISSUE TITLE
related query without having to query twice

### ISSUE THREAD

**Issue by PiedPieper** [Vincit/objection.js#1444]
```
const txnRes = await Txn.query().findById(20);
const payer = await txnRes.$relatedQuery("payer");
```

Can this be done in one action using relatedQuery? [This example ](https://github.com/Vincit/objection.js/blob/master/examples/express-ts/src/api.ts)at least uses 2 separate queries each. The issue is that this will be 2 round trips.

**Comment by koskimas** [comment]
Not yet, 2.0 can do just that:

```js
await Txn.relatedQuery('payer').for(20)
```

you will be able to give multiple ids

```js
await Txn.relatedQuery('payer').for([20, 21])
```

or even subqueries

```js
await Txn.relatedQuery('payer').for(
  Txn.query().where('something', something)
)
```

**Comment by koskimas** [comment]
https://github.com/Vincit/objection.js/issues/1365

**Comment by koskimas** [comment]
But of course you can already do that using SQL. Assuming `payer` is a `BelongsToOneRelation`, you can do this:

```js
await Payer.query().where('id', Tx.query().findById(20).select('payerId'))
```

That's one single query, and basically what the static `relatedQuery` method will be building.
