### ISSUE TITLE
Limit on paged results

### ISSUE THREAD

**Issue by avck25** [Vincit/objection.js#1445]
How would I go about passing a limit to the number of results I want from the page function? 
For example, if I have a query that would return 15,000 calling `page(pageNumber, 15) `
I get 15 results but the total is 15,000 and the number of pages is 1000  how would I be able to limit that total to like passing in another limit of like 150  and get a total of 150 and pages 15?

**Comment by koskimas** [comment]
By removing items.

**Comment by koskimas** [comment]
Or you can simply change the `total` value of the returned object and then explicitly disallow/limit the maximum page that can be requested.

**Comment by avck25** [comment]
thanks for the response I can't really remove items as this is a company with 1000's of products and the issue is when somebody searches with an empty search term.
Your second option is intriguing it might go quicker than searching through 1000's of products to just limit to 250 and then run the paged on that.
Thank you very much I greatly appreciate your taking the time to answer and thank you for speeding up my development time by having worked on Objection.
