### ISSUE TITLE
No way to create custom identifier for use in many to many relations with upsertGraph

### ISSUE THREAD

**Issue by zjr** [Vincit/objection.js#1447]
It can sometimes be useful to relate to items to each other through a many to many relationship multiple times. Currently, `upsertGraph` doesn't support this because it uses the `id` of the target item to identify items. 

Related to discussion here: https://gitter.im/Vincit/objection.js?at=5d587a33bb5364334c4f8690

**Comment by jamespedid** [comment]
Can't you use "#ref{myrecord.someOtherValue}" in each field that you need to refer to that object's property?
