### ISSUE TITLE
QueryBuilder returns null even if array is expected

### ISSUE THREAD

**Issue by alexkvak** [Vincit/objection.js#1448]
There is an issue in TS typings or even Objection `QueryBuilder`.
https://github.com/Vincit/objection.js/blob/master/lib/queryBuilder/QueryBuilder.js#L1431

If the query gets nothing from DB it returns `null` instead of empty array.

Have you plan to fix this behavior?

**Comment by koskimas** [comment]
It returns null only in case a single item is queried (findById, findOne, first). Those should be correctly typed.
