### ISSUE TITLE
Creating new model instances without changing the database?

### ISSUE THREAD

**Issue by sripberger** [Vincit/objection.js#1449]
This is intended more as a question and less as a feature request. I'm aware that Objection deliberately does not do a lot of the things other ORM's do-- it is one of the reasons I've been enjoying it.

However, a common pattern in other ORM's allows you to create an instance of a model, use it in some way, then call a method (usually put) to actually save it to the database. I can't seem to find documentation or issues mentioning anything like this, so it leads me to believe this is not possible by design-- though of course I do want to double check.

My use case has to do with permissions checks-- particularly for creation of entities. The permissions model at my company is rather complicated, and permissions for one entity can occasionally depend on the state of related entities.

For example, let's say a 'Foo' model has a `has one` relation with a 'FooParent' model. FooParents  have a property called `state` which is either 'open' or 'closed'. A user may be allowed to create Foo entities inside open FooParents only, and not closed ones. 

I'm addressing these complications by creating a permissions-checking library similar to [this one](https://www.npmjs.com/package/flexperm) which will accept an entity (an instance of a Model) and, given a certain permission string, check to see if the user is granted that specific permission string for that specific entity.

This library would be aware that the instance provided to it is an Objection model, so it could automatically use `$relatedQuery` to look up information about related entities, where necessary. So the permissions check on creation would work something like this:

```js
// Assuming 'foo' is an instance of Foo:
await permissions.check(foo, 'create');
```

The `permissions` object here would contain the info that says the 'create' permission depends on the state of the parent of Foo, so it would do that $relatedQuery (assuming the parent wasn't already eagerly-loaded onto foo) and verify that `parent.state === 'open'` as part of the check. Of course, it will reject if the check fails, causing a 403 on my endpoint.

The only trouble here is where I get that instance of Foo in the first place. It doesn't exist in the database yet-- so I can't get it from a query-- and I of course don't want to write anything to the database until *after* the permissions check is done, not before, so doing something like this won't work unless I wrap it in a transaction that I can abort later, which seems wasteful:

```js
const foo = await Foo.query().insert({ /* properties from request params */ });
```

The `Foo` constructor won't do anything as Objection's `Model` class uses the default JS class constructor-- which is to say it does nothing but set the prototype. So if I wanted to do this, it seems I would have to create it with the constructor and then assign all the properties I need onto it myself. Or possibly make a static method in my own Model subclass that does this.

Is there an API or method somewhere that I am missing which I could use to do something like this? If not, is it something you guys would be open to adding to Objection itself? I would be happy to help out, of course.

**Comment by koskimas** [comment]
Objection has the sttatic `fromJson` and `fromDatabaseJson` methods that are used instead of the constructors. You should be able to use those.

**Comment by koskimas** [comment]
https://vincit.github.io/objection.js/api/model/static-methods.html#static-fromjson

**Comment by sripberger** [comment]
Perfect. Not sure how I missed those. Thank you!
