### ISSUE TITLE
Objection vs Knex

### ISSUE THREAD

**Issue by rickmed** [Vincit/objection.js#145]
Hello,

Seems like a very cool library but I'm a bit confused about what knex provides and what objection adds...Is there somewhere I can read about it? thanks!

EDITED: nevermind. Thanks :)

**Comment by elhigu** [comment]
Knex provides basic query builder, transactions, connection pooling. 

On top of that Objection.js provides models, relations, schema for models attributes and some more advanced features to insert / fetch nested models and JSONB query support for postgresql... and probably much more that I forgot to mention.

**Comment by fl0w** [comment]
@elhigu I'd be specific about the distinction between "schema" and "schema validation", but other than that, sums it up! 👍

**Comment by fl0w** [comment]
Maybe this can be closed (original post edited, post enlightenment).

**Comment by elhigu** [comment]
This stuff kind of relates to #11 if also knex vs. objection distinction is described there some day.
