### ISSUE TITLE
Is it possible to "eager" without string wrapped array syntax?

### ISSUE THREAD

**Issue by shaibam** [Vincit/objection.js#1450]
Hello,
When querying using an "eager" array the syntax is a string wrapped array, which makes the query syntax very strict. If you forget to add a character space after the comma the whole query goes to hell.
Is there a way to "eager" query with an "object" syntax?

eg.
instead of :
`.eager('[firstRelation(firstfilter), seconfRelation(secondFilter)])`
do something like :
`.eager({firstRelation:{filter:()=>{}},secondRealtion:{filter:()=>{}})`

**Comment by koskimas** [comment]
Yes https://vincit.github.io/objection.js/api/types/#relationexpression-object-notation

**Comment by shaibam** [comment]
THank you very much!
