### ISSUE TITLE
patchAndFetchById with empty patch object does not fetch object from database

### ISSUE THREAD

**Issue by svrnwnsch** [Vincit/objection.js#1452]
The code
```
Model.query().patchAndFetchById(1,{})
```
does not fetch the object with `id=1` from database. Either this is a bug or the documentation can be improved here. But I would expect that in these cases just the unmodified object would be returned like calling `fetchById`. 

objection version: 1.6.3

**Comment by koskimas** [comment]
This is intended behavior. The empty result is the only way to know id something actually got updated. An update to the docs is welcome as a PR.
