### ISSUE TITLE
Map json_agg() column to Model class

### ISSUE THREAD

**Issue by josser** [Vincit/objection.js#1454]
Hi! 
I'm using raw selects to avoid issues with page() and eager loading via InnerJoin.
Here is how I do this: 
 ```javascript
Video.query()
      .select(raw('video.*'), raw('json_agg(output.*)').as('output'))
      .where('user_id', userId)
      .page(options.page, options.limit)
      .innerJoinRelation('output(playable)')
      .groupBy('video.id')
```
Produced sql is something like: 
```sql
select video.*, json_agg(output.*) as output
from video
inner join output on video.id = output.video_id
where video.user_id = ?
group by video.id
```

And response from knex is good, the only one thing is not working properly - virtual fields. 
Is there any way to specify model mapping for jsonb column. Maybe something like: 
```javascript
raw('json_agg(output.*)').as('output').model(Output)
```
so every item in jsonb returned from db will be cast to model instance. So, I can get virtual fields from my 'output' model. 

thank you and sorry if my english is not good :)

**Comment by koskimas** [comment]
You can just use `joinEager` instead of joinRelation. But if you want to use json_agg, you can use virtual attributes to convert the result to model instances.

**Comment by josser** [comment]
joinEager can't work with .page()
Can you please explain a bit your suggestion about virtual attributes.
I thought this thing is used to create virtual columns. In examples they usually used to create 'fullName' column from first_ and last_ names. 
But I can't imagine how I can use this to convert result to model instance. 
I guess there should be method to convert plain object to model

**Comment by josser** [comment]
I've managed to do this in such way: 
```javascript
Media.query()
      .select('video.*', raw('json_agg(output.*)').as('output'))
      .where('user_id', userId)
      .innerJoin(raw('output on output.video_id = video.id'))
      .groupBy('video.id')
      .page(page, limit)
      .then(data => {
        data.results = data.results.map(video => {
          video.output = video.output.map(output => Output.fromDatabaseJson(output))
          return video
        })
        return data
      })
```

But maybe there is more elegant way?
