### ISSUE TITLE
UpsertGraph deletes rows for relation which is not mentioned in graph

### ISSUE THREAD

**Issue by lynxtaa** [Vincit/objection.js#1455]
I'm using `objection@1.6.9` and have these models:

```js
class Role extends Model {
  static get tableName() {
    return 'roles'
  }

  static get relationMappings() {
    return {
      sets: {
        relation: Model.HasManyRelation,
        modelClass: 'Set',
        join: { from: 'roles.id', to: 'sets.roleId' },
      },
    }
  }
}

class Set extends Model {
  static get tableName() {
    return 'sets'
  }

  static get relationMappings() {
    return {
      setAttributes: {
        relation: Model.HasManyRelation,
        modelClass: 'SetAttribute',
        join: { from: 'sets.id', to: 'sets_attributes.setId' },
      },
    }
  }
}

class SetAttribute extends Model {
  static get tableName() {
    return 'sets_attributes'
  }
}
```

Suppose role with ID 1 already has set with ID 1.

If I'm using upsertGraph like this, It works correctly -- new row is inserted in "sets" table:

```js
transaction(Role.knex(), trx =>
  Role.query(trx).upsertGraph({
    id: 1,
    sets: [{ id: 1 }, { name: 'New Set' }],
  }),
)
```

But if I pass "setAttributes" for newly created set, **Objection deletes all setAttributes for the first set** (with id=1):

```js
transaction(Role.knex(), trx =>
  Role.query(trx).upsertGraph({
    id: 1,
    sets: [
      { id: 1 },
      { name: 'New Set', setAttributes: [{ name: 'New Set Attribute' }] },
    ],
  }),
)
```

Is this behaviour expected?

**Comment by koskimas** [comment]
Could you provide a reproduction for this? I don't believe this is really happening. There are tests for this case. I'll fix it immediately if you can provide a reproduction.

**Comment by lynxtaa** [comment]
Thanks for a quick response ! I've created reproducible example: https://github.com/lynxtaa/objection-issue

**Comment by koskimas** [comment]
Thanks for the repro! I'll see what's going on asap.

**Comment by lynxtaa** [comment]
@koskimas any updates on this?

**Comment by koskimas** [comment]
I'll post here once I find time to work on this.

**Comment by koskimas** [comment]
Fix coming up soon. Sorry it took so long.

**Comment by koskimas** [comment]
Oh man, this was a pretty nasty bug! I can't believe why nobody reported this earlier. objection 1.6.10 will be released in couple of minutes.

**Comment by lynxtaa** [comment]
@koskimas Thank you! We are using Objection.js in production and very happy with it
