### ISSUE TITLE
how to combine map() and pick()?

### ISSUE THREAD

**Issue by NajwaSM** [Vincit/objection.js#1456]
Hi, I try to do a function like this for my services - try to combine map and pick but it seems like not working. can someone help? p/s: i'm a newbie :) sorry if my issue seems stupid 

```js
const orderHistory = async () => {
  const trades = await Trade.query().whereNotIn('status', ['PENDING', 'CANCELED']);

  const data = trades.map(trades.pick(Trade, ['marketId', 'orderType', 'tradeType', 'status']));

  return {
    fields: ['marketId', 'orderType', 'tradeType', 'status'],
    data,
  };
};

export default {
  orderHistory,
};
```

**Comment by koskimas** [comment]
You don't need to use both `map` and `pick`. Pick picks the fields from every item. All you need is this:

```js
const orderHistory = async () => {
  const trades = await Trade
    .query()
    .whereNotIn('status', ['PENDING', 'CANCELED'])
    .pick(['marketId', 'orderType', 'tradeType', 'status']);

  return {
    fields: ['marketId', 'orderType', 'tradeType', 'status'],
    data,
  };
};

export default {
  orderHistory,
};
```

in your example, the `trades` variable already contains an `Array` of `Trade` items. An `Array` doesn't have a `pick` method. The objetion query builder does. `await` executes the query builder and returns the result (in this case the array).

**Comment by koskimas** [comment]
Actually even better would be to select only the fields you need:

```js
const orderHistory = async () => {
  const trades = await Trade
    .query()
    .select(['marketId', 'orderType', 'tradeType', 'status'])
    .whereNotIn('status', ['PENDING', 'CANCELED']);

  return {
    fields: ['marketId', 'orderType', 'tradeType', 'status'],
    data,
  };
};

export default {
  orderHistory,
};
```

**Comment by NajwaSM** [comment]
> Actually even better would be to only select the fields you need:
> 
> ```js
> const orderHistory = async () => {
>   const trades = await Trade
>     .query()
>     .select(['marketId', 'orderType', 'tradeType', 'status'])
>     .whereNotIn('status', ['PENDING', 'CANCELED']);
> 
>   return {
>     fields: ['marketId', 'orderType', 'tradeType', 'status'],
>     data,
>   };
> };
> 
> export default {
>   orderHistory,
> };
> ```
> 
> this way no unneeded data is transferred from the database to the node process.
Hi @koskimas 
thank you for replying. i actually try to create a service. where user can choose whatever field that they want. that is why i'm specifying all the fields that can be accessible by user despite of limit the attributes. i actually try to use both pick and map like this: 

const orderHistory = async () => {
  const trades = await Trade.query().whereNotIn('status', [ 'PENDING',  'CANCELED']);

  const data = trades.map(trade => trade.pick(Trade, ['marketId', 'orderType', 'tradeType', 'status']));

  return {
    fields: ['marketId', 'orderType', 'tradeType', 'status'],
    data,
  };
};

**Comment by NajwaSM** [comment]
> You don't need to use both `map` and `pick`. Pick picks the fields from every item. All you need is this:
> 
> ```js
> const orderHistory = async () => {
>   const trades = await Trade
>     .query()
>     .whereNotIn('status', ['PENDING', 'CANCELED'])
>     .pick(['marketId', 'orderType', 'tradeType', 'status']);
> 
>   return {
>     fields: ['marketId', 'orderType', 'tradeType', 'status'],
>     data,
>   };
> };
> 
> export default {
>   orderHistory,
> };
> ```
> 
> in your example, the `trades` variable already contains an `Array` of `Trade` items. An `Array` doesn't have a `pick` method. The objetion query builder does. `await` executes the query builder and returns the result (in this case the array).

trades variable return object, not array. since i'm using objectionsJS, it'll return the variable trades into object instead of array
