### ISSUE TITLE
Should throw when using loadRelated incorrectly

### ISSUE THREAD

**Issue by lynxtaa** [Vincit/objection.js#1457]
Consider we have following code:

```js
transaction(User.knex(), async trx => {
  const user = await User.query(trx).insertGraph(...)
  const { roles } = await user.$loadRelated('roles', trx)
  // ...
})
```

There's a bug, correct usage is:
```js
$loadRelated('roles', null, trx)
```

Objection.js shows no warning: `$loadRelated` doesn't use transaction and may cause knex errors like `TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?` when we run transactions in parallel.

Can you add a check for the `modifiers` argument or make Objection work if second argument is a transaction?

**Comment by koskimas** [comment]
I'd merge a PR for throwing if the second argument is the transaction. Feel free to provide one.

**Comment by lynxtaa** [comment]
@koskimas , will it be better if we do something like this?
```js
if (isKnexTransaction(modifiers)) {
  modifiers = null;
  trx = modifiers;
}
```

**Comment by koskimas** [comment]
@lynxtaa Actually this gets taken care of in v2.0 that is just around the corner. I've unified the method naming and interfaces and the `$loadRelated` method will be called `$fetchGraph` that has the following API:

```js
transaction(User.knex(), async trx => {
  const user = await User.query(trx).insertGraph(...)
  const { roles } = await user.$fetchGraph('roles', { transaction: trx })
  // ...
})
```

Modifiers are no longer passed to the function at all, but a separate `query` method `modifiers` will be added. The old `$loadRelated` method will not be removed before 3.0 though.

With `$fetchGraph`, the modifiers can be installed like this:

```js
transaction(User.knex(), async trx => {
  const user = await User.query(trx).insertGraph(...)
  const { roles } = await user
    .$loadRelated('roles(someModifier)', trx)
    .modifiers({
      someModifier(query) {
        ...
      }
    })
  // ...
})
```

**Comment by lynxtaa** [comment]
That's perfect! I'll wait for the next version
