### ISSUE TITLE
Bug: Models break with jest config resetModules: true

### ISSUE THREAD

**Issue by markmsmith** [Vincit/objection.js#1458]
When using the jest testing framework, you can set the configuration `resetModules` to `true`, which will cause any previously loaded modules to be reset between tests (removed from the module cache), so as to avoid any contamination between tests from modules' first-load behavior:  
https://jestjs.io/docs/en/configuration#resetmodules-boolean

Unfortunately, this causes a problem when working with a graph of Objection models, as it checks if their base class is `Model` by walking up the Constructor hierarchy and doing an exact equals check:  
https://github.com/Vincit/objection.js/blob/1.6.9/lib/utils/classUtils.js#L11  
which is called from here:  
https://github.com/Vincit/objection.js/blob/1.6.9/lib/relations/Relation.js#L266  

Since the modules have been reset between the initial import of the `Model` for the class and when the test runs `getModel()` under the hood, you incorrectly get the error `Relation's owner is not a subclass of Model` due to the different instances of the class not comparing equal,  and go hunting for circular imports, even when none exist.  

At a minimum, it would  be nice to call out a warning about this in the docs (since it took me a long time to figure out what was going on), but it might also be possible to avoid the issue entirely if a different mechanism can be found to detect that a class extends `Model` (even if it's a different instance of it).  

I don't have a perfect solution, but one option that might work for most practical purposes would be to add a long static `CLASS_ID` property to `Model` and then just check for that instead, eg
```js
class Model {
  static get CLASS_ID() {
    // some long value that's unlikely to ever accidentally clash
    return 'objectionjs_model_1234556789-CAFE-BEEF'
  }
   ....
}
```
Alternatively, you could maybe implement some sort of duck-typing, where the check instead confirms if the necessary static methods of `Model` are present on the Constructor being tested.

**Comment by koskimas** [comment]
If there was a warning about this in the docs, do you really think you would have found it? Feel free to implement a workaround for this. I will merge the PR. But I think you are misusing the resetModules flag. Why aren't you recreating the inherited classes too? You should never mix different instances of the same module like that. Objection won't be the last module that breaks when misused like that

**Comment by koskimas** [comment]
Actually all the usages of `isSubclassOf` will fail when you use `resetModules` without recreating the objection models. It's not used just for model classes, but internal classes too. `isSubclassOf` is used 18 times in the codebase. In order to fix this, all those should be removed.

Must of those checks only check against a known base class. All internal objection classes already have these

```js
Object.defineProperties(Relation.prototype, {
  isObjectionRelation: {
    enumerable: false,
    writable: false,
    value: true
  }
});
```

so you could implement functions like `isObjectionRelationClass`, `isObjectionModelClass` etc. instead of using the `isSubclassOf`. For example:

```js
function isObjectionModelClass(maybeModelClass) {
  return isFunction(maybeModelClass) && !!maybeModelClass.prototype.$isObjectionModelClass
}
```

**Comment by markmsmith** [comment]
Nice, that definitely seems like a good approach.  
It can take a while to get approval from our Legal department to contribute to Open Source projects unfortunately (and I'm about to go vacation), so I can't promise when I'd be able to do a PR for this.  

As for the warning in the docs, I read every scrap of info I could find about require loops and the error message when I ran in to this, so I'm pretty sure it would have helped me if there had been something in there.  Instead I spent quite a long time chasing down what was different between your (excellent) TS example and my code, eventually narrowing it down to only breaking during tests, and only when that flag was on.
Maybe a short note in the [Require loops](https://vincit.github.io/objection.js/guide/relations.html#require-loops) section like:

```md
Note: This error can also occur in Jest unit tests using `resetModules`, which will cause the originally imported model's base class not to match the instance that Objection looks for during the test.  The workaround at this time is to set `resetModules` to `false`, or to dynamically import the model during the test to ensure it's using the exact same instance of the `Model` base class.
```

**Comment by koskimas** [comment]
> It can take a while to get approval from our Legal department to contribute to Open Source projects

For what kind of a shithole company do you work for :smile: 

I'll remove the isSubclassOf calls and release a new version soon.

**Comment by markmsmith** [comment]
Thanks for the fix, this is much better that just the warning I had suggested! :)

**Comment by jpongin** [comment]
5 years in, and I may be running into this after spending 2 days debugging. Thank you so much for the detailed discussion. Will try to look into our usage of resetModules. We're still on the version of objection that uses `isSubclassOf`.
