### ISSUE TITLE
Bug: Unique binary hex IDs are being mistakenly flagged as duplicates

### ISSUE THREAD

**Issue by rajdeut** [Vincit/objection.js#1459]
It appears that the `uniqBy` function in `objectUtil.js` is incorrectly removing IDs that are unique when they're Hex encoded binaries.

Using MySQL we have a series of `meetings` with a very basic belongs to one relationship with `venues`.

We're using binary fields to store a UUID for each.

When we retrieve more than 10 meetings in a query we noticed that occasionally venues were returning as null, despite displaying a different decoded UUID.

Our UUID's are formed by taking the string representation and turning them into Buffers
eg. `Buffer.from(uuid.replace(/-/g, ''), 'hex');`

Digging deeper the `uniqBy` function would take the Buffer.toString() value and perform its necessary operations removing duplicates, however as you can see from the attached screenshot despite having different UUIDs the UTF8 `.toString()` representation has duplicates and would be removed.

![Screen Shot 2019-09-02 at 9 02 00 pm](https://user-images.githubusercontent.com/401329/64110543-d0fcf180-cdc5-11e9-8b91-f8f589a64731.png)

For now we've solved it by checking if IDs supplied are arrays of buffers and converting them back to a UUID string with `.toString('hex')` before removing dupes, but that assumes all buffers supplied are hex encoded and likely not an end solution for the project. I've pushed this to my fork [here](https://github.com/rajdeut/objection.js/commit/503477e35dfbbc32e6010fe0b0c302c66a0f403c).

This only seems to happen when there are over a certain number of ids to be used in the `Model.WhereInEagerAlgorithm`. If the model is queried directly that has a null venue it works fine.

**Comment by koskimas** [comment]
Thanks for opening the issue. I'll fix this and release a new patch release soon.

**Comment by koskimas** [comment]
I'm fixing this right now. If everything goes well, you'll have a working release of objection by monday

**Comment by koskimas** [comment]
I just went through the codebase and it seems that making objection support `Buffer`s in id or foreign key columns would be really really difficult. I'd suggest that you just work with strings in the node side. You can convert the binary blobs to strings in `$parseDatabaseJson` and back to binary in `$formatDatabaseJson`. Something like this:

```js
class Person extends Model {
  $parseDatabaseJson(json) {
    json = super.$parseDatabaseJson(json)

    if (json.id) {
      json.id = json.id.toString('hex')
    }

    return json
  }

  $formatDatabaseJson(json) {
    if (json.id) {
      json.id = Buffer.from(json.id.replace(/-/g, ''), 'hex')
    }

    return super.$formatDatabaseJson(json)
  }
}
```
