### ISSUE TITLE
Add ability to add modifiers to "Through" relationships.

### ISSUE THREAD

**Issue by jonathan-playvs** [Vincit/objection.js#1461]
Hi -- First off, thanks for the hard work with this library. My company is using it to implement our entire data access layer, and our needs are (nearly) completely satisfied!

There is one use case which I am surprised I have not been able to find documentation for, which leads me to believe it's missing:

**Scenario**: You have a many-to-many relationship between models, with a linking table in between -- let's say `User` relates to `User` with an m2m relation called `followers` through a linking table called `user_followers`:

```
// User.js
get relationMappings() {
  followers: {
    modelClass: 'User'
    relation: Model.ManyToManyRelation,
    join: {
      from: 'user.id',
      through: {
        from: 'user_followers.user_id'
        to: 'user_followers.follower_id'
      },
      to: 'user.id'
  }
}
```

**Desired behavior**: Now, let's say you want to be able to "soft-delete" a `follower` relationship by setting a timestamp in the `deletedAt` column of the linking table (`user_followers`), which is initially `null`. We would like to be able to add a `modify` clause to the relationship to apply this filter.

**Issue**: There does not seem to be a way to add a `modify` clause to the `followers` relationship such that `followers` are only fetched if the linking row between them has `{ deletedAt: null }`, although this would be possible in SQL. Is this possible to model with Objection?

**Comment by jonathan-playvs** [comment]
The workaround I'm currently using is this:

```
// User.js
get relationMappings() {
  followerLinks: {
    modelClass: 'UserFollowers'
    relation: Model.HasManyRelation,
    join: {
      from: 'user.id',
      modify: 'connected'
      to: 'user_followers.user_id'
  }
}
```

```
// UserFollower.js
get modifiers() {
  return {
    connected(builder) {
      return builder.where({ deletedAt: null })
    }
  }
}
```

```
// follower-services.js
function getUserFollowers(userId)
await userWithFollowers = User
  .query()
  .eager('followerLinks.follower')
 
return userWithFollowers.followerLinks.map(followerLink => followerLink.follower)
```

**Comment by koskimas** [comment]
Hi! This will be added eventually. There' another issue about this #1356.

Right now I'm busy putting v2.0 release together and it will take a while for me to get to this. There's even a pending PR about this, but I haven't had time to look it through yet.

I'll close this as a duplicate. You can follow #1356 for progress.

**Comment by fiznool** [comment]
I've found another way to do this, which takes advantage of the `extra` property on the `join` relation definition. By exposing an `extra` field, we can use this in the modifier.

``` js
// User.js
get relationMappings() {
  followers: {
    modelClass: 'User'
    relation: Model.ManyToManyRelation,
    join: {
      from: 'user.id',
      through: {
        from: 'user_followers.user_id'
        to: 'user_followers.follower_id',
        extra: {
          user_deleted_at: 'deleted_at'
        }
      },
      to: 'user.id'
    },
    modify: (builder) => builder.whereNull('user_deleted_at')
  }
}
```
