### ISSUE TITLE
set default value to table.json

### ISSUE THREAD

**Issue by NajwaSM** [Vincit/objection.js#1463]
hi, 
i was trying to set default value to my table.json. the code is something like this:
    table.json('notification')
      .notNullable
      .defaultTo({
        buySell: true,
        sendReceive: true,
      });

however, i have error that says i cannot set default value to table.json. i already include this line in my model, still, its not working:
  static get jsonAttributes() {
    return ['notification'];
  }

i also added this is my model:
  static get jsonSchema() {
    return {
      type: 'object',
      properties: {
        notification: {
          type: 'boolean',
          default: false,
        },
      },
    };
  }

and i get error message: "error": "insert into `setting` (`notification`, `userId`) values (false, 4) - Invalid JSON text: \"not a JSON text, may need CAST\" at position 0 in value for column 'setting.notification'.",

is there any other way can i add default value to the attributes? 
thank you so much in advace

**Comment by koskimas** [comment]
Wrap the default value in JSON.stringifu.

**Comment by NajwaSM** [comment]
Hi koskimas,
Thank you :)
