### ISSUE TITLE
$afterDelete and parent delete

### ISSUE THREAD

**Issue by Stephane-Peyroutet** [Vincit/objection.js#1464]
I have a Cell table and a Row table with each row containing 0 to many cells.
I also have some properties on my Row table which apply to all cells of that row.
In my application, I mainly deal with cells so I can add, edit or delete cell.
I can also edit or delete a row...which then delete all children cells for that row with a Cascade.

Is there a way to do the opposite and delete the parent (Row) if there is no more children.
I was thinking $afterDelete could do the trick but I'm wondering what's the request for "If there is no more children then delete parent".

Here is the Cell model :

```
class Cell extends Model {
  static get tableName() {
    return "Cell";
  }
  static get relationMappings() {
    return {
      row: {
        relation: Model.BelongsToOneRelation,
        modelClass: "Row",
        join: {
          from: 'Cell.fkRowId',
          to: 'Row.id',
        }
      }   
    }
  }
  async $afterDelete(queryContext) {
    await super.$afterDelete(queryContext);
    await Row
      .query //????????????????
                 // how to test for children presence ?? then delete the row ??
  }
}
```

**Comment by koskimas** [comment]
Here's one way:

```js
await { count: numCiblings } = await Cell.query().count('id as count').where('fkRowId', this.fkRowId)
```
