### ISSUE TITLE
Support for Postgres composite types

### ISSUE THREAD

**Issue by villesau** [Vincit/objection.js#1465]
Often times data structure has nested strictly defined values but Objection does not support that use case very well. Would be quite useful to support composite types in order to guarantee strict schema for nested data. I didn't find any mention about composite types in the documentation.

More details: https://www.postgresql.org/docs/9.6/rowtypes.html

**Comment by koskimas** [comment]
I think you should use relations when you need strict schema in the db and jsonb if you don't. In which case do you want to use composite types instead of separate table and relations?

**Comment by villesau** [comment]
When I have nested data. e.g following object:

```
{
  prop1: 123,
  prop2: {
    nestedProp: 321
  }
}
```

I can have composite type for `prop2` defining the nested data strictly and enforce that on DB level. No need for relations. Relation is just cumbersome compared to composite types. Composite types are exactly a match for this kind of use cases. With relation it's difficult to have proper mapping of nested data: I need id:s and remove policies etc. With composite types there are no need for that.

Why should I use relations instead of builtin solution?

**Comment by koskimas** [comment]
Relations kind of feel like builtin solution for **relational** databases :wink: With cascading, constraints and objection's `insertGraph` they are not that difficult to use. I personally have never needed composite types.

I could maybe add some sort of support if knex and the pg driver already support composite types natively and the support wouldn't require too many changes. I really want to minimize db-specific code in objection. How do knex and pg support composite types?

**Comment by villesau** [comment]
But does relational === nested? :) IMO it's different thing but that might be matter of taste. Composite types are also builtin solution for strict and nested data. I'd say that it's just not widely enough known although it solves nested data problem quite elegantly. 

Knex & pg driver seems supports it: https://github.com/tgriesser/knex/issues/3123

**Comment by koskimas** [comment]
Ok, cool. What kind of things you would like objection to do? What are the biggest pain points at the moment?

**Comment by villesau** [comment]
At this point, as far as I know, there is no way to map nested data to composite types. At least no mention in documentation or issues. Let's take the postgres example:

```
CREATE TYPE inventory_item AS (
    name            text,
    supplier_id     integer,
    price           numeric
);

CREATE TABLE on_hand (
    item      inventory_item,
    count     integer
);

```

Now I'd like to insert following data:

```
{
  count: 123,
  item: {
    name: 'some item',
    supplier_id: 321,
    price: 25
  }
}
```

The resulting sql query would look like: `INSERT INTO on_hand VALUES (ROW('some item', 321, 25), 123);`

And When I `SELECT * FROM on_hand;` it would return the data in similar form as inserted.

The model would roughly look something like this:

```
export default class OnHand extends Model {
  // prettier-ignore
  readonly id!: number;
  count: number;
  // prettier-ignore
  item: {
    name: string,
    supplier_id: number,
    price: number
  };

  static tableName = 'on_hand';

  // Optional JSON schema. This is not the database schema! Nothing is generated
  // based on this. This is only used for validation. Whenever a model instance
  // is created it is checked against this schema. http://json-schema.org/.
  static jsonSchema = {
    type: 'object',
    required: ['item', 'count'],

    properties: {
      id: { type: 'integer' },
      count: { type: 'integer' },
      item: {
        type: 'object',
        required: ['name', 'supplier_id', 'price'],

        properties: {
          name: { type: 'string' },
          supplier_id: { type: 'integer' },
          price: { type: 'integer' }
        }
      }
    }
  };
}
```

and the call could look like this:


```
OnHand.query()
  .insert({
    count: 123,
    item: {
      name: 'some item',
      supplier_id: 321,
      price: 25
    }
  })
  .returning('*')
```

Does this make sense to you?

**Comment by koskimas** [comment]
Ok, so knex *doesn't* have support. If it had, all those things would work.

**Comment by koskimas** [comment]
You should be able to create a mixin (or just a base class) like this

```js
const { raw } = require('objection')

function withCompositeTypes(Model) {
  return class extends Model {
    $formatDatabseJson(json) {
      json = super.$formatDatabseJson(json)

      for (const compositeTypeColumn of this.constructor.compositeTypeColumns || []) {
        if (json[compositeTypeColumn]) {
          const keys = Object.keys(json[compositeTypeColumn])
          const values = Object.values(json[compositeTypeColumn])

          json[compositeTypeColumn] = raw(`ROW(${keys.map(() => '?').join(',')})`, values)
        }
      }

      return json
    }
  }
}
```

and then you can just mix that in with your models when you want to use composite types:

```js
export default class OnHand extends withCompositeTypes(Model) {
  static compositeTypeColumns = ['item'];

  readonly id!: number;
  count: number;

  item: {
    name: string,
    supplier_id: number,
    price: number
  };

  static tableName = 'on_hand';

  // Optional JSON schema. This is not the database schema! Nothing is generated
  // based on this. This is only used for validation. Whenever a model instance
  // is created it is checked against this schema. http://json-schema.org/.
  static jsonSchema = {
    type: 'object',
    required: ['item', 'count'],

    properties: {
      id: { type: 'integer' },
      count: { type: 'integer' },
      item: {
        type: 'object',
        required: ['name', 'supplier_id', 'price'],

        properties: {
          name: { type: 'string' },
          supplier_id: { type: 'integer' },
          price: { type: 'integer' }
        }
      }
    }
  };
}
```

I'm guessing `knex` and `pg` still return those items as objects?
