### ISSUE TITLE
 i use knex with objectionjs but i can't retrieved data  error this "TypeError: Cannot read property 'isPartial' of null" 

### ISSUE THREAD

**Issue by maprangsoft** [Vincit/objection.js#1466]
hello i use knex with objectionjs but i can't retrieved data 
error this "TypeError: Cannot read property 'isPartial' of null"  i make relation in database  completed 
i use mysql database
----------------------------
Model:
Categorie: https://1drv.ms/u/s!An-gKc2bfnTOgYgu0MpqJNbT-nCbgg?e=BoI2S9
Blog: https://1drv.ms/u/s!An-gKc2bfnTOgYgtCw_FvlmwCOSkGg?e=QrmVIz
Controller:
BlogController: https://1drv.ms/u/s!An-gKc2bfnTOgYgvgtEx6uemT4SUbw?e=0IiVoP
thank you advance.

**Comment by koskimas** [comment]
You have this

```js
  await Blog
    //.query()
    .relatedQuery("categorie")
    .then(data => {
      res.send(helper.sendResponse(data, "Blog retrieved successfully."));
    })
    .catch(function(err) {
      res.send(helper.sendError("Blog can't retrieved. " + err));
    });
```

what are you trying to do here? You don't specify a blog id anywhere, so how would objection know for which blog to fetch the `categorie`? Or are you trying to fetch all `Blog` instances and load the `categorie` with them? In that case, you need to use `eager`:

```js
  await Blog
    .query()
    .eager("categorie")
    .then(data => {
      res.send(helper.sendResponse(data, "Blog retrieved successfully."));
    })
    .catch(function(err) {
      res.send(helper.sendError("Blog can't retrieved. " + err));
    });
```

The static `relatedQuery` can only be used for subqueries. The instance method `$relatedQuery` can be used to build queries to a single relation of a **model instance**. You probably need to take a closer look to the documentation. The `guide` section is a good place to start.

**Comment by maprangsoft** [comment]
oh thank you very much this is thing i want. ^___^
