### ISSUE TITLE
Async virtual attributes

### ISSUE THREAD

**Issue by willsoto** [Vincit/objection.js#1468]
Previous discussions: #175 #1252 #866

With Objection v2.0 on the horizon, I wonder if it would be worth re-exploring the possibility of `async` `virtualAttributes`? Does the architecture still prevent `async` `virtualAttributes`?

**Comment by koskimas** [comment]
The architecture makes it difficult and also async operations per model instance are rarely a good idea. With async operations, you usually get big performance benefits by batching them for multiple instances.

**Comment by koskimas** [comment]
You can implement them pretty easily yourself by utilizing the $afterGet hook.

**Comment by jalidchaer** [comment]
is possible to get a relation query and return in virtualAttributes?

**Comment by biggytech** [comment]
`$afterGet` was deprecated and removed from Objection.js, any other options how to do this?
