### ISSUE TITLE
Flatten Nested Eager relationMappings

### ISSUE THREAD

**Issue by rnicholls** [Vincit/objection.js#1469]
I was just wondering if there is a way to "flatten" the results of one of the children in an eager relationMappings.

```
Movie.query()
      .select('id', 'title', 'original_title', 'synopsis', )
      .where('movies.id', req.params.id)
      .eager('credits.actors')
```

My goal is for the JSON response to be:

```
 result: {
  ...
  credits: {
  ...credits and actors data in here...
  }
 }
```

Any help would be greatly appreciated. If it isn't possible I will just have to do some mapping but wanted to double-check.

**Comment by koskimas** [comment]
In case the `credits` is a `HasManyRelation` you can simply say this (assuming the foreign key is `movieId'):

```js
const credits = await Credits
  .query()
  .where('movieId', 'req.params.id')
  .eager('actors')
```

In case of `ManyToManyRelation` it's a bit trickier. With objection 2.0 you will be able to use `relatedQuery` like this

```js
const credits = await Movie
  .relatedQuery('credits')
  .for(req.params.id)
  .eager('actors')
```

But If you need also need the `movie`, I think the easiest way is to just, you know, access the relation :smile:

```js
const movie = await Movie
  .query()
  .select('id', 'title', 'original_title', 'synopsis', )
  .findById(req.params.id)
  .eager('credits.ators')

const credits = movie.credits
```

**Comment by rnicholls** [comment]
Thanks so much for the help. Ended up being a combination of "through" and the above solution that got me what I wanted.
