### ISSUE TITLE
Fetching pivot data from join table

### ISSUE THREAD

**Issue by fl0w** [Vincit/objection.js#147]
I'm not sure if I'm missing something in docs, or if I'm approaching this the wrong way.
I'm trying to get some values from the join table of a ManyToManyRelation while eager loading.

I'd like to request support to fetch pivot data from join table, perhaps like so:
```js
class MyModel extends Model {
  static get relationMappings () {
    return {
      myOtherModels: {
        relation: Model.ManyToManyRelation,
        modelClass: MyOtherModel,
        join: {
          from: 'MyModel.id',
          through: {
            modelClass: MyJoinModel,
            from: 'MyJoinModel.myModelId',
            to: 'MyJoinModel.myOtherModelId',
            // `select` to follow knex naming convention
            // but could be `with`, or `include`
            // bookshelfjs uses `withRelated`
            select: ['column1', 'column2']
          },
          to: 'MyOtherModel.id'
        }
      }
    }
  }
}
```

Not sure if those against objection.js philosophy, in which case; How would I solve this in current (`-rc.5`) codebase? My guess is to use `context` and `onBuild` or `runBefore`, but would appreciate any pointer.

Or perhaps the eager(fn) is to be played with to solve this?

**Comment by koskimas** [comment]
The magic word you are looking for is `extra`:
```js
        join: {
          from: 'MyModel.id',
          through: {
            modelClass: MyJoinModel,
            from: 'MyJoinModel.myModelId',
            to: 'MyJoinModel.myOtherModelId',
            extra: ['column1', 'column2']
          },
          to: 'MyOtherModel.id'
        }
```

This is a new feature in 0.5.0 and the docs are not published yet. You can see the docs in slightly crappier format in  the [docs](https://github.com/Vincit/objection.js/tree/master/doc) folder.

**Comment by fl0w** [comment]
Hah, well, at least I'm thinking in line with how `objection.js` ought to work :) Thanks.
