### ISSUE TITLE
Type of JoinRelation doesn't match the docs

### ISSUE THREAD

**Issue by abdullah-kasim** [Vincit/objection.js#1470]
According to the docs here: https://vincit.github.io/objection.js/api/query-builder/join-methods.html#joinrelation

`.joinRelation()` accepts `relationExpression` as the first argument.

However, in the types `typings/objection/index.d.ts` at line 349:

```ts
  interface JoinRelation {
    <QM extends Model>(relationName: string, opt?: RelationOptions): QueryBuilder<QM, QM[]>;
  }
```

the first parameter shows `relationName` instead of `relationExpression`

From my testing, the doc is correct (I only tested the object notation, however), the typing is wrong.

**Comment by koskimas** [comment]
Yep, that's true. I'll update the type.
