### ISSUE TITLE
Overriding page with modify breaks response structure

### ISSUE THREAD

**Issue by ayZagen** [Vincit/objection.js#1471]
Hello,

Problem is what exactly the title says. Here is a sample code ( Not the actual use case ):
```js

return Model.query()
      .where({ query })
      .page(offset, limit) // Need this for returning type to be `Page<Model>`
      .modify((builder => {
          // override offset and limit
          builder.page(offset + 1, limit + 100);
      }));
```
**Response:**
```js
{ results: { results: [ [Model] ], total: 1 }, total: 1 }
```
**Expected response:**
```js
{ results: [ [Model] ], total: 1 }
```

However if you remove one of `page` modifiers, response structure would be the same.

**Comment by koskimas** [comment]
That's a bug. I'll make `page` throw if called twice.

**Comment by ayZagen** [comment]
Allowing to override it in modify would be better and it seems more appropriate.

**Comment by koskimas** [comment]
You're right. Fixed by allowing override (not just in modify, but always).

**Comment by ayZagen** [comment]
Thanks a lot
