### ISSUE TITLE
Deferred Constraints for Transactions with Foreign Keys

### ISSUE THREAD

**Issue by imwillhang** [Vincit/objection.js#1472]
Thanks for the help. I am wondering what happens when I have a transaction with two actions:

1. I create an entry in a `User` table
2. I create an entry in a join table for the `User` entry, where one of the fields in the join table has a foreign key constraint on `User`

Since we do not commit Step 1 before the whole transaction completes, Step 2 cannot execute because the entry in `User` does not exist yet. 

I know a solution to this issue is to set the foreign key constraint to `DEFERRED`, but this doesn't seem to be documented in Objection. 

Is there any solution to this?

**Comment by koskimas** [comment]
You don't need to commit there are n between. The user is inserted in the transaction.

**Comment by imwillhang** [comment]
Thanks so much!!!
