### ISSUE TITLE
Which fetches data faster? Eager or manual join and grouping?

### ISSUE THREAD

**Issue by cerberusv2px** [Vincit/objection.js#1473]
This is not an issue. Just a question. 
Which method fetches data faster and in optimal way? Defining relationships in model and using eager or manually joining the tables and group the flat data into tree hierarchy?

**Comment by koskimas** [comment]
It completely depends on the query and your schema. As a rule of thumb, if you have multiple 1-m or m2m relations, `eager` is faster. If you only mostly have 1-1 relations, joining is faster. But you really need to measure your **real life code** to know which is faster.

`eager` is a safer default. Using joins or `joinEager` can lead to some extremely slow queries in the worst case. `eager` will always remain rerelatively fast.

I also like to remind people in these cases to ignore the performance until you have a real measured problem, and only then try to optimize it. Premature optimization is the #1 stupid thing all programmers do :smile:

**Comment by cerberusv2px** [comment]
Nicely written. Thank you.
