### ISSUE TITLE
Pick, omit etc. doesn't work if query is a paged query

### ISSUE THREAD

**Issue by ayZagen** [Vincit/objection.js#1476]
Hello,

The methods which are running after fetching query result don't work well with pagination results. I haven't tried them all ( only tried `pluck`, `pick` and `omit`) or inspected the code but I think they would behave in the same way. Here is a sample code:
```js

/**
example Model
Model : {
  field1: string
  field2: string
}
*/
return Model.query()
      .where({ query })
      .page(offset, limit)
      .pick(['field1']) // or pick(Model, ['field1'])
```
**Response:**
```js
{ results: [ { field1: 'someVal', field2: 'someOtherVal' }], total: 1 }
```
**Expected response:**
```js
{ results: [ { field1: 'someVal' } ], total: 1 }
```

Thanks in advance.

**Comment by koskimas** [comment]
You can just move the `page` method to last.
