### ISSUE TITLE
How do you mock?

### ISSUE THREAD

**Issue by DHFW** [Vincit/objection.js#1477]
For unit testing and mocking of database calls I use the following:

```typescript
modelsSpy = jest.spyOn(models.CourseParticipation, 'query');
      modelsSpy.mockReturnValue({
        eager: (): any => {
          return {
            findById: (queryObject: any): Partial<CourseParticipation> => {
              return {
                PersonID: 1,
                SomeOtherKeyID: 1,
                Course: {
                  CourseCode: '1234',
                  SpecialtyID: 123,
                  Title: 'Test course',
                  Sessions: [
                    {
                      Date: new Date(2019, 0, 1), // Local time
                      Begintime: new Date(1970, 0, 1, 13, 0, 0, 0), // Local time
                    },
                  ],
                },
              };
            },
          };
        },
        where: (): any => {
          return {
            patch: (): number => {
              return 1;
            },
          };
        },
      });
``` 

This works pretty well for me (ObjectionJS version: 1.6.8) with Jest 24.
I wonder what your code looks like? We don't have so much help from TypeScript here (using everything as `any` because the models have so many properties and methods), so *any* ;) suggestions are welcome!

**Comment by koskimas** [comment]
You can use the [resolve](https://vincit.github.io/objection.js/api/query-builder/other-methods.html#resolve) method to skip the db query and mock the db result.

**Comment by DHFW** [comment]
@koskimas Thanks for the quick response. However, do you have an example how to implement this in a simple unit test? How do I go about this when I want to spy/mock on just say one findById request?

**Comment by imwillhang** [comment]
Yeah, I'd love to +1 @DHFW's most recent comment. Specifically,

**if I already have calls to** `Model.query().select().join()` in my server code, is there any cleaner way to mock the entire call in some unit test? Or will @DHFW's first post have to suffice?

**Comment by devinivy** [comment]
You can override the model's `query()` method so that it returns a query builder calling `resolve()` with whatever value you like.

**Comment by imwillhang** [comment]
Thanks @devinivy. Does this mean that I either need to go and edit my DB code so that it calls the `resolve()` function? As in, there is no in-place mock? Or, are you suggesting that I can completely mock out `query()` with `resolve()` and everything will be fine?

The reason I'd like to clarify is that `query()` is often the first in a chain of calls. Mocking `query()` to return the result of `resolve()` instead, when there are still chained calls after `query()`, seems like it will break anything chained onto `query()`.

**Comment by devinivy** [comment]
It should work just fine without modifying any application code!  As the docs show, `queryBuilder.resolve()` returns `queryBuilder`, so you can keep chaining :) https://vincit.github.io/objection.js/api/query-builder/other-methods.html#resolve

**Comment by imwillhang** [comment]
Oh damn! Amazing! Thanks so much for pointing that out. This is a huge plus for the community because this just makes server testing so much easier now. Thank you all!

**Comment by aalimovs** [comment]
For anyone stumbling upon this from hapi/hapipal/schwifty land, here's an example for a route handler:

```
// route handler
const { Person } = request.models(true);
const person = await Person.query().findById(request.params.id);
```

```
// test with stub
import { QueryBuilder } from "objection";

const { Person } = server.models(true); // or import Person from "../wherever/models/Person";

Sinon.stub(server.models(true), 'Person').value({
    query: () => QueryBuilder.forClass(Person).resolve({ id: 111 }),
});
```

**Comment by evandeininger** [comment]
Doing what @devinivy said in sinon:
```
sandbox.stub(MyModel, 'query').returns(
  Model.query().resolve(<your-object>),
)
```

**Comment by lucasrcosta** [comment]
I have found that [mock-knex](https://github.com/jbrumwell/mock-knex) offers the most complete experience for mocking and asserting the queries. :orange_circle: :orange_circle:

**Comment by richardweaver** [comment]
@lucasrcosta How are you injecting the mock-knex instance? I can't figure it out.

**Comment by BlairCurrey** [comment]
A self-contained example using jest and typescript that you can copy-paste: https://gist.github.com/BlairCurrey/aa5df18a73269250f49687e95563bd5f

**Comment by carlosLMZarego** [comment]
@BlairCurrey when I try to run that code I get

```
Cannot read properties of undefined (reading 'identity')
```

do you know what could be the problem? thanks!
