### ISSUE TITLE
eagerAlgorithm doesn't work with pathAndFetchById

### ISSUE THREAD

**Issue by burashka** [Vincit/objection.js#1479]
If use eagerAlgorithm with patchAndFetchById:
```
const application = await Application.query()
        .patchAndFetchById(applicationId, {status: value})
        .eagerAlgorithm(Application.JoinEagerAlgorithm)
        .eager('participant')
```
then application doesn't contains eagers properties.

DB: Postgres

**Comment by koskimas** [comment]
Yep, it's not supported to do that. It's just as readable (and only one line more) to split that into two queries. Your code would anyway execute a separate `update` and a `select` query.

```js
await Application.query().findById(applicationId).patch({ status: value })
await Application.query().findById(applicationId).joinEager('participant')
```
