### ISSUE TITLE
`modifyEager` not being called

### ISSUE THREAD

**Issue by Negan1911** [Vincit/objection.js#1484]
Hello, I had been using `modifyEager` to currently alter the default ordering of a column, given this code:

```js
this.query(tx)
  .findById(id)
  .eager('*')
  .modifyEager('timeline', builder => {
    console.log(builder)
    builder.orderBy('timestamp', 'asc')
  })
```

ModifyEager is not going to be called, even when eager was a wildcard (and timeline came with the response).

on other case, if I do:
```js
this.query(tx)
  .findById(id)
  .eager('timeline')
  .modifyEager('timeline', builder => {
    console.log(builder)
    builder.orderBy('timestamp', 'asc')
  })
```

it works, but `modifyEager` should be called if the eager is a wildcard right? also, if i do `.modifyEager('*')` or `.eager('*').mergeEager('timeline')`  is also not called.

Thoughts?

**Comment by koskimas** [comment]
Hi! `*` is buggy in many ways and I'll deprecate it in v2.0. It will be removed in 3.0. I'd suggest you avoid using it. It becomes completely useless as soon as you have a two models that have relations to each other in both directions (causes an infinite query loop)
