### ISSUE TITLE
[Question/Docs] WHERE with parent records

### ISSUE THREAD

**Issue by strarsis** [Vincit/objection.js#1485]
@koskimas, @elhigu:
I want to query all records before a specific date and then get a list of the parents of these records.
The output should be the parents of the records, with the queried records nested inside.

```php
await Model1
        .query()
        .joinRelation('parent')
        .where('model1.created_at', '>=', "'" + someDate.toISOString() + "'"  );
````

Output:
- Parent 1
  - Record
- Parent 2
  - Record
- Parent 3
  - Record
- Parent [...]
  - Record
[...]

Each parent would have only the queried record that they got as child record.

I already tried several approaches, like using joins - which didn't work at all, 
and also iterating over the records and getting their parent via property, 
appending the parents to array and using the array as output, 
but this also doesn't work as the parent property after the query doesn't seem to resolve.

**Comment by koskimas** [comment]
What is a record in your explanation?

**Comment by koskimas** [comment]
If you want a list of parents, then query the parents and not the records. Then you can create a inverse relation of `parent` and eagerly load those. Let's assume the inverse relation of `parent` is `children`

```js
await Parent
  .query()
   .joinEager('children')
    .where('children.created_at', '>=', someDate.toISOString());
```

**Comment by strarsis** [comment]
@koskimas: Yes, this works great, thanks!
Is it also possible to limit the child records to one per parent record?
`.limit()` acts on the child _and_ also the parent records, not only on the joined child records though.
