### ISSUE TITLE
TypeError: properties.reduce is not a function

### ISSUE THREAD

**Issue by rburdet** [Vincit/objection.js#1486]
I'm having this issue when i try to `omit` a property from a query:
```
ProductModel.query()
  .insert({ ...data, deleted: false })
  .omit('deleted')
  .returning('*');
```

But is working with the array version of `omit`
```
ProductModel.query()
  .insert({ ...data, deleted: false })
  .omit(['deleted'])
  .returning('*');
```

I guess it has something to do with [this line](https://github.com/Vincit/objection.js/blob/master/lib/queryBuilder/QueryBuilder.js#L711)

Version: `1.6.9`

**Comment by koskimas** [comment]
Yep, definitely a bug. Thanks for reporting.

I'll fix this soon, but in the meanwhile you can use something like this

```js
ProductModel.query()
  .insert({ ...data, deleted: false })
  .returning(Object.keys(data);
```
