### ISSUE TITLE
Getting properties when a NotFound error is thrown

### ISSUE THREAD

**Issue by nunovieira220** [Vincit/objection.js#1488]
At the moment, using the query builder, we are not able to get any property fields like type and message when a `NotFound` error is thrown. Based on [this](https://vincit.github.io/objection.js/recipes/error-handling.html) that information is supposed to be present.

After some analysis, I found the only method that really uses the `createNotFoundError()` model method is `throwIfNotFound()` and that method does not send any property and just the context.

**Comment by koskimas** [comment]
The link you posted has this
```js
  } else if (err instanceof NotFoundError) {
    res.status(404).send({
      message: err.message,
      type: 'NotFound',
      data: {}
    });
  }
```
where does it say that any fields except `message` should be found?

**Comment by koskimas** [comment]
I think it doesn't contain any fields right now by desing. What kind of fields and information would you like it to have?

**Comment by nunovieira220** [comment]
We'd like to have both the type and message fields information at this point.

**Comment by koskimas** [comment]
What additional information would that offer in addition to doing `instanceof NotFoundError`?

**Comment by nunovieira220** [comment]
We would like to have a generic validator/handler of some of the errors that can be thrown and both the fields would allow us to do that in an easier way.

**Comment by felipap** [comment]
Same here. `throwIfNotFound` has been useful to avoid adding checks for undefined after every query, but, correct me if I'm mistaken, it gives no stack or other hints as to where things went wrong.

**Comment by koskimas** [comment]
@felipap It's a normal error. It gives just as much information as any error. This issue is simply about adding a type field to the error object.

**Comment by johnmaia** [comment]
@koskimas any prediction when we may have the `type` field to the `error` object?

**Comment by koskimas** [comment]
This is the easiest thing in the world to add.

```js
this.type = 'NotFound'
```

a PR would have been nice. I'll fix this now.
