### ISSUE TITLE
How to remove the item using hooks (afterGet json, $formatJson)

### ISSUE THREAD

**Issue by hassan-jahan** [Vincit/objection.js#1490]
Hi,

Imagine a post contains an appropriate word which should be removed. It's possible to remove specific fields using $formatJson but is it possible to remove the entire item from the list?

Something like this:
```
$formatJson(data){
   return false
}
```
Current result:
`[false]`

And this is what I expect:
`[]`

**Comment by koskimas** [comment]
Nope, there's no way to do that in the model itself.
