### ISSUE TITLE
LATERAL JOIN + relation

### ISSUE THREAD

**Issue by strarsis** [Vincit/objection.js#1492]
@koskimas, @elhigu:

Goal: Only fetch the most recent child record (`updated_at`) of each parent, output as a parent/child tree structure.

The database server is Postgres and a `LATERAL JOIN` is used as it seems to be the most intuitive and fastest approach:
```js
let parents = await parent
                      .query()

                      // only the most recent child child
                      .joinRaw(`LEFT JOIN LATERAL (
                        SELECT
                          id,
                          parent_id
                        FROM
                          child
                        ORDER BY
                          child.updated_at ASC
                        LIMIT 1
                      ) AS child ON child.parent_id = parent.id`)

                      .joinRelation('childs');

````

Resulting query:
```sql
select "parent".* from "parent" LEFT JOIN LATERAL (\n' +
    '                        SELECT\n' +
    '                          id,\n' +
    '                          parent_id\n' +
    '                        FROM\n' +
    '                          child\n' +
    '                        ORDER BY\n' +
    '                          child.updated_at ASC\n' +
    '                        LIMIT 1\n' +
    '                      ) AS child ON child.parent_id = parent.id inner join "child" as "childs" on "childs"."parent_id" = "parent"."id"
````

The problem is that when not using `joinRelation` only the parents are listed, without child records. With `joinRelation` the parents are listed multiple times, probably as often as they got child records, so some incorrect JOIN is used.

**Comment by koskimas** [comment]
That's the way joins work. The result structure is not specific to objection.

This particular problem is pretty difficult to implement cleanly. With postgres, you may be able to use `jsonb_agg` to do something like this

```js
const parents = await Parent.query()
  .select(raw(
    'jsonb_agg(?),
    Parent.relatedQuery('chillds').orderBy('updated_at').limit(1)
  ))
```

**Comment by strarsis** [comment]
@koskimas: Thanks! Also awesome that you are using the query builder even for the raw query.
Now only one child record is listed per parent, which is great. 
But how can I have the parent fields for the parent records, currently there is only the child record.

**Comment by koskimas** [comment]
I don't know if you saw the newest version (based on the comment about `raw`), I updated the answer like 20 times 😀. If you also want the parent oe any other relations, you can still use `eager` for that.

**Comment by strarsis** [comment]
@koskimas: Correct, just the extra parent field names had to be added to `select()`.
The `child` record got own child records, let's call them `grandchild` records.
How can I join them? Do the join-related functions accept the field names to be used for the join, so I can use `child.id` as parent ID for the grand child records?
Something like `js .joinRelation('grandchild', 'child.id', 'grandchild.child_id')` ?

**Comment by koskimas** [comment]
`joinRelation` joins relations. You can use the normal `join*` methods to make joins like that. But remember that `joinRelation` and the `join*` methods never nest the objects. They only join them.
