### ISSUE TITLE
how to add new key into existing configuration data

### ISSUE THREAD

**Issue by NajwaSM** [Vincit/objection.js#1494]
i have these configuration file in my code: example:
fees: process.env.PAYPAL_FEES || 3.9,

I created 2 API which is GET and PUT API as i planned to migrate all keys in config DB. However, if there's some additional key in future, how could a non-developer admin going to add in the system without using POST API?

i was going to combine Config Model with Config file, config  || config.db but it seems like not a good approach

**Comment by koskimas** [comment]
I fail to see how this is related to objection. Could you elaborate?
