### ISSUE TITLE
npm release supporting knex 0.11

### ISSUE THREAD

**Issue by johanneslumpe** [Vincit/objection.js#150]
@elhigu Would it be possible to publish a new RC with the updated knex version in it?

**Comment by elhigu** [comment]
@koskimas is doing the releases. It just might be possible 🎱

**Comment by johanneslumpe** [comment]
Awesome 👍

**Comment by koskimas** [comment]
Coming right up.

**Comment by koskimas** [comment]
Released 0.5.0.

**Comment by johanneslumpe** [comment]
Awesome @koskimas thanks a lot! :)
