### ISSUE TITLE
[Meta] Add pre-commit hook to run prettier

### ISSUE THREAD

**Issue by willsoto** [Vincit/objection.js#1503]
[See here for more information](https://prettier.io/docs/en/precommit.html).

Would you be open to adding a pre-commit hook to run prettier over files? I find that as I am working I end up causing unnecessary churn because certain files haven't been formatted.

**Comment by koskimas** [comment]
I'm open to adding a pre-commit hook that checks that prettier has been run **for staged changes**. This way the developer needs to remember to format it, but also allows you to commit only a part of the changes in your local branch.

**Comment by willsoto** [comment]
#1504 would support those requirements. `lint-staged` supports partial adds and knows how to stash files that haven't been staged yet.

**Comment by koskimas** [comment]
Merged in 2.0 branch
