### ISSUE TITLE
Question about default upsertGraph behavior

### ISSUE THREAD

**Issue by k98kumar** [Vincit/objection.js#1507]
When I have an array of values, I just store it as a string on the backend, and I use `JSON.parse()` whenever I get the value back on the frontend.

However, when I use `upsertGraph` to store an array and I forget to convert it to a string, it converts it to a string of an object. For example, if I do:
```
const t = await transaction BasicModel.knex(), trx => {
  return BasicModel
    .query(trx)
    .upsertGraph({
      id: 1,
      arr: ['hello', 'world']
    });
});
```
and then I get that row, one of the fields is:
```
arr: '{"hello", "world"}'
```

Is this the intended behavior? I thought that it should just convert the array to a string instead of converting it to an object then to a string.

If it is the intended behavior, is there a way of replicating the get() and set() methods of Sequelize so I can ensure the proper values are getting stored and don't have to parse the value on the frontend?
Sequelize reference: [https://sequelize-guides.netlify.com/getters-and-setters/](https://sequelize-guides.netlify.com/getters-and-setters/)

**Comment by koskimas** [comment]
Objection doesn't do any kind of mapping by default. That conversion is done by your database client. Which db are you using?

In objection you can make that kind of conversions in `$parseDatabaseJson` and `$formatDatabaseJson` hooks.

```js
class BasicModel extneds Model {
  $parseDatabaseJson(json) {
    json = super.$parseDatabaseJson(json)

    if (json.arr) {
      json.arr = JSON.parse(json.arr)
    }

    return json
  }

  $formatDatabaseJson(json) {
    if (json.arr) {
      json.arr = JSON.stringify(json.arr)
    }

    return super.$formatDatabaseJson(json)
  }
}
```
