### ISSUE TITLE
Option to Omit $formatJson()

### ISSUE THREAD

**Issue by trapcodeio** [Vincit/objection.js#1509]
Good day, 

I am in a situation where i use `$formatJson()` to omit some fields i don't want users to see.
I know there is `$omit()` function but it does not apply to relational query's results.

But now am building an admin section and i need to show all data as it is from the database without  calling `$formatJson`, is there any way to do this?

Or any way to apply `$omit()` to an array of results without looping?

**Comment by koskimas** [comment]
The query builder has an `omit` method that does go through the relations too. There's also the static `Model.traverseAsync` that goes through all model instances recursively.
