### ISSUE TITLE
[Question] Throwing an error if a document cannot be found

### ISSUE THREAD

**Issue by johanneslumpe** [Vincit/objection.js#151]
Back when using bookshelf, there was the nice option to mark a fetch as required so it would throw an error when no results were returned. It looks like objection does not support this out of the box. Is adding a custom `fetchRequired` method to the query builder the way to go here?

**Comment by koskimas** [comment]
I'd add a method like `requireResult()` to the query builder that you can chain to any query:

```js
objection.Model.QueryBuilder = class CustomBuilder extends objection.QueryBuilder {
  requireResult() {
    return this.runAfter(result => {
      if (_.isEmpty(result)) {
        throw new Error('blah');
      } else {
        return result;
      }
    });
  }
}
objection.Model.RelatedQueryBuilder = objection.Model.QueryBuilder;
```

**Comment by johanneslumpe** [comment]
@koskimas Great, thanks for the info, will try this :)

**Comment by Juanpam** [comment]
For anyone ending up here from Google, #874 Is related to this.

You can use query().throwIfNotFound() to throw an error if your query does not have results and you could also chain it to the static method query() so it is chained to all your queries automatically.
