### ISSUE TITLE
Remove result fields by default in all search methods of Model

### ISSUE THREAD

**Issue by edson-nascimento** [Vincit/objection.js#1511]
I have a User Model with fields (id, name, email, password, jwt, createAt, updateAt).
Is there any way to remove the fields (password, jwt, createAt, updateAt) from the result by default in all search methods?

Or only with .select('id','name','email') is possible?

**Comment by koskimas** [comment]
You can implement the `$formatJson` method:

```js
class User extends Model {
  $formatJson(json) {
    json = super.$formatJson(json)
    delete json.password
    delete json.jwt
    delete json.createdAt
    delete json.updatedAt
    return json
  }
}
```
