### ISSUE TITLE
Missing documentation for ref().from()

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#1515]
Hi
using objection 1.6.11

Taking this example from the documentation:
```
await Person
  .query()
  .select('persons.id', 'parent:parent.name as grandParentName')
  .joinRelation('[pets, parent.[pets, parent]]')
  .where('parent:pets.species', 'dog');
```
if i suppose `pets` has also a json column `traits` with property `color` and i want to select pink dogs:
```
await Person
  .query()
  .select('persons.id', 'parent:parent.name as grandParentName')
  .joinRelation('[pets, parent.[pets, parent]]')
  .where('parent:pets.species', 'dog')
  .where(ref('parent:pets.traits:color').castText(), 'pink')
```
but that last line outputs:
`CAST("parent"#>>'{pets,traits:color}' AS text)`

Is a way out of this problem ? (besides raw ?)

**Comment by kapouer** [comment]
[That works](https://github.com/Vincit/objection.js/issues/404#issuecomment-307582863):
`ref('traits:color').from('parent:pets').castText()`

However it's not easy to find because it's not documented in
https://vincit.github.io/objection.js/api/types/#class-referencebuilder

**Comment by koskimas** [comment]
I didn't realize that wasn't documented. Thanks for bringing this up. I'll also document this use case in the json query examples :+1:

**Comment by koskimas** [comment]
Documented in 2.0 branch
