### ISSUE TITLE
Need help: belongsToOne implicit relation 

### ISSUE THREAD

**Issue by cloudever** [Vincit/objection.js#1516]
Hi there!

I have a two models (tables):
`pets(id uuid primary key, name text not null)`
`pets_constaints(id uuid primary key, pet_id uuid not null, eat_time timestamp_tz)`

Table `pets` cannot have a `pets_constraint_id` to make a reference.

How to add a `pets_constraints` as `constraints` relation field to `pet` model without defining a `pets_constraint_id` on `pet` table name? Is it possible for the task using a `belongsToOneRelation` in objection.js and if it is then what `join` expression should I use?

Thanks a lot!

**Comment by koskimas** [comment]
Use `HasOneRelation` instead.
