### ISSUE TITLE
alias in joinRelation when m-m relation with same table seems to rename related table

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#1517]
Hi,

my model is a Block table in m-m relation with itself.
When doing
```
Block.query().alias('site').where('site.id', 1).joinRelation('children')
```
i get
`inner join (select * from "block" as "site")`
which is clearly not what i expected.

I don't think [the tests check that case](https://github.com/Vincit/objection.js/blob/665c75b67605c512139b05358978d15d855f3e3d/tests/integration/viewsAndAliases.js#L197).

**Comment by koskimas** [comment]
I really don't believe this is what happens. I'll need a reproduction for this one.

**Comment by kapouer** [comment]
Right, i can't reproduce in integration tests. Bug is on my side !
