### ISSUE TITLE
from(query) when query is missing 'as()' just writes wrong sql

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#1518]
This is a feature request.

I find myself often spending hours trying to figure how to make
```
Model.query().select(rawstr).from(Model.query().where(obj))
```
work.
It's very simple:
```
Model.query().select(rawstr).from(Model.query().where(obj).as('sub'))
```
However objection outputs the wrong sql and when debugging, it looks like a bug in objection.
I think it would be nice to users if a missing `as()` could be detected and a warning printed.

**Comment by koskimas** [comment]
Open this bug in knex.
