### ISSUE TITLE
joinRelation can have filters, too

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#1520]
I believe the documentation could advertise that `joinRelation` also allows filters:
```
Model1.query().joinRelation({
  model1Relation3: {
    $modify: [(builder) => {
      builder.where('model2.someCol', 'someVal');
    }]
  }
})
```
which is not a superb example of how it's super cool to be able to do that ;)

**Comment by koskimas** [comment]
Yep, this will be advertised in 2.0 docs. 2.0 is just around the corner. Actually in 2.0 you can also do this

```js
Model1
  .query()
  .joinRelation('model1Relation1(someModifier)')
  .modifiers({
    someModifier(builder)  {
      builder.where('model2.someCol', 'someVal');
    }
  })
```
