### ISSUE TITLE
Postgres Returning Method Issue

### ISSUE THREAD

**Issue by abramjstamper** [Vincit/objection.js#1522]
The code below is considered invalid in Typescript because the `returning` function is only expecting 1 argument. However, if I convert it to an array as the tooltip suggests in VS Code, it ignores this statement and returns everything. The specific error is `Expected 1 arguments, but got 9.ts(2554)`. [Knex's documentation](http://knexjs.org/#Builder-returning) specifies that it accepts an array or N parameters of columns to return. Honestly, I'm not very familiar with Typescript, but it seems like the type needs to be updated to accept N number of arguments of type string.

```js
  const user = await User
    .query()
    .patchAndFetchById(1, { password: 'new-password' })
    .throwIfNotFound()
    .returning(
      'id',
      'first_name',
      'last_name',
      'email'
    );
```

Tested with:
- PG: 7.12.1
- Knex: 0.19.5
- Objection: 1.6.11
- Database: PostgreSQL 10
- OS: Ubuntu 18.04

**Comment by koskimas** [comment]
This is fixed in 2.0 (will be relased soon). In the meantime you can use an array:

```js
  const user = await User
    .query()
    .patchAndFetchById(1, { password: 'new-password' })
    .throwIfNotFound()
    .returning([
      'id',
      'first_name',
      'last_name',
      'email'
    ]);
```

**Comment by koskimas** [comment]
By the way, no need for `returning` if you use `patchAndFetch`. It will fetch the whole row using a separate `select` statement anyway.

**Comment by abramjstamper** [comment]
Is there a better way to only select specific columns without using returning? I'm trying to avoid returning the password hash back to the user in the API response. During a refactor, before I stumbled upon this, I was doing a `delete user.password` before returning.

**Comment by koskimas** [comment]
I usually implement either `$formatDatabaseJson` or `$formatJson` method of the model. The first one is called when a model instance is created from the database result, and the second one is called when the model instance is serialized (for example when you call `res.send(user)` or similar). You can delete the password there.

```js
class User extends Model {
  $formatJson(json) {
    json = super.$formatJson(json)
    delete json.password
    return json
  }
}
```
