### ISSUE TITLE
ID field disappears when using eager

### ISSUE THREAD

**Issue by Bastiaan225** [Vincit/objection.js#1523]
`Model.query().select("actions.*")`

returns correctly :

`[{
       id: 1
       name: "test"
},
{
       id: 2
       name: "test 2"
}]`

But when I use eager:

`Model.query().select('actions.*').eager('actionMembers')`

I get:

`[{
    name: 'test',
    actionMembers: [{
        id: 1,
        related_data: 'abc'
    }]
},
{
    name: 'test 2',
    actionMembers: [{
        id: 2,
        related_data: 'xyz'
    }]
}]`

In this example, field id_pet is present in both main table and relation table, and when using eagers it disappears from main table's result.

When  I chain `debug()` to the query I get this:

```js
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'c8c238ea-31d0-4a06-87d3-dacdf05f714e',
  sql:
   'select `actions`.*, `actions`.`action_id`, `actions`.`action_id` from `actions`' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings:
   [ 1,
     2,
     3,
     5, ],
  __knexQueryUid: '51da9d6b-fbe2-4752-8c06-ad7a5f5b652f',
  sql:
   'select `action_members`.* from `action_members` where `action_members`.`action_id` in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' }
```

**Comment by koskimas** [comment]
You still get the `id`. The `actions.*` selection still gets you the id. I have no idea why `action_id` is there twice, but without knowing what you are actually doing, there's no way for me to help you. I'll fix any bug you can prove by providing a reproduction.

**Comment by Bastiaan225** [comment]
When I do `.select("actions.*")` and use eager the id column won't show up in the result.
