### ISSUE TITLE
Bug? Binding a model to a transaction

### ISSUE THREAD

**Issue by Boosmith** [Vincit/objection.js#1524]
Hi
In the documentation https://vincit.github.io/objection.js/guide/transactions.html#using-a-transaction, it suggests that the following pattern can be used for binding models to transactions. 

```
const { transaction } = require('objection');

try {
  const scrappy = await transaction(Person, Animal, async (Person, Animal) => {
    // Person and Animal inside this function are bound to a newly
    // created transaction. The Person and Animal outside this function
    // are not! Even if you do `require('./models/Person')` inside this
    // function and start a query using the required `Person` it will
    // NOT take part in the transaction. Only the actual objects passed
    // to this function are bound to the transaction.

    await Person
      .query()
      .insert({firstName: 'Jennifer', lastName: 'Lawrence'});

    return Animal
      .query()
      .insert({name: 'Scrappy'});
  });
} catch (err) {
  console.log('Something went wrong. Neither Jennifer nor Scrappy were inserted');
}

```

However, adding models as parameters before the callback which then passes copies of those models doesn't seem to work. It does seem to clash with the 'standard' approach of 
```
const { transaction } = require('objection');
// You can access `knex` instance anywhere you want.
// One way is to get it through any model.
const knex = Person.knex();

try {
  const scrappy = await transaction(knex, async (trx) => {
(...)
```

I am quite new to the Objection world, so I wondered if I am misunderstanding something.

**Comment by koskimas** [comment]
It works. `trx` is always the last argument passed to the callback.

**Comment by koskimas** [comment]
If you think this is a bug you found, it must mean that literally nobody is using this library since you are the first one to find it. In that case you shouldn't be using the library either. The other option is that it isn't a bug. Objection has 4000 tests.

**Comment by Boosmith** [comment]
As I said, I am quite new to objection. I am not sure what you mean about "library"? This is code directly from the Objection documentation and I am using the Objection library.
I have found that the below works

```
    const knex = Booking.knex();
    if (has(Booking, 'jsonSchema.properties.user_id')) {
      req.body.user_id = req.user.schema_user_id;
    }
    const bookingResults = await transaction(knex, async trx => {
```
but the below doesn't. According the documentation they are synonymous.
```
const bookingResults = await transaction(Booking, async BoundBooking => {
```

**Comment by koskimas** [comment]
😄 Both of those eork, but they are in no way synonymous. Please read the docs a little better.
