### ISSUE TITLE
Disabling update/insert/delete for relation

### ISSUE THREAD

**Issue by Chaalie** [Vincit/objection.js#1526]
Is there any way to disable an update, insert or delete action for certain relation?

Let's consider a following scenario. We have three tables: 
-  `Users` - user data that only user himself can change
- `Movies` - movies data that only admin can change
- `WatchedMovies` - mapping table between users and movies
As we can see here we have a Many-to-Many relation between `Users` and `Movies`. If we implement it using objection relation then there's is a chance that by using `Users.upsertGraph` some `Movies` data will be changed (by using `WatchedMovies` relation) and that's a big vulnerability if we `Movies` should be immutable for the users.

Of course there's at least three ways to fix it:
1. Leverage `noUpdate`, `noInsert` and `noDelete` options of `upsertGraph`
2. Use `update` or `patch` instead of `upsertGraph`
3. Don't use objection relations for cases where relation should be somehow read-only.

Approach 1 is reasonable but it gets quite complicated if there are multiple relations in the model as then in every `upsertGraph` call we need to consider such read-only relations.
Approaches 2 and 3 are also somewhat reasonable, but they are limiting the usage of relations feature, which is quite a loss.

So, would it be possible to introduce such noUpdate, noInsert or noDelete relations? Or is there any other way to solve the scenario that I presented using objection?

**Comment by koskimas** [comment]
There's the `allowUpsert` method.

**Comment by Chaalie** [comment]
I don't think you understood what I was asking about. Your solution is just my first approach just instead of defining which relations shouldn't be affected by upsert you are defining which ones should be affected. It's still solution on query defining level, what isn't the best thing if model has plenty of relations.

I was asking if there are plans to support defining such allows or disallows of upsert in relation definition e.g as a part of RelationMapping type.

**Comment by Chaalie** [comment]
> There's the `allowUpsert` method.

I don't think you understood what I was asking about. Your solution is just my first approach just instead of defining which relations shouldn't be affected by upsert you are defining which ones should be affected. It's still solution on query defining level, what isn't the best thing if model has plenty of relations.

I was asking if there are plans to support defining such allows or disallows of upsert in relation definition e.g as a part of RelationMapping type.

**Comment by koskimas** [comment]
No
