### ISSUE TITLE
All eager will converted into naiveEager when use mergeNaiveEager

### ISSUE THREAD

**Issue by hyhilman** [Vincit/objection.js#1528]
Hi, is it possible to make only one relation that doing `naive eager` loading?

In my case I would use something like this
```
Job.query().
      .eager('[ \
        users(active) \
      ]')
      .mergeNaiveEager(mailing_lists(sortLatestVisit)')
      .modifyEager('mailing_lists(sortLatestVisit)', builder => builder.limit(100))
```
When I run the debug mode in that query, All of the eager relation is querying just like the `naiveEager`. I just want to make only one relation to querying like that. because the data is pretty big, and my server sometimes crash because of out of memory. I just read the docs and didn't found anything to help me. Thank you!

**Comment by koskimas** [comment]
Unfortunately you cannot mix eager types. This API will be cleaner in 2.0.
