### ISSUE TITLE
New knex version

### ISSUE THREAD

**Issue by Biktop** [Vincit/objection.js#153]
New version of knex was released (0.11.7) where was fixed Bluebird warnings (Fix code that triggered Bluebird warnings. #1460, #1489). Now Objection.js has peer dependencies ("knex": ">= 0.8.0 <= 0.11.5"). Could you bump Objection.js to new the version of knex please?

**Comment by fl0w** [comment]
With proper referencing: tgriesser/knex#1460, tgriesser/knex#1489

**Comment by koskimas** [comment]
I'll release 0.5.1 soon with the latest knex. This will be a continuing issue because of the peerdep. The peerdep was added because some minor knex updates broke objection and I wanted to quarantee compatibility. I don't know which is the lesser evil?

**Comment by Biktop** [comment]
I think that using peerdep can be a good decision. Any way if user ignored a warning it would be his responsibility.

**Comment by fl0w** [comment]
I think peerDependencies serve a real purpose, it's only a pain because knex still is at `< v1`. If knex was `1+`, a peerDependency of `^1.0` would've been sufficient (as long as knex doesn't break on minor and patch releases).
