### ISSUE TITLE
Unclear usage of modify()

### ISSUE THREAD

**Issue by yanickrochon** [Vincit/objection.js#1535]
From the [docs](http://knexjs.org/#Builder-modify) :

```js
var withUserName = function(queryBuilder, foreignKey) {
  queryBuilder.leftJoin('users', foreignKey, 'users.id').select('users.user_name');
};
knex.table('articles').select('title', 'body').modify(withUserName, 'articles_user.id').then(function(article) {
  console.log(article.user_name);
});
```

However, this does not work :

```js
class User extends Model {
   static get tableName() {
      return 'usr_info';
   }

   static get modifiers() {
      return {
         withCredentials(builder, login, pass) {
            console.log( "****", builder, login, pass);
            builder.where( knex.raw('login = :login AND password = MD5(:pass)', { login, pass }) );
         },
         onlyActive(builder) {
            builder.where('actif', 1);
         },
      }
   }
}

const login = 'john.smith';
const pass = 'secret';

User.query().modify('withCredentials', login, pass).then(users => console.log(users));
// **** undefined undefined
// ERROR: ModifierNotFoundError: Unable to determine modify function from provided value: "john.smith".
```

## Expected result
The modifier method `withCredentials` is called with the two arguments provided.

## Actual result
The modifier `withCredentials` is called with no argument, and a second modifier `"john.smith"` is attempted to be called. (And I can presume that a third modifier `"secret"` would also be called with no argument.

**Comment by koskimas** [comment]
The parameters only work when you provide a function, unfortunately. This will be fixed in 2.0. Fixing this is a breaking change and cannot be done before 2.0.

In the meanwhile, you can do this

```js
User.query().modify(user.modifiers.withCredentials, login, pass).then(users => console.log(users));
```

**Comment by koskimas** [comment]
Actually this is already fixed in the 2.0 branch. I'll close this once 2.0 is released.

**Comment by yanickrochon** [comment]
Alright, thanks.

**Comment by koskimas** [comment]
Closing already. 2.0 will be released in couple of weeks.
