### ISSUE TITLE
This comment is not correct

### ISSUE THREAD

**Issue by johncmunson** [Vincit/objection.js#1546]
https://github.com/Vincit/objection.js/blob/12268cdbec2c67e598717c1a9fcaaf71a7abb57c/examples/express-es7/src/models/Person.js#L39

**Comment by koskimas** [comment]
k

**Comment by koskimas** [comment]
Fixed in 2.0 branch.

**Comment by johncmunson** [comment]
There are still places in 2.0 where it is not correct

https://github.com/Vincit/objection.js/blob/5c88c9b6690916d548f9bdd389b1896d40443520/examples/koa/models/Movie.js#L36
