### ISSUE TITLE
[Question] $relatedQuery returning array

### ISSUE THREAD

**Issue by johanneslumpe** [Vincit/objection.js#155]
I just want to make sure that this is expected behavior: not matter what the relation type is, $relatedQuery always returns an array. Even for `BelongsToOneRelation`. Is there any way around this or do I have to explicitly call `first()`?

**Comment by koskimas** [comment]
This is expected, but stupid 😀 I haven't fixed  this because it would probably break alot of code. I'm willing to change this behaviour in 0.6.0 if this gets votes.

**Comment by johanneslumpe** [comment]
@koskimas Are 3 votes enough? :D I I could look into this if you need help btw.

**Comment by koskimas** [comment]
Thanks for the offer @johanneslumpe, but the change itself is trivial. The users' code is the one that will break. I suppose 3 votes is enough. This has bugged me a long time also. Even though semver says that anything can break at any time before 1.0, I only break stuff between minor versions so this will need to wait for 0.6.0. I can release an 0.6.0 alpha-version that can be used until that.

**Comment by johanneslumpe** [comment]
@koskimas Ok cool! I didn't mean to push in any way, was just curious :)

**Comment by koskimas** [comment]
This didn't make it into 0.6. There was already a couple of breaking changes and I didn't want to make migration from older versions a major PITA. This will be fixed in 0.7.

**Comment by fl0w** [comment]
offtopic

There's quite a few enhancement labels (which I assume are - not necessarily accepted - feature requests). Might I suggest creating a 0.7 milestone to easier communicate what the near future looks like?

**Comment by koskimas** [comment]
@fl0w Good idea. I'll do that.

**Comment by koskimas** [comment]
Fixed in 0.7.0-rc.1.

**Comment by jgozal** [comment]
was this fix ported to newer versions? I have the same issue for 3.1.3 :-(

**Comment by lehni** [comment]
Happy to accept a PR fixing the typings, @jgozal
