### ISSUE TITLE
Inconsistent model behavior between .insert() and .findById()

### ISSUE THREAD

**Issue by johncmunson** [Vincit/objection.js#1550]
Given the following two routes for creating and fetching a fairly simple todo list item, where `due_date` is an optional property...

```js
router.post('/', async (req, res) => {
  const todo = await req.context.models.Todo
    .query()
    .insert(req.body)
  res.status(200).json(todo)
})

router.get('/:id', async (req, res) => {
  const { id } = req.params
  const todo = await req.context.models.Todo
    .query()
    .findById(id)
    .throwIfNotFound()
  return res.status(200).json(todo)
})

class Todo extends Base {

  static get tableName() {
    return 'todo'
  }

  static get jsonSchema () {
    return {
      type: 'object',
      required: [ 'title', 'complete', 'priority' ],
      properties: {
        title: { type: 'string' },
        complete: { type: 'boolean' },
        note: { type: 'string' },
        due_date: { type: 'string' },
        priority: { type: 'string' },
        category_id: { type: 'integer' }
      }
    }
  }

  static get relationMappings() {
    return {
      category: {
        relation: Model.BelongsToOneRelation,
        modelClass: `${__dirname}/category`,
        join: {
          from: 'todo.category_id',
          to: 'category.id'
        }
      }
    }
  }

}
```

<img width="423" alt="Screen Shot 2019-11-06 at 8 52 20 AM" src="https://user-images.githubusercontent.com/19480078/68309303-d4d21c00-0073-11ea-938d-a9b1f9e5b390.png">

<img width="425" alt="Screen Shot 2019-11-06 at 8 53 06 AM" src="https://user-images.githubusercontent.com/19480078/68309323-dc91c080-0073-11ea-9e86-9a7caea1cb49.png">

Why does the POST return with `due_date` as undefined / not included, but the subsequent GET returns with `due_date` set to null? To me, the GET is exhibiting correct behavior, but I'm after consistency more than anything.

**Comment by johncmunson** [comment]
In addition, there are a few more discrepancies...

1. `complete` is defined in the jsonSchema as a boolean, and is submitted as such in the POST. Yet, the GET returns it as 0, it's SQLite representation. What is the recommended strategy for keeping the datatypes in sync with the jsonSchema?
2. The timestamps do not get returned in the response body of the POST, similar to how `due_date` is not getting returned. How to amend this?

**Comment by koskimas** [comment]
Because that's how SQL inserts work. You get at most the inserted id back by default. On postgres you get nothing back by default. Objection always gets the identifier, but the rest of the properties come from the input in case of insert. You can use `insertAndFetch` or if you use postgres, you can chain `returning('*')` which is better since you don't get a second query.

**Comment by johncmunson** [comment]
Okay, awesome, thank you. On a sidenote, amazing work with everything you've done with this library. Such a breath of fresh air after trying to work with the bloated mess that is Sequelize.

**Comment by koskimas** [comment]
Thank you :bowing_man: :beers:
