### ISSUE TITLE
Modifying a single row: .findById(id) vs .where('id', id)

### ISSUE THREAD

**Issue by johncmunson** [Vincit/objection.js#1553]
I've noticed in the documentation that there are two different methods shown for modifying a single row. For example, compare these examples that are given for `patch()` and `update()`...
```js
const numberOfAffectedRows = await Person
  .query()
  .patch({ age: 24 })
  .findById(personId)
```
```js
const numberOfAffectedRows = await Person
  .query()
  .update({firstName: 'Jennifer', lastName: 'Lawrence', age: 24})
  .where('id', 134)
```
I'm curious if there is any significant difference between the two, and if one way is generally recommended over the other. Thanks!

**Comment by koskimas** [comment]
No difference, except that `findById` also works with composite keys.

**Comment by koskimas** [comment]
`findById` also prefixes the column reference with the table name to prevent clashes, and respects the `Model.idColumn`. So the direct equivalent in case of non-composite id is
```js
where(`${Person.tableName}.${Person.idColumn}`, id)
