### ISSUE TITLE
Please provide better documentation on certain query results.

### ISSUE THREAD

**Issue by jamespedid** [Vincit/objection.js#1555]
Hello, I'm having trouble determining what is coming back from queries due to lack of documentation. Many sections of the documentation have console.logs that sort of suggest what might come back, but it's difficult to assess what really comes back in many situations.

Examples of what can be improved:

For eager loading, describe what comes back from an eager result when you have a many-to-many relationship. Is the through model included or not? Is it consistently provided through the same property? Do I have to define a "BelongsToRelation" on the model to access the join table?

When you use a method like joinRelation, it is not clear how the joined relation records are brought back. Is this the same as eager? If so, why the difference? If not, what are the differences? Are the values brought back on the parent record, or are they brought back on individual records that are processed by some grouping mechanism.

Also, if there is a set of assumptions that should be made when reading the documentation, can these assumptions be listed somewhere?

**Comment by koskimas** [comment]
PR's are welcome.
