### ISSUE TITLE
Eager Query Hanging

### ISSUE THREAD

**Issue by parker789** [Vincit/objection.js#1558]
So, I'm not sure what is happening. I've been using Objection.js successfully for quite some time, and I just altered a column within my DB and now a specific query is hanging.

I'll try and simplify the example below:

I have a `Page` table, an `Image` table, and an `ImageLocation` table, as well as a `vw_Images` view.

Within the `Page` model, I have a relation defined as so:

```
    image: {
      relation: BaseModel.BelongsToOneRelation,
      modelClass: vw_Images,
      join: {
        from: "Page.ImageID",
        to: "vw_Images.ImageID"
      }
    }
```

The `vw_Images` view builds itself by joining on `Image` / `ImageLocation`, as well as some other weird quirks. I altered a column within `ImageLocation`, and now my query will not succeed if I include the `.eager("image")`.  The SQL which is generated is below:

```
bindings: [ 10 ],
select [vw_Images].* from [vw_Images] where [vw_Images].[ImageID] in (?)
```

But if I manually run this query, I get a result. Any thoughts?

**Comment by koskimas** [comment]
No ideas. This can't really be caused by objection. I'd try to run the query using knex and the db driver to see if it still happens and open an issue in their github. Feel free to reopen this if this only happens with objection.

**Comment by parker789** [comment]
That's what I thought.. no worries, I'll figure it out.
