### ISSUE TITLE
Can #ref appear with extra properties?

### ISSUE THREAD

**Issue by nurkkala** [Vincit/objection.js#156]
Objection is wonderful -- thanks so much!

One quick question: when using `#ref` with `insertWithRelated`, can the object enclosing the `#ref` have  `extra` properties (to be inserted into a `through` table)?

**Comment by elhigu** [comment]
Do you mean like in example from documents:

```js
Person
  .query()
  .insertWithRelated([{
    firstName: 'Jennifer',
    lastName: 'Lawrence',

    movies: [{
      "#id": 'Silver Linings Playbook'
      name: 'Silver Linings Playbook',
      duration: 122
    }]
  }, {
    firstName: 'Bradley',
    lastName: 'Cooper',

    movies: [{
      "#ref": 'Silver Linings Playbook'
    }]
  }]);
```

But with having for example:

```js
    movies: [{
      "#ref": 'Silver Linings Playbook',
      "count": 5
    }]
```

where count would be written in join table?

I have no idea if that works, @koskimas should have better idea of it. Sounds interesting idea 👍

**Comment by koskimas** [comment]
I don't know 😁 Have you tried it? Sounds like something that should work.

**Comment by fl0w** [comment]
Wasn't this added when the addition of `extra` was added to relationMappings?
