### ISSUE TITLE
Suggestion: Distant/nested relationship mappings

### ISSUE THREAD

**Issue by jarommadsen** [Vincit/objection.js#1563]
I have an `assignment` model that relates to an `employee` through a `employee_assignment` relationship table that then relates to a `user`.

To relate the employee is straightforward:

```js
static get relationMappings() {
    return {
      employee: {
        relation: Model.HasOneThroughRelation,
        modelClass: models.Employee,
        join: {
          from: 'assignment.id',
          through: {
            modelClass: models.EmployeeAssignment,
            from: 'employee_assignment.assignment_id',
            to: 'employee_assignment.employee_id'
          },
          to: 'employee.id'
        }
      },
    }
}
```

This is adequate for getting by and I can get the user from `assignment.employee.user` but it's still actually a one to one inbetween the `assignment` and the `user`. I want the relationship to still reside on the `employee` so that if the `employee` is terminated the `assignment` is automatically deleted as well but most of the information I want is on the user such as name, email, etc.
What I would really like to do is have a relation map to the user using something like this:

```js
static get relationMappings() {
    return {
      user: {
        relation: Model.HasOneThroughRelation,
        modelClass: models.User,
        join: {
          from: 'assignee.id',
          through: {
            modelClass: models.Employee,
            from: 'employee.id',
            through: {
              modelClass: models.EmployeeAssignment,
              from: 'employee_assignment.assignee_id',
              to: 'employee_assignment.employee_id'
            },
            to: 'employee.user_id'
          },
          to: 'user.id'
        }
      },
    }
}
```

I've had quite a few situations where this would be very convenient to have stored on the model rather than in a helper function.

I'd love to know if there is some kind of workaround to set this up in objection but virtualAttributes are synchronous functions and modifiers would only allow me to add onto `employee`. Although... now that I think of it, I might be able to do a join that replaces the employee fields with user fields and then rename that to the user... Edit: That _kind_ of works but for whatever reason the `id` field is parsed out ~and I lose all the virtualAttributes on the user model like `fullName`~. Edit 2: Using the `castTo` method fixed the virtualAttributes but I'm still strangely missing the user's id... Edit 3: `select('employee.id', 'user.*')` works but `select('user.*')` and `select('user.id', 'user.*')` does not? Bit confusing but this will do the job.

Anyway, just thought that if you could go down one level with a relationThrough, I was curious if it was feasible to make that logic recursive.

Let me know what you think, thanks for all you do!

**Comment by koskimas** [comment]
This is a good idea which has been requested before, but it would be really difficult to implement. It would complicate the codebase a lot and I don't think this would be useful for that many people. You can always achieve the same thing using multiple relations.

**Comment by jarommadsen** [comment]
Fair enough. I thought I'd seen someone else suggest it before too but I had trouble searching for it. Thanks for considering it :)

**Comment by hadrienReuze** [comment]
> This is a good idea which has been requested before, but it would be really difficult to implement. It would complicate the codebase a lot and I don't think this would be useful for that many people. You can always achieve the same thing using multiple relations.

What do you mean by "multiple relations" ? Do you have an example ?
