### ISSUE TITLE
Run function before or after model has been deleted

### ISSUE THREAD

**Issue by AbdusamadTurdiev** [Vincit/objection.js#1566]
I have `File` model with `fullPath` property. I'm running this function everywhere where I'm deleting file
```
const file = await File.query().findById(params.fileId)
const document = await ClientDocument.query().findById(params.id)

await document
  .$relatedQuery('files')
  .unrelate()
  .where('file.id', file.id)

fs.unlink(file.fullPath, async error => {
  if (error) {
    return sendErrorMessage(res, error)
  } else {
    await File.query().deleteById(file.id)
    return res.status(200).end()
  }
})
```

how can I use `$beforeDelete` method to access current deleting file's `fullPath` and call
```
fs.unlink(file.fullPath, async error => {
  if (error) {
    return sendErrorMessage(res, error)
  } else {
    await File.query().deleteById(file.id)
    return res.status(200).end()
  }
})
```

**Comment by koskimas** [comment]
`unrelate` doesn't delete and thus doesn't call the delete hooks. The hooks are instance methods so you can simply use `this` to access the properties.

**Comment by AbdusamadTurdiev** [comment]
> `unrelate` doesn't delete and thus doesn't call the delete hooks. The hooks are instance methods so you can simply use `this` to access the properties.

I have `manyToMany` relation between `Document` and `File` models. What would be the best way to remove files from database and storage after document or documents have been deleted
