### ISSUE TITLE
BUG - inserting when a model has relation mappings yields a select

### ISSUE THREAD

**Issue by Ryanauger95** [Vincit/objection.js#1571]
This is really crazy behavior. Below I have a BaseModel which I add some functionality to so that I can use it in my other models. Mainly, I created my own upsert function because upsertGraph wasn't working:
```
class BaseModel extends Model {
  static get transaction() {
    return transaction;
  }
  static async upsert(graph: any) {
    const sqlInsert = this.query()
      .insert(graph)
      .toString();
    console.log("Graph: ", graph);
    console.log("Insert String: ", sqlInsert);
    const sqlUpdate = this.query()
      .update(graph)
      .toString()
      .replace(/^update(.*?)set\s/gi, "");
    console.log("Update String: ", sqlUpdate);
    const sql = `${sqlInsert} ON DUPLICATE KEY UPDATE ${sqlUpdate}`;
    return await this.raw(sql);
  }
}
```
This works amazingly actually, it's great:
```
Graph:  { id: '4f42ea191855bd2f', location_id: 2339, app_version_id: 1 }
Insert String:  insert into `device` (`app_version_id`, `id`, `location_id`) values (1, '4f42ea191855bd2f', 2339)
Update String:  `id` = '4f42ea191855bd2f', `location_id` = 2339, `app_version_id` = 1
```

But in my Device Model, which extends this class, I add a relationship mapping so that I can start joining tables, and **my insert turns into a select!**
```
class DeviceModel extends BaseModel {
  // Table name is the only required property.
  static get tableName(): string {
    return "device";
  }

  static get relationMappings() {
    return {
      app_version_id: {
        relation: BaseModel.BelongsToOneRelation,
        modelClass: AppVersionModel,
        join: {
          from: DeviceModel.tableName + ".app_version_id",
          to: AppVersionModel.tableName + ".id"
        }
      }
    };
  }
}
```

```
Graph:  { id: '4f42ea191855bd2f', location_id: 2339, app_version_id: 1 }
Insert String:  **select `device`.* from `device`**
Update String:  `id` = '4f42ea191855bd2f', `location_id` = 2339
```

This is really crazy. It seems like a bug to me.

**Comment by Ryanauger95** [comment]
A solution to this is to use knex() straight up instead of Objection for the upsert query

**Comment by koskimas** [comment]
It's super dangerous to execute the result of `toString`! This is clearly stated in the documentation! Do not do it!

I have no idea why the query would change to select. Could you provide a reproduction?

**Comment by Ryanauger95** [comment]
What else do you need for a reproduction?

**Comment by koskimas** [comment]
Well, a reproduction :smile: A piece of code I can run that reproduces the bug.

**Comment by koskimas** [comment]
This could be related to the fact that you have a relation with the same name as the foreign key. That should throw with a recent objection version. Which version are you using?

**Comment by koskimas** [comment]
I think `toString()` should return an error string in that case, and not a select query. But the error is caused by the relation name. That combined with the fact that you are misusing `toString()` I'd say this is a user error.

**Comment by koskimas** [comment]
Oh, I forgot to mention that `toString` and `toSql` will be removed in 2.0. They will be replaced by toKnexQuery() for which you can call toSQL.

**Comment by Ryanauger95** [comment]
@koskimas 
`This could be related to the fact that you have a relation with the same name as the foreign key. That should throw with a recent objection version. Which version are you using?`

- This was my mistake, I must have copied an earlier version of that code. I was getting an error and had to change it.
