### ISSUE TITLE
typings/objection - Incorrect type inference when using model instance query builder 

### ISSUE THREAD

**Issue by royshouvik** [Vincit/objection.js#1572]
```
const created = await Person
  .fromJson({ firstName: 'Jennifer' })
  .$query()
  .insert();
```
The type of `created` is incorrectly inferred as `Person[]` whereas it should be `Person`.

Type inference works nicely if we insert using static query builder

```
const created = await Person.query().insert({ firstName: 'Jennifer' });
```
Here, `created` is correctly inferred as `Person`.

**Comment by royshouvik** [comment]
`index.d.ts`
```
  interface Insert<QM extends Model> {
    (modelsOrObjects?: Partial<QM>[]): QueryBuilder<QM, QM[]>;
    (modelOrObject?: Partial<QM>): QueryBuilder<QM, QM>;
    (): this;
  }
```
It appears that since `modelsOrObjects` and `modelOrObject` are marked as `?` (Optional), the type inference (rightly) picks up the first matching definition and never hits the third definition. I am not sure if there is a reason for marking those as optional.

Also, `this` in the return type of the third definition resolves to `Insert<QM>` 

From my limited TypeScript knowledge, I think we should have something like 

```
  interface Insert<QM extends Model> {
    (modelsOrObjects: Partial<QM>[]): QueryBuilder<QM, QM[]>;
    (modelOrObject: Partial<QM>): QueryBuilder<QM, QM>;
    (): QueryBuilder<QM, QM>; 
  }
```

**Comment by koskimas** [comment]
Seems like a good solution 👍
