### ISSUE TITLE
Object parsing to one table

### ISSUE THREAD

**Issue by hondem** [Vincit/objection.js#1575]
Hi. I'm trying to solve a problem where I have an object like this on input (this is just an example - my object is way bigger):
```
{
  "name": "Jan",
  "address": {
    "city": "Yadiadiada",
    "postal_code": "541"
  }
}
```
... and I need to save it inside the database with really bad structure
```
NAME (varchar),
CITY (varchar),
POSTAL_CODE (varchar)
```
But as far as I know, I can't just `insert` my data in this table - that would crash, right? Is there any way to somehow "define" schema for input and output? Something like:
```
{
  "name": db.name,
  "address": {
    "city": db.city,
    "postal_code": db.postal_code
  }
}
```
Right now I have function that converts one type to another, but that is... Wel... I don't like it.

Thanks for your help!

**Comment by koskimas** [comment]
Try something like this:

 ```js
class Person extends Model {
  $parseDatabaseJson(json) {
    json = super.$parseDatabaseJson(json)

    if (json.city || json.postal_code) {
      json.address = {
        city: json.city,
        postal_code: json.postal_code
      }

      delete json.city
      delete json.postal_code
    }

    return json
  }

  $formatDatabaseJson(json) {
    if (json.address) {
      json.city = json.address.cirty
      json.postal_code = json.address.postal_code
      delete json.address
    }

    return super.$formatDatabaseJson(json)
  }
}
```
