### ISSUE TITLE
default values for relationMapping

### ISSUE THREAD

**Issue by graemec23** [Vincit/objection.js#1576]
I was wondering if there is a way to have default values for relationMapping?

For example a user can have many interests, and can like many foods. At the moment on query if the fields don't exist, it returns undefined. I would prefer it to return an empty array, rather than undefined.

Is there an easy way through Objection / Knex to do this?

**Comment by koskimas** [comment]
You can try this:

```js
class BaseModel extends Model {
  $parseDatabaseJson(json) {
    json = super.$parseDatabaseJson(json)

    for (const relationName of getManyToManyRelationNames(this.constructor.relationMappings)) {
      json[relationName] = []
    }

    return json
  }
}
```

`getManyToManyRelationNames` should loop through your relation mappings and return the names of the `ManyToMany` and `HasMany` relations. Or you can just hardcode them.

Then you need to inherit your models from `BaseModel`. 

I'm not sure if this will work in all situations. Let me know how it goes.

**Comment by koskimas** [comment]
Another option you could try is to define a constructor and sett the empty arrays there.

**Comment by graemec23** [comment]
Thanks for the reply @koskimas . I just tried your response, I get an error getManyToManyRelationNames is not defined, do I have to import that from Objection?

Also how would you go about setting the array in the constructor?

**Comment by koskimas** [comment]
> getManyToManyRelationNames should loop through your relation mappings and return the names of the ManyToMany and HasMany relations. Or you can just hardcode them.
