### ISSUE TITLE
withGraphFetched not a function

### ISSUE THREAD

**Issue by Chigozie391** [Vincit/objection.js#1577]
The documentation says that the eager method is deprecated, so I tried to use the .withGraphFetched as suggested.
const people = await Person.query()
  .where('firstName', 'Arnold')
  .withGraphFetched('pets');

Person.query(...).where(...).withGraphFetched is not a function

The Deprecated eager worked though

**Comment by koskimas** [comment]
The documentation is for the most recent version, which is 2.0. You are using 1.x.
