### ISSUE TITLE
Functional-style Model definitions

### ISSUE THREAD

**Issue by gylaz** [Vincit/objection.js#1579]
Hi,

Is there a way to define models using functions instead of classes? I imagine in a code-base that is avoiding the use of classes (favoring functional approach) this would be preferred.

**Comment by koskimas** [comment]
Only classes are supported for model classes.

**Comment by devinivy** [comment]
@gylaz if you worked on a functional adaptor to objection's classes, I would be interested to see what you come-up with.  At the end of the day the model instances are _instances_ of some class, so I don't know just how far one might want to go with this idea.
