### ISSUE TITLE
[Objection2], PartialModelObject doesn't work well with generics

### ISSUE THREAD

**Issue by ganymedes01** [Vincit/objection.js#1581]
It seems to ignore properties that have generic types. Below is a minimum way to reproduce the error. Getting an error in `patch` because the property `payload` doesn't exist in `PartialModelObject<MyModel<T>>`.

```ts
import { Model } from 'objection';

class MyModel<T> extends Model {
  id: string;
  payload: T;

  public updateStuff(payload: T) {
    const patch: PartialModelObject<MyModel<T>> = { payload };
    this.$query().patch(patch);
  }
}
```

**Comment by koskimas** [comment]
This is weird. The following works

```js
class MyModel<T> extends objection.Model {
  id!: string
  payload!: T
}

const m = new MyModel<string>()

m.$query().patch({ id: 'hello', payload: 'string' })
```

but if the same code is moved to a instance method, it doesn't  work :confused:

**Comment by koskimas** [comment]
This works though. Maybe you can use it as a workaround until this is fixed?

```js
class MyModel<T> extends objection.Model {
  id!: string;
  payload!: T;

  public updateStuff(payload: T) {
    this.payload = payload
    this.$query().patch();
  }
}
```

**Comment by ganymedes01** [comment]
We're not in a rush to update to `v2` :)

**Comment by koskimas** [comment]
This actually seems like a typescript bug. I found out that this doesn't work either:

```js
class MyModel extends objection.Model {
  id!: string;
  payload!: string;

  public updateStuff(payload: string) {
    this.$query().patch({ payload });
  }
}
```

but this works!!!

```js
```js
class MyModel extends objection.Model {
  id!: string;
  payload!: string;

  public updateStuff(payload: string) {
    const self: MyModel = this // This is the only difference!
    self.$query().patch({ payload });
  }
}
```
```

**Comment by ganymedes01** [comment]
I think it's due to `PartialModelObject` excluding any keys that are `Function`s. Since inside the `class` TS can't know wether `T extends Function` or not, it just excludes that property.

**Comment by koskimas** [comment]
If that's true, there's nothing we can do about it. The second issue may not be related at all if that's the case.

**Comment by koskimas** [comment]
Yep, it really seems to be like you said. Unfortunately we cannot modify `PartialModelObject` to work in this situation without significantly changing the typings. I was able to fix the second issue I found. If you find a way to fix the typings, I'd be happy to merge a PR.
