### ISSUE TITLE
[Objection2] Types for returning always (seem to) want to return array

### ISSUE THREAD

**Issue by willsoto** [Vincit/objection.js#1583]
https://github.com/Vincit/objection.js/blob/1d4ecff1c83350bbea382d554f2c698ee6ab8685/typings/objection/index.d.ts#L671-L679

Given the following - works in 1.x both at run time and compile time:

```typescript
const person = await Person.query()
      .findById(obj.id)
      .update(obj)
      .returning('*');

// Property 'id' does not exist on type 'Person[]'. ts(2339)
console.log(person.id);
```

Where `obj` is typed as an `object` (really an interface, but definitely not an array).

### Expected behavior

The typings for `returning` should return a `Model[]` when an array is provided as an argument to `update`, `insert`, etc and a `Model` when an object is provided.

**Comment by koskimas** [comment]
Easy fix is to move `findById` to last.

**Comment by willsoto** [comment]
That does fix it, thank you. I'll spend some time thinking about the typings to see if there is a better fix.

**Comment by eugene-kim** [comment]
Hi @koskimas , slightly related question so I figured I'd ask here. Let me know if there's a better channel for this. Thanks again for the wonderful library.

The documentation around [returning tricks](https://vincit.github.io/objection.js/recipes/returning-tricks.html#examples) shows a model instance being patched and returning the updated model instance:

```js
const updateJennifer = await jennifer
  .$query()
  .patch({ firstName: 'J.', lastName: 'Lawrence' })
  .returning('*');

console.log(updateJennifer.updatedAt); // NOW()-ish
console.log(updateJennifer.firstName); // "J."
```

Unfortunately the return type on `patch()` is `NumberQueryBuilder`, which results in a model array when `returning()` is chained. Do you have a suggestion / workaround on getting the resolved type of`...$query().patch({...}).returning('*')` to be the single model instance?

Many thanks!

**Comment by ayZagen** [comment]
I am facing with the same problem of @eugene-kim.
My current workaround is as following:

```js
const updateJennifer = await jennifer
  .$query()
  .patch({ firstName: 'J.', lastName: 'Lawrence' })
  .returning<QueryBuilder<Person, number | Person>>('*');
```
