### ISSUE TITLE
v2 .offset & .limit typings denote return type as wrapped in a Page

### ISSUE THREAD

**Issue by mastermatt** [Vincit/objection.js#1585]
https://github.com/Vincit/objection.js/blob/f68fc6bfd932ac1b039db94173a0a0baca2d2955/typings/objection/index.d.ts#L715-L721

I think, both of these methods should just be returning `QB` instead of `PageQueryBuilder<QB>`.

**Comment by koskimas** [comment]
Whoops! I'll fix that asap and release a patch version. Thanks for reporting!

**Comment by koskimas** [comment]
2.0.1 has been released.
