### ISSUE TITLE
[Objection2] fromJson typing does not allow second argument

### ISSUE THREAD

**Issue by jamespedid** [Vincit/objection.js#1586]
Hello, this change is omitted from the migration guide, so I'm not sure if it is a bug or not. Is the second options parameter still supported?

```
interface FromJsonMethod {
    <M extends Model>(this: ModelClass<M>, json: object): M;
}
```

```
static fromJson: FromJsonMethod;
static fromDatabaseJson: FromJsonMethod;
```

Edit: Here is a possible PR
https://github.com/Vincit/objection.js/pull/1587

**Comment by koskimas** [comment]
PR merged. I'll release a new patch version tomorrow.

**Comment by koskimas** [comment]
2.0.2 is out with this fixed.
