### ISSUE TITLE
pluck, pick, and omit depreciation 

### ISSUE THREAD

**Issue by mastermatt** [Vincit/objection.js#1588]
`QueryBuilder#[pluck|pick|omit]` are all now deprecated according to the warnings as of v2.

I just want to confirm because the changelog, migration guide, nor the docs reference the deprecations.

Is the idea that Objection is getting out of the business of collection manipulation and the caller is expected to cover the utility work? Which is fine, of course, I just don't want to go down the wrong path while migrating. 

For example, I currently have this use of `pluck`:
```ts
const dates: Date[] = await MyModel.query()
      .where(...)
      .select("update_date as date")
      .pluck("date")
```
... and while the following is equivalent, without `pluck`, is it the recommended approach now? 
```ts
const rows: { date: Date }[] = await MyModel.query()
      .where(...)
      .select("update_date as date")

const dates = rows.map(row => row.date)
```

**Comment by koskimas** [comment]
I must have forgotten to update the documentation. The changelog doesn't list deprecated methods.

You can chain `then`:

```js
const dates: Date[] = await MyModel.query()
      .where(...)
      .select("update_date as date")
      .then(items => items.map(it => it.date))
```

**Comment by koskimas** [comment]
Documentation has now been fixed.

**Comment by srdone** [comment]
The `lodash/fp` example above is not equivalent to the simple lambda example just above it. `pick` creates a new object from a given object, and returns an empty object if it is handed an array.

Instead, the example should read:

```javascript
const { map } = require('lodash/fp')

const dates: Date[] = await MyModel.query()
      .where(...)
      .select("update_date as date")
      .then(map('date'))
```

**Comment by joneldiablo** [comment]
Hi!!!!
how we could replace omit?

**Comment by bentaber** [comment]
@joneldiablo @LakjeewaW omit can be simply `delete modelInstance[prop];`

**Comment by joneldiablo** [comment]
@bentaber is not the best. For example, if we find 10,000 rows and the column we want to delete is a blob type and each row has 1mb of information, the transaction will be really reckless, getting so much information and then deleting it. Although I am doing it with a password field, I get some rows from a users table and then I do: `users.forEach (u => delete u.pass)`
@LakjeewaW, @bentaber the most suitable solution I found has been to use the modifiers in the model, like this:

```
   static modifiers = {
     related: builder => {
       builder.select ('id', 'UUID', 'payment_date');
     },
     files: builder => {
       builder.select ('id', 'UUID', 'xml', 'pdf', 'rfc_emitter');
     }
   };
```

but I still thinking it's a lot of code declare a modifier with all columns except the column which you want remove, if you only want to remove one or two fields from your selection

**Comment by lehni** [comment]
@joneldiablo a bit late, but for those missing `omit()` from older versions, here a suggestion: 

https://github.com/Vincit/objection.js/issues/2284#issuecomment-1509082977
