### ISSUE TITLE
Insert child Record along with Parent Record

### ISSUE THREAD

**Issue by bhavikpatel7023** [Vincit/objection.js#1590]
Hi,

I have the following table.

1. User
2. Role

I want to assign multiple roles when I'm creating a User.

How I can do this?

**Comment by koskimas** [comment]
Ssee [insertGraph](https://vincit.github.io/objection.js/api/query-builder/mutate-methods.html#insertgraph).

**Comment by bhavikpatel7023** [comment]
Thanks @koskimas 
 insertGraph worked well.

const sylvesters = await Person.query()
    .where('firstName', 'Sylvester')
    .withGraphFetched('children')
    .orderBy('id');

When I'm trying to this. I'm getting error.

```
My Version is  
    "objection": "1.6.11",
    "knex": "^0.14.4",
```
.default.query(...).withGraphFetched is not a function

**Comment by koskimas** [comment]
`withGraphFetched` was added in 2.0.
