### ISSUE TITLE
Property scrubbed from .insert()

### ISSUE THREAD

**Issue by jdolearydl** [Vincit/objection.js#1593]
Executing the following:
``` js
const question = await Question.query().insert({ 
  text: 'bb14',
   display_type: 'radio',
   section_id: 7005,
   order: 7,
   control_question_id: 532,
   control_option_id: 2,
   abbreviation: 1 })
```
Runs the sql:
`insert into "question" ("control_option_id", "control_question_id", "display_type", "order", "section_id", "text") values (?, ?, ?, ?, ?, ?) returning "id"`

**Why is the abbreviation property removed from the query?**

May be similar to: https://github.com/Vincit/objection.js/issues/100

**Comment by jdolearydl** [comment]
Extra info:

This is the Question Model:
``` js
const Model = require('objection').Model
const Option = require('./Option')
const Abbreviation = require('./Abbreviation')
const QuestionOption = require('./QuestionOption')

class Question extends Model {
  static get tableName () {
    return 'question'
  }

  static get relationMappings () {
    return {
      options: {
        relation: Model.ManyToManyRelation,
        modelClass: Option,
        join: {
          from: 'question.id',
          through: {
            from: 'question_option.question_id',
            to: 'question_option.option_id',
            modelClass: QuestionOption
          },
          to: 'option.id'
        }
      },
      abbreviation: {
        relation: Model.HasOneRelation,
        modelClass: Abbreviation,
        join: {
          from: 'question.abbreviation',
          to: 'abbreviation.id'
        }
      }
    }
  }

  static get jsonSchema () {
    return {
      type: 'object',
      properties: {
        'id': { type: 'integer' },
        'text': { type: 'string' },
        'help_text': { type: 'string' },
        'description': { type: 'string' },
        'display_type': { type: 'string' },
        'section_id': { type: ['integer', 'null'] },
        'control_question_id': { type: ['integer', 'null'] },
        'control_option_id': { type: 'integer' },
        'description_required': { type: 'boolean' },
        'order': { type: 'integer' },
        'abbreviation': { type: ['integer', 'null'] }
      }
    }
  }
}

module.exports = Question

```

**Comment by jdolearydl** [comment]
Is it because the relationMapping 'abbreviation' shares the same name as the 'abbreviation' property?  If so, that still shouldn't prevent and insert or update.

**Comment by koskimas** [comment]
Yes it should.

**Comment by koskimas** [comment]
It seems that there's no error message if the first operation you do is an insert. That's because of lazy initialization that is important in serverless setups. You only get the error message the first time you use the relation in some way, but unfortunately `insert` still removes the property because it needs removes all relations before insert.

**Comment by koskimas** [comment]
By the way, your `abbreviation` relation should be a `BelongsToOneRelation` and not `HasOneRelation`.

**Comment by jdolearydl** [comment]
> By the way, your `abbreviation` relation should be a `BelongsToOneRelation` and not `HasOneRelation`.

What's the returned difference?  It still returns the data as I would expect.
I now know what [the differences are](https://vincit.github.io/objection.js/guide/relations.html#examples) but I'm wondering why it gives me a usable result?  Where could this go wrong if it stays `HasOneRelation`?

**Comment by koskimas** [comment]
At least inserts `relate` and `unrelate` would fail.
