### ISSUE TITLE
Changelog outdated

### ISSUE THREAD

**Issue by Heartnett** [Vincit/objection.js#1594]

**Comment by koskimas** [comment]
They are patch versions.

**Comment by Heartnett** [comment]
It would be great to know what has been patched. Unfortunately not everybody has the time to dig through the commit logs the see what changed.

**Comment by koskimas** [comment]
Unless you install objection using sn exact locked version, patch versions will get automatically upgraded. They are meant to be installed by all. They should never break anything. Changelog for patch versions is pretty useless unless you arw waiting for a fix for some particular bug.

**Comment by koskimas** [comment]
Here you go https://vincit.github.io/objection.js/changelog/

Next time, use words like a human being.
