### ISSUE TITLE
[Question] Virtual async field.

### ISSUE THREAD

**Issue by Satont** [Vincit/objection.js#1596]
Hi.

I'm interest, does it possible have async virtual field or something in model on find query?

I wan't do request to some api before show table data, like:
```js
class MyModel extends Model {
  id!: number
  myAsyncValue: 'string'

 async afterFind(){
   this.myAsyncValue = await axios.get('http://localhost/api')
 }
}
async function test() {
  const result = await MyModel().findOne({ id: 1 })
  console.log(result)
//{
// id: 1
// myAsyncValue: 'This value returned from api'!
//}
}
```

**Comment by koskimas** [comment]
There is $afterFind. Your code should work if you just prefix your method with a dollar sign. Before 2.0 the hook is called $afterGet. Be careful with those hooks though. The hook is called for each model instance. 2.0 has more suitable static hooks. See the documentation secrion about hooks.

**Comment by koskimas** [comment]
https://vincit.github.io/objection.js/guide/hooks.html#instance-query-hooks

**Comment by Satont** [comment]
Well, i was tryed static function instead.
Thanks, instance method is working for me.

**Comment by koskimas** [comment]
You didn't declare the function static. Also `this` in static methods is the model class constructor.
