### ISSUE TITLE
for is not a function

### ISSUE THREAD

**Issue by AbdusamadTurdiev** [Vincit/objection.js#1597]
Objection's version is 1.6.9

I'm using `for` method with `relatedQuery` and getting `.for is not a function`

![image](https://user-images.githubusercontent.com/33511684/70410942-8e0c8300-1a72-11ea-8dc0-bace52a3cc4e.png)

I've checked and there's really no `for` method 

![image](https://user-images.githubusercontent.com/33511684/70411062-fce9dc00-1a72-11ea-9da4-9e720a7b466c.png)

**Comment by koskimas** [comment]
That method was added in 2.0.
