### ISSUE TITLE
upsertGraph not working for composite key

### ISSUE THREAD

**Issue by carotorrehdz** [Vincit/objection.js#1599]
@koskimas I know you are tired of issues regarding `upsertGraphAndFetch` 😅 but it's really an amazing feature so I hope this issue won't bother you that much.

I have a model with a composite key `id, version`, I set `idColum` in my model to be
`['id', 'version']`. If I use objection `0.9.4 (really old version I know, it's a project I made a while ago`, I can use `upsertGraph` with my composite key without any trouble. 
```javascript
Model.query(trx).upsertGraphAndFetch({ id: 8, version: "A", status: "SENT" });
```
But in a new project I'm currently working on using objection `2.0.0` I can't make that same call to `upsertGraphAndFetch`. First it throws an insertMissing option warning, but if I add insertMissing to graphOptions it still won't work.

**Comment by koskimas** [comment]
Could you provide a reproduction? We do have tests for composite keys and they pass.

**Comment by koskimas** [comment]
I just tried you example and it works.

**Comment by koskimas** [comment]
Even though it worked, I found some weirdness in the SQL that may be causing the bug for you in some case (not in the case you provided though).

**Comment by koskimas** [comment]
@carotorrehdz I just fixed the bug I found. Could you try the new 2.0.5 version?

**Comment by carotorrehdz** [comment]
I have tried the new version 2.0.5, but still got an error.
Let me show you my schema:

```SQL
CREATE TABLE A (
    id SERIAL,
    version text,
    CONSTRAINT A_pk PRIMARY KEY (id, version)
);
```

```javascript
const Model = require('objection').Model;
class A extends Model {
    static get tableName() {
        return 'A';
    }

    static get idColumn() {
        return ['id', 'version'];
    }
}
```

And I'm trying to use `upsertGraphAndFetch` like this:
```javascript
A.query()
 .upsertGraphAndFetch({
    "id": 8,
    "version": "A"
 }, {})
 .debug(true);
```

The error that is thrown is
```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 8, 'A' ],
  __knexQueryUid: 'e2b86709-81dc-4331-bd0d-b468d8886de5',
  sql: 'select "proposals"."version", "proposals"."id" from "proposals" where ("proposals"."id", "proposals"."version") in ((?, ?))' }
(node:52123) UnhandledPromiseRejectionWarning: NotFoundError: root model (id=8,A) does not exist. If you want to insert it with an id, use the insertMissing option
```

**Comment by koskimas** [comment]
I cannot reproduce that. Objection has a test just like that, and it passes. I'll need a full reproduction I can run using a single command. There's the `reproduction-template.js` file in the repo root you can use as  a starting point.

**Comment by koskimas** [comment]
No response, closing.
