### ISSUE TITLE
Could we extend all normal knex query builder methods to support json field expression

### ISSUE THREAD

**Issue by elhigu** [Vincit/objection.js#16]
Json query API could be even easier to use if all knex query builder methods can take in Json field expressions in addition to plain knex column references. In that case instead of knex implementation our json query versions would be called.

Somewhat related to #18

**Comment by diorahman** [comment]
+1

**Comment by elhigu** [comment]
This needs to be done before #187 so this is now in progress

**Comment by elhigu** [comment]
Implemented in https://github.com/Vincit/objection.js/pull/270
