### ISSUE TITLE
insertWithRelated validates models before interpolation

### ISSUE THREAD

**Issue by johanneslumpe** [Vincit/objection.js#160]
I'm not using `JSONSchema`, but `Joi` to validate my models. I was about to use `insertWithRelated` and then use `#id` and `#ref(myId.id)` to add the model's new id to the nested inserts.

Then I noticed that the nested models get validated before the strings get interpolated. This seems a bit odd because the validation cannot properly assert whether the values are going to be correct. Is this intended @koskimas or is there something we can do about this so that related models only get validated after interpolation/replacement took place?

**Comment by koskimas** [comment]
The `$validate` method gets an options objection as a second parameter. I only now realised this is not documented anywhere 😁. Anyways you need to honour the `options.skipValidation` boolean which is true when the method is called before interpolation. I know it's weird that the method is called at all when validation needs to be skipped. There are also some other issues with the validation system that I intend to fix in the near future.

The real signature of `$validate`
```
  /**
   * @throws {ValidationError}
   * @param {Object=} json
   * @param {ModelOptions=} options
   * @return {Object}
   */
  $validate(json = this, options = {}) {

  }
```

**Comment by johanneslumpe** [comment]
Oh 😁 Ok great, I will give that a go, thanks!
