### ISSUE TITLE
How to bind argument to modifyGraph

### ISSUE THREAD

**Issue by IceTrooper** [Vincit/objection.js#1604]
Usually I'm not creating new issues on github when I want to only ask, but Objection lacks of some forum or Discord server / or a guide where to ask (I'm new in web-dev and even more in Objection/knex and that lack sucks :/ it's so difficult to start when you can't ask).
I got problems with doing this:
```js
// This way you can bind arguments to modifiers.
  onlyDogs: query => query.modify('onlySpecies', 'dog')
```

but for modifyGraph (I started with Offer model)
```js
      const offersQuery = req.db.Offer
        .query()
        .where('search_id', maxedSearch)
        .withGraphJoined('[outboundFlight, inboundFlight]');
// ........

      const dateDeparture = new Date(req.query.departure);
      console.log(dateDeparture);
      offersQuery.modifyGraph('outboundFlight', 'onlyDepartureInDate', dateDeparture);
```
and my modifier in Flight model
```js
    onlyDepartureInDate(query, date) {
      console.log(date);
      if (+date) {
        query.whereBetween('from_date',
          [date.getTime(), date.getTime() + 86400000]);
      }
    },
```
It doesn't pass a dateDeparture to modifyGraph. I got undefined in onlyDepartureInDate modifier. How to do it?

**Comment by koskimas** [comment]
There is a [gitter](https://gitter.im/Vincit/objection.js) "room".

you can do this:

```js
      offersQuery.modifyGraph('outboundFlight', query => query.modify('onlyDepartureInDate', dateDeparture));

```
