### ISSUE TITLE
$afterInsert

### ISSUE THREAD

**Issue by crespowang** [Vincit/objection.js#1605]
Just a simple question not an issue, is $afterInsert part of the Object.query().insert()?
ie 
will
```
await Object.query().insert()
```
wait until `$afterInsert` is complete?

**Comment by ky-cheng** [comment]
In particular, we can to know how this will behave when run in AWS lambda serverless environment. Just worry that `$afterInsert` won't have a chance to run / finish if it does its work asynchronously behind the scene independent of `insert`.

**Comment by koskimas** [comment]
`$afterInsert` can be async as it is clearly said in the documentation.
