### ISSUE TITLE
NotNullViolationError does not exist in typings

### ISSUE THREAD

**Issue by e1337us3r** [Vincit/objection.js#1607]
I switched to v2 this morning and got the following error in my error handler middleware:

`TS2305: Module '"../../node_modules/objection/typings/objection"' has no exported member 'NotNullViolationError'.`

I checked the typings file, NotNullViolationError really does not exist there. 

Fix: NotNullViolationError originates from db-errors so a simple export in typings file will fix the issue.

**Comment by koskimas** [comment]
Thanks! Will be fixed in the next patch version. Will release it this week. In the meantime you can import it from `db-errors` . No need to add it to your package.json explicitly. Objection depends on it.

**Comment by e1337us3r** [comment]
Dang, that was the fastest closure of an issue that I have ever seen. Thanks!
