### ISSUE TITLE
Documentation does not specify if forUpdate/forShare is propagated on withGraphFetched

### ISSUE THREAD

**Issue by svrnwnsch** [Vincit/objection.js#1608]
Neither the documentation for [withGraphFetched](https://vincit.github.io/objection.js/api/query-builder/eager-methods.html#withgraphfetched) nor the documentation for [forUpdate](https://vincit.github.io/objection.js/api/query-builder/find-methods.html#forupdate) state if the forUpdate is propagated to the other fetch queries.

If this is currently not the case I would like to have such a feature where I can explicitly say: "the related fetched parts will also be updated" to the database.

I only found this similar discussion for #1127 upsert graph.

**Comment by koskimas** [comment]
It's not propagated to other queries. You can always chain `debug` to any query to see what's going on.

You can use modifiers:

```js
await Person.query().withGraphFetched('[children(forUpdate), movies(forUpdate)]')
```

and then define a `forUpdate` modifier for your models (or a single shared parent class).

**Comment by svrnwnsch** [comment]
thank you for you quick answer, and the suggestion.
