### ISSUE TITLE
Feature Request: Type checked where

### ISSUE THREAD

**Issue by fer22f** [Vincit/objection.js#1609]
So, I hacked something:

```js
export class QueryBuilder<
  QM extends Objection.Model,
  RM,
  RV
> extends Objection.QueryBuilder<QM, RM, RV> {
  whereModel(obj: PartialModelObject<QM>): this {
    return this.where(obj);
  }
}

const Model = class CustomModel extends DBErrors(Objection.Model) {
  static get QueryBuilder() {
    return QueryBuilder;
  }

  static query<U extends CustomModel>(...args: Array<any>) {
    return super.query(...args) as QueryBuilder<U, U[], U[]>;
  }
};
```

Now if I use

```js
await MyModel.query<MyModel>(trx).whereModel({
  someColumn: null,
  someNonExistentColumn: null
})
```

I get Typescript errors :D. The problem, as you can see is that requirement of `<MyModel>`, which is caused by this: https://github.com/microsoft/TypeScript/issues/5863. But I think there are ways around that.

**Comment by koskimas** [comment]
Unfortunately it's really not that simple. With objection, you can join anything, tables, subqueries etc. you can select `from` any expression. There's no way to typecheck all that.

**Comment by fer22f** [comment]
Sure, but couldn't we have a specific method for this, say `whereModel`, `selectModel`?

**Comment by kanekv** [comment]
@koskimas  Typed version of where and select seem like a good idea, is it possible though?
