### ISSUE TITLE
innerJoinRelation without specifying .select() would overwrite values 

### ISSUE THREAD

**Issue by oiime** [Vincit/objection.js#161]
eg: 

`
model.query().innerJoinRelation('model2')
`

would overwrite model's id column with model2's id column as not specifying .select() defaults to '*', no ambiguous column warning is given (using mysql 5.7 with mysql2 as adapter)

**Comment by koskimas** [comment]
There is currently no way of knowing the columns the table has, so we need to use a generic `*`. `jsonSchema` is optional and even if one uses it there are cases when the properties in that are different from the table columns. You need to specify `select()`.

**Comment by oiime** [comment]
That's reasonable, But I think it'll be good to maybe do one of the following 

* note that in the documentation
* default to selecting only model.* unless .select() is specified if innerJoinRelation is used. 
* you can figure out which columns belong to which table using this trick:

`
SELECT table1.*, '' AS 'table1_END', table2.*, '' AS 'table2_END' FROM table1 INNER JOIN table2 ON (table1.table2id = table2.id)
`

This would give you each table columns separated by the table name suffixed with _END, not sure if you'd consider this too "hackish" or not but it should work fine in both mysql variants and postgresql (dunno about sqlite) 

Overall I think doing both the first and second option would be best, there are very few scenarios I can think of where defaulting to * with a join is good.

up to you

**Comment by koskimas** [comment]
I think we should default to `select model.*` as you mentioned. I'll fix this for 0.6.0 release.

**Comment by koskimas** [comment]
Sorry, didn't fix this for 0.6.0 😬 There was so much new stuff in 0.6 and it has been a while since a stable release that I just decided to release it.
