### ISSUE TITLE
Updating Child record it's not considering parent as updated

### ISSUE THREAD

**Issue by bhavikpatel7023** [Vincit/objection.js#1610]
I have two table.
1.Mailbox
2.MailboxDoor

When I updating MailboxDoor, it's not considering Mailbox as updated.

The mailbox has no of doors. based on the number of doors, I have to do the validation. 

If I set a number of the door would be 2, I can not enter more then two rows. 

In this framework we need below listed all hooks.
validate
before_save
autoname
before_insert
after_insert
before_submit
before_cancel
before_update_after_submit
on_update
on_submit
on_cancel
on_update_after_submit
on_change
on_trash
after_delete

![image](https://user-images.githubusercontent.com/13928055/70726976-e76fee80-1ccc-11ea-9f95-009b56507708.png)

**Comment by koskimas** [comment]
I have no idea what all this means. Please read the instructions on how to create issues and try again.

**Comment by bhavikpatel7023** [comment]
Please refer to this.

https://frappe.io/docs/user/en/guides/basics/hooks

**Comment by bhavikpatel7023** [comment]
There is no document that say's what should I mention to create an issue.

**Comment by koskimas** [comment]
Yes there is https://vincit.github.io/objection.js/guide/contributing.html.

You can start by clearly stating your question/issue. What you wrote here, just seems to be a specification for your app. There's no question, there's no clearly stated problem, and nothing seems to be related to objection.

> When I updating MailboxDoor, it's not considering Mailbox as updated.

What does this mean? Are you already doing an update? If so, what method are you using? What data are you passing in? You need to provide the code you are running. Is is a problem or is this the intended behaviour?
