### ISSUE TITLE
Multi eager wasn't returned by library

### ISSUE THREAD

**Issue by Satont** [Vincit/objection.js#1611]
Objection.js version: 2.0.6
Node.js version: 12
Platform: linux
Db engine: postgres
How i'm initialize library: 
```ts
import { Model } from 'objection'
import Knex from 'knex'

const knex = Knex({
  client: 'postgres',
  connection: {
    host: db.host,
    port: Number(db.port),
    database: db.database,
    user: db.username,
    password: db.password,
  },
})

Model.knex(knex)
```
I have an query with multi relations, example is:
```ts
const myResults = await RequestModel.query()
      .withGraphJoined('[userway.[point1, point2], types]')
      .where({ user_id: 1 })
      .page((1 - opts.page) * opts.per_page, opts.per_page)
```

It's not throwing any error, but working wrong, atleast for me.
Problem is: `point1` and `point2` wasn't `returned` from that query.

I've added .debug() to that query, copyed sql query, executed at pg server, and it returned me `point1` and `point2`, but library not (possible just not showed as result), only `userway` relation.

So, something with multi-eagered relations.
Maybe i missed something, but why sql query  - working, `Request.query()` - not?

**Comment by koskimas** [comment]
See the docs of withGraphJoined. Paging doesn't work correctly with joins. This is not related to objection, but the way joins work in SQL.

**Comment by Satont** [comment]
It also not working without paging.

**Comment by Satont** [comment]
Again: `request_table:userways:point1`, `request_table:userways:point2` exist on plain sql result (via pgAdmin/phppgadmin), but on library result not.
Even i'm not using `where()` and `page()`
How i can proper debug it?

`debug()` shows only sql queries, but not sql results.

Thank you.

**Comment by koskimas** [comment]
I'll fix any bug you can prove by providing a reproduction. You can use the `reproduction-template.js` file as a starting point. Otherwise I'll assume that this is a user error.

You may be able to use knex debug env variables to log the results too, but I'm not sure.

**Comment by koskimas** [comment]
I can first take a look at the models to see if you have something funky in the relation mappings. Could you share all relevant models here?

**Comment by Satont** [comment]
I can't share that models, but I'll try create reproducable template.
