### ISSUE TITLE
JSON schema validation seems not to be applied to insertGraph()

### ISSUE THREAD

**Issue by ohueter** [Vincit/objection.js#1614]
I'm trying to control the insertion of data by using JSON schema validation. I created a custom Ajv validator on my model according to this [recipe](https://vincit.github.io/objection.js/recipes/custom-validation.html) to supply custom options, i.e. `removeAdditional: "all"`.

When I use insert() with intentionally wrong data (containing a field/column not existing on the table) for testing, additional fields not specified in the schema are removed from the query as expected, and the insert is executed. 

When I use `insertGraph(data, { relate: true })` with the same data, Objection fails with an error like `DBError: <query> column "<additional_field>" of relation "<name>" does not exist`, i.e. a database error. It seems like the validation is not done at all, although insertGraph() is listed in the [docs](https://vincit.github.io/objection.js/guide/validation.html#examples) as a function triggering the validation. Is that expected behavior?

**Comment by koskimas** [comment]
Data passed to `insertGraph` does get validated.
