### ISSUE TITLE
JsonSchema issue

### ISSUE THREAD

**Issue by ssruiz** [Vincit/objection.js#1615]
Hi! I followed the docs on this but I'm having issues with the static method jsonSchema
My class look like this:
![image](https://user-images.githubusercontent.com/11683136/70937333-dc95c080-2022-11ea-9d6e-e015bfb9fef3.png)
And I'm getting this error:
![image](https://user-images.githubusercontent.com/11683136/70937554-38f8e000-2023-11ea-85b1-39420fad1f39.png)

I'm working on a Node backend using Nestjs framework. I already upgraded Objection to the 2.0 version but the error still remains. I noticed that in other class I have  I use that property and not getting the error(using 'objection-password'). That class looks like this :
![image](https://user-images.githubusercontent.com/11683136/70937899-f08df200-2023-11ea-9978-c42ead276c77.png)

**Comment by koskimas** [comment]
The `type` field has a type `'string' | 'boolean' | 'integer' ...` etc. It's not compatible with a generic string, because you could in theory just say `UsuarioModel.jsonSchema.properties.id.type = 'lol'`. You need to specify a type for the `jsonSchema` property

```js
static jsonSchema: JSONSchema = { ...
```

**Comment by koskimas** [comment]
Don't know why a plugin is causing this, but that's not really objection's fault, but the plugin's

**Comment by ssruiz** [comment]
Oh I see. Thanks for the quick answer!. I also try this and works:
![image](https://user-images.githubusercontent.com/11683136/70941433-35695700-202b-11ea-9f90-11a669dcb666.png)
Thank you again. I love objection!, keep it up the good work

**Comment by koskimas** [comment]
Thanks! 

That works because `Model` has `any` type when you use that, effectively disabling typescript. The same probably happens with the plugin by the way.
