### ISSUE TITLE
Instance method $relatedQuery doesn't reuse knex instance

### ISSUE THREAD

**Issue by aelayeb** [Vincit/objection.js#1616]
If I'm trying to retrieve related object from an Objection model without giving the knex instance, it throws an error.

Currently I have to do the following:
`await service.$relatedQuery('offers', service.$knex())`

But I would have expected this to also work:
`await service.$relatedQuery('offers')`

Having the choice to specify a specific knex instance is good, but by default it should naturally reuse the parent model one.
It feels cumbersome and not intuitive.

**Comment by koskimas** [comment]
If `modelInstance.$knex()` holds a knex instance, it does use it.

**Comment by aelayeb** [comment]
Then it doesn't work indeed.
I made a minimal reproduction here: https://github.com/aelayeb/objectionjs-issue-1616
If you can check this up it would be great.

Thanks

**Comment by koskimas** [comment]
You only install the knex for `Service` model. The related query is for `Offer` modelm

**Comment by aelayeb** [comment]
Yes but that's what I'm saying: I expected the children model to inherit his parent connection if it's not specified.

**Comment by koskimas** [comment]
Yeah, I misunderstood that originally. Everything works as expected here.

**Comment by aelayeb** [comment]
Any way to have this feature then ?
When working with transaction it becomes hard to read.

**Comment by koskimas** [comment]
If you are using transactions like that, things will go horribly wrong. Calling `Service.knex` installs the transaction globally, and all concurrent queries will take part in the same transaction. Just don't do it like that.

**Comment by aelayeb** [comment]
Yes of course but even If I use it at the instance level, like `service.$knex(knex)` I have the same problem.

**Comment by koskimas** [comment]
`service.$knex(knex)` simply calls `Service.knex(knex)` which does the same thing. It's just a shortcut to the static method.

You can do this instead:

```js
const BoundService = Service.bindTransaction(trx)

const service = await BoundService.query().findById(id)
const offers = await service.$relatedQuery('offers')
```

which works the way you expect.

**Comment by koskimas** [comment]
Actually `service.$knex(knex)` does nothing. This is the implementation

```js
  $knex() {
    return this.constructor.knex();
  }
```
