### ISSUE TITLE
How to set up one connection pool or one connection without a connection pool to share TEMPORARY TABLE at Objectio.js?

### ISSUE THREAD

**Issue by wwwork** [Vincit/objection.js#1617]
I need to use the Postgres temp table (**only**) to share that data between other controllers and methods.

My app (Nest.js  + Objection.js)

// app.module.ts
   
```
    async onModuleInit() {
          this.createVideoTempFolder();
          // create temporaty table at account.repository.ts
          await this.accountRepository.createAccountTempTable();
        }
```

// account.repository.ts

```
    public async createAccountTempTable() {
        // create TEMP TABLE FOR CURRENT SESSION
        const queryRaw = this.modelClass.knex();
        await queryRaw.raw(`CREATE TEMPORARY TABLE accounts ON COMMIT PRESERVE ROWS as select * from accounts_main;`);
          }
```

But my App doesn't see any temporary table at an existing connection pool.
It means that every router request starts a new connection pool with Objection.js and the temporary table stays at a previously created connection pool and my App doesn't see any temporary table.

How to set up one connection pool or one connection without a connection pool to share TEMPORARY TABLE at Objectio.js?

**Comment by koskimas** [comment]
You probably need to create a transaction, which reserves one single connection and then pass around that transaction. See the transaction guide in the docs.

**Comment by elhigu** [comment]
There is also non public API in knex which can be used to get connection from pool manually and releasing it back. Something like that is meant to be made public too in knex.

There is a method in knex, which then allows you to pass that connection to the builder https://knexjs.org/#Builder-connection

Something like this:

```
let connection = await knex.client.acquireConnection();
try {
    const queryRaw = this.modelClass.knex().connection(connection);
    await queryRaw.raw(`CREATE TEMPORARY TABLE accounts ON COMMIT PRESERVE ROWS as select * from accounts_main;`);
} finally {
    knex.client.releaseConnection(connection);
}
```

**Comment by wwwork** [comment]
Thanks, I'll try it.

**Comment by koskimas** [comment]
Are temp tables really per connection and not per transaction? Sounds odd
