### ISSUE TITLE
How to track changes to models?

### ISSUE THREAD

**Issue by brax10ward** [Vincit/objection.js#1620]
I am in search of a library similar to https://www.npmjs.com/package/sequelize-paper-trail but for objection.

Does something exist? I haven't been able to find anything. 

If not, does anybody have any tips of how to implement something like this easily?

**Comment by koskimas** [comment]
I haven't heard of anything like that for objection. You could probably use the [new static hooks](https://vincit.github.io/objection.js/guide/hooks.html#static-query-hooks) to implement something like that (at least to some degree).
