### ISSUE TITLE
A typescript issue: [tsserver 2315] []Type 'QueryBuilder' is not generic.

### ISSUE THREAD

**Issue by kelgendy1204** [Vincit/objection.js#1625]
I can find this issue at this line in the type definition file

https://github.com/Vincit/objection.js/blob/54dcc32f568f18cfa6d089009414b8c5a4ae3d11/typings/objection/index.d.ts#L1049

**Comment by koskimas** [comment]
I can't

**Comment by kelgendy1204** [comment]
Yes, my bad after updating knex it works, thanks.

**Comment by huzaifaAhmedTestlio** [comment]
I am also getting same error,
  "dependencies": {
    "@koa/cors": "^4.0.0",
    "joi": "^17.7.0",
    "jsonwebtoken": "^9.0.0",
    "knex": "^2.3.0",
    "koa": "^2.14.1",
    "koa-body": "^6.0.1",
    "koa-helmet": "^6.1.0",
    "koa-jwt": "^4.0.3",
    "koa-router": "^12.0.0",
    "lodash": "^4.17.21",
    "mysql2": "^2.3.3",
    "newrelic": "^9.7.4",
    "objection": "^3.0.1",
    "performance-now": "^2.1.0",
    "raygun": "^0.13.2"
  },
  "devDependencies": {
    "@types/chai": "^4.3.4",
    "@types/joi": "^17.2.3",
    "@types/jsonwebtoken": "^9.0.0",
    "@types/koa": "^2.13.5",
    "@types/koa__cors": "^3.3.0",
    "@types/koa-helmet": "^6.0.4",
    "@types/koa-router": "^7.4.4",
    "@types/lodash": "^4.14.191",
    "@types/mocha": "^10.0.1",
    "@types/node": "^18.11",
    "@types/proxyquire": "^1.3.28",
    "@types/raygun": "^0.11.0",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.47.1",
    "@typescript-eslint/parser": "^5.47.1",
    "chai": "^4.3.7",
    "concurrently": "^7.6.0",
    "eslint": "^8.31.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "mocha": "^10.2.0",
    "mocha-junit-reporter": "^2.2.0",
    "nodemon": "^2.0.20",
    "nyc": "^15.1.0",
    "prettier": "^2.8.1",
    "proxyquire": "^2.1.3",
    "sinon": "^15.0.1",
    "supertest": "^6.3.3",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.4"
  }
