### ISSUE TITLE
Generating select into join clause

### ISSUE THREAD

**Issue by moutb** [Vincit/objection.js#1629]
I'm getting this SQL when i'm making a join clause:

```sql
select 
  "CALL_REQ"."ID", 
  "CALL_REQ"."DESCRIPTION",
  "CUSTOMER"."CONTACT_UUID" "CUSTOMER_CONTACT_UUID", 
  "CUSTOMER"."FIRST_NAME" "CUSTOMER_FIRST_NAME",
  "CUSTOMER"."LAST_NAME" "CUSTOMER_LAST_NAME"
from
  "CALL_REQ"
  inner join (select "CA_CONTACT".* from "CA_CONTACT") "CUSTOMER" on "CUSTOMER"."CONTACT_UUID" = "CALL_REQ"."CUSTOMER"
where "CALL_REQ"."PERSID" = ? and "CALL_REQ"."TYPE" = ?
```
My db connector is oracle.
Here is my code:

```javascript
// ticket.js
export default class Ticket extends Model {

    static get tableName() {
        return 'CALL_REQ';
    }

    static get idColumn() {
        return 'PERSID';
    }

    static get relationMappings() {
        const Contact =  require('./contact').default;
        return {
            customer: {
                relation: Model.BelongsToOneRelation,
                modelClass: Contact,
                join: {
                    from: `${Contact.tableName}.CONTACT_UUID`,
                    to: `${Ticket.tableName}.CUSTOMER`                    
                }
            }
        }
    }
}
```

```javascript
// contact.js
export default class Contact extends Model {

    static get tableName() {
        return 'CA_CONTACT';
    }

    static get idColumn() {
        return 'CONTACT_UUID';
    }
}
```
And in my query js file i have
```javascript
let fields = ['CALL_REQ.ID', 'CALL_REQ.DESCRIPTION']
    .concat(['CUSTOMER.CONTACT_UUID as CUSTOMER_CONTACT_UUID', 
    'CUSTOMER.FIRST_NAME as CUSTOMER_FIRST_NAME',
    'CUSTOMER.LAST_NAME as CUSTOMER_LAST_NAME']);
        
return await Ticket.query()
    .findById(id)
    .select(fields)
    .joinRelated('customer', { alias: 'CUSTOMER' })
    .andWhere(Ticket.tableName + '.TYPE', 'R');
```
What i've to do to get the next SQL?
```sql
sql
select 
  "CALL_REQ"."ID", 
  "CALL_REQ"."DESCRIPTION",
  "CUSTOMER"."CONTACT_UUID" "CUSTOMER_CONTACT_UUID", 
  "CUSTOMER"."FIRST_NAME" "CUSTOMER_FIRST_NAME",
  "CUSTOMER"."LAST_NAME" "CUSTOMER_LAST_NAME"
from
  "CALL_REQ"
  inner join "CA_CONTACT" "CUSTOMER" on "CUSTOMER"."CONTACT_UUID" = "CALL_REQ"."CUSTOMER"
where "CALL_REQ"."PERSID" = ? and "CALL_REQ"."TYPE" = ?
```
I'm using objection@2.0.8
Thanks!

**Comment by koskimas** [comment]
You shouldn't be getting that SQL from that query. I've seen people getting this kind of queries before, but none have ever provided a reproduction for them.

Objection has tests for `joinRelated` queries like that, and they don't produce the subquery in the join. I'd be happy to fix this bug, but I really don't know how to reproduce it. Could you provide a standalone script that reproduces this? Something I can run with a single command like `node reproduction.js`.

**Comment by koskimas** [comment]
Having said that, why do you want to get rid of the subquery? All modern database engines optimize the subquery away and both the current query and the query you want, end up running exactly the same operations in the database engine.

**Comment by moutb** [comment]
Well, i just wanted to check the performance of each query (which is bigger than i've posted here). I will try to reproduce it in the test but i can't use the database credentials so i will use sqlite. ¿Can this issue related with the connector?

**Comment by koskimas** [comment]
You can use sqlite. I don't think this can be related to the db driver. I tried the code you posted, but It didn't reproduce the bug. So it's caused by your setup somehow.

> Well, i just wanted to check the performance of each query

Did you actually measure the performance or did you just assume it's slower because of the subquery? If the latter, that's rarely useful.

**Comment by moutb** [comment]
I've measured the performance and the currently built sql is slower (from 100ms to 20ms more or less) so i will try to send you a complete example reproducing the error.

**Comment by koskimas** [comment]
@moutb Any luck reproducing this?

**Comment by moutb** [comment]
Hi @koskimas, I just got back from vacation and I haven't tried it yet. I'd like to do it this weekend.
