### ISSUE TITLE
TS2684 error when adding constructor to models

### ISSUE THREAD

**Issue by e1337us3r** [Vincit/objection.js#1633]
Objection.js version: 2.0.10
Typescript version: 3.7.2

Problem: I created a class called MyModel which extends from Model class. Everything was good so far, but when I added a public constructor to this class I started getting TS2684 compiler when calling static methods(query, fromJson, etc.) of Model.

> TS2684 : The 'this' context of type 'typeof MyModel' is not assignable to method's 'this' of type 'ModelClass<Payment>'.

MyModel:
`export default class MyModel extends Model {

  public constructor(a:any) {
     // do something
  }
}`

The compiler error message is very cryptic, I have no idea what the problem is.

**Comment by koskimas** [comment]
Objection model constructor takes zero arguments. you also need to call the super.

**Comment by koskimas** [comment]
Objection doesn't really use the constructors though (except for creating empty instances). You are probably better off by overriding the static `fromJson` and `fromDatabaseJson` methods.

**Comment by ahmadtofeeq** [comment]
Prior to objection.js version 2.0.0, non empty constructor in model were allowed. Is there any specific reason of this change implementation @koskimas
