### ISSUE TITLE
Nested relations with 3-way many-to-many join table

### ISSUE THREAD

**Issue by demisx** [Vincit/objection.js#1634]
Hello. First of all, thank you very much for such an outstanding Node ORM framework, excellent online documentation and numerous answers to the community questions. It really, really helps and solves 99% of issues we run into. Except this one that I couldn't find an example how to solve. 

I've looked at these too which seemed related, but I just can't derive my solution from them:
* https://stackoverflow.com/questions/55542139/many-to-many-to-many-relationship-in-objection-js
* https://github.com/Vincit/objection.js/issues/525

Basically, I have these relations in DB model:

![Screen Shot 2019-12-27 at 1 01 35 PM](https://user-images.githubusercontent.com/4452412/71532617-0a8fc600-28a9-11ea-8bdb-a4196473a8d3.gif)

With Objection models defined as:

```ts
// In classified.model.ts
export class ClassifiedModel extends BaseModel {
  static tableName = 'Classifieds'

  static relationMappings = {
    sections: {
      relation: BaseModel.ManyToManyRelation,
      modelClass: () => SectionModel,
      join: {
        from: 'Classifieds.code',
        through: {
          from: 'ClassifiedsSections.classifiedCode',
          to: 'ClassifiedsSections.sectionCode',
        },
        to: 'Sections.code',
      },
    },
  }
  ...
}
```

```ts
// In section.model.ts
export class SectionModel extends BaseModel {
  static tableName = 'Sections'

  /* istanbul ignore next */
  static relationMappings = {
    categories: {
      relation: BaseModel.ManyToManyRelation,
      modelClass: () => CategoryModel,
      join: {
        from: 'Sections.code',
        through: {
          from: 'SectionsCategories.sectionCode',
          to: 'SectionsCategories.categoryCode',
          extra: ['classifiedCode', 'adExpiration'],
        },
        to: 'Categories.code',
      },
    },
  }
  ...
}
```

```ts
// In category.model.ts
export class CategoryModel extends BaseModel {
  static tableName = 'Categories'
  readonly code: CategoryCode
  readonly adExpiration?: number
}
```

I am trying to get all available classifieds with the corresponding eager relations nested in each classified instance:

```ts
const classifiedModels = await ClassifiedModel.query()
      .withGraphFetched('[sections.categories, subs]')
```

and everything seems to work fine except the `categories` relation. I get all possible combinations of them in each section, because the "SectionCategories" is sort of a three-way join table and requires `classifiedCode` passed in order to  filter out categories which aren't part of the current classified row. I spent two days trying to figure out how to do this but pretty stuck so far. Basically, I am trying to get these results back ( i.e `ClassifiedModel[]` with nested relations where categories in each section are those that match given classified):

```ts
ClassifiedModel [
  // Classified 1
  {
    id: 1,
    code: 'classifiedCode1',
    sections: [
      // Section 1
      {
        code: 'section1Code',
        // Categories in section 1 of classified 1
        categories: [ // <-- Need these for section1Code/classifiedCode1 only
          // Category 1
          {
            code: 'category1Code',
            adExpiration: 'adExpiration1',
          },
          // Category 2
          {
            code: 'category2Code',
            adExpiration: 'adExpiration2',
          },
          ...
          // Category N
        ],
      },
      // Section 2
      {
        code: 'section2Code',
        // Categories in section 2 of classified 1
        categories: [ // <--  <-- Need these for section2Code/classifiedCode1 only
          // Category 1
          {
            code: 'category1Code',
            adExpiration: 'adExpiration1',
          },
          // Category 2
          {
            code: 'category2Code',
            adExpiration: 'adExpiration2',
          },
        ],
      },
      ...
      // Section N
    ],
  },

  // Classified 2
  ...
]
```

Thank you very much.

**Comment by koskimas** [comment]
Sorry, I never found time to look into this. This is a difficult problem and I don't have a clear solution for this. Using `withGraphJoined`  you should be able to manually filter those queries though.

**Comment by z1haze** [comment]
I believe I have this same issue which I opened here #2210. Did you ever figure this out? It is very unfortunate that the author completely bailed on you, hoping you found a solution and can share it with me too. Such a shame if not, this is a really neat library.

**Comment by maxkoryukov** [comment]
It is always better to provide a PR / solution

 than distributing moods like _"the library author didn't do this/that"_
 
simply because without the efforts of @koskimas (and the authors of all other libs) we would have spent x2 x3 x4 more time writing/debugging code for managing our data in the DB
 
 it is **open** and **free** software, and participation is welcome (opposed to complaints)

**Comment by z1haze** [comment]
But it does exist, and many people have chosen it for their projects.  Something can free and open-source, and still be expected to provide support. Until the repository is archived and no longer supported, opened issues should be taken seriously. If you read my comment I called out that the author just ignored this user's request to fix an issue, which I also have. If we both have the same issue, it is very likely countless others have this same issue.
