### ISSUE TITLE
$query() on $beforeUpdate()

### ISSUE THREAD

**Issue by wyllyan** [Vincit/objection.js#1635]
I need to get the old value before updating a record with patch() or update() through $beforeUpdate hook. The problem is that we can’t call $query() because the model instance id is undefined.

Is there any good solution for this situation?
Thanks.

Objection version: 1.6.11

**Comment by koskimas** [comment]
There's no easy solution on 1.x. In 2.x there's a new set of static hooks that can achieve that. See the hooks guide in the docs.
