### ISSUE TITLE
Multi-tenancy scenario support

### ISSUE THREAD

**Issue by pragmaticivan** [Vincit/objection.js#1639]
Is there a reasonable way to support multi-tenancy with a schema-based tenant?

ex, I have 3 DBS, each DB has the same table structures so it could use the same modules, but it requires 3 Knex connections, how would someone manage to kee the 3 connections and selecting the right one when using a model?

**Comment by devinivy** [comment]
There is a recipe objection docs dedicated to this problem: https://vincit.github.io/objection.js/recipes/multitenancy-using-multiple-databases.html#multitenancy-using-multiple-databases

**Comment by pragmaticivan** [comment]
Thanks @devinivy it went through the raw docs but was not familiar with the recipes section Thanks!
