### ISSUE TITLE
Default Postgres Schema definition in models

### ISSUE THREAD

**Issue by pragmaticivan** [Vincit/objection.js#1640]
Hi there, is there a way to define `withSchema` in the model so I would not need to set it when using the model somewhere?

Something like:

```
import { Model } from 'objection';

class Template extends Model {
  static get tableName() {
    return 'templates';
  }

  static get withSchema() {
    return 'ea';
  }
}
```

**Comment by koskimas** [comment]
You can override the `query` method and set it there.

**Comment by pragmaticivan** [comment]
Thanks, maybe that should become a recipe later on.
