### ISSUE TITLE
Question: Does passing a knex instance to .query() override the bound knex instance?

### ISSUE THREAD

**Issue by jdolearydl** [Vincit/objection.js#1641]
I wish to use the [Model binding pattern](https://vincit.github.io/objection.js/recipes/multitenancy-using-multiple-databases.html#model-binding-pattern) by default but to occasionally override it for a particular query with the [Knex passing pattern](https://vincit.github.io/objection.js/recipes/multitenancy-using-multiple-databases.html#knex-passing-pattern).

Based on [this](https://github.com/Vincit/objection.js/blob/master/lib/model/Model.js) line 543-547
```js
  static query(trx) {
    const query = this.QueryBuilder.forClass(this).transacting(trx);
    this.onCreateQuery(query);
    return query;
  }
```
and [this](https://github.com/Vincit/objection.js/blob/921e07b78ed8645763ef6ac4e9ec84bbfbd61337/lib/queryBuilder/QueryBuilderBase.js) line 46-49
```js
  transacting(trx) {
    this._context.knex = trx || null;
    return this;
  }
```

**I would assume that I can, indeed, override the Model binding pattern on a case-by-case basis.**

Is this correct?

**Comment by devinivy** [comment]
Correct, and this feature is frequently used as a way of running queries within transactions: https://vincit.github.io/objection.js/guide/transactions.html#passing-around-a-transaction-object
