### ISSUE TITLE
Objection.js has no collection!!

### ISSUE THREAD

**Issue by abouolia** [Vincit/objection.js#1642]
First of all i would to thank everyone maintain/develop this project, i tried to search in document about this question but there is no answer. Why this ORM tool has no collection? there are many use cases where i wanted to define custom collection, let me give you example collection of `Category` model has `buildTree` method. Thanks.

**Comment by koskimas** [comment]
Objection is also missing the left filangi!!!!

**Comment by abouolia** [comment]
Thank you for your quick response. I have `Category` model, category array should has methods such as `buildTree`, `toFlatTree`, `flattenTree` and another methods. How can possible to implement these methods to the returned array.

**Comment by koskimas** [comment]
You can extend the Array class

```js
class CategoryArray extends Array {
  buildTree() { ... }
  toFlatTree() { ... }
  flattenTree() { ... }
}
```

and do something like this:

```js
const categories = CategoryArray.from(await Categories.query().where(...))
```
