### ISSUE TITLE
upsertGraphAndFetch on .eager() without { unrelate: true } deletes root data of ref'd table

### ISSUE THREAD

**Issue by foureyedraven** [Vincit/objection.js#1645]
Hi there,

_I've read the instructions on opening issues, and because we're trying to release a product tomorrow I won't be immediately able to make a repro version of this issue. I'm sorry!_

Issue in title happens on v1.6.10 (which we are using at least til next week), as well as tested and confirmed (for me) with v2.1.2. 

In our project, we are using upsertGraphAndFetch on .eager() which, without using `{ unrelate:true }`, was deleting the root data of the `students` and `lessons` data. See usage snippet below:
**Snippet 1**
```  result = await Class.query()
    .eager('[students, lessons]')
    .upsertGraphAndFetch(
      {
        ...req.body,
        id: req.params.classId,
      },
      { relate: true }
    )
```

In req.body, we send in full original `lesson` and `student` row data. So that, if req.body shows `lessons: []`, aka empty, it will delete the lesson that was removed in the `lesson` table as well as in the `class_lesson` table. 

Relations on the models look like:
**Snippet 2**
Class.js:
```
  static get relationMappings() {
    return {
      lessons: {
        relation: BaseModel.ManyToManyRelation,
        modelClass: 'Lesson',
        join: {
          from: 'class.id',
          through: {
            from: 'classLesson.classId',
            to: 'classLesson.lessonId',
          },
          to: 'lesson.id',
        },
      },
      students: {
        relation: BaseModel.ManyToManyRelation,
        modelClass: 'Student',
        join: {
          from: 'class.id',
          through: {
            from: 'classStudent.classId',
            to: 'classStudent.studentId',
            extra: ['group'],
          },
          to: 'student.id',
        },
      },
    }
  }
```

**Snippet 3**
ClassLesson.js (just sending example of lesson, but it happens with students and lesson, which are written the same way).
```
  static get relationMappings() {
    return {
      class: {
        relation: BaseModel.HasManyRelation,
        modelClass: 'Class',
        join: {
          from: 'classLesson.classId',
          to: 'class.id',
        },
      },
      lesson: {
        relation: BaseModel.HasManyRelation,
        modelClass: 'Lesson',
        join: {
          from: 'classLesson.lessonId',
          to: 'lesson.id',
        },
      },
    }
  }
```

The deleting of important root data was prevented by adding { unrelate: true }, that is, so Snippet 1 above becomes:
**Snippet 4**
```
  result = await Class.query()
    .eager('[students, lessons]')
    .upsertGraphAndFetch(
      {
        ...req.body,
        id: req.params.classId,
      },
      { relate: true, unrelate: true }
    )
```

The reason I'm making this ticket is, from the documentation, I was under the impression that upsertGraph cannot possibly delete root data when using it on relational tables.

Please let me know if I've done something incorrectly, or if more information is needed. Also sorry if this is duplicate, I didn't see any similar issues listed.

**Comment by koskimas** [comment]
I'm sorry, but this is the kind of issue I really need the reproduction for. I have no idea how I could reproduce this. If I can't reproduce it, it's pretty difficult to fix it. So no, it's not expected that the root items get deleted in any situation. It could be linked to the `eager` call. You are not supposed to call **any** other methods with `upsertGraph` but that only produces an error in 2.0 onward.

**Comment by koskimas** [comment]
Actually this is completely expected. If you pass an empty array in `req.body.students` it will delete all students that are related to the `Class` item. Same for all other relations.

**Comment by foureyedraven** [comment]
Oh that's great to know!! Thank you @koskimas
