### ISSUE TITLE
Nested relation childs count

### ISSUE THREAD

**Issue by AbdusamadTurdiev** [Vincit/objection.js#1646]
I have a base query variable which is growing according to request params

```
let query = Client.query()
  .withGraphFetched(
    '[documents.[files], loans(onlyActiveLoansByMfo).[documents.[files]]]',
  )
  .modifiers({
    onlyActiveLoansByMfo(builder) {
      builder.whereIn('filialCode', mfos).andWhere('condition', '1')
    },
  })
```

like this

```
if (user.mfoAccesses.length !== 0 && mfos.length !== allMfos.length) {
  // Hasn't access to all mfos
  query = query.whereExists(
    Client.relatedQuery('accounts')
      .whereIn('filialCode', mfos)
      .andWhere('number', 'like', '202%')
      .andWhere(function() {
        this.where('status', 'M').orWhere('status', 'O')
      }),
  )

  const ClientDocument = require('~root/models/clientDocument')

  if (params.withStatistic) {
    statistic.clientDocumentsTotal = await ClientDocument.query().whereIn('clientCode', mfos)
    .andWhere('condition', '1').count()
    
    statistic.loanDocumentFilesTotal = await Loan.relatedQuery('documents').whereIn('filialCode', mfos)
    .andWhere('condition', '1').whereExists().count()
  }
}
```

at the end of this code I have unfinished queries where I want to get all clients (of above query) documents total amount and total amount of documents with files.

my relations schema: client has many documents and loans, documents and loans has many to many files relationship

**Comment by koskimas** [comment]
Cool, looks good.

**Comment by AbdusamadTurdiev** [comment]
> Cool, looks good.

@koskimas can help with query? I need to to count client and loan documents total and also them which have files. clients also has `hasMany` loans relation

**Comment by koskimas** [comment]
I don't understand what you are after. I can't help if you can't explain the problem better.

**Comment by AbdusamadTurdiev** [comment]
I have clients query
```
Client.query().whereExists(
    Client.relatedQuery('accounts')
      .whereIn('filialCode', mfos)
      .andWhere('number', 'like', '202%')
      .andWhere(function() {
        this.where('status', 'M').orWhere('status', 'O')
      })
```

I want to get these clients related documents without and with files total count. Not separately for each client, but the total. Same for loans which also have documents relation

**Comment by koskimas** [comment]
I still don't know if I understood, but how about this?

```js
const clientsQuery = Client.query().whereExists(
    Client.relatedQuery('accounts')
      .whereIn('filialCode', mfos)
      .andWhere('number', 'like', '202%')
      .andWhere(function() {
        this.where('status', 'M').orWhere('status', 'O')
      })
    )

statistic.loanDocumentFilesTotal = await Client.relatedQuery('documents').for(clientsQuery).count()
```

**Comment by AbdusamadTurdiev** [comment]
@koskimas oh, yes, that's exactly what is needed

**Comment by AbdusamadTurdiev** [comment]
Now I have this, but there's a problem with performance when I'm adding this condition to `relatedQuery`
```
.whereExists(ClientLoanDocument.relatedQuery('files'))
```
In the console you can see that performance degrades about 10 times

![image](https://user-images.githubusercontent.com/33511684/72724947-8201fe00-3ba6-11ea-94c3-fa4e43ed875e.png)

**Comment by AbdusamadTurdiev** [comment]
@koskimas same thing here when I'm trying to delete documents through `loansQuery` with condition.

is it possible to reduce the query completion time?

![image](https://user-images.githubusercontent.com/33511684/72893609-40ef2280-3d3b-11ea-870b-f5c0f78f5b0a.png)

**Comment by koskimas** [comment]
You probably don't have the needed indexes.
