### ISSUE TITLE
question mark postgres operator

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#1648]
Using objection@2.0.10, assuming data is jsonb and strcol is text,
`where(ref('data:myarray'), '?' ref('strcol'))`
outputs an escaped `\\?` question mark.

Available since postgres 9.4:
https://www.postgresql.org/docs/9.4/functions-json.html

But maybe there's another way to do this with objection ?
I do it using
`where(ref('data:myarray'), '@>' raw('to_jsonb(strcol)'))`
which is ugly.

See also
https://github.com/knex/knex/issues/867
which kind of question if the that kind of operator should be handled by knex at all.

**Comment by koskimas** [comment]
Objection doesn't touch the operators at all. It simply passes them to knex. This should be handled in knex.

**Comment by koskimas** [comment]
I believe you can also use this though:

```js
where(ref('data:myarray'), '@>' , ref('strcol').castJson())
```
