### ISSUE TITLE
New types in v2 have some issues with single/multiple return types, e.g. with returning("*")

### ISSUE THREAD

**Issue by lukewlms** [Vincit/objection.js#1649]
We're having some issues with typings in 2.0.  (v2.1.2 - latest)

Breaking out into multiple issues, I can log separately if needed.

1. This example from Objection's [Postgres Returning Tricks](https://vincit.github.io/objection.js/recipes/returning-tricks.html) actually is typed as returning an array - not a single object.  So this code in the official Recipe won't work.  (The recipe code may just be wrong since patch().where() seems like it could always return multiple, unless querying for 'id' is a specific case in the types that indicates singular return.)

```
const jennifer = await Person.query()
  .patch({ firstName: 'Jenn', lastName: 'Lawrence' })
  .where('id', 1234)
  .returning('*');
```

2. findOne() is typed as returning `T`, not `T | undefined`.  This means we always have to manually add `as T | undefined`, as findOne could always fail.  In TS there are things that can fail but nevertheless return only T (array indexing for example), but findOne function seems far more analagous to JS array.find() which returns `T | undefined`, as I believe findOne should.  Or, perhaps a tryFindOne function would make sense, which could return undefined.

3. I'd expect these two queries to both return single User objects:

`await User.query().patch({}).findOne({}).returning("*");`

`await User.query().findOne({}).patch({}).returning("*");`

However, the former is typed as returning a single User and the latter returns an array.  I'd suggest the latter is the more intuitive usage (find object then patch it) and should return a single User.

---

I'm sure I'm not aware of all the interactions in the types and whether the changes above are mutually compatible.  We're huge fans of Objection on our team, thanks for all your work contributing this to the JS/TS community!

**Comment by mattleff** [comment]
Issue 2. is what I reported in #1592. @koskimas said that change was intentional but it still seems wrong IMO.

**Comment by koskimas** [comment]
1 can be fixed by moving `findOne`/`findById`/`first` after `returning`. There's no way to make the typings work in every case, believe me, I've tried.

2 is an unfortunate tradeoff I had to make to implement some other features a lot of people wanted.

An insane amount of my time went to writing the new typings. You'll just have to live with the little flaws or write better typinga.

**Comment by lukewlms** [comment]
@koskimas I can appreciate that.  If these are really blocking us in the future we'll take a look at whether we can PR any tweaks.  Thanks again for your work here and quick response.

**Comment by lukewlms** [comment]
@koskimas Could it be beneficial to include tryFindOne/tryFindById methods that could return undefined?  It would be very useful for us, to skip repeated typing `T | undefined`.

Looking at the code I see it might not be simple.  This might need a definition like

`SingleOrUndefinedQueryBuilderType: QueryBuilder<M, M | undefined>;`

In which case it seems it would be a pretty significant change.

**Comment by koskimas** [comment]
You can add those methods to a custom query builder yourself. Or even override a bunch of methods to return the type you want.
