### ISSUE TITLE
Do models retain their schema name?

### ISSUE THREAD

**Issue by briancray** [Vincit/objection.js#1650]
Objection version: 2.1.2

I'm working on an app that uses the same models in different schemas. If I create a model in a schema, then within that model instance make a query, it doesn't seem to include the schema with the table in the query sql.

For example, if I create a model using something like:
`await session.$relatedQuery('scraps').withSchema(options.__withSchema).insert(session.scraps)`

Then call an instance method on that model, `session.scraps.scrape()` and within `scrape` I call `const session = await this.$relatedQuery('session')`, it doesn't search `"select from schema"."sessions"` in the sql, instead it's simple `select from "sessions"`.

Any ways about this?

**Comment by koskimas** [comment]
No they don't. There's nothing built-in for this kind of stuff.
