### ISSUE TITLE
Document clarification

### ISSUE THREAD

**Issue by peara** [Vincit/objection.js#1655]
Hi, I think there are some confusing regarding documentation.

Here is the header of the docs:
![image](https://user-images.githubusercontent.com/24425403/72782359-2131fe80-3c56-11ea-853f-e00169c0563f.png)
There is a tab named `v1.x`. But it is not clear what that means.
Although I know that objection is now on version 2, but some of my friends don't and make an assumption that objection is on version 1.x and the current docs is about version 1.x.

I think this need to be clarified.
Maybe that tab should be grouped with the `Changelog` tab and renamed to `Revisions` or `Versions` for better understanding?

**Comment by koskimas** [comment]
Feel free to provide a PR.
