### ISSUE TITLE
Removing eagerAlgorithm() in 2.x - how should I change existing algorithm in build query

### ISSUE THREAD

**Issue by jasir** [Vincit/objection.js#1656]
Hello,

after removing (deprecating) method eagerAlgorithm() - how can I change the type of eagerAlgoritm. 

My current workflow:

* `objection-builder` - builds a query for me
* to get total rows, I clone created query,  modify algorithm to join (to get real amount of rows)

Any ideas?

Thank you!

**Comment by koskimas** [comment]
Unfortunately you can't do that after once the `eagerAlgorithm` is removed in 3.0. Both eager algorithms work so differently that `eagerAlgorithm` has been a source of endless problems and bugs. It's better to explicitly use either `withGraphFetched` or `withGraphJoined` to emphasize that they do very different things and the same query may not work or make sense with both.

**Comment by koskimas** [comment]
I forgot about the `builder.graphExpressionObject()` method. You can do it like this

```js
const expr = builder.graphExpressionObject()
builder.clearWithGraph()
builder.withGraphJoined(expr) // or builder.withGraphFetched
```
