### ISSUE TITLE
Query date column in Postgres

### ISSUE THREAD

**Issue by tomw** [Vincit/objection.js#166]
What type should I pass when querying a date column in Postgres? I'm getting an "invalid input syntax for type date" error with ISO strings, YYYY-MM-DD, and Date objects, and can't see any examples in the documentation. It's working fine with Sqlite though.

**Comment by koskimas** [comment]
I'm pretty sure all of those should work. I'm certain that ISO strings work. Maybe the problem is somewhere else? Can you post the model and the query code here?

**Comment by koskimas** [comment]
https://www.postgresql.org/docs/9.1/static/datatype-datetime.html

**Comment by tomw** [comment]
Ok, got this working. I was checking that the date was within a range, and only in some cases (one out of every 1000 or so in my test data) my max date was before my min date due to a bug. The error I got back was a fairly unhelpful 'invalid date' Postgres one, and sqlite didn't seem to care, which is what threw me off track!
