### ISSUE TITLE
How to create custom serializers?

### ISSUE THREAD

**Issue by talmr** [Vincit/objection.js#1662]
Imagine I have `Post` and `User` models.

If I create a `createdByUser` relation on `Post` to get the `User` who created the `Post`, how can I only limit the fields in this relation to the `User`'s `firstName`, `lastName`, and `avatarUrl`?

In my case, I have a bunch of fields on `User` which I do not want to expose.  

Here's how I am currently doing it - I have methods on each model, so for `Post` it might be something like this so I avoid doing something I don't understand in my Model class..

```
export async function getPost(id: number): Promise<Post> {
  try {
    const res = await Post.query()
      .findById(id)
      .withGraphFetched('createdByUser');

    return serializePost(res);
  } catch (err) {
    throw newRepositoryError(err);
  }
}
```

PS: Thanks for the great project

**Comment by koskimas** [comment]
See [modifiers](https://vincit.github.io/objection.js/recipes/modifiers.html#modifiers). They might be the way to go especially if you want multiple different views. If you always want only certain set of fields, consider overriding the [$formatJson](https://vincit.github.io/objection.js/guide/hooks.html#model-data-lifecycle-hooks) method.

For what it's worth, I usually do exactly what you are doing now. That's the best way in my opinion.
