### ISSUE TITLE
fetchGraph doesn't get M2M extra properties

### ISSUE THREAD

**Issue by ChrisBates** [Vincit/objection.js#1663]
I have a model `ProductGroup` that has the following M2M relation setup:
```
productWarnings: {
      relation: Model.ManyToManyRelation,
      modelClass: ProductWarning,
      join: {
        from: 'productGroups.groupId',
        through: {
          from: 'product_group_warnings_assoc.group_id',
          to: 'product_group_warnings_assoc.warning_id',
          extras: ['warningArgs'],
        },
        to: 'productWarnings.id',
      },
    },
```

I'm using Dataloader to get the relation via:
```
const productWarningLoader = new DataLoader((group: any[]) => {
  return ProductGroup.fetchGraph(group, 'productWarnings').then(rows =>
    rows.map(product => {
      console.log(product.productWarnings);
      return product.productWarnings;
    })
  );
});
```

I'm not able to get `fetchGraph` to return the `warningArgs` extra, and note that the docs don't explicitly mention it either. I'm wondering if it's possible, or whether I need to rethink my data structure?

**Comment by koskimas** [comment]
Weird, you should be getting them. I'll see what's going on. By the way, maybe a cleaner way to get one single relation is to use `$relatedQuery`:

```js
return group.$relatedQuery('productWarnings')
```

**Comment by ChrisBates** [comment]
Will $relayedQuery deliver the same benefits as Dataloader? If so, that's less code! :)

I tried it that way too, just to see if it'd make a difference - but not go. 
```
productWarnings: async group => {
      return group.$relatedQuery('productWarnings').then(r => {
        console.log(r);
        return r;
      });
```

Returning:
```
[ ProductWarning {
    id: 4,
    title: 'Warning B',
    message:
     'This is warning B, it has [one], [two], [three] <i>shortcodes!</i>',
    args: [ [Object], [Object], [Object] ],
    type: null } ]
```

**Comment by koskimas** [comment]
You are using either`knexSnakeCaseMappers` or `snakeCaseMappers` and using the wrong casing. See [this guide](https://vincit.github.io/objection.js/recipes/snake-case-to-camel-case-conversion.html#snake-case-to-camel-case-conversion). You  probably need to use `extra: 'product_warnings'`.

**Comment by ChrisBates** [comment]
Works perfectly @koskimas - thank you very much for spotting my error.
