### ISSUE TITLE
.patch() requires id in it's object keys

### ISSUE THREAD

**Issue by soblinskas** [Vincit/objection.js#1667]
Looks like a bug to me, or is not documented, or I'm just missing something.

when I call this query (let's assume the userId variable is always valid):

`await User.query().patch(update).findById(userId);`

with update body:
`{
  email: 'Travis_Adams@hotmail.com',
  firstName: 'Lowell',
  lastName: 'McDermott',
  phone: '1-476-021-8315'
}`

it always fails:

`Error: undefined passed as a property in argument #0 for 'where' operation. Call skipUndefined() method to ignore the undefined values.`

but the same query with a body of:

`{
  email: 'Travis_Adams@hotmail.com',
  firstName: 'Lowell',
  lastName: 'McDermott',
  phone: '1-476-021-8315',
  id: 'ea276e60-4160-11ea-9fe4-eb6443e9ab55'
}`

doesn't fail. Why is it required to pass an ID field to the patch body? I already define it .findById(userId)

Note that I'm using custom validators, but I don't think they interfere here, they actually strip the id field in $beforeValidate hook.

**Comment by koskimas** [comment]
Yeah, this doesn't happen. You simply had an undefined `userId` you passed to `findById`.

**Comment by soblinskas** [comment]
These outputs are from the same integration test, so they can't be.

Here's a full output of this piece of code:
![image](https://user-images.githubusercontent.com/17228130/73266596-d7aa5c00-41df-11ea-8d21-1f10daf24beb.png)

without id in body:
![image](https://user-images.githubusercontent.com/17228130/73266553-c06b6e80-41df-11ea-8158-693bfe9399a0.png)

with id in body: no errors

**Comment by koskimas** [comment]
Objection has 4000 tests, and this case is definitely covered tens of times. The bug is in your code or in some 3rd party plugin or such. Maybe you can find the culprit if you start from a clean slate like the `reproduction_template.js` file in the repo root and try to reproduce this using it?
