### ISSUE TITLE
Extra quotes in object stringification result

### ISSUE THREAD

**Issue by C-Saunders** [Vincit/objection.js#1670]
This may actually be a Knex or other supporting library question, if so hopefully you'll be able to point me to the right place and I apologize. 

Due to JavaScript's limitations around numbers, I'd like to work with [Big.js](https://github.com/MikeMcl/big.js/) objects in my code, serialized as `bigint` and `decimal` in Postgres.

I can deserialize without any issues by following the [steps in pg-types](https://github.com/brianc/node-pg-types).

However, when I try to serialize, I get an error, like this:
```
DataError: insert into "Payment" ("id", "amount") values ($1, $2) returning "id" - invalid input syntax for type numeric: ""123.45""
```

The debug looks like this:
```
{
  method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [
    'test_id',
    Big {
      s: 1,
      e: 2,
      c: [ 1, 2, 3, 4, 5 ],
      constructor: <ref *1> [Function: Big] {
        DP: 20,
        RM: 1,
        NE: -7,
        PE: 21,
        version: '5.2.2',
        Big: [Circular *1],
        default: [Circular *1]
      }
    }
  ],
  __knexQueryUid: '04159a2f-fee2-4c02-ad4f-b0daabfcadab',
  sql: 'insert into "Payment" ("id", "amount") values (?, ?) returning "id"',
  returning: 'id'
}
```

I'm using Objection version 2.0.7.

Model:
```ts
import { Big } from 'big.js'

class Payment extends Model {
    id?: string
    amount?: Big // decimal in Postgres
}
```
Is there a way I can get this to work properly?

Thank you!

**Comment by koskimas** [comment]
This is something knex does when it sees a an object binding it doesn't recognize.

You can implement objection's`$parseDatabaseJson` and `$formatDatabaseJson` methods to do the conversions:

```js
class Payment extends Model {
    id?: string
    amount?: Big

    $parseDatabaseJson(json) {
      json = super.$parseDatabaseJson(json)
  
      if (json.amount) {
        json.amount = new Big(json.amount)
      }

      return json
    }

    $formatDatabaseJson(json) {  
      if (json.amount) {
        json.amount = json.amount.toString() 
      }

      return super.formatDatabaseJson(json)
    }
}
```
