### ISSUE TITLE
How does one type a plugin with a custom QueryBuilder?

### ISSUE THREAD

**Issue by JaneJeon** [Vincit/objection.js#1672]
So yay for objection@2 allowing `.query()` to have types even when QueryBuilder is overwritten.

However, I am completely lost as to how to follow this https://vincit.github.io/objection.js/recipes/custom-query-builder.html#extending-the-query-builder-in-typescript when writing a _plugin_.

In particular, the pain points lie in the fact that the recommended way to write plugins is to export a function that takes a model class and return a model class, but:
1. `static QueryBuilder = MyQueryBuilder;` doesn't work within a module, so `.query()` type is lost
2. having the return type of the plugin actually extend off of the input model class _and_ Objection's `Model` class (it's especially confusing when to use `Model` vs `ModelClass` in typings).

Any thoughts/tips on the "recommended" way of writing types for plugins? Thanks

For sample types, see https://github.com/JaneJeon/objection-hashid/pull/51/files

P.S. I looked in https://github.com/Vincit/objection.js/issues/625 but to no avail (these were all pertaining objection@1)

**Comment by koskimas** [comment]
Does this help https://github.com/Vincit/objection.js/blob/master/doc/recipes/plugins.md?

**Comment by JaneJeon** [comment]
Oh my god how have I not seen this xP

Thank you! @koskimas

**Comment by koskimas** [comment]
That's not actually released in the doc site yet, so that's why :slightly_smiling_face:
