### ISSUE TITLE
Strings not being stringified when used with a JSONB column on PGSQL using jsonAttributes

### ISSUE THREAD

**Issue by dinodeSimon** [Vincit/objection.js#1673]
Hi, 

We are receiving a `invalid input syntax for type json` error when inserting a string value into a JSONB column on PGSQL using `upsertGraph` with a payload like:
 `{
      jsonField: "value"
  }`

Similar to this comment here it seems that if a plain string is used as a value for a JSONB column on PGSQL an error is generated even if the property is in jsonAttributes

https://github.com/Vincit/objection.js/issues/452#issuecomment-562385393

It looks like jsonAttributes doesn't stringify the string because it isn't detected as an Object
https://github.com/Vincit/objection.js/blob/5b76a4c1e0dee70649d32b8a59383021bb5d5927/lib/model/modelJsonAttributes.js#L38

To work around this we can do something like this which works but it would be nice to know if there is a supported way or if we are missing something obvious

`$beforeInsert() {
    if (this.jsonField) {
      this.jsonField = JSON.stringify(this.jsonField);
    }
  }`

Thanks for building such an awesome orm. Let me know if you need more details or more detailed steps to repeat.

**Comment by lehni** [comment]
It looks like this was intended by @koskimas, see https://github.com/Vincit/objection.js/issues/452#issuecomment-317696066

But there is a contraction in the current behavior in the symmetry between `parseJsonAttributes()` that always parses the string value and `formatJsonAttributes()` that only formats if it's an object. 

So if you have a JSON string of a string in your DB, reading it will give you a proper JS string as expected, but storing this again will now store an invalid JSON string.

I think removing the `isObject()` check is the right thing to do, and it will allow people to store all kinds of JSON values, not just objects and arrays.
