### ISSUE TITLE
Two models referencing same table

### ISSUE THREAD

**Issue by tommymarshall** [Vincit/objection.js#1674]
**Version:** 2.1.2
**Problem:** I have a `post` table that is responsible for a number of objects in our app (posts, blog posts, messages, replies, notifications, etc.) I would like to create a class for each and have that class instantiated with a scope (i.e. `post_type == 'notification'`, `post_type == 'message'`, etc.) each with their own custom relations.

In Laravel they call it [global scopes](https://laravel.com/docs/6.x/eloquent#global-scopes), and have been going through the Objection.js documentation to see if there is something similar. The closest I found is Modifiers.

**Preferred API:**
```js
// Posts
class Post extends Model {
  static get tableName() {
    return 'posts';
  }
}

// Message
class Message extends Model {
  static get tableName() {
    return 'posts'
  }

  function globalScope(query) {
    return query.where('post_type', '=', 'message')
  }
}

// Blog
class Blog extends Model {
  static get tableName() {
    return 'posts'
  }

  function globalScope(query) {
    return query.where('post_type', '=', 'blog')
  }
}
```

**Comment by koskimas** [comment]
You should be able to override the static `query` method like this

```js
class Message extends Model {
  static get tableName() {
    return 'posts'
  }

  static query(...args) {
    return super.query(...args).where('post_type', 'message')
  }
}
```

Model instances are always created using either `fromJson` or `fromDatabaseJson` methods. You should be able to override those. Something like this

```js
class Post extends Model {
  static get tableName() {
    return 'posts';
  }

  static fromDatabaseJson(json) {
    if (json.post_type === 'message') {
      return Model.fromDatabaseJson.call(Message, json)
    } else if (json.post_type === 'blog') {
      return Model.fromDatabaseJson.call(Blog, json)
    } else {
      return Model.fromDatabaseJson.call(Post, json)
    }
  }
}
```

The `Model.fromDatabaseJson.call` trick is needed to not invoke the inherited `fromDatabaseJson` method again causing an infinite recursion. You could also pass a second argument indicating the case or whatever you can think of.

Let me know if this helps?

**Comment by tommymarshall** [comment]
Doesn't look to be working if I want to seed the DB using the same API as I would if I were simply adding `Post.query().insert()`. By that I mean, I would expect this simpler example to work:
```js
// Person.js
class Person extends Model {
  static get tableName() {
    return 'persons';
  }

  static fromDatabaseJson(json) {
    if (json.actor) {
      return Model.fromDatabaseJson.call(Actor, json)
    }

    return Model.fromDatabaseJson.call(Normal, json)
  }
}

class Normal extends Person {
  static query(...args) {
    return super.query(...args).where('actor', false);
  }
}

class Actor extends Person {
  static query(...args) {
    return super.query(...args).where('actor', true);
  }
}

// app.js
  // Delete all persons from the db.
  await Normal.query().delete();
  await Actor.query().delete();

  // Insert one row to the database.
  await Actor.query().insert({
    firstName: 'Jennifer',
    lastName: 'Aniston'
  });

  await Normal.query().insert({
    firstName: 'Tommy',
    lastName: 'Marshall'
  });

  // Read all rows from the db.
  const people = await Normal.query();
  const actors = await Actor.query();

  console.log(people);
  console.log(actors);
```

**Comment by tommymarshall** [comment]
Got it working by utilizing *$parseJson* hook, like so:

```js
class Actor extends Person {
  static query(...args) {
    return super.query(...args).where('actor', true);
  }

  $parseJson(json, opt) {
    json = super.$parseJson(json, opt);

    return {
      ...json,
      actor: true // false in my Normal person model
    };
  }
}
```

**Comment by koskimas** [comment]
`$parseJson` should work just fine. Another option is `$beforeInsert` and `$beforeUpdate`.

**Comment by tommymarshall** [comment]
Thanks so much for your help!

**Comment by wyllyan** [comment]
@koskimas Could you give an example of overriding the static query method in Typescript? Thanks.

**Comment by jhlabs** [comment]
@koskimas this is an old issue, but I tried implementing your [solution](https://github.com/Vincit/objection.js/issues/1674#issuecomment-584619332) to construct the right class. When I try to do so I inevitably get a circular inference error. I have three types of classes that extend from another base class. But if I have to reference them in the `static fromDatabaseJson(json)` method inside this base class, I will get a circular inference. How can that be solved?

**Comment by marko-x** [comment]
Hi,

if i use the model based query manipulation with

```javascript
class Post extends Pages {
  static get tableName() {
    return "page";
  }

  static query(...args) {
    return super.query(...args).where('pagetype', 'post');
  }

  static get relationMappings() {
    return {
      images: {
        relation: Model.HasManyRelation,
        modelClass: "Image",
        join: {
          from: "page.id",
          to: "image.page_id"
        }
      }
    };
  }
}
```
the insertGraph function creates a nice `post` in table `page` and the image(s) in table `images`:

```javascript
const post = await Post.query().insertGraph(
  {
    title: "A Post",
    /* ... */

    image: [
      {
        filename: "test123.jpg"
      }
    ]
  }
);
```

but the upsertGraph function creates an error.

```javascript
const post = await Post.query().upsertGraph(
  {
    id: 1234,
    title: "An edited Post title",
    /* ... */

    image: [
      {
        id: 5678,
        filename: "newfilename.jpg"
      }
    ]
  }
);
```

error: 
`upsertGraph query should contain no other query builder calls like findById, where...`

I would like to use upsertGraph in some cases with the "different models from one db table". 
Is there a solution?

Thanks.

**Comment by wwei-flux** [comment]
Curious to know if this is recognized as a pattern to handle the "multiple models sharing a table" aka. the [Single Table Inheritance](https://en.wikipedia.org/wiki/Single_Table_Inheritance) pattern. It's a relatively common pattern that several concept "models" have similar underlying data structures but different business logic, so we want them to share a DB table, but separate models to separate logic.

I hope Objection.js can recognize it as a pattern/recipe and support it. The issue reported about `upsertGraph` in the last comment is a concern of whether we should use it or not.
