### ISSUE TITLE
Missing implementation for `QueryBuilder.andWhereNot`

### ISSUE THREAD

**Issue by BjornLuG** [Vincit/objection.js#1675]
`QueryBuilder.andWhereNot` seems to be declared in the typings but is not implemented. I got an error when trying to call the function. The related lines are as below:

https://github.com/Vincit/objection.js/blob/5b76a4c1e0dee70649d32b8a59383021bb5d5927/typings/objection/index.d.ts#L814-L816

https://github.com/Vincit/objection.js/blob/5b76a4c1e0dee70649d32b8a59383021bb5d5927/lib/queryBuilder/QueryBuilderBase.js#L167-L173

Thanks for the awesome library :)

**Comment by koskimas** [comment]
Thanks for bringing this up. I'll add that asap.

**Comment by fiznool** [comment]
I also saw this today.

As a workaround I used `whereNot`, which appears to work in the same way as you'd expect `andWhereNot` to.

**Comment by koskimas** [comment]
Finally fixed. Sorry it took forever :grimacing:
