### ISSUE TITLE
Patch inconsistency with knex for empty json

### ISSUE THREAD

**Issue by ayZagen** [Vincit/objection.js#1677]
In knex passing empty json to update method throws an error while objection.js accept it as valid and returns 0 as a result.
Please have a look at following code:
```js
const Knex = require('knex');
const { Model } = require('objection');
// Initialize knex.
const knex = Knex({
  client: 'pg',
});

// Give the knex instance to objection.
Model.knex(knex);

// Person model.
class Person extends Model {
  static get tableName() {
    return 'persons';
  }
}


async function main() {

  // Throws following:
  // Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: persons. Columns: .
  await knex('persons').update({}).where({id: 'someid'})

   // returns 0
  const result1 =  await Person.query().patch({}).where({id: 'someId'});
  
  // it also returns 0 when where condition fails
  const result2=  await Person.query().patch({}).where({id: 'notExistingId'});
}

main()
  .then(() => knex.destroy())
  .catch(err => {
    console.error(err);
    return knex.destroy();
  });
```

It would be great objection.js follows knex in this situation.

Thanks

#### Environment
**NodeJS**: 12.12.0
**Objection.js**: v2.1.2
**knex.js**: v0.20.9

**Comment by koskimas** [comment]
After a lot of complaints from users, I changed the behavior to the current one.

**Comment by ayZagen** [comment]
Could you make this configurable? There is not any way without querying first to get the related data to inform the user whether the condition failed or nothing updated. I believe that's why knex devs throws that error.
