### ISSUE TITLE
Insert request fails if `length` field is present

### ISSUE THREAD

**Issue by tsabolov** [Vincit/objection.js#168]
Hi there. I have spent more than hour trying to realize why does my insert query fail.
It turned out that presence of a `length` field in the insert data, causes a request to fail. I guess that somewhere in the code (sorry, I didn't search it myself) there is a passing of `arguments`. Or maybe check for array by testing argument's `length` property.
Anyway, the issue gone, once I renamed the field into `size`.

**Comment by koskimas** [comment]
Weird. I'll check this out today.

**Comment by koskimas** [comment]
The bug/feature is in lodash `each` method:

```js
_.each({length: 10}, (v, k) => console.log(v, k))
undefined 0
undefined 1
undefined 2
undefined 3
undefined 4
undefined 5
undefined 6
undefined 7
undefined 8
undefined 9
```

Supporting the `length` column in all situations means getting rid of the `_.each` method everywhere + writing tens of tests. The fix won't come soon I'm afraid.

**Comment by tsabolov** [comment]
Yes, you're right. It seems they have a solution — https://github.com/lodash/lodash/issues/339#issuecomment-23714704

**Comment by koskimas** [comment]
I didn't know about `_.forOwn` function. I can probably just change all my `_.each` calls to `.forOwn`. Maybe the fix is easier than I thought.
