### ISSUE TITLE
patch against oneOf->not->required jsonSchema fails

### ISSUE THREAD

**Issue by villesau** [Vincit/objection.js#1681]
Hi,

patch operation against following schema fails (obfuscated from real world usage):

```
{
        oneOf: [
          {
            required: ['a'],
            not: { required: ['c'] }
          },
          {
            required: ['b']
          },
          { required: ['a', 'c'] }
        ],

        properties: {
          a: { type: 'string' },
          b: { type: 'number' },
          c: { type: 'string' },
          d: { type: 'string' }
        }
      }
```

Minimun repro:

```
{
        oneOf: [
          {
            not: { required: ['a'] }
          }
        ],
        properties: {
          a: { type: 'string' },
          b: { type: 'string' }
        }
      }
```

The `jsonSchemaWithoutRequired` produces following jsonSchema which seems to be invalid:

```
{
  "properties": {
    "a": {
      "type": "string"
    },
    "b": {
      "type": "string"
    }
  },
  "oneOf": [
    {
      "not": {}
    }
  ]
}
```

I believe that the whole `oneOf` should be ripped off in this case since `not` is empty.

**Comment by koskimas** [comment]
Please read the instructions on how to open issues. How does it fail? For what data? With what kind model? Which objetion version? Stack traces? And by the way, a reprodution is a script that reproduces the bug by simply executing it.

**Comment by villesau** [comment]
@koskimas no need to be so heated up. See the pull request, it provides a test case for it: https://github.com/Vincit/objection.js/pull/1682
