### ISSUE TITLE
Validation errors thrown with upsertGraph/insertGraph doesn't stop the relations from being updated

### ISSUE THREAD

**Issue by JReinhold** [Vincit/objection.js#1686]
# The use case

Say we have tables with a ManyToMany relationship, through a join table:
`sales_announcement <--> sales_announcement_customer_node <--> customer_node`

### Migration
```typescript
knex.schema
    .createTable('sales_announcement', (table) => {
      table.integer('id').primary();
      table.string('header');
    })
    .createTable('customer_node', (table) => {
      table.integer('id').primary();
      table.string('description');
    })
    .createTable('sales_announcement_customer_node', (table) => {
      table
        .integer('sales_announcement_id')
        .references('id')
        .inTable('sales_announcement');
      table
        .integer('customer_node_id')
        .references('id')
        .inTable('customer_node');
      table.primary(['sales_announcement_id', 'customer_node_id']);
    });
```

### Sales Announcement Model
```typescript
export class SalesAnnouncement extends Model {
  readonly id!: number;
  header!: string;

  customers?: Customer[];

  static readonly tableName = 'salesAnnouncement';

  static readonly jsonSchema = {
    type: 'object',
    required: ['header'],

    properties: {
      id: { type: 'integer' },
      header: { type: 'string' },
    },
  };

  static readonly relationMappings = {
    customers: {
      relation: Model.ManyToManyRelation,
      modelClass: CustomerNode,
      join: {
        from: 'salesAnnouncement.id',
        through: {
          from: 'salesAnnouncementCustomerNode.salesAnnouncementId',
          to: 'salesAnnouncementCustomerNode.customerNodeId',
        },
        to: 'customerNode.id',
      },
    },
  };
}
```

### Customer Node Model
```typescript
export class Customer extends Model {
  readonly id!: number;
  description!: string;

  static readonly tableName = 'customerNode';

  static readonly jsonSchema = {
    type: 'object',
    required: ['description'],

    properties: {
      id: { type: 'integer' },
      description: { type: 'string', minLength: 1, maxLength: 255 },
    },
  };

  static readonly relationMappings = {
    salesAnnouncements: {
      relation: Model.ManyToManyRelation,
      modelClass: 'SalesAnnouncement',
      join: {
        from: 'customerNode.id',
        through: {
          from: 'salesAnnouncementCustomerNode.customerNodeId',
          to: 'salesAnnouncementCustomerNode.salesAnnouncementId',
        },
        to: 'salesAnnouncement.id',
      },
    },
  };
}
```

Now, I want to validate, that whenever we insert or update a Sales Announcement using **insertGraph or upsertGraph**, its related Customer Nodes MUST have a `description` that starts with `"SA Customer"`.

I've tried multiple solutions, but none of them work, with the fundamental issue being that **validation errors thrown in one of the models, doesn't stop the other model from being inserted/updated**.

Examples of queries we want to validate:
```typescript
// insert new
await SalesAnnouncement.query(transaction).insertGraph(
      { header: 'hi', customers: [ {id: existingCustomer.id} ] },
      { relate: true }
    );

// update existing
await SalesAnnouncement.query(transaction).upsertGraph(
      { id: someId, customers: [ {id: existingCustomer.id } ] },
      { relate: true, unrelate: true, noDelete: true }
    );
```

## Solution 1 - `$beforeValidate` in `SalesAnnouncement`

This is not possible, as `before/afterValidate` doesn't get passed the related fields, so there is no way to assert that they are valid.

## Solution 2 - Define model for the join table and add `$beforeValidate`

We could define a model class for the join table, and reference that in our `through` relationMapping:

```typescript
export class SalesAnnouncementCustomerNode extends Model {
  readonly salesAnnouncementId!: number;
  readonly customerNodeId!: number;

  idColumn = ['salesAnnouncementId', 'customerNodeId'];
  static readonly tableName = 'salesAnnouncementCustomerNode';

  ...$beforeValidate here
}


... in SalesAnnouncement model
  static readonly relationMappings = {
    salesAnnouncements: {
      relation: Model.ManyToManyRelation,
      modelClass: 'SalesAnnouncement',
      join: {
        from: 'customerNode.id',
        through: {
          modelClass: SalesAnnouncementCustomerNode
          from: 'salesAnnouncementCustomerNode.customerNodeId',
          to: 'salesAnnouncementCustomerNode.salesAnnouncementId',
        },
        to: 'salesAnnouncement.id',
      },
    },
  };
```

Here, we can use the `customerNodeId` to validate that the customer is allowed. However, if we throw an error in the join model, the **actual SalesAnnouncement model will still be created, but without any customer relations**. (And maybe the error is even swallowed, and doesn't get passed to the initial `insertGraph` call, I haven't quite figured that out yet).

## Solution 3 - `$beforeInsert/Update` in `SalesAnnouncement`

We can actually run validation on the relations in `$beforeInsert/Update`, and throw to cancel the operation. However, throwing here **will not prevent the relations from being updated/inserted**, ie. the `customers` will STILL update even if the `$beforeUpdate` throws.

## Solution 4 - rollback transaction when validation fails

**this COULD be a good workaround**

So, instead of just throwing in `$beforeInsert`, we ALSO rollback the transaction from the `queryContext` parameter. I haven't actually tried this solution yet, but I expect it should work, as long as all the related inserts and updates are running in the same transaction. I'm not entirely comfortable using this solution though, as I believe transaction rollbacks/commits should be handled by the caller, and not the models being queried (but maybe I'm wrong).

## Solution 5 - validating data before ever calling the query

**this is a viable workaround**

This is the "nuclear" option and should work. Basically, we create our own function `upsertSalesAnnouncementGraph`, that validates the parameters, and doesn't even call the query if the input is invalid.

# Expected result

I can understand, that `insertGraph` and `upsertGraph` are not atomic (as mentioned in the documentation), but I still expected that the relations would not even be created/updated, if the base model was invalid.

A simple answer could be "don't expect that", and that's it. Then we can just close this, and keep it for others to reference.

**Comment by koskimas** [comment]
> validation errors thrown in one of the models, doesn't stop the other model from being inserted/updated.

The operations are done in parallel for speed. You need to use a transaction to achieve atomicity.

**Comment by JReinhold** [comment]
> The thrown validation exception will cause the transaction to be rolled back.

That's not my experience. I use transactions everywhere (as seen in the examples), and the issue still occurs. Unless I'm misunderstanding transactions, I shouldn't even be able to reuse a rolled back transaction later, which I am currently. This leads me to believe that the transaction is not rolled back.
