### ISSUE TITLE
typescript error when trying to `patch` a column with a null value

### ISSUE THREAD

**Issue by zig** [Vincit/objection.js#1690]
When doing the following query :
```js
Session.query().findById(s.id).patch({ name: null });
```
I get the following typescript error : 
`[0] server/src/sessions.ts(180,62): error TS2322: Type 'unknown' is not assignable to type 'string | RawBuilder | Raw<any> | ReferenceBuilder | AnyQueryBuilder | ValueBuilder | undefined'.
`
I have to either use `raw('null')` or force the type like this : `null as unknown as string`.  Is that intentional ?

(objection 2.1.2)

**Comment by koskimas** [comment]
If that value can be null, the type for that field should also be nullable. Simply update your typings for that field.

**Comment by zig** [comment]
> If that value can be null, the type for that field should also be nullable. Simply update your typings for that field.

indeed, I completely forgot the type taken by patch was deduced from my Session type. Sorry about that :)
