### ISSUE TITLE
One-To-Many relation issue

### ISSUE THREAD

**Issue by smubarak-ali** [Vincit/objection.js#1691]
Hi there, 
First of all, this is an awesome library :)

The problem that I am facing now is that I am not getting the one-to-many relation data correctly and I know that I must be doing something wrong here, can some point out what I am doing wrong here. I have a Content table which have a many-to-many relation with ContentMusic via a link table music_in_content, also Content has a one-to-many relation with ContentImage table but I am not able to fetch the data for this ContentImage relation. 

Below is my schema diagram:

![image](https://user-images.githubusercontent.com/11365385/74668754-d7025580-51e0-11ea-9256-0a5845b1e546.png)

Below is my code:
```
export class ContentMusic extends Model {
    public readonly id: number;
    public musicType: "express"|"spectral"|"space";
    public musicFileUrl: string;

    public contents: Content[];

    public static tableName = "content_music";
    public static relationMappings: RelationMappings = {
        contents: {
            relation: Model.ManyToManyRelation,
            modelClass: join(__dirname, "Content"),
            join: {
                from: "content_music.id",
                through: {
                    from: "music_in_content.content_music_id",
                    to: "music_in_content.content_id",
                },
                to: "content.id",
            },
        },
    }
}

export class ContentImage extends Model {
    public readonly id: number;
    public contentId: number;
    public contentRefId: number;
    public image: string;

    public content?: Content;

    public static tableName = "content_images";
    public static relationMappings: RelationMappings = {
        content: {
            relation: Model.BelongsToOneRelation,
            modelClass: join(__dirname, "Content"),
            join: {
                from: "content_images.content_id",
                to: "content.id",
            },
        },
    }
}

export class Content extends Model {
    public readonly id: number;
    public category: "fiveSteps"|"music"|"empowerment"|"advance";
    public refId: number;
    public title: string;
    public content: string;
    public infoMessage: string;

    public music?: ContentMusic[];
    public images?: ContentImage[];

    public static tableName = "content";
    public static modelPaths = [__dirname]
    public static relationMappings: RelationMappings = {
        music: {
            relation: Model.ManyToManyRelation,
            modelClass: "ContentMusic",
            join: {
                from: "content.id",
                through: {
                    from: "music_in_content.content_id",
                    to: "music_in_content.content_music_id",
                },
                to: "content_music.id",
            },
        },
        images: {
            relation: Model.HasManyRelation,
            modelClass: "ContentImage",
            join: {
                from: "content.id",
                to: "content_images.content_id",
            },
        },
    }
}
```
The query is as follows:
```
const content = await Content.query()
     .eager("[images, music]")
     .where("category", "=", category).debug();
return content;
```

The result is coming out as follows:

![image](https://user-images.githubusercontent.com/11365385/74668637-9571aa80-51e0-11ea-903b-7452fbfbdb71.png)

I have scanned the documentation and couldn't figure out the problem. The music relation is loading fine as it a many-to-many relationship.

I am using the latest version of the library and peer dependency
![image](https://user-images.githubusercontent.com/11365385/74668865-0b761180-51e1-11ea-9e8d-efe0ccb1da28.png)

Any help would be highly appreciated.
Thanks in advance :)

**Comment by koskimas** [comment]
Everything seems to be correct in what you posted here...

**Comment by smubarak-ali** [comment]
> Everything seems to be correct in what you posted here...

Hi @koskimas, thank you for response. In this case, I will give it one more try and if still not working then I will push it to github, maybe you can have a look at it, if not too much trouble off course :)

**Comment by smubarak-ali** [comment]
Hi @koskimas, I have uploaded the project, when you get some time, please clone it and check
https://github.com/smubarak-ali/objection-1-m-issue

Appreciate all your help.

**Comment by koskimas** [comment]
You are using `knexSnakeCaseMappers` and therefore need to define **everything** in `camelCase` instead of `snake_case` as explained in the docs. So for example instead of the current mappings, you need to write:

```ts
    public static relationMappings: RelationMappings = {
        music: {
            relation: Model.ManyToManyRelation,
            modelClass: "ContentMusic",
            join: {
                from: "content.id",
                through: {
                    from: "musicInContent.contentId",
                    to: "musicInContent.contentMusicId",
                },
                to: "contentMusic.id",
            },
        },
        images: {
            relation: Model.HasManyRelation,
            modelClass: "ContentImage",
            join: {
                from: "content.id",
                to: "contentImages.contentId",
            },
        },
    }
```

**Comment by smubarak-ali** [comment]
Hi @koskimas 
Thanks a million 👍 
Problem is solved!

**Comment by neriosoft** [comment]
I do I implement one-to-one, one-to-many and many-to-many differently in objectionjs please

**Comment by neriosoft** [comment]
How I do I implement one-to-one, one-to-many and many-to-many differently in objectionjs please
