### ISSUE TITLE
help - parsing a structure for generating a tree with nested elements

### ISSUE THREAD

**Issue by colzeri** [Vincit/objection.js#1692]
Let's say I have the following structure in my db:

**b_hierarchy** table - describes how the elements are related to each other within a tree structure. specifically:

- level1 (parent = level1-element-id, child=level1-element-id && last_tree_level_flag = false)
- level2 (parent = level1-element-id, child = level2-element-id && last_tree_level_flag = false)
- level3 (parent = level2-element-id, child = level3-element-id && last_tree_level_flag = true)
- etc if more levels are required
(the relationship between parent and children is many to many)

**b_hierarchy_element** table - describes all elements that are part of the trees

**banking_product** table - describes all the products and each product has a relationship to b_hierarchy (_many banking products to one hierarchy_). This relationship is linked to the last level of the tree (e.g. level3 row for the above example)

and now I would like to use objection to get a JSON in this format:
```

{
    level1_id: '1',
   ...,
    level2: [
      {
        level2_id:'2',
        ...,
        level3: [
          {
            level3_id: '3',
            ...,
            banking-products: [
                {
                     banking_product_id: 4
                },
                {
                     banking_product_id: 5
                },
            ]
          }
        ]
      }
    ]
 }


```
**Could you help to do this?** the depth of the tree should be dynamic and in the JSON there should be only tree from father to final child and not all combinations.

see below my previous implementation (which is NOT fully working as I want as it is not dynamically recursive and the output is not clean - I get all combination of trees):
```
const getStructuredBankingProducts = async (req, res, next) => {
  try {
    const structuredBankingProducts = await BHierarchyElement.query().withGraphJoined(
      "[children as L2 .[banking_products, children as L3 .[banking_products]]]"
    );
    res.status(200).send(structuredBankingProducts);
  } catch (error) {
    next(error);
  }
};
```
where, in b_hierarchy_element I describe the following relationships:
```
static get relationMappings() {
    return {
      children: {
        relation: Model.ManyToManyRelation,
        modelClass: __dirname + "/b_hierarchy_element",
        join: {
          from: "b_hierarchy_element.uuid",
          through: {
            from: "b_hierarchy.b_hierarchy_element_uuid_parent",
            to: "b_hierarchy.b_hierarchy_element_uuid_child"
          },
          to: "b_hierarchy_element.uuid"
        }
      },
      banking_products: {
        relation: Model.ManyToManyRelation,
        modelClass: __dirname + "/banking_product",
        join: {
          from: "b_hierarchy_element.uuid",
          through: {
            from: "b_hierarchy.b_hierarchy_element_uuid_child",
            to: "b_hierarchy.uuid"
          },
          to: "banking_product.b_hierarchy_uuid"
        }
      }
    };
  }
```

see below schema declaration:
```
knex.schema.createTable("b_hierarchy_element", table => {
      table.increments("uuid").primary();
      table
        .string("name_short")
        .unique()
        .notNullable();
      table.string("name_long");
      table.string("description");
    })
```

```
knex.schema.createTable("b_hierarchy", table => {
      table.increments("uuid").primary();
      table.integer("b_hierarchy_element_uuid_parent"); //foreign key
      table.integer("b_hierarchy_element_uuid_child"); //foreign key
      table.unique([
        "b_hierarchy_element_uuid_parent",
        "b_hierarchy_element_uuid_child"
      ]); //composite key
      table.integer("b_hierarchy_level_type_uuid"); //foreign key
      table.string("tree_level");
      table.boolean("last_tree_level_flag");
    })

```

**Comment by koskimas** [comment]
There doesn't seem to be anyone willing to answer this. You can try asking this in objection gitter.
