### ISSUE TITLE
Filtering relations by a target's relation attribute

### ISSUE THREAD

**Issue by andrucz** [Vincit/objection.js#1693]
I have the following entities:

**Users**
- id: UUID
- name: string

_enum_ **GroupType** = _TEAM_ | _DEPARTMENT_ | _REGION_

**Groups**
- id: UUID
- name: string
- type: GroupType

**GroupMembers**
- userId: UUID
- groupId: UUID

How can I add a relation mapping in the User model class that loads the memberships to groups that are teams?

The _User_ has many _GroupMembers_, which has one _Group_, which has a type that can be _TEAM_.

**Comment by koskimas** [comment]
Like this:

```js
class User extends Model {
  static relationMappings = {
    teams: {
      relation: Model.ManyToManyRelation,
      modelClass: Group,
      modify: query => query.where('type', 'TEAM')
      join: {
        from: 'users.id',
        through: {
          from: 'group_members.userId',
          to: 'group_members.groupId'
        },
        to: 'groups.id'
      }
    }
  }
}
```

**Comment by andrucz** [comment]
Thanks for the prompt response @koskimas 

I'm trying to create a relation mapping to `GroupMembers,` not `Groups.` I forgot to mention that `GroupMembers` has some additional fields that I have to load, such as the role of the member in the group.

This is the solution I've come up with:
```
{
  relation: Model.HasManyRelation,
  modelClass: `${__dirname}/group-member.model`,
  join: {
    from: 'group_members.userId',
    to: 'users.id',
  },
  filter: (builder: QueryBuilder<GroupMemberModel>) =>
    builder.joinRelation('group').where('group.type', GroupType.Team),
  },
}
```

I don't know if it's the best, though.
