### ISSUE TITLE
not all related rows are included in eager query with many-to-many relation

### ISSUE THREAD

**Issue by GGAlanSmithee** [Vincit/objection.js#1695]
I have classes `A` and `B` that are joined via the many-to-many relation `AB`:
```ts
import { Model } from 'objection'

class B extends Model {
    id: undefined
}

class A extends Model {
    id: undefined

    listOfBs: {
            relation: Model.ManyToManyRelation,
            modelClass: B,
            join: {
                from: 'bs.id',
                through: {
                    from: 'abs.bId',
                    to: 'abs.aId',
                },
                to: 'as.id',
            },
        },
}
```
These are seeded with the folloing data
```ts
const as = [ { id: 1, }, { id: 2, }, { id: 3, }, { id: 4, }, ]
const bs = [ { id: 1, }, { id: 2, } ]
const abs = [
    { id: 1, aId: 1, bId: 1, },
    { id: 2, aId: 1, bId: 2, },
    { id: 3, aId: 2, bId: 1, },
    { id: 4, aId: 2, bId: 2, },
    { id: 5, aId: 3, bId: 1, },
    { id: 6, aId: 3, bId: 2, },
    { id: 7, aId: 4, bId: 1, },
    { id: 8, aId: 4, bId: 2, },
]
```

Notice that I have seeded a total of 8 many-to-many relations, that is 2 `B`s for each `A`. This get seeded properly to the database and works as expected when querying it, that is
```sql
select * from as inner join abs on as.id=abs.aId
```

will retreive 8 rows of `A/AB` pairs.

However, when querying this using Objection (and I guess in extension knex) it will _**only retreive relations for as many records of `B`s there is**_. So, the query
```ts
A.query().select('*').eager('listOfBs')
```
will get all 4 records of `A` but only only include `listOfBs` for as many `B`'s there are, in this case 2. This doesn't make sense since even if there are only 2 B's, there are still 8 ABrelations. I have no idea why this behavior is, if there is a improper constraint being set, but judging by the behavior it does not look like it, it just does not make sense.

Not sure how to provide a reproduction of this but please let me know if you need additional info or if what I'm saying doesn't make sense.

Thanks in advance, BR Jesper

**Comment by koskimas** [comment]
This is completely expected and correct behaviour. Each A should have two B instances in the result.

**Comment by GGAlanSmithee** [comment]
> This is completely expected and correct behaviour. Each A should have two B instances in the result.

Thanks for your answer. I'm sorry If I was unclear, but that is **not** the result I'm getting. The result I am getting is:

```ts
// list of A's with B's joined via AB
[
	{ id:1, listOfBs: [{ id: 1, id: 2 }], },
	{ id:2, listOfBs: [{ id: 1, id: 2 }], },
	{ id:3, listOfBs: [], },
	{ id:4, listOfBs: [], },
	{ id:5, listOfBs: [], },
	{ id:6, listOfBs: [], },
]

```

So, as you can see I only get joined results for as many B's there are. If there were three B's, three record of A's would have gotten their relations populated.

**Comment by GGAlanSmithee** [comment]
@koskimas I hope the above clarfication better shows the problem

**Comment by koskimas** [comment]
Ok, there's something wrong with your setup. Without any actual code, there's no way for me to know what.

**Comment by GGAlanSmithee** [comment]
Yeah, I understand, I'll try to put up a reproduction, thanks for interest and time

**Comment by GGAlanSmithee** [comment]
@koskimas I created a simplified reproduction, and it works as expected. The code is directly taken from the actual webapp so it's weird, but def. not related to objection - it's a user-error :) Thanks for your help!

**Comment by GGAlanSmithee** [comment]
@koskimas and future googlers, I found out the error, I had inverted the relationmapping

## Wrong

```ts
class B extends Model {
    id: undefined
}

class A extends Model {
    id: undefined

    listOfBs: {
            relation: Model.ManyToManyRelation,
            modelClass: B,
            join: {
                from: 'bs.id',
                through: {
                    from: 'abs.bId',
                    to: 'abs.aId',
                },
                to: 'as.id',
            },
        },
}
```

## Correct

```ts
class B extends Model {
    id: undefined
}

class A extends Model {
    id: undefined

    listOfBs: {
            relation: Model.ManyToManyRelation,
            modelClass: B,
            join: {
                from: 'as.id',
                through: {
                    from: 'abs.aId',
                    to: 'abs.bId',
                },
                to: 'bs.id',
            },
        },
}
```

Given this, the behavior kind of make sense, since it mapped as many rows as it could find.
