### ISSUE TITLE
QueryBuilderOperation in plugin development

### ISSUE THREAD

**Issue by olavim** [Vincit/objection.js#1697]
I've been developing [objection-cursor](https://github.com/olavim/objection-cursor) and recently wanted to start tidying up the code. Since the plugin introduces new, relatively complex query building methods, the query builder class has grown to the point where I want to start splitting it up into smaller pieces.

Initially I just split the functionality of the new methods to their own classes.  Although this enabled me to encapsulate the functionality a little bit better, the result was a class hierarchy I disliked very much (`CursorQueryBuilder extends OrderQueryBuilder extends ContextBase extends QueryBuilder`).

I came upon [operations](https://github.com/Vincit/objection.js/tree/master/lib/queryBuilder/operations) while going through Objection's native way of doing it, and [gave it a shot](https://github.com/olavim/objection-cursor/tree/operation-refactor/lib/query-builder/operations) myself. I liked this solution a lot, but I wanted to make sure operations are meant for "public consumption" before going through with my refactors. Operations haven't been documented (in API docs) AFAIK, but it looks like they have existed at least since v0.9.4.

If operations are meant to be exposed, I would also like to request documentation for them.

**Comment by koskimas** [comment]
Unfortunately the operation API is private and I still significantly change it from time to time. Everything not documented is considered private.
