### ISSUE TITLE
havingNull and friends should be declared as WhereNullMethod

### ISSUE THREAD

**Issue by IlyaSemenov** [Vincit/objection.js#1699]
Shouldn't `havingNull` and friends be declared as `WhereNullMethod` not `WhereMethod `?

https://github.com/Vincit/objection.js/blob/9a7f89c4ed7922af087bbfc94ccde4eb983dff4b/typings/objection/index.d.ts#L884-L887

Currently, this code doesn't compile with typing errors:

```ts
MyModel.query().havingNull('foo')
```

Same issue for other having methods, they should be declared as `WhereInMethod`, `WhereExistsMethod`, etc.

**Comment by koskimas** [comment]
Yep, you are absolutely right. Thanks for bringing this up! I'll fix those in the next release.

**Comment by koskimas** [comment]
Sorry it took me forever to fix this. Thank you for bringing this up.
