### ISSUE TITLE
Cookbook example how to create index and use json fields

### ISSUE THREAD

**Issue by elhigu** [Vincit/objection.js#17]
The same query example + link to field expression syntax could be added also to `readme.md`

**Comment by koskimas** [comment]
Is this going to happen some day or can I close it?

**Comment by elhigu** [comment]
I can do it. I have those queries and info already in the old blog post about postgres jsonb stuff. Just need to write them down here.

**Comment by elhigu** [comment]
https://github.com/Vincit/objection.js/pull/347

**Comment by koskimas** [comment]
Merged
