### ISSUE TITLE
JSON Querying for specific string attribute

### ISSUE THREAD

**Issue by makeitrein** [Vincit/objection.js#170]
Hey all - playing around with the express-es7 example and am trying to come up with a query method to find Persons by a specific zip code. I've read through the API methods that relate to JSON queries, and I came up with Person.query().whereJsonSupersetOf('address:zipCode', '95066'), but that got me this error:  SQLITE_ERROR: unrecognized token: "#"] errno: 1, code: 'SQLITE_ERROR' }

What's the right way to call it?

For reference, here is the JSON validation for the Person model.

  static jsonSchema = {
    type: 'object',
    required: ['firstName', 'lastName'],

    properties: {
      id: {type: 'integer'},
      parentId: {type: ['integer', 'null']},
      firstName: {type: 'string', minLength: 1, maxLength: 255},
      lastName: {type: 'string', minLength: 1, maxLength: 255},
      age: {type: 'number'},

      address: {
        type: 'object',
        properties: {
          street: {type: 'string'},
          city: {type: 'string'},
          zipCode: {type: 'string'}
        }
      }
    }
  };

**Comment by koskimas** [comment]
Json operations only work on postgresql. I'll make this more clear in the docs and add a descriptive error message when used on other databases.
