### ISSUE TITLE
Incorrect typing when using `deleteById()` + `returning()`

### ISSUE THREAD

**Issue by jsonmaur** [Vincit/objection.js#1700]
Consider the following:
```js
const result = await SomeModel()
  .deleteById(req.params.id)
  .returning("*")
```

The type of `result` in this case should be `SomeModel`. However, the current typings define the type as `SomeModel[]`.

**Comment by elhigu** [comment]
Does this work better for you:
```
const result = await SomeModel()
  .returning("*")
  .deleteById(req.params.id)
```

**Comment by koskimas** [comment]
@elhigu's solution is the easiest fix. Fixing the typings to work in all possible combinations is impossible without huge changes.

**Comment by jsonmaur** [comment]
With @elhigu's method, Typescript expects the result to be a number, since `deleteById` returns a deleted count by default. However, I was able to get around it with this:

```js
const [result] = await SomeModel.query()
  .delete()
  .where("id", req.params.id)
  .returning("*")
```

Thanks for the quick response!
