### ISSUE TITLE
How to apply where filter to eager loading

### ISSUE THREAD

**Issue by MrScX** [Vincit/objection.js#1701]
So I have two tables:

User
u_id | first_name

User_Friend
u_id | friend_id

Now I wish to search for a user's friends by their first name. 

Below is a relation I defined in the UserFriend model:

```
static get relationMappings() {

        return {

            friend: {
                relation: Model.BelongsToOneRelation,
                modelClass: User,
                join: {
                    from: "users.u_id",
                    to: "user_friends.friend_id"
                }
            },
        }
    }
```
Code for fetching all friends of a user:

const friends = await UserFriends.query().eager("friend").where({ u_id: 2 });

How can I apply a filter here that will get me, friends of u_id = 2, by their first name?

**Comment by C-Saunders** [comment]
It looks like [eager](https://vincit.github.io/objection.js/api/query-builder/eager-methods.html#eager) is deprecated, so you might want to try one of the [withGraph](https://vincit.github.io/objection.js/api/query-builder/eager-methods.html#withgraphfetched) methods instead.

I think you should be able to use [modifyGraph](https://vincit.github.io/objection.js/api/query-builder/eager-methods.html#modifygraph) to do the filtering you're describing once the models and relationships are in order.

It looks like you are missing the Friend model from your example, so I am going to assume it exists. This seems like a [many to many relation](https://vincit.github.io/objection.js/guide/relations.html), so you will want to define the "through" relation to make this work.

```js
const friends = await User
  .query()
  .withGraphFetched('friends')
  .modifyGraph('friends', builder => {
    builder.where('name', 'ilike', ...);
  })
```
