### ISSUE TITLE
Extending base model and query builder together

### ISSUE THREAD

**Issue by leeallen337** [Vincit/objection.js#1702]
Hi,

Currently using Objection for a production project and loving it so far. I have an issue I'm running into and I'm not sure if I'm thinking about it the correct way. I'll post some code with some questions below:

```javascript
// BaseModel.js
import { Model, QueryBuilder } from 'objection';

class BaseQueries extends QueryBuilder {
  someQuery() {
    // do stuff
  }
}

class BaseModel extends Model {
  static get QueryBuilder() {
    return BaseQueries;
  }
}

export default BaseModel;

// User.js
import { QueryBuilder } from 'objection';
import BaseModel from './BaseModel';

class UserQueries extends QueryBuilder {
  doSomeUserQuery() {
    return this.someQuery(); // this is from the base model/querybuilder
  }
}

class User extends BaseModel {
  static get QueryBuilder() {
    return UserQueries;
  }
}

export default User;
```

When attempting to perform `User.query().doSomeAQuery()` it gives me an error about `someQuery` not being a function. This makes sense to me since I'm extending `QueryBuilder` in `UserQueries` but I was thinking that some how when extending the base model the custom queries would inherit as well?

The reason I want this is there are one or two queries that I want to be available to all models but still be able for each model to have their own custom queries defined.

Is the correct way to do this like below and extend the `BaseModel` and `BaseQueries` separately and combine them in the `User` model?

```javascript
// BaseModel.js
import { Model, QueryBuilder } from 'objection';

class BaseQueries extends QueryBuilder {
  someQuery() {
    // do stuff
  }
}

class BaseModel extends Model {
  // no longer needed?
  // static get QueryBuilder() {
  //   return BaseQueries;
  // }
}

export { BaseModel, BaseQueries };

// ModelA.js
import { BaseModel, BaseQueries } from './BaseModel';

class UserQueries extends BaseQueries {
  doSomeAQuery() {
    return this.someQuery(); // this is from the base model/querybuilder
  }
}

class User extends BaseModel {
  static get QueryBuilder() {
    return UserQueries;
  }
}

export default User;
```

Is there any way to do it under my initial assumption or is my proposed solution the correct way to go about accomplishing this? It would be nice to be able to access the `BaseModel`s custom queries inside the custom queries on the `User` model but if that's not possible that's okay.

Thanks!

**Comment by koskimas** [comment]
The way you are doing it is correct. There's no way around that because we are using javascript's class inheritance and nothing more. You can do this though

```js
class UserQueries extends BaseModel.QueryBuilder {
  ...
}
```

which removes the need to export BaseQueries.
