### ISSUE TITLE
HasManyRelation where key can be one of

### ISSUE THREAD

**Issue by Yooooomi** [Vincit/objection.js#1709]
Hello, thanks for your project !

I am building a bet application where `Teams` play matches. I then have HasManyRelation from `Teams` to `Matches`.

In the `Matches` table, the team can be the `local` team or the `guest` team.
When retrieving a Team, I would like to have all the matches under the `matches` field of the Team.

I tested few things so far:

Merging them using the eager loading feature
```
 Team.query()
    .findById(id)
    .withGraphFetched('[locals(order) as matches .[local, guest], guests(order) as matches .[local, guest]]')

```
Resulting in `matches` being only guest matches.

Trying to tell Objection that the key can be one of
```
class Team extends Model {
  static get tableName() {
    return 'teams';
  }

  static get relationMappings() {
    return {
      locals: {
        relation: Model.HasManyRelation,
        modelClass: Match,
        join: {
          from: ['teams.id'],
          to: ['matches.local_team_id', 'matches.guest_team_id'],
        }
      }
    };
  }
}
```
Resulting in crashing the request

I didn't find anything about this case in the documentation, is this even possible with "native" Objection or I have to merge them manually after the request ?

Thanks

**Comment by koskimas** [comment]
Unfortunately there's no way to do this using a single relation.
