### ISSUE TITLE
$beforeDelete hook not getting called

### ISSUE THREAD

**Issue by ehubbell** [Vincit/objection.js#1710]
Hi There,

I'm running into issues getting the `$beforeDelete` hook to fire on an instance of my models. I've followed the guides making sure to call the instance and am also using the document [here](https://github.com/Vincit/objection.js/blob/3fcb87b59ea423bf69d114561c18a3a4ba429eef/doc/guide/hooks.md) as a reference.

in my controller, I have the following:

```
// controllers/user-cards-controller.js
let card = await Card.query().findById(req.params.id)
await card.$query().delete()
res.status(200).send({})
```

Then in my model...

```
// models/card.js
  async $beforeDelete(context) {
    await super.$beforeDelete(context);
    await this.destroyStripeCard();
    this.id ? this.scheduleWorkers('deleted') : null;
  }
```

I haven't had any difficulty with the other hooks nor objection otherwise. I'm also currently using Objection 2.1.3. Any help would be appreciated!

**Comment by koskimas** [comment]
Based on the info you provided, I can't really help you. Please provide the relevant models and other code that may be causing this.

**Comment by ehubbell** [comment]
Ok, thanks for the reply. That helps actually.. It looks like this was related to the `objection-soft-delete` library being used on the corresponding model. Apologize for the confusion!
