### ISSUE TITLE
paging with dense_rank

### ISSUE THREAD

**Issue by ameinhardt** [Vincit/objection.js#1711]
Hi,
I am looking for a way to page `withGraphJoined()` and tried that via `DENSE_RANK` and subqueries. I noticed that the main query doesn't parse the relation, so that needs to be done 'manually' after:
```javascript
await initialize([Post, Comment]);
const [posts, [{ count }]] = await Promise.all([
  Post.query()
    .select()
    .from(Post.query()
      .as('rankedQuery')
      .select(raw('DENSE_RANK() OVER (ORDER BY ??) AS ??', ['posts.id', 'rank']))
      .withGraphJoined('comments')
    )
    .castTo(Model) // important to not run $parseDatabaseJson twice
    .whereBetween('rank', [0, 20])
    .runAfter((rows, qb) => {
      const joiner = new RelationJoiner({ modelClass: Post })
        .setExpression(RelationExpression.create('comments'));
      joiner.build(qb);
      return joiner.parseResult(qb, rows);
    }),
  Post.knexQuery('posts').count('* as count')
]);
```
Is there any better way to do that with objection? Or is the paging of withGraphFetched (`WHERE ... IN ...`) just performant enough, even for big pages (and e.g. oracle)?

**Comment by koskimas** [comment]
Sorry, can't help you there. As there are no other people commenting, I'm closing this.
