### ISSUE TITLE
Implicit many-to-many relations through a shared "belongs to"

### ISSUE THREAD

**Issue by robwold** [Vincit/objection.js#1714]
Having read something like this:
https://github.com/Vincit/objection.js/issues/316 I'm sure what I'm trying to do here should be possible somehow, but I can't seem to figure it out.

 I have a `customers` table which has a has_many relationship with both `users` and `vehicles`, which therefore have an implied many_to_many relationship between them. Given a user, I want to find all the vehicles that belong to that user's customer.

 The SQL is trivial:
```SQL
SELECT v.* from vehicles v
JOIN users u on u.customer_id = v.customer_id
WHERE u.id = --WHATEVER
```

I tried to piece together a few variants such as
```javascript
const { Model } = require('objection');

class users extends Model {

  static get tableName() {
    return 'users';
  }

  vehicles(){
    this.$relatedQuery('vehicles');
  }

  static get relationMappings() {

    const vehicle = require('./vehicles.model');
    const customer = require('./customer.model');
    return {
      customer: {
        relation: Model.BelongsToOneRelation,
        modelClass: customer,
        join: {
          from: 'users.customer_id',
          to: 'customers.id'
        }
      },

      vehicles: {
        relation: Model.ManyToManyRelation,
        modelClass: vehicle,
        join: {
          from: 'users.customer_id',
          join: {
            modelClass: customer,
            from: 'customers.id',
            to: 'vehicles.customer_id'
          },
          to: 'vehicles.id'
        }
      }
    };
  }
}

module.exports = function () {
  return users;
};
```

And as far as I can tell from the ensuing error messages, the many-to-many relationship HAS to be through a join which HAS to have two columns from the same join table. Is there some way of achieving this?

**Comment by koskimas** [comment]
You can simply define a `HasManyRelation`:

```js
      vehicles: {
        relation: Model.HasManyRelation,
        modelClass: vehicle,
        join: {
          from: 'users.customer_id',
          to: 'vechicle.customer_id'
        }
      },
```

**Comment by robwold** [comment]
Well that's simple! Thanks for the swift response over the weekend.
