### ISSUE TITLE
Can we get auto-completion for $set method?

### ISSUE THREAD

**Issue by cerino-ligutom** [Vincit/objection.js#1716]
Pretty much like how we get the current auto complete when using `.where()` method.

![image](https://user-images.githubusercontent.com/6721822/76849572-9c8fe500-6880-11ea-9f62-a9ca75fd8967.png)

Currently, we get nothing.

![image](https://user-images.githubusercontent.com/6721822/76849620-b0d3e200-6880-11ea-8ccf-636c7b6e33bf.png)

**Comment by koskimas** [comment]
I'm not sure if this can be done because `$set` takes an object. What's your use case for `$set`? You do get auto complete if you simply assign values like

```js
form.lastName = 'Anderson'
```

**Comment by cerino-ligutom** [comment]
> I'm not sure if this can be done because `$set` takes an object. What's your use case for `$set`? You do get auto complete if you simply assign values like
> 
> ```js
> form.lastName = 'Anderson'
> ```

Basically using it as a form. For example, when registering.

![image](https://user-images.githubusercontent.com/6721822/76966693-53fc2880-6961-11ea-8627-f94efa00c5fa.png)

**Comment by cerino-ligutom** [comment]
Unless this isn't the way we should be doing this... But since the class that extends the `Objection.Model` practically contains the properties of my db table, might as well use that.

-----

I've thought of separating things to two classes. 1 for my entity models (just pure properties of the db table) and 2nd for objection models which extends the corresponding entity model so that when I create a "form" for insertion to the database, I just use the entity model as the type> then again that just adds extra work when the objection model practically holds all the properties of my db table. Not to mention letting a class extend more than 1 class thru TS mixins.

-----

I'd like to avoid type assertion as well.

```ts
const form = {
  // ...properties
} as User;
```

mainly because even this is valid:
```ts
const form = {} as User;
```
TS thinks `form` is of type User but on runtime it contains nothing. So even though a field is required but due to the type assertion, this gets ignored and fails during insertion because the field is non-nullable in the database.

-----

One could say use `Partial<T>` then type assert later when passed as an argument but that makes all fields optional so that defeats the purpose and I get the same issue as above during insertion.

```ts
const form: Partial<User> = {
  // ...properties
}

User.query().insertAndFetch(form as User);
```

-----

Just making the type of my `form` variable to be the type of my objection model, `User` in this case` would cause an error since I cannot provide the methods/properties of the objection model unless I instantiate one and start individually assigning the properties.

It's not really much of an issue but I think `$set()` could do better to support object assignment **with types**.

I just now realize while writing this, is the purpose of `$set()` just to map whatever is in the argument object to the instance? If that's the case, then I guess a `Partial<T>` will do. I'd like to at least get auto-completion when assigning and the cascading we get when we rename with F2 in VS Code.


Also, would just like to hear from you, is the individual assignment how you intended the users to assign property values? For example:
```ts
const form: User = new User();
form.firstName = firstName;
form.middleName = middleName;
form.lastName = lastName;
form.username = username;
form.email = email;
form.hash = hash;
form.salt = salt;
```

**Comment by koskimas** [comment]
There's no intended way of setting properties. You can do it however you want. The $set method works, you just don't get auto completion currently. We could in theory define the `$set` method like this

```js
$set(obj: PartialModelObject<this>)
```

Where `PartialModelObject` is like `Partial`, but it also removes methods. But that would only allow a subset of the defined properties to be set. Objection allows you to set any properties for historical reasons.

Objection was developed without typescript, and adding typescript typings afterwards like this is always a compromise, and some things don't work so well.

You can easily create your own helper like:

```js
class BaseModel extends Model {
  set(obj: PartialModelObject<this>): this {
    return this.$set(obj)
  }
}
```

And then just inherit your models from `BaseModel ` instead of `Model`.

**Comment by cerino-ligutom** [comment]
Nice, this works great for our use case, thanks!
