### ISSUE TITLE
Include the supplied value in the validation errorHash that is passed to createValidationError

### ISSUE THREAD

**Issue by fiznool** [Vincit/objection.js#1718]
I've found myself wanting to create a custom `ValidationError` that includes the value that was validated alongside the error message. For example, if I have the following JSON Schema:

``` js
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "minLength": 5
    }
  }
}
```

And I try to validate the following:

``` js
{
  "name": "abcd"
}
```
I'd like the exception to contain the following information:

``` js
{
  "name": [
    {
      "message": "should be at least 5 characters",
      "keyword": "minLength", 
      "params": {
        "limit": 5
      },
      "data": "abcd"  // <-- the submitted value
    }
  ]
}
```

The `ajv` library will [add a 'data' property to its error object if the `verbose` option is set](https://github.com/epoberezkin/ajv#validation-and-reporting-options). The implementation in Objection [currently takes the `message`, `keyword` and `params` keys](https://github.com/Vincit/objection.js/blob/master/lib/model/AjvValidator.js#L176-L180), so even if the `verbose` option is set via a custom Ajv instance, the `data` property won't be propagated to the `createValidationError` static method.

Would you be open to supporting this functionality, either by default or as an opt-in config flag?

Alternatively if there is another way I can achieve this goal, please let me know.

Thanks again for a great library 😄

**Comment by fiznool** [comment]
Just bumping this.

Happy to implement a PR, but don't want to do so if it's unlikely to be accepted!

**Comment by lehni** [comment]
I'd be happy to review a PR for this!

**Comment by cesumilo** [comment]
> I'd be happy to review a PR for this!

Here it is 😉

**Comment by lehni** [comment]
Thanks @cesumilo !
