### ISSUE TITLE
Working with the bindKnex() cache for multiple versions of same model

### ISSUE THREAD

**Issue by devinivy** [Vincit/objection.js#1719]
This is going to be a tricky one to explain, so bear with me!  At surface value the issue I'm having is that `bindKnex()` caches models based upon their `name` and `tableName`, which means I can't use two separate models with the same instance of knex that have identical `name` and `tableName`.

How did I generate this issue?  Well, as you can imagine, if I had this issue in a standalone application I would probably be doing something wrong.  But I'm actually building tooling for others to use via schwifty and the hapi pal ecosystem, with an emphasis on flexible application structure.  To keep it brief: independent areas of an application can define their own models, and we would like to allow for a case where one area of an application might be very generic, while another area more specific.  The generic area uses very minimal models, and the more specific area might extend those models to define its own further validation, lifecycle hooks, relation mappings, etc.  So there may be two models in the application with the same `name` and `tableName`, where one is essentially more specific than the other.

I have dug into this problem and have a pretty good understanding of how this is handled inside objection, and it makes perfect sense to me that it works the way it does.  I'm soliciting feedback/thoughts about how to either work with the current behavior, alter the current behavior (I would offer to work on this), or really any other solution I haven't thought of.

I have started working on this by extending the base model to have a more involved `uniqueTag()`.  You can see a draft of this approach here: https://github.com/hapipal/schwifty/commit/c7f0f9381eed2389063ed97afb92045b269cbd8f#diff-a140b60b6a99a8c69f4b5d0d1f1f2bfaR15

This approach is a little tricky—it's never fun to introduce state to keep track of, although of course I can live with it— and I'm not positive if `uniqueTag()` is fair game to extend, as it's not in documentation (although I see it has been in place for a long while).  The other downside is that this approach doesn't work with plain objection models (rather than the schwifty base class), which I would like to support equally well.

If moving away from `uniqueTag()` for `bindKnex()` caching is an option, I have an idea about how that could work, taking advantage of the fact that the unique tag is primarily being used to protect `bindKnex()` from itself (or, `inheritModel()`).  But I would like to get some thoughts before jumping there.  For anyone who made it this far, thanks for reading!

**Comment by koskimas** [comment]
Short answer before I have time to read this thoroughly: uniqueTag id fair game! I've just forgotten to document it.

**Comment by devinivy** [comment]
Thanks @koskimas.  I wasn't able to support my "sandboxing" feature for all objection models, but i was able to support it for the schwifty base class, which is good enough for me.  The relevant PR is here for those interested https://github.com/hapipal/schwifty/pull/88
