### ISSUE TITLE
Is there a combination of insertWithRelated and insertAndFetch?

### ISSUE THREAD

**Issue by mcchrish** [Vincit/objection.js#172]
As the title says, `insertWithRelated` that returns all the column like `insertAndFetch`, without resorting to `returning`.

**Comment by koskimas** [comment]
Why don't you want to use `returning`? Are you not using postgres? Would you like the new `insertWithRelatedAndFetch` to fetch the whole graph or just the root?

**Comment by mcchrish** [comment]
Personally I'm using postgres, so I think `returning` is enough for my need.
However, I'm working on a [feathers.js](https://github.com/feathersjs/feathers) DB adapter API based on objection.js. As for an API, I'm seeking for a way to make things uniform regardless of what DB is in used, that's why I think it makes sense to also have an `insertWithRelatedAndFetch` much like `updateAndFetch`, `patchAndFetch` etc.

>Would you like the new `insertWithRelatedAndFetch` to fetch the whole graph or just the root?

I think it would make more sense to send the whole graph, rather than just the root.

The [DB adapter](https://github.com/mcchrish/feathers-objection) in question.

**Comment by koskimas** [comment]
`insertWithRelatedAndFetch` will be added to 0.6.0. Probably already in the next alpha version.
