### ISSUE TITLE
upsertGraph does not set the column to null

### ISSUE THREAD

**Issue by slim-hmidi** [Vincit/objection.js#1721]
I have a model `Officer` contains a `reported_case_id`  and I tried to update it to null whenever I call the `upsertGraph()` inside my controller.
I realized that `reported_case_id` contains the previous value after calling the ` upsertGraph`. You can check my [example](https://runkit.com/slim-hmidi/5e80ef7804c382001316c47e).

**Objection**: 2.3.1
**Node**:  12.16.0
**pg**: 7.11.0
**knex**: 0.17.5

**Comment by koskimas** [comment]
You are also inserting s new instance to that relation, so its id gets set. Your example makes no sense. At the same time, you are setting the value to null and to value 1.

**Comment by slim-hmidi** [comment]
I inserted it at the first case to the table `officers`:
```
 await Officer.query().insertGraph({
    id: 1, name: 'officer 2', available: false, reported_case_id: 1,
    reportedCase: [
      {
      id: 1, name: 'Alex Stan', email: 'alex.stan@gmail.com', bike_frame_number: 88525956, case_resolved: false,
    },
    ]
  });
```

Then, when the officer update the `reportedCase ` and resolve it, the `reported_case_id` should be `null ` in the row of the given `officer`. If the `upsertGraph` does not update the ` officers ` and the `reported_case` simultanously, how I can fix that.
I don't understant what is the thing that has no sens in the example @koskimas
