### ISSUE TITLE
[Feature Request] Optional message param to throwIfNotFound

### ISSUE THREAD

**Issue by PhilipBale** [Vincit/objection.js#1722]
**Describe the solution you'd like**
Would love to be able to provide a message string to the throwIfNotFound method.

**Describe alternatives you've considered**
N/A

**Additional context**
Would help solve the pain of writing a few lines of code to throw a custom error every time a necessary object doesn't exist.

**Comment by koskimas** [comment]
That's a good idea. Let's add it.
