### ISSUE TITLE
How to model multiple many-to-many relations between tables

### ISSUE THREAD

**Issue by enyiasonye** [Vincit/objection.js#1725]
I'm working on creating models that represent friendship between users. I have a few tables with the following schemas:

users:
-  id (primary key)
- first_name
- last_name
- email
- created_at

friendship_status:
- id (primary key)
- status

user_friendship:
- id (primary key),
- user_one_fkey -references-> users(id),
- user_two_fkey -references-> users(id),
- user_action_id -references-> users(id),
- friendship_status_fkey -references-> friendship_status(id),
- date_established

I am working on creating the `user` model and I'm a bit stumped as to how to go about creating the relation mapping. I have considered creating a model for the `user_friendship` join table, but it doesn't entirely solve my relation mapping issue.

**Comment by koskimas** [comment]
This should help https://vincit.github.io/objection.js/recipes/ternary-relationships.html#ternary-relationships
