### ISSUE TITLE
resultSize() with CTE

### ISSUE THREAD

**Issue by ameinhardt** [Vincit/objection.js#1726]
I would like to use [resultSize()](https://vincit.github.io/objection.js/api/query-builder/other-methods.html#resultsize) on a query with CTE [.with()](https://vincit.github.io/objection.js/api/query-builder/find-methods.html#with).
In mssql, `with` has to be on the top level of the query.
Currently, I have to use my custom QueryBuilder with:
```javascript
async resultSize() {
    const knex           = this.knex(),
          builder        = this.clone().clear(/orderBy|offset|limit/),
          withOperations = builder._operations.filter(({ name }) => name.startsWith('with')),
          countQuery = knex.count('* as count').from(knexBuilder => {
            builder.clear(/^with/).toKnexQuery(knexBuilder).as('temp');
          });
    withOperations.forEach(({ name, args }) => countQuery[name](...args));
    if(this.internalOptions().debug) {
      countQuery.debug();
    }

    const result = await countQuery;
    return result[0] && result[0].count ? parseInt(result[0].count) : 0;
  }
```
Maybe knex should put all with statements to the top-level, but meanwhile, that could be an improvement to `resultSize()`.

**Comment by koskimas** [comment]
This is not something objection should handle.

**Comment by ameinhardt** [comment]
@koskimas: The developer can't handle it, because objection wraps the query. knex will not modify the developers query.
objection offers the method. So I think it would be reasonable to fix it. Otherwise this ticket just serves as a reference if someone else comes along this particularity.
