### ISSUE TITLE
Unclear migration path for findQuery(query, opts) -> findQuery(query, owner)

### ISSUE THREAD

**Issue by kibertoad** [Vincit/objection.js#1727]
Objection 1.x was expecting an opts entity instead of an owner, that it used to resolve ownerIds.
Objection 2.x is expecting `RelationOwner`, which is an internal class that isn't even exported, so one can't instantiate it externally, and it's also not available from relationship itself.

This breaks objection-find filter logic, which was based on invoking this:

```
    if (rel && !rel.isOneToOne()) {
      const opts = {
        ownerIds: rel.ownerProp.refs(builder),
      }
      const query = rel.relatedModelClass.query()
      
      const subQuery = rel.findQuery(query, opts);
      subQuery[whereMethod].apply(subQuery, filter.args);

      builder.whereExists(subQuery.toKnexQuery().select(1));
    } else {
      builder[whereMethod].apply(builder, filter.args);
    }
```

Which is no longer a valid approach. Could you suggest any solution within existing codebase? Alternatively I guess RelationOwner class could be exported, then we could try instantiating it ourselves.

**Comment by koskimas** [comment]
Even the old implementation used the internal API, so there's no clear migration path for that. You need to keep on using the internal API. There might be a way to do that using the current public API, but I'm not familiar with `objection-find` code anymore.
