### ISSUE TITLE
Allow non-primitive types in Where

### ISSUE THREAD

**Issue by Smtih** [Vincit/objection.js#1728]
I've been trying to create a model where one of the database fields is automatically parsed into a class on read, and serialised on write such that my app code only ever has to deal with the class instance (not the string that's written to the database. I've been able to achieve this with the Mode lifecycle methods like so

```
class ModelWithResource extends PaginatedModel {
  id!: String
  resource!: Resource
  
  $parseDatabaseJson(json: Pojo): Pojo {
    json = super.$parseDatabaseJson(json);
    if (json.resource) {
      json.resource = new Resource(json.resource);
    }
    return json;
  }

  $formatDatabaseJson(json: Pojo): Pojo {
    json = super.$formatDatabaseJson(json);
    if (json.resource instanceof Resource) {
      json.resource = json.resource.toString();
    }

    return json;
  }
}
```

What I would like to do is be able to pass a resource class into a query like so
```
const resource = new Resource("Movie:123");
ModelWithResource.query().where("resource", resource);
```

I've been experimenting and as my backing database is Postgres, by adding a toPostgres method to my class I can make this work.
There are still two issues though.
1: Objection/Knex typescript typings don't allow me to pass a class instance into a where.
2: I think objection should be handling this as it is at the Model layer that all these transforms should happen.

Is this already possible and I'm not sure how to make it work? Or would it be possible to accept an object the implements something like a `toPrimitive()` function in objection and have this called before being added to the where bindings?

**Comment by koskimas** [comment]
Implementing this would be very difficult. If you have control over the `Resource` class, you can already implement a `toKnexRaw` method for it and it will get handled by objection. You need to return a knex `Raw` objection from that method. Something like this

```js
class Resource {
  toKnexRaw(query) {
    // `query` is the objection query buier this will be part of
    return query.knex().raw('?', this.toString())
  }
}
```

`toKnexRaw` is not yet documented, but it will be.

**Comment by Smtih** [comment]
Can confirm this works for my situation. Problem is still that typescript is obviously not happy so will have to still wrap this in my own function and ignore the type warnings there for now.

Do you plan to enhance the typings to allow this when you add the docs, otherwise I can open a PR?

**Comment by jtomaszewski** [comment]
Note for the others. On knex 0.20.13 and objection 2.1.3, adding `toKnexRaw()` broke our app. 

After adding `toKnexRaw()` to `Engine` class , if we passed `Car.insert({ engine: engineAsClass })`, where `engineAsClass` was an instance of the `Engine` class, the `Car` would be created, but with `engine: undefined`.

After updating to knex 0.21.1 and objection 2.2.0 , problem disappeared.
