### ISSUE TITLE
Clarify that JSON queries only work on postgres

### ISSUE THREAD

**Issue by koskimas** [Vincit/objection.js#173]
- [ ] Better documentation
- [ ] Add descriptive error message on other databases

related to #170

**Comment by taoeffect** [comment]
SQLite now has full-blown support for JSON:

- https://www.sqlite.org/json1.html
- http://charlesleifer.com/blog/using-the-sqlite-json1-and-fts5-extensions-with-python/

Can objection.js support it using this? (Are raw queries compatible with this in the meantime?)

**Comment by koskimas** [comment]
We should add support for other databases instead
