### ISSUE TITLE
Typescript support for Ajv Keywords

### ISSUE THREAD

**Issue by jaimedeverall** [Vincit/objection.js#1732]
Hi everyone, I really appreciate objection as it's much easier to use and more powerful than any of the ORM alternatives in the node.js ecosystem - thank you for this gift!

I'm using objection v2.1.3 and I've decided to use the `ajv-keywords` pacakage to add the `instanceof` keyword to `AjvValidator` like this in my `BaseModel.ts` file:

```
  static createValidator() {
    return new AjvValidator({
      onCreateAjv: ajv => {
        ajvKeywords(ajv, 'instanceof');
      },
    });
  } 
```

When I try to use ```{ instanceof: 'Date'}``` in my code I get a typescript error because `instanceof` is not part of `JSONSchema` as defined in `typings/objection/index.d.ts`.

I've settled on using `patch-package` to change the interface definition of `JSONSchema` in `typings/objection/index.d.ts` but I was wondering if you have any other ideas on how I might extend `JSONSchema` to add `instanceof`.  Really appreciate any help.

**Comment by koskimas** [comment]
Glad you like objection! Your words mean a lot to me :bow: 

Unfortunately, I don't think there's an easy way to do that. You could try this https://www.typescriptlang.org/docs/handbook/declaration-merging.html.

Note that you probably need to declare the merges inside objection namespace. See the objection typings.

So something like this (didn't test, probably doesn't work)

```js
declare namespace Objection {
  interface JSONSchema {
    instanceof?: string
  }
}
```
