### ISSUE TITLE
PSQL model setup

### ISSUE THREAD

**Issue by kHRISl33t** [Vincit/objection.js#1734]
First of all, I love objection.js I have been using it with MySQL for months. Now I started using it with Postgres, and I ran into the following issue: [#675](https://github.com/Vincit/objection.js/issues/675)

Versions:
```
knex = 0.20.11
pg = 8.0.2
objection = 2.1.3
```

If I do the model setup according to the docs

```js
import { Model } from 'objection';
import { db } from './db';

Model.knex(db);

export default class Users extends Model {
  ...mymodel
}
```

I got the following error when I'm trying to use it with `Users.query()`: 

```
Error: no database connection available for a query. You need to bind the model class or the query to a knex instance.
    at QueryBuilder.knex (/Users/kristofivancza/development/geo-backend-ts/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:206:15)
    at buildKnexQuery (/Users/kristofivancza/development/geo-backend-ts/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1579:56)
    at doExecute (/Users/kristofivancza/development/geo-backend-ts/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1470:31)
    at QueryBuilder.execute (/Users/kristofivancza/development/geo-backend-ts/node_modules/objection/lib/queryBuilder/QueryBuilder.js:682:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

The db I import looks like this:

```js
export const db = knex({
  client: dbConfig.client,
  connection: {
    ...dbConfig.connection,
    timezone: 'UTC',
  },
  searchPath: [`${dbConfig.schema}`],
  pool: {
    ...dbConfig.pool,
  },
  debug: dbConfig.debug,
  ...knexSnakeCaseMappers(),
});
```

But managed to solve it with the following:

```js
import { Model } from 'objection';
import { db } from './db';

class Users extends Model {
  ...mymodel
}

Users.bindKnex(db);
Users.knex(db);

export default Users;
```

I found nothing about this in the docs (or I missed something). Can someone clarify this is a valid/proper solution?

**Comment by koskimas** [comment]
The original code should work. It doesn't matter when you call Model.knex, as long as you do it once during the lifetime of the app before the first query. The Model.bindKnex line is just wrong. It does nothing when you use it like that. You have some weird code somewhere that's causing this. No way to know what and where.

**Comment by koskimas** [comment]
Feel free to post more info here even though I closed this. I closed it because this isn't a bug in objection.

**Comment by kHRISl33t** [comment]
You were right, I was just stupid to check what's in my db variable. I messed up the import with my db connection, it was undefined at the first call.
Now it's working as expected (and according to the docs:)), sorry to waste your time. :(
