### ISSUE TITLE
Insert Graph and default inserts

### ISSUE THREAD

**Issue by adprajwol** [Vincit/objection.js#1735]
Currently I have three models

``` 
User
id(PK)
name

Product
id(PK)
user_id(FK)
name

Stock
id(PK)
product_id(FK)
quantity
```

When inserting products I am currently using: 

``` 
await User.relatedQuery('userProducts')
.for(req.user.id)
.insertGraph({
      "name": "Product"
       "stock": {
            "quantity": 10
       }
})
``` 

But if I only insert name for the product only the product gets inserted, the stock does not. 

``` 
await User.relatedQuery('userProducts')
.for(req.user.id)
.insertGraph({
 "name": "Product"
})
``` 

How does one go about inserting a default stock value only if only product is inserted. 

Also, is there a better way to insert user_id for the product. Currently I am setting allowAdditionalProperties: true, so that it does not throw an error for user_id.

**Comment by koskimas** [comment]
Unfortunaltely there's no easy way to set default relationships. You can try overriding `fromJson` method and setting it there, but it can cause other problems.

As for the user_id, simply add it to your jsonSchema as a property.
