### ISSUE TITLE
Help: What is the best way to establish a default value for "limit" on all select queries?

### ISSUE THREAD

**Issue by sokulski** [Vincit/objection.js#1736]
Hello all,

I'm looking to establish a default "limit" value for select queries using Objection.js, but I'm unsure of the best method to do this.

My first attempt used a static beforeFind hook in the model, but that doesn't appear to allow me to modify the query that is about to be executed, save for cancelling it.

I could extend query to add a default limit to it that gets overridden by subsequent calls. Is that a viable answer?

**Comment by koskimas** [comment]
There is no way to do that, and it's a very bad idea. How would relation joins work? How would nested relation `where i` queries work? Alot of objection features would be get broken if you did that.

**Comment by razukc** [comment]
I had a similar situation where I had to add a `deleted` column in a `messages` table. To avoid modifying all API functions , I first had to create a static modifier function and then use that modifier using custom query builder.

What do you think of this approach?

```
/** Modifier */ 
static get modifiers () {
     return {
       undeleted(builder) {
         builder.where('deleted', false)
       }
     }
}
```
```
/** Custom query builder */
  static query(...args) {
    const query = super.query(...args);
    return query.modify('undeleted')
  }
```

[https://vincit.github.io/objection.js/api/model/static-properties.html#static-modifiers](https://vincit.github.io/objection.js/api/model/static-properties.html#static-modifiers)
[https://vincit.github.io/objection.js/recipes/custom-query-builder.html](https://vincit.github.io/objection.js/recipes/custom-query-builder.html)
