### ISSUE TITLE
ManyToMany relation's require loop

### ISSUE THREAD

**Issue by AbdusamadTurdiev** [Vincit/objection.js#1737]
Hi, I have Base model
```
// models/base.js

const { Model } = require('objection')

class Base extends Model {
  static get modelPaths() {
    return [__dirname]
  }
}

module.exports = Base
```

Card model
```
// models/card.js

const Base = require('./base')
const { pg: knex } = require('~root/db')

class Card extends Base {
  static get tableName() {
    return 'cards'
  }

  static get relationMappings() {
    return {
      partners: {
        relation: Base.ManyToManyRelation,
        modelClass: 'partner',
        join: {
          from: 'cards.id',
          through: {
            from: 'partner_card.card_id',
            to: 'partner_card.partner_id',
          },
          to: 'partners.id',
        },
      },
    }
  }

  $beforeUpdate() {
    this.updatedAt = knex.fn.now()
  }
}

module.exports = Card.bindKnex(knex)
```

Partner model
```
// models/partner.js

const Base = require('./base')
const { pg: knex } = require('~root/db')

class Partner extends Base {
  static get tableName() {
    return 'partners'
  }

  static get relationMappings() {
    return {
      cards: {
        relation: Base.ManyToManyRelation,
        modelClass: 'card',
        join: {
          from: 'partners.id',
          through: {
            from: 'partner_card.partner_id',
            to: 'partner_card.card_id',
          },
          to: 'cards.id',
        },
      },
    }
  }

  async $beforeUpdate() {
    this.updatedAt = knex.fn.now()
  }
}

module.exports = Partner.bindKnex(knex)
```

everything seems good but I'm getting this error
![image](https://user-images.githubusercontent.com/33511684/80077991-b6030b80-8567-11ea-934d-e77fd62c2cb0.png)

Objection: 2.1.3
Node.js: v12.16.1
OS: macOS Catalina 10.15.3

**Comment by AbdusamadTurdiev** [comment]
this is working when I'm writing like this `modelClass: 'Card'` or `modelClass: 'Partner'`

![image](https://user-images.githubusercontent.com/33511684/80082615-0d0bdf00-856e-11ea-97b7-cf5d3c7b7461.png)

but when I'm uploading this to production server (Ubuntu) I'm getting this because my model names are lowercase

![image](https://user-images.githubusercontent.com/33511684/80082827-4e9c8a00-856e-11ea-8288-abbac77fe25e.png)

**Comment by koskimas** [comment]
Yep, in linux files are case sensitive. You should use the same case.

**Comment by AbdusamadTurdiev** [comment]
> Yep, in linux files are case sensitive. You should just write the correct file name in `modelClass`.

@koskimas I'm sorry, but did you see my issue's main message? It's not working even the file name is correct.

**Comment by AbdusamadTurdiev** [comment]
@koskimas Please can you fix this bug? Still not working

![image](https://user-images.githubusercontent.com/33511684/81524857-3ac59600-936c-11ea-952a-e2958314aa05.png)

**Comment by AbdusamadTurdiev** [comment]
@koskimas could reproduce this bug? I can't understand why are you ignoring this issue? Please help me to solve this problem

**Comment by elhigu** [comment]
Try to simplify your code until you find where your require loop happens. It doesn't look like being related to objection.

**Comment by AbdusamadTurdiev** [comment]
> Try to simplify your code until you find where your require loop happens. It doesn't look like being related to objection.

@elhigu why should I simplify my code if I'm using solution pattern described in the [docs](https://vincit.github.io/objection.js/guide/relations.html#examples)?

**Comment by AbdusamadTurdiev** [comment]
@koskimas can you help please? seems like relationMappings method isn't running lazily

**Comment by Dev-El-badry** [comment]
in model file 
defined modeClass like this: 

`
modelClass: join.path(__direname, 'path/to/model/transactioni');
`

that's will be solve problem !
