### ISSUE TITLE
Feature request: Validation custom error messages

### ISSUE THREAD

**Issue by advename** [Vincit/objection.js#1739]
The AjvValidator package does not accept custom error messages and uses a default of not user friendly messages.
Integrating the [Ajv-Errors](https://github.com/epoberezkin/ajv-errors/#supporters) package should solve this, allowing us to use:
```js
 email: {
          type: "string",
          format: "email",
          maxLength: 254,
          errorMessage: "Invalid email"
},
```
I've tried it myself to integrate it - but failed miserably.

It should tho not be so hard, based on Ajv-errors documentation:
```js
var Ajv = require('ajv');
var ajv = new Ajv({allErrors: true, jsonPointers: true});
// Ajv options allErrors and jsonPointers are required
require('ajv-errors')(ajv /*, {singleError: true} */);
```

## Edit
My bad, it is possible - had to dig through AjvValidator issues to find a solution since I couldn't find it in the documentation.

This code below works
```
        email: {
          type: "string",
          format: "email",
          maxLength: 254,
          errorMessage: { format: "Invalid email" }
        },
```

But it would still be nice to use one error message for all failed validation keywords, since this message only applies to the `format` keyword.

**Comment by globsecure** [comment]
You can create one BaseModel and use extends on own Models:

![Screenshot 2020-04-30 at 16 19 05](https://user-images.githubusercontent.com/1958192/80750366-532ce980-8afe-11ea-9809-f84617604ac7.png)

then you can use errorMessage inside the models:
![image](https://user-images.githubusercontent.com/1958192/80750597-bd458e80-8afe-11ea-9a0b-c74bcdd602c9.png)
