### ISSUE TITLE
Boolean fields are read as 1/0 instead of true/false 

### ISSUE THREAD

**Issue by purepear** [Vincit/objection.js#174]
Not sure if this is SQLite3 specific but it looks like it's not converting 0 & 1 to true & false after .query().select()....
It's probably a Knex thing.. if you got info or any comments...

**Comment by elhigu** [comment]
Yeah as far as I know it is knex / underlying driver thing. I had problems with that when I wrote migration table locking feature to knex.

**Comment by koskimas** [comment]
Objection doesn't touch the values coming from the db driver by default. As elhigu mentioned, this is a knex/db client issue.

**Comment by noise-machines** [comment]
Since Objection doesn't handle this, one solution is to use knex's typeCast option. (The only mention I could find is [this](https://stackoverflow.com/questions/38004328/knex-js-mysql-casting-integer-into-boolean-for-bulk-select) StackOverflow answer.)

```js
const knex = require('knex')({
  client: 'mysql2',
  connection: {
    host: 'localhost',
    user: 'mysql',
    password: 'mysql',
    database: 'mysql',
    typeCast (field, next) {
      // Convert 1 to true, 0 to false, and leave null alone
      if (field.type === 'TINY' && field.length === 1) {
        const value = field.string()
        return value ? value === '1' : null
      }
      return next()
    }
  }
})

```
