### ISSUE TITLE
Timestamp documentation example not working as expected

### ISSUE THREAD

**Issue by yasuf** [Vincit/objection.js#1740]
### Problem
When implementing the example in the timestamps documentation, it doesn't dun by default, you get an error similar to:
```
Incorrect datetime value: \'2020-05-02T01:13:27.557Z\' for column \'created_at\' at row 1',
```

https://vincit.github.io/objection.js/recipes/timestamps.html

### To Reproduce
* Add `table.timestamps()` to a table using migrations
* Add both of these to the model for that table:
```
  $beforeInsert() {
    this.created_at = new Date().toISOString();
  }

  $beforeUpdate() {
    this.updated_at = new Date().toISOString();
  }
```
* Try creating an instance of that model

**Comment by koskimas** [comment]
Works in my tests.

**Comment by abrain** [comment]
In my case, this was due to MariaDB not accepting timestamps with the trailing Z (or any time zone indication, see [this issue](https://jira.mariadb.org/browse/MDEV-11829)). But it works when you pass `Date` objects instead of the ISO strings.

**Comment by z1haze** [comment]
have this same issue.
