### ISSUE TITLE
Issue with insert into many to many table

### ISSUE THREAD

**Issue by TobiasBms** [Vincit/objection.js#1741]
I have two models: Board and users these two have a many to many relation.
I want to insert the ids into a binding table called Board_Has_Users.
Here is the board model where I have the relationquery:
`static get relationMappings() {

      const User = require("./User");

      return {
        boardUsers: {
          relation: BaseModel.ManyToManyRelation,
          modelClass: User,
          join: {
            from: "board.boardId",
            through: {
              from: "board_has_user.boardId",
              to: "board_has_user.userId"
            },
            to: "users.userId"
          }
        }
      }
    }`

My issue is that I dont seem to understand how to do it, I have read your documentation two times it's abit cryptic for me. 

I appriciate your help and time!

**Comment by koskimas** [comment]
Feel free to improve the documentation.`relate` method is what you are looking for. You can also sumply insert rows to the join table directly. There's no magic that prevents that.

**Comment by koskimas** [comment]
https://vincit.github.io/objection.js/api/query-builder/mutate-methods.html#relate
https://vincit.github.io/objection.js/guide/query-examples.html#relation-relate-queries
