### ISSUE TITLE
patch attempts to update all columns, not just the ones provided

### ISSUE THREAD

**Issue by GGAlanSmithee** [Vincit/objection.js#1742]
As the title say, I cannot patch just a single column / field value. (AKA do a partial model update)

Given the code:
```ts
await Item.query()
    .patch({ isSuggestion: false, })
    .findById(id)
```

I would expect the following query:
```sql
update "items" set "isSuggestion" = $1 where "items"."id" = $2
``` 

But the query that is created is
```sql
pdate "items" set "isSuggestion" = $1, "title" = $2, "description" = $3, "briefDescription" = $4, "shortDescription" = $5, "image" = $6 where "items"."id" = $7
``` 

So, as you can see it attempts to (incorrectly) bind all columns in the table. The provided code is the actual use-case, a very minimal application, more or less taken from the docs.

The only thing I can think of having even a remote chance of creating this behaviour would be that I have default values in my model:

```ts
class Item extends Model implements IItem {
    id = undefined
    isSuggestion = true

    title = ''
    description = ''
    briefDescription = ''
    shortDescription = ''

    ... // more stuff
}
```

Could that be it?

Thankful for any help on this. Meanwhile I will fetch and update it manually.

Thanks!

**Comment by koskimas** [comment]
Nope, this doesn't happen. You are logging something else than the query that updates the single field. Don't you think something like this is tested in objection?

**Comment by GGAlanSmithee** [comment]
@koskimas of course I think this is tested, but there are things such as regressions etc. What's with the passive aggressiveness?

I am pretty sure I am logging the correct query, and the problem is very likely with my code, but can't understand what that would be, since it's such a minimal usecase. I will try to provide a simple reproduction 

Thanks for your time and this awesome project!

**Comment by kibertoad** [comment]
@GGAlanSmithee "Tested" means covered with automatic tests, meaning that regressions would be discovered immediately. Minimal reproduction definitely would be super helpful!

**Comment by GGAlanSmithee** [comment]
@kibertoad alright, thanks for the additional explanation. I will create a reproduction, and maybe I'll discover my error while doing it.
