### ISSUE TITLE
Mass Assignment Protection + Hidden Attributes

### ISSUE THREAD

**Issue by zanechua** [Vincit/objection.js#1746]
Are there any plans to add mass assignment protection via a `fill` method?

and hiding attributes via the `$toJson()` method?

Basically it's the same features as what Eloquent has (https://laravel.com/docs/7.x/eloquent)

Could be as simple as add it to the base model and you call the model class with the syntax like so:

```javascript
Model:
static get fillable() {
    return ['']
}


static fill (data) {
   return data.filter(this.fillable);
}

Code:
const data = {}
const filledData = Model.fill(data);
```

The other is for hidden attributes:

```javascript
Model:
get hidden() {
    return ['']
}

$formatJson (json) {
   return json.filter(this.hidden);
}

Code:
const jsonData = Model.$toJson();
```

**Comment by koskimas** [comment]
You can easily add these yourself. I don't think this should be handled by objection.
