### ISSUE TITLE
typescript type for eagerloaded relation

### ISSUE THREAD

**Issue by Liooo** [Vincit/objection.js#1747]
The code below is an eagerload example from the doc:

```
const people = await Person.query().withGraphFetched('pets');

console.log(people[0].pets[0].name);
```

When I write the equivalent in typescript I get `Property 'pets' does not exist on type 'Person'`, which sounds pretty straightforward, but how can I get this to work?

(sorry probably I'm missing something but couldn't find anything in docs nor in gitter 🙏)

**Comment by koskimas** [comment]
Simply add that property for the class. Just like always with typescript.

**Comment by mmb12345** [comment]
Is there anything new that can infer the `correct typing when relations are utilized via `relationMapping` + `withGraphFetched`?
