### ISSUE TITLE
Question on virtual attributes

### ISSUE THREAD

**Issue by casalot** [Vincit/objection.js#175]
I have the following model definition:

```javascript
var AssessmentStatus = require(appDir + process.env.PATH_API + process.env.PATH_MODELS + 'knex/assessmentstatus');

class Assessment extends Model {
  static get tableName() {
    return 'Assessment';
  }

  static get virtualAttributes() {
    return ['status','currentState'];
  }

  currentState() {
    return this.assessmentTimeline[this.assessmentTimeline.length-1];
  }

  status() {
    AssessmentStatus
    .query()
    .then(assessmentStatus => {
      console.log(assessmentStatus);
      return assessmentStatus;
    })
    .catch(err => {
      console.log(err);
    });
  }
};

module.exports = Assessment;
```
In the JSON payload I can see all the attributes from the table, as well as the `currentState`. But, the `status` attribute is not included. Any ideas?

**Comment by fl0w** [comment]
If virtualAttributes support promises, you need to return the promise initially, e.g:

```js
status() {
  return AssessmentStatus
    .query()
    .then(assessmentStatus => {
      console.log(assessmentStatus);
      return assessmentStatus;
    })
    .catch(err => {
      console.log(err);
    });
}
```

**Comment by casalot** [comment]
Hm, I've tried that, and I now see this in the json:

```json
  "status": {
    "isFulfilled": false,
    "isRejected": false
  },
```

**Comment by koskimas** [comment]
Virtual attributes cannot be promises. To support async values, we would need to make everything asynchronous starting from the point that adds the virtual attributes. That would be a huge change and it would have a severe performance penalty to everything. Async virtual attributes won't be supported.

You can use `$afterGet` for this though. Or actually can't you just create a relation and use `eager`?

**Comment by casalot** [comment]
When using `$afterGet`, I'm having the same issue. The json result object is delivered before the `AssessmentStatus` response completes.

My use case is a bit different than the usual relationship between entities. I have the following:
- `Assessment`
- `AssesmentStatus`
- `AssessmentTimeline` - which is the linking table between `Assessment` and `AssessmentStatus`.

Now, I can easily do a many-to-many, but it will only return the values in AssessmentTimeline. I actually want to bring back ALL entries in `AssesmentStatus` in the `Assessment` payload. I then use this to build a timeline which includes ALL possible steps (statusses) which an `Assessment` can go through, not only the ones in `AssessmentTimeline`.

**Comment by casalot** [comment]
Okay, I have taken a different approach. I have moved this out of the model, and into the controller handler. Here I do something like this:
```javascript
      AssessmentStatus
      .query()
      .eager('[assessmentTimeline]')
      .filterEager('assessmentTimeline', builder => {
        builder.where('assessmentId',req.query.assessmentId);
      })
      .then(assessmentStatus => {
        res(assessmentStatus);
      })
```
So, I use `filterEager` to select only the relevant children.

**Comment by koskimas** [comment]
Did you remember to return the promise from the `$afterGet` method? Doing async stuff in `$afterGet` is fully tested and works for sure.
