### ISSUE TITLE
Patch call the Model constructor

### ISSUE THREAD

**Issue by ftaiolivista** [Vincit/objection.js#1751]
patch method call the class constructor. If you have any default values setup in class constructor the values will be updated in any patch query.

```
class Person {
 constructor() {
    this.active = 'm'
  }
}

const numberOfAffectedRows = await Person.query()
  .patch({ age: 24 })
  .findById(personId);
```
The above query will update **age** but event **active** value.

Is this  a desired behavior? It's bad to have defaults value in constructors?

**Comment by koskimas** [comment]
That's expected behavior. You shouldn't set default values in the constructor.
