### ISSUE TITLE
[Question] Is it safe to use a model instance as parameter for insert/update/patch?

### ISSUE THREAD

**Issue by cerino-ligutom** [Vincit/objection.js#1752]
I can't seem to find an example in the docs so I thought I'd ask here. Is it safe to pass a model instance to the following write operations below:

- `insert`
- `insertAndFetch`
- `update`
- `updateAndFetchById`
- `patch`
- `patchAndFetchById`

and probably `graph inserts/updates` also?

We make it a rule not to put any default value on the model properties so that when we instantiate the model, there are no default values that could potentially/accidentally replace the values on the db in case the properties were not set before the write operation.

With that, take this example (in TS). Imagine we have a `Product` objection model and we want to insert a row to the db:

```ts
// Controller Layer
const form = new Product();
form.$set({
  // set object here from the request
});
// Then pass the `form` model instance to the business logic layer service
```

```ts
// Business Logic Layer
async function createProduct(product: Product) {
  // Some business logic before insertion

  // Notice here we're inserting the product model instance. Is this safe?
  const newProduct = await Product.query().insertAndFetch(product);

  // Other business logic after the db operation

  return newProduct;
}
```

This currently works fine but would like to know if this could potentially be problematic in one way or another.

**Comment by devinivy** [comment]
If I recall correctly, doing this could bypass your model's validation within `createProduct()`.  That's the only thing I can think of off the top of my head, but it would probably be smart to see if anyone else knows of other issues.

**Comment by cerino-ligutom** [comment]
> If I recall correctly, doing this could bypass your model's validation within `createProduct()`. That's the only thing I can think of off the top of my head, but it would probably be smart to see if anyone else knows of other issues.

By model's validation, you mean the usage of the [static jsonSchema](https://vincit.github.io/objection.js/api/model/static-properties.html#static-jsonschema) property right?

We don't utilize it but instead do the validation on a middleware upfront (before hitting the controller) using `Yup` so I guess we don't need to worry about that.

**Comment by devinivy** [comment]
Yeah, that is the validation I was thinking of.  (Although technically there are other validators aside from JSONSchema implemented by the community— you could make one for yup if you wanted to, for example!)

**Comment by koskimas** [comment]
Yup, it's safe.
