### ISSUE TITLE
Filter children by parent value withGraphFetched

### ISSUE THREAD

**Issue by apemberton** [Vincit/objection.js#1753]
Sorry for the noob question: is it possible to filter a child collection based on properties from the parent?

Model:

- A (HasMany: B)
- B (HasMany: C)

```
const result = await A.query()
	.withGraphFetched('B.C')
	.modifyGraph('B.C', builder => {
	builder.where('B.C', '=', 'A.someProperty');
})
.page(page, size);
```
	
How can I filter the collection of Cs, hanging off the instances of Bs, based on a property value on A? 

I tried withGraphJoined with more success, but I need paging, so wondering if something like above is possible withGraphFetched.

**Comment by koskimas** [comment]
I don't think this is possible without using joins.
