### ISSUE TITLE
How to search the extra field on a M:M table using related queries?

### ISSUE THREAD

**Issue by cerino-ligutom** [Vincit/objection.js#1755]
Say I have an Objection model class named `Project` with a `relationMappings` definition of:

```ts
  static relationMappings: RelationMappings = {
    members: {
      relation: Model.ManyToManyRelation,
      modelClass: `${__dirname}/Employee.model`,
      join: {
        from: 'projects.id',
        to: 'employees.id',
        through: {
          from: 'project_members.projectId',
          to: 'project_members.employeeId',
          extra: ['workScheduleType'],
        },
      },
    },
  };
```

How do I query the extra field? `workScheduleType` in this case. My attempt is the snippet below. 

```ts
Project.query()
      // more where statements
      .joinRelated('members')
      .orWhere((builder) =>
        builder
          .orWhere('members.name', 'ILIKE', `%${args.search}%`)

          // The code below doesn't work
          .orWhere('members.workScheduleType', 'ILIKE', `%${args.search}%`),  
      );
```

I get the error:

> column members.workScheduleType does not exist

There's a [recipe for inserting](https://vincit.github.io/objection.js/recipes/extra-properties.html#join-table-extra-properties) but how about fetching it w/ related query? What's the objection way to achieve this?

**Comment by koskimas** [comment]
`workScheduleType` is not in the table `members` (which is an alias for `projects`) but in the table `project_members`. Actually I think you can simply leave out the table name:

```js
Project.query()
      // more where statements
      .joinRelated('members')
      .orWhere((builder) =>
        builder
          .orWhere('members.name', 'ILIKE', `%${args.search}%`)

          // The code below doesn't work
          .orWhere('workScheduleType', 'ILIKE', `%${args.search}%`),  
      );
```

**Comment by cerino-ligutom** [comment]
> `workScheduleType` is not in the table `members` (which is an alias for `projects`) but in the table `project_members`. Actually I think you can simply leave out the table name:
> 
> ```js
> Project.query()
>       // more where statements
>       .joinRelated('members')
>       .orWhere((builder) =>
>         builder
>           .orWhere('members.name', 'ILIKE', `%${args.search}%`)
>           .orWhere('workScheduleType', 'ILIKE', `%${args.search}%`),  
>       );
> ```

That worked! I guess we can omit the aliases or table names if there's no ambiguity on the column names (e.g. both tables have a column that have the same name). Will keep that in mind. Thanks!
