### ISSUE TITLE
Spread operator in upsertGraph resulting in typescript array

### ISSUE THREAD

**Issue by kennethacohen** [Vincit/objection.js#1756]
When using a spread operator inside of the `upsertGraph` call, the output type is an array, even when I'm using an object + specifying an ID in the call:

```ts
const updatedProject = await Project.query().upsertGraphAndFetch({
   id: id,
  ...graph
}, {
  relate: true,
  unrelate: true,
});
```

**Current output**: `updatedProject` is of type `Project[]`
**Expected output**: `updatedProject` is of type `Project`

Not sure if this is expected behavior so just passing along.

**Comment by koskimas** [comment]
The types first try to match the graph to a single item, if there's no match the types assume the input is an array. So I'm quessing `graph` contains something that doesn't belong to `Project` and therefore it doesn't match the single item type and you get an array.

**Comment by kennethacohen** [comment]
Got it! Fixed by creating more strict types upstream.

Thank you @koskimas! I just spent a few days converting from Sequelize => Objection and could not be happier 😄
