### ISSUE TITLE
$afterFind not working as expected 

### ISSUE THREAD

**Issue by hazee007** [Vincit/objection.js#1760]
hello everyone,
I have a delete query that set a user to false in database, i want when i use the User.query() to get all user that isActive is not false. i use $afterFind to no effect here is my code 
in my user model
`  $afterFind() {
    this.$omit({ isActive: !false });
    this.isActive = undefined;
  }`

and how can i replace use of $omit from my code i'm getting its depreciation warning in my console.
This is a beginner question i will really appreciate your answers..

**Comment by koskimas** [comment]
What are you trying to do here? All your code does, it that it sets the `isActive` property of each result row to `undefined`. The `omit` call in your code does absolutely nothing.

If you want to get all users that are active you need to do something like this

```js
const users = await User.query().where({ isActive: true })
```

**Comment by hazee007** [comment]
> What are you trying to do here? All your code does, it that it sets the `isActive` property of each result row to `undefined`. The `omit` call in your code does absolutely nothing.
> 
> If you want to get all users that are active you need to do something like this
> 
> ```js
> const users = await User.query().where({ isActive: true })
> ```

yes this works, but what i want is to do this on the instance method so i don't have to include the .where({ isActive: true }) when doing other api methods..

**Comment by koskimas** [comment]
You'll be better off just adding that manually. There are ways to do it in the model, but I don't think it's worth the hassle. See [this plugin](https://github.com/griffinpp/objection-soft-delete) for reference if you still want to do it.
