### ISSUE TITLE
Methods like 'findById' should have undefined in their return types

### ISSUE THREAD

**Issue by Kinrany** [Vincit/objection.js#1763]
Currently a snippet like

```typescript
const myModel = await MyModel.query(knex).findById(someId);
```

results in `myModel` being typed as `MyModel`.

This is not mentioned in [the docs](https://vincit.github.io/objection.js/api/query-builder/find-methods.html#findbyid), but I assume it will be `undefined` if no row with primary key `someId` exists.

In that case the returned type should be `MyModel | undefined`.

This applies to most other methods that return a single instance, like `findOne` and `first`.

**Comment by koskimas** [comment]
https://github.com/Vincit/objection.js/pull/1651
