### ISSUE TITLE
nested column as relationMapping

### ISSUE THREAD

**Issue by michellechsy** [Vincit/objection.js#1766]
When I tried to use the nested column in a json column to map the relation, it can't return any data for the relation table even there's data, and the converted SQL looks incorrect!! please help

-- relationMapping like this:
```
child: {
        relation: Model.HasOneRelation,
        modelClass: ChildTable,
        join: {
          from: ref(`ParentTable.jsonColumn:nestedCol`),
          to:  ref(`ChildTable.jsonColumn:nestedCol`)
        }
      }
```    
when query with `.eager(child)`, it can return data for the parent table with a `null` child. the converted SQL is like this:
```
select "ParentTable".* from "ParentTable" where "id" = ?   
select "ChildTable".* from "ChildTable" where "ChildTable"."jsonColumn"#>'{nestedCol}' in (?) 
```

**Comment by koskimas** [comment]
How is that generated query wrong?

**Comment by koskimas** [comment]
Could you also provide the code that fails. The actual real code that fails, not a made up example.

**Comment by koskimas** [comment]
No answer, closing. Feel free to open a new issue.

**Comment by michellechsy** [comment]
sorry, didn't notice the message. Here are the details:
We have two tables with columns like this:
Parent: {
   child: { name, **dref** }
} 
Child: {
   id, name, details: { **dref**, description }
}
We are connecting the `Child` to `Parent` via `dref`, not `id`. 
```
child: {
        relation: Model.HasOneRelation,
        modelClass: ChildTable,
        join: {
          from: ref(`Parent.child:dref`),
          to:  ref(`Child.details:dref`)
        }
      }
```
and it turns out like this
```
select "Parent".* from "Parent" where "id" = ?   
select "Child".* from "Child" where "Child"."details"#>'{dref}' in (?) 
```
**Temp fixed in my side**:
I created a DB view for the `Child` "details" column, and then it works by changing the relation to: ref(`ChildView.dref`)

**Comment by koskimas** [comment]
The query is 100% correct. There's nothing wrong here. That's the syntax for accessing nested json properties.

**Comment by michellechsy** [comment]
both the 'from' and 'to' are nested JSON properties, sure it can work?  I saw it wrong converted into SQL last time when i wrote in that way :(  

anyway, i'll try again a bit later and see if still same error, and let you know. Thanks @koskimas

**Comment by koskimas** [comment]
The ids are extracted from the fetched rows and are passed to the where in query. Rhis is not rocket science. Use the debugger or console even look at the bindings and see that they arw correct.

**Comment by michellechsy** [comment]
Or maybe can you provide a better sample for such case?? relation between nested json properties and another json properties. Either the `from` or `to` is nested properties work well, but can't be both. So I'm wondering if this is really supported underlying. 
Can you provide a sample for this?
