### ISSUE TITLE
How can I write a custom SQL query using knex with objection js?

### ISSUE THREAD

**Issue by amirhamdy** [Vincit/objection.js#1768]
`select * from products as outerQuery join
(select products_id, providers_id, price from products_providers GROUP BY products_id, price ORDER BY price DESC) as innerQuery
on outerQuery.id = innerQuery.products_id
where category_id = 1
GROUP BY products_id`

**Comment by koskimas** [comment]
```js
await Product.query()
  .alias('outerQuery')
  .join(
    ProductsProviders.query()
      .select(['products_id', 'providers_id', 'price'])
      .groupBy(['products_id', 'price'])
      .orderBy('price', 'desc')
      .as('innerQuery'),
    'outerQuery.id',
    'innerQuery.åroducts_id'
  )
  .where('category_id', 1)
  .groupBy('products_id')
```

**Comment by amirhamdy** [comment]
Hello, Thanks for your reply.

the generated query from your code is:

`select `outerQuery`.* from `products` as `outerQuery` inner join (select `products_id`, `providers_id`, `price` from `products_providers` group by `products_id`, `price` orde
r by `price` desc) as `innerQuery` on `outerQuery`.`id` = `innerQuery`.`products_id` where `category_id` = 1 group by `products_id`

but it only returns the product info without the price and the provider info. although when I run this query in SQL I get the right result.

sql query: 

`select * from products as outerQuery inner join (select products_id, providers_id, price from products_providers group by products_id, price order by price desc) as innerQuery on outerQuery.id = innerQuery.products_id where category_id = 1 group by products_id`

any idea why that happens?

**Comment by koskimas** [comment]
Oh my god. You ARE allowed to use your brains. Use `select` to select whatever you want!
