### ISSUE TITLE
Additional transaction API suggestion

### ISSUE THREAD

**Issue by elhigu** [Vincit/objection.js#177]
Today I was coding happily service method, which needed to run some code of existing instance objects in single transaction and I found out that there was no nice way to do it right now.

Thing I wanted to do would look something like this: 

```js
import objection from "objection";

class Foo {
  static async allocatePort(
    site: Site, 
    options: PortAllocationOptions, 
    oldAllocation?: VpnPortAllocation): Promise<VpnPortAllocation> {

    if (oldAllocation) {
      let extrnalPort = oldAllocation.externalPort;

      // update info to DB that we are trying to update certain port allocation
      let newAllocation = await objection.transaction(Site.knex(), function (trx) {
        await oldAllocation.$query(trx).update({ status: "removing" });
        return await VpnPortAllocation.query(trx).insert({ 
          mother: "hugger", 
          status: "new" 
        }).returning('*');
      });
    } else {
      // TODO:
    }
    return newAllocation;
  }
}
```

Current objection APIs doesn't support this, but would be nice to be able to actually give transaction, where query should be ran.

Other thing that I would like to get rid off is to actually need to import objection module, just to be able to initialize transaction. Initializing transaction is currently pretty much only reason why I ever need to import objection (in addition to model declarations ofc.).

So it would be convenient if I could access objection directly through model / model instance.

Maybe something like this: 

```js
      let newAllocation = await Site.objection.transaction(function (trx) {
        await oldAllocation.$query(trx).update({ status: "removing" });
        return await VpnPortAllocation.query(trx).insert({ 
          mother: "hugger", 
          status: "new" 
        });
      });
```

Any comments if this could make using transactions any clearer that it is right now?

**Comment by koskimas** [comment]
I like the idea that you can pass the transaction to the `query` methods. I'll implement that next. I will also make it possible to start the transaction like this:

```js
objection.transaction(SomeModel.knex(), trx => {

});
```

which is equivalent to

```js
SomeModel.knex().transaction(trx => {

});
```

I'll also add the transaction object as the last argument of the model binding version of the transaction function:

```js
objection.transaction(Person, Animal, (Person, Animal, trx) => {

});
```

I don't know about accessing objection through the Model. Feels kind of wrong, even though I can't think of any problems right now :smile:.
