### ISSUE TITLE
Missing FROM-clause entry for table "sessions"

### ISSUE THREAD

**Issue by zeeshanaligold** [Vincit/objection.js#1771]
Error => Missing FROM-clause entry for table "sessions"

Member.query()
        .withGraphFetched('sessions')
        .groupBy('membernumber')
        .sum({ turnover: 'session.turnover' })
        .orderBy('turnover', 'DESC')
        .limit(5)

**Comment by koskimas** [comment]
Error not enough words used in issue

**Comment by koskimas** [comment]
You should probably be using `withGraphJoined` or `joinRelated`.

**Comment by zeeshanaligold** [comment]
@koskimas 

There is 2 tables (Member & MemberSession). Below is the model's structure. 

class Member extends Model {
  static get tableName() {
    return 'members'
  }

  static relationMappings = {
    sessions: {
      relation: Model.HasManyRelation,
      modelClass: path.join(__dirname, 'MemberSession'),
      join: {
        from: 'members.membernumber',
        to: 'member_session.membernumber',
      },
    },
  }
}

class MemberSession extends Model {
  static get tableName() {
    return 'member_session'
  }
}

I'm trying to get 5 members order by sum(session.turnover) desc & group by membernumber.

**Comment by koskimas** [comment]
`withGraphFetched` doesn't use joins. Therefore you cannot refer to related tables like you are trying with `.sum({ turnover: 'session.turnover' })`. `joinRelated` is what you want to use here. It simply joins the relations and does nothing else.

**Comment by koskimas** [comment]
https://vincit.github.io/objection.js/api/query-builder/eager-methods.html#withgraphfetched

**Comment by koskimas** [comment]
```js
await Member.query()
  .leftJoinRelated('sessions')
  .groupBy('membernumber')
  .sum({ turnover: 'sessions.turnover' })
  .orderBy('turnover', 'DESC')
  .limit(5)
```

**Comment by zeeshanaligold** [comment]
@koskimas  Thanks.

**Comment by zeeshanaligold** [comment]
Can I conditionally add a where() clause to my query?
```
const members = await Member.query().limit(5);

if(condition === true) {
       members.where('id', '>', 5)
}
```

**Comment by zeeshanaligold** [comment]
Ok, I did it with modify method. 

```
.modify((builder) => {
     if (condition === true) {
          builder.where('id', '<=', 5)
     }
 })
```

**Comment by koskimas** [comment]
Of course you can.

```js
a.x1().x2().x3()
```

is exactly the same thing as

```js
a = a.x1()
a = a.x2()
a = a.x3()
```

Of course you can make the calls conditional.

```js
a = a.x1()
if (something) {
 a = a.x2()
}
x = a.x3()
```

this is true in all programming languages I know.

**Comment by ameinhardt** [comment]
I found  an if-else helper function in a custom query builder helpful
```javascript
if(test, fnif, fnelse) {
  return test ? fnif(this) : fnelse ? fnelse(this) : this;
}
```

**Comment by zeeshanaligold** [comment]
@koskimas Above query is working fine. I just want to make sure. Is it the perfect way?
I have to calculate the sum of turnover which is group by series of tradedate. So for the missing records on dates, it'll be zero.

```
await Session.query()
        .select(raw('coalesce(turnover,0) AS turnover'))
        .from(
          raw("generate_series('2020-07-29'::timestamp, '2020-08-29'::timestamp, '1 day') AS date")
        )
        .leftOuterJoin(
          Session.query()
            .select(
              raw('SUM(turnover) / 100 as turnover'),
              raw("DATE_TRUNC('day',tradedate) as tradedate"),
            )
            .where({ playerid })
            .where('tradedate', '>=', raw(`Now() - INTERVAL '1 month'`))
            .groupBy('tradedate')
            .as('m'),
          (query) => {
            query.on('date', '=', 'm.tradedate')
          }
        )
```
