### ISSUE TITLE
Preventing duplicate entries in join tables

### ISSUE THREAD

**Issue by Aposhian** [Vincit/objection.js#1772]
I want to prevent duplicate entries from being inserted into my join table.

I would like to make my join table for a many-to-many relation have a unique composite key to prevent duplicate insertions by `relate` queries.

I can do that in [MySQL](https://dev.mysql.com/doc/refman/8.0/en/partitioning-limitations-partitioning-keys-unique-keys.html) with the UNIQUE KEY constraint.

Is there a way to specify this in the [relations definition](https://vincit.github.io/objection.js/guide/relations.html)?

Then I would like to figure out how to use `relate` to perform an idempotent insert (i.e. with `INSERT IGNORE` in MySQL). Is this possible, or do I need to do a raw insert on the join table?

**Comment by sayhicoelho** [comment]
I just implemented a method for BaseModel to sync many-to-many data without dups.

BaseModel.js
```js
class BaseModel extends Model {
  static async sync({ relate, for: forId, ids }) {
    const promises = ids.map(id => this.query()
      .findById(forId)
      .whereExists(this.relatedQuery(relate).where(`${relate}.id`, id))
      .resultSize())

    const existence = await Promise.all(promises)
    const safeIds = ids.filter((_, i) => !existence[i])

    if (safeIds.length > 0) {
      await Promise.all(safeIds.map(id => this.relatedQuery(relate)
        .for(forId)
        .relate(id)))
    }
  }
}
```

Example:

```js
const postId = 1
const tagIds = [10, 12]

await Post.sync({
  relate: 'tags',
  for: postId,
  ids: tagIds,
})
```
