### ISSUE TITLE
Returning with Postgres

### ISSUE THREAD

**Issue by danilodeveloper** [Vincit/objection.js#1773]
Hello guys!
I'm trying to use `returning` function but objection is ignoring what I would like to return. I tried the same query on the same DB with Knex (without Objection) and worked properly.

```js
fields.password = await PasswordUtils.generateHash(password);
fields.email = email;
fields.firstName = firstName;
fields.lastName = lastName;
fields.photoProfileURL = photoProfileURL;
fields.userPublicId = await PublicIdGenerator.generate();

let newUser = await User.query()
      .returning(['userPublicId'])
      .insert(fields)
      .debug();
```
The Objection code above generated a query that should works:
```js
{
  method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [
    '160@gmail.com',
    'first,
    'last',
    'asdffdsaasdffdsaasdf,
    'https://via.placeholder.com/150',
    'p0JgZFUrx'
  ],
  __knexQueryUid: '93969f30-ae75-11ea-a678-dd25528d8462',
  sql: 'insert into "server-core"."users" ("email", "firstName", "lastName", "password", "photoProfileURL", "userPublicId") values (?, ?, ?, ?, ?, ?) returning "userPublicId"',
  returning: [ 'userPublicId' ]
}
```
But Objection is returning a complete object after execute the query, ignoring the `returning` asking to return only the `userPublicId`

```
Database - PostgreSQL 10;
Objection - ^2.2.0
Knex - ^0.21.1
pg - ^8.2.1
```

Tks!

**Comment by koskimas** [comment]
Objection returns the input object **plus** the fields listed in `returning`.

**Comment by danilodeveloper** [comment]
humm... I got it.
Just to clarify, why Knex return only the field informed in `returning`? Objection shouldn't have same return as Knex? I mean, return only what is asked in `returning`.

I saw that Objection have a deprecated `pick` method, so what I should use to return only what I want?

Sorry for the question, I'm an old Knex user but a 2 days Objection user :).
Tks!!
