### ISSUE TITLE
Shouldn't .patch() trigger $beforeUpdate or maybe $beforePatch hooks?

### ISSUE THREAD

**Issue by shashank1010** [Vincit/objection.js#1775]
I'm new to objection.js and backend development as a whole.
Objection JS makes my job really easy.

My query is.
When I insert an object into the DB, $beforeInsert and $afterInsert hooks is called on the model instance.
Similar is the case when I update an object.
From the documentation, I derived i could do something like this.

In the $beforeInsert hook
`this.createdAt = new Date();`

In the $beforeUpdate hook
`this.updatedAt = new Date();`

For the most cases, patch makes sense; and as such it has been recommended and rightly documented after a discussion in one of the issues a long time ago.
A patch is an update on the row and I would like to update the updatedAt property on a patch query. However, this does not happen.
Is this the intended behaviour? Is there a work around other than the messy and repetitive redundant duplication wherever I perform a patch query?
In my opinion, either we should have a $beforePatch hook or the $beforeUpdate hook should be called and the after counterpart for the same as well.

Thanks.

**Comment by koskimas** [comment]
$beforeUpdate does get called.

**Comment by shashank1010** [comment]
My bad. I had wrong implementation.
Tested it all over again and it works absolutely fine.
$beforeUpdate hook is called.
