### ISSUE TITLE
example of eager loading from both sides of belongsToOne and hasOne

### ISSUE THREAD

**Issue by panigrah** [Vincit/objection.js#1776]
I am not able to figure out from the documentation how to eager load 1:1 relationships from both sides of the relationship. All the examples are for 1:n and m:n situations.

Please share any examples of eager loading for either loading from the left side or the right side of relationship. e.g. user has one profile. 

How do I load the profile with the user or the user with the profile?

thanks

**Comment by koskimas** [comment]
You need to create the relation to both models.

**Comment by panigrah** [comment]
@koskimas so I would do a `BelongsToOneRelation` on the source and then `HasOneRelation` on the parent with the `to` and `from` flipped?

thanks!

**Comment by koskimas** [comment]
Yep, exactly like that.
