### ISSUE TITLE
$query().patch mutates model instance and also removes other fields

### ISSUE THREAD

**Issue by prolificrohit** [Vincit/objection.js#1777]
I am migrating my code from version 1.x to version 2.x and saw a weird problem with the patch function which looks like a breaking change but nothing seems to be mentioned about it in the [migration doc](https://vincit.github.io/objection.js/release-notes/migration.html)

Minimal Code:
```
// person is a model instance
console.log("Before", person);
person.$query().patch({first_name: 'prolific'});
console.log("After", person);
```

Before Patch:
```
Before Person {
  id: 1,
  first_name: 'Rohit',
  last_name: 'Agarwal'
}
```

After Patch in v1.6:
```
After Person {
  id: 1,
  first_name: 'prolific',
  last_name: 'Agarwal'
}
```

After Patch in v2.2:
```
After Person {
  id: undefined,
  first_name: 'prolific',
  last_name: undefined
}
```

Once the patch is executed the original model instance mutates and all the old fields are set to undefined (including the primary field 'id') while keeping only the data that is patched.

**Expected Behavior:**
Either the model instance should mutate while keeping the old fields and patching the new fields (like in v1.x) OR the model should not mutate at all (which I personally would not like but makes sense if decided). Current behavior (in v2.x) seems odd because it is both mutating as well deleting the old fields.

I really hope I am not doing anything wrong but do let me know if I am.

PS: Just want to thank for creating such a wonderful ORM which does exactly what it is suppose to do and doesn't get in the way when something complex is needed to be done. Simple yet powerful :)

**Comment by prolificrohit** [comment]
@koskimas Please do let me know know if any further information is needed. I have tried this multiple times but getting the same output. Do you believe it must be an error on my end only?

**Comment by abedmurrar** [comment]
use [patchAndFetch](https://vincit.github.io/objection.js/api/query-builder/mutate-methods.html#patchandfetch)

**Comment by prolificrohit** [comment]
> use [patchAndFetch](https://vincit.github.io/objection.js/api/query-builder/mutate-methods.html#patchandfetch)

@abedmurrar I am not saying that the return type of the function should be different. What I am saying is that there is a bug where the original model instance is getting mutated (and in the wrong way) in the newer version. (It was working correctly in version 1.x). I don't want to fetch. I already had all the data which is lost due to query which doesn't seem correct.

For example the below code will fail:
```
// person is a model instance
person.$query().patch({first_name: 'prolific'});
person.$query().delete(); // Error
```
This fails simply because the patch query has mutated the person instance and removed all the fields except 'first_name' including the primary key 'id' which was needed to delete the instance. This is just one example of the other issues it may cause.

On top of all this, nothing is mentioned regarding this on the migration guide (from 1.x to 2.x) so it was a design decision for some reason then at least it should be documented.

Please let me know if I have misunderstood you or thinking in the wrong direction.

**Comment by prolificrohit** [comment]
Hey @koskimas, can you please look into this and tell if it is really a issue or not?

**Comment by vvo** [comment]
I think this can be closed. This is a TypeScript/babel configuration issue.
