### ISSUE TITLE
AWS Redshift "returning" Syntax Error

### ISSUE THREAD

**Issue by dmahler26** [Vincit/objection.js#1779]
It seems that all insert queries auto-include a return of at least the table key. AWS Redshift does not support the RETURNING operation, so I am consequently unable to perform any `insert()` queries using the Model class. For example, executing a query such as:
```js
Person.query().insert(record)
```
Results in the error:
```
insert into "persons" ("key", "value") values ($1, $2) returning "key" - syntax error at or near "returning"
```
I had hoped using `insertAndFetch()` might circumvent this issue but I encountered the same error. Glancing through the repo it appears this reuses the base `insert()` method (with it's auto-returning logic) before performing the 2nd query.

Perhaps I'm missing something in the docs somewhere but I cannot find a way to disable this - attempts at providing an empty array parameter (e.g. `insert(record, [])` or `insert(record).returning([])`) still resulted in the error above. The only workaround I've found so far is utilizing the Knex instance directly, e.g.:
```js
Person.knex()('persons').insert(record, [])
```
But it would be preferable to leverage the Model class directly and have some means of disabling the auto-inclusion of the returning operation or have the `insertAndFetch()` method skip it entirely given the explicit redundancy.

```
objection: 2.1.3
knex: 0.20.13
pg: 8.2.1
```

Thanks!

**Comment by koskimas** [comment]
Since redshift is using the postgres driver, there's no way for objection to detect that you are not actually using a real postgres db.

**Comment by russelldc** [comment]
Is there any cleaner way to skip the `returning` part when using `insert()` than what @dmahler26 had provided as a workaround at the end of his post?
