### ISSUE TITLE
Can I hide the plain meaningless number in SQL from higher layer module?

### ISSUE THREAD

**Issue by k7** [Vincit/objection.js#178]
Thank you for your time.

In my project, I want to hide the plain meaningless number in SQL from higher layer module.

for example,  in my account table, `status = 1` means that the account is active.

but I want to query it in the higher layer module, just use  
```javascript
Account.query().where('status', '=', 'active') 
```
and it should translate to SQL 
```SQL
select * from account_table where status = 1;
```

How can I do this?

Thank you very much again!

**Comment by koskimas** [comment]
I think you should create an "enum" for this like so:

```js
const AccountStatus = {
  Active: 1,
  Inactive: 2
};

// You can store it for example in the Account model for easy access.
Account.Status = AccountStatus;

// Then you can use it like this.
Account.query().where('status', Account.Status.Active);
```

There is no way (that I know of) to add the mapping to objection or knex.

**Comment by k7** [comment]
@koskimas thank you. I have already use this method.  

However, it is not a perfect solution, because if someone does not follow this rule, there is no error throw to warn him/her.

**Comment by koskimas** [comment]
That's the problem with dynamic languages. I don't think adding this kind of mapping layer to objection is a good idea. It would require a lot of work. We would need to replicate the knex methods to objection and maintain them. Currently most of the query methods simply do something like this:

```js
knexBuilder[methodName].apply(knexBuilder, arguments);
```

so we don't have to understand what each argument is. To implement the mapping we would need to understand which of the arguments need to be mapped.
