### ISSUE TITLE
Has any way to automatic generate models with existent data?

### ISSUE THREAD

**Issue by geovanipfranca** [Vincit/objection.js#1780]
In the last moments i was using Sequelize and they had a lib called *Sequelize Auto*, in that lib theirs automatically generated the model using the data based in connected database.

I wanna to know if the objection has some lib to make the something like that, but creating the model for Objection.js

Sorry for everyone reading this text, i am really bad in english!

**Comment by koskimas** [comment]
Nope. There might be a 3rd party plugin for this, but I'm not aware of one.
