### ISSUE TITLE
Concatenating map function is not working

### ISSUE THREAD

**Issue by roggervalf** [Vincit/objection.js#1782]
Hi, I'm using the latest version of this package on one of my project and looking on its documentation, appears map function here:
https://vincit.github.io/objection.js/api/query-builder/other-methods.html#map
I tried in this way:
```js
const userNames=await User.query().map((user=>user.name))
```
As I see now, I avoid using pluck since is going to be deleted in the next version (3v), so I would like to know if this function should be deprecated too, so docs should be updated, or just am I using it in a wrong way?`

**Comment by koskimas** [comment]
That method has been removed in 2.0 version. I forgot to remove the documentation.

**Comment by roggerval** [comment]
@koskimas thank you for the quick response.

**Comment by roggervalf** [comment]
Thank you @koskimas for the quick response.
