### ISSUE TITLE
Automate publishing and changelog generation

### ISSUE THREAD

**Issue by roggervalf** [Vincit/objection.js#1786]
This is a question, in order to automate the changelog generation I'm using [semantic-release](https://www.npmjs.com/package/semantic-release). In case sounds good to you, I could make a PR for this config. I have some repos where I set it, i.e: [here](https://github.com/roggervalf/iam-policies). In case not, feel free to close this issue.
Thank for maintaining this package.

**Comment by koskimas** [comment]
Thanks for the offer, but I don't think that's a good fit for objecction.
