### ISSUE TITLE
Custom returning object for the pagination

### ISSUE THREAD

**Issue by Naeoth** [Vincit/objection.js#1789]
Hi ! I'm using the pagination and I would like to modify the returning object.

What I have:
```javascript
const result = await Person.query()
  .where('age', '>', 20)
  .page(5, 100);

console.log(result);
/*
{
  results: [...],
  total: 10
}
*/
```

What I would like to have:
```javascript
const result = await Person.query()
  .where('age', '>', 20)
  .page(5, 100);

console.log(result)
/*
{
  data: [...],
  size: 5,
  total: 10
}
*/
```

The best option I think, should be the possibility to override the [RangeOperation](https://github.com/Vincit/objection.js/blob/9cae4b8a72d7d2595e02445236c6b9b1f2aef93d/lib/queryBuilder/operations/RangeOperation.js) with the `onAfter3` method to modify the returning object. But this builder is not exported by the package. What would be the best solution ?

**Comment by koskimas** [comment]
You can override the `page` method like this

```js
class CustomQueryBuilder extends Model.QueryBuilder {
  page(page, size) {
    return super.page(page, size).runAfter(result => ({...result, size}));
  }
}
```

See [this recipe](https://vincit.github.io/objection.js/recipes/custom-query-builder.html) about extending the query builder.

**Comment by Naeoth** [comment]
Thanks, it works like a charm !
