### ISSUE TITLE
contradicting docs on $relatedQuery

### ISSUE THREAD

**Issue by ameinhardt** [Vincit/objection.js#1790]
In the documentation of [$relatedQuery()](https://vincit.github.io/objection.js/api/model/instance-methods.html#relatedquery), it suggests that
>  By default, any fetched or inserted items are also stored to the owner model’s property

Whereas it is actually defaults to false as indicated in [relatedInsertQueryMutates](https://vincit.github.io/objection.js/api/model/static-properties.html#static-relatedinsertquerymutates)
> The default is false.

Is the suggested way to insert properties to db and model also now to do it manually?

**Comment by koskimas** [comment]
The docs need updating. Thanks for bringing this up. Since objection 2.0, model instances are no longer mutated and the `relatedInsertQueryMutates` method will be removed in 3.0. So yeah, you need to assign/push the item to the model's relation manually.
