### ISSUE TITLE
Using the join table in a many-to-many relation in a query?

### ISSUE THREAD

**Issue by Linksku** [Vincit/objection.js#1792]
I have the tables `posts`, `users`, and `users_posts`. The relation for the Post model is:

```
      users: {
        relation: Model.ManyToManyRelation,
        modelClass: require('./User').default,
        join: {
          from: 'posts.id',
          through: {
            from: 'users_posts.postId',
            to: 'users_posts.userId',
          },
          to: 'users.id',
        },
      },
```

If I want to get all the posts by a user, I can do:

`Post.query.joinRelated('users').where('users.id', userId);`

However, I don't actually need to join the `users` table, all I need is the `users_posts` table. Is there a way to use the join table in this relation? It's pretty easy to define a new one-to-many relation or just use the Knex builder, but it'll be cleaner if I could leverage the existing many-to-many relation.

**Comment by koskimas** [comment]
The join table is joined, so you can refer to it's columns. If their names are unambiquous you don't even need to prefix the column with the table name.
