### ISSUE TITLE
Can i do this in relation??

### ISSUE THREAD

**Issue by V4LC1R** [Vincit/objection.js#1794]
```js
company:{
                relation:Model.ManyToManyRelation,
                modelClass:User,
                join:{
                     from:'users.id',
                     through:{
                         from:'contracts.company_id',
                         to:'contracts.deliveryman_id'
                    },
                     to:'users.id'
                },
                 join:{
                     from:'users.id',
                      through:{
                         from:'contracts.company_id',
                         to:'contracts.deliveryman_id'
                    },
                    to:'users.id'
                }
            }
```

**Comment by V4LC1R** [comment]
pois um usuario com previlegios de empresa, contrata outro usuario com previlegios de entregador.

mas antes de  contratar ele precisa fazer uma proposta

se aceita gera um contrato

ou seja contratos(user.id=contract.company_id,user.id=contract.deliveryman)
tenders(user.id=tenders.company_id,user.id=tenders.deliveryman

**Comment by V4LC1R** [comment]
because a user with company privileges hires another user with delivery person privileges.

but before hiring he needs to make a proposal

if accepted generates a contract

ie contracts (user.id = contract.company_id, user.id = contract.deliveryman)
tenders (user.id = tenders.company_id, user.id = tenders.deliveryman)

**Comment by koskimas** [comment]
No, unfortunately you cannot.

**Comment by V4LC1R** [comment]
then will i have to create a new relationship statement ??

**Comment by koskimas** [comment]
?

**Comment by V4LC1R** [comment]
company:{
                relation:Model.ManyToManyRelation,
                modelClass:User,
                join:{
                     from:'users.id',
                     through:{
                         from:'contracts.company_id',
                         to:'contracts.deliveryman_id'
                    },
                     to:'users.id'
                },
                 join:{
                     from:'users.id',
                      through:{
                         from:'contracts.company_id',
                         to:'contracts.deliveryman_id'
                    },
                    to:'users.id'
                }
            }

proposal_company:{
                relation:Model.ManyToManyRelation,
                modelClass:User,
                join:{
                     from:'users.id',
                     through:{
                         from:'contracts.company_id',
                         to:'contracts.deliveryman_id'
                    },
                     to:'users.id'
                },
                 join:{
                     from:'users.id',
                      through:{
                         from:'contracts.company_id',
                         to:'contracts.deliveryman_id'
                    },
                    to:'users.id'
                }
            }

**Comment by koskimas** [comment]
?

**Comment by koskimas** [comment]
'use strict';

const { inheritModel } = require('./inheritModel');
const { staticHiddenProps } = require('./modelUtils');
const { defineNonEnumerableProperty } = require('./modelUtils');

function bindKnex(modelClass, knex) {
  let BoundModelClass = getBoundModelFromCache(modelClass, knex);

  if (BoundModelClass === null) {
    BoundModelClass = inheritModel(modelClass);
    BoundModelClass = copyHiddenProperties(modelClass, BoundModelClass);

    BoundModelClass.knex(knex);

    BoundModelClass = putBoundModelToCache(modelClass, BoundModelClass, knex);
    BoundModelClass = bindRelations(modelClass, BoundModelClass, knex);
  }

  return BoundModelClass;
}

function getBoundModelFromCache(modelClass, knex) {
  const cache = getCache(knex);
  const cacheKey = modelClass.uniqueTag();

  return cache.get(cacheKey) || null;
}

function getCache(knex) {
  if (!knex.$$objection) {
    createCache(knex);
  }

  return knex.$$objection.boundModels;
}

function createCache(knex) {
  defineNonEnumerableProperty(knex, '$$objection', {
    boundModels: new Map()
  });
}

function copyHiddenProperties(modelClass, BoundModelClass) {
  for (const prop of staticHiddenProps) {
    // $$relations and $$relationArray are handled in separately.
    if (modelClass.hasOwnProperty(prop) && prop !== '$$relations' && prop !== '$$relationArray') {
      defineNonEnumerableProperty(BoundModelClass, prop, modelClass[prop]);
    }
  }

  return BoundModelClass;
}

function putBoundModelToCache(modelClass, BoundModelClass, knex) {
  const cache = getCache(knex);
  const cacheKey = modelClass.uniqueTag();

  cache.set(cacheKey, BoundModelClass);
  return BoundModelClass;
}

function bindRelations(modelClass, BoundModelClass, knex) {
  const boundRelations = Object.create(null);
  const boundRelationArray = [];

  for (const relationName of modelClass.getRelationNames()) {
    const relation = modelClass.getRelation(relationName);
    const boundRelation = relation.bindKnex(knex);

    boundRelations[relation.name] = boundRelation;
    boundRelationArray.push(boundRelation);
  }

  defineNonEnumerableProperty(BoundModelClass, '$$relations', boundRelations);
  defineNonEnumerableProperty(BoundModelClass, '$$relationArray', boundRelationArray);

  return BoundModelClass;
}

module.exports = {
  bindKnex
};
