### ISSUE TITLE
JoinMethod typescript interface problems.

### ISSUE THREAD

**Issue by xjuanc** [Vincit/objection.js#1795]
JoinMethod interface doesn't accept a callback as a first argument. Knex does. 

I've manage to allow it locally on my project with the following code:

```
interface JoinMethod<QB extends AnyQueryBuilder> {
    (table: TableRef, leftCol: ColumnRef, op: Operator, rightCol: ColumnRef): QB;
    (table: TableRef, leftCol: ColumnRef, rightCol: ColumnRef): QB;
    (table: TableRef, cb: CallbackVoid<Knex.JoinClause>): QB;
    (table: TableRef, raw: Raw): QB;

    (table: CallbackVoid<QB>, leftCol: ColumnRef, op: Operator, rightCol: ColumnRef): QB;
    (table: CallbackVoid<QB>, leftCol: ColumnRef, rightCol: ColumnRef): QB;
    (table: CallbackVoid<QB>, cb: CallbackVoid<Knex.JoinClause>): QB;
    (table: CallbackVoid<QB>, raw: Raw): QB;

    (raw: Raw): QB;
  }
```
But it's kinda tedious to do so everytime I have to npm i dependencies

**Comment by koskimas** [comment]
Can't you still pass a query builder as the first argument with the current typings? There's no need to use a callback.

**Comment by xjuanc** [comment]
You're right, a QueryBuilder is accepted but since we already had a lot of huge queries made with Knex, and since objection  is built upon it, we were hoping we could use kind of the same sintax for that kind of things.

Thanks for answering and great tool you've built here. Amazing job.

**Comment by koskimas** [comment]
Thank you! I'll also add the callback versions since knex supports them.
