### ISSUE TITLE
Using Objection model in Knex migration throws an error

### ISSUE THREAD

**Issue by Ali-Dalal** [Vincit/objection.js#1796]
I have the following migration
```js
const Person = require('./models/person');
exports.up = function (knex) {
    return Person.query().insert({
        name: 'John'
    });
};

exports.down = function (knex) {
 //do something else
};
```
the code throwing an error like the following:
```
migration file "20200709092607_add_john_to_persons.js" failed
migration failed with error: insert into "persons" ("created_at", "name") values ($1, $2) returning "id" - relation "persons" does not exist
```
although there is another migration before that one to create persons table.

trying the same migration with `knex('persons).insert` work as expected.

I am curious to understand why this happens.

Thanks

**Comment by koskimas** [comment]
You shouldn't use models in migrations. Migrations should never ever change while models evolve with the project.

**Comment by koskimas** [comment]
Also inserting stuff in migrations is kind of a bad idea. Sometimes you need to do things like that when you migrate a table into another for example, but most of the time it should be avoided.

**Comment by koskimas** [comment]
The error isn't caused by objection by the way. You simply don't have the `persons` table created at that point. But that's irrelevant. Just don't use anything that can change in migrations.
