### ISSUE TITLE
how to change skipFetched default to true?

### ISSUE THREAD

**Issue by capaj** [Vincit/objection.js#1797]
Sorry about spamming weird questions, but we're using Objection in a way where we basically always want to ignore an already fetched relation. Now we could go ahead and litter our codebase with `{skipFetched: true}`, but I was wondering-could we override it globally? Other than extending the objection model and aliasing methods that take this config on our own model?

**Comment by koskimas** [comment]
You should be able to set it in `Model.defaultGraphOptions` object.
