### ISSUE TITLE
Make type definition for `.first()` additionally return undefined

### ISSUE THREAD

**Issue by llamadeus** [Vincit/objection.js#1800]
Currently calling `.first()` on a query builder suggests that the return value is always of a non-`undefined` value which is not true if the query did not match any records (or the table is empty ofc).

My suggestion is to replace 
`SingleQueryBuilderType: QueryBuilder<M, M>;` with 
`SingleQueryBuilderType: QueryBuilder<M, M | undefined>;`
within [typings/objection/index.d.ts](https://github.com/Vincit/objection.js/blob/master/typings/objection/index.d.ts#L1153).

**Comment by koskimas** [comment]
https://github.com/Vincit/objection.js/pull/1651

**Comment by llamadeus** [comment]
Sorry for the "repost". I only checked open issues before opening this one.
