### ISSUE TITLE
Broken link to 'ref' in documentation

### ISSUE THREAD

**Issue by shashank1010** [Vincit/objection.js#1801]
A link to 'ref' on the page https://vincit.github.io/objection.js/recipes/subqueries.html takes the user to https://vincit.github.io/api/objection.js#ref which gives a 404 error.

Following is the line containing the link.
`You can use ref to reference the parent query in subqueries:`

**Comment by koskimas** [comment]
Thanks! I'll fix that soon.

**Comment by shashank1010** [comment]
I think I found the right file to make this fix, if needed I can raise a PR

**Comment by koskimas** [comment]
Fixed in #1802
