### ISSUE TITLE
Table `table` specified more than once when using HasOneThroughRelation

### ISSUE THREAD

**Issue by noiarek** [Vincit/objection.js#1803]
Hey team, really nice product here :)

I'm currently having two issues and hopefully you're able to give me a hand. 

1. I defined this relation
```
manager: {
        relation: Model.HasOneThroughRelation,
        modelClass: User,
        join: {
          from: 'forms.employeeId',
          through: {
            from: 'users.id',
            to: 'users.reportingManagerPayglobalUsername',
          },
          to: 'users.reportingManagerPayglobalUsername'
        }
```
when using `withGraphFetched('[manager]')` I get an error from postgres. The error is Table name specified more than once
```
db_1       | 2020-07-26 02:44:52.624 UTC [641] ERROR:  table name "users" specified more than once
db_1       | 2020-07-26 02:44:52.624 UTC [641] STATEMENT:  select "users".*, "users"."u" as "users", "users"."reporting_manager_payglobal_username" as "objectiontmpjoin0" from "users" inner join "users" on "users"."reporting_manager_payglobal_username" = "users"."id" where "users"."reporting_manager_payglobal_username" in ($1)
```

So it seems to solve this I would have to add an alias in the `through`. Is it currently possible to do this? 

2. Is it possible to do an insert and retrieve the relations when using returning?

i.e (simplified to better understanding)

```
        const data = {employeeId: 20}

         ...
        .insertGraph(data)
        .returning("*");
```

and in the entity

```
employee: {
        relation: Model.BelongsToOneRelation,
        modelClass: User,
        join: {
          from: "forms.employeeId",
          to: "users.id"
        }
```

is it possible to somehow do `returning('*')` and get

```
{
  employeeId: insertedId
  employee: HydratedObject {}
}

```

Rather than doing 2 queries, inserting and then retrieving via `withGraphFetched()` ?

Please let me know if my examples are clear enough :)

Cheers!

**Comment by koskimas** [comment]
1. The relation you defined should actually be a `HasOneRelation` like this:

```js
manager: {
        relation: Model.HasOneRelation,
        modelClass: User,
        join: {
          from: 'forms.employeeId',
          to: 'users.id'
        }
}
```

Joining `reportingManagerPayglobalUsername` to itself does nothing.

2. You should be able to simple add `.returning('*')`

**Comment by noiarek** [comment]
Hi @koskimas , I appreciate your prompt answers!

About 1.

I've noticed I've made a mistake in the code. This is the correct one

```
manager: {
        relation: Model.HasOneThroughRelation,
        modelClass: User,
        join: {
          from: 'forms.employeeId',
          through: {
            to: 'users.id',
            from: 'users.reportingManagerPayglobalUsername',
          },
          to: 'users.payglobalUsername'
        }
```

The relation I'm looking for is a double join. `Form` table has a field called `employeeId` and I want to get the manager of that employee doing a second from join with the fields `payglobalUsername` and  `reportingManagerPayglobalUsername`. 

I guess I'm looking for something like this (sorry if the sql is incorrect)

```
Select form.*, u2.*
join user u1 on form.employee_id = u1.id
join user u2 on u1.reporting_manager_payglobal_username = u2.payglobal_username
```

And the result something like this:

```
Form Object
{
FormPropertyN1: Value
FormPropertyN2: Value
...
Manager: ResultOfU2Query
}
```

However, after I fixed my code I still can see the same error. The query looks sort of correct but it complains because the join doesn't have an alias.

```
db_1       | 2020-07-26 09:25:39.791 UTC [1048] ERROR:  table name "users" specified more than once
db_1       | 2020-07-26 09:25:39.791 UTC [1048] STATEMENT:  select "users".*, "users"."id" as "objectiontmpjoin0" from "users" inner join "users" on "users"."payglobal_username" = "users"."reporting_manager_payglobal_username" where "users"."id" in ($1)
```

Any ideas about that one?

About 2.

Even though I use `.returning('*')`, it doesn't return the entity (Form) with the hydrated relations. It will come back with `employeeId` but not with the `Employee` object, only if I query via `withGraphFetched()`. Do you know if I need to set somehow something like "Every time this entity is called, bring all the relations"

**Comment by ArtReeX** [comment]
My solution:

CREATE OR REPLACE VIEW users_clone AS select * FROM users;

Then:

manager: {
        relation: Model.HasOneThroughRelation,
        modelClass: User,
        join: {
          from: 'forms.employeeId',
          through: {
            to: 'users_clone.id',
            from: 'users_clone.reportingManagerPayglobalUsername',
          },
          to: 'users.payglobalUsername'
        }
