### ISSUE TITLE
beforeInsert args.items and args.inputItems are both empty

### ISSUE THREAD

**Issue by dmahler26** [Vincit/objection.js#1806]
```
objection: 2.1.3
knex: 0.20.13
pg: 8.2.1
```
I am trying to implement some validation via the `Model.beforeInsert()` static method. When building/running a basic query as such:
```
await MyModel.query(trx).insertAndFetch(myModelObj)
```
Running with the debugger I see that `static beforeInsert(args) {}` on the model class get invoked, but the incoming `args.items` and `args.inputItems` are both empty arrays. From my understanding of the docs, I would have expected `args.inputItems` to contain the objects I am attempting to insert.

I tested this same query out using the plain `insert()` query method instead, and `args.itemInputs` had the object as expected (i.e. `[MyModel]`), so it seems this is an issue specific to the `insertAndFetch()` method not having args propagated correctly.

**Comment by dmahler26** [comment]
Quick update: both the model instance `$beforeInsert` and static `beforeInsert` methods appear to get invoked (in that order) when executing `insertAndFetch`. I can successfully implement validation using the $beforeInsert method (`this` has access the model instance, as expected), so that is at least a workaround for the issue.

However, this still seems counter to what is described in the docs regarding [static query hooks](https://vincit.github.io/objection.js/guide/hooks.html#static-query-hooks) and `beforeInsert` being the appropriate method for a query such as `Model.query().insertAndFetch({ ... })`. Additionally, the workaround above is fine for individual model validation, but batch processing of all models being inserted will not be possible without use of `beforeInsert` and access to `items` and/or `inputItems` arguments.

**Comment by lehni** [comment]
@dmahler26 I believe this is the same issue as #1839 which I fixed today in #1841. Could you confirm that this fixes your issues?

**Comment by lehni** [comment]
@dmahler26 could you check if this resolves it? thanks!

**Comment by lehni** [comment]
@koskimas pretty sure this has been fixed by #1841, I'd close in the absence of new info

**Comment by mercteil** [comment]
I use upsert:

```javascript
export const upsertOrder = payload =>
  transaction(Orders.knex(), trx =>
    Orders.query(trx).upsertGraph(payload, { relate: true, unrelate: true })
  );
```

and a m2m relationship in Order:

```javascript
 vouchers: {
      relation: Base.ManyToManyRelation,
      modelClass: path.resolve(__dirname, 'Vouchers'),
      join: {
        from: 'orders.id',
        through: {
          modelClass: path.resolve(__dirname, 'OrderVouchers'),
          from: 'order_vouchers.order_id',
          to: 'order_vouchers.voucher_id',
        },
        to: 'vouchers.id',
      },
    },
```


In OrderVouchers `static hooks` everything is empty or undefined

```javascript
static beforeInsert({ items, inputItems, relation }) {
    console.log(items, inputItems, relation);
  }

  static beforeDelete({ items, inputItems, relation }) {
    console.log(items, inputItems, relation);
  }

  static afterDelete({ items, inputItems, relation }) {
    console.log(items, inputItems, relation);
  }
```

**Comment by koskimas** [comment]
@mercteil You need to use `asFindQuery()` in the `beforeDelete` hook. Obviously before insert of after insert, there's nothing to fetch and the result is empty or garbage. `items` is supposed to be empty in all those situations and `inputItems` is only populated under very specific circumstances where the models have already been fetched before the delete operation.
