### ISSUE TITLE
Feature request:  function(builder) for Having similar to where

### ISSUE THREAD

**Issue by nogurenn** [Vincit/objection.js#1807]
Hello! I found myself wanting to do a pattern like the one below. My `where` is mostly just the same pattern, which is possible because i can process the potential `where`s inside the function. I thought it would work similarly for having, but I sadly disproved myself.

```js
Paper.query()
  .select('papers.*')
  .max('versions.versionYear as latestYear')
  // join ......
  .having(b => {
    if (filters.fromYear)
      b.having('latestYear', '>=', filters.fromYear)

    if (filters.toYear)
      b.having('latestYear', '<=', filters.toYear)
  })
```

**Comment by koskimas** [comment]
You can use `modify`.
