### ISSUE TITLE
How to update an array of items at once with a unique constraint

### ISSUE THREAD

**Issue by austinthetaco** [Vincit/objection.js#1809]
This is almost certainly something with me not understanding the library, but I keep running into a unique constraint for my sort_order column. I'm trying to update (and add) all the records at once with their new updated sort order by passing it in an upsertGraphAndFetch. What's the proper way to deal with this?

i.e. my db has:
`[{ name: "austin", sort_order: 0}, {name: "tim", sort_order: 1}]`

and I'm trying to upsert:
`[{ name: "austin", sort_order: 1}, {name: "tim", sort_order: 0}, {name: "john", sort_order: 2 }]`
but it immediately says i violated the constraint for sort_order.

**Comment by koskimas** [comment]
There is no way to do that without disabling the constraint. Remove the unique constraint. How useful is it anyway in this case?

**Comment by austinthetaco** [comment]
@koskimas It's useful in that it prevents other calls to the table (i.e. posting a single record) doesn't collide.
