### ISSUE TITLE
Writing a plugin, how to know it is a main query in the builder instance?

### ISSUE THREAD

**Issue by winsontam** [Vincit/objection.js#1811]
I am writing a plugin.
I want to decorate the main query by appending a where condition.
I follow the plugin tutorial to extend the QueryBuilder.
My question is can i know that it is a Main Query from the QueryBuilder instance?
Because if i extend QueryBuilder will affect the Sub Query as well.
But i don't want to change the sub query.

**Comment by koskimas** [comment]
There's no way to do that. See this example:

```js
const query1 = Person.query().where('id', 1)
const query2 = Person.query().whereIn('id', query1)
const result = await query2;
```

There is no possible way to know if the query is going to be executed or not by the time the `where` gets called.
