### ISSUE TITLE
Add documentation for QueryBuilder toFindQuery()

### ISSUE THREAD

**Issue by TehNrd** [Vincit/objection.js#1812]
This is a super useful method, especially when doing access/permission checks before performing the operation of a query, but I noticed it is not documented.

The method is public on the Querybuilder and I hope it is okay to use this method and the lack of documentation was only an oversight and not with the intention to discourage its use.

I'll try to get a PR at some point, but pretty slammed with work at the moment and wanted to at least get this issue created in case anyone else wanted to fix the documentation.

**Comment by koskimas** [comment]
It's not public at the moment, but I don't see any reason why we shouldn't make it public. A PR would be great! All we need is documentation and typescript types, which should be trivial.

**Comment by koskimas** [comment]
Actually we need a bunch of tests for all kinds of queries before we can make `toFindQuery` public.

* All $relatedQuery versions (relate, unrelate, update, insert, etc.) for ALL relation types.
* upsertGraph
* updateAndFetch
* and so on.
