### ISSUE TITLE
Dumb question: do I need to pass transaction to asFindQuery?

### ISSUE THREAD

**Issue by JaneJeon** [Vincit/objection.js#1815]
So in https://vincit.github.io/objection.js/api/types/#type-statichookarguments, under `transaction` section it says:

> If the query being executed has a transaction, this property will contain it. Otherwise this holds the knex instance installed for the query. Either way, this can and should be passed to any queries executed in the static hooks.

Does that mean I need to pass transaction to `asFindQuery` as well? Or is it just for when you're calling `query/$query/etc`?

Thanks

**Comment by koskimas** [comment]
Nope, asFindQuery is automatically bound to any existing transaction within the query. It's said in the docs, but maybe in a cryptic way.
