### ISSUE TITLE
Aggregates in nested graph fetch

### ISSUE THREAD

**Issue by kennethacohen** [Vincit/objection.js#1817]
I am working through a query for a pretty standard e-commerce setup – while I got something that (kind of) works, I'm curious if there is a cleaner way of approaching this.

I have an `Order` model, which has many `LineItems` – these represent the products that were purchased within the order. A `LineItem` references a `Product` and a separate `Price`, and has a set quantity.

I am attempting to have a default select on the `Order` model so I can easily see the total amount of the order - this would be calc'd by summing the price * quantity of each `LineItem`. My solution right now only works when selecting a specific order, as I'm referencing the order ID in the modifier (see below).

Is there a better way to accomplish this query? It feels like I'm currently running duplicate queries, and am also not supporting any kind of bulk Order fetch.

My semi-working attempt is as follows:

```
return await Order.query()
  .findOne({ uuid })
  .modify("defaultRelations")
  .modify("defaultSelect", uuid)
```

Where the following modifiers set on the `Order` model:
```
static modifiers = {
    defaultRelations(query: QueryBuilder<Order>) {
      query.withGraphFetched("[fulfillmentOption, lineItems.[price, product], user, currentFulfillmentStatus]")
    },

    defaultSelect(query: QueryBuilder<Order>, uuid: string) {
      query.select([
        "orders.*",
        LineItem.query()
          .select(raw("sum(line_items.quantity * price.unit_amount)"))
          .joinRelated("[price, order]")
          .where("order.uuid", uuid)
          .as("line_items_total")
      ])
    }
  }
```

**Comment by koskimas** [comment]
You probably have a `lineItems` relation in your `Order` class? If not, add one :slightly_smiling_face: 

Then you can do this:

```js
static modifiers = {
    defaultRelations(query: QueryBuilder<Order>) {
      query.withGraphFetched("[fulfillmentOption, lineItems.[price, product], user, currentFulfillmentStatus]")
    },

    defaultSelect(query: QueryBuilder<Order>) {
      query.select([
        "orders.*",
        Order.relatedQuery('lineItems')
          .select(raw("sum(line_items.quantity * price.unit_amount)"))
          .joinRelated("price")
          .as("line_items_total")
      ])
    }
  }
```

This is called a correlated subquery. `relatedQuery` is just a shortcut. See what SQL gets generated. Let me know if this works.

**Comment by kennethacohen** [comment]
Oh wow, I ended up getting pretty close 😄 – that makes sense though. For some of these strange queries I find it easier to write the raw SQL then say "how can I make this objection-y?"

```js
defaultSelect(query: QueryBuilder<Order>) {
  query.select([
        "orders.*",
        LineItem.query()
          .select(raw("sum(line_items.quantity * price.unit_amount)"))
          .joinRelated("[price, order]")
          .where("order.uuid", ref("orders.uuid"))
          .as("line_items_total"),
      ])
}
```

Thanks @koskimas

**Comment by kennethacohen** [comment]
Small fix to what @koskimas  posted to anyone who references this in the future – not the `sum` should reference the camelcase `lineItems` vs the table name `line_items`. Otherwise this is 💯 

```js
defaultSelect(query: QueryBuilder<Order>) {
      query.select([
        "orders.*",
        Order.relatedQuery("lineItems")
          .select(raw(`sum("lineItems".quantity * price.unit_amount)`))
          .joinRelated("price")
          .as("line_items_total"),
      ])
    }
```
