### ISSUE TITLE
Undefined relation, but no field-to-field relation

### ISSUE THREAD

**Issue by hydroper** [Vincit/objection.js#1818]
With latest version, I'm getting this:

> DBError: `select "users".* from "users" where "networkid" = $1` - relation "users" does not exist

With query:

```javascript
await User.query().where('networkid', '=', fields.networkid);
```

With model:

```javascript
import objection from 'objection';

const { Model } = objection;

export default class User extends Model {
    static get tableName() {
        return 'users';
    }
}
```

**Comment by koskimas** [comment]
You haven't created the table yet. Make sure to run your migrations.

**Comment by hydroper** [comment]
Knex doesn't create the table on migration.

**Comment by koskimas** [comment]
Well there's your reason. Objection doesn't create tables or migrate things behind the scenes. You need to make sure the tables exist before running queries.
