### ISSUE TITLE
Best Practices for Inserting/Updating/Deleting Nested Relations

### ISSUE THREAD

**Issue by mc962** [Vincit/objection.js#1819]
I've been working with Objection+Knex with a Postgres database, and had some questions about the best way to approach certain operations. (I mostly come from a Rails/ActiveRecord and Python/SQLAlchemy background)

Objection is being used in an express-based web application.
I have several resources with relationships like so:

There are 3 resources, **resourceA**, **resourceB**, **resourceC**.

- resourceA has a _OneToMany_ relationship with resourceB
- resourceB has a _ManyToMany_ relationship with resourceC, through **joinTableD**

On a particular create/update page for resourceA, users will have the ability to add and update more of resourceB, and resourceB will be linked to resourceA, in the same HTTP submission made by the user.
Users will also be able to link more of resourceC to resourceB in that same submission (although will not necessarily be able to update attributes for resourceC at this time).

At this point I have a few questions.

- Right now, I want to have the ability to create/update multiple resourceB at a time, and have them linked to resourceA, and the ability to link multiple of resourceC to resource B.
I also need their lifecycle hook callbacks to be run, which handle things like setting/updating timestamps and slugs.
At the moment, I iterate through the list of items sent up and run the necessary INSERT/UPDATE/DELETE query for each item individually, as that is what I was able to get working.
Is there a better way to do a bulk operation for these records, instead of issuing the queries for each record individually?
I am fine with separating out the different actions INSERT/UPDATE/DELETE for each list of items if needed, I just feel like 
executing so multiple queries at once seems like potentially extra work. But I do still want the lifecyle hooks to be run.
- Is something like [upsertGraph](https://vincit.github.io/objection.js/guide/query-examples.html#graph-upserts) what I may likely want?
It seems like a somewhat recommended way to handle inserting and updating records and their nested relations, that might simplify some things and possible be more efficient. I just noticed the recommendations in the documentation to try other solutions before using the graph methods, so I wanted to make sure I wasn't missing anything simpler. (I also couldn't get it to work the last time I tried using it, which led me to the simpler, if possibly less efficient, for-loop strategy).

**Comment by koskimas** [comment]
Only tool objection has for simplifying this kind of stuff is `upsertGraph`. `upsertGraph` will probably have about the same performance as your for-loop solution. There's no reasonable way to do multiple updates in one query for example. `upsertGraph` can be a good tool in this situation.
