### ISSUE TITLE
JSON Schema validation fails for BigInt

### ISSUE THREAD

**Issue by nedzadalibegovic** [Vincit/objection.js#1821]
If a property is defined as an `integer` type in the JSON schema, trying to insert a `BigInt` number returns a `ValidationError` with the message that it should be an integer.

### JSON Schema:
```json
"BigID": {
      "$id": "#/properties/BigID",
      "type": "integer"
 }
```

### JS:
```js
await Example.query().insert({
    BigID: 10016543188383690n,
});
```

The above function would throw a ValidationError, is this intended behavior or am I doing something wrong? To go around this I'm using a string property with regex validation.

**Comment by koskimas** [comment]
Objection uses AJV as a validator. You should open this issue there. There's nothing we can do about this.
