### ISSUE TITLE
Joining table on value included in joint table as extra value

### ISSUE THREAD

**Issue by mstaniewski** [Vincit/objection.js#1824]
Hello community,

I've faced a problem I cant neither solve nor find solution in documentation and issues.
In short description, I'm building an ecommerce solution, where I have following models: Product, Variant, Attribute, AttributeDictionary

Shortly, whenever user create an attribute of dictionary type, then it's answers are saved on AttributeDictionary model.
Each variant has many attributes.

**Let's present db schema:**
<img width="750" alt="Screenshot 2020-08-20 at 14 38 29" src="https://user-images.githubusercontent.com/11744682/90770971-e4fd7400-e2f2-11ea-9c59-b729fc1bbd64.png">

There are solutions like `filter` for relations, was wondering about kind of `modify` function, that would allow me to `join` attribute dictionary value.

The point is that in fields of type text, number etc. values are flat, but for dictionaries, those are predefined and stored in separate db table. 

I have no idea how to approach this problem, since the choice is saved as an id in joint table. It could be saving as flat value, but it wouldn't respond to dictionary changes then.

**Comment by koskimas** [comment]
> The only thing that I wonder about now is if I can merge resolvedValue and value and display it conditionally, kind of (ternary notation)

You can write this `raw` monstrosity

```js
 modify: (qb) => {
    const subQuery =  Attribute.relatedQuery('dictionary')
        .select('dictionary.value')
        .where('dictionary.id', '=', raw('attributes_dictionaries_id'));

    qb.select(
      `attributes.*`,
      'value',
      raw('coalesce(?, ?)', [subQuery, value]).as('resolvedValue');
    );
  },
```

but it's probably cleaner to do that in code after the query.
