### ISSUE TITLE
Is it possible to compare against a constant in relationMappings?

### ISSUE THREAD

**Issue by Linksku** [Vincit/objection.js#1827]
As an example, I have 3 tables: posts, comments, and likes. The `likes` table has `entityType` (which can be "post" or "comment") and `entityId` columns. This is so I can use one table for liking both posts and comments. To clarify, the alternative would be creating separate `postLikes` and `commentLikes` tables.

I tried creating a relationship like this:

```
class Post extends Model {
  static get relationMappings() {
    return {
      reactions: {
        relation: Model.HasManyRelation,
        modelClass: require('./Like').default,
        join: {
          from: ['"post"', 'posts.id'],
          to: ['likes.entityType', 'likes.entityId'],
        },
      },
    }
  }
}
```

However, I get:

`Error: Post.relationMappings.likes: join.from must have format TableName.columnName. For example "SomeTable.id" or in case of composite key ["SomeTable.a", "SomeTable.b"].`

I know I can simply use `where`, but it'll be easy to introduce bugs if the caller forgets the `where`. If I can't use the constant in relationMappings, is there a way to avoid having to remember the `where` like the following?

```
Post.query()
  .withGraphFetched('likes')
  .where('likes.entityType', '"post"');
```

**Comment by koskimas** [comment]
Instead of using a composite key with a cobstant, you can use the `modify` function in the relation mapping

https://vincit.github.io/objection.js/api/types/#type-relationmapping

**Comment by johnny5th** [comment]
I have a very similar use case where I have a constant "entity type" as part of the composite ID. The modify function definitely works for querying, but it does not allow for the use of the insertGraph on the relationship. The entity type needs to be inserted into the data prior to running it.
