### ISSUE TITLE
CreateNotFoundError Model method should be able to accept a context object but the types don't allow it

### ISSUE THREAD

**Issue by jgahn-xom** [Vincit/objection.js#1829]
Model method CreateNotFoundError should be able to accept a context object but the typings do not allow it:
https://vincit.github.io/objection.js/api/model/static-methods.html#static-createnotfounderror
https://github.com/Vincit/objection.js/blob/1fdd5a630610e1ffbb4fcb5e4db157e88864092d/typings/objection/index.d.ts#L1438-L1439

**Comment by jgahn-xom** [comment]
Has no one run into this? It would be really useful to use this feature in our typescript app.

**Comment by koskimas** [comment]
This was recently fixed.
