### ISSUE TITLE
Sample auto migrate - not practically

### ISSUE THREAD

**Issue by TechComet** [Vincit/objection.js#1837]
Hi,

I write automigrate

It still needs a lot of work

you need add type increments

https://gist.github.com/TechComet/cbe018d880472189a4ed73040eab41a5

**Comment by koskimas** [comment]
I'm sorry, but nothing like this will never be added to objection. Automatic migrations only work for very simple cases. Any non-trivial migration you still have yo write by hand. So you might as well write them by hand each time.

Just look at tools like django. The generation works for basic cases, but once you do anything non-trivial, you need to write a migration by hand. And django has basically the best implementation for this, you could write.

**Comment by TechComet** [comment]
Auto migrate .. optinal
It is possible, but it needs a lot of work

I will work on it later
However, we will need some changes to objection.js to make the migrations process easier

**Comment by TechComet** [comment]
Please need jsonSchema file with full power objection.js

**Comment by koskimas** [comment]
It is possible for very simple stuff, like the things you are writing in your example. But consider these two simple mgrations:

1. Combine `firstName` and `lastName` columns into a single `fullName` column.
2. Add composite unique constraint on `firstName`  and `lastName` columns.

How would you generate migrations for those?
