### ISSUE TITLE
StaticHookArguments#result is always an array

### ISSUE THREAD

**Issue by lehni** [Vincit/objection.js#1842]
The way `StaticHookArguments#result` is currently defined, it is always an array, even when the actual result returned from the query operation (e.g. `findOne()`) would be a single model object. That means that defining the `afterFind` hook as follows would have unexpected side-effects, converting the expected result to an array: `[result]`.

```js
afterFind({ result }) {
  return result
} 
```

This makes writing plugins with some kind of abstraction harder, as there is no way of knowing within the hook whether the actual expected result is a model item or an array of items.

This is unfortunate?

What's the reason for always converting `result` to an array? I understand that `items` and `inputItems` needs to be handled this way, but I would like to argue that `result` is different, not only linguistically (`result` can be both and that isn't wrong), but also in terms of what it represents an how it is to be used.

If it is too late to change this now (it may not be, because it's barely mentioned in the docs), then there are two other options:

* Add a boolean property to `StaticHookArguments` that identifies if the result should be an array of items, or a singular item
* Have the surrounding code that calls the hooks handle returned array results, and automatically unbox arrays with one item inside in situations where the original query would return a single item.

**Comment by koskimas** [comment]
Yep, that's by design.

**Comment by lehni** [comment]
Would you consider adding a property so the hook can know which situation it is? Otherwise it is impossible to return meaningful data from the hook that works in all use cases.

**Comment by lehni** [comment]
@koskimas this property could be called `isSingular` or `isSingleItem`? This would still be of use here…
