### ISSUE TITLE
Querying agains the virtual fields

### ISSUE THREAD

**Issue by AhmadRaza786** [Vincit/objection.js#1843]
Hi Everyone
I have added a custom field in my modal like
```
get fullName() {
    return `${this.firstName} ${this.lastName}`; 
  }
```
I want to do the query with this custom field. Like
```
  this.query().select(fields).where(‘fullName’, ‘ilike’, ‘%test%’)
```
How can i do this in objectionJS ?

**Comment by koskimas** [comment]
You need to use`raw` in `where` or the `whereRaw` method.

```js
this
  .query()
  .select(fields)
  .whereRaw(‘("firstName" || "last name") ilike ?', '%test%')
```

You obviously cannot use the `fullName` getter from SQL since it's in javascript.

**Comment by AhmadRaza786** [comment]
@koskimas I am still getting error as 
`column "("firstName" || ' ' || "lastName")" does not exist`

**Comment by koskimas** [comment]
You are using `"` around the whole thing which means an identifier in postures. Make sure you write valid SQL. This is not specific to objection.
