### ISSUE TITLE
Alter the name of a relationship in the modifyGraph section

### ISSUE THREAD

**Issue by randomiser** [Vincit/objection.js#1850]
Quick question is it possible to change the name of a relationship that you've fetched via a graph?

Something like:

```
 let plans = await Person.query()
      .withGraphFetched([pastAddresses])
      .modifyGraph('pastAddresses', builder => {
        // I want to rename 'pastAddresses' to something else like 'addresses'
      });
```

**Comment by ameinhardt** [comment]
@randomiser : why does it have to be specific to objection?
```
plans.forEach(({ pastAddresses:addresses, ...plan }) => ({ addresses, ...plan }));
```
Or even in [runAfter](https://vincit.github.io/objection.js/api/query-builder/other-methods.html#runafter).

**Comment by randomiser** [comment]
Thanks for your quick reply. I was hoping there might already might be a supported way of doing this.

**Comment by randomiser** [comment]
Now that I've taken a look at runAfter that looks to be a good option. Thanks!
