### ISSUE TITLE
How to omit a field?

### ISSUE THREAD

**Issue by fookit** [Vincit/objection.js#1851]
Howdy! How do I omit fields when query? For instance, I'd like to hide `password` and `is_admin` fields.

`GET http://localhost:4000/users`:

```json
[
  {
    "email": "some@one.com",
    "is_admin": true,
    "name": "Some One",
    "password": "this_is_the_password"
  },
  {
    "email": "any@one.com",
    "is_admin": false,
    "name": "Any One",
    "password": "this_is_the_password"
  }
]
```

`GET http://localhost:4000/users/1`:

```json
{
    "email": "some@one.com",
    "is_admin": true,
    "name": "Some One",
    "password": "this_is_the_password"
}
```

---

Objection.js (v2.2.3), TypeScript (v4.0.2), Koa (v2.13.0), Postgres (v12)

**Comment by TheHerobrine** [comment]
@fookit I used this plugin: https://www.npmjs.com/package/objection-visibility

And my model looks like this:

```js
import { Model } from "objection";
import ObjectionVisibility from "objection-visibility";

export class UserModel extends ObjectionVisibility(Model) {
    id!: string;
    name!: string;

    static tableName = "users";
    static hidden = ["password"];
}
```

**Comment by Kadeluxe** [comment]
Jesus... Why all Node ORMs look like a giant hack ll

**Comment by koskimas** [comment]
You can simply `select` the fields you want. But for making sure password hashes and other sensitive stuff never leaves the server, you can overrde the `$formatJson` method that gets called each time a model instance is serialized to json

```js
export class UserModel extends Model {
    id!: string;
    name!: string;
    password?: string;
    is_adming?: boolean;

    static tableName = "users";

    $formatJson(json) {
      json = super.$formatJson(json);
      delete json.password;
      delete json.is_admin;
      return json;
    }
}
```

I hope `password`  fields contains a hash of the password and not the real password though :wink:

**Comment by koskimas** [comment]
@Kadeluxe You are probably really young and new to open source and programming in general, so I'll give you the benefit of a doubt and assume you didn't really want to be mean. But for future reference comments like that will destroy people's willingness to write open source and help you and others by spending their free time answering questions like this.

Projects like this are written by people for free on their spare time without any compensation or other benefits. For example in my case, that message really fucking hurt and I won't be answering any questions, or fixing any bugs for a while. Thanks to you.

**Comment by fookit** [comment]
Thanks @koskimas :)

**Comment by lordvcs** [comment]
@koskimas Dude u r a friggin legend for creating this project. Thanks for writing this great piece of software.

**Comment by kasvith** [comment]
Yes @koskimas thanks for this awesome OSS project. Finally the Only ORM we can use without fears

**Comment by miguelrrsantos** [comment]
Hello all. 

I'm new to objection and do not have much experience using it. 

There are some cases where i need to fetch user with password and some other times i want to omit it. What is the best approach? Can a conditional be used to delete the password field in the `$formatJson(json)` method? Or with a modifier? 

If you can provide examples i would be appreciated. 

Best regards,
Miguel.

**Comment by kasvith** [comment]
@miguelrrsantos I think you can use a [modifier](https://vincit.github.io/objection.js/recipes/modifiers.html#usage-in-a-query)

**Comment by lehni** [comment]
For those missing `omit()` from older versions, here a suggestion: 

https://github.com/Vincit/objection.js/issues/2284#issuecomment-1509082977
