### ISSUE TITLE
Proper usage of virtualAttributes?

### ISSUE THREAD

**Issue by NoahTheDuke** [Vincit/objection.js#1854]
**Which versions are you using?**
* objection 2.2.3
* knex 0.21.5
* pg 7.18.3
* PostgreSQL server 12.3

**What are you trying to do?**
Set transient/virtual attributes that exist only on the model instance but are not persisted in the database when inserted/updated.

**What happens?**
Virtual attributes are included in the insert/update calls.

**Reproduction code**
This is build on top of the [reproduction-template.js](https://github.com/Vincit/objection.js/blob/master/reproduction-template.js). I have only repeated the modified code here.
```javascript
async function main() {
  await createSchema();

  const jennifer = await Person.query().insert({
    firstName: 'Jennifer',
    lastName: 'Lawrence',
  });

  jennifer.foobar = '10';
  await jennifer.$query().patch();

  chai.expect(jennifer.foobar).to.equal('10');
}

class Person extends Model {
  static get tableName() {
    return 'Person';
  }

  static get virtualAttributes() {
    return ["foobar"];
  }
}
```

**Expected results**
Code should run without error.

**Actual results**
```
$ node reproduction-template.js
DBError: update `Person` set `firstName` = 'Jennifer', `lastName` = 'Lawrence', `id` = 1, `foobar` = '10' where `Person`.`id` = 1 - SQLITE_ERROR: no such column: foobar
    at wrapError (/Users/noah/dev/objection-test/node_modules/db-errors/lib/dbErrors.js:19:14)
    at handleExecuteError (/Users/noah/dev/objection-test/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1506:32)
    at QueryBuilder.execute (/Users/noah/dev/objection-test/node_modules/objection/lib/queryBuilder/QueryBuilder.js:687:20) {
  name: 'DBError',
  nativeError: [Error: update `Person` set `firstName` = 'Jennifer', `lastName` = 'Lawrence', `id` = 1, `foobar` = '10' where `Person`.`id` = 1 - SQLITE_ERROR: no such column: foobar] {
    errno: 1,
    code: 'SQLITE_ERROR'
  },
  client: 'sqlite'
}
```

**Comment by koskimas** [comment]
Virtual attributes must be getters or methods, not real attributes (hence virtual).

**Comment by NoahTheDuke** [comment]
Is there a way to accomplish what I’m trying to accomplish that doesn’t involve using the `$` prefix? Or is that the only way?

**Comment by koskimas** [comment]
You should be able to use non-enumerable properties:

```js
Object.defineProperty(this, 'foobar', {
  value: 'some value',
  enumerable: false
})
```

Another option is to define `$formatDatabaseJson` method and delete the properties you don't want to go to the db there.

**Comment by NoahTheDuke** [comment]
Cool, thank you.
