### ISSUE TITLE
asFindQuery() returns wrong builder for patchAndFetchById() operations

### ISSUE THREAD

**Issue by lehni** [Vincit/objection.js#1855]
I am using `asFindQuery()` to get the affected items in a static `beforeUpdate()` model hook that gets called when `patchAndFetchById()` is executed. 

In this situation, `asFindQuery()` does not return a query that only selects the affected model items, it returns a query without a where clause, returning all model items of the given model class. 

According to the docs, it should only return the model item with the given id?

**Comment by lehni** [comment]
Looking at the involved `UpdateAndFetchOperation`, I understand now why this is happening. It only runs `findById()` inside the `onBuild()` method, which only gets called upon execution, not before:

```js
  onBuild(builder) {
    if (!this.skipIdWhere) {
      builder.findById(this.id);
    }

    super.onBuild(builder);
  }
```

**Comment by lehni** [comment]
Redefining `toFindQuery()` as follows works for me indeed:

```js
  toFindQuery() {
    const builder = this.clone()
    const selector = op => op.is(InsertOperation) || op.is(UpdateOperation) || op.is(DeleteOperation)
    builder.forEachOperation(selector, op => op.onBuild(builder));
    return builder.clear(selector);
  }
```

I quickly checked all possible `InsertOperation`, `UpdateOperation`, and `DeleteOperation` classes, and I think this is fine to do. 

Another class where the same problem will occur otherwise is `InstanceUpdateOperation`, where `onBuild()` is defined as follows:

```js
  onBuild(builder) {
    super.onBuild(builder);

    assertHasId(this.instance);
    builder.findById(this.instance.$id());
  }
```

**Comment by lehni** [comment]
Quick fix using monkey-patching in user space:

```js
function getOperationClass(modify) {
  const query = Model.query()
  let constructor = null
  // Locally override QueryBuilder#addOperation() in order to extract the
  // private operation constructor / class:
  query.addOperation = operation => {
    constructor = operation.constructor
  }
  modify(query)
  return constructor
}

const InsertOperation = getOperationClass(query => query.insert())
const UpdateOperation = getOperationClass(query => query.update())
const DeleteOperation = getOperationClass(query => query.delete())

QueryBuilder.prototype.toFindQuery = function() {
  const builder = this.clone()
  const selector = op => (
    op.is(InsertOperation) ||
    op.is(UpdateOperation) ||
    op.is(DeleteOperation)
  )
  builder.forEachOperation(selector, op => op.onBuild(builder))
  return builder.clear(selector)
}
```

**Comment by fvinogradov** [comment]
I'm facing the same issue with `updateAndFetchById`. In code below `asFindQuery` executing returns all rows from DB: 
``` javascript
class CampaignModel extends Model {
  static async beforeUpdate(ops) {
    await super.beforeUpdate(ops);
    const { asFindQuery, inputItems } = ops;
    const foundCampaigns = await asFindQuery().select('id', 'status');
  }
}

await CampaignModel
  .query()
  .updateAndFetchById(
    id,
    {
      status: 'PROCESSING',
    },
  );
```

As a temporal solution, for this model with `beforeUpdate` hook I replaced `updateAndFetchById` with 
``` javascript
await CampaignModel
  .query()
  .update(
    {
      status: 'PROCESSING',
    },
  )
  .where({ id });
```

**Comment by JaneJeon** [comment]
Hi, sorry to bother you again @koskimas but this is sort of a blocker for an objection plugin I’m writing as it relies _heavily_ on `asFindQuery` (unless I use the utterly hacky, ‘should-not-be-done-in-prod’ style of monkeypatching `asFindQuery` listed above, which, to be fair, _works_).

It would be greatly appreciated if this fix was implemented directly in Objection itself. Thanks!

**Comment by koskimas** [comment]
I'll start working on this now.

**Comment by lehni** [comment]
Thanks @koskimas for taking care of this!
