### ISSUE TITLE
How to get parent value from child table use child id only.

### ISSUE THREAD

**Issue by ombak** [Vincit/objection.js#1856]
First I want to say I'm happy to use objection.js in my project. And I will use objection.js for my another project.
But now I have problem when I use relation in objection, it's simple when I use sql query, but I want to know what the correct way to solve the problem when I use objection.js relations. I have two table.

tbl_categories                   
+-------------------                 
id                                        
title                                     

tbl_videos
+---------------
id
category_id
title

I have created models and relationships between tables.

Now I want get data from tbl_videos and tbl_categories by video id. I currently solve this problem using a left join.

Like [this](https://stackoverflow.com/questions/63727366/how-to-join-table-one-to-many-using-objection-js?noredirect=1#comment112707649_63727366)

But when I use objection.js like the link above. I don't thing it's the best way.

can you show me the right way. 

Thank you very much.

**Comment by koskimas** [comment]
Depending on the data output format you want, use one of the following:

(both examples assume you have defined the `category` relation for the Video model)

```js
const videos = await Video.query()
  .select('tbl_videos.*', 'tbl_categories.*')
  .leftJoinRelated('category')
  .findById(videoId)
```

```js
// This will get you the video with a nested `category` field that holds the category object.
const videos = await Video.query()
  .withGraphFetched('category')
  .findById(videoId)
```

```js
// Exactly the same as the previous query, but uses joins internally instead of separate
// queries. You can use `withGraphJoined` when you need to filter the query based on
// relations. Read the documentation about the differences and possible caveats.
const videos = await Video.query()
  .withGraphJoined('category')
  .findById(videoId)
```
