### ISSUE TITLE
QueryBuilder isn't explicitly resolving null values with resolve()

### ISSUE THREAD

**Issue by andrucz** [Vincit/objection.js#1857]
As stated at https://vincit.github.io/objection.js/api/query-builder/other-methods.html#resolve the function `resolve()` should skip the database query and fake a result.

I've noticed it doesn't work when trying to fake null values. I'm trying to create unit tests that validate the behavior of a service when the query returns null (with `findById`, for example).

```
jest
  .spyOn(ContactModel, 'query')
  .mockImplementationOnce(db => ContactModel.query(db).resolve(null));
```

Any further query generated by `ContactModel.query()` tries to hit the database instead of returning `null`.

**Comment by koskimas** [comment]
Value you pass to `resolve` is the value the query would resolve without any methods chained, which is always an array. If you pass an empty array to `resolve` a `findById` queries should return `undefined`.
