### ISSUE TITLE
How to handle query().count() in TypeScript?

### ISSUE THREAD

**Issue by naishe** [Vincit/objection.js#1858]
Hi,

This is not an issue, rather a query. I am little confused when it comes to `count()`. I want to do something like this:

```Typescript
      const { count } = (await User.query().count())[0] as {
        count: number;
      };
```

It gives a warning saying:

```
Conversion of type 'User' to type '{ count: number; }' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Property 'count' is missing in type 'User' but required in type '{ count: number; }'.ts(2352)
```

I apologies that I am bringing a TypeScript specific question to ObjectionJS. Feel free to close the issue if it is unrelated.

Thanks.

**Comment by koskimas** [comment]
You can use the `resultSize` helper instead.
