### ISSUE TITLE
Using distinctOn() with withGraphFetch

### ISSUE THREAD

**Issue by jnfrdle** [Vincit/objection.js#1862]
Hi everyone,

I'm writing because I'm stumbling on a small issue and I can't figure out if I am missing something in the documentation or if it is a feature that is not supported by Objection.

I have a model Company that has a BelongsToOneRelation relation with model Country:

```
class Company extends Model {

  static get tableName() {
    return 'companies';
  }

  static get relationMappings () {

    const Country = require('./country')

    return {
      country: {
        relation: Model.BelongsToOneRelation,
        modelClass: Country,
        join: {
          from: 'company.country_id',
          to: 'countries.id'
        }
      }
    }
  }
}
```

When I run the query to get objects in Companies, I successfully get rows from companies:

```
var query = Company.query().orderBy('companies.id','asc')
        .offset(page*page_size)
        .limit(page_size)
```

When I use withGraphFetched, I successfully get the relational object from country nested into each company object:

```
var query = Company.query().withGraphFetched('country').orderBy('companies.id','asc')
        .offset(page*page_size)
        .limit(page_size)
```

However, when I use distinctOn().withGraphFetched, it only returns the nested country object field in each company object and not the rest of the company fields:

```
[
  { 
     'country': {
          'id': 2,
          'name': 'Canada'
    }
  },
  { 
     'country': {
          'id': 5,
          'name': 'United States'
    }
  }
]
```

Am I missing something?

Note: I need to use distinctOn() because I might need to add a joinRelated to the query with a model like "Rivers" which is linked as HasManyRelation.

**Comment by koskimas** [comment]
You probably want to use `withGraphJoined`.
