### ISSUE TITLE
Static type checking for model attributes

### ISSUE THREAD

**Issue by jowparks** [Vincit/objection.js#1867]
I am wondering why objection doesn't take into account the optionality of the models when static type checking for insert?

For example lets say I have this user model:
```
export class UserModel extends BaseModel implements User {
  static tableName = 'users';

  username!: string;
  userEmail!: string;
}
```

and then I have a service that creates instances of these models in the database:
```
export class UserService {
  constructor(
    @Inject(UserModel) private readonly userModel: typeof UserModel
  ) {}

  async addUser(userInfo: UserInput): Promise<UserModel> {
    const userModel = {
        username: userInfo.username,
    };
    return this.userModel.query().insert(userModel);
  }
}
```

This will pass type checking, when it shouldn't because I have listed the `userEmail` field as required.

Wondering if I am missing something? I would like to catch these issues through static type checking rather than writing a jsonValidation method that will only catch these issues at runtime.

**Comment by abedmurrar** [comment]
it is required for typescript but not for validation, you'd have to use a validation scheme of yours, or you can define a json schema for the model.

**Comment by koskimas** [comment]
`userEmail!` doesn't mean "this property is required". It means "Hey typescript, this property is here even though I don't set it anywhere. Just ignore the errors".

**Comment by Axxxx0n** [comment]
sorry, but it is not clear to me. Is what OP wants to do possible?
