### ISSUE TITLE
Can all where clauses be enclosed in parentheses after they have been added?

### ISSUE THREAD

**Issue by mikeconley12** [Vincit/objection.js#1868]
#### Code example

```js
// Creates an Objection query. 
// I have no control over the creation of the query. I can only modify the query after it has been created.
// Example: "select `todos`.* from `todos` where `text` = ?"
const objectionQuery = thirdPartyService.createQuery(userControlledInput);
// Adds an access check. Example "select `todos`.* from `todos` where `text` = ? and `userId` = ?"
objectionQuery.andWhere("userId", currentUser.id);
```

The above example has a security bug. If the `thirdPartyService` generates a query like this: 

```sql
select `todos`.* from `todos` where `text` = ? or `id` = ?
```

Then after adding the access check we will get the following query:

```sql
select `todos`.* from `todos` where `text` = ? or `id` = ? and `userId` = ?
```

And this query can return data that doesn't belong to the current user.
To fix this bug, we need to enclose the user-controlled conditions in parentheses:

```sql
select `todos`.* from `todos` where (`text` = ? or `id` = ?) and `userId` = ?
```

**But how do I do this with the Objection query builder?** I imagine something like this:

```js
const objectionQuery = thirdPartyService.createQuery(userControlledInput);
wrapWhereClauses(objectionQuery);
objectionQuery.andWhere("userId", currentUser.id);
```

**Comment by abedmurrar** [comment]
These are the ways to group where clauses, this is from knex documentation.

![Screenshot_20201027_043912](https://user-images.githubusercontent.com/37074425/97250347-7109ab80-180e-11eb-837f-eefcdf610106.jpg)
![Screenshot_20201027_043848](https://user-images.githubusercontent.com/37074425/97250349-723ad880-180e-11eb-9425-99614c15fc90.jpg)
