### ISSUE TITLE
Is there a way to modify the query being executed inside the 'beforeFind' hook?

### ISSUE THREAD

**Issue by mikeconley12** [Vincit/objection.js#1869]
I'd like to add some kind of access checking to the query being executed inside the 'beforeFind' hook. Is it possible?
Something like:

```js
class Person extends Model {
  static async beforeFind({ queryToExecute, context }) {
    queryToExecute.andWhere("userId", context.user.id);
  }
}
```

Is there a better place to add this access check?

**Comment by egluhbegovic** [comment]
@mikeconley12 Did you resolve this?

**Comment by koskimas** [comment]
Not possible unfortunately.
