### ISSUE TITLE
missing methods when extending BaseModel in Typescript

### ISSUE THREAD

**Issue by kbyatnal** [Vincit/objection.js#1871]
```
const { Model } = require("objection");

class BaseModel extends Model {
  static get modelPaths() {
    return [__dirname];
  }

  $beforeInsert() {
    const timestamp = new Date().toISOString();
    this.createdAt = timestamp;
    this.updatedAt = timestamp;
  }

  $beforeUpdate() {
    this.updatedAt = new Date().toISOString();
  }
}

export default BaseModel;

```

```
import { BaseModel } from "./BaseModel";

class User extends BaseModel {
  id!: string;
  firstName!: string;
  lastName!: string;
  email!: string;
  phone!: string;
  createdAt!: string;
  updatedAt!: string;

  static get tableName() {
    return "users";
  }
}

export default User;
```

When attempting to use `User.query()`, we see a typescript error that `query` does not exist on `User`.

**Comment by koskimas** [comment]
You export the BaseModel as a default export but import it using a named import.

**Comment by kbyatnal** [comment]
@koskimas thanks for the quick reply!

Sorry, that was an issue while copy/pasting the example over. I've gone ahead and updated it, we're still running into the same issue.

**Comment by koskimas** [comment]
I think it's because you use `require` instead of `import` in the base model. The type of `Model` is probably `any`. Use `import` and things should work.

**Comment by kbyatnal** [comment]
I knew it was something silly 🤦 I copy pasted from the getting started guide and didn't double check that part.

Thank you for your help!
