### ISSUE TITLE
Setting BaseModel to throwIfNotFound on query giving TS error

### ISSUE THREAD

**Issue by ultd** [Vincit/objection.js#1872]
Objection Version: ^2.2.1
TS Version: 3.9.5

I have a base model in which I would like to make the default behavior for queries to throw an error if not found like so: 

```ts
class BaseModel extends Model {

	static query<M extends Model>(
		this: Constructor<M>,
		trxOrKnex?: TransactionOrKnex
	  ): QueryBuilderType<M> {
		return super.query(trxOrKnex).throwIfNotFound();
	  } 
}
```

All of my models would extend this model and use it to have default query behavior. When I do this, I get a TS error like so (highlighted in VS Code specifically over the return statement): 

```
Type 'QueryBuilder<Model, Model[]>' is not assignable to type 'M["QueryBuilderType"]'.
  Type 'QueryBuilder<Model, Model[]>' is not assignable to type 'QueryBuilder<M, M[]>'.
    The types returned by 'findById(...).execute()' are incompatible between these types.
      Type 'Promise<Model>' is not assignable to type 'Promise<M>'.
        Type 'Model' is not assignable to type 'M'.
          'Model' is assignable to the constraint of type 'M', but 'M' could be instantiated with a different subtype of constraint 'Model'.
```

Not sure if this is a bug or if I'm implementing this incorrectly. Any help would be appreciated.

**Comment by ultd** [comment]
Any ideas on this?

**Comment by ultd** [comment]
2 weeks later.. any ideas? Would really appreciate any feedback.

**Comment by koskimas** [comment]
Remove the explicit return type `QueryBuilderType<M>` and rely on the implicit typing.

**Comment by ultd** [comment]
@koskimas Thanks so much! 😃
