### ISSUE TITLE
Alias column with typescript

### ISSUE THREAD

**Issue by galkatz373** [Vincit/objection.js#1876]
First I have to say I enjoy your amazing library a lot.
I just have one problem which I cannot find a solution, while looking at objection and knex documentations.

![image](https://user-images.githubusercontent.com/2151890/95001041-f5319000-05ce-11eb-9fb5-2117f8e8d74a.png)

When I query a model and want to give a column alias, typescript complains as the image above.

I'm sure there is a solution for it, but I couldn't find it.
Thanks in advance!

**Comment by albinstman** [comment]
Typescript can't extract types from runtime variables, you have to explicitly set the types for compile time. 

I can think of two solutions:

1. Update the User model

`
class User extends Model {
    identifier: number
}
`

2. Type casting

`
const { identifier } = ((await User.query().select('id as identifier').findById(1)) as unknown) as User & { identifier: number }
`

**Comment by galkatz373** [comment]
Thanks for the answer.
I guess there aren't built-in solutions for this. 
Hopefully knex.js will be more type safety in the future

**Comment by koskimas** [comment]
@galkatz373 The point was, there is no possible way to even add that kind of a feature. What typescript would need to be able to do is

1. Parse the string `id as identifier` and somehow understand that the third part separated by whitespace is a column name
2. Create a type based on that identifier

Neither of these things is possible in typescript.

So no, unortunately neither objection or knex will support this.
