### ISSUE TITLE
Conditionally add a where clause ( query/clone is not a function )

### ISSUE THREAD

**Issue by anup-a** [Vincit/objection.js#1877]
I'm trying to filter my Model conditionally before running some other where clauses. 

What I tried

```
let query1 = Post.query()

if (condition) {
   query1 = query1.clone().where("x", y)   // error in this line
   // also tried -> query1 = query1.query().where("x", y)
}
// other where clauses
result = query1.query().where("a", b)
```

I'm getting error that clone is not a function , similarly query is not a function.

I think I'm missing a very silly point, but couldn't figure out.

**Comment by koskimas** [comment]
There's no need to clone the query if you don't plan on using the old query as well. Since you are overriding the query, I don't thing that's the case. You can do this:

```js
let query1 = Post.query()

if (condition) {
   query1where("x", y) 
}

result = await query1.where("a", b)
```

Are you sure you didn't accidentally `await` the `Post.query()` line? The query builder is executed and turned into a promise once you `await` it. Until then, it's just a query builder.

**Comment by anup-a** [comment]
1. Thanks Thats it.

I guess the key point was  -
> The query builder is executed and turned into a promise once you await it. Until then, it's just a query builder.


2. 

> Are you sure you didn't accidentally await the Post.query() line?

I though `Post.query()` would initialize query builder, so I could use query inside and outside of `if statement`.

**Comment by anup-a** [comment]
> Are you sure you didn't accidentally await the Post.query() line? 

I couldn't think of any other way. Is there any better way?

**Comment by patricechaula** [comment]
> There's no need to clone the query if you don't plan on using the old query as well. Since you are overriding the query, I don't thing that's the case. You can do this:
> 
> ```js
> let query1 = Post.query()
> 
> if (condition) {
>    query1.where("x", y) 
> }
> 
> result = await query1.where("a", b)
> ```
> 
> Are you sure you didn't accidentally `await` the `Post.query()` line? The query builder is executed and turned into a promise once you `await` it. Until then, it's just a query builder.

Super 👌
