### ISSUE TITLE
Strict mode for undefined arguments

### ISSUE THREAD

**Issue by jc21** [Vincit/objection.js#188]
Hi, I'm not sure if this is really a Knex request or not. I've noticed that when I use a `where()` method with a variable that is `undefined`, the query simply ignores that `where` statement and does not throw any errors. As a result I have had moments of time consuming debugging.

```javascript
someModel.query().where('field', some_undefined_var).first();
```

It would be nice if there was a way to make objection throw errors when using a variable that is strictly undefined.

I get that people might be relying on this behaviour already, so a config switch disabled by default would be perfect.

**Comment by koskimas** [comment]
This is fixed in 0.6.0-rc.1. You can install it using npm install objection@next.

**Comment by fl0w** [comment]
Generally, knex behaviours like these can easily be overloaded when needed:

```js
class MyQueryBuilder extends objection.QueryBuilder {
  where () {
    if (arguments.length === 2) assert(arguments[1], 'cannot be undefined')
    return super.where(...arguments)
  }
}

class MyModel extends objection.Model {
  static get tableName () {
    return 'SomeTable'
  }
  static get QueryBuilder () {
    return MyQueryBuilder
  }
}

MyModel.query().where('id', 1) // should not fail
MyModel.query().where('id', undefined) // should fail
```

**Comment by fl0w** [comment]
Oops, closed and fixed .. my bad. Wasn't paying attention.
