### ISSUE TITLE
Feature request literal string values in relationMappings from/to

### ISSUE THREAD

**Issue by vasilevich** [Vincit/objection.js#1881]
Hey I am trying to use relationMappings()

it seems like an useful tool but I have a need to put static literal strings into the "from"
for example:
```
class SomeModel extends Model {
  static get relationMappings() {
    return {
      permissions: {
        relation: Model.HasManyRelation,
        modelClass: TestTable,
        join: {
          from: ['SomeModel.id','`constant string`'],
          to: ['TestTable.type_id','TestTable.type'],
        }
      }
    };
  }

}

```

now I know that "from" and "to" expect a table.column path,  but what if i want to give it a literal known string?
I don't seem to find any help on that in the documentation.

please help

thanks

**Comment by koskimas** [comment]
You should be able to use the `modify` property.

**Comment by vasilevich** [comment]
Thanks
