### ISSUE TITLE
Migrating from 0.9.4 to latest version of objection.js cause models break

### ISSUE THREAD

**Issue by ahmadtofeeq** [Vincit/objection.js#1885]
We are using objection.js version 0.9.4 in our TypeScript Backend Project. Now we want to upgrade it to latest to leverage new features. While moving to latest version, the biggest issue i face is that it doesn't allow non empty constructor.  It was allowed earlier. 
Below is our demo model class which is using a parameterized constructor.  
```
export class DemoModel extends Model {

    /**
     * The app consent table
     */
    public static tableName = 'tables';

    /**
     * Relationship of current model with others
     */
    public static relationMappings = {
     
    };

    public constructor(jsonObj: Partial<DemoTable>) {
        super();
        Object.assign(this, jsonObj);
    }
}
```
Now we need to keep empty constructor and we can use fromJson method to create model. But I have many models in project. And its leading to lots of changes. I am looking for quick workaround if there is any. Pls suggest

**Comment by koskimas** [comment]
See the change log. There are a lot of breaking changes between 0.9.4 and the current version.
