### ISSUE TITLE
Add type-safe method to access model class by instance

### ISSUE THREAD

**Issue by IlyaSemenov** [Vincit/objection.js#1886]
### Problem

Given an arbitrary model instance, I would like to know which specific model this instance belongs to.

Example use case: in a `Model.beforeInsert` global hook, I would like to recognize each of `inputItems`'s model class (e.g. look up its `tableName`).

I can already access it with `item.constructor` but it's typed as `Function` so I have to use ugly casts like:

```ts
if (item instanceof Model) {
  console.log((item.constructor as ModelClass<Model>).tableName)
}
```

### Proposed API addition

There could be an instance level getter `item.$modelClass` which would simply return `this.constructor` properly typed.

**Comment by abedmurrar** [comment]
you could add it in your base model class if it suits your case

**Comment by IlyaSemenov** [comment]
Of course I could. I could also ugly-cast `item.constructor` (and I do that), or invent other weird methods to get what I want. My point here is that the said accessor will constitute *common good* and is thus worth adding to the core, similarly to how [`queryBuilder.modelClass()`](https://vincit.github.io/objection.js/api/query-builder/other-methods.html#modelclass) already exists.

**Comment by abedmurrar** [comment]
so why don't you use `item.$query().modelClass().tableName` instead of casting and getting the constructor.

i know it would be a good feature to the core, but it's just a beneficial proposal to your case.

plus `item.$query().modelClass().tableName` does not return a promise.

**Comment by IlyaSemenov** [comment]
> so why don't you use `item.$query().modelClass().tableName`

Because
a) replacing one awkward approach with another awkward approach doesn't really make the code better, and
b) it's slower.

**Comment by koskimas** [comment]
There's no way to add a method, getter or a property that has the type `typeof this`, which would be the correct type of `this.constructor`. Typescript simply doesn't allow that. We could add `$modelClass: ModelClass<this>` but that will only contain the static interface of the `Model` base class and none of the static methods defined for the subclass. Adding such property feels like a hack.

**Comment by koskimas** [comment]
Actually that's what the query builder's `modelClass()` method also returns. I'll add the method.
