### ISSUE TITLE
#> is not a valid mysql operator

### ISSUE THREAD

**Issue by hroland** [Vincit/objection.js#1887]
Using the steps described in the [JSON Queries](https://vincit.github.io/objection.js/recipes/json-queries.html#json-queries) docs, the produced query implements the `json#>{path}` operator, which is not available in mysql. The alternative `json->>"$.path"` cannot be used in any way without producing an error.

```
parents: {
  relation: Model.HasManyRelation,
  modelClass: Child,
  join: {
    from: 'children.id',
    to: ref('children.details:parent')
  }
}
```
```
from debug: `children`.`details`#>'{name}'
```

**Comment by hroland** [comment]
Made advancements internally, with this super-band-aid solution, of overriding `ReferenceBuilder.prototype._createReferenceSql` with the Mysql appropriate operator

```
ReferenceBuilder.prototype._createReferenceSql = function(builder, bindings) {
  bindings.push(this.fullColumn(builder))

  if (this._parsedExpr.access.length > 0) {
    const extractor = this._cast ? '->>' : '->>'
    const jsonFieldRef = this._parsedExpr.access.map(field => field.ref).join(',')
    return `??${extractor}'$.${jsonFieldRef}'`
  } else {
    return '??'
  }
}
```

**Comment by koskimas** [comment]
Unfortunately, JSON queries only work on postgres at the moment.
