### ISSUE TITLE
Calling query() on a union type throws a Typescript error?

### ISSUE THREAD

**Issue by Linksku** [Vincit/objection.js#1888]
Not sure if this is an expected issue. Assume I have 2 models: `PostReply` and `ChatReply`.

```
const Model = type === 'post' ? PostReply : ChatReply;
const query = Model.query();
```

This causes the error:

```
The 'this' context of type 'typeof PostReply | typeof ChatReply' is not assignable to method's 'this' of type 'Constructor<PostReply>'.
  Type 'typeof ChatReply' is not assignable to type 'Constructor<PostReply>'.
    Type 'ChatReply' is missing the following properties from type 'PostReply': post
```

Looks like `query()` with TS unions causes errors? Is there a workaround? I'd imagine this is a pretty common use-case. Thanks!

**Comment by koskimas** [comment]
Unfortunately, union types don't work with objection typings. You need to work around that using, for example generics.
