### ISSUE TITLE
Method deleteById throws warning QueryBuilder#mergeContext` method is deprecated

### ISSUE THREAD

**Issue by alex-w0** [Vincit/objection.js#1889]
Is the method [deleteById](https://vincit.github.io/objection.js/api/query-builder/mutate-methods.html#deletebyid) still using internally the method mergeContext?
It gives me the following warning:
`QueryBuilder#mergeContext method is deprecated. The context method now behaves just like mergeContext. mergeContext method will be removed in 3.0`

**Comment by koskimas** [comment]
Nope, that method is not called internally. Are you sure you aren't using a plugin or something that overrides the deleteById and uses mergeContext?

**Comment by alex-w0** [comment]
Sorry my fault, i'm using indeed the plugin [objection-soft-delete](https://github.com/griffinpp/objection-soft-delete), which still is using mergeContext.
