### ISSUE TITLE
Cannot set transaction isolation level

### ISSUE THREAD

**Issue by AleG94** [Vincit/objection.js#1890]
The official documentation shows the following example code to set the isolation level for a transaction:

```js
const scrappy = await Person.transaction(async trx => {
    await trx.raw('SET TRANSACTION ISOLATION LEVEL SERIALIZABLE');
});
```

But when performing the raw query, the transaction has already began so I get the following error:

`Transaction characteristics can't be changed while a transaction is in progress`

I'm using the `mysql2` driver along with `MariaDB 10.4.8`.

Am I missing something? How can I set the isolation level for the transaction?

**Comment by koskimas** [comment]
The example works on postgres. See [the mysql documentation](https://dev.mysql.com/doc/refman/8.0/en/set-transaction.html). Weirdly it seems that on mysql, you can't set the isolation level of an ongoing transaction. You can only set the isolation level of the **next** transaction, which is insanely unsafe in a multi-threaded database. Another transaction may get executed before the one you meant and things will break.

Unfortunately it would seem that you cannot use mysql isolation levels with knex or objection, unless you set the connection pool size to 1.

**Comment by koskimas** [comment]
https://github.com/knex/knex/issues/581
