### ISSUE TITLE
Chain Collate Query to the Query builder - Allow Collation win search query

### ISSUE THREAD

**Issue by VrushabhGore** [Vincit/objection.js#1893]
### Trying to write a query which allow chain collation

Hi,

Is there a way to write a chain collate with the where clause so that the query becomes accent sensitive?

Currently I am using the raw function
`raw("Select email from user where email="àbc@example.com" collate utf8_bin")`

Is this the most optimal way of doing such queries or can we do better?

Any help is appreciated.

**Comment by abedmurrar** [comment]
you dont need to collate the query, and you don't need to use raw to enter non ASCII characters, you just to make sure you set the character set for the table or for the database or for the column on creation, if you haven't, you can alter it.

if you're using MySQL 8 here's an example

https://dev.mysql.com/doc/refman/8.0/en/charset-database.html

**Comment by koskimas** [comment]
There's no way to do that other than raw queries I'm afraid.
