### ISSUE TITLE
hasWheres returns false for instance query builder

### ISSUE THREAD

**Issue by kousun12** [Vincit/objection.js#1897]
This may be how this is intended to work but I'm having issues with the `hasWheres` method on `QueryBuilder`

```javascript
MyModel.query().hasWheres() // expect false
// false
const inst = await MyModel.query().findById(1)
inst.$query().hasWheres() // expect true
// false
```

I'd expect this single instance query builder to return true for `hasWheres` since what it ultimately generates will include a `where id = $` clause. Is that incorrect? If so, is there a way to check whether or not it's an instance query builder or a class query builder?

**Comment by abedmurrar** [comment]
```js
// this is a query, we're not checking if it has any where clause and it is executed
const inst = await MyModel.query().findById(1);

/* 
 * this is a total different query that does not include any where clause 
 * so it expects false
 */
inst.$query().hasWheres();
```


to check if `findById` has and where clause you need to perform the following action

```js 

// this is checking if query has any where clause
// expects true, returns true
const inst = await MyModel.query().findById(1).hasWheres();
```

**Comment by kousun12** [comment]
Right I get that instance query builders are separate but my argument is that they do have a where qualifier. In your example 

```javascript
inst.$query().toKnexQuery().toString()
``` 

would evaluate to something like 

```sql
select * from my_model where my_model.id = 1
```

which has a where clause. If there's some other way to check for the instance, I'm okay with that too, just not sure if there's a easy way to get that. I'm using

```javascript
const updateOperation = this._updateOperationFactory(this);
const isSingleInstance = updateOperation.instance instanceof this.modelClass();
```

from within the query builder, but it seems awkward
