### ISSUE TITLE
Static methods not exposed on Model Type 

### ISSUE THREAD

**Issue by elby22** [Vincit/objection.js#1898]
The static methods [Model.columnNameToPropertyName()](https://vincit.github.io/objection.js/api/model/static-methods.html#static-columnnametopropertyname) and [Model.propertyNameToColumnName() ](https://vincit.github.io/objection.js/api/model/static-methods.html#static-propertynametocolumnname) are defined in the docs and are implemented on the Model class, but aren't exposed in `typings/objection/index.d.ts`.

Typescript complains when I do something like this (User extends Model): 
`const propName = User.columnNameToPropertyName('first_name');`

Type casting User to any satisfies Typescript and outputs the mapped name `firstName`: 
`const propName = (<any>User).columnNameToPropertyName('first_name');
console.log(propName);`

I'd be happy to submit a PR if someone would confirm it is indeed a bug and not a misunderstanding on my part.

**Comment by yukulelix** [comment]
I run into the same problem :) !

**Comment by ducher** [comment]
I have the same problem! Some methods are missing from the typings.

**Comment by lehni** [comment]
I'd  be happy to review a PR adding these typings

**Comment by cesumilo** [comment]
> I'd be happy to review a PR adding these typings

Here it is! 😉

**Comment by lehni** [comment]
Closed by #2612
