### ISSUE TITLE
Support for polymorphic associations?

### ISSUE THREAD

**Issue by juanjoLenero** [Vincit/objection.js#19]
Are you planning to support polymorphic associations?

[Here's](https://gist.github.com/p-baleine/7703145) an example of it in another ORM. 
Another [one](http://docs.sequelizejs.com/en/latest/docs/associations/#1m).

I haven't delved into moron's source code but perhaps an API like this would work:

``` javascript
// Schema for a comment model which relates polymorphically 
// to several tables through the commentable and commentableId attributes.
Comment.jsonSchema = {
    type: 'object',

    properties: {
        id: {type: 'integer'},
        text: {type: 'string'},
        commentable: {type: 'string'},
        commentableId: {type: 'integer'},
        authorId: {type: 'integer'},
        createdAt: {type: 'string', format: 'date-time'},
        updatedAt: {type: 'string', format: 'date-time'}
    }
};

Comment.relationMappings = {
    // A comment can be related to a topic.
    topic: {
        relation: Model.OneToOneRelation,
        modelClass: __dirname + '/topic',
        join: {
            from: 'Comment.commentableId',
            to: ['Comment.commentable', 'id']
        }

    // A comment can also be related to a user's profile.
    profile: {
        relation: Model.OneToOneRelation,
        modelClass: __dirname + '/profile',
        join: {
            from: 'Comment.commentableId',
            to: ['Comment.commentable', 'id']
        }
    }
};

```

Or maybe something like this:

``` javascript
    topic: {
        ...
        join: {
           from: 'Comment.commentableId',
           morph: {table: 'Comment.commentable', attribute: 'id'},
        }
```

**Comment by koskimas** [comment]
I will definitely add some way to support polymorphic associations at some point. I'm just about to add a feature that allows you add a filter to relations like this:

```js
Topic.relationMappings = {
  comments: {
    relation: Model.OneToManyRelation,
    modelClass: Comment,
    // Extra filter query for the relation. This can be a hash of `{column: 'value'}` pairs
    // or a function that takes a query builder as a parameter.
    filter: {commentable: 'Topic'},
    join: {
      from: 'Topic.id',
      to: 'Comment.commentableId'
    }
  }
};

Profile.relationMappings = {
  comments: {
    relation: Model.OneToManyRelation,
    modelClass: Comment,
    filter: {commentable: 'Profile'},
    join: {
      from: 'Profile.id',
      to: 'Comment.commentableId'
    }
  }
};
```

This partially solves the problem, but you still have to set the `commentable` property by hand when inserting new `Comments`. Calling `someTopic.$relatedQuery('comments`).insert({text: 'foo'});` doesn't set the `commentable` property to `Topic`.

**Comment by juanjoLenero** [comment]
That filter feature looks great. I could live with setting the commentable property manually.

**Comment by koskimas** [comment]
Just pushed the filter feature to master.

**Comment by fiddur** [comment]
You could consider NOT supporting polymorphic associations and proposing a more SQLish pattern where you can use `FOREIGN KEY` constraints correctly.

In the above example, `Commentable` would be it's own model, and everything that you can comment would need to have a `commentable_id`, like in [Polymorphism in SQL database tables?](http://stackoverflow.com/questions/561576/polymorphism-in-sql-database-tables/562030#562030)

**Comment by fl0w** [comment]
@fiddur I recently got bitten by an "ORM-centric" polymorphic solution, as you said, there's no constraint integrity in those.

Any pointers/examples of how to achieve a more "SQLish" (great word) polymorphism using Objection.js?

**Comment by makeitrein** [comment]
@koskimas @fl0w @fiddur 

Have a Many-to-Many polymorphic join table, called **tagable_entity_tag** - it connects a **tagable_entity** like blog, document, or calendar with the **tag** row... does Objection allow for this sort of setup? I was having issues with getting the filter query to work on on the join table, can't quite figure that portion out.

Page Class
     tags: {
            relation: Model.HasManyRelation,
            modelClass: `${__dirname}/Tag`,
            filter: query => query.where('page:tagable_entity_tag.object_data:type', 'Page'),
            join: {
                from: 'page.page_id',
                through: {
                    from: 'tagable_entity_tag.tagable_entity_id',
                    to: 'tagable_entity_tag.tag_id'
                },
                to: 'tag.tag_id'
            }
        },

**Comment by makeitrein** [comment]
Ah! Think this will work for my use case...

The flow is as follows... page -> tagable_entity_tag w/ type: "Page" -> tag

So because I already had the tagable_entity_tag as query, all I needed to add was **.join("tag", "tagable_entity_tag.tag_id", "tag.tag_id")** to capture the rest of the tag's information.

```
tags: {
            relation: Model.HasManyRelation,
            modelClass: `${__dirname}/TagableEntityTag`,
            filter: query => query
                .join("tag", "tagable_entity_tag.tag_id", "tag.tag_id")
                .whereJsonField("tagable_entity_tag.object_data:type", "=", "Page"), // gotta do this for these polymorphic tables yo!
            join: {
                from: 'page.page_id',
                to: 'tagable_entity_tag.tagable_entity_id'
            }
        },
```

**Comment by juanjoLenero** [comment]
I no longer have a use case for my original request. I stopped using the `commentable(string), commentable_id(integer)` pattern where `commentable` would be a table name and `commentable_id` the id of a record on that table.

I started using another approach that is completely compatible with Objection and mantains referential integrity. It's known as an [exclusive arc](https://hashrocket.com/blog/posts/modeling-polymorphic-associations-in-a-relational-database#exclusive-belongs-to-aka-exclusive-arc-) table.

Here's how I would do it, for the use case of adding tags to different models.

You define your tables like this:
```sql
create table tags(
    id serial primary key,
    tag text not null
);

create table tags_taggables(
    id serial primary key,

    -- Tag
    tag_id integer not null references tags(id) on delete cascade,

    -- Taggables (one for each table that can be "tagged")
    post_id integer references posts(id) on delete cacade,
    event_id integer references events(id) on delete cacade,

    -- This constraint ensures that for any row only one of [post_id, event_id] is set
    constraint exactly_one_taggable check(
        (post_id is not null and event_id is null)
        or
        (post_id is null and event_id is not null)
    )
);
```

And the relation mapping in your model would look like this:
```js
class Event extends BaseModel {

    static get tableName () {
        return 'events';
    }

    static get relationMappings () {
        return {
            tags: {
                relation: BaseModel.ManyToManyRelation,
                modelClass: Tag,
                join: {
                    from: 'events.id',
                    through: {
                        from: 'tags_taggables.event_id',
                        to: 'tags_taggables.tag_id'
                    },
                    to: 'tags.id'
                }
            }
        };
    }
}
```

That's it. 

To add a tag to an event you would create a new row in the tags_taggables with `tag_id` and `event_id` set to the ids of the rows you want to associate. 

The best thing about this pattern is that referential integrity is mantained, you will never be able to associate a tag to a non-existing event or vice versa, you will also be able to use cascades to react to deletions on either sides of the association.

**Comment by devinivy** [comment]
@juanjoLenero never heard of that– thanks for sharing!

**Comment by PierBover** [comment]
Does anyone know how to implement the `constraint exactly_one_taggable` proposed by @juanjoLenero be implemented in knex?

**Comment by newhouse** [comment]
@PierBover (just saw your edit, but was nearly done with this comment, so I'll post anyways)
In trying to do some complex constraints, or dropping and redefining existing constraints, I ended up finding that it's not very well supported due to the differences between DB syntaxes, so I've always just done it with `raw`. Just 1 example, as there are several ways to do this:
```
exports.up = function(knex, Promise) {
  return Promise.all([
    knex.schema.createTable('foo', function(table) {
      // table definition stuff goes here
      ..
    ).raw('YOUR CONSTRAINT COMMAND(S) GO HERE')
  ];
}
```

**Comment by PierBover** [comment]
Thanks @newhouse I finally solved it like this:

```js
await knex.schema.createTable('Product', function(table) {
	table.increments('id').primary();
	table.string('type').notNullable().references('ProductType.code');
	table.integer('laptopId').references('Laptop.id')
	table.integer('tabletId').references('Tablet.id')
	table.integer('desktopId').references('Desktop.id')
}).raw(`
	alter table "Product"
	add constraint "exactlyOneProductType" check(
		("laptopId" is not null and "tabletId" is null and "desktopId" is null)
		or
		("laptopId" is null and "tabletId" is not null and "desktopId" is null)
		or
		("laptopId" is null and "tabletId" is null and "desktopId" is not null)
	)
`);
```

**Comment by newhouse** [comment]
Glad you figured it out @PierBover glad I can help with this repo's success. I really like it a lot

**Comment by koskimas** [comment]
Full support for this is finally implemented in commit d8d6a8c.

**Comment by jordansexton** [comment]
@koskimas Question -- in the example for polymorphic relationships, how does a comment get a relation mapping back to a commentable model? This is pseudocode, but is there a way to express this?

```javascript
class Comment extends Model {
  static get relationMappings () {
    return {
      commentable: {
        relation: BelongsToOneRelation,
        modelClass: <PullRequest | Issue>
        typeColumn: 'commentableType',
        join: {
          from: '<PullRequest | Issue>.id',
          to: 'Comment.commentableId'
        }
      }
    };
  }
}
```

**Comment by koskimas** [comment]
@jordansexton Unfortunately that's not possible. It would be a massive pain to get working with eager queries, graph inserts etc. What I implemented isn't actually a support for polymorphic associations, but a feature that accidentally makes most of it possible.

**Comment by jordansexton** [comment]
Ah, okay. That makes sense, thanks for the explanation.

**Comment by heisian** [comment]
I just figured out how to do an `N:M` polymorphic relationship through a join table, which isn't described in the documentation. This ORM is so well architected it was easy:

```node
class GoalKeeper extends Model {
  static get relationMappings() {
    return {
      yellowCards: {
        relation: Model.ManyToManyRelation,
        modelClass: YellowCard,
        filter: {
          playerType: 'goalKeeper',
          foulType: 'yellowCard',
        },
        beforeInsert(model) {
          model.playerType = 'goalKeeper'
          model.foulType = 'yellowCard'
        },
        join: {
          from: 'goalKeepers.id',
          through: {
            from: 'playersFouls.playerId',
            to: 'playersFouls.foulId',
            extra: ['playerType', 'foulType'],
          },
          to: 'fouls.id'
        }
      }
    }
  }
}
```

I am currently in the process of ditching Sequelize - it proved too painful to be good for LTS. Thanks a ton, @koskimas. I hope to be able to make contributions as we start using your ORM in prod.

[getethos.com](getethos.com)

**Comment by capaj** [comment]
@heisian good decision. We did the same at @LeapLabs and we're very glad we did. Objection is awesome.

**Comment by gordonk** [comment]
@koskimas thank you for the awesome work.  I've worked with typeorm, sequelize and bookshelf and this stays right in the lane I want an ORM to.

I'm converting a project to objection, primarily because the knex connection injection is the cleanest approach to multi-database multi-tenancy I've seen in node.

And I've just just hit a difficult blocker. As described in @jordansexton comment above, I just can't work out how to get back from the child polymorphic model, to the parent, '-able' model.  

I'm just checking in, that nothing has changed since Jordan posted.  I'm loving this so much I guess I'll have to rearchitect the table maybe STI with individual belongsTo if not happening.

https://github.com/Vincit/objection.js/issues/19#issuecomment-350504103

Thanks again.

**Comment by meelash** [comment]
Given that this issue is linked from the documentation, I'd like to share a simple solution for getting back the commentable models from the comments. Obviously, this doesn't cover all general cases, as mentioned above, that is difficult. But on a use case-by-use case basis, objection is flexible enough to be able to do it.

Using the example with tags and taggables: https://github.com/Vincit/objection.js/issues/19#issuecomment-291621442, I have the following relationship to the taggable defined in tags:
```
class Tag extends BaseModel {

    static get tableName () {
        return 'tags';
    }

    static get relationMappings () {
        return {
            taggable: {
                relation: BaseModel.HasOneRelation,
                modelClass: Taggable,
                join: {
                    from: 'tags.id',
                    to: 'tags_taggables.tag_id'
                },
                modify: (builder) => {
                    builder
                        .leftJoin('posts', 'tags_taggables.post_id', 'posts.id')
                        .leftJoin('events', 'tags_taggables.event_id', 'events.id')
                        .select('posts.*', 'events.*');
                }
            }
        };
    }
}
```
Since only one of post_id and event_id are ever not null, the taggable property returned from the database will have all the values of the defined one (and null for any columns that exist in the undefined one and not in the defined one).

Then the class Taggable instantiates the correct models from the data:
```
class Taggable extends Model {
  static tableName = 'tags_taggables';

  static fromDatabaseJson(json) {
    let taggable;
    switch json.something_identifiable {
      case 'post':
        taggable = new Post();
        break;
      case 'event':
        taggable = new Event();
        break;
      default:
        throw new Error('Unknown taggable type');
    }
    return taggable;
  }
}
```

The advantage of this approach is that you can select all the columns in post and event with the wildcard '*'. However, you have to have some reliable way of identifying which type is which in the data itself.

Some other approaches (not tested completely, may have mistakes) in the modify are as follows:
```
        .select(raw(`
          JSON_OBJECT(
            'post', CASE WHEN post.id IS NOT NULL THEN JSON_OBJECT(
              'id', post.id,
              'column1', post.column1,
              .
              .
              .
              'type', 'post'
            ) END,
            'event', CASE WHEN event.id IS NOT NULL THEN JSON_OBJECT(
              'id', event.id,
              'column1', event.column1,
              .
              .
              .
              'type', 'event'
            ) END
          ) as taggable
        `));
```
or, using coalesce to only get a JSON_OBJECT with the appropriate data. In these latter approaches, you'd need to specify all the columns you want back, but you don't need an identifying characteristic in the data itself.
