### ISSUE TITLE
either `from` or `to` must point to the owner model table.

### ISSUE THREAD

**Issue by mariotacke** [Vincit/objection.js#190]
I'm having a hard time understanding this error: `Manager.relationMappings.user: join: either 'from' or 'to' must point to the owner model table.`. I have two classes, `Manager` and `User`; `Manager` is a sub-type to `User`.

### Models
```js
class User extends Model {
  static get tableName () {
    return 'user';
  }
}

class Manager extends Model {
  static get tableName () {
    return 'manager';
  }

  static get relationMappings () {
    return {
      user: {
        relation: Model.HasOneRelation,
        modelClass: User,
        join: {
          from: 'Manager.id',
          to: 'User.id'
        }
      }
    };
  }
}
```

### Query
```js
const user = yield Manager
  .query()
  .joinRelation('user')
```

I tried setting up a corresponding relation on `User` but it did not make a difference. I am probably misunderstanding something... Love the lib thus far!

**Comment by koskimas** [comment]
The reference needs to be `TableName.columnName` so in your case `user.id`  and not `User.id`. ES6 classes always have a name and we could use that, but for ES5 compatibility the table name is used.

Also you seem to be joining `user.id` to `manager.id` which is a primary key to primary key join. You probably want something like

```js
from: `manager.userId`,
to: `user.id`
```

**Comment by mariotacke** [comment]
Wow... thanks for answering this so quickly! Indeed, it was the lower-casing of the class name. Does this apply to the docs as well? They all seem Pascal-cased. 

Btw, i'm intentionally joining on primary key, because `Manager` is a sub-type to `User`.

Thanks!

**Comment by koskimas** [comment]
Ah, okay :D. The examples use PascalCase because the table names are also PascalCased in them.
