### ISSUE TITLE
Json validation date-time ISO8601 is not compatible with mysql datetime type

### ISSUE THREAD

**Issue by alex-w0** [Vincit/objection.js#1900]
The JSON schema validation has a format type called ["date-time"](https://json-schema.org/understanding-json-schema/reference/string.html?highlight=date%20time#built-in-formats) that accepts an ISO string as a valid input: `2018-11-13T20:20:39+00:00`

Unfortunately the [mysql datetime type](https://dev.mysql.com/doc/refman/8.0/en/datetime.html) requires this kind of format `YYYY-MM-DD hh:mm:ss` and will throw an error when an ISO string is given: `ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2020-11-01T12:50:42.063Z' for column` 

Someone else has experienced the same problem and can tell me how normally this use case will be handled?

**Comment by ombak** [comment]
A few days ago I had a problem similar to yours. I have problem when save to my DB from API in date-time type.
I solve the problem with this:
1. I use { format: 'date-time' } in my model jsonSchema
2. Because I use Joi for validation. This the validation Joi.date().timestamp()
3. And I input with value timestamps ( milliseconds ). You can see this link https://www.timestampconvert.com
I hope this can give you some clue to solve yours issue.

**Comment by alex-w0** [comment]
@ombak I solved it a little bit different now, because I would like to have the same type format in the validation and in the database. I've overwritten the validation for the date-time:


```
    static createValidator() {
        return new AjvValidator({
            onCreateAjv: (ajv) => {
                ajv.addFormat('date-time', {
                    validate: (dateTimeString) =>
                        dayjs(
                            dateTimeString,
                            'YYYY-MM-DD HH:mm:ss',
                            true
                        ).isValid(),
                });
            },
            options: {
                allErrors: true,
                validateSchema: false,
                ownProperties: true,
                v5: true,
            },
        });
    }
```

Dayjs has an option where it's possible to define that the input must match exactly the format that is specified: https://day.js.org/docs/en/parse/string-format
The validation can be done with any other date libary or regex.

**Comment by ombak** [comment]
@alex-w0 Good to hear you solve the issue. And for me I got new insight from your way. 
Thanks.

**Comment by alex-w0** [comment]
@ombak  No problem, I'm also glad to get other solution proposals as well 👍
