### ISSUE TITLE
Reference base model in Relation Expression?

### ISSUE THREAD

**Issue by alukach** [Vincit/objection.js#1902]
Is it at all possible to reference the root model in a relation expression?  

Scenario: Using the standard `Person.[parent, pets, movies]` example (see below).
<details>

<summary>Example data</summary>

```js
[{
  id: 1,
  firstName: 'Jennifer',
  lastName: 'Aniston',

  // This is a BelongsToOneRelation
  parent: {
    id: 2,
    firstName: 'Nancy',
    lastName: 'Dow'
  },

  // This is a HasManyRelation
  pets: [{
    id: 1,
    name: 'Doggo',
    species: 'Dog',
  }, {
    id: 2,
    name: 'Kat',
    species: 'Cat',
  }],

  // This is a ManyToManyRelation
  movies: [{
    id: 1,
    name: 'Horrible Bosses',

    reviews: [{
      id: 1,
      title: 'Meh',
      stars: 3,
      text: 'Meh'
    }]
  }, {
    id: 2,
    name: 'Wanderlust',

    reviews: [{
      id: 2,
      title: 'Brilliant',
      stars: 5,
      text: 'Makes me want to travel'
    }]
  }]
}]
```
</details>

 I'd like an endpoint purely focused on updating an existing person's properties and relating/unrelating pets.  An example upsert could be:

```js
const options = {
  relate: ['pets'],
  unrelate: ['pets'],
  noUpdate: ['pets', 'parent', 'movies']
};

await Person.query().upsertGraph(
  {
    id: 1,
    firstName: "Jenny",  // New name
    lastName: "Aniston",
    pets: [
      {
        id: 2,
        name: "Kat",
        species: "Cat",
      },
    ], // Omit dog
  },
  options
);
```

However, I find the `noUpdate: ['pets', 'parent', 'movies']` declaration to be a bit cumbersome and somewhat difficult to maintain (e.g. if I were to add a new relation to the `Person` model, I'd need to find all upserts and append the relation to the `noUpdate` clause).  What would be ideal would be to either a) specify that I can't update any relation (e.g. `{update: true, noUpdate: ['.*']}`) or b) specify that I can update the base model (e.g. `{update: ['.']}`).

It's entirely possible that this may be doable today, however it is not clear to me how to do so.  I'm still a novice with this library so please do point out if I'm missing a bigger part of the picture.

**Comment by koskimas** [comment]
There is no easier way to do that. Please consider not using upsertGraph at all, or only using it when it makes the code much simpler and shorter. Most of the time it just makes the code slow, unreadable and impossible to maintain.
