### ISSUE TITLE
Open and close connection to the database for each query?

### ISSUE THREAD

**Issue by binemecio** [Vincit/objection.js#1903]
I can't find the way to create a connection for each query made to the database (I don't want to work with connection pool)

example:

Is there a way to open a connection for each query?
If 100 users connect at the same time, they would have 100 active connections and they would immediately close when they stop using them.

An example of what I am looking for

```
endpoint: getDevices {
   const conecction = createConecction ()
   const response = await
   DeviceModel.conection (connection) .query () ...
   conecction.close ()
   return response
}
```

Thanks in advance

**Comment by koskimas** [comment]
There's no way to do that.
