### ISSUE TITLE
selectRaw is orphaned ?

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#1905]
Hi,
https://github.com/Vincit/objection.js/search?q=selectRaw

https://github.com/Vincit/objection.js/blob/master/doc/recipes/raw-queries.md#raw-queries mentions selectRaw but knex does not and it's nowhere else to be found.

**Comment by lehni** [comment]
It is missing indeed. You can add it yourself in your own `QueryBuilder` class:

```js
  selectRaw(...args) {
    return this.select(this.knex().raw(...args))
  }
```

**Comment by kapouer** [comment]
I only care because doc != implementation.
In fact, i think selectRaw and whereRaw should be dropped in favor of select(raw) and where(raw).
