### ISSUE TITLE
How to create method in model to get relation data

### ISSUE THREAD

**Issue by ombak** [Vincit/objection.js#1906]
I have two table :
1. table job_learnings
2. table job_learning_tasks, this table have foreign key from job_learnings (job_learning_id)

In class model job_learnings I want create method who query to get data from table job_learning_tasks:

```
class JobLearningModel extends Model {
     ...
     getJobLearningTasks() {
          return JobLearningTaskModel.query().where('job_learning_id', this.id);
     }
     ...
}
```

Instance object and try to get job_learning_tasks data.

```
let project = await JobLearningModel.query().findById(1);
console.log('project id' + JSON.stringify(project.getJobLearningTasks())); //<--- not return data from table job_learning_tasks
```
My question is, it is possible to create method in model to query relation table? If possible, can I get the correct way to do that.

Many thanks.

**Comment by koskimas** [comment]
You need to use `await`. All queries are asynchronous. Also see the `$relatedQuery` method in the docs.

**Comment by ombak** [comment]
Thank for your response @koskimas, But I don't use `await` in my query in model because when I use it, I got error.
`SyntaxError: await is only valid in async function`

**Comment by ombak** [comment]
Thanks @koskimas, I thing I don't need `await` to run query from instance model. 
Now the code has run. This my correct code:
```
let _project = await DlJobLearningsModel.query().findById(data['id']);          
let _tasks = await _project.getJobLearningTasks();
```
