### ISSUE TITLE
Symmetric many-to-many to self

### ISSUE THREAD

**Issue by jorr** [Vincit/objection.js#1907]
This is more of a question for @koskimas than an issue.

I have a symmetric relationship on a model, where two instances are deemed to be "similar". I only want to store the relationship once in the DB because it's obviously redundant to do otherwise. So i have a many-to-many to self:

```js
similar: {
        relation: Model.ManyToManyRelation,
        modelClass: MyModel,
        join: {
          from: 'mymodels.id',
          through: {
            from: 'mymodels_similarity.first',
            to: 'mymodels_similarity.second'
          },
          to: 'mymodels.id'
        }
      },
```

Now let's say i have instance A and instance B that are similar. When I write to the DB, I use:
```js
MyModel.relatedQuery('similar').for(A.id).relate(B.id);
```

However, this doesnt preserve the symmetry obviously. If I fetch A with the relationship, I do have B as similar. But if I fetch B, I don't have A as similar, because the relationship is only defined one-way.

What is the best way to address this? Obviously I can define a second relationship and swap "from" and "to" but that's super awkward. I was thinking of using "beforeFind" but I see no way to modify the query and add an additional orWhere (assuming i can check whether the relation was fetched but it seems i can). I was also thinking of using parseDatabaseJson and add additional properties to the instance but I can't in fact do that because nothing would be fetched from the DB for B in the first place.

Short of raw queries what can I possibly do? This can't really be a very isolated case.. ?

**Comment by ombak** [comment]
Looks like you need two relation for solve your problems:

```
similarFirst: {
	relation: Model.ManyToManyRelation,
	modelClass: MyModel,
	join: {
		from: 'mymodels.id',
		through: {
			from: 'mymodels_similarity.first',
			to: 'mymodels_similarity.second'
		},
		to: 'mymodels.id'
	}
},
similarSecond: {
	relation: Model.ManyToManyRelation,
	modelClass: MyModel,
	join: {
		from: 'mymodels.id',
		through: {
			from: 'mymodels_similarity.second',
			to: 'mymodels_similarity.first'
		},
		to: 'mymodels.id'
	}
},
```
I hope you get clue to solve your problems.

**Comment by jorr** [comment]
@ombak well i mentioned this possibility in my text but i dont like it, it's super awkward and doesnt capture the semantics well.

**Comment by koskimas** [comment]
There's no way to model this as a relationship. The best solution is to write a custom SQL. Something like this:

```js
function getSimilar(id) {
  return MyModel.query()
    .whereIn('id', MyModelsSimilarity.query().where('first', id).select('second'))
    .orWhereIn('id', MyModelsSimilarity.query().where('second', id).select('first'))
}
```
