### ISSUE TITLE
this.query() is not function

### ISSUE THREAD

**Issue by ombak** [Vincit/objection.js#1908]
Hello...

I have class MasterModel:

```
const { Model } = require('objection');

class MasterModel extends Model {
     // method to save
     toSave(data, graph=false) {
          if (graph) {
               return this.query().insertGraph([data], { relate: true });
          }
          return this.query().insert(data);    
     }
}
```

And my model:

```
class JobModel extends MasterModel {
     // jsonSchema
     static get jsonSchema() {
          ... 
     }
}
```

And I call my model to save data in another file
```
let data = { ...my data... }
let _save = new DlJobLearningsModel();
let _data = await _save.toSave(data);

```

When I run the code, I got error `this.query is not a function`
My question is, can I write master model to describe my save function? so I can use for all my code.

Many Thanks.

**Comment by koskimas** [comment]
`query` is a static method.

**Comment by ombak** [comment]
Sorry @koskimas, can you give me some sample code to make run my masterModel. Thanks very much.
