### ISSUE TITLE
Query returns wrong values due to related-query conditions

### ISSUE THREAD

**Issue by andrucz** [Vincit/objection.js#1909]
`A` has a list of `B`, and `B` has a list of `C` and `D`.

I'm writing a query that returns all fields of `A`, and the number of related `B` records that have any `C` or `D`.

```
A.query(db).select(
      'a.*',
      A.relatedQuery('b')
        .whereExists(B.relatedQuery('c'))
        .orWhereExists(B.relatedQuery('d'))
        .count()
        .as('usedBCount'),
    );
```

It ends up generating a query like this: `b.a_id = a.id and exists (b.c) or exists (b.d)`. Given that `false and false or true` returns `true `, the query returns wrong results for `usedBCount`.

I solved the issue by creating a sub builder. so that it generates `b.a_id = a.id and (exists (b.c) or exists (b.d))`. That seems not straightforward, though.

**Comment by koskimas** [comment]
You don't need to use a subquery. You can (and always should) wrap your `OR` conditions in parentheses:

```js
A.query(db).select(
      'a.*',
      A.relatedQuery('b')
        .where(qb => {
          qb.whereExists(B.relatedQuery('c'))
          qb.orWhereExists(B.relatedQuery('d'))
        })
        .count()
        .as('usedBCount'),
    );
```
