### ISSUE TITLE
Before insert issue when bulk inserting entities

### ISSUE THREAD

**Issue by nunovieira220** [Vincit/objection.js#1911]
**Problem and use-case**

Imagine a `post` model entity that has an `order` field. Before inserting a new `post`, I add the `order` field based on the max `order` of the older `posts` (auto-increment is not a possibility since we are not using numeric values). Everything works as expected except when inserting multiple `posts` because those entities depend on each other and the `beforeInsert` method will add the same `order` in all posts.

I know this is happening because those entities are still not inserted but is there a better way to solve this instead of inserting one by one?

**Example**
You have [here](https://github.com/nunovieira220/objection-bulk-insert-issue) a very simple example if it helps.

**Comment by koskimas** [comment]
There's at least two better options:

1. Create a database after insert hook that sets the value
2. Add a query column to each inserted row:

```js
await Person.query().insert({
  ...person,
  order: Person.query().max('order')
})
```
