### ISSUE TITLE
Typescript interface for model query arguments

### ISSUE THREAD

**Issue by tonyfm15** [Vincit/objection.js#1912]
I understand that JSON schema can be used at run-time to validate query arguments for a given model (i.e. child class of Model).

Is there any way to derive a typescript interface from a model so that query arguments can be type-checked at compile time instead?

**Comment by koskimas** [comment]
No. There's no way to create typescript for json schema. For example, how would you generate an interface for this

```
{
  type: 'object',
  properties: {
    foo: { type: 'number', minimum: 10 },
  }
}
```

**Comment by tonyfm15** [comment]
Sorry, my question was poorly worded. I don't know much about JSON schema so I can't comment on your response. I'm interesting in typing the inputs to queries based on the model definition. For example, if I have:

```typescript
class MyModel extends Model {
    static tablename = 'mytable';
    name!: string;
    id!: number;
}
```

I would like to programmatically generate an interface like:

```typescript
interface MyModelColumns {
   name!: string;
   id!: number;
}
```

I don't see how to derive this from `MyModel` directly, since it contains many other properties and methods. Do `ModelObject` or `PartialModelObject` have anything to do with this?

**Comment by asabatba** [comment]
Codegen might be worth looking into:
[json-schema-to-typescript](https://github.com/bcherny/json-schema-to-typescript)

Closest thing I've gotten is using the jsonSchema static and compile it using json-schema-to-typescript into a different .ts file.
The interface in that file is then implemented by the original Model.

```
// Company.ts
class Company extends Model implements CompanySchema {
...
}
```

```
// CompanySchema.ts generated by json-schema-to-typescript
interface CompanySchema { ...}
```

```
// file that compiles the schemas
compile(Company.jsonSchema as any, 'CompanySchema').then(ts => {

    fs.writeFileSync('somewhere/CompanySchema.ts', ts);
})
```

It's pretty contrived, and it only adds type checking to the Model (you have to type it out again) but i'ts something.
