### ISSUE TITLE
Support Knex's new onConflict method

### ISSUE THREAD

**Issue by willsoto** [Vincit/objection.js#1913]
As part of v0.21.10, Knex added support for [`onConflict`](https://knexjs.org/#Builder-onConflict). 

Is support for it "free" as long as you update to the correct version of Knex? It looks like typings will need to be updated at the very least.

**Comment by frdrwrt** [comment]
Getting the error `Person.query(...).insert(...).onConflict is not a function`, if using it like this:
```
await Person.query(db)
       .insert(data)
       .onConflict('id')
       .merge();
```

If using `.toKnexQuery()` it works. But I assume that is not how it should work.
```
await Person.query(db)
       .toKnexQuery()
       .insert(data)
       .onConflict('id')
       .merge();
```

**Comment by koskimas** [comment]
There's already a PR for that [here](https://github.com/Vincit/objection.js/pull/1904). It will get merged faster if you can help out the author.
