### ISSUE TITLE
findByIds() generates an invalid query for composite IDs

### ISSUE THREAD

**Issue by rafaelvcaetano** [Vincit/objection.js#1914]
When a model has a composite ID, calling `findByIds` with an empty array generates an invalid query.

Lets assume a model `Sample` like this:

```js
class Sample extends Model {
    static get tableName() {
        return 'sample';
    }

    static get idColumn() {
        return ['id_a', 'id_b'];
    }
}
```

Querying the model like this:
`await Sample.query().bindByIds([]);`
Generates the following invalid query:
`select * from "sample" where ("id_a", "id_b") in (());`

The correct query should be (notice the missing set of parenthesis):
`select * from "sample" where ("id_a", "id_b") in ();`

**Comment by koskimas** [comment]
Objection uses knex to generate the SQL.
