### ISSUE TITLE
sort by virtual attribute and page results

### ISSUE THREAD

**Issue by z1haze** [Vincit/objection.js#1918]
Given that virtual attributes are calculated in JS, after the query is run, how might I achieve being able to filter my query results by a virtual attribute and still use the paging functionality?

Does Objection provide a way to page without having a query builder, eg call page() on the results collection?

**Comment by koskimas** [comment]
There's no way to use virtual attributes to sort the query, but you can just sort by an expression, just like you would with SQL:

```js
await Person.query().orderBy(raw('(some * sql) + expression - here'))
```

There's no concept of collection in objection. Objection is a query builder.
