### ISSUE TITLE
Cannot use withGraphFetched and withGraphJoined in same query

### ISSUE THREAD

**Issue by lenolib** [Vincit/objection.js#1923]
I have a use case where I would like to use withGraphJoined and withGraphFetched in the same query. This does not seem to be possible however as this example shows (`PoiModel` is a model with two BelongsToOne relations `story` and `type`):
```sql
nesh> PoiModel.query().withGraphFetched('story').withGraphJoined('type').then()
Promise { <pending> }
knex:query select "pois"."id" as "id", "pois"."name" as "name", "pois"."type_id" as "type_id",
"story"."id" as "story:id", "story"."name" as "story:name",
"type"."id" as "type:id", "type"."organization_id" as "type:organization_id", "type"."name" as "type:name"
from "pois"
left join "stories" as "story" on "story"."id" = "pois"."story_id"
left join "object_types" as "type" on "type"."id" = "pois"."type_id" undefined +2s

nesh> 
nesh> PoiModel.query().withGraphJoined('story').withGraphFetched('type').then()
Promise { <pending> }
knex:query select "pois".* from "pois" undefined +13s
knex:query select "object_types".* from "object_types" where "object_types"."id" in (?) undefined +10ms

nesh> 
```
As we can see in the first case the `story` relation is fetched eagerly even though this was not specified. In the second the `story` relation is not fetched at all.

The reason for wanting to use `withGraphJoined` is to be able to filter and sort on a relation, and the reason for wanting to use `withGraphFetched` in the same query is as to not mess up the number of matching rows for one-to-many relations (retrieved by `count(*) OVER() AS full_count`)

**Comment by koskimas** [comment]
You can probably replace `withGraphJoined` by `joinRelated`.
