### ISSUE TITLE
Question: Optimizing WhereInEagerAlgorithm for models with multiple ID columns 

### ISSUE THREAD

**Issue by pvatterott** [Vincit/objection.js#1926]
Mainly looking for advice/guidance here. For context, we're still on Objection 1.6.11, but open to hearing solutions that would only work on 2.x.x

Basically, we have a multi-tenant SaaS app that's sharded based on an `owner_id` column. Basically all of our models have the `idColumn` on the model set to `[owner_id, id]`. The primary key is on `(owner_id, id)` and when querying data the `owner_id` value will be the same for the entire query. Objection assumes (fairly) that both the `owner_id` and `id` columns will vary in a given batch of eager loads, which leads to queries like this:
```sql
select * from user where (owner_id, id) IN ((1, 1), (1, 2), (1, 3))
```
and query plans like this:
```
	Query Text: select * from user where (user.owner_id, user_id) in (($1, $2), ($3, $4), ($5, $6))
	Bitmap Heap Scan on user  (cost=38.52..44.67 rows=3 width=128) (actual time=121.078..1986.130 rows=957 loops=1)
	  Recheck Cond: (((owner_id = 1) AND (id = 1)) OR ((owner_id = 1) AND (id = '2)) OR ((owner_id = 1) AND (id = 3))
	  ->  BitmapOr  (cost=38.52..38.52 rows=3 width=0) (actual time=110.885..110.885 rows=0 loops=1)
	        I/O Timings: read=110.350 write=0.023
	        ->  Bitmap Index Scan on user_pkey (cost=0.00..2.57 rows=1 width=0) (actual time=0.014..0.014 rows=2 loops=1)
	              Index Cond: ((owner_id = 1) AND (id = 1))
	        ->  Bitmap Index Scan on user_pkey (cost=0.00..2.57 rows=1 width=0) (actual time=0.783..0.783 rows=1 loops=1)
	              Index Cond: ((owner_id = 1) AND (id = '2))
	        ->  Bitmap Index Scan on user_pkey (cost=0.00..2.57 rows=1 width=0) (actual time=0.837..0.837 rows=2 loops=1)
	              Index Cond: ((owner_id = 1) AND (id = 3))
```

It would be a big win for us, performance wise, if we could rewrite all of those like this:
```sql
select * from user where owner_id = 1 AND id IN (1, 2, 3)
```
which would give us this query plan:
```
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| QUERY PLAN                                                                                                                                                                              |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Index Scan using user_pkey on user (cost=0.56..7.14 rows=1 width=128)                                                                                                                   |
|   Index Cond: ((owner_id = 1) AND (id = ANY ('{1,2,3}')))                                                                                                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

It would be a nice win for us across the board to move all of our eager loading logic to index scans. Has anyone solved this before? Would love to hear any guidance for extending or patching Objection to get this query behavior.

Thanks!

**Comment by koskimas** [comment]
I think the database/relation design is at fault here. If `owner_id` is enough to create the relation, why not just use `owner_id` in the relation instead of both `id` and `owner_id`? There's nothing in objection that forces the other end of a relation to be the full primary key. Also if the `id` or `owner_id` are alone enough to uniquely identify a row, there's no reason to create a compound primary key. If it's the uniqueness you are after, you can create an unique compound index instead.

**Comment by pvatterott** [comment]
@koskimas it looks like you added a comment but may have removed it. Would it be helpful for me to elaborate on your questions here?

**Comment by koskimas** [comment]
Would a compound index for `id` and `owner_id` help?

```sql
CREATE INDEX user_id_owner_id_index ON "user" (id, owner_id);
```

**Comment by koskimas** [comment]
Or simply adding an index for `owner_id` if it doesn't have one already.

**Comment by koskimas** [comment]
That's a really weird query plan you are getting. How many rows does the `user` table have?

**Comment by pvatterott** [comment]
Adding another compound index on `(id, owner_id)` wouldn't help since the compound primary key is an implicit compound index on `(id, owner_id)`. The issue is with the generated query format, which requires a bitmap heap scan instead of an index scan.

An index just on `owner_id` or an index just on `id` could be used, though Postgres would still need to `Recheck cond` on the additional condition which would be a performance hit. For security purposes, we never query just the `id` column - every query for a specific tenant must include the `owner_id`, so our indexes are created with that expectation and queries that aren't generated via a relation work well with a condition on `ownerId`.

The `user` table is around 1M rows and there are a few hundred `owner_id`s, for perspective.

**Comment by koskimas** [comment]
I see no reason why postgres couldn't use a compound index to optimize that query if it wanted to. That's why I was wondering about the query plan. Or is there something I'm missing?

The only thing objection could do in this case is to detect cases where all compound key tuples in a list have a common element, and extract that outside the `where in` list. And that's not something objection (or any ORM for that matter) should be doing. That's the job of the query optimizer, and for some reason, it's failing.

You can always try to use the `joinEager` to see if that's more efficient in your case, or not use eager loading at all for the affected queries and write custom queries.

**Comment by koskimas** [comment]
By the way, did you notice that one of your id's is `'2` and others are numbers. What's that about?

**Comment by pvatterott** [comment]
Just simplified the plans to make things easier to read, we actually use `uuid`s.

Yes, this is certainly something the query optimizer could handle, but it doesn't, hence my question. I don't expect a generic solution for Objection, which is why I phrased the question as "is there any way for us to extend or patch Objection to do this?" and not "this is a bug in Objection"

I understand that we rewrite every single one of our eager loads. We've done that in some key places, but I was hoping for some guidance on how we could solve this generically in our codebase. If that's not possible, that's fine.

**Comment by koskimas** [comment]
You could create a custom query builder and override the `whereInComposite` method. There you could check the special case where one of the compound values is shared and optimize the query.

**Comment by koskimas** [comment]
Something like this:


```js
const { QueryBuilder } = require('objection');

class CustomQueryBuilder extends QueryBuilder {
  whereInComposite(cols, values) {
    if (Array.isArray(cols) && cols.length > 1 && Set(values.map(it => it[0])).length === 1) {
      return this.where(builder => builder.where(cols[0], values[0][0]).whereInComposite(cols.slice(1), values.map(it => it.slice(1)))
    } else {
      return super.whereInComposite(cols, values);
    }
  }
}

class BaseModel {
  static QueryBuilder = CustomQueryBuilder;
}

// Extend all your models from `BaseModel` instead of `Model`.
class User extends BaseModel {

}
```

**Comment by pvatterott** [comment]
That sounds like just what we're looking for, and is likely worth the upgrade to >= 2.0.0

Really helpful, thank you!

**Comment by koskimas** [comment]
Let me know if it works. I didn't try the code.
