### ISSUE TITLE
yet another undefined as argument #1 in whereComposite

### ISSUE THREAD

**Issue by o1dnik** [Vincit/objection.js#1928]
Hi,

I have read the documentation and searched for issues, but still do not understand how the raw query may work or how to perform a composite where requests. Here's an example of what I do:

```
.whereComposite(["baseUrl"], "LIKE", [`%${referrer}%`])
```

```
.whereRaw(`baseUrl LIKE %${referrer}%`)
```

```
.where(raw(`baseUrl LIKE %${referrer}%`))
```

on the model which is very simple and only has a foreign key on another model. The table in Postgres got "id" field as primary. So what's the catch, why does it not work?

**Comment by koskimas** [comment]
Composite query is a query, where there are multiple columns involved. This isn't one. Queries 2 and 3 are missing a `'` marks around the search string. This is a valid query:

```js
.where('baseUrl', 'LIKE', `%${referrer}%`)
```
