### ISSUE TITLE
.resolve() still goes through database for relations if resolved data uses Model instances

### ISSUE THREAD

**Issue by mogzol** [Vincit/objection.js#1929]
Lets say I have a couple entities like so:

```typescript
class Pet extends Model {
  public static tableName = "pets";

  public id: number;
  public personId: number;
  public name: string;
}

class Person extends Model {
  public static tableName = "people";

  public id: number;
  public name: string;
  public pets?: Pet[];

  public static relationMappings = {
    pets: {
      relation: Model.HasManyRelation,
      modelClass: Pet,
      join: { from: "people.id", to: "pets.personId" },
    },
  };
}
```

Now I want to skip the database using `.resolve()` for a certain query that includes a `.withGraphFetched()`, like this:

```typescript
  const result = await Person.query()
    .withGraphFetched("pets")
    .resolve([
      new Person().$set({
        id: 1,
        name: "Bob",
        pets: [
          new Pet().$set({ id: 1, personId: 1, name: "Max" }),
          new Pet().$set({ id: 2, personId: 1, name: "Buddy" }),
        ],
      }),
      new Person().$set({
        id: 2,
        name: "Doug",
        pets: [new Pet().$set({ id: 3, personId: 2, name: "Coco" })],
      }),
    ]);
```

This does skip the database for the Person part, and returns "Bob" and "Doug" from my resolve data, but it goes through the database for the relations, so the Pets end up coming from the database rather than using the ones in my resolve data. 

If I use plain objects rather than Model instances in the resolve data (i.e. `.resolve([{ id: 1, name: "Bob", pets: ... }, ... ])`, then it works properly, and there are no database queries, but the returned data is just plain objects, and I need the query to return Models like it would if it went through the database.

Is there any way to make this work properly? I know in this example I can just take out the `.withGraphFetched()`, but in my actual program that's not really possible.

**Comment by koskimas** [comment]
Resolve only resolves the query you call it for. withGraphFetched runs multiple queries. Works as expected.
