### ISSUE TITLE
query() by default

### ISSUE THREAD

**Issue by sheerun** [Vincit/objection.js#193]
Hey,

Is there any reason why query() isn't used by default in knex? Instead of followng:

```
Person
  .query()
  .where('age', '>', 40)
  .andWhere('age', '<', 60)
  .andWhere('firstName', 'Jennifer')
  .orderBy('lastName')
  .then(function (middleAgedJennifers) {
    console.log('The last name of the first middle aged Jennifer is');
    console.log(middleAgedJennifers[0].lastName);
  });
```

I'd like to write only

```
Person
  .where('age', '>', 40)
  .andWhere('age', '<', 60)
  .andWhere('firstName', 'Jennifer')
  .orderBy('lastName')
  .then(function (middleAgedJennifers) {
    console.log('The last name of the first middle aged Jennifer is');
    console.log(middleAgedJennifers[0].lastName);
  });
```

It's the same for many other operators. `query()` seems to be extra detail I need to care about.

Couldn't it be solved with something like:

```
Model.where = function (...args) {
  return Model.query().where(...args)
}
```

**Comment by elhigu** [comment]
It is there to make clear distinction when you are actually creating database queries and using query builder and when you are just calling methods of an class / instance. Also that way it is kind of consistent with `knexQuery()`which gives you knex query builder (this is less important though).

IIRC those methods were directly in interface of model before the release of `objection.js` (in some early internal versions used only inside the company), but it was even more confusing to make separation of query builder and normal methods of Models.

**Comment by koskimas** [comment]
@elhigu pretty much summed it up. Nothing stops you from doing something like this:

```js
class BaseModel extends Model {}

_.forOwn(objection.QueryBuilder.prototype, (method, name) => {
  BaseModel[method] = function (...args) {
    return this.query()[method](...args);
  };
});
```

and then just inheriting your models from `BaseModel`.

**Comment by sheerun** [comment]
ok then, thank you for a quick answer
