### ISSUE TITLE
Composite query error

### ISSUE THREAD

**Issue by o1dnik** [Vincit/objection.js#1931]
> Composite query is a query, where there are multiple columns involved. This isn't one. Queries 2 and 3 are missing `'` marks around the search string. This is a valid query:

> ```js
> .where('baseUrl', 'LIKE', `%${referrer}%`)
> ```

> Your raw queries are also vulnerable to SQL injection attacks. Never ever ever concatenate user input to raw SQL strings.

> _Originally posted by @koskimas in https://github.com/Vincit/objection.js/issues/1928#issuecomment-738132388_

Unfortunately it throws the same error. I don't see this working as you say. Let's try it again. I go to the documentation of `findOne` and `where` and read it through:

> ["Shorthand for where(...whereArgs).first()"](https://vincit.github.io/objection.js/api/query-builder/find-methods.html#findone)

and the query

```
.where("wl.base_url", "LIKE", `%${hostname}%`)
```

throws not found with single-quotes, while the SQL works fine from the psql. I don't get it, where do I make a mistake?

**Comment by o1dnik** [comment]
Here is an example of a correct SQL:

```sql
select "settings".* from "settings" where "settings"."base_url" like '%app.example.com%';
```

which is created by the following query:

```js
.findOne(raw(`"white_label_settings"."base_url" like '%${hostname}%'`))
```

but the SQL works fine and I get the correct result while the query does not match.

**Comment by koskimas** [comment]
Oh my god. You are still concatenating SQL to raw strings. Do not do it.

This code works:

```js
.where('baseUrl', 'LIKE', `%${referrer}%`)
```

There are multiple tests for it.
