### ISSUE TITLE
`$beforeInsert` not triggered during join table insert

### ISSUE THREAD

**Issue by chivalry** [Vincit/objection.js#1933]
I have a base model that is used to contain common elements of my other models. Currently it's very simple:

```
const { Model } = require('objection');
const { v4: uuid } = require('uuid');

class Base extends Model {
    async $beforeInsert(context) {
        await super.$beforeInsert(context);
        this.uuid = uuid();
    }
}

module.exports = Base;
```

I have three other models with one of them representing a join table between the other two. Creating new entities with `Entity.query().inert({})` works perfectly with the above, and the `uuid` field correctly gets populated.

However, if I use `left_entity.$relatedQuery('right_entity').relate(right_entity)`, where `right_entity` contains an instance of one of the other side of the join's object, while I get a correctly related record in the join table, the `uuid` field doesn't get populated even though an `INSERT` is obviously happening in the background.

Is this a bug or is there a different way to accomplish what I'm trying to do?

**Comment by koskimas** [comment]
You need to define the `modelClass` for the `through` object in the relation mapping of the many to many relationship.

**Comment by chivalry** [comment]
I thought I had. Here's how one side looks:

```
class SideA extends Base {
    ...
    static get relationMappings() {
        ...
        join_table: {
            ...
            relation: Model.ManyToManyRelation,
            from: 'side_a.id',
            through: {
                from: 'join.side_a_id',
                to: 'join.side_b_id'
            },
            to: 'side_b.id'
        },
        ....
    }
}
```

`SideB` has the same information but flips the `from` and `to`.

**Comment by koskimas** [comment]
```
I thought I had. Here's how one side looks:

class SideA extends Base {
    ...
    static get relationMappings() {
        ...
        return {
            ...
            join_table: {
                ...
                relation: Model.ManyToManyRelation,
                from: 'side_a.id',
                through: {
                    from: 'join.side_a_id',
                    to: 'join.side_b_id',
                    modelClass: TheRelatedTableModelClasThatsInheritedFromBaseClass
                },
                to: 'side_b.id'
            },
            ....
        }
    };
}
```

**Comment by chivalry** [comment]
Thanks so much for the assist. :)
