### ISSUE TITLE
Mocking Model.query() with .resolve() fails when using insertAndFetch()

### ISSUE THREAD

**Issue by ScottEnock** [Vincit/objection.js#1934]
Objection tries to access DB connection when chaining `insertAndFetch` off of a mocked query using `.resolve()`. This results in the following error: `no database connection available for a query. You need to bind the model class or the query to a knex instance.`

Other methods such as insert work fine when chained off of `.resolve(). `

My assumption is that this issue is caused because the `insertAndFetch` method is responsible for fetching the inserted record as well, however, one would expect this to be handled due to the `resolve` method being used. 

I would guess that a simple solution to solve this issue would be to treat `insertAndFetch` method the same as `insert` when chained to the `resolve` method.  

### Animal Model

```javascript

const { Model } = require("objection");

class Animal extends Model {
	static get tableName() {
		return "Animal";
	}

	static get jsonSchema() {
		return {
			type: "object",
			required: ["name"],

			properties: {
				id: { type: "integer" },
				ownerId: { type: ["integer", "null"] },
				name: { type: "string", minLength: 1, maxLength: 255 },
				species: { type: "string", minLength: 1, maxLength: 255 },
			},
		};
	}
}

module.exports = Animal;


```

### Unit Test
```javascript
const Animal = require("./Animal");
const { QueryBuilder } = require("objection");

describe("dbMethods.createUser", () => {
	const queryMock = jest.spyOn(Animal, "query");

	const animalObj = {
		name: "scott",
	};

	queryMock.mockImplementation(() =>
		QueryBuilder.forClass(Animal).resolve(animalObj)
	);

	it("calls Animal.query()", async () => {
		const result = await Animal.query().insert(animalObj); // THIS WORKS WITHOUT DB CONNECTION
		const result2 = await Animal.query().insertAndFetch(animalObj); // THIS DOES NOT WORK WITHOUT DB CONNECTION
		expect(queryMock).toBeCalled();
	});
});

```

**Comment by koskimas** [comment]
`resolve` is not meant for mocking. There's no guarantee that the knex instance is not accessed. I think you can mock the query builder's `execute` method instead and return whatever you want from there.

**Comment by ScottEnock** [comment]
Sorry for the confusion, however, I arrived at the solution to use `resolve` for mocking from your own suggestion in the issue raised here: https://github.com/Vincit/objection.js/issues/1477#issuecomment-533789575

> You can use the [resolve](https://vincit.github.io/objection.js/api/query-builder/other-methods.html#resolve) method to skip the db query and mock the db result.

Should resolve be used for mocking or not?

**Comment by ScottEnock** [comment]
@koskimas probably busy, however, this inconsistency is still here. Should resolve be used for mocking or not? If not, can you consider updating the linked issue with an appropriate solution?

**Comment by koskimas** [comment]
You can use it for mocking, but it is not designed for mocking. That's why you can have some issues with it. Do whatever you like with it. Why do you need some kind of approval from me?
