### ISSUE TITLE
related query is always returning an array in the TS type

### ISSUE THREAD

**Issue by capaj** [Vincit/objection.js#1935]
I find that I have to do this ugly thing to satisfy Typescript:
```ts
  const scimResourceInDb = ((await group.$relatedQuery<ScimResourceModel>(
    'scimResource'
  )) as any) as ScimResourceModel
```

Is there a better way to type this?

**Comment by koskimas** [comment]
If you add the relation for the model as a property, you get the correct type.

```js
class Group extends Model {
  scimResource?: ScimResourceModel;
}
```

That way you also don't need to explicitly give the type using `<ScimResourceModel>`.
