### ISSUE TITLE
Add support for BigInt ids in typescript typings

### ISSUE THREAD

**Issue by JaspervRijbroek** [Vincit/objection.js#1936]
As BigInt is already supported in nodejs would it be possible to add BigInt support to the Ids?

https://github.com/Vincit/objection.js/blob/bda8e13c90ab00f5a67eab0a3fb050914220308e/typings/objection/index.d.ts#L139

```ts
type Id = string | number | BigInt;
```

**Comment by mikicho** [comment]
@koskimas I think this feature isn't compatible with Knex's `WhereMethod` interface:
![image](https://user-images.githubusercontent.com/11459632/153724391-344c4227-729d-40a8-a3d2-93b58f1f091b.png)
