### ISSUE TITLE
Inherit props for type definition

### ISSUE THREAD

**Issue by AustinGil** [Vincit/objection.js#1937]
I'm using `yup` with a custom validator for my Objection models and would really like my models to inherit properties from the `yup` schema.

Here is what my code looks like, but I'll remove some of the shema props for brevity:

```js
const yup = require('yup');
const { Model } = require('objection');

const schema = AutoVersion.validationSchema.clone().shape({
  baseImageId: yup.number().integer().positive().required(),
  parentId: yup.number().integer().positive().required(),
  // several more fields
});

class ImageInstance extends Model {
  static tableName = 'image_instance';
  static validationSchema = schema;

  /** @type {number} */
  baseImageId;
  /** @type {number} */
  parentId;
  // several more properties
}

ImageInstance.test = 'yolo';

module.exports = ImageInstance;
```

`schema.fields` will return a list of all the properties of that object. What I would like to do is programmatically include those fields as properties in the Model. The only way I can think of doing that is with a `constructor` function, but without calling `new` to instantiate the Model, I can't think of a way.

What I want

```js
const yup = require('yup');
const { Model } = require('objection');

const schema = AutoVersion.validationSchema.clone().shape({
  baseImageId: yup.number().integer().positive().required(),
  parentId: yup.number().integer().positive().required(),
  // several more fields
});

class ImageInstance extends Model {
  static tableName = 'image_instance';
  static validationSchema = schema;

  // inject schema.fields here automatically.
}

ImageInstance.test = 'yolo';

module.exports = ImageInstance;
```

Can anyone help with this? It's not a major issue, but would help to prevent repeating myself, and may reduce errors.

**Comment by koskimas** [comment]
Why do you want to define properties like that? You don't need to do that.

**Comment by AustinGil** [comment]
@koskimas I just updated the original comment to make it more clear. Basically what I would like is to only write the properties in one place. I use yup for validation, so Im going to write those anyway. If the `yup` fields could be automatically be injected as properties into the model then I would only need to write them and maintain them in one place.

I'm using TypeScript in my project, so when I grab an `ImageInstance`, I can see the list of properties it has and the types. These can also be inferred from the `yup` fields. 

I can't really think of any way to accomplish this, but it would be ideal. What I have to do now is repeat every `yup` field as a property in the model, and redefine the property type.

Does that give a better explanation?

**Comment by koskimas** [comment]
You can't inject typescript field types runtime. Typescript is completely compile-time thing.

**Comment by AustinGil** [comment]
Im aware of that. Im not trying to inject the TS props. Im trying to inject the `yup` validation schema props which would bring along their type definitions. `schema.fields` would be runtime properties (such as `baseImageId` and `parentId` above). If those could be injected into the model as properties, then they would bring along their types. In the example above, they would be defined as `number` types.

**Comment by koskimas** [comment]
So you are asking if typescript somehow can understand and parse yup code and generate type information based on that compile time. Nope.

**Comment by AustinGil** [comment]
Actually, it doesn't have to be at compile time. It doesn't even have to relate to Yup. I just want the benefit from the type-checking while I write my code, but I need to be able to define the properties outside of the model class. A simpler example might be:

```
const { Model } = require('objection');

const properties = {
  str: '',
  num: 0,
}

class ImageInstance extends Model {
  static tableName = 'image_instance';

  // inject properties here automatically.
}

module.exports = ImageInstance;
```

So this way when I query `ImageInstance.query()` it will return a list of `ImageInstance` objects and will auto-suggest the `str` or `num` properties with their respective types.

One thing I found that's relevant:

```
const { Model } = require('objection');

const properties = {
  str: '',
  num: 0,
}

class ImageInstance extends Model {
  static tableName = 'image_instance';
}
// This works
ImageInstance.prototype.str = properties.str

for (const prop in properties) {
  // This does not work
  ImageInstance.prototype[prop] = properties[prop]
}

module.exports = ImageInstance;
```

Maybe this has something to do with what you have been saying this whole time. But I don't understand why this would not work
