### ISSUE TITLE
Is it possible to insert asynchronously? (without await)

### ISSUE THREAD

**Issue by dimqakolyada** [Vincit/objection.js#1941]
In documentation I found this example:
`const jennifer = await Person.query().insert({
  firstName: 'Jennifer',
  lastName: 'Lawrence'
});`

it works nicely with `await` statement. But what if I want to insert asynchronously? In my case, It doesn't work without await statement.

**Comment by koskimas** [comment]
You mean synchronously? (await is asynchronous). There's no way to do that. Node is single threaded, so the only way to make it fast is to do all IO asynchronously. That's why most libraries only provide asynchronous API:s.

**Comment by dimqakolyada** [comment]
If I am not mistaken when I use the await statement my program waits until this insert gets completed. But the rest of the code below doesn't depend on this insert and I don't want to wait for this insert.

**Comment by koskimas** [comment]
You can call `execute` to execute the query and then ignore the returned promise.
