### ISSUE TITLE
How return only QueryBuilder without execute?

### ISSUE THREAD

**Issue by vampyar** [Vincit/objection.js#1942]
```typescript
@Injectable()
export class AppointmentNoteRepository extends BaseRepository<AppointmentNote> {
  constructor(
    @Inject('AppointmentNote') private _modelClass: ModelClass<AppointmentNote>,
    private redisService: RedisService
  ) {
  }

  async findAllByAppointmentId(appointmentId: number) {
    const boundModel = await this.getBoundModelClass({appointmentId});

    return this.findAll(boundModel)
      .joinEager('author')
      .andWhere({ appointmentId });
  }
}
```
In this case I'm need QueryBuilder after call `findAllByAppointmentId` how I can do this with if it async ?

```typescript
const appointmentQuery = await this.appointmentNoteRepository.findAllByAppointmentId(10022);
const client = await this.redisService.findNote(userId)
if (client.isNote) {
     appointmentQuery.where({noteId: client.noteId})
}
appointmentQuery.where({answerId})
```

**Comment by elhigu** [comment]
You need to make those `findAll` and `findAllByAppointment`  to not be async functions. If they are async they will always return a promise.

**Comment by vampyar** [comment]
Not I cant remove `async` because I have method  `getBoundModelClass`  it's redis client his always return Promise, and I can't easy solved this problem

**Comment by elhigu** [comment]
Then you need to wrap the resulting query builder to an object { builder: queryBuilderToReturn } to prevent javascript thenable mechanism from working (a bit inconvenient).

Or call that ` this.getBoundModelClass({appointmentId});` elsewhere and pass it in some synchronic way to query building phase.
