### ISSUE TITLE
Best way to do a like query for an object in a nested JSONB array?

### ISSUE THREAD

**Issue by mmartinsky** [Vincit/objection.js#1943]
DB: Postgres
Objection version: 2.1.3
----

SQLFiddle: http://sqlfiddle.com/#!17/8c01f/1

Let's say I have a table `books` like below

```
CREATE TABLE books (  
  book_id serial NOT NULL,
  data jsonb
);
INSERT INTO books VALUES (1, '{"title": "ABC", "genres": [{"name": "Fiction"}, {"name": "Thriller"}]}');  
INSERT INTO books VALUES (2, '{"title": "DEF", "genres": [{"name": "Mystery"}, {"name": "Horror"}]}');  
INSERT INTO books VALUES (3, '{"title": "GHI", "genres": [{"name": "Horror"}, {"name": "Filler"}]}'); 
```

My use case is creating a search component that can do fuzzy matching on the genre - entering `search=ill` should return any results where "ill" appears in the name of any of the genres. In this example, it would return rows 1 and 3 for Thriller and Filler.

In raw SQL, I can do
```
select books.*
from books, jsonb_array_elements(books.data->'genres') as genres
where genres->>'name' ilike '%ill%';
```

Is there a clean way to do this sort of lookup in Objection without having to do the `jsonb_array_elements` extraction? It's not terrible here, since it's a simple table, but with a more complex query (checking other fields in our fuzzy search) it can get hairy fast.

I was looking at [whereJsonSuperSetOf](https://vincit.github.io/objection.js/api/query-builder/find-methods.html#wherejsonsupersetof), but it looks to just do an `@>` query

**Comment by elhigu** [comment]
The query you are doing with raw can be done like this:

```
Books.query()
  .select('*', raw('jsonb_array_elements(??) as genres', [ref('data:genres')])
  .where(ref('genres:name').castText(), 'ilike', '%ill%'); 
```

Though I don't know if that query does what you think it does 🤔 It very well might 👍
