### ISSUE TITLE
Query in from

### ISSUE THREAD

**Issue by ombak** [Vincit/objection.js#1944]
I have query like this:

`select u.id, u.full_name, table1.score  
from (
        select rs.user_id, sum(rs.points) as score 
	from public.classroom_response_student rs 
	join public.program_pathways pp on pp.classroom_id = rs.classroom_id 
	join public.program_users pu on pu.user_id = rs.user_id 
	join public.users u on u.id = pu.user_id 
	where pp.program_id = 1 
	group by rs.user_id 
) table1 
inner join public.users u on u.id = table1.user_id;`

How if I want use objection for query above.

note: I have searched but found no way.

Thanks advance.

**Comment by koskimas** [comment]
You can pass in a query builder for the `from` method.

```js
Person.query()
  .from(Person.query().select('blah').where(bloh))
```
