### ISSUE TITLE
upsertGraph fails to relate when relation uses composite primary key

### ISSUE THREAD

**Issue by lenolib** [Vincit/objection.js#1945]
It seems that upsertGraph ignores relations if the relation uses a composite key. 
Given the models:
```javascript
class IssueSubscriptionSettingsModel extends Model {
  static get idColumn() {
    return ['issue_id', 'user_id'];
  }
  static get tableName() {
    return 'issue_subscriptions';
  }
};

class IssueModel extends Model {
  static get tableName() {
    return 'issues';
  }

  static get relationMappings() {
    return {
      subscription_settings: {
        relation: Model.HasManyRelation,
        modelClass: IssueSubscriptionSettingsModel,
        join: {
          from: 'issues.id',
          to: 'issue_subscriptions.issue_id',
        },
      },
    };
  }
}
```
The following upsertGraph fails to relate `subscription_settings`
```javascript
IssueModel.query().upsertGraph([
    {
      id: 'foo',
      subscription_settings: [
        {
          // issue_id: 'foo', // works if supplied
          user_id: 'bar',
          subscription: true,
        },
      ],
    },
  ], { insertMissing: true, relate: true }
  ).then()
```
Expected result: A row in `issues` table and a related row in the `issue_subscriptions` table
Actual result: No row is inserted in the `issue_subscriptions` table.

We mostly use upsertGraph for setting up test data, so it's not much a problem in practice, but it would be nice if e.g. the query would fail hard instead of silently ignoring part of the input, or we at least could add it to the documentation as an unsupported case.
I feel a little bit bad about creating another upsertGraph corner case issue :sweat_smile:

Other issues that seem related are #1447 or #1419

**Comment by jarommadsen** [comment]
I've just run into this after migrating to v2.2.15.

In my use case I'm uploading a file with tags, permissions, and attachments and relating it to an employee with `employeeFile` which has a composite key of `['fileId', 'userId', 'companyId']`. This is what the code looked like v1 which inserted the employeeFile just fine:

```js
const graph = {
  name: "File Name",
  expiration: null,
  effectiveDate: null,
  employeeFile: { userId: 3593, companyId: 37, showUser: undefined },
  tags: [ { id: 1 } ]
}
await upsert(models.File, graph, context, info, {
    upsertGraphOptions: {
      relate: true,
      unrelate: ['tags', 'permissions', 'attachments']
    }
});
```
  
After the migration, it inserted the file and related the tags, permissions, and attachments but did not insert the employeeFile.

Adding `insertMissing: true` did nothing but changing the relate option to specifically exclude `employeeFile` worked:

```js
await upsert(models.File, graph, context, info, {
    upsertGraphOptions: {
      relate: ['tags', 'permissions', 'attachments'],
      unrelate: ['tags', 'permissions', 'attachments']
    }
  });
```

The documentation has this to say about the relate option:
> By giving relate: true and/or unrelate: true options as the second argument, you can change the behaviour so that instead of inserting and deleting rows, they are related and/or unrelated. Rows with no id still get inserted, but rows that have an id and are not currently related, get related.

I'd expect the behaviour to still be the same then in v2 with regards to inserting rows with incomplete composite keys (in my case, `fileId` is missing.
