### ISSUE TITLE
joinEager with ManyToMany relation failing with error

### ISSUE THREAD

**Issue by MrScX** [Vincit/objection.js#1946]
Objection Version: 1.6.9
Knex Version: 0.19.3

I'm executing the below code to search through a table:
```
                   Army
                        .query()
                        .select(
                            "army.u_id", 
                            "army.name", 
                            "army.email", 
                            "army.contact_no", 
                            "army.status", 
                            "army.gender",
                            "army.created_at"
                        )
                        .joinEager("[insta, paymentInfo, industry, city]")
                        .where("army.name", "like", `%${search_key}%`)
                        .modifyEager("paymentInfo", builder => {
                            builder.orderBy("created_at", "desc");
                        })
                        .orWhere("army.email", "like", `%${search_key}%`)
                        .orWhere("army.contact_no", "like", `%${search_key}%`)
                        .orWhere("insta.username", "like", `%${search_key}%`)
                        .limit(parseInt(query.limit))
                        .offset(parseInt(query.offset))
```

The reason I'm using joinEager instead of plain eager is that I need to add a few filters to the data. Below is the relation I have defined in the Army model:

```
industry: {
                relation: Model.ManyToManyRelation,
                modelClass: Industry,
                filter: builder => builder
                    .select("industries.id", "industries.name", "army_industry.level"),
                join: {
                    from: "army.u_id",
                    through: {
                        from: "army_industry.u_id",
                        to: "army_industry.industry_id"
                    },
                    to: "industries.id"
                }
            }
```

Now the error I'm getting is 

```
"Error: ER_BAD_FIELD_ERROR: Unknown column 'army_industry.level' in 'field list'\n
```
If I remove the  'army_industry.level' from the filter the query works fine. But I need that data to be returned from this query. What am I doing wrong?

**Comment by koskimas** [comment]
The `army_industry` table is given an alias other than `army_industry` by `joinEager`. If the `industries` table doesn't have a column called `level` you can simply drop the table name from the select like this:

```js
                filter: builder => builder
                    .select("industries.id", "industries.name", "level"),
```

**Comment by MrScX** [comment]
> The `army_industry` table is given an alias other than `army_industry` by `joinEager`. If the `industries` table doesn't have a column called `level` you can simply drop the table name from the select like this:
> 
> ```js
>                 filter: builder => builder
>                     .select("industries.id", "industries.name", "level"),
> ```

Hey there, thanks for the response. I tried that before. Dropping the table name. But the same error is thrown.

**Comment by koskimas** [comment]
There's a built in feature those called `extra properties`. You can try using that instead of your own select in a filter

https://vincit.github.io/objection.js/recipes/extra-properties.html#join-table-extra-properties
