### ISSUE TITLE
How to extend QueryBuilder and Model?

### ISSUE THREAD

**Issue by anttilinno** [Vincit/objection.js#195]
I wanted to implement soft delete. I am more or less completely clueless about constructor and super part. Just pasted together some examples, that I could find here in issue tracker. I have a gut feeling, that I have created some abomination 😄  So I created two files in my models directory, BaseModel.js and CustomQueryBuilder.js.

CustomQueryBuilder.js
```
	const QueryBuilder = require('objection').QueryBuilder;

	class CustomQueryBuilder extends QueryBuilder {
	  constructor(modelClass) {
		super(modelClass);

		this.onBuild(builder => {
		  if (!builder.context().withArchived) {
			builder.whereNull('deleted_at');
		  }
		});
	  }

	  withArchived(withArchived) {
		this.context().withArchived = withArchived;
		return this;
	  }

	  softDelete() {
		return this.patch({deleted_at: new Date().toIsoString()});
	  }
	}

	module.exports = CustomQueryBuilder;
```
and BaseModel.js

```
	const Model = require('objection').Model;
	const CustomQueryBuilder = require('./CustomQueryBuilder');

	class BaseModel extends Model {
	  static get Model() {
		return Model;
	  }

	  static get QueryBuilder() {
		return CustomQueryBuilder;
	  }

	  static get RelatedQueryBuilder() {
		return CustomQueryBuilder;
	  }
	}

	module.exports = BaseModel;
```
However, I get
 
```
	function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
																											  ^

	TypeError: Super expression must either be null or a function, not undefined
```

Full code in [repo](https://github.com/anttilinno/todo), in case it helps somehow. And bonus thanks for helping to port to es7 😄

**Comment by koskimas** [comment]
In `Todos.js` you have `import {BaseModel} from './BaseModel';`. It should be `import BaseModel from './BaseModel` instead because you don't use named exports in `BaseModel`.

**Comment by koskimas** [comment]
Also since you are using ES7, you don't need to use getters. You can just say:
```js
    class BaseModel extends Model {
      static QueryBuilder = CustomQueryBuilder;
      static get RelatedQueryBuilder = CustomQueryBuilder;
    }
```

Also why do you have the `static get Model()` getter there? You should never need the Base model constructor except when inheriting from it. All the static and instance properties are inherited to all subclasses.

**Comment by anttilinno** [comment]
I seem to be missing some babel settings or modules. Do you have idea which? 
```
SyntaxError: src/lib/nmodels/BaseModel.js: Unexpected token (6:35)
  4 | class BaseModel extends Model {
  5 |     static QueryBuilder = CustomQueryBuilder;
> 6 |     static get RelatedQueryBuilder = CustomQueryBuilder;
```

Added stage-0, but still same error.

**Comment by koskimas** [comment]
I accidentally left the `get` keyword after `static`. Simply remove it.

**Comment by anttilinno** [comment]
Ok, dropped `get` in `static get RelatedQueryBuilder` and code started to work. Thank you for your assistance. Seems, that I have working softDelete now.
Can I somehow help with the extending query builder example in documentation?

**Comment by koskimas** [comment]
You can extend the documentation by modifying the markdown files in the `docs` directory and creating a pull request of those changes.
