### ISSUE TITLE
nitPICKS and incomplete implementation of model.$pick()

### ISSUE THREAD

**Issue by JaneJeon** [Vincit/objection.js#1952]
First of all, sorry (not sorry), but I had to get that pun in there.

While maintaining my new version of objection-authorize, I came across a small issue that others somehow surprisingly didn't point out before:

The internal implementation of `pick` does NOT support dot notations (due to using `Object.keys()`):
https://github.com/Vincit/objection.js/blob/412bb77b9cf69496e477c38fc10bca679ceca461/lib/model/modelFilter.js#L77

This means that if you have a model with a JSON field, and you'd like to selectively "pick out" a subfield (e.g. `a.b` from a model represented by object `{a: {b: 'foo'}}`, it will not properly recognize that subfield (`Object.keys({a: {b: 'foo'}})` is `a`, after all).

So to properly implement "picking" subfields, you'd either need to re-implement JSON dotpath, or, just use `lodash.omit` and `lodash.pick`. Either way, if you're not going to implement this change, you really should note on the docs that it doesn't support dot notation and nested fields.

As for the nitPICK... in line 84 of that file I noticed that you were just iterating over the `pick` array to check rather than using `Array.prototype.includes()` or better yet, producing a set from that array and checking membership for that sweet, sweet O(1) lookup time.

**Comment by JaneJeon** [comment]
Consider this bug report a belated Christmas gift from me :)

**Comment by JaneJeon** [comment]
Or I suppose you could simply add a remark on the documentation about the current limitations and deprecate it, and just let the users use `lodash/pick`/`lodash/omit` instead. Might be easier that way since the tests aren't even testing nested properties.

**Comment by koskimas** [comment]
Why did you assume `$pick` would work with sub paths and dot notation? There's nothing in the docs that would suggest that and I don't think most people would expect it to work like that just because some other library (lodash) has a method with the same name that does support dot notation.

> As for the nitPICK... 

Much of the code is really old. Back in the day, `array.includes` didn't exist and handwritten for loops were much faster than `array.find`. Nowadays we could replace code like this with `includes/map/filter/find` etc. built-in methods.

**Comment by JaneJeon** [comment]
Well, I “assumed” `$pick` would work with dot notation because otherwise you literally can’t filter out model subfields in case you had a JSON field. It’s quite the limitation, considering that JSON fields are nowadays more commonplace with both JSONB in Postgres and proper JSON support in MySQL... 🤷‍♀️ 

I think it’s a reasonable assumption to have in $current_year, so my advice still remains to deprecate it if it’s not used internally (I hope to god it isn’t) or add proper subfield support if it is. @koskimas

**Comment by koskimas** [comment]
I'll deprecate those methods and remove them in 3.0.

**Comment by JaneJeon** [comment]
@koskimas excellent, thanks for at least acknowledging this!
