### ISSUE TITLE
GraphOptions.joinOperation is incorrectly typed as required

### ISSUE THREAD

**Issue by IlyaSemenov** [Vincit/objection.js#1954]
GraphOptions.joinOperation is typed as required here:

https://github.com/Vincit/objection.js/blob/412bb77b9cf69496e477c38fc10bca679ceca461/typings/objection/index.d.ts#L752-L758

which is not correct because it defaults to `leftJoin`.

In particular, this leads to Typescript error in innocent uses like:

```ts
MyModel.query().withGraphFetched("foo", { maxBatchSize: 1 })
```

result:

```
Argument of type '{ maxBatchSize: number; }' is not assignable to parameter of type 'GraphOptions'.
  Property 'joinOperation' is missing in type '{ maxBatchSize: number; }' but required in type 'GraphOptions'.ts(2345)
```

**Comment by MatiasMinian** [comment]
Isn't also `aliases` incorrectly typed? We are having issues as well having the `joinOperation` as mandatory, but a bigger problem for us is the `aliases` which asks for a `string[]`. Based on the docs, it should be an object right? 
Shouldn't it be: `aliases?: { [key: string]: string }`?

By the way, thanks for this amazing library!

**Comment by ibrahimjamil** [comment]
poor typescript types
