### ISSUE TITLE
Use JSON field in relationMappings join

### ISSUE THREAD

**Issue by ChrisBates** [Vincit/objection.js#1956]
I'm trying to create a `HasOneRelation` from a property in a JSON field on TableA to a field on TableB.

TableA has a `json_field` with a property `Quantity Break Code`. TableB has a normal int field `code`. Note I'm using knex snake case mapper.

My model on TableA looks like:
```
static relationMappings = {
  quantityBreak: {
      relation: Model.HasOneRelation,
      modelClass: TableB,
      join: {
        from: ref('tableA.jsonField:"Quantity Break Code"').castInt(),
        to: 'tableB.code',
      },
  },
}
```

When I try to query this with `await TableA.loadRelated(data, 'quantityBreak')` I get a null result for the relation. No error, just no result.

Oddly I log all queries with `knex.on('query', ...)` and don't see any SQL being executed for this relation either... So I'm thinking I've done something wrong ObjectionJS side, despite not getting an error.

I know this issue has been very generalized, but I couldn't find any example of using JSON fields in relationMappings like this... Hoping this is enough to explain why it isn't working.

**Comment by koskimas** [comment]
Does it work if you drop the `"` around "Quantity Break Code"?

**Comment by ChrisBates** [comment]
@koskimas Hah, that worked. It's always something stupidly simple isn't it? Appreciate your help a lot!
