### ISSUE TITLE
Upsert Graph Fails and All Records Are Unrelated

### ISSUE THREAD

**Issue by mrondin1** [Vincit/objection.js#1958]
When my UpsertGraph fails due to improper parameters passed (values passed with a named field that already existed and should have been passed with "dbRef"), all join records are unrelated.

```
    const options = {
      unrelate: ['allergies']
    }

await ClientPreference.query().upsertGraph(
        {
          user_id: user_id,
          allergies: allergies,
        },
        options,
      )
```

Allergies can either be matched to existing allergy record by name and passed in as dbRef, or, if they don't exist, passed in as a name, for which a new primary allergy record is created. In either case, a new join record including both user and allergies is created in a join table. Users can add and delete allergies as required.

This is what the allergies array might look like. In this example, the allergies record 'peanuts' was passed in error, and should have been matched to a dbRef instead. dbRef was passed in correctly for a different, existing record. 

```
[{ '#dbRef': 13 }, { allergies: 'peanuts' }]
```

UpsertGraph has been a good solution for me, as I'm able to add new relations, insert new records in the allergy tables, and unrelate old relations that the user removed, all in one call. It works perfectly for my use case when it comes to properly passed data.

Now, if UpsertGraph fails due to passing an existing record by name instead of dbRef, I get the expected database error that there is a unique constraint in the allergies table: 

```
'insert into "allergies" ("created_at", "name") values ($1, $2) returning "id" - duplicate key value violates unique constraint "allergies_name_unique"' }
```

The solution to the immediate problem is to correctly validate existing records to get dbRefs and not pass duplicate names for entry. Easy enough.

My question is about what happens to the rest of the user-allergy join records after this error. When the UpsertGraph fails, the rest of the join records for this user are unrelated. Is the expected behavior for a failed upsertGraph that the rest of the query executes as if I passed an empty list for allergies? The behavior I expected is that nothing would execute from this call at all, so no records would change. However, if I have existing allergy records for a user, and I make an UpsertGraph call that fails, now all my join records for that user and allergies are gone. It's as if I passed in an empty list (like the user was trying to delete all their records).

Appreciate any insight into if I'm handling this incorrectly or if this expected behavior. Thanks!

**Comment by koskimas** [comment]
Don't use upsertGraph.

**Comment by mrondin1** [comment]
Because of the use case or don't use it at all?

**Comment by ps2goat** [comment]
You could write a function or procedure for this functionality and more easily control what it does. I've only used `upsertGraph` for minor things, but I could see how this use case could create some unpredictability and potential breakage down the road.
