### ISSUE TITLE
Get old data from static afterUpdate hook

### ISSUE THREAD

**Issue by mrjdavidfg** [Vincit/objection.js#1961]
Is there any way to get the old data (previouss updating) from [static `afterUpdate` hook](https://vincit.github.io/objection.js/api/model/static-methods.html#static-afterupdate)? 

```
static async afterUpdate({items, asFindQuery, ...rest}) {
  // I want to have old data here
}
```
I noticed that when I'm calling an update query from and instance model, the `items` property from the `StaticHookArguments` correctly does return the data being modified, but it doesn't work for Model queries.

```
person.$query().patch({ lastName: 'Aniston' }) // 'items' with data
PersonModel.query().findById(1).patch({ lastName: 'Aniston' }) // 'items' with empty data
```

I tried with the `asFindQuery`, but it returns the data already updated, which its kinda obvious for the [property description](https://vincit.github.io/objection.js/guide/hooks.html#static-query-hooks) and the "after" update hook.

The thing is, I wish I could have that old data in the hook from calls from the model and instances. My current workaround its to use the static `beforeUpdate` hook and use the `asFindQuery`.

**Comment by koskimas** [comment]
There's no other way to get the old data but using `asFindQuery` in the before hook.
