### ISSUE TITLE
withGraphFetched didn't return staticHook afterFind result

### ISSUE THREAD

**Issue by jcyh0120** [Vincit/objection.js#1963]
When using withGraphFetched in the [example repo koa](https://github.com/Vincit/objection.js/tree/master/examples/koa), I try to fetch a person withGraphFetched his pet.
But the result didn't return afterFind in in Pet.

Here's my static afterFind hook method modify from this [koa example Animal model file](https://github.com/Vincit/objection.js/blob/master/examples/koa/models/Animal.js).

```javascript
static async afterFind({result}){
    console.log("HelloWorld")
    return {...result, hello:"world"}
  }
```

I couldn't get the hello property in Person relation Pet, but it did print the HelloWorld string.

**Comment by koskimas** [comment]
`result` is an array. What happens if you do this:

```js
result[0].hello = 'world';
```

or

```js
return { ...result[0], hello: 'world' }
```

**Comment by jcyh0120** [comment]
@koskimas it works!! Thanks a lot!!!

**Comment by jcyh0120** [comment]
I found that it won't work if I make a new array like:
```
return result.map((item) => ({ ...item, hello: "world" }))
```
I had to directly mutate the object to get it work.
