### ISSUE TITLE
merge() doesn't seem to use model hooks

### ISSUE THREAD

**Issue by willsoto** [Vincit/objection.js#1964]
Thanks for adding `onConflict()`, it's a great addition. 

One thing I noticed was that `merge()` doesn't seem to "process" the object in the same way `insert`, `patch`, etc do. As a simple example, `columnNameMappers` - like `snakeCaseMappers` - don't seem to be getting applied. Same for things like `$parseJson` as far as I can tell. Since `merge` can accept an optional record to update in the case of a conflict, I'd expect that record to be processed using the same hooks as `insert`, `patch`, etc

**Comment by koskimas** [comment]
Objection cannot know if the query ended up being an update instead of insert.

**Comment by willsoto** [comment]
@koskimas Ok that is fine for the `$beforeInsert`, `$beforeUpdate` hooks, but why should that matter for something like `columnNameMappers `?

**Comment by koskimas** [comment]
Oh crap, sorry. I only read the title and just assumed what you meant 😬 

You are absolutely right. The data passed into `merge` should be treated just like the data passed in to `patch`.
