### ISSUE TITLE
jsonSchema { default: [] } for array properties resulting in Postgres errors

### ISSUE THREAD

**Issue by TimNZ** [Vincit/objection.js#1967]
This was discussed in https://github.com/Vincit/objection.js/issues/1715 but not resolved.

Is {default:[] } for arrays meant to work in jsonSchema, because it is generating SQL that Postgres doesn't like for an array column:

partial class:
```
class Connection extends Model
{
   static get tableName() { return 'connection' }
   static get jsonSchema() {
     return {
         type: 'object', 
         properties: {
           tags: {type: array, default: [], items: { type: 'string' } }
      }
   }
}
```

```
models.Connection.query().insert({type: 'admin', from: 1, to: 2}) // no 'tags' specified so default from jsonSchema used
```

```
{
  method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, '[]', 2, 'admin' ],
  __knexQueryUid: 's4jcp_JbCzeoijJ00UXI-',
  sql: 'insert into "connection" ("from", "tags", "to", "type") values (?, ?, ?, ?) returning "id"',
  returning: 'id'
}
```

Error:
```
DataError: insert into "connection" ("from", "tags", "to", "type") values ($1, $2, $3, $4) returning "id" - malformed array literal: "[]"
```
I can't see a clean way of hooking into the model static or instance method hooks as by the the time you get to $beforeInsert and check for null and set a value on the column, you must have already used val() to cast a javascript array to a ValueBuilder instance, and the bindings have already been defined.
You can see the $$queryProps is set on the model instance passed into $beforeInsert in the below screenshot, and the 'tags' property is still an empty array.

Using val() ValueBuilder helper in the original insert(), you can see individual bindings for each item in the array:

```
models.Connection.query().insert({name: 'Test event',status: 'planning',tags: val(['tag1','tag2']).asArray()})
```

```
{
  method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '{}', 'Test event', 'planning', 'tag1', 'tag2' ],
  __knexQueryUid: 'dJFQtmHDPSH1JGyjNyxuZ',
  sql: 'insert into "connection" ("data", "name", "status", "tags") values (?, ?, ?, ARRAY[?, ?]) returning *',
  returning: [ '*' ]
}
```

I can use knex.defaultTo to set a default in PG, but what to confirm that this is as designed, or a bug in Objection or Knex.

```
columnBuilder.defaultTo('{}')
```
![image](https://user-images.githubusercontent.com/1051701/104085599-affbb900-52b5-11eb-91ef-eb6ee6a99155.png)

**Comment by koskimas** [comment]
The array default works if the column type is `json` `jsonb` or some sort of a string. Objection doesn't know the real column type, so it can't set a different default when the column has an array type. This should be implemented in the database driver level. In this case the `pg` library.
