### ISSUE TITLE
Model instantiation hook with info from relation instance

### ISSUE THREAD

**Issue by briancray** [Vincit/objection.js#1971]
Below is a contrived example of what i'm trying to do. I need properties of the parent during instantiation to do conditional instantiation. In this case Parent as a HasManyRelation to Child called children.
```
class Parent extends Model {
}
class Child extends Model {
    static fromDatabaseRow(row) {
        if (row.parent.foo === 'bar') {
            // return a model instance with additional properties
        }
       // return child model instance
    }
}

Person.query().fetchGraph('children')
```
Any ideas how I might achieve this?

**Comment by koskimas** [comment]
There's no way to do that unfortunately.
