### ISSUE TITLE
Update JSONSchema generics in types definition

### ISSUE THREAD

**Issue by waveiron** [Vincit/objection.js#1973]
If we let JSONSchema knows how our models are structured, we can easily modify model props and methods in typescript contaxt, without "manually" maintain each property names in different places, which is tedious and error-prone.

Currently we have:

```typescript
// typings/objection/index.d.ts
export interface JSONSchema {
    $id?: string;
    $ref?: string;
    // ...
}
```

Ajv definition:

```typescript
// dist/core.d.ts with 
//                         ↓ this 
export type JSONSchemaType<T, _partial extends boolean = false> = {
    // lots of thing...
}
```

https://github.com/ajv-validator/ajv/blob/ca2ae61c489f45fa2ec3ff2ee78b10136cb1ed3c/lib/types/json-schema.ts#L10

**Comment by waveiron** [comment]
I notice that ajv has it's own type definition now:

https://github.com/ajv-validator/ajv/blob/ca2ae61c489f45fa2ec3ff2ee78b10136cb1ed3c/lib/types/json-schema.ts#L10

**Comment by koskimas** [comment]
Nice idea, but not worth the bugs, maintenance and corner cases the implementation would bring. Not to mention that this would be a breaking change.

**Comment by Sleepful** [comment]
How about updating `ajv` dependency to `7.0.3`?
It comes with `JSONSchemaType`, then ppl can use it as they see fit.
