### ISSUE TITLE
Clarify $relatedQuery documentation regarding relatedFindQueryMutates

### ISSUE THREAD

**Issue by CassandraNewell** [Vincit/objection.js#1977]
The documentation suggests that the default behavior is to mutate the owner model, when [the opposite is true in v2](https://vincit.github.io/objection.js/api/model/static-properties.html#static-relatedfindquerymutates). 

Examples ([here](https://vincit.github.io/objection.js/api/model/instance-methods.html#relatedquery)):

> Use this to build a query that only affects the items related to an instance through a relation. By default, any fetched or inserted items are also stored to the owner model’s property named after the relation. See relatedFindQueryMutates or relatedInsertQueryMutates to change this behaviour.

> Fetch all items related to an item through a relation. The fetched items are also stored to the owner item's property named after the relation (by default):

```
const pets = await jennifer.$relatedQuery('pets');

console.log('jennifer has', pets.length, 'pets');
console.log(jennifer.pets === pets); // --> true
```

**Comment by koskimas** [comment]
Yep the documentation is outdated. Thanks for bringing this up. I'll fix the docs.
