### ISSUE TITLE
Wrong data retrieved when using objection.js with Electron renderer process

### ISSUE THREAD

**Issue by jetacpp** [Vincit/objection.js#1978]
Hello,
I am using objection.js with sqlite3 database. First of all, the problem that I experienced only happened with joined database/table, I did not see problems with independent tables. The issue that narrowed down had to do with the Electron and its main/renderer process. If I run the code with NodeJS (same as main process) then the issue did not happen at all.

I put together a demo (https://github.com/jetacpp/demo-objection) that reproduced the issue. It is very simple Electron Vuejs project. Here, I have `background.js` which runs the main process, and `App.vue` which runs in renderer process. Because of that and I instantiate knex instance in `background.js` so it creates `demo.db` file locally. I then globalize that instance so renderer process can reach it and initialize Model. The function `demo` is the same in both `background.js` and `App.vue`
```
async function demo() {
  Model.knex(knex);

  await Person.query().insert({id: 1, firstName: 'peter', lastName: 'chao'})
  await Movie.query().insert({id: 2, name: 'epic'})

  const peter = await Person.query().findById(1)
  await peter.$relatedQuery('movies').relate(2).then(n => console.log('peter -> epic', n))
  await Person.query().findById(1).withGraphFetched('movies').then( p => console.log(p))

  await Movie.query().insert({id: 3, name: 'titan'})
  await Person.query().findById(1).withGraphFetched('movies').then( p => console.log(p))

}
```

Test 1:
uncomment `demo()` in `background.js` and comment out `demo() in `App.vue`
Here is the output (the expected correct output):
```
peter -> epic 1
Person {
  id: 1,
  parentId: null,
  firstName: 'peter',
  lastName: 'chao',
  age: null,
  address: null,
  movies: [ Movie { id: 2, name: 'epic' } ]
}
Person {
  id: 1,
  parentId: null,
  firstName: 'peter',
  lastName: 'chao',
  age: null,
  address: null,
  movies: [ Movie { id: 2, name: 'epic' } ]
}
```

Test 2:
comment out `demo()` in `background.js` and uncomment `demo() in `App.vue`
Here is the output:

![image](https://user-images.githubusercontent.com/31259584/105283596-a865cb00-5b65-11eb-95a6-6b38606bb92f.png)

As you can see, Person 'peter' has 2 movies joined with. He should only have one ! As a matter of fact, any movies created will join with 'peter'.
Although I am not 100% sure, but I believe this is the issue with `objection.js` and not with `knex`. The reason is I looked at the content of `demo.db` file created in each demo, they were fine in each tests. This led me believe that somehow `objection.js` interpret the data wrong in this particular setup.

**Comment by jetacpp** [comment]
I added `debug()` statement, and I think I found the issue, objection.js appeared to issue different SQL statement for each 2 cases:

Incorrect / renderer process
```
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '6zr01WJ0vqlcA4SWatM0O',
  sql: 'select `persons`.* from `persons` where `persons`.`id` = ?'
}
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '2te_cmd-EvRlId3J9e_ai',
  sql: 'select `movies`.*, `persons_movies`.`personId` as `objectiontmpjoin0` from `movies` inner join `persons_movies` where `persons_movies`.`personId` in (?)'
}
```

Correct, main process
```
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '5PJZXEv8pi7XcAcxib1YV',
  sql: 'select `persons`.* from `persons` where `persons`.`id` = ?'
}
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '7LZO-VxN4OcAJW4JrITwg',
  sql: 'select `movies`.*, `persons_movies`.`personId` as `objectiontmpjoin0` from `movies` inner join `persons_movies` on `movies`.`id` = `persons_movies`.`movieId` where `persons_movies`.`personId` in (?)'
}

```

**Comment by koskimas** [comment]
The same code is executed in all environments. Objection doesn't know about electron in any way. I don't think this bug is in objection.
