### ISSUE TITLE
Access new values in $afterUpdate

### ISSUE THREAD

**Issue by ctavan** [Vincit/objection.js#1979]
Issue #828 was closed but I believe it is still valid.

* When running an `insert()` with `.returning('*')` on postgres, the `$afterInsert` hook contains all fields of the model record in `this`.
* When running a `patch()` with `.returning('*')` on postgres, the `$afterUpdate` hook contains only the data that was passed for the update.

This is pretty unexpected as it doesn't allow to run the same code in the `$afterInsert` and `$afterUpdate` hooks.

I think the reason is that there is special treatment of the `returning` values in https://github.com/Vincit/objection.js/blob/5b6c8afe07ac5a297daa0d789dd72586e6c96d8d/lib/queryBuilder/operations/InsertOperation.js#L54-L60

which is lacking https://github.com/Vincit/objection.js/blob/master/lib/queryBuilder/operations/UpdateOperation.js

**Comment by koskimas** [comment]
Yeah, I think we could fix that. But instead I'd take a look at the static `afterUpdate` hook. The result passed to that method should already contain all the properties.

**Comment by ctavan** [comment]
Thanks for the hint @koskimas. Using the static hooks instead worked well for me. My hook setup is now much more consistent. I'll leave it up to you to close this or keep it open, I for my part no longer need this feature.
