### ISSUE TITLE
where clause on relation

### ISSUE THREAD

**Issue by s8v** [Vincit/objection.js#1980]
I have a relationship like this https://prnt.sc/xdh5xi and I need to select rows based on movies.name. How should I do?

**Comment by koskimas** [comment]
There are couple of ways at least:

```js
await Person.query()
  .distinctOn('persons.id')
  .joinRelated('movies')
  .where('movies.name', name)
```

`distinctOn` only works on postgres though. Here's another way using a subquery:

```js
await Person.query()
  .whereExists(Person.relatedQuery('movies').where('name', name))
```

Note that these are both just SQL wrapped in a nice package. That's what objection is. A query builder with a bunch of helpers that simplify the code.

When you have a problem like this, first find out how you would do this with raw SQL and then simply translate that to objection code. You can then gradually refactor the code and start using objection specific helpers like `joinRelated` and `relatedQuery` when you lear about them.

You can always add `.debug()` to any query and objection will print the generated SQL.
