### ISSUE TITLE
Missing skipLocked, an oversight or is implementation blocked?

### ISSUE THREAD

**Issue by miwnwski** [Vincit/objection.js#1982]
Hi,

Unintuitively `skipLocked` is a missing property not delegated to knex.QueryBuilder. I was wondering if this is an oversight or there's something blocking integrating it? I skimmed through the code (just quickly at glance) and to me it looks like it could be a normal KnexOperation in queryBuilder/QueryBuilderBase.js just like e.g. `forUpdate`?

By the way, `skipLocked` [exists in knex](http://knexjs.org/#Builder-skipLocked)

Ps. sorry if this has been raised previously but I see no issue (open or closed) when I search for it and no mention of it in code either. If an oversight, I can maybe try PR if requested.

**Comment by koskimas** [comment]
Just an oversight. Let's add it.

**Comment by miwnwski** [comment]
Thank you! I though you wanted me to PR and got to the computer to do it only to see it being closed, hah, you're too fast
