### ISSUE TITLE
QUESTION: Can I make a subquery for a nested array

### ISSUE THREAD

**Issue by AustinGil** [Vincit/objection.js#1985]
This is more of a question than an issue. Is there a way to write a query that returns a nested array for a related item? For example, if I have Persons and Pets the result might be:

```js
[
  {
    name: 'Sam',
    pets: [
      { name: 'Nugget' },
      { name: 'Fluffy' },
    ],
  },
];
```

I know in Postgres I can use `array_to_json(array_agg(row_to_json(data)))` for something like this:

```sql
SELECT
  person.name,
  ( SELECT array_to_json(array_agg(row_to_json(pet)))
    FROM (
      SELECT
        name
      FROM
        pet
      WHERE
        pet.owner = person.id
    ) AS pet
  ) AS pets
FROM
  person
```

I've tried a `relatedQuery()` that selects everything, but I get the error: "subquery must return only one column"

**Comment by koskimas** [comment]
Objection is a query builder so anything is possible. That exact query can be built like this:

```js
const fromSubQuery = Pet.query()
  .select('name')
  .where('pet.owner', ref('person.id'))
  .as('pet')

const petsSubQuery = Pet.query()
  .from(fromSubQuery)
  .select(raw('array_to_json(array_agg(row_to_json(pet)))'))
  .as('pets')

const result = await Person.query().select('person.name', petsSubQuery)
```

But there's a much easier ways to get the same result:

```js
const result = await Person.query().withGraphFetched('pets')
```

or

```js
const result = await Person.query().withGraphJoined('pets')
```

You can find information about the differences between `withGraphFetched`  and `withGraphJoined` in the docs.

**Comment by AustinGil** [comment]
Ok. I figured there was a way. I even tried using `withGraphedFetch`, but I must have done something wrong. I'll give that another go. 

Thanks!

**Comment by koskimas** [comment]
The documentation and the examples are quite useful. I suggest you take a look at them. `withGraphFetched` should be familiar to you if you even glanced at the documentation 😉

**Comment by AustinGil** [comment]
Thanks. I actually did look through the documentation quite thoroughly. I tried an approach with all these before posting:
https://vincit.github.io/objection.js/recipes/subqueries.html
https://vincit.github.io/objection.js/recipes/relation-subqueries.html
https://vincit.github.io/objection.js/api/query-builder/eager-methods.html#withgraphfetched
https://vincit.github.io/objection.js/api/query-builder/eager-methods.html#withgraphjoined

Your example above worked well. I was missing the `ref` in my implementation. So I'll have to give the withGraphedJoin another try.
