### ISSUE TITLE
Code breaking change in 2.2.10 - modelClass is now required on ValidationError arguments

### ISSUE THREAD

**Issue by dryu** [Vincit/objection.js#1986]
So, just to give you a bit of an update, I'm using a Typescript, and my code was like this :

```js
new objection.ValidationError({
    message: "...",
    type: "...",
    data: {...}
});
```

This is how it is mentioned in the documentation for the custom validation by the way.

Before 2.2.10 everything was fine, but now `ValidationError` requires a `modelClass` argument and without it Typescript compilation fails with the error about a missing required param.

I had to add this param to make builds work.

The new code may work with a pure JS, but it is Typescript compilation that is a problem, because the arguments for `ValidationError` now includes ` & {modelClass: ModelClass<Model>}` which wasn't there before.

It is unexpected to encounter a code breaking change in the patch release, since most of us has the dependency specified as something like this: `"objection": "^2.2.3",` which will install the latest patch version by default.

_Originally posted by @dryu in https://github.com/Vincit/objection.js/issues/1891#issuecomment-769696636_

**Comment by koskimas** [comment]
So sorry the free tool I wrote for you inconvenienced you so much. My deepest apologies. I undestand why you are so angry, after all, you are totally entitled to all the free work from me. I will fix this as soon as I possibly can.
