### ISSUE TITLE
setRelated and appendRelated return undefined

### ISSUE THREAD

**Issue by leontastic** [Vincit/objection.js#1987]
The documentation claims `Model.setRelated` and `Model.appendRelated` return the input `model` for chaining purposes:

 - [Model.setRelated](https://github.com/Vincit/objection.js/blob/master/doc/api/model/instance-methods.md#setrelated)
 - [Model.appendRelated](https://github.com/Vincit/objection.js/blob/master/doc/api/model/instance-methods.md#appendrelated)

I found that these functions return `undefined` instead of `model` as the documentation says they should. Opening up the source code it looks like these functions are incorrectly returning `this` (which is undefined in the scope of the function) instead of `model`.

The offending lines:

 - https://github.com/Vincit/objection.js/blame/master/lib/model/modelSet.js#L98
 - https://github.com/Vincit/objection.js/blame/master/lib/model/modelSet.js#L114

It looks like changing these lines to `return model` should fix the issue.

**Comment by leontastic** [comment]
@koskimas Also, just wanted to say this library is really incredible. Makes my code beautiful 🌈

**Comment by leontastic** [comment]
Quick fix PR: #1988

**Comment by koskimas** [comment]
Thanks for the fix. I've merged it and 2.2.14 version will be released as soon as the CI is done.
