### ISSUE TITLE
Typescript: issue with deleteById / returning

### ISSUE THREAD

**Issue by pdemarino** [Vincit/objection.js#1991]
Hi all -

I believe I may have found an issue with the typing of deleteById.

Repro:

```ts
import Objection from "objection";

class MinimalModel extends Objection.Model {
  static get tableName() {
    return "someTableName";
  }

  id!: string;
}

export async function deleter() {
    const resultOne = await MinimalModel.query().deleteById("Hello");   // Typed as number
    const resultTwo = await MinimalModel.query().deleteById("Hello").returning("*"); // Typed as MinimalModel[] instead of MinimalModel
}
```

The actual value of `resultTwo` (checked with the PostGres driver) appears to be `MinimalModel[]`.

Using Typescript 4.1.3 and objection 2.2.10.

**Comment by koskimas** [comment]
Move `returning` before `deleteById` or chain `first` as the last method. There's no reasonable way to fix the typings. Feel free to try.
