### ISSUE TITLE
[feature request] ajv 7

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#1993]
Really impressive work in that release. I look forward to use it with objection ;)

**Comment by koskimas** [comment]
I tried to update but ran into a bunch of failing tests. Will need to look into this with more time.

**Comment by waveiron** [comment]
How can I use [ajv-keywords](https://www.npmjs.com/package/ajv-keywords) in current version of objection.js?

**Comment by rstrand** [comment]
Ajv version 8 is out now
