### ISSUE TITLE
Argument of type 'string' is not assignable to parameter of type 'OrderByDirection'.

### ISSUE THREAD

**Issue by AustinGil** [Vincit/objection.js#1996]
I'm using `yup` as a validator and part of my validation logic is to ensure a string is either "asc" or "desc" for the orderby clause on my database query. Yup has typescript support and with it's validation schema, it returns a type of "string", but when I pass the returned value to Objection as the second parameter in an `orberBy` clause, I get a TypeScript error: 

`Argument of type 'string' is not assignable to parameter of type 'OrderByDirection'.`

In understand why TypeScript is complaining that "string" is not the same as "OrderByDirection", but why not accept the type of "string"? Knex will accept any string and ignore anything that is not 'asc' or 'desc'.

For the time being, I can just `ts-ignore` the line.

**Comment by koskimas** [comment]
It's better API to only accept values that work. Silently failing is not a good idea. If you know the string is either asc or desc you can simply cast the string to type `'asc' | 'desc'`
