### ISSUE TITLE
Bug hitting DB connection max when using withGraphJoined()

### ISSUE THREAD

**Issue by markdoliner** [Vincit/objection.js#1997]
Hi! I believe I've found a bug where hitting the DB pool max connection limit and getting a legitimate `KnexTimeoutError` causes future queries to get `KnexTimeoutError` even when there are available connections in the pool. The latter, illegitimate KnexTimeoutError happens _immediately_ when the query is made rather than after the timeout interval configured in the pool, which I think is telling that this is a bug somewhere.

It seems to happen in a very specific situation:
- Querying with `withGraphJoined()`.
- Enough simultaneous queries to hit the DB pool max connection limit and have some queries time out while waiting for an available connection.
- Hitting the connection limit happens on the first query to the table, or something (I go into a little more detail about this in my comment in the repro case linked to below).

Here's my repro case: https://github.com/markdoliner/objection.js/blob/Repro_case_for_incorrect_timeout_bug/reproduction-template.js

I hoped to be able to track this down further but I don't think I'll be able to spend much time on it in the near future. My hunch is that there's somewhere in Objection where a promise from the first timed out query does not have appropriate error handling and is bleeding over into the subsequent query. But I could be wrong! Don't let me prevent you from exploring other possibilities.

**Comment by koskimas** [comment]
This is all handled by knex. Cannot be fixed in objection.

**Comment by markdoliner** [comment]
@koskimas Are you sure? It looks like Objection caches a promise as the table metadata [here](https://github.com/Vincit/objection.js/blob/98a2f7cbcea864199eb5a7affb6b31f5699b303b/lib/model/modelTableMetadata.js#L57). If that promise rejects due to no available connections in the DB pool, is there anything that would unset `modelClass[TABLE_METADATA]` and retry?

**Comment by elhigu** [comment]
You can probably prevent that problem by running the query in transaction. Though I suppose objection could limit maximum concurrency while executing .withGraphJoined.

**Comment by kibertoad** [comment]
@elhigu Limiting concurrency definitely sounds like the right thing to do.

**Comment by markdoliner** [comment]
> You can probably prevent that problem by running the query in transaction.

Yes, thank you. In my repro case I'm intentionally not using a transaction to simulate connection timeout. But you can imagine this happening in other scenarios where no connections are available (like an overloaded DB server paired with short DB pool timeouts).

But the bigger problem I'm trying to highlight is that when the metadata lookup fails, Objection caches the rejected promises and continues to use it. So future queries continue to reject even though there are available connections in the pool.

I keep looking at this and it really seems like an Objection bug to me, but if you think a change should be made to Knex could you share a little more info about what you think should be changed? I don't have a good enough understanding of what could be wrong to be able to file a useful issue there.

I've been looking at modelTableMetadata.js more. [This change](https://github.com/Vincit/objection.js/commit/f586b183627cf4c72eac632735dee09d35a49eca?branch=f586b183627cf4c72eac632735dee09d35a49eca&diff=split) is enough to prevent the problem from happening (with some downsides mentioned in the commit message). [This change](https://github.com/Vincit/objection.js/commit/7cce5c170e320fe68fce4f232819ca9b44fb6dff?branch=7cce5c170e320fe68fce4f232819ca9b44fb6dff&diff=split) is an arguably better fix, however there's still a change required in RelationJoiner.js and I'm not sure of the right way to make that change (see the commit message and TODO for details).

**Comment by koskimas** [comment]
`mapPromise` is not a problem since the all the code inside `fetchColumnInfo` gets executed even if other parallel calls fail. There is no mechanism to "cancel" running promise chains and since `mapPromise` gets a list of promises returned by `fetchColumnInfo`, we're fine.

**Comment by strmer15** [comment]
Thanks for the explanation!

**Comment by markdoliner** [comment]
> mapPromise is not a problem

Ah yeah, ok, I think you're right. I think I got lost in a web of promises when I was thinking about this before.

Thanks for taking care of this, @koskimas!
