### ISSUE TITLE
Case conversion for model properties with returning('*')

### ISSUE THREAD

**Issue by kolpav** [Vincit/objection.js#200]
Hello,

This is my base model
```
import { Model, QueryBuilder } from 'objection'
import _ from 'lodash'

class SoftDeleteQueryBuilder extends QueryBuilder {
  constructor (modelClass) {
    super(modelClass)

    this.onBuild(builder => {
      if (!builder.context().withArchived) {
        builder.whereNull('deleted_at')
      }
    })
  }

  withArchived () {
    this.context().withArchived = true
    return this
  }

  softDelete () {
    return this.patch({ deleted_at: new Date().toISOString() })
  }

  unDelete () {
    return this.patch({ deleted_at: null })
  }
}

Model.QueryBuilder = SoftDeleteQueryBuilder
Model.RelatedQueryBuilder = SoftDeleteQueryBuilder

class ModelBase extends Model {
  $beforeUpdate () {
    this.updated_at = new Date().toISOString()
  }
  $beforeInsert () {
    this.created_at = new Date().toISOString()
  }
  $formatDatabaseJson (json) {
    json = super.$formatDatabaseJson(json)
    return _.mapKeys(json, (value, key) => _.snakeCase(key))
  }
  $parseDatabaseJson (json) {
    json = _.mapKeys(json, (value, key) => _.camelCase(key))
    return super.$parseDatabaseJson(json)
  }
}

export default ModelBase
```

I am using this #22 approach to convert camelCase <-> snake_case it works great but when I use `returning('*')` after `insert` I get model with both cases like
```
{
  createdAt: null,
  created_at: null
}
```
Otherwise it seems to work fine. Is it a bug or I am doing something wrong?

**Comment by koskimas** [comment]
You should use the camelCased property names in beforeInsert and beforeUpdated. They are ran before the case conversions.

**Comment by kolpav** [comment]
@koskimas Thanks for quick reply that solved my problem. Also I haven't touched the code in a while and I tough I should use db names for inserts and camelCased for queries when it is exactly the opposite :smile: . Is there any chance that we could use one unified case for both inserts and queries in the future?

**Comment by koskimas** [comment]
It would be possible to change the inserts and updates to take their inputs in database format, but that would be inconsistent in cases like this:

```js
const person = await Person.query().findById(1);
person.firstName = 'Updated';
await Person.query().update(person);
```

The queries need to be written using database case because knex (the underlying query builder) has no mechanism for mapping the identifiers from case to another. Have you considered simply leaving out the case conversion and using either case?
