### ISSUE TITLE
How to use the IN operator on an attribute of a JSONB column?

### ISSUE THREAD

**Issue by madarche** [Vincit/objection.js#2002]
Hello,

First many thanks for this great library 🙇‍‍♂️

Please, with PostgreSQL 11 and Objection.js latest version as of this writing (`2.2.14`), how to perform a query with the `IN` operator on an attribute value of a JSONB column, like the following SQL query does?

```sql
SELECT * FROM users WHERE metadata->>'countries' IN ('Chad', 'Japan');
```

I've tried to use the following code with no success:
```javascript
const countries = ['Chad', 'Japan'];
const query = SomeModel.query().whereIn(ref('metadata:country'), countries);
```

As this produces the following error:
```
DataError: select "some_model".* from "some_model" where "metadata"#>'{country}' in ($1, $2) - invalid input syntax for type json
```

I couldn't find the `->>` jsonb operator in the source code of Objection.js.

What would be the best/cleanest way to achieve this? With a raw query? But if so, would it still be possible to use `ref` in this raw query?

Thank you!

PS: The use of the IN operator for JSONB fields is for example described in this document:
https://medium.com/hackernoon/how-to-query-jsonb-beginner-sheet-cheat-4da3aa5082a3

**Comment by madarche** [comment]
I forgot to say that, before asking, I've done many tests, many searches on the web and reading of the source code with no success 😟

**Comment by elhigu** [comment]
Try:

```
const query = SomeModel.query().whereIn(ref('metadata:country').castText(), countries);
```

**Comment by madarche** [comment]
That works great! Thanks a lot @elhigu! Kiitos!
