### ISSUE TITLE
Error running insertGraph

### ISSUE THREAD

**Issue by rage28** [Vincit/objection.js#2011]
While trying to run the koa [example](https://github.com/Vincit/objection.js/tree/master/examples/koa) I'm facing the following error:

```
knex:query BEGIN; trx1 +0ms
knex:query insert into "persons" ("age", "children", "firstName", "lastName", "movies", "parent", "pets") values (?, ?, ?, ?, ?, ?, ?) returning "id" trx1 +2m
knex:query ROLLBACK trx1 +17ms

DBError: insert into "persons" ("age", "children", "firstName", "lastName", "movies", "parent", "pets") values ($1, $2, $3, $4, $5, $6, $7) returning "id" - column "children" of relation "persons" does not exist
```

Trying to run this on node 14.15.5 version, objection (2.2.14) and knex (0.21.18)

**Comment by rage28** [comment]
I've created a smaller test project [here](https://github.com/rage28/graph-action) which throws the same error.

**Comment by koskimas** [comment]
If you follow the README.md of the example project, there's no errors.

**Comment by koskimas** [comment]
Ok, so in your test project you've done all sorts of modifications. First of all, the `relationMappings` cannot be an async function. It will not work. Second, you've caused circular dependencies by removing the `require` statements from the `relationMappings` method/getter.
