### ISSUE TITLE
raw is not allowed within modifyGraph in a withGraphJoined

### ISSUE THREAD

**Issue by diegotorre5** [Vincit/objection.js#2013]
Hello, 
I am experiencing difficulty adding a raw column within a modifyGraph. This makes me think that raw is not allowed within withGraphJoined. Is there any other way I could achieve this?

The result contains my desired columns exlcept "translation" the result of raw(`(SELECT ${nameTranslatedColumn} )AS translation`),

No error is thrown, but the column "translation" is just not included in the result.
This is how my relational map looks like

```
      category: {
        relation: Model.HasOneRelation,
        modelClass: join(__dirname, 'article-category'),
        join: {
          from: 'article_categories.id',
          to: 'articles.categoryId',
        },
      },
```

Thanks!

```
    const nameTranslatedColumn = userLanguage === Language.english
      ? 'null'
      : 'article_categories.name_'.concat(userLanguage)

    Article.findAll()
      .withGraphJoined('[translations, category]')
      .modifyGraph('translations', builder => void builder
        .andWhere('progress', 100))
      .modifyGraph('category', builder => void builder
        .select(
          'id',
          'name',
          raw(`(SELECT ${nameTranslatedColumn} )AS translation`),
        ))
```

**Comment by koskimas** [comment]
Your code generates something like this `SELECT "id", "name", (SELECT article_categories.name_fi) AS translation`

You don't need to use a nested select or `raw` for that metter.

You can do this:

```js
    const nameTranslatedColumn = userLanguage === Language.english
      ? null
      : 'article_categories.name_'.concat(userLanguage)

    Article.findAll()
      .withGraphJoined('[translations, category]')
      .modifyGraph('translations', builder => void builder
        .andWhere('progress', 100))
      .modifyGraph('category', builder => {
        builder.select('id', 'name')
        if (nameTranslatedColumn) {
          builder.select(`${nameTranslatedColumn} as translation`)
        }
      })
```

**Comment by diegotorre5** [comment]
@koskimas Thank you so much for your answer. Would this way also work when userLanguage === Language.english? So the generated string would be "null as translation"? Or objection will confuse null with a column name rather that the value to be returned?

**Comment by koskimas** [comment]
At least on postgres you can select `null`. So this should work

```js
    const nameTranslatedColumn = userLanguage === Language.english
      ? null
      : 'article_categories.name_'.concat(userLanguage)

    Article.findAll()
      .withGraphJoined('[translations, category]')
      .modifyGraph('translations', builder => void builder
        .andWhere('progress', 100))
      .modifyGraph('category', builder => {
        builder.select('id', 'name')
        builder.select(`${nameTranslatedColumn} as translation`)
        }
      })
```

**Comment by diegotorre5** [comment]
Thank you Sami @koskimas, very appreciated.

**Comment by diegotorre5** [comment]
I just had the opportunity to run it and I had `"column \"null\" does not exist\n"` my database is postgres:12-alpine. That part of the query looks like

` left join (select \"id\", \"name\", \"icon\", \"created_at\", \"updated_at\", \"null\" as \"translation\" from \"article_categories\") as \"category\"`

for some reason, it is adding double-quotes for the null.

Any idea how could I work around this?

**Comment by diegotorre5** [comment]
It is working in this way, with a minimum modification:
` 
const nameTranslatedColumn = userLanguage === Language.english
      ? 'null'
      : 'article_categories.name_'.concat(userLanguage)

    Article.findAll()
      .withGraphJoined('[translations, category]')
      .modifyGraph('translations', builder => void builder
        .andWhere('progress', 100))
      .modifyGraph('category', builder => {
        builder.select('id', 'name')
        void builder.select(raw(`${nameTranslatedColumn}`).as('translation'))
        }
      })
`
Thank you so much
