### ISSUE TITLE
Passing config to model as a dependency

### ISSUE THREAD

**Issue by wizard11** [Vincit/objection.js#2015]
Hi all, I have a User Model, and I want to include a profileUrl field in it as virtual attribute. The problem is that I don't want to hard code the website domain into the profileUrl method as it comes from the config. Is there a way to pass the config to UserModel as a dependency, so that it can be accessed in the profileUrl method?

**Comment by koskimas** [comment]
I don't really know what you mean, or how you access the config in your app, but here's a couple of ways

```js
import { Model } from 'objection'
import { config } from '../config'

class User extends Model {
  get profileUrl() {
    return config.someUrl + '/profile'
  }
}
```

```js
import { Model } from 'objection'

class User extends Model {
  get profileUrl() {
    return this.constructor.someUrl + '/profile'
  }
}

// And then somewhere in the codebase
User.someUrl = config.someUrl
```

If you want to inject the URL per query, and not globally, It's probably simples to just add it to the returned objects.
