### ISSUE TITLE
insertGraph not working for specific column name

### ISSUE THREAD

**Issue by kevhender** [Vincit/objection.js#2016]
I'm trying to debug why `insertGraph` won't work for a specific column of a specific table. The table just has an ID and a "dob" date column. The ID uses a sequence and the insert does create the record, but the "dob" column is not inserted.

This:
```js
Person
  .query()
  .insertGraph({ dob: '1980-01-01' })
  .returning('*')
```
yields this:
```sql
insert into "person" default values returning *
```

However, if I rename the column to "dob123", and leave everything else the same, it works:
```js
Person
  .query()
  .insertGraph({ dob123: '1980-01-01' })
  .returning('*')
```
yields:
```sql
insert into "person" ("dob123") values (?) returning "id"
```

Any idea what could possibly be wrong here? Or how I could debug how this SQL is being created?

**Comment by devinivy** [comment]
I think it would be useful to get some more information about your `Person` model.  Are you using validation, and if so, what does that look like?  Are you using any lifecycle hooks?

**Comment by kevhender** [comment]
@devinivy Your comment was all I needed to trigger it in my brain... My model inherits from another model that had the `dob` property as a virtual attribute, so that was keeping this from working. Thank you for your help!

**Comment by devinivy** [comment]
@kevhender nice, glad that's all it was!
