### ISSUE TITLE
Possible to filter withGraphFetched or withGraphJoined?

### ISSUE THREAD

**Issue by armandAkop** [Vincit/objection.js#2018]
Objection Version: 2.2.14

Following this Person HAS MANY Pets, Pet HAS ONE Person model

```node
class Person extends Model {
  static get tableName() {
    return 'person';
  }
  static get idColumn() {
    return 'person_id';
  }

  static get relationMappings() {
    return {
      pets: {
        relation: Model.HasManyRelation,
        modelClass: Pet,
        join: {
          from: 'person.person_id',
          to: 'pet.pet_id'
        }
      }
    }
  }
}

class Pet extends Model {
  static get tableName() {
    return 'pet';
  }
  static get idColumn() {
    return 'pet_id';
  }

  static get relationMappings() {
    return {
      person: {
        relation: Model.HasOne,
        modelClass: Person,
        join: {
          from: 'pet.pet_id',
          to: 'person.person_id',
        }
      }
    }
  }
}

```

Is it possible to filter out results from the parent table "Person" with data from the child table "Pets" without first filtering on Person? The use case being there might be additional columns in the child table that I would like to filter on and only return those corresponding parent entries. 

```node
Person.query()
.withGraphFetched('pets(byOtherCol)')
.modifiers({
  byOtherCol(builder) {
    builder.where(some_other_col, ‘=‘, ‘abc’)
  }
})
```

So the results would return something like
```node
[{
  person_id: 555,
  pets: [{
    pet_id: 123,
    person_id: 555,
    some_other_col: “abc”
  },{
    pet_id: 124,
    person_id: 555,
    some_other_col: “abc”
  }]
}]
```

Currently, the above query returns ALL Person(s) along with empty arrays for their Pets, except for some_other_col: “abc”  which 2 pets have.

**Comment by koskimas** [comment]
You can do that using `wirhGraphJoined`

```js
Person.query()
  .withGraphJoined('pets')
  .where('pets.some_orher_col', 'abc')
```

**Comment by armandAkop** [comment]
@koskimas It seems that doing `withGraphJoined` performs a LEFT JOIN from `Person` to a subselect of `Pet`, which returns back the same results. I guess my question is, would it be possible to perform an inner join on that subselect instead?

**Comment by koskimas** [comment]
You can specify the `joinMethod` for `withGraphJoined`.

https://vincit.github.io/objection.js/api/query-builder/eager-methods.html#withgraphjoined
https://vincit.github.io/objection.js/api/types/#type-graphoptions

**Comment by PushkarDureja15** [comment]
@armandAkop did you manage to work it out ? I am dealing with the same problem
