### ISSUE TITLE
merge(["some", "fields"]) is not available

### ISSUE THREAD

**Issue by vvo** [Vincit/objection.js#2024]
Hi there, I was trying to use:

```js
Model.query()
  .insert({name: "Hello", age: 10, uniqueId: 2})
  .onConflict("uniqueId")
  .merge(["name"]);
```

As per Knex documentation: http://knexjs.org/#Builder-merge.
![image](https://user-images.githubusercontent.com/123822/112341608-da102500-8cc1-11eb-926b-aca32f059b07.png)

But it seems like only the object mode works with Objection.js:

```js
Model.query()
  .insert({name: "Hello", age: 10, uniqueId: 2})
  .onConflict("uniqueId")
  .merge({name: "Hello"});
```

Which is fine, I can use this instead. But maybe we want to have the same API than Knex here too?

Thanks!

**Comment by koskimas** [comment]
Thanks for bringing this up. I'll add support for that syntax.

**Comment by ricjd** [comment]
Trying to see if there is a work around for this as this is an issue for me as well

**Comment by arpadgabor** [comment]
Any update to this issue?
