### ISSUE TITLE
About raw queries

### ISSUE THREAD

**Issue by imri-dev** [Vincit/objection.js#2025]
I am trying to join two tables and trying to distinct the id of parent table with where clause. However, my below query is not working. I went through all the docs cant seem to find any answer.  EDIT: Yes, I am awaiting the query. 

```js
this.query
  .knex()
  .raw(
    `SELECT DISTINCT ON(management_company.id) m_name FROM management_company INNER JOIN buildings 
      on m_id = management_company.id WHERE m_name LIKE '%nana%`
  );
  return this;
```

**Comment by koskimas** [comment]
In the example you are not awaiting the query. And also returning `this` after awaiting would not return the result. You need to return the result of the knex query.

Anyway, there's no need to use raw. You can do this

```js
await ManagementCompany.query()
  .select('m_name')
  .distinctOn('management_company.id')
  .innerJoin('buildings', 'm_id', 'management_company.id')
  .where('m_name', 'like', ''%nana%`)
```
