### ISSUE TITLE
Syntax question: self reference relation with other relations?

### ISSUE THREAD

**Issue by waveiron** [Vincit/objection.js#2026]
- Model `Category` belongs to one `Category` (self-reference)
- Model `Category` has many `Product`

How can I write something like this (with products data loaded for each category level):
```typescript
Category.query().withGraphFetched('[children.^, products]')
```

**Comment by koskimas** [comment]
There's no way to do that using the string expressions but maybe this works:

```js
const expr = {
  products: true,
}

expr.children = expr

Category.query().withGraphFetched(expr)
```
