### ISSUE TITLE
Is there a way to have a dynamic table name in objection?

### ISSUE THREAD

**Issue by jeddine** [Vincit/objection.js#2028]
I have a case when I can't use a static table name, the table name is available at runtime, I'm wondering if something like the following is possible:

```js
class Resource extends Model {
    storeId: number;

   constructer(storeId: number) {
      this.storeId = storeId; 
   }

  static get tableName() {
     return `prefix_${this.storeId}`
  }
}
```

Or maybe something like this:

```js
const myModules = {
    resource: Resource.tableName(394893)
}
```

and the model class will be like this:

```js
class Resource extends Model {
  static get tableName(storeId: number) { // this will not work because of the get :/
     return `prefix_${storeId}`
  }
}
```

**Comment by koskimas** [comment]
You can't do it that way. The table name is expected to remain unchanged per model. You can however create new subclasses of the model wherever you need to.

```js
const Resource2 = class extends Resource {
  static tableName = 'whatever'
}
```

now `Resource2` is just like `Resource` but with a new table name.
