### ISSUE TITLE
Correct esm modules usage in relations

### ISSUE THREAD

**Issue by vladshcherbin** [Vincit/objection.js#2029]
Hey 👋 

I'm trying to use native esm modules in relations.
Two models - `Huddle`, `HuddleJoinRequest`, they import each other.  Here is simplified `HuddleJoinRequest` model:

```js
class HuddleJoinRequest extends BaseModel {
  static relationMappings = {
    huddle: {
      modelClass: Huddle
    }
  }
}
```

With direct import I get circular dependency with error:

```console
ReferenceError: Cannot access 'Huddle' before initialization
```

From docs I've tried solution 2 (path to model):

```js
class HuddleJoinRequest extends BaseModel {
  static relationMappings = {
    huddle: {
      modelClass: path.join(path.dirname(fileURLToPath(import.meta.url)), 'Huddle')
    }
  }
}
```

Error:

```console
Error: HuddleJoinRequest.relationMappings.huddle: Must use import to load ES Module: ...
require() of ES modules is not supported.
```

I've also tried solution 3 (set `modelPaths`):

```js
class HuddleJoinRequest extends BaseModel {
  static modelPaths = [path.dirname(fileURLToPath(import.meta.url))]

  static relationMappings = {
    huddle: {
      modelClass: 'Huddle'
    }
  }
}
```

Error is the same as above one.

I've also tried `await import` (similar to solution 1 I believe):

```js
class HuddleJoinRequest extends BaseModel {
  static relationMappings = async () => ({
    huddle: {
      modelClass: await import('./Huddle')
    }
  })
}
```

error is:
```console
Error: A model class HuddleJoinRequest doesn't have relation huddle
```

I believe it's because relationMappings promise is not resolved in time.

Last one I've tried is:

```js
class HuddleJoinRequest extends BaseModel {
  static relationMappings = {
    huddle: {
      modelClass: () => import('./Huddle')
    }
  }
}
```

Error is:

```console
Error: HuddleJoinRequest.relationMappings.huddle: modelClass: is not a subclass of Model or a file path to a module that exports one.
You may be dealing with a require loop. See the documentation section about require loops.
 ```

I'm not using Babel or Typescript to transpile code, just Node 14 and Objection 2.2.13 with plain esm module imports.
Wondering what's the solution for this.

Thanks

**Comment by alimertcakar** [comment]
I reserved my sunday for exploring objection.js, and I was struggling with this too, just as I was checking objection.js issues I saw yours. What a coincidence :)

I think the solution is just to import the Model from the top, and make relation mappins a thunk. That is supposed to prevent circular dependencies as mentioned in koa example:
` // property can be a thunk to prevent circular dependencies.
  static relationMappings = () => ({
`


https://github.com/Vincit/objection.js/blob/master/examples/koa-ts/models/Movie.ts

**Comment by vladshcherbin** [comment]
@alimertcakar yep, it works, thank you 🥳

I've used it before and didn't try now because linter screamed at me as soon as I wrote top import.
Wondering if solutions from docs can be adapted to support esm modules, especially with upcoming 3.0 and https://github.com/Vincit/objection.js/issues/2023.
I'd love to use `modelPaths` in `BaseModel` and just use string model name in `modelClass`.

**Comment by koskimas** [comment]
`modelPaths` or path strings can't be easily supported with esm because esm imports are async.

**Comment by vladshcherbin** [comment]
@koskimas what's the recommended solution though? 🤔  None of solutions from docs would work with esm imports.

**Comment by harishk630** [comment]
Just want to share the workaround I am doing. 
I added  `static async setupRelation( allModels )` function in all all models and  did this in `models/index.js` file
```javascript
import { Model1 } from './Model1.js';
import { Model2 } from './Model2.js';
import { Model3 } from './Model3.js';
import { Model4 } from './Model4.js';

const allModels = [
  Model1,
  Model2,
  Model3,
  Model4
];

Object.values(allModels).forEach(async function (model) {
  if (model.setupRelation) {
    model.relationMappings = await model.setupRelation(allModels);
  }
});

export default allModels;

```

**Comment by harish2704** [comment]
Just want to share the workaround I am doing. 
I added  `static async setupRelation( allModels )` function in all all models and  did this in `models/index.js` file
```javascript
import { Model1 } from './Model1.js';
import { Model2 } from './Model2.js';
import { Model3 } from './Model3.js';
import { Model4 } from './Model4.js';

const allModels = [
  Model1,
  Model2,
  Model3,
  Model4
];

Object.values(allModels).forEach(async function (model) {
  if (model.setupRelation) {
    model.relationMappings = await model.setupRelation(allModels);
  }
});

export default allModels;

```
