### ISSUE TITLE
Self reference relation (tree) optimization?

### ISSUE THREAD

**Issue by waveiron** [Vincit/objection.js#2030]
Say we have a self-reference model:

```typescript
{
  id: 2
  parentId: 1
}
```

`withGraphFetched('children^')` makes a new query() for each level of its children, how optimize this? Typeorm has 4 ways to optimize this kind of scenario: [Tree Entities](https://github.com/typeorm/typeorm/blob/master/docs/tree-entities.md), how to implement that while keeping the power of objection query builder?

The tree structure is important in many scenarios since that's how most things work, (social hierarchy, category Inclusion, traits extension...), really expecting objection to have optimized tree query support. Again, @koskimas, great work!

**Comment by devinivy** [comment]
In my opinion objection provides all the querying primitives one needs to implement these patterns, and special support for modeling trees in various ways would make for a fantastic objection plugin.  As I see it, the recursive relation expression exists for completeness more so than to support a specific way to represent trees in a relational database.

**Comment by koskimas** [comment]
I agree with @devinivy
