### ISSUE TITLE
Remove JSONB property with patch

### ISSUE THREAD

**Issue by elby22** [Vincit/objection.js#2034]
Objection supports partial updates (patches) of JSONB columns through field expressions. However I can't seem to delete a property without doing an update by getting the existing value and excluding the properties to delete. 
Would it be possible to support deleting a property by supplying a value of `undefined`?

As of now giving an undefined in the fieldExpression generates no query.
Example:

```
const params = { tags: { deleteMe: true } };
const person = await Person.query().insert(params).returning('*');
await person.$query().patch({ 'tags:deleteMe': undefined });
```

This does not update the `deleteMe` field of the `tags` column, and the value is still `true`. Is setting a fieldExpression to undefined a reasonable approach to this or is there a better way to remove a JSONB property with a patch operation?

**Comment by dhruvg0001** [comment]
Did you ever find the solution? Please let me know. Similar issue.

**Comment by koskimas** [comment]
There's no shortcut syntax for this but you can always use raw sql:

```js
await person.$query().patch({ tags: raw("tags - 'deleteMe'") });
```
