### ISSUE TITLE
[Question] is it possible to incorporate your custom validation error into jsonSchema validation errors?

### ISSUE THREAD

**Issue by rhazegh** [Vincit/objection.js#2036]
First of all, thank you for this fantastic project. I have just started using it and am enjoying it. 🙏

### Current situation
Currently I have a `jsonSchema` for validation and also a `custom validation` for `email` like this:

user.js file:

```javascript
import emailValidator from "email-validator";
import { Model, ValidationError } from "objection";

class User extends Model {
  static get tableName() {
    return "users";
  }

  static get jsonSchema() {
    return {
      type: 'object',
      properties: {
        id: { type: 'integer' },
        name: { type: 'string', minLength: 3, maxLength: 255 },
        email: { type: 'string' },
        passwordHash: { type: 'string' }
      }
    };
  }

  $afterValidate(json, opt) {
    if(json.email) {
    const validEmail = emailValidator.validate(json.email);
      if(!validEmail) {
        throw new ValidationError({
          type: 'ModelValidation',
          data: {
            email: [
              {
                message: "should be valid email address",
                keyword: "validEmail",
                params: {}
              }
            ]
          },
        });
      }
    }
  }
}

export default User;
```

When I attempt to create a user with `invalid name`, the validation error looks like this:
```json
{
  "name": "ValidationError",
  "type": "ModelValidation",
  "data": {
    "name": [
      {
        "message": "should NOT be shorter than 3 characters",
        "keyword": "minLength",
        "params": {
          "limit": 100
        }
      }
    ]
  },
  "statusCode": 400
}
```

When I attempt to create a user with `invalid email`, the validation error looks like this:
```json
{
  "name": "ValidationError",
  "type": "ModelValidation",
  "data": {
    "email": [
      {
        "message": "should be valid email address",
        "keyword": "validEmail",
        "params": {}
      }
    ]
  },
  "statusCode": 400
}
```

When I attempt to create a user with `invalid name` and `invalid email`, the validation error looks like this:
```json
{
  "name": "ValidationError",
  "type": "ModelValidation",
  "data": {
    "name": [
      {
        "message": "should NOT be shorter than 3 characters",
        "keyword": "minLength",
        "params": {
          "limit": 100
        }
      }
    ]
  },
  "statusCode": 400
}
```

### Question:
When both `name` and `email` are invalid, is it possible to have both errors in the same validation error as follows? If yes, how? Is there documentation or a practical example I can look at? Thank you!

```json
{
  "name": "ValidationError",
  "type": "ModelValidation",
  "data": {
    "name": [
      {
        "message": "should NOT be shorter than 3 characters",
        "keyword": "minLength",
        "params": {
          "limit": 100
        }
      }
    ],
    "email": [
      {
        "message": "should be valid email address",
        "keyword": "validEmail",
        "params": {}
      }
    ]
  },
  "statusCode": 400
}
```

**Comment by koskimas** [comment]
`$afterValidate` is not called if the validation throws. Therefore you don't get the second error.

AJV (the validator objection uses) already has `email` validation, maybe you can use that one instead?
https://ajv.js.org/packages/ajv-formats.html

If not, you can probably use AJV user-defined keywords
https://ajv.js.org/guide/user-keywords.html
https://ajv.js.org/packages/ajv-keywords.html

You can modify the AJV validator by overriding the static createValidator method as described here
https://vincit.github.io/objection.js/api/model/static-methods.html#static-createvalidator
