### ISSUE TITLE
[Question] modify() on updateAndFetchById

### ISSUE THREAD

**Issue by thefoxie** [Vincit/objection.js#2037]
Hey, I've stumbled upon this when I tried to use query with updateAndFetchById() and modify() at the same time. Doesn't work with returning("*") as well.

Is it by design? That would be my wild guess.

Works only when I call update() and find separately.
```js
await Item.query().update(newItem).where("id", newItem.id);

const updatedItem = Item.query()
	.findById(newItem.id)
	.modify("defaultResponse");
```

**Comment by koskimas** [comment]
`updateAndFetchById` runs two queries: the update and a separate `select` query. Which query should `modify` affect? Therefore it currently has no effect on either.

if you are on postgres, you don't need `updateAndFetchById` at all. You can use `returning` with the normal `update` or `patch` method.
