### ISSUE TITLE
[Question] Flatten nested relation mappings object into Model instance JSON?

### ISSUE THREAD

**Issue by kennyhuynh125** [Vincit/objection.js#2040]
https://vincit.github.io/objection.js/guide/relations.html#examples

I'm wondering if it is possible to have a relation mapping for a Model, but not have a nested object of that mapping when using `withGraphFetched()`.

For example:

```
class Person extends Model {
  static tableName = 'persons';

  static relationMappings = {
    animal: {
      relation: Model.HasOneRelation,
      modelClass: Animal,
      join: {
        from: 'persons.id',
        to: 'animals.ownerId'
      }
    }
  };
}
```

If I do a query like `Person.query().withGraphFetched('animal')` this would be the JSON output of a single `Person` instance:

```
{
    firstName: 'John',
    lastName: 'Smith',
   animal: {
       name: 'Mochi',
       type: 'dog'
   }
}
```

Is it possible to somehow have the output for a single `Person` instance to not have a nested `animal` object, but rather have the fields be a part of the `Person` instance like this:

```
{
    firstName: 'John',
    lastName: 'Smith',
    animalName: 'Mochi',
    animalType: 'dog'
}
```

**Comment by koskimas** [comment]
What you want is a join:

```js
Person.query()
  .joinRelated('animal')
  .select('person.*', 'animal.name as animalName', 'animal.type as animalType')
```
