### ISSUE TITLE
withGraphJoined  ignored when Used alongside withGraphFetched

### ISSUE THREAD

**Issue by pradosh987** [Vincit/objection.js#2041]
I am trying to `withGraphJoined` alongside `withGraphFetched` but ObjectionJS ignore `withGraphJoined` and fetches all relations in separate query.

```
const result = await User.findById(1)
  .withGraphJoined("avatar")
  .withGraphJoined("currentAddress")
  .withGraphFetched("playlists.[movies.[actors], tvShows.[actors]]")
```

`withGraphJoined ` is totally ignored and even avatar is fetched in separate query. I want to do this because there will be only one entry for avatar and currentAddress. 

Is this a bug or by design. Any alternative way I can achieve this? What id the recommended way to load more than 5 relations at a time with mixed cardinality ?

**Comment by koskimas** [comment]
Unfortunately you can't mix those two like that. What you can do, is first run the withGraphJoined query and then load the other relations using $loadGraph for the returned item.

**Comment by koskimas** [comment]
You're welcome, asshole.

**Comment by pradosh987** [comment]
Is this guys so desperate for attention to leave such comment. Thats sad @koskimas. I hope you'll find better meaning for life rather than waiting for strangers on internet to thank you. 
![Screenshot 2021-04-28 at 5 29 39 PM](https://user-images.githubusercontent.com/7407795/116401021-61fcc800-a848-11eb-9c2a-39a7b9ba1958.png)
