### ISSUE TITLE
Define Model with Stored Procedure

### ISSUE THREAD

**Issue by NamedArray** [Vincit/objection.js#2042]
Can I use the results of a Stored Procedure to define a Model with Objection.js?

**Comment by koskimas** [comment]
Each model must point to a table. The table name cannot be arbitrary SQL. Maybe you could create a [view](https://www.postgresql.org/docs/9.2/sql-createview.html) and make the model point to that?

**Comment by NamedArray** [comment]
My DBA's mandate is that I must use Stored Procedures to interact with the DB.

What if I could guarantee you that the Stored Procedure would return the the appropriate representation of the "Model/Table" each and every time?

OR --- are does the use of Stored Procedures sort of negate ORMs?

**Comment by koskimas** [comment]
You don't need to guarantee me anything  😄. It would be extremely difficult to make this work and figure out how to pass arguments to the stored procedures. Also you are the first one I've ever met that wants to use only stored procedures to interact with the DB. 

Considering the amount of people this feature would be useful for (very few), and how difficult it would be to implement, support is just not going to be added.

I'd say you'll have very difficult time getting any ORM to work like this. My suggestion is to use SQL or a query builder like knex.
