### ISSUE TITLE
Add id value to $afterUpdate hook

### ISSUE THREAD

**Issue by vladshcherbin** [Vincit/objection.js#2045]
Hey 👋 

Trying to get `id` value when using `$afterUpdate` and `patch` method. `this` has only patched fields and it's not always possible to rely on `old`. Would be nice to have `id` value, currently hook functionality seems limited.

Related issue and comment before v2 - https://github.com/Vincit/objection.js/issues/966#issuecomment-398499398

Thanks

**Comment by koskimas** [comment]
There's no way to get the is there in all cases without querying the database. You can implement this yourself using the static hooks.

**Comment by koskimas** [comment]
As an example, consider this query:

```js
await Person.query().update({ something: 'foo' })
```

That query updates all rows in the database. The only way to get the `id` in `$afterUpdate` is to query **all** rows in the database and select their `id`. Now you can understand it would be surprising to say the least for people that only expect an update to take place.

This kind of magic will never be added to objection.

With the static hook API added to objection 2 you can choose to do this yourself

```js
class Person extends Model {
  static afterUpdate({ asFindQuery }) {
    const idsOfUpdatedRows = await asFindQuery().select('id')
   ...
  }
}
```

**Comment by vladshcherbin** [comment]
@koskimas thanks for static hook alternative. What about `returning` trick here?

For example I'm using `patch` with `returning`:

```js
await joinRequest.$query().patch({ is_cancelled: true }).returning('*') // I know "this.old" can be used here
```

It produces sql

```sql
update "huddle_join_requests" SET "is_cancelled" = TRUE, "updated_at" = '2021-05-02T08:39:47.480Z' WHERE "huddle_join_requests"."id" = 5 returning *
```

`this` has:

```js
{
  is_cancelled: true,
  updated_at: '2021-05-02T08:39:47.480Z'
}
```

In this case all data is returned, maybe it's possible to also add it to `this`?

**Comment by vladshcherbin** [comment]
It's also possible to add `returning` to your update example:

```js
await Person.query().update({ something: 'foo' })).returning('*')
```

This will return all info for updated items without additional select queries.

What do you think?

**Comment by koskimas** [comment]
Why not just use the static hooks? For example, rename the `$afterUpdate` to `afterUpdate` and do this

```ts
class Person extends Model {
  static async afterUpdate({ result }) {
    for (const item of result) {
      await item.afterUpdate();
    }
  }
}
```
