### ISSUE TITLE
Unsetting a property on a TypeScript model

### ISSUE THREAD

**Issue by fiznool** [Vincit/objection.js#2046]
The [example model class in the tests](https://github.com/Vincit/objection.js/blob/master/tests/ts/examples.ts#L49-L54) uses the following syntax to define nullable and non-nullable fields:

``` ts
class Person extends objection.Model {
  // With TypeScript 2.7, fields in models need either optionality:
  firstName?: string;
  // Or for not-null fields that are always initialized, you can use the new ! syntax:
  lastName!: string;
}
```

When using the optional `?` operator for nullable properties, TypeScript equates this as a type of `string | undefined`.

This poses a problem when trying to unset a model property that has previously been set in the database, i.e. set it to `null`. Using the example above, we could try to use `patch` to update the model. Either:

``` ts
await Person.query()
  .patch({
    firstName: null
  })
  .where('id', someId);
```

Or, with a model instance:

``` ts
await personModel.$query().patch({
  firstName: null
});
```

The trouble is, TypeScript does not consider `null` to be a valid value for the `firstName` property - it must be `string | undefined`. We can't use `undefined` as the value, as this does not unset the property - I guess Objection ignores any value which is `undefined`?

So, we must either:

1. Change the typings for any nullable field to include `null` as a valid type. For example:

``` ts
class Person extends objection.Model {
  firstName?: string | null;
}
```

2. Use some fugly casting in any `patch` operation:

``` ts
await personModel.$query().patch({
  firstName: null as unknown as undefined
});
```

I can see from [another issue](https://github.com/Vincit/objection.js/issues/1690) that the recommended approach is option 1, but this doesn't really tally up with optionality. When reading a `null` column from the database, Objection sets this to `undefined`. But, here we must use `null`, since setting a field to `undefined` does not include it in the update operation.

I've therefore opened this issue to clarify how this should behave. One option could be to allow `undefined` as a valid value for any property in a `patch` operation, and Objection treats this as 'set this property to `null` in the database'. Contrast this with an object which does not contain the property at all, which would signify 'don't include this property in the update operation at all, i.e. leave it how it currently is in the database'. But this would likely be considered a breaking change, if it is at all feasible in the first place...

**Comment by fiznool** [comment]
ref #1690

**Comment by fiznool** [comment]
Another thought: perhaps the typings for `PartialModelObject` could automatically add `| null` to all properties on the associated model?

**Comment by fiznool** [comment]
For anyone else experiencing this issue, I have found a workaround for the instance model variation:

``` ts
personModel.$set({
  firstName: null
});
await personModel.$query().patch();
```

**Comment by koskimas** [comment]
Null columns are read as null. If you don't select a column, then the column is missing (undefined).
