### ISSUE TITLE
lower case table name with upper snake case column names

### ISSUE THREAD

**Issue by madhura-utterwise** [Vincit/objection.js#2047]
I am using Objectionjs with FeathersJS.
I have tables with names like **user_details, user_roles**. The columns in the tables have names like **USER_NAME, USER_ROLE_ID**, etc.
If I use `knexSnakeCaseMappers({ upperCase: true })`, the query results in an error as :
**Table 'db.USER_DETAILS' doesn't exist** 
It tries to convert the table name to upper case.

If I do not provide the upperCase as true, then the fields are returned as `{USERNAME: 'abc}'`

Is there a way we can ignore case of table names and have the `knexSnakeCaseMappers `applied only on table columns?

**Comment by koskimas** [comment]
Unfortunately that's not possible.
