### ISSUE TITLE
create a new object of group of field in select query in objection js

### ISSUE THREAD

**Issue by ravipateldhg** [Vincit/objection.js#2048]
I have one select query in Objections JS(NodeJs). That will return few fields. I need to modify the result. Suppose we have got below JSON from the response of the query.

```js
{
   group_id, 
   group_name,
   link,
   created,
   user_id
}
```
I need to update this response like below with the use of the loop of the.

```js
{
   group: {
      id, 
      name,
   },
   link,
   created,
   user_id
}
```
Is there any option in objections to updating our result like this? Please help me with this concern.

**Comment by koskimas** [comment]
If that all comes from a single table, there's no built-in tool to help with that. If `group_id` and `group_name` come from a join to another table, you can simply create a relation to that table and use `withGraphFetched('group')` to get the nested structure.

Without knowing anything about your setup, I can't help more.

You can of course always just modify the returned objects:

```js
const item = await Group.query().findById(1)

item.group = { id: item.group_id, name: item.group_name }
```

Or you can create a getter for the model

```js
class Group extends Model {
  ...other stuff

  // This will include the group getter in the serialized result
  static virtualAttributes = ['group']

  get group() {
    return { id: this.group_id, name: this.group_name }
  }
}
```

If you want the `group_id` and `group_name` removed from the result you can override the `$formatJson´ method

```js
class Group extends Model {
  ...other stuff

  // This will include the group getter in the serialized result
  static virtualAttributes = ['group']

  get group() {
    return { id: this.group_id, name: this.group_name }
  }

  $formatJson(json) {
    json = super.$formatJson(json)
    delete json.group_id
    delete json.group_name
    return json
  }
}
```

**Comment by ravipateldhg** [comment]
@koskimas Thanks. Your solution is working with me. But I need this virtual field in only one query. I need the rest of the query for this table is remain the same. Is there any way to do it?

**Comment by koskimas** [comment]
If you only need it for one query, then I'd just modify the result

```js
const item = await Group.query().findById(1)

item.group = { id: item.group_id, name: item.group_name }
delete item.group_id
delete item.group_name
```

**Comment by koskimas** [comment]
Then use a for loop 😂
