### ISSUE TITLE
use withGraphJoined or withGraphFetched and page and where

### ISSUE THREAD

**Issue by joneldiablo** [Vincit/objection.js#2051]
(.withGraphJoined || .withGraphFetched) && .page && .where <tableName>.<columnName>
Hi!!!!
good day, I'm trying to use the method `page` to get some data from mysql data base, I have some relations which I try to get data filtered by the related tables, like this:

```
FacturaNoCargadaModel.query()
      .withGraphFetched('[proveedor(related),factura(related),comprobante(related)]')
      .where('proveedor.razon', 'LIKE', '%........%').page(....);
```

the problem is: when I use `withGraphJoined` the filter works ok (filter by: `proveedor.razon`) but the number of total rows from page are wrong, and when I use `withGraphFetched` the filter not working and returns me error `Unknown column 'proveedor.razon' in 'where clause'`

how can I use all them together?

**Comment by throrin19** [comment]
Any solution with mysql ?
