### ISSUE TITLE
Setting json: no such function: jsonb_set

### ISSUE THREAD

**Issue by zzph** [Vincit/objection.js#2055]
Hi,

I am trying to patch JSON data onto my model, however I keep geting `SQLITE_ERROR: no such function: jsonb_set`. 

Here is an example to reproduce the error

```
Person.query().patchAndFetchById(personId, {
        'jsonData:address.suburb': 'Foo'
})
```

My migration has this field:

```
table.json('jsonData')
```

How can I get around this error? Is it a bug?

Thanks

**Comment by devinivy** [comment]
The JSON queries can only be expected to work when using PostgreSQL.  This is documented here: https://vincit.github.io/objection.js/recipes/json-queries.html#json-queries.  In this case objection is using `jsonb_set()`, which is a PostgreSQL function but not a SQLite function, which is the cause of the error.  You may be able to achieve what you're trying to do using a raw query part— I think SQLite does support a similar-but-different `json_set()` function.
