### ISSUE TITLE
snakeCaseMappers doesn't work on returned data from merge

### ISSUE THREAD

**Issue by joziahg** [Vincit/objection.js#2057]
I have a method that looks like this:
```javascript
await Model.query().select().insertAndFetch({ creator_id: user.id, some_data: 'hello_world' }).onConflict('id').merge({ editor_id: user.id, some_data: 'goodbye_world' }).withGraphFetched({ editor: true })
```

On inserts, it returns the data with snake_case mapped to camelCase. But on conflict-merges it does not, additionally neither does the withGraphFetched. It will add the object key, but the value will always be null.

knexjs: 0.95.6
objection: 2.2.15
mysql: 2.2.5

**Comment by koskimas** [comment]
Please provide a minimal reproducible example.

**Comment by koskimas** [comment]
You are trying to make a select query and an insert query at the same time. You are also using snake_case even though you are using snakeCaseMappers.

**Comment by joziahg** [comment]
I use snake_case in queries because I don't use knexSnakeCaseMappers so everything is defined with snake_case in models. I didn't know you don't need to pre-append insertAndFetch with select. The issue still remains though, the merge not is returning camelCased values
