### ISSUE TITLE
UpsertGraph returning trick doesn't return all data if graph has no changes

### ISSUE THREAD

**Issue by vladshcherbin** [Vincit/objection.js#2058]
Hey 👋 

Using `upsertGraph` and `returning *` trick:

```js
Book.query()
  .upsertGraph({
    id: 20,
    title: 'new title'
  })
  .returning('*')
```

When any field is changed, full model is returned (`title` is changed in example above):

```js
Huddle {
  id: 20,
  title: 'new title',
  description: 'nice book',
  // rest fields
}
```

However, if nothing is changed, only provided fields from `graph` are returned (using same query above):

```js
Huddle {
  id: 20,
  title: 'new title'
}
```

I believe it's because only `graph` fields are selected from database to check if `update` is needed:

```sql
SELECT "books"."id", "books"."title" FROM "books" WHERE "books"."id" IN (20)
```

If new data is added, `returning *` trick gets the rest of data:

```sql
UPDATE "books" SET "title" = 'new title', "updated_at" = '2021-05-27T18:38:58.998Z' WHERE "books"."id" = 20 returning *
```

Possible fix is to select all fields if `returning *` trick is present.

objection - 2.2.15

**Comment by koskimas** [comment]
`returning` is only supposed to add a `returning` statement. It shouldn't add a `select` statement, let alone a separate select query.

You can use `upsertGraphAndFetch`.

**Comment by vladshcherbin** [comment]
@koskimas I didn't mean adding separate `select` query. When using `upsertGraph` there is already a `select` query which fetches provided graph fields. From example above (`id`, `title`):

```sql
SELECT "books"."id", "books"."title" FROM "books" WHERE "books"."id" IN (20)
```

As you can see, `id` and `title` will be returned. What I propose is if `returning` is present, this select would take all columns from database:

```sql
SELECT "books".* FROM "books" WHERE "books"."id" IN (20)
```

This way, if graph data is unchanged and `update` query is not executed, all data will be still present and `upsertGraphAndFetch` won't be needed.

Makes sense?

**Comment by koskimas** [comment]
returning should only add a returning statement.

**Comment by vladshcherbin** [comment]
Okay, makes sense. Maybe an option in `upsertGraph` can be used to select all fields for the model 🤔

I'm just trying to find a way skip using `upsertGraphAndFetch` as it produces extra queries when data is almost already there.
