### ISSUE TITLE
Having to pass Knex instance to query() while attribute knex is ignored.

### ISSUE THREAD

**Issue by CodeSpent** [Vincit/objection.js#2059]
So every example I see mentions using `Model.knex = Knex()` to set the knex instance, but for some reason this doesn't work for me and I can't find any documentation on a change.

Weirdly I have to pass `Knex()` to the `query()` method like `query(Knex())` and this works as expected, until a join or anything is needed.

Anyone know what has changed?

Knex 0.21.18
Objection 2.2.15

The implementation as follows does work, but if I were to change `Tag.query(db)` to `Tag.query()` as illustrated in examples, I'd get the following error.

```
TypeError: builder.knex(...).queryBuilder is not a function
```

However, if I do use `.query(db)` then I can make a normal query, but if I try `.query(db).joinRelated('category')` then I'll get the same error above, but for the next query. So for some reason setting the instance with `Model.knex = db` is not working and joins rely on this if I'm understanding correctly.

**models/tag.ts**
```javascript
import TagCategory from "./tag-category";
import TagType from "./tag-type";
import db from "../database/db";

Model.knex(db);

export default class Tag extends Model {
  id!: number;
  name!: string;
  keywords!: string[];
  category!: TagCategory;
  type!: TagType;
  parent!: Tag;

  static tableName = "tags";
  static idColumn = "id";
  ...
```

**db.ts**
```javascript
const knex = require("knex");

const knexfile = require("../knexfile");

const env = process.env.NODE_ENV || "development";

const configOptions = knexfile[env];

export default knex(configOptions);
```

**controllers/tags.ts**
```javascript
import Tag from "../models/tag";

export async function getTags(req: Request, res: Response): Promise<void> {
  const tags = await Tag.query(db);
  res.json(tags);
}
```

**Comment by CodeSpent** [comment]
I sorted this out. For anyone who else may run into this issue, what was wrong was I was mislead by an abstraction I saw in another example.

In my `server.ts` file I was also doing
```
Model.knex = db;
```

Which was setting the `knex` method to my knex instance, which was overriding it's use in `Model.query()`.

So be sure you're not doing the same.

**Comment by koskimas** [comment]
Mislead by what? Maybe just admit you made a mistake and don't blame the tool or others? How about that? There's zero examples that do what you did. You were not mislead.
