### ISSUE TITLE
Computed JSON schema based on query (static method)

### ISSUE THREAD

**Issue by zzph** [Vincit/objection.js#2061]
Hi there :)

Is it possible to "compute" my json schema when a query occurs. However, I can't seem to figure out how to "tell" what kind of query is received. 

```
static get jsonSchema() {
    return getSchemaBasedOnQuery(this.TYPE_OF_QUERY)
   // eg insert/patch/delete
  }
```

Is this possible? If not, do you suggest another method of doing this?

Cheers

**Comment by caschbre** [comment]
I believe the purpose of the jsonSchema is to provide a static definition of the Model and not be dynamic based on the query.

There are several jsonSchema builders based on knex that will read your db schema and generate jsonSchemas... however I'm betting those are table-based and not necessarily Model-based so you might have to generate them and the cut/paste.

**Comment by koskimas** [comment]
Not possible I'm afraid
