### ISSUE TITLE
newbie question about objection (NOT an issue)

### ISSUE THREAD

**Issue by edwardsmarkf** [Vincit/objection.js#2063]
hello - Objection looks very interesting, and probably a great replacement for sequelize.

question:  if one is starting out with many pre-existing sql statements from old code, would it be better to use "raw" sql in objection or try to rewrite the sql using the objection method?

or is there some slick way of taking existing sql statements and converting them into objection code?

apologies in advance for the newbie questions.

**Comment by caschbre** [comment]
The answer is probably ... "it depends".  :-)

I'm fairly new to Objection and have quite a few queries written in PHP.  I'm migrating an app to node/javascript and Objection looked like a great library to use.  The way I've gone about this was to first create the Model's along with defining the relationships between them. It took me some time reading through the docs to understand how the queries work in this regard, but once I had them setup I found that Objection handled most of my queries out of the box.  There are a few edge-case queries that I haven't migrated yet but if Objection can't handle them easily then using "raw" is always an option.  

I found that attempting to use Objection Models first helped be better understand the library and the multitude of options it provides.  I also didn't want to get in a position where I was using Objection... but not really using Objection with all of the "raw" statements.  I'd end up having to move on to another feature and those would linger.
