### ISSUE TITLE
Alter Delete behavior on logical delete tables

### ISSUE THREAD

**Issue by n8eloy** [Vincit/objection.js#2064]
Hey all! I know it has been said a dozen times that `$beforeDelete` only works for instance deletes and not for the static `.query()` method, but is there any way of preventing the physical delete from happening at all by using one of the hooks or static Model functions? I'm trying to work on a sort of soft delete logic since some of my sensitive tables maintain their statuses through a `deleted_at` column. Are we able to "override" the delete routine for such tables for running an update instead of erasing data, without actually having to override the QueryBuilder delete method?

I'm currently doing it programmatically by simply using `.update()` instead of `.delete()` for such models, but having to rely on everyone remembering to use update instead of delete with the risk of erasing important records can become kinda of a bummer. Is there a better option?

Just an example of what I'm trying to achieve:
```js

export class MyModel extends Model {
  // $beforeDelete won't work for query(), just using it as an example
  $beforeDelete(myDeleteArgs) {
    MyModel.query()
      .update({ deleted_at: new Date.toISOString() })
      .where(myDeleteArgs);
      
      // Some magic that keeps delete from happening
      ...
  }
}

MyModel.query().delete().where({ id: 1 });

```

**Comment by devinivy** [comment]
You may have some luck [overriding the query-builder](https://vincit.github.io/objection.js/recipes/custom-query-builder.html#custom-query-builder-extending-the-query-builder) to change the behavior of `delete()`.  But there's also a great example in the docs showing how to use the static `beforeDelete()` hook to cancel the deletion and instead perform a patch [here](https://vincit.github.io/objection.js/guide/hooks.html#static-query-hooks).

**Comment by n8eloy** [comment]
> 
> 
> You may have some luck [customizing the query builder](https://vincit.github.io/objection.js/recipes/custom-query-builder.html#custom-query-builder-extending-the-query-builder) to change the behavior of `delete()`. But there's also a great example in the docs showing how to use the static `beforeDelete()` hook to cancel the deletion and instead perform a patch [here](https://vincit.github.io/objection.js/guide/hooks.html#static-query-hooks).

I didn't know there were static versions of the hooks. I'll be using the static `beforeDelete()` since it looks like a more elegant solution. Thank you for the quick response!

I'm leaving the solution as seen in the docs shall anyone stumble upon this issue in the future:

```js
export class MyModel extends Model {
  static async beforeDelete({ asFindQuery, cancelQuery }) {
    // Mark the row as logically deleted
    const [items] = await asFindQuery()
        .patch({ deleted_at: new Date.toISOString() });

    // Avoid physically deleting row
    cancelQuery(items);
  }
}

//
await MyModel.query().delete().where({ id: 1 });
```
