### ISSUE TITLE
Feature: porting to Deno

### ISSUE THREAD

**Issue by Alex-Aeg** [Vincit/objection.js#2067]
Any plans porting to [Deno](https://deno.land/)?

**Comment by kibertoad** [comment]
Most likely knex would need to be ported to deno first. Which is not planned either, but contributions to that end are most welcome.

**Comment by Alex-Aeg** [comment]
There is a port of knex called dex, that could be evaluated:

https://deno.land/x/dex@1.0.2

**Comment by elhigu** [comment]
```
