### ISSUE TITLE
Add possibility to select all fields in upsertGraph

### ISSUE THREAD

**Issue by vladshcherbin** [Vincit/objection.js#2068]
Hey 👋 

### What happened

I'm hitting select limitations of upsertGraph ([first report](https://github.com/Vincit/objection.js/issues/2058)).

When you provide fields to `upsertGraph`, only this fields are selected from database.

Here are the limits I faced:

1. Can't return directly updated model since it doesn't have all fields:

```js
const book = await Book.query()
  .upsertGraph({
    id: 1,
    title: 'New title'
  })
  .returning('*')

// no description since this field was not selected
console.log(book.description)
```

sql

```sql
SELECT "books"."id", "books"."title" FROM "books" WHERE "books"."id" IN (1)
```

Workaround is to use `upsertGraphAndFetch`.

2. Instance hooks don't have enough `old` values:

I'm using `$beforeUpdate` hook and I don't have all fields in `options.old`.

```js
async $beforeUpdate(options, queryContext) {
  await super.$beforeUpdate(options, queryContext)

  if (this.startDate || this.duration) {
    // no options.old.startDate or options.old.duration if they are not passed to upsertGraph
    this.endDate = addMinutes(
      this.startDate || options.old.startDate,
      this.duration || options.old.duration
    )
  }
}
```
 
 ### Suggested solution

Add an option for `upsertGraph` to select all fields from database.

This would not be a breaking change to anyone and would be a simple solution to faced limitations.

### Another solutions

`upsertGraph` select can be changed to wildcard by default.

This might be a breaking change and can have some drawbacks I don't know of.

### Packages

objection - 2.2.15

**Comment by vladshcherbin** [comment]
I'll add that I'm asking this because `upsertGraph` is actually saving me _a lot_ of relation code and this field selection limitation is blocking me from having a satisfying clean solution.

Hopefully I could express my limitations better this time and proposed a viable solution 😅

**Comment by koskimas** [comment]
You can already use a `{ fetchStrategy: 'Everything' }` upsert option, but it's not documented.

**Comment by vladshcherbin** [comment]
@koskimas yep, I've tried it and it selects everything 🥳

However, seems like I can't get all `options.old` from hooks (tried both `$beforeUpdate` and `beforeUpdate`), just fields passed to `upsertGraph`.

**Comment by koskimas** [comment]
Use the static hooks 🙂 They are meant to eventually replace the instance hooks anyway.

**Comment by vladshcherbin** [comment]
@koskimas hm, I believe with static `beforeUpdate` I would need to use `asFindQuery` to get `old` values which would create a new select query and kinda destroy my idea of a wildcard select to get all `old` values 🤔

I'm using instance hooks and `old` to calculate column value before update, similar to `createdAt` example from docs. I believe that's why `fetchStrategy` is not documented - since it fetches all fields, `old` values can be populated, right?

**Comment by koskimas** [comment]
No you don't. If the query was started for an instance, the args contain the instance(s).
