### ISSUE TITLE
Possible to flatten a relationMapping object when using withGraphFetched?

### ISSUE THREAD

**Issue by kennyhuynh125** [Vincit/objection.js#2072]
I'm wondering if it is possible to flatten a relationMapping object when using `withGraphFetched()`.

For example, let's say I have this Model:

```
class Person extends Model {
  static tableName = 'persons';

  static relationMappings = {
    animals: {
      relation: Model.HasManyRelation,
      modelClass: Animal,
      join: {
        from: 'persons.id',
        to: 'animals.ownerId'
      }
    },
    // some relational model
    relation2: {
      relation: Model.HasOneRelation,
      modelClass: Relation2,
      join: {
        from: 'rperson.relationId',
        to: 'relation2.id'
      }
    }
  };
}
```

Let's say `relation2` has two fields: `relation2Id` and `relation`.

If I use `withGraphFetched()`, each person would have an `animals` property and `relation2` prop.  `animals` would be an array of `Animal` and `relation2` would be an object like described below:

```
const person = Person.findOne({ ... }).withGraphFetched({ animals: true, relation2: true });
```

`person` would output something like this:

```
{
   id: 'some id',
   firstName: 'John',
   lastName: 'Smith',
   animals: [
      { ... pet 1 },
      { ... pet 2 }
   ],
   relation2: {
     relation2Id: 'id',
     relation: 'myrelation'
   }
}
```

My question is... Is it possible to do a query where for each `Person`, `relation2` is equal to the value of  `relation` but still get the `animals` array?

For example, I would want the output to be like so:

```
{
   id: 'some id',
   firstName: 'John',
   lastName: 'Smith',
   animals: [ // animals is still an array of animal objects
      { ... pet 1 },
      { ... pet 2 }
   ],
   relation2: 'myrelation' // instead of this being an object, I just want the value in the column relation
}
```

Also, I just assume that `withGraphFetched()` is the right method to use here, but I can also be completely wrong and not understand the different methods that Objection provides.

Any help is appreciated, thank you!

**Comment by koskimas** [comment]
You can use joins to do that:

```js
const person = Person.findOne({ ... })
  .withGraphFetched({ animals: true }).
  .joinRelated({ relation2: true })
  .select('person.*', 'relation2.someColumn as relation2SomeColumn' )
```

However, it's not possible to use the name `relation2` for the joined column. That name is reserved for the relation.

By the way, you should be using `BelongsToOneRelation` for `relation2` in your example if the `Person` model holds the foreign key.
