### ISSUE TITLE
Help required How to fetch all rows from objection.js

### ISSUE THREAD

**Issue by prashantnirgun** [Vincit/objection.js#2073]
Kindly excuse its hot an issue its help required, I didn't find the forum so I am seeking help,
 am using Knex.js & Objection.js, I want to display country drop down so I need all rows but it was only returning me 10 rows. How do I override the pagination functionality?

Is there any params I can set in url localhost:3031/countires?pages='All', there should be some easy way. I am using "knex": "^0.21.1", "objection": "^1.6.11" version. 
File : default.js
```
"paginate": {
    "default": 10,
    "max": 2000
  },
```
For time being I just made the following changes in src\serivices\countries\countires.services.js
```
module.exports = function (app) {
  const options = {
    Model: createModel(app),
    //paginate: app.get("paginate"),
    paginate: {
      default: 0,
      max: 0,
    },
  };

  // Initialize our service with any options it requires
  app.use("/countries", new Countries(options, app));
```

**Comment by koskimas** [comment]
The code you posted here is not related to objection. That code is some project specific helper code or part of some other library's interface. There's no default pagination in objection. You need to specifically call `page` or `range` method for the query builder, and that could be overridden by just removing the `page` or `range` call.
