### ISSUE TITLE
Best practice to list attributes for frontend dev

### ISSUE THREAD

**Issue by sehmaschine** [Vincit/objection.js#2074]
Just starting out with Objection and it looks great so far (coming from Python/Django and then Prisma). But since a `Model` is simply initialized with a `tableName`, how does the frontend developer knows which attributes are available? Is there an easy and straightforward way to list all attributes for all `Models`? Or should we use comments in order to make that clear?

This might be a silly question, but with the current setup, our frontend (javascript) developer needs to look into Python code in order to figure out what she can actually use with a given Model.

**Comment by koskimas** [comment]
Look at the DB schema? There are plenty of good tools for that. If you don't pass all columns from the DB to the frontend, then the column definitions in the code wouldn't help much.

Can I also suggest using openapi for documentation or even autogenerating code.

Also if you use typescript, you can (and need to) define the columns in the models.

One more option: define the jsonSchema property.
