### ISSUE TITLE
Modifiers from a plugin result in Unable to determine modify function

### ISSUE THREAD

**Issue by caschbre** [Vincit/objection.js#2075]
I've created a custom plugin that adds some modifiers to the model.  The plugin is pretty basic. It essentially reads the jsonSchema properties and creates a modifier "defaultFields" that automatically adds those columns to the query select. This is done because the table may have more fields than defined in the jsonSchema.

```javascript
const ObjectionDefaultFields = (_config) => {
  return (Model) => {
    return class extends Model {
      static get modifers() {
        const { ref } = this;

        return {
          ...Model.modifers,

          defaultFields: (query) =>
            query.select(...this.jsonSchema.properties.map(ref)),
        };
      }
    };
  };
};
```

```javascript
const { compose, Model } = require('objection');

const mixins = compose(
  ObjectionDefaultFields({})
);

class UserModel extends mixins(BaseModel) {
  static get tableName() {
    return 'users';
  }

  static get idColumn() {
    return 'uid';
  }

  static get jsonSchema() {
    return jsonSchema; // Note this is defined, just not shown here.
  }

  static get modifiers() {
    return {
      ...BaseModel.modifiers,

      filterBySessionToken: (query, token) =>
        query.findOne(
          UserModel.relatedQuery('sessions').where(
            token['column'],
            token[token['column']]
          )
        ),
    };
  }
}
```

When I run the following, I get the error message "Unable to determine modify function from provided value: \"defaultFields\"."

Doing a console.log(UserModel.modifiers) does show the 'defaultFields' as a modifier.

```javascript
const user = UserModel.query().modify('defaultFields').findById(userId);
```

If I add 'defaultFields' to the UserModel modifiers method, it does work.

I dug through some of the objectionjs code and from what I can tell, it seems to break down in createModifiers().  The modelClass.getModifiers() doesn't find the plugin added modifiers.

I could also easily be implementing the custom plugin incorrectly.

**Comment by koskimas** [comment]
Use `this.modifiers` instead of `BaseModel.modifiers`. The BaseModel doesn't have the mixins.

**Comment by caschbre** [comment]
@koskimas I gave that a shot but unfortunately still get the same error.  Any other ideas?

**Comment by koskimas** [comment]
You did it wrong, the code above is the correct fix. It's not related to objection, but basic ecmascript. Maybe if you posted the real code instead of something made up, I could point your mistake to you.

**Comment by caschbre** [comment]
Ok, I'll give it another shot and strip out other logic / plugins I have in place.  Thanks for the quick response!

**Comment by caschbre** [comment]
@koskimas Just wanted to report back that a syntax typo on my end was causing the issue.  The solution you provided worked great. Thanks!
