### ISSUE TITLE
Querying Json fields with question marks

### ISSUE THREAD

**Issue by from-nibly** [Vincit/objection.js#2077]
Please read the instructions linked below before opening an issue.

I have a json field in my database that stores answers to survey questions. The keys are the question themselves, and the values are the responses. I allow my users to pick what the name of the question is and often they put question marks in the question. I'm trying to pivot this data into a CSV file that would include 1 column for every question/answer in the json blob.

I'm struggling with the question mark characters though because it looks like a combination of objection and knex are interpreting those question marks as something that needs to be replaced.

here is the relevant code.

```typescript
 //questions is a string[]
  const result = await MyModel.query()
    .select([
      'created_at',
      'contact.email as contact_email',
      ...questions.map(question => {
        const escapedQ = question.replace(/\?/g, '\\\\?');
        return raw(`answers->"${escapedQ}" as "${escapedQ}"`);
      }),
    ])
    .where('relation_id', '=', relationID)
    .debug();
```

The result is that the json column query either includes the values of some variables (like the relationID one), or what looks like a replacement variable "$1" etc.

I've tried using raw pictured above and ref like this

```typescript
return ref(`answers:["${escapedQ}"]`).castText().as(escapedQ);
```

I've also tried adding/removing slashes on the question mark escape.

Any help with understanding how this works would be greatly appreciated.

**Comment by from-nibly** [comment]
Ok well it looks like I was adding too many slashes? It looks like it works if I do.

```typescript
const escapedQ = question.replace(/\?/g, `\\?`)
```

However, I'm also having issues with periods "." in the alias.

It shows up as

```
as "what type of food do you like".""
```
or
```
as "what type of food do you like".""
```

in the query.

**Comment by from-nibly** [comment]
It looks like if I remove the `as` the query executes? but since the columns are not aliased they all come back as `?column?` to which objection.js merges all the columns into one value.

**Comment by elhigu** [comment]
The part of query in `.as(...)` is considered as an identifier, which is handled by knex/objection with automatic parsing and quoting, so periods -marks has special meaning in those. 

if you call `.as(raw('anything'))` it might go through without knex trying to parse it.
