### ISSUE TITLE
Change useLimitInFirst to true by default in v3

### ISSUE THREAD

**Issue by vladshcherbin** [Vincit/objection.js#2080]
Hey 👋 

This is the confirmed proposal which was scheduled for v2 but was probably forgotten. Let's see if it can hit v3 🥳 

Related - https://github.com/Vincit/objection.js/issues/1302#issuecomment-502491894

**Comment by koskimas** [comment]
This didn't make it to 3.0. This change as a large amount of consequences, both in objection test set and in user code. I simply didn't have time to do and document all that. The 3.0 release took forever and I just had to get it out.
