### ISSUE TITLE
Model relations fail to join when using string columns which may have different case values

### ISSUE THREAD

**Issue by johnatzark** [Vincit/objection.js#2081]
As the title suggests when cases do not match on a string based relations, the join will fail.
While "technically" this is correct, it would be super nice to have an option to specify the use of LIKE or ILIKE operators in the relation comparison.

maybe:
specify a compare operator to use
join: {
  from: 'TableA.email',
  to: 'TableB.email',
  compareMethod:'like'
},

or

specify your own callback transform code to transform the data in javascript
join: {
  from: 'TableA.email',
  to: 'TableB.email',
  transform: (value)=>{return value.toLowerCase()}
},

I am using version ^2.1.2

In Postgres I have 2 tables

TableA:
id | email | firstName | lastName
___________________________
abc123, john@foo.com, John, Smith

TableB:
id | email | profilePhoto
_____________________
abcxyz, JOHN@FoO.com, http://www.google.com/somePhoto.png

I have an Objection Model like:

const { Model } = require('objection');
class TableA extends Model {
  static get tableName() {
    return 'TableA';
  }
  
    static get relationMappings() {
    return {
      userPhoto: {
        relation: Model.HasOneRelation,
        modelClass: require('../users/TableB'),
        join: {
          from: 'TableA.email',
          to: 'TableB.email',
        },
      },
    };
  }
  
}

**Comment by devinivy** [comment]
I'd recommend creating a case-insensitive collation and apply it to those `email` columns.  This may be a little bit more natural for both postgres and objection, and will help enforce constraints too (e.g. if `email` is a primary key or otherwise unique up to casing).

**Comment by johnatzark** [comment]
Thanks for the feedback, 
I will get with my devops team and see about getting that done
