### ISSUE TITLE
JSONSchema Validator fails when using format options

### ISSUE THREAD

**Issue by NurfitraPujo** [Vincit/objection.js#2082]
### Description
Objection v3 returning error `unknown format "date" ignored in schema at path "#/properties/tanggalLahir"` when using JSON Schema Builder attributes format option

### Example
```
const PersonSchema = SchemaBuilder.emptySchema()
  .addString('id')
  .addString('fulllName')
  .addString('nickname', {}, false)
  .addString('bornDate', { format: 'date' })
```
### Package.json
```
"objection": "^3.0.0-alpha.4",
"@serafin/schema-builder": "^0.14.2",
```

### Proposed Solution
When I look up at the objection dependencies, i notice it uses the latest version of ajv is ^8. After reading through ajv documentation and issues, it was apparent that ajv version 7 above is implementing breaking changes. They now implement the JSON format specifications in separate module `ajv-formats`. Looking from the available issues there is solution for this, it was implemented like this
```
	const AJV = require('ajv').default;
	const addFormats = require('ajv-formats').default;

  	const ajv = new AJV();
  	addFormats(ajv);
```

 I think I will just  modify the AjvValidator.js directly and patch it using patch-package to automate the patching process. Can anyone help me how to implement (adding the ajv formats) this ? Thank you

**Comment by koskimas** [comment]
See this section in the docs https://vincit.github.io/objection.js/api/types/#class-validator

**Comment by NurfitraPujo** [comment]
Hello @koskimas thank you for your answer, i have a question how can I override the self.ajv in onCreateAjv function?
\

**Comment by koskimas** [comment]
Why do you need to override it? You can mutate it:

```js
const ajvKeywords = require("ajv-keywords")

...

onCreateAjv(ajv) {
  ajvKeywords(ajv)
}
```

**Comment by NurfitraPujo** [comment]
Weird.. this afternoon i tested it returns an error, then I just tried it again it was successful. Maybe I forgot to extend the BaseModel instead of Model in one of my models before. Thank you @koskimas, and sorry for the inconvenience
