### ISSUE TITLE
Insert to model with get virtualAttributes cause Hapi to return error

### ISSUE THREAD

**Issue by jprumekso** [Vincit/objection.js#2083]
First, let me thank you for such a wonderful orm. With objection I can model a complex data and retrieve it pretty easily. :)

I don't know if it's objection's issue or rather a hapi issue. I have Bill Model with several virtualAttributes. When I perform insert or insertAndFetch to this model I know it was succesful (the data goes through database also I can console.log the result), but the handler return 'internal server error'. However, if I delete the virtualAttribute related code, the handler working properly. 

Modela
```js
class Bill extends Model {
  static get tableName() {
    return 'bill';
  }

  static get relationMappings() {
    return {
      payments: {
        relation: Model.HasManyRelation,
        modelClass: path.join(__dirname, 'Payment'),
        join: {
          from: 'bill.id',
          to: 'payment.billId'
        }
      }
    }
  }

  static get virtualAttributes() {
    return ['totalPayment'];
  }

  get totalPayment() {
    return this.payments.reduce((acc, payment) => acc + payment.amount, 0)
  }
}
```

Route handler:
```js
  server.route({
    method: "POST",
    path: "/bill",
    handler: async (request, h) => {
      try {
        const billData = request.payload;
        const newBill = await Bill.query().insertAndFetch(billData);
        console.log('output', newBill); // always work
        return newBill; // only work if I delete the get totalPayment()
      } catch (error) {
        // none of these code get executed even if hapi return internal server error
        console.log(error);
        throw error;
      }
    }
  });
```

**Comment by koskimas** [comment]
`this.payments` is undefined. You need to check for it in the totalPayment method

**Comment by jprumekso** [comment]
Oh i see. Alright, thank you so much for your generous support.
