### ISSUE TITLE
relationMappings.<relationName>.join.to accepts snake_case and camelCase when used with knexSnakeCaseMappers()

### ISSUE THREAD

**Issue by Prellenium** [Vincit/objection.js#2084]
Hi,

today my colleague and i have encountered a weird "bug". We are using knexSnakeCaseMappers():

```javascript
const knex = createKnexInstance({
  // ...
  ...knexSnakeCaseMappers(),
})

Model.knex(knex)
```

If one create a relation mapping as follows, queries work without problems even though there is snake_case in `relationMappings.logo.join.to`.

```javascript
class Person extends Model {
  // ...

  static tableName = 'persons'
  
  static relationMappings = {
    logo: {
      relation: Model.HasOneRelation,
      modelClass: Image,
      join: {
        from: `persons.id`,
        to: 'images.snake_case_person_id', // can be 'images.snakeCasePersonId' but doesn't have to 
      },
    },
  }
}

const person = await Person.query().findById(1)
const logo = await person.$relatedQuery('logo') //works
```

On the other hand this does not work:

```javascript
class Person extends Model {
  // ...

  static tableName = 'persons'
  
  static relationMappings = {
    logo: {
      relation: Model.BelongsToOneRelation,
      modelClass: Image,
      join: {
        from: 'persons.snake_case_image_id', // has to be 'persons.snakeCaseImageId'
        to: `images.id`,
      },
    },
  }
}

const person = await Person.query().findById(1)
const logo = await person.$relatedQuery('logo') // returns undefined
```

Apparently `relationMappings.logo.join.from` gets **always** translated by knexSnakeCaseMappers() while `relationMappings.logo.join.to` can be snake_case **OR** camelCase. Both options work.

I know that this is rather a minor "bug" but it is some kind of weird behavior. So far we've only used `Model.HasOneRelation` and everything has worked fine even though we've used snake_case in relationMappings. Today we've started to use `Model.BelongsToOneRelation` and it took us some time to come up with the actual problem because what worked before suddenly didn't work in a different context.

 I'm also not 100% sure if this is a problem of objection.js or knex.js and if there is a possible "fix" at all.

Anyway, thank you in advance!

**Comment by koskimas** [comment]
This is because `snakeCase('snake_cased_word') === 'snake_cased_word'`. There's really nothing we can do about this. The reason it work in one direction, but not the other is that the column name in the result row is parsed from the same `'persons.snake_case_image_id'` string and it's wrong. The relation works when the internal code doesn't need to access the column in the row (`HasOneRelation`) but doesn't when it needs to (`BelongsToOneRelation`)
