### ISSUE TITLE
Handling/preventing UnallowedRelationErrors

### ISSUE THREAD

**Issue by EmileSpecs** [Vincit/objection.js#2086]
I use `eager` to pull data including relational data from the DB for use in the client.

The relational data included includes data 2 or 3 levels deep (relationally).
The `allowedGraph` property might allow certain relational data to be upserted with the root model data.

Since the data on the client is fully populated, the entire object might be sent to the server in an upsert operation.

I then get the error `trying to upsert an unallowed relation` because there is relational data that's not been included in the `allowedGraph` option.

Is there no other way to resolve this than to clean each request's data before it's validated?
Is there no way to simply ignore relational data that's not included in the `allowedGraph` option?

**Comment by koskimas** [comment]
Unfortunately there are no tools for stripping unwanted relations from the request like that. You need to do it by hand or expand the allowGraph expression to include them

**Comment by Artaud** [comment]
I've been looking for a way to strip the unallowed relations from an object that is sent to the server and ended up implementing a generic solution that could be prepended before the actual upsert call.

I'm using FeathersJS so there are some specifics to that but should be easily adjustable to other environments.

It checks for any objects in your incoming data and crosschecks them recursively with your allowedUpsert option. 
It hasn't been tested much so don't trust this blindly :)

```
export const stripUnallowedUpsertRelationsHook = () => async (ctx: HookContext) => {
  doStripUnallowedUpsertRelations(ctx.data, ctx.service.allowedUpsert)
}

function isInAllowedUpsert(allowedUpsert: any, currentPath?: string): boolean {
  if (!currentPath) return true
  return !!allowedUpsert.node[currentPath]
}

function doStripUnallowedUpsertRelations(data: any, allowedUpsert: RelationExpression<ClientSession>, currentPath?: string) {
  for (const prop in data) {
    if (!!data[prop] && typeof data[prop] === 'object') {
      if (isInAllowedUpsert(allowedUpsert, currentPath) || !currentPath) {
        doStripUnallowedUpsertRelations(data[prop], allowedUpsert, currentPath ? `${currentPath}.${prop}` : prop)
      } else {
        data[currentPath] == null
        delete data[currentPath]
      }
    }
  }
}
```
