### ISSUE TITLE
How to create queries with dynamic `where` clauses?

### ISSUE THREAD

**Issue by kennyhuynh125** [Vincit/objection.js#2088]
Hi all,

I am wondering if it is possible to create a dynamic query with different where clauses. My situation is that I have an endpoint that could pass in different statuses, different types, etc.

For example, the base endpoint is: `/api/my-endpoint` and if this was called, my query would be like so (lets call this the base query)

```
Model.query();
```

However, I can add query parameters like so: `/api/my-endpoint?status=Success&type=Red`, and I would want my query to look something like this:

```
Model.query().where('status', 'Success').andWhere('type', 'Red');
```

However, I wouldn't want to hardcode it, I would want to do something like so:

```
if (status) {
 // add where clause to base query
}

if (type) {
  // add another where clause to base query
}

// any other query parameters
```

Is there a way to do this in Objection?

Thanks!

**Comment by koskimas** [comment]
The query is only executed once you `await` it. Before that, it remains an instance of QueryBuilder. The QueryBuilder class is mutable and each `where` call mutates the query. You don't need to assign the return value back to the `query` variable, but you can if you want (`where` always returns `this`)

```js
const query = Model.query()

if (status) {
  query.where('status', status)
}

if (type) {
  query.where('type', type)
}

const result = await query;
```

You can make the last line more explicit by calling `execute`, but it's not needed:

```js
const result = await query.execute();
```
