### ISSUE TITLE
Delete/Update Cascade

### ISSUE THREAD

**Issue by lvffilho** [Vincit/objection.js#209]
Is there any way to make a update or delete cascade from Owner Model?

Base
```
Owner {
  id: '1',
  name: 'Teste 123',
  create_date: '01-01-2010',
  update_date: '01-01-2010',
  children: [
   {
     id: '1',
     name_complete: 'Teste One',
     active: true }, 
   {
     id: '2',
     name_complete: 'Teste One',
     active: true }, 
 ]}
```

When i remove a children from the list and update Owner model will delete chilndren removed from model? Like:

```
Owner {
  id: '1',
  name: 'Teste Update',
  create_date: '01-01-2010',
  update_date: '01-01-2010',
  children: [
   {
     id: '1',
     name_complete: 'Teste One',
     active: true }]}
```

**Comment by koskimas** [comment]
Unfortunately there is no graph/cascade update available at the moment.

**Comment by fl0w** [comment]
If you're using PostgreSQL you could `cascade on delete` in table schema, maybe that would work for you? I'm sure MySQL has equivalent options (I'm just not familiar enough with it).

**Comment by lvffilho** [comment]
For delete its easier... cascade on delete resolve my problem. But update dont. I have to merge both model and applay delete on diff

**Comment by koskimas** [comment]
Let's continue in #211
