### ISSUE TITLE
Documentation doesn't explain recursive models in `withGraphFetched`.

### ISSUE THREAD

**Issue by pulli23** [Vincit/objection.js#2091]
Well as per title, the explanation for `.^` notation when fetching a graph isn't anywhere on the documentation page (https://vincit.github.io/objection.js/api/query-builder/eager-methods.html#withgraphfetched).

It can only be found somewhere deep inside the query examples. ( https://vincit.github.io/objection.js/guide/query-examples.html#eager-loading ).

I think such an "unique" feature would demand some explanation and limitations.

**Comment by koskimas** [comment]
It's there. No need to demand more free work from other people.
