### ISSUE TITLE
Monkey Patching Objection where, findOne etc

### ISSUE THREAD

**Issue by chuksgpfr** [Vincit/objection.js#2092]
Hi, is there a way to make my model not to select a user with a flag (let's say banned = true), when selecting with "where, findById or findOne" etc.

**Comment by devinivy** [comment]
Yeah, you can get objection to do that with some customization.  Here's how you [customize a model's query builder](https://vincit.github.io/objection.js/recipes/custom-query-builder.html#custom-query-builder-extending-the-query-builder), and here's an example of how someone has used this to [apply default criteria to find queries](https://github.com/ackerdev/objection-softdelete/blob/6eb4cef2a1eee987fb95ddded4e1e035e5eeec4d/index.js#L15-L19).
