### ISSUE TITLE
Should asFindQuery() in hooks and toFindQuery() clear RunAfterOperation entries?

### ISSUE THREAD

**Issue by lehni** [Vincit/objection.js#2093]
I noticed that `asFindQuery()` calls both `toFindQuery()` and `clearWithGraphFetched()`. That means that any `runAfter()` operation that was added to it that expects a graph to be fetched breaks once you use `asFindQuery()` in a hook, since the resulting query doesn't load the graph anymore, but still runs the `runAfter()` operations that were added to the original query. 

It seems to me that `asFindQuery()`, or perhaps even  `toFindQuery()` should also clear the `runAfter()` operations?

**Comment by lehni** [comment]
The workaround currently is to use `asFindQuery().clear('runAfter')` but it seems strange to have to do so. So I've currently overridden in `QueryBuilder`:

```js
  toFindQuery() {
    return super.toFindQuery().clear('runAfter')
  }
```

**Comment by koskimas** [comment]
The functions installed using runAfter could just as well be meaningful in a find query and removing them would be wrong. It's just your use case where they aren't useful.

**Comment by lehni** [comment]
I think that's something that will happen quite often with `runAfter()`… isn't `asFindQuery()` supposed to give you a pristine find query that you can use to expand it for other purposes within the hooks? I would expect such a "pristine" query not to call any `runAfter()`callbacks.
