### ISSUE TITLE
Feature request: Customizable strategies for withGraphFetched

### ISSUE THREAD

**Issue by laurisvan** [Vincit/objection.js#2096]
Our GraphQL + Objection.js stack utilises eager (and in near future withGraphFetched) queries for building object graphs. When eager fetching children for thousands of items, the resulting `WHERE IN (?, ?, ?, ...)` queries get pretty heavy for the postgres driver, and we can see from query statistics that actually majority of the time is spent in encoding the parameters (and in excess ClientRead in postgres internal statistics).

We have a similar case with our .whereIn queries and have written a custom .whereInLarge method for our custom query builder. 
This method actually decodes the thousands of input parameters into one string, e.g. `WHERE col IN (?, ?, ?, ...)` is replaced by `WHERE col = ANY('{?}')` and this empiricallly performs much better with hundreds/thousands of inputs.

How to do something with graph queries? How might we create a custom .withLargeGraphFetched method or tune the strategy on how withGraphFetched transforms the eager query into SQL?

**Comment by laurisvan** [comment]
Thanks, @koskimas this sounds clear and simple!

**Comment by laurisvan** [comment]
For reference, for anybody that wants to do sth similar:

```
export class MyQueryBuilder<M extends Model, R = M[]> extends QueryBuilder<M, R> {
  static WHERE_IN_ANY_THRESHOLD = 5

  ArrayQueryBuilderType!: MyQueryBuilder<M, M[]>
  SingleQueryBuilderType!: MyQueryBuilder<M, M>
  NumberQueryBuilderType!: MyQueryBuilder<M, number>
  PageQueryBuilderType!: MyQueryBuilder<M, Page<M>>

  // Note: Array function used simply to make this work with current TS typedefs
  whereIn: WhereInMethod<this> = (...args) => {
    if (Array.isArray(args[1]) && args[1].length > MyQueryBuilder.WHERE_IN_ANY_THRESHOLD) {
      return super.where(args[0], raw(`ANY (?)`, `{${uniq(args[1]).join(',')}}`))
    }

    return super.whereIn.apply(this, args)
  }

  whereNotIn: WhereInMethod<this> = (...args) => {
    if (Array.isArray(args[1]) && args[1].length > MyQueryBuilder.WHERE_IN_ANY_THRESHOLD) {
      return super.whereNot(args[0], raw(`ANY (?)`, `{${uniq(args[1]).join(',')}}`))
    }

    return super.whereNotIn.apply(this, args)
  }

  orWhereIn: WhereInMethod<this> = (...args) => {
    if (Array.isArray(args[1]) && args[1].length > MyQueryBuilder.WHERE_IN_ANY_THRESHOLD) {
      return super.orWhere(args[0], raw(`ANY (?)`, `{${uniq(args[1]).join(',')}}`))
    }

    return super.orWhereIn.apply(this, args)
  }

  orWhereNotIn: WhereInMethod<this> = (...args) => {
    if (Array.isArray(args[1]) && args[1].length > MyQueryBuilder.WHERE_IN_ANY_THRESHOLD) {
      return super.orWhereNotIn(args[0], raw(`ANY (?)`, `{${uniq(args[1]).join(',')}}`))
    }

    return super.orWhereNotIn.apply(this, args)
  }
}
```

**Comment by rgoomes** [comment]
@laurisvan please check my issue at #2175. Did you managed to make this work with `withGraphFetched`? Maybe there is a specific way to set the custom query builder that I'm not aware.

**Comment by laurisvan** [comment]
@rgoomes We haven't had a chance to migrate to Objection v3 yet and are still running v2. But we're about to do it (maybe this weekend), so I'll keep you posted.

**Comment by rgoomes** [comment]
@laurisvan thanks for the update. The situation was already clarified in #2175. With `withGraphFetched` you have to override `whereInComposite` instead. That is what `withGraphFetched` apparently uses.
