### ISSUE TITLE
$toDatabaseJson doesn't work with objection's `raw` and `fn`.

### ISSUE THREAD

**Issue by ialexi-bl** [Vincit/objection.js#2098]
Objection version 2.2.15

Returning `raw` or `fn` from `$toDatabaseJson` function for one of the fields causes it to be interpreted as a simple object, not a raw part of query, and yields a query as such

```
"insert into ... (...) values ({"_sql":"FROM_UNIXTIME(1630522329)","_args":[],"_as":null})
```

Which, evidently, is an SQL error. The code that produces this query:

```
import {fn} from 'objection'

// ...
$toDatabaseJson() {
  const json = super.$toDatabaseJson()
  if(json.timestamp) json.timestamp = fn('FROM_UNIXTIME', Math.floor(this.timestamp / 1000))
  return json
}
```

However using `knex.raw` works fine:

```
import knex from './knex'

// ...
$toDatabaseJson() {
  const json = super.$toDatabaseJson()
  if(json.timestamp) json.timestamp = knex.raw(`FROM_UNIXTIME(${Math.floor(this.timestamp / 1000)})`)
  return json
}
```

I expect both code snippets to produce the same result.

**Comment by koskimas** [comment]
Move it before the super call.

**Comment by ialexi-bl** [comment]
Before super call that is `this.timestamp = fn('FROM_UNIXTIME', this.timestamp); super.$toDatabaseJson();`? But I can't do that because I'm using typescript and return type of `fn` is not assignable to `timestamp` of type `number`. And I don't want to change the type of `timestamp` because it doesn't make sense
