### ISSUE TITLE
Is it possible to join a related table to the records within a withGraphJoined call?

### ISSUE THREAD

**Issue by iandoesallthethings** [Vincit/objection.js#2099]
So I have 2 tables/models (User, WorkOrder) who are many-to-many related through a bridge model, Assignment. I have a situation where I'm fetching a WorkOrder by ID, and I want to get a list of its assigned users.
```js
const workOrder = await WorkOrder
  .query()
  .findById(workOrderId)
  .withGraphJoined('users as assignedUsers')
```

This actually works great, and I end up with a clean JSON object with an assignedUsers property that contains an array all of the assigned users! 
```js
{
  id: 10,
  name: 'Abel Luna',
  location: 'Unde officia eos do',
  description: 'Alias aut dolores ma',
  startDate: null,
  endDate: null,
  projectId: 1,
  createdAt: 2021-09-02T23:01:32.054Z,
  users: [
    { id: 1, firstName: 'Bob', lastName: 'Zimburg' },
    { id: 2, firstName: 'Jeff', lastName: 'Berlin' },
   ]
}

```

But I also have some meaningful data stored on the Assignment itself (acceptedAt, declinedAt, etc). Is there a way to join the users in that array with their associated assignments? 

I'd love to end up with 
```js
{
  id: 10,
  name: 'Abel Luna',
  location: 'Unde officia eos do',
  description: 'Alias aut dolores ma',
  startDate: null,
  endDate: null,
  projectId: 1,
  createdAt: 2021-09-02T23:01:32.054Z,
  users: [
    { id: 1, firstName: 'Bob', lastName: 'Zimburg', acceptedAt: 2021-09-02T23:03:53.900Z, declinedAt: null, status: 'accepted' },
    { id: 2, firstName: 'Jeff', lastName: 'Berlin', acceptedAt: null, declinedAt: null, status: 'pending' },
   ]
}

```
Where acceptedAt, declinedAt are attributes on Assignments, and status is a virtual attribute. I tried to use modifyGraph, but it didn't seem to do anything.

Any ideas? Or is there a better way to do this?

**Comment by Sultannis** [comment]
You can use join table extra properties. Here is the link from documentation:
(https://vincit.github.io/objection.js/recipes/extra-properties.html#join-table-extra-properties) 

You will have to modify your relation mappings by adding "extra" object where you will need to specify the Assignments column names.
