### ISSUE TITLE
knexSnakeCaseMappers - defining a primary key without 'constraint name' leads to TypeError

### ISSUE THREAD

**Issue by DavidPVaz** [Vincit/objection.js#2101]
Knex version: 0.95.11
Objection version: 2.2.15 (also tried ^3.0.0-alpha.4)
Sqlite version: 5.0.2

What are you doing?
 - Trying to execute a simple migration. The code itself is quite simple and can be checked [here](https://runkit.com/embed/fis3tpx7pa4y)
 
What is happening? 
- With knex `0.21.18`, using `knexSnakeCaseMappers` on Knex Config this code executes as expected 
 ```js
 exports.up = function (knex) {
    return knex.schema.createTable('tablename', table => {
        table.integer('number').primary();
        table.string('description');
    });
};
```
 But after the update to knex `0.95.11` the above code fails with the error 
```bash
TypeError: Cannot read property 'lastIndexOf' of undefined
    at Function.get (.../backend/server/node_modules/knex/lib/knex-builder/make-knex.js:43:26)
    at Object.exports.up (.../backend/server/db/migrations/development/migrationfile.js:2:17)
    at .../backend/server/node_modules/knex/lib/migrations/migrate/Migrator.js:521:40
```
 If I pass an argument to `.primary('constraint name')` it works, but I shouldn't have to pass anything.
 It's happening in here but I still haven't figure it out why.
```bash
objection/lib/utils/identifierMapping.js 
```
```js
function mapLastPart(mapper, separator) {
    return (str) => {
        const idx = str.lastIndexOf(separator);
        const mapped = mapper(str.slice(idx + separator.length));
        return str.slice(0, idx + separator.length) + mapped;
    };
}
```

**Comment by koskimas** [comment]
You shouldn't use knexSnakeCaseMappers in the migrations. There's a warning in the docs. Knex doesn't fully support that.
