### ISSUE TITLE
Does Objection.js handle batch inserts like knex.batchInsert?

### ISSUE THREAD

**Issue by eugene-kim** [Vincit/objection.js#2103]
I'm running into an issue when attempting to insert thousands of rows ~40K into a table in a Postgres DB. I believe this is an issue that's arising because there are over 65535 parameters in the prepared statement.

My question: What's the recommended approach to handling large inserts like this in Objection? Should I use `knex.batchInsert`?

The error I receive:

```json
{
    "name": "Error",
    "stack": "Error: insert into \"desynced_airtable_records\" (\"base_id\", \"created_at\", \"desynced_at\", \"id\", \"reason\", \"shopify_entity_id\", \"updated_at\") values ($1, $2, $3, $4, $5, $6, $7), ($8, $9, $10, $11, $12, $13, $14), ($15, $16, $17, $18, $19, $20, $21),
......
($67194, $67195, $67196, $67197, $67198, $67199, $67200) returning \"id\" - bind message has 1664 parameter formats but 0 parameters",
    "nativeError": {
        "code": "08P01",
        "file": "postgres.c",
        "line": "1662",
        "name": "error",
        "length": 121,
        "routine": "exec_bind_message",
        "severity": "ERROR"
    }
}
```

The [documentation around insert()](https://vincit.github.io/objection.js/api/query-builder/mutate-methods.html#insert) mentions batch inserts:

> Batch inserts only work on Postgres because Postgres is the only database engine that returns the identifiers of all inserted rows. 

But it's unclear whether this simply refers to inserting multiple rows or if if it's referring to being able to insert many rows without being limited to the prepared statement parameter limit.

I searched `batchInsert` in the Objection repository and couldn't find anything.

"objection": "^2.2.15",
Postgresql 12

I'm happy to provide more information if necessary.

Thank you!

**Comment by koskimas** [comment]
I think you already have your answer if you ran into errors don't you? It's pretty trivial to split the list of items into chunks and insert the chunks one by one or in parallel.

**Comment by eugene-kim** [comment]
@koskimas , I have a way to proceed. I was just curious if there was a dedicated method in Objection to handle this.

Cheers and thanks again for the wonderful library!
