### ISSUE TITLE
Typescript complains about `undefined` value in `.where` clause

### ISSUE THREAD

**Issue by ionizer** [Vincit/objection.js#2104]
I have a small problem when using this package on Typescript.

```
await MyModel.query()
    .skipUndefined()
    .where('col1', undefined) // Skips this WHERE query correctly, but Typescript complains
    .where('col2', null); // Type correct, but produces `WHERE "col2" IS NULL` (not skipped)
```

Here is the Typescript error with `col1` by passing `undefined` to the second argument:
```
No overload matches this call.
  Overload 1 of 10, '(col: "col1" | "col2", expr: Expression<PrimitiveValue>): QueryBuilder<...>', gave the following error.
    Argument of type 'undefined' is not assignable to parameter of type 'Expression<PrimitiveValue>'.
      Type 'undefined' is not assignable to type 'Expression<PrimitiveValue>'.
  Overload 2 of 10, '(col: ColumnRef, expr: Expression<PrimitiveValue>): QueryBuilder<MyModel, MyModel[]>', gave the following error.
    Argument of type 'undefined' is not assignable to parameter of type 'Expression<PrimitiveValue>'.ts(2769)
```

This seems fixed by adding `undefined` to the union type `PrimitiveValue`. However I don't know what are the exact side effects of adding it and therefore unsure whether it will need further changes/adjustments or not. Does anyone mind checking this out?

Package versions:
objection: ^2.2.15
knex: ^0.21.21
pg: ^8.7.1
typescript: ^4.4.2

**Comment by koskimas** [comment]
undefined is not allowed by default. It's only allowed when you use `skipUndefined`. To fix this, we would need have a different set of types IF `skipUndefined` is called. That's way too much work for such a small (and quite frankly a bad) feature. I'd recommend not using `skipUndefined` at all. Consider this query

```
Person.query().delete().where('id', someId).skipUndefined()
```

Now if you accidentally pass undefined in `someId` you end up deleting the whole table.

`skipUndefined` is a legacy method that should be removed from the API.
