### ISSUE TITLE
Get Parent from related query builder

### ISSUE THREAD

**Issue by mlazuardy** [Vincit/objection.js#2108]
is it possible to access parent model from related query builder ? 

for example

```
blog.$relatedQuery('tags').sync(ids);
```
while `sync` is my custom query builder act like `relate` method

In query builder

```
sync(ids: any[]) { 
//
}
```

in the `sync` method on query builder , `this` will refer to `tags` right? and can i access the blog model / query too ?

because i `console.log` the `this.context()` there is a `_relatedQueryFor` property there but i dont know how to access it

**Comment by koskimas** [comment]
There's no way to do that I'm afraid.
