### ISSUE TITLE
Invalid `next` npm version tag

### ISSUE THREAD

**Issue by spridev** [Vincit/objection.js#2109]
According to the [installation guide](https://vincit.github.io/objection.js/guide/installation.html) and to this [comment](https://github.com/Vincit/objection.js/issues/2012#issuecomment-881352171), the `next` npm version tag should refer to the `3.0.0-alpha.4` version. 

Currently, it refers to the [latest version](https://www.npmjs.com/package/objection?activeTab=versions) (`2.2.16`).

**Comment by koskimas** [comment]
Whoops, thanks for reporting this. It's now fixed
