### ISSUE TITLE
Best place for fallback to NULL if value is empty string

### ISSUE THREAD

**Issue by marko-x** [Vincit/objection.js#2110]
Hi,

If we have a table with some text fields (postgresql):

```typescript
await knex.schema.createTable("businesses", (table: Knex.TableBuilder) => {
    // ...
    table.string("name").notNullable();
    table.text("short_description");
    table.text("text");
    table.string("street");
    table.string("zip");
    table.string("city");
    // ...
});
```
the default values are set to null. However, if we insert an empty string, the value is set to `EMPTY` instead of `NULL`.
So i thought there is maybe an already integrated solution in Objection. But i can't find anything.

Therefore my current solution is to always check the empty strings and replace them with null. For each column... and twice in update and insert. But this feels wrong:

```typescript
class BusinessModel extends Model {
  static tableName = "businesses";
  
  // ...

  shortDescription: string | null;
  text: string | null;
  street: string | null;
  zip: string | null;
  city: string | null;

  // ...

  $beforeInsert(): void {
    if (this.shortDescription === "") {
      this.shortDescription = null;
    }
    if (this.text === "") {
      this.text = null;
    }
    // ... AND SO ON with all other fields :(
  }

  $beforeUpdate(): void {
    if (this.shortDescription === "") {
      this.shortDescription = null;
    }
    if (this.text === "") {
      this.text = null;
    }
    // ... AND SO ON with all other fields :(

    this.updatedAt = new Date().toISOString();
  }

  // ...
}
```

This is not the way to go, isn't it? 

Thank you for any tips or finger pointing on keywords.

**Comment by koskimas** [comment]
You can turn that stuff into a function and just call the function from both `beforeInsert` and `beforeUpdate`. No need to copy paste everything.

Another option is to override the `$formatDatabaseJson`

```ts
$formatDatabaseJson(json) {
  json = super.$formatDatabaseJson(json)

  for (const key of Object.keys(json)) {
    if (json[key] === '') {
      json[key] = null
    }

    return json
  }
}
```

**Comment by koskimas** [comment]
https://vincit.github.io/objection.js/api/model/instance-methods.html#formatdatabasejson

**Comment by marko-x** [comment]
Ok. Thank you.
