### ISSUE TITLE
How to apply LOWER() to a ref

### ISSUE THREAD

**Issue by adefrutoscasado** [Vincit/objection.js#2111]
First of all, Im not sure if this is related to Knex or Objection. I see `ref` is provided by knex, but `castText` doesnt appear on Knex docs. Please correct me if this is not the place to ask this question.

Im using a `like` where statement in my query like this:

```js
import { ref } from 'objection'

const key = ref('data.nested_data').castText()
query = query.where(key, 'like', `%${value}%`)
```

And its working fine. The resulting query looks like this:
```sql
WHERE CAST("data"#>>'{nested_data}' AS text) like '%example%'
```

Now I want to use `LOWER()` funcion in the key, so I can find results case-insensitive. So my query now looks like this:
```js
import { ref, raw } from 'objection'

const key = ref('data.nested_data').castText()
query = query.where(raw(`LOWER(key)})`), 'like', `%${value.toLowerCase()}%`);
```
But this results to the following SQL query (throwing an error):
```sql
WHERE LOWER([object Object]) like $1

-- ERROR:  syntax error at or near "["
-- LINE 6: WHERE LOWER([object Object]) like $1
```

Is there any way to achieve what Im looking for? I prefer not using a raw query since my key is created dinamically in my case.

**Comment by abedmurrar** [comment]
```js
const key = ref('data.nested_data').castText();
query = query.where(raw('LOWER(??)', [key]), 'like', `%${value.toLowerCase()}%`);
```

**Comment by adefrutoscasado** [comment]
Wonderful, working fine! Thanks!
