### ISSUE TITLE
Using an objection model as `SQLDataSource`

### ISSUE THREAD

**Issue by garritfra** [Vincit/objection.js#2113]
I am looking for a way to add Apollo server-side caching to my knex queries through the [SQLDataSource](https://github.com/cvburgess/SQLDataSource) class. Since Objection and SQLDataSource both use inheritance, I don't see a way to implement the data source on top of the Objection base model. 

I stumbled across #1475 which seems to address a similar issue, but I'm unsure if this solves the problem at hand.

Is there a way to implement a data source on top of Objection's `Model` class?

**Comment by devinivy** [comment]
It looks like they could be used together, and #1475 does provide a piece of the puzzle:

```js
// Support SQLDataSource's cache() method that it adds to knex on your model's query-builder
class CustomQueryBuilder extends Model.QueryBuilder {
  cache() {
    return this.onBuildKnex(knexQuery => knexQuery.cache())
  }
}

// Provide the custom query-builder to your model
class User extends Model {
  static QueryBuilder = CustomQueryBuilder
}

// Create your SQLDataSource
const knex = Knex({/* config */});
const dataSource = new SQLDataSource(knex);

// Make queries using dataSource's modified knex (which happens to be the same as `knex` above).
// You can also setup your model using knex(), bindKnex(), or however you typically like to do this.
const users = await User.query(dataSource.knex).cache();
```

**Comment by garritfra** [comment]
Ahh, the missing piece of the puzzle was that I can use knex through the data source in my queries.

Thanks for your clarification!
