### ISSUE TITLE
A Question about uuids and upsertGraph

### ISSUE THREAD

**Issue by marko-x** [Vincit/objection.js#2114]
The following code is not working. Thats an example for what i want to achieve.

```javascript
/*
event_date table
id | event_id | uuid* | value

event table
id | uuid* | title

*generated on create by postgres

*/

const fromFrontend = {
  uuid: "b872e347-5650-5e9b-8bbe-97301d744908",
  title: "Something like an Event",
  dates: [
    {
      uuid: "22de8ada-7887-5fef-b95b-9bad8453a7a5",
      value: "2021-10-01"
    },
    {
      uuid: "558c3dd1-48fb-591c-a532-f851facb1e8b",
      value: "2021-11-30"
    },
    {
      value: "2021-12-12"
    }
  ]
};

const Event = await Event.query().upsertGraph({
  id: Event.findOne("uuid", fromFrontend.uuid).select("id"),
  title: fromFrontend.title,
  options: [
    ...fromFrontend.dates.map((date) => ({
      // if we have a uuid ? update : create
      ...(!!date.uuid && {id: EventDate.findOne("uuid", date.uuid).select("id")}),
      value: date.value
    }))
  ]
});
```

I could transform all `uuid` to primary keys and remove all the `id` columns. But i would like to use `id` in the database and `uuid` for frontend requests.

Is there any kind of possibility (maybe already built in objection)? 
I thought on something like `beforeInsert` and `beforeFind` or the queryBuilder inside a BaseModel. But after hours of trying — to remap the id to an uuid in upsert — I a came up with no solution.

Can somebody can point me in the right direction?
Thank you a lot.

**Comment by koskimas** [comment]
I don't think this is possible.
