### ISSUE TITLE
Large where-query right-hand operand (for Google access token)

### ISSUE THREAD

**Issue by Klaider** [Vincit/objection.js#2116]
With the latest Objection.js version, I'm using `await M.query().where('googleTokenId', googleToken)` and it returns `[]`, however my database does have a data row whose `googleTokenId` is equals `googleToken` (created previously by Objection). I've compared `googleToken` as of row insertion and as of row search and they yield the same value (a long encoded string representing a Google access token).

So is there some limitation on what can be compared, maybe due to Knex?

**Comment by koskimas** [comment]
There's no limitation. Could you show me how to reproduce this? What's the data type of the googleTokenId in the database? What's the type of the googleToken variable in JavaScript? How large is the token?

**Comment by Klaider** [comment]
@koskimas Thanks for the reply. The database column `googleTokenId` is `varchar(5000)` and the actual Google token is 1226 characters long. Objection is 2.2.17.

**Comment by koskimas** [comment]
What database and node driver are you using?

**Comment by Klaider** [comment]
I'm using PostgreSQL 13.4 and NodeJS driver `pg@8.7.1`.

**Comment by koskimas** [comment]
Here's a test case that runs just fine on all databases. I'm not able to reproduce this

```
const crypto = require('crypto');
const { expect } = require('chai');
const { Model } = require('../../../');

module.exports = (session) => {
  describe(`long string column`, () => {
    let knex = session.knex;
    let Person;
    let longName = crypto.randomBytes(1000).toString('hex');

    before(() => {
      return knex.schema.dropTableIfExists('Person').createTable('Person', (table) => {
        table.increments('id').primary();
        table.string('name', 5000);
      });
    });

    after(() => {
      return knex.schema.dropTableIfExists('Person');
    });

    before(() => {
      Person = class Person extends Model {
        static get tableName() {
          return 'Person';
        }
      };

      Person.knex(knex);
    });

    before(() => {
      return Person.query().insert({
        id: 1,
        name: longName,
      });
    });

    it('should be able to filter using a very long string value', async () => {
      const person = await Person.query().findOne('name', longName);
      expect(person.name).to.equal(longName);
    });
  });
};
```
