### ISSUE TITLE
How would you filter what is being passed to select, insert, update, (...)where(...) and orderBy?

### ISSUE THREAD

**Issue by iamnashdev** [Vincit/objection.js#2124]
Hello,

Coming from Sequelize I must admit Objection.js is mostly all I was looking for to not overcomplicate my code. But I can't seem to find an elegant way to filter what's being passed to these methods (select, insert, update, (...)where(...) and orderBy) based on my user permissions and wanted to ask how you would do it. I've tried several ways to try to achieve it but couldn't find a reliable way to do it.

## Actual example :
```
const { Knex, Model } = require('./lib/database');

const migrations = async () => {
  if (await Knex.schema.hasTable('todo'))
    return;

  await Knex.schema
    .createTable(
      'todo',
      table => {
        table.increments();
        table.string('name', 128).notNullable();
        table.string('hidden', 128)
      }
    )
    .createTable(
      'task',
      table => {
        table.increments();
        table.string('name', 128).notNullable();
        table.string('hidden', 128)
        table.integer('todoId').references('todo.id').notNullable()
      }
    );
};

class Task extends Model {
  static get tableName() { return 'task'; }
};
class Todo extends Model {
  static get tableName() { return 'todo'; }
  static get relationMappings() {
    return {
      task: {
        relation: Model.HasManyRelation,
        modelClass: Task,
        join: {
          from: 'todo.id',
          to: 'task.todoId'
        }
      }
    }
  }
};

const run = async () => {
  await migrations();

  // expected: hidden must not be added
  const todo = await Todo.query()
    .insert({
      name: 'Todo list 1',
      hidden: 'this field must not be set'
    });

  // expected: hidden must not be added
  await Task.query()
    .insert({
      name: 'Do something tomorrow',
      hidden: 'this field also must not be set',
      todoId: todo.id
    });

  // expected: hidden must not be added in both todo and task
  await Todo.query()
    .insertGraph({
      name: 'Todo list 2',
      hidden: 'nope',
      task: [
        {
          name: 'Do something',
          hidden: 'nope again'
        }
      ]
    });

  // todo: update must also be filtered

  /*
    expected:
    [
      { name: 'Todo list 1' },
      { name: 'Todo list 2' }
    ]
  */ 
  const findAll = await Todo.query();
    // .withPermission(user.role); // this is doable by creating a custom query builder

  console.log(findAll);

  // expected: remove hidden from todo and tasks
  const findAllWithTasks = await Todo.query()
    .withGraphFetched('task');
    // .withPermission(user.role); // if I override queryBuilder, todo will be filtered but not tasks

  console.log(findAllWithTasks);

  // expected: throw an error because hidden is forbidden
  const findByHidden = await Todo.query()
    .where({ hidden: 'nope' })
    .orderBy('hidden');
  // and so on must be filtered (orWhere, ...)  
  // .withPermission(user.role);

  console.log(findByHidden);

  await Knex.destroy();
};

run();
```

## What I tried : 
- Hooks :
I was able to filter what's being returned by the database even tho it's not exactly what I am looking for. Still I can't filter what's being passed to where, ...

- Custom query builder : 
I am able to filter the parent table but not able to filter relations recursively

- Objection-Authorize : 
This seems to not cover all I need

- Wrapper around objection model : 
Doing this I just loose the flexibility of the QueryBuilder and it will just look like any other ORM I've used nowadays

## What I expect : 
Ideally, pass my user role through a query builder method (withPermission?) and expect it to filter everything (relation stuff included) based on a schema permission in my model. Also this way I would be able to throw in my query params without having to manually filter for permissions.

Hoping to find an answer here, also I think this would be a super feature for objection.

Thanks for reading

**Comment by koskimas** [comment]
I'm afraid there's no easy way to do this. I wouldn't recommend trying to do this in the model level.
