### ISSUE TITLE
Version 3 migration guide

### ISSUE THREAD

**Issue by davidmwhynot** [Vincit/objection.js#2129]
As mentioned [here](https://github.com/Vincit/objection.js/pull/1992#issuecomment-883906897), 3.0 alpha versions can be used. It would be nice if there was, at the very least, a summary of the breaking changes introduced in 3.0. I would hope that having this documentation will help @koskimas establish a timeline for a 3.0 release.

Perhaps we could compile said list in this issue before a PR is opened to update the documentation.

**Comment by koskimas** [comment]
https://vincit.github.io/objection.js/release-notes/migration.html
