### ISSUE TITLE
Error when using range() and whereJsonHasAny()

### ISSUE THREAD

**Issue by purepear** [Vincit/objection.js#213]
This works fine
`Model.query().whereJsonHasAny('someJsonField', 'someKey').then(...)`
but this doesn't
`Model.query().range(0, 10).whereJsonHasAny('someJsonField', 'someKey').then(...)`
Here is the error:
`select count(*) as "count" from (select * from "Model" where "someJsonField"#>'{}' $1| array['someKey']) as temp - syntax error at or near "$1"`

I think when range is making the count query it replaces `?|` with`$1|` and causes the problem.

**Comment by elhigu** [comment]
Yep... looks like that somewhere in objection escaping is dropped from front of ? -mark... in `\\?|` operator.

**Comment by purepear** [comment]
I believe this is knex bug because`range` count query uses `knex.raw()`. This example also fails the same way

```knex.raw(`SELECT * FROM "Model" WHERE "someJsonField"#>'{}' ?| array['someKey']`).then(...)```

**Comment by elhigu** [comment]
In knex you need to escape ? -mark 

```js
knex.raw(`SELECT * FROM "Model" WHERE "someJsonField"#>'{}' \\?| array['someKey']`).then();
```

**Comment by purepear** [comment]
I was just writing the same thing... my bad :)

**Comment by koskimas** [comment]
@elhigu I have no idea what is going on here. It has something to do with knex:

```
  resultSize() {
    const knex = this.knex();

    // orderBy is useless here and it can make things a lot slower (at least with postgresql 9.3).
    // Remove it from the count query. We also remove the offset and limit
    const query = this.clone().clear(/orderBy|offset|limit/).build();
    console.log(query.toString())
    const rawQuery = knex.raw(query).wrap('(', ') as temp');
    console.log(rawQuery.toString());
    const countQuery = knex.count('* as count').from(rawQuery);
    console.log(countQuery.toString());

    if (this.internalOptions().debug) {
      countQuery.debug();
    }

    return countQuery.then(result => result[0] ? result[0].count : 0);
  }
```

yields:

```sql
select "ModelJson".* from "ModelJson" where "jsonObject"#>'{b}' ?| array['2']
(select "ModelJson".* from "ModelJson" where "jsonObject"#>'{b}' ?| array['2']) as temp
select count(*) as "count" from (select "ModelJson".* from "ModelJson" where "jsonObject"#>'{b}' ?| array['2']) as temp
```

but the query still fails.

**Comment by koskimas** [comment]
The `knex.raw(query).wrap(...)` needs to be there or otherwise the `from` won't work. Should't `from` be able to take a knex query builder? `query` in the above example is a knex query builder and not objection query builder.

**Comment by elhigu** [comment]
Indeed it looks like knex doesn't wrap it correctly https://runkit.com/embed/9goo8spc4qtk

IIRC there is some issue in knex repo about that and workarounds.

**Comment by elhigu** [comment]
Maybe `knex.count('* as count').from(rawQuery);` could be changed to:

```js
knex.with('rows', rawQuery).count('* as count').from('rows');
```

so that query builder is not passed to `.from()`

**Comment by koskimas** [comment]
Does `with` work on all databases?

**Comment by koskimas** [comment]
@elhigu `with() second argument must be a function or a raw`

**Comment by elhigu** [comment]
Yeah... and looks like `.with` is not supported by mysql older than 8.0.1.  :(

**Comment by koskimas** [comment]
This horrible hack works:

```js
    const countQuery = knex.with('count', (builder) => {
      Object.assign(builder, query);
    }).count('* as count').from('count');
```

So if `from` or `with` would just accept query builders, I could implement this. Why don't they accept them?

**Comment by elhigu** [comment]
IMO, it should accept any query builder like it accepts .raw... probably just bug in knex.

Here is other hack to convert query -> raw 
```
    const countQuery = knex.with('count', knex.raw('?', [query])).count('* as count').from('count');
```

**Comment by koskimas** [comment]
Ha! That one worked. Thanks!

**Comment by koskimas** [comment]
But it doesn't work with mysql...

**Comment by elhigu** [comment]
how about something like this: https://runkit.com/embed/9goo8spc4qtk

```js
knex.count('* as count').from(knex.raw('(?)', [query]))
```
