### ISSUE TITLE
[Feature Request] Add Model Generation from database schema

### ISSUE THREAD

**Issue by eduardhasanaj** [Vincit/objection.js#2133]
### Motivation
I have been working with [SQLBoiler](https://github.com/volatiletech/sqlboiler) and it has been
a very pleasant experience without giving up too much performance side. Their philosophy is to 
generate models tailored to db schema. In this way they avoid using reflection and 
other expensive operations.  The models are optimized and metadata about columns is 
generated in such a manner that helps them to handle db operations efficiently.
objection.js look amazing and this feature can optimize the performance even more 
by learning from the mentioned library.

### Benefits

Supporting this philosophy has following benefits:
- Work with existing databases: Don't be the tool to define the schema, that's better left to other tools.
- ActiveRecord-like productivity: Eliminate all sql boilerplate, have relationships as a first-class concept.
- optimize hot paths by generating specific code for each schema model.

The third point is very important. With this approach we basically generate specific logic for models and this can help us to get extra performance.  We can use generated complex structures to store column, foreign key metadata which can help us to build efficient queries or during the model parsing.

### DISCLAIMER
I am new user of objection.js and have no contribution to this project. This proposal is just an idea
which may help us to make this ORM even better.

**Comment by ggallovalle** [comment]
That sound like a really cool idea. Never seem any thing like it because I'm not into the go ecosystem.
But to me it seems like is a lot kind of like prisma, kind of. What inside do you have when comparing SQLboilder with Prisma, if by any chance you have checked that orm.

**Comment by eduardhasanaj** [comment]
@ggallovalle I checked it briefly and the main turn off was how they construct queries. They basically use objects to configure a query. Why is that inefficient? Because these objects needs to be processed to convert them into raw SQL queries and this calculation has its cost. That's why I prefer more a query builder.
As for parsing the result into a model(binding) I have no idea or contention about Prisma as I have not studied their source code.
There is a [benchmark](https://github.com/prisma/prisma/issues/8166) which compares Sequelize and Prisma where the former is the winner. Unfortunately most of benchmarks does not cross out delay incurred by http request and connection with the database.

**Comment by koskimas** [comment]
This is not something that should be added to objection. A separate library makes more sense.

**Comment by eduardhasanaj** [comment]
@koskimas The proposal was to learn from the mentioned library.
 I was not proposing to add cli tool for model generation to this repository, of course it should be a separate repository but part of Objection.js project.
When the cli tool is finished, only parsing part is left to be handled by the Objection.js.

**Comment by koskimas** [comment]
I meant this is not something that should be part of the *objection project*. 

You may have misunderstood what objection is all about. The whole point is to not try to be smart and build special queries. That's an insanely difficult task. Hibernate has done that pretty well, but it's a massive project with a million lines of code and over ten years of work put into it by a huge team. And even hibernate sometimes generates awful code.

Objection is just a query builder with some relational features on top. Most of the time objection just builds whatever you tell it to build. Nothing more.
