### ISSUE TITLE
Value mappers everywhere

### ISSUE THREAD

**Issue by IkorJefocur** [Vincit/objection.js#2134]
I'm new at objection and have a question. I think it's better to describe with real example.

Let's say I have table `players` in my database and corresponding model `Player`. The structure is very simple: table have only one column (excluding id) named `user_id`. And this column is not reference to id of some other table's entry in my database. Instead, something called `user` is object that i can retrieve from some external API. But anyway, each `user` has unique id that can be used to retrieve object, using something like `User.byId(id)`. In simple words, each player is our user, registered through other application, and we are using his data from that application in ours.

My question is: **How to tell objection (and, probably, knex) to transform `user` object into `user.id` primitive wherever i using `user_id` field of `Player` model?**

Some examples of behaviour that i want:

```js
const user = await User.byId(123);
user.id // 123
user.name // Ikor

Player.query()
	.insert({
		'user_id': user // Must insert "123"
	});

Player.query()
	.select()
	.where('user_id', user); // Must select row where "user_id" is "123"
```

**Comment by koskimas** [comment]
Like this

```js
const user = await User.byId(123);
user.id // 123
user.name // Ikor

Player.query()
	.insert({
		'user_id': user.id
	});

Player.query()
	.select()
	.where('user_id', user.id); 
```

**Comment by IkorJefocur** [comment]
That was not what i'm needed. I want to be able to tell `Player` something like **"Take that user and register him in your database"**.

Ok, lets add some more complexity to example that can help understand what i want better. Database `players` also have field `name`. It's name of registered user by default, but then it can be changed independently. So, i'd like to do something like this:

```js
// This two queries should be equivalent

Player.query()
	.insert({
		'user': user
	});

Player.query()
	.insert({
		'user_id': user.id,
		'name': user.name
	});
```
