### ISSUE TITLE
Update api queryBuilder find doc to add intersect, referencing the knex doc

### ISSUE THREAD

**Issue by JonathanClaybrough** [Vincit/objection.js#2137]
Hi,
I noticed the doc for Querybuilder find doesn't mention intersect, even though it mentions union and unionAll. Looking further into the issue I notice the knex doc mentions intersect but doesn't have a hyperlink to it. In the meanwhile until knex updates their doc, I suggest adding the following to the Objection doc :  
 
 
## intersect()

See [knex documentation](http://knexjs.org/#Builder-unionAll)

##### Return value

| Type                                | Description                        |
| ----------------------------------- | ---------------------------------- |
| [QueryBuilder](/api/query-builder/) | `this` query builder for chaining. |

**Comment by JonathanClaybrough** [comment]
Linked PR should be https://github.com/Vincit/objection.js/pull/2138

**Comment by koskimas** [comment]
PR merged.
