### ISSUE TITLE
deprecated methods in changelog are not appearing

### ISSUE THREAD

**Issue by abedmurrar** [Vincit/objection.js#2139]
In https://vincit.github.io/objection.js/release-notes/migration.html#dropped-a-bunch-of-deprecated-methods-and-features
List of deprecated methods in objection v2 are not appearing 
![image](https://user-images.githubusercontent.com/37074425/141054427-e236c1c8-816e-4f72-9a6e-d85884fc7865.png)

**Comment by koskimas** [comment]
They are not supposed to
