### ISSUE TITLE
Discard inheriting tables data

### ISSUE THREAD

**Issue by harshpatel01** [Vincit/objection.js#2141]
For every table in the database there is an audit table that inherits the main table.  However I would like to discard inheriting audit table data for all queries unless I want to find all the audit log for given record. In knex.js I can pass only in options like below to achieve this. 

knex(tableName, options={only: boolean}) to achieve this. 

I am not sure if this is possible when using objection.js can't seem to find anything related to this in the documentation.

**Comment by koskimas** [comment]
Nope, not possible with objection.
