### ISSUE TITLE
type must be JSONType or JSONType[]: date-time

### ISSUE THREAD

**Issue by thefoxie** [Vincit/objection.js#2142]
After update to the 3.0.0 I got this validation error.

```js
static get jsonSchema() {
		return {
			type: "object",
			required: [
				"first_name",
				"last_name",
				"email",
				"phone_number",
			],
			properties: {
				first_name: { type: "string" },
				last_name: { type: "string" },
				last_change: { type: "date-time" },
				email: { type: "email" },
				phone_number: { type: "string" },
				last_try: { type: "date-time" },
				last_logged: { type: "date-time" },
			},
		};
	}
```
```js
const now = new Date(Date.now());
const lastLogged = response.isValid ? { last_logged: now } : {};

const toPatch = {
	last_try: now,
	...lastLogged,
};

await user.$query().patch(toPatch);
```

**Comment by koskimas** [comment]
`date-time` is not a valid type. It's been working before by accident. I think `Ajv` has added more validation in the recent versions.

**Comment by koskimas** [comment]
Here's the JSON schema spec https://json-schema.org/specification.html

**Comment by thefoxie** [comment]
Thank you, I see now :smile: 

https://ajv.js.org/guide/formats.html

**Comment by thefoxie** [comment]
Is there any way how to use/import `ajv-formats` globally in objection?

**Comment by thefoxie** [comment]
Ok my fault RTFM :smile: 
https://vincit.github.io/objection.js/api/types/#class-ajvvalidator

**Comment by rhazegh** [comment]
@thefoxie Can you please share how you made `ajv-formats` work?

**Comment by wafaboussada** [comment]
> Ok my fault RTFM smile https://vincit.github.io/objection.js/api/types/#class-ajvvalidator

how can i use it in model like this please @thefoxie 
class Cart extends Model {
  // Table name is the only required property.
  static get tableName() {
    return 'cart';
  }

  static get jsonSchema() {
    return {
      type: 'object',
      properties: {
        id: { type: 'integer' },
        history_id: { type: 'integer' },
        currency_id: { type: ['integer', 'null'] },
        modification_date: { type: 'datetime' },
      },
    };
  }
}

**Comment by thefoxie** [comment]
@wafaboussada you have to change it somewhere where you init objectionjs. In my case:

```js
import knex from "knex";
import Objection from "objection";
import addFormats from "ajv-formats";
import config from "./config.js";

const { Model: ObjectionModel, AjvValidator } = Objection;

class Model extends ObjectionModel {
	static createValidator() {
		return new AjvValidator({
			onCreateAjv: (ajv) => {
				addFormats(ajv);
			},
			/* options: {
				allErrors: true,
				validateSchema: false,
				ownProperties: true,
				v5: true,
			}, */
		});
	}
}

const knexInit = knex(config[process.env.NODE_ENV || "development"]);
Model.knex(knexInit);
export default Model;
```

**Comment by wafaboussada** [comment]
@thefoxie in my case i did this i create file validate model with this code 
const {Model, AjvValidator} = require('objection')
const addFormats = require("ajv-formats")

class ValidatedModel extends Model {
    static createValidator() {
        return new AjvValidator({
            onCreateAjv: (ajv) => {
				addFormats(ajv);
			},
          options: {
            $data: true,
            allErrors: true,
            validateSchema: false,
            ownProperties: true,
            v5: true,
            coerceTypes: true,
            removeAdditional: true,
          },
        });
      }
    }

module.exports = ValidatedModel


and then i do this in the model cart 
class Cart extends ValidatedModel {
// Table name is the only required property.
static get tableName() {
return 'cart';
}

static get jsonSchema() {
return {
type: 'object',
properties: {
id: { type: 'integer' },
history_id: { type: 'integer' },
currency_id: { type: ['integer', 'null'] },
modification_date: { type: 'datetime' },
},
};
}
}


but it didin't work the same error always type must be JSONType or JSONType[]: date

**Comment by thefoxie** [comment]
@wafaboussada  see https://ajv.js.org/guide/formats.html
`{ type: "datetime"} ` is not valid. Try to use `{ type: "string", format: "date-time" }` instead. Take into account, that it must be a string -> you have to parse it from js Date object.

**Comment by wafaboussada** [comment]
@thefoxie i got this error unknown format "date-time" ignored in schema at path "#/properties/modification_date"

**Comment by thefoxie** [comment]
@wafaboussada might be somewhere else (in different model).

**Comment by wafaboussada** [comment]
@thefoxie i will see thxx

**Comment by wafaboussada** [comment]
@thefoxie  hello for the type timestamp when i put { type: "string", format: "timestamp" } it make an error. i think timestamp format not used in ajv-formats. there is a solution fo this ?

**Comment by thefoxie** [comment]
@wafaboussada `{ type: "string", format: "date-time" }` should work I guess.

**Comment by LordA98** [comment]
For anyone wondering, if you go down the route of adding the ajv-formats package and creating a property with `type: string` and `format: date-time` - the easiest way to get a value that matches this format is `new Date().toISOString()`.

Wasn't obvious to me so thought I'd add a note.
