### ISSUE TITLE
withGraphFetched returns Array for BelongsToOneRelation

### ISSUE THREAD

**Issue by loliman** [Vincit/objection.js#2145]
Hi,

I do have two models Foo and Bar. Foo is related to Bar through a BelongsToOneRelation, Bar is related to Foo through a HasManyRelation. Now, if i fetch the graph of one Bar through 

```
    Bar.query()
      .select('foos.*', 'foos:bar*')
      .leftJoinRelated('[foos.bar]')
      .withGraphFetched('foos.[bar]');
```

the Bar of each Foo is an Array, which seems to be strange, because each Foo can only be related to one Bar. Is this intended or am I doing something wrong?

**Comment by koskimas** [comment]
That's not intended, but I can't really tell what you're doing wrong or if there's a bug based on this. Can you try to provide a simple reproduction? There's a template at the root of the repo if you want to use it.

**Comment by koskimas** [comment]
Can I expect a reproduction, or should I close this?

**Comment by loliman** [comment]
Hi! 

Sorry, had a busy week. You can close this issue. For some reason I can not reproduce it anymore, dont ask me why. Thanks for your help!
