### ISSUE TITLE
[Objection 3.0] unknown format "iso-date-time" ignored in schema at path

### ISSUE THREAD

**Issue by rhazegh** [Vincit/objection.js#2147]
```
"objection": "^3.0.0"
"knex": "^0.95.14"
"ajv-formats": "^2.1.1"
```

I updated to the latest objection and realized I had to change some models to avoid type errors (for example `date` is now an invalid type in the json schema). I saw https://github.com/Vincit/objection.js/issues/2142 and updated my code to use `ajv-formats` package. But I am still getting this error:

```
unknown format "iso-date-time" ignored in schema at path "#/properties/main/properties/registeredAt"
```

`iso-date-time` is in the list of supported formats according to https://ajv.js.org/packages/ajv-formats.html#formats

Any idea what I am doing wrong?

Here is what my model looks like:

## base-model.js
```javascript
import { Model, QueryBuilder, AjvValidator } from "objection";

const addFormats = require('ajv-formats').default;

class DefaultSchemaQueryBuilder extends QueryBuilder {
  constructor(modelClass) {
    super(modelClass);
    if (modelClass.defaultSchema) {
      this.withSchema(modelClass.defaultSchema);
    }
  }
}

export default class BaseModel extends Model {
  // Add all shared configurations here
  static get QueryBuilder() {
    return DefaultSchemaQueryBuilder;
  }

  static createValidator() {
    return new AjvValidator({
      onCreateAjv: (ajv) => {
        addFormats(ajv);
      },
      options: {
        allErrors: true,
        validateSchema: false,
        ownProperties: true,
        v5: true,
      },
    });
  }
}
```

## user-setting.js
```javascript
import { set } from "lodash";

import BaseModel from "./base-model";
import { languages } from "../constants";

class UserSettingAbstract extends BaseModel {
  static tableName = "user_settings";

  static get jsonSchema() {
    return {
      type: "object",
      properties: {
        id: { type: "string", format: "uuid" },
        userId: { type: "string", format: "uuid" },
        main: {
          type: "object",
          properties: {
            registeredAt: {type: "string", format: "iso-date-time" },
            dailyGoal: { type: "integer" },
            welcomedAt: { type: "string", format: "iso-date-time" },
          },
        },
      },
    };
  }
}

let dynClassMemoizer = {};

function UserSetting(lang) {
  if (!lang) {
    throw new Error(`lang: argument is required`);
  } else if (!languages.map((l) => l.code).includes(lang)) {
    throw new Error(`Invalid language: ${lang}`);
  }

  if (!dynClassMemoizer[lang]) {
    const dynClass = class extends UserSettingAbstract {
      static defaultSchema = lang;
    };
    dynClassMemoizer[lang] = dynClass;
  }
  return dynClassMemoizer[lang];
}

export default UserSetting;
```

**Comment by koskimas** [comment]
I think this is more an Ajv issue than objection issue. I don't know why that's happening.

**Comment by rhazegh** [comment]
@koskimas Understood. I used `format: "date-time"` instead and it's working. 

I will try to find out what's going on with `iso-date-time`. Thanks for this fantastic project.

**Comment by rhazegh** [comment]
It seems `iso-date-time` is a new supported format that will appear in `ajv-formats` version `3.0.0` and does not exist in the version we are currently using.

**Comment by jboxxx** [comment]
https://stackoverflow.com/questions/55521116/can-i-validate-a-date-using-ajv-json-schema-without-converting-the-date-to-stri

helpful if you DONT want to convert your date into a string

**Comment by LordA98** [comment]
For anyone wondering, if you go down the route of adding the ajv-formats package and creating a property with `type: string` and `format: date-time` - the easiest way to get a value that matches this format is `new Date().toISOString()`.

Wasn't obvious to me so thought I'd add a note.
