### ISSUE TITLE
How to add columns?

### ISSUE THREAD

**Issue by Steviey** [Vincit/objection.js#215]
I have read the API-reference carefully, but I can't figure out how to add columns to a model, so the table structure updates. If "Person.jsonSchema = {" is only for validation, what does "Model.fromJson". Is there an example? How can I add columns/alter tables without deleting the table?
I hope this is the right place to ask this questions. Thank you.

PS: Is there a way of generic error-catching too?

**Comment by koskimas** [comment]
This is the right place for questions. You can also try the gitter chat in the future.

Objection itself doesn't handle migrations. You need to use some other library for that. The preferred way is to use knex migrations. They are excellent and knex is already a dependency. Check out the [example projects](https://github.com/Vincit/objection.js/tree/master/examples/express-es6) on how to use it. It's really simple.

**Comment by Steviey** [comment]
hm...thank you but...

Uncaught ReferenceError: exports is not defined

trying: "schemaPromise.exports.up = function (knex) {"

throws:
Uncaught TypeError: Cannot set property 'up' of undefined

I also try to convert the complete person example to class methods, because I need the methods pragmatically invoked.

**Comment by koskimas** [comment]
You are trying something funny. Just copy-paste the example project's migration file and modify it. You are trying to set the `exports.up` of a some promise apparently? `exports` should be the node.js module export object and nothing else.

**Comment by Steviey** [comment]
I'm somehow very old school JavaScriptler (1996).
When i try this 
var modify = knex.schema.table('Person', function (table) {
  table.string('finland');  
})

nothing changes too. Could you point me to the project's migration file?

**Comment by koskimas** [comment]
I updated the previous comment. The file is hidden in the `migrations` folder 😉

**Comment by Steviey** [comment]
I created an external file /js/migrate.js with the following content:

exports.up = function (knex) {
    return knex.schema.table('Person', function (table) {
    table.string('theColumnYouWantToAdd');
  });
};

Then in my main app.js I say: 
var modify = require('./js/migrate.js');

but nothing happens to my table...hm.

**Comment by koskimas** [comment]
Please just read the knex documentation or the example app I linked. You are not doing it right. First of all requiring the file does nothing but return the object with `up` function. This is how modules work in node.js. Second of all, even if the require somehow magically did something, it would be _asynchronous_ and you would need to wait for the result. All IO operations in node.js are asynchronous.

You need to use the knex cli tool to run the migrations or if you really want to run them in code, you can do this:

```js
knex.schema.table('Person', function (table) {
  table.string('theColumnYouWantToAdd');
}).then(function () {
  // In here the async operation is ready.
});
```

You should probably start by reading how promises and asynchronous programming in javascript work. Then you should continue to knex documentation.

**Comment by Steviey** [comment]
Still no result. I think I will go with 'alter table'.
