### ISSUE TITLE
Defining a model based on JsonB backing column

### ISSUE THREAD

**Issue by rocketjsquirrel** [Vincit/objection.js#2152]
I see the KOA-ts example with Person table with a `json` type on column Address.  How would you set the type on an address property on the model to access it? I see it referenced in the validation schema.

**Comment by koskimas** [comment]
You can define an interface for the json and just use that in the model:

```ts
interface Address {
  postalCode: string
  streetAddress: string
}

class Person extends Model {
  address!: Address
}
```
