### ISSUE TITLE
error TS2709: Cannot use namespace 'Ajv' as a type.

### ISSUE THREAD

**Issue by ionizer** [Vincit/objection.js#2157]
There is a problem when transpiling from Typescript using `tsc` when using Objection on Typescript project. The following is the error log:

```
$ tsc
node_modules/objection/typings/objection/index.d.ts:1208:22 - error TS2709: Cannot use namespace 'Ajv' as a type.

1208     onCreateAjv(ajv: Ajv): void;
                          ~~~


Found 1 error.
```

NodeJS: 16.13.0
Typescript: ^4.5.2
Objection: ^3.0.0

**Comment by ionizer** [comment]
Fixing the import from [line 15](https://github.com/Vincit/objection.js/blob/c8d3452952e9da4d105abe8ba19435842865badf/typings/objection/index.d.ts#L15) of the `index.d.ts` to `import { Ajv, Options as AjvOptions } from 'ajv';` seems to fix this issue, but I don't know what the consequences are for other Typescript or Node versions.

**Comment by koskimas** [comment]
My guess is that your `tsconfig` is configured in a way that objection typings point to a wrong, older version of `Ajv` that had completely different typings. For example, do you have something in the `compilerOptions.paths` field in tsconfig?

```json
  "compilerOptions": {
    "paths": {
      "*": ["Something here?"]
    }
```

**Comment by ionizer** [comment]
> If you cmd-click (or ctrl-click) ajv in the typings file, you'll probably see where the configuration points it. It should be pointing to the version that's compatible with objection's version selector for Ajv, but my guess is that it will take you to a file that's under some other dependency's node_modules.

ctrl-clicking on the Ajv import does bring me to the node_modules/ajv/dist/ajv.d.ts. Does this mean that it's more of the deps issue?

**Comment by ionizer** [comment]
> do you have something in the compilerOptions.paths field in tsconfig?
Now that you mention it, there's `ajv` dir inside my node_modules and there's also `ajv` dir under node_modules/objection/node_modules... I guess having `{"paths": ["node_modules/*"]}` is the cause of this issue.

**Comment by koskimas** [comment]
I think it's still weird that typescript ends up picking the wrong `ajv` in this case. Were you able to fix this somehow?

**Comment by ionizer** [comment]
So I had the following in my tsconfig and caused the problem:
```
  "compilerOptions": {
    "paths": {
      "*": ["node_modules/*", "src/*"]
    }
```

I ended up removing the "node_modules/*" from there to fix the `tsc` error. After a bit of testing, everything about my project still seem to work just fine.

For now, I think I am considering it fixed. Thanks!

**Comment by koskimas** [comment]
Great!
