### ISSUE TITLE
Is it save (prepared statements)?

### ISSUE THREAD

**Issue by Steviey** [Vincit/objection.js#216]
If I say something like this:
   
    Person.query().insert(
    {firstname: externalVarA},
    {surname: externalVarB},
    {comment: externalVarC},
    {sortabletimestamp: sortableTimestamp}
    );

...How will it be interpreted? Are there implicit prepared statements, or do I have it to prepare manually?

**Comment by koskimas** [comment]
You can see the generated SQL by chaining `.debug()` method to the query. You don't need to prepare manually.

**Comment by Steviey** [comment]
Thank you.
