### ISSUE TITLE
Did the Ajv validation change to strict mode in v3?

### ISSUE THREAD

**Issue by caschbre** [Vincit/objection.js#2162]
I add extra elements to my jsonSchema for various uses.  After upgrading to v3.0.0 I've started to receive a "strict mode: unknown keyword" error.  I see that we can customize the [Ajv validator](https://vincit.github.io/objection.js/recipes/custom-validation.html), but before I go down that route I wanted to double check if that was a change from v2 -> v3?

**Comment by koskimas** [comment]
v3 updated to the latest Ajv (8.x). Nothing else has changed. Maybe `Ajv` changed some defaults in 8.x?

**Comment by caschbre** [comment]
It must have been Ajv then... I downgraded objectionjs and the error went away.

I expect others to run into this as well if they have extra elements in their jsonSchema. Might be worth making a note in the changelog that others may run into this as well.

**Comment by mohghaderi** [comment]
I ran into the same issue when upgrading from v2 to v3. I had to override ajv default values for "patch" function to work.
`
const AjvValidator = require('objection').AjvValidator;

class Model {
  static createValidator() {
    return new AjvValidator({
      onCreateAjv: ajv => {
        // Here you can modify the `Ajv` instance.
      },
      options: {
        strict: false, // doesn't work with update function where we use patch for updating.
      }
    });
  }
}
`

Reference:   https://vincit.github.io/objection.js/recipes/custom-validation.html#examples
