### ISSUE TITLE
Defining setters only on beforeInsert and beforeUpdate?

### ISSUE THREAD

**Issue by mmahalwy** [Vincit/objection.js#2163]
Having this:
```ts
set email(value: string) {
    console.log(value);
    this.$set({ email: value.toLowerCase() });
  }
```

Run into `RangeError: Maximum call stack size exceeded` error. Is the only way to define a setter on a field through `beforeInsert` and `beforeUpdate`?

**Comment by koskimas** [comment]
You get the error because `$set` internally does `this.email = value` which will again invoke the setter. You can simply assign the value to the object, but clearly the value cannot be named `email` because that's the name of your setter.

Something like this will work

```js
set email(value: string) {
  this.$email = value
}

get email() {
  return this.$email
}
```
