### ISSUE TITLE
How best to find which items were altered in afterUpdate hook?

### ISSUE THREAD

**Issue by shedworth** [Vincit/objection.js#2164]
I'm trying to call a function for items that have had a particular attribute changed (`birdId`), using the static `afterUpdate` hook.

`asFindQuery` tells me half of the story: the full list of updated items (but not what was changed); `inputItems` tells me the other half: the items that had their `birdId` changed (but not the id of the item). My naïve approach below assumes that the returned result of `asFindQuery` is in the same order as `inputItems`, allowing me to zip the two arrays, but I suspect this might not always be the case. What's the preferred approach here?

Thanks in advance,
Tim

```
  static async afterUpdate(args: StaticHookArguments<Sighting>): Promise<void> {
    await super.afterUpdate(args);
    const { asFindQuery, inputItems } = args;
    const sightingsToUpdate = await asFindQuery().select("id", "sessionId");

    const updateUserStatsProms = zipWith(
      inputItems,
      sightingsToUpdate,
      (inputItem, sighting) => {
        if (pipe(keys, includes("birdId"))(inputItem))
          return (
            User.updateSightingStats(sighting.userId),
            BadgeAward.awardForUser(sighting.userId)
          );
      }
    );
    await Promise.all(updateUserStatsProms);
```

**Comment by koskimas** [comment]
Not possible I'm afraid.
