### ISSUE TITLE
Can't catch the error.

### ISSUE THREAD

**Issue by Steviey** [Vincit/objection.js#217]
Hello readers,
**column firstName1 does not exist**...
```javascript
function (person) {
return Person.query()
.where('firstName1', 'Sylvester')
//.debug()
//.then(function (numUpdated) {console.log(numUpdated);})
.catch(function (err) {console.log(err.stack);})
}
```
And **".catch"** prints no error. 
What do I missing here? Did I found a library bug?

**Comment by koskimas** [comment]
Can you post a bigger segment of the code. Your example should work and the `catch` callback should be called. I tested the code myself, and it works. Is your actual code somehow different from what you posted here?

**Comment by Steviey** [comment]
var objection = require('objection');
var Model = objection.Model;
var Knex = require('knex');

// Initialize knex connection.
var knex = Knex({
    client: 'sqlite3',
    connection: { filename: 'example.db' },
    useNullAsDefault: true
});

// Give the connection to objection.
Model.knex(knex);

//create
var sortableTimestamp = Math.floor(Date.now() / 1000);
//console.log(sortableTimestamp);
// Create database schema. You should use knex migration api to do this. We
// create it here for simplicity.
var schemaPromise = knex.schema.createTableIfNotExists('Person', function (table) {
    table.increments('id').primary();
    //table.dropColumn('firstName');
    table.string('firstname');
    table.string('surname');
    table.text('comment');
    table.timestamp('gendate').defaultTo(knex.fn.now());
    table.timestamp('editdate').defaultTo(knex.fn.now());
    table.string('sortabletimestamp');
});


// model
function Person() {
    Model.apply(this, arguments);
}
Person.tableName = 'Person';
Model.extend(Person);

//migration
//All IO operations in node.js are asynchronous. Man muss warten bis die Meldung kommt.
/*
knex.schema.table('Person', function (table) {
  table.string('sortabletimestamp');
}).then(function () {
  console.log('function has finished.');
});
*/

//insert
schemaPromise.then(function () {
    // Create a person.
    return Person.query().insert(
        {
            firstname: 'Peter',
            surname: 'Meier',
            comment: 'Ein Test',
            sortabletimestamp: sortableTimestamp
        })
    //.debug()
    //.then(function (numUpdated) {console.log(numUpdated);})
    //.catch(function (err) {console.log(err.stack);})
})

    //select
    .then(function (person) {
        //.query()  = all
        return Person.query()
            .where('firstName1', 'Sylvester')
            //.andWhere('firstname', 'Jennifer')
            //.orderBy('lastName')
            //.debug()
            //.then(function (numUpdated) {console.log(numUpdated);})
            .catch(function (err) { console.log(err.stack); })
    })

    //update
    .then(function (person) {
        return Person.query()
            .patchAndFetchById(1, { firstname: 'nameAnders', surname: 'surnameAnders' })
            //.debug()
            .then(function (updated) { console.log('Updated:' + JSON.stringify(updated)); })
            .catch(function (err) { console.log(err.stack); })
    })

    //delete
    .then(function (person) {
        return Person.query()
            .delete()
            .where(Person.raw('lower("firstname")'), 'like', '%vest%')
            .then(function (numDeleted) { console.log(numDeleted, 'people were deleted'); })
            .catch(function (err) { console.log(err.stack); })
    })


    //close
    .then(function () {
        return knex.destroy();
    });

// run the following command to install:
// npm install objection knex sqlite3

/*
SRC

return Person.
return knex.schema
    .raw("ALTER TABLE profiles ALTER COLUMN license DROP NOT NULL;")
    .raw("ALTER TABLE profiles ALTER COLUMN national_id DROP NOT NULL;");
*/

**Comment by elhigu** [comment]
@Steviey could you provide minimal test case, which shows your problem. Preferably one executable .js file which shows exactly your problem, but doesn't have any extra unrelated code. 

It is a bit too much to ask it here to debug your complete application. If you are able to point out where your bug is it also makes it easier for you to find any future problems.

**Comment by Steviey** [comment]
What do you mean with one excecutable.js? 
The relevant code is the first part (app1.js).
I provided the complete code on request of koskimas. There is no more code at all.

**Comment by elhigu** [comment]
With one executable `.js` file I  mean: one small javascript file which one can run with node and reproduce your failing code.

**Comment by fl0w** [comment]
Inspirational bug reports within this tracker alone
* https://github.com/Vincit/objection.js/issues/158
* https://github.com/Vincit/objection.js/issues/205
* https://github.com/Vincit/objection.js/issues/189

(And read [my comment](https://github.com/Vincit/objection.js/issues/221#issuecomment-254333479) in your other issue @Steviey which you closed yourself)

**Comment by Steviey** [comment]
I did not closed it myself!

**Comment by jetacpp** [comment]
@Steviey , from your code it appeared that you instantiated knex instance in renderer process, in fact all database operations done in render process. How did you do that ? I was only able to instantiate knex instance in main process, and make it available to render processes thru IPC.
