### ISSUE TITLE
Error in insert data type date or timestamp

### ISSUE THREAD

**Issue by wafaboussada** [Vincit/objection.js#2170]
Hello
when updating objection to 3.0.0 and knex to 0.95.14, i got this error : type must be JSONType or JSONType[]: date.
and there are warnings in node modules objection

**Comment by koskimas** [comment]
https://github.com/Vincit/objection.js/issues/2147
https://github.com/Vincit/objection.js/issues/2146
https://github.com/Vincit/objection.js/issues/2142

**Comment by LordA98** [comment]
For anyone wondering, if you go down the route of adding the ajv-formats package and creating a property with `type: string` and `format: date-time` - the easiest way to get a value that matches this format is `new Date().toISOString()`.

Wasn't obvious to me so thought I'd add a note.
