### ISSUE TITLE
Naming convention for relation mappings

### ISSUE THREAD

**Issue by KrisLau** [Vincit/objection.js#2171]
So I'm trying to figure out if the relation mapping objects should be the table name or if it's just arbitrarily decided by me? Also if it is arbitrary, is it supposed to be snake_case or camelCase?

Example:
```
class Animal extends Model {
    static get tableName() {
        return 'animal';
    }
    static get relationMappings() {
        return {
             // I know this could be shortened to just "species" but it's mainly for example's sake
            animal_species: { // should this be animalSpecies?
                ...
            }
        }
    }
}
```
another question is do relations have to be mutually mapped? Using the above example, would I also need to define a `HasManyRelation` on the `Species` table?

**Comment by devinivy** [comment]
It shouldn't have the same name as one of the attributes on your model, but beyond that it's pretty much up to you!  Camel-case and snake-case both work equally well— I would recommend choosing whichever fits the code style/lint of your project better.
