### ISSUE TITLE
typeError for pluck() with objection version 3.0.0

### ISSUE THREAD

**Issue by ilyanemtsov** [Vincit/objection.js#2172]
Knex version: "0.95.12"
Objection version: "3.0.0
node: node:16-alpine

Once Objection version was updated to latest(3.0.0), queries started to fail on `pluck()` and few other methods failed as well.
example of error is `TypeError: Person.query(...).orderBy(...).pluck is not a function`
any idea why `pluck()` stopped working ?

example:
this doesn't work anymore
`const ids = await Person.query().orderBy('id').pluck('id')`

i tried to look for some help and found Vincit/objection.js#1588
it works after removing pluck and substituting to this
`const ids = await Person.query().orderBy('id').then(members => members.map(member => member.id))`

according to knex:  ``If you are invoking it on a query builder, yes, if you are trying to execute it on a promise you get, no.
orderBy returns QueryBuilder, which has pluck method on it, so your given example should be fine.``

**Comment by koskimas** [comment]
`pluck` was deprecated in 1.x and removed in 3.x.
