### ISSUE TITLE
Typed queries?

### ISSUE THREAD

**Issue by Kameecoding** [Vincit/objection.js#2174]
Just started to play around with objection using Typescript and the one thing I can't seem to find is if there is any native way to reference only columns that are mapped on the Model class.

e.g. if I have a person
```
import { Model } from 'objection'

export default class Person extends Model {
    static tableName = 'person'
    
    id!: number;
    surname!: string;
    lastname!: string;
}
```

Then I would assume there is a way to use queries type safely, instead of having to use hard coded string keys?

```
//this is the way I found it works
Person.query().select('surname'); // -> what if someone makes a typo in 'surname'
// I won't know it until it fails during runtime which defeats the purpose of typescript a bit, doesn't it.

//Is there way a to reference existing, known columns? e.g.:

Person.query().select(Person.columns.surname);
```
Similar issue with where, etc.

I know I can basically create a static columns property with all the column names, but then couldn't/shouldn't be this done automatically so there is no need to repeat myself?

**Comment by koskimas** [comment]
Unfortunately this is very very difficult to implement while keeping all the current features. Objection was designed for javascript and the typings were added afterwards. I've implemented this kind of full type safety in [Kysely](https://github.com/koskimas/kysely). Just take a look at the tyoings in [this file](https://github.com/koskimas/kysely/blob/master/src/parser/table-parser.ts) and [this file](https://github.com/koskimas/kysely/blob/master/src/parser/select-parser.ts) to see how difficult it is when the "models" are simple interfaces. Objection models are much much more complex (relations, inheritable query builders) and for historical reasons, allow all kind of references.

**Comment by koskimas** [comment]
It's not only the columns of that model that can be referenced in SQL. It's also all the joined table's columns, all CTEs etc. Also you can join a subquery with a weird select that again needs to be taken into account. Only naively allowing the model's columns in `select` or `where` would drop about 90% of objection's features.
