### ISSUE TITLE
Custom whereIn of custom query builder not invoked with withGraphFetched

### ISSUE THREAD

**Issue by rgoomes** [Vincit/objection.js#2175]
This is a follow up of issue #2096. I have created a custom query builder as suggested in the comments. It looks like this:
```ts
class CustomWhereInQueryBuilder<M extends Model, R = M[]> extends QueryBuilder<M, R> {
    ArrayQueryBuilderType!: CustomWhereInQueryBuilder<M, M[]>;
    SingleQueryBuilderType!: CustomWhereInQueryBuilder<M, M>;
    NumberQueryBuilderType!: CustomWhereInQueryBuilder<M, number>;
    PageQueryBuilderType!: CustomWhereInQueryBuilder<M, Page<M>>;

    whereIn: WhereInMethod<this> = (...args) => {
        console.log('whereIn', args);
        return super.whereIn.apply(this, args);
    };

    where: WhereMethod<this> = (...args) => {
        console.log('where', args);
        return super.where.apply(this, args);
    }
}
``` 
This is how I set the custom query builder and how my query looks like:
```ts
export class UserModel extends Model {
    ...
    static get QueryBuilder() {
        return CustomWhereInQueryBuilder;
    }
}

await UserModel.query().withGraphFetched('[inventory]').where(true);
```
which produces the following output:
```txt
where [ true ]
[
  UserModel {
    id: 1,
    name: 'name',
    inventory: UserInventoryModel { user_id: 1, coins: 300 }
  }
]
```
As you can see it did not enter the custom `whereIn`, but it did execute the custom `where`. 

What am I doing wrong? I can fully provide both model files if necessary.

**Comment by koskimas** [comment]
The inventories are not of class `UserModel`. The inventories are fetched using the `InventoryModel`. You need to install the custom query builder for that model too.

**Comment by rgoomes** [comment]
> The inventories are not of class `UserModel`. The inventories are fetched using the `InventoryModel`. You need to install the custom query builder for that model too.

@koskimas I had already tried that with no success. These are the models:
```ts
// user-inventory-model.ts
export class UserInventoryModel extends Model {
    static tableName = 'user_inventory';
    static idColumn = 'user_id';

    static get QueryBuilder() {
        return CustomWhereInQueryBuilder;
    }

    static tableMetadata() {
        return { columns: ['user_id', 'coins'] };
    }

    static relationMappings = {
        user: {
            relation: Model.BelongsToOneRelation,
            modelClass: require('./user-model').UserModel,
            join: {
                from: 'user_inventory.user_id',
                to: 'user.id'
            }
        }
    };

    user_id!: number;
    coins!: number;
}

// user-model.ts
export class UserModel extends Model {
    static tableName = 'user';
    static idColumn = 'id';

    static get QueryBuilder() {
        return CustomWhereInQueryBuilder;
    }

    static tableMetadata() {
        return { columns: ['id'] };
    }

    static relationMappings = {
        inventory: {
            relation: Model.HasOneRelation,
            modelClass: require('./user-inventory-model').UserInventoryModel,
            join: {
                from: 'user.id',
                to: 'user_inventory.user_id'
            }
        }
    };

    id!: number;
    name!: string;
}
```
Produces the same output. Is this incorrect?

**Comment by koskimas** [comment]
Don't know what to tell you. That' seems correct and objetion has a bunch of tests that prove it works. You are also doing something else wrong that is not in either of these files.

**Comment by rgoomes** [comment]
@koskimas please take a look at my code [test.zip](https://github.com/Vincit/objection.js/files/7728285/test.zip). It's a fully complete test.   

I'm compiling with `tsc -t es6 *.ts --downLevelIteration --module commonjs`. In order to reproduce the situation a postgresql database is needed with data. There's a `test.sql` for that and then I created some records with `INSERT INTO "user" (name) VALUES ('name');` and `INSERT INTO "user_inventory" (user_id, coins) VALUES (1, 300);`  

Can you see something wrong in the files? I started using the BaseModel that is suggested in Objection.js documentation, but still the custom `whereIn` is not invoked.

**Comment by koskimas** [comment]
Sure, if you bake me a cake and do my laundry for a week.

**Comment by rgoomes** [comment]
> Sure, if you bake me a cake and do my laundry for a week.

Instead, I can make a unit test that fails this use case just to show how good objection tests are. I'll even open a pull request for objection. Take it or leave it.

**Comment by koskimas** [comment]
If you can do that, I'll happily fix the bug. But I'm guessing you are having hard time making that happen.

**Comment by koskimas** [comment]
Actually, there is no bug. You are overriding the wrong method. `whereInComposite` is called internally by `withGraphFetched` and not `whereIn`.

**Comment by rgoomes** [comment]
> Actually, there is no bug. You are overriding the wrong method. `whereInComposite` is called internally by `withGraphFetched` and not `whereIn`.

That seems to be the case, yes.
> `withGraphFetched` (and I think also the `eager` method in the old objection) uses the objection query builder's `whereIn` method. You can [override the query builder's whereIn method](https://vincit.github.io/objection.js/recipes/custom-query-builder.html#custom-query-builder-extending-the-query-builder) with your own implementation. Ultimately objection calls knex's `whereIn` method that does the actual query building, but you could call `where(raw('YOUR SQL'))` in your custom implementation.

However, this comment in the other issue clearly mentions `whereIn` and not `whereInComposite`. There is no mention of `whereInComposite` in that issue and even the custom query builder suggested in the comments doesn't override `whereInComposite`.

Thanks for everything.
