### ISSUE TITLE
Error putting withGraphJoined inside modifiers

### ISSUE THREAD

**Issue by joneldiablo** [Vincit/objection.js#2176]
Hi!
I having this error when I try to get related data from one table:

```
UnhandledPromiseRejectionWarning: Error: table metadata has not been fetched. Are you trying to call toKnexQuery() for a withGraphJoined query? To make sure the table metadata is fetched see the objection.initialize function.
```

I have a "SessionModel" which have a relation to  "UserModel" and it has the modifier "session" like this:
```
session: builder => {
      builder.withGraphJoined('[roles, permissions, rolesPermissions, groups]')
    },
```
then, when I try to do this request:
```
session = await SessionModel.query()
      .findOne({ 'sessions.active': 1, client: data.UserAgent, token })
      .withGraphJoined('user(session)');
```
the system throws the metadata error.

..... but if I do:
```
session = await SessionModel.query()
      .findOne({ 'sessions.active': 1, client: data.UserAgent, token })
      .withGraphJoined('user.[roles, permissions, rolesPermissions, groups]');
```
works ok.
=============
I think this is an error
I have  "objection": "^3.0.0"

**Comment by koskimas** [comment]
It makes no sense to call `withGraphJoined` on a subquery. Use `joinRelated` instead. `withGraphJoined` is just `joinRelated` + parsing of the result into a tree structure. The subquery will never have a result, so there's nothing to parse.

```js
session: builder => {
      builder.joinRelated('[roles, permissions, rolesPermissions, groups]')
    },
```

**Comment by joneldiablo** [comment]
thanks a lot!!!

**Comment by joneldiablo** [comment]
!!!
Hi, I have new error here, if I put
```
session: builder => {
      builder.joinRelated('[roles, permissions, rolesPermissions, groups]')
    },
```
into the modifiers
the request:
```
session = await SessionModel.query()
      .findOne({ 'sessions.active': 1, client: data.UserAgent, token })
      .withGraphJoined('user(session)');
```
works OK.
But now this not work:
```
const user = await UserModel.query().findOne({ userName })
      .orWhere({ email: userName }).modify('session');
``` 
this returns nothing always

**Comment by lopezvit** [comment]
I was running in the same problem. At the end I used `leftJoinRelated` instead of `joinRelated` and that worked.
