### ISSUE TITLE
Unable to access properties for aggregate functions output

### ISSUE THREAD

**Issue by lesley2958** [Vincit/objection.js#2180]
Code example below: 

``` typescript
const maximum = await Post.query().max('numberLikes as likes').where({ authorId: 1 });  // Post { likes: 3 } 
console.log(maximum[0].likes);  // returns error that property does not exist
```

instead of an error, i'd expect it to return `3`. 

I found this workaround:
``` typescript
const maximum = await Post.query().max('numberLikes as numberLikes').where({ authorId: 1 });  // Post { numberLikes: 3 } 
console.log(maximum[0].numberLikes); // 3
```
But this isn't very elegant & this seems more like a bug since other methods that return a Model instance allow you to access properties without a workaround.

**Comment by koskimas** [comment]
You can use the `castTo` method to cast the type. It's unfortunately impossible at this point to make the types support that automatically.

**Comment by lesley2958** [comment]
Does that work for aggregate functions in the first code sample above? Or would I have to reuse a column name like I did in the second example? 

The following also does not work:

``` typescript
const minimum = await Post.query().min('numberLikes as likes').castTo<Post[]>();
console.log(minimum[0].likes) // errors out 
console.log(minimum[0].numberLikes) // returns undefined
```

**Comment by lesley2958** [comment]
Ah, I see. I'd have to define an interface first:

``` typescript
const minimum = await Post.query().min('numberLikes as likes').castTo<Post[]>();
console.log(minimum[0].likes) // 2
console.log(minimum[0].numberLikes) // errors out
```

**Comment by koskimas** [comment]
A type "literal" is also fine

```ts
const minimum = await Post.query()
  .min('numberLikes as likes')
  .castTo<{ likes: number }[]>();
