### ISSUE TITLE
Typescript runs much faster when QueryBuilderType is an interface rather than class?

### ISSUE THREAD

**Issue by Linksku** [Vincit/objection.js#2181]
When I added a custom QueryBuilder based on the guide (https://vincit.github.io/objection.js/recipes/custom-query-builder.html), Typescript took a long time to run. I noticed if I made `QueryBuilderType` an interface instead of a class, it runs in about half the time (35s vs 1min). This is roughly the same speed as before I added a custom QueryBuilder.

Before:

```
class MyQueryBuilder<M extends Model, R = M[]> extends QueryBuilder<M extends Model, R = M[]> {
  myMethod(): this {}
}

class BaseModel extends Model {
  QueryBuilderType!: MyQueryBuilder<this>;
  static QueryBuilder = MyQueryBuilder;
}
```

After:
```
interface MyMethods {
  myMethod(): this;
}

class MyQueryBuilder<M extends Model, R = M[]>
  extends QueryBuilder<M extends Model, R = M[]>
  implements MyMethods {
  myMethod(): this {}
}

interface MyQueryBuilderInterface<M extends Model, R = M[]>
    extends QueryBuilder<M, R>, MyMethods {}

class BaseModel extends Model {
  QueryBuilderType!: MyQueryBuilderInterface<this>;
  static QueryBuilder = MyQueryBuilder;
}
```

I don't know why this is faster, any ideas? If this is safe to do, maybe you can change the guide to this method.

Related SO question about Objection TS speed: https://stackoverflow.com/questions/70459685/prevent-typescript-compiler-from-checking-entire-classes-to-save-time

**Comment by koskimas** [comment]
The speed problems are a bug in the type or typescript itself. 35 seconds is still way too much. We shouldn't pollute the documentation with hacks to work around a problem that should be fixed.

**Comment by koskimas** [comment]
The speed problems are a bug in the type or typescript itself. 35 seconds is still way too much. We shouldn't pollute the documentation with hacks to work around a problem that should be fixed.
