### ISSUE TITLE
Nested to Death.

### ISSUE THREAD

**Issue by Steviey** [Vincit/objection.js#219]
Any idea how I get my model object a level deeper to the query part? 

C:\MyPorn\SQLITE3_ORM\node_modules\bluebird\js\release\debuggability.js:864 Unhandled rejection TypeError: model.query is not a function
    at file:///C:/MyPorn/HTML5/SQLITE3_ORM/js/PslSqliteDb.js:85:19
From previous event:
    at PslSqliteDb.insertData (file:///C:/MyPorn/HTML5/SQLITE3_ORM/js/PslSqliteDb.js:83:28)
    at file:///C:/MyPorn/HTML5/SQLITE3_ORM/js/invokeDummy.js:8:8

```
Class SqliteDb {
[...]
insertData(argsObj) {
        console.log(this.sortableTimestamp);
        var model = this.MinimalModel;
        this.schemaPromise.then(function (model) {
            
            model.query().insert(
                {
                    firstname: 'Hans',
                    surname: 'Meier',
                    comment: 'Ein Test',
                    sortabletimestamp: this.sortableTimestamp
                })
                //.debug()
                //.then(function (numUpdated) {console.log(numUpdated);})
                .catch(function (err) {console.log(err.stack);})
                return;
        })   
    }
[...]


let myTable   = 'Person';
let myDb      = 'example2.db';
let initDb    = new SqliteDb({tableName:myTable}); 
initDb.extendModel({tableName:myTable});
initDb.createDatabase({dBName:myDb});
initDb.createTable({tableName:myTable});
initDb.insertData({tableName:myTable});





```

**Comment by koskimas** [comment]
I have no idea what you are asking, but the problem is in the stack trace you copied. `TypeError: model.query is not a function`. `schemaPromise` obviously doesn't resolve to a model constructor.

**Comment by Steviey** [comment]
I'm not sure if I should/have to use the schemaPromise part derivied from one of your examples with the promise chain. Theoretically I could also write...

```
 insertData(argsObj) {
        console.log(this.sortableTimestamp);
        this.MinimalModel.query().insert(
            {
                firstname: 'Hans',
                surname: 'Meier',
                comment: 'Ein Test',
                sortabletimestamp: this.sortableTimestamp
            })
            //.debug()
            //.then(function (numUpdated) {console.log(numUpdated);})
            .catch(function (err) {console.log(err.stack);})

        return;
    }

```
Then my only problem would be a scoping problem with this.sortableTimestamp. I can't get it globally, or work in the query function.

Do I have to use promises, or would I be in danger otherwise?
