### ISSUE TITLE
Batch update

### ISSUE THREAD

**Issue by exhaler** [Vincit/objection.js#2194]
Is there a way to use objection to do a batch update? instead of doing this
```js
for (const productToUpdate of productsToUpdate) {
   await FeedProducts.query()
   .findById(productToUpdate.sku)
   .update(productToUpdate);
}
```
or a way to get the SQL syntax without executing the query
```js
const builder = Users.query()
  .findById(1)
  .toKnexQuery()

console.log(builder.toQuery())
```

**Comment by exhaler** [comment]
Managed to figured it out using `await Promise.allSettled(updateProductQueries);`

**Comment by atwright147** [comment]
Please add more info

**Comment by alvinlys** [comment]
`upsertGraph` not suitable for you?
