### ISSUE TITLE
Password field returned despite being omitted in`$formatJson()`

### ISSUE THREAD

**Issue by vedtam** [Vincit/objection.js#2195]
Hi,

I'm having a problem omitting the password field of my Member model. I use the bellow method (from the docs) to omit the password field, whenever the model get's queried, but _sometimes_ it still returns it:

```
$formatJson(json: any) {
  json = super.$formatJson(json);
  delete json.password;
  //test
  console.log({json});
  return json;
}
```

for example, here I'm asking for one user, here the password is removed just fine from the response:

```
export const one = async (req, res, next) => {
  try {
    const member = await Member.query().findById(req.body.id);
    res.status(200).send(member);
  } catch (e) {
    next(e);
  }
};
```

but here, in my email.ctrl where I'm sending a notification about new registrations, the password gets included into the response:

```
const notifyAdmin = async (id: number) => {
  const memberTest = await Member.query().findById(id);
  console.log({memberTest}) // <--- has the field: `password`:(

  new Email().send({msg: 'hello...'})
}
```

It's the same model, the same query, same process and there's not even a concurrency issue, what could cause the password field to be present despite omitting it in $formatJson() ?

An even simpler reproduction of the issue is querying the model right in my `server.ts` - file, as soon as the app starts via:

```
...
server.listen(process.env.PORT || 3000, () => {
  console.log(`Server listening on port ${process.env.PORT || 3000}`);
});

(async function() {
  const memberTest = await Member.query().findById(1);
  console.log({memberTest})
})();
```

Log output:

```
{
  memberTest: Member {
    id: 1,
    full_name: 'xxx xxx',
    email: 'foo@yahoo.com',
    password: '$2a$10$ci2lQqsvhNi3kWbxvlo42u4Mc/r86AdMJUal48Kxxxxxxxxx',
    role_id: 1,
    created_at: 2019-01-15T10:42:52.000Z,
    updated_at: 2022-01-14T10:12:03.923Z
  }
}
```

**Comment by koskimas** [comment]
You need to override the `$parseDatabaseJson` method. `$formatJson` is called when the model instance is serialized using `JSON.strigify` (when it's sent to the fronted).

**Comment by vedtam** [comment]
@koskimas Thanks! I got it now. Haven't noticed the difference between the two, sorry!
