### ISSUE TITLE
Object types such as the `Knex.Config` are not exported for importing types into application

### ISSUE THREAD

**Issue by mlerner-ml** [Vincit/objection.js#2196]
I'd like to create some wrapper functions for my applications around the Knex initializer in TypeScript. The `Knex.Config` interface is not reference-able. Is it possible to make it reference-able?

I'd like to be able to do something like
```TypeScript
import Knex from 'knex';

function wrapper(config: Knex.Config) {
    return Knex(config)
}
```

**Comment by koskimas** [comment]
How is this related to objection?
