### ISSUE TITLE
Get query raw column value as a int

### ISSUE THREAD

**Issue by KrisLau** [Vincit/objection.js#2198]
My query is returning a string for the `created_at` and `updated_at` columns (they are `timestampz` that I'm converting to millisecond precision unix timestamps) but I want it to be returned as an int/number. I need it as an integer because of my sync mechanism dictated by my local DB package. 

The timestamps were created like this: `timestamps(true, true)` 

#### Query code
```
 const columns = [
          'id',
          'description',
          raw('round(extract(epoch from created_at) * 1000)').as('created_at'),
          raw('round(extract(epoch from updated_at) * 1000)').as('updated_at')
        ];

const created = await Table.query().select(columns)
console.log(created);
```

#### Console.log result
```
[
  Table {
    id: '1',
    description: 'Banana',
    created_at: '1642701405550',    //not sure why this is a string
    updated_at: '1642701405550'    //not sure why this is a string
  },
  ...
]
```

#### Desired result
```
[
  Table {
    id: '1',
    description: 'Banana',
    created_at: 1642701405550,
    updated_at: 1642701405550
  },
  ...
]
```

#### Things I tried
- Casting the raw column query like this: `raw('CAST(round(extract(epoch from created_at) * 1000) AS bigint)').as('created_at')` but it didn't seem like it changed anything 
- Tested just removing the select but it just became a stringified DateTime
- `JSON.parse(created)` didn't work either which makes sense since it's an Object hahah
- Ran the raw sql in pgAdmin and the timestamps returned as numeric type

**Comment by koskimas** [comment]
You need to configure the database client to return the given data type as a number. Most database clients return 64bit (or larger) integers as strings because they don't fit insider javascript numbers. Javascript numbers can only hold 53 bit integers and everything larger than that gets truncated.

**Comment by KrisLau** [comment]
Not sure if this is the best way but I ended up doing this in the database setup based off this comment https://github.com/knex/knex/issues/3071#issuecomment-509429039
```
    const parseTimestamp = (val) => {
        return val === null ? null : new Date(val).getTime();
    };
    types.setTypeParser(builtins.TIMESTAMPTZ, parseTimestamp);
```
