### ISSUE TITLE
Multitenancy recipe

### ISSUE THREAD

**Issue by tgranqvist** [Vincit/objection.js#2201]
In the multitenancy example, model binding pattern, the map used as the cache is created **inside** the middleware handler and passed on to `getKnexForRequest`. Doesn't this  create a new, empty map on each request? Effectively not doing any caching at all.

I'm talking about [this recipe](https://vincit.github.io/objection.js/recipes/multitenancy-using-multiple-databases.html#model-binding-pattern).

**Comment by devinivy** [comment]
That's correct, and it was recently fixed here: https://github.com/Vincit/objection.js/pull/2179.  I expect that the docs will be updated next time the site is built.

**Comment by lehni** [comment]
Sadly it looks like the site hasn't been rebuilt, and the automatic building on doc changes is broken?

**Comment by lehni** [comment]
@koskimas could you shine some light as to how the site is generated and what triggers updates of it? Is there anything I need to do manually to do so?

**Comment by lehni** [comment]
i've just figured out how to build the site, all good :)
