### ISSUE TITLE
Get IDs of query as a flat array instead of an object

### ISSUE THREAD

**Issue by KrisLau** [Vincit/objection.js#2202]
So right now I'm querying a table like this `Table.query().select('id').where('description', 'fruits')` and that's returning:
```
[
    {"id": "12345678-1234-5678-0123-123456789012"},
    {"id": "01234123-1234-5678-0123-123456789012"},
]
```
I was hoping to get an array like this:
```
["12345678-1234-5678-0123-123456789012", "01234123-1234-5678-0123-123456789012"]
```

I know there are ways for me to extract it with JS like with `.map` but I was wondering if there was a more efficient/in built method in Objection that would allow me to do the same thing?

**Comment by KrisLau** [comment]
Found `pluck` on the `lodash/fp` library thanks to this issue: https://github.com/Vincit/objection.js/issues/1588

**Comment by devinivy** [comment]
An objectiony idea for you.  You could add a model modifier that does the following:
```js
modifiers = {
    selectIds: (query) => {
        const getId = (model) => model.$id();
        return query
            .select(query.modelClass().idColumn)
            .runAfter((models) => models.map(getId))
    }
};

// ...

const ids = await MyModel.query().modify('selectIds');
```
