### ISSUE TITLE
$beforeUpdate precision not the same as migration & seeding

### ISSUE THREAD

**Issue by KrisLau** [Vincit/objection.js#2209]
Hi, I've been trying to implement a base model that implements `$beforeUpdate` methods to set the timestamps based of this doc: https://vincit.github.io/objection.js/recipes/timestamps.html#timestamps. However I noticed that the precision of the timestamps for the `$beforeUpdate` was not the same as the ones that were set during the migration using `timestamps(true, true)` or even the one i created with `timestamp('created_at', {useTz: true}).defaultTo(knex.fn.now());`. 

Screenshot:
![image](https://user-images.githubusercontent.com/46275463/151611067-99732ea4-0d2e-4cdb-af19-e9dd5086743b.png)
The top two were automatically updated by objection/postgres when i inserted the record and the bottom one is the one where it was updated by the `$beforeUpdate`

I tried looking through the implementation of the `knex.fn.now()` and it seemed to just be `Date.now()` but when I tried setting `this.updated_at = Date.now()`, it seems like it just fails silently. I also tried `new Date(Date.now()).toISOString()` but the precision of that stayed the same as just doing `new Date().toISOString()`

**Comment by koskimas** [comment]
`knex.fn.now()` adds an SQL statement that generates the timestamp _inside the database_. `Date.now()` has lower precision than the date library inside the db.

**Comment by KrisLau** [comment]
@koskimas how do I use knex.fn.now inside the `$beforeUpdate`? When i do it the same way I did in my seeding, it doesn't seem to update?

**Comment by KrisLau** [comment]
@koskimas how do I use `knex.fn.now` inside the `$beforeUpdate`? When i do it with `knex.fn.now` the same way I did in my seeding, it doesn't seem to update?

**Comment by KrisLau** [comment]
@koskimas how do I use `knex.fn.now` inside the `$beforeUpdate`? When i do it with `knex.fn.now` the same way I did in my seeding, it doesn't seem to update the timestamp? Or is there some other way I should be doing the `$beforeUpdate` to get the same level of precision?

**Comment by koskimas** [comment]
I recommend using a database trigger and moving the whole thing to the db side.

**Comment by KrisLau** [comment]
What I ended up using:
```
CREATE OR REPLACE FUNCTION fn_update_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql AS
'
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
';
```
```
DO $$
DECLARE
    t text;
BEGIN
    FOR t IN
        SELECT table_name FROM information_schema.columns WHERE column_name = 'updated_at'
    LOOP
        EXECUTE format('CREATE TRIGGER tr_update_timestamp
                    BEFORE UPDATE ON %I
                    FOR EACH ROW EXECUTE PROCEDURE fn_update_updated_at()', t,t);
    END loop;
END;
$$ language 'plpgsql';
```
Source: https://stackoverflow.com/questions/34818544/postgresql-how-to-add-multiple-table-for-one-trigger
