### ISSUE TITLE
Tutorial need to fix, sqlite3 connector no longer supported

### ISSUE THREAD

**Issue by bianyuanop** [Vincit/objection.js#2214]
Installation page guidance need to fix: https://vincit.github.io/objection.js/guide/installation.html

by running `npm install knex`, it will install it with version `1.0.1`. Then we will rush into trouble that sqlite3 is no longer supported by knex now. 

There is a part of changelog

1.0.0 — 16 January, 2022
Breaking changes
Dropped support for Node 10;
**Replaced unsupported sqlite3 driver with @vscode/sqlite3;**

**Comment by catpea** [comment]
I wanted to add some extra information here.

Command line is reporting wrong instructions (hint), and the website is pointing to sqlite3 where it may need to say '@vscode/sqlite3' until whatever is going on is solved.

Here is the misleading text on website:
https://vincit.github.io/objection.js/guide/installation.html 

I get an error instructing me to:

```
Knex: run
$ npm install sqlite3 --save
```

But upon running that it says:

```
Cannot find module '@vscode/sqlite3'
```

You may need to change

```
Knex: run
$ npm install sqlite3 --save
```

to

```
Knex: run
$ npm install @vscode/sqlite3 --save
```
(I am sure you are aware of this, I am just reporting more info. I apologize for not having the time to read up on what is going on.)

**Comment by bianyuanop** [comment]
Thanks for responding
