### ISSUE TITLE
Not allowed to batch insert into a MySQL8 server

### ISSUE THREAD

**Issue by santi6291** [Vincit/objection.js#2217]
Now allowed to execute batch inserts on MySQL8 server, Works fine when running with knex directly, maybe mysql2 client is not getting grouped together with the mysql/postgress client?

The following query works just fine using knex directly 
```
knex('plaid_account_meta')
	.insert([{
		account_id: '12345',
		type: 'abc'
	}, {
		account_id: '1574515',
		name: 'test'
	}])
	.onConflict('account_id')
	.merge();
```

but  get the error below when I try to run it using Objectionjs

```
PlaidAccountMeta.query()
	.insert([{
		account_id: '12345',
		official_name: 'abc3',
	},{
		account_id: '1574515',
		name: 'testName3',
	}])
	.onConflict('account_id')
	.merge();
```

```
error: Error: batch insert only works with Postgresql and SQL Server
      at InsertOperation.onBefore2 (/home/node/app/node_modules/objection/lib/queryBuilder/operations/InsertOperation.js:31:13)
      at QueryBuilder.callAsyncOperationMethod (/home/node/app/node_modules/objection/lib/queryBuilder/QueryBuilderOperationSupport.js:387:39)
      at /home/node/app/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1143:19
```

On the knex file:
```
client: 'mysql2',
version: '8.0',
```

**Comment by koskimas** [comment]
MySQL doesn't return the identifiers of the created rows. Kysely models can't be created for the result without identifiers. That's why it's not supported.

**Comment by santi6291** [comment]
That makes sense. In my opinion, I believe there should still be some support, and instead of returning a set of models, just a count or boolean. Especially since this in a sort creates a weird scenario where it removes a feature of knex. I would imagine having this feature would still be more beneficial than having to break out of using objection to make a knex query? or at least some clearer explanation as to why in the docs or error messages.
