### ISSUE TITLE
Add support for ajv-keywords

### ISSUE THREAD

**Issue by rafaljanicki** [Vincit/objection.js#222]
Hello,

Thanks for adding the ajv validator, it seems much of an improvement. However, as it kind of breaks handling of the regexp patterns (we have to provide strings instead of regexp) what leads to lack of possibility of providing flags to the pattern, would you mind adding a support for [ajv-keywords](https://github.com/epoberezkin/ajv-keywords#regexp)? Or at least a way to get the ajv object in order to bind with the keywords

Thanks

**Comment by koskimas** [comment]
JSON schema spec says that JSON schema itself must be json, therefore regexes must be strings. AJV is fully spec compliant and tv4 wasn't. 

We are currently adding support for ajv keywords in #210. Let's continue this discussion in there.
