### ISSUE TITLE
Error: Requests can only be made in the LoggedIn state, not the SentClientRequest state

### ISSUE THREAD

**Issue by KrisLau** [Vincit/objection.js#2227]
Error only showed up after migrating from postgres to mssql as my client. Full error:
```
(node:18556) UnhandledPromiseRejectionWarning: Error: Requests can only be made in the LoggedIn state, not the SentClientRequest state
    at Connection.makeRequest (...\backend\node_modules\tedious\lib\connection.js:2238:24)
    at Connection.commitTransaction 
```

**Comment by KrisLau** [comment]
fixed it by making sure all my queries were in transactions which seems a little strange

**Comment by koskimas** [comment]
These have nothing to do with objection. Figure out the differences between postgres and mssql languages and drivers and change the differences.
