### ISSUE TITLE
Question: How to handle parent -> grandchild relationships?

### ISSUE THREAD

**Issue by caschbre** [Vincit/objection.js#2228]
I have three primary tables setup, along with two join tables, creating a parent table -> child table -> grandchild table scenario.

Example: 

`Lessons <---> lesson_notes <---> Notes <---> notes_files <---> Files`

The relations between each of the three main Models works well. When I query the lessons, I can easily get all of the notes for that lesson.  If I query notes I can get all of the files for the notes.

What I'm investigating is can a relationship be setup on Lessons to easily get all files for a lesson... basically a many-to-many relationship that needs to go through two join tables instead of just one.

`Lessons <---> lesson_notes <---> notes_files <---> Files`

That way I could easily query Lessons.withGraphFetched('files').

Is that feasible?

**Comment by jeff3yan** [comment]
I've found that the easiest way to achieve this is to create an intermediate view to simulate a new join table (eg `lesson_files`).

**Comment by caschbre** [comment]
@jeff3yan Yeah, that's how I've approached in the past. I was curious if objectionjs offered some "built-in" alternative to handle that setup. Sounds like the view may be the best way at this time.

**Comment by JeongJuhyeon** [comment]
> I've found that the easiest way to achieve this is to create an intermediate view to simulate a new join table (eg `lesson_files`).

Do you mean you manually created a view in the DB?

**Comment by jeff3yan** [comment]
@JeongJuhyeon that's right, I think it's reasonable to setup some useful views if you want some specific relation querying via an ORM anyway.

You could maybe dynamically generate a temp view at runtime, if creating views isn't an option.

**Comment by lehni** [comment]
The question appears to have been answered, closing.
