### ISSUE TITLE
Column aliasing on RelationMapping.RelationJoin.RelationThrough.extra to avoid name collisions?

### ISSUE THREAD

**Issue by newhouse** [Vincit/objection.js#223]
First let me say that so far I'm very much liking Objection.js. It's got a lot of raw power, with a lot less bloat than other ORMs while still maintaining plenty of great conveniences (like RelationMapping). I've recently chosen it over Sequelize and Bookshelf (after migrating prior work from Mongo(ose)). It's great!

One handy feature I'm leveraging is the ability to provide ```modelClass``` and ```extra``` options when creating ```relationMappings``` that go ```through``` a join table. It's really useful to fetch information from a join table on your way through!

The problem I've encountered is when I put a column, say ```created_at``` into my ```extra``` array but a column with that name exists on both the ```RelationJoin.to``` and ```RelationThrough.to``` tables. It appears that in this case the related objects that are returned are using the value from the ```RelationThrough.to``` / ```extra``` table.  In this example, I would want to have _both_ ```created_at``` values as properties on the returned objects somehow. Perhaps allowing for aliasing the ```extra``` columns? e.g.:

```
// Suggestion 1:
extra: [ { 'created_at': 'join_table_created_at' }, { 'col_with_name_collision': 'non_colliding_name' } ];
// Suggestion 2:
extra: { 'created_at': 'join_table_created_at', 'col_with_name_collision': 'non_colliding_name' };
```

Oh, and trying to keep this also true at the same time would be great:

> Columns listed here are automatically joined to the related objects when they are fetched **_and automatically written to the join table instead of the related table on insert._**

**Comment by koskimas** [comment]
Thanks!

Sounds like a good addition! This should be pretty easy to implement. I'll take a look at this and if there are no obstacles I can't think of now, I'll implement this for 0.7 release. Probably will put this out with a patch release sooner since this won't break anything.

**Comment by newhouse** [comment]
That would be pretty slick and would help reduce my query amount in a few places. I'll keep an eye out for progress via this Issue. Thanks!

**Comment by koskimas** [comment]
Fixed in 0.7.0-rc.1.

**Comment by rodrigosanchezg8** [comment]
Please add this to the docs! It can be used like this `extra: {hierarchyStatus: 'status'},` where status is the colliding name

**Comment by koskimas** [comment]
@rodrigosanchezg8 It's there
https://vincit.github.io/objection.js/api/types/#type-relationthrough
