### ISSUE TITLE
use modifiers with arguments with withGraphFetched()

### ISSUE THREAD

**Issue by Artaud** [Vincit/objection.js#2234]
Is it possible to pass arguments to modifiers used in withGraphFetched() ?

The docs are full of examples on how to use modifiers without arguments such as 
```
const people = await Person.query()
  .withGraphFetched(
    '[pets(selectName, onlyDogs), children(orderByAge).[pets, children]]'
  )
```

but I couldn't find anything about passing arguments. Is this supported in Objection?

Thanks
Jiri

**Comment by jacobpgn** [comment]
It looks like there's an example of adding arguments to modifiers here: https://github.com/Vincit/objection.js/blob/23ce2af9efa1f75ba2d5a1c0f3fcd14de857553d/doc/api/query-builder/eager-methods.md?plain=1#L124-L149 – hope that helps!

**Comment by Artaud** [comment]
Thank you for your reply @jacobpgn  - I've read the documentation thoroughly searching for ways to pass arguments and saw this, but it doesn't solve the problem I'm facing, because it doesn't allow for dynamic arguments.
Let me be more specific.
I'm passing the argument to .withGraphFetched(arg) from my client app, and need to add a .where(id) clause for one of the relations in .withGraphFetched() - the where clause is dynamic, so I can't just bind the modifier arguments like the docs say.

I'm thinking that maybe .withGraphFetched doesn't allow this, but it maybe could with a small change to the code, right?
Currently the method accepts a string argument in the shape of:
`[relation1(modifier1, modifier2),relation2.[relation21(modifier3)]]`
This could be widened so it would accept:
`[relation1(modifier1('arg1', 'arg2'), modifier2),relation2.[relation21(modifier3)]]`
And pass the arg1, arg2 to the modifier1. I don't see any issues with parsing this.

Any ideas?

**Comment by jacobpgn** [comment]
I still think that part of their docs is what you're asking for, but maybe I've misunderstood what you mean by dynamic arguments! Here's how I'd use the current functionality to take a `dynamicId` input and apply it to one of the modifiers :

```js
class RelationA extends Model {
  static get tableName() {
    return "a"
  }

  static relationMappings = {
    relationBs: {
      relation: Model.BelongsToOneRelation,
      modelClass: RelationB,
      join: {
        from: "a.b_id",
        to: "b.id",
      },
    },
  }
}

class RelationB extends Model {
  static get tableName() {
    return "b"
  }

  static get modifiers() {
    return {
      modifyId(builder, id) {
        builder.findById(id)
      },
    }
  }
}

const dynamicId = "some_client_provided_id"

RelationA.query()
    .modifiers({
      findByDynamicId(builder) {
        builder.modify("modifyId", dynamicId)
      },
    })
    .withGraphFetched(`relationBs(findByDynamicId)`)

```

**Comment by romain130492** [comment]
> I still think that part of their docs is what you're asking for, but maybe I've misunderstood what you mean by dynamic arguments! Here's how I'd use the current functionality to take a `dynamicId` input and apply it to one of the modifiers :
> 
> ```js
> class RelationA extends Model {
>   static get tableName() {
>     return "a"
>   }
> 
>   static relationMappings = {
>     relationBs: {
>       relation: Model.BelongsToOneRelation,
>       modelClass: RelationB,
>       join: {
>         from: "a.b_id",
>         to: "b.id",
>       },
>     },
>   }
> }
> 
> class RelationB extends Model {
>   static get tableName() {
>     return "b"
>   }
> 
>   static get modifiers() {
>     return {
>       modifyId(builder, id) {
>         builder.findById(id)
>       },
>     }
>   }
> }
> 
> const dynamicId = "some_client_provided_id"
> 
> RelationA.query()
>     .modifiers({
>       findByDynamicId(builder) {
>         builder.modify("modifyId", dynamicId)
>       },
>     })
>     .withGraphFetched(`relationBs(findByDynamicId)`)
> ```

Alenouilla, thanks for that!

**Comment by lehni** [comment]
The terminology has changed, but there was a lot of discussion around this in the past:

https://github.com/Vincit/objection.js/issues/481#issuecomment-322648250

One way to pass arguments to modifiers (then: named filters) is still as suggested by @devinivy then: to use the use the builder's [context](http://vincit.github.io/objection.js/api/query-builder/other-methods.html#context).
