### ISSUE TITLE
How to go about altering a where clause

### ISSUE THREAD

**Issue by caschbre** [Vincit/objection.js#2238]
I know that I can add to a query build where clause with qb.where, qb.orWhereIn, etc. and those have been working great. However I recently came across a scenario where the query (via separate modifiers/logic) ends up like...

```javascript
Model.query().where('foo', 'bar').orWhere('abc', 'xyz')
```

Before that executes I need to change that to...

```javascript
Model.query().where(qb => 
  qb.where('foo', 'bar').orWhere('abc', 'xyz')
).whereIn('id', [123, 456]);
```

Essentially trying to figure out how to grab an existing where clause and wrap it and then add to it.

**Comment by koskimas** [comment]
There's no way to do that.
