### ISSUE TITLE
what does MSSQL buggy driver mean actually?

### ISSUE THREAD

**Issue by hsynlms** [Vincit/objection.js#2243]
[Docs](https://vincit.github.io/objection.js/api/model/static-properties.html#static-concurrency) says:

> The mssql default is needed because of the buggy driver that only allows one query at a time per connection.

I just wanted to know which driver it is and have more details about it if possible (maybe a detailed explanation and/or references).

**Comment by hsynlms** [comment]
There is still no explanation. So it does not seem to have any basis.

**Comment by devinivy** [comment]
I believe it was in reference to this behavior of the mssql driver: https://github.com/tediousjs/node-mssql/issues/491

**Comment by hsynlms** [comment]
@devinivy thank you.

I read the issue it seems is the behavior and is not because of a bug. As I searched on the tediousjs library's GitHub issues to get more, I found that internal queue feature dropped off in `mssql` driver v4. But I still have doubt to call the driver `buggy`.

https://github.com/tediousjs/node-mssql/issues/412
