### ISSUE TITLE
$relatedQuery and handling of 'OR' filters could be clearer

### ISSUE THREAD

**Issue by mtpoutanen** [Vincit/objection.js#225]
Writing a query like this:

```
organization
    .$relatedQuery('agreements')
    .patch({ validUntil: req.body.validUntil })
    .whereNull('validUntil')
    .orWhere('validUntil', '>', req.body.validUntil);
```

was meant to set a new validUntil date for all agreements where the validUntil date is either later or null for that organization. However the SQL that came out resulted in all agreements with a null validUntil field being updated:

```
update "agreement" set "validUntil" = ? where "validUntil" is null or "validUntil" > ? and "agreement"."organizationId" in (?) {2016-10-20, 2016-10-20, 1}
```

The correct way to write it is to wrap the where-conditions in a where-function builder like this:

```
organization
    .$relatedQuery('agreements')
    .patch({ validUntil: req.body.validUntil })
    .where((builder) => {
      builder
        .whereNull('validUntil')
        .orWhere('validUntil', '>', req.body.validUntil)
    })
```

Resulting in the following SQL (with behaviour as I expected in the first case):

```
update "representationAgreement" set "validUntil" = ? where ("validUntil" is null or "validUntil" > ?) and "representationAgreement"."organizationId" in (?)  {2016-10-20, 2016-10-20, 218}
```

I feel that  isn't immediately obvious how or where the final $relatedQuery-filter is added to the sql, so it might be worth it to add an extra warning to the documentation, print something in the console if an or-condition is outside of a builder function, or change the logic slightly here so that all filter conditions in a $relatedQuery are automatically wrapped in brackets.

**Comment by koskimas** [comment]
This hasn't attracted any attention during the year it has been open. This is also pretty nasty to implement, so I'm closing this.
