### ISSUE TITLE
Graph Expression Object returns null for childless graph

### ISSUE THREAD

**Issue by mkaynakk** [Vincit/objection.js#2254]
Hi,
When I use the `graphExpressionObject` method on a graph that has no children, it returns null instead of `$modify` information. May I know the reason for this? I didn't see any information about this in the document.

**My code block**
```
.withGraphFetched(`
    [
      games(
        filterNews, filterDeleted
      )
    ]
  `)
  .modifyGraph('games', builder => {
    console.log(builder.graphExpressionObject())
 }
```

**Actual behavior**

`return null`

**Expected behavior**
```
{
  '$name': 'games',
  '$relation': 'games',
  '$modify': [
    'filterNews',
    'filterDeleted'
  ]
}
```

**Comment by hsynlms** [comment]
He is curious about the repository and expects a different result so asks a question about it. Closing the issue without a reply is not nice @koskimas
