### ISSUE TITLE
Get list of errors with index on insertGraph array

### ISSUE THREAD

**Issue by zelid** [Vincit/objection.js#2264]
Hello,

I'm trying to insert array of objects using insertGraph like here:
https://github.com/Vincit/objection.js/blob/master/tests/ts/query-examples/graph-inserts.ts#L23

I expect to get a list of validation errors for each model in array with appropriate array index, but only one error (for one element in array is returned about missing required firstName) with:
```
  const body = [
    {
      // firstName: 'Jennifer',
      lastName: 'Lawrence',
    },
    {
      // firstName: 'Bradley',
      lastName: 'Cooper',
    },
  ]
  const insertedGraph = await Person.query()
        .insertGraph(body)
        .onError((err) => {
          console.log("validation error in callback: ", err);
        });
```

How to get list of all validation errors with valid array indexes to represent errors in UI form list?

Thanks!

**Comment by koskimas** [comment]
Not possible.
