### ISSUE TITLE
I believe the function resolveModel is wrong, or receiving the wrong parameter on certain occasions

### ISSUE THREAD

**Issue by BlueSialia** [Vincit/objection.js#2270]
I'm experiencing an issue where, when executing a `relatedQuery` for a `ManyToManyRelation` I get the "is not a subclass of Model or a file path to a module that exports one. You may be dealing with a require loop. See the documentation section about require loops.".

Debugging the code I've noticed in the file `lib/utils/resolveModel.js` the function `resolveModel` checks if the first parameter, `modelRef`, is an Objection.js model. In my case, the parameter `modelRef` contains the Objection.js model inside the property `default` of `modelRef`. That is, `isModelClass(modelRef.default) === true`.

I'm importing the models inside `relationMappings` to avoid loops, in case you are wondering.

Did I just stumbled on a bug or am I doing something wrong that causes the `resolveModel` to **almost** be correct?

**Comment by lehni** [comment]
I believe you are using ESM (`"type": "module"` in package.json), and dynamic `import()` to import the models inside the static `relationMappings` getter, correct? And your models are the default export of the dynamically imported file?

When using dynamic imports, you need to unwrap the default export yourself, something like:

```js
const MyModel = (await import('./MyModel.js')).default;
```

We could consider making `resolveModel()` detect and handle the case of dynamic imports of default exports, but what if you export your models named? Would you expect to unwrap this for you too? I doubt it's the job of `resolveModel()` to handle either of these situations.

**Comment by lehni** [comment]
I'm closing this in the absence of a response to my suggestion. I'm happy to reopen if the suggestion does not work.
