### ISSUE TITLE
[question] can I get ref to this row?

### ISSUE THREAD

**Issue by joneldiablo** [Vincit/objection.js#2275]
HI!!!!
Will it be possible to get a reference to the row being inserted? similar to references with isertGraph, for example:
```
await Model.query().insert({
  name:'fulano',
  workplace: 4,
  place:'#ref{this.id}-#ref{this.workplace}'
});
```
its there a way to do this?
this example the id is still unknow

**Comment by davidpaulhunt** [comment]
@joneldiablo have you tried using `ref`? [docs](https://vincit.github.io/objection.js/api/objection/#ref)

**Comment by lehni** [comment]
Closing in the absence of a response
