### ISSUE TITLE
Knex supports whereLike() as of v1.0.4 but via Model.query() it's not available. 

### ISSUE THREAD

**Issue by CodisRedding** [Vincit/objection.js#2285]
Knex now supports [whereLike() ](http://knexjs.org/guide/query-builder.html#wherelike) as of [version 1.0.4](https://github.com/knex/documentation/blob/ad67a3f7b86fcff696087fed7492b64a6f8bc1db/src/changelog.md) but when using it via Model.query() it's not available. (see pic below)

**Which objection version are you using?** ^3.0.0
**Which knex version are you using?** 1.0.7
**What are you doing?** Running a simple query with a knex whereLike() statement
**What code are you running?** node 14.19.0
**What is happening?** whereLike() is not available as a function even though I can use it directly via knex
**What are you expecting to happen instead?** whereLike() should be available to use

```
const response = await PharmacyScriptCounts.query()
            .withGraphFetched('PharmacyMdspMaster')
            .distinct('d_Pharmacy_MDSP_Master.MDSP_Brand_Name')
            .sum('Claim_Count')
            .sum('Virtual_Volume')
            .sum('Member_Count')
            .sum('Client_Cost')
            .sum('Current_Copay')
            .whereLike('d_Pharmacy_MDSP_Master.MDSP_Brand_Name', 'something%')
            .groupBy('d_Pharmacy_MDSP_Master.MDSP_Brand_Name');
```
* if I comment out whereLike() it responds, also moving whereLike up the chain doesn't matter
* if i use whereLike directly via knex() it works

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/1033604/173095687-72569ba4-f57d-497e-9b80-40a6770e3f9d.png">

**Comment by lehni** [comment]
Fixed in #2372
