### ISSUE TITLE
How to use TypeScript and MyModel.bindKnex(Knex);

### ISSUE THREAD

**Issue by jcwatson11** [Vincit/objection.js#2289]
Given:
1. class User exists and extends Model in my code.
2. I have two database connections defined as separate Knex objects:
     A. a mysql connection
     B. a SQL Server connection.
     (So using `Model.knex(k)` is not an option)
4. I'm trying to use TypeScript to bind those connections to each model using

`const m:User = User.bindKnex(knex).`

When I try to run this code, I get:

`[tsserver 2740] [E] Type 'typeof User' is missing the following properties from type 'User': UserId, Email, Password, $modelClass, and 35 more.`

The following does not produce the error, but I loose intellisense on const m.

`const m:any = User.bindKnex(knex);`

I've tried doing:

```
const m:any = User.bindKnex(knex);
const n:User = m;
```

This resolves the error on that line, but then when I try to use n.query()... I get:

`[tsserver 2576] [E] Property 'query' does not exist on type 'User'. Did you mean to access the static member 'User.query' instead?`

Obviously I must be doing something wrong. I can't find any examples online for how to do this properly in TypeScript. How can I get this to work?

I'm using TypeScript 4.3.2.

**Comment by lehni** [comment]
Closing this in the absence of more information.
