### ISSUE TITLE
It seems that .insertGraph is broken in 0.6.1

### ISSUE THREAD

**Issue by tsabolov** [Vincit/objection.js#229]
In 0.6.1 (in 0.6.0 too) the `insertGraph` method is seems to be broken. Checked it back in `0.5.5` (as `insertWithRelated`) and it works there.
In short, when inserting a graph an error is thrown that states that `column "COLUMN_NAME" of relation "MODEL_NAME" does not exist`, where `COLUMN_NAME` is a relation field of model `MODEL_NAME`.

**Comment by koskimas** [comment]
Can you please provide more information. `insertGraph` is not broken alltogether, there are hundreds of tests that make sure of that each time I release a build. Some part of it may be broken, which causes your particular code to break. This is why I need more information than that. 

The best way to get your bug fixed is to a test case or a standalone script that I can run, that reproduces your bug. If you are not willing to do that, then at least some context is needed. The graph you are inserting, the models that are involved etc.

**Comment by tsabolov** [comment]
@koskimas Sorry for judging too fast. It turned out totally my fault. I have forgot an empty `jsonSchema` in my models so the validation failed.
Thank you for the great library and for your near-instant reaction to issues :)
