### ISSUE TITLE
invalid JSON format for child component 

### ISSUE THREAD

**Issue by johnnyLai-coding-demo** [Vincit/objection.js#2290]
I have a very long query using queryBuild which joined many tables

```
  let queryBuilder = baseTable.query()
    .withGraphJoined('otherTable')
    .modifyGraph('vessel', (builder) => builder
      .select(GRAPH_SELECTED_COLUMNS.vessel)) ... joined many tables
```      
In SQL, it is something like 
```
SELECT customerName, customercity, customermail, salestotal FROM onlinecustomers AS oc INNER JOIN orders AS o ON oc.customerid = o.customerid INNER JOIN sales AS s ON o.orderId = s.orderId
```
This query return more than 100 fields, so I have a business requirement to allow to select the which fields returns every time user calls  the API So, I added an outer layer and the origin query become subquery

```
const outer = await VesselOwnership.query().from(queryBuilder.as('base_table_fullset'));
```
In SQL, it is something like 
```
select * from (select * from base table left join...)
```

It works, however the returning json result in invalid format for child component

It should be
```
    {
      "results": [
        {
          "id": 1399,
          "date": null,
          "other_contacts_id": 3,
          "car": {
            "id": 3724,
            "car_club": {
              "id": 64,
              "value": "car club, japan"
            }
          }
        }
      ]
      "totalCount": 69
    }
```

but now it returns

```
    {
      "results": [
        {
          "id": 1399,
          "date": null,
          "other_contacts_id": 3,
          "car":"id": 3724,
          "car":"car_club":"id": 64,
          "car":"car_club":"value": "car club, japan"
           
         }
        }
      ]
      "totalCount": 69
    }
```

my question is how to fix the formatting of child component?

**Comment by lehni** [comment]
The second output isn't valid JSON, how can it be returning that? Could you provide a simple reproducible example using the `reproduction-template.js` in the objection repo? This would help a lot with debugging and understanding this issue.

**Comment by lehni** [comment]
Closing this in the absence of new info.
