### ISSUE TITLE
When passing undefined value to findById function it returns first row

### ISSUE THREAD

**Issue by pwalczyszyn** [Vincit/objection.js#231]
This is very dangerous issue, when passing `undefined` value to `findById(id)` function it returns first row from queries table. I'm observing this issue on MySQL database.

**Comment by koskimas** [comment]
Should already be fixed. What version are you using?

**Comment by pwalczyszyn** [comment]
I'm on `^0.5.5`

**Comment by koskimas** [comment]
Yep, update to 0.6 and this will work.

**Comment by pwalczyszyn** [comment]
Thx :)
