### ISSUE TITLE
query row based on some row exists in a related table

### ISSUE THREAD

**Issue by pokhiii** [Vincit/objection.js#2313]
Consider the following 3 tables:

1. `book_components`
   id | title
   ---|-------
   1  | chapter 1
   2  | chapter 2

1. `file_versions`
   id | book_component_id  | file_id
   ---|--------------------|--------
   1  | 1                  | 1
   2  | 1                  | 2
   3  | 2                  | 3

3. `files`
   id | title       | category
   ---|-------------|---------
   1  | med.xml     | converted
   2  | req.xml     | source
   3  | doc.xml     | source

Now I want to fetch all the book components for which at least on file exists with category converted exists. So, for minimal example shown above, the query should return the row from `book_components` where `id = 1`. Because for that there exists a file converted file in the files table (`id = 1`).

Is there a way to do this via Objection?

**Comment by lehni** [comment]
You can do use `whereExists()` in conjunction with `Model.relatedQuery()` to do something like this:

```
query.whereExists(
  BookComponents.relatedQuery('files').where('category', 'source')
)
```

There's an example of this here: https://vincit.github.io/objection.js/guide/query-examples.html#delete-queries
