### ISSUE TITLE
UpsertGraph do not delete relation if it is undefined

### ISSUE THREAD

**Issue by ErlanBazarov** [Vincit/objection.js#2315]
We have an entity concept in our codebase. It doesn't always have all the properties for performance reasons. We fetch relations only if necessary. So, when upserting this entity, we want to ignore undefined relations. However, when the relation is null or empty for `hasManyRelations`, we want to delete that relation. Is it possible to do with `upsertGraph`, or is it default behaviour?

**Comment by lehni** [comment]
Yes this is possible, check the `relate` and `unrelate` options for upserts:
https://vincit.github.io/objection.js/guide/query-examples.html#graph-upserts

You can configure them globally with boolean values, or on a per-expression basis, as shown in this example here:

```js
const options = {
  // Only enable `unrelate` functionality for these two paths.
  unrelate: ['pets', 'movies.reviews'],
  // Only enable `relate` functionality for 'movies' relation.
  relate: ['movies'],
  // Disable deleting for movies.
  noDelete: ['movies']
};
```
