### ISSUE TITLE
How should groupBy and withGraphJoined be used together?

### ISSUE THREAD

**Issue by JakeTompkins** [Vincit/objection.js#2317]
I'm working on an application that frequently pulls data from multiple tables, and sometimes one or two of those columns need to be aggregated, usually with `sum`. In raw SQL, I would limit the columns selected and use `group by` to aggregate the columns that are not being summed. i.e.

```sql
select employees."firstName", employees."lastName", sum(earnings.amount)
from employees join earnings on employees.id = earnings."employeeId"
group by (employees."firstName", employees."lastName") where earnings."createdAt" = '2020-01-01'
```

However, when I try something similar in objection, it seems that `withGraphJoin`  automatically selecting `id` columns defeats the purpose of `groupBy` i.e.

```js
class Employee extends Model {
 static tableName = 'employees'

  static relationsMapping = {
   earnings: {
      modelClass: Earning,
      relation: Model.hasManyRelationship,
      join: {
        from: 'earnings.employeeId',
        to: 'employee.id'
      }  
    }
  }
}

class Earning extends Model {
 static tableName = 'earnings'

  static relationsMapping = {
   employee: {
      modelClass: Employee,
      relation: Model.belongsToOneRelationship,
      join: {
        from: 'earnings.employeeId',
        to: 'employee.id'
      }  
    }
  }
}


Employee.query()
.select('firstName', 'lastName')
.withGraphJoined({earnings: true})
.modifyGraph('earnings', builder => builder.sum('amount'))
.groupBy(
 "firstName", "lastName"
)
.where('earnings.createdAt', '2020-01-01')
```

EDIT:
added a where to illustrate that the query needs to select based on a column in the joined table

This seems to generate SQL that necessarily selects both `employees.id` and `earnings.id` so that it can properly hydrate model instances, but including those ids means that the `groupBy` will fail unless those IDs are included in the `groupBy`, but that makes the `sum` on `earnings.amount` meaningless since each earning would then be its own row.

I'm pretty confident that I'm missing something, but I've scoured the internet and the docs and haven't found a working example of this type of query. A little direction would be greatly appreciated.

**Comment by JakeTompkins** [comment]
This seems to be related to the implementation in issue #73 for reference. Once the ids of joined tables are selected, `groupBy` seems to be made useless

**Comment by JakeTompkins** [comment]
Update: I was able to confirm the behavior by making a slight alteration to an existing test.

```js
it('count of HasManyRelation', () => {
      return session.models.Model1.query()
        .select('Model1.*')
        .count('model1Relation2.id_col as relCount')
        .joinRelated('model1Relation2')
        .groupBy('Model1.id')
        .orderBy('Model1.model1Prop1')
        .then((models) => {
          expect(models[0].relCount).to.eql(3);
          expect(models[1].relCount).to.eql(2);
        });
    });

    it('groupBy and sum with withGraphJoined', () => {
      return session.models.Model1.query()
        .select('Model1.*')
        .count('model1Relation2.id_col as relCount')
        .withGraphJoined('model1Relation2')
        .groupBy('Model1.id')
        .orderBy('Model1.model1Prop1')
        .then((models) => {
          expect(models[0].relCount).to.eql(3);
          expect(models[1].relCount).to.eql(2);
        });
    });
```

The first is an existing test which passes, the second is the same test with `joinRelated` replaced with `withGraphJoined` and does not pass

**Comment by yachaka** [comment]
Encountered the same problem as of today and fixed this by replacing `withGraphJoined` by `joinRelated`
