### ISSUE TITLE
When passing undefined value to patchAndFetchById function it updates all rows

### ISSUE THREAD

**Issue by pwalczyszyn** [Vincit/objection.js#232]
This one is kinda related to #231 but I believe it's even more dangerous. When updating with `patchAndFetchById(id)` function and if value of `id` is `undefined` it will update all rows of table.

**Comment by koskimas** [comment]
Should be already fixed. What version are you using?

**Comment by pwalczyszyn** [comment]
I'm on `^0.5.5`

**Comment by koskimas** [comment]
Yep, update to 0.6 and this will work.

**Comment by pwalczyszyn** [comment]
Thx :)
