### ISSUE TITLE
Mapping One to Many relation to an enum linking table without id

### ISSUE THREAD

**Issue by OleksandrKuleshov** [Vincit/objection.js#2321]
Using postgres

I have two tables, Organization and OrganizationLocation(which has no id) and one enum (type) Location.

Organization can be in multiple locations, OrganizationLocation linking table links organization_id to location.

How can I map this one to many relation?

On insertGraph I am getting, `columnd id does not exist`

This is what I've tried so far

      `locations: {
        relation: Model.HasManyRelation,
        modelClass: OrganizationLocationModel,
  
        join: {
          from: `organization.id`,
          to: `organization_location.organization_id`,
        }
      },`

**Comment by JVBorges** [comment]
If you take a look at the Objection documentation, you'll notice that every table is required to have an identifier and the "id" column is the default one.

> Each model must have an identifier column. The identifier column name can be set using the [idColumn](https://vincit.github.io/objection.js/api/model/static-properties.html#static-idcolumn) property. [idColumn](https://vincit.github.io/objection.js/api/model/static-properties.html#static-idcolumn) defaults to "id". If your table's identifier is something else, you need to set [idColumn](https://vincit.github.io/objection.js/api/model/static-properties.html#static-idcolumn). A composite id can be set by giving an array of column names. Composite keys are first class citizens in objection.
[Model guide](https://vincit.github.io/objection.js/guide/models.html)

**Comment by lehni** [comment]
Closing since the question was answered.
