### ISSUE TITLE
Objection does not pass its context to the underlying Knex query builder

### ISSUE THREAD

**Issue by dryu** [Vincit/objection.js#2322]
I've been long wanting to add a proper SQL logging to my applications that rely on ObjectionJS/Knex . Such projects often rely on combination of Objection-initiated queries and Knex-initiated queries, so having a single place where logging for both could be configured would be very useful. Since Objection relies on Knex, it makes sense to set up an event listener on it to cover both scenarios. 

One can log SQL queries quite successfully if registering an event listener directly on knex like this:

```ts
db.on('query', (data) => {
  log.info("[%s] %s %j", data["__knexUid"], data.sql, data.bindings);
});
```
The problem is that for some unclear ObjectionJS does not pass its own context object to the underlying Knex query builder, and even though `queryContext` is available on `data` prop inside the above event handler, it is `undefined` even though a proper context object was assigned to the command that initiated the query. This prevents from passing custom props to be used in the logging (e.g. a custom logger handler) to the underlying knex logic.

Is there any reason for not passing the context down to knex or am I missing something here?

**Comment by lehni** [comment]
What do you mean with "`queryContext` is available on data prop inside the above event handler"? Is the key set, but the value is undefined?

**Comment by dryu** [comment]
Yes, that is what I meant.

**Comment by lehni** [comment]
Ok I see, Knex has the same concept, I wasn't aware.

You can work around this quite easily in a custom `QueryBuilder`:

```js
class QueryBuilder extends objection.QueryBuilder {
  toKnexQuery(knexBuilder) {
    return super.toKnexQuery(knexBuilder).queryContext(this.queryContext());
  }
}

class Model extends objection.Model {
  static QueryBuilder = QueryBuilder
}
```

Does this work for you, and would it suffice?

**Comment by dryu** [comment]
It certainly works, thank you for that!

**Comment by lehni** [comment]
That's great! I am closing this, I don't think we should do this by default and it's easy enough to add?
