### ISSUE TITLE
Type 'T' does not satisfy the constraint '{}'. error in toKnexQuery 

### ISSUE THREAD

**Issue by oljubuncic1** [Vincit/objection.js#2324]
Hello,

I am facing an issue where Typescript compilation fails if the `strictNullChecks` flags is set to `true`.
Typescript version: `4.8.4`
Objection version: `3.0.1`

```
node_modules/objection/typings/objection/index.d.ts:1011:58 - error TS2344: Type 'T' does not satisfy the constraint '{}'.

1011     toKnexQuery<T = ModelObject<M>>(): Knex.QueryBuilder<T, T[]>;
                                                              ~

  node_modules/objection/typings/objection/index.d.ts:1011:17
    1011     toKnexQuery<T = ModelObject<M>>(): Knex.QueryBuilder<T, T[]>;
                         ~~~~~~~~~~~~~~~~~~
    This type parameter might need an `extends {}` constraint.
```

Any help on how this should be resolved is appreciated.

**Comment by QHolmes** [comment]
This is related to #2307 Which hasn't been released yet. For now you may need to backtrack to typescript  `4.7.4`

**Comment by lehni** [comment]
#2307 has been released now. Is this still an issue?

**Comment by lehni** [comment]
Closing this in the absence of feedback.
