### ISSUE TITLE
Can unrelate unrelated a given instance?

### ISSUE THREAD

**Issue by mmmmmrob** [Vincit/objection.js#2327]
Confused about unrelate :(
In the docs I can use relate to connect two instances like this:

```
const actor = await Person.query().findById(100);
const movie = await Movie.query().findById(200);
await actor.$relatedQuery('movies').relate(movie);
```

I had expected to be able to unrelate the same way:

```
const actor = await Person.query().findById(100);
const movie = await Movie.query().findById(200);
await actor.$relatedQuery('movies').unrelate(movie);
```

That doesn't seem to be possible. Am I missing something?

**Comment by lehni** [comment]
`unrelate()` doesn't take arguments. If you run this, you'll get an error: `Don't pass arguments to unrelate(). You should use it like this: unrelate().where('foo', 'bar').andWhere(...)`

So in your case, you should be able to do:

```
await actor.$relatedQuery('movies').unrelate(). findById(200);
```
Or:
```
await actor.$relatedQuery('movies').unrelate().where({ id: 200 });
```
