### ISSUE TITLE
Support ability to configure ajv unknownFormats property

### ISSUE THREAD

**Issue by pwalczyszyn** [Vincit/objection.js#233]
I'm using custom format to serialize and deserialize certain properties. The underyling [ajv](https://github.com/epoberezkin/ajv) library is giving me following warning:
```
In the next major version it will throw exception. See option unknownFormats for more information
```

It would be nice to configure `unknownFormats` property to `ignore`.

**Comment by koskimas** [comment]
You can do this after the feature discussed in #210 has been implemented.
