### ISSUE TITLE
Add factory method to create new Model subclasses

### ISSUE THREAD

**Issue by zuck** [Vincit/objection.js#234]
It would be nice to have a factory method (expecially for ES5) to create new `Model` subclasses like in **Bookshelf.js** or **Sequelize.js**:

```
objection.model = function(name, options) {

  // Create a constructor.
  function ctor() {
    objection.Model.apply(this, arguments);
  }

  // Update ctor's name.
  Object.defineProperty(ctor, "name", { value: name });

  // Basic ES6 compatible prototypal inheritance.
  objection.Model.extend(ctor);

  // Assign all properties to new Model class.
  Object.keys(options || {}).forEach(function(key) {
    var property = options[key];
    if (typeof property === 'function')
      ctor.prototype[key] = property;
    else
      ctor[key] = property;
  });

  return ctor;
}
```

It would make `Model` definition a lot clearer, less error-prone and DRY! e.g.

```

var Person = objection.model('Person', {
  tableName: 'person',
  // ...
});
```

**Comment by zuck** [comment]
The declarative form could be used too, e.g.

```
var Person = objection.model('Person');

Person.tableName = 'person';
// ...
```

**Comment by koskimas** [comment]
There is no factory method to emphasize the fact that models are created using basic prototypal inheritance and without any additional magic. For the same reason relationMappings are as explicit as they are. You only have to write the extra couple of lines once per model. It's my oppinion that the extra lines help people new to the project understand how things work more quickly. For any non-trivial application the model definitions should be an insignificant part of the total code.

With ES6 there is no use whatsoever for the factory method. It would only be confusing. There should be little reason to use ES5 anymore anyways.

I will have to say no to this one.

**Comment by zuck** [comment]
I understand your point: it seems reasonable.

By the way, the **error-prone** and **verbosity** factors should be keep in more consideration, IMHO, especially on the `relationMappings` side...But this is another issue :wink:
