### ISSUE TITLE
Models with relations from different DBS

### ISSUE THREAD

**Issue by jsagethuboo** [Vincit/objection.js#2348]
Hello, do you have a solution/implementation example of having models with relationships between different databases?

For example we were planning to use inject models into repositories with the correct DB instance to which they correlate to example:

`injectedModel.withGraphFetched('[relationOnDifferentDB, relationOnSameDB]')
`
but it seems this assumes that all relations are on the same DB connection which was injected into the model which fails, has anyone encountered this issue or found a good solution?

**Comment by lehni** [comment]
Closing this in favour of #2349 which has more information.
