### ISSUE TITLE
Models with relationships across different databases

### ISSUE THREAD

**Issue by jsagethuboo** [Vincit/objection.js#2349]
Hello, do you have an example with models that contain nested relationships between different databases?

For example if you had an **Order** model which hasMany **Items**  which are on the same DB but then the **Items** have a manufacturer which is on another DB I know if they were non nested I would use two queries with different transaction knex connections:

```
        await order.$fetchGraph(
           '[items]',
          {transaction: this.ordersDB.getConnection()}
        )
```

 ```
       await order.$fetchGraph(
          '['items.manufacturer']',
          {transaction: this.manufacturerDB.getConnection()}
        )
```

But If like in my given example the relation is through a model which lives on the same DB but the relation on that model lives on another DB how would that be achieved?
 
Thanks for any support/guidance let me know if you need me to clarify anything

**Comment by lehni** [comment]
Given the current state of the library and its lack of a core maintainer, as well as more general question as to wether this pattern is even a good idea in general (See https://stackoverflow.com/questions/8561412/relationships-between-tables-from-different-databases for example), I am going to close this as as a wontifx. I hope you understand.
