### ISSUE TITLE
Access jsonschema from custom validator

### ISSUE THREAD

**Issue by danrvc** [Vincit/objection.js#2354]
Hi, 

I would like to access the default "static get jsonSchema()" object that being defined in the model via a custom validator.
Is there a way to do that?

Thanks in advance

**Comment by lehni** [comment]
If you're using a custom validator, you must be creating it from `static createValidator() {}`

You can simply pass on a reference to the model class (`this` inside the static method) to the constructor of your validator class, and store a reference there, e.g. called `modelClass`. Then you can use `this.modelClass.jsonSchema` in the validator.
