### ISSUE TITLE
whereIn doesn't throw error if it receives undefined value

### ISSUE THREAD

**Issue by haweecodes** [Vincit/objection.js#2366]
Recently discovered something that I think objection.js can handle to provide more query safety for its query builder functions. The `whereIn` function if receives an `undefined` value it omits the condition and runs the other queries chaining it. I suppose if objection throws an error if a value is not sql query valid it can enhance development experience more.

example: 

```typescript
const users = await Users.query(trx)
         .whereIn('id', userIds)
        .andWhere('type', '=', 'civilian')
        .andWhere('status', '=', 'PENDING');

``` 
If the `userIds` by any chance has undefined value it creates this query
```shell
 select * from users where type = 'civilian' and status = 'PENDING'
``` 
this updates all the data with those values. I understand this can be handled from developer side, but failing a non sql value can help this library in its overall usage.

**Comment by zhfahan77** [comment]
@haweecodes , I guess its not related to the library. Actually, in `Objection.Js` there is a feature `skipUndefined`, if applied

> If this method is called for a builder then undefined values passed to the query builder methods don't cause an exception but are ignored instead.

Here is the [Ref link](https://vincit.github.io/objection.js/api/query-builder/other-methods.html#skipundefined)
