### ISSUE TITLE
npm package is not up to date with master

### ISSUE THREAD

**Issue by rocketjsquirrel** [Vincit/objection.js#2367]
Recent commit `dbb20ae` is missing when I installed latest from npm so I had to install from the repo directly. 
In package.json I had to replace this: `"objection": "3.0.1",`with this: `"objection": "github:Vincit/objection.js",` 

If someone can update the package, I'd really appreciate it. My project the depends on objection deploys via ElasticBeanstalk and it fails installing npm packages via git.

**Comment by rocketjsquirrel** [comment]
Just incase anyone else is having issues with referencing the package in an elastic beanstalk deployment, the following entry worked: `"objection": "https://github.com/Vincit/objection.js/archive/master.tar.gz"`

**Comment by jorgebv** [comment]
@kibertoad I don't want to clutter the "future of objection" thread and saw this issue. I saw the release 3.0.2 includes commit dbb20ae which I was also needing. 3.0.2 passes the test suite of my codebase and also resolved the typescript compilation issues I was experiencing, enabling me to bump up my TS version. Not sure if you are looking for feedback on the version at this point but just wanted to share. Thank you!

**Comment by kibertoad** [comment]
Thank you for verifying it! I will close this issue now.

**Comment by rocketjsquirrel** [comment]
Thanks @kibertoad . It works for me, too.
