### ISSUE TITLE
Custom function in releated join

### ISSUE THREAD

**Issue by Sosiashvili** [Vincit/objection.js#2377]
Hello Team,

I need custom function in releated join... something like that...

```
.joinRelated('i18n(test)', function(e) {
e.on('i18n.product_id', "=", "test.id").on('i18n.lang_id', "=", raw("?", [lang_id])
})
```

```
static relationMappings = {
    i18n: {
      relation: Model.BelongsToOneRelation,
      modelClass: class i18n extends Model { static tableName = 'product_i18n' },
      join: {
        from: 'product.id',
        to: 'product_i18n.product_id'
      }
    }
  };
```

**Comment by lehni** [comment]
I believe this should already be possible through the modifiers that get passed on to the join query. I'm not certain what `test` is in the code above, it look there should be a relation for it. But as to the bit that handles language, you could try something like this:

```js
const langId = <…>

.modifiers({
  language: builder => builder.on('i18n.lang_id', "=", langId)
})
.joinRelated('i18n(language)')
```

**Comment by lehni** [comment]
I'm closing this in the absence of a response to my suggestion. I'm happy to reopen if the suggestion does not work.
