### ISSUE TITLE
objection@3.0.1 (latest) as published on NPM has an outdated `typings/objection/index.d.ts` which makes it incompatible with typescript@5.0.4 (latest)

### ISSUE THREAD

**Issue by pineapplemachine** [Vincit/objection.js#2381]
PR #2307 fixed a problem with the TypeScript typings in September 2022. However, the objection@3.0.1 package in my NPM install does not include this fix, and it is preventing me from building a TypeScript project that depends on objection.

You can see that the `index.d.ts` typings file on NPM does not match the typings file in this GitHub repository, and that it contains the issue that #2307 fixed: https://www.npmjs.com/package/objection?activeTab=code

Please publish a new version of the package which includes the up-to-date types!

**Comment by pineapplemachine** [comment]
Oh, I see that this is related to #2367 and that there was recently a 3.0.2 release. Though this is not very apparent on NPM, which still shows 3.0.1 as the latest version.

I was able to get my project building correctly by installing objection@3.0.2.

On this page you can see that there is a 3.0.2 release, but it is labeled as "next", and 3.0.1 is still labeled as "latest":

https://www.npmjs.com/package/objection?activeTab=versions

**Comment by lehni** [comment]
@kibertoad something seems to indeed have gone wrong a bit with the publishing: `3.0.2` has the `next` tag, while `3.0.1` still has the `latest` tag.

**Comment by koskimas** [comment]
The `next` tag is the default in package.json. You need to explicitly set the latest tag after running `npm publish .`.

**Comment by iamtomcat** [comment]
Not quite related, but there have been some good fixes put into the code base and could fix this issue along with doing another release.

**Comment by lehni** [comment]
3.0.3 is finally released and should fix this!
