### ISSUE TITLE
GitHub releases not kept up to date with NPM

### ISSUE THREAD

**Issue by RyanTheAllmighty** [Vincit/objection.js#240]
Hiya,

I've noticed a couple times that the releases in GitHub don't always sync up to whats published on NPM.

Such as right now there is no 0.6.1 on GitHub, only 0.6.0.

This makes it difficult to see exactly whats published and make sure my knex version is locked correctly to match objection.js.

**Comment by koskimas** [comment]
Sorry, fixed.
