### ISSUE TITLE
Support jsonschema v5 proposals

### ISSUE THREAD

**Issue by musou1500** [Vincit/objection.js#241]
Hi.
What do you think about enabling `v5` option of `ajv`?
Thanks.

**Comment by koskimas** [comment]
I actually thought it was already enabled 😬 I'll enabled it in the next release.

**Comment by musou1500** [comment]
thanks!!
I'm looking forward to next release!

**Comment by koskimas** [comment]
Fixed in 0.7.0-rc.1.
