### ISSUE TITLE
Question: ManyToMany Relationship updates - UpsertGraphAndFetch vs PatchAndFetchById

### ISSUE THREAD

**Issue by marksark** [Vincit/objection.js#2449]
Hi All!

I have seen the question about updating ManyToMany relationships a bunch and when trying something out I wanted to get some feedback on a workaround I found that seems to work for me.

Assuming a payload that includes a ManyToMany relationship data in the body:

`Model.query(trx).patchAndFetchById(ctx.params.id, ctx.request.body)`
will not update any relationships on a PATCH call but the following will:
`Model.query(trx).upsertGraphAndFetch(ctx.request.body, { relate: true, unrelate: true, noInsert: true, noDelete: true });`

My question is - if I use the upsertGraph and ensure it doesn't insert or delete anything is this a bad idea?

**Comment by lehni** [comment]
Did you read the warning about `upsertGraph()` here?

https://vincit.github.io/objection.js/guide/query-examples.html#graph-upserts

> My question is - if I use the upsertGraph and ensure it doesn't insert or delete anything is this a bad idea?

So the bottom line is, if there's another way to do so, then better use that way. In this case, you might find something here:

https://vincit.github.io/objection.js/guide/query-examples.html#relation-update-queries

**Comment by marksark** [comment]
just saw this @lehni. I definitely read the warning but our app has multiple many-to-many relationships that we needed to join and were hoping to do it at one time with upsertGraph limiting the number of API calls and custom code needed per endpoint! 
For now we removed all upsertGraph calls except for PATCH calls, and limited the scope to the following snippet below. I would love your thoughts if you don't mind taking a quick look at it:

```
// utils.js

  patchParams: {
    relate: true,
    unrelate: true,
    noDelete: true,
    noInsert: false, // Prevents insert new entity relations on patch request
  }

...
___________

User Route
___________

router.patch("/api/clients/:id", authorizeUser(CLIENT_UPDATE), async (ctx) => {
  try {
    const client = await Client.transaction(async (trx) => {
      // using this allows us to pass { ... "address": { id: (id) }  } to relate the new client to an existing address
      const client = await Client.query(trx).upsertGraphAndFetch(
        ctx.request.body,
        patchParams
      );
      return client;
    });
    return (ctx.body = client);
  } catch (err) {
    console.log(err, " err");
    ctx.status = err.status || 500;
    ctx.body = {
      message: err.message || err.data || "Oh No! Something went wrong!",
    };
    ctx.app.emit("error", err, ctx);
  }
});

```
