### ISSUE TITLE
Support for Views

### ISSUE THREAD

**Issue by hibearpanda** [Vincit/objection.js#245]
First off really appreciate your team's effort - really like objection!

Is there any support for querying views? I noticed there wasn't any mention of them in the docs and even in knex there isn't any interface for views. I'm guessing that I can't define views as models?

The reason I ask is I have an application with a very normalised database - a section of that database gets queried often but the data needed is scattered over several tables. Without denormalizing the schema, we are using a lot of eager queries to complete those queries. We are therefore looking into replacing some of those queries with views to reduce the number of eager queries needed.

**Comment by koskimas** [comment]
Have you tried creating creating a Model for a view? It should work.

**Comment by koskimas** [comment]
Did you solve this?

**Comment by koskimas** [comment]
This has been around for a while and without an answer to my questions. Closing this now. Feel free to reopen.
