### ISSUE TITLE
More examples and mentions in the docs about the glorious 'returning()' query building method

### ISSUE THREAD

**Issue by newhouse** [Vincit/objection.js#248]
I know you're on vacation, and I hope you're enjoying it! Still loving Objection as I get deeper and deeper, so thanks again!

I noticed in the docs that you nicely mention how, **_if you're using Postgres_**, you can chain a `returning(...)` to an `insert` to "get the same result without an additional query" as `insertAndFetch`. I think this is a great feature that's exposed, and a great suggestion in the docs.

After wondering if it would also work for `patch` queries, and upon seeing [these Postgres docs](https://www.postgresql.org/docs/9.1/static/sql-update.html), I tinkered around with Objection and found that it _is_ possible to leverage this pattern on `patch`, avoiding an additional query associated with `patchAndFetch`. This was a happy discovery, but this solution/trick is _not_ mentioned anywhere else outside of `insert` contexts, and I think users would really benefit by seeing it in the docs, or perhaps even in the cookbook with a bit more slickness.

```
// The only way the docs suggest: this performs 2 queries, right? 1 update and 1 select?
person
  .$query()
  .patchAndFetch({first_name: 'Jennifer'})
  .then(function(updatedPerson) {
    ...
  })
  .catch(...);

// Do the same thing in a single query with Postgres. Yay!
person
  .$query()
  .patch({first_name: 'Jennifer'})
  .returning('*') // Get the data back in a single query, yay!
  .then(function(updatedPeople) {
    let updatedPerson = updatedPeople[0];
    ...
  })
  .catch(...);

// Do the same thing in a single query with Postgres, but turn it into a single row returned. Double yay!
person
  .$query()
  .patch({first_name: 'Jennifer'})
  .first()  // Only deal with 1 row in the return, yay!
  .returning('*') // Get the data back in a single query, yay!
  .then(function(updatedPerson) {
    ...
  })
  .catch(...);
```

I did not try this out for `update` queries because I don't really use them, but I'd imagine it would work the same there as well?

Maybe even make a change to Objection that automatically "make single" the responses from `patch` (and perhaps `update`) queries that are built from instance queries starting with `$query`?
```
person
  .$query()
  .patch({first_name: 'Jennifer'})
  //.first() // No longer needed because Objection will .first() it for you since it's $query
  .returning('*') // Get the data back in a single query, yay!
  .then(function(updatedPerson) {
    // Objection has already applied .first() to the query, so single instance of person is returned
    // to promise resolution
    ...
  })
  .catch(...);

```

You guys are awesome!

**Comment by elhigu** [comment]
You are right, returning should work for all insert, update and patch queries with those databases that supports it (postgres, oracledb and mssql). I agree that mentioning about it would be good addition to documentation. 

About `$query().patch()` and `$query.update()` returning single element, I'm not sure if it would be confusing or good. I don't have strong opinion about it maybe slightly agreeing since I cannot think of any downsides in that solution. If one likes to do update / patch for multiple elements, they should do it through `.query()` anyways.

**Comment by newhouse** [comment]
Hi @elhigu  - Though I personally think it would be nice and seems intuitive to make the suggested `$query.patch().returning() → singleInstance` (especially if it's properly documented), it's of course up to you guys to decide what you think is best. I think even leaving it as is, but improving the docs would lead most people to find this way to get it done.

I'm glad you agree that the additional examples of the existing capabilities would be helpful. I'm happy to make a PR for the doc changes if I can figure it out and if it would be helpful for you?

**Comment by elhigu** [comment]
@newhouse maybe better separate these 2 issues now. 

1. I completely agree that documenting that `.returning()` works for all `update`, `patch` and `insert` queries would be good thing and will merge documentation PR for that without hesitation. 

2. For changing `$query.patch` and `$query.update` I would like to get input from more people, so could you open another issue for that and let's dedicate this one for the documentation update of `returning`.

**Comment by newhouse** [comment]
👍

**Comment by newhouse** [comment]
PR submitted: https://github.com/Vincit/objection.js/pull/249
