### ISSUE TITLE
OracleDB Dates

### ISSUE THREAD

**Issue by firrae** [Vincit/objection.js#250]
Hi there,

I love the library quite a bit, but I'm not sure if it is throwing the following error or the database is.

```
{ [Error: {
  "LOGDATE": "should be date"
}]
  data: { LOGDATE: 'should be date' },
  statusCode: 400,
  message: '{\n  "LOGDATE": "should be date"\n}' }
```

In the code block I define the LOGDATE field as a 'date' and looking at the OracleDB driver it says "Date and timestamp columns are mapped to JavaScript dates" so I'm passing a pure JS date to the insert query.

Am I doing something wrong or am I misunderstanding something?

**Comment by elhigu** [comment]
Hi, the underlying library `knex` has just recently got oracledb support, so there might be more bugs in comparison to postrgres or mysql. Also I have no experience how oracledb dialect handles different datatypes. It is really up to db driver (e.g. node-oracledb) how it requires that data should be passed, it might not support sending dates as javascript date objects.

You could try to pass date as ISO8601 string e.g. '2016-11-22'....  Do you have some example how to reproduce the problem?

**Comment by firrae** [comment]
Yea, I know it was new, but I wasn't able to tell the source of the error so I figured I'd start at the top layer in the abstraction. Currently the insert rejects ISO strings, JS dates, custom made strings like '22-11-2016' (that's our date style in the DB), as well as other date formats in string form.

Looking at the driver documentation it states that it should take a JS date object and map it to the appropriate DB format but as I said something along the line is saying that's not allowed.

In Objection is there type checking on the models or is that handled by Knex underneath? If it is then I shall move along the abstraction layers to them and ask them if they know the issue, otherwise I might jump straight to Oracle.

Thanks,

Steve

**Comment by elhigu** [comment]
You can check the created query by setting DEBUG=knex:* environment parameter. Then you can test e.g. on sqlplus console if that query should work and which kind of query actually should work with date type. Then it should be easy to figure out if the problem is in driver, knex or objection.

**Comment by elhigu** [comment]
Please reopen if this appears to be objection issue after all.

**Comment by firrae** [comment]
It was an error in the OracleDB driver, though I don't believe they have fixed it yet.
