### ISSUE TITLE
Need way to ignore relationships on * all recursive query

### ISSUE THREAD

**Issue by skn3** [Vincit/objection.js#260]
So I have a single page model setup that has:
child pages relation
parent page relation
external model relation

I want to recursively fetch a tree of page models, each having the external model relation.

As I have seen I have two options:

1. Use the provided * syntax to catch all relations
2. Manually build a finite depth in the relation syntax

I would be happy with option 1, however this causes an infinite loop. Because the parent relation back tracks on already touched data. Is it possible in current Objection to catch all relations, but ignore the parent one?

If not, perhaps could we have a syntax for this `[children.*, !parent]` or `.omitRelation('parent')` ?

**Comment by elhigu** [comment]
Maybe something like this works `[children.[all,relations,except,parent,children]]`? Of course it requires that you will list all the relations manually or maybe check them from Models relation declaration and omit parent from it.

Though I'm not against having specialised syntax for this either.

**Comment by skn3** [comment]
Your proposed solution looks great. I'd rather have a smaller number of queries by manually picking the ones I want.

**Comment by koskimas** [comment]
You can quite easily create a helper function that builds the relation expression you want. I don't think we should add a special syntax for this.
