### ISSUE TITLE
how to retrieve transaction in $beforeUpdate or $beforeInsert?

### ISSUE THREAD

**Issue by skn3** [Vincit/objection.js#262]
I have been unable to get the current transaction in these functions using any of the built in methods. I tried this.$transaction() or Model.transaction() and neither worked. I confirmed this by storing the transaction in a global variable and then using this in $beforeUpdate instead. It worked this way, but not with the Objection api.

The only way I have managed to retrieve the current transaction, is by storing it in the query context.

Here is how I am creating the transaction:
```
return objection.transaction.start(Page).then(function (transaction) {
    return Page.query(transaction).insert({name: 'page1'}).then(function(page){
        //update some pages here
        return page.$query(transaction).patch({count:123});
    });
});
```

Here is my $beforeUpdate:
```
function $beforeUpdate() {
        return Page.bindTransaction(this.$transaction()).query().then(function(results){
           console.log(results);
        });
}
```

I have trimmed the code as I don't have a standalone example. The result should basically be that it logs whatever page entries exist in the database. I can confirm that these entries exist if I swap this.$transaction() for a global variable that i stored when the transaction was started.

What am I doing wrong? Is this possible?

**Comment by koskimas** [comment]
context.transaction will point to the active transaction on the next minor version of objection. It is already implemented and just waiting for a release.
