### ISSUE TITLE
Is it possible to "override" the default FROM of a Model query?

### ISSUE THREAD

**Issue by Vectarian-Jorge** [Vincit/objection.js#2628]
When you have a Model `MyModel` any query executed with `MyModel.query()...` includes a FROM clause to `MyModel.tableName` (`public.my_model`, for example) by default. Is it possible to change/override that FROM for specific queries?

Is it possible to execute `MyModel.query().fromRaw('public.my_custom_model(?)', foo)...` somehow? 
I know I could create another model for this but `public.my_custom_model(?) ` has the same structure as `public.my_model` so everything I've implemented in `MyModel` (virtual columns, modifiers, hooks...) and every class extending `MyModel` will be valid for this new model too.

It would be more of a hassle to maintain everything if I need to have a new class just for this.

**Comment by Vectarian-Jorge** [comment]
It appears that in order to achieve this the [FromSelector](https://github.com/Vincit/objection.js/blob/main/lib/queryBuilder/QueryBuilderOperationSupport.js#L15) regex should include `fromRaw`. But that is not enough because with `fromRaw`, Objection.js understandably does not extract aliases so any `where` clause will use the original `MyModel.tableName` with the column names.

That results in invalid queries: `select * from public.my_custom_model(?) as my_custom_model where "public"."my_model"."id" = ?`

How can we assign an alias to a `fromRaw`?

**Comment by Vectarian-Jorge** [comment]
Figured it out. The trick is to use `aliasFor` to create a mapping from the original table name to whatever alias you used in the `fromRaw`. So something like:
```typescript
MyModel.query().fromRaw(`public.my_custom_model(?) as my_custom_model`, foo).aliasFor(MyModel.tableName, 'my_custom_model');
```

So in order to achieve what this issue is asking about only `fromRaw` needs to be added to the regex.

**Comment by Vectarian-Jorge** [comment]
Tagging @lehni to try to get some feedback on this.

**Comment by lehni** [comment]
@Vectarian-Jorge this seems reasonable. Apologies for taking so long to review it.
