### ISSUE TITLE
unable to update data with nulls or empty strings

### ISSUE THREAD

**Issue by maxwellsmart84** [Vincit/objection.js#265]
Env information:
mysql: Ver 14.14 Distrib 5.7.14, for osx10.11 (x86_64)
node: 6.9.2,
knex: 0.11.7,
objection: ^0.5.2

Here is the model I am using as an example.  As you can see I have "street2" schema set to string or null.  I have ran this same test with setting the property to only null with the same results.

<img width="718" alt="screen shot 2016-12-21 at 12 50 14 pm" src="https://cloud.githubusercontent.com/assets/14876902/21400026/1efaebf6-c77c-11e6-9ea4-543f791362b7.png">

Here is a screenshot of my database schema.  As you can see "street2" is allowed nulls.

<img width="424" alt="screen shot 2016-12-21 at 12 44 11 pm" src="https://cloud.githubusercontent.com/assets/14876902/21399836/4e9bf842-c77b-11e6-9fd1-986dea0ac0c2.png">

Here is my PUT request which is using the update() method with objection (see below).  This shot was taken after sending the request, below is the response.  As you can see, street2 did not update with null or an empty string value.

<img width="861" alt="screen shot 2016-12-21 at 1 33 09 pm" src="https://cloud.githubusercontent.com/assets/14876902/21401481/86ac50fe-c782-11e6-835f-d6447f4fb6fd.png">
<img width="979" alt="screen shot 2016-12-21 at 1 51 19 pm" src="https://cloud.githubusercontent.com/assets/14876902/21402037/bdc2076c-c784-11e6-846e-a696fd235d27.png">

Here is my code for the update query.  Location has a belongs to one relationship with address.  I know this test would probably be better by bypassing the relationship however I am importing the Address model  directly and running the query directly on the Address table/model.

<img width="749" alt="screen shot 2016-12-21 at 1 33 20 pm" src="https://cloud.githubusercontent.com/assets/14876902/21401488/8c6318e8-c782-11e6-8655-7fd69e7e4524.png">

<img width="466" alt="screen shot 2016-12-21 at 1 45 44 pm" src="https://cloud.githubusercontent.com/assets/14876902/21401840/d1218da6-c783-11e6-9534-c9f49827635a.png">

With the debug running you can see the two outcomes of running the above query.  The first is when I updated street2 (defaults to null in our seed file) to "APT B".  You can see the data is in the bindings array of the queryobject.  The 2nd update it is missing completely.  This behavior also occurs with empty strings ("").

<img width="860" alt="screen shot 2016-12-21 at 1 33 00 pm" src="https://cloud.githubusercontent.com/assets/14876902/21401487/8c5eefca-c782-11e6-894d-868404fb9e2f.png">

Here I am updating the database with straight knex.  And it works fine, this is leading me to believe this is a bug with Objection.

<img width="706" alt="screen shot 2016-12-21 at 2 00 10 pm" src="https://cloud.githubusercontent.com/assets/14876902/21402301/e077572a-c785-11e6-8ffd-1da9ffa1c7c7.png">

<img width="824" alt="screen shot 2016-12-21 at 2 01 37 pm" src="https://cloud.githubusercontent.com/assets/14876902/21402339/06b7b092-c786-11e6-84d7-fe2748774121.png">
<img width="494" alt="screen shot 2016-12-21 at 2 01 30 pm" src="https://cloud.githubusercontent.com/assets/14876902/21402342/091064ba-c786-11e6-869e-372f201ea5ff.png">

**Comment by koskimas** [comment]
I wrote a test case and it seems to work ok. Have you tried this with objection 0.6.X?

**Comment by maxwellsmart84** [comment]
Hey Koskimas - I just tested again with 0.6.2 and I get the same behavior

**Comment by koskimas** [comment]
These both tests work on all databases:

```js
      it('should be able to update to null value', function () {
        return Model1
          .query()
          .update({model1Prop1: null, model1Prop2: 100})
          .where('id', '=', 1)
          .then(function (numUpdated) {
            expect(numUpdated).to.equal(1);
            return session.knex('Model1').orderBy('id');
          })
          .then(function (rows) {
            expect(rows).to.have.length(3);
            expectPartEql(rows[0], {id: 1, model1Prop1: null});
            expectPartEql(rows[1], {id: 2, model1Prop1: 'hello 2'});
            expectPartEql(rows[2], {id: 3, model1Prop1: 'hello 3'});
          });
      });

      it('should be able to update to an empty string', function () {
        return Model1
          .query()
          .update({model1Prop1: '', model1Prop2: 100})
          .where('id', '=', 1)
          .then(function (numUpdated) {
            expect(numUpdated).to.equal(1);
            return session.knex('Model1').orderBy('id');
          })
          .then(function (rows) {
            expect(rows).to.have.length(3);
            expectPartEql(rows[0], {id: 1, model1Prop1: ''});
            expectPartEql(rows[1], {id: 2, model1Prop1: 'hello 2'});
            expectPartEql(rows[2], {id: 3, model1Prop1: 'hello 3'});
          });
      });
```

Are you absolutely sure the null values are present when the update operation is done? I'm unable to reproduce this.

**Comment by maxwellsmart84** [comment]
Well good news - it works, bad news im a moron.  Thanks for helping out here - it turns out one of our other functions was removing data that was null (a filter).  Thanks for you time and efforts on this one.

**Comment by koskimas** [comment]
😄 No problem.
