### ISSUE TITLE
$relatedQuery().insert() on a model instance sets id to null

### ISSUE THREAD

**Issue by kyrisu** [Vincit/objection.js#266]
I'm using the following query to update / insert person address info. 
```js
    Person
      .query()
      .patchAndFetchById(id, changes)
      .then(person => {
        if (person.addressId) {
          return person
            .$relatedQuery('address')
            .update(person.address);
        } else {
          return person
            .$relatedQuery('address')
            .insert(brand.address);
        }
      });
```

The update (first related query in the example) works, but if the person doesn't have an address I get the following error:

```
error: insert into "addresses" ("city", "id") values ($1, $2) returning "id" - null value in column "id" violates not-null constraint
```

`changes` variable contains the following info:
```js
{
  name: 'John',
  address: {
    city: 'London'
  }
}
```

I'm assuming I'm doing very similar query to the one in the [docs](http://vincit.github.io/objection.js/#_s_relatedquery) : 
```js
jennifer
  .$relatedQuery('pets')
  .insert({species: 'dog', name: 'Fluffy'})
  .then(function (waldo) {
    console.log(waldo.id);
  });
```

Unfortunately, it doesn't seem to work.

**Comment by koskimas** [comment]
Are you sure the `brand.address.id` is not null? If it is null, then you are trying to insert a null into `id` column. If it is not, there might be a bug.

**Comment by kyrisu** [comment]
Actually, it's undefined.

I've also tried doing just
```js
...
          return person
            .$relatedQuery('address')
            .insert({city: 'London'});
...
```

I've assumed this will leave the creation of the address id to the database, and that the new resulting entity will be "related" to the person entity.

**Comment by koskimas** [comment]
There is probably something wrong with your relationMappings. objection has 1500 tests and the basic insert case is tested hundreds of times. I simply don't believe that there is such a fundamental bug. Can you try to create a standalone `.js` file that reproduces the bug? Or a test case for the objection test suite?

**Comment by kyrisu** [comment]
I've created a [gist](https://gist.github.com/kyrisu/3dc04841d664c7a3bdc54060224c5a9a)

To save you time for setup this is what it returns:

```
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'London', null ],
  __knexQueryUid: '9fff3f81-4d0f-45ec-8328-82d92c68e80b',
  sql: 'insert into "addresses" ("city", "id") values (?, ?)' }
-----------------------------------------
[ { id: 1, city: 'London' } ]
[ { id: 1, name: 'Some Name', address_id: null } ]
```

As you can see it works because sqlite inserts default value on null, but in postgresql case (sorry for not mentioning it before) when I issue:

```sql
insert into "addresses" ("city", "id") values ('London', NULL)
```

it will complain with the following error:

```
19:05:46 Kernel error: ERROR:  null value in column "id" violates not-null constraint
```

Of course that might be my incorrect understanding of what $relatedQuery is supposed to do in this case. I assumed that using it this way it will insert a new row in the address table (issuing insert without id column specified), return Id from this insert and use it to update the address_id field in the person table.

Of course, I can accomplish the same with 3 separate queries but so far Objection is so awesome I somehow expected this level of magic ;).

**Comment by kyrisu** [comment]
After I've looked at it for the n-th time - what happens is that the patchAndFetchById() sets `address_id` to NULL which is later used in the $relatedQuery as the Id.

I expected NULL to be interpreted as a lack of value and that it won't be used in the related query, but I can understand that your perception may be different.

**Comment by koskimas** [comment]
`patchAndFetchById`only sets anything to null if there is a null value. If a value is missing, nothing is set (unless maybe if you have a default value in `jsonSchema` for the `address_id`.)

**Comment by koskimas** [comment]
Sorry, I missed your previous message. The gist confirmed my suspicion: address is a `HasOneRelation` when it should be a `BelongsToOneRelation` since `Person` has the foreign key.

**Comment by kyrisu** [comment]
It works like magic - as I initially expected :+1: 

Thank you very much for help! I would probably spend the next few hours before I would figure it out on my own.

**Comment by koskimas** [comment]
Happy to help!
