### ISSUE TITLE
Is there a way to extend the insert function in a customQueryBuilder so that it automatically handles duplicate key errors?

### ISSUE THREAD

**Issue by KrisLau** [Vincit/objection.js#2686]
I'm trying to upsert instead of insert but I cant seem to get this PR to work: https://github.com/knex/knex/pull/6050 

Because my tables have triggers to automatically update the created and updated timestamps on tables. so now I'm trying to extend the QueryBuilder for objection with a custom one so that all my inserts automatically handles the duplicate key error. How do I go about doing so?

I tried extending it but I end up causing and infinite loop because I'm calling .insert in the insert override. What should I be doing to handle duplicate key error for mssql?

**Comment by kapouer** [comment]
Documentation
https://vincit.github.io/objection.js/api/query-builder/mutate-methods.html#onconflict
examples:
https://github.com/Vincit/objection.js/blob/main/tests/integration/insert.js

**Comment by KrisLau** [comment]
> Documentation
https://vincit.github.io/objection.js/api/query-builder/mutate-methods.html#onconflict

Quote form the docs:
> Implemented for the PostgreSQL, MySQL, and SQLite databases

My issue is for mssql:
> What should I be doing to handle duplicate key error for **_mssql_**?

**Comment by KrisLau** [comment]
For anyone else who might run into this, the answer is that it doesn't work at all for mssql, [you shouldn't use merge at all](https://michaeljswart.com/2021/08/what-to-avoid-if-you-want-to-use-merge/), and you will basically just have to cobble together a solution by yourself in the `BaseModel` by creating your own method. 

This is what I ended up using in my `BaseModel` with a combination of lodash & existing objection methods:
```js
 static async insertMerge(trx, created) {
    await this.query(trx)
      .insert(created)
      .onError(async (error, _query) => {
        // 2627 is a primary key conflict error
        if (error.number === 2627) {
          const createdIDs = created.map(l => l.id);
          const conflicts = await this.query(trx).whereIn('id', createdIDs);
          const inserts = _.differenceBy(created, conflicts, 'id');
          const updates = _.differenceBy(created, inserts, 'id');

          if (inserts.length > 0) {
            await this.query(trx).insert(inserts);
          }

          if (updates.length > 0) {
            for (const x of updates) {
              const updateData = _.omit(x, ['id', ...any other columns you want to omit like timestamps]);
              await this.query(trx).where('id', x.id).patch(updateData);
            }
          }
        } else {
          return Promise.reject(error);
        }
      });
  }
```
