### ISSUE TITLE
Possible to `bindKnex` on an instance of a Model class?

### ISSUE THREAD

**Issue by newhouse** [Vincit/objection.js#273]
Hi there and thanks again for your work on Objection!

I've begun implementing a separation between read-only and read-write knex connections (based on the "multi-tenant" pattern) so I can achieve the following:

- Directing queries/connections to Master and Minion/Slave clusters appropriately.
- Using DB users/roles credentials that have only the required `SELECT, UPDATE, INSERT, DELETE, ...` permissions for a given action or part of the app...so as to avoid accidents.
- Other things as well...

I've managed to create a good system for getting `readOnly` and `readWrite` anonymous subclasses roughly based off the `multi-tenanancy` recipes (thanks! 👍 ). But I'm running into the following scenario where I start out with an instance that's bound to my 'readOnly' connection, but then I want to update that instance:
```
UserReadOnly
  .query()
  .select()
  .where({id: 1})
  .first()
  .then(readOnlyUser => {
    // Normally, it's a read-only operation so:
    if(noUpdateRequired) {
      return callback(readOnlyUser);
    }
    // But sometimes I may have to update this instance. I've been doing:
    return UserReadWrite
      .query()
      .patch({foo:'bar'})
      .where({id: readOnlyUser.id})
      .returning('*')
      .first()
      .then(updatedUser => {
        return callback(updatedUser);
      });
  })
  .catch(console.log);
```

This is easy enough when the `where` clause is just an `id`, but sometimes it's more complicated and/or I don't know or want to remember what the criteria was for getting the `readOnlyUser` I'm working with. It's also pretty scary to get this wrong: I don't want to update or delete an entire table by accident!

Is there an easier way to "convert" or re-bind the `readOnlyUser` instance to another knex connection? Something like:
```
// Maybe this?
let readWriteUser = readOnlyUser.$bindKnex(readWriteKnex);

// Or this?
let readWriteUser = new UserReadWrite().$set(readOnlyUser);
```

It's not clear to me what's possible or best. Any help would be much appreciated!

**Comment by koskimas** [comment]
There is no clean way to do this at the moment, but we really need one. This is something I often need myself when dealing with transactions. You can always pass the database connection to each query explicitly. `query`, `$query` etc. take a connection/transaction as the last argument. Something like this:
```js
readOnlyUser.$query(UserReadWrite.knex()).patch({foo: 'bar'});
```
but that is not always easy. I've thought of implementing `$bindKnex` just as you suggested, but I ran into some trouble with that one. I'll give it another try at some point.

**Comment by newhouse** [comment]
@koskimas appreciate the suggestion - that should probably work well enough, actually. I'll comment back here with any learnings when I circle back around to that work. Thanks!

**Comment by newhouse** [comment]
FYI - I went with something like the following to solve it. This is almost certainly not be the best solution for pure multi-tenancy where there are `n` possible connections combinations, but for my simpler `readOnly / readWrite` scenario it should work fine:

```
// Base Model that's inherited by all other Model classes I create
const {
  getReadOnlyConnection,
  getReadWriteConnection
}                           = require('./someHelperThatReturnsConnections');
const readOnlyConnection    = require('knex')(getReadOnlyConnection());
const readWriteConnection   = require('knex')(getReadWriteConnection());

const Model                 = require('objection').Model;
Model.knex(null);


class Base extends Model {

  // BIND INSTANCE QUERY TO READ-WRITE
  $queryReadWrite() {
    return this.$query(readWriteConnection);
  }

  // BIND INSTANCE QUERY TO READ-ONLY
  $queryReadOnly() {
    return this.$query(readOnlyConnection);
  }

  // BIND STATIC QUERY TO READ-WRITE
  static queryReadWrite() {
    return this.query(readWriteConnection);
  }

  // BIND STATIC QUERY TO READ-ONLY
  static queryReadOnly() {
    return this.query(readOnlyConnection);
  }

  // CREATE ANONYMOUS SUB-CLASS BOUND TO READ-WRITE
  static bindReadWrite() {
    return this.bindKnex(readWriteConnection);
  }

  // CREATE ANONYMOUS SUB-CLASS BOUND TO READ-ONLY
  static bindReadOnly() {
    return this.bindKnex(readOnlyConnection);
  }

  ...
}

module.exports = Base;
```

If something looks horribly wrong in there, please let me know!  Thanks!

**Comment by newhouse** [comment]
Oh yeah, I think I remember why I keep trying to use `$loadRelated` vs `$relatedQuery` in cases like this: I didn't recall this nuance of the documentation: `The fetched models are also stored to the owner model’s property named after the relation`. I'm guessing this means that `parentInstanceFromSlowSlave.$relatedQuery('children', txn)` should work above?!

Is that only true for basic usage like `parent.$relatedQuery('child').then(...)`? When exactly will it and will it not store the fetched models on the owner model? I will update the docs for you if you can clarify!

Thanks again for all of your work and effort!

**Comment by koskimas** [comment]
`relatedQuery(...)` should always store the related models to the parent. The difference between `loadRelated` and `relatedQuery` is that `loadRelated` takes an eager expression and chaining `where` or other query methods to `loadRelated` do nothing.

**Comment by jeffijoe** [comment]
I think I have got the same request, albeit for a different reason.

I use [Awilix](https://github.com/jeffijoe/awilix) to manage my Knex connection which is especially useful when testing in watch-mode, as each tests instantiates a server and Knex connection, and tears it down as well. 

The knex connection is injected to my repositories which would use Objection for querying, but I need a way to pass in the knex connection to the `query` call. Is this possible somehow?

**Comment by t3h2mas** [comment]
@jeffijoe Digging this up from the past, but did you get anywhere on binding knex to Objection models with Awilix?

**Comment by jeffijoe** [comment]
@t3h2mas no, I decided to use plain Knex. 😄

**Comment by zzph** [comment]
Hi,

I just came across this one, and thought I wouldn't start a new thread.

It is quite different to your example @koskimas (here)[https://vincit.github.io/objection.js/recipes/multitenancy-using-multiple-databases.html#model-binding-pattern] which binds it to each request and uses `getKnexForRequest`.

Will my approach be slower/less optimised? 

I have the following "databases" I want running on the same `express` server

- Main DB
- Archive DB
- Session DB

```
// knex.js

module.exports = {
    main: require('knex')(// ...main config)
    ...etc
}
```

```
// Example model (for main)
const { Model } = require('objection');
const knex = require('../knex')

Model.knex(knex.main)

class Person extends Model {
  static get tableName() {
    return 'persons';
  }
}

module.exports = Person.bindKnex(knex.main)
```
