### ISSUE TITLE
Implement shorthand methods lit() and raw()

### ISSUE THREAD

**Issue by elhigu** [Vincit/objection.js#275]
`raw()` would be same kind of lazily evaluated wrapper for `raw` that is done for `ref()` so that one doesn't have to dig it from `knex` instance.

`lit()` would be used to be able to give for example javascript array to different array format `{1,2,3}` vs. `(1,2,3)` etc. and to be able to cast literal explicitly like `ref()` allows for field expressions.

**Comment by koskimas** [comment]
I'm currently refactoring the code to get rid of the hideous `stashedQueryProps` hack. I'll move the logic to `UpdateOperation` and `InsertOperation` where it goes naturally. This should make implementing these easier.

**Comment by koskimas** [comment]
`raw` is now implemented.
