### ISSUE TITLE
Possible to chain `eager` to query more than once and/or append`RelationMappings` for an `eager`?

### ISSUE THREAD

**Issue by newhouse** [Vincit/objection.js#279]
Hi there, welcome back, and thanks again for your continued development on Objection! Sorry for the multiple issues/questions, but I've found another scenario where I'm looking for a solution, and perhaps there's an enhancement that can be made if there's not already something I'm missing.

I have a scenario where I have a "base" `relationExpression` that I'd like to use in the `eager` for a query. Depending on some logic, I may want to add more relationships to the `eager`. It seems like when chaining multiple `eager`s to a query, they overwrite one another. My solution has been to "build" my `relationExpression`, but it doesn't feel right and could actually get quite nasty in some scenarios. It would be nice if there was a way to append more eagers to a query. Example problem code:
```
let q = User.query().select().eager('account');
...
if (req.user.shouldSeeSecrets === true) {
  q.eager('secretStuff');
  // This eager seems to replace the earlier eager, so 'account' will not be loaded
}
...
```

Existing solution/workaround:
```
let eagerArray = ['account'];
let q = User.query().select();
...
if (req.user.shouldSeeSecrets === true) {
  eagerArray.push('secretStuff');
}
let eagerString = `[${eagerArray.join(', ')}]`;
q.eager(eagerString);
// This works, but I imagine this could get tricky when trying to generate more complex eagers like:
// '[account.[notSecretStuff, secretStuff], secretStuff]'
...
```

Possible solution:
```
let q = User.query().select().eager('account');
...
if (req.user.shouldSeeSecrets === true) {
  q.addEager('secretStuff');
  // This eager would hopefully have the same effect as if the query was:
  // User.query.select().eager('[account, secretStuff]');
}
...
```

Is there already a way to accomplish this add/append eager behavior?

Thanks!

**Comment by koskimas** [comment]
Thanks!

There is no way to currently accomplish this, but this sounds like a good idea! We could add a `mergeEager` method that merges the two eager trees. It would work even in these cases:

```
q.eager('a.b')
q.mergeEager('a.c')
// --> a.[b, c]

q.eager('[a, b.c]')
q.mergeEager('[a.d, b.[e, f], g]')
// --> [a.d, b.[c, e, f], g]
```

I'll implement this for 0.7. Please add any additional ideas and comments here.

**Comment by newhouse** [comment]
That behavior looks great to me and those examples cover simple and more complex use cases very nicely! Would love to see it in future versions! Thanks!

**Comment by zuck** [comment]
My previous work on #235 (default eager loading) would benefit from this enhancement too!

**Comment by newhouse** [comment]
@kos

**Comment by newhouse** [comment]
@koskimas lots of great changes scheduled for 0.7.0! Any idea when it's coming out?

Thank you very much for all your work!

**Comment by koskimas** [comment]
Thanks 🙏 I'll release it today
