### ISSUE TITLE
Keep documentation of older versions

### ISSUE THREAD

**Issue by elhigu** [Vincit/objection.js#280]
At some point node 0.12 is dropped and also for other reasons it might be good idea to preserve documentation snapshots to older releases of objection.

Maybe some separate folder where to store documentation for each version number and root would be always the latest.

**Comment by koskimas** [comment]
There's a tag for each version and the documentation can be found in `doc` folder in a pretty readable format since it's github flavored markdown. I think that's enough for now. Let's revisit this when moving from 1.0 to 2.0 in the distant future.
