### ISSUE TITLE
Migration from Bookshelf.js

### ISSUE THREAD

**Issue by Playrom** [Vincit/objection.js#293]
I'm trying to find an alternative to bookshelf.js, because I think it will die, and I found out that objection.js has a lot in common with it

I have some apps running with bookshelf so I wanna know if it is hard to migrate to objection... I don't want to rewrite all my models and express controllers

For new project I could. start directly with objection

someone can help me with this questione?

**Comment by elhigu** [comment]
Could you add some example part of your Model and controller code for us to have some idea how different your current code is from the way how its done with objection?

**Comment by koskimas** [comment]
Bookshelf and objection are both built on knex, but the similarities pretty much end there. You will have to rewrite your models and most of the queries. I have never migrated from bookshelf to objection so I don't have a migration guide to give you. As elhigu said, we can try to help if you ask something more specific.

**Comment by koskimas** [comment]
@Playrom If you don't have a more specific question, I'm going to close this issue. We are happy to help, but we don't have time to create a migration tutorial for you.
