### ISSUE TITLE
update knex dependency

### ISSUE THREAD

**Issue by rodrigopivi** [Vincit/objection.js#294]
Using objection@0.7.0-rc.3 and knex@0.12.6, i get this warning at yarn:
```
warning "objection@0.7.0-rc.3" has incorrect peer dependency "knex@>= 0.8.0 <= 0.12.5".
```

**Comment by koskimas** [comment]
Yeah, I'll update it in the next rc. Is there something you actually need in 0.12.6?

**Comment by rodrigopivi** [comment]
thanks for the fast response! nothing in particular, but was using it before and would prefer not to downgrade it

**Comment by xcapt** [comment]
bump on this one, and to give more context on our issue: we use knex in multiple modules and if each module specifically requires an old version without the possibility for minors being upgraded we end up with a messy node_modules (e.g. knex 0.12.5, 0.12.6 and 0.127 installed)
thank you!

**Comment by koskimas** [comment]
@rodrigopivi @xcapt The knex peerdep is for `0.x` in objection `0.7.0`.
