### ISSUE TITLE
If no models are found throw error (Improvement)

### ISSUE THREAD

**Issue by zmts** [Vincit/objection.js#297]
Hi there!
Hope for some improvement for Objection.js. 
I believe that feature will be helpful.
If it possible implement something like >>>

```
SomeModel.getAll = function () {
    return this.query({require: true});
};
```
__require: true__ That trigger an error if no models are found.

Tnx! Hope for support =)

**Comment by devinivy** [comment]
I would suggest creating a base model class for yourself that will do this.  Then extend your base model rather than objection's.  I hope to see the surface-area of objection's API to stay relatively minimal.

**Comment by koskimas** [comment]
I agree with devinivy. Sorry.
