### ISSUE TITLE
schema.switch support in version 0.7.0-rc.3

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#299]
Here's the schema i'm using:
```
{
 "type": "object",
 "required": [
  "type"
 ],
 "properties": {
  "id": {
   "type": "integer"
  },
  "type": {
   "type": "string"
  }
 },
 "switch": [
  {
   "if": {
    "properties": {
     "type": {
      "constant": "site"
     }
    }
   },
   "then": {
    "properties": {
     "data": {
      "type": "object",
      "default": {},
      "properties": {
       "name": {
        "type": "string"
       }
      },
      "required": [
       "name"
      ]
     }
    }
   }
  },
  {
   "if": {
    "properties": {
     "type": {
      "constant": "page"
     }
    }
   },
   "then": {
    "properties": {
     "data": {
      "type": "object",
      "default": {},
      "properties": {
       "title": {
        "type": [
         "string",
         "null"
        ]
       },
       "template": {
        "type": "string"
       }
      },
      "required": [
       "template"
      ]
     }
    }
   }
  }
 ]
}
```
It validates all right with ajv and that kind of data:
```
{
 "type": "page",
 "data": {
  "title": "Home",
  "template": "templates/home.html"
 }
}
```

$afterValidate receives that json all right.
However, when inserting it using insertGraph method, it strips the `data` property.

I have to modify the schema and declare "properties.data" to keep objection from pruning that column.
I suppose the problem comes from the "switch" clause, while objection only checks what's in the schema "properties".
Isn't there any way to abstract that second-guessing from objection and let all knowledge about schema be given by ajv ?

**Comment by koskimas** [comment]
[Yes](http://vincit.github.io/objection.js/#pickjsonschemaproperties)

**Comment by kapouer** [comment]
Ha, that explains a lot of confusion i had. IMO pickJsonSchemaProperties should be false by default, but i won't complain.

**Comment by koskimas** [comment]
I agree. The feature is just a historical remnant. I'll probably set the default to true or remove the feature alltogether at some point.

**Comment by kapouer** [comment]
Well, actually, before changing anything, i think something's wrong with ajv or with json-schema spec about additionalProperties and switch keywords.

**Comment by koskimas** [comment]
Did you reopen this by accident? Or is there something you wish to be changed in objection?

**Comment by kapouer** [comment]
> I'll probably set the default to false or remove the feature alltogether at some point.

so i thought this issue should stay open until that point ? Or not !

**Comment by koskimas** [comment]
We should open a separate issue for that. This isn't very descriptive.
