### ISSUE TITLE
`delete()` and/or `unrelate()` in `$relatedQuery` not removing children after deletion

### ISSUE THREAD

**Issue by newhouse** [Vincit/objection.js#304]
I'm on Objection 0.6.2

I _think_ I know the answer to this already, but wanted to check:

I have a model class `Campaign` that has a `ManyToManyRelation` relationship with `User` through `CampaignRoles`. I've set up the relationship in the `Campaign` class 2 ways:
1. As a `HasManyRelation` called `campaignRoles`, linking to the `CampaignRole` table directly/only. (for various reasons)
2. As a `ManyToManyRelation` called `users` which links to the `User` table/model _through_ the `CampaignRole` table/model.

I don't believe that the above details are significant regarding the behavior I'm seeing, but I wanted to set the scene properly.  The scenario in question occurs when I am trying to remove Users from a Campaign (i.e. delete some `CampaignRole`s). I have an instance of `Campaign` loaded up with `campaignRoles` (or `users`), and when I execute the following delete commands, the appropriate `CampaignRole`s are in fact deleted, yet the `campaignRoles` (or `users`) on the instance remain unchanged.

Here's some sample code:
```
const userIds = [1,2,3];
console.log(campaign.campaignRoles); // Let's say 4 entries come out.
console.log(campaign.users); // Equivalent 4 entries come out.

// Go the "delete()" route
campaign.$relatedQuery('campaignRoles')
  .delete()
  .whereIn('user_id', userIds)
  .then(numRows => {
    console.log(numRows); // 3
    // The same 4 entries come out, even though 3 have been deleted.
    console.log(campaign.campaignRoles);
  });

...

// Start again and go the "unrelate()" route
campaign.$relatedQuery('users')
  .unrelate()
  .whereIn('id', userIds)
  .then(numRows => {
    // Actually I don't know what this returns, looks like an empty object?
    console.log(numRows);
    // The same 4 entries come out, even though 3 have been deleted
    console.log(campaign.users);
```

How come the 3 related objects are not removed? Is this expected behavior? My guess is that this is expected behavior, and it's because Objection has no way of knowing if none, some (and in that case, which) or all of the related objects were deleted (except if the `numRows` turns out to be the same length as the supplied `userIds` array, but even that is not necessarily a safe/solid assumption to make).

If that's the case, does anyone have suggestions for getting this done _efficiently_? Some ideas:
1. After the `delete()`/`unrelate()`, re-load the related objects via `campaign.$relatedQuery('campaignRoles').then()` or `campaign.$loadRelated('campaignRoles').then()`
2. Go through the `campaign.campaingRoles` myself and delete any matching the supplied `userIds`. This is lame.
3. Some other way I'm not thinking of?

Here's an interesting twist:
I'm running Postgres 9.5.5. If I chain a `returning('*')` to the `delete()` approach (this has no effect for `unrelate()` as it still passes `{}` to the Promise resolution), the actual rows that were deleted are passed back. I'm not seeing that mentioned in the docs anywhere for `delete` (only `insert`, should I file a ticket or PR to get it into the `delete` area docs, or is this unexpected?). I could leverage that, but even more awesome would be if Objection leveraged that and removed the deleted stuff.

Apologies for the HUGE post and I thank you, thank you, thank you for all your work on this great library. Happy to try and get my hands dirty on this as well, if you can point me in the right direction.

Cheers!

**Comment by koskimas** [comment]
> My guess is that this is expected behavior, and it's because Objection has no way of knowing if none, some (and in that case, which) or all of the related objects were deleted

Yep, you guessed correctly.

> If I chain a returning('*') to the delete() approach (this has no effect for unrelate() as it still passes {} to the Promise resolution), the actual rows that were deleted are passed back. 

I didn't actually know `returning` also work with delete. I think `update` and `insert` cases are documented.

> should I file a ticket or PR to get it into the delete area docs,

A PR would be great! Also there are no tests for this behaviour, so if you find time to add a simple test for this, it would be even more awesome. I would be happy with just a documentation PR though.

> but even more awesome would be if Objection leveraged that and removed the deleted stuff.

`returning` only works with postgres (and maybe oracle or something?). Removing rows in `delete()` only on some databases is not an option. We could possibly add a special method that uses `returning` and removes the needed objects, but It would be marginally useful, and I'm not a huge fan of this option.

Maybe we could add `deleteAndFetch` and `unrelateAndFetch` (not the best names, they seem like they fetch the deleted rows) methods that would only work when chained to `$relatedQuery` and would reload the relation. We could then maybe optimize the postgresql version so that it uses `returning`.

**Comment by newhouse** [comment]
Haven't forgotten about trying to add some to the documentation/tests...super busy. I ❤️  you all though!

**Comment by drew-r** [comment]
Could a method like `model.$refresh()` or `model.$refreshRelation('relation')` help here?

If a model instance is able to hold on to the query that generated it (and apply some magic to limit the result set to only that particular model as with `$query()`), it can be refreshed at will .
Same with it's relations but not sure this could work for join algorithm. 

This would allow me to run relatedQuerys, patch some relation completely independently of the parent, generally not care about results from patch / updates and just hit `model.$refreshRelation` or something when I'm ready. 
This way all my relation expressions, filters, etc are reapplied.

**Comment by newhouse** [comment]
Just submitted a PR for the documentation: https://github.com/Vincit/objection.js/pull/376

I'll try my hand at adding tests if I feel brave enough...

**Comment by koskimas** [comment]
@drew-r That would be pretty impossible to implement so that it would work in all situations. Think about this:

```js
const person = await Person.query().eager('movies.actors').findById(1);
const movie = person.movies[3];
await movie.$refresh();
```

It would be pretty difficult to determine which query to execute for `movie`.

I'm closing this now since the original question has been answered.
