### ISSUE TITLE
schema with id throws Error: schema with key or id "/api/xxxx" already exists

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#305]
Objection compiles schemas potentially twice (once with the original schema,
and once for skipRequired, [here](https://github.com/Vincit/objection.js/blob/master/src/model/AjvValidator.js#L70).

If the schema had an id, it will make ajv throw an error.
There are two ways around this when compiling schema with skipRequired:
- remove schema id
- prefix or suffix schema id (i prefer that one because i suppose ajv is using id as a cache key,
but i'm not sure).

**Comment by kapouer** [comment]
Oh actually the bug is in version 0.6.2 !
Latest 07.0-rc.3 is not affected because it uses two different ajv instances to compile the schema (with defaults) and its skipRequired variant (without defaults) so ajv(s) won't notice the id collision.

**Comment by koskimas** [comment]
Fixed by accident in 0.7.0 :D
