### ISSUE TITLE
Real error types

### ISSUE THREAD

**Issue by felixSchl** [Vincit/objection.js#306]
Would be great to do something like sequelize where they analyze the various errors and transform them for easier usage (i.e. for use with `typeof`): https://github.com/sequelize/sequelize/blob/559488974fd426db5523942beadc984fb0539df7/lib/dialects/sqlite/query.js#L315-L365.

What do you think?

**Comment by elhigu** [comment]
@felixSchl it is pretty big job to try to harmonize between errors got across different database drivers.

Would be really nice feature, but I think it should be implemented as separate npm module. There are some error translation libraries available at least for postgres there is https://github.com/moll/node-pg-error to start with.

**Comment by koskimas** [comment]
I totally agree with @elhigu. Would be a nice feature, but someone would have to maintain it and I don't have time to do it 😞. Separate module would be the best solution.
