### ISSUE TITLE
MSSQL parameter limit of 2100 Issue

### ISSUE THREAD

**Issue by vbedekar** [Vincit/objection.js#311]
I have a nested model and the underlying query that executes does a IN clause with more than 2100 parameters. MYSQL cant take this.
Usually its recommended to handle this my breaking up the IN parameter list and chaining the sublists by doing multiple OR's

```js
v_portfolio_api
    .query()
    .eager('[trading_group.head_traders.trader, traders.trader]')
    .then(function(portfolios) {
      res.status(200).json(portfolios);
    });
```

Do you have a solution? Can the ORM handle this for MSSQL?

**Comment by koskimas** [comment]
The default eager algorithm uses where in queries. Check out JoinEagerAlgorithm from the documentation. The current stable version 0.6.2 has some bugs related to it but they shouldn't affect the query in question.

**Comment by koskimas** [comment]
If you do experience some missing data using the join based  algorithm, please test the objection@next version. (npm install objection@next)

**Comment by vbedekar** [comment]
Using this now with next version of objection.

  v_portfolio_api
    .query()
    .eagerAlgorithm(Model.JoinEagerAlgorithm)
    .eager('[trading_group.head_traders.trader, traders.trader]')
    .then(function(portfolios) {
      res.status(200).json(portfolios);
    });

The query executing on the back end looks fine but I am getting an empty array as a result.

**Comment by vbedekar** [comment]
This on the other hand works perfectly for same models -

v_portfolio_api
    .query()
    .where('v_portfolio_api.portfolio_id', '=', req.params.portfolio_id)
    .eager('[trading_group.head_traders.trader, traders.trader]')
    .then(function(portfolios) {
      res.status(200).json(portfolios);
    });

As you can see its getting a specific portfolio and using WhereIn.

**Comment by vbedekar** [comment]
Yes thts the version I have.
The query is executing but it returns multiple rows even though the search is by ID. I was expecting one row with all the columns. Apologize for the query length -

select [v_portfolio_api].[portfolio_id] as [portfolio_id], [v_portfolio_api].[portfolio_code] as [portfolio_code], [v_portfolio_api].[status_id] as [status_id], [v_portfolio_api].[status] as [status], [v_portfolio_api].[start_date] as [start_date], [v_portfolio_api].[shutdown_date] as [shutdown_date], [v_portfolio_api].[trading_group_id] as [trading_group_id], [v_portfolio_api].[middle_office_coverage_id] as [middle_office_coverage_id], [v_portfolio_api].[attestation_owner_id] as [attestation_owner_id], [v_portfolio_api].[last_updated_on] as [last_updated_on], [v_portfolio_api].[last_updated_by] as [last_updated_by], [v_portfolio_api].[cost_center_id] as [cost_center_id], [v_portfolio_api].[cost_center_code] as [cost_center_code], [v_portfolio_api].[cost_center_desc] as [cost_center_desc], [v_portfolio_api].[investment_region_id] as [investment_region_id], [v_portfolio_api].[investment_region_code] as [investment_region_code], [v_portfolio_api].[region_id] as [region_id], [v_portfolio_api].[region_code] as [region_code], [v_portfolio_api].[trader_ids] as [trader_ids], [v_portfolio_api].[strategy_id] as [strategy_id], [v_portfolio_api].[strategy] as [strategy], [v_portfolio_api].[strategy_group] as [strategy_group], [v_portfolio_api].[sector_id] as [sector_id], [v_portfolio_api].[sector] as [sector], [v_portfolio_api].[is_primary_strategy]as [is_primary_strategy], [v_portfolio_api].[is_strategy_active] as [is_strategy_active], [v_portfolio_api].[regulatory_country_id] as [regulatory_country_id], [v_portfolio_api].[regulatory_country_code] as [regulatory_country_code], [v_portfolio_api].[first_traded_date] as [first_traded_date], [v_portfolio_api].[last_traded_date] as [last_traded_date], [trading_group].[trading_group_id]as [trading_group:trading_group_id], [trading_group].[trading_group_acronym] as [trading_group:trading_group_acronym], [trading_group].[trading_group_long_name]as [trading_group:trading_group_long_name], [trading_group].[trading_group_type_id] as [trading_group:trading_group_type_id], [trading_group].[trading_group_type_code] as [trading_group:trading_group_type_code], [trading_group].[primary_strategy_id] as [trading_group:primary_strategy_id], [trading_group].[primary_strategy_code] as [trading_group:primary_strategy_code], [trading_group].[primary_strategy_notes] as [trading_group:primary_strategy_notes], [trading_group].[investment_manager_id] as [trading_group:investment_manager_id], [trading_group].[investment_manager_code] as [trading_group:investment_manager_code], [trading_group].[legal_entity_id] as [trading_group:legal_entity_id], [trading_group].[supervisor_id] as [trading_group:supervisor_id], [trading_group].[pnl_supervisor_id] as[trading_group:pnl_supervisor_id], [trading_group].[relationship_owner_id] as [trading_group:relationship_owner_id], [trading_group].[trading_group_status_id] as [trading_group:trading_group_status_id], [trading_group].[trading_group_status_code] as [trading_group:trading_group_status_code], [trading_group].[contract_status_id] as [trading_group:contract_status_id], [trading_group].[contract_status_code] as [trading_group:contract_status_code], [trading_group].[target_start_date] as [trading_group:target_start_date], [trading_group].[shutdown_date] as [trading_group:shutdown_date], [trading_group].[office_type_id] as [trading_group:office_type_id], [trading_group].[office_type_code] as [trading_group:office_type_code], [trading_group].[sector_id] as [trading_group:sector_id], [trading_group].[sector_code] as [trading_group:sector_code], [trading_group].[region_id] as[trading_group:region_id], [trading_group].[region_code] as [trading_group:region_code], [trading_group].[mlp_address_id] as [trading_group:mlp_address_id], [trading_group].[mlp_address_name] as [trading_group:mlp_address_name], [trading_group].[mlp_city] as [trading_group:mlp_city], [trading_group].[mlp_state_id] as [trading_group:mlp_state_id], [trading_group].[mlp_state_code] as [trading_group:mlp_state_code], [trading_group].[mlp_country_id] as [trading_group:mlp_country_id], [trading_group].[mlp_country_code] as [trading_group:mlp_country_code], [trading_group].[trading_group_email] as [trading_group:trading_group_email], [trading_group].[trading_group_email_domain] as [trading_group:trading_group_email_domain], [trading_group].[first_traded_date] as [trading_group:first_traded_date],[trading_group].[last_traded_date] as [trading_group:last_traded_date], [trading_group].[head_trader_ids] as [trading_group:head_trader_ids], [trading_group].[last_updated_by] as [trading_group:last_updated_by], [trading_group].[last_updated_on] as [trading_group:last_updated_on], [trading_group:head_traders].[trading_group_trader_id] as [trading_group:head_traders:trading_group_trader_id], [trading_group:head_traders].[trading_group_id] as [trading_group:head_traders:trading_group_id], [trading_group:head_traders].[trader_id] as [trading_group:head_traders:trader_id], [trading_group:head_traders].[incentive_fee] as [trading_group:head_traders:incentive_fee], [trading_group:head_traders].[cap_amount] as [trading_group:head_traders:cap_amount], [trading_group:head_traders].[payout_percentage] as [trading_group:head_traders:payout_percentage], [trading_group:head_traders].[payout_date] as [trading_group:head_traders:payout_date], [trading_group:head_traders].[last_updated_by] as [trading_group:head_traders:last_updated_by], [trading_group:head_traders].[last_updated_on] as [trading_group:head_traders:last_updated_on],[trading_group:head_traders:trader].[trader_id] as [trading_group:head_traders:trader:trader_id], [trading_group:head_traders:trader].[first_name] as [trading_group:head_traders:trader:first_name], [trading_group:head_traders:trader].[last_name] as [trading_group:head_traders:trader:last_name], [trading_group:head_traders:trader].[title_id] as [trading_group:head_traders:trader:title_id], [trading_group:head_traders:trader].[title_code] as [trading_group:head_traders:trader:title_code], [trading_group:head_traders:trader].[target_start_date] as [trading_group:head_traders:trader:target_start_date], [trading_group:head_traders:trader].[transfer_date] as [trading_group:head_traders:trader:transfer_date],[trading_group:head_traders:trader].[termination_date] as [trading_group:head_traders:trader:termination_date], [trading_group:head_traders:trader].[status_id] as [trading_group:head_traders:trader:status_id], [trading_group:head_traders:trader].[status] as [trading_group:head_traders:trader:status], [trading_group:head_traders:trader].[investment_manager_id] as [trading_group:head_traders:trader:investment_manager_id], [trading_group:head_traders:trader].[investment_manager_code] as [trading_group:head_traders:trader:investment_manager_code], [trading_group:head_traders:trader].[previous_employer] as [trading_group:head_traders:trader:previous_employer], [trading_group:head_traders:trader].[mlp_address_id] as [trading_group:head_traders:trader:mlp_address_id],[trading_group:head_traders:trader].[mlp_address_name] as [trading_group:head_traders:trader:mlp_address_name],[trading_group:head_traders:trader].[mlp_city] as [trading_group:head_traders:trader:mlp_city], [trading_group:head_traders:trader].[mlp_state_id] as[trading_group:head_traders:trader:mlp_state_id], [trading_group:head_traders:trader].[mlp_state] as [trading_group:head_traders:trader:mlp_state], [trading_group:head_traders:trader].[mlp_country_id] as [trading_group:head_traders:trader:mlp_country_id], [trading_group:head_traders:trader].[mlp_country] as [trading_group:head_traders:trader:mlp_country], [trading_group:head_traders:trader].[primary_email] as [trading_group:head_traders:trader:primary_email], [trading_group:head_traders:trader].[home_phone] as [trading_group:head_traders:trader:home_phone], [trading_group:head_traders:trader].[work_phone] as [trading_group:head_traders:trader:work_phone], [trading_group:head_traders:trader].[cell_phone] as [trading_group:head_traders:trader:cell_phone], [trading_group:head_traders:trader].[region_id] as [trading_group:head_traders:trader:region_id], [trading_group:head_traders:trader].[region_code] as [trading_group:head_traders:trader:region_code], [trading_group:head_traders:trader].[last_updated_on] as [trading_group:head_traders:trader:last_updated_on], [trading_group:head_traders:trader].[last_updated_by] as [trading_group:head_traders:trader:last_updated_by], [trading_group:head_traders:trader].[username] as [trading_group:head_traders:trader:username],[trading_group:head_traders:trader].[workday_employee_id] as [trading_group:head_traders:trader:workday_employee_id], [traders].[portfolio_trader_id] as [traders:portfolio_trader_id], [traders].[portfolio_id] as [traders:portfolio_id], [traders].[trader_id] as [traders:trader_id], [traders].[active_ind] as [traders:active_ind], [traders].[last_updated_by] as [traders:last_updated_by], [traders].[last_updated_on] as [traders:last_updated_on], [traders:trader].[trader_id] as [traders:trader:trader_id], [traders:trader].[first_name] as [traders:trader:first_name], [traders:trader].[last_name] as [traders:trader:last_name], [traders:trader].[title_id] as [traders:trader:title_id], [traders:trader].[title_code] as [traders:trader:title_code], [traders:trader].[target_start_date] as [traders:trader:target_start_date], [traders:trader].[transfer_date] as [traders:trader:transfer_date], [traders:trader].[termination_date] as [traders:trader:termination_date], [traders:trader].[status_id] as [traders:trader:status_id], [traders:trader].[status] as [traders:trader:status], [traders:trader].[investment_manager_id] as [traders:trader:investment_manager_id], [traders:trader].[investment_manager_code] as [traders:trader:investment_manager_code], [traders:trader].[previous_employer] as [traders:trader:previous_employer], [traders:trader].[mlp_address_id] as [traders:trader:mlp_address_id], [traders:trader].[mlp_address_name] as [traders:trader:mlp_address_name], [traders:trader].[mlp_city] as [traders:trader:mlp_city], [traders:trader].[mlp_state_id] as [traders:trader:mlp_state_id], [traders:trader].[mlp_state] as [traders:trader:mlp_state], [traders:trader].[mlp_country_id] as [traders:trader:mlp_country_id], [traders:trader].[mlp_country] as [traders:trader:mlp_country], [traders:trader].[primary_email] as [traders:trader:primary_email], [traders:trader].[home_phone] as [traders:trader:home_phone], [traders:trader].[work_phone] as [traders:trader:work_phone], [traders:trader].[cell_phone] as [traders:trader:cell_phone], [traders:trader].[region_id] as [traders:trader:region_id], [traders:trader].[region_code] as [traders:trader:region_code], [traders:trader].[last_updated_on] as [traders:trader:last_updated_on], [traders:trader].[last_updated_by] as [traders:trader:last_updated_by], [traders:trader].[username] as [traders:trader:username], [traders:trader].[workday_employee_id] as [traders:trader:workday_employee_id] from [v_portfolio_api] as [v_portfolio_api] left join (select * from [v_trading_group_api]) as [trading_group] on [trading_group].[trading_group_id] = [v_portfolio_api].[trading_group_id] left join (select * from [v_head_trader_api]) as [trading_group:head_traders] on [trading_group:head_traders].[trading_group_id] = [trading_group].[trading_group_id] left join (select * from [v_trader_api]) as [trading_group:head_traders:trader] on [trading_group:head_traders:trader].[trader_id] = [trading_group:head_traders].[trader_id] left join (select * from [v_portfolio_trader_api]) as [traders] on [traders].[portfolio_id] = [v_portfolio_api].[portfolio_id] left join (select * from [v_trader_api]) as [traders:trader] on [traders:trader].[trader_id] = [traders].[trader_id] where [v_portfolio_api].[portfolio_id] = 1000

**Comment by vbedekar** [comment]
Something smaller - 

v_portfolio_api
    .query()
    .debug()
    .where('v_portfolio_api.portfolio_id', '=', req.params.portfolio_id)
    .eagerAlgorithm(Model.JoinEagerAlgorithm)
    .eager('[trading_group]')
    .then(function(portfolios) {
      res.status(200).json(portfolios);
    });

Output - 

method: 'select',
options: {},
timeout: false,
cancelOnTimeout: false,
bindings: [ '1500' ],

select [v_portfolio_api].[portfolio_id] as [portfolio_id], [v_portfolio_api].[portfolio_code] as [portfolio_code], [v_portfolio_api].[status_id] as [status_id], [v_portfolio_api].[status] as [status], [v_portfolio_api].[start_date] as [start_date], [v_portfolio_api].[shutdown_date] as [shutdown_date], [v_portfolio_api].[trading_group_id] as [trading_group_id], [v_portfolio_api].[middle_office_coverage_id] as [middle_office_coverage_id], [v_portfolio_api].[attestation_owner_id] as [attestation_owner_id], [v_portfolio_api].[last_updated_on] as [last_updated_on], [v_portfolio_api].[last_updated_by] as [last_updated_by], [v_portfolio_api].[cost_center_id] as [cost_center_id], [v_portfolio_api].[cost_center_code] as [cost_center_code], [v_portfolio_api].[cost_center_desc] as [cost_center_desc], [v_portfolio_api].[investment_region_id] as [investment_region_id], [v_portfolio_api].[investment_region_code] as [investment_region_code], [v_portfolio_api].[region_id] as [region_id], [v_portfolio_api].[region_code] as [region_code], [v_portfolio_api].[trader_ids] as [trader_ids], [v_portfolio_api].[strategy_id] as [strategy_id], [v_portfolio_api].[strategy] as [strategy], [v_portfolio_api].[strategy_group] as [strategy_group], [v_portfolio_api].[sector_id] as [sector_id], [v_portfolio_api].[sector] as [sector], [v_portfolio_api].[is_primary_strategy]as [is_primary_strategy], [v_portfolio_api].[is_strategy_active] as [is_strategy_active], [v_portfolio_api].[regulatory_country_id] as [regulatory_country_id], [v_portfolio_api].[regulatory_country_code] as [regulatory_country_code], [v_portfolio_api].[first_traded_date] as [first_traded_date], [v_portfolio_api].[last_traded_date] as [last_traded_date], [trading_group].[trading_group_id]as [trading_group:trading_group_id], [trading_group].[trading_group_acronym] as [trading_group:trading_group_acronym], [trading_group].[trading_group_long_name] as [trading_group:trading_group_long_name], [trading_group].[trading_group_type_id] as [trading_group:trading_group_type_id], [trading_group].[trading_group_type_code] as [trading_group:trading_group_type_code], [trading_group].[primary_strategy_id] as [trading_group:primary_strategy_id], [trading_group].[primary_strategy_code] as [trading_group:primary_strategy_code], [trading_group].[primary_strategy_notes] as [trading_group:primary_strategy_notes], [trading_group].[investment_manager_id] as [trading_group:investment_manager_id], [trading_group].[investment_manager_code] as [trading_group:investment_manager_code], [trading_group].[legal_entity_id] as [trading_group:legal_entity_id], [trading_group].[supervisor_id] as [trading_group:supervisor_id], [trading_group].[pnl_supervisor_id] as [trading_group:pnl_supervisor_id], [trading_group].[relationship_owner_id] as [trading_group:relationship_owner_id], [trading_group].[trading_group_status_id] as [trading_group:trading_group_status_id], [trading_group].[trading_group_status_code] as [trading_group:trading_group_status_code], [trading_group].[contract_status_id] as [trading_group:contract_status_id], [trading_group].[contract_status_code] as [trading_group:contract_status_code], [trading_group].[target_start_date] as [trading_group:target_start_date], [trading_group].[shutdown_date] as [trading_group:shutdown_date], [trading_group].[office_type_id] as [trading_group:office_type_id], [trading_group].[office_type_code] as [trading_group:office_type_code], [trading_group].[sector_id] as [trading_group:sector_id], [trading_group].[sector_code] as [trading_group:sector_code], [trading_group].[region_id] as [trading_group:region_id], [trading_group].[region_code] as [trading_group:region_code], [trading_group].[mlp_address_id] as [trading_group:mlp_address_id], [trading_group].[mlp_address_name] as [trading_group:mlp_address_name], [trading_group].[mlp_city] as [trading_group:mlp_city], [trading_group].[mlp_state_id] as [trading_group:mlp_state_id], [trading_group].[mlp_state_code] as [trading_group:mlp_state_code], [trading_group].[mlp_country_id] as [trading_group:mlp_country_id], [trading_group].[mlp_country_code] as [trading_group:mlp_country_code], [trading_group].[trading_group_email] as [trading_group:trading_group_email], [trading_group].[trading_group_email_domain] as [trading_group:trading_group_email_domain], [trading_group].[first_traded_date] as [trading_group:first_traded_date], [trading_group].[last_traded_date] as [trading_group:last_traded_date], [trading_group].[head_trader_ids] as [trading_group:head_trader_ids], [trading_group].[last_updated_by] as [trading_group:last_updated_by], [trading_group].[last_updated_on] as [trading_group:last_updated_on] from [v_portfolio_api] as [v_portfolio_api] left join (select * from [v_trading_group_api]) as [trading_group] on [trading_group].[trading_group_id] = [v_portfolio_api].[trading_group_id] where [v_portfolio_api].[portfolio_id] = ?

**Comment by fl0w** [comment]
Oh god, pro tip: use triple back-ticks (```) so format output.

```js
// much easier to read
v_portfolio_api
  .query()
  .debug()
  .where('v_portfolio_api.portfolio_id', '=', req.params.portfolio_id)
  .eagerAlgorithm(Model.JoinEagerAlgorithm)
  .eager('[trading_group]')
  .then(function(portfolios) {
    res.status(200).json(portfolios);
  });
```

**Comment by vbedekar** [comment]
Thanks for the tip......Anything I can do to get around this issue?

**Comment by koskimas** [comment]
Unfortunately I don't have an mssql setup so that I could test this. There is obviously something wrong with either knex or objection. The query should return multiple rows as it is a join. Relational databases return joins in a flat list and not as a nested tree. Objection then parses the flat list and turns it into a tree.

Only postgres, mysql and sqlite are tested on objection side and I think even knex doesn't have tests for mssql.

What I could do though, is to make the normal eager case work by limiting the amount of parameters it sends by doing multiple queries. I'll add this to my TODO list.

**Comment by vbedekar** [comment]
Thanks you.....having the choice of Join VS WhereIn is a very useful feature.
