### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by ozum** [Vincit/objection.js#314]
Hi,

I was looking to change log and saw that version 0.6.0, 0.7.0 etc. has breaking changes.

May I kindly suggest to change versioning scheme to semantic versioning. Same major versions (0 in this case) should not have breaking changes, because developers may rely on this contract.

Regards,

**Comment by fl0w** [comment]
objection is following semantic versioning. Versions below 1.x are parse differently. Versions below 1.x can break on minor versions because it's not considered stable yet.

I recommend consulting [semver.org](semver.org) for more information.

**Comment by ozum** [comment]
@fl0w, you are right, I forgot 0.x part.

On the other hand, AFAIK, objection.js is 2 years old and has near 1.000 github stars. I think this indicates that many developers including me depend on and trust it.

Maybe it is time to move v1 and follow >1 semver rules.

To be honest, it is very convenient and mind relaxing to have `1.x` or `2.x` etc. in `package.json` and updating packages to latest minor versions without first having to check change log.

This is of course a personal opinion, and I kindly hope developers consider it.

Regards,

**Comment by fl0w** [comment]
How long a library has existed or how many stars it received unfortunately has nothing to do with the stability of a library.

The library still changes API and I personally no reason to force a "stable 1.x release". All it would do is move the minors to majors, but it still would be bumped as much and the regular `^1.0.0` still would/should upgrade a major.

Think minor version as major, and patch as bug fixes and features and you get the same effect.

Not to even mention that `knex`, `objection`'s main dependency is also not on a major.

**Comment by fl0w** [comment]
Sorry, tons of errors in my last reply. Iphone commenting on a bumpy train is not recommended :) (I'll update and edit when I get to office)

**Comment by elhigu** [comment]
I think it is already a good time to start discussion when objection will be made stable. 

One major change that would have to be made after making objection stable is to lock `knex` version that objection depends on and update it only on objection major version updates. 

Also it will be a bit harder to keep on development in a way that one doesn't have to change major version all the time. Going to stable without minimizing major version changes wouldn't make much sense.

**Comment by fl0w** [comment]
@elhigu I understand the argument to want a stable release - but my (as a non-member) point was that slapping a 1.x label on anything without actually considering the lib stable does nothing in practice, as you pointed out.

**Comment by ozum** [comment]
> Also it will be a bit harder to keep on development in a way that one doesn't have to change major version all the time. Going to stable without minimizing major version changes wouldn't make much sense.

I completely agree with that.

> How long a library has existed or how many stars it received unfortunately has nothing to do with the stability of it.

Mostly agree with that. 2 year old library is probably used in enough projects by its developer and thousand stars indicate that a bunch of other developers used it in several projects too. So library developer and other people probably trust library's api for some time. On the other hand I agree with @fl0w, that even so, library may not be mature enough for developer's future plans.

@elhigu, I don't want to mean to push for a 1.x release. I just assumed it is mature enough, since release cycle which has breaking changes does not seem daily or weekly.

Even I also hesitate big major numbers, v10+ (react), v20 even v50 (chrome) seems normal these days.

**Comment by koskimas** [comment]
We should start thinking about 1.0 soon, but I don't think we are there just yet. I'll close this issue now as objection is following semver. Feel free to start an issue about releasing 1.0.
