### ISSUE TITLE
Is it possible to use SQL_CALC_FOUND_ROWS?

### ISSUE THREAD

**Issue by tbazko** [Vincit/objection.js#315]
Is it possible to use this option? Like in:
SELECT SQL_CALC_FOUND_ROWS * FROM tbl_name WHERE id > 100 LIMIT 10;
SELECT FOUND_ROWS();

Can't find the way to create a query.

**Comment by koskimas** [comment]
Only with raw queries I'm afraid. Something like this (not tested):

```js
objection.transaction(async (trx) => {
  await Person.query().select(Person.raw('SQL_CALC_FOUND_ROWS *')).where('id', '>' 100).limit(10);
  await trx.raw('SELECT FOUND_ROWS()')
});
```

**Comment by koskimas** [comment]
I'm thinking about implementing the `page` and `range` methods using `SQL_CALC_FOUND_ROWS` and `SELECT FOUND_ROWS()` for mysql. The you could simply do this:

```js
Person
  .query()
  .where('id', '>', 100)
  .limit(10)
  .page()
```

or this

```js
Person
  .query()
  .page(10, 10)
```

related to #62

**Comment by koskimas** [comment]
@tbazko 

SQL_CALC_FOUND_ROWS seems to be significantly slower than just doing two queries when the database has proper indexes for the query. If you do paged searching and don't have indexes, you are screwed anyways. I also ran my own simple tests with a table with million rows, and two separate queries was around twice as fast.

In addition to this, knex doesn't seem to support adding options for select (note that SQL_CALC_FOUND_ROWS is not just a item in the select list but an option). Implementation would be a hack.

https://www.percona.com/blog/2007/08/28/to-sql_calc_found_rows-or-not-to-sql_calc_found_rows/

You are better off using the objection's [`page`](http://vincit.github.io/objection.js/#page)  and [`range`](http://vincit.github.io/objection.js/#range) methods.

**Comment by tbazko** [comment]
Thanks! I think, actually, page will fit my needs pretty well. I never saw this method.

**Comment by koskimas** [comment]
Currently this doesn't work

```js
Person
  .query()
  .where('id', '>', 100)
  .limit(10)
  .range()
```

But I'll soon release a version where it does. Currently you have to give the range or page and pageSize to the `page` and `range` methods as arguments.

This works:

```js
Person
  .query()
  .where('id', '>', 100)
  .range(100, 110)
```

but it isn't the same thing.
