### ISSUE TITLE
Validate a partial set of values

### ISSUE THREAD

**Issue by cpsubrian** [Vincit/objection.js#317]
Been pouring through the docs and not seeing how I'd do this. I am setting up CRUD controllers for my models and I'd like to do something like the following (pseudo-code):

```js
function patchModel (req, res, next) {
  let id = req.query.id
  let body = Model.fromJson(req.body).toJSON()
  return Model.query().patchAndFetchById(id, body).then((model) => {
    req.objects[objKey] = model
    next()
  })
}
```

The problem is `Model.fromJson()` validates against the whole schema, which errors out on things like missing required props.

**Comment by cpsubrian** [comment]
Another route I tried is creating an instance and using `model.$setJson()` but that validates similarly.

**Comment by WilliamSWoodruff** [comment]
@cpsubrian I think `patchAndFetchById` doesn't require a model instance, but just the properties you're changing. So something like `Model.query().patchAndFetchById(id, req.body)` I think should work

**Comment by cpsubrian** [comment]
@WilliamSWoodruff Yeah I think you're right about that, but I should have included more of my code hehe .. I'm using some custom jsonSchema stuff and a custom serializer so my code actually looks more like this:

```js
function patchModel (req, res, next) {
  let id = req.query.id
  let body = Model.fromJson(req.body).serialize({writeOnly: true})   // Custom Serializer  <---
  return Model.query().patchAndFetchById(id, body).then((model) => {
    req.objects[objKey] = model
    next()
  })
}
```

**Comment by WilliamSWoodruff** [comment]
@devinivy do you remember what we did to solve the issue where required fields are preventing model updates?

**Comment by devinivy** [comment]
Yes! The model's `$validate(json, options)` receives `options.patch = true` when performing a patch– this can be used to adjust the validation as necessary.

**Comment by WilliamSWoodruff** [comment]
Thanks! @cpsubrian does that help?

**Comment by cpsubrian** [comment]
Yep, I should be able to do `(new Model()).$set().$validate(json, {patch: true})`. Thanks guys!

**Comment by koskimas** [comment]
I assume this was resolved? Please reopen this if not.

**Comment by koskimas** [comment]
@cpsubrian You can also do this
```js
const model = Model.fromJson({foo: 'bar'}, {patch: true})
```
