### ISSUE TITLE
Update an entity with a non persistent child.

### ISSUE THREAD

**Issue by arantessergio** [Vincit/objection.js#322]
Hi everyone,

I have an entity called Order and this has many Items, when I try to update Order, where my items is not persisted yet, I have an updated Order, but my added Item doesn't persist. The solution that I found is persist the Item before I try update the Order. Is there a most easy and correct to do way?

**Comment by koskimas** [comment]
Let me guess, you have been working with hibernate 😄 

You shouldn't think of objection as an ORM, but more like a query builder on steroids. I should probably remove all references to the word ORM from the documentation. You have to explicitly start every database query and nothing like this is done automatically (eager, insertGraph and other "bulk" methods are exceptions to this rule). The whole point of objection is that what you see is what you get; minimal amount of magic. You really need to know SQL (not saying that you don't) to use objection.

I'm working on a `updateGraph` method #211 that would do what you want, but that isn't ready yet unfortunately.

If you are looking for a true ORM that attempts to abstract away SQL, sequelize is probably the best option in the node world.

**Comment by arantessergio** [comment]
First, You guessed :)

I will persist the Item before update Order, provisionally, until your `updateGraph` is not ready, and study Sequelize too.

Thanks very much.
