### ISSUE TITLE
Eager loading with polymorphic associations

### ISSUE THREAD

**Issue by mshibl** [Vincit/objection.js#324]
In your documentation you have the following example for a polymorphic association: 

```
Issue.relationMappings = {
  comments: {
    relation: Model.HasManyRelation,
    modelClass: Comment,
    filter: {commentableType: 'Issue'},
    join: {
      from: 'Issue.id',
      to: 'Comment.commentableId'
    }
  }
};

PullRequest.relationMappings = {
  comments: {
    relation: Model.HasManyRelation,
    modelClass: Comment,
    filter: {commentableType: 'PullRequest'},
    join: {
      from: 'PullRequest.id',
      to: 'Comment.commentableId'
    }
  }
};
```

What if you need to eagerly load the related `commentable_entity` through the `Comment` model? 
Note the modelClass is dependent on the commentable_entity_type which could either be a PullRequest or an Issue, how would you specify the modelClass in this case?

```
Comment.relationMappings = {
    commentable_entity: {
        relation: Model.BelongsToOneRelation,
        modelClass: ????????????????????????,
        join: {
            from: 'comment.commentable_entity_id',
            to: '?????.commentable_entity_id'
        }
    }
}
``` 
I could create 2 eager relations one for the PullRequest and one for the Issue, but I would prefer if I only had to use one relation mapping, for my use case we have 20 different models that can be commented on.

**Comment by ackerdev** [comment]
Adding my support for this. Currently forced to work around this in a very awkward manner by using a module to return another model object based on the parent's type column.

Also very important for our needs for the `type` column to be mapped to custom values, and not inferred from tables/models.

**Comment by koskimas** [comment]
This is impossible at the moment. There is no real support for polymorphic associations at the moment. I'm not sure if we should even add it. #19

**Comment by heisian** [comment]
My solution is this:
```node
const { resolveModel } = require('objection/lib/utils/resolveModel')

class BaseModel extends objection.Model {
  static get modelPaths() {
    return [__dirname]
  }

  // Expose the model resolver utility in model instances
  $resolveModel(modelString) {
    return resolveModel(modelString, this.constructor.modelPaths)
  }
}

class Comment extends BaseModel {
  getCommentable() {
    if (!this.commentableType) return undefined

    // Leverage resolver cache and avoid any require/circular dependencies
    const CommentableModel = this.$resolveModel(this.commentableType)

    // Return the correct commentable type
    return CommentableModel.query().where('id', this.commentableId)
  }
}
```
