### ISSUE TITLE
expose Promise ?

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#33]
Model.Promise or something ?
This is to avoid having to require a (possibly different) promise lib - granted, it is questionnable request.

**Comment by koskimas** [comment]
I could add the Promise constructor to the "main" object like this:

```js
var objection = require('objection');
var Promise = objection.Promise;
```

would that work for you?

**Comment by kapouer** [comment]
Yes, thank you.

**Comment by koskimas** [comment]
Exposed in version 0.2.3.
