### ISSUE TITLE
How work $parseDatabaseJson when we use insertGraph? 

### ISSUE THREAD

**Issue by shcoderAlex** [Vincit/objection.js#331]
When I use insertGraph I get strange json in $parseDatabaseJson method. 
`User.query().insert(user):`
```
User {
  first_name: 'Test',
  last_name: 'Test',
  email: 'test@example.com',
  team_id: 8,
  created_at: '2017-03-16T03:52:40.470Z',
  id: 7 
}
```
`User.query().insertGraph(user):`
```
{}
{ team_id: null }
{}
{ id: null }
{}
{ role_id: null }
{}
{ id: null }
{}
{ id: null }
```
I think it's strange behavior.

**Comment by koskimas** [comment]
Could you post here what you actually pass for the insertGraph method?

**Comment by koskimas** [comment]
Ah, I just figured it out. `$parseDatabaseJson` is is used to detect if your model transforms the column names somehow (for example snake_cas to camelCase conversion). So `$parseDatabaseJson`  is called once for each relation column you have. What are you trying to do in `$parseDatabaseJson` that makes this an issue? The documentation clearly states that you should be prepared fo any input in `$parseDatabaseJson`.

**Comment by koskimas** [comment]
I could specify in the docs that `$parse*Json` and `$format*Json` methods must be pure functions . There should be no side effects since they are called from unexpected places. They should simply map their input to output and do nothing else. There are other hooks that may be better suited for what you are trying to do. For example `$beforeInsert` and `$afterInsert` could work for you.

**Comment by koskimas** [comment]
I updated [the documentation](http://vincit.github.io/objection.js/#_s_formatdatabasejson).

**Comment by shcoderAlex** [comment]
@koskimas 
Hi, thx for your answers, but I think my problem is in another
I use just for this
```
$parseDatabaseJson(json) {
  const newJson = _map(json, (value, key) => camelCase(key));
  return super.$parseDatabaseJson(newJson);
}
```
If I use insert it everything is good, but if I use insertGraph there are problems with some properties

For example:

BaseModel:
```
class BaseModel extends Model {

  $formatDatabaseJson(json) {
    const newJson = super.$formatDatabaseJson(json);
    return _mapKey(newJson, (value, key) => snakeCase(key));
  }

  $parseDatabaseJson(json) {
    const newJson = _mapKey(json, (value, key) => camelCase(key));
    return super.$parseDatabaseJson(newJson);
  }
}
```

User Model:
```
class User extends BaseModel {

  static get tableName() { return 'User'; }

  static get jsonSchema() {
    return {
      type: 'object',
      required: ['email', 'password'],

      properties: {
        id: { type: 'integer' },
        email: { type: 'string' },
        first_name: { type: 'string', minLength: 1, maxLength: 255 },
        last_name: { type: 'string', minLength: 1, maxLength: 255 },
        team_id: { type: 'integer' },
        password: { type: 'string', minLength: 6 }
      }
    };
  }

  static get relationMappings() {
    return {
      team: {
        relation: Model.BelongsToOneRelation,
        modelClass: `${__dirname}/Team`,
        join: {
          from: 'User.team_id',
          to: 'Team.id',
        },
      }
    };
  }
}
```

insert:
```
const user = {
  "first_name": "Test",
  "last_name": "Test",
  "email": "test@example.com",
  "password": "123456"
};

const newUser = User.query().insert(user);

console.log(newUser.firstName) // => Test
console.log(newUser.first_name) // => undefined

```

insertGraph:
```
const user = {
  "first_name": "Test",
  "last_name": "Test",
  "email": "test@example.com",
  "password": "123456",
  "team": {
    "name": "Test"
  }
};

const newUser = User.query().insertGraph(user);

console.log(newUser.firstName) // => undefined
console.log(newUser.first_name) // => Test
```

It's my problem. Maybe I do something wrong.

**Comment by koskimas** [comment]
I don't know why this is happening exactly, but you should give the user you are inserting in the camelCased format since that's what you have defined as your "external" format.

This should work for both `insert` and `insertGraph`:

```js
const user = {
  firstName: "Test",
  lastName: "Test",
  email: "test@example.com",
  password: "123456",
  team: {
    name: "Test"
  }
};

const newUser1 = await User.query().insertGraph(user);
const newUser2 = await User.query().insert(user);

console.log(newUser1.firstName) // => Test
console.log(newUser2.firstName) // => Test
```

**Comment by shcoderAlex** [comment]
@koskimas 
Thank you for your help.
