### ISSUE TITLE
Specify select/returning defaults or default cast for a field?

### ISSUE THREAD

**Issue by pstoica** [Vincit/objection.js#332]
Hey, not sure what I'm looking for exactly but I'm using PostGIS for the Point/Geometry fields and I need to call an internal pg function to get a readable format. I'm using knex-postgis to do:

```
.select(st.asGeoJSON('location'))
```

This gets inconvenient when you want to do an asterisk since you can't override location as far as I could tell, so I made an array I can reference that has all the jsonschema property names with `location` converted. Is there a way to extend QueryBuilder to either default what asterisk is or create an alias for the column? Or am I thinking about this the wrong way?

Thanks for your help!

**Comment by koskimas** [comment]
Unfortunately there is currently no easy way to get a list of columns the asterisk would expand to. There is the `columnInfo` method that returns this information, but objection doesn't fetch that by default.

I'm not familiar with knex-postgis, but if you cannot give an aliast to the `asGeoJson` method, I think this should work:

```js
.select('TheTable.*', 'location as foo', st.asGeoJSON('location'))
```

**Comment by elhigu** [comment]
This might work https://github.com/jfgodoy/knex-postgis/blob/master/lib/functions.js#L85:

```js
.select(st.asGeoJSON('location').as('foo'))
```

**Comment by koskimas** [comment]
@pstoica Did any of the suggestions solve your problem?

**Comment by pstoica** [comment]
Haven't had a chance to try yet but they look like they'd work, thanks! I guess there's not a way that makes sense to change `*` or default the behavior for `foo`, but I can probably create a cast and refer to that without importing knex-postgis every time. I'm good with closing this, thanks again for the suggestions!
