### ISSUE TITLE
Relationship with same name as column

### ISSUE THREAD

**Issue by alexwhitman** [Vincit/objection.js#333]
I have a model which has a relationship with the same name as a column in the table:
```js
static get relationMappings() {
	return {
		section : {
			relation : Model.BelongsToOneRelation,
			modelClass : __dirname + '/Section',
			join : {
				from : 'articles.section',
				to   : 'sections.id'
			}
		}
	};
}
```
If I run
```js
Article.query().insert({
    title : 'Title',
    section : 2
});
```
the `title` attribute is set correctly, but `section` is set to `NULL`.  I'm assuming this is due to the field having the same name as a relationship.

I'm dropping in a lot of seed data for testing purposes so it would be useful to be able to use the above method.  I'm working with a pre-defined database which I cannot change so renaming the column isn't an option.  Is there another solution short of renaming the relationship?

**Comment by koskimas** [comment]
Nope, you need to rename the relationship.

**Comment by modeswitch** [comment]
I'm troubled by the same issue. Would you accept a patch that allows the caller to provide a property name where all the relations will be stashed?

```
.withGraphJoined("my-relation", { propertyName: "@" })
```

which would attach the relation as

```
{
  ... // model properties
  "@": {
    "my-relation": { ... }
  }
}
```

along with any child relations that might be specified using the same property name for each nested model.
