### ISSUE TITLE
`.insertGraph` and `.insert` yields different results.

### ISSUE THREAD

**Issue by peteyy** [Vincit/objection.js#337]
I try to call `.insertGraph` with the same object as I do with `.insert` but `.insertGraph` fails with a property validation error (that is there both times)

If I try to do the same thing with `$relatedQuery` it works fine.

Any ideas how could I be doing wrong, or could you please recommend some potential debugging methods for this issue? `.debug` is a no go since it doesn't even hit `knex` query because it fails on the validation levels.

**Comment by koskimas** [comment]
`console.log`? debugger? what do you normally do to debug?

You could also try posting the actual data and error here, so that I could try to help. With this information there is absolutely nothing I can do.

**Comment by peteyy** [comment]
sorry for the lack of context, since then I figured that it's a bug that was already fixed, but I haven't yet upgraded.

**Comment by peteyy** [comment]
just for anyone bumbing into this thread, it was some $toJson timing issue on inserting.
