### ISSUE TITLE
Select specific fields using returning()/insertAndFetch()?

### ISSUE THREAD

**Issue by iwan-wijaya** [Vincit/objection.js#339]
Hi, I'm a bit confused, what is the "correct" way to select fields from result after an insert/update/patch?

```javascript
// My schema
knex.schema
    .createTable('guest', (table) => {
      table.increments('id').primary()
      table.string('name').notNullable()
      table.string('emailAddress')
      table.string('nationality')
      table.dateTime('createdAt')
      table.dateTime('updatedAt')
    })

// Inserted data
req.body = {
  "name": "Lorem",
  "nationality": "RU"
}
```
**Desired "guest" object result**
`GuestModel { name: 'Lorem' }`

**At first, I tried using returning() as mentioned in the docs (I'm using PostgreSQL)**
```javascript
GuestModel
  .query()
  .insert(req.body)
  .first()
  .returning('name')
  .then(guest => console.log(guest))
```

Result

```javascript
GuestModel {
  name: 'Lorem',
  nationality: 'RU',
  createdAt: '2017-03-22T17:34:09.280Z',
  updatedAt: '2017-03-22T17:34:09.280Z',
  id: 'Lorem' } // ?
```

How come all data get selected? (except nulls)
Using knex's insert without objection.js, it will return just `["Lorem"]` without a property name. Why does this behave differently?

**So I tried using insertAndFetch()**
```javascript
GuestModel
  .query()
  .insertAndFetch(req.body)
  .select('name')
  .then(guest => console.log(guest))
```

Result 

```javascript
GuestModel {
  name: 'Lorem',
  nationality: 'RU',
  createdAt: 2017-03-22T18:27:20.598Z,
  updatedAt: 2017-03-22T18:27:20.598Z,
  id: 233,
  emailAddress: null
```

All data selected including nulls. Not sure if select() is allowed there.

**This works but requires additional function call**

```javascript
  GuestModel
    .query()
    .insert(req.body)
    .then(guest => GuestModel.query().findById(guest.id).select('name'))
    .then(guest => console.log(guest))
```
Result
`GuestModel { name: 'Lorem' }`

Why does `returning()` behave differently in plain knex? and what is the correct way to do this?

**Comment by koskimas** [comment]
There actually seems to be a bug when giving just one column name to `returning`. In that case it assigns the column as the `id` 😬 

Otherwise that's how it has always worked in objection. The columns listed in `returning` are assigned to the inserted object. You can chain the [`pick`](http://vincit.github.io/objection.js/#pick) method to the query to limit properties in this case.

`select` doesn't currently work with `insertAndFetch`, but maybe it should. I'll give that some thought.

**Comment by iwan-wijaya** [comment]
@koskimas Ah, I see. Thanks

**Comment by KhalidBhyan** [comment]
any update about this? `pick` seems not supported anymore and will be deprecated in v3 as per [the documentation](https://vincit.github.io/objection.js/api/query-builder/other-methods.html#pick)

I have the same issue, I can't select which columns to be returned when insert/update/delete while `returning(), select()` can be chained on any query but they return unexpected results, also there are no examples for them in the docs and they redirected me to knex documentation.

**Comment by pkiing** [comment]
Hi, any news on this issue
