### ISSUE TITLE
should query building methods chained to `insertAndFetch`, `patchAndFetch` etc. be called for the fetch query? 

### ISSUE THREAD

**Issue by koskimas** [Vincit/objection.js#340]
Currently they are ignored. Should they be applied to the fetch part of the query? Related to #339

**Comment by elhigu** [comment]
I suppose we have 2 choices:

1. We could allow some building methods to be passed to fetch. We would need to keep track which ones are called and must be passed and clearly document that for example you can call `.select()` for it.

2. Or we can just decide that no. If one likes to change stuff that is selected from in fetch part, they can write own simple helper for that.

Choice 2 sounds simpler. Also allowing `.select()` would be like emulating support for `.returning()`. Anyone has more thoughts about this one?

**Comment by fl0w** [comment]
I'm a simple man, and thus I like simple solutions. Either let fetch in `*AndFetch` to be static (easy to maintain and explain), or require a separate chained call. My brain will hurt if I have to understand why some QB methods propagates down to the fetch call and some doesn't. I fear this might get messy to maintain?

```js
// easy to reason about
Model.query().x().y().z().insertAndFetch(fetchQB => fetchQB.a().b().c())
Model.query().x().y().z().modifyFetch().a().b().c().insertAndFetch()

// not so easy
Model.query().x().y().z().insertAndFetch() // -> y() and z() was passed, not x()
Model.query().x().y().z().insertAndFetch() // -> x() was passed, but also wanted z()
Model.query().x().y().z().customX().insertAndFetch()
// -> customX() cannot be passed? Or can it? How do I pass it to fetch but not the insert?
```

**Comment by koskimas** [comment]
@fl0w You have an excellent point. I was only thinking about `insertAndFetch` where it's pretty clear which methods belong to the insert part and which don't. With  `patchAndFetch` and others it's not clear at all.

So maybe it's better to forget about this.
