### ISSUE TITLE
Join fields lost when using eager

### ISSUE THREAD

**Issue by adiamini** [Vincit/objection.js#341]
`Model.query().select('pets.*')`

returns correctly:

```
[{
    id_pet: 1,
    name: 'One'
},
{
    id_pet: 2,
    name: 'Two'
}]
```

When using eager like:

```
related: {
    relation: Model.HasOneRelation,
    join: {
        from: 'pets.id_pet',
        to: 'something.id_pet'
    }
}
Model.query().select('pets.*').eager('related')
```

This returns wrong, with missing field:

```
[{
    name: 'One',
    related: [{
        id_pet: 1,
        related_data: 'abc'
    }]
},
{
    name: 'Two',
    related: [{
        id_pet: 2,
        related_data: 'xyz'
    }]
}]
```

In this example, field **id_pet** is present in both main table and relation table, and when using eagers it disappears from main table's result.

Note: this is an example, you can try with BelongsToOneRelation or ManyToManyRelation, issue is the same.
Note 2: Just updated objection from 0.6.2 to 0.7.10

**Comment by adiamini** [comment]
I just tested downgrading back to 0.6.2, and then upgrading progressively to 0.7.0, then 0.7.1, then 0.7.2 ...

The issue appears when upgrading to version 0.7.4

**Comment by koskimas** [comment]
Does it work if you leave out the `select pets.*`? I'm assuming that `Model.tableName` is "pets" in your example?

**Comment by koskimas** [comment]
Could you chain `.debug()` method to the failing query and post the generated sql here?

**Comment by adiamini** [comment]
Yes, Model.tableName is "pets".
Yes again, if I remove `select pets.*` it works. (However I need it to select other fields, pets.* is a simplification).

**Comment by adiamini** [comment]
Debug:

```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '6026bdb3-ac37-485b-9920-8da83b888b6b',
  sql: 'select `pets`.*, `pets`.`id_pet` from `pets`' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: 
   [ 1,
     2 ],
  __knexQueryUid: '75066de3-e48c-4735-b27e-38a5ea11dad3',
  sql: 'select `something`.* from `something` where `something`.`id_pet` in (?, ?)' }
```

**Comment by koskimas** [comment]
Yeah, both `pets.*` and a list of columns should work. I was just ruling out a possibility. Seems like a bug that really shouldn't have ended up in a release. I'll try to reproduce and fix this immediately.

**Comment by koskimas** [comment]
I'm not able to reproduce this. I tried that exact query with all different relation types and got all columns back. Could you please write a standalone app that reproduces the problem? There is something in your setup that is triggering this bug that you haven't mentioned here.

**Comment by koskimas** [comment]
For some reason that I cannot figure out the implicit `pets.id_pet` select appears in the query, even though `pets.*` should already select the id. For some reason objection thinks the query doesn't select the needed columns. It then adds those columns to the select clause and removes the values afterwards (the feature added in 0.7.4). Is it possible that you have a typo in `Model.tableName` for example an extra space or something like that?

**Comment by adiamini** [comment]
I agree with your comment: if I debug the same query with 0.7.3 I see

`  sql: 'select `pets`.* from `pets`' }`

in place of

`  sql: 'select `pets`.*, `pets`.`id_pet` from `pets`' }`

I (nor anybody here) can't see any typo in the code.

However we are prefixing table names with database name (since we are merging tables cross different databases), so it actually looks more like:

`  sql: 'select `zoo`.`pets`.*, `zoo`.`pets`.`id_pet` from `zoo`.`pets`' }`

Note: `pets` and `something` are in the same `zoo` database.

**Comment by koskimas** [comment]
The prefixing is the key here :D. Maybe you could have included that in the original example. Using a dot as a separator is not a good idea. I'm pretty sure many other things with objection and knex will blow up as they interpret anything coming after the first dot as the column name. Could you use for example `:` as the separator?

**Comment by adiamini** [comment]
Sorry for not including that in original example, I couldn't figure out the problem could be related to that :-) I think I can't change the dot, because of sql (the dot is not inside the table name, it's to separate DB name and table name); actually if I replace it I got this:

```
  sql: 'select `zoo:pets`.* from `zoo:pets`' }
Error: ER_NO_DB_ERROR: No database selected
```

The extra `id_pet` has disappeared, but ...

**Comment by koskimas** [comment]
Oh, sorry! I thought you had just prefixed your table names. I can fix this particular case, but I'm pretty sure you will run into others that I cannot fix because of knex. I have never used multiple databases like this with mysql. Maybe you could use the `schema` method? That's a knex feature for postgresql schema's which is a similar feature. Objection supports that. Something like this:

```js
Model.query().schema('zoo').select('pets.*').eager('related')
```

I don't know if that works with mysql, but you could give it a try. Anyway I'll try to fix the issue at hand if I can do it without breaking anything else.

**Comment by koskimas** [comment]
@adiamini 0.7.11 is out with this one fixed. I did some testing and you may not be as screwed with the cross-db dot separated queries as I thought. Everything I tried just worked.

**Comment by adiamini** [comment]
Thank you ! I just upgraded to 0.7.11 and tested it and there are cases when it doesn't work: if I use `select('*')` it's ok, but if I use `select('pets.*')` it doesn't (I can see it still adds the extra `id_pet` field in debug).

**Comment by koskimas** [comment]
If your table is `zoo.pets` and you select `pets.*` it won't work, because objection cannot know if there is a `pets` table in your "main" database your knex is connected to. `select('zoo.pets.*')` should now work.

**Comment by adiamini** [comment]
Oh, right ! I can confirm that adding the DB name in the select it works. Thank you very much ! :-)

**Comment by koskimas** [comment]
But column names should work without table name! For example `select('foo', 'bar')` should work now.

**Comment by adiamini** [comment]
Yes of course. ... but I need table name because I'm getting data from joined tables too :-)
