### ISSUE TITLE
Eager fetch is resulting in empty array

### ISSUE THREAD

**Issue by jsumners** [Vincit/objection.js#35]
I have three tables: `people`, `roles`, `person_roles`. I have defined many-to-many relationships on each of the models for `people` (`person`) and `roles` (`role`). As a test, I issue the following query:

```javascript
models.Person
  .query()
  .eager('roles')
  .where({id: 1})
  .then(function (people) {
    console.log(people[0]);
    knex.destroy();
  })
  .catch(function (err) {
    console.error(err);
    knex.destroy();
  });
```

The result of which is the details from the `people` table for that person, but with a `roles` attribute set to `[]`. It looks to me like the issue is happening on [line 94](https://github.com/Vincit/objection.js/blob/master/lib/relations/ManyToManyRelation.js#L94) of `ManyToManyRelation.js`. The result of that line is an object with one property. The name of that property is "undefined". But the next access of that object is:

```javascript
owner[self.name] = relatedByOwnerId[owner[self.ownerProp]] || [];
```

Nothing in the bracket resolves to "undefined", so the result is `[]`.

![2015-09-22_17-26-20](https://cloud.githubusercontent.com/assets/321201/10032113/1c718c58-614f-11e5-892f-3512ed7aa8b2.png)

**Comment by koskimas** [comment]
Can you post the `relationMappings` object of the Person model here?

**Comment by koskimas** [comment]
Actually I think I know what the bug is here. You have a snake_case to camelCase conversion in the model right? It is messing up the `ownerJoinColumnAlias` temporary column here. Can you try to run your code as a test by setting the `ownerJoinColunAlias` constant to for example 'asdasdasd'? Anything that doesn't contain underscore or capitals?

**Comment by jsumners** [comment]
That was it:

```javascript
var _ = require('lodash')
  , Relation = require('./Relation')
  , ownerJoinColumnAlias = 'foobar';
```

After that change the result is an array of `Role` objects just as it should be. For reference, here's my `Model` subclass:

```javascript
'use strict';

const camelCase = require('camel-case');
const snakeCase = require('snake-case');
const Model = require('objection').Model;

function BaseModel() {
  Model.apply(this, arguments);
}

BaseModel.prototype = Object.create(Model.prototype);
BaseModel.prototype.constructor = BaseModel;
Model.extend(BaseModel);

// Convert camel cased object properties to snake cased column names
BaseModel.prototype.$formatDatabaseJson = function objToDb(json) {
  json = Model.prototype.$formatDatabaseJson.call(this, json);

  const dbObj = {};
  for (let key of Object.keys(json)) {
    dbObj[snakeCase(key)] = json[key];
  }

  return dbObj;
};

// Convert snake cased column names to camel cased object properties
BaseModel.prototype.$parseDatabaseJson = function dbToObj(json) {
  const obj = {};
  for (let key of Object.keys(json)) {
    obj[camelCase(key)] = json[key];
  }

  return Model.prototype.$parseDatabaseJson.call(this, obj);
};

module.exports = BaseModel;
```

**Comment by koskimas** [comment]
Great! I will fix this tomorrow and put a new patch version out immediately. This is kind of an embarrassing bug. Thank you for an excellent description!

**Comment by koskimas** [comment]
By the way: you don't need the lines

```js
BaseModel.prototype = Object.create(Model.prototype);
BaseModel.prototype.constructor = BaseModel;
```

Model.extend does this for you.

**Comment by jsumners** [comment]
I look forward to the fix.

I was unaware that `Model.extend` was doing that. I have updated my code. Thank you.
