### ISSUE TITLE
Postgres 'returning "id"' appended to Insert query on table/model that has no "id" column

### ISSUE THREAD

**Issue by newhouse** [Vincit/objection.js#350]
I'm using Postgres and (sadly) Objection 0.6.2, so maybe this is not an issue anymore, or perhaps it's a Knex issue.

I have a simple Model and table called `performance` that has the following columns:
`object_id`, `time` and a JSON `data` column.

Here's an example query giving me trouble:
```
Performance
  .query()
  .insert({
    object_id: someId,
    time: someTime
    data: someData
  });
```

When I perform that Insert query, I get an error back saying `error: column "id" does not exist`.  A debug output shows the following query:
`insert into "performance" ("data", "object_id", "time") values (?, ?, ?) returning "id"`

Something is tacking on the `returning "id"` to the query. Everything is very vanilla except that my Model/table doesn't have an `id` column (they'd really a composite PK at best). I'm not sure why the 'returning "id"' is getting tacked on there, but it's causing this error.

Workarounds/solutions/thoughts:
- Should I add an "id" getter to my model? I don't really have an ID or need anything back after insertion, so while it may work it doesn't _feel_ right so I have not tried it.
- If I chain a `.returning(false)` the "returning" clause is omitted from the query and this seems like what I wanted/expected it to do.
- If I chain a `returning('*')` to the query, a "returning('*')" is added and it's all good...but I don't _want_ any data back.

Is this expected behavior and just a bug in my brain, or is it a bug in Objection/Knex, or something else?

**Comment by koskimas** [comment]
The static idColumn property should point to an existing column. As a workaround you can set it to be any existing column like `object_id`.
