### ISSUE TITLE
Possible to use instance property in `modify` of `relationMapping` triggered by an `eager`?

### ISSUE THREAD

**Issue by newhouse** [Vincit/objection.js#351]
Hello again, and thanks for all the hard work!

I'm wondering if the following is possible:
To utilize a property of a parent instance in the `modify` portion of a `relationMapping` for a Model that's triggered as part of an `eager` clause.

Example:
I have `Post` Model (table `posts`) which is related to the `Performance` Model (table `performance`) as `performanceHistory` by way of a `relationMapping`. I want to have the `modify` portion of the `Post.relationMappings.performanceHistory` entry use a calculation that's based on a value contained on/in `Post`/`posts`. I'm having trouble figuring out a way (or the best way) to do so.  It may also be of import that I am eager-querying from the `Post` Model, and not via an instance...though I could change that if it will get the job done efficiently and elegantly. Here's some relevant code:

```
// POST CLASS
class Post extends Model {
...
  relationMappings() {
    return {
      performanceHistory: {
        relation: Model.HasManyRelation,
        modelClass: __dirname + 'Performance',
        join: {
          from: 'posts.id',
          to: 'performance.object_id'
        }
        modify: builder => {
          // Where 'this' is an instance of Post...but it's not actually an instance, in my experience/testing/fiddling
          const valueImAfterBasedOnPostValue = someFunctionReturningAValue(this.someProperty); 
          if (valueImAfter) {            
            builder.where({
              someField: valueImAfterBasedOnPostValue
          });
        }
      }
    };
  }
...
}

// QUERY EXAMPLE
Post
  .query()
  .eager('performanceHistory')
  .where({id: 'POSTID123'})
  // Actually in this example I'm not sure what would come out, probably all `Performance` instances related to Post 123,
  // but definitely not the ones filtered by the 'where' I was trying to use in relationMapping
  .then(console.log); 
```

It appears that `this` in the `relationMapping.modify` is the `Post` class itself and _not_ an instance. When I think about it, this makes sense and I'm not surprised, really....but I'm wondering if the capability I'm after exists. For full disclosure, the actual query is on a much "hairier" beast that looks something like:
```
const allowedEagers = '[campaignRoles, broadcasts.posts.[channel, performanceHistory]]';
const eager = req.query.relations;
Campaign
  .query()
  .eager(eager)
  ...
```

I was thinking about plucking out the `performanceHistory` from the user-provided `eager` (if it's there) and then calling `loadPerformanceData` on each `Post` instance or something after the initial query results, but that feels quite hackish/roundabout.

Thanks for your time, effort, and expertise!

**Comment by koskimas** [comment]
Eager queries are created for multiple parents at a time for peformance reason. So there is no single parent for the query passed into the `modify` functions. For example in your eager query `[campaignRoles, broadcasts.posts.[channel, performanceHistory]]` one single `performanceHistory` query is generated for all posts of all broadcasts of all campaigns.

One way to do this is to override the `$afterGet` hook and call `loadPerformanceData` from there.

**Comment by newhouse** [comment]
Ok, thanks for the reply and the suggestion!
