### ISSUE TITLE
whereInComposite for mssql

### ISSUE THREAD

**Issue by ivanbaj** [Vincit/objection.js#355]
I am trying to use whereInComposite with a mssql dialect.

The SQl that comes out is:

where ([Id], [OrganizationId]) in (@p0, @p1),(@p2, @p3).....)

However this is not proper TSQL for MS-SQL server.

Are there any plans for making whereInComposite  compatible with MS-SQL?

Or any guidance how to modify the code?

I see: './operations/whereInComposite/WhereInCompositeSqliteOperation'

Is the plan to have ./operations/whereInComposite/WhereInCompositeMSSqlOperation'?

**Comment by koskimas** [comment]
There are no plans to maintain MSSQL-specific things at least until there is some way to test them in travis. I will accept a pull request though.

`WhereInCompositeMSSqlOperation` is the way to do it. You also need to specify the operation class for the `whereInComposite` function in QueryBuilder the same way it is done for sqlite.
