### ISSUE TITLE
HasManyRelation - inserting child (same model)

### ISSUE THREAD

**Issue by adamryvola** [Vincit/objection.js#358]
Hi,
I have model Message and each message could have sub-messages (list of child messages).
Relation definition is: 
```
            messages: {
                relation: Model.HasManyRelation,
                modelClass: Message,
                join: {
                    from: `${MESSAGE_TABLE_NAME}.id`,
                    to: `${MESSAGE_TABLE_NAME}.parent_message_id`
                }
            }
```

If I want to add some child message to messages collection I got error: 

```
error: duplicate key value violates unique constraint "message_pkey"
detail: "Key (id)=(2) already exists."
```
So it looks like hasOne, not hasMany relation.

I tried 2 methods for insert:
1. insert submessage with `parrent_message_id` attribute
2. insert message  (without `parent_message_id`) and then call `relate(message.id, submessage.id)`
And both return same error.

Can you help me with it?

I use postgreSQL.

Thanks for your time and advice!

**Comment by koskimas** [comment]
I'm quessing the model you are trying to insert has some value in the `id` property...

**Comment by koskimas** [comment]
@xxxKOTxxx It's actually the database itself that does that. Database engines don't increment the identifier sequence when it's not used (a value is given by user).

**Comment by xxxKOTxxx** [comment]
Got it, thanks!
