### ISSUE TITLE
Use context in model

### ISSUE THREAD

**Issue by Claud** [Vincit/objection.js#359]
How i can get access to the context inside model?

```
    $formatJson(json) {
        json = super.$formatJson(json);
        let context = this.context(); // not defined
    }
```

**Comment by koskimas** [comment]
There is no way to access the query context from `$formatJson` because it's not always associated with a request at all. What are you trying to achieve? Maybe you can use `$afterGet` instead? `$afterGet` gets passed the query context.

**Comment by Claud** [comment]
I try access to "koa context" object. My "koa context" have common data: user model, log, id request. user timezone. I try use this data for processing result.
