### ISSUE TITLE
Strange join eager query issue

### ISSUE THREAD

**Issue by richardsimko** [Vincit/objection.js#361]
I'm having some trouble using the Join algorithm for eager queries. When running my tests it will some normally resolve to the following SQL:

    select "TableA"."id" as "id", "TableA"."date" as "date", "relation"."id" as "relation:id" from "TableA" as "TableA" left join "TableB" as "relation" on "relation"."foreignKey" = "TableA"."id" where "TableA"."id" = ?

(I've omitted a lot of the columns but basically it lists every column)

That query works as expected, it gets all the related and the `TableA` objects that it's supposed to. 

However in some cases it does the following query instead:

    select * from "TableA" as "TableA" left join "TableB" as "relation" on "relation"."foreignKey" = "TableA"."id" where "TableA"."id" = ?

And in this case it doesn't work, the related models aren't mapped properly and the returned object does not contain the relations, only the base model.

The code doing this is exactly the same in both cases, the only difference being that I in one situation run all the tests (Integration+unit) in one go, at that point it works, but if I pick only the unit tests the same code does not work. If I run a single test it also works.

I understand that knowing the source of this weird behavior is a tall order but I was hoping that someone might be able to point me in the right direction as to where I might find some more clues. For example, where is the actual query generated? Where is the logic that differentiates the cases where all columns are listed and when `*` is used?

**Comment by koskimas** [comment]
It's really difficult to say anything based on this information without sacrificing hours to your problem. Please read and follow [the issues section](http://vincit.github.io/objection.js/#contribution-guide) from the contribution guide if you want more help.

What I can tell you based on this is that `select *` should never be there. The relevant code is found [here](https://github.com/Vincit/objection.js/blob/master/src/queryBuilder/operations/eager/RelationJoinBuilder.js).

**Comment by richardsimko** [comment]
Yeah, I'm fully aware that it's a tall order to be able to give a direct answer to this (Which is why I wrote so in the ticket) however debugging a code base such as this one without knowing it is close to impossible, which is why I thought this would be the place to ask for pointers.

The fact that it shouldn't be there is helpful, now at least I know which of the two is the expected behavior ;) I'll have a look at the file you linked, thanks!

**Comment by koskimas** [comment]
I'd be happy to help if you can provide a standalone app that reproduces the problem (gets the `select *` there). `0.7.X` patch versions have lots of fixes for the eager join stuff. Are you using the latest version.

**Comment by richardsimko** [comment]
Yeah, but the problem is for me to figure out what actually causes it, as the only reproduction I've found so far is running a certain subset of my test cases which is really odd.

I made a little bit of progress, noting that in the bad case the following array is empty: `columnInfo[modelClass.tableName].columns` in the method `buildSelects` in the piece of code you linked me to. Now I'm trying to figure out why that happens only in some cases and not in others.

Yeah, we're using `0.7.10` I'm afraid.

**Comment by fl0w** [comment]
@richardsimko are you able to minimise and isolate what's happening? With current information, my only idea is that you're leaving a state which "overflows" to adjacent tests.

**Comment by richardsimko** [comment]
I'm trying my best ;)

I'm using SQLite in-memory and wiping it between tests, my current working theory is that some part of the tests are not properly waiting for this to be done, causing objection to attempt a fetch of columnData when there are no columns (Because the migrations are being run) and as a result ending up with an empty list of columns. However there's a lot of guesswork involved from my side at this point!

**Comment by richardsimko** [comment]
Found it! I've nailed it down to one of the test cases (Which was being run first in one case but not in the other) which runs through all methods triggering database queries, doing some validation on how input is handled. This test doesn't perform migrations in the "normal" way and since Objection caches the columnInfo, that bad state gets left behind for future test cases.

While I wouldn't really call this a bug, it falls more in the column of "user induced weird behavior", is it possible to somehow clear out this state between test cases, forcing Objection to re-fetch the columnInfo?

**Comment by koskimas** [comment]
The `columnInfo` cache is the only global state objection stores. I would really like to get rid of it somehow, but the `columnInfo` queries need to be cached or they will destroy the eager join performance.

I could maybe store the cache in the `knex` instance. That way it would get destroyed with knex. Would this solve your problem? I don't really like adding a method like `objection.reset()` because it seems like something you __need__ to call between every test or something even if it's useful only in this kind of weird test scenarios.

**Comment by richardsimko** [comment]
Yeah, it's a really slim usecase. I worked around it by running the test causing the issues in a separate run. Is the variable holding the columnInfo exposed somehow? I realize that it would be a "private" variable but for a test it might be good enough to simply set it back to `undefined`?

**Comment by koskimas** [comment]
It's not exposed at the moment, but I can move it to `RelationJoinBuilder.columnInfo`. Then you could clear it out like this:

```js
require('objection/lib/queryBuilder/operations/eager/RelationJoinBuilder').columnInfo = {};
```

**Comment by richardsimko** [comment]
Yeah, that would work! Since it's only for the purposes of a test case so I feel like it would be OK to use a private variable that way.
