### ISSUE TITLE
Empty object after json validation

### ISSUE THREAD

**Issue by richardsimko** [Vincit/objection.js#362]
When using JSON validation with `patchAndFetchById()` (I'm assuming `patch()` behaves the same way) one can end up with an empty object after validation, since the `required` part of the schema isn't validated. This will result in invalid SQL statements such as this one:

    update "Test" set  where "Test"."id" = 1

Perhaps an error should be thrown after validation if the resulting model is completely empty during a patch or operation?

Here is a sample model:

    const Model = require('objection').Model;

    class TestModel extends Model {
      static get tableName(){
        return 'Test'
      }

      static get jsonSchema() {
        return {
          type: 'object',
          required: ['test'],
          properties: {
            id: {type: 'integer'},
            test: {type: 'string'}
          }
        };
      }
    }
    
    TestModel.query().patchAndFetchById(1, {test2: 'test'});

**Comment by koskimas** [comment]
Yep. Currently all properties that are not listed in `jsonSchema` (if jsonSchema is defined) are omitted from the database representation. This behaviour will change in 0.8.0. You can already control it using the static `Model` property [`pickJsonSchemaProperties`](http://vincit.github.io/objection.js/#pickjsonschemaproperties).

Related to #299 and #308

**Comment by richardsimko** [comment]
I knew I had seen something like that in the docs but I couldn't find it when I went back to look for it, thanks!
