### ISSUE TITLE
Querying a parent model by related properties

### ISSUE THREAD

**Issue by jeff3yan** [Vincit/objection.js#363]
I'm trying to filter a parent model based on it's related properties on PostgresQL, e.g.
Country _hasMany_ City _hasMany_ Customers

I want to query all customers who live in a country.

I thought the query would look something like this:
```
Customer
  .query()
  .eagerAlgorithm(Customer.JoinEagerAlgorithm)
  .eager('[city.country]')
  .modifyEager('[city.country]', builder => builder.where('city:country:name', 'United States'))
```

The eager query works as expected, including the related models on the customer rows.

However, using the alias in the where query results in postgres throwing an error about the column not existing. It looks like this is a [known behavior of postgres](http://stackoverflow.com/questions/38040631/postgresql-does-not-accept-column-alias-in-where-clause), since column aliases cannot be used in where queries.

Is this a bug, or have I read the [documentation](http://vincit.github.io/objection.js/#joinrelation) wrong?

**Comment by koskimas** [comment]
Since the whole relation tree is joined, you need to apply the filter on the root query like this:

```js
Customer
  .query()
  .eagerAlgorithm(Customer.JoinEagerAlgorithm)
  .eager('city.country')
  .where('city:country.name', 'United States')
```

**Comment by jeff3yan** [comment]
@koskimas that works perfectly, wasn't aware that this was the case. Originally thought it was an issue with [objection-find](https://github.com/Vincit/objection-find).

Great to hear nested filtering exists with this type of syntax natively, as it's perfect to (partially) expose via API.

**Comment by Rfrixy** [comment]
Is there a way to make such filters in withGraphFetched also?

**Comment by jeff3yan** [comment]
@Rfrixy what exactly is the filter you want to apply?

**Comment by Rfrixy** [comment]
@jeff3yan  ty for asking.

I have an Object A related to Object B and B is related to C..

I fetch graph for A - { B: { C }} , so the whole nested result is returned.

Now I want all 'A's where there exists a C = 1...  
I do NOT want to filter Cs where C is 1.

**Comment by jeff3yan** [comment]
@Rfrixy I don't think there's a built-in method to do this arbitrarily for _any_ relation types.

However if the relationship above is exactly how you specified (A _belongsTo_ B _belongsTo_ C), then you could something like:

```javascript
A.query()
  .leftJoinRelation('b.c')
  .eager('b.c')
  .where('b:c.columnNameInC', 1)
```

Just a bit of shameless self-promotion, but I do the exact thing in [objection-filter](https://github.com/tandg-digital/objection-filter) - on arbitrarily defined relations.
