### ISSUE TITLE
Regression: 0.7.6 broke count()

### ISSUE THREAD

**Issue by Huulivoide** [Vincit/objection.js#364]
Prior to 0.7.6 doing `Model.query().count()` resulted in in a query `select count(*) from "model"` as the underlying knex count function defaults to '*' as the column name parameter, in an falsy value is passed in.

After 0.7.6 if no column name is specified the query becomes  `select "model".* from "model"`.

**Comment by koskimas** [comment]
hmm.. Does knex documentation mention that `count` can be called without arguments? I didn't find it. I'm trying to make objection as compatible as possible with the knex API, but I don't try to reproduce the undocumented functionality. 

It's possible that this worked before by accident. I'd recommend just changing the `count` calls to take a column name or `*`. Or is this somehow not an option?

**Comment by Huulivoide** [comment]
The documentation doesn't mention that, but they do have tests for that functionality.

**Comment by koskimas** [comment]
Fair enough. This will be fixed in 0.8.
