### ISSUE TITLE
Objection with GraphQL usage

### ISSUE THREAD

**Issue by VladShcherbin** [Vincit/objection.js#365]
I'm trying to wire graphql and objection to avoid N+1 queries. Simple example:

GraphQL:

```graphql
type LeatherType {
  id: Int!
  title: String!
  colors: [LeatherColor]
}

type LeatherColor {
  id: Int!
  title: String!
}

type Query {
  leatherTypes: [LeatherType]
}
```

Objection models:

```js
class LeatherType extends Model {
  static tableName = 'leather-types'

  static relationMappings = {
    colors: {
      relation: Model.HasManyRelation,
      modelClass: `${__dirname}/LeatherColor`,
      join: {
        from: 'leather-types.id',
        to: 'leather-colors.leather_type_id'
      }
    }
  }
}

class LeatherColor extends Model {
  static tableName = 'leather-colors'

  static relationMappings = {
    leatherType: {
      relation: Model.BelongsToOneRelation,
      modelClass: `${__dirname}/LeatherType`,
      join: {
        from: 'leather-colors.leather_type_id',
        to: 'leather-types.id'
      }
    }
  }
}
```

So, now I want to take all leatherTypes and their colors with graphql resolvers:

```js
LeatherType: {
  colors(leatherType) {
    return leatherType.$relatedQuery('colors')
  }
},
Query: {
  leatherTypes() {
    return LeatherType.query()
  }
}
```

It works, but produces N+1 queries. How is it possible to prevent this?

**Comment by koskimas** [comment]
You may want to check out https://github.com/Vincit/objection-graphql. Its not actively maintained at the moment, but you can check out the code. Basically I get the graphql AST tree and build a eager expression from it. Then I only register a resolver to the root that performs the eager query.

**Comment by VladShcherbin** [comment]
Would be great to see an example of this (in the docs or in the examples folder) as graphql is getting a hype today.

**Comment by koskimas** [comment]
https://github.com/Vincit/objection-graphql is the example 😄 

This isn't a simple problem and objection-graphql is pretty much the minimal amount of code you need to do it. If you build your GraphQL schema by hand you can probably get forward by simply checking out the [buildEager method](https://github.com/Vincit/objection-graphql/blob/master/lib/SchemaBuilder.js#L230).

**Comment by ismaelaarab** [comment]
@vladshcherbin find any solution for the N+1 with this example?

**Comment by vladshcherbin** [comment]
@ismaelaarab yep, I used [dataloader](https://github.com/facebook/dataloader). There is a related [issue](https://github.com/Vincit/objection.js/issues/419) with an example and suggestions to follow 😉
