### ISSUE TITLE
Relate behaving in unexpected way for 1-to-many relation

### ISSUE THREAD

**Issue by mattboutet** [Vincit/objection.js#366]
I'm using the `relate` function and it seems to pass the key through regardless of whether or not any records were updated.  For the return value, I'd have expected an integer representing the number of updated rows, or maybe the updated record, but what I'm getting back gives no indication of whether or not it succeeded.  
Note: this is a MySQL DB.

```javascript
const modelId = 2;
const nonexistentRelationKey = 'foo';

Model.query().findById(modelId).asCallback((modelErr, foundModel) => {

    foundModel.$relatedQuery(relationModel).relate(nonexistentRelationKey)
    .asCallback((updateErr, value) => {

        if (updateErr){
            return (updateErr);
        }

        if (value === nonexistentRelationKey) {
            return (null, 'This seems like a bug');
        }
    });
}
```

This code is generating 

```
bindings: [ 2, 'foo' ],
sql: 'update `relation` set `model` = ? where `relation`.`id` in (?)' }
```

Which is fine, but which affects 0 rows.

Am I doing something wrong here?  If not, is there a way to get `relate` to divulge more info about what was updated?

**Comment by devinivy** [comment]
I delved into this a bit and found that the input to `relate()` is explicitly being returned, which isn't particularly useful.  It seems the code change to instead return the result of the underlying `patch()` (the number of affected rows) is relatively straightforward.  I think it would be useful.  Might this fit into v0.8 @koskimas?

**Comment by koskimas** [comment]
Sounds like a good idea. I'll fix this in 0.8.

**Comment by mattboutet** [comment]
@koskimas -- I'd be happy to submit a PR to make this change.  I've already made the code changes, and am hoping to go through the tests this weekend.

**Comment by koskimas** [comment]
For `BelongsToOne`, `HasOne` and `HasMany` relations `relate` is an update operation and returning the number of affected rows makes sense. For `ManyToMany`  and `HasOneThrough` it's an insert. What should we return for those? I see two options:

1. Keep the API consistent across relation types and return a number (the number of inserted rows)
2. Return what the insert would natively return (the ids of the inserted rows etc.)

I'm leaning towards 1, but the number of inserted rows has very little use. Basically it would always be the number of items you try to relate. If something goes wrong with an insert, an error is thrown.

**Comment by koskimas** [comment]
@mattboutet Thanks for the offer, but this is a small change and it's easier if I do it myself.

**Comment by devinivy** [comment]
I'd go with whatever is most flexible– so probably pass-through what it would natively return.  That way (I think) one could take advantage of postgresql's `returning()` trick to, for example, obtain the newly created join records or updated records.  That idea relates to something I was wondering about with `relate()`– might it make sense to allow passing the full join record to `relate()` in the case of a many-to-many through?  Imagine if there are additional columns on the junction table, and you'd like to `relate(id, record).returning('*')` to obtain the created `record`.
