### ISSUE TITLE
Problem using composite keys on Model that uses $formatDatabaseJson and/or $parseDatabaseJson

### ISSUE THREAD

**Issue by newhouse** [Vincit/objection.js#367]
Hello there!

I've got an issue where I have a table/model called `Performance`, which has the following significant columns: `object_id`, `time` and `frequency`. (It actually has more, such as the actual data, but they're not significant I don't believe)

- As you might guessed, the `object_id` is a Foreign Key, but can point to a Primary Key on many different Models/Tables. Probably not significant, but mentioning in case.
- The primary key on the `Performance` Model/Table is a composite key consisting of: `object_id`, `time` and `frequency` together.
- In order to store things in the DB more efficiently, I'm leveraging the `$formatDatabaseJson` to dehydrate human-readable values before writing them to the Database, and calling `$parseDatabaseJson` to convert them back upon loading.

Here's a rough outline of the `Performance` model:
```
class Performance extends Model {
  ...
  static get idColumn() {
    return ['object_id', 'time', 'frequency'];
  }

  ...

  $formatDatabaseJson(json) {
    json = super.$formatDatabaseJson(json);
    // Dehydrate frequency, etc.
    json.frequency = mapLongFrequencyToShort(json.frequency);
    ...
  }

  $parseDatabaseJson(json) {
    // Hydrate frequency, etc.
    json.frequency = mapShortFrequencyToLong(json.frequency);
    ...
    return super.$parseDatabaseJson(json);
  }
  ...
}
```

Here's my quandary:
- With `frequency` coming back as part of the composite key, I receive the following error when I try to delete a model instance with `performanceInstance.$query().delete()`:
```
// I *think* this only happens during Delete, but maybe other cases
Error: performance.$parseDatabaseJson probably changes the value of the id column `frequency` which is a no-no.
```
- If I remove `frequency` from my composite key, I may inadvertently delete extra `Performance` entries in the DB if, for example, there are several rows in the DB with the same `object_id` and `time` as my instance, but with different `frequency` values. This is 💀 🔥 ⚠️  and I don't trust myself to remember to add `performanceInstance.$query().delete().where('frequency', mapLongToShort(performanceInstance.frequency)` (or equivalent) every time I want to delete an instance.

Any guru suggestions on this one? I'm afraid I'll likely have to take the approach of using the "dehydrated" values everywhere, and converting them to their human-readable values during to `toJSON` processing when appropriate. This would not be the end of the world by any means, but am wondering if there's a trick or approach I'm missing that could work and leave things mostly as-is. I may have chosen the wrong approach for this one from the start 😭 

Thank you very much for all the work on Objection. I've been spreading the word as much as possible...

**Comment by koskimas** [comment]
`$parseDatabaseJson` and `$formatDatabaseJson` get called in weird places to convert column names to property names (in case they have been overridden to perform for example a snake_case to camelCase conversion). You need to be prepared for undefined null and missing values in `json`.

Does the error go away if you only call `mapShortFrequencyToLong` when the json contains a `frequency` and make sure you the function handles null properly?

**Comment by newhouse** [comment]
I saw those _nota benes_ in the docs, and figured they are the reason behind the error. Unfortunately only mapping `frequency` when it's present as you suggested did _not_ result in the error going away.

Out of curiosity, I tried applying the same approach in the `$parseDatabaseJson` and received a new, different error:
```
// bindings: [ 'PSTZZNPGNVG5151VWFREE1', 'daily', 2017-04-27T22:51:56.037Z ]
error: delete from "performance" where "performance"."object_id" = $1 and "performance"."frequency" = $2 and "performance"."time" = $3 - invalid input syntax for integer: "daily"
```

Are you saying that you think this is a bug and can be changed/fixed to allow this to happen as I expected? Wouldn't want to cause anything to break, of course. Thanks for your help!

**Comment by koskimas** [comment]
This is definitely a bug, but I cannot figure out what is causing this if my suggestion didn't fix it. Could you create a minimal standalone app that reproduces the problem?

**Comment by newhouse** [comment]
Yeah I can whip something up. Before I do, I didn't mention that I'm still using 6.x. Do you think that changes anything materially?

**Comment by newhouse** [comment]
This reproduces this issue for me:
https://gist.github.com/newhouse/88acab94f45388a8fa19070926779556

Let me know if you need anything else...

**Comment by koskimas** [comment]
Thanks for the excellent repro! If only I got one of these every time someone had a problem.

The problem is in objection, but I don't know if it is a bug or not. As you found out also, a new error is thrown if you also check the existence of `frequency` in `$parseDatabaseJson` but that's what you should do. The error in that case is because objection doesn't map the `id` values through `$formatDatabaseJson` in case of `$query().delete()`. The same thing happens when you pass a `frequency` to any of the query building methods (where, whereIn etc.): you would need to use the database values. This is such a large issue that changing it would break __a lot__ of code out there and both approaches have their issues. So here's what is would suggest: map the frequency to "short" in the `$parseJson/$formatJson` interface and always deal with the short values in code. You should probably use some kind of constants instead of literals to make it readable.

```js
  static get jsonSchema() {
    return {

      type: 'object',

      required: ['object_id', 'frequency', 'time'],

      properties: {

        object_id: {
          type: 'string',
          maxLength: 4
        },

        frequency: {
          type: 'integer',
          enum: _.values(FREQ_LONG_TO_SHORT)
        },

        time: {
          type: 'string',
          format: 'date-time'
        }
      }
    };
  }

  $formatJson(json) {
    json = super.$formatJson(json);

    if('frequency' in json) {
      json.frequency = FREQ_SHORT_TO_LONG[json.frequency];
    }

    return json;
  }

  $parseJson(json, opt) {
    if ('frequency' in json) {
      json.frequency = FREQ_LONG_TO_SHORT[json.frequency];
    }

    return super.$parseJson(json, opt);
  }
```

I know this is not the optimal solution. Does this work for you?

**Comment by newhouse** [comment]
I can make it work and realize that it's probably just how it is and needs to be. Thanks for looking into it!
