### ISSUE TITLE
Timestamptz being parsed into js Date

### ISSUE THREAD

**Issue by Tapppi** [Vincit/objection.js#368]
Hey, reading through past issues it seems dates from PostgreSQL timestamp with timezone isn't supposed to be parsed through dates, but since upgrading to latest from ~0.6.x, I'm getting back JS Date objects from a model. I don't have any custom type parsing.

I'll test this more once I have time, since this wasn't critical in this upgrade, but will be soon.

**Comment by elhigu** [comment]
By default node-postgres parses timestamp, timestampz and date columns to Date objects. I don't remember that older objection would have changed that default behavior either.

**Comment by Tapppi** [comment]
Alright, I must have been mistaken, I'll dig through if I just had my assumptions wrong about how this sits into our stack.
