### ISSUE TITLE
Model.$beforeUpdate has no effect on actual SQL update

### ISSUE THREAD

**Issue by jsumners** [Vincit/objection.js#37]
I have a model that defines a `$beforeUpdate` method:

```javascript
Person.prototype.$beforeUpdate = function beforeUpdate() {
  this.email = `${this.email}.updated`;
  this.updatedAt = new Date();
};
```

If I log the `Person` instance prior to `$beforeUpdate` then `email` and `updatedAt` are at their original values. Once `$beforeUpdate` is invoked, and I log the same instance of `Person`, the fields have been modified accordingly. However, if I query my database directly, those two fields contain the original values they had _prior_ to `$beforeUpdate` being invoked.

I am performing my update like so:

```javascript
Person.query()
    .update(person)
    .where({id: person.id})
    .then(function (p) {
      console.log(`Updated person: ${p.username}`);
      return Promise.resolve(p);
    });
```

This is happening with Objection version 0.2.4.

**Comment by koskimas** [comment]
Wow, you seem to be right. I'm fixing this right now and writing tests for it that actually work :D

**Comment by jsumners** [comment]
Thank you very much.
