### ISSUE TITLE
Feature request: add JoinEagerAlgorithm equivalent for loadRelated

### ISSUE THREAD

**Issue by fl0w** [Vincit/objection.js#372]
A common use case I keep stumbling upon is having allot of 1-1 relations in "large" quantities loaded eagerly. For example, query an account and all its users, and some user meta table.

`Account` <== `User` <-- `Meta`

Instinctively I'd like to avoid throwing a 3-4k `whereInComposite` query at Postgres by doing:
```js
const account = await Account
  .query()
  .where(...)
await account
  .$loadRelated('[users.meta]')
  .eagerAlgorithm(Account.JoinEagerAlgorithm)
```

There's simple workaround today by splitting the request e.g.
```js
// pseudo, untested
const account = await Account
  .query()
  .where(...)
account.users = await User
  .query()
  .where('account_id', account.id)
  .eager('meta')
  .eagerAlgorithm(User.JoinEagerAlgorithm)
```

*Disclaimer; I understand the example "table design" is stupid*

**Comment by koskimas** [comment]
Good idea. I can't promise anything before I see if there was a reason I didn't do this in the first place.

Regarding your example, why don't you just do this:

```js
const accounts = await Account
  .query()
  .eager('users.meta')
  .eagerAlgorithm(Account.JoinEagerAlgorithm)
```

?

**Comment by fl0w** [comment]
@koskimas Micro optimisation was the initial reason, really. The example is not real-world.
Consider having a larger amount of users rows, I'd love to avoid duplication thrown from account table for each user, it's the same for each.

**Comment by fl0w** [comment]
I keep stumbling on the following use case:

```js
const user = await User.forge().where(...)
...
if (someCondition) {
  user.$loadRelated(...) // Here's where I'd like to manipulate eager algorithm.
}
```

**Comment by koskimas** [comment]
You wouldn't believe how difficult this would be to implement 😓 It involves creating a hybrid of `WhereInEagerAlgorithm` and `JoinEagerAlgorithm` because the first level is already fetched. I tried to implement such an algorithm because it would be really great from performance perspective also: it could fetch one-to-one relations using joins recursively and all other relations using `WHERE IN`s. It would be the best from both worlds.

Maybe I'll attack that at some point, but not for a while.

**Comment by fl0w** [comment]
Understood.
In my specific case, I found that `QueryBuilder.joinRelated` (and friends) in combination with a little forethought did the trick. E.g. I preferred to `JOIN` an extra or two tables instead of conditioning it down the road. I think my real problem is the weird schema design.
