### ISSUE TITLE
Correct insertGraph usage

### ISSUE THREAD

**Issue by VladShcherbin** [Vincit/objection.js#373]
I'm got User and Permission (many to many).
User has unique fields (username, email), same as Permission has unique (title, description).
Simple user insert example:

```js
// Models
class User extends Model {
  static tableName = 'users'

  static relationMappings = {
    permissions: {
      relation: Model.ManyToManyRelation,
      modelClass: `${__dirname}/Permission`,
      join: {
        from: 'users.id',
        to: 'permissions.id',
        through: {
          from: 'user_permission.user_id',
          to: 'user_permission.permission_id'
        }
      }
    }
  }
}

class Permission extends Model {
  static tableName = 'permissions'

  static relationMappings = {
    users: {
      relation: Model.ManyToManyRelation,
      modelClass: `${__dirname}/User`,
      join: {
        from: 'permissions.id',
        to: 'users.id',
        through: {
          from: 'user_permission.permission_id',
          to: 'user_permission.user_id'
        }
      }
    }
  }
}

// Example
const user = await User.query().insertGraph({
  username: 'user',
  email: 'email@gmail.com',
  password: 'password',
  permissions: [
    {
      title: 'admin.all',
      description: 'Yolo'
    }
  ]
})

const secondUser = await User.query().insertGraph({
  username: 'user-1',
  email: 'email-1@gmail.com',
  password: 'password',
  permissions: [
    {
      title: 'admin.all',
      description: 'Yolo'
    }
  ]
})
```

First user will be added with no problem, the second will hit the unique error:

```js
error: duplicate key value violates unique constraint "permissions_title_unique"
```

However, the second user info will be stored in the database, but without permissions. Isn't it supposed to rollback all second user queries?

**Comment by koskimas** [comment]
Objection never starts a transaction implicitly. You need to start a transaction yourself and perform the insert inside it.

```js
const secondUser = await objection.transaction(User.knex(), async (trx) => {
  const secondUser = await User.query(trx).insertGraph({
    username: 'user-1',
    email: 'email-1@gmail.com',
    password: 'password',
    permissions: [
      {
        title: 'admin.all',
        description: 'Yolo'
      }
    ]
  })

  return secondUser;
})
```

**Comment by VladShcherbin** [comment]
@koskimas thanks, will try this. What's the recommended way of returning unique validation error here?

**Comment by koskimas** [comment]
What do you mean? If `insertGraph` throws in this example, the `await objection.transaction(...)` will also throw the same exception after the transaction has been rolled back. Do you mean how to detect the unique violation error and send seomething useful back to the client?

**Comment by VladShcherbin** [comment]
@koskimas yeah, a recommended way how to handle unique violation in `catch` to send a useful error object to the client (didn't want to open another issue for this question) ?

**Comment by koskimas** [comment]
That's a bit tricky at the moment.. There are no libraries that map the errors of various database clients (postgres, mysql, mysql2, sqlite, etc.) to a shared set of errors. Basically you need to handle whatever your database client throws. For postgres I have used utility functions like these:

```js
isPostgresError(error) {
  if (!error) {
    return false;
  }
  // Just check the existence of a bunch of attributes. There doesn't seem to be an easier way.
  return _.all(['severity', 'code', 'detail', 'internalQuery', 'routine'], (attr) => _.has(error, attr));
  });
}

function isUniqueConstraintViolation(error) {
  return isPostgresError(error) && error.code === '23505';
}
```

**Comment by VladShcherbin** [comment]
@koskimas looks hacky. Thank you a lot, will try this.

**Comment by zanzara** [comment]
I know it's very late to answer to this, but is there no other way to do it with a transaction if I want (intentionally) to add user-1 with the same relation to the permissions?!?!
How should `permissions:` look like?   (Cause I think, i need first the right permission id?!)
