### ISSUE TITLE
Should we think about models differently for aggregate queries?

### ISSUE THREAD

**Issue by devinivy** [Vincit/objection.js#374]
Model instances seem to represent a table "row" conceptually, at least in the sense that they are validated upon writes (they seem to not be validated when fetched from the database– is that correct?).  I find this to be a little confusing when performing reads that do not actually return a valid record.

A simple example of this is when performing an aggregate query, where the result does not represent a physical row in the database– consider summing a `rating` attribute that is supposed to be between `1` and `5`– of course the result may fail that requirement.  Another example is using a query builder method like `columnInfo()` that doesn't return data in the table at all.

Is there anything we can do to make this more conceptually consistent?  I love that objection helps me make my weird queries, and I don't want to mess with that.  I don't have any answers to the problem– just curious if there are any ideas out there.  My one idea would be a query-builder option that can make the results of a query _not_ wrapped in a model instance.

Here's an example of that adapted from the docs,
```js
Person
  .query()
  .select(Person.raw('coalesce(sum(??), 0) as ??', ['age', 'childAgeSum']))
  .groupBy('parentId')
  .asInstances(false)      // Do not wrap the results in `Person` instances
  .then(childAgeSums => {
    console.log(childAgeSums[0].childAgeSum);
  });
```

**Comment by koskimas** [comment]
There is the `knexQuery` method:

```js
Person
  .knexQuery()
  .select(Person.raw('coalesce(sum(??), 0) as ??', ['age', 'childAgeSum']))
  .groupBy('parentId')
  .then(childAgeSums => {
    console.log(childAgeSums[0].childAgeSum);
  });
```

**Comment by devinivy** [comment]
Ah, thanks!  That's actually great for my purposes– I had overlooked it.
