### ISSUE TITLE
Parsing knex.raw() result to a model

### ISSUE THREAD

**Issue by roytz** [Vincit/objection.js#378]
Hi,
Is there a way calling parsing `knex.raw()` result to a specific model (the query I run returns a specific model)?

More so, if I call a postgres function (I created) using `knex.raw()`, can I get the result "objectified" to a clear json and not having to go through all the object 'rows'?

Thanks

**Comment by koskimas** [comment]
Could you give an example of how you are trying to use it?

**Comment by roytz** [comment]
Sure, I call `knex.raw('select some_function()')` which call a postgres function I created that does some work but eventually returns rows of known (and "modelized") object.

**Comment by koskimas** [comment]
So you are asking if objection modifies the output of `knex.raw`? The answer is no. Objection in no way monkey patches `knex.raw`. If you have a question about the output of `knex.raw` you should probably ask this question in knex forums or github.

**Comment by newhouse** [comment]
Perhaps your best bet is to use [fromJson](http://vincit.github.io/objection.js/#fromjson) somewhere/somehow to create Model instances from the results of that function.

**Comment by roytz** [comment]
@koskimas it seems like you didn't understand my question.. In no place I requested for a monkey patch but a simple objet conversion from the knex.raw() results.

@newhouse thank you. I guess that's what I'll do.

**Comment by elhigu** [comment]
@roytz how about you call 

```js
Model.query().select(Model.raw('some_function()'))
```

to be able to make query through objection instead of directly calling knex? I have no idea what kind of result object you will get like that though...

**Comment by shai32** [comment]
@elhigu: I tried that, not working

**Comment by Kostanos** [comment]
Anyone found the solution? I'm looking for the same. Thank you.

**Comment by nicosierra** [comment]
What about setting an auxiliary static method that calls the original static raw and parses the result?
_(please note that this is meant for mysql exclusively, so I put it in a base model class for such purposes)_
```
  static rawModel(query, ...params) {
    return super.raw(query, ...params).then(data => {
      const results = data[0];
      return results.length > 1
        ? data[0].map(value => super.fromDatabaseJson(value))
        : super.fromDatabaseJson(data[0][0]);
    });
  }
```
Despite this, I don't see that the results are treated the same way as the rest of the model methods do (e.g. the knexSnakeCaseMappers is not used).

**Comment by nicosierra** [comment]
ok.. regarding my former post, the reason why the knexSnakeCaseMappers is not applied is because obviously this is part of the query builder from where all necessary info about columns is fetched beforehand (and is part of knex logic).
Fortunately, objection exposes such functionality so I find a way of returning a model from a raw query by using @Kostanos answer and a bit of inheritance, so you can have the method available in your code.

```
const { Model } = require('objection');
const { snakeCaseMappers } = require('objection');

const { parse, format } = snakeCaseMappers();

class BaseMySQLModel extends Model { // this implementation is for mysql
  static modelRawSelect(query, ...params) {
    return super.raw(query, ...params).then(data => {
      const results = data[0];
      return results.length > 1
        ? results.map(value => parse(super.fromDatabaseJson(value)))
        : parse(super.fromDatabaseJson(results[0]));
    });
  }
}

module.exports = BaseModel;
```

**Comment by ianbytchek** [comment]
@nicosierra Thanks for posting this out! Though, you probably want to parse the result `super.fromDatabaseJson(parse(value))`, not the model `parse(super.fromDatabaseJson(value))`.
