### ISSUE TITLE
Calling Functions with objection

### ISSUE THREAD

**Issue by shai32** [Vincit/objection.js#380]
does objection support calling to functions:
https://www.postgresql.org/docs/9.6/static/sql-syntax-calling-funcs.html

it will be nice if we had something like.
Model.call('functionName', args)
that call the function and return the result as js object.

**Comment by elhigu** [comment]
As you noticed this has been discussed in knex lately https://github.com/tgriesser/knex/issues/2021

Making up syntax for calling stored procedures/functions in platforms independent way, that supports e.g. casting parameters (or some other strange things people might like to do when calling) and using function calls as part of other queries / calls is not very trivial task.

For now I would suggest doing that by writing small helper function which provides nice interface for your use case to do a  call and it returns a `knex.raw`, you can do that for example in your own model base class, where you have reference to knex available.

**Comment by shai32** [comment]
@elhigu can you consider adding it in a roadmap?

its not trival but I think its feasible. 
I think using functions are good, performance wise, and this feature will encourage using functions.

**Comment by elhigu** [comment]
I think that feature should be implemented at knex level if there will be good syntax proposal which is significantly cleaner to use than `raw`. 

For example it is common to use functions as a part of select/where like this (dummy code, couldn't think of real query at the moment):

```js
.query()
  .select('id', raw('parsedate(??)::text', ['created_at']))
  .where('name', raw('lower(??)',  [nameToFindSubquery]));
```

AFAIK just calling some function and getting the results is pretty uncommon use case.

**Comment by roytz** [comment]
@elhigu I also think it should be implemented at knex level.
Why calling function and getting results is uncommon? If I want to do some complex actions on multiple tables it is much more efficient calling a function(/store procedure) with the relevant parameters that will do all the work and return the relevant result instead of passing the whole query from the server as string (and definitely better than calling the db multiple times).

**Comment by elhigu** [comment]
@roytz uncommon compared to the case where people call them as part of select / where to do conversions etc. I believe that you are using them all the time.

About the performance some times it is a lot more performant, some times it is marginally more performant. From my career I can remember only one case years ago where we had to write stored procedure to make query enough performant (IIRC it was some statistics generation thing).

Anyways the performance discussion is is not really relevant to this discussion how flexible function call syntax should be.

**Comment by koskimas** [comment]
This is definitely something that needs to be implemented on the knex side.
