### ISSUE TITLE
Docs should go into more detail for jsonSchema behavior and pickJsonSchemaProperties for validation

### ISSUE THREAD

**Issue by mitchellporter** [Vincit/objection.js#382]
A colleague and I realized through trial and error yesterday that when you implement `jsonSchema` in a `Model` subclass, that any properties in the json that are not listed in the `jsonSchema` property will be excluded from the insert or update.

The only place I found this mentioned in the docs was under the description for `pickJsonSchemaProperties`, but no mention of this property or the above functionality is found when reading about the `jsonSchema` property.

I feel like there should be a quick note about either `pickJsonSchemaProperties`, the behavior of `jsonSchema`, or both when reading the validation section in the docs: http://vincit.github.io/objection.js/#validation

**Comment by mitchellporter** [comment]
I would happy to take a first pass at this and submit a PR for this if you guys agree.

**Comment by koskimas** [comment]
The default value for pickJsonSchemaProperties will be changed to false in version 0.8.0. Thank you for the offer but after the change it doesn't need extra documentation. 0.8.0 is coming soon.
