### ISSUE TITLE
Complex queries

### ISSUE THREAD

**Issue by roytz** [Vincit/objection.js#383]
Hi,
From what I read in your api I saw we can use `where`/`andWhere`/`orWhere` and each receives search conditions.
What if I want to do something more complex such as:
```
SELECT * FROM some_table
WHERE x = 1
AND ((y = 2 AND z = 3) OR (y = 3 AND z = 5) OR (y = 5 AND z = 1))
```
Is there a way achieving it using the selectors above?
Thanks.

**Comment by fl0w** [comment]
Yes, if you pass a function it'll be grouped.
Your example would translate to
```js
Model
  .query()
  .where(x, 1)
  .where(function () {
    this.where({ y: 2, z: 3 })
  }).orWhere(function () {
    this.where({ y: 3, z: 5 })
  }).orWhere(function () {
    this.where({ y: 5, z: 1 })
  })
```

There's a better description at http://knexjs.org/#Builder-where

**Comment by roytz** [comment]
That's exactly what I look ed for @fl0w , thanks!
