### ISSUE TITLE
Flow typedefs?

### ISSUE THREAD

**Issue by dearsaturn** [Vincit/objection.js#385]
Are there plans to support flow-type in the future?

**Comment by elhigu** [comment]
Also typescript bindings were kindly contributed by the library users. So if someone is willing to create and maintain flow-typings I don't see any problems for supporting it.

**Comment by fl0w** [comment]
Is it even possible to externalise flow typings? I thought it had to reside in source (e.g. cannot opt out without removing flow)?

**Comment by elhigu** [comment]
@fl0w in that case it sounds impossible to support flow-type

**Comment by fl0w** [comment]
@elhigu yea, that's what I'm pondering about. I would say it's to intrusive and would re-introduce babel (+flow) as a hard dependency

**Comment by koskimas** [comment]
I know nothing about flow types, but isn't this what we want https://flow.org/en/docs/libdefs/creation/

**Comment by fl0w** [comment]
@koskimas I swear I was searching flow docs for 5 minutes for it. Sorry for the confusion all. I'll show myself to the coffee brewer.

**Comment by dearsaturn** [comment]
You can create `libdefs` the way the `flow-typed` project does and install them using their module.

**Comment by Prinzhorn** [comment]
Did anyone create type definitions (possibly in another project) that I'm just not able to find? It would be awesome if they could be contributed to [flow-typed](https://github.com/flow-typed/flow-typed/wiki/Contributing-Library-Definitions).
