### ISSUE TITLE
Exception getIdProperty ?

### ISSUE THREAD

**Issue by facundopoblete** [Vincit/objection.js#387]
I'm using objection & MSSQL.
My model (ClassA) is something like this:

```
import { Model } from 'objection';

export class ClassA extends Model {

	public constructor(init?: Partial<ClassA>) {
		super();
		Object.assign(this, init);
	}

	static get tableName() {
		return 'ClassA';
	}

	public Name? : string = undefined;
}
```

And for the objection query I defined my where clause in a var objectClassA.

```
let objectClassA: ClassA = new ClassA({
	Name: "name"
});

return await ClassA.query().where(objectClassA).first();
```

But this throws a exception: "TypeError: model.constructor.getIdProperty is not a function."

**Comment by koskimas** [comment]
This probably has something to do with the constructor and the ES5/6 the typescript compiler produces. What happens if you remove the constructor and use `fromJson` method instead? Also you don't need to pass a model instance to the `where` method. You can just use an object literal.

**Comment by koskimas** [comment]
@facundopoblete Did you solve this? If so, please close this issue.

**Comment by facundopoblete** [comment]
@koskimas Same problem.

```
import { Model } from 'objection';

export class ClassA extends Model {

	static get tableName() {
		return 'ClassA';
	}

	public Name? : string = undefined;
}
```

```
let objectClassA = ClassA.fromJson({
    Name: "name"
});

return await ClassA.query().where(objectClassA).first();
```

const idProp = model.constructor.getIdProperty();

**model debug info** => 
Builder {client: Client_MSSQL, and: Builder, _single: Object …}

**model.constructor debug info** => function Builder(client) { … }

**Comment by koskimas** [comment]
Weird.. I'll try to reproduce.

**Comment by koskimas** [comment]
It was an actual bug. Really weird that this hasn't come up earlier. Passing a model instance to the where method broke things mysteriously. I still don't know why you do that :D. Anyway fix is on the way. I'll release it with the next patch version 0.8.1.
