### ISSUE TITLE
es6 example

### ISSUE THREAD

**Issue by maxnachlinger** [Vincit/objection.js#39]
Thanks for this great ORM. I was wondering if you planned on creating an es6 example project. I'm trying to get this lib working with Node 4.x / es6, but simply inheriting from Model isn't working, e.g.:
```javascript
'use strict';
const Model = require('objection').Model;
class MyModel extends Model {
  get tableName() {
    return 'someTable';
  }
  // etc
}
```
In Model ``this.knex()`` returns null. Here's the specific method in Model that's angry:
```javascript
Model.knexQuery = function () {
  return this.knex().table(this.tableName);
};
```

**Comment by koskimas** [comment]
I added an ES6 example project if you are still interested.

**Comment by alimertcakar** [comment]
> I added an ES6 example project if you are still interested.

Where?
