### ISSUE TITLE
Eager and LeftJoinRelation

### ISSUE THREAD

**Issue by ssljivic** [Vincit/objection.js#390]
It seems that an error is thrown if `eager` and `leftJoinRelation` are used with the same path prefix:

```
Person
  .query()
  .eager('children')
  .leftJoinRelation('children.pets')
  ...
```

The above will throw error the _"table name "children" specified more than once"_.

**Comment by ssljivic** [comment]
Forgot to mention: eagerAlgorithm is **JoinEagerAlgorithm**

**Comment by koskimas** [comment]
`.leftJoinRelation('children.pets')` creates exactly the same join as `eager('children')` (plus the join for `pets`). You have two options here:

1. Call `.eager('children.pets')` and you don't need the`leftJoinRelation`
2. Use `WhereInEagerAlgorithm` for the eager part.

I would be possible to detect which joins have already been created and skip those when added the second time, but currently that would mean a largish refactor. By the way, you can chain `.debug` to queries to see the SQL that gets generated.

**Comment by ssljivic** [comment]
@koskimas thanks for answering.

The option #1 is not optimal. eager on children.pets would return all pets in a result set, which is not desirable. Therefore I need leftJoin on 'pets' so that where condition can be applied on pets without returning them in a result set.

**Comment by koskimas** [comment]
You get the result even when using just `leftJoinRelation`. The __only__ difference is that `eager` parses the result from the a flat list of records into a tree structure. Maybe as a workaround, you can  simply omit the pets afterwards:

```js
Person
  .query()
  .eager('children.pets')
  .omit('pets')
```

**Comment by koskimas** [comment]
This is one option:

```js
Person
  .query()
  .eager('children.pets')
  .omit('pets')
```

but not optimal for performance.

I'll try to figure out how to fix this, but I'm not positive it can be done with a reasonable amount of work. For objection to be able to detect if the same join has already been made, I would have to implement equality check for the query builder, and that's __a lot__ of work.

**Comment by newhouse** [comment]
@ssljivic Can you provide an example of the SQL you'd be trying to generate? I feel like there are a few important details missing from this description that really change the possible route you should take and the area where the solution can/should be found. Example:

Are you trying to get "People + their Children + their Children's Pets that are Dogs"? If so, have you tried (not tested at all):
```
Person
  .query()
  .eager('children.pets')
  .modifyEager('children.pets', builder => {
    return builder.where('species', 'dog');
  })
```

Or, are you trying to get only "People who have Children who have Pets that are Dogs"(or somewhere in between)? If so, this doesn't sound like a `leftJoin` to me so I'll hold off from an example.

**Comment by koskimas** [comment]
After looking into this I don't think it's worth the work to fix this right now. This is one of those things I'd like to be solved in knex (preventing or at least detecting duplicate operations).
