### ISSUE TITLE
Where did `objection.transaction.start()` documentation go?

### ISSUE THREAD

**Issue by newhouse** [Vincit/objection.js#391]
I've recently been re-visiting some code that I wrote that uses transactions and it looks (something) like this:

```
return objection.transaction.start(FooModel.knex()).then(txn => {
  return FooModel
    .query(txn)
    .patch({foo: 'bar'})
    .where({foo: 'foo'})
    .then(() => {
      txn.commit();
      return Promise.resolve('yay!');
    })
    .catch(err => {
      txn.rollback();
      return Promise.reject(err);
    });
})
.then(console.log)
.catch(console.log);
```

I'm pretty sure I got this example from the docs, and the code is still working, and I think even as intended (as far as transactions go)!  However, I cannot _currently_ find anything in the docs about `objection.transaction.start()` being used in this manner anymore. I only found [this bindTransaction](http://vincit.github.io/objection.js/#bindtransaction) example, which makes it look like I'm using this incorrectly.

Did the documentation accidentally disappear, or did supported usage for `objection.transaction.start` in this manner go away? I didn't see anything in the changelog that would suggest an intentional change.

Thanks!

**Comment by koskimas** [comment]
I'm trying to discourage people from using the "binding" version of the `transaction` and the `transaction.start` method and use the `transaction(knex, trx => {})` version instead. I couldn't think of a reason why `transaction.start` would be better than `transaction` in any situation. Please enlighten me if you can. Your example can be written like this:

```js
return objection.transaction(FooModel.knex(), txn => {
  return FooModel
    .query(txn)
    .patch({foo: 'bar'})
    .where({foo: 'foo'})
    .then(() => {
      return Promise.resolve('yay!');
    });
})
.then(console.log)
.catch(console.log);
```

The binding version and `transaction.start` are still tested and are not going anywhere. I just didn't see any point in advertising the usage of `transaction.start` anymore.

**Comment by koskimas** [comment]
Whoops, I just realized that the  `API` documentation only points to the now missing. I'll update the API docs.

**Comment by newhouse** [comment]
Thanks for the reply. I can't think of any reason at the moment that I can't do this one of the other ways, but I'll let you know if I find one.

Thanks!!!
