### ISSUE TITLE
Joining many-to-many data after an .eager() query

### ISSUE THREAD

**Issue by malimichael** [Vincit/objection.js#392]
I have 4 tables `users`, `playlists`, `genres` and `playlists_genres`. `playlists_genres` is a table that contains `playlist_id` and `genre_id`. I'm currently successfully querying a user by their id and returning all their associated playlists:

```
  User
    .query()
    .where('id', 1)
    .first()
    .eager('playlists')
    .then((user) => {
      console.log(user);
    })
```

However I'm wondering what would be the best way to then populate the returned playlists with their respective genres that sits in the `genres` table. I have tried chaining eager queries but to no luck.

**Comment by koskimas** [comment]
If your `relationMappings` are set up correctly you can simply do this:

```js
  User
    .query()
    .where('id', 1)
    .first()
    .eager('playlists.genres')
    .then((user) => {
      console.log(user);
    })
```

Since you probably already tried that, there must be something wrong with the `Playlist` model's `realationMappings.genres` definition. Can you post the `Playlist` model here?

**Comment by malimichael** [comment]
Thanks for the speedy reply.

Here is the `relationMappings` from my `Playlist` model

```
  static get relationMappings() {
    return {
      user: {
        relation: Model.BelongsToOneRelation,
        modelClass: User,
        join: {
          from: 'playlists.user_id',
          to: 'users.id'
        }
      },
      genres: {
        relation: Model.ManyToManyRelation,
        modelClass: Genre,
        join: {
          from: 'playlists.id',
          through: {
            from: 'playlists_genres.playlist_id',
            to: 'playlists_genres.genre_id'
          },
          to: 'genres.id'
        }
      }
    };
  }
```

**Comment by koskimas** [comment]
Looks good to me. The problem is somewhere else. Can you create a simple standalone app I can run that reproduces your problem?

**Comment by malimichael** [comment]
Sure, Ill put something together now

**Comment by malimichael** [comment]
I managed to fix it. The issue was that I was setting a many-to-many relationship within my `Genre` model too. As soon as i commented out this code within that model it worked as expected. Thanks for your help

 ```
 static get relationMappings() {
    return {
      playlist: {
        relation: Model.ManyToManyRelation,
        modelClass: Playlist,
        join: {
          from: 'genre.id',
          through: {
            from: 'playlists_genres.genre_id',
            to: 'playlists_genres.playlist_id'
          },
          to: 'playlist.id'
        }
      }
    };
  }
```

**Comment by koskimas** [comment]
You can define the relation from both directions and you need to if you want to create the query from the other direction. You probably have a circular dependency. Try to move the `require('Playlist')` inside the `relationMappings()` getter in `Genre`.
