### ISSUE TITLE
Static properties, static methods undefined after bindTransaction

### ISSUE THREAD

**Issue by jovinbm** [Vincit/objection.js#395]
When I try to bind a transaction to a class, my previous static properties and methods get lost. i.e.
```
console.log(BlogUserXref.getIdFromUUID);
console.log(BlogUserXref.bindTransaction(trx).getIdFromUUID);
```
Output
```
[Function]
undefined
```
Am I missing something? I hoped that `bindTransaction` returned the the original class bound to the passed transaction. Thanks in advance.

Node 8.0
Objection 0.8.1

**Comment by koskimas** [comment]
I wrote this test and it works perfectly. 

```js
const Model = require('objection').Model;
const fakeKnex = {};

class Person extends Model {
  static foo() {
    return 1;
  }
};

Person.bar = 2;
Person.baz = function () {
  return 3;
}

const BoundPerson = Person.bindTransaction(fakeKnex);

console.log(BoundPerson.foo());
console.log(BoundPerson.bar);
console.log(BoundPerson.baz());
```

Could you be more specific about what you are trying to do?

**Comment by jovinbm** [comment]
There might be something wrong with my code that's causing this issue. I'll keep investigating and perhaps try to extract some code that you can use to reproduce.

**Comment by jovinbm** [comment]
So here is what I've been to come up with so far: When I do
```
BlogUserXref.prop     = '123';
  BlogUserXref.propFunc = () => console.log('yes');
  //
  console.log(BlogUserXref.prop);
  console.log(BlogUserXref.propFunc);
  console.log(BlogUserXref.bindTransaction({}).prop);
  console.log(BlogUserXref.bindTransaction({}).propFunc);
  console.log(BlogUserXref.bindTransaction(trx).prop);
  console.log(BlogUserXref.bindTransaction(trx).propFunc);
```
The static properties and method remain intact when using the fakeTrx `{}` object. The `trx` object passed in the last two statements is a real `trx` object got from the `objection.transaction` api as in 
```
objection.transaction(Model1, Model2, async function (Model1, Model2, trx) {...
```
Hopefully this might be helpful.

**Comment by koskimas** [comment]
I have a test for that case and I repeatedly use custom methods in transactions like that. This probably has something to do with your setup. Could you write a standalone app that I can easily run that reproduces your problem?

**Comment by jovinbm** [comment]
After further debugging, I think I have found the issue. In my case I have a `Blog` model that uses the `BlogUserXref` as part of it's relationMappings like so:
```
...
memberXref: {
    relation  : BaseModel.HasManyRelation,
    modelClass: path.join(__dirname, '../blogUserXref/Model'), // points to where BlogUserXref is defined
    join      : {
      from: 'blog.id',
      to  : 'blog_user_xref.blog_id'
    }
  }
...
```
Here is `BlogUserXref` snippet
```
/**
 *
 * @class
 * @augments BaseModel
 */
class BlogUserXref extends BaseModel {
}

BlogUserXref.tableName  = 'blog_user_xref';
BlogUserXref.idColumn   = 'id';
...
```
It seems that somewhere in the pipeline, `BlogUserXref` appears to be already cached in `knex.$$objection.boundModels` (the trx being passed) and as seen below, the cached model is not what I was expecting. e.g. the idColumn is listed as `blog_id` instead of `id`. I understand that objection might be changing the model someway to enable things like `GraphInsert` but I think this is where my setup goes wrong.
![screen shot 2017-06-05 at 8 33 08 pm](https://cloud.githubusercontent.com/assets/8378840/26795651/1e192ea6-4a2f-11e7-87b6-ec830a3a0432.png)


My `BlogUserXref` model includes some custom validation methods that are called `$beforeInsert` and I rely on them when doing my own methods such as `GraphUpdate` implementations. 
When I pass the fakeTrx `{}` object, the model is not cached so that works. 

I guess, another question to answer is how and when are relation model classes cached in `knex.$$objection.boundModels`? If I call 
```
objection.transaction(Model1, Model2, async function (Model1, Model2, trx) {...
```
are the modelClasses in the relationMappings of Model1 and Model2 cached too and are they modified?

**Comment by koskimas** [comment]
Could you try this version if it fixes your problem:

```
// In package.json
"objection": git://github.com/Vincit/objection.js.git#76fcffcd
```

**Comment by jovinbm** [comment]
This works perfectly!

**Comment by koskimas** [comment]
Awesome. You were using `BlogUserXref` table as a join table in some `ManyToMany` relation right? That's what created an invalid model. The fix won't be out just yet. In the mean time you can specify the `BlogUserXref` model as a model class for the `ManyToManyRelations` like this:

```js
// In relationMappings
through: {
  from: 'blog_user_xref.user_id',
  to: 'blog_user_xref.blog_id',
  modelClass: BlogUserXref
}
```

**Comment by jovinbm** [comment]
Okay, that was fast! Thanks for the quick fix, really appreciated!

**Comment by devinivy** [comment]
@koskimas could this be done more cleanly with a `Map`? https://github.com/Vincit/objection.js/blob/c5a640c5bccea76ffbc296adfb62addfc48d6496/lib/model/Model.js#L650

**Comment by koskimas** [comment]
@devinivy Great idea! I forgot that `Map` can be used now that 4.0.0 is the minimum.
