### ISSUE TITLE
Eager the same model twice (as custom name)

### ISSUE THREAD

**Issue by allxie** [Vincit/objection.js#397]
I have a table called Page with a bunch of different page_types. Page has a many to many relationship with itself, and I have the ability to eager parents or children through a parent_id and a child_id in the page_relationship table.
BUT, I would love to eager two page_types divided up into different arrays based on their page_type. 

I'd love to get back...

```
Page:{
           page_id: 5,
           type_page: [...], // these are children of page 5
           type_subdomain: [...] // these are also children of page 5
}

```

 I've been messing around with the following code, but it only returns the second set of children. I'd love to be able to do `children(typeSubdomain) as type_subdomain` or be able to add something in the builder to automatically rename the eager'd array.

```
let domain = await Page
            .query()
            .findById(domain_id)
            .eager('[children(typeSubdomain), children(typePage)]', {
            typeSubdomain: (builder) => {
                builder
                    .whereJsonField("object_data:page_type", "=", "Subdomain")
                    .select(knex.raw("object_data->>'name' as name"), "page_id as subdomain_id");
            }, typePage: (builder) => {
                builder
                    .whereJsonField("object_data:page_type", "=", "Page")
                    .select(knex.raw("object_data->>'name' as name"), "page_id");
            }
```

I could obviously do this with javascript after the fact, but I'm curious if there a way that already exists to do this using eager or any of the builder operations?

I love this library! Thanks for all the hard work.

**Comment by allxie** [comment]
Side note-- it would be great to have `as` in eager for other reasons, besides being able to eager the same model twice. I have `parents` and `children` that would be great to rename based on what item I'm eagering them from.

**Comment by koskimas** [comment]
If I understood your problem correctly, you can setup two separate relations with filters:

```js
relationMappings = {
  children_foo: {
    relation: Model.ManyToManyRelation,
    modelClass: Page,
    filter: {type: 'foo'},
    join {
      ...
    }
  },

  children_bar: {
    relation: Model.ManyToManyRelation,
    modelClass: Page,
    filter: {type: 'bar'},
    join {
      ...
    }
  }
}
```

**Comment by allxie** [comment]
Oh! Perfect. Thank you!

**Comment by koskimas** [comment]
You're welcome! Let me know If that doesn't work for some reason.

**Comment by koskimas** [comment]
All good? Can I close this?
