### ISSUE TITLE
pickJsonSchemaProperties and $beforeInsert / $beforeUpdate hooks usage

### ISSUE THREAD

**Issue by VladShcherbin** [Vincit/objection.js#398]
Hey.

I've got a model with `$beforeInsert`, `$beforeUpdate` hooks where I set timestamps. I also want to use `pickJsonSchemaProperties = true` to clean all unwanted data.

```js
class Page extends Model {
  static tableName = 'pages'

  static pickJsonSchemaProperties = true

  static jsonSchema = {
    type: 'object',
    required: ['url', 'seoTitle', 'seoDescription', 'isVisible'],
    properties: {
      url: { type: 'string', minLength: 2, maxLength: 20 },
      seoTitle: { type: 'string', minLength: 3, maxLength: 55 },
      seoDescription: { type: 'string', minLength: 10, maxLength: 154 },
      isVisible: { type: 'boolean' }
    }
  }

  $beforeInsert() {
    const date = new Date().toISOString()

    this.createdAt = date
    this.updatedAt = date
  }

  $beforeUpdate() {
    this.updatedAt = new Date().toISOString()
  }
}
```

The problem is that *before hooks* run first and my timestamps are cut after. Is it the correct behaviour or is it supposed to filter data -> run before hooks -> insert into db?

**Comment by koskimas** [comment]
Json schema properties are picked in `$formatDatabaseJson` which is the last step before database. So what's happening is expected. One solution is to add the timestamps to jsonSchema.

**Comment by VladShcherbin** [comment]
@koskimas  Yeah, but this way I can pass this properties which I don't want to. Do I need to always clean the incoming data from them? This kinda kills the `pickJsonSchemaProperties` purpose.

**Comment by koskimas** [comment]
I not following... Do you mean that you don't want `createdAt` and `updatedAt` to come from the outside world? Leaving them out from `jsonSchema` doesn't guarantee that. So nothing changes if you add `createdAt` and `updatedAt` to `jsonSchma`. If you want to be absolutely sure that `createdAt` is never updated (`updatedAt` gets overwritten in every case) you can override `$parseJson` to remove `createdAt` before a model instance is created.

**Comment by VladShcherbin** [comment]
@koskimas My use-case is the form data coming from client. The incoming object can be for example `{ url: 'page', ..., createdAt: 'hello' }`.

I need to remove the fields that I don't want to receive so I wanted to set `pickJsonSchemaProperties = true`. This way, all incoming object properties that are not defined in `jsonSchema` are removed. Then I wanted hooks to add timestamps and save to database.

If I add timestamps to the schema, they won't be deleted and if received from outside - they will be replaced in before hooks.

Do you suggest to do this way or something better in this use-case?

**Comment by koskimas** [comment]
I don't know if you read the comment I deleted, but that was a brain fart on my part. I can see why you would think that the properties are filtered as the first thing when `pickJsonSchemaProperties` is true. That makes absolute sense since `jsonSchema` is the "outside world schema" and not the database schema. `pickJsonSchemaProperties` is kind of an anti feature. Before, there was no such property and non-jsonSchema properties were always stripped. Then I realised that that's not what people always want and I made it optional, and then later changed the default value to true. It actually should work as you expect, but that's a breaking change and I don't know if I want to change it yet again.

You can achieve this by implementing `$parseJson` hook which is executed as the very first thing when a model is created.

```js
class Person extends Model {
  $parseJson(json, opt) {
    delete json.createdAt;
    delete json.updatedAt;
    return super.$parseJson(json, opt);
  }
}
```

**Comment by VladShcherbin** [comment]
@koskimas yeah, I saw you turned `pickJsonSchemaProperties` false in 0.8.0.

Sorry, I'm a bit confused, I want to remove all fields that are not in jsonSchema properties.

- if I use `$parseJson` to delete fields, I need to list all fields I want to delete (but I don't know all of them)
- if I use `pickJsonSchemaProperties = true` and define this two fields (createdAt, updatedAt) in schema, their values will be replaced in beforeInsert/beforeUpdate hooks (but I have to control that they are replaced)

I'm a bit confused what to choose. Maybe beforeInsert/beforeUpdate can be executed after incoming fields are checked with jsonSchema so hooks will be not affected to fields removal?

**Comment by VladShcherbin** [comment]
And even if I define this fields in schema and use `pickJsonSchemaProperties = true` this will not work as `createdAt` is not replaced in `beforeUpdate` hook, only `updatedAt` is replaced. So, in this `beforeUpdate` hook I'll need to delete `createdAt` or something else =/

**Comment by koskimas** [comment]
```js
class Page extends Model {
  static tableName = 'pages'

  static pickJsonSchemaProperties = true

  static jsonSchema = {
    type: 'object',
    required: ['url', 'seoTitle', 'seoDescription', 'isVisible'],
    properties: {
      url: { type: 'string', minLength: 2, maxLength: 20 },
      seoTitle: { type: 'string', minLength: 3, maxLength: 55 },
      seoDescription: { type: 'string', minLength: 10, maxLength: 154 },
      isVisible: { type: 'boolean' }
    }
  }

  $beforeInsert() {
    const date = new Date().toISOString()

    this.createdAt = date
    this.updatedAt = date
  }

  $beforeUpdate() {
    this.updatedAt = new Date().toISOString()
  }

  $parseJson(json, opt) {
    delete json.createdAt;
    delete json.updatedAt;
    return super.$parseJson(json, opt);
  }
}
```

**Comment by VladShcherbin** [comment]
@koskimas thank you :)

**Comment by VladShcherbin** [comment]
@koskimas maybe the second variant can be included in the library with some model flag, smth like `persistOnlySchemaProperties = true`, what do you think?

**Comment by VladShcherbin** [comment]
@koskimas maybe the second variant can be included in the library with some model flag, smth like `persistOnlySchemaProperties = true` or maybe `pickJsonSchemaProperties = true` can work this way by default, what do you think?
