### ISSUE TITLE
$formatJson being applied to database JSON

### ISSUE THREAD

**Issue by gausie** [Vincit/objection.js#401]
I am trying to omit two fields from appearing when my model is formatted to JSON while still saving them to the database.

```
  $formatJson(rawJson) {
    const json = super.$formatJson(rawJson);
    return Ramda.omit(Booking.privateFields, json);
  }
```

When this line is included, however, the fields defined in Booking.privateFields do not get saved to Postgres. Isn't this the point of $formatJson vs $formatDatabaseJson?

**Comment by koskimas** [comment]
Yep, `$formatJson` shouldn't affect the database representation. Could you write a simple standalone app I can easily run that reproduces the problem. I have never encountered anything like this. This is probably very specific to your setup.

**Comment by gausie** [comment]
Ah this was on my end. await/async on Knex queries are confusing because it runs .then() immediately.
