### ISSUE TITLE
Aliases for eager expressions?

### ISSUE THREAD

**Issue by koskimas** [Vincit/objection.js#402]
What do you think about extending the eager expression language to support aliases:

```js
const people = await Person
  .query()
  .eager(`[
    children as kids,
    parent as p .[
      pets(filterDogs) as dogs,
      pets(filterCats) as cats
    ]
  ]`);

console.log(people[0].p.dogs);
```

Combined with the new Model property `namedFilters` this would provide a pretty powerful and highly configurable graphql-like language. Competing with graphql is in no way a goal here, but this would be pretty easy to implement without complicating the codebase and could be really useful.

This was originally suggested by @allxie.

What do you think?

**Comment by zuck** [comment]
Yes, definitely a great addition!

**Comment by devinivy** [comment]
Could someone provide the equivalent version of @koskimas's code above using objection v0.8?  I think it will be easier to understand the benefits with something to compare to.

**Comment by fl0w** [comment]
@koskimas would it be super complicated having graphql as a core feature of objection? I know Vincit has done (and probably used?) objection-graphql, but instead of working and maintaining a graph-like language - why not graphql specifically? Maybe it's technical maybe it's just out of the scope of objection.

However, with the introduction of namedFilters, this looks amazingly pleasing.

**Comment by koskimas** [comment]
@devinivy What do you mean? There is no way to do that currently. Well you could loop through the related models, fetch the filtered relations to all of them separately, etc. etc. That would be like 100 lines of code.

This is completely supported in 0.8
```js
const people = await Person
  .query()
  .eager(`[
    children,
    parent.[
      pets(filterDogs)
    ]
  ]`);

console.log(people[0].parent.pets);
```

**Comment by allxie** [comment]
@koskimas, I love it! 
As a heads up, I'm going to open a few separate issues/feature requests somewhat related to this, eg. selecting json fields in joinRelated queries.

**Comment by koskimas** [comment]
@fl0w I thought about it, but graphql is a very complicated beast and we could only support a small subset of its features if used as a eager language. Also graphql is just a language, we would still need to implement and maintain all the code that actually builds and runs the query. 

The eager expression language itself (even with aliases) is just a 100-line pegjs file.
