### ISSUE TITLE
Select jsonb fields when using .joinRelation

### ISSUE THREAD

**Issue by allxie** [Vincit/objection.js#404]
Hello again. 
I'm selecting some children and grandchildren of my model, and I'd love to be able to grab fields from jsonb. Currently I have...
```
let grandChildPages = await Page
            .query()
            .select("children:children.page_id", "children:children.object_data")
            .joinRelation('[children.[children]]')
            .where('children.is_deleted', false)
            .andWhere("page.page_id", "=", domain_id);
```
But I would love...

```
let grandChildPages = await Page
            .query()
            .select("children:children.page_id", "children:children.object_data->>'name'") 
            .joinRelation('[children.[children]]')
            .where('children.is_deleted', false)
            .andWhere("page.page_id", "=", domain_id);
```
Other syntaxes...
`.select("children:children.page_id", {"children:children": knex.raw("object_data->>'name'")})`
Or...
`.select("children:children.page_id", "children:children.object_data.name")`
Or...
```
let grandChildPages = await Page
            .query()
            .joinRelation('[children.[children(pruneSelect)]]', {
                        pruneSelect: (builder) => {
                               builder.select("page_id as grandchild_id", knex.raw("object_data->>'name' as name")) 
                        }
            })
            .where('children.is_deleted', false)
            .andWhere("page.page_id", "=", domain_id);
```
Might be separate, but I'd also love aliases on this syntax. 
```
.joinRelation('[children.[children]]')
.select("children:children.page_id as domain_id") 
```

Objection version 0.7.12

Thoughts? Thanks,
-Allxie

**Comment by koskimas** [comment]
Does this work?

```js
let grandChildPages = await Page
            .query()
            .select("children:children.page_id", knex.raw(`"children:children.object_data"->>'name'`)) 
            .joinRelation('[children.[children]]')
            .where('children.is_deleted', false)
            .andWhere("page.page_id", "=", domain_id);
```

**Comment by allxie** [comment]
Woo! Thanks, yes it does! I appreciate the help.

**Comment by koskimas** [comment]
Excellent! By the way @elhigu has been working on a nicer syntax for jsonb stuff. Try if this works:

```js
const ref = require('objection').ref;

let grandChildPages = await Page
            .query()
            .select("children:children.page_id", ref("children:children.object_data:name")) 
            .joinRelation('[children.[children]]')
            .where('children.is_deleted', false)
            .andWhere("page.page_id", "=", domain_id);
```

**Comment by elhigu** [comment]
Ref has also `.as` builder method to be used for example like this `.select(ref('columnRef').as('aliasName'))`

http://vincit.github.io/objection.js/#ref

Having colons in names might be a problem for the parser though. I have never used them with eagered relations.

**Comment by koskimas** [comment]
dangit, it doesn't work when there are colons. @elhigu Do you think this could be fixed?

**Comment by elhigu** [comment]
Maybe parser could be changed to support relation name or ref() builder could support some `.rel()` or something like that to allow for passing relation name.

I'm a bit confused how this all is works also when one is also trying to declare which schema query should use :D

**Comment by koskimas** [comment]
In case there colons in the table name, it's already an alias (unless someone actually puts colons in the table name) and the schema has been specified when the alias is created:
```
INNER JOIN schema.table as "some:crap:with:colons"
```
I don't think we need to support the case where the actual table name has colons.

I suppose it's impossible to solve this with a parser update since the json field expression language supports the case where there is no json reference at all. Therefore this
```
a:b.c
```
Could either mean that `a:b = table, c = column` or `a = column, b = json field, c = property`.

**Comment by koskimas** [comment]
How about this?
```js
ref('object_data:name').from('children:children').as('name')
```

**Comment by elhigu** [comment]
I like the builder approach. If some day there is need to have parser syntax, it can be figured out later on.
