### ISSUE TITLE
Updating extra in related query

### ISSUE THREAD

**Issue by kacpak** [Vincit/objection.js#413]
I've been struggling with updating extra field on many-to-many relation.
I have join table with user_id, session_id, character_id, is_game_master.  
```javascript
export default class User extends Model {
    static tableName = 'user';

    static relationMappings = {
        sessions: {
            relation: Model.ManyToManyRelation,
            modelClass: path.join(__dirname, 'session.model'),
            join: {
                from: 'user.id',
                through: {
                    from: 'character_session_user.user_id',
                    to: 'character_session_user.session_id',
                    extra: ['is_game_master', 'character_id']
                },
                to: 'session.id'
            }
        },
        character: {
            relation: Model.HasOneThroughRelation,
            modelClass: path.join(__dirname, 'character.model'),
            join: {
                from: 'user.id',
                through: {
                    from: 'character_session_user.user_id',
                    to: 'character_session_user.character_id',
                    extra: ['is_game_master', 'session_id']
                },
                to: 'character.id'
            }
        }
    };
}
```
I wanted to update character_id through related session.  
I hope I was clear enough with what I want to accomplish.  
What is the best way to accomplish that?

**Comment by fl0w** [comment]
```js
// insert should find both extra keys and update correctly.
User.insert({ is_game_master: 3, session_id: 'dsadasd' })
```

Also, take a look at the last example in [docs for insert](http://vincit.github.io/objection.js/#insert)

**Comment by kacpak** [comment]
Won't it create another user with extras? Or am I reading wrong?  
I want something like this:
```sql
UPDATE character_session_user SET character_id=% WHERE session_id=% AND user_id=%
```

**Comment by fl0w** [comment]
Right, you want to update, have you tried using `.patch()` and a `.where()`?

**Comment by kacpak** [comment]
I tried 
```javascript
await user.$relatedQuery('sessions').where('session.id', id).patch({
    character_id: character.id
});
```
But then I am getting `SQLITE_ERROR: no such column: character_id` or `SQLITE_ERROR: near ".": syntax error` when I try `'character_session_user.character_id': character.id`.   
Right now I am considering deleting relation and recreating it with character_id as extra, but it seems too hacky to me.

**Comment by newhouse** [comment]
@kacpak Can you chain a `debug()` to the query builder for any attempts? It will show the raw SQL that is being generated and can help with figuring out what your attempts are doing wrong. I played around with this just now and was not able to successfully get an update/patch to work, either. Maybe this is a bug or an enhancement can be made.

In my experience, however, given that you have meaningful data on the join table you may want to consider creating a simple model for `character_session_user`, e.g `class CharacterSessionUser` and add a relationship to it from the `User` class. Something like:
```
class User extends Model {
  ...
  static relationMappings = {
    ...
    characterSessions: {
      relation: Model.HasManyRelation,
      modelClass: path.join(__dirname, 'character_session_user.model'), // You have created this model class CharacterSessionUser
      join: ...
    }
  }
}
```

Which should allow you to write something like:
```
await user
  .$relatedQuery('characterSessions')
  .patch({ character_id: character.id })
  .where({ session_id: id });
```

**Comment by fl0w** [comment]
I played around with this as well. The reason is because the update/path is done against the end table (not against join table) - this is true for `Model.ManyToManyRelation` as well.

**Comment by newhouse** [comment]
@fl0w yeah, this is not surprising that it's not currently working they way we were hoping here...that would be really poweful/magical if it did!

**Comment by fl0w** [comment]
Well, I'm not sure how the logic flows through objection - but theoretically it should be possible to check, pseudo:
```
if field exists in extra:
  await relations.through.modelClass
    .query(trx)
    .where(constraints)
    .patch(extra)
```
Though the absence of this might be by design, it would require (for most DBs) an additional statement as PG does not allow UPDATEs for multiple tables.

**Comment by kacpak** [comment]
OK, so for the time being I created a new model for join table as you suggested.  
Thanks for the help :)  

Would you consider adding such a feature to update extras in the future?

**Comment by koskimas** [comment]
@kacpak Maybe... There probably was a reason I didn't implement this in the first place. I'll check to see if the only reason was laziness 😄

**Comment by newhouse** [comment]
oh man, sweet! Is this in the docs, too?!

**Comment by koskimas** [comment]
No docs yet. I'll write them before the next release.

**Comment by sammarks** [comment]
If docs aren't available yet (haven't checked), the usage is as described above according to the tests:

```js
await model.$relatedQuery('other').where('id', 123).patch({ extra: 'update' })
```
