### ISSUE TITLE
Linking models with a many-to-many relationship

### ISSUE THREAD

**Issue by jeff3yan** [Vincit/objection.js#416]
I've looked through the documentation and have read that using the `insertGraph` method can be used to create a model and it's relations with a single query.

However, I can't seem to find any information about linking 2 existing models which are related with a many-to-many relationship. For example if `Person` hasMany `Role`, and `Role` hasMany `Person`, how would I go about creating a new `Person` instance, then linking that to an existing role when the roleId is known prior?

Is the only method inserting directly into the join table?

**Comment by newhouse** [comment]
@jeff3yan Did you have a look at the [relate](http://vincit.github.io/objection.js/#relate) area of the documentation? Sounds like what you're looking for, I hope.

**Comment by jeff3yan** [comment]
@newhouse thanks for that, don't know how I missed it. Went through all the examples but not the full API reference list.

**Comment by newhouse** [comment]
You're welcome @jeff3yan
