### ISSUE TITLE
Dynamic Defaults - Setting values based on other properties

### ISSUE THREAD

**Issue by aconran** [Vincit/objection.js#418]
I would like to change the value of one field dependent on setting the value of another value.

My use-case is a User authentication system. When an email matches certain "safe-domains", I don't require that they activate the account. ie get an email/click the link. They can automatically login.

How can I set the value based on email?

Something along the lines of
```
    set email(email) {
        if (email) {
            const emailParts = email.split('@');
            if (emailParts.length > 1) {
                const domain = emailParts[emailParts.length - 1];
                if (safeDomains.indexOf(domain) !== -1) {
                    this.isActive = true;
                }
            }
        }
    }
```

Should I be overriding $beforeInsert and $beforeUpdate or is there a more appropriate place to do this?

**Comment by aconran** [comment]
Put this into $beforeInsert like this

```
    $beforeInsert(context) {
        super.$beforeInsert(context);
        const {email, password} = this;
        if (password) {
            this.password = bcrypt.hashSync(password, bcrypt.genSaltSync(10));
        }
        if (email) {
            const emailParts = email.split('@');
            if (emailParts.length > 1) {
                const domain = emailParts[emailParts.length - 1];
                if (safeDomains.indexOf(domain) !== -1) {
                    this.isActive = true;
                }
            }
        }
    }
```

Are there concerns about changing/re-writing the same field name?

**Comment by newhouse** [comment]
@aconran I personally think that's a good solution based on what you've stated above. I've used `$beforeInsert` and/or `$beforeUpdate` for some similar things, such as creating UUIDs, automatically set the `update_at` fields, etc.

**Comment by aconran** [comment]
@newhouse thank you for the response! Are there any concerns about changing/re-writing the same field?

For an example say I store password in the db column password. so am I safe to re-write this.password or do I have an issue where it could be rewritten twice/not hashed

**Comment by fl0w** [comment]
Re-hasing the same field will yield different values, which isn't great for passwords :)
I store my pass using bcrypt (like you have), but I also compare for signatures - 2y specifically.

As I've hashed and stored all passwords myself and do not allow anything other than hashes using fixed crypt_blowfish. So 1, 2, 2a, 2x, 5, 6 will all be disregarded as valid passwords and thus (somewhat wrongfully) re-hashed (5 and 6 are SHA256 and 512, 1 is MD5 I think).

This doesn't matter because in "worst case" the user gets locked out and has to request a new password.

**Comment by newhouse** [comment]
@aconran As @fl0w pointed out, for the original `email -> isActive` check you posted, there's little danger here, but with auto-hashing of the `password` field any time it's encountered in `$beforeInsert` and `$beforeUpdate`, you could run into problems. If you're only doing `User.query.insert`s and `User.query.patch || user.$query().patch`, but NOT [updates](http://vincit.github.io/objection.js/#update) (where you are updating the whole object) then Objection is not likely to screw you up, but you (or someone on your team) could screw you up just the same.

In my prior comment where I said that this approach was OK, I was going to add a caveat around the password stuff that you added in: Hiding the logic that hashes the password in the Model's `$before` hooks is slick and powerful, but also dangerous and unless you provider some VERY clear documentation and comments is likely to lead to some confusion to the next developer that comes in as to what's going on and how to handle password hashing. Personally, I make the hashing of the password field a separate, explicit action wherever I'm ingesting a new User password for these reasons. 

Here are some examples of safety and trouble:

```
// All good here b/c not doing anything with password
const existingRawPass = 'bunnies';

user.$query().patch({foo:'bar'}).then(() => {
  // All good because no 'password' was passed.
  assert(user.password === hashStuff(existingRawPass));
});

...

// User changing their password: safe implementation
const newRawPass = 'doggies';

user.$query.patch({password: newRawPass}).then(() => {
  assert(user.password === hashStuff(newRawPass)); // All good.
});

...

// User changing their password: incorrect implementation
const newRawPass = 'doggies';
// New dev on the team says: "Oh wow, a password? I'd better hash it before writing it to the DB!"
const newHashedPass = hashStuff(newRawPass);

user.$query.patch({password: newHashedPass}).then(() => {
  // Nope, user.password equals hashStuff(newHashedPass), a hash of a hash.
  assert(user.password === newHashedPass); 
});

```

I didn't do an `update` example, but basically that's completely out of the question unless the User has just supplied their raw password to you.

**Comment by aconran** [comment]
@fl0w and @newhouse thank you.

That was my understanding and think I have it implemented properly here. Have a handful of tests along with it verifying that it works properly.
