### ISSUE TITLE
Objection usage with dataloader

### ISSUE THREAD

**Issue by VladShcherbin** [Vincit/objection.js#419]
Hey, I'm trying to make [dataloader](https://github.com/facebook/dataloader) work with Objection.

The simple example is user - permissions (one to many).

```js
// tables
// users: id, name
// permissions: id, userId, title

// models
class User extends Model {
  static tableName = 'users'

  static relationMappings = {
    permissions: {
      relation: Model.HasManyRelation,
      modelClass: `${__dirname}/permission`,
      join: {
        from: 'users.id',
        to: 'permissions.userId'
      }
    }
  }
}

class Permission extends Model {
  static tableName = 'permissions'

  static relationMappings = {
    user: {
      relation: Model.BelongsToOneRelation,
      modelClass: `${__dirname}/user`,
      join: {
        from: 'permissions.userId',
        to: 'users.id'
      }
    }
  }
}
```

In graphql I have a `permissions` field which I can load as `user.$relatedQuery('permissions')`, but this would create N+1 queries. Instead, I want to use dataloader, so that the resolver is (here I have user model and I pass `user.id` to dataloader):

```js
const resolvers = {
  User: {
    permissions: (user) => {
      return permissionLoader.load(user.id)
    }
  },
  Query: {
    users: () => User.query()
  }
}
```

The dataloader expects an array of users (I can pass user models or user ids) and expects to return an array of users with permissions array (as in example above). 

```js
const permissionLoader = new DataLoader(users => {
  // users is [2, 3, 4]
  return Promise.resolve([
    [{ title: 'first user permission 1' }],
    [{ title: 'second user permission 1' }],
    [{ title: 'third user permission 1' }, { title: 'third user permission 2' }]
  ])
})
```

What's the best way to provide the same result using objection. Something similar to this, or using `Permission` model, or map results after receiving, or something else ?

```js
const userPermissions = await User.query().whereIn('id', [2, 3]).eager('permissions')
```

Since I already have all users, I need only 1 select to `permissions` table.

**Comment by VladShcherbin** [comment]
Or maybe if I pass `user` model instead of `user.id`, I can use `loadRelated` and map after:

```js
const resolvers = {
  User: {
    permissions: (user) => {
      return permissionLoader.load(user)
    }
  },
  ...rest
}

const permissionLoader = new DataLoader(users => {
  // users is an array of user models
  return User.loadRelated(users, 'permissions').then(users => {
    return users.map(user => user.permissions)
  })
})
```

This one works but I'm not sure if this is the best way.

**Comment by koskimas** [comment]
`loadRelated` is probably the best option here.

**Comment by VladShcherbin** [comment]
@koskimas thank you! :)

**Comment by rosendi** [comment]
How could I apply limit and offset (pagination) for each user permissions? Should I execute separate queries?

**Comment by vladshcherbin** [comment]
@rosendi I'd advise you to make a simple working example where you fetch users by ids and their paginated permissions.

If you'll have it working it'll be possible to use with dataloader since it just gives you user ids and you'll have to return correct permissions (using eager join or loadRelated and maybe modifiers).
