### ISSUE TITLE
Access QueryBuilder or query SQL from $afterGet

### ISSUE THREAD

**Issue by drew-r** [Vincit/objection.js#422]
Currently the query context is passed into the $afterGet hook, I am wondering if it is possible to pass the QueryBuilder or the SQL used in the query (could be added to context?).

My use case is a Model.refresh() method that will re-execute the original query that produced the model.

**Comment by koskimas** [comment]
I'm sorry, but no. Query context is a shared object between multiple queries. It's not query specific. For example when you execute an `.eager` query and give the query some context object, that object will be shared across all queries started by the original query. Same goes for all other queries that actually create multiple queries. Adding the current query to the context would be pretty hacky.

The context is internally always accessed through the public `context()` method. Maybe  you could create a custom query builder and override `context()`:

```js
class CustomQueryBuilder extends Model.QueryBuilder {
  context(...args) {
    const ret = super.context(...args);

    // Check if the call was a `set` or a `get`.
    if (ret !== this) {
      ret.query = this;
    }

    return ret;
  }
}
```

**Comment by koskimas** [comment]
Just to clarify: The solution I provided is the hack I referred to, but I don't think it's a good idea to add that to objection.
