### ISSUE TITLE
Return single item after updating/patching single item

### ISSUE THREAD

**Issue by VladShcherbin** [Vincit/objection.js#423]
```js
const user = await User.query().where('id', id).first()
const patchedUser = await user.$query().patch(input).returning('*')
```

In this example, `user` will return me a single user. Now I want to patch the user and return it. If I use the above, `patchedUser` will be an array of users so instead I have to use:

```js
const patchedUser = await user.$query().patch(input).first().returning('*')
```

It feels a little bit weird to call `first` after updating already fetched single item.

Is it somehow possible that objection will automatically return single item if `first` was used before patching/updating?

I'm also interested in usage of `limit` with `first()` method in this [issue](https://github.com/Vincit/objection.js/issues/307#issuecomment-310828172).

**Comment by koskimas** [comment]
Thanks, I'll fix the issue with `returning`.

**Comment by koskimas** [comment]
This is now implemented, but since this is a breaking change, we need to release this with 0.9.

**Comment by VladShcherbin** [comment]
@koskimas sure, I can wait 0.9 and then update code. Thank you!
