### ISSUE TITLE
Possibility to always return all fields after query execution

### ISSUE THREAD

**Issue by VladShcherbin** [Vincit/objection.js#425]
Is it possible to always return all fields after query execution (`'*'`) instead of using `.returning('*')` if database is postgres ?

Maybe a model property can be added and set to true (false by default) ?

It's useful when using GraphQL as it typically returns full types.

**Comment by koskimas** [comment]
It's not a good idea for objection, but you can easily implement this yourself. The easiest way to do it is this:

```js
class BaseModel extends Model {
  query(...args) {
    const query = super.query(...args);

    if (!query.isFindQuery()) {
      query.returning('*');
    }

    return query;
  }
}
```

`isFindQuery` is not documented yet, but will be in the next version.

**Comment by VladShcherbin** [comment]
@koskimas maybe there are edge cases when it can cause troubles?

**Comment by koskimas** [comment]
Not that I can think of. Performance should't be an issue. The insert/update itself will surely dominate the runtime.
