### ISSUE TITLE
$relatedQuery not triggering $afterUpdate hook on related Model

### ISSUE THREAD

**Issue by newhouse** [Vincit/objection.js#428]
Hello!

I'm seeing an issue whereby if I perform a `$relatedQuery` patch, the related Model's `$afterUpdate` hook (and probably others) is not getting triggered. Is this expected behavior? I don't see anything in the `$afterUpdate` hook documentation mentioning that this will not occur. I can figure out a workaround by making this query directly via the `Child` model class, but I was expecting it to be handled via the `parentInstance.$relatedQuery('children').patch()` route as well.

Psuedo-Example:

```
class Parent extends Model {
  ...
  static get relationMappings(): {
    return {
      children: {
        relation: Model.HasManyRelation,
        modelClass: __dirname + '/Child',
        join: {
          from: 'parents.id',
          to: 'children.parent_id'
        }
      }
    }
  }
}

class Child extends Model {
  ...
  $afterUpdate: (options, queryContext) => {
    // Do something important
    console.log('Hook triggered!');
  }
}

parentInstance
  .$relatedQuery('children')
  .patch({active: false})
  .then(() => {
    console.log('Did "Hook triggered!" get logged?');
    // No, it didn't.
  })
  .catch(console.log);        
```

Thanks for all your hard work on this great library!

**Comment by koskimas** [comment]
It should be triggered, and according to my test cases it is. I just wrote a bunch test just to make sure. Could you create a minimal reproduction to help me find out what is going on?

**Comment by newhouse** [comment]
I was afraid you'd say that! Only thing different here I can think of that may be significant is that the 'children' relationship has a modifier specifying only Child records with a certain property. I'll whip something up to try and reproduce.

**Comment by newhouse** [comment]
Oh man...after getting 90% of the way done writing an solid reproduction gist, it occurred to me that I was actually doing in my code was patching the Parent, and _**deleting** the Children_ (not patching the Children), so the hook I was after was the `$afterDelete` hook on the Children. The docs clearly state that "this method is only called for instance deletes started with `$query()` method". I think I just jumbled the two in my head and never took a fresh look.

This has almost certainly been a wild goose chase 🐦 , and I'll be back shortly I expect to close this issue out. I'm very sorry to have made you run more tests, etc. Stay tuned.

**Comment by koskimas** [comment]
I actually wrote test cases to the test suite so I should thank you 😀 There can never be too much tests.
