### ISSUE TITLE
modifyEager#builder.limit for eager limits entire N+1

### ISSUE THREAD

**Issue by fl0w** [Vincit/objection.js#429]
node 8.1.2
objection 0.8.3

While I was running a rather complex eager structure with more than a few relations and namedFilters I found that, when appending a `builder.limit` on a child relation, it does so for the entire N+1 query; i.e. not yielding a limit on rows per child.

This might or might not be expected/unsolvable by objection. I initially thought this was a bug in namedFilters, or eager expression parser - but alas, this is an N+1 and SQL thing. If not for anything, there's an issue to find if anyone else googles something similar.

**Question:** Without having to fetch all the data and then resolving this in app, is there a way to solve this using SQL? At first I tried something naively like `builder.limit( son.length * grandssons )`, but if first son has more grandsons than actual son-results, the limit is useless once again.

**Short and sweet and to the point:**
```js
await Father
  .query()
  .eager(`sons.grandsons`)
  .modifyEager('sons.grandsons', builder => builder.limit(1))
  // Here I assume limit 1 grandson per son,
  // but it's actually a limit on the entire N+1 query
```

The above query debug yields:
```sh
... abbreviated ...
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 2, 1 ],
  __knexQueryUid: '0e7ca6c5-c8ca-4517-82ad-3799eb3c794a',
  sql: 'select "Grandson".* from "Grandson" where "Grandson"."sonId" in (?, ?) limit ?' }
[ Father {
    id: 1,
    name: 'Brad',
    sons: 
     [ Son {
         id: 1,
         fatherId: 1,
         name: 'John',
         grandsons: [ Grandson { id: 1, sonId: 1, name: 'Dorian' } ] },
       Son { id: 2, fatherId: 1, name: 'Blow', grandsons: [] } ] } ]
```

But each son actually has more than one .. er, son (i.e. grandson).

**Full reproducible example:**
```js
'use strict'
// $ node -v
// v8.1.2
// $ npm view objection version
// 0.8.3


const { inspect } = require('util')
const objection = require('objection')
const knex = require('knex')({
  client: 'postgresql',
  connection: {
    database: 'obj_bug',
    user: process.env.USER
  },
  pool: {
    min: 2,
    max: 10
  }
})

objection.Model.knex(knex)

async function migrate () {
  return knex.schema
    .dropTableIfExists('Father')
    .dropTableIfExists('Son')
    .dropTableIfExists('Grandson')
    .createTable('Father', t => {
      t.increments('id')
      t.string('name')
    })
    .createTable('Son', t => {
      t.increments('id')
      t.integer('fatherId')
      t.string('name')
    })
    .createTable('Grandson', t => {
      t.increments('id')
      t.integer('sonId')
      t.string('name')
    })
}

async function fixtures () {
  await knex('Father').insert({ id: 1, name: 'Brad' })

  await knex('Son').insert([
    { id: 1, fatherId: 1, name: 'John'},
    { id: 2, fatherId: 1, name: 'Blow' }
  ])

  await knex('Grandson').insert([
    { id: 1, sonId: 1, name: 'Dorian' },
    { id: 2, sonId: 1, name: 'Eric' },
    { id: 3, sonId: 2, name: 'Tommy' },
    { id: 4, sonId: 2, name: 'Dany' },
    { id: 5, sonId: 2, name: 'Harry' }
  ])
}

class Father extends objection.Model {
  static get tableName () {
    return 'Father'
  }

  static get relationMappings () {
    return {
      sons: {
        relation: objection.Model.HasManyRelation,
        modelClass: Son,
        join: {
          from: 'Father.id',
          to: 'Son.fatherId'
        }
      }
    }
  }
}

class Son extends objection.Model {
  static get tableName () {
    return 'Son'
  }

  static get relationMappings () {
    return {
      grandsons: {
        relation: objection.Model.HasManyRelation,
        modelClass: Grandson,
        join: {
          from: 'Son.id',
          to: 'Grandson.sonId'
        }
      }
    }
  }
}

class Grandson extends objection.Model {
  static get tableName () {
    return 'Grandson'
  }
}

async function run () {
  await migrate()
  await fixtures()

  // the actual query
  const father = await Father
    .query()
    .eager(`sons.grandsons`)
    .modifyEager('sons.grandsons', builder => builder.limit(1)) // Here I assume limit 1 grandson per son
    .debug()
  
  console.log(inspect(father, false, null))
}

run().catch(err => console.error(err)).then(() => knex.destroy())
```

**Comment by fl0w** [comment]
So, once you've stopped laughing, this can (probably) be closed without an answer to my question.
I posted this in full because I initially thought there was a bug in eager expression parser - felt bad deleting it after dwelling at this issue for about 3 hours.

**Comment by koskimas** [comment]
Yeah, this is one of the limitations of eager fetching. I recently added the `NaiveEagerAlgorithm` that allows you to use `limit` but doesn't solve the N+1 selects problem. You could maybe achieve `limit(1)` using some kind of `groupBy` trick in `modifyEager`.

**Comment by koskimas** [comment]
By the way, I just added some shorthand methods with `0.8.4`. This should work for you:

```js
  const father = await Father
    .query()
    .naiveEager(`sons.grandsons`)
    .modifyEager('sons.grandsons', builder => builder.limit(1))
    .debug()
```
but if you have a large dataset to fetch, it can become slow because of N + 1 selects. With small datasets the performance difference is minimal.

**Comment by fl0w** [comment]
Yes, was pondering about `NaiveEager` briefly but that's unfortunately worse than just selecting everything :). I'm currently considering sub-querying and casting results to JSONB array. But this is mad science for me - so I have no clue if it's an acceptable solution :)

**Comment by fl0w** [comment]
The "pure" PG approach is to use a combination of `ROW_NUMBER()` and `OVER (PARTITION BY ...)`, but it's still a sub-query.

For reference: https://stackoverflow.com/questions/1124603/grouped-limit-in-postgresql-show-the-first-n-rows-for-each-group
