### ISSUE TITLE
Transaction rollback method

### ISSUE THREAD

**Issue by nbeydoon** [Vincit/objection.js#43]
Hi! first, thanks for this great orm is it possible to have a rollback transaction for unit test or something similar. Exemple I use mocha for my unit test, inside each describe in the before hook I want begin a transaction and rollback in after hook. I don t know how I can do it simply now.

**Comment by koskimas** [comment]
Hi! The transaction API is still a work in progress, and what you want is not currently easy to implement. You should test the following implementation though:

```js
var Person = require('./path/to/your/models/Person');
var Movie = require('./path/to/your/models/Movie');

describe('foo', function () {
  // The knex transaction object. It has `commit` and `rollback` methods
  // in addition to all the normal query building methods.
  var transaction;

  // These are the models that you should use in the tests since.
  // they are bound to the transaction. Queries started through
  // the original models do not take part in the transaction.
  var TransactingPerson;
  var TransactingMovie;
  
  before(function (done) {
    objection.transaction(Person, Movie, function (Person, Movie) {
      transaction = this;
      TransactingPerson = Person;
      TransactingMovie = Movie;
      done();

      // This is a hack that makes sure the transaction ends only after you
      // call transaction.rollback() or transaction.commit(). I will consider
      // updating objection.js so that this is not needed.
      return new Promise(function (res, rej) {});
    });
  });

  it('bar', function () {
    // Test something,
  });

  after(function () {
    return transaction.rollback();
  });
});
```

**Comment by nbeydoon** [comment]
Thanks for the fast reply, your solution is good but I don t use directly the models, I use it inside some services where models is directly included.

**Comment by koskimas** [comment]
Yeah transactions are a bit difficult with single threaded environments such as node.js. Because of the asynchronous way things are handled, you must specify the transaction for each database operation explicitly. If you declare some kind of global transaction, it will be used for all operations of all request that are running in parallel.

So you must somehow pass the transaction to your services. In objection.js you currently should pass the "bound" models to the services and use them instead of the directly required ones. Another way to do this is to pass the transaction object around. You could do something like this:

```js
var Person = require('./path/to/your/models/Person');
var Movie = require('./path/to/your/models/Movie');

function myAwesomeServiceFunc(transaction) {
  return Person.bindKnex(transaction).where('foo', 'bar').then(function (people) {
    // ... do more stuff.
  });
}

describe('foo', function () {
  // The knex transaction object. It has `commit` and `rollback` methods
  // in addition to all the normal query building methods.
  var transaction;
  
  before(function (done) {
    objection.transaction(Person, Movie, function (Person, Movie) {
      transaction = this;
      done();

      // This is a hack that makes sure the transaction ends only after you
      // call transaction.rollback() or transaction.commit(). I will consider
      // updating objection.js so that this is not needed.
      return new Promise(function (res, rej) {});
    });
  });

  it('bar', function () {
    return myAwesomeServiceFunc(transaction);
  });

  after(function () {
    return transaction.rollback();
  });
});
```

**Comment by nbeydoon** [comment]
Oh if I just need to bind the transaction is a lot easier, thanks a lot !

**Comment by nbeydoon** [comment]
I do it like this
````
class MyAwesomeClass {
  constructor() {
    this.MyModel = require('./path/to/my/MyModel');
  }
  /*For the test*/
  bindTransaction(transaction) {
    this.MyModel.bind(transaction);
  }
  someFunction() {
    return this.MyModel.query().first()
  }
}

describe('foo', function () {
  // The knex transaction object. It has `commit` and `rollback` methods
  // in addition to all the normal query building methods.
  var transaction;
  var MyAwesomeService = new MyAwesomeClass();

  before(function (done) {
    objection.transaction(Person, Movie, function (Person, Movie) {
      transaction = this;
      done();

      // This is a hack that makes sure the transaction ends only after you
      // call transaction.rollback() or transaction.commit(). I will consider
      // updating objection.js so that this is not needed.
      return new Promise(function (res, rej) {});
    });
    MyAwesomeService.bindTransaction(transaction);
  });

  it('bar', function () {
    return MyAwesomeService.someFunction();
  });

  after(function () {
    return transaction.rollback();
  });
});
````

**Comment by nbeydoon** [comment]
It is possible to use Models.bindKnex to do the same thing without declaring each model in objection.transaction?

**Comment by koskimas** [comment]
Sure. But currently you still need to give at least one model from which the transaction function can get the knex connection. Something like this:

```js
var SomeModel = require('./models/SomeModel');
var SomeOtherModel = require('./models/SomeOtherModel');

objection.transaction(SomeModel, function () {
  return Promise.all([
    SomeModel.bindKnex(this).insert({foo: 'bar'}),
    SomeOtherModel.bindKnex(this).insert({spam: 'eggs'})
  ]);
});
```

All `transaction` function does is it calls the `bindKnex` method for all models that are passed in and passes them to the callback. You don't need to use them.

**Comment by nbeydoon** [comment]
Bluebird don't like the hack I get Unhandled rejection Error: undefined at Object.ensureErrorObject

**Comment by koskimas** [comment]
If you copy my example _exactly_ you don't get the unhandled exception. Note that I don't return the promise from the before method. I will figure out a better way to do this for sure. Something like this:

```js
var transaction;
before(function () {
  return objection.transaction.start(SomeModelOrTheKnexConnection).then(function (trx) {
    transaction = trx;
  });
});

after(function () {
  return transaction.rollback();
});
```

I reopened the issue and will close this when I add a fix in the near future. Please post any suggestions you might have here.

**Comment by nbeydoon** [comment]
I don t see .start method in the transaction.js file and i get undefined

**Comment by nbeydoon** [comment]
And I think if the objection.transaction is call without any models you can use this.Model.knex() inside transaction to get the global knex instance?

**Comment by koskimas** [comment]
Yes, `start` method doesn't exist yet. My comment was a bit confusing.. I meant that I will add the `start` method or something similar in the near future.

The `transaction` call needs a model or a knex instance so that it can create the transaction.

**Comment by nbeydoon** [comment]
Ok sry my english is really limited, I'm looking for implement something like
`````
var transaction = objection.transaction.start(knexInstance);

if (ok)
    transaction.end();
else
    transaction.rollback();

`````

**Comment by nbeydoon** [comment]
see https://github.com/Vincit/objection.js/pull/44
