### ISSUE TITLE
objection doesn't use mysql.js's typeCast option

### ISSUE THREAD

**Issue by jansenignacio** [Vincit/objection.js#430]
I basically have something like this

```javascript
const knex = require('knex')({
    client: 'mysql2',
    connection: {
        host     : config.MYSQL_SERVICE_HOST,
        port     : config.MYSQL_SERVICE_PORT,
        user     : config.MYSQL_USERNAME,
        password : config.MYSQL_PASSWORD,
        database : config.MYSQL_DATABASE,
        typeCast: (field, next) => {
            console.log(field);
            return next();
        }
    },
});
```

I pass this knex instance to Objection

```javascript
Model.knex(knex)
```

but Objection doesn't use it. I've tried using the knex instance outside objection and it logs the fields when I query something.

**Comment by jansenignacio** [comment]
P.S. I'm using mysql2 but it honors the same options as mysql

**Comment by koskimas** [comment]
Objection doesn't alter knex in any way. It simply uses it's public interface. If you really think this is objection's fault, please provide a minimal standalone app that reproduces the issue.

**Comment by elhigu** [comment]
@jansenignacio knex filters out some mysql config parameters. It has been removed in master, but current 0.13 still filters some out. https://github.com/tgriesser/knex/commit/804c338dd00cb644a1dc3fdcb2d5fff5aadb6760 however looks like `typeCast`indeed is included in the list that is picked from confs but it was included here https://github.com/tgriesser/knex/commit/c4fcfa8f7632d3de570bf28b7427cb3d66cb07a0 

Which knex version are you using?

**Comment by jansenignacio** [comment]
I'm using knex 0.13. It correctly uses typeCast. I'll work on a minimal standalone app and try to reproduce the issue.

**Comment by jansenignacio** [comment]
My bad. I forgot that I wired my Objection models to check redis first for a cached version of their database counterparts. Since the objects I was trying to query were cached, knex wasn't even called. Sorry for wasting your time but thanks for the quick responses. :)
