### ISSUE TITLE
conversion to utc for DATETIME

### ISSUE THREAD

**Issue by capaj** [Vincit/objection.js#434]
I am migrating and app from sequelize to objection and one thing I've hit is that sequelize normalizes any date into a UTC before storing in the DB: https://stackoverflow.com/a/28410849/671457

knex/objection just stores the time local to the machine it is running on. Is there a way to normalize all dates to UTC as with sequelize @koskimas ?

**Comment by koskimas** [comment]
Neither objection nor knex touch the dates. They are saved as given and returned in the format the DB returns them. One way to change the DB timezone is to add a `afterCreate` hook to the knex config:

```js
const knexConfig = {
  client: 'postgres',
  connection: {
    ...
  },
  pool: {
    min: 2,
    max: 50,
    afterCreate(conn, cb) {
      conn.query('SET timezone="UTC";', function (err) {
        cb(err, conn);
      });
    }
  },
}
```

**Comment by capaj** [comment]
Thanks @koskimas I solved it even easier by doing:
```javascript
const db = knex({
  client: 'mysql',
  connection: {
    host: sqlConfig.hostname,
    user: sqlConfig.username,
    password,
    database,
    timezone: 'UTC'  // this needed to be added
  }
})
```
as suggested here https://stackoverflow.com/a/25729295/671457

**Comment by koskimas** [comment]
Oh, didn't know about that 😄

**Comment by elhigu** [comment]
@capaj  yup mysql driver supports that attribute in connection object. If you are using postgres you would need the trick mentioned by @koskimas

**Comment by GeeeCoin** [comment]
@elhigu @koskimas do you know why this is not working for my postgres setup? When I query a timestamp with my objection model, it still comes in as GMT followed by my time zone offset. I am using `afterCreate` to specify "UTC" thanks!

**Comment by kojilab** [comment]
I'm having that kind of issue. My Mysql system timezone is +00:00 and yet dates are being converted to UTC with a 7 hour difference. I'm PST daylight saving.

**Comment by kurdin** [comment]
Sorry to reopen but this might help to somebody with the same issue.
 
I hit this problem with Postgres I had all global Postgres db config setting using 'UTC'. 
To get the same UTC dates in objection model as its in db data, you simple want to make sure your local or production NODE environment setting TZ  has UTC in timezone:

`process.env.TZ = "UTC"`
