### ISSUE TITLE
Bug in InsertGraph

### ISSUE THREAD

**Issue by Gustav0ar** [Vincit/objection.js#442]
I found a bug when inserting item to database where the children has errors like invalid id. In this cause it is inserting the parent, where it should rollback in case it can't insert its children. Look at issue  #441 where I used the same example, but passed invalid ids (that doesn't exist) to the related table.

**Comment by koskimas** [comment]
There are no implicit transactions in objection. You need to start a transaction and perform the insertGraph operation insde it.

**Comment by Gustav0ar** [comment]
Ah ok, I thought that it treated a single operation like a transaction
