### ISSUE TITLE
Using objection to update row with ID if it exists, otherwise insert a new row

### ISSUE THREAD

**Issue by pineapplemachine** [Vincit/objection.js#446]
I'm used to writing `REPLACE INTO` queries in MySQL, but what's the best way to achieve a similar query with objection and postgres? Is there any builtin tool for update-else-insert queries?

Thanks!

**Comment by fl0w** [comment]
Refer to https://github.com/Vincit/objection.js/issues/447
I think this can be closed.

**Comment by koskimas** [comment]
Yeah, upsert should be implemented in knex.
