### ISSUE TITLE
Add documentation how .retruning() works with to API documentation. 

### ISSUE THREAD

**Issue by elhigu** [Vincit/objection.js#45]
QueryBuilder `returning()` method works slightly different to `knex`, so some objection specific description could be added to API docs.

**Comment by koskimas** [comment]
What is the difference?

**Comment by elhigu** [comment]
Difference I was thinking here was that if in knex one writes ´.returning('id')´ return value is an array of ids, not an array of ´{id: 12}´ objects. Objection returns an array of objects where id is patched to original data given to insert. 

Actually the documentation I was looking for is in API docs but I was looking it from wrong place. Objection API docs tells check what `.returning` does from `knex`documentation which refers to `knex`s `.update` / `.insert` documentation.

Probably would be enough to just add links to objection's  `.returning` jsdoc to correct `.insert` / `.update` where functionality is explained.

**Comment by koskimas** [comment]
All the knex query builder methods are just documented with a link to knex.org, not even to a specific anchor. We could add a link with a correct anchor to each of them.

**Comment by koskimas** [comment]
This has actually been fixed long ago.
