### ISSUE TITLE
insertGraph - should it be auto-populating the parent id?

### ISSUE THREAD

**Issue by theogravity** [Vincit/objection.js#450]
I have a model that's defined like this

[User] - hasOne -> [Profile]
[Profile] - belongsTo -> [User]

There is a `Profile.user_id` field that needs to be populated.

When I try

```
User.query.insertGraph({
  name: 'The user',
  profile: {
     email: 'test@emailaddr.com'
  }
})
```

It errors out saying `Profile.user_id` is not defined. The docs for `insertGraph` made it seem that it would auto associate the `User.id` -> `Profile.user_id` due to the relational mapping.

Does it not? Do I need to use the `#id` and `#ref` instead?

If so, how do I dynamically inject it in the models? I'm building a GraphQL API where you can create a new X, and the user shouldn't need to know to insert `#id` / `#ref`.

The incoming mutation input would be directly fed to the `insertGraph` method. Tried using some of the lifecycle methods, but whatever I have tried does not work.

eg.

```

// in the User model
$setJson (json) {
   json['#id'] = 'user'
   return this
}

// in the Profile model
$setJson (json) {
   json.user_id = `#ref{user.id}`
   return this
}

```

**Comment by theogravity** [comment]
Figured out the dynamic way

```
  $parseJson (json, opt) {
    json['#id'] = 'user'
    json = super.$parseJson(json, opt)
    return json
  }

  $parseJson (json, opt) {
    json.user_id = '#ref{user.id}'
    json = super.$parseJson(json, opt)
    return json
  }
```

Still unsure if I actually need to go this route.

**Comment by koskimas** [comment]
It should set the id automatically. There should be tons of tests for this in the test suite, but I'll try to reproduce this when I get to my computer.

**Comment by koskimas** [comment]
I cannot reproduce this. The problem is somehow related to your setup. Could you try to write a minimal standalone reproduction that I can debug?

**Comment by theogravity** [comment]
Thanks for looking into it - I've created a repro sample here:

https://github.com/theogravity/objectionjs-issue-450

After installing via npm / yarn,

- `npm migrate`  for db creation
- `npm start` to exec the sample

```
600025:es6-babel-boilerplate t.gravity$ yarn migrate
yarn migrate v0.27.5
$ node --require babel-register ./node_modules/.bin/knex migrate:latest
Using environment: development
[ { sql: 'select * from sqlite_master where type = \'table\' and name = ?',
    output: [Function: output],
    bindings: [ 'knex_migrations' ] } ]
[ { sql: 'select * from sqlite_master where type = \'table\' and name = ?',
    output: [Function: output],
    bindings: [ 'knex_migrations_lock' ] } ]
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'cf84ebac-753e-4d46-bf00-3f0a70cf46e2',
  sql: 'select * from "knex_migrations_lock"' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'a2b3855c-0a2c-4454-b050-593d2390a6f2',
  sql: 'select "name" from "knex_migrations" order by "id" asc' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'b527120e-1bb9-4cd9-9ef8-61878f719906',
  sql: 'select * from "knex_migrations_lock"' }
{ method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: 'b033322a-78d7-4f1a-a902-c86643f29154',
  sql: 'update "knex_migrations_lock" set "is_locked" = ?' }
[ { sql: 'select * from sqlite_master where type = \'table\' and name = ?',
    output: [Function: output],
    bindings: [ 'knex_migrations' ] } ]
[ { sql: 'select * from sqlite_master where type = \'table\' and name = ?',
    output: [Function: output],
    bindings: [ 'knex_migrations_lock' ] } ]
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'c0da2a52-7426-4603-9a46-e0dcad5c0b8a',
  sql: 'select * from "knex_migrations_lock"' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '2aa7e9bb-5dff-4724-a249-5f39f0dccbd4',
  sql: 'select "name" from "knex_migrations" order by "id" asc' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: '6375aebb-60a2-4128-9746-6a04358b87af',
  sql: 'select max("batch") as "max_batch" from "knex_migrations"' }
{ method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 0 ],
  __knexQueryUid: '13c5732f-ec80-46f4-8441-4179d34c9621',
  sql: 'update "knex_migrations_lock" set "is_locked" = ?' }
Already up to date
Done in 1.29s.
600025:es6-babel-boilerplate t.gravity$ yarn start
yarn start v0.27.5
$ node --require babel-register ./src/index.js
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '0.459842707624734', 'Test User', null ],
  __knexQueryUid: '8ce99c67-8543-4bf6-bf64-c99dbbad5325',
  sql: 'insert into "user" ("id", "name", "web_url") values (?, ?, ?)' }
(node:54493) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: {
  "userId": [
    {
      "message": "should have required property 'userId'",
      "keyword": "required",
      "params": {
        "missingProperty": "userId"
      }
    }
  ]
}
```

**Comment by koskimas** [comment]
Awesome! Thank you for the repro. I'll take a look at this as soon as I can.

**Comment by theogravity** [comment]
Thanks - i've updated the repo with some comments and cleaned it up a bit just now - it's yours to take

**Comment by koskimas** [comment]
Your `$format*` and `$parse*` methods are quite complex. Objection uses this code to figure out the conversion between database and "external" column names:

```js
function columnNameToPropertyName(ModelClass, columnName) {
  const model = new ModelClass();
  const addedProps = Object.keys(model.$parseDatabaseJson({}));

  const row = {};
  row[columnName] = null;

  const props = Object.keys(model.$parseDatabaseJson(row));
  const propertyName = difference(props, addedProps)[0];

  return propertyName || null;
}

function propertyNameToColumnName(ModelClass, propertyName) {
  const model = new ModelClass();
  const addedCols = Object.keys(model.$formatDatabaseJson({}));

  const obj = {};
  obj[propertyName] = null;

  const cols = Object.keys(model.$formatDatabaseJson(obj));
  const columnName = difference(cols, addedCols)[0];

  return columnName || null;
}
``` 

What happens is the column name is not converted from `user_id` to `userId` at any point in the repro and that's why the validation is failing.

Is there are reason you have snake_case column names and camelCase properties in the code? Have you considered using the same casing everywhere? You would save your self from a lot of these kind of problems.

Maybe you could create a base class that implements all `$parse*` and `$format*` hooks so that they map all properties to correct casing. Then you could only deal with camelCased properties in the rest of the code. Something like [this](http://vincit.github.io/objection.js/#map-column-names-to-different-property-names)

**Comment by theogravity** [comment]
ah - I had some odd feeling that might have been the case - we're just starting to build this out so we can switch to a case format that's consistent with the objection model. I'll try with that - thanks

**Comment by theogravity** [comment]
To add on the snake vs camel case, it's a minor thing with postgres - postgres will lowercase camel case fields without adding quotes around each field name. 

https://www.drupal.org/node/1622982 (we're not using drupal here, but the issue describes it well)

I wanted to have an external API def that uses camel casing, while the internals are lower cased.

**Comment by theogravity** [comment]
Your suggestion worked - thanks!
