### ISSUE TITLE
String conversion to JSON not working as it should.

### ISSUE THREAD

**Issue by ppinel** [Vincit/objection.js#452]
Hello,

I have troubles using json as string with mariadb and Objection.js.
I tagged my column as json in knex migration file. This should just fallback on text and it does.

My issue is when I use Objection.js to get data from database. As I saw in code, it should try to convert any string to JSON. It doesn't for in my case.
In a column I have a stringify json object and I am expecting Objection to parse it in $parseDatabaseJson when a query is made.

Is it correct?

PS: I tried Bookshelf and Objection, I end up with Objection because I found it better to work with.
Thanks for your hardwork.

**Comment by koskimas** [comment]
You need to mark the property as `object` or list it in the `jsonAttributes` list for it to get automatically stringified andbparsed. Did you do either of those?

**Comment by ppinel** [comment]
Nope I didn't.
Thanks for your help!

**Comment by charlescapps** [comment]
I am finding that even if I declare a JSON type column in `jsonAttributes`, it still will not convert a string, e.g. `"foo"` into a JSON string, `"\"foo\""`, so I get an error at insert time from PostgreSQL - `invalid input syntax for type json`.

This seems like a bug to me, Objection should uniformly call `JSON.stringify` on any value, not have a special case for strings.

**Comment by charlescapps** [comment]
For now I can probably work around this by hacking a `$beforeUpdate` and `$beforeInsert`...
