### ISSUE TITLE
Generic Transaction

### ISSUE THREAD

**Issue by danieloprado** [Vincit/objection.js#455]
With the new update, the Transaction became a generic type, but its broken all my code, see the example below:

![image](https://user-images.githubusercontent.com/7683575/28668270-6c8911de-72a5-11e7-9174-0241197a7652.png)

I can't use the same transaction for two different queries and it create a idea that is not possible.

**Comment by elhigu** [comment]
What is the error typescript is giving? It might be caused also because you are shadowing variable name `transaction`. Try to change inner `transaction` argument name to `trx` and pass that to queries?

**Comment by danieloprado** [comment]
Rename didn't work, The error message:
```
Argument of type 'Transaction<User>' is not assignable to parameter of type 'Transaction<ChurchUser>'.
  Type 'User' is not assignable to type 'ChurchUser'.
    Property 'userId' is missing in type 'User'.
```

The **ChurchUser.query()** expect a Transaction<ChurchUser> not a Transaction<User>, but Transaction works in both cases

**Comment by elhigu** [comment]
Yeah, looks like typing is too strict. These are good test cases for typings 👍

**Comment by danieloprado** [comment]
Yep! I think Transaction don't need to be a Generic Type, like before...
