### ISSUE TITLE
Eagers pick doesn't work when doing patchAndFetchById but omit works

### ISSUE THREAD

**Issue by tahv0** [Vincit/objection.js#459]
Eg. if I have models like this:
```
class Person extends Model{
...
  static get relationMappings() {
    return {
      account: {
        relation: Model.HasOneRelation,
        modelClass: __dirname + '/Account',
        join: {
          from: 'Person.id',
          to: 'Account.personId'
        }
      }
}
```
```
class Account extends Model{
...
  static get relationMappings() {
    return {
      person: {
        relation: Model.BelongsToOneRelation,
        modelClass: __dirname + '/Person',
        join: {
          from: 'Account.personId',
          to: 'Person.id'
        }
      }
}
```

And I'm doing query like this:
```
Account
    .query()
    .patchAndFetchById(
       accountId,
       patchValues
  )
  .eager('person.account')
  .pick(Account, ['somekey'])
   ....
```
It returns Account object that doesn't have Person in it as eager.
But if I use **omit** instead of **pick** it returns Person object normally as part of it and Account fields are parsed like it should be after omitting some key-value-pairs.

**Comment by koskimas** [comment]
Thanks for bringing this up! There's not that many (if any) tests for patchAndFetchById + other query methods. I'll look into this as soon as I can. Currently I'm on vacation and comfortably drunk in Berlin, but maybe during the next week or so.

**Comment by newhouse** [comment]
Enjoy your vacation, @koskimas ! 🍻 🕺

**Comment by koskimas** [comment]
@tahv0 `person` I started debugging this and realised that `person` shouldn't be present if you don't pick it. I'm assuming you didn't list `person` in `pick`? `pick` simply picks properties (just like `_.pick`) and doesn't care whether a property is a column or a relation.

**Comment by tahv0** [comment]
@koskimas  I replied to your question in Slack

**Comment by koskimas** [comment]
This was resolved in a slack conversation.
