### ISSUE TITLE
Automatic createdAt & updatedAt

### ISSUE THREAD

**Issue by nbeydoon** [Vincit/objection.js#46]
For each table I have createdAt and updatedAt and it s redondant to set it in each beforeCreate/Update It is possible to add a static option to add it automatically ex: 
``````
class Foo extends Model {

    static $createdAt = 'tableName'
    static $UpdatedAt = 'tableName'

}
```````

**Comment by koskimas** [comment]
Basic OOP saves you here. Just create a base class:

```js
class ModelBase  extends Model {
  $beforeUpdate() {
    this.updatedAt = new Date().toISOString();
  }

  $beforeInsert() {
    this.createdAt = new Date().toISOString();
  }
}
```

and then inherit all your models from `ModelBase` instead of `Model`. This way the code is only in once place.

**Comment by nbeydoon** [comment]
but I need to call super in this case

**Comment by koskimas** [comment]
So you have `$beforeUpdate` and `$beforeInsert` implemented for all your models to do different things in addition to the timestamps? If they do common stuff, just move them to the parent class. If they do different things then yes, you need to call super.

I always add those timestamps in the database using triggers. Have you considered that?

**Comment by nbeydoon** [comment]
Yeah I know for super, but I have to set a random pid in beforeInsert for exemple but I go look for triggers

**Comment by radiumrasheed** [comment]
> Basic OOP saves you here. Just create a base class:
> 
> ```js
> class ModelBase  extends Model {
>   $beforeUpdate() {
>     this.updatedAt = new Date().toISOString();
>   }
> 
>   $beforeInsert() {
>     this.createdAt = new Date().toISOString();
>   }
> }
> ```
> 
> and then inherit all your models from `ModelBase` instead of `Model`. This way the code is only in once place.

I think its best to remove the createdAt field when updating

```javascript
   $beforeUpdate() {
     delete this.createdAt;
     this.updatedAt = new Date().toISOString();
   }
```
