### ISSUE TITLE
Catching a query error only returns an empty object

### ISSUE THREAD

**Issue by marcus-sa** [Vincit/objection.js#461]
I think that all the ORM's is handling errors really bad. 
e.g Bookshelf.js only output error code, SQL state, and field index.

Objection.js doesn't provide anything at all.
When catching a promise the error only returns an empty object.

Example when creating a new user:
```
export default class UsersCreate {

  method = 'post'
  model = 'users'

  route(req, res, next, config, Users) {
    const { username, password } = req.body

    Users.query()
      .insert({ username, password })
      .then(user => {
        user.token = user.createToken()

        req.login(user, (err) => {
          if (err) {
            res.status(501).send(err)
          } else {
            res.status(202).end()
          }
        })
      })
      .catch(err => res.status(501).send(err)) // error only returns an empty object {}
  }

}
```

Model:
```
import { Model } from 'objection'
import jwt from 'jwt-simple'
import bcrypt from 'bcrypt'

import config from '../../../src/config'

export default class Users extends Model {

  static tableName = 'users'

  static get jsonSchema() {
    return {
      type: 'object',
      required: [
        'username',
        'password'
      ],

      properties: {
        id: { type: 'integer' },
        username: {
          type: 'string',
          minLength: 2,
          maxLength: 16
        },
        password: { type: 'string' }
      }
    }
  }

  set password(password: String) {
    const salt = bcrypt.genSaltSync(config.bcrypt.rounds)

    this.password = bcrypt.hashSync(password, salt)
  }

  verifyPassword(password: String) {
    return bcrypt.compareSync(password, this.password)
  }

  createToken() {
    return jwt.encode(this.password, config.secret)
  }

}
```

**Comment by newhouse** [comment]
Are you saying that (and are you sure that) the error is occurring due to your `insert()` attempt? In my experience, Objection would definitely throw a useful error to the `catch` if something went wrong with the `Users.query.insert()` part. Perhaps there's a bug in this instance, but I get totally useful errors and always have.

Are you sure that the problem is not within the `.then(user => { ` clause and you are, in fact, inserting properly but then something goes wrong?

**Comment by koskimas** [comment]
First of all, really nice way to report an issue! It really makes me want to help you. Second of all, you are simply wrong. Objection returns the database error in case of database errors. I realize that there should probably be a layer that unifies those errors between different database engines, but that should be implemented as a separate module. I don't want to start maintaining that layer as it would require alot of work and I simply don't have time for it. Whatever the case, ther error should at least have a message and stack a stack trace. Please feel free to provide a standalone reproduction of a case that throws an empty object and I'll fix it immediately. Until that I will very much ignore this issue.

**Comment by marcus-sa** [comment]
@koskimas I'm really sorry, I didn't mean to be harsh in any way at all.

I found out, that by removing the catching the error will then be logged into the console.
I'm using a routing middleware I coded that iterates through all my models requires them and assigns them to an object.
```
glob.sync(path.join(models, '**')).forEach(modelFile => {
        const resolve = path.resolve(modelFile)

        if (fs.lstatSync(resolve).isDirectory()) {
          return false
        }

        const model = require(modelFile)

        this.models[model.tableName] = model
})
```

Aside from all that even if I import them normally I receive this error:
```
Unhandled rejection TypeError: Class constructor Model cannot be invoked without 'new'
    at new Users (/home/sentinel/git/stormcms-github/api/database/models/users.js:51:117)
    at Function.fromDatabaseJson (/home/sentinel/git/stormcms-github/node_modules/objection/lib/model/Model.js:287:19)
```
