### ISSUE TITLE
patch - dedicated field for required attributes?

### ISSUE THREAD

**Issue by theogravity** [Vincit/objection.js#463]
When I'm doing a patch, I'd like to still validate against some required fields (eg an id). Currently, I have to do something like this separately before my patch:

```
User.fromJson({
 // send required fields here
})
```

to test if the incoming patch data meets validation requirements. It'd be nice to be able to define required fields specifically for patching. It won't always match the required fields for inserting.

**Comment by koskimas** [comment]
You can implement your [own validator](http://vincit.github.io/objection.js/#custom-validation) to do that. You can for example extend the default `AjvValidator`:

```js
class MyValidator extends AjvValidator {
  validate(args) {
    const json = super.validate(args);
    
    if (arg.options.patch) {
      // You can either implement this as a static list in the model class
      // or as a new property in `jsonSchema` or anything you want.
      const require = args.model.constructor.requiredPatchAttributes;

      // Check here and throw an error if patch attribute is missing.
    }

    return json;
  }
}
```

This is such a specific request that I don't think it should be added to objection.

**Comment by koskimas** [comment]
Also if you have the same required properties for insert and update, you can just use the`update()` method instead of `patch()`. `update()` checks against the required properties.

**Comment by theogravity** [comment]
ah, thanks
