### ISSUE TITLE
model.query().insert(...).toSql() does not return a valid query string

### ISSUE THREAD

**Issue by pineapplemachine** [Vincit/objection.js#464]
I have an insert query that looks like this:

``` js
const timestamp = moment.utc();
const q = app.db.Respondent.query().insert({
    "respondentId": respondentId,
    "creationTime": timestamp,
    "lastActiveTime": timestamp,
})
```

I am trying to extend the query builder in a way that seemingly requires me to produce a query string for the insertion before using `this.modelClass().raw(queryStringIncludingInsertion, bindings)`. It looks as though this would work fine for my use case except that the result of calling `toSql` is not a valid query, even though the query performs as expected if using `then`.

`q.toSql()` returns:

``` sql
insert into "maptionnaire"."Respondents" ("creationTime", "lastActiveTime", "respondentId")
values ("2017-07-31T11:19:16.222Z", "2017-07-31T11:19:16.222Z", 'TEST!')
returning "respondentId"
```

In order for this to be a valid postgres query, the double quotes surrounding the timestamp string literals must be single quotes, i.e.

``` sql
insert into "maptionnaire"."Respondents" ("creationTime", "lastActiveTime", "respondentId")
values ('2017-07-31T11:19:16.222Z', '2017-07-31T11:19:16.222Z', 'TEST!')
returning "respondentId"
```

**Comment by koskimas** [comment]
Objection usea knex to build the SQL. You should probably open this issue in knex github. Objection calls knex's `toString` method to create the string.

**Comment by koskimas** [comment]
I'm closing this since there is nothing that can be done on objection's side. By the way, you can probably make that work if you use `timestamp.toISOString()` instead of the moment instance `timestamp` itself. knex probably check's its type and does somethings weird because it is an object, and finally calls its `toString` method.
