### ISSUE TITLE
first() not respected in modifyEager

### ISSUE THREAD

**Issue by juanjoLenero** [Vincit/objection.js#467]

**Comment by koskimas** [comment]
Unfortunately that's one of the limitations of eager queries as explained [here](http://vincit.github.io/objection.js/#eager). You can use `naiveEager` algorithm, but even then you cannot change arrays into objects. You can use `limit(1)` and get an array with only one item. Also note that by default `first` doesn't add `limit 1` to the query. You can change this behaviour using [useLimitInFirst](http://vincit.github.io/objection.js/#uselimitinfirst) config property.

**Comment by juanjoLenero** [comment]
Thank you, sorry about the empty message body, I accidentally pressed enter when editing the submission. I'm aware of the limitations I just wanted a convenience method for doing exactly that `picking the first element out of the array`.

Several times in my APIs I have to return something like this:
```js
Person.query()
    .eager('movies as firstMovie')
    .modifyEager('movies', (builder) => {
        builder.orderBy('publish_date', 'asc').first();
    }

// Would return:
[
{name: 'Ragnar', firstMovie: {title: 'someMovie'}},
{name: 'Lagertha', firstMovie: {title: 'someOtherMovie'}}
]

// Instead of:
[
{name: 'Ragnar', firstMovie: [{title: 'someMovie'}]},
{name: 'Lagertha', firstMovie: [{title: 'someOtherMovie'}]}
]
```
I don't need paging/limiting on the relation, I just need to transform the array to its first element.

I'll just do the transformation before sending the response to the client, but this would be nice to have.

**Comment by koskimas** [comment]
Actually you can achieve what `first` would do by combining couple of things:

```js
class Person extends Model {
  static get relationMappings() {
    return {
      // Let's pretend this is your relation.
      children: {
        modelClass: Person,
        relation: Model.HasManyRelation,
        join: { ... }
      },

      // Now you can create another relation that is a copy of the previous one, but
      // instead of `HasManyRelation` you'll use `HasOneRelation`. And if `children`
      // is a `ManyToManyRelation` you can use `HasOneThroughRelation`. You can
      // even name it better this way.
      firstChild: {
        modelClass: Person,
        relation: Model.HasOneRelation,
        join: { ... }
      },
    };
  }
}
```

Now when you want to query a single item (use `first`) you can do something like this:

```js
Person
  .query()
  .naiveEager('firstChild')
  .modifyEager(qb => qb.where('something', 'blaa').orderBy('publish_date', 'asc'))
```

**Comment by juanjoLenero** [comment]
That works! 👍
