### ISSUE TITLE
query.throwIfNotFound().delete() not working

### ISSUE THREAD

**Issue by joaonice** [Vincit/objection.js#469]
Hi,
`throwIfNotFound` method is not working with `delete` (and maybe other methods) since the result of deleting an inexistent row is `0`.

Maybe we can change the `throwIfNotFound` method to be like:

```js
  throwIfNotFound() { 
    return this.runAfter((result, builder) => {
      if (Array.isArray(result) && result.length === 0) {
        throw this._modelClass.createNotFoundError(builder.context());
      } else if (result === null || result === undefined || result === 0) {
        throw this._modelClass.createNotFoundError(builder.context());
      } else {
        return result;
      }
    });
  }
```

I'm not sure if there is another case that the result is `0` and we don't want to throw the error.

What do you think?

Thank you

**Comment by koskimas** [comment]
Sounds good! The result is zero also when updating and no rows get updated, but we should probably throw then too.
