### ISSUE TITLE
Helper for applying multiple plugins

### ISSUE THREAD

**Issue by koskimas** [Vincit/objection.js#473]
This can become a mess:

```js
class BaseModel extends Plugin1(Plugin2(Plugin3({opt: 'foo'})(Plugin4(Model)))) {

}
```

Should we add a helper like this:

```js
class BaseModel extends Model.plugin(Plugin1, Plugin2, Plugin3({opt: 'foo'}), Plugin4) {

}
```

Or would `mixin` be a better name for the method?

Arrays would also be supported:

```js
class BaseModel extends Model.plugin([
  Plugin1, 
  Plugin2, 
  Plugin3({opt: 'foo'}),
  Plugin4
]) {

}
```

**Comment by devinivy** [comment]
Worth checking the API/implementation of this lib for inspiration https://github.com/justinfagnani/mixwith.js

If you go the direction you're hinting at, I'd request to at least let `Model.plugin(P1, ..., Pn)` extend from `Model` even if `Model` is already an extension of `Objection.Model`.

**Comment by koskimas** [comment]
@devinivy That library was my inspiration. I originally thought of adding a helper like:

```js
class Person mixin(Model, Plugin1, Plugin2) {

}
```

but the you would need to require the `mixin` helper. Since we are always mixin in stuff to `Model` or `QueryBuilder` or some othe known baseclass, we can make the mixin helper a static method.

The implementation would be simply this:

```js
class Model {
  static plugin() {
    return _.flatten(_.toArray(arguments)).reduce((Model, Plugin) => {
      return Plugin(Model);
    }, this);
  }
}
```

Of course it will always extend `this` instead of `objection.Model`.

**Comment by fl0w** [comment]
Wouldn't it be easier to have a callable api that just reassigns model with most recent "extends"?

```js
objection.plugin(Plugin1)
objection.plugin(Plugin2)
objection.plugin(Plugin3)
```

**Comment by koskimas** [comment]
@fl0w Nope, then we would lose part of the flexibility. After that you would have no way to access the original unmodified `Model`.

**Comment by fl0w** [comment]
@koskimas understood. Storing the plugin/model chain layout wouldn't help either?

```js
objection.inspectPluginChain = {
  original: Model,
  'plugin-name-1': Plugin1, 
  'plugin-name-2': Plugin2
}
```

Extending with intent is always an option but, correct me if I'm wrong, generally plugins would be used application wide? (considering soft-delete/case-conversion/auto-update-timestamps perhaps).

**Comment by koskimas** [comment]
> generally plugins would be used application wide?

Probably, but nothing prevents you from doing

```js
objection.Model = objection.Model.plugin(Plugin1, Plugin2);
```

**Comment by fl0w** [comment]
Ah, got it. Thanks.

**Comment by koskimas** [comment]
Would you prefer `mixin` instead of `plugin` as the name? I think we could use this kind of helper because many people seem disgusted by

```js
class BaseModel extends Plugin1(Plugin2(Plugin3({opt: 'foo'})(Plugin4(Model)))) {

}
```

This seems cleaner to me:

```js 
class BaseModel extends Model.mixin([
  Plugin1, 
  Plugin2, 
  Plugin3({opt: 'foo'}),
  Plugin4
]) {

}
```

**Comment by fl0w** [comment]
That's sort of reminiscent of a stack of decorators (visually).
I think it's generally easier to list than scope depth, so I personally prefer the latter.

**Comment by koskimas** [comment]
Yeah, mixin is what we are doing. I think that's a better name. I'll still document plugin usage using simple function calls (like it is explained today) so that people see what is going on. I'll only add a side note about the `mixin` helper for the people that throw up in their mouths.

**Comment by VladShcherbin** [comment]
Is it possible to have something like a [HOC in react](https://facebook.github.io/react/docs/higher-order-components.html)?

```js
class Animal extends Model {
  static tableName = 'animals'
}

// Single plugin
export default timestamps({ type: 'timestamptz' })(Model)

// Multiple plugins
export default compose(
  timestamps({ type: 'timestamptz' }),
  softDeletes()
)(Model)
```

**Comment by VladShcherbin** [comment]
Working example of this:

hoc:

```js
function timestamps(options) {
  // check for required options
  return (WrappedModel) => {
    class TimeStampsModel extends WrappedModel {
      $beforeInsert() {
        const date = new Date().toISOString()

        this[options.createdColumnName] = date
        this[options.updatedColumnName] = date
      }

      $beforeUpdate() {
        this[options.updatedColumnName] = new Date().toISOString()
      }
    }

    return TimeStampsModel
  }
}
```

model:

```js
class Animal extends Model {}

export default timestamps({
  createdColumnName: 'created_at',
  updatedColumnName: 'updated_at'
})(BaseModel)
```

**Comment by koskimas** [comment]
@VladShcherbin The problem with applying the mixings after extending the parent class is that the class name will be the name of the last applied polugin class. All stack traces containing model methods will have confusing names. Otherwise you can already do that.

I'm getting the feeling that no-one is especially thrilled about the `plugin` or `mixin` helper as a static member of `Model`. @devinivy Would you prefer a separate helper function in objection core:

```js
import { mixin, Model } from 'objection'

class Animal extends mixin(Model, [Plugin1, Plugin2]) {
  static tableName = 'animals'
}
```

Or would you prefer no helpers at all?

@VladShcherbin If we go down that road, I could also add a `compose` method like you suggested.

**Comment by devinivy** [comment]
While it's not a big deal to me, I think it would be useful to have a very basic one in objection to reinforce the standard way to write an objection plugin.  I think it would be positive for the objection ecosystem.  Whether it's `Model.mixin()` or `mixin(Model)`, I think it's fine :)

**Comment by VladShcherbin** [comment]
@koskimas no, the class names won't be wrong if higher-order function will define class like this:

```js
function timestamps(options) {
  // check for required options
  return WrappedModel => (
    class extends WrappedModel {
      ...
    }
  )
}
```

This way, the result class will have WrappedModel name.

**Comment by koskimas** [comment]
Try this:

```js
class X {}
const f = (M) => class extends M {}
const Y = f(X);
console.log(Y.name);
```

and you get `''` as an output. The last extending class has no name.

**Comment by VladShcherbin** [comment]
@koskimas yea, it gives me `"_class"` as a result. Here is how it's handled in react - [link](https://facebook.github.io/react/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging), `displayName` is used instead of `name`. But maybe it's too much for Objection.

**Comment by VladShcherbin** [comment]
@koskimas hm, actually it gives me `X`. Here is jsbin example - https://jsbin.com/yodotohevi/edit?js,console

**Comment by VladShcherbin** [comment]
@koskimas actually it's giving me `X` as a result. Here is the [jsbin example](https://jsbin.com/yodotohevi/edit?js,console).

**Comment by koskimas** [comment]
Node 7 gives an empty string and so does node 4. I doubt that 5,6 or 8 act any different. Babel is not 100% compatible in this case.

**Comment by VladShcherbin** [comment]
@koskimas for me, babel is working exactly the same as node. Here is the same code in pure node 8:

![screen shot 2017-08-08 at 11 18 04 pm](https://user-images.githubusercontent.com/6711845/29092737-0e3aa350-7c90-11e7-81ef-94b2d4a8dd51.png)

**Comment by koskimas** [comment]
You're right. Node 8 does work like that. Older versions give the empty string.

**Comment by VladShcherbin** [comment]
@koskimas yeah, this will be great. With latest node versions and babel you get nice things like `async/await`, decorators, etc.

Adding plugins also becomes a joy with higher-order functions and a combining helper like `compose`. This is exactly the way I would add them in my projects.

**Comment by maprangsoft** [comment]
> @vladshcherbin The problem with applying the mixings after extending the parent class is that the class name will be the name of the last applied plugin class. All stack traces containing model methods will have confusing class names. Otherwise you can already do that.
> 
> I'm getting the feeling that no-one is especially thrilled about the `plugin` or `mixin` helper as a static member of `Model`. @devinivy Would you prefer a separate helper function in objection core:
> 
> ```js
> import { mixin, Model } from 'objection'
> 
> class Animal extends mixin(Model, [Plugin1, Plugin2]) {
>   static tableName = 'animals'
> }
> ```
> 
> Or would you prefer no helpers at all?
> 
> @vladshcherbin If we go down that road, I could also add a `compose` function like you suggested.

thank you very much.
