### ISSUE TITLE
Easiest/best way to refresh an instance *and* it's relations?

### ISSUE THREAD

**Issue by newhouse** [Vincit/objection.js#476]
Let's say that something like this does exactly what you'd think it would do (all of this is hastily written, not validated code):
```
let parentId = 123,
  parent,
  child,
  grandChild;

Parent
  .query()
  .eager('child.grandchild')
  .where({id: parentId})
  .then(p => { 
    parent = p;
    child = parent.child;
    grandchild = child.grandchild;
  });
```

Earlier today, after making an API call that changed `parent`, `child` and `grandchild` in the DB, I found myself just naturally whipping out the following in order to refresh them in my scope:
```
parent
  .$query() // Fetch a fresh instance of 'parent'
  .eager('child.grandchild') // Fetch some relations as well, please!
  .then(...);
```
This, unfortunately, didn't do what I thought it would: it only updated `parent` and not [`parent.child` and `parent.child.grandchild`]. I think the `eager()` was just ignored (maybe it should have errored?). I guess I don't think I've seen anywhere that this would work, but it felt natural...anyway, I looked at and weighed `$loadRelated` and `$relatedQuery` and `Parent.query().eager(...).where(...) /* all over again */` as possible fixes, and ended up writing:
```
parent.
  .$query()
  .then(p => {
    parent = p;
    return parent
      .$relatedQuery('child')
      .eager('grandchild');
  .then(c => {
    child = c;
    grandchild = child.grandchild;
    ...
  );
```

I guess my question is: is there a better way to refresh an instance _and its child relations_? I'd like to utilize that, if so...and I'd probably see about adding it to the docs!

Thanks for all your help!

**Comment by koskimas** [comment]
This should work

```js
parent
  .$query() // Fetch a fresh instance of 'parent'
  .eager('child.grandchild') // Fetch some relations as well, please!
  .then(...);
```

Are you using `JoinEagerAlgorithm`? If not, there's probably a bug.

**Comment by koskimas** [comment]
I wrote this test:

```js
      return Model1
        .query()
        .findById(1)
        .then(model => {
          return model
            .$query()
            .eager('[model1Relation1, model1Relation2.model2Relation1]');
        })
        .then(model => {
          expect(yaddaYadda)
        })
```

And it worked. Is there something special about your query or the models? Any hooks or modified query builders or something like that?

**Comment by koskimas** [comment]
Oh, but I just realized that the model `.$query()` is called, doesn't get updated.

**Comment by newhouse** [comment]
What the? I just went back and wrote a standalone-ish, deliberate test and it worked as it should/as you said. Maybe my brain is [on drugs](http://imgsrc.allposters.com/img/print/posters/brain-on-drugs-eggs-college-humor-poster_a-G-8926674-0.jpg)...again.

I came to the conclusion that something was wrong while working out of a tiny cafe with no wifi jacked up on coffee waiting for my motorcycle to get all fixed up, so I was not as clear-headed as I can be, but I'll go back and double check the area that I originally "discovered" this issue, and see if I was just being dumb.

Either way, I've got a few questions:
1) If the `parent.child.grandchild` refresh does work as expected via `instance.$query().eager('child.grandchild')`, is that use case documented and/or tested? I can try to at least write the docs, if not...you may already have just written the tests!
2) In the docs, the `instance.$query().then(...)` as a "refresh" tactic has an example titled ["Re-fetch the instance from the database:"](http://vincit.github.io/objection.js/#_s_query) and it doesn't explicitly show that the original instance will be updated (it uses the instance passed to the resolution). I think the fact that it did not update the original instance chafed me originally until I noticed that nuance in the docs, but once I realized how it worked I thought of it less like a "bug" and more like something that could have been slightly more clearly documented. Plus, if you change Objection to update the original instance, it becomes much more laborious to have the old an new instances around at the same time if you so desired (I'm thinking toJSON -> fromJSON or worse, right?).  I guess what I'm saying is that "fixing" this behavior may be a worse idea than simply updating the docs and leaving it be...plus it would certainly piss a lot of people off if not carefully considered.

I'll circle back with whether this whole thing was a wild goose chase...wouldn't be my first one in here. Many thanks...

**Comment by newhouse** [comment]
Yeah, the `parent.child.grandchild` refresh does work as expected...

**Comment by koskimas** [comment]
Yeah, maybe it's better to not change it. I just thought it would have made it consistent with `update` and `insert`, but let's change if more issues pop up.

The current behaviour is tested already. This could be documented better though.
