### ISSUE TITLE
[Bug] Issues while updating with Upsert with n x n relation + extra field

### ISSUE THREAD

**Issue by Gustav0ar** [Vincit/objection.js#477]
I'm having the following issues while updating an NxN relation that has extra fields:

> { method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, true, 1, 2, false, 1 ],
  __knexQueryUid: 'a050bcb9-cf2a-4137-b9d2-860518490aef',
  sql: 'insert into "IdiomasFalados" ("idioma_id", "oficial", "pais_id") values (?, ?, ?), (?, ?, ?) returning "idioma_id"',
  returning: [ 'idioma_id' ] }
{ error: insert into "IdiomasFalados" ("idioma_id", "oficial", "pais_id") values ($1, $2, $3), ($4, $5, $6) returning "idioma_id" - insert or update on table "IdiomasFalados" violates foreign key constraint "idiomasfalados_idioma_id_foreign"
    at Connection.parseE (/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  name: 'error',
  length: 292,
  severity: 'ERROR',
  code: '23503',
  detail: 'Key (idioma_id)=(1) is not present in table "Idiomas".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'IdiomasFalados',
  column: undefined,
  dataType: undefined,
  constraint: 'idiomasfalados_idioma_id_foreign',
  file: 'ri_triggers.c',
  line: '3324',
  routine: 'ri_ReportViolation' } null 2

My object schema:
```js
          export class Pais extends BaseId {
          static tableName = 'Paises';
        
          static tableColumns = {
            id: 'id',
            nome: 'nome',
            moedaId: 'moeda_id'
          };
        
          static jsonSchema = {
            type: 'object',
        
            required: ['nome', 'moedaId'],
        
            properties: {
              nome: { type: 'string', minLength: 1, maxLength: 120 }
            }
          };
        
          static relationMappings: RelationMappings = {
            moeda: {
              relation: Model.BelongsToOneRelation,
              modelClass: Moeda,
              join: {
                from: 'Paises.moeda_id',
                to: 'Moedas.id'
              }
            },
            idiomas: {
              relation: Model.ManyToManyRelation,
              modelClass: Idioma,
              join: {
                from: 'Paises.id',
                through: {
                  from: 'IdiomasFalados.pais_id',
                  to: 'IdiomasFalados.idioma_id',
                  extra: ['oficial']
                },
                to: 'Idiomas.id'
              }
            }
          };
        
          nome: string;
          moedaId: number;
          moeda: Moeda;
          idiomas: Idioma[];
    }
```

I'm updating this object:

```js
     { id: 1,
        nome: 'Brasil',
        moedaId: '1',
        idiomas: 
        [ { '#dbRef': 1, oficial: true },
          { '#dbRef': 2, oficial: false } ] }
```

Where idiomas[0] exists in the db and idiomas[1] doesn't.
For some reason it gives a constraint error that it doesn't find idiomas_id., but it exists in the db.
Also, since it's a n x n relation and doesn't have an id column, it tries to insert both relations, and it would fail since the primary key is based on 'pais_id' and 'idioma_id'.

I'm using this command to update (it works fine with insertGraph):

```js
      const knex = Pais.knex();
      const pais = await objection.transaction(knex, async (trx: any) => Pais.query(trx).upsertGraph(model)) as any;
```

Any way to solve this issue in the current model?

**Comment by koskimas** [comment]
You shouldn't use `#dbRef` if you are not sure the object already exist in the db. If `#dbRef: 2` doesn't exist, it should fail. `#dbRef` tells objection that "this id exists in the database".

You should be able to use `relate` and `unrelate` flags like this:

```js
const pais = await objection.transaction(knex, async (trx: any) => {
  return Pais
    .query(trx)
    .upsertGraph(model, { relate: true, unrelate: true });
});
```

If that doesn't work, there could be a bug with `extra` properties.

**Comment by koskimas** [comment]
Also `idiomas` needs to look like this:

```js
[ 
  { id: 1, oficial: true },
  { oficial: false } 
]
```

if `id: 1` exists, but the other item doesn't.

**Comment by Gustav0ar** [comment]
> Also idiomas needs to look like this:
>
> 
> [ 
>   { id: 1, oficial: true },
>   { oficial: false } 
> ]
> if id: 1 exists, but the other item doesn't.

This won't work, I don't know if you looked at the model, but 'idiomas' inside 'pais' is a NxN relation that I need to pass the idiomaId because it can change. In other words, I need to pass the id to it to know which 'idioma' it's related to.

I tried your approach with the model:
```
{ id: 1,
  nome: 'Brasil',
  moedaId: '1',
  idiomas: [ { id: 1, oficial: true }, { id: 2, oficial: false } ] }
```

It almost worked. But for some reason it gave me validation error while trying to insert Idioma in table 'Idiomas' where it shouldn't do, as you can see below:

```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '88138427-7a47-47bd-ae00-7150df9a9d72',
  sql: 'select "Paises"."id" from "Paises" where "Paises"."id" in (?)' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '1' ],
  __knexQueryUid: '6f53ced1-fdf7-49c2-b49e-1f914b1f00aa',
  sql: 'select "IdiomasFalados"."pais_id" as "objectiontmpjoin0", "Idiomas"."id" from "Idiomas" inner join "IdiomasFalados" on "IdiomasFalados"."idioma_id" = "Idiomas"."id" where "IdiomasFalados"."pais_id" in (?)' }
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 2, false, 1 ],
  __knexQueryUid: '392620aa-fc94-48aa-8e86-40ffd6037491',
  sql: 'insert into "IdiomasFalados" ("idioma_id", "oficial", "pais_id") values (?, ?, ?) returning "idioma_id"',
  returning: [ 'idioma_id' ] }
{ method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '2017-08-12T12:50:07.259Z', 1, '1', 'Brasil', 1 ],
  __knexQueryUid: 'a6faebf6-4aec-4bb6-b50e-6f1d37ce531f',
  sql: 'update "Paises" set "data_alteracao" = ?, "id" = ?, "moeda_id" = ?, "nome" = ? where "Paises"."id" = ?',
  returning: undefined }
{ Error: {
  "nome": [
    {
      "message": "should have required property 'nome'",
      "keyword": "required",
      "params": {
        "missingProperty": "nome"
      }
    }
  ],
  "sigla": [
    {
      "message": "should have required property 'sigla'",
      "keyword": "required",
      "params": {
        "missingProperty": "sigla"
      }
    }
  ],
  "identificadorUsb": [
    {
      "message": "should have required property 'identificadorUsb'",
      "keyword": "required",
      "params": {
        "missingProperty": "identificadorUsb"
      }
    }
  ]
 }
    at ValidationError (/node_modules/objection/lib/model/ValidationError.js:5:5)
    at Function.createValidationError (/node_modules/objection/lib/model/Model.js:318:12)
    at parseValidationError (/node_modules/objection/lib/model/AjvValidator.js:147:21)
    at AjvValidator.validate (/node_modules/objection/lib/model/AjvValidator.js:61:13)
    at Idioma.$validate (/node_modules/objection/lib/model/modelValidate.js:30:20)
    at Idioma.$validate (/node_modules/objection/lib/model/Model.js:144:22)
    at Promise.map.node (/node_modules/objection/lib/queryBuilder/operations/rtGraphOperation.js:98:24)
    at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/node_modules/bluebird/js/release/ise_array.js:114:31)
    at MappingPromiseArray.init (/node_modules/bluebird/js/release/promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
  data: 
   { nome: [ [Object] ],
     sigla: [ [Object] ],
     identificadorUsb: [ [Object] ] },
  statusCode: 400 } null 2

```

It correctly tried to insert only the one that was missing.

I also tried a different approach, I changed a bit my structure, I added the id column to the the NxN relation (IdiomasFalados). I used this model:

```
{ id: 1,
  nome: 'Brasil',
  moedaId: '1',
  idiomas: 
   [ { '#dbRef': 1, oficial: true, id: 1 },
     { '#dbRef': 2, oficial: false } ] }
```
But it gave me this error:

```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '5830c244-99d8-4114-9204-cac4a6638d8e',
  sql: 'select "Paises"."id" from "Paises" where "Paises"."id" in (?)' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '1' ],
  __knexQueryUid: '1dc978ed-4fb0-4c74-80bc-25757566ef00',
  sql: 'select "IdiomasFalados"."pais_id" as "objectiontmpjoin0", "Idiomas"."id" from "Idiomas" inner join "IdiomasFalados" on "IdiomasFalados"."idioma_id" = "Idiomas"."id" where "IdiomasFalados"."pais_id" in (?)' }
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, true, 1, 2, false, 1 ],
  __knexQueryUid: '1fe93464-8031-4d0d-ab2b-66ab08e16236',
  sql: 'insert into "IdiomasFalados" ("idioma_id", "oficial", "pais_id") values (?, ?, ?), (?, ?, ?) returning "idioma_id"',
  returning: [ 'idioma_id' ] }
{ error: insert into "IdiomasFalados" ("idioma_id", "oficial", "pais_id") values ($1, $2, $3), ($4, $5, $6) returning "idioma_id" - dupliicate key value violates unique constraint "idiomasfalados_idioma_id_pais_id_unique"
    at Connection.parseE (/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  name: 'error',
  length: 266,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (idioma_id, pais_id)=(1, 1) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'IdiomasFalados',
  column: undefined,
  dataType: undefined,
  constraint: 'idiomasfalados_idioma_id_pais_id_unique',
  file: 'nbtinsert.c',
  line: '433',
  routine: '_bt_check_unique' } null 2
```

It didn't work because it tried to insert an existing row with the id=1 that has a unique key between 'pais_id' and 'idioma_id'.
These were the closest approaches to working that I got.

**Comment by koskimas** [comment]
You have `required: ['nome', 'moedaId']` this in your jsonSchema, so it _should_ fail if you don't give those for the model you are _inserting_. I'm not really sure what you want to achieve? Are both `id: 1` and `id: 2` already inserted or are you trying to insert the other one? If both exist, simple give the id for both of them:

```js
const pais = await objection.transaction(knex, (trx: any) => {
  return Pais
    .query(trx)
    .upsertGraph(model, { relate: true, unrelate: true });
});
```

```js
[ 
  { id: 1, oficial: true },
  { id: 2, oficial: false } 
]
```

**Comment by koskimas** [comment]
Here are couple of examples:

This is the query:

```js
const pais = await objection.transaction(knex, (trx: any) => {
  return Pais
    .query(trx)
    .upsertGraph(model, { relate: true, unrelate: true });
});
```

Assume that this is the current `idiomas` before the query:

```js
[ 
  { id: 1, oficial: true },
  { id: 2, oficial: false } 
]
```

Not if `idiomas` in the `model` is:

```js
[ 
  // This is already in `idiomas` --> update
  { id: 1, oficial: true },
  // This is not in `idiomas` but exists in the database --> relate
  { id: 3, oficial: false },
  // This doesn't have an id --> insert
  { oficial: true }
]

// And finally `{ id: 2 }` gets unrelated since it is not listed at all in `idiomas`.
```

If you don't give the `relate: true` and `unrelate: true` flags:

```js
[ 
  // This is already in `idiomas` --> update
  { id: 1, oficial: true },
  // This is not in `idiomas` but exists in the database --> error
  { id: 3, oficial: false },
  // This doesn't have an id --> insert
  { oficial: true }
]

// And finally `{ id: 2 }` gets deleted since it is not listed at all in `idiomas`.

**Comment by Gustav0ar** [comment]
> You have required: ['nome', 'sigla', 'identificadorUsb'] in your jsonSchema, so it should fail if you don't give those for the model you are inserting

Well, this schema is in 'Idioma' model. I'm not trying to insert Idioma, I'm trying to insert 'Pais' and the 'IdiomasFalados' table (idiomas property inside Pais) which is a Many to Many relation. It shouldn't give any validation error for trying to insert in Idioma because I didn't specify it to.

I gave the `relate: true` and `unrelate: true` flags like you mentioned.
My case is pretty simple:
**id 1** (which is Idioma.id = 1) is already related, but **id 2** isn't related yet and I'm trying to relate it

Like I told you above, I used the following model and it gave me Validation Errors for no apparent reason:

```
{ id: 1,
  nome: 'Brasil',
  moedaId: '1',
  idiomas: [ { id: 1, oficial: true }, { id: 2, oficial: false } ] }
```
For some reason it tried it validated Idioma to insert in Idiomas table, where it shouldn't

**Comment by koskimas** [comment]
You are not inserting `Pais`. You have specified an `id 1` for it. Therefore `upsertGraph` simply updates the `Pais`. But you are right. If you specified `{relate: true, unrelate: true}` options, the query shouldn't try to insert `Idioma` rows, but relate them.

I'm sorry, I don't know how to help. I have an equal test case and it works perfectly. Only way I can help you is if you provide a minimal standalone app that reproduces the bug so that I can debug it.

**Comment by Gustav0ar** [comment]
It doesn't really insert, if I remove the required from the jsonSchema in Idioma, it works flawlessly

**Comment by koskimas** [comment]
I just realized that in my test cases there are no `required` properties. Let me update the tests and I'll report what I find.

**Comment by Gustav0ar** [comment]
Ok, thanks, if you can't find, I'll try to debug here or build you a test case

**Comment by koskimas** [comment]
I found the bug. Sorry about me being a bit lost in this issue. I didn't read your comments properly. I fixed the problem and I'll release a patch as soon as possible.

**Comment by Gustav0ar** [comment]
Hooray! Thanks very much. Was my fault, I thought the problem was one thing and it was actually another.
