### ISSUE TITLE
Nested model validation

### ISSUE THREAD

**Issue by VladShcherbin** [Vincit/objection.js#478]
I tried to use `insertGraph` method, but I'm not sure how to handle validation errors for nested models. 

For example

```js
Person.query()
  .insertGraph({
    firstName: 'Sylvester',
    lastName: 'Stallone',
    children: [{
      firstName: 'Sage'
    }]
  })
```

If `children` model has required field for `lastName` and input value is not provided, I'd expect a nested error with `children.0.lastName`.

For current workaround I take input data, validate and then use model to save so validation is handled outside of the model.

This also led me to thoughts, if validation logic belongs to a model or a request layer. Shall we validate data first and then use model to save it or leave validation to model and improve nested validation.

I'm interested in recommended way of doing this since nested data validation is common and current ways of solving this.

**Comment by VladShcherbin** [comment]
Same question for different validation scenario: you need to validate model with different rule sets (for example, different rules for insert and update).

One way is to use `patch` method which omits required fields check, but there are sure another use cases, where you need to validate different fields. I can think of an example where your validation rules depend on a received field value.

If validation is handled outside of the model, you can validate incoming data with different rule sets and use models just to insert or update after.

**Comment by koskimas** [comment]
After trying to implement this in objection, I think the best way to achieve this is by also adding your relations to `jsonSchema`. It will lead to some duplicate validation in some cases, but it's still the cleanest way to get this done since Ajv can already give those nested errors. Adding the logic to objection is really difficult.

**Comment by VladShcherbin** [comment]
@koskimas yeah, I ended up by moving validation away from model level and never had any issues :)
