### ISSUE TITLE
Pass arguments to namedFilters?

### ISSUE THREAD

**Issue by jordansexton** [Vincit/objection.js#481]
This is probably outside the scope of #375, but could arguments be passed to named filters?

e.g.
```javascript
class Person extends Model {
  static get namedFilters() {
    return {
      lastName (builder, value) => {
        builder.where('lastName', value);
      }
    };
  }
}

Movie
  .query()
  .eager('actors(lastName)', { lastName: 'Schwarzenegger' })

// or if ambiguous: { 'actors(lastName)': 'Schwarzenegger' }
```

or

```javascript
class Job extends Model {
  static get namedFilters() {
    return {
      status (builder, ...statuses) => {
        builder.whereIn('status', statuses);
      }
    };
  }
}

Job
  .query()
  .filter('status', { status: ['failed', 'expired'] })

// or with a shorthand: .filter('status', ['failed', 'expired'])
```

(I imagine this is possible another way, I just don't know the internals well yet.)

**Comment by devinivy** [comment]
I think one way you might be able to approach this is using the builder's [`context`](http://vincit.github.io/objection.js/#context).

**Comment by fl0w** [comment]
I do it using context (as @devinivy suggested). Though it is hard to keep the context clean as the number of filters grows.

**Comment by jordansexton** [comment]
Thanks @devinivy and @fl0w. Would you mind providing an example of your usage? The examples in the docs of `context`/`mergeContext` feel a little contrived, so it's hard for me to understand the "keep the context clean" part.

**Comment by koskimas** [comment]
You could do something like this:

```js
class CustomQueryBuilde extends Model.QueryBuilder {
  eager(expr, args) {
    this.mergeContext({namedFilterArgs: args});
    return super.eager(expr);
  }
}

class BaseModel extends Model {
  static get QueryBuilder() {
    return CustomQueryBuilder;
  }
}

class Person extends Model {
  static get namedFilters() {
    return {
      lastName (builder) => {
        const args = builder.context().namedFilterArgs;
        builder.where('lastName', args.value);
      }
    };
  }
}
```

**Comment by fl0w** [comment]
@jordansexton sorry for not answering earlier, I must have viewed it in my sleep as I can't remember seeing a GH notification for your reply.

What koskimas purposed sounds like a good idea.

I mistakenly didn't "namespace" namedFilter-arguments in context, which at least once gave unexpected results/behaviour because of collisions.

**Comment by koskimas** [comment]
@jordansexton Can you live with a solution like the one I posted above?

**Comment by jordansexton** [comment]
Thanks! I'll definitely close this for now.

I would be interested in working in working on a PR for passing named arguments to filters. I think the context passing approach works, but it

  - is not self-documenting as a method signature would be
  - requires that the caller know the internal implementation of the named filter function
  - counts on multiple named filter functions that could be invoked in any application context not caring about the same arguments
  - not sure about this, but it seems like it would help with static analysis to pass known args

Is this something you'd entertain? If so, I'll dig into it further.
Thanks again for sharing your work and your help.

**Comment by koskimas** [comment]
@jordansexton I'm not sure this should be in the core. The eager stuff is already pretty complex beast and implementing this would make it even more complex. Have you considered using graphql?

The first problem is the `eager` method signature. `eager` already takes a second argument: a hash of named filters. The method would need to be called like this to pass arguments:

```js
Person
  .query()
  .eager('foo.bar(someFilter)', null, {
    someFilter: [1, 2]
  });
```

not that pretty.

**Comment by unhawkable** [comment]
@koskimas is there currently a way to use namedFilters with arguments, when calling applyFilter()? (similar to knex's modify())

**Comment by MrHassanTariq** [comment]
Hello @koskimas. i know its a bit old now. I am trying to pass arguments to namedFilters, but how i will passing these argumnets while using Model.query().eager(). Right now i am trying to pass it like
```
let result = await Training.query().eager(payload.eager, { IsActive: 1 })
```
and i have a namedFilter,IsActive, in Training Model just as you described above in your suggested solution.
But passing args like this says that IsActive modifer is not found.

**Comment by koskimas** [comment]
@MrHassanTariq See https://vincit.github.io/objection.js/recipes/modifiers.html
