### ISSUE TITLE
Join on clauses for queries / relations

### ISSUE THREAD

**Issue by jordansexton** [Vincit/objection.js#482]
Is there a way to add `join.on` clauses for a given relation or query? It's easy enough to join and then add `where` clauses, but I can't find a way to add `on` clauses to the join operation itself.

**Comment by koskimas** [comment]
You an add `on` clauses to plain joins like this:

```js
Person
  .query()
  .join('Pet', join => {
    join.on('Person.id', 'Pet.ownerId').on(...)
  });
```

What do you mean by adding `on` clauses to a relation?

**Comment by koskimas** [comment]
Check out [this file](https://github.com/Vincit/objection.js/blob/master/lib/queryBuilder/JoinBuilder.js) for available methods on the `join` builder.

**Comment by koskimas** [comment]
@jordansexton Was that what you were looking for? Can I close this?

**Comment by jordansexton** [comment]
Thanks for following up! I was writing up something to demonstrate the use case for this, as I thought a practical example would help. Essentially, I want to exclude related rows in the join clause rather than matching all related rows and then excluding them in the where clause. Aside from being more performant, this is practical for doing joins (esp. inner joins) against a related table where you want exclude items from the left table based on matching/not matching `on` clauses in the join.

As a simplified but concrete example, I have a `jobs` and `job_statuses` table. A job's status changes by inserting a new row into the `job_statuses`. The latest (by an auto-incrementing`serial` column) is the job's status; this allows viewing status changes over time by grabbing all the statuses related by a given `jobId`.

To find a queued job to run, I want to `joinRelation('statuses')` from jobs, but I want to only join where the latest status is `queued`, and do a self anti-join on the statuses table. The SQL I generate looks something like this:

```sql
SELECT "jobs".*
FROM "jobs"
     INNER JOIN "job_statuses" ON
                               "job_statuses"."jobId" = "jobs"."id" AND
                               "job_statuses"."status" = 'queued'
     LEFT JOIN "job_statuses"
               AS "job_statuses_2" ON
                                   "job_statuses_2"."jobId" = "job_statuses"."jobId" AND
                                   "job_statuses"."serial" < "job_statuses_2"."serial"
WHERE "job_statuses_2"."jobId" IS NULL
```

I hack this a bit right now by calling QueryBuilder methods on separate instances to perform joins, and then concating their `_operations` into a single QueryBuilder instance.

The API using `joinRelations` I'm imagining looks something like this:

```javascript
class Job extends Model {
    static get relationMappings () {
        return {
            statuses: {
                relation: HasManyRelation,
                modelClass: JobStatus,
                from: 'Job.id',
                to: 'JobStatus.jobId'
            }
        };
    }
}

class JobStatus extends Model {
    static get relationMappings () {
        return {
            job: {
                relation: BelongsToOneRelation,
                modelClass: Job,
                from: 'JobStatus.jobId',
                to: 'Job.id'
            },
            forJob: {
                relation: HasManyRelation,
                modelClass: this,
                from: `JobStatus.jobId`,
                to: `JobStatus.jobId`
            }
        };
    }
}

Job.query()
    .joinRelation('statuses', function (join) {
        join.on('status', raw('queued'));
    })
    .joinRelation('statuses.forJob', function (join) {
        join.on('statuses.serial', '<', 'related.serial');
    });
```

**Comment by jordansexton** [comment]
(Edited the builder code above to match the SQL.)

Essentially, I want to be able to customize the join (while still using the inferred relation's aliases, `on` clauses, and filters) rather than just add `where` clauses.

**Comment by koskimas** [comment]
That would be pretty difficult to implement. Currently both `statuses` and `statuses.forJob` join calls would create the same join and alias for `statuses` that would cause an "ambiguous identifier" error. There is no easy way to solve that because there is no way to test if an existing join equals the one we are creating in knex. We would need to build that mechanism to objection.

I think your are better off using plain knex joins for now.

By the way, have you actually measured the performance difference? Database engines have pretty amazing query optimizers that should be able to convert those `where`s to `on`s.

**Comment by jordansexton** [comment]
On further consideration, I agree. The implementation would be complicated and likely appear ambiguous or magical, even if the ambiguities could be resolved. Also, it's not much more code to use `join` with a function (you're essentially just saving the first `on` clause), and to use `copyFrom` for composing complex queries.
