### ISSUE TITLE
Full-Text Search?

### ISSUE THREAD

**Issue by mycahjay-nms** [Vincit/objection.js#485]
Hi there - Absolutely love using Objection.js! Switched from Sequelize, and I've never, ever looked back! 

Does Objection support full-text searches on pgsql or mysql? Any tips on implementing fulltext search on an existing postgres DB?

Thank you!

**Comment by elhigu** [comment]
Full text search in postgresql is quite limited, but should work ok if you limit on searching complete words. It doesn't really handle fuzzy searching etc. What kind of usecase you have for it? If indexed stuff are for example text docuements, it might be good enoug, but if you want to use it to search user names etc. it might not be as good as you wish...

Anyways there is no special support for full text search in knex nor in objection.js. So you would need to write raw queries... Would be interesting to write plugin for that stuff though.

**Comment by devinivy** [comment]
It is pretty simple with raw queries.  Say you have an index on a column `searchview` of tsvectors.  Then you can search that (in postgres) with,
```js
YourModel.query().whereRaw('searchview @@ plainto_tsquery(?)', [term])
```

**Comment by koskimas** [comment]
As @elhigu mentioned there is no special support for full text search and no plans to add it. I'll close this for now. Feel free to continue the conversation here though.
