### ISSUE TITLE
Virtual attributes are still written to the database

### ISSUE THREAD

**Issue by jordansexton** [Vincit/objection.js#486]
When calling `insert`/`update`/`patch` with properties, even if a property is included in `virtualAttributes`, it is not excluded by `$formatDatabaseJson`.

```javascript
class User extends Model {
    static get virtualAttributes () {
        return ['password'];
    }
}

await User.query().insert({ password: 'foo' });
// Error: insert into "users" ("password") values ($1) returning "id" - column "password" of relation "users" does not exist
```

Expected behavior (to me) is that marked virtual attributes are truly virtual — never written to the database — even if they are in the schema, are enumerable, have setters, etc.

**Comment by koskimas** [comment]
How did you implement the virtual attribute? As a getter, a function or getter + setter? Please provide a real example.

**Comment by jordansexton** [comment]
As far as I can tell, it doesn't matter; I tried several implementations (with and without the virtual attribute listed in the JSON schema, with and without a setter). 

```javascript
const knex = require('@/config/database/knex');

const { Model } = require('objection');

class User extends Model {
    static get tableName () {
        return 'users';
    }

    static get virtualAttributes () {
        return ['password'];
    }
}

User.knex(knex);

class UserWithJsonSchema extends User {
    static get jsonSchema () {
        return {
            type:       'object',
            properties: {
                password: {
                    type: 'string'
                }
            }
        };
    }
}

class UserWithGetter extends User {
    get password () {
        return super.password;
    }
}


class UserWithGetterSetter extends User {
    get password () {
        return super.password;
    }

    set password (password) {
        super.password = password;
    }
}

(async function () {
    for (const UserClass of [User, UserWithJsonSchema, UserWithGetter, UserWithGetterSetter]) {
        try {
            await UserClass.query().insert({ password: 'foo' });
        }
        catch (error) {
            console.log(error);
        }
    }
})();
```

In our actual application, I work around this by doing

```javascript
$formatDatabaseJson (json: Object): JSONObject {
    const { virtualAttributes }: { virtualAttributes: string[] } = this.constructor;
    if (virtualAttributes.length !== 0) {
        json = omit(json, virtualAttributes);
    }
    return super.$formatDatabaseJson(json);
}
```

**Comment by jordansexton** [comment]
Actually, the UserWithGetter doesn't pass it through. But if it has a setter, or appears in the schema, it fails.

**Comment by jordansexton** [comment]
(This is a problem for us, because we put virtuals in our JSON schemas. This is necessary because we enforce `additionalProperties: false`, which is how I originally encountered it).

**Comment by jordansexton** [comment]
I guess what I'm wondering is, why should it matter if a virtual has a setter? A locally writeable virtual should still be treated as a virtual as far as the database is concerned, right? If not, it's not really "virtual", is it?

**Comment by koskimas** [comment]
There should be no way to define a virtual property and have an actual property at the same time. What you are doing is really funky. Try this:

```js
class X {
  set a(a) {
    super.a = a;
    console.log('setter was called');
  }
}

const x = new X;
x.a = 100; // prints 'setter was called'
x.a = 200; // Doesn't print anything because the setter was replaced with an actual property.
```

**Comment by jordansexton** [comment]
Haha you are right. I don't know what I was doing. I get/set `$properties` elsewhere, so I don't know how I missed this...
