### ISSUE TITLE
Pass context (transaction) to loadRelated?

### ISSUE THREAD

**Issue by jordansexton** [Vincit/objection.js#488]
The [current implementation](https://github.com/Vincit/objection.js/blob/d2e40624a1ec6d4368f38e5fdd779a37bf5bc479/lib/model/Model.js#L540-L547) calls `query()` with no context argument. Is there a way to execute `loadRelated`/`$loadRelated` within a transaction?

**Comment by koskimas** [comment]
There is no easy way. You can use `bindTransaction`:

```js
const person = await Person
  .bindTransaction(trx)
  .query()
  .findOne({name: 'Jennifer'});

// `person` is now bound to the transaction and all queries
// started through it will be executed in the transaction.
await person.$loadRelated('[pets, movies]');
```

I'll add the transaction argument.

**Comment by jordansexton** [comment]
Got it. Thanks for your help!

**Comment by jordansexton** [comment]
You rock, thanks!
