### ISSUE TITLE
withSchema not working?

### ISSUE THREAD

**Issue by bs1180** [Vincit/objection.js#49]
Thanks for a great tool.

I have my models up and working successfully, except for the withSchema method. A query like this:
```User.query().withSchema('shared')``` throws a TypeError ```withSchema is not a function```.
This works fine if I use knex directly (eg. ``` knex('users').select().withSchema('shared')```)

Any thoughts?

**Comment by koskimas** [comment]
Glad you like it!

Yeah, that method is still missing in 0.3.0, but will be available in 0.3.1. It is actually already there in the master branch, so as a temporary fix, you can point to the github commit in your package.json. I will publish 0.3.1 during next week.

**Comment by bs1180** [comment]
Ah I see, thanks for the quick response.
