### ISSUE TITLE
Merged user context is not passed to query / $relatedQuery using same context

### ISSUE THREAD

**Issue by jordansexton** [Vincit/objection.js#491]
This is a toy example, but the issue itself seems pretty simple.

```javascript
class User extends Model {
    async $afterInsert (context) {
        console.log(context.someValue); // "exists"

        await this.$relatedQuery('status', context).insert({ status: 'active' });
    }
}

class Status extends Model {
    async $afterInsert (context) {
        console.log(context.someValue); // undefined
    }
}

await User.query().mergeContext({ someValue: 'exists' }).insert({});
```

If changed to

```javascript
await this.$relatedQuery('status', context).mergeContext(context).insert({ status: 'active' });
```

it works as I would expect. My understanding is that the whole context would be passed, but instead, `query` and `$relatedQuery` just call `transacting` with it, and don't keep the user context.

Is this behavior by design? I think my lack of understanding here is due to how context objects and transactions are used somewhat interchangeably.

**Comment by koskimas** [comment]
The last argument you can pass to `query`, `$relatedQuery` etc. is a knex instance or a transaction object. That's not the same thing as query context. You can use the context method:

```js
class User extends Model {
    async $afterInsert (context) {
        console.log(context.someValue); // "exists"

        await this.$relatedQuery('status').context(context).insert({ status: 'active' });
    }
}
```

If you need to use the same transaction, you also need to do this:

```js
```js
class User extends Model {
    async $afterInsert (context) {
        console.log(context.someValue); // "exists"

        await this.$relatedQuery('status', context.transaction).context(context).insert({ status: 'active' });
    }
}
```
```
