### ISSUE TITLE
upsertGraph gets upset when id field isn't named 'id'

### ISSUE THREAD

**Issue by venkatperi** [Vincit/objection.js#492]
upsertGraph fails if the primary key isn't named `id`.

```
Person
  .query()
  .upsertGraph({
    // primary key is `someId`
    someId: 1,
    firstName: 'Jonnifer',
...
```

**Comment by jordansexton** [comment]
`upsertGraph` appears to whatever is defined as the model's `idColumn`: https://github.com/Vincit/objection.js/blob/1e61de996947d5494aa5ad2cf755fb5676cf9297/lib/queryBuilder/graphUpserter/UpsertGraph.js#L48-L57

Have you tried setting it yet? http://vincit.github.io/objection.js/#idcolumn

**Comment by koskimas** [comment]
@venkatperi @jordansexton Is right. You need to tell objection each model's primary key using the `idColumn` field.

**Comment by venkatperi** [comment]
That makes sense. I saw it was using `idColumn` but didn't realize it needed to be set. Thanks!
