### ISSUE TITLE
Skipping an update when the model hasn't changed

### ISSUE THREAD

**Issue by jordansexton** [Vincit/objection.js#493]
I'd like to be able to skip (not error on, but not actually perform, and not run the `$afterUpdate` handler on) an `update` or `patch` operation on a model if it hasn't changed. A logical place to check might to be in the `$beforeUpdate` method, by diffing `this` against `options.old`. However, the only way to stop the update from there is to throw an error. I can do this, but I'm not quite sure where I'd catch it. I recognize that change tracking and all that is outside the scope of Objection, but do you have any pointers on how I might do this? Monkey patching or overriding the `UpdateOperation` class is the only thing that I can see working offhand.

**Comment by jordansexton** [comment]
On closer inspection, it looks like monkey patching `InstanceUpdateOperation` is the only mechanism I can find (or subclassing it and also overriding `$query` to return the subclass).

**Comment by koskimas** [comment]
Maybe you can override `QueryBuilder#execute()`:

```js
class SkipUpdateError extends Error {}

class CustomQueryBuilder extends Model.QueryBuilder {
  execute() {
    return super.execute().catch(err => {
      if (err instanceof SkipUpdateError) {
        // Zero rows updated.
        return 0;
      } else {
        return Promise.reject(err);
      }
    });
  }
}

class BaseModel extends Model {
  static get QueryBuilder() {
    return CustomQueryBuilder;
  }

  $beforeUpdate(ctx) {
    if (!hasChanges(this, ctx) {
      throw new SkipUpdateError();
    }
  }
}
```

**Comment by jordansexton** [comment]
Pretty elegant, thanks!
