### ISSUE TITLE
Implement shorthand method lit()

### ISSUE THREAD

**Issue by elhigu** [Vincit/objection.js#498]
Method like ref() and raw(), but this one just allows people to choose how certain literal is casted in DB side. So this is mostly to prevent need for writing `raw('?::text', [val]) and can help with more complex cases where JS literal -> SQL is ambiguous, like for example how an arrays should be presented.

Original issue https://github.com/Vincit/objection.js/issues/275

Some related knex issues:
https://github.com/tgriesser/knex/issues/791
https://github.com/tgriesser/knex/issues/1537
https://github.com/tgriesser/knex/issues/1733

**Comment by koskimas** [comment]
Already implemented.
