### ISSUE TITLE
Typings for raw(), ref() and lit()

### ISSUE THREAD

**Issue by elhigu** [Vincit/objection.js#499]
Currently these has not been exposed through typescript bindings.

**Comment by koskimas** [comment]
We should add the `raw`, `ref` and `lit` methods to the main object and those should return `RawBuilder`, `ReferenceBuilder` and `LiteralBuilder` instances respectively. There are corresponding javascript classes for those.

I started writing the typings, but I don't know how I should go about it. The typings are a bit confusing to me:

There are types like

```ts
type ColumnName<T>
type Value
```

that list all possible column name and value types, but those are not used in all places. Most methods like `where` have a separate typing for each signature and types are listed there in-place. `ColumnName` and `Value` types are not used there for some reason. Is there a reason for this or should we start using the `ColumnName` and `Value` types everywhere (where they can)?

@mceachen Could you explain this to me?

**Comment by mceachen** [comment]
If those types aren't used in places you think they're applicable, it's most likely a mistake. Do you want me to take a swing at adding those methods? Do you want to share what you've got so far?

Thanks again for objection!

**Comment by koskimas** [comment]
> Do you want me to take a swing at adding those methods?
That would be great! Thank you! I have nothing so far 😄

**Comment by suubee** [comment]
How does one import ref() currently with TypeScript without getting the dreaded``` "no exported member 'ref'"```

**Comment by mceachen** [comment]
@suubee you can use bracket notation, like ```.query()["lit"]```, but that's the stuff of monsters. I'll do this now.

**Comment by mceachen** [comment]
@elhigu , @koskimas if you guys could sketch out examples (here or in a gist or in a pr) that'd be helpful.

**Comment by mceachen** [comment]
Also, in the example

```js
Person.query()
  .select(raw('coalesce(sum(??), 0) as ??', ['age', 'childAgeSum']))
  .where(raw(`?? || ' ' || ??`, 'firstName', 'lastName'), 'Arnold Schwarzenegger')
  .orderBy(objection.raw('random()'));
```

shouldn't the bound params in the where clause be in an array?

```
  .where(raw(`?? || ' ' || ??`, ['firstName', 'lastName']), 'Arnold Schwarzenegger')
```

**Comment by mceachen** [comment]
@suubee unfortunately, `.ref` and `.lit` are a bit more involved. You can temporarily add the type to your project with namespace merging, though: https://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by mceachen** [comment]
@elhigu @koskimas if you guys could provide examples of `.ref` and `.lit` that'd be a big help.

**Comment by elhigu** [comment]
@suubee I've been importing them with plain require and used as `any`
 type.

```js
const { ref, lit, raw } = require('objection');
```

@mceachen Do you mean examples like this: http://vincit.github.io/objection.js/#ref75 ?

**Comment by timothyallan** [comment]
I'd been trying 'import', not 'require' with no luck. Will give require a go.

**Comment by koskimas** [comment]
@mceachen Here's more examples and documentation https://github.com/Vincit/objection.js/blob/master/doc/includes/API.md#global-query-building-helpers

**Comment by mceachen** [comment]
fwiw I don't see `.as()` on `LiteralBuilder.js` but it's there in the docs.

@koskimas do you want me to update my PR with all three additions, or would you like two smaller PRs?

**Comment by mceachen** [comment]
Also, there are a number of methods on `ReferenceBuilder` that aren't in the docs, like `.reference`, `.column`, `.tableName`, and `.expression`. Do you want those publicly exposed by the typings?

**Comment by koskimas** [comment]
Nope, only the documented methods and properties are public.

**Comment by mceachen** [comment]
OK, pushed the PR, reviews appreciated!
