### ISSUE TITLE
patch(obj).returning('*') returns 1

### ISSUE THREAD

**Issue by beworker** [Vincit/objection.js#503]
I am trying to `patch()` an object and return the updated row with all properties as following
```
const season = await Season.query()
    .patch({id: 20, title: 'Updated title'})
    .returning('*')
```

but instead of an object I receive `1`.

When I rewrite query into
```
const season = await Season.query()
    .patchAndFetchById(20, {id: 20, title: 'Updated title'})
```
then I receive the updated object with all properties.

Does the `patch()` + `returning()` query works as expected or is it rather a bug?

**Comment by fl0w** [comment]
What database are you using?

**Comment by beworker** [comment]
MySql 5.7.11

**Comment by fl0w** [comment]
Yea, AFAIK only PG is supported by the returning statement. In this case, patch returns number of rows updated. This is expected, and thus not a bug.

**Comment by beworker** [comment]
I see. Because the objection query corresponds to the SQL query and there is no `returning` keyword in MySQL, the query just returns the number of updated rows, which is `1`, correct?

Do you know whether there is a way to enforce objection (knex) to not silently ignore `returning()` for MySQL but add it to the query, that the query can gracefully fail with MySQL syntax error?

**Comment by fl0w** [comment]
> Because the objection's query corresponds to the SQL query and there is no returning keyword in MySQL, the query just returns the number of updated rows, which is 1 in my case. Correct?

Correct.

> Do you know whether there is a way to enforce objection (knex) to not silently ignore returning() for MySQL but add it to the query, that the query can gracefully fail with MySQL syntax error?

@beworker I probably technically possible, though there's probably reasons why not to do it. I'm not sure. Though in objection for your own use, you can overload and throw you if you want. Not sure how valuable it is for you, as you now know about it.

```js
class MyQueryBuilder extends objection.QueryBuilder {
  returning () {
    throw new Error('nope')
  }
}
```

**Comment by beworker** [comment]
@fl0w Thanks you very much for helping, Martin!

**Comment by elhigu** [comment]
@beworker If someone adds check to `knex` for throwing an exception if one tries to use `.returning()` with invalid dialect I'm happy to review and merge it, however I would be even more happy to have more complete set of checks that API is used correctly.
