### ISSUE TITLE
patchAndFetchById() returns a String-value for decimal type

### ISSUE THREAD

**Issue by beworker** [Vincit/objection.js#504]
I use the following simple code
```
if (episode.id) {
    return Episode.query().patchAndFetchById(episode.id, episode)
}
return Episode.query().insert(episode)
```
* when `insert()` path is executed, resulting `episode.size` contains a number value (`"size": 12.34`), which is OK
* when `patchAndFetchById()` path is executed, resulting `episode.size` contains a String value (`"size": "12.34"`), while expected value should be a number (NOT OK).

In both cases `size` value given in the model is 12.34 (a number). The `size` field is a `DECIMAL(8,2)` in database and a `number` in JSON schema. This seems to be a bug in `patchAndFetchById()`, right?

Objection 0.8.8, MySQL 5.7.11

**Comment by koskimas** [comment]
When you insert the value, the returned object does not come from the database. Only the id is returned from the db. The object you inspect is the one you insert. That causes the difference between the methods.

Objection does no type mapping whatsoever by default. The return types are totally up to the db driver knex uses. The db driver probably has some way to map types. Maybe this helps https://github.com/mysqljs/mysql#type-casting.

**Comment by beworker** [comment]
@koskimas Thanks for looking into! Your link helped. Decimal is mapped to String and after migration to `float` everything started to work as expected. Sorry for the noise.

**Comment by fl0w** [comment]
Off topic: This is why I switched from MySQL :)
