### ISSUE TITLE
Override QueryBuilderContext

### ISSUE THREAD

**Issue by jordansexton** [Vincit/objection.js#506]
I'd like to be able to override the QueryBuilderContext implementation. In our case, this is to add custom methods (for example, we have a depth-based context that increments in `childQueryOf` to help with filtering relations based on permissions), and we change the `clone` implementation so that the internal `userContext` is cloned as well (not shared between instances).

The easiest way I can see of doing this is [changing these two lines](https://github.com/Vincit/objection.js/blob/269a9dd15f5956bed65f5d353cd7277b2f6d8493/lib/queryBuilder/QueryBuilder.js#L34-L35):

```javascript
  constructor(modelClass) {
    super(modelClass.knex(), QueryBuilderContext);
```

to something like

```javascript
constructor(modelClass, contextClass) {
    super(modelClass.knex(), contextClass || QueryBuilderContext);
```

I can see how the way above might be brittle, and it's always questionable adding new constructor params. We're doing this in a fork right now, but is this something you might plan to expose in any way?

**Comment by koskimas** [comment]
The `QueryBuilderContext` is an implementation detail I don't want to expose. I could add `QueryBuilerContext` constructor as a static property of `QueryBuilder` so that it could be overridden and you could implement your feature, but I don't want to document that either. If I do this, you should be aware that it can change at any point (it probably won't, but I reserve the right to change it).

**Comment by jordansexton** [comment]
Gotcha, okay. I think that's probably a better approach anyway than as a constructor arg.

**Comment by koskimas** [comment]
Sorry, actually the thing I suggested isn't possible in javascript. The constructor cannot be accessed before `super` constructor call.

**Comment by jordansexton** [comment]
`new.target` might be helpful here

**Comment by jordansexton** [comment]
e.g. `new.target.QueryBuilderContext` should be available before calling super with `this`

Alternatively, `QueryBuilderBase` can call `this.constructor.QueryBuilderContext`.

**Comment by koskimas** [comment]
Thanks for the tips! I don't think `new.target` is available in node 4.0.0, but I'll implement your second suggestion.

**Comment by jordansexton** [comment]
Thanks for doing this! I really appreciate this library and your work. I can't tell you how much this has improved our API design in just a few weeks since switching from Bookshelf.

**Comment by koskimas** [comment]
Thank you! Comments like this are the reason I like to do this ❤️
