### ISSUE TITLE
Adding 3rd party module to docs

### ISSUE THREAD

**Issue by jeff3yan** [Vincit/objection.js#507]
I've created a module ([objection-filter](https://github.com/tandg-digital/objection-filter)) which could be useful to include in the docs.

Would be great to have it in there!

**Comment by jeff3yan** [comment]
I was originally using objection-find, but really wanted the ability to filter based on related models.

For example, you have some models set up such that:
`Customer` belongsTo `Branch` belongsTo `City` belongsTo `Country`

Then you want to search all `Customers` which belong to a `Country` that starts with _"A"_.

The module will do the required joins and filter then only return the root model (`Customer`).

**Comment by fl0w** [comment]
I think the unwritten practice is to just make a PR with the added module to docs, see https://github.com/Vincit/objection.js/pull/500

**Comment by koskimas** [comment]
@jeff3yan Could you provide a short description for the documentation? See the plugin descriptions for reference.

**Comment by jeff3yan** [comment]
How about:
API filtering on data and related models
