### ISSUE TITLE
InsertGraph retuning id on a table that doesn't have id

### ISSUE THREAD

**Issue by Toni-B** [Vincit/objection.js#509]
I have the following models and query

```
export default class Region extends Model {
  static tableName = 'domain.region';

  static relationMappings = {
    translations: {
      relation: Model.HasManyRelation,
      modelClass: RegionTranslations,
      join: {
        from: 'domain.region.id',
        to: 'domain.region_translations.region_id'
      }
    }
  }
}

export default class RegionTranslations extends Model {
  static tableName = 'domain.region_translations';

  static relationMappings = {
    region: {
      relation: Model.BelongsToOneRelation,
      modelClass: `${__dirname}/region`,
      join: {
        from: 'domain.region_translations.region_id',
        to: 'domain.region.id'
      }
    }
  }
};

const region = { ..., translations: [...] };

return objection.transaction(Region.knex(), async (trx) => {
  const result = await Region.query(trx).insertGraph(region);
  return result;
});
```

The problem is that on the `domain.region_translations` insert, a `returning "id"` is added and the table does not have an id column, which of course fails the whole query.

These are the queries generated:

```
insert into "domain"."region" ("active", "banner", "country_id", "icon") values (?, ?, ?, ?) returning "id"
```
```
insert into "domain"."region_translations" ("description", "lang_id", "name", "region_id", "slug") values (?, ?, ?, ?, ?), (?, ?, ?, ?, ?) returning "id"
```

Is there a way I can avoid this and specify a returning column on the child table?

**Comment by koskimas** [comment]
Each objection model must have an id column. You can specify a custom column using the static `idColumn` Model property (see the docs). If there is no single column that uniquely identifies a row, you can specify a composite key by setting and array of column names for `idColumn`. If your table really has not way to identify rows (probably not a good idea) you can simply set any column to `idColumn`, but some parts of objection will break.

**Comment by Toni-B** [comment]
Tnks! ID did the trick. I completely missed the idColumn in the docs

**Comment by koskimas** [comment]
👍
