### ISSUE TITLE
withSchema and eager joins

### ISSUE THREAD

**Issue by bs1180** [Vincit/objection.js#51]
Thanks for the new version. While withSchema works on solo queries, is there a way to pass it through to subsequent eager joins?

Eg. ```User.query().withSchema('1').eager('tasks')``` correctly uses schema 1 when selecting all users, but the second query to get the tasks doesn't have it. I realise that automatically using the same schema might not always be desired though, if you're doing some sort of cross-schema query. Is there a way to set it easily?

**Comment by bs1180** [comment]
Ok, I'm working round it for now like this: 
```User.query()
  .withSchema("1")
  .eager('tasks(schema)', {
    schema: function (builder) {
      builder.withSchema("1");
    }
})```
Obviously a bit clunky, but it works :)

**Comment by koskimas** [comment]
No, there isn't an easier way. You can set a

```js
filter: function (builder) {
  builder.withSchema("1");
}
```

property for the relation in `relationMappings` but that would always use the same schema for the relation and that probably isn't what you want.

What do you mean "stops the allowEager"? It doesn't work if you have the filter in place? How does it fail? It should work...

**Comment by bs1180** [comment]
Cheers. Sorry, I didn't explain that very clearly - I had been piping the eager values directly into the query from my route handler (like in the express example):
```
User.query()
.allowEager(['tasks', 'notes'])
.eager(request.query.eager)
```
I don't want the API call to have knowledge of the schema system (eg. not using ```/users?eager=tasks(schema)```) but I can add a helper utility to take care of parsing the request params, so that's not really an issue.

Thanks again for the quick responses :+1:

**Comment by koskimas** [comment]
No problem, I'm glad to help. This way the library gets better. Keep the issues coming!

Many of the query builder methods actually execute multiple queries, and there is currently no way to pass data from the original query to the "internal" queries. What do you think about something like this:

```js
User.query()
  .withSchema("1")
  .context({schema: "1"})
  .eager('tasks');
```

then the context would be available everywhere through `builder.context()`, even for the "internal" queries. You could for example add a filter for the relations:

```js
filter: function (builder) {
  if (builder.context().schema) {
    builder.withSchema(builder.context().schema);
  }
}
```

Or better yet, implement your own QueryBuilder:

```js
class MySuperSpecialQueryBuilder extends objection.QueryBuilder {
  constructor() {
    super();
    // Add a withSchema call on build time if the schema is specified
    // in the query context.
    this.onBuild(function (builder) {
      if (builder.context().schema) {
        builder.withSchema(builder.context().schema);
      }
    });
  }
}

// This puts our own query builder into use everywhere.
objection.Model.QueryBuilder = MySuperSpecialQueryBuilder;
objection.Model.RelatedQueryBuilder = MySuperSpecialQueryBuilder;
```

Do you think you would use a feature like this, or is this too complicated for such a simple problem? This would make many other things possible too.

**Comment by bs1180** [comment]
Access to a context object would be helpful and I can think of several other uses - eg. implementing fine grained permissions, or ensuring audit trails. So yes please!

Subclassing the query builder would also be an option, but yes, a bit complicated.

**Comment by bs1180** [comment]
Hmm, just ran into this same issue but on a many-to-many insert.

**Comment by koskimas** [comment]
Yeah, many-to-many insert creates two inserts: the actual row and the join row. Ugly workaround for until we come up with a solution would be to insert the two rows separately.

**Comment by koskimas** [comment]
The `QueryBuilder` class has hooks. You can register methods to be ran in different phases of the query execution using methods `runBefore`, `onBuild`, `runAfter` etc but those are only ran for the query at hand and not for any possible other queries.

What if we add those hooks also to the context object so that you can write something like this:

```js
User.query()
  .context({
    onBuild: function (builder) {
      builder.withSchema("1");
    }
  })
  .eager('tasks');
```

The `context.onBuild` method would be ran for all started queries. This would solve the insert case also. That is still not that pretty, but now you can for example implement your own query builder that has some `allQueriesWithSchema` method that does that.

How does this sound?

**Comment by bs1180** [comment]
I'm using ES7 ```await/async``` for the first time and so the workaround is not too bad.

I've had a look at subclassing the querybuilder and it seems straightforward, so that looks like the way to go. Accessing the hooks from the internal query is neat though.

**Comment by koskimas** [comment]
Ok, great. You still need the `context` feature to solve the problem by subclassing the querybuilder. I'm working on it and it seems pretty easy to implement. I'll keep you updated on the progress.

**Comment by bs1180** [comment]
Fab, looking forward to it.

**Comment by koskimas** [comment]
I pushed the first version of the query context feature to a `query-context` branch, if you want to try it out already. The simplest way to solve your problem is now this:

```js
User.query()
  .context({
    onBuild: function (builder) {
      builder.withSchema("1");
    }
  })
  .eager('tasks');
```

and this

```js
someModel
  .$relatedQuery('someManyToManyRelation')
  .insert(something)
  .context({
    onBuild: function (builder) {
      builder.withSchema("1");
    }
  });
```

But a cleaner way to do this is probably by subclassing QueryBuilder like discussed above.

The context can be accessed using `queryBuilder.context()` for each query that is started by a query builder for which the context was given. The context is also passed to the `$beforeInsert`, `$afterInsert`, `$beforeUpdate` and `$afterUpdate` model hooks.

The change was quite large, so there may still be bugs in this early version.

**Comment by bs1180** [comment]
:heart: Thanks for doing it so quick! 

I tried using it as part of my queries like this
```
.context({
    onBuild: function (builder) {
      builder.withSchema("1");
    }
  })
``` 
and it worked flawlessly. 

However, when I try and subclass my QueryBuilder it loses the knex binding:
```
import { Model, QueryBuilder } from 'objection'

console.log(Model.query()) // knex exists - the Model.knex(...connection...) occurs elsewhere.

class TenantedQueryBuilder extends QueryBuilder {
  constructor() {
    super();
    this.onBuild(function (builder) {
      if (builder.context().schema) {
        builder.withSchema(builder.context().schema);
      }
    });
  }
}

Model.QueryBuilder = TenantedQueryBuilder;
Model.RelatedQueryBuilder = TenantedQueryBuilder;

console.log(Model.query()) // throws with a TypeError - Cannot read property 'knex' of undefined
```

**Comment by koskimas** [comment]
You need to pass the constructor arguments to `super`

```js
class TenantedQueryBuilder extends QueryBuilder {
  constructor(...args) {
    super(...args);
    this.onBuild(function (builder) {
      if (builder.context().schema) {
        builder.withSchema(builder.context().schema);
      }
    });
  }
}
```

**Comment by bs1180** [comment]
:+1: :+1: :+1: 
Thanks, worked immediately. This really makes building multi-tenant apps significantly easier, and is much more straightforward than either Sequelize or Bookshelf. I'll keep implementing and let you know if I encounter any issues!

**Comment by koskimas** [comment]
Excellent! I think this will be a useful feature for many purposes.

**Comment by remidewitte** [comment]
:thumbsup:

**Comment by koskimas** [comment]
I'll soon release the 0.5.0-alpha.0 version that has an update `withSchema` method that automatically passes the schema to all internal queries. You no longer need to use the `TenantedQueryBuilder` subclass.

You can install it using npm install objection@next

**Comment by bs1180** [comment]
Thanks again for this. Objection is a core part of a product I'm developing and it's been a joy to use. I look forward to the future development as well!
