### ISSUE TITLE
Issue with typings for page/range and postgres 'returning' technique

### ISSUE THREAD

**Issue by akramali86** [Vincit/objection.js#510]
Objection Version: ^0.8.8
Node version: v6.11.1
Typescript Version: ^2.5.2
Database Client: Postgres

Hi, i've been using objection with typescript fairly successfully. However have had a few issues with the typings which i would like to report.

The typescript compiler seems to think that the below query returns an array of Ingredients

```typescript
// Typescript thinks result === Ingredent[], but the result is actually {total: number, results: Ingredient[]}
const result = await Ingredient
        .query()
        .page(options.page, options.limit);
``` 

I'm also unable to use the postgres 'returning' techniques as described in the documentation when patching/updating. As the typescript compiler seem to think the return type is a number. I understand there may be no way to fix as this is only an issue when using postgres.

```typescript
// Typescript thinks ingredient === number
const ingredient = await Ingredient
            .query()
            .where('id', id)
            .patch(data)
            .returning('*')
            .first()
```

I'm managed to get around the above issues by overwriting some of the typings with some less then ideal typings
```typescript
declare module 'objection' {
    interface QueryBuilderBase<T> extends QueryInterface<T> {
       // Seems a bit hacky
        patch(modelOrObject: Partial<T>): QueryBuilderSingle<T>;
        page(page: number, pageSize: number): QueryBuilderPaged<T>;
    }

    export interface QueryBuilderPaged<T> extends QueryBuilderBase<T>, Promise<{total: number, results: T[]}> { }
}
```
The typings also do not seem have any reference to the knex modify operator.

Thanks

**Comment by koskimas** [comment]
Thank you for for creating the issue! I will fix these for the next release.
