### ISSUE TITLE
Feature based folder structure (vs role based)

### ISSUE THREAD

**Issue by jeff3yan** [Vincit/objection.js#515]
I'm following a [role based folder design pattern](https://blog.risingstack.com/node-hero-node-js-project-structure-tutorial/) right now, with all objection.js models in a single folder.

This looks something like:
```
├── controllers
|   ├── product.js
|   └── user.js
├── models
|   ├── product.js
|   └── user.js
 ```
 
 This works well with the objection.js static `modelPaths()` function returning `[__dirname]`.
 
 I want to move to more of a feature based folder structure:
 
 ```
 ├── product
|   ├── controller.js
|   ├── model.s
├── user
|   ├── controller.js
|   ├── model.js
 ```
 
 With this folder structure, does `modelPaths` need to return an array of every top level _feature/folder_?

**Comment by koskimas** [comment]
Yes it does. Objection doesn't try to search subfolders nor does `modelPaths` allow glob patters such as `features/*`. Unfortunately you need to list all folders. You can do something like this though:

```js
static get modelPaths() {
  return fs.readdirSync(path.join('__dirname', '..', 'features'))
}
```

**Comment by koskimas** [comment]
Were you able to solve this one? Can I close this?

**Comment by jeff3yan** [comment]
Yes returning an array worked fine, thanks :)

**Comment by fl0w** [comment]
Late, but what I do is set `modelPath` to app/ root, from where all feature-directories branch. Then in any given model I do `modelClass: 'feature-dir/Model'`.
