### ISSUE TITLE
Unhandled rejection errors when builder generates multiple queries

### ISSUE THREAD

**Issue by mattboutet** [Vincit/objection.js#516]
The problem pops up when executing a query against a nonexistent table. Basic queries fail just as I'd expect, but queries that end up being more than one DB roundtrip, e.g. `Model.query().range(start, end).asCallback((err, found) => {});` which generates a count and a plain select will generate two rejected promises, which causes problems. One of those rejected promises will come through as err and I can handle it, but the other one is unhandled and ends up showing up as an Unhandled rejection Error -- `select count(*) as "count" from (select "foo".* from "foo") as "temp" - SQLITE_ERROR: no such table: foo at Error (native)`

I've created a small runkit example here: https://runkit.com/mattboutet/59ba7e3fda90790012ff4ae7

**Comment by koskimas** [comment]
For some reason github is not showing that I closed this from this https://github.com/Vincit/objection.js/commit/0cf28e8406144bca8458168838f0314768932719
