### ISSUE TITLE
How to get errors

### ISSUE THREAD

**Issue by chamini2** [Vincit/objection.js#518]
I want to catch certain errors like `duplicate key value violates unique constraint` and I am not sure how this error would look from Objection.js. What class are the DB errors?

**Comment by koskimas** [comment]
Objection doesn't touch the db errors. It simply passes through anything that knex throws (which passes through anything the db clients throw). So basically you have to consult the db client docs to see what kind of objects get thrown.

This is something I would like to change though. See [this issue](https://github.com/Vincit/objection.js/issues/501)
