### ISSUE TITLE
Can't pass .context({}) with .$query()

### ISSUE THREAD

**Issue by pwalczyszyn** [Vincit/objection.js#519]
My `$afterUpdate()` function doesn't receive context object passed via `.$query().context({})'.

Example:

```js
myModelInstance.$query().context({myVal: true}).patch({...});
```

```js
class MyModel extends Model {

  $afterUpdate(context) {
    console.log(context.myVal); // undefined
  }

}
```

**Comment by pwalczyszyn** [comment]
Just realised that in case of $afterUpdate context is passed as second argument. This is a bit confusing. Closing this issue.

**Comment by koskimas** [comment]
It's not confusing if you think that the context is always passed as the last argument. The context feature was added after some of the hooks already had arguments.

**Comment by pwalczyszyn** [comment]
Confusing is the docs in the second example here: http://vincit.github.io/objection.js/#_s_afterupdate

It has following line:
```js
$afterUpdate(queryContext) {
```

**Comment by koskimas** [comment]
So you found that I posted the response right 😉 Or why didin't you mention that in the previous mesagge. I'll fix that for the next release.

**Comment by pwalczyszyn** [comment]
Sorry, yes your previous response is right, if you think in terms of having context always as last argument ;) But it kinda confused me at first because I expected it to be first argument (without reading docs), and than I looked into the docs and I got double confused.

But I guess if docs will be fix all will be good ;)

**Comment by mona-chen** [comment]
This is 2024 and i still spent an entire day figuring this out, even though it was written here it passed as a second argument in patch or update operation, i still went on looking at the wrong direction, apparently this statement is correct when getting the value of context within $beforeUpdate in this case your context value will be available here 

```js
    async $beforeUpdate(_, queryContext) { 
    // your logic here
    }
   ```
   
  and not in the order the context was invoked/passed as in Model.query().context({}) or Model.query.patch().context({})
  
  i do agree it confusing maybe a better documentation should be done in regards to this.
