### ISSUE TITLE
Unable to fetch many to many: modelClass not defined

### ISSUE THREAD

**Issue by erosenberg** [Vincit/objection.js#521]
I have a column in my table called `Position`, which has a many-to-many relationship with `Users`.

Here are my relevant files:

**Position.js**
```
import _ from 'lodash';
import { Model } from 'objection';
import User from './User';

export default class Position extends Model {
  static tableName = 'position';

  static jsonSchema = {
    type: 'object',
    properties: {
      id: {
        type: 'integer',
      },
      title: {
        type: 'string',
      },
    },
  }

  static relationMappings = {
    user: {
      relation: Model.ManyToManyRelation,
      modelClass: User,
      join: {
        from: 'position.id',
        through: {
          from: 'user_position.user_id',
          to: 'user_position.position_id',
        },
        to: 'user.id',
      },
    }
}
```

**User.js**
```
import _ from 'lodash';
import { Model } from 'objection';
import { formatTableName, parseTableName } from '../utils/decoration';
import Position from './Position';

export default class User extends Model {
  static tableName = 'user';

  static jsonSchema = {
    type: 'object',
    properties: {
      id: {
        type: 'integer',
      },
      firstName: {
        type: 'string',
        minLength: 1,
        maxLength: 30,
      },
      lastName: {
        type: 'string',
        minLength: 1,
        maxLength: 30,
      },
      birthday: {
        type: 'date',
      },
    },
  }

  static relationMappings = {
    positions: {
      relation: Model.ManyToManyRelation,
      modelClass: Position,
      join: {
        from: 'user.id',
        through: {
          from: 'user_position.user_id',
          to: 'user_position.position_id',
        },
        to: 'position.id',
      },
    },
  }

  // This is called when an object is serialized to database format.
  $formatDatabaseJson(json) {
    json = super.$formatDatabaseJson(json);

    return formatTableName(json);
  }

  // This is called when an object is read from database.
  $parseDatabaseJson(json) {
    json = parseTableName(json);

    return super.$parseDatabaseJson(json);
  }
}
```

The query I wrote to get all users associated with a position:

```
app.get('/positions', async (req, res) => {
  try {
    await Position
      .query()
      .eager('children.[user]')
      .then((positions) => {
        res.json(positions);
      }).catch((err) => {
        res.json(err);
      });
  } catch (err) {
    console.log(err);
  }
});
```

The error I'm getting is:
```
Error: o.relationMappings.user: modelClass is not defined
```

Maybe I'm misunderstanding how `eager` works, but I've read through the docs and thought I was doing things correctly. Could it be a possible ES7 bug?

**Comment by koskimas** [comment]
There are at least three things wrong here:

## 1.

In `relationMappings.join.through` tables need to match `from` and `to` in the outer object.

```js
      join: {
        from: 'position.id',
        through: {
          from: 'user_position.user_id',
          to: 'user_position.position_id',
        },
        to: 'user.id',
      },
```

should be

```
      join: {
        from: 'position.id',
        through: {
          // HERE: Tables need to match `from` and `to` in the outer object.
          from: 'user_position.position_id',
          to: 'user_position.user_id',
        },
        to: 'user.id',
      },
```

## 2.

You are querying `.eager('children.[user]')` but you have not defined a `children` relation for `Position`.

## 3.

You have a circular dependency. `Position` imports `User` that imports `Position` that imports `User´ that imports `Position` that ... There are multiple solutions to this in the docs. One is to absolute use file paths in `modelClass` instead of constructors. For example `modelClass: __dirname + 'Position'`

**Comment by koskimas** [comment]
This is not relevant, but why are you using `await` with `then` and `catch` methods? You could simply do this:

```js
app.get('/positions', async (req, res) => {
  try {
    const positions = await Position
      .query()
      .eager('children.[user]');

    res.send(positions);
  } catch (err) {
    console.log(err);
  }
});
```

**Comment by erosenberg** [comment]
> This is not relevant, but why are you using await with then and catch methods? You could simply do this:
Good point. I was getting errors earlier for not having a catch block so I thought it would give me more room to debug if needed. Completely unnecessary though, you are correct.

> You are querying .eager('children.[user]') but you have not defined a children relation for Position.
From reading this in the docs, it was a little confusing because it seems like you're talking about `People.children` in the docs, instead of the children of the People instance. The wording was a little unclear, but that could just be entirely on me.

> You have a circular dependency. Position imports User that imports Position that imports User´ that importsPositionthat ... There are multiple solutions to this in the docs. One is to absolute use file paths inmodelClass instead of constructors. For example: modelClass: __dirname + 'Position'`

Ah that makes sense. I'm still running into strange errors. Does that mean I would have to use that workaround in both files? In other word, in *User.js*, I would have to say that the `modelClass` for the `positions` relationship is `${__dirname}/Position` and in *Position.js* I would have to set the `modelClass` to `${__dirname}/User` in the `user` relationship? It looks like in the ES7 examples you are importing the constructor in one file and implementing the workaround on one of the files. Is that accurate?
Also I did a quick search in the docs and the term "circular dependencies" is only mentioned in the graph insert section. Is there somewhere else I should have looked first?

Thanks for your fast response!

**Comment by erosenberg** [comment]
Update: I've tried multiple variations of things that you recommended above. Starting to think it might be a babel error. :\

**Comment by koskimas** [comment]
Are you able to run the [ES7 example project](https://github.com/Vincit/objection.js/tree/master/examples/express-es7)? Maybe start from that and  incrementally modify it into what you want?

**Comment by koskimas** [comment]
You are right about the docs. It's basically impossible to find the information about circular deps by searching it 😄 I just tried, and failed. It is there though:

This property can be used:
http://vincit.github.io/objection.js/#modelpaths

There are couple of ways to solve the problem in the examples here (search the words `require loop`):
http://vincit.github.io/objection.js/#models

**Comment by erosenberg** [comment]
Thanks for the related info! I've tried some things and still no avail... I just wish the error messages were more explanatory.

```
import { Model } from 'objection';
import path from 'path';
import paths from '../../../config/paths';

export default class User extends Model {
  static tableName = 'user';

  static modelPaths = [paths.apiModelsPath, paths.apiBuildPath, paths.apiSrcPath];

  static jsonSchema = {
    type: 'object',
    properties: {
      id: {
        type: 'integer',
      },
      firstName: {
        type: 'string',
        minLength: 1,
        maxLength: 30,
      },
      lastName: {
        type: 'string',
        minLength: 1,
        maxLength: 30,
      },
      birthday: {
        type: 'date',
      }
    },
  }

  static relationMappings = {
    positions: {
      relation: Model.ManyToManyRelation,
      modelClass: 'Position',
      join: {
        from: 'user.id',
        through: {
          from: 'user_position.user_id',
          to: 'user_position.position_id',
        },
        to: 'position.id',
      },
    },
  }
}
```

**Position.js**
```
import { Model } from 'objection';
import path from 'path';

import paths from '../../../config/paths';

export default class Position extends Model {
  static tableName = 'position';

  static modelPaths = [paths.apiModelsPath, paths.apiBuildPath, paths.apiSrcPath];

  static jsonSchema = {
    type: 'object',
    properties: {
      id: {
        type: 'integer',
      },
      title: {
        type: 'string',
      },
    },
  }

  static relationMappings = {
    user: {
      relation: Model.ManyToManyRelation,
      modelClass: 'User',
      join: {
        from: 'position.id',
        through: {
          from: 'user_position.position_id',
          to: 'user_position.user_id',
        },
        to: 'user.id',
      },
    },
  }
}
}
```

**Query**

```
app.get('/users', async (req, res) => {
  try {
    const users = await User
      .query()
      .eager('[positions]');

    res.send(users);
  } catch (err) {
    console.log(err);
  }
});
```

**babel settings**
```
"babel": {
    "presets": [
      [
        "env",
        {
          "targets": {
            "node": "current"
          }
        }
      ],
      "stage-0"
    ]
  }
```

where `paths` resolves absolute paths. Still nothing. I've tried the suggestions above and I feel like I'm so close but still missing something probably very minute. Did I forget anything??

**Comment by erosenberg** [comment]
My absolute path to the models folder matches up in Finder as well as in my docker image, and yet it still tells me that that's not a valid directory.
```
modelClass: /Users/erosenberg/Sites/Projects/erose/api/src/models/Position is an invalid file path to a model
```
I don't know how much more verbose I can get with my path.

**Comment by koskimas** [comment]
Please try to run the example project and work from there. The example project works. If it doesn't I'll fix it immediately.

I see nothing wrong with your code you posted here. I'm assuming `/Users/erosenberg/Sites/Projects/erose/api/src/models/Position` is the path to the transpiled code and not the ES7 code right? It should be. Don't include the non-transpiled code to `modelPaths`. There is no way for objection to import ES7 modules.

You can also try this:

```js
  static relationMappings = () => ({
    user: {
      relation: Model.ManyToManyRelation,
      // Now that `relationMappings` is a function, the `require` gets executed when
      // it is really needed which is after both `User` and `Position` modules have been
      // fully loaded. You need the `default` there because you use `export default` 
      // in your modules.
      modelClass: require('./User').default
      join: {
        from: 'position.id',
        through: {
          from: 'user_position.position_id',
          to: 'user_position.user_id',
        },
        to: 'user.id',
      },
    }
  })
```

**Comment by erosenberg** [comment]
I got it to work! I was using webpack to compile my server file along with all of my data models, but decided to just skip that for the backend and use strictly babel with the recommended settings. I guess webpack wasn't meant to do that, or I just haven't found the right way to configure it. Regardless, thank you very much for your help. Greatly appreciated. 👍
