### ISSUE TITLE
Support eager joining on many-to-many "extra" fields

### ISSUE THREAD

**Issue by bunchjesse** [Vincit/objection.js#525]
Hi there, got a feature request for you!

I have the following scenario:

```
Users
Teams
Users-Teams (join table)
```

The join table has a `roleId` field and I've added this to the `extra` mapping in the many-to-many relation. Now, when I query `team.$relatedQuery('users')` I get the `roleId` joined in. Nice!

One thing that would make this better is if I could go ahead and eager load that role in while it is being joined in.

My current workaround, which is totally fine:

```
const users = queryUsers();
const roles = queryRoles();
return users.map(/* Manually set the role on each user */)
```

Thanks in advance!

**Comment by koskimas** [comment]
This is not exactly the same thing, but pretty close:

```js
class User extends Model {
  static relationMappings = {
    // Relation to the join table items.
    userTeams: {
      relation: Model.HasManyRelation,
      modelClass: UserTeam,
      join: {
        from: 'User.id',
        to: 'UsersTeams.userId'
      }
    },

    teams: {
      relation: Model.ManyToManyRelation,
      modelClass: Team,
      join: {
        from: 'User.id',
        through: {
          from: 'UserTeam.userId',
          to: 'UserTeam.teamId'
        },
        to: 'Team.id'
      }
    }
  }
}

// Model for the join table.
class UserTeam extends Model {
  static relationMappings = {
    user: {
      relation: Model.BelongsToOneRelation,
      modelClass: User,
      join: {
        from: 'UserTeam.userId',
        to: 'User.id'
      }
    },
    team: {
      relation: Model.BelongsToOneRelation,
      modelClass: Team,
      join: {
        from: 'UserTeam.teamId',
        to: 'Team.id'
      }
    },
    role: {
      relation: Model.BelongsToOneRelation,
      modelClass: Role,
      join: {
        from: 'UserTeam.roleId',
        to: 'Role.id'
      }
    }
  }
}

class Team extends Model { ... }
class Role extends Model { ... }
```

Now you can do things like this:

```js
await User
  .query()
  .eager('userTeams.[role, team]')
```

**Comment by koskimas** [comment]
And actually, you can probably simply define the relationMapping for `Role` through `roleId` even though it is not the team's own property. This should work (without any of the stuff I wrote in the previous post):

```js
class Team extends Model {
  static relationMappings = {
    role: {
      relation: Model.BelongsToOneRelation,
      modelClass: Role,
      join: {
       from: 'Team.roleId',
       to: 'Role.id'
      }
    }
  }
}
```

```js
team.$relatedQuery('users').eager('role')
```

**Comment by koskimas** [comment]
And actually, you can probably simply define the relationMapping for `Role` through `roleId` even though it is not the team's own property. This should work (without any of the stuff I wrote in the previous post):

```js
class User extends Model {
  static relationMappings = {
    role: {
      relation: Model.BelongsToOneRelation,
      modelClass: Role,
      join: {
       from: 'User.roleId',
       to: 'Role.id'
      }
    }
  }
}
```

```js
team.$relatedQuery('users').eager('role')
```

**Comment by koskimas** [comment]
As an answer to the feature request, I don't think that would make sense. `extra` fields can be any fields, not just foreign keys. A feature that allows them to be eager loaded would be pretty arbitrary. I'm closing this now, but feel free to comment on my suggestions. I can help you find an alternative way to eager load the role.

**Comment by danmo** [comment]
In need of this feature too. Currently, have a junction table which references some user ids. These users need to get eagerly loaded.

Is there a way of getting this working without modifying the current database design?

**Comment by heisian** [comment]
@danmo I would suggest creating a specific model for the pivot table itself, and then defining a `RelationMapping` for the models that you would like to be eager loaded.

**Comment by heisian** [comment]
You could potentially do something like this:
```node
myFirstModel.$loadRelated({
  myPivotModel: {
    myModelReferencedInPivotTable: true
  }
})
```

..IF your relations are set up correctly, it COULD work, but I haven't tried it myself. This sort of nesting though may point at a larger issue, that the tables could be architected differently. I'm just shooting from the hip, though, because I have no knowledge of your application or its requirements.

**Comment by heisian** [comment]
Yeah, what I wrote is exactly what @koskimas suggested, but his example lays it all out for you. I don't think this should be clouded into an additional feature, since what is desired is already supported.

**Comment by danmo** [comment]
Here is a more specific example: clients and books in a many to many relations. The junction/pivot table will also hold an extra rejected_by column which will reference users that have rejected the book.


```
export default class Reject extends Model {
  static get relationMappings() {
    const User = require('../User');
    return {
      rejectedBy: {
        relation: Schwifty.Model.BelongsToOneRelation,
        modelClass: User,
        join: {
          from: 'rel_clients_books.rejected_by',
          to: 'users.id',
        },
      },
    };
  }
}
```

```
export default class Client extends Model {
  static get relationMappings() {
    const Book = require('books').Model;
    const Like = require('likes').Model;

    return {
      books: {
        relation: Schwifty.Model.ManyToManyRelation,
        modelClass: Book,
        join: {
          from: 'clients.id',
          through: {
            modelClass: Reject,
            from: 'rel_clients_books.client_id',
            to: 'rel_clients_books.book_id',
            extra: ['rejected_by'],
          },
          to: 'books.id',
        },
      },
    };
  }
}
```

The question is how can I get a hold of  `client.books[0].rejectedBy.{data}`, where rejectedBy would be the *extra* eagerly loaded relation on the Reject model.

**Comment by danmo** [comment]
Client.query().eager(`[books.*]`) won't do the trick.

**Comment by koskimas** [comment]
Why won't `Client.query().eager('books.rejectedBy')` do?

**Comment by koskimas** [comment]
If you add the `rejectedBy` relation for `Book` I mean...

**Comment by koskimas** [comment]
You should be able to do this, even though `Book` doesn't have the `rejected_by` column. It gets joined to it while eager loading:

```js
export default class Book extends Model {
  static get relationMappings() {
    const User = require('../User');
    return {
      rejectedBy: {
        relation: Schwifty.Model.BelongsToOneRelation,
        modelClass: User,
        join: {
          from: 'books.rejected_by',
          to: 'users.id',
        },
      },
    };
  }
}
```

**Comment by koskimas** [comment]
@danmo :arrow_up:

**Comment by danmo** [comment]
@koskimas that's an awesome solution, worked. thank you!
