### ISSUE TITLE
upsertGraph, should update property when relating new association

### ISSUE THREAD

**Issue by johannessjoberg** [Vincit/objection.js#527]
When creating a new relationship (null => some id) for a resource that already exists in the database `upsertGraph` is not updating passed properties. But when the relation already exists it's possible update the properties on the child as expected.

Verification tests (add to `/tests/integration/upsertGraph.js`):
```
    it.only('should relate and update property of belongsToOne relation (fails)', () => {
      const upsert = {
        id: 1,
        // update BelongsToOneRelation. null => 3 and model1Prop1 change
        model1Relation1: { id: 3,  model1Prop1: 'updated belongsToOne' },
      };

      return transaction(session.knex, trx => {
        return Model1
          .query(trx)
          .upsertGraph(upsert, { relate: true })
          .then(result => {
            expect(result.$beforeUpdateCalled).to.equal(1);
            expect(result.$afterUpdateCalled).to.equal(1);

            expect(result.model1Relation1.$beforeUpdateCalled).to.equal(1);
            expect(result.model1Relation1.$afterUpdateCalled).to.equal(1);

            return Model1
              .query(trx)
              .findById(result.id)
              .eager('model1Relation1')
              .then((result2) => {
                expect(result2.model1Relation1.model1Prop1).to.equal('updated belongsToOne');
              });
          });
      });
    });

    it.only('should update property of belongsToOne relation (works)', () => {
      const upsert = {
        id: 2,
        // update BelongsToOneRelation. 3 => 3(no change), but model1Prop1 change
        model1Relation1: {
          id: 3,
          model1Prop1: 'updated belongsToOne',
        },
      };

      return transaction(session.knex, trx => {
        return Model1
          .query(trx)
          .upsertGraph(upsert, { relate: true })
          .then(result => {
            expect(result.$beforeUpdateCalled).to.equal(undefined);
            expect(result.$afterUpdateCalled).to.equal(undefined);

            expect(result.model1Relation1.$beforeUpdateCalled).to.equal(1);
            expect(result.model1Relation1.$afterUpdateCalled).to.equal(1);

            return Model1
              .query(trx)
              .findById(result.id)
              .eager('model1Relation1')
              .then((result2) => {
                expect(result2.model1Relation1.model1Prop1).to.equal('updated belongsToOne');
              });
          });
      });
    });
```

The behaviour is the same for both `BelongsToOne` and `ManyToMany` relations.

So is this expected behaviour? The docs are a little vague concerning this case.

**Comment by koskimas** [comment]
I thought about this and simply ignored in the initial implementation just so that I could get `upsertGraph` released 😄  This is one of the things I meant to return to at some point. Off the top of my head, I don't see any problems with updating the related rows. Implementation can be a bit tricky though since currently the `upsertGraph` architecture only allows one operation per model instance. No we would need to do 2 (relate + update). 

Thank you for the test case again! Those really make my job easier and I can immediately see that the issue is not a case of user error.

**Comment by koskimas** [comment]
`relate + insert` work but for different rows.. I mean you an relate a row, and insert another, but you also van relate a row and _update_ another. In that sense they work the same. I'm pretty sure this will be out before 1.0.
