### ISSUE TITLE
where for n n relation

### ISSUE THREAD

**Issue by nbeydoon** [Vincit/objection.js#53]
Hello, I am searching a way to do this with objection I know how to do this with knex but I can t do the same with objection, I have try this:

```
Tags.query()
        .eager('[invoiceLines]')
        .where({key: 'collectId', "invoiceLines.payerId": '2'})

```

```
select * from tags t

left join invoiceLines_tags it on it.tagId = t.id
left join invoiceLines i on it.invoiceLineId = i.id

where t.key = "collectId"
	and i.payerId = 2
```

Thanks

**Comment by koskimas** [comment]
Hi,

The eager method doesn't actually create joins. It creates separate queries for the relations. Therefor you cannot refer to the `invoiceLines.payerId` in the where clause. You would probably do this using a explicit join in knex, and you can do that with objection also. Something like this:

```js
Tags.query()
  .leftJoin('invoiceLines_tags as it', 'it.tagId', 'tags.id')
  .leftJoin('invoiceLines as i', 'it.invoiceLineId', 'i.id')
  .where({key: 'collectId', "i.payerId": '2'})
```

You don't need the `eager` here, but if you want to fetch the relations also, you can add it. The point of objection is that you can always use default SQL just as you would with knex. There are helpers for eager loading and bunch of other things that are not easily done with SQL, but there is no custom query DSL like HQL in hibernate.

**Comment by nbeydoon** [comment]
Thanks guy, it works!
