### ISSUE TITLE
Query promise resolve before commit end.

### ISSUE THREAD

**Issue by scandinave** [Vincit/objection.js#531]
Hi,

When i use transaction to wrap some queries. The promise is resolve before queries in the transaction are executed. This is the code that make the transaction.
```

objection.transaction(Model.knex(), trx =>
        Model.query(trx)
          .upsertGraph(req.body.model, {
            relate: true,
            unrelate: false
          })
          .then(model => {
            res.status(httpCode.HTTP_CREATED).json(model);
          }).catch(err => {
            res.statusMessage = "There is an error";
            res.status(httpCode.HTTP_UNPROCESSABLE_ENTITY).end();
          })
      );
```
Now this code is the unit test that call this endpoint : 

```
chai.request(server)
        .post(`${basePath}/models`)
        .set("Authorization", `JWT ${tokenAdmin}`)
        .set("Content-Type", "application/json")
        .send({
          model: newModel
        })
        .then(res => {
          Model.query().findOne({name: "modelName"}).then(model => {
            console.log(model); // model is undefined
            res.should.have.status(httpCode.HTTP_CREATED);
            res.body.should.be.a("object");
            res.body.should.not.be.empty;
            res.body.should.have.property("description", "modelDescription");
            Model.query().delete().where("id", model.id).then(() => {
              done();
            }).catch(err => {
              done(err);
            });
          }).catch(err => {
            done(err);
          });
        }).catch(err => {
          done(err);
        });
```
If I pause the test with breakpoints. This test works well. So what's the problem? am I missing something?

thx

**Comment by koskimas** [comment]
You need to return a promise from the transaction callback:

```js
objection.transaction(Model.knex(), trx =>
        // HERE: notice the return in the next line.
        return Model.query(trx)
          .upsertGraph(req.body.model, {
            relate: true,
            unrelate: false
          })
          .then(model => {
            res.status(httpCode.HTTP_CREATED).json(model);
          }).catch(err => {
            res.statusMessage = "There is an error";
            res.status(httpCode.HTTP_UNPROCESSABLE_ENTITY).end();
          })
      );
```

**Comment by koskimas** [comment]
Also you shouldn't respond inside the transaction or you can lose atomicity. This is better:

```js
objection.transaction(Model.knex(), trx =>
  // HERE: notice the return in the next line.
  return Model.query(trx)
    .upsertGraph(req.body.model, {
      relate: true,
      unrelate: false
    });
}) .then(model => {
  // Here the transaction has been committed.
  res.status(httpCode.HTTP_CREATED).json(model);
}).catch(err => {
  // Here the transaction has been roleld back.
  res.statusMessage = "There is an error";
  res.status(httpCode.HTTP_UNPROCESSABLE_ENTITY).end();
});
```

**Comment by koskimas** [comment]
This is off topic, but it always bugs me when people don't use promises correctly 😄 . Your unit test can be written like this using promise chaining:

```js
chai.request(server)
        .post(`${basePath}/models`)
        .set("Authorization", `JWT ${tokenAdmin}`)
        .set("Content-Type", "application/json")
        .send({
          model: newModel
        })
        .then(res => {
          return Model.query().findOne({name: "modelName"});
        }).then(model => {
            console.log(model); // model is undefined

            res.should.have.status(httpCode.HTTP_CREATED);
            res.body.should.be.a("object");
            res.body.should.not.be.empty;
            res.body.should.have.property("description", "modelDescription");

            return Model.query().delete().where("id", model.id);
        }).then(() => {
          done();
        }).catch(err => {
          done(err);
        });
```

Now there is only one `catch` block but the result is exactly same.

**Comment by scandinave** [comment]
Nice, this works like a charme. And i will update my test code. 
Just for information,  write 
`val => {
return foo();
}`

is exactly the same as writing :
`val => foo()`
😆

**Comment by koskimas** [comment]
Yes I know 😄  I just copied your style of writing the arrow functions from your example.

**Comment by brokercl** [comment]
this 

 exports = async  function({ query, headers, body }, response) {
    // Extracting token_ws from query parameters
    const { token_ws } = query;
    
    // Making the commit using the received token
      const commitTransaction = await ( new Transaction()).commit(token_ws);

    // Retornando el objeto como respuesta
    return commitTransaction;
};
return {"vci":"TSY","amount":500,"status":"AUTHORIZED","buy_order":"ordenCompra12345678","session_id":"sesion1234557545","card_detail":{"card_number":"6623"},"accounting_date":"0501","transaction_date":"2024-05-01T21:13:57.614Z","authorization_code":"1213","payment_type_code":"VD","response_code":0,"installments_number":0},
how show something like this 
<h1 style="color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Transacción Exitosa</h1><h2 style="color: rgb(51, 51, 51); font-family: Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Detalles de la Transacción</h2>
Ítem | Valor
-- | --
Compañía: | TSY
Monto: | $34.531
Estado: | AUTHORIZED
Orden de Compra: | ordenCompra12345678
Identificador de Sesión: | sesion1234557545
Número de Tarjeta: | X[object Object]
Fecha Contable: | 0504
Fecha de Transacción: | 2024-05-04T18:43:43.551Z
Código de Autorización: | 1213
Tipo de Pago: | VD
Código de Respuesta: | 0
Número de Cuotas: | 0
thanks
