### ISSUE TITLE
Typings: throwIfNotFound() doesn't have one

### ISSUE THREAD

**Issue by kblomster** [Vincit/objection.js#533]
And I'm not clever enough to figure out how to add it. I'm pretty new to TypeScript, but I think using it would at the very least change the return type of all the query methods that are currently typed to return `QueryBuilderOption<T>`, so maybe it needs a different `QueryBuilder` type all of its own?

**Comment by koskimas** [comment]
@mceachen Could you take a look at this at some point?

**Comment by mceachen** [comment]
Typescript (afaict) doesn't support interface signatures that declare what errors can be raised. It seems that `.throwIfNotFound()` would be an interface passthrough. Am I correct?

**Comment by kblomster** [comment]
Well, kinda. It's not about typing the exception. Right now e.g. `findById` is typed to return a `QueryBuilderOption<T>`, which means it can return one or zero results (`T | undefined`, https://github.com/Vincit/objection.js/blob/master/typings/objection/index.d.ts#L397). What I would want is that if you use `throwIfNotFound` earlier in the query builder, `findById` would now be expected to return exactly one result (because otherwise it'd raise an error). If I can't get that there's no real point in using `throwIfNotFound` because I'll have to either typecast the `| undefined` away or write my own check for an empty result to get TypeScript to agree with me that the value can't be undefined.

**Comment by mceachen** [comment]
When I did research for this a while back, it seemed that the TypeScript team didn't want to add support for a method to be able to declare `throws <T extends Error>`. With the idea that "Exceptions" should be "exceptional," having missing db records not be exceptional, and coming from scala that had `Some/None/Maybe` support, I've been living with [this Option class](https://gist.github.com/mceachen/ba885d4ef56c35f963fb9c6bb68d5cd4) to handle these maybe-undefined values.

**Comment by kblomster** [comment]
I don't mind not having `throws <T extends Error>`, that's no problem. I do like that options class too (thanks!), but in this case it doesn't do what I want. If I expected there to maybe be a result, it'd do what I wanted, but in my mind the use case for `throwIfNotFound` is to very explicitly declare that not finding this particular db record *is* an exceptional condition that I *don't* want to handle gracefully.

**Comment by mceachen** [comment]
@kblomster the following blew my mind, coming from 30 years of experience with 10 other languages, but make sure you really internalize this: [uncaught exceptions should kill the current process](https://nodejs.org/api/process.html#process_warning_using_uncaughtexception_correctly). 

It's made me pretty hesitant to throw errors, given a caller may not `.catch` the exception or wrap the call in an async try/catch. Returning a Maybe<T> is typesafe, and if the caller knows it's OK, it can un-maybe the call with a bang.

```ts
type Maybe<T> = T | undefined
const foo: Maybe<string> = "hello"
console.log(foo!)
```

that said, the signature is in the API, so we should add it. @koskimas where is it valid to be added to the query builder chain? Everywhere?

**Comment by kblomster** [comment]
Yep! That's how my previous Node project (not TS) works. If something throws, there's a programmer error and it does crash the process (as per [Joyent's take](https://www.joyent.com/node-js/production/design/errors#operational-errors-vs-programmer-errors) on it). That's what I expect and want - I don't even attempt to catch exceptions. My intended use case for `throwIfNotFound` is where the entity not existing is actually some degree of a constraint violation.
