### ISSUE TITLE
Example of best practice for using multiple plugins on a model

### ISSUE THREAD

**Issue by mtpultz** [Vincit/objection.js#535]
I don't see an example for applying multiple plugins so I'm adding this as a discussion and to make sure this is actually how it should be setup since it seems quite verbose.

```
import { Model } from 'objection';
import * as ObjectionPassword from 'objection-password';
import * as ObjectionUnique from 'objection-unique';
import * as ObjectionVisibility from 'objection-visibility';

// Initialize mixins, and combine
const Password = ObjectionPassword();
const Unique = ObjectionUnique({
  fields: ['email'],
  identifiers: ['id']
});
const Visibility = ObjectionVisibility;
const MixinModel = Visibility(Unique(Password(Model)));

export default class User extends MixinModel {
  static tableName = 'User';

  // Blacklist properties
  static hidden = ['password'];

  // ...
}
```

**Comment by koskimas** [comment]
Hi!

First of all, I'd recommend creating a common base class from which to inherit all your models. That way you only need to apply most of your plugins once. In addition to that there are couple of helpers for applying multiple plugins.

```js
// BaseModel.js
import { Model, mixin } from 'objection';
import * as Plugin1 from 'objection-plugin1';
import * as Plugin2 from 'objection-plugin2';

export class BaseModel extends mixin(Model, [
  Plugin1,
  Plugin2({someOption: ['foo', 'bar']})
]) {
  // Add your shared stuff like hooks here.
}
```

```js
// User.js
import { BaseModel } from './BaseModel';
import * as Plugin3 from 'objection-plgugin3';

export default class User extends ObjectionPassword(BaseModel) {
  static tableName = 'User';

  // Blacklist properties
  static hidden = ['password'];

  // ...
}
```

If you don't like this approach, there's a `compose` helper that let's you compose multiple plugins. With that you can do something like this.:
```js
// plugins.js
import { compose } from 'objection';
import * as Plugin1 from 'objection-plugin1';
import * as Plugin2 from 'objection-plugin2';

const plugins = compose([
  Plugin1,
  Plugin2({someOption: ['foo', 'bar']})
]);

export plugins;
```js

```js
// User.js
import { plugins } from './plugins';
import { Model } from 'objection';
import * as Plugin3 from 'objection-plugin3';

export default class User extends ObjectionPassword(plugins(Model)) {
  static tableName = 'User';

  // Blacklist properties
  static hidden = ['password'];

  // ...
}
```

Of course none of this works if you use plugins that need to be configured differently for each model, but those are badly designed plugins. That kind of per-model configuration should be implemented as static fields on the model class.

**Comment by koskimas** [comment]
I don't recommend this, but you can also avoid creating a `BaseModel` by doing this:

```js
import * as objection from `objection`;
import * as Plugin1 from 'objection-plugin1';
import * as Plugin2 from 'objection-plugin2';

objection.Model = mixin(objection.Model, [
  Plugin1,
  Plugin2({someOption: ['foo', 'bar']})
]);
```

**Comment by mtpultz** [comment]
Thanks @koskimas that clears a lot up.  I was definitely doing this wrong since I was applying these mixins on a per model basis.  I'll definitely package the plugins up into a BaseModel and keep pushing through the docs.  Cheers

**Comment by mtpultz** [comment]
@koskimas looks like the typings for ObjectionJS are out of date.  Seem to be missing mixin and compose.  Looks like they are for v0.8.4 and the current version is v0.8.9.

**Comment by mtpultz** [comment]
I filed an issue so it is more visible - https://github.com/Vincit/objection.js/issues/536

**Comment by mceachen** [comment]
@koskimas I suggest you edit the comment I downvoted, and replace "I don't recommend this, but you can also avoid creating a BaseModel by doing this" with "Please don't do the following, which edits the Objection Model implementation in place, but that way leads to madness:"

In some cultures (*cough* silicon valley *cough*) "don't recommend" means "eh, it might be ok, who knows."

**Comment by koskimas** [comment]
@mceachen 😂 Some people prefer to shoot themselves in the foot with a railgun.

**Comment by mceachen** [comment]
I mean, if you're going to shoot your own foot, do it with style, right?
