### ISSUE TITLE
Typings are missing .mixin and .compose

### ISSUE THREAD

**Issue by mtpultz** [Vincit/objection.js#536]
Typings are for v0.8.4 not v0.8.9 and are missing at least `mixin` and `compose` exports.

**Comment by koskimas** [comment]
The typings usually lag a little behind since they were contributed by the community and are not actively maintained by more active members of the project. I don't use typescript myself, but I'll try to remember to at least add simple things like this in the future.

**Comment by drew-r** [comment]
@mceachen has kindly been maintaining the typings for the most part.

There's also `QueryBuilder.resultSize(): Promise<Number>` but objection returns a string for this as far as I can tell.

**Comment by mceachen** [comment]
I can take this.

@koskimas maybe you can open issues (and at-reference me?) to track adding typings for new features, so typings expose new features as they're released. I'll try to get to them.

@drew-r I'll ping you when my PR is ready so you can make sure I understood you correctly.

**Comment by mceachen** [comment]
> There's also QueryBuilder.resultSize(): Promise<Number> but objection returns a string for this as far as I can tell.

I'm floating off master:

```
$ grep objection package.json
    "objection": "Vincit/objection.js",
```

and I see a number from the promise:

```
 Asset.query().where("foo", 123).resultSize().then(console.dir)
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
> 0
```

**Comment by koskimas** [comment]
@mceachen I'd love to delegate the typing related tasks to you if you have time to take care of them! I've avoided doing that because I haven't wanted to bother you. I'm really grateful for your contributions!!

**Comment by mceachen** [comment]
I'm happy to help when I can. Feel free to ping me, just know there might be latency in my response.

I'm grateful for objection!

**Comment by mtpultz** [comment]
I don't know if it's helpful for me to point out other missing typings or not, but the chained query() method on models appears to be missing typings as well.

```
User
  .query() // <--- query does not exist on typeof User
  .insert({ username: 'info@example.com', password: 'secret' })
  .then((user: User) => {
    console.log(user.id);
  });
```

**Comment by mceachen** [comment]
@mtpultz there are examples that prove that use case is handled correctly, so you've got an issue with your setup. Does your User model extend Model?

**Comment by mtpultz** [comment]
Thanks @mceachen.  

I am extending Model through a BaseModel so I'm not sure what the issue might be, but this is only day two using Objection, but can't run an insert query since the project won't build, and throws `error TS2339: Property 'query' does not exist on type 'typeof User'.`.  If I remove the insert the migrations run properly and the database structure is setup.

```
import { BaseModel } from './base.model';

export class User extends BaseModel {
  static tableName = 'Users';

  // ... removed for brevity
}
```

```
import { Model, mixin } from 'objection';
import * as Password from 'objection-password';
import * as Unique from 'objection-unique';
import * as Visibility from 'objection-visibility';

export class BaseModel extends mixin(Model, [
  Password,
  Unique({
    fields: ['username'],
    identifiers: ['id']
  }),
  Visibility
]) {
  // ... removed for brevity
}
```

**Comment by mceachen** [comment]
@mtpultz fwiw I have a non-trivial app using Objection, and have not needed to use plugins yet--I wouldn't get hung up on that bit.

I'd use the knex migration to set up unique constraints and PKs:

```js
exports.up = function (knex, Promise) {
  return knex.schema
    .createTable("Example", table => {
      table.increments("id").primary()
      table.string("name").notNullable().unique()
      table.dateTime("createdAt").notNullable()
      table.dateTime("updatedAt").notNullable()
    })
```

Don't be afraid to hook into the `$beforeInsert` and `$beforeUpdate` hooks, and even the `$parseDatabaseJson` method in your base model class. You can do date serialization, ensure columns are set, and encrypt passwords (or better yet, have a method in your model that writes the encrypted contents to a column, rather than relying on magicks).

I don't think my PR is quite right, after looking at the implementation of these composable plugins. I'm hoping to get answers to what @koskimas would like for the official public API before I send an update to my PR.

**Comment by mtpultz** [comment]
@mceachen you're right it has something to do with the plugins.  If I just use Model directly in my BaseModel then the issue stops occurring, but the addition of multiple or a single plugin causes TypeScript to throw.  I'll stick to using what's available through Knex and skip the magic.

After removing the mixed-in plugins the error TypeScript error jumps into the insert indicating argument types are not assignable to Partial<User> and the resolved promise can't be `user: User`, and either has to  `user: any`, or switch `insert` to `insertAndFetch`.

```
User
  .query()
  // Error: Argument of type "{ username: 'mtpultz@gmail.com', password: 'secret', role: 'admin' }" is not assignable to parameter of type Partial<User>
  .insert({ username: 'info@example.com', password: 'secret' })
  .then((user: User) => {
    console.log(user.id);  // Error: Property "id" does not exist on User
  });
```

The typings indicate that `insert` should take a `Partial<T>` and respond with `T` so not quite sure why this error is occurring since username and password definitely exist on the User model in the jsonSchema.

```
import { Model } from 'objection';
import { BaseModel } from './base.model';
import { UserProfile } from './user-profile.model';

export class User extends BaseModel {
  static tableName = 'Users';

  static jsonSchema = {
    type: 'object',
    required: ['username', 'password'],

    properties: {
      id: { type: 'integer' },
      username: { type: 'string', maxLength: 50 },
      password: { type: 'string', minLength: 8, maxLength: 255 },
      role: {
        type: 'string',
        enum: ['guest', 'admin'],
        default: 'guest'
      },
      created_at: { type: 'dateTime' },
      updated_at: { type: 'dateTime' }
    }
  };

  static relationMappings = {
    profile: {
      relation: Model.HasOneRelation,
      modelClass: UserProfile,
      join: {
        from: 'users.id',
        to: 'user_profiles.user_id'
      }
    }
  };
}
```

**Comment by oscaroox** [comment]
@mtpultz you can try this
```javascript
const plugins: typeof Model = mixin(...)
```
I haven't tried it yet but it should probally work.

**Comment by mceachen** [comment]
@oscaroox that approach has some issues, namely, no signatures from the plugins will be carried into his models, and no static typings. Rather than `typeof Model`, he can define a plugin interface, say, `MyPlugin`, and then use `const plugins: ModelClass<Model & MyPlugin> = mixin(...)`.

**Comment by mceachen** [comment]
This is fixed in https://github.com/Vincit/objection.js/pull/546
