### ISSUE TITLE
Add new method 'mergeAllowEager' to 'QueryBuilder'

### ISSUE THREAD

**Issue by zuck** [Vincit/objection.js#539]
Add a `QueryBuilder.mergeAllowEager` method, which behaves similar to how `QueryBuilder.mergeEager` does.

**Comment by koskimas** [comment]
Good idea! I'll do that.

**Comment by koskimas** [comment]
Actually, here's a good first contribution if someone wants to create pull request.

**Comment by newhouse** [comment]
I've been meaning to tackle this one...will try and get to it this weekend...

**Comment by koskimas** [comment]
Added by @newhouse in https://github.com/Vincit/objection.js/commit/f7606bf665da599eae03ecbed3cc4b7d43983953
