### ISSUE TITLE
querying a model by related properties

### ISSUE THREAD

**Issue by behalka** [Vincit/objection.js#541]
Hey, I have a question about `joinRelation` helpers. I'd like to query `Product` model based on `Item` model - `Product` hasMany `items`. When I use `joinRelation`, the filtering works:

```js
Product.query()
.joinRelation('items')
.where('items.affiliate_id', 2)
```

produces following sql as expected:

```sql
select "products".* from "products" inner join "product_items" as "items" on "items"."product_id" = "products"."id" where "items"."affiliate_id" = 2
```

But I would also like to return the list of filtered `items` - I tried it like this (based on [this answer](https://github.com/Vincit/objection.js/issues/93))

```js
Product.query()
.joinRelation('items')
.eager('items')
.where('items.affiliate_id', 2)
```

Products are again filtered correctly, but eager loaded `items` are not:

```js
[{
"id": 1,
"name": "THE ROMAN",
"items": [
	{
		"id": 1,
		"productId": 1,
		"affiliateId": 1, // noooooooo
	},
	{
		"id": 2,
		"productId": 1,
		"affiliateId": 2,
	}]
}]
```

I found out I could achieve the result either
- with adding `modifyEager()` into the query above
- or doing the query with `eagerAlgorithm(Product.JoinEagerAlgorithm)` 

What would be the best way to achieve this? I'd like to stick with `joinRelation` if that's possible Thanks :)

(btw I really like this project, keep it up guys!)

**Comment by koskimas** [comment]
Hi,

Using `eagerAlgorithm(Product.JoinEagerAlgorithm).eager('items')` actually executes the same query as `joinRelation('items')` but in addition to that, it parses the result into a tree structure. There's also a `joinEager` shortcut you can use instead of `eagerAlgorithm(Product.JoinEagerAlgorithm).eager('items')`:

```js
Product.query()
  .joinEager('items')
  .where('items.affiliate_id', 2)
```

**Comment by behalka** [comment]
Thanks a lot, closing :)
