### ISSUE TITLE
Shared Validator

### ISSUE THREAD

**Issue by lehni** [Vincit/objection.js#549]
Is there a reason why a separate validator object is created for each model through `createValidator()`?

Having a shared AJV validator across all models would offer a few benefits:

* Additional keywords and formats could be registered and used across all JSON schemas, see http://epoberezkin.github.io/ajv/custom.html
* Definitions could be easily shared and referenced through `$ref`

I can already achieve this by returning the same instance in each model's static `createValidator()` method, but I think it's worth considering making this easier.

**Comment by koskimas** [comment]
It is not shared so that you can have different validator for different model. For example if your node app is connected to two different databases, and both need to have different Model hierarchies that use different validation, you can do that.

Can't you simple define a shared base class, say `BaseModel`, and define your custom definitions and keywords there?

**Comment by lehni** [comment]
Yes, that makes sense, thanks!

**Comment by lehni** [comment]
Actually, there are two things still that make sharing a validator and definitions of keywords and formats difficult:

- Caching of non-changing schemas all happen under the key `'default'`, thus they override each other with multiple models sharing the same validator. I would recommend using the `constructor.name` or `tableName` here instead. Happy to create a PR for it.

- There are two instances of `ajv` created, one called `ajvNoDefaults` and one `ajv`. If I add keywords or formats to be used in the json schema, I have to add them to both.

The 1st is easy to address, the 2nd has me wondering a bit. Isn't this perhaps something that really should be addressed in AJV, so one validator can handle both scenarios?

**Comment by lehni** [comment]
And as an example why I would like to make shared validators work, beyond the mentioned additional keywords and formats, is that the use of `$ref` allows for a lot of interesting scenarios. Here a simple example:

#### Schema for Author model
```json
{
  "id": "Author",
  "type": "object",
  "properties": {
    "id": {
      "type": "number",
    },
    "name": {
      "type": "string"
    },
    "comments": {
      "type": [ "array", "null" ],
      "items": { "$ref": "Comment" }
    }
  }
}

#### Schema for Comment model
````js
{
  "id": "Comment",
  "type": "object",
  "properties": {
    "id": {
      "type": "number",
    },
    "comment": {
      "type": "string"
    },
    "author": {
      "$ref": {
        "anyOf": [
          { "$ref": "Autho" },
          { "type": "null" }
        ]
      }
    }
  }
}
````

Schemas can reference each other, and this can then therefore be applied to nested relations also. This would be a great match for graph upserts, where the full graph could be validated at once before storing it, and precise errors could be returned with JSON pointers pointing at the right sub-properties causing the validation errors.

**Comment by lehni** [comment]
#551 addresses 1. above, and if I add keywords in `onCreateAjv()`, then they get added to both Ajv instances (`ajv` and `ajvNoDefaults`), so 2. is fine for me too after this is merged.

**Comment by jordansexton** [comment]
@lehni This is interesting, how do you get both model schemas to compile with the same validator such that the references resolve?

**Comment by lehni** [comment]
I am currently using it to support inheritance of `jsonSchema` without the need to redefine shared properties. In the sub-class, I can do this:

```js
{
  id: 'SubModel',
  $schema: 'http://json-schema.org/draft-06/schema#',
  $merge: {
    source: { $ref: 'BaseModel' }
    with: {
      type: 'object',
      properties: {
        someProperty: {
          type: 'string'
        }
      }
    }
  }
}
```

Note that this requires `ajv-merge-patch` to work. I am adding it in the `onCreateAjv()` hook passed in the `AjvValidator` constructor's `config` object:

```js
onCreateAjv: function (ajv) {
  setupMergePatch(ajv)
}
```

**Comment by jordansexton** [comment]
@lehni Smart! I'll give this a shot.

**Comment by jordansexton** [comment]
@lehni Do you reference on model's schema from another? If so, do you have to do something to compile all their schemas into the validator before validation attempts to resolve the refs?

**Comment by lehni** [comment]
I am importing the models in the right sequence so that the references are defined known ahead of time. So far I haven't had any problems with that, but circular references would be problematic I guess.

**Comment by jure** [comment]
@lehni: I've had a few issues with this approach, mainly with the ref ids not being resolvable. Are you still using this, or have you gone a different route?
