### ISSUE TITLE
SQL clause precedence?

### ISSUE THREAD

**Issue by theganyo** [Vincit/objection.js#55]
I'm having an issue with precedence of SQL statements. I have something like this:

```
  Resource
    .query()
    .first()
    .where('id', id)
    .whereJsonSupersetOf('data:permissions', [{ actor: user.id, action: action }])
    .orWhereJsonSupersetOf('data:permissions', [{ actor: user2.id, action: action }])
```

Which emits SQL like this:

```
select * from "Resource" where "folderId" = ? and ( "data"#>'{permissions}' )::jsonb @> ?::jsonb or ( "data"#>'{permissions}' )::jsonb @> ?::jsonb
```

But that's not quite correct... I really need parenthesis around the JSON permission checks. In other words, I'd like to see the ultimate SQL look like this:

```
select * from "Resource" where "folderId" = ? and ( ( "data"#>'{permissions}' )::jsonb @> ?::jsonb or ( "data"#>'{permissions}' )::jsonb @> ?::jsonb )
```

Is there a way to force precedence / add parentheses?

Thanks!
Scott

**Comment by koskimas** [comment]
@elhigu Can you take a look at this?

**Comment by koskimas** [comment]
Actually have you tried this:

```js
  Resource
    .query()
    .first()
    .where('id', id)
    .where(function (builder) {
          builder
            .whereJsonSupersetOf('data:permissions', [{ actor: user.id, action: action }])
            .orWhereJsonSupersetOf('data:permissions', [{ actor: user2.id, action: action }]);
    });
```

**Comment by theganyo** [comment]
No, I hadn't. It works like a champ! Thanks so much! Was that documented and I just missed it?

**Comment by koskimas** [comment]
No, not really :D. The documentation is a bit crap at the moment, but I'm writing a new one as we speak. It is documented in [knex.js documentation](http://knexjs.org/#Builder-where). Objection.js query builder attempts to be 100% compatible with knex query builder, so you can always use knex's docs.

**Comment by theganyo** [comment]
Ah. I actually did look at Knex docs as well, but I missed that "Grouped Chain" means precedence. :)

Thanks again!
