### ISSUE TITLE
Where can I find test database configurations file?

### ISSUE THREAD

**Issue by capaj** [Vincit/objection.js#553]
Running the tests I get:
```
  955 passing (27s)
  2 failing

  1) integration tests mysql "before all" hook:
     Error: Could not connect to mysql. Make sure the server is running and the database objection_test is created. You can see the test database configurations from file /home/capaj/git_projects/objection.js/testUtils/index.js

```

the error thrown refers to the file index.js, but it does not exist. Is this file not in git and I have to create it manually?

**Comment by koskimas** [comment]
It's [here](https://github.com/Vincit/objection.js/blob/master/tests/integration/index.js)

**Comment by koskimas** [comment]
[Development setup docs](http://vincit.github.io/objection.js/#development-setup)

**Comment by koskimas** [comment]
The error message seens to be misleading. I'll fix that.
