### ISSUE TITLE
Add patchGraph() and maybe updateGraph() methods?

### ISSUE THREAD

**Issue by lehni** [Vincit/objection.js#557]
I would like to suggest the addition of `patchGraph()`that is similar to `upsertGraph()`, but would receive a sub-set of the full graph and just patch, without creating new instances in the graph, and throwing an error if data for new instances was included.

Perhaps it is then also worth considering `updateGraph()`, as a version of `upsertGraph()`that would just update and not create new instances? 

And in symmetry to #556, it would then be great to then also add `*AndFetch()` versions of these: `patchGraphAndFetch()` and `upsertGraphAndFetch()`.

**Comment by koskimas** [comment]
I'm going to add options for `upsertGraph` that allow you to select any subset of `[insert, update, delete, relate, unrelate]` to be selected for an `upsertGraph` call. This case will be covered by only enabling `update`. Let's continue this discussion in #526

**Comment by lehni** [comment]
@koskimas there is a difference between update and patch, yes? would this cover both use-cases?

**Comment by koskimas** [comment]
`upsertGraph` always uses `patch`. It's possible to add an option for that too.

**Comment by lehni** [comment]
Thanks for clarifying! Those options sounds perfect, BTW. Exactly what I need. That and the `upsertGraphAndFetch()` variant : )
