### ISSUE TITLE
PLEASE VOTE: Should we change object references from JSON methods in the TypeScript typings?

### ISSUE THREAD

**Issue by mceachen** [Vincit/objection.js#558]
Currently all references to JSON objects in the typings are `objects`, like

```ts
    fromJson(json: object, opt?: ModelOptions): M;
    fromDatabaseJson(row: object): M;
    loadRelated(models: (Model | object)[],
    ...
```

TypeScript's `object` has no methods, so if you override, say, `$formatDatabaseJson`, and your overriding method uses `object`, you have to use bracket-notation to get member values (like `obj["id"]` rather than `obj.id`.

We could use the `any` type, but then strings, numbers, functions, and symbols would be legal arguments to these methods, which clearly isn't correct. We *could*, however, introduce a new `JsonObject`:

```ts
  type JsonValue = string | number | boolean | Date | null | undefined | JsonObject 

  interface JsonObject {
    [key: string]: JsonValue | JsonValue[]
  }
```

Please thumb-up if you'd like to see this change, or thumb-down if you think the typings are fine as they are. Feel free to comment, as well.

**Comment by newhouse** [comment]
I *think* I understand the problem you're highlighting, and the pros/cons of your solution...but I leave it up to you TS experts, of which I am definitely not one.

**Comment by jordansexton** [comment]
Given that `undefined` and `Date` are not valid JSON values, is the idea of a JSON value here an ad-hoc convention to follow, but not necessarily JSON standard?

I'm also wondering what would happen if parsing values into something novel with https://github.com/brianc/node-pg-types. Would a looser object type achieve the desired effect of being able to use property dot notation? e.g.

```typescript
interface PlainObject {
  [key: string]: any
}
```

**Comment by mceachen** [comment]
@jordansexton I'm using "JSON" in reference to the methods with that substring--you're correct, a naked Date wouldn't make sense in a JSON string, but the objects you pass into `.fromJSON()` will absolutely support Date or other value types.

I'm finding it a bit ungainly to have to cast the result from, say, `$toJSON()`, before I can do normal dotted field access (like `foo.bar` instead of `foo["bar"]`. Another alternative from the above `JsonObject` would be to simply use `any`.

**Comment by kblomster** [comment]
I think I'm with @jordansexton on this one. "JSON" is a misnomer and you can stuff all kinds of things into the database, and those things can be serialized in any way you please. For example, salted passwords are frequently stored in binary form in database and can be kept in the model in a `Buffer` field, but there's nothing that says you can't store serialized higher order objects or other such things, and while it's a fairly exotic use case, it does happen. Trying to restrict the typings to JSON-compatible ones at all levels helps more than it hurts in this case, I think - Objection simply doesn't know enough about the types.

**Comment by mceachen** [comment]
Closing.
