### ISSUE TITLE
Graph insert and related API should return the TypeScript type that was passed into insertWithRelatedAndFetch

### ISSUE THREAD

**Issue by mtpultz** [Vincit/objection.js#559]
Using `insertWithRelatedAndFetch` has a TypeScript error regarding what is returned from `User.query().insertWithRelatedAndFetch`, which it assumes is `User`, but more of a `Partial<User>`, and you can't add generics like `insertWithRelatedAndFetch<UserWithProfile>` to resolve it to a proper type.  

> Type 'User' is not assignable to type 'UserWithProfile'.  Property 'profile' is missing in type 'User'.

It feels like graph queries should return a similar type that is passed since it returns an object literal that is not the model used to perform the insert (`User` in this case) and instead provides an object literal that is similar to the object literal passed into `insertWithRelatedAndFetch` (`UserWithProfile` in this case), or at least a `Partial<UserWithProfile>` if the interface doesn't contain the full model as optional keys.

```js
interface UserWithProfile {
  id?: number;
  username: string;
  password: string;
  created_at?: string;
  update_at?: string;
  profile: {
    id?: number;
    user?: number;
    first_name: string;
    last_name: string;
    created_at?: string;
    update_at?: string;
  };
}

// Error
private async store(userWithProfile: UserWithProfile): Promise<UserWithProfile> {
  return await User.query() // <--- Expects User instead of UserWithProfile
    .insertWithRelatedAndFetch(userWithProfile);
}

// Possible solution?
private async store(userWithProfile: UserWithProfile): Promise<UserWithProfile> {
  return await User.query()
    .insertWithRelatedAndFetch<UserWithProfile>(userWithProfile);
}
```

The typings seem to suggest the solution is possible, but using `insertWithRelatedAndFetch<UserWithProfile>(userWithProfile)` displays this error:

> Expected 0 type arguments, but got 1

**Current Typings**

```
insertWithRelated: Insert<T>;
insertWithRelatedAndFetch: InsertGraphAndFetch<T>;

interface InsertGraphAndFetch<T> {
  (modelsOrObjects?: Partial<T>): QueryBuilderSingle<T>;
  (modelsOrObjects?: Partial<T>[]): QueryBuilder<T>;
}

export interface QueryBuilderSingle<T> extends QueryBuilderBase<T>, Promise<T> { }
```

**Workaround**

These are workarounds allow transpiling, but it means using `Partial<User>` or `Partial<UserWithProfile>` throughout other methods that use the returned object literal when it actually is a `UserWithProfile`. 

```js
private async store(userWithProfile: UserWithProfile): Promise<Partial<User>> {
  return await User.query()
    .insertWithRelatedAndFetch(userWithProfile);
}

private async store(userWithProfile: UserWithProfile): Promise<Partial<UserWithProfile>> {
  return await User.query()
    .insertWithRelatedAndFetch(userWithProfile);
}
```

**Comment by koskimas** [comment]
`insertWithRelatedAndFetch` should return a model subclass type just like it does at the moment. Why don't you simply add the `profile` relation for the `User` model instead of creating interfaces? I think this can be closed, but @mceachen could take a look if he has time.

**Comment by mtpultz** [comment]
@koskimas I didn't know I could add `profile: UserProfile` to my User model.  I thought the member variables of the models were supposed to be related to the table columns since the model is the representation of a table, and otherwise it would only have methods.

```
// ... removed for brevity
import { UserProfile } from './user-profile.model';

export class User extends BaseModel {
  readonly id: number;
  username: string;
  password: string;
  role: string;

  profile: UserProfile; // <--- where UserProfile is the related model

  static tableName = 'users';

  // ... removed for brevity
}
```

**Comment by mceachen** [comment]
FWIW, I always directly add all fields to my model classes, and use `eager`when needed.

**Comment by koskimas** [comment]
@mtpultz Model is are representation of a table but it can be a superset. Nothing bad happens if you add your relations to it. Objection doesn't parse the fields of a model in any way. You can add whatever you want to them. Actually I don't thing anything is added to the transpiled javascript from field declarations like `profile: UserProfile`.

The correct way to deal with relations is to add them to the models with the current typings.
