### ISSUE TITLE
Compound primary key

### ISSUE THREAD

**Issue by Biktop** [Vincit/objection.js#56]
Thanks for the great component!

How I should handle situation where I use compound primary key? For example I try to insert new record and I get error 'Failed to create model: ... - column "id" does not exists'.
I tried to override idColumn and specify something as [ 'col1', 'col2' ].

**Comment by koskimas** [comment]
Sorry, no support for compound primary keys at the moment. I think this is a feature that all self respecting ORMs should have though and it is on my todo list. Full support for compound primary keys requires a lot of work and a couple of breaking changes, but I'm just about to release a 0.4.0 and I could squeeze this feature in. I'll take a closer look at this and post here if I decide to start working on this.

**Comment by koskimas** [comment]
I'm working on compound key support and I haven't found any show stoppers yet. I'll publish a new release candidate of 0.4.0 as soon as I have a working version ready.

In the future, compound primary key can be specified by setting `idColumn` to an array of column names, just as you tested. Similarly `relationMappings` can take an array of columns like so:

```js
someRelation: {
  relation: Model.OneToManyRelation,
  modelClass: SomeModel,
  join: {
    from : ['tbl1.a', 'tbl1.b'],
    to: ['tbl2.c', 'tbl2.d']
  }
}
```

If you have any ideas or requirements for this feature, please feel free to post them here.

**Comment by Biktop** [comment]
Good news!
I think that an array of columns is good idea. I will try a new version as soon as it will be released.

**Comment by koskimas** [comment]
First version with compound key support is ready by the end of this week. I'm writing tests now and everything seems to work so far.

**Comment by koskimas** [comment]
@Biktop I just published the version `0.4.0-rc.3` that has support for compound keys. Let me know if there are any problems.

**Comment by Biktop** [comment]
Thank you very much! I've tried new version and haven't found any problems related to my use cases.

**Comment by koskimas** [comment]
I'm closing this as solved. Please open a new issue if you encounter any bugs.
