### ISSUE TITLE
Not able to insert JSON array of object in Postgres JSON column

### ISSUE THREAD

**Issue by tnolet** [Vincit/objection.js#563]
I might be overlooking something, but I guess inserting arrays of objects into JSON columns is not directly supported? It works if I do a JSON.stringify() of the array, but that kind of defeats the whole ease of use of persisting JSON object with a simple command as I have to map and adjust each item before I can insert it. Postgres throws the following error, which shows that the array is being serialized as an object, and that fails:

```
{ error: invalid input syntax for type json
...
where: 'JSON data, line 1: {"{\\"foo\\":\\"someVal\\",\\"bar\\":\\"someVal\\"}"}',
```

Example
```
# column definition in knex migration file
table.json('myKeyValueColumn').nullable()
```

```
# jsonSchema definition
myKeyValueColumn: { type: 'array' },
```

```
# object to insert:
myKeyValueColumn: [{ foo: "someVal", bar:  "someVal" }]
```

**Comment by koskimas** [comment]
It should work and does work in [our tests](https://github.com/Vincit/objection.js/blob/master/tests/integration/jsonQueries.js). Could you create a test case or a standalone reproduction that I can easily debug?

**Comment by tnolet** [comment]
@koskimas yes, on it right now

**Comment by tnolet** [comment]
@koskimas Ok, here we go. I just ran it on my box with specs:
- Postgresql 9.5 and 10
- Knex 0.13.0
- Objection 0.8.9

It fails because it's treating the array as an object:

```javascript
// SETUP
const Knex = require('knex')
const knex = Knex({
  client: 'postgresql',
  connection: {
    database: 'json_array_test'
  }
})

const Model = require('objection').Model
Model.knex(knex)

knex.schema.createTable('json_array_test', function (table) {
  table.increments('id').primary()
  table.json('kv').nullable()
}).then(() => {
  console.log('created table')
})
  .catch(console.error())

class JsonArrayTest extends Model {
  static get tableName () {
    return 'json_array_test'
  }

  static get jsonSchema () {
    return {
      kv: {
        type: 'array',
        items: {type: 'object'}
      }
    }
  }
}

// TEST

const obj = { kv: [{ foo: '1', bar: '2' }] }

JsonArrayTest
.query()
.insert(obj)
.then(console.log)
.catch(console.error)
```

**Comment by koskimas** [comment]
Your jsonSchema is invalid. This is a valid json schema:

```js
  static get jsonSchema () {
    return {
      type: 'object',
      properties: {
        kv: {
          type: 'array',
          items: {type: 'object'}
        }
      }
    }
  }
``

**Comment by koskimas** [comment]
By the way, I'd recommend using `jsonb` instead of `json` type. It's much more efficient.

**Comment by tnolet** [comment]
@koskimas Ahaaaaa...thanks for the super quick help! I guess I just didn't register how Json schema works together with Objection. Again, may thanks!

**Comment by ps2goat** [comment]
Do you (objection.js team) have json tests that work with models that don't define a schema?

**Comment by mordof** [comment]
@ps2goat what would that look like? JSON validation only happens if there is a schema defined. In the case of JSON/JSONB columns, there's now a `jsonAttributes` helper to automatically stringy/parse data as necessary.

**Comment by ps2goat** [comment]
@mordof I meant for testing json/jsonb columns without a schema.  I'm asking because from the app to the database, the objects weren't saving, but they were parsing automatically when loading from the database.  It was just a little confusing for me at first, as I started with create and expected loading to work the same.

In the end, I added a json schema _only_ for those json properties, and it's working with objects in both directions. I see that the jsonAttributes is automatically populated based on the schemas I added.  My original inquiry was because all other types seem to be inserted/updated and loaded properly without any special handling.  But if I have to create the schema or use the jsonAttributes method, that will work.

Thanks!

**Comment by harry-ng15** [comment]
> Your `jsonSchema` is invalid. This is a valid schema:
> 
> ```js
>   static get jsonSchema () {
>     return {
>       type: 'object',
>       properties: {
>         kv: {
>           type: 'array',
>           items: {type: 'object'}
>         }
>       }
>     }
>   }
> ```

best trick bro :V

**Comment by treyenelson** [comment]
I had the same experience as @ps2goat: error on insertion (invalid input syntax for type json) until I added a `jsonSchema` getter to my model for just that JSON array field.
