### ISSUE TITLE
Add .addEager() method

### ISSUE THREAD

**Issue by IlyaSemenov** [Vincit/objection.js#569]
Currently, `query.eager()` replaces the previous eager definition. It makes it hard to compose a query in multiple steps.

For example, I might have a function that prepares an object listing query:

```js
function listSelector (query) {
  // only pull data that is needed for the object listing
  return query.select('name', ....)
    .eager('[foo(foo), bar(bar)]', {
      foo: query => query.select('name'),
      bar: query => query.select('name'),
    })
}
```

Now if I want to have a more detailed selector for an individual record, I currently have to repeat the previous eager details:

```js
function viewSelector (query) {
  return listSelector(query)
    .eager('[foo(foo), bar(bar), baz(baz), xyz(xyz)]', {
      foo: query => query.select('name'), // unfortunately I have to copy/paste this
      bar: query => query.select('name'),
      baz: query => query.select('name'),
      xyz: query => query.select('name'),
    })
}
```

Instead, it would be simpler to use `addEager`:

```js
function viewSelector (query) {
  return listSelector(query)
    .addEager('[baz(baz), xyz(xyz)]', {
      baz: query => query.select('name'),
      xyz: query => query.select('name'),
    })
}
```

**Comment by jordansexton** [comment]
There's a [`mergeEager` method](http://vincit.github.io/objection.js/#mergeeager) that does exactly this.

**Comment by IlyaSemenov** [comment]
My bad. Thanks!

**Comment by jordansexton** [comment]
No worries!

**Comment by koskimas** [comment]
@IlyaSemenov Also check out [namedFilters](http://vincit.github.io/objection.js/#namedfilters). They can help reduce copy-pasta with eager expressions.
