### ISSUE TITLE
Row level locking

### ISSUE THREAD

**Issue by Biktop** [Vincit/objection.js#57]
Hello!
I try to implement read-modify pattern via row level locking mechanism. Something like this:
```
SELECT ... FOR UPDATE;
UPDATE ... COMMIT;
```
And cannot imagine how I can realise it in Objection. With pure knex I can use *transaction* method plus *forUpdate*.
Could you suggest any workaround for implementation this query?

**Comment by koskimas** [comment]
The `forUpdate` and `forShare` methods are missing. I will add them in the 0.4.0 version. Until then you could try this _really_ ugly workaround:

```js
objection.QueryBuilder.prototype.forUpdate = function () {
  this._knexMethodCalls.push({method: 'forUpdate', args: []});
  return this;
};
```

Then you should be able to use this method in a [transaction](http://vincit.github.io/objection.js/#transactions).

**Comment by Biktop** [comment]
Thank you very much for workaround. It works!

**Comment by koskimas** [comment]
@Biktop `0.4.0-rc.2 has the `forUpdate` method, if you want to test it out.
