### ISSUE TITLE
Crash when select(1) is used in eager query with JoinEagerAlgorithm

### ISSUE THREAD

**Issue by IlyaSemenov** [Vincit/objection.js#570]
Consider two models:

```js
class Foo extends Model {
  static tableName = 'foo'

  static get relationMappings () {
    return {
      bar: {
        relation: Model.HasOneRelation, // reverse link
        modelClass: Bar,
        join: {
          from: 'bar.foo_id',
          to: 'foo.id',
        },
      },
    }
  }
}

class Bar extends Model {
  static tableName = 'bar'
  static idColumn = 'foo_id'
}
```

If you do an eager lookup with JoinEagerAlgorithm, querying all foos that are linked by a bar, and decide not to pull any bar fields but use `select(1)`, Objection will crash:

```js
const foosWithBar = await Foo.query()
  .eagerAlgorithm(Foo.JoinEagerAlgorithm)
  .eager('bar(bar)', {
    bar: query => query.select(1),
  })
  .whereNotNull('bar.foo_id')
```

```
TypeError: Cannot read property 'length' of undefined
    at createModel (/Users/semenov/obj_crash/node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:662:31)
    at RelationJoinBuilder.rowsToTree (/Users/semenov/obj_crash/node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:163:19)
    at JoinEagerOperation.onRawResult (/Users/semenov/obj_crash/node_modules/objection/lib/queryBuilder/operations/eager/JoinEagerOperation.js:54:29)
```

Replacing `bar: query => query.select(1)` with `bar: query => query.select('foo_id')` makes it work.
Using default eager algorithm with `select(1)` also works (not allowing `whereNotNull` filter, of course).

A complete reproducible example here: https://gist.github.com/IlyaSemenov/f4a81b5e1006fd5fb396f2d17facf2b9. Put it into `test.js` and run with `dropdb test; createdb test; node test`

This is objection 0.8.9.

### Expected result

The query doesn't crash, and returns a single result:
`[ Foo { id: 2, name: 'two', bar: Bar { '?column?': 1 } } ]`.

**Comment by koskimas** [comment]
Unfortunately you cannot use `select(1)` in eager query like that. The result of each query needs to be an array of objects (rows with columns).

**Comment by IlyaSemenov** [comment]
I understand that I can't use it like that at the moment, but I don't really see the reason for that limitation. After all, **it already works** with `WhereInEagerAlgorithm`. It's also rather obvious which SQL query must be constructed for `JoinEagerAlgorithm`, and what should be returned to node.

Wouldn't the library benefit if this was a supported scenario in both eager methods? Won't this use case help when planning some future refactoring? I mean, I understand it's surely not top-priority, but why closing the issue immediately?

**Comment by koskimas** [comment]
It would be great if that was supported, but I have already had this discussion a couple of times before and supporting that would require huge amount of work. If the implementation is obvious to you, feel free to submit a pull request with working tests and I'd be happy to review and merge it.
