### ISSUE TITLE
reduce is missing

### ISSUE THREAD

**Issue by appedemic** [Vincit/objection.js#571]
Knex has the option for a reduce operation on the query, directly reducing all records:

```js
knex.from('table').reduce((result, record) => {
  return `some complex operation on the entire record`
})
```

This doesn't work with Objection:

```js
Model.query().reduce(...)
```

Results in:
```
reduce is not a function
```

It seems to be missing from the Objection QueryBuilder. Now of course I could first map all records, which returns a promise and then apply (bluebird) reduce on that promise but I have some complex cases where there is no purpose for a mapping operation and I directly want to reduce the record into something. It makes no sense to add a bodus: `.map(x => x)` inbetween.

**Comment by koskimas** [comment]
Thanks, I'll `reduce` to 0.9 version.

**Comment by juanjoLenero** [comment]
I can take a stab at this, unless someone else is already working on it.

**Comment by tleytek** [comment]
Was this taken out? My result is
```
.query(...).where(...).reduce is not a function
```

**Comment by kibertoad** [comment]
@tleytek Objection (nor knex) no longer use Bluebird, hence function is no longer available. Instead, you should await query and call reduce on result array.
