### ISSUE TITLE
Can't insert/patch attribute when name matches relation.

### ISSUE THREAD

**Issue by juanjoLenero** [Vincit/objection.js#579]
Whenever I try to patch an attribute that shares name with a relation, that attribute is missing from the resulting sql.

```js
Thing.query().patch({foo: 'bar', createdBy: 2}).toString();
// update "things" set "foo" = 'bar'
```
* This also seems to be the case with insert/update operations.

```js
const Objection = require('objection'); // v0.8.9
const Model = Objection.Model;
const Knex = require('knex');

const knex = Knex({
    client: 'sqlite3',
    useNullAsDefault: true,
    connection: {
        filename: 'example.db'
    }
});
Model.knex(knex);

class User extends Model {
    static get tableName() {
        return 'users';
    }
    static get relationMappings() {
        return {
            things: {
                relation: Model.HasManyRelation,
                modelClass: Thing,
                join: {
                    from: 'users.id',
                    to: 'things.created_by'
                }
            }
        };
    }
}

class Thing extends Model {
    static get tableName() {
        return 'things';
    }
    static get relationMappings() {
        return {
            createdBy: {
                relation: Model.BelongsToOneRelation,
                modelClass: User,
                join: {
                    from: 'things.created_by',
                    to: 'users.id'
                }
            }
        };
    }
}
```

**Comment by koskimas** [comment]
Unfortunately that's a limitation that cannot be fixed. This particular bug could probably be fixed, but you will run into several others if you give the same name to a column and a relation. They are properties of the same object. This issue has come up before. You just need to rename the column or the relation.

**Comment by juanjoLenero** [comment]
Got it, figured that would also be the case due to graph related functionality.

Is there anything we can do to warn others about this limitation? Maybe a note in the relations section of the documentation? Or a new gotchas/caveats section? Would that be worthwhile?

**Comment by koskimas** [comment]
Yeah that probably should be documented, but there is no good place where people would find it. A caveats section is a good idea. I'll create a new issue.
