### ISSUE TITLE
Support {relate: true} option with insertGraph.

### ISSUE THREAD

**Issue by koskimas** [Vincit/objection.js#586]
Currently `insertGraph` allows existing rows to be related using a special property `#dbRef`. `upsertGraph` supports simply passing an id by using a `{relate: true}` or `{relate: ['rel1.rel2', 'rel3']}` options.

Add `relate` option for `insertGraph`.

**Comment by lehni** [comment]
While looking into this a few days ago, I noticed that the documentation of `#dbRef` does not mention that it only works with `ManyToManyRelation`, but in the code it sure looks this way. Am I correct about this, and will `{ relate: true }` work with the other kind of relations also?

**Comment by koskimas** [comment]
@lehni Not at first. `relate` makes little sense for the other relation types. You can already relate `BelongsToOneRelation` by providing the foreign key for the owner. Also for `HasOne` and `HasMany` it's kind of a weird operations since they can be owned by a single parent. Relating a `HasManyRelation` removes it from the previous parent and relates to the new one. I have never needed `relate` for `HasMany` relations. I'll add the support if someone actually needs it and opens an issue.

**Comment by lehni** [comment]
I am currently using `upsertGraph()` instead of `insertGraph()` for inserts where I use this. My is handling linked lists for versioning, and looks something like this:

```js
const currentVersion = await parent.$relatedQuery('currentVersion')
const newVersion = await parent.$relatedQuery('versions').upsertGraph({
  vesrionHash,
  previous: currentVersion // may be null
}, {
  relate: true
})
```

If I had to provide the id directly, it would looks like this:

```js
const currentVersion = await parent.$relatedQuery('currentVersion')
const newVersion = await parent.$relatedQuery('versions').insertGraph({
  vesrionHash,
  previousId: currentVersion && currentVersion.id
}, {
  relate: true
})
```

I think it's much nicer if I don't have to be concerned with the name of the id columns since I've already defined the relations, and Objection.js would handle those cases for me, for all relation types...

**Comment by koskimas** [comment]
I'll add support for `BelongsToOneRelation` since that's easy.

**Comment by koskimas** [comment]
@lehni Actually I won't deprecate `#dbRef`. It allows inserts and relates within the same relation which can be useful.

**Comment by lehni** [comment]
Yes I thought you'd allow both versions, yes?

**Comment by lehni** [comment]
Great, thanks! I just tested it, and it works as expected!

**Comment by drew-r** [comment]
@koskimas does this work for HasManyRelations?
