### ISSUE TITLE
How to run queries with conditions?

### ISSUE THREAD

**Issue by slim-hmidi** [Vincit/objection.js#589]
I'm trying to run a query based on some `req.query.params`:
````
 const queryBuilder = Place
    .query()
    .select('place.*', 'user.name as userName')
    .join('user', 'place.user_id', 'user.id');
  if (req.query) {
    queryBuilder
      .skipUndefined()
      .where(raw('to_tsvector(\'simple\',??) @@ to_tsquery(\'simple\',?)', ['place.name', `${checkNameQuery(req.query.name)}:*`]))
      .orderBy(raw('ts_rank_cd(to_tsvector(\'simple\',??), to_tsquery(\'simple\',?))', ['place.name', `${checkNameQuery(req.query.name)}:*`]))
      .limit(req.query.limit);
  }
  queryBuilder
    .then((places) => {
      console .log(places);
    })
    .catch((err) => {
      console.error(err);
    });
};
````
When I put a `req.query.name` I got results but when I didn't put any `req.query.name` I didn't get any result. Why the queryBuilder did not display any data when the there is no `req.query.params`?

**Comment by newhouse** [comment]
I think that `req.query` may be an empty Object even if you don't provide any query parameters in the request. `req.query` is "truthy", so your check of `if (req.query) {` will be satisfied with every request. It will sometimes then use an empty Object to populate your extra chain calls within that block, which will result in nonsense queries, and hence no results.

I think you need to be a little more specific with your `if` statement, for example:
```
// This:
if (!_.isEmpty(req.query)) { ... };

// Or this:
if (Object.keys(req.query).length > 0) { ... };

// Or this:
if (req.query.name) { ... };
```

Also, for future reference, you can chain `.debug()` to the query builder and it will give you information about the query. I suspect you'd see that it's got some conditions that would explain having no results.

**Comment by koskimas** [comment]
Yes, `req.query` is an empty object even when there are no query parameters.

**Comment by slim-hmidi** [comment]
thank you very much

**Comment by jeff3yan** [comment]
@slim-hmidi I've made a small filtering library for [objection](https://github.com/tandg-digital/objection-filter) and have been extremely interested in postgres' text search feature.

How have you found the integration of objection and using these text search features?

**Comment by slim-hmidi** [comment]
@jeff3yan I didn't found any official documentation how to integrate objection with FTS so I tried to combine the `raw()` function of `Objection` with the features of text search to obtain what I want.
