### ISSUE TITLE
can relate() mirror unrelate() ?

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#590]
I do:
```
person
  .$relatedQuery('movies')
  .unrelate().where(someWhereObj)
```
I think it would be very neat to have
```
person
  .$relatedQuery('movies')
  .relate().where(someWhereObj)
```
And the documentation doesn't make it so clear this works (or not):
```
person
  .$relatedQuery('movies')
  .relate(someWhereObj);
```

**Comment by koskimas** [comment]
`relate` is always either an `update` operation or an `insert` operation. `where` doesn't really make sense in those queries most of the time. 

This doesn't work the way you expect
```js
person
  .$relatedQuery('movies')
  .relate(someWhereObj);
```

You need to think of `relate` like `insert` and `update`: you pass an object that gets inserted or updated. I'd be happy to merge a PR that explains this better in the docs.
