### ISSUE TITLE
<Schema>.<Table Name> in table name property and using column info

### ISSUE THREAD

**Issue by Allam76** [Vincit/objection.js#591]
Hello.

Since a while back we can use database schema name in objection. Example:

``` js
  static get tableName() {
    return 'metadata.action';
  }
```

This works great in most cases and makes my life a lot easier. Thank you very much for this addition. However I found one case where it causes problems. If you call columnInfo() on such a model, knex constructs the sql with the schema name in the table name binding :-(

```js
Action.query().columnInfo().debug();
``` 

gives sql: 

``` sql
bindings:Array(2) ["metadata.action", "base"]
"select * from information_schema.columns where table_name = $1 and table_catalog = $2 and table_schema = current_schema"
```
first binding, I believe should be only table name, without schema name...

Many thanks
Martin

**Comment by koskimas** [comment]
Yeah, I noticed the same. I had to use this hack to make it work:

```js
const tableParts = table.split('.');
const columnInfoQuery = knex(_.last(tableParts)).columnInfo();

if (tableParts.length > 1) {
  columnInfoQuery.withSchema(tableParts[0]);
}
```

I think this is a bug in knex, not objection.

**Comment by elhigu** [comment]
Actually `<schema>.<table>` type of identifiers are not valid in knex. withSchema is only robust way to refer schema. I've already added section about knex identifier to docs for knex 0.14 release.

**Comment by koskimas** [comment]
Good to know @elhigu. Objection relies that knex can handle `<schema>.<table>` in many places. There is very little extra handling for it and stuff just works. I hope you are not going to remove the current functionality from knex or objection will break pretty bad?

**Comment by Allam76** [comment]
@koskimas 
I use the same hack as you do. Could we add this to the query().columnInfo() method?

**Comment by koskimas** [comment]
If that's not going to be fixed in knex, then we should add it.

**Comment by elhigu** [comment]
Its not supported in knex, because already now identifier syntax is a bit ambiguous string can be `colNameOrTableName` depending on context and knex isn't passing that context to compiler and there is no way to pass the context for raw queries.

It could be fixed, but it would need some bigger internal changes to make sure that context is known everywhere. I couldn't find the knex discussion about this. I'll add a link if I find it later.
