### ISSUE TITLE
Question: Can we drop the support for node 4 for next release (1.0)?

### ISSUE THREAD

**Issue by koskimas** [Vincit/objection.js#593]
4.0.0 at least seems like too old a goal. We need to bumb that to 4.4 or something because objection's dependencies require that.

Could we move straight to 6.X? How many of you are still stuck with node 4 in production or otherwise?

Thumbs up for moving to 6, down for not moving

**Comment by fl0w** [comment]
Wether or not node 4 is supported or not, how about helping the community by not allowing versions with known security issues?

```json
"engines": {
  "node": "^4.8.4 || ^6.10.1 || ^7.10.1 || >= 8.1.4"
}
```

**Comment by elhigu** [comment]
Maybe it could be documented that objection supports 2 last node LTS version?

**Comment by koskimas** [comment]
@elhigu That could be a good strategy. I think more important than LTS releases is the actual adoption. How fast do people usually move to a new version? How fast are they available in AWS and the like?

@fl0w Sure, if that's a thing in the community. Is there a good place to get such a list?

**Comment by koskimas** [comment]
Actually the original question is stupid. I will only get thumbs down since no-one really cares unless the change breaks their code 😄

**Comment by elhigu** [comment]
@koskimas its impossible to know timelines, I think AWS elastic beanstalk platforms start support them pretty soon (IIRC they update the platform image twice a year). But I don't know a about othe places... In app engine flex I can select any version. I suppose it should be the same in every place where they run code in docker containers. 

Also I think that it also means that if version 1.0 supports node 4, then all the versions 1.x must support it too?

**Comment by koskimas** [comment]
That's a good point about minimum version change being a breaking change. If we could determine that basically no-one is using 4.0, then bumbing the minimum version wouldn't be that bad even without a major version change. If we really need to consider it a breaking change, then 1.0 will absolutely have 6.X as a minimum 😄 I don't want to be stuck with legacy javascript

**Comment by kblomster** [comment]
I think for a major version bump, supporting only the two latest Node LTS versions is perfectly reasonable. A mature project on older infrastructure isn't going to update major versions of something as central as the ORM without pressing reasons and a significant testing effort, and if you're going to that length you might as well upgrade Node too.

**Comment by fl0w** [comment]
> @fl0w Sure, if that's a thing in the community. Is there a good place to get such a list?

No I don't think it exists. I have a PR in Koa that purposes the same solution, based on comments and conclusions from repo owners (i.e. not my idea). The purposed solution for keeping it up to date is just to PR and follow along as security announcements are made.

Engine support is a continuously debated topic there as well.

**Comment by koskimas** [comment]
@fl0w I'll merge a PR, but I won't start maintaining the list.

**Comment by devinivy** [comment]
Supporting latest of v4 seems great to me.  In case you're looking for inspiration: the hapi community is dropping support for latest v4 thru v6 with their next major version, and basing the whole dang thing on async/await.  But also supporting the prior version of hapi (i.e. backporting security/bug fixes) while node v6 is LTS.

**Comment by koskimas** [comment]
Minimum node version will be 6.0.0 from objection 1.0 onward.
