### ISSUE TITLE
Default value using raw()

### ISSUE THREAD

**Issue by npasserini** [Vincit/objection.js#594]
I've been trying to create a default value for an uuid column in mysql but I couldn't arrive to make it work. Is it doable? Is it a bug or am I doing something wrong?

I couldn't fin a reference of how to use a raw value as a default. 
What I did is to add this to my model:

```
  static get jsonSchema() {
    return {
      type: 'object',
      properties: {
        uuid: {
          type: 'uuid', 
          default: raw('UUID()'),
        },
      },
    };
  }
```

And I get this error:
```
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: 
   [ 1,
     '{"companies":["Samsung"],"from":"2016-09-26","to":"2017-09-26"}',
     'BrandPerception',
     { _sql: 'UUID()', _args: null } ],
  __knexQueryUid: 'f0d2936c-fa78-4033-90b5-f0ca2e2d50d9',
  sql: 'insert into `analyses` (`alien_project_id`, `intent`, `type`, `uuid`) values (?, ?, ?, ?)' }
Error: ER_BAD_FIELD_ERROR: Unknown column '_sql' in 'field list'
```

**Comment by koskimas** [comment]
You cannot set non-json values to __JSON__ schema. The best way to do this would be to set a default value in the database.

If you cannot set the default value in the database, you can use `$beforeInsert` hook:

```js
class BaseModel extends Model {
  $beforeInsert() {
    this.uuid = uuid.v4(); // or something like that
  }
}
```

And then instead of inheriting your models from `Model` inherit them from `BaseModel`.

**Comment by koskimas** [comment]
http://knexjs.org/#Schema-defaultTo

**Comment by npasserini** [comment]
Thank you!

PS:
Set the default value in the database in this case is not an option,
because the default value has to be a static literal value and I need to
put a function call "UUID()". Some people recommend using a trigger, but we
prefer not to add triggers to the database.


2017-11-04 6:03 GMT-03:00 Sami Koskimäki <notifications@github.com>:

**Comment by koskimas** [comment]
@npasserini Nope, the default value can be a function call among other things. This should work:

```
table.dateTime('uuid').notNullable().defaultTo('UUID()');
```

**Comment by koskimas** [comment]
This is from the knex documentation:

```
table.timestamp('created_at').defaultTo(knex.fn.now());
```

**Comment by koskimas** [comment]
I was wrong about the first example, but this works:

```
table.string('uuid').defaultTo(knex.raw('UUID()'));
```

**Comment by npasserini** [comment]
Are you sure?

Does not work for me:
```
Knex:warning - migrations failed with error: create table `test` (`uuid`
varchar(255) default UUID()) - ER_PARSE_ERROR: You have an error in your
SQL syntax; check the manual that corresponds to your MySQL server version
for the right syntax to use near 'UUID())' at line 1
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the
manual that corresponds to your MySQL server version for the right syntax
to use near 'UUID())' at line 1
```

I tried it with mysql:5.6.33 and
```
    "knex": "^0.13.0",
    "objection": "^0.8.9"
```

2017-11-06 12:21 GMT-03:00 Sami Koskimäki <notifications@github.com>:

**Comment by npasserini** [comment]
Are you sure?

Does not work for me:
```
Knex:warning - migrations failed with error: create table `test` (`uuid` varchar(255) default UUID()) - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UUID())' at line 1
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UUID())' at line 1
```

I tried it with mysql:5.6.33 and 
```
    "knex": "^0.13.0",
    "objection": "^0.8.9"
```

**Comment by fl0w** [comment]
I do this with PG, so I'm certain passing a `raw` to `defaultTo` works with knex.
For reference: https://github.com/tgriesser/knex/issues/1488

I'm not sure how `UUID()` works in MySQL, can you do a simple `SELECT UUID();` without issues?

**Comment by elhigu** [comment]
@npasserini adding default problem you should be able to reproduce with plain knex. It shouldn't have anything to do with objection.
