### ISSUE TITLE
how to order raws using raw and orderBy?

### ISSUE THREAD

**Issue by slim-hmidi** [Vincit/objection.js#598]
I'm trying to select some data from postgresql db using full text search features. But when I tried to test the data displayed on my app and the other given using a simple sql test I found that the results displayed using the Objection functions are not in the same order.
```
.select('place.*', 'user.name as userName')
    .join('user', 'place.user_id', 'user.id')
    .skipUndefined();
  if (req.query.name) {
    userBuilder
      .where(raw('to_tsvector(\'english\',??) @@ to_tsquery(\'english\',?)', ['place.name', `${req.query.name}:*`]))
      .orderBy(raw('ts_rank('to_tsvector(\'english\',??), to_tsquery(\'english\',?), ?)', ['establishment.name', `${req.query.name}:*`, 0]), 'desc')
      
```
I found that the data are ordered in the app `asc with the id` however I want to rank them using the result of `ts_rank_cd desc`. The `orderBy()` doesn't order the data and the function doesn't work. How can I fix that?

**Comment by koskimas** [comment]
I think you have a bunch of quotation mark and parenthesis errors in there. You can use `.debug` method to see the generated SQL. Compare that to your SQL test until they match.

**Comment by koskimas** [comment]
No that you can use all three quotation marks of javascript to make the queries more readable. You can eliminate the need to escape `\'` by using different quotes. Something like this:

```
 .where(raw("to_tsvector('english', ??) @@ to_tsquery('english', ?)", [
  'place.name', 
  `${req.query.name}:*`
]))
```

**Comment by koskimas** [comment]
Also when using `orderBy(raw(...))` the second argument, `desc`, probably does nothing. You need to include that in your raw sql also.

**Comment by slim-hmidi** [comment]
without putting `desc` I found on the sqlQuery build by Objection the word `asc` with `order by`

**Comment by koskimas** [comment]
If that's so, then it's a bug in knex and you should report it there. I think there is also a `orderByRaw`method you can test.
