### ISSUE TITLE
Virtual fields?

### ISSUE THREAD

**Issue by afm-sayem** [Vincit/objection.js#60]
Do you have any plan to support computed fields in models?

**Comment by koskimas** [comment]
You can implement computed fields using [`$parseDatabaseJson`](http://vincit.github.io/objection.js/#_s_parsedatabasejson) and [`$formatDatabaseJson`](http://vincit.github.io/objection.js/#_s_formatdatabasejson) methods like this:

```js
class Person extends Model {
  $parseDatabaseJson(row) {
    let obj = super.$parseDatabaseJson(row);
    obj.fullName = obj.firstName + ' ' + obj.lastName;
  }

  $formatDatabaseJson(obj) {
    // Delete our computed property so that it is not inserted into db.
    delete obj.fullName;
    return super.$formatDatabaseJson(obj);
  }
}
```

Or is there something I'm missing that this doesn't solve? I'm not a fan of a adding something like:

```js
class Person extends Model {
  static get virtuals() {
    return {
      fullName(model) {
        return model.firstName + model.lastName;
      };
    };
  }
}
```

That was basically the same amount of code and adds another feature to maintain.

**Comment by koskimas** [comment]
Using ES6 you can also solve this using getters, which is a better solution as it keeps the computed properties up-to-date:

```js
class Person extends Model {
  get fullName() {
    return this.firstName + ' ' + this.lastName;
  }

  $formatJson(obj) {
    obj = super.$formatJson(obj);
    // The getter is not enumerable, so we need to add our computed fields 
    // to the output object explicitly.
    obj.fullName = this.fullName;
  }
}
```

You can do this with ES5 also using `Object.defineProperty`.

The only downside here is that you need to add code to two places instead of one, if we had a direct support for virtual fields.

**Comment by afm-sayem** [comment]
Great! I'm using es6 so getters seems to be the way to go. Thanks for the help (and for such a cool ORM ;))

**Comment by koskimas** [comment]
@afm-sayem You're welcome! I forgot to return the object from the $formatJson method in the above example if you didn't already notice this. I updated the example.

**Comment by retorquere** [comment]
What is the ES5 equivalent for this? I can't yet move to ES6.

**Comment by koskimas** [comment]
@retorquere Objection now has a real support for virtual attributes. Check out the documentation 
http://vincit.github.io/objection.js/#virtualattributes

**Comment by mwbennett** [comment]
Updated link to virtual attributes documentation: https://vincit.github.io/objection.js/api/model/static-properties.html#static-virtualattributes

**Comment by stephanoparaskeva** [comment]
Is there no way to make the returned json object have a value that is based on existing fields?

For example, the jsonSchema() {
properties: {
    full_name = this.firstName + ' ' + this.lastName
}
}

**Comment by stephanoparaskeva** [comment]
> @retorquere Objection now has a real support for virtual attributes. Check out the documentation
> http://vincit.github.io/objection.js/#virtualattributes

Is there no way to make the returned json object have a value that is based on existing fields?

For example, the jsonSchema() {
properties: {
    full_name = this.firstName + ' ' + this.lastName
}
}

**Comment by reergymerej** [comment]
My turn to update the URL

http://vincit.github.io/objection.js/api/model/static-properties.html#static-virtualattributes
