### ISSUE TITLE
$loadRelated multiple times with different level of relations

### ISSUE THREAD

**Issue by shtse8** [Vincit/objection.js#604]
Consider this code:
```js
A belongsTo B
B belongsTo C

class A extend Model {
  async getB () {
    await this.$loadRelated('b')
    return this.b
  }

  async getC () {
    await this.$loadRelated('b.c')
    return this.b.c
  }
}

let id = 1

let a = await A.findById(id)
let c = await a.getC() // It works fine
let b = await a.getB() // It works fine

let a = await A.findById(id)
let b = await a.getB() // It works fine
let c = await a.getC() // It throws error "Cannot read property 'c' of undefined"
```

Since calling `getB()` first, the `b` is loaded, when calling `getC()`, `$loadRelated` detects `this.b` is set, it will not override, the `b` is missing `c` inside. so an error is thrown. I suggest `$loadRelated` should detected the model recursively if it is fulfilled the new `loadRelated`, and append the eager inside. Or any suggested way to do this?

**Comment by koskimas** [comment]
I cannot reproduce this. Please provide a simple reproduction I can debug or this issue will be closed.

**Comment by koskimas** [comment]
And objection cannot detect if the model fullfills the eager experssion. How would you detect it with query like this:

```
await this.$loadRelated('b(someFilter, someOtherFilter).c(modifyThisToo)')
```

?

Also the there could be new rows inserted in the database, and existing rows updated between the two calls. How could objection detect those?

**Comment by koskimas** [comment]
Any progress on the reproduction? I wrote a test case that did exactly what you describe and it worked. `$loadRelated` doesn't check existing relations. It fetches the whole tree each time.

**Comment by shtse8** [comment]
I don't have time to check recently, let's close the issue. Thanks for your help.
