### ISSUE TITLE
The field name in where is ambiguous when using with joinRelation

### ISSUE THREAD

**Issue by shwuhk** [Vincit/objection.js#606]
```
instance.$query()
  .joinRelation('b')
  .where('id', '<', 10) 
```

Both the instance class and its relation `b` class has the field `id`. I would like to inner join the instance and its `b` relation with the condition of the `id` of the instance < 10. However, the above code will throw error `ER_NON_UNIQ_ERROR: Column 'id' in where clause is ambiguous`.

Here is the SQL that generated from the above code.
```
select `Instance`.* from `Instance` inner join `B` as `b` on `b`.`instanceId` = `Instance`.`id` where `Instance`.`id` = '1' and `id` < 10
```

The field name in the where clause of the instance should append the table alias name in order to prevent from ambiguous when joining with its relation.

**Comment by elhigu** [comment]
Objection cannot know, which id field you want to refer. You need to do that manually:

```
instance.$query()
  .joinRelation('b')
  .where('Instance.id', '<', 10) 
```

**Comment by shwuhk** [comment]
If we need to refer to the relation, we should `.where('relation.field', value)` but if not specified, it should refer to the instance field. Otherwise, we must know the table name when we do joinRelation query.

Or at least, is there any method to give an alias name to the instance table name so that I can do it like, 
```
instance.$query().alias('instanceAlias')
  .joinRelation('b')
  .where('instanceAlias.id', '<', 10) 
```

**Comment by elhigu** [comment]
I think you can get the table name of the instance at least from `instance.constructor.tableName`. I don't know if there are any nicer API to get table name of model instance.

**Comment by shwuhk** [comment]
Ok. Thanks. This can solve it.
However, I think objection.js can do better by prepending the table name to it.
I will submit the PR later hope it can be approved.

**Comment by elhigu** [comment]
> If we need to refer to the relation, we should .where('relation.field', value) but if not specified, it should refer to the instance field. Otherwise, we must know the table name when we do joinRelation query.

I bet there would be bunch of corner cases to resolve, where that logic would produce wrong queries.

**Comment by koskimas** [comment]
> Or at least, is there any method to give an alias name to the instance table name so that I can do it like

Yes there is, [alias](http://vincit.github.io/objection.js/#alias) 😄
