### ISSUE TITLE
$patch with undefined value creates invalid sql

### ISSUE THREAD

**Issue by sebbarg** [Vincit/objection.js#607]
Hi,

Patching a record with an undefined value messes up the resulting SQL and throws an error in the database driver. This could potentially lead to an injection attack. 

Example:
```
person
  .$query()
  .patch({age: undefined})
  .debug(true);

```
Results in exception:

`update "persons" set  where "persons"."id" = $1 - syntax error at or near "where"`
 
The patch operation should probably ignore the entire statement if the undefined value is the only one being updated.

There is a similar scenario when running Person.query.patch.

**Comment by koskimas** [comment]
> This could potentially lead to an injection attack.

How could this lead to an injection attack?

Anyways, this is how knex handles the situation. I think this is a "bug" in knex instead of objection. @elhigu Any thoughts?

**Comment by fl0w** [comment]
Have you tried [skipUndefined](http://vincit.github.io/objection.js/#skipundefined)?

**Comment by sebbarg** [comment]
@koskimas I don't know if an attack could be fabricated, but having malformed SQL reach the database should probably avoided :)

**Comment by elhigu** [comment]
Probably it would be better to throw an error when knex sees that update query has no fields set. I remember that there has been some discussion about this (or for inserts and passing empty objects). Maybe you can find some answers from there. From top of my head it would be better to throw an error before even sending the query. Anyways this is a kenx problem.
