### ISSUE TITLE
Typescript: invalid type for query().execute()

### ISSUE THREAD

**Issue by pradel** [Vincit/objection.js#608]
First of all thanks for this awesome library, I really like it :), you guys did an amazing job!

I run into a problem with the typings in typescript.
When you run execute in this case it should return an array of objects but currently it return only a single object.

```typescript
const repositories = await RepositoryModel.query().execute();
 // error Property 'length' does not exist on type 'Repository'.
console.log(repositories.length);
```

**Comment by koskimas** [comment]
@pradel Thank you!

That's clearly a bug in the typings, but you don't need to call `execute`. You can just leave it out. Does that work for you as a workaround until this gets fixed?

**Comment by pradel** [comment]
Yeah it is working thanks!

**Comment by kblomster** [comment]
Where it's defined in the typings file currently, there's no way (that is apparent to me, at least) to figure out which specific subtype of query builder is being executed. I think the current return type is either a placeholder or something that got overlooked - previously it used to be typed to return `Promise<any>` which was technically correct but highly unhelpful.

To fix it, I think all you need to do is to remove the generic form from the `QueryBuilderBase` interface and instead add it (with an appropriate return type) to each of the more specific query builder interfaces (that is `QueryBuilderSingle`, `QueryBuilderUpdate` etc). I'll see about creating a pull request.
