### ISSUE TITLE
Running a UpsertGraph on a ManyToMany with an Extra parameter fails

### ISSUE THREAD

**Issue by scandinave** [Vincit/objection.js#609]
Hi,
I have to model Application and user like related like this : 
```
class User extends password(Model) {
   static get tableName() {
    return "admin.User";
   }
    static get relationMappings() {
        const Application = require("./application");
        applications: {
        relation: Model.ManyToManyRelation,
        modelClass: Application,
        join: {
          from: "admin.User.id",
          through: {
            from: "core.Application_User.user_id",
            to: "core.Application_User.application_id",
          },
          to: "core.Application.id"
        }
      },
    }
}
```

```
class Application extends Model {

  static get tableName() {
    return "core.Application";
  }

/**
   *  This object defines the relations to other models.
   */
  static get relationMappings() {
   return {
      users: {
        relation: Model.ManyToManyRelation,
        modelClass: User,
        join: {
          from: "core.Application.id",
          // ManyToMany relation needs the `through` object
          // to describe the join table.
          through: {
            // If you have a model class for the join table
            // you need to specify it like this:
            // modelClass: PersonMovie,
            from: "core.Application_User.application_id",
            to: "core.Application_User.user_id",
            extra: ["responsability"]
          },
          to: "admin.User.id"
        }
      },
    }
}
```

Now i need to upsert the application. I use this : 

```
objection.transaction(Application.knex(), trx =>
        Application.query(trx)
          .upsertGraph(req.body.application, {
            relate: true,
            unrelate: true
          })
      )
```

This fail saying me that column responsability of relation Application does not exist.
With a debug the request executed are : 

`sql: 'update "core"."Application" set "id" = ?, "name" = ?, "description" = ?, "thumbnail" = ?, "apiKey" = ?, "apiSecret" = ?, "responsability" = ? where "core"."Application"."id" =?',`

Data send to the server have the same structure than data receive from it. 
```
application | 
    id | 90
    name | app
    description | App 1 Description
    thumbnail | assets/app/generic.png
    apiKey | app1Key
    apiSecret | app1Secret
    users | […]
        0 | {…}
             id | 120
             email | admin@admin.com
             name | admin
             firstname | admin
             responsability | Staff
```

Why does objection add the filed responsability into application update query? Any idea?

**Comment by koskimas** [comment]
Hi, your examples are missing multiple return statements among other things. I don't know which models exist in the database, which are related, updated, deleted etc. Also you don't show the content of `req.body.application` (or is it the last code block which is also missing most of the things).

There is no way for me to help you based on this information.

Could you please create a standalone example file that reproduces the problem? Or at very least, provide real working code snippets with all relevant information. Thank you.

**Comment by scandinave** [comment]
My bad. i found the solution. This was a old code that cause the problem. 

> req.body.application.responsibility = "something". 
Sorry for the inconvenience
