### ISSUE TITLE
Incorrect information about returning method

### ISSUE THREAD

**Issue by Biktop** [Vincit/objection.js#61]
In documentation in the site several times are mentioned:
> Note that on postgresql you can just chain returning('') to the normal insert method to get the same result without an additional query.

But according to postgresql documentation it should be passed '*' instead ''. In this case it works as expected.

**Comment by koskimas** [comment]
Thanks for pointing this out. There is a `*` in the .md file, but slate (the tool I use to generate the site) removes the stars.

**Comment by koskimas** [comment]
fixed
