### ISSUE TITLE
Distinguish errors caused by model validation from other validation errors

### ISSUE THREAD

**Issue by lehni** [Vincit/objection.js#611]
At the moment, Objection uses `modelClass.createValidationError()` for a lot of different errors, among them the ones caused by failed `AjvValidator` validations.

Those validation errors contain a `data` property with an object listing `propertyName: [...errors]`, where `errors` is a list of validation errors for the given property.

The other validation errors, e.g. caused when using a faulty `eager()` statement, also contain properties, but those can mean very different things, making handling of such errors currently difficult:

```js
modelClass.createValidationError({
  eager: 'eager expression not allowed'
})
``` 
```js
throw modelClass.createValidationError({
  message: 'Invalid relation expression "' + expr + '"',
  cause: err.message
});
```
```js
throw modelClass.createValidationError({
  cyclic: 'the object graph contains cyclic references'
});
```
```js
throw modelClass.createValidationError({
  notModel: 'not a model'
});
```
```js
throw modelClass.createValidationError({
  allowedRelations: 'trying to insert an unallowed relation'
});
```
etc.

I think it would be good to reconsider the current handling and formatting of such errors, and facilitate easier handling on the receiving end of the errors.

This could either be by introducing different sub-classes, or by adding a more standardised property that can be check against, not different property names for each type of error, e.g.:

```js
throw modelClass.createValidationError({
  type: 'relation-error',
  message: 'trying to insert an unallowed relation'
});
```
I don't have the answer what the best solution is here, but I believe the current state is a bit too difficult to facilitate good exception handling practises.

**Comment by lehni** [comment]
@koskimas I just remembered this one. I'm happy to help out here if help is welcome. Do you have an idea already how the errors should be structured? Different classes with the same parent class?

**Comment by koskimas** [comment]
@lehni Could you check out the commit I just pushed if it seems ok to you?

**Comment by koskimas** [comment]
I should add a error handling recipe to docs that shows how to catch each error thrown by objection.

**Comment by lehni** [comment]
Thanks for working on this! The code looks promising. I have a few concerns though:

- You've added `type`, but it is still quite generic and just distinguished validator errors from other validation related errors, and I still have to look at the properties in `data` to find out what's actually wrong, e.g. `allowedRelations` VS `notModel `, making the lookups a bit complicated. I am wondering if these shouldn't be types as well, and the content of `data` for these would then simply become the `message` instead?

- You access `modelClass.ValidationError.Type` internally, making overriding or replacing of the `ValidationError` class more difficult (I already do this in my app). I think it would be better if these type values came from a separate structure that is also exported from `objection`, or if they were at least loaded explicitly from objection's own `ValidationError` class through `ValidationError.Type`, but without accessing `ValidationError` on the `modelClass` (importing it instead). I am currently defining my own `ValidationError` in the same way as I do `QueryBuilder`. But maybe that's not supposed to be done this way? If it is, then accessing `Type` on it is tricky.

- So far, the message of all errors where actual JSON, and I started to see this as a feature. `errorsToMessage()` does things quite differently now. It's something to consider.

**Comment by koskimas** [comment]
1. I agree, but changing things that way would be a major breaking change. The current change only breaks some small corner cases. Maybe we should go for a full rewrite and break the compatibility completely?

2. Model.ValidationError is private and shouldn't be relied upon, but that's a good point nonetheless. I'll change that.

3. There is no mention in the docs that the message is json or anything else about its format. It shouldn't be relied upon.

**Comment by lehni** [comment]
1. I would say since things change already and we're going 1.0.0, we might as well do it properly, but that's completely up to you of course, and I don't have legacy projects to maintain...

2. I guess you can tell by now that I've been looking more at the source code than the docs. It's a habit that I've built based on many open-source projects having docs out of sync with the current state of the code base : ) But this in the docs may have had a part in it as well: 
  ```js
  class Model {
    static createValidationError(errorHash) {
      return new this.ValidationError(errorHash);
    }
  }
  ```
3. That's fine. If I want that behavior, I can override `ValidationError` which I already do.

**Comment by koskimas** [comment]
Which errors would you like to detect? What's a good granularity for the `ValidationError.Type` enum?

**Comment by lehni** [comment]
Let me collect the current validation errors once more, grouped by topic:

## `QueryBuilder`

```js
.createValidationError({
  message: 'Invalid relation expression "' + expr + '"',
  cause: err.message
});
```

```js
.createValidationError({
  eager: 'eager expression not allowed'
})
```

## `DependencyGraph` / `GraphInserter`:

```js
.createValidationError({
  cyclic: 'the object graph contains cyclic references'
});
```

```js
 .createValidationError({ notModel: 'not a model' });
```

```js
.createValidationError({
  allowedRelations: 'trying to insert an unallowed relation'
});```

```js
.createValidationError({
  ref: `could not resolve reference "${ref}"`
});
```

## `UpserGraph`:

```js
.createValidationError({ allowedRelations: 'trying to upsert an unallowed relation' });
```

## `RelationJoinBuilder`:

```js
.createValidationError({
  eager: `could not find filter "${filterName}" for relation "${relation.name}"`
})
```

```js
.createValidationError({
  eager: `identifier ${alias} is over ${ID_LENGTH_LIMIT} characters long and would be truncated by the database engine.`
});
```

```js
.createValidationError({
  eager: `identifier ${alias} is over ${ID_LENGTH_LIMIT} characters long and would be truncated by the database engine.`
});
```

```js
.createValidationError({
  eager: `recursion depth of eager expression ${expr.toString()} too big for JoinEagerAlgorithm`
});
```

## `WhereInEagerOperation`:

```js
.createValidationError({
  eager: `unknown relation "${childExpression.name}" in an eager expression`
});
```

```js
.createValidationError({
  eager: `could not find filter "${filterName}" for relation "${relation.name}"`
});
```

**Comment by lehni** [comment]
A few things strike me:

1. Not all of these have to do with validation of data / graphs. I would argue that the `ValidationError` class should only be used for errors in data that the code passes to DB function as actual data.

2. Most of these are errors for eager expressions. I would argue for the need of a separate `EagerError` class.

3. Only the errors in `DependencyGraph` / `GraphInserter` and `UpsertGraph` are real validation errors for me. After #686, all of these could actually have proper `dataPath`, and use these in their `data` values. We could follow the format that's already used for other validation errors, and introduce new values for `keyword` and `params` for them. Possible values for `keyword`: `'cyclic', 'model', 'relation', 'reference'`.

4. This leaves us with only the first one, which has to do with relation expressions. Why not a new `RelationError` class for this?

**Comment by lehni** [comment]
PS: Maybe this bit of code from my own app could be of use, instead of using `cause`:

```js
class WrappedError extends Error {
  constructor(error, status = 400) {
    if (isString(error)) {
      error = { message: error }
    }
    super(JSON.stringify({
      message: error.message,
      ...error
    }, null, 2))
    this.name = this.constructor.name
    this.status = status
    this.stack = error.stack
  }
}
```

**Comment by koskimas** [comment]
All of those errors are caused by invalid input by the user and can, in my mind, be called ValidationErrors. If we create a bunch of error classes we need to rethink the error factory stuff too or we would need to add `createEagerError`, `createRelationError` etc. methods.

If we had those three different errors, how would you use them? How would you react differently to each of them? I think we should add a separate type (or class) only for those errors that someone would want to handle differently. How do we decide which those groups are? What would you handle `EagerError` and `RelationError` differently?

**Comment by koskimas** [comment]
And if we only create three classes (or enums) and remove the properies, we actually make the error handling options worse. There would be no way to reason with those errors except base on the error message, which is not the best idea.

**Comment by koskimas** [comment]
Actually the `allowedRelations` stuff needs to be distinguishable. I'd send back a 403 error for those. And I don't know if that one can be called a ValidationError

**Comment by lehni** [comment]
For me there is different type of input. Things like eager statements tend to come from the application logic, while the data tends to come, either directly or indirectly, from a front end or an admin interface, other service, etc. To me it feels confusing that both cause the same kind of `ValidationError`. I would prefer to have a clearer separation there.

**Comment by lehni** [comment]
As for the factories, that's a good point... The question is maybe: Do you need factories, or could the public API way to expose / override these constructors be the same as you already do for `QueryBuilder`: Set them simply as static members on the `Model` class?

**Comment by koskimas** [comment]
Eager expressions are strings instead of objects so that they can be easily passed from the client side. I use that feature all the time. That's why there's the `allowEager` method. In that use case, invalid and relation expressions  should create a validation error and "unallowed" relation expressions should be somehow distinguishable from those.

Meaningful grouping of the errors depends very much on the way one uses objection. To support all possible cases, we'd end up with too many error classes. That's why I think adding a `type` property and giving a distinct type for each different error could be a good idea. For some errors like

```
identifier ${alias} is over ${ID_LENGTH_LIMIT} characters long and would be truncated by the database engine.
```

and 

``` 
recursion depth of eager expression ${expr.toString()} too big for JoinEagerAlgorithm
```

it's difficult to think of a situation where they would need to be distinguished from one another. These can be pretty safely grouped under the same type.

**Comment by lehni** [comment]
Ok yes, I see your point. So if we go the `type` route, then there could be: `eager`, `relation`, and `graph`, `data` or `input`?

**Comment by lehni** [comment]
And should the values of `type` really be camel-cased words that look like classes? I prefer short lowercased strings, but that's of course a question of taste more than anything (think of the event types in HTML event objects).

**Comment by koskimas** [comment]
I'm used to `PascalCased` enums. That probably comes from my java background. I've also seen that in c++ code. All enums are named that way in objection codebase.

**Comment by lehni** [comment]
I agree that it's the norm for their names. I meant the content of the strings. It seems strange to me to put that in there too.

**Comment by koskimas** [comment]
The new types are now in 1.0.0 branch.

**Comment by lehni** [comment]
I like this much better, great!

Two remarks:

- `UnallowedRelation` sounds strange to me. I don't think *unallowed* is proper word in the English vocabulary. Isn't it *disallowed* instead? And should it then be `DisallowedRelation` or `IllegalRelation` instead?

- `InvalidGraph` could also just be `GraphValidation` in analogy to `ModelValidation`, speaking more of the nature of the `ValidationError` than being a description of the actual error, and allowing a bit more flexibility for future validation errors, e.g. the one I recently proposed on Gitter.

**Comment by lehni** [comment]
@koskimas did you see my two remarks in the last comment above? Maybe still worth considering before 1.0.0 hits the road.

**Comment by koskimas** [comment]
I don't know how common `unallow` is but it's a word https://www.merriam-webster.com/dictionary/unallowed

Yeah, the names could have been thought out better, but it's too late now. Maybe in 2.0 😄
