### ISSUE TITLE
Unable to define PascalCase column names for relations

### ISSUE THREAD

**Issue by rmp135** [Vincit/objection.js#613]
Not sure if I've missed something in the docs but I'm having trouble setting the `to` and `from` tables for relationships to use PascalCase column names e.g. `Game.CardID`, it just refuses to enter the column into the `insert` statement. I've managed to get around this by using ~~camelCase~~ snake_case but it took hours to figure out. You might want to make it more obvious in the documentation that this format is required.

**Comment by koskimas** [comment]
If you don't have any case conversion set up for your models you need to give every column in the database format. If your columns are pascal cased in the db, then use pascal case in relation mappings. If they are snake cased, then use snake case. Objection doesn't require you to use any specific casing. You have probably messed something else up. If you post your migrations and models here I may be able to help.

The next version will have a better snake case conversion system. It's already in the master, but not yet released.

**Comment by rmp135** [comment]
I don't have case conversion setup.

My models couldn't really simpler.

```javascript
export default class CardModel extends Model {
  static get tableName() {
    return 'Card'
  }
  static get relationMappings() {
    return {
      game: {
        relation: Model.BelongsToOneRelation,
        modelClass: GameModel,
        join: {
          from: 'Card.GameID',
          to: 'Game.ID'
        }
      }
    }
  }
}
export default class GameModel extends Model {
  static get tableName() {
    return 'Game'
  }
  static get relationMappings() {
    return {
      cards: {
        relation: Model.HasManyRelation,
        modelClass: CardModel,
        join: {
          from: 'Game.ID',
          to: 'Card.GameID'
        }
      }
    }
  }
}
```
The database columns are in pascal case.
If I keep the relations in pascal case and attempt to perform a graph insert
```javascript
GameModel.query().graphInsert({
  cards: [{ Text: 'card a' }, { Text: 'card b' }]
})
```
The ID columns of the cards are skipped. If I change the case of the relation to camel case then they do insert but performing a select with `eager('cards')` fails (it was performing two queries with a 'where 1 = ?' on the cards, very strange). The only remedy was to change both database and relation names to snake case.

**Comment by koskimas** [comment]
The default id column is lowercase `id`. You probably need to add this to your models:

```js
static get idColumn() {
  return 'ID';
}
```

**Comment by koskimas** [comment]
Was that it?

**Comment by rmp135** [comment]
Looks like that fixed it. Thanks.
