### ISSUE TITLE
knexSnakeCaseMappers is undefined

### ISSUE THREAD

**Issue by cemremengu** [Vincit/objection.js#618]
Are snake_case conversions discussed in docs included in `0.9.0` ?
```
// knex conversion
...knexSnakeCaseMappers()
```

This turns out to be undefined for some reason

**Comment by koskimas** [comment]
The docs in the repo are for the master branch. The docs for the released version are [here](http://vincit.github.io/objection.js/). `knexSnakeCaseMappers` are not yet released.
