### ISSUE TITLE
QueryBuilder.range implementation

### ISSUE THREAD

**Issue by Biktop** [Vincit/objection.js#62]
I have learnt that _QueryBuilder.range_ executes two queries (first for getting result and second for total count). As far as I know it could be implemented in more effective way for Postgres and MySQL as well.
In [Stack-overflow question](http://stackoverflow.com/questions/156114/best-way-to-get-result-count-before-limit-was-applied-in-php-postgresql) is described technics for both databases.

I think that at least details of _range_ implementation should be mentioned in the documentation.

**Comment by elhigu** [comment]
Interesting I didn't know the way mentioned in stackoverflow either :) 

I would like to see some performance test on this. I'm not 100% confident that getting count the way mentioned in stackoverflow is more efficient especially if `order by` is used in query.

If I remember correctly objection drops `order by` part of count query, which makes it really fast in comparison to of getting count from query having `order by` (even that count() is used at least postgres order whole result and not only until offset + limit).

**Comment by Biktop** [comment]
Related to Postgres I guess that `order by` is omitted in case of window function. It's described [here more details](http://www.postgresql.org/docs/current/interactive/tutorial-window.html).

Any way I think that the documentation could be updated to show more details related to implementation. I thought that `range` is just wrapper for knex function but it turns out that it own implementation.

I will probably make performance test in Postgres.

**Comment by koskimas** [comment]
I have been trying to write the same code for all three databases (postgres, mysql and sqlite) and that is the only solution that works for all three. I'd be interested in the results of you're performance tests if you make some. If the performance is significantly better, It is a good reason to write separate implementations for different databases.

You are right about the documentation. I will add a mention that two queries are performed.

**Comment by koskimas** [comment]
I'll try to implement `range` and `page` using the special database features for postgres and mysql. We'll see how it goes.

**Comment by koskimas** [comment]
I did some research:

## Mysql

`SQL_CALC_FOUND_ROWS` seems to be significantly slower than just doing two queries when the database has proper indexes for the query. If you do paged searching and don't have indexes, you are screwed anyways. I also ran my own simple tests with a table with million rows, and two separate queries was around twice as fast.

In addition to this, knex doesn't seem to support adding options for select (note that `SQL_CALC_FOUND_ROWS` is not just a item in the select list but an option). Implementation would be a hack.

https://www.percona.com/blog/2007/08/28/to-sql_calc_found_rows-or-not-to-sql_calc_found_rows/

## Postgresql

Using `select(*) over () as total` seems to perform better than two separate queries in my simple tests (same db that was used in mysql tests). I also couldn't find anything on the internet that suggested the window function approach to be slower. I'll start using the window function version for postgresql

**Comment by bharathiram** [comment]
@koskimas Did you guys rollback this fix for postgres? It is still generating 2 queries for range(). One actual query & another count query.I don't see these changes (73edf6d) in the new build.

```
searchQuery
        .limit(params.limit)
        .offset(params.offset)
        .range();
```

**Comment by koskimas** [comment]
Nope

**Comment by koskimas** [comment]
This was never fixed
