### ISSUE TITLE
$loadRelated in docs is confusing

### ISSUE THREAD

**Issue by wubzz** [Vincit/objection.js#621]
I have a `relationMapping` with a default `modify` filter to always ensure my model only loads reations based on `>= TimeStamp`, which works great.

In another part of my application, I want to load all relations with an additional condition: `TimeStamp <= maxDateTime`.

The following is described in docs as a valid filter so it seemed like the obvious choice:
```javascript
await this.$loadRelated('*', (queryBuilder) => queryBuilder.andWhere('TimeStamp', '<=', maxDateTime));
```

![objection](https://user-images.githubusercontent.com/10179061/32830944-13ade0ea-c9f7-11e7-8f75-dc6837e8d2cf.png)

Unfortunately the filter function is not being called at all. Using named filters does not seem like an option since there's no way to submit `maxDateTime` to such a function.

Am I completely misinterpreting the docs? Thanks.

**Comment by wubzz** [comment]
I also tried using `.modifyEager('*', (queryBuilder) => ...)` but it yielded the same issue.

**Comment by wubzz** [comment]
@koskimas Ah, that explains a lot. Thanks, closing this!

As for `*` I had a feeling it was wrong, but having to type out relation names in plain strings while they're already part of the `relationsMapping` was really a turn off for me. Are there any alternative ways to eager-load all relations without having to specify the list?

**Comment by koskimas** [comment]
Unfortunately there isn't. Are you loading nested relations? If not, you could always do something like this:

```js
const eagerAll = `[${
  Object.keys(Person.relationMappings)
    .map(it => it.name)
    .join(',')
}]`;

Person.query().eager(eagerAll)
```

**Comment by koskimas** [comment]
There is a way to hook into all executed queries without the need for eager filters, but it's in no way obvious from the docs. This is fully supported though:

```js
Person
 .query()
 .eager(eagerAll)
 .mergeContext({
   // Called when building queries in the same "context", meaning all
   // queries stared by this query.
   onBuild(builder) {
    builder.where('TimeStamp', '<=', maxDateTime);
   }
 });
```

**Comment by wubzz** [comment]
Yeah I'm using deeply nested relations. I ended up still taking the risk of using `*`, but unfortunately using `*(filter)` did not work either, so had to do this:

```javascript
const filters    = ['addMaxDateTimeCondition'];
const expression = `[${_.map(_.keys(Model.relationMappings), (relationName) => `${relationName}(${filters.join(', ')}).[*]`).join(', ')}]`;

//[relation1(addMaxDateTimeCondition).[*], relation2(addMaxDateTimeCondition).[*']]
```

**Comment by wubzz** [comment]
For anyone coming here from searches, the above example no longer works in v1+ as '*' is not recognized as a valid expression anymore.
