### ISSUE TITLE
How to intercept all update query from a $beforeUpdate in a shared Base class

### ISSUE THREAD

**Issue by marcpearson** [Vincit/objection.js#622]
I presently using Objection.js for a project for the first time.

But i try to do something special but i can’t make it work, let me explain

I have a BaseModel (extended from Objection.js Model) shared for all my model class

The BaseModel class contains a $beforeUpdate(opt, queryContext) method.
In this method, i try to intercept the current query (coming from all model) to append
a where condition so this way all update will have a «mandatory» where.

I tried many many way with: this, BaseModel, query(), $query(), queryContext.transaction
but nothings work and i can’t find any example on the net.

**Comment by koskimas** [comment]
I should warn you though that this can have some unwanted side effects.

**Comment by marcpearson** [comment]
OK but how  i my suppose to write my $beforeUpdate hook in my BaseModel to append a where condition to the «current» update query ? Can you give me an example please ?

**Comment by koskimas** [comment]
```js
$beforeUpdate(opt, queryContext) {
  queryContext.builder.where(...)
}
```

**Comment by marcpearson** [comment]
i tried your example as is but i got : TypeError: ModelClass.QueryBuilder.forClass is not a function
My code use typescript typings

**Comment by koskimas** [comment]
Are you sure your custom builder extended `Model.QueryBuilder` correctly?

**Comment by koskimas** [comment]
Or is that a typescript error? In that case I don't know how to fix it. I don't use typescript and I haven't written the typings. Maybe @mceachen can help?

**Comment by marcpearson** [comment]
There is no way to access the current query context in the $beforeUpdate without writing my custom QueryBuilder class ?

**Comment by koskimas** [comment]
Yes you can access the query context. It's always there as the second argument. It just doesn't contain the query builder you need to add the `where` call. The custom method I suggested adds a `builder` property to the `queryContext` so that you can access the current query builder.

**Comment by koskimas** [comment]
You could also override the `QueryBuilder#update` method and add your `where` there?

**Comment by mceachen** [comment]
@koskimas if you want, please provide sample code for the context method, so I can add it to the typings tests and make sure everything works as expected.

**Comment by marcpearson** [comment]
I tried this (base on the answer from @koskimas)  but it doesn't work:

import { Model, QueryBuilder } from 'objection';

class CustomQueryBuilder extends QueryBuilder<Model> {
  context(...args) {
    const result = super.context(...args);

    if (args.length === 0) {
      // When there are no args, `context()` is used as a getter.
      result.builder = this;
    }

    return result;
  }
}


Typescript complain about class CustomQueryBuilder not extended correctly the QueryBuilder class

I'm not an expert with typescript so i'm stuck ...

**Comment by marcpearson** [comment]
I found this [https://github.com/alekbarszczewski/knex-hooks](https://github.com/alekbarszczewski/knex-hooks) and works very well for what i need to do.
Maybe you should give a way to access the «current» QueryBuilder without the need to write a custom querybuilder class

**Comment by koskimas** [comment]
Modifying the query in hooks is not the best idea. That's why the query is not passed to them. The hooks are instance methods and are called to each model instance. The same query can operate on multiple model instances. If you modify that kind of query in a hook, you modify the query N times (where N is the number of model instances).

**Comment by carotorrehdz** [comment]
@marcpearson have you found a workaround for your problem? I need exactly the same, every single query must contain a where condition and it doesn't look logic having to repeat code for each query.
