### ISSUE TITLE
Problems while using #dbRef

### ISSUE THREAD

**Issue by timho93** [Vincit/objection.js#629]
Hey, i am running into trouble while using #dbRef. 

This is my Code:
```
Conversation
    .query()
    .insertGraph([{
      msg_id : req.message.id, 
      participants:[
        {"#dbRef": req.message.receiver_id},
        {"#dbRef": req.message.sender_id}
      ]}])
      .then(conversation => {
        console.log(conversation);
        req.conversation = conversation;
        return next();
    })
    .catch( err => {
      next(err);
    }); 
```
In the Model of Conversation there is the following relationMapping:
```
participants: {
                relation  : Model.HasManyRelation,
                modelClass: __dirname + '/User',
                join      : {
                    from   : 'message_conversations.id',
                    through: {
                        from: 'message_conversation_participants.conversation_id',
                        to  : 'message_conversation_participants.user_id'
                    },
                    to     : 'users.id'
                }
            }
```

This results in a situation where it tries to insert a new User. 
```
Error: insert into `users` (`#dbRef`, `id`) values (2, 33) - Unknown column '#dbRef' in 'field list'
    at Packet.asError (/Users/timhofer/Documents/GitHub/fa17g16/node_modules/mysql2/lib/packets/packet.js:713:13)
    at Query.Command.execute (/Users/timhofer/Documents/GitHub/fa17g16/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/Users/timhofer/Documents/GitHub/fa17g16/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/Users/timhofer/Documents/GitHub/fa17g16/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/Users/timhofer/Documents/GitHub/fa17g16/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.
```

Whats wrong with my Code ???

Thanks,
Tim

**Comment by elhigu** [comment]
Shoudn't `#dbRef` to be used for rows that are added inside the same graph insert. If you have already rows in DB which you are going to relate 4th example of http://vincit.github.io/objection.js/#graph-inserts might work for you?

**Comment by timho93** [comment]
Tried this already. Code:
```
function createConversation(req, res, next){
  console.log(req.message.id);
  console.log(req.message.receiver_id);
  console.log(req.message.sender_id);

  Conversation
    .query()
    .insertGraph([{
      msg_id : req.message.id,
      
      participants:[
        {id: req.message.receiver_id}]
    }, {
      relate: true
    }])
    .catch( err => {
      next(err);
    }); 
}
```
Error:
```
Error: insert into `message_conversations` (`created_at`, `relate`) values ('2017-11-22T16:19:00.332Z', true) - Unknown column 'relate' in 'field list'
    at Packet.asError (/Users/timhofer/Documents/GitHub/fa17g16/node_modules/mysql2/lib/packets/packet.js:713:13)
    at Query.Command.execute (/Users/timhofer/Documents/GitHub/fa17g16/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/Users/timhofer/Documents/GitHub/fa17g16/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/Users/timhofer/Documents/GitHub/fa17g16/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/Users/timhofer/Documents/GitHub/fa17g16/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.
```

Any idea of what could be wrong? Not only with respect to the code but also with how we use it.

Thanks

**Comment by elhigu** [comment]
Are you using the latest objection?

**Comment by timho93** [comment]
We are using the version 0.9.2. Could this problem result out of a conflict with the objection-find module ?

```
├─┬ UNMET PEER DEPENDENCY objection@0.9.2
│ └─┬ ajv@5.4.0
│   ├── co@4.6.0
│   ├── fast-deep-equal@1.0.0
│   ├── fast-json-stable-stringify@2.0.0
│   └── json-schema-traverse@0.3.1
```

`npm ERR! peer dep missing: objection@^0.8.0, required by objection-find@0.5.1`

**Comment by kapouer** [comment]
objection-find is not yet compatible with objection 0.9. However i'll probably take care of it later today.

**Comment by timho93** [comment]
So you recommend to use only one of it at a time =

**Comment by kapouer** [comment]
objection-find is going to be broken with objection 0.9 at some places.
However the issue here doesn't seem to be related to objection-find.

For example in https://github.com/Vincit/objection.js/issues/629#issuecomment-346400943 you misplaced the `{relate: true}`parameter inside the array parameter.

**Comment by timho93** [comment]
> For example in #629 (comment) you misplaced the {relate: true}parameter inside the array parameter.

If i compare the placement in my code with the example in your documentation, i can't recognize any differences.

<table>
<tr>
<td>MyCode</td>
<td>Code from your Doc </td>
</tr>
<tr>
<td>

```
.insertGraph([{
      msg_id : req.message.id,   
 
      participants:[{
        id: req.message.receiver_id
      }]
    }, {
      relate: true
    }])
```

</td>
<td>

```
.insertGraph([{
    firstName: 'Jennifer',
    lastName: 'Lawrence',

    movies: [{
      id: 2636
    }]
  }, {
    relate: true
  }])
```

</td>
</tr>
<table>

**Comment by chilly2go** [comment]
Thanks for the Answer. If we do it like that objection does not treat `relate` as a field that has to be inserted.
But it still does not relate the inserted (for us `conversation`) and the supplied user identified by an ID.
If we execute it we get error messages based on the jsonSchema of the related model of the `participants` relation.

**Comment by koskimas** [comment]
@kapouer Nice catch! I'll fix that typo.
