### ISSUE TITLE
Eager loading fails in postgres

### ISSUE THREAD

**Issue by afm-sayem** [Vincit/objection.js#63]
Seems like eager loading is not working for postgres databases. The fields get populated in sqlite but when I switch to postgres, the fields are returned nulll.

**Comment by kapouer** [comment]
Using which version of objection ? They do load here with postgres.

**Comment by koskimas** [comment]
I have hundreds of tests that say otherwise :D Could post some more details about the failing eager query and your setup?

**Comment by afm-sayem** [comment]
Nevermind. While posting the sample code I realised I changed the column name of the foreign key but forgot to do the same in `relationshipMappings`. False alarm. :camel:
