### ISSUE TITLE
"Snake case to camel case conversion" recipe example fails to work

### ISSUE THREAD

**Issue by igor-savin-ht** [Vincit/objection.js#630]
```
const Knex = require('knex');
const { knexSnakeCaseMappers } = require('objection');

const knex = Knex({
  client: 'postgres',

  connection: {
    host: '127.0.0.1',
    user: 'objection',
    database: 'objection_test'
  }

  // Merge `postProcessResponse` and `wrapIdentifier` mappers.
  ...knexSnakeCaseMappers()
});
```

  ...knexSnakeCaseMappers() seems to rely on spread support which only landed in 8.x. Also I wonder if there is a missing comma in the preceding line, current version doesn't look valid JS to me.

Is there a non-spread version of the same code (it's ok if it is somewhat more verbose) that would work with NodeJS 6/7?

**Comment by Palisand** [comment]
http://vincit.github.io/objection.js/#objection-knexsnakecasemappers

See "For older nodes"

**Comment by igor-savin-ht** [comment]
@Palisand Thanks! Recipe probably should include link to that as well as it's not very intuitive to search for it there :)

**Comment by Palisand** [comment]
The link is on `knexSnakeCaseMappers`.
