### ISSUE TITLE
Using views for select but the base table for inserts

### ISSUE THREAD

**Issue by jeff3yan** [Vincit/objection.js#631]
I'd like to create a SQL view that contains a couple of computed columns on a specific table.

It'd be ideal if _find_ queries on the objection model used the view, and any inserts/updates/deletes referenced the base table.

Is there any way to achieve this in an objection model, or is this something I should keep in the database layer?

**Comment by jordansexton** [comment]
I use views and matviews and keep separate Objection models for them, so I don't do what you're asking exactly, but you could either override the `insert(Graph)`/`update(Graph)`/`patch`/`delete` methods on a `QueryBuilder` subclass for your views to delegate the calls to a different model, or possibly use  [`QueryBuilder#isFindQuery`](http://vincit.github.io/objection.js/#isfindquery) in the execute method to do it.

Something like this (untested and hacky):

```javascript
class ViewQueryBuilder extends Model.QueryBuilder {
    execute (...rest) {
        if (this.isFindQuery()) {
            return super.execute(...rest);
        }
        else {
            let modelClass = this.modelClass();
            let delegatesWritesTo = modelClass.delegatesWritesTo;
            if (modelClass === delegatesWritesTo) {
                return super.execute(...rest);
            }
            else {
                return delegatesWritesTo.query()
                    .childQueryOf(this)
                    .copyFrom(this)
                    .execute(...rest);
            }
        }
    }
}

class View extends Model {
    static get delegatesWritesTo () {
        return this;
    }

    static get QueryBuilder () {
        return ViewQueryBuilder;
    }
}

class SomeView extends View {
    static get delegatesWritesTo () {
        return SomeModel;
    }
}
```

**Comment by elhigu** [comment]
Probably the easiest is to have separate model for the view and for the normal table and decide which one to use per query basis. Though im not familiar with your use case. Is it impossible to decide which model to use query basis?

**Comment by jeff3yan** [comment]
I'll go with the separate model for the view, and manually call it for now. It's definitely possible to decide what model to use on a per-query basis using `this.isFindQuery()`.

I'll also give the delegated query builder a try as I wasn't aware of that method. Thanks!
