### ISSUE TITLE
JSON API support

### ISSUE THREAD

**Issue by chamini2** [Vincit/objection.js#632]
I wanted to know if there is any support for going from Objection to JSON API (http://jsonapi.org/format/).

Are there any known plugins for it? I searched a bit and could only find stuff regarding the JSON API of Postgres from Objection.

**Comment by elhigu** [comment]
I haven’t heard that anyone has been working on it.

**Comment by jamesdixon** [comment]
@chamini2 funny I find this question being asked by you? Abandoning Bookshelf? Thinking about doing the same and was looking for something similar to our mapper

**Comment by chamini2** [comment]
Yeah @jamesdixon! I even saw you work on [some Objection stuff](https://github.com/scoutforpets/objection-password). I am searching for something similar to jsonapi-mapper too! I even wrote to you on Gitter to see if you had any ideas on what to do.

No luck finding a mapper to JSON API?

**Comment by jamesdixon** [comment]
Sorry about the no-reply on Gitter! I haven't been on there in ages!

I haven't found anything, so I'm guessing we'll probably need to write something. I haven't looked deep enough into the Objection object model, but it appears simpler from what I recall (used it on another project). I'm not sure if it can fit in as another ORM under the mapper or not.

Thoughts?

**Comment by jamesdixon** [comment]
Btw, Bookshelf is definitely becoming problematic on our end as well. Admittedly, it would be quite a large refactor and I'm nervous to undertake it given the number of hacks and other things I put in place to "fill the gaps."

**Comment by chamini2** [comment]
I was thinking that if I found no mapper I would use the jsonapi-serializer directly for a while to understand what kind of objects I need to be passing in it. And when I have a good understanding on it I planned on working in a jsonapi-mapper version.

**Comment by jamesdixon** [comment]
Makes sense. Let me know if you decide to embark on creating a library/adding it to jsonapi-mapper.

Have you guys made the transition yet? If so, has it been painful?

**Comment by jamesdixon** [comment]
I messaged you on GItter; feel free to reply there.

**Comment by haywirez** [comment]
Would be interested to hear about this as well 👍

**Comment by chamini2** [comment]
I ended up using the https://www.npmjs.com/package/json-api-serializer package for serialization.

**Comment by honestserpent** [comment]
@chamini2 good reviews on that package?

**Comment by chamini2** [comment]
Yeah, totally. The maintainer is replies fast and works as expected.

**Comment by honestserpent** [comment]
awesome, thanks!

**Comment by honestserpent** [comment]
@chamini2 can I ask you how you used the `json-api-serializer` packege? Did you implement the serializization and deserialization in the `$parseJson` and `$formatJson`? Do you have a working example that I can look at?

Cheers

**Comment by chamini2** [comment]
Define your resources like:

```ts
const JSONAPISerializer = require('json-api-serializer');

const Serializer = new JSONAPISerializer({
  convertCase: 'kebab-case'
});

Serializer.register('activities', {
  id: 'id'
});

Serializer.register('guaranteed-dates', {
  id: 'id',
  relationships: {
    activity: {
      type: 'activities'
    }
  }
});
```

To be used like this:

```ts
const gdates = await GuaranteedDate
  .query()
  .innerJoinRelation('activity')
  .where({
    // Published and promoted
    'activity.published': true,
    'activity.promoted': true
  });

const data = Serializer.serialize('guaranteed-dates', map(gdates, (gdate) => gdate.toJSON()));
// data is the JSONAPI object
```
