### ISSUE TITLE
Option to ignore additional properties

### ISSUE THREAD

**Issue by igor-savin-ht** [Vincit/objection.js#634]
Currently it is only possible either to silently include additional (undefined in schema) properties or to throw exception when these are found. It is not currently possible to silently omit fields that are not in the schema during .fromJson instantiation. I presume this could be a new flag in ModelOptions entity that is passed to .fromJson method or an explicit argument for .fromJson method.

I could provide a PR for this functionality if this change is approved.

**Comment by igor-savin-ht** [comment]
@koskimas Could you please comment whether you think that this is an appropriate change? I obviously can implement this change on our consumer part, but my preferred option is to contribute to upstream when it makes sense to.

**Comment by koskimas** [comment]
I think this is easy enough to implement in userland and it shouldn't be added to core:

```js
const { Model, lodash } = require('objection');


class BaseModel extends Model {
  $parseJson(json, opt) {
    const json = super.$parseJson(json, opt);
    return lodash.pick(json, Object.keys(this.jsonSchema.properties));
  }
}
```

Also there is [this](http://vincit.github.io/objection.js/#pickjsonschemaproperties) if it's enought to remove the properties before they get to the database.

**Comment by kapouer** [comment]
This ajv option can also be handy: [removeAdditional](https://github.com/epoberezkin/ajv#filtering-data)

**Comment by igor-savin-ht** [comment]
@kapouer @koskimas Thank you for the extremely useful information! Is there any value in me creating new Recipe PR for the objection.js documentation?

**Comment by koskimas** [comment]
@igor-savin-ht I think a recipe could be useful. The difficult part is to use the correct words so that people find that recipe. I don't think many people find `pickJsonSchemaProperties` because of its name.

**Comment by kapouer** [comment]
Correct me if i'm wrong, but isn't `pickJsonSchemaProperties` only working on top-level properties ?
If i remember well, it's the reason i ended up using `removeAdditional`.

**Comment by koskimas** [comment]
@kapouer That's correct. Its purpose is to remove nonexistent __columns__ from being inserted to database. Nested json objects are unaffected. It works for nested relations though (if they have the flag on).

**Comment by EmileSpecs** [comment]
> I think this is easy enough to implement in userland and it shouldn't be added to core:
> 
> ```js
> const { Model, lodash } = require('objection');
> 
> 
> class BaseModel extends Model {
>   $parseJson(json, opt) {
>     const json = super.$parseJson(json, opt);
>     return lodash.pick(json, Object.keys(this.constructor.jsonSchema.properties));
>   }
> }
> ```
> 
> Also there is [this](http://vincit.github.io/objection.js/#pickjsonschemaproperties) if it's enought to remove the properties before they get to the database.

I'm struggling with allowing the relevant properties when relational data is involved.

Am I correct in saying that relational properties will be removed using `pickJsonSchemaProperties` and `$parseJson` (they are when I use this)?
If I also manually add my relational properties to the pick list I can get those to be included, but then what about `extra` columns used in many-to-many relationship join tables?

If I also add the join table columns it'll work when making requests that include that relation but it'll throw an error if I just simply patch base model object.

```
$parseJson(json: Object, opt: ModelOptions) {
    const properties = (this.constructor as typeof ExerciseModel).jsonSchema.properties || {};
    const allowedProperties = Object.keys(properties);
    const allowedRelationalProperties = ['relations'];
    const allowedRelationalExtraProperties = ['relation'];

    json = super.$parseJson(json, opt);

    return lodash.pick(json, allowedProperties.concat(allowedRelationalProperties).concat(allowedRelationalExtraProperties));
  }

static get relationMappings(): RelationMappings {
    return {
      relations: {
        relation: Model.ManyToManyRelation,
        modelClass: ExerciseModel,
        join: {
          from: 'exercises.id',
          through: {
            modelClass: ExerciseRelationModel,
            from: 'exercise_relations.exercise_id',
            to: 'exercise_relations.related_exercise_id',
            extra: ['relation']
          },
          to: 'exercises.id'
        }
      }
}
```

So in the example above I want it to allow `relations` property and the extra `relation` column but only if it's for the relation and not when patching the model without any relational data.

Some of the relations are used for `eager` only and some for `upsertGraph`, so then those also have to be manually added to the `allowedRelationalProperties` list to only allow relations that are allowed by `upsertGraph` to be included.

Hope this makes sense, the manual allowing of the correct properties is a slippery slope. It feels like simply setting an `ignoreUnallowedProperties` option for the model would make things a whole lot easier, or am I completely missing something?
