### ISSUE TITLE
Question: PromiseLike instead of Promise?

### ISSUE THREAD

**Issue by hardeep** [Vincit/objection.js#636]
I'm using the bluebird library, it seems that the type definitions [specify Promise instead of PromiseLike](https://github.com/Vincit/objection.js/blob/master/typings/objection/index.d.ts#L440).

Any reason for using Promise vs PromiseLike? I'd be willing to submit a PR to change it.

**Comment by koskimas** [comment]
@mceachen Could you take a look at this?

**Comment by mceachen** [comment]
@hardeep `Promise` and `PromiseLike` are mostly ducktype compatible, but Promise neither extends nor implements PromiseLike in the TypeScript 2.6.2 typings. You'd have to change every reference to Promise to be `Promise<T> | PromiseLike<T>`, and callers would have to either cast (which is unsafe) or `instanceof` guard those calls if they had consumers that only accepted `Promise`s.

About a year ago I'd tried to use PromiseLike when Promise wasn't necessary in my own projects, but it caused so much signature bloat I ended up only using the Promise signature internally.

If there's a clever way to do this that I'm missing, I'm all ears!

**Comment by mceachen** [comment]
Will reopen if @hardeep or others offer workarounds.

**Comment by Aankhen** [comment]
> You'd have to change every reference to Promise to be Promise<T> | PromiseLike<T>

Has something changed? [This compiles:](https://www.typescriptlang.org/play/#src=function%20foo%3CT%3E(bar%3A%20PromiseLike%3CT%3E)%3A%20void%20%7B%0D%0A%20%20%20%20bar.then(alert)%0D%0A%7D%0D%0A%0D%0Afoo(new%20Promise((resolve%2C%20reject)%20%3D%3E%20resolve(1)))%3B%0D%0A)

```typescript
function foo<T>(bar: PromiseLike<T>): void {
    bar.then(alert)
}

foo(new Promise((resolve, reject) => resolve(1)));
```

Of course, consumers that only accept `Promise` are another story.

**Comment by mceachen** [comment]
@Aankhen the typings were changed a while back from `PromiseLike` to `Promise`.
