### ISSUE TITLE
inst.$query().patch(data) need skipUndefined ?

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#638]
I might be confused but in some places i use `patch`, i now need to add `skipUndefined` as well.
Since version 0.9.2.

Typically in here:
```
site.$query().where('id', site.id).patch(data)
```

but not here:
```
SiteModel.query().where('id', site.id).patch(data)
```

Is this me not understanding the use case for `$query()` ?

**Comment by kapouer** [comment]
Correction: using version 0.9.2. It probably existed before.

**Comment by koskimas** [comment]
`site.$query()` already adds the `where('id', site.id)` part to the query and you shouldn't add it yourself.

**Comment by kapouer** [comment]
I think it's the case here. I don't want to expose internal `_id` so i don't select it at all.
In the end i removed the `inst.$query()` calls and just used `Model.query()` to avoid confusion.
