### ISSUE TITLE
`where*Exists` in `insert`

### ISSUE THREAD

**Issue by newhouse** [Vincit/objection.js#640]
Hi there!

Let's say I have `Post`, `Campaign` and `Organization` models/tables:
- `Post` requires `organization_id`, which is an FK to a `Organization`.
- `Post` has an optional `campaign_id`, which is an FK to a `Campaign`.
- `Campaign` requires `organization_id`, which is an FK to an `Organization`

I want to allow users to create a `Post` that relates to a `Campaign`, but I want to ensure that the `Campaign` it might relate to is connected to the same `Organization` that they are trying to relate the `Post` to.

Example wishful pseudocode:
```
const data = {
  // An Organization with this ID exists
  organization_id: 123,
  // A Campaign with this ID exists, but it may not be related to the same Organization ID listed above.
  campaign_id: 456
};

Post
  .query()
  .insert(data)
  .whereExists(
    Campaign
      .query()
      .select(1)
      .where({
        id: data.campaign_id,
        organization_id: data.organization_id
      })
  )
  .then(console.log)
  .catch(console.log);
```

All the combinations I've tried with `insert` + `whereExists` have led to no `whereExists` clause being generated, at least not as far as I can tell. I've found [this Objection issue](https://github.com/Vincit/objection.js/issues/447) to the closest to my situation but while it started out like mine, but turned to an `upsert` question.

I suppose the SQL I want is something like this:
https://stackoverflow.com/questions/15710162/conditional-insert-into-statement-in-postgres
or this:
https://dba.stackexchange.com/questions/112431/how-to-use-a-value-from-insert-in-conditional-insert-in-postgres

Which I realize is quite different than a normal `insert`...but is it supported in Objection? Or any idea how to accomplish what I'm trying to do?

I've also found these:
https://github.com/tgriesser/knex/issues/1323 
https://github.com/tgriesser/knex/issues/1322
https://github.com/tgriesser/knex/issues/211

Thanks for any help!!!

**Comment by koskimas** [comment]
Something like this is possible with knex

```js
      knex
        .into('post')
        .insert(
          knex()
            .selectRaw("'your', 'property', 'values'")
            .from('campaign')
            .whereExists(...)
        )
```

but unfortunately it's not possible with objection. Even if it was, you would basically need to write the same exact raw query. You probable need to drop down to knex or raw SQL with this one.

**Comment by newhouse** [comment]
@koskimas thanks for the reply. I was afraid you'd say that...oh well.

On this note, is there any way to utilize the `Post` model a bit to:
1) perform validations on `data`
2) perform any `$beforeInsert` changes on data/`data` (my `Post` model has a `$beforeInsert` hook that adds some stuff like timestamps)
3) dump out something I can use to generate the insert column names and `values()` clauses

There's probably a hook/method or 2 that I can leverage here?
