### ISSUE TITLE
Question: Is it possible to return an array of object ids from eager query?

### ISSUE THREAD

**Issue by pwalczyszyn** [Vincit/objection.js#641]
I would like to make an `eager` query that would return me a flat array of IDs of related objects.

So instead of something like this:
```
{
eagerRelationProperty: [{id: 1}, {id:2}...]
}
```
I would like to get:
```
{
eagerRelationProperty:  [1,2]
}
```
Is this possible to achieve in any way? Basically what I need is something like `pluck` function that I can apply to eager relations.

**Comment by elhigu** [comment]
As far as I know that is not possible. 

You need to write your own helper function which does that transformation after fetching data with nested relations. You can probably hook that helper to `runAfter()` functions and use for example quer builder context to pass information which attributes should be flattened like that.
