### ISSUE TITLE
Empty array on ManyToMany relations

### ISSUE THREAD

**Issue by antonyarchukcodemotion** [Vincit/objection.js#643]
I have an app with models: `User`, `Application`, `Role`. And I have a `users_apps_roles` bridge table, so one user can have one role in each application.

my relation mapping of the User model:
```
rolesInApps: {
        relation: Model.ManyToManyRelation,
        modelClass: Role,
        join: {
          from: `users.id`,
          through: {
            from: `users_apps_roles.user_id`,
            to: `users_apps_roles.role_id`
          },
          to: `roles.id`
        }
```

Now I'd like to get a list of roles for a user.
I'm trying to `User.query().where('id', userID).first().eager('rolesInApps');` but all the time I'm getting an empty array. With casual joins I can get the roles list, so it is not about the invalid data.

Is it a bug or I'm doing something wrong?

**Comment by koskimas** [comment]
No it's not a bug for sure. This kind of code is used by basically everyone that uses objection. Also objection has over 2000 tests that cover a wide variety of eager queries. There is something else going on. Could you create a reproduction I can debug?
