### ISSUE TITLE
How to handle Enum values?

### ISSUE THREAD

**Issue by Trellian** [Vincit/objection.js#646]
Hi, 

Can anyone tell me how Enums are/should be handled in Objection.js? I have found nothing in the documentation so far, and only oblique references to it in the Issues? Does anyone have an example I can look at?  How is/would it be handled in the jsonSchema?

Thanks!

**Comment by koskimas** [comment]
Hi,

Here are the results of 20 seconds of using google:

[JSON schema documentation on enum](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1.2)
[knex documentation on enum](http://knexjs.org/#Schema-binary)

You're welcome.

**Comment by Trellian** [comment]
Thanks @koskimas , I could slap myself!

**Comment by developer239** [comment]
🤡

<img width="1846" alt="image" src="https://github.com/Vincit/objection.js/assets/14946081/f20dce5b-14d6-427e-98b8-b0ca3331fc4f">
