### ISSUE TITLE
How to add parameter sanitification?

### ISSUE THREAD

**Issue by honestserpent** [Vincit/objection.js#651]
I have setup my Objection models and I can work fine with them.

I have mapped my models to the DB, but I have a problem sanitizing the input. For instance, I want to trim my _string_ fields in order to remove leading and trailing white spaces.

Something like https://github.com/chriso/validator.js maybe?

How is this possibile? What is the proper way?

**Comment by koskimas** [comment]
You can implement the `$parseJson` model hook:

```js
class SomeModel extends Model {
  ...
  $parseJson(json) {
    if (json.someField) {
      json.someField = json.someField.trim();
    }

    return json;
  }
  ...
}
```
