### ISSUE TITLE
Querying models' data

### ISSUE THREAD

**Issue by honestserpent** [Vincit/objection.js#654]
What is the way to implement filtering and search on objection models?

I was expecting something like Model.find(_filters_) where _filters_ would be something like [Loopback ones](http://loopback.io/doc/en/lb3/Querying-data.html#examples).

How do I implement this?

**Comment by koskimas** [comment]
See any of the examples or the documentation.

**Comment by honestserpent** [comment]
The only thing I was able to find was explicitly using the knex functions like _where_. But I was wondering if there is any automated thing like that.

Could you tell me which exmaples you are thinking of?

**Comment by koskimas** [comment]
I meant the [example projects](https://github.com/Vincit/objection.js/tree/master/examples). If you read the first couple of sentences from the readme, you'll learn that the whole idea behind objection is that you basically write SQL using a query builder. You need to understand SQL to use objection. If you want a tool that abstracts away SQL, objection is not the right tool for you.

What do you mean by automated? If you bother to read the documentation you'll find a bunch of helper methods like `findOne`, `findById` and you would learn that `where` accepts an object.

**Comment by honestserpent** [comment]
I do understand SQL and I know that the idea behind objection is to use a query builder. But, for instance, there already are commodity methods available such as `findById` which is essentialy a placeholder for `Model.query().select('*').where('id', id)`

I was wondering if there was a similar method to perform filtering.

For instance, say I have the `/people` endpoint and I want to let the user filter the people they search. Say I want them to be able to filter by first_name, last_name, age, provide offset, limit and skip options.

Is my only option to use the `QueryBuilder`? What is the way to deal with optional parameters?
