### ISSUE TITLE
Return single item after deleting single item

### ISSUE THREAD

**Issue by VladShcherbin** [Vincit/objection.js#659]
Same as https://github.com/Vincit/objection.js/issues/423, but for `delete`:

```js
// expected
const user = await User.query().where('id', id).first()
const deletedUser = await user.$query().delete().returning('*')

// current
const deletedUser = await user.$query().delete().first().returning('*')
```

Currently, this returns an array, even if I use `first` in the first query. It would be great to return a single item when `first` was used.

**Comment by koskimas** [comment]
I'd merge a PR for this.

**Comment by VladShcherbin** [comment]
@koskimas sure, I can give it a shot next week.
