### ISSUE TITLE
Change timestamp example to match knex defaults.

### ISSUE THREAD

**Issue by delaneyj** [Vincit/objection.js#66]
The section [discussing timestamps in the docs](http://vincit.github.io/objection.js/#timestamps) is great for showing flexibility.  However the default in knex for table.timestamps() is `create_at` and `updated_at` so probably best to change to match that semantic for clarity.

```jsx
Person.prototype.$beforeInsert = function () {
  this.created_at = new Date().toISOString();
};

Person.prototype.$beforeUpdate = function () {
  this.updated_at = new Date().toISOString();
};
```

**Comment by koskimas** [comment]
Good idea! I will do that.
