### ISSUE TITLE
Should the typings include AjvValidator?

### ISSUE THREAD

**Issue by jtlapp** [Vincit/objection.js#664]
I'm using Typescript with the AjvValidator in a custom query builder. I noticed that the type definitions don't include `Objection.AjvValidator`. Is that intentional? If so, it's easy enough to add it locally.

I realize custom query builders are currently broken with Typescript (#319), but I'm hoping to offer a fix for that. (I'm porting working JS code.)

**Comment by jtlapp** [comment]
After resolving this, I believe that the type does belong in `objection.js`. The signature is specific to this module, requiring people to reverse engineer the code to get it right.

Here's a fix. I'll shortly be working on a fix for #319 and can send a PR for everything at once.

```ts
import * as ajv from 'ajv';

declare namespace Objection {
  /*...*/
  export type AjvConfig = {
    onCreateAjv(ajv: ajv.Ajv): void;
    options?: ajv.Options;
  };
  const AjvValidator: new(config: AjvConfig) => ajv.Ajv;
  /*...*/
}
```

**Comment by jtlapp** [comment]
I've also got a fix for adding the `createValidationError()` tyepdef. Looks like I'll be collecting mods until I've got everything ported.

**Comment by koskimas** [comment]
AjvValidator is a class, not a function that returns an instance of `Ajv`.

**Comment by koskimas** [comment]
To answer the original question, yes the typings should include `AjvValidator`. My previous comment was about your suggested typings.

**Comment by jtlapp** [comment]
Got it. I see what the problem is. The typedef for `Model.createValidator()` is missing too, so Typescript inferred its return value. My code never calls the created object, so everything works.

Okay, looks like I've got more to add thanks.

BTW, the `new` keyword in a typedef defines a constructor rather than a function per se, so the above code effectively includes the Ajv class without redefining it. (Might just be your word choice I'm responding to, in which case I apologize.)

**Comment by koskimas** [comment]
@jtlapp A constructor that returns the wrong type though. `new AjvValidator()` returns an instance of `AjvValidator` which is a wrapper around `ajv.Avj`. `AjvValidator` doesn't inherit `ajv.Ajv`.

**Comment by jtlapp** [comment]
Yeah, got all that. Sorry, I quit when the first thing I threw in satisfied Typescript, not realizing that satisfying Typescript didn't mean the types were right yet.

Okay, I'm going to PR new typings for just the validation stuff. Most of it was missing, but a bit of what was there was also wrong. Plus I may have found a bug in AjvValidator. Will explain below...

**Comment by jtlapp** [comment]
Okay, a number of issues arose for possible discussion during this lucky-numbered PR:

1) The methods of Validator share a `ctx` of `{}`. Rather than create a named type for this, I just called it an `object`, because it only appears within the new type ValidatorArgs.
2) `$beforeValidate()` was typed to return JsonSchema. Objection does not carry forward the return value, so I changed this to `void`.
3) `$validate()` was incorrectly typed, but obviously so. Corrected.
4) `$beforeValidate()` is called from within AjvValidator, but `$afterValidate` is not called from this subclass. Is this a bug? Is either the calling or the failure-to-call a bug?
5) It might be useful for the docs to note that `$validate()` takes precedence over the validator returned by `createValidator()`. I learned this tracing execution in a debugger.
6) I had several occurrences of calls to `beforeValidate()` on a custom Validator (not subclassing AjvValidator) whose `args` argument contained only `{ ctx, json }` and not the full `{ ctx, json, model, options }` that I normally expected. Returning to it later to confirm a recreation, I was unable to recreate it. I guess it's possible I was doing something wrong at the time.

I think that's it. I only started working with Typescript a few months ago and have only gotten into external type declarations recently, so please do double-check my stuff. Thanks!

Oh, there's a bit of irony here. After all this, I find myself inclined to rip out the custom validator. I need to validate at more points than just object creation, so I might as well do it manually with shared validation code. I might still use Ajv though.

**Comment by jtlapp** [comment]
Oh, another item:

7) AjvValidator has more methods than just those that Validator exposes. None are prefixed with an underscore, so I don't know whether which are intended to be externally exposed, which not. I only added the constructor to the AjvValidator subclass.

**Comment by jtlapp** [comment]
8) The docs illustrate returning a value from `$beforeValidate()`. Either the docs are wrong or the code is wrong. The code does not heed a return value.
9) The docs illustrate returning a value from the Validator `beforeValidate()` and `afterValidate()` methods. Again, the code ignores the return values.

**Comment by koskimas** [comment]
@jtlapp 
1. [Objection __does__ use the return value of $beforeValidate](https://github.com/Vincit/objection.js/blob/master/lib/model/AjvValidator.js#L51)
4. $afterValidate is called from the base class, and thus inherited
5. What? `$validate()` uses the validator created using `createValidator`.
8. Same as 1
9. The docs show that a value should be returned for future compatibility. Currently the return value is not used, but in the future we might add a return value. Maybe the return value can be marked as `any` at this point or something.

**Comment by jtlapp** [comment]
I stepped through the debugger. `$beforeValidate`'s value was ignored and `$afterValidate` was not called when `createValidate` returned a `new Objection.AjvValidator`.

Checking now, I see that I was using origin/master for the tests, not the recent pub.

Re 5: When I override `$validate`, `createValidator` does not get called. That's an obvious consequence if `$validate` is calling `createVaidator`.

The problem with the Pojo definition is that it can't be customized for static type checking.

I'll try again with the latest master and get back with you, this time pointing into the code.

**Comment by koskimas** [comment]
`$beforeValidate`s return value was always used. There are tests for it and I never commit anything to master without all tests passing.

**Comment by koskimas** [comment]
Same goes with `$afterValidate` being called. It does work, and has always worked.

https://github.com/Vincit/objection.js/blob/master/tests/unit/model/Model.js#L208
https://github.com/Vincit/objection.js/blob/master/tests/unit/model/Model.js#L239

These are all called by `Validator` or its subclasses. If you implement a custom validator, you need to take care of them being called.

**Comment by jtlapp** [comment]
Okay. Gimme time to check things. I spent most of a day on this last time, coming up with typings.

**Comment by jtlapp** [comment]
Ah poo on `$beforeValidate`. I see why I was mistaken. It's AjvValidator's `beforeValidate` who's return value is ignored (as expected).

However, when returning AjvValidator, VSCode will not run my `$afterValidate` override on a Model. It never gets stepped into, can't breakpoint within it.

And yet the code suggests that it should be called. Still looking into this.

**Comment by jtlapp** [comment]
Aaaaand... I'm missing a `super.$afterValidate` call from a descendant model.

Cancel items (2), (4), and (8). I'm so sorry to waste your time.

With (9), it's only `$afterValidate` that doesn't return a value.

**Comment by jtlapp** [comment]
Looks like our discussion disappeared after my last PR bringing things current. I opted to do the following to get static type checking on declared properties and pojo behavior otherwise:

```ts
  export interface ValidatorContext extends Pojo { }

  export type ValidatorArgs = {
    ctx: ValidatorContext,
    model: Model,
    json: Pojo,
    options: ModelOptions
  }
```

ValidatorContext can be opened to have specific properties constrained, leaving all non-named properties remain unconstrained:

```ts
declare module 'objection' {
    export interface ValidatorContext {
        foo: number;
    }
}
```

The latest also adds the JsconSchema return to back to `$beforeValidate`.

**Comment by jtlapp** [comment]
I'll leave this open as a reminder to add typings test cases. Will get to ASAP.

**Comment by jtlapp** [comment]
You can close this once you merge #722, me thinks.
