### ISSUE TITLE
bindKnex will create subClass without custom static methods and getters

### ISSUE THREAD

**Issue by seeden** [Vincit/objection.js#667]
I am using multi tenancy http://vincit.github.io/objection.js/#multi-tenancy.
When I do

Test.js
```js
import { Model } from 'objection';
export default class Test extends Model {
  static modelName = 'test';
}
```

Request.js
```
import Test from './Test';
const TestModel = Test.bindKnex(knex);

TestModel.modelName === undefined
```

I will get undefined modelName. It is not working for static functions as well.

**Comment by seeden** [comment]
Can I use my own extending of the class with combination Model.knex method?

**Comment by koskimas** [comment]
It does work in objection's tests and it also works in the following runkit:

https://runkit.com/koskimas/bindknextest

**Comment by koskimas** [comment]
`bindKnex` does nothing magical. It uses native inheritance to inherit a subclass.

**Comment by seeden** [comment]
Sorry for that. I have started to use Babel 7 maybe it is the reason. I am going to investigate it.
Standard inherit is working for me as well with knex method.

**Comment by koskimas** [comment]
No problem. Let me know if you find out what's causing that. If it's babel 7, other people will probably have the same problem.

**Comment by juhaelee** [comment]
@seeden did you find a solution for this? i recently upgraded to babel 7 and im getting similar errors
