### ISSUE TITLE
queryBuilder.findById is not a function

### ISSUE THREAD

**Issue by delaneyj** [Vincit/objection.js#67]
findById [is discussed in the docs](http://vincit.github.io/objection.js/#findbyid) but doesn't appear to be accessible on a QueryBuilder instance in version 0.3.3.

Btw I realize that you can add these on a BaseModel, just don't want the docs to confuse users if it has been removed.

**Comment by koskimas** [comment]
Yeah, the docs are already at version 0.4. The 0.4.0-rc.3 will be the actual release version, so I think it is safe to updgrade to that if you want. I'll keep the docs in sync with the actual release version in the future.

**Comment by delaneyj** [comment]
Is there a special tag I need? npm says its [the 0.4 alpha](https://www.npmjs.com/package/objection) but when i do a `npm i --save objection` I get the 0.3.3 version.

**Comment by koskimas** [comment]
I want the people to install the stable release version by default and not an alpha or RC. You have to specify an exact version for npm if you want to use a prerelease version.
