### ISSUE TITLE
Cannot relate HasManyRelation using insertGraph or upsertGraph

### ISSUE THREAD

**Issue by koskimas** [Vincit/objection.js#672]
`upsertGraph` uses `insertGraph` and expects it to do the job, but `insertGraph` cannot relate a `HasManyRelation` because it is an update operation, not an insert. `insertGraph` only inserts stuff.

`insertGraph` should throw an exception in this case and advice the user to use `upsertGraph` instead. `upsertGraph` should just work.

Thank you @Allam76 for bringing this to our attention!

Reproduction provided by @Allam76

```js
const {up, down} = require('./migrations/20150613161239_initial_schema');

async function test(){
    await up(knex);
    var person = await Person.query().insert({id:1,firstName:"Peter",lastName:"Jackson"});
    var pet = await Animal.query().insert({id:1, name:"Mila"});
    var test = await Person.query().upsertGraph({
        id:1,
        pets:[{
            id:1
        }]
    },{relate:true}).debug();
}

test();
```

**Comment by Allam76** [comment]
Ok. I will test now.

**Comment by Allam76** [comment]
It works now in the example model. Thank you for fixing this so quickly!!
