### ISSUE TITLE
Documentation clarification of insertWithRelated

### ISSUE THREAD

**Issue by delaneyj** [Vincit/objection.js#68]
Included in the docs is an example of inserting a graph
```jsx
Person
  .query()
  .insertWithRelated({
    firstName: 'Sylvester',
    lastName: 'Stallone',

    children: [{
      firstName: 'Sage',
      lastName: 'Stallone',

      pets: [{
        name: 'Fluffy',
        species: 'dog'
      }]
    }]
  })
```

Would it be possible when relationship's model is already in the database?   If so if the what is the syntax to do that properly?  Maybe `pets:[fluffyId]` or `pets:[Fluffy]`?  The docs don't really cover this situation.

**Comment by koskimas** [comment]
What you want isn't currently supported directly, but there are workarounds for one-to-one and many-to-many relations. I think it would be a good addition to allow one to give an array of identifiers in place of models, to do this. I'll put this on my todo list.

Workarounds:

For one-to-one relation you already have the join column in the table you want, so you can just set it in the graph like so:

```js
Person
  .query()
  .insertWithRelated({
    firstName: 'Sylvester',
    lastName: 'Stallone',
    parentId: 364621
  });
```

In case of many-to-many relations, you can create a model for the join table and insert those objects to create connections. Let's assume there is a `Movie_Actor` join table between `Person` and `Movie`. You would need to create a `MovieActor` model and a one-to-many relation to that model for `Person`. Let's call the relation `movieConnections`. Then you can do this:

```js
Person
  .query()
  .insertWithRelated({
    firstName: 'Sylvester',
    lastName: 'Stallone',
    
    movieConnections: [{
      movieId: 1235136
    }, {
      movieId: 5652492
    }]
  });
```

This would insert two rows to the join table `Movie_Actor`.

**Comment by delaneyj** [comment]
That's actually a great example, kinda makes me want to drop the auto M2M relations I have as this is more explicit.  Would be great is this was in the docs..

**Comment by koskimas** [comment]
Cool, I'll add that example to the docs. I'm reopening this as a reminder for myself. I'll close this when I've updated the docs and possibly implemented the "array of ids" feature discussed in the first two posts.
