### ISSUE TITLE
get count from relatedQuery |  question

### ISSUE THREAD

**Issue by seeden** [Vincit/objection.js#682]
Is there any simpler option how to get count number from relatedQuery?
Currently I am doing this

```js
    const followersCount = await user
      .$relatedQuery('followers')
      .count('*')
      .pluck('count')
      .first();
```

I have tried next code but it is not working without ```'*'```. With ```'*'``` it will returns array ```[{ count: '22' }]```.
```js
const followersCount = await user
      .$relatedQuery('followers')
      .count();
```

**Comment by koskimas** [comment]
Unfortunately there's no easier way to do that at the moment. `count('whatEver')` simply adds a `SELECT COUNT(whatEver) as count` to the query.

**Comment by seeden** [comment]
I saw one solution for this case in another library. They have function scalar() in query builder. It will take first item from array and first item in the object.

You are able to change next code:
```js
const followersCount = await user
      .$relatedQuery('followers')
      .count('*')
      .pluck('count')
      .first();
```

with
```js
const followersCount = await user
      .$relatedQuery('followers')
      .count('*')
      .scalar();
```

I am not sure if you are intristed. Maybe it can be nice addon to current API

**Comment by seeden** [comment]
@koskimas what do you think about scalar method?

**Comment by andrepcg** [comment]
@koskimas @seeden That scalar method seems to be very useful!

**Comment by seeden** [comment]
@andrepcg  yes it is. The strange thing is that you need to write different code for static and instance method.

static example:
```js
await User
    .query()
    .count('*')
    .pluck('count')
    .first()
```

instance example (without first):
```js
const res = await this
      .$query()
      .where((builder) => {
        builder
          .where('value', '>', value)
          .where({ type });
      })
      .count('*');

 return res.count;
```
