### ISSUE TITLE
relate might insert duplicate rows or cause constraint violations in the join table

### ISSUE THREAD

**Issue by ferrao** [Vincit/objection.js#683]
I have a many-to-many association between two models. Calling `relate` populates the join table properly, but if I call it a second time, it will attempt to insert a duplicate row. This might cause a duplicate or a constraint violation, depending on the db setup.

Is this intended behavior and do I need to check if the relationship already exists before calling relate, or is it a bug?

**Comment by koskimas** [comment]
Totally intended for multiple reasons.

1. Sometimes duplicate rows are actually needed
2. Checking for duplicates would require a separate query and to make the operation atomic, a transaction would need to be enforced.

The best way to deal with this is a unique constraint and catching the violation error.

**Comment by ferrao** [comment]
Thanks for the prompt reply @koskimas! Happy new year to the Objection team!

**Comment by ferrao** [comment]
@koskimas, just realized one thing regarding this issue. It is quite hard to catch the violation error in a way that is agnostic to the specific database being used. SQLITE will throw an error with `error.errno === 19`, Postgres something with `error.code === 23505`, etc. 

I wanted to make this code solid enough to work across the different DB engines supported by knex, but without breaking every time something changes on that side..

I guess I will have to check if the relation already exists beforehand, probably opening a transaction for that, exactly what you describe in 2) but just wanted to double check I was not overlooking something...

**Comment by ferrao** [comment]
Just came across [objection-db-errors](https://github.com/Vincit/objection-db-errors), perhaps it is what I am looking for, will have a look :)
