### ISSUE TITLE
How would you implement logging with objection?

### ISSUE THREAD

**Issue by tnrich** [Vincit/objection.js#69]
Hey there,

I was wondering how you'd go about implementing "activity logging" using objectionjs. Bookshelf, for example, gives some nice hooks on its model objects like "onCreated", "onSaved", etc. which greatly aid in the logging of user activity. 

Does objectionjs have something similar, and if not, how would you go about determining if, say, a user created a new record and logging that action?

Thanks!

**Comment by koskimas** [comment]
Hi,

You can override the [`$afterInsert`](http://vincit.github.io/objection.js/#_s_afterinsert) and [`$afterUpdate`](http://vincit.github.io/objection.js/#_s_afterupdate) methods of a model:

```js
class User extends Model {
  $afterInsert() {
    console.log(`user ${this.username} created`);
  }
  $afterUpdate() {
    console.log(`user ${this.username} updated: ${JSON.stringify(this)}`);
  }
}
```

**Comment by tnrich** [comment]
Hmm thanks for the info!
