### ISSUE TITLE
Getting query options in $beforeUpdate for non-instance queries?

### ISSUE THREAD

**Issue by mikefowler** [Vincit/objection.js#695]
Is it possible to reference arguments passed to `updateAndFetchById` (for example) inside of a model's `$beforeUpdate` hooks? If not, is there a better way to go about this?

```js
class User extends Model {
  $beforeUpdate(context) {
    const maybePromise = super.$beforeUpdate(context);

    return Promise.resolve(maybePromise).then(() => (
      // How do I perform a side-effect using the provided ID?
    ));
  }
}

User.query().updateAndFetchById(3, {
  firstName: 'Mike',
  lastName: 'Fowler',
});
```

I am still wrapping my head around Objection/Knex, so I expect the answer may be "just fetch a model and use `.$query` from the instance".

**Comment by koskimas** [comment]
There's no way to access the id currently. You can fetch a model and use `.$query()`, but that's generally not "idiomatic objection code". Objection encourages you to do things the SQL way when possible.

If you want, you can (pretty) easily override `updateAndFetchById` and store the id to `context`:

```js
class CustomQueryBuilder extends Model.QueryBuilder {
  updateAndFetchById(id, obj) {
    // The same propery name `$query` uses. You can use whatever name you want though.
    this.mergeContext({old: {id}});
    return super.updateAndFetchById(id, obj);
  }
}

...

class BaseModel extends Model {
  static get QueryBuilder() {
    return CustomQueryBuilder;
  }
}

...

class User extends BaseModel {
  $beforeUpdate(context) {
    const maybePromise = super.$beforeUpdate(context);

    return Promise.resolve(maybePromise).then(() => (
      const id = context.old.idM;
      // How do I perform a side-effect using the provided ID?
    ));
  }
}
```

**Comment by mikefowler** [comment]
Thanks for the great example, @koskimas 💯
