### ISSUE TITLE
Using 'page' on a query with eager loading not loading more than one relation

### ISSUE THREAD

**Issue by davidchalifoux** [Vincit/objection.js#701]
In the [docs](http://vincit.github.io/objection.js/#eager) it says that using `limit` or `page` on the root query should work, however it's only loading the first relationship(there's 3).

[Here](https://gist.github.com/davidchalifoux/7c0dbf8f904b023fa665651bb0841d34) is a gist of my models. The relationships essentially break down into this:

`Track` belongsTo `User`
`Track` hasMany `Tags` _(through manyToMany)_
`Track` hasMany `likers`  _(through manyToMany between User and Track)_

When trying to query `Track` with eager loading, but **without** `limit` or `page`, all three relationships are loaded without a problem.

However, when trying to query `Track` with eager loading, but **with** `offset` or `page`, only the first relationship to `User` is loaded.

Here's my query:
```
Track
        .query()
        .page(1, 1)
        .eager('[user, tags, likers]')
        .then(tracks => {
            res.json(tracks)
        })
        .catch(err => {
            console.log(err)
            res.send('Error')
        })
```

[Here](https://gist.github.com/davidchalifoux/0724091fe9b9d90e9afa1a21d78869c3) is also a gist of what the response looks like.

Any help would be greatly appreciated!

**Comment by koskimas** [comment]
Are you using JoinEagerAlgorithm?

**Comment by davidchalifoux** [comment]
@koskimas Yes when I try setting it to `JoinEagerAlgorithm` it outputs `user: null` and `likers: []` instead of both being empty when I have it to the default.

**Comment by koskimas** [comment]
There's something wrong with the way you are using it. Its highly unlikely this is a bug since there are hundreds of tests for this kind of simple eager queries in objections test suite. Could you try to reproduce your problem for example using [this file](https://github.com/Vincit/objection.js/blob/master/reproduction-template.js) as a template?

**Comment by koskimas** [comment]
By the way, did you notice that `range` is zero-based. If you want the first result, you need to say `range(0, 0)`.

**Comment by davidchalifoux** [comment]
@koskimas You are correct, it seems to work just fine with the example project. I don't understand what I could have done wrong that would break only when pagination is added though. Maybe I need to use an alias on `User` since it's technically related in two ways?
In my model a `Track` is owned by a `User`, and has likers who are also users.

(btw thanks for reminding me that `page` is zero-based, I didn't notice that in the docs)

**Comment by davidchalifoux** [comment]
@koskimas Oh my goodness I feel quite dumb right now. I totally forgot that I didn't setup the related data for the second `Track` in the DB, so when I was calling for the second result there was simply no data there to return in the first place.

Thanks for the help!!!
