### ISSUE TITLE
Typings don't support generic use of ModelClass with strictFunctionTypes

### ISSUE THREAD

**Issue by jtlapp** [Vincit/objection.js#702]
To configure objection.js via dependency injection, I pass configuration to per-model repositories that encapsulate access to objection.js behind domain-specific repo APIs. (These are the DI "services" of my #658 inquiry.) The configuration includes the knex connection that the repo is to use. In order to ensure I get the configuration logic right for all such repos, as well as to reduce code redundancy, I have them extending Typescript generic classes that do the job.

I had all this working in my app but decided to see what might pop up porting the `express-ts` example to my DI architecture. The port wouldn't build because I didn't previously have the new `--strictFunctionTypes` restriction enabled but `express-ts` did, by virtue of using `--strict`.

After a bit of investigation, I discovered that the objection.js typings sometimes define overloaded functions as having a type that is a disjunction of signatures. For example:

```ts
  interface QueryInterface<T> {
    //...
    where: Where<T>;
  }

  interface Where<T> extends WhereRaw<T> {
    (callback: (queryBuilder: QueryBuilder<T>) => void): QueryBuilder<T>;
    (object: object): QueryBuilder<T>;
    (column: ColumnRef, value: Value | Reference | QueryBuilder<any>): QueryBuilder<T>;
    //...
  }
```

Under `--strictFunctionTypes`, the `where()` method is technically contravariant, whereby TS guarantees at compile time that if ever `Where<S>` is assigned to the `where` property, then S must either be a T or a supertype of T. That way any method argument satisfying `Where<T>` is guaranteed to also satisfy the assigned `Where<S>`.

Were `Where<T>` instead an interface of named, multiply-overloaded methods, and were `QueryInterface<T>` to instead extend `Where<T>`, the method sigs would then be bivariant, allowing app context to guarantee correctness. `--strictFunctionTypes` does not affect method and constructor sigs because contravariance can't be enforced in all circumstances involving inheritance.

We create custom models that inherit from the objection.js Model class, so sometimes we may need the benefit of bivariant method signatures. My circumstance is one example. Consider:

```js
// fakelib.js

module.exports = function () {};
```

```ts
// fakelib.d.ts -- a simplified subset of the objection.js typings

export = Objection;
declare namespace Objection {

  interface ModelClass<M extends Model> {
  }

  export class Model {
    $query(): QueryBuilderSingle<this>;
  }

  export interface QueryBuilderSingle<T> {
    insert: (model: T) => void;
  }
}
```

```ts
// index.ts

import * as fakelib from './fakelib';

export class MyModel extends fakelib.Model {
    id: number;
}

export class MyModelRepo<M extends MyModel> {
    Model: fakelib.ModelClass<M>; // ERROR at <M>
}
```

The above yields the following error:

```
Type 'M' does not satisfy the constraint 'Model'.
  Type 'MyModel' is not assignable to type 'Model'.
    Types of property '$query' are incompatible.
      Type '() => QueryBuilderSingle<MyModel>' is not assignable to type '() => QueryBuilderSingle<Model>'.
        Type 'QueryBuilderSingle<MyModel>' is not assignable to type 'QueryBuilderSingle<Model>'.
          Type 'Model' is not assignable to type 'MyModel'.
            Property 'id' is missing in type 'Model'.
```

As best I'm able to determine, the error occurs because `insert()` is being asked to contravariantly receive an instance whose type is MyModel, which is a subtype rather than a supertype of Model.

The error vanishes upon replacing the `insert()` signature with the following:

```ts
  export interface QueryBuilderSingle<T> {
    insert(model: T): void;
  }
```

The two forms are logically equivalent, just different in the assurances TS makes.

My actual code has the following form:

```ts
export class Model extends Objection.Model implements RepoObject
{
    id: number;
}

export class ModelRepo<M extends Model> implements Repo<M> 
{
    Model: Objection.ModelClass<M>; // ERROR at <M>

    constructor(modelClass: Objection.ModelClass<M>, knex: Knex) {
        this.Model = modelClass.bindKnex(knex);
    }
}
```

And yields the following error:

```
Type 'M' does not satisfy the constraint 'Model'.
  Type 'Model' is not assignable to type 'Objection.Model'.
    Types of property '$query' are incompatible.
      Type '(trxOrKnex?: Objection.Transaction | Knex | undefined) => Objection.QueryBuilderSingle<Model>' is not assignable to type '(trxOrKnex?: Objection.Transaction | Knex | undefined) => Objection.QueryBuilderSingle<Objection....'.
        Type 'Objection.QueryBuilderSingle<Model>' is not assignable to type 'Objection.QueryBuilderSingle<Objection.Model>'.
          Types of property 'findById' are incompatible.
            Type '{ (id: Objection.Id): Objection.QueryBuilderOption<Model>; (idOrIds: Objection.IdOrIds): Objectio...' is not assignable to type '{ (id: Objection.Id): Objection.QueryBuilderOption<Objection.Model>; (idOrIds: Objection.IdOrIds)...'.
              Type 'Objection.QueryBuilderOption<Model>' is not assignable to type 'Objection.QueryBuilderOption<Objection.Model>'.
                Types of property 'findOne' are incompatible.
                  Type 'Objection.FindOne<Model>' is not assignable to type 'Objection.FindOne<Objection.Model>'.
                    Types of parameters 'condition' and 'column' are incompatible.
                      Type 'ColumnRef' is not assignable to type 'boolean'.
                        Type 'string' is not assignable to type 'boolean'.
```

Notice that it's failing to assign the more specific type Model to the more generic type Objection.Model because the method signatures of `findOne()` in one are not all compatible with those of `findOne()` in the other. This is due to the requirement that the signature of the assigned function must match every overload of the receiving variable. (This requirement is easily verified in quick-and-dirty experiments.)

Neither the contravariant problem nor the compatible overloading problem would exist were the typings to always define methods in method syntax. However, making this change would affect quite a bit of the typings file, and I'm not sure it would achieve any benefit other than being able to generically use ModelClass. Most other generics appear to be sourced via the `this` type.

The only workaround I could find was to define my repo as follows:

```ts
export class ModelRepo<M extends Model> implements Repo<M> 
{
    Model: Objection.ModelClass<any>;

    constructor(modelClass: Objection.ModelClass<any>, knex: Knex) {
        this.Model = modelClass.bindKnex(knex);
    }
}
```

This gives me model type enforcement on the repo APIs but not within the repo code itself.

Less desirably, I could duplicate the common repo code in every repo class and hard-code the definition of `this.Model` (e.g. `Model: Objection.ModelClass<UserModel>`).

I prefer something generic in order to be inviting to others who might help me further develop and popularize the framework. DI has yet to become common server-side, but it's catching on, and I'd like a clean objection.js solution out there so that objection.js can play too.

Thoughts, @mceachen? How do you feel about supporting ModelClass generics? What else might the new `--strictFunctionTypes` have affected? I do prefer to keep `--strictFunctionTypes`.

**Comment by jtlapp** [comment]
I'll post a version of the `express-ts` example using a generic ModelClass so you can see the benefit of this approach. The graph and transaction stuff require some extension of my approach, so I'm glad I tackled this little port. I'll try to share it this evening or by tomorrow night.

**Comment by mceachen** [comment]
I replied earlier this morning, but it seems to not have persisted.

First off, thanks for taking the time to write this, it was quite readable.

## Re: DI and DAO/Repo objects

My earlier post was in much more diplomatic terms, but tersely: I did a decade in the DI mines, with Spring, Guice, and more XML and annotations than you can shake a stick at, and, pardon my old-man voice, but that shit can stay off my lawn. DI proved to make codebases much less navigable as consumer/producer links were severed, and test validity tenuous, as the veracity of bytes being exercised in test versus production to be circumspect. Integration and system tests should not pass when production can't even spin up. 

I initially adopted DI to separate model objects from DAOs, because that seemed like a best practice. I recoiled at ActiveRecord's *audacity* to tightly couple DAOs and models, but in decidedly non-trivial codebases with hundreds of contributors, this proved to be just fine. (It turned out that a whole slew of other issues around AR were deal-killers, but I digress). It's hard enough to make code work reliably. Adding switchable implementations and DI's combinatorial explosion of what-works-with-what is something I've been happy to avoid for the past half-decade. 

There. End old-man rant.

## Re: ModelClass and generics

I'm really hoping that TypeScript resolves the missing static typings against interfaces soon, at which point `ModelClass` can be deleted. `ModelClass` is a hack to handle both static members in Model, and support comprehensive typeof assertions.

## Re: Removing Model from QueryBuilderSingle's typing

Those constraints should strictly match the Objection API--if Objection will always return Model instances, the typings should reflect that. If the result can be an ad-hoc POJO, again, the typings should reflect that.

## Generally

I chose Objection over other ORMs precisely due to the API, DRY models, and pleasant ergonomics. I think the current `examples.ts` code is fairly reasonable (and I have a lot of code that assumes the current ergonomics). I'm certainly open to massaging the typings to reduce the number of casts or type hints in people's code, and, generally, will be hesitant to change the typings to require more casts or type hints by consumers. We may be able to avail ourselves of the new generics defaults to avoid this.

I'll wait for your branch update to comment more.

**Comment by jtlapp** [comment]
Thanks! I followed all that but the bit about "Removing Model from QueryBuilderSingle's typing." If you're responding to my stripped-down objection typings above, that was for the purpose of isolating the problem and getting rid of stuff that might distract us into thinking it's a problem.

I'm new to DI but have been programming for nearly 37 years (since age 12), but mainly infrastructure libraries requiring only unit testing. I got a taste of poor-man's DI using hapi.js and was fond of being able to dynamically configure my system to run in different environments and isolating code for testing. As I migrated to TS, I realized that the language could rid me of the pain and discovered inversify.

Upon investigating inversify, I found that I could be configuring my end-point APIs as well, all with DI-analogous decorator syntax. Server code has never looked more readable to me. I do think DI belongs in the framework.

So I already see how DI practices can help with configuring systems at a large-scale level, but I'm more dubious about using DI on well-encapsulated internals. Hearing your thoughts suggests to me that maybe I shouldn't bother playing with DI beyond systems integration.

**Comment by jtlapp** [comment]
I hear ya that we should wait for TS to implement static interfaces, assuming they ever plan to do so. There's a lot of chatter about workarounds out there. I'll look into them. If there isn't anything my code alone can do, maybe there's still a simple tweak to the typings that will help.

**Comment by jtlapp** [comment]
Okay, as I play with graphs and relations, I'm realizing that my configurable units should be related groups of models, not each individual model. Now I have to rethink my approach.

I just want DI for configuring deployments. I posted related thoughts to [gitter](https://gitter.im/Vincit/objection.js?at=5a53a8820505ad8b45cc8b4c).

**Comment by jtlapp** [comment]
Should we close this until -- and if -- Typescript ever allows for static interfaces?

**Comment by mceachen** [comment]
> Should we close this until -- and if -- Typescript ever allows for static interfaces?

I think that's reasonable, especially if we keep both the examples and `express-ts` compiling with `--strict` (which includes `--strictFunctionTypes`). Closing.
