### ISSUE TITLE
Add TypeScript to the README as a feature?

### ISSUE THREAD

**Issue by mceachen** [Vincit/objection.js#711]
The typings seem to be pretty stable at this point, do you want to advertise them in the README?

**Comment by koskimas** [comment]
Sure, seems like a good idea!

**Comment by jtlapp** [comment]
I guess I should officially register my discontent with the typings:

- I find them largely unusable for determining the types that methods yield. They just take too much work to decipher.
- The former point makes them very hard to maintain. I'm maintaining typings elsewhere without trouble.
- They don't work with custom query builders.

I find myself wondering how wise it was to build a typescript solution on objection. I'm thinking maybe I should be investigating a solution along the lines of @koskimas' proposal [here](https://github.com/Vincit/objection.js/issues/717#issuecomment-357511876) for bringing more clarity and maintainability, even if it appears more verbose.

**Comment by jtlapp** [comment]
Basically, I don't want to be one of the few people using Typescript with objection. I want to feel like I have the support of a community. That makes the dependency less fragile, lowers my risk.

Hard-to-understand, difficult-to-maintain typings aren't going to foster a typescript community.

**Comment by jtlapp** [comment]
I can see some changes to type names (especially generics) that would have helped me make sense of the typings when I first looked at them. I'm playing with that now.

**Comment by jtlapp** [comment]
QUESTION: What is a good term for referring to the Person model in the following code and clearly distinguishes it from the "result model" Movie?

```ts
const movies = await person.$relatedQuery<Movie>('movies');
```

Maybe "queried model"?

(The `<Movie>` param is necessary here, as otherwise `$relatedQuery` types out to Person.)

**Comment by mceachen** [comment]
I believe @jtlapp and I have worked through the issues he's had, and those solutions are now in PRs #735 and #753 . I'll push a PR to add a README line now.

**Comment by jtlapp** [comment]
Yes, I think the typings are stable. I do have suggestions for making them a bit easier to understand :wink:, but that shouldn't affect typings behavior and can be done post-1.0.

Thanks for bearing with me and for all the help @mceachen!
