### ISSUE TITLE
Provide explanation for migration path from Model.formatter

### ISSUE THREAD

**Issue by igor-savin-ht** [Vincit/objection.js#715]
Currently Model.formatter method is spitting out 'deprecated! formatter() method will be removed in version 1.0' warning but neither source code nor the changelog provide explanation for what is the recommended migration path for clients that currently depend on it (e. g. objection-find).

**Comment by koskimas** [comment]
```
'lower(' + formatter.wrap(propertyRef.fullColumnName()) + ')'
```

-->

```
raw('lower(??)', propertyRef.fullColumnName())
```

**Comment by igor-savin-ht** [comment]
Thanks! Do you think it makes sense to create PR that would add this example in the comment near the deprecation warning?
