### ISSUE TITLE
.allowEager() munges the QueryBuilder yield type

### ISSUE THREAD

**Issue by jtlapp** [Vincit/objection.js#719]
When `.allowEager()` modifies a query, the QueryBuilder suddenly changes from yielding a `Model` or `Model[]` type to yielding a `{}` or `{}[]` type.

Consider the following [code from `examples/express-ts/api.js`](https://github.com/Vincit/objection.js/blob/master/examples/express-ts/src/api.ts#L69):

```ts
    const persons = await Person.query()
      .skipUndefined()
      // For security reasons, limit the relations that can be fetched.
      .allowEager('[pets, parent, children.[pets, movies.actors], movies.actors.pets]')
      .eager(req.query.eager)
      .where('age', '>=', req.query.minAge)
      .where('age', '<', req.query.maxAge)
      .where('firstName', 'like', req.query.firstName)
      .orderBy('firstName')
      // Order eagerly loaded pets by name.
      .modifyEager('[pets, children.pets]', qb => qb.orderBy('name'));
```

VSCode indicates that `persons` above has type `{}[]`. When I comment out the `.allowEager()` line, VSCode then correctly indicates that `persons` has type `Person[]`.

A glance at the typings suggests that `allowInsert()` and `allowUpsert()` might also do this.

I'd offer to find a fix, but with @mceachen around pulling rabbits out of hats, I'm just leaving it all to him. (Sorry if I'm proving frustrating. I'm finding TS types pretty darn challenging.)

**Comment by mceachen** [comment]
@jtlapp please consider adding this code to the `examples.ts` and tweaking `.allowEager` to make things go green--I don't really have the free time to do more than PR reviews.

**Comment by jtlapp** [comment]
I'm happy to give it a shot, with you looking over PRs. Thanks!

**Comment by jtlapp** [comment]
The typings appear to be missing the [RelationExpression class](https://github.com/Vincit/objection.js/blob/master/lib/queryBuilder/RelationExpression.js) alternative to string expressions. The typings [only allow strings](https://github.com/Vincit/objection.js/blob/master/typings/objection/index.d.ts#L222). The RelationExpression class looks like a way to precompile these strings.

I'll **not** be adding the RelationExpression class to the typings with this PR.

**Comment by mceachen** [comment]
Thanks!
