### ISSUE TITLE
Select a single instance with .first() 

### ISSUE THREAD

**Issue by drew-r** [Vincit/objection.js#72]
Knex.js supports a `.first()` method for selecting only one row with the result being an object instead of an array.

Thoughts on implementing an analogous method?

**Comment by drew-r** [comment]
My bad, already there!

**Comment by molomby** [comment]
For others who may wander in -- be aware that `.first()` will still retrieve the entire dataset from the DB. [Docs](https://vincit.github.io/objection.js/api/query-builder/other-methods.html#first):

> NOTE: This doesn't add limit 1 to the query by default.

This is different behaviour than Knex. If you want a `limit` added to your query under the hood you should add `.limit(1).first()` or configure [`useLimitInFirst` on you model](https://vincit.github.io/objection.js/api/model/static-properties.html#static-uselimitinfirst).
