### ISSUE TITLE
Example Typescript wrapper for Objection

### ISSUE THREAD

**Issue by jtlapp** [Vincit/objection.js#726]
Okay @koskimas and @mceachen, I'm ready to share the project. It works, but there a few more things I want to do.

I've ported the `express-ts` example to [an example I'm calling `ts-wrapper`](https://github.com/jtlapp/objection.js/tree/ts-wrapper-example/examples/ts-wrapper). The README page at that link provides an overview. (`src/repl.js` is there only because I haven't moved it to `test.js` yet.)

In short, I'm demonstrating a way to encapsulate the Objection.js implementation behind Typescript interfaces to minimize the amount of code that depends on Objection.js. It happens to demonstrate this abstraction with a koa frontend, but I'm not wedded to that.

I'm sharing it for any feedback you might have and for you to consider whether it (or any part of it) might be useful to include within the Objection repo. No skin off my back either way, as I did it mainly to help me learn Objection and figure out a way to integrate Objection into my project.

I plan to write more tests, because doing so helps me understand how things work and occasionally reveals typings problems or my misunderstandings of the `express-ts` example. The mocha tests are currently just a port of `express-ts/example-requests.sh`, but I plan to test my repo API more directly with a port of `express-es7/client.js` to mocha tests.

I also have a number of unresolved TBDs to investigate. You can ignore all that.

Thanks!

**Comment by mceachen** [comment]
I looked through your repo.

IMHO, I think the typescript example should match as closely as possible to @koskimas' esnext example. Indeed, just a couple PRs ago, I cloned the esnext tree and replaced the ts tree with the esnext code with the minimal changes necessary to make TypeScript happy in strict mode.

Introducing interfaces and services and brokers layers to example code adds both conceptual and implementation weight that, frankly, makes Objection appear to be harder to use than it actually is. I don't favor importing this.

**Comment by mceachen** [comment]
That said, I think replacing the example-requests.sh with a mocha test suite would be wonderful (and we should push that over to the esnext tree as well, as a validation test before npm publishing).

**Comment by jtlapp** [comment]
Thanks @mceachen!

> the typescript example should match as closely as possible to @koskimas' esnext example.  Indeed, just a couple PRs ago, I cloned the esnext tree and replaced the ts tree...

Where's this esnext tree? I search through the repo just yields some examples of static initializers.

> Introducing interfaces and services and brokers layers... makes Objection appear to be harder to use than it actually is.

I agree on that point.

At the same time, an architect managing risk and an engineering team would likely skip right past objection without this protective abstraction. I think this approach makes objection more accessible to enterprise projects. I myself require it.

For example, I don't yet know whether I'm going to have to switch out objection for plain knex or SQL. I want to give objection a shot, and I want to minimize wasted effort if it doesn't work out. You can do that without Typescript or interfaces, but these interfaces all but guarantee it.

>  I think replacing the example-requests.sh with a mocha test suite would be wonderful...

I'd be happy to do so. I just need to add a few more GETs for verifying data.

**Comment by jtlapp** [comment]
Here's another way to think about it:

- I was advised to avoid ORMs because I'm going to need sophisticated queries.
- Objection claims to be a kind of ORM, though a flexible kind.
- Therefore, I am taking a risk by embracing an "ORM" despite advice.

An interface wrapper allows me to safely manage that risk and safely try Objection.

**Comment by jtlapp** [comment]
After talking with @lehni on gitter, I've decided to pass a context in to each broker, where this context allows each broker API to decide for itself which objection models it's accessing.

Passing an app/session context through will make the API a bit more complex, but detaching the interfaces from strictly wrapping objection models may simplify things a bit.

**Comment by jtlapp** [comment]
Okay, once I make "brokers" independent of objection models, it becomes a server architecture and not a technique requiring a specific solution for objection -- with one exception.

@lehni is working on that exception, which is to find a way to make an app-provided context session-dependent context available across the objection API. *That* example may be worth checking in.

I'm withdrawing this proposal because the wrapping can be done in an objection-independent way.

Thanks for giving things a look-over!
