### ISSUE TITLE
eager: 'identifier .... is over 63 characters long and would be truncated by the database engine.'

### ISSUE THREAD

**Issue by tahv0** [Vincit/objection.js#727]
Just reminding that long nested eager queries causes error.

I have faced this problem only with JoinEagerAlgorithm.

```
eager: 'identifier reviewersorganizations:documents:customType:group:indexingPrefix is over 63 characters long and would be truncated by the database engine.'
```

**Comment by koskimas** [comment]
There's no way around that but the option to [minimize](http://vincit.github.io/objection.js/#eageroptions) the identifiers.

```js
await Person.query()
  .joinEager('jadda.jadda.jadda...')
  .eagerOptions({ minimize: true })
```

That's a database limitation.

**Comment by koskimas** [comment]
You could use aliases in the query if you need to filter it using the identifiers (the minimized ones make the code unreadable).

Something like this:

```js
await Person.query()
  .joinEager(`
    reviewersorganizations as revOrgs .[
      documents as docs .[
        customType as cType .[
          group.indexingPrefix as idxPref
        ]
      ]
    ]
  `)
```

**Comment by koskimas** [comment]
But you also get the relations named with the alisese. One more option is to use the `aliases` option:

```js
await Person.query()
  .joinEager('jadda.jadda.jadda...')
  .eagerOptions({ 
    aliases: { 
      reviewersorganizations: 'revOrgs',   
      documents: 'docs',
      customType: 'cType'
    } 
  });
```

(I didn't remember this existed :D)

**Comment by koskimas** [comment]
Aaand one more hint http://vincit.github.io/objection.js/#defaulteageroptions
