### ISSUE TITLE
Named filters don't appear to be working correctly

### ISSUE THREAD

**Issue by oliver-giersch** [Vincit/objection.js#731]
I've been trying to get named filters with "order by" statements to work without success.

The follwing code should by my understanding return an array of _Favorite_ objects, ordered by the _updated_at_ field of its _AbstractItem_ related object, but the ordering doesn't work.

```javascript
const favorites = await Favorite
    .query()
    .eager("[abstractItem(orderByDate).[location, favorite, item.type, component.type, accessory.type]]");
```

The _Favorite_ model has a 1:1 relation called _abstractItem_ and the _AbstractItem_ model has a named filter _orderByDate_ defined like this:

```javascript
orderByDate: builder => {
    builder.orderBy("updated_at", "DESC");
}
```

I've been able to find a workaround by using _joinEager_ and a "manual" _orderBy_ at the end of the statement, but my example is pretty close to the examples in the documenation, so it should work I think.

**Comment by koskimas** [comment]
They work as expected.

**Comment by oliver-giersch** [comment]
I did, the query is generated correctly, but the resulting array is not ordered accordingly.

**Comment by koskimas** [comment]
Look again. The named filter orders the query that fetches abstractItems, not the query that fetches Favorites.
