### ISSUE TITLE
select in namedFilter + joinEager

### ISSUE THREAD

**Issue by behalka** [Vincit/objection.js#733]
Hey, I'm trying to use `joinEager` together with a named filter in order to return joined "virtual" properties. Normal `eager` query works alright.

The SQL query looks almost correct, but additional fields are missing in the `select` clause so even though they are fetched, they are never returned.

The filter looks like this:

```js
static get namedFilters() {
    return {
      flattened: builder => {
        return builder
          .join('parameters', 'parameter_values.parameter_id', 'parameters.id')
          .leftJoin('parameter_enums', 'parameter_values.enum_id', 'parameter_enums.id')
          .leftJoin('parameter_enum_values', 'parameter_values.enum_value_id', 'parameter_enum_values.id')
          .select([
            'parameter_enum_values.value as enum_value',
            'parameter_values.id as id',
            'parameter_values.parameter_id',
            'parameter_values.product_variant_id',
            'parameter_values.float_value',
            'parameters.name',
            'parameters.type',
            'parameters.unit',
          ])
      },
    }
  }
```

Query as follows:

```js
    query
      .where('product_items.id', itemId)
      .joinEager('productVariant.parameterValues(flattened)')
      .first()
```

And generated SQL:

```sql
SELECT "productVariant:parameterValues"."name",
       "product_items"."id" AS "id",
       "productVariant"."id" AS "productVariant:id",
       "productVariant"."product_id" AS "productVariant:product_id",
       "productVariant:parameterValues"."id" AS "productVariant:parameterValues:id",
       "productVariant:parameterValues"."parameter_id" AS "productVariant:parameterValues:parameter_id",
       "productVariant:parameterValues"."product_variant_id" AS "productVariant:parameterValues:product_variant_id",
       "productVariant:parameterValues"."float_value" AS "productVariant:parameterValues:float_value"
FROM "product_items"
LEFT JOIN "product_variants" AS "productVariant" ON "productVariant"."id" = "product_items"."product_variant_id"
LEFT JOIN
  (SELECT "parameter_enum_values"."value" AS "enum_value",
          "parameter_values"."id" AS "id",
          "parameter_values"."parameter_id",
          "parameter_values"."product_variant_id",
          "parameter_values"."float_value",
          "parameter_values"."string_value",
          "parameter_values"."integer_value",
          "parameter_values"."text_value",
          "parameters"."name",
          "parameters"."description",
          "parameters"."type",
          "parameters"."unit"
   FROM "parameter_values"
   INNER JOIN "parameters" ON "parameter_values"."parameter_id" = "parameters"."id"
   LEFT JOIN "parameter_enums" ON "parameter_values"."enum_id" = "parameter_enums"."id"
   LEFT JOIN "parameter_enum_values" ON "parameter_values"."enum_value_id" = "parameter_enum_values"."id") AS "productVariant:parameterValues" ON "productVariant:parameterValues"."product_variant_id" = "productVariant"."id"
WHERE "product_items"."deleted_at" IS NULL
  AND "product_items"."deleted_at" IS NULL
  AND "product_items"."id" = 1;
```

Additional fields are aliased correctly, but they are not in the `select`. When I tried to add them manually, Objection returns an error - I guess because the fields are not really present in the `parameter_values` table. Is there any way to use named filters and joinEager like this? It would be really really useful in my use case. Again, with normal `eager` it works :)

The error stack starts like this:

```
TypeError: Cannot read property 'length' of undefined\n    at createModel (../node_modules/objection/lib/queryBuilder/operations/eager/RelationJoinBuilder.js:663:32)
```

**Comment by koskimas** [comment]
Hi,

thanks for bringing this up. I'll see if there is something I can easily do about this. If the change ends up being a big one, I'm afraid this won't be at the top of the list of things to add because I think this isn't that common a use case.

**Comment by thunderball1** [comment]
+1

**Comment by MichalKlacko** [comment]
+1

**Comment by koskimas** [comment]
Wow, maybe I was wrong about how common this is, or do all three of you work together 😉

**Comment by koskimas** [comment]
This should be fixed now. I'll release a new 1.0 RC version shortly.

By the way, three votes from the same team is only counted as one and will only make me want to help you less, since it seems like you tried to pretend there is more demand for this feature than there really is.

**Comment by koskimas** [comment]
1.0 RC3 is now released with this fix in it. You can install it using `npm install objection@next`. [Here's the change log](https://github.com/Vincit/objection.js/blob/master/doc/includes/CHANGELOG.md#100-). Note that there are some breaking changes if you try this out. Also the links in the changelog only work in the compiled html, not in the markdown files. You need to search the relevant sections from the `docs` folder.

**Comment by behalka** [comment]
Hey @koskimas I can confirm it works now, thanks a lot! 
To clarify, maybe you'll be glad to know that we use your library a lot, we really really like it and this fix will actually help more people on multiple projects than just me :)
Have a great day!

**Comment by koskimas** [comment]
That's nice to ~hear~ read!

This is off topic, but reading the code you posted, are you aware of the `joinRelation` helper? You could probably replace this code:

```js
          .join('parameters', 'parameter_values.parameter_id', 'parameters.id')
          .leftJoin('parameter_enums', 'parameter_values.enum_id', 'parameter_enums.id')
          .leftJoin('parameter_enum_values', 'parameter_values.enum_value_id', 'parameter_enum_values.id')
```

With something like this (if you have defined the relationships):

```js
          .joinRelation('parameters')
          .leftJoinRelation('[parameter_enums, parameter_enum_values]')
```

saving you from repeating the foreign keys.

**Comment by behalka** [comment]
Yeah, I know about it :) Thanks again and happy coding!

**Comment by marlon-bain** [comment]
Is there a way to be able to do this, but with a computed column like `age + age AS twice_age`?
