### ISSUE TITLE
Ambiguous select in subquery

### ISSUE THREAD

**Issue by eshell** [Vincit/objection.js#737]
I have a table events and members with id event_id and member_id as primary keys associated through a table members_events also with member_id and event_id keys. When I eager load members and perform a select on member_id column (among others), I get an error that member_id is ambiguous. If I only select on other columns without the key, it's fine.

 It doesn't appear that selects on modified eager relations "always" prepends the eagerly loaded table name to select columns. Sometimes it does, I just haven't figured out why it doesn't always do this yet. I have to manually prepend the eagerly loaded table name when selecting the key "members.member_id", "members.photo", etc. 

If I have duplicate column names in both tables but don't select the primary key, the eagerly loaded table select query auto prepends the table name. 
Seems like a bug or inconsistency to me.

Event.query()
.eager('members')
. modifyEager('members', member => { 
member.select('member_id', 'created_at') 
}).then(
// member_id ambiguous...
)

**Comment by eshell** [comment]
Should 'members' always be prepended to the select query? Sometimes it actually does this automatically, in case of selecting primary key, it doesn't.

**Comment by eshell** [comment]
I'll try to post a reproduction later if needed. Not at my computer right now.

**Comment by koskimas** [comment]
This is expected. You need to specify the table. We cannot automatically prepend the table, because there is not javascript-side SQL parser so that we could __really__ know which table, view, or from expression has which column. There is no way to do this reliably on the objection side without implementing all database engines in javascript.

**Comment by koskimas** [comment]
The columns you explicitly select are __never__ prepended with a table name. The table is added only in cases where we absolutely certainly know the table.
