### ISSUE TITLE
Possible logos

### ISSUE THREAD

**Issue by jtlapp** [Vincit/objection.js#738]
I didn't see a way to post this to gitter, so I'm posting here. I guess this could be a thread for examining possible logos.

Here's an O bound to a square object to look like a Q (as in query or SQL). Sorry, it's sketchy!

![objection-logo](https://user-images.githubusercontent.com/138133/35162662-b349697c-fd09-11e7-9b5c-781e6bbcce8b.jpg)

**Comment by koskimas** [comment]
Thanks for the idea, but the guy that designed the first logo is working on a new one. I'll see what he comes up firts.

**Comment by jtlapp** [comment]
Sure thing. Feel free to close this thread.

**Comment by newhouse** [comment]
That's cool @jtlapp...excited to see what comes up @koskimas . If you guys need any help let me know and I can get some of my peeps on it, too. Objection will be big I think. Thanks to all for the hard work!

**Comment by jtlapp** [comment]
A modification came to mind. Can you find the S, the Q, the L, and of course the O?
![objection-logo-sql](https://user-images.githubusercontent.com/138133/35176087-b293ce04-fd3c-11e7-845c-84efc1b92a68.jpg)

**Comment by heisian** [comment]
pretty cool. simple shapes and use of negative space. i like it.

**Comment by koskimas** [comment]
So we could bring up this discussion again. I left the company that had the logo guy a year ago :smile: 

@jtlapp I like your idea. Just one thing bugs me, and I might be the only one: it reminds me of a gender symbol like ♂ or ♀. Maybe it's a brand new gender SQL-sexual :smile:

**Comment by koskimas** [comment]
By the way, the guy did design [this](https://github.com/Vincit/objection.js/blob/master/resources/objection_logo.svg). It's really cool, but it's too much of a copy from the JSON logo.
