### ISSUE TITLE
QueryBuilder can build a subquery for `where()` but not `select()`

### ISSUE THREAD

**Issue by drew-r** [Vincit/objection.js#74]
I noticed the following when looking to subquery an aggregate into the select list. 
I found I could do it with knex's builder but not with objection.

````javascript
Product.
     query().
     select('*',
// works
 select(function(builder){
 	builder.
 	avg('rating').
 	from('productReviews').
 	whereRef('productReviews.productId', '=', 'products.id')
 }),
// doesn't work as not wrapped with brackets
 select(ProductReview.
   query().
   avg('rating').
   whereRef('productReviews.practiceId', '=', 'products.id')).
````
I know you can pass a QueryBuilder instance to `where()` so thinking this might not be by design?

**Comment by koskimas** [comment]
Weird, that should work. I'll write some tests and get back to you. I'm quite busy with other stuff right now, so it may take some days.

**Comment by koskimas** [comment]
This works for me if you give the selection a name using `as` method. You probably want to do that anyway (?). Could you try something like this:

```js
Product
  .query()
  .select('Product.*', ProductReview.query()
    .avg('rating')
    .whereRef('productReviews.practiceId', '=', 'products.id')
    .as('avgRating')
  )
  .then(products => {
    console.log(products)
  });
```

**Comment by drew-r** [comment]
Confirmed working. Thanks!
