### ISSUE TITLE
can unrelate() take a transaction as optional param

### ISSUE THREAD

**Issue by capaj** [Vincit/objection.js#746]
for a `query()` I can pass an optional transaction as the first parameter.
Could this be the same for`unrelate`?

**Comment by koskimas** [comment]
You can only call `unrelate` for a query, and you can give the transaction for the query method, in this case `$relatedQuery('foo', transaction)`

**Comment by capaj** [comment]
@koskimas thanks for the quick response. I've misread the docs.
