### ISSUE TITLE
insertWithRelated not setting up the foreign key

### ISSUE THREAD

**Issue by thetutlage** [Vincit/objection.js#75]
I am trying to insert related model using `insertWithRelated` method but it is not setting up the relation `foreignKey`.

```javascript
class User extends Model {
	static get tableName () {
		return 'users'
	}
}

class Profile extends Model {
	static get tableName () {
		return 'profiles'
	}
}

User.relationMappings = {
  profile: {
		relation: Model.OneToOneRelation,
		modelClass: Profile,
		join: {
			from: 'users.id',
			to: 'profiles.user_id'
		}
	}
}
```

## Insert call

```javascript
User
	.query()
	.insertWithRelated({
		username: 'doe',
		firstname: 'john',
		lastname: 'doe',
		profile: {profile_name: 'john doe'}
	})
	.then(console.log)
	.catch(console.error)
```

But it does not sets up the `user_id` inside the profiles table

**Comment by koskimas** [comment]
The `OneToOneRelation` only works in the other direction. The model class that declares the relation should have the foreign key. I know that this is counter intuitive and has caused confusion for others also. We will work out some solution for this.

As a kind of weird workaround you can declare the relation as `OneToManyRelation` and do this:

```js
User
    .query()
    .insertWithRelated({
        username: 'doe',
        firstname: 'john',
        lastname: 'doe',
        profile: [{profile_name: 'john doe'}]
    })
    .then(console.log)
    .catch(console.error)
```
