### ISSUE TITLE
Model.raw() returns plain js

### ISSUE THREAD

**Issue by sultan99** [Vincit/objection.js#751]
I'm using:

```js
const knex = new Knex({
  client: `postgres`,
  connection, // some connection options
  ...objection.knexSnakeCaseMappers()
})

class Document extends Model {
  static async assingedToMe() {
    const strSQL = `select * from documents` // in real here is a complex SQL query
    const result = await this.raw(strSQL)
    return result.rows
  }
}
```
Result:
```js
[
  anonymous {
    id: '534',
    start_date: `2019-12-31T18:00:00.000Z`,
    end_date: null,
    company_id: '2',
    workflow_id: '1' },
  anonymous {
    id: '530',
    start_date: `2017-12-31T18:00:00.000Z`,
    end_date: null,
    company_id: '2',
    workflow_id: '1'
  }
 ]
```

I get fields of the returned value not converted to camelCase, as the reason I get result of anonymous objects not model (Document), is there way how to make it to return Model object?

**Comment by elhigu** [comment]
At least in `knex` `knex.raw` always returns unprocessed result got from database driver. So probably objection does the same. As far as I know `Model.raw` is just shorthand for `knex.raw`. So it is not processed through objection like `Model.query()` queries, but does plain knex query.

**Comment by sultan99** [comment]
@elhigu yes that is the point, it pass unprocessed result from db.

My question is there any way how to force Objection to use the raw query as it was built by QueryBuilder.

I' have found some kind lifehack to make it work as expected:

```js
static async assingedToMe() {
  const strSQL = `select * from document` // still, in real case it is a big SQL query
  return await this.query()
    .with(`document`, this.raw(strSQL))
    .from(`document`)
}
```

**Comment by koskimas** [comment]
Objection cannot know the result type of a raw query without parsing the raw SQL and that's not possible for obvious reasons. You can use `fromDatabaseJson` method to create model instances from the raw rows.
