### ISSUE TITLE
/DELETE Not Found Issue

### ISSUE THREAD

**Issue by joemccann** [Vincit/objection.js#752]
First, thanks for the great work on objection.js.

I've been able to test it out a bit with `client.js` hitting the `api.js` but when I added the following code:

```js
  let del = await req.delete('persons',{
    params: {
      id: 1
    }
    })
```

I get the following response:

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot DELETE /persons</pre>
</body>
</html>
```

This is likely user error but a simple `DELETE` example in the `client.js` file would be helpful to me.

Thanks~

**Comment by koskimas** [comment]
Hi,

this should work:

```js  
let del = await req.delete(`persons/1`)
```

**Comment by joemccann** [comment]
🤦‍♂️ definitely user error. Thanks!
