### ISSUE TITLE
Many to many relation in a single table

### ISSUE THREAD

**Issue by claudiomramirez** [Vincit/objection.js#757]
Hi, I'm trying to create a many to many relationship, but the problem is that the table is related to itself. So I basically have 2 tables, articles and related_articles, where related_articles has 2 article_ids. I don's see how can I create a relation here, because I can't distingish between the main table and the related table:

```ja
relation: Model.ManyToManyRelation,
        modelClass: 'Article',
        join: {
          from: 'Article.id',
          through: {
            from: `related_articles.articleId`,
            to: `related_articles.related_article_id`,
          },
          to: 'Article.id'
        }
```

Is there a way to achive this?

**Comment by koskimas** [comment]
Your example should work. If it doesn't something else is wrong. Why do you think this doesn't work?
