### ISSUE TITLE
page command assigns incorrect value to offset in query.

### ISSUE THREAD

**Issue by ntraylor1985** [Vincit/objection.js#762]
Example: 
await Shapes
                .query()
                .page(1, 10).toString();

outputs -> 
"select "shapes".* from "shapes" limit 10 offset 10"

Looks like it is copying pageSize to both limit and offset.

**Comment by koskimas** [comment]
page index is zero based.

**Comment by koskimas** [comment]
http://vincit.github.io/objection.js/#page
