### ISSUE TITLE
UpsertOptions in typings doesn't equal to the js version

### ISSUE THREAD

**Issue by aposashenko** [Vincit/objection.js#765]
Hi there,

Can you please update UpsertOptions interface in typings so it equals to the js version. It doesn't contain these properties:
```typescript
update?: boolean;
noInsert?: boolean;
noUpdate?: boolean;
noDelete?: boolean;
noRelate?: boolean;
noUnrelate?: boolean;
```

I need some of them in my project.

Thanks in advance!

**Comment by koskimas** [comment]
I'll fix that asap. Thanks!

**Comment by aposashenko** [comment]
You're flash, thanks for responding so fast, appreciate it!
