### ISSUE TITLE
Subqueries' aliases don't work in 1.0.0

### ISSUE THREAD

**Issue by fer22f** [Vincit/objection.js#769]
I have queries of the form:
```javascript
    Item.query().alias('i').where('creation',
      Item.query().alias('ii').select(max('creation'))
        .where({ cancellation: null, 'i.creation': ref('ii.creation') }))
```
Suddenly, when upgrading to the new version, it broke in an unexpected way: Both queries were being renamed to `ii`. I digged into the changes and found the problem, which is caused by the **wrong order** of merging of aliases.

https://github.com/Vincit/objection.js/blob/d5fd4b1bdf2a357b87985166bc5efd5fb17d367c/lib/queryBuilder/QueryBuilder.js#L116-L117

Before objects were changed into maps, the order was correct:

https://github.com/Vincit/objection.js/blob/ef5ca408eed17133c995175c851c55beef66d7f1/lib/queryBuilder/QueryBuilder.js#L119-L120

We should setup tests for this.

**Comment by koskimas** [comment]
Whoops, nice catch. Yeah, we need to add a test for this. Would you happen to have time to put together a PR for this? Just say no if you don't and I'll fix this soon.

**Comment by fer22f** [comment]
I prefer to leave it up to you, because my testing environment isn't properly setup and no time to work on this.

**Comment by koskimas** [comment]
@fer22f I just released RC 9 that has this fixed

**Comment by fer22f** [comment]
Thanks!
