### ISSUE TITLE
InsertGraph fails when foreign column name doesn't end with "id"

### ISSUE THREAD

**Issue by ncjones** [Vincit/objection.js#770]
Given the following Knex migration:

```javascript
exports.up = function(knex, Promise) {
  return Promise.all([
    knex.schema.createTable('Address', table => {
      table.increments('id')
      table.string('line1', 40)
      table.string('line2', 40)
    }),
    knex.schema.createTable('User', table => {
      table.string('id', 32).primary().index()
      table.integer('address').unsigned().references('address.id')
    })
  ])
}
```

And the following Objection model:

```javascript
class Address extends Model {
  static get tableName() {
    return 'Address'
  }
}

class User extends Model {
  static get tableName () {
    return 'User'
  }
  static get relationMappings () {
    return {
      address: {
        relation: Model.BelongsToOneRelation,
        modelClass: Address,
        join: {
          from: 'User.address',
          to: 'Address.id'
        }
      }
    }
  }
}
```

Then the following query should insert a user and an address and relate them through the foreign key relationship:
```javascript
  User.query().insertGraph({
    id: Faker.random.uuid().replace(/-/g, ''),
    address: {
      line1: Faker.address.streetAddress(),
      line2: Faker.address.city(),
    }
  })
```

The actual outcome is that the user and address are inserted but the user's "address" column is null.

The workaround is to rename the "address" column to "addressId". I don't have a problem with this workaround because it's a good convention to follow but a) this limitation should be documented and b) it's not always possible given a legacy schema.

**Comment by koskimas** [comment]
You cannot have a relation and a column have the same name since they share the same object. Thos is a common mistake. I'll add a check and a good error message for this case.

**Comment by koskimas** [comment]
Related issue #580

**Comment by koskimas** [comment]
In case of a legacy schema, $parseDatabaseJson and $formatDatabaseJson methods can be used to change the column name.
