### ISSUE TITLE
joinRelation().delete() seems to miss related table

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#774]
Hi, using 0.9.4 with knex 0.14.2 i'm doing
```
Block.query().where('block.id', id).first().joinRelation('parents')
.where('parents.type', 'site')
.delete()
```
And the mapping for parents is
```
parents: {
  relation: Model.ManyToManyRelation,
  modelClass: Block,
  join: {
      from: 'block._id',
      through: {
        from: "relation.child_id",
        to: "relation.parent_id"
      },
      to: 'block._id'
  }
}
```
knex shows:
```
delete from "block" where "parents"."type" = $1 and "block"."id" = $2
```
parents is missing.
I know for example that the call to `first()` is not required, i'm just reusing a portion of code from elsewhere and kept it in this example in case it was the culprit.

**Comment by kapouer** [comment]
Ho ! `USING` is a postgresql-only feature. To do what i want i needed to do a subquery:
```
Block.query().where('id',
  Block.query().select('block.id').where('block.id', data.id).joinRelation('parents').where('parents.type', 'site')
).delete();
```

**Comment by koskimas** [comment]
I think knex should throw instead of silently ignore joins (and other stuff) when they cannot be applied to a query. This has caused confusion before.
