### ISSUE TITLE
Upsert not setting fields to null

### ISSUE THREAD

**Issue by igor-savin-ht** [Vincit/objection.js#775]
If you upsert entity with a field set to null from previously existing value, previous value remains. Simple update doesn't have this problem.

This works correctly:
```
instance
		.$query(db)
		.update(instance)
```

This does not:
```
instance
		.$query(trx || db)
		.upsertGraph(instance);
```

**Comment by igor-savin-ht** [comment]
@koskimas Is this by design or a bug?

**Comment by koskimas** [comment]
If that really happens, it's a bug, but I'm afraid I have a hard time believing that's true :D So a reproduction is again needed.

**Comment by koskimas** [comment]
Oh, and `$query().upsertGraph` is meaningless. `upsertGraph` needs to have identifiers in it as described in the docs. All other query methods are ignored.

**Comment by igor-savin-ht** [comment]
@koskimas I'm literally switching between two methods right now and watching unit test to check for this behavior toggle between red and green.
Might be related to missing identifiers as you've mentioned, but I wonder why relations are updated properly then. I'll give it a try and write a failing test for objection if it's still not working.
Thanks!

**Comment by igor-savin-ht** [comment]
@koskimas Created pull request with test that reproduces the issue - note that it happens both for nested and parent-level entities.

**Comment by koskimas** [comment]
@igor-savin-ht Thanks for the reproduction! There really seems to be a bug. How the **ck hasn't this come up earlier? 😄

**Comment by igor-savin-ht** [comment]
You are welcome! Hopefully it's an easy fix :)

**Comment by igor-savin-ht** [comment]
Thanks! Appreciate it a lot.
