### ISSUE TITLE
Related entities are not automatically instantiated during upsert

### ISSUE THREAD

**Issue by igor-savin-ht** [Vincit/objection.js#777]
Not sure if it qualifies as bug or as missing convenience feature, but if you set one of the relation properties of the entity to a value that adheres to the structure of related entity in question but is not an instance of Model, Objection crashes during upsertion. This is inconsistent with behavior of other functions, which accept either Objection Model instances or plain javascript objects as long as they duck-type properly.

Here is where it fails:
objection/lib/queryBuilder/RelationExpression.js:
```
function modelToNode(model, node) {
  const modelClass = model.constructor;
  const relations = modelClass.getRelationArray(); //fails with modelClass.getRelationArray is not a function
```

**Comment by igor-savin-ht** [comment]
@koskimas If you think that this is wrong, I can provide a failing test here as well.

**Comment by koskimas** [comment]
All the tests pass plain javascript objects to `upsertGraph` and it works. The whole graph is converted into a model tree before anything else is done. Or did I misunderstand something?

**Comment by igor-savin-ht** [comment]
@koskimas Let me concoct an example :)

**Comment by koskimas** [comment]
Or are you doing something along these lines:

```js
const person = await Person.query().findById(1);
person.children = [child1, child2];

Person.query().upsertGraph(person);
```

In that case objection detects that `person` is already an instance of a model and doesn't convert anything.

**Comment by igor-savin-ht** [comment]
@koskimas  Yes, pretty much your example, since use-case is like this:

```
const address = req.body.address; //this is not an entity
const person = await Person.query().findById(1); //this is an entity
person.address = address;
Person.query().upsertGraph(person);
```

Obviously it works if you manually instantiate every single involved entity, but if you don't have a single entity but get entire tree for PATCH where plenty of related entities may or may not be set, it becomes painful quickly.

**Comment by koskimas** [comment]
Yeah, this fails because the root (person) is a model instance and therefore it is not converted into a model instance using `Person.fromJson` which recursively converts all relations. I think this should work though. Could you create a test case for this again? I'll fix it asap.

**Comment by igor-savin-ht** [comment]
Sure!

**Comment by koskimas** [comment]
In the meantime you can do this:

```js
const address = req.body.address; //this is not an entity
const person = await Person.query().findById(1); //this is an entity
person.address = Address.fromJson(address);
Person.query().upsertGraph(person);
```

As I said, `fromJson` recursively converts nested relations.

**Comment by koskimas** [comment]
Although "meantime" will probably be the nest 20 minutes 😄

**Comment by koskimas** [comment]
If you create a PR, add `it.skip` to the failing test so that I can merge it.

**Comment by igor-savin-ht** [comment]
@koskimas Added test with skip.
