### ISSUE TITLE
How to add field before validation | question

### ISSUE THREAD

**Issue by seeden** [Vincit/objection.js#779]
I want to add slug automatically before insert.
Currently I am using $beforeValidation because I have slug as required field in the JSON schema and it is automatically computed from current model fields. 
I am not able to change current json and add new slug in the $beforeValidation. Is $beforeValidation sync method? 

```js
  async $beforeValidate(jsonSchema, json, objectionOptions) {
    await super.$beforeValidate(jsonSchema, json, objectionOptions);

    json.slug = await this.computeSlug(json);

    return jsonSchema;
  }
```

This example is not working.

**Comment by koskimas** [comment]
$parseJson is the right place to do that.

**Comment by koskimas** [comment]
@seeden Oh, sorry I didin't notice that `comouteSlug` is async. There is no way to do that in any hook before validation. Validation is done synchronously. Why is the slug in jsonSchema if it's autogenerated? Why do you need to validate it? Can it also come from the outside world?
