### ISSUE TITLE
Dealing with circular references

### ISSUE THREAD

**Issue by sebbarg** [Vincit/objection.js#787]
Say I have two models M1 and M2 that need to query each other. They have no logical relations (i.e. no relationMappings() )

What is the proper objection.js way of handling this circular dependency? Right now I'm dropping down to doing knex queries, so I don't have to require M1/M2, but that doesn't feel right :)

Thanks,
Sebastian

**Comment by koskimas** [comment]
There is no objection.js way. This is not objection's problem if you don't use `relationMappings`. You have this problem with any two modules that require each other. The solution is to understand what is happening and change the order of the `require` calls accordingly. I cannot help you without seeing the code. Could you post it here?

**Comment by koskimas** [comment]
Usually you can solve this by moving the `require` after you set the export value in __one__ of the files.

**Comment by koskimas** [comment]
If you use ES6 modules and `import` you can probably use the dynamic import `await import()` inside the function.

**Comment by sebbarg** [comment]
@koskimas - thanks for the feedback. I'll have a look at your suggestions. 

I don't have a concrete example to share with you, but my reasoning is that one model that needs to lookup up stuff in another model, and the other way around (which is a pretty common scenario in any relational model), will sooner or later run into a circular ref. So I'm just checking if there is a best practice when using objection.js (apart from relationMappings).

If I DO set up a relationMappings between M1 and M2, what is the correct way to get to the M1 class from M2? E.g.:

```
class M1 extends Model
// ...
static get relationMappings() { /* M2 ... */ }

static someQueryOnM2() {
  // what do I do here to get the equivalent of:
  M2.query()...
  // through relationMappings ?
}

```
Thanks :)

**Comment by fl0w** [comment]
Aside using ES6 `import()`, I previously lazy loaded all models, so by example:

```js
// models/ModelOne.js
const ModelTwo = () => require('./ModelTwo')
class ModelOne extends objection.Model {}

// models/ModelTwo.js
const ModelOne = () => require('./ModelOne')
class ModelTwo extends objection.Model {}

// index.js
const ModelOne = () => require('./models/ModelOne')
ModelOne()
  .query()
  ...
```

These days I stuff a `Map` which acts as a registry which I monkey patch onto objection lib.

**Comment by koskimas** [comment]
@sebbarg What I meant was that objection doesn't offer any solutions for this problem since it is a fundamental programming problem and has absolutely nothing whatsoever to do with objection, or any library in existence for that matter.

**Comment by koskimas** [comment]
@fl0w 's example of lazy loading is one solution. Here's another:

```
class M1 extends Model
// ...
static someQueryOnM2() {
  const M2 = require('./M2');
  // what do I do here to get the equivalent of:
  M2.query()...
  // through relationMappings ?
}
```

**Comment by koskimas** [comment]
Here's another:

```js
// allModels.js

// Don't reassign the exports object. The whole reason this solution works
// is that we use the original `exports` object.
module.exports.M1 = require('./M1');
module.exports.M2 = require('./M2');
```

```js
// Don't destructure or get the `M2` value here. The whole reason this solution
// works is that we use the original `exports` object.
const models  = require('./allModels');

class M1 extends Model
// ...
static someQueryOnM2() {
  models.M2.query()...
}
```

**Comment by sebbarg** [comment]
@koskimas good stuff, thanks!

**Comment by koskimas** [comment]
Babel + default exports / imports solve this problem also because babel transpiles the code to look like the example above.

```js
import M2 from './M2';

class M1 extends Model
// ...
static someQueryOnM2() {
  M2.query()...
}
```

actually gets transpiled into something like this:

```js
const _M2 =  require('./M2');

class M1 extends Model
// ...
static someQueryOnM2() {
  // `default` is the property Babel generates when you use `export default`
  _M2.default.query()...
}
```
