### ISSUE TITLE
Support both `hasOne` and `belongsToOne` cases of `OneToOneRelation? 

### ISSUE THREAD

**Issue by koskimas** [Vincit/objection.js#79]
Currently `OneToOneRelation` only works in one direction. It only works when the model that declares the relation has the foreign key. `OneToManyRelation` can be used to make a relation in the other direction, but you need to use arrays even though there never is more than one related object.

One possible fix for this would be to determine the direction from the order of the keys in the `join` object of `relationMappings`, but currently the order is ignored so that you don't need to remember it. Changing this so that the order matters would be a breaking change.

Another possibility would be to add a `direction` enum for the `OneToOneRelation`. Something like this

```js
static relationMappings = {
  pets: {
    relation: Model.OneToOneRelation,
    modelClass: Animal,
    direction: 'HasOne',
    join: {
      from: 'Animal.ownerId',
      to: 'Person.id'
    }
  }
}
```

but this smells like boilerplate.

One more solution comes to mind. 99% of the time you want to join the primary key of one model to the foreign key in the other model. In this case you would only need to specify one column: the foreign key column. What if we make the following syntax possible:

```js
static relationMappings = {
  pets: {
    relation: Model.OneToOneRelation,
    modelClass: Animal,
    foreignKey: 'Person.ownerId'
  }
}
```

Using this syntax would be like saying "this is the foreign key, the other column is a primary key" and we could easily determine which way the relation should work. The current syntax is so verbose for two reasons:

 1. No magic, you see exactly what gets joined.
 2. You can join any column to any column, the other column doesn't need to be a primary key.

I would love some input on this issue. How would you like this to work?

Related to #75 
ping @thetutlage

**Comment by thetutlage** [comment]
I agree with you, adding more configuration to the relations object is not sensible. 

Using the last method `foreignKey`, we are removing the flexibility of defining a different key other than `primaryKey` ( known as `idColumn` ).

May be having a alias method called `Model.hasOne`, which is inverse of `Model.OneToOneRelation`.

Having a method is more sensible only if we are not duplicating the code. As i see you have dedicated class for each relation, may be `hasOne` can inherit `OneToOne` and override specifics only.

**Comment by koskimas** [comment]
My idea with the last method was that the old way of defining relations would still work. This would be an additional way to define relations. But then we have many ways of doing the same thing, which adds to the complexity.

Isn't `BelongsToOneRelation` the inverse of  `OneToOneRelation`? If "having" means owning the foreign key. Or am I thinking this wrong?

I would definitely avoid duplicating the code. I would either subclass `OneToOneRelation` or create a common subclass.

The only problem I'm having with this solution is that the other relation names `OneToOne`, `OneToMany` and `ManyToMany` describe the relation type on a higher level. `BelongsToOne` is a special case of `OneToOneRelation`. Maybe we should also add a `HasOneRelation` for clarity, but then there would be no use for the `OneToOneRelation`, but removing it would be a breaking change. It is ok to break things this early in the life of objection, but I think it should be avoided if we can come up with a solution that doesn't.

**Comment by thetutlage** [comment]
actually belongsTo is the one which holds the foriegn key. Using the same api you will have to introduce another option on the object, which i don't think will work.

For example if you go with `direction` option, it will only be valid for this relation type and for other relations this will ignored.

If u do not want breaking changes, you can have direction inside the `join` option.

Ideal solution will be to have `hasOne` and `belongsTo` methods

**Comment by thetutlage** [comment]
Finally i think `HasOneRelation` and `BelongsToOneRelation` will make more sense, i know there will be a breaking change, but if not done now can become a pain later.

**Comment by koskimas** [comment]
I agree. I think we should also rename `OneToManyRelation` to `HasManyRelation` for consistency. I think that `HasOne` only makes sense as a special case of `HasMany`. Otherwise it seems like the foreign keys are the wrong way around. 

We should deprecate the old relations that get renamed so that people have time to migrate. I'll add an annoying deprecation `console.warn` message whenever you use the old relations.

**Comment by koskimas** [comment]
@elhigu any thoughts?

**Comment by elhigu** [comment]
Sounds good. New names sound a lot more intuitive to me.

**Comment by koskimas** [comment]
`npm install objection@next` will give you an alpha version that has the new relations.

**Comment by thetutlage** [comment]
:+1:

**Comment by thetutlage** [comment]
@koskimas Was checking the alpha version and found `HasOneRelation` returns an array, ideally it should be an object

**Comment by koskimas** [comment]
Returns an array in which case? When you use `$relatedQuery('blaa')`? Currently all the find queries return an array. The old `OneToOneRelation` returns an array as does the new `BelongsToOneRelation`. The property created by an eager query should be an object though. 

This is something we should consider changing.

It was a design choice. The reasoning behind this is that you always know the result type of a query. Consider a function that takes a `QueryBuilder` as an argument and does something with the result. The function doesn't know anything about the query. Just that it is a find query. If the result is always an array, you don't need to write code like:

```js
async function doStuffWithQuery(builder) {
  let res = await builder;

  if (!_.isArray(res)) {
    res = [res];
  }

  _.each(res, model => {
    doSomethingWithModel(model);
  });
}
```

But I'm not really sure which is more annoying, the current implementation or writing the checks in the rare cases you do things like the `doStuffWithQuery` does. Changing this would again break a lot of code. And this time the errors would be weird stuff like `TypeError`s.
