### ISSUE TITLE
[Question] Change jsonSchema based on the type of query

### ISSUE THREAD

**Issue by loryman** [Vincit/objection.js#791]
In Ruby on Rails i can add or remove validations in a model if that model is being updated, created or deleted. I'd like to do this on objection as well.

Do you have any ideas on how to do this?

**Comment by kapouer** [comment]
https://github.com/epoberezkin/ajv-keywords#selectselectcasesselectdefault
and
https://github.com/pageboard/api/blob/1aa27d78bf6fee87cc9353e1e4a0bdd985293bb0/index.js#L46
to install it.

**Comment by loryman** [comment]
Thank you for your feedback! And sorry for the late response,

i don't think i understand how `select` works. Basically i have a `BaseModel`:

```javascript
const { Model, AjvValidator } = require('objection');
const pluralize = require('pluralize');
const AjvKeywords = require('ajv-keywords');

class BaseModel extends Model {
  static get timestamps() {
    return true;
  }

  static get tableName() {
    return pluralize(this.name.toLowerCase());
  }

  static get modelPaths() {
    return [__dirname];
  }

  static createValidator() {
    return new AjvValidator({
      onCreateAjv: (ajv) => {
        AjvKeywords(ajv, 'select');
      },
      options: {
        $data: true,
        allErrors: true,
        validateSchema: false,
        ownProperties: true,
        v5: true,
        coerceTypes: true,
        removeAdditional: true,
      },
    });
  }
}

module.exports = BaseModel;
```

and a `User` model:

```javascript
const BaseModel = require('./BaseModel');
const { encryptPassword } = require('../lib/common');

lass User extends BaseModel {
  static get jsonSchema() {
    return {
      type: 'object',
      required: ['email'],

      properties: {
        id: { type: 'integer' },
        email: { type: 'string', format: 'email' },
        encrypted_password: { type: 'string' },
        password: { type: 'string' },
        password_confirmation: {
          type: 'string',
          const: { $data: '1/password' },
        },
      },

      select: { $data: '0/password' },
      selectCases: {
        // ...??
      },
    };
  }

  async $beforeInsert() {
    this.encryptedPassword = await encryptPassword(this.password);
  }
}

module.exports = User;
```

I need to set `password` and `password_confirmation` as required only when a user is being created.

I tried with `$beforeValidate` like this:

```javascript
  $beforeValidate(jsonSchema, json, opt) {
    if (!opt.old) {
      // We are in the insert phase
      jsonSchema.required.concat(['password', 'password_confirmation']);
    }
  }
```

but when i update the user with this notation:

```javascript
User.query().update({ email: 'example@email.com' }).where('id', 1)
```

`password` and `password_confirmation` are still required. Instead, when i do this:

```javascript
user.$query().update({ email: 'example@email.com' })
```

everything works fine.

**Comment by koskimas** [comment]
`opt.old` is only present when `$query` is used. There is no reliable way to achieve what you want right now using only jsonSchema. You could use `$beforeInsert` and `$beforeUpdate` hooks and add checks there for the stuff that needs to be validated differently and only add common validation to jsonSchema. That's what I've ended up doing.

We could possibly add a property to `opt` that indicates whether the validation is being done for an insert operation or an update operation. I'll see if that is plausible.

**Comment by loryman** [comment]
Thank you!

**Comment by koskimas** [comment]
Let's leave this open until I check if the `opt` property can be added.

**Comment by koskimas** [comment]
No, it can't.

**Comment by kapouer** [comment]
Thinking of that, now i would advise to try it with [ajv's custom keywords](https://github.com/epoberezkin/ajv/blob/master/CUSTOM.md#define-keyword-with-validation-function) and you'd just have to check if `id` is defined or not.

**Comment by capsule5** [comment]
Hello, sorry I'd like  to require password only for insert but  I  don't get the solution with $beforeUpdate though it will fit my needs.. How do you know from there if opt not working  that you're in insert mode? could you provide an example ?
