### ISSUE TITLE
`mixins` not working?

### ISSUE THREAD

**Issue by dannytatom** [Vincit/objection.js#793]
No idea what I'm doing wrong, but none of the plugins I'm using seem to work. Password isn't being hashed and I can create multiple records with the same email.

```javascript
// The model

const { mixin, Model } = require('objection')

const Password = require('objection-password')()
const Unique = require('objection-unique')({
  fields: [ 'email' ],
  identifiers: [ 'id' ]
})

module.exports = class User extends mixin(Model, [
  Password, Unique
]) {
  static get tableName () {
    return 'users'
  }

  static get jsonSchema () {
    return {
      type: 'object',
      required: [ 'name', 'email', 'password' ],

      properties: {
        id: { type: 'integer' },
        name: { type: 'string', minLength: 1 },
        email: { type: 'string', minLength: 1 },
        password: { type: 'string', minLength: 1 }
      }
    }
  }

  $beforeInsert () {
    this.created_at = new Date().toISOString()
  }

  $beforeUpdate () {
    this.updated_at = new Date().toISOString()
  }
}

// Using it like

const user = await User.query().insert({
  name: 'Dingus',
  email: 'dingus@gmail.com',
  password: 'unodostres'
}).returning('*')
```

**Comment by koskimas** [comment]
I see nothing wrong with the way you use `mixin` function which is the only part of this issue that concerns objection. The plugins you use are provided by the community and are not maintained by us. You need to open issues in the plugins' repositories.

**Comment by koskimas** [comment]
Do the plugins work if you use them like this `class User extends Password(Unique(Model))`?

**Comment by koskimas** [comment]
One thing that may be causing this is that you don't call `super` in $beforeInsert and $beforeUpdate. You are probably overriding some plugin code.

**Comment by Frans06** [comment]
@koskimas  suggested code works amazing. Internal function calls are been overwrite. Same problem, same solution.
