### ISSUE TITLE
Use objection.js.org

### ISSUE THREAD

**Issue by deadcoder0904** [Vincit/objection.js#797]
Checkout https://github.com/js-org/dns.js.org & add it. Its simple & free so people don't have to remember the URL again.

**Comment by koskimas** [comment]
Great idea, thanks! I'll get that done soon.

**Comment by koskimas** [comment]
Every time I think about doing this, I open this issue and see that **king sarcastic smiley by @TheMisir and I change my mind. Not going to do this.
