### ISSUE TITLE
Dates in changelog

### ISSUE THREAD

**Issue by ozum** [Vincit/objection.js#80]
Hi,

Small detail, but may be important for some. It would be nicer to see dates besides version numbers in changelog.

Regards,

**Comment by koskimas** [comment]
Hi,

I'll add dates from now on. You can also check the [releases](https://github.com/Vincit/objection.js/releases) page for dates.

**Comment by ozum** [comment]
Thanks. By the way, I see 5.0 alpha 2 in git. Is there a rough document what features/changes to expect in 5.0?

**Comment by koskimas** [comment]
Sorry, we don't have a roadmap at the moment. I mean that we don't know what will end up in 0.5.0. We are listening to feedback from the community and concentrating on fixing issues.

We haven't yet perfected the release process, but the alpha builds are not meant to be stable. Any features in them may change or even get removed. We are using the alpha tag to release test versions to get feedback from the early adopters. You can install the newest alpha/beta/rc version using `npm install objection@next`. We should really document this somewhere :smile:.

You can try to decipher the changes from the commit messages. I refer to the issue the commit is fixing in the commit message.

Also the documentation is always for the most recent release version, so for 0.4.0 at the moment.

**Comment by ozum** [comment]
Thanks again.

**Comment by koskimas** [comment]
I'll be honest: I'll never get this done 😄 You can see the dates from the `releases` tab in github.
