### ISSUE TITLE
Undefined variable args in Validator.js

### ISSUE THREAD

**Issue by canadianveggie** [Vincit/objection.js#804]
Looks like you missed a variable when you refactored the code for ES6.

In Validator.beforeValidate there is a broken reference to args.model.

This should be easy to catch with eslint. I'll add a pull request to fix this and enable no-undef checks with eslint.

**Comment by canadianveggie** [comment]
I would look into turning on all of "eslint:recommended" - it catches a bunch of potential problems (mostly unused imports, unused variables, and strings that are unnecessarily escaped).

**Comment by calvinl** [comment]
@koskimas do you have an ETA to release this fix? Creating a custom validator is broken at the moment due to this.

**Comment by canadianveggie** [comment]
As a workaround, we're ensuring we always override beforeValidate:

```javascript
class CustomValidator extends Validator {
  validate(args) {
    // some code
  }

  // Override Validator.beforeValidate until https://github.com/Vincit/objection.js/issues/804 is released
  beforeValidate({ model, json, opts }) {
    model.$beforeValidate(null, json, opts);
  }
}
```

**Comment by calvinl** [comment]
@canadianveggie thanks!
