### ISSUE TITLE
Provide access to model fields from $beforeValidate 

### ISSUE THREAD

**Issue by drew-r** [Vincit/objection.js#81]
Would it be possible to provide access to the model instance from `$beforeValidate` and `$beforeUpdate` when updating / patching?

e.g
````
User.prototype.$beforeValidate = function(jsonSchema, json, opt) {

    if (this.provider === 'local' && json.password && json.password.length > 6) {
       throw new objection.ValidationError({ password: 'Password too short' });
    }

};

User.query().first().then(function(user){
      user.$query().patch({ password: '123' }).then(function(){});
});

````
In the example above `this` ends up being  the model constructor rather than the instance.

**Comment by drew-r** [comment]
On second thoughts this would lead to inconsistent behaviour depending on if the patch was made via the instance method or the class method which would be undesirable.
I don't think there is any application level way around the problem of validating some fields based on the value of other fields that may or may not be supplied.

**Comment by elhigu** [comment]
I think this is actually valid ticket and bug in the system. To me it was really unexpected behavior that `this` inside `$beforeValidate` did not refer to model instance. 

One can use query context feature to achieve getting the model instance, but still to me it would be more sane behaviour if `this` would refer directly to the model instance.

@koskimas any thoughts?

**Comment by koskimas** [comment]
With `patch` and `update` `this` could be the model instance to be updated, and `json` could contain the new values, but what would `this` point to in an `insert`? To a fake model created from the `json` without validation? To an empty object?

I'm not saying this is a bad idea, but we need to consider all cases before changing anything.

**Comment by koskimas** [comment]
Also this would be inconsistent with other `$before` and `$after` hooks consider this:

```js
class Person extends Model {
  $beforeUpdate() {
    console.log(this);
  }
  $beforeValidate(schema, json) {
    console.log(this);
  }
}
```

Both methods would log a different object.

**Comment by koskimas** [comment]
On the other hand, `this` is completely useless in `$beforeValidate` at the moment.

**Comment by elhigu** [comment]
Agreed consistency and documentation for this would be good. I don't have strong opinion which way it is, since after query context feature lack of `this` has not been a problem anymore. 

Does any other `$lifeCycleMethod` use this for anything?

**Comment by koskimas** [comment]
@elhigu `this` is useful in `$beforeInsert`, `$beforeUpdate`. `$parse*Json` and `$format*Json` methods have no use for it, and they could be made `static`. They are not `static` so that you can do hackish stuff like this:

```js
someModel.$formatDatabaseJson = (json) => delete json.password;
doSomethingThatRequiresPasswordAndThenInsertToDatabase(someModel);
```
