### ISSUE TITLE
updateAndFetchById , patchAndFetchById fails if primary key is not 'id'

### ISSUE THREAD

**Issue by jagan-veeraraghavan** [Vincit/objection.js#810]
My Model is a simple

    class User extends Model{
      static get tableName(){
        return 'users';
      }
    }
With the following schema 

    knex.schema.createTable('users',function(table){
          table.increments('uid').primary();
          table.string('name');
          table.string('email').notNullable();
          table.string('password').notNullable()

I get an error, if I try to run the following statement:

    await User.query().patchAndFetchById(2,{email:"test@test.in"});

The error throws is

    Unknown column 'users.id' in 'where clause'

If The primary key is named as id. the code works.

**Comment by koskimas** [comment]
Use the static idColumn model property to set the correct id column
