### ISSUE TITLE
Lack of documentation for relationship filtering

### ISSUE THREAD

**Issue by igor-savin-ht** [Vincit/objection.js#815]
"Polymorphic associations" entry in the recipe book is the only place where `filter: {commentableType: 'Issue'},` feature is mentioned, and even then it is not mentioned that it supports either object, or string or function there. Given how useful this feature is, I believe it belongs somewhere in the core documentation.

**Comment by igor-savin-ht** [comment]
@koskimas 
I could give writing documentation entry a shot, but would appreciate pointing out what particular part of documentation you would like it to be added to.

**Comment by koskimas** [comment]
It should be added [here](http://vincit.github.io/objection.js/#relationmappings)

**Comment by kibertoad** [comment]
@koskimas PR created.

**Comment by koskimas** [comment]
PR merged. Thanks 👍

**Comment by ekeric13** [comment]
I am also having trouble findng docs on the filter aspect of relations. The link above now seems defunct with the updated docs.

Is there a way to access the old docs?
Or maybe get an update where the link is suppose to go to?
