### ISSUE TITLE
Migration support?

### ISSUE THREAD

**Issue by brylie** [Vincit/objection.js#816]
We are currently researching how to 'reset' our knex database migrations, and generate fresh model/schema.

Does objection.js provide capabilities for migrations? I found one example in the Vincit repo using Knex for migrations.

**Comment by koskimas** [comment]
Nope. Knex migrations are pretty much the best you can find in the node world. Since objection already uses knex, there is no reason to create our own migration system. Nothing forces you to use knex migrations though. Objection doesn't rely on knex migrations in any way.
