### ISSUE TITLE
Have omit() and pick() work with update / patch 

### ISSUE THREAD

**Issue by drew-r** [Vincit/objection.js#82]
Use case for this would be to prevent overwriting of sensitive data when user input is sent to the DB.
e.g

````
user.$query.patch(req.body).omit(['password', 'username']);
````

**Comment by drew-r** [comment]
Closing as I don't think this would reconcile well with `patchAndFetchById` etc.

**Comment by koskimas** [comment]
Maybe you could override [`$toDatabaseJson`](http://vincit.github.io/objection.js/#_s_todatabasejson) method:

```js
$toDatabaseJson(json) {
  return _.omit(json, ['password', 'username']);
}
```

This way the password and username never get to database.

**Comment by drew-r** [comment]
I used lodash on the patch object in the end, it works out better that way
as gives more flexibility.
I can't override `$toDatabaseJson` as it does need to be stored in the
database from some points in the application.
I override `$formatJson` to prevent sensitive data getting out to the user
though.
