### ISSUE TITLE
Patch/Update and simultaneously change object without fetching

### ISSUE THREAD

**Issue by Palisand** [Vincit/objection.js#820]
Is it possible to patch or update a previously-fetched object and have both the object and it's associated db row patched simultaneously, akin to calling patch/update on the object itself? I know of `patchAndFetchById` but I'm trying to avoid the extra fetch query.

```javascript
import {User} from 'models';

const user = await User.query().findById(id);
console.log(user.bio); // 'I eat cereal for breakfast.'

// do stuff with 'user'

user.patch({bio: 'I eat rusty nails for breakfast.'});
console.log(user.bio); // 'I eat rusty nails for breakfast.'
```

**Comment by newhouse** [comment]
@Palisand 

Are you using PostgreSQL?
- If so,  you should have a loo at the [PostgreSQL “returning” tricks](http://vincit.github.io/objection.js/#postgresql-quot-returning-quot-tricks) area of the documentation. That area outlines how what you want can be accomplished.
- If not, I don't believe you can accomplish this without the extra query as I'm not aware of other databases that offer that `returning` behavior (though there could be some more). Depending on what you expect to see updated in the DB (e.g. `updated_at`) you might be able to:
    - Add those expected changes to your Model's `$beforeUpdate` hook.
    - Or you can, of course, re-fetch the instance using `const reFetchedUser = await user.$query();` as mentioned in the docs [here](http://vincit.github.io/objection.js/#_s_query).

**Comment by Palisand** [comment]
I am using MySQL, I'm not concerned with properties that were not part of the update arguments (like `updated_at`), and I completely forgot about $beforeUpdate and $afterUpdate!
