### ISSUE TITLE
orderBy is ignored in the where builder

### ISSUE THREAD

**Issue by seeden** [Vincit/objection.js#821]
orderBy is ignored when it is used inside where. It is working outside of the where. Here is small example 

```js
static async search(text) {
  return this
      .query()
      .where((builder) => {
        if (text) {
          builder.where('name', 'ILIKE', `%${text}%`);
        }

        return builder
          .orderBy('followersCount', 'DESC')
          .orderBy('id', 'ASC');
      })
      .limit(first);
```

**Comment by elhigu** [comment]
So it seems https://runkit.com/embed/5w4xho1llwq7

**Comment by seeden** [comment]
Yes, orderBy is ignored as you can see on the result

**Comment by elhigu** [comment]
So correct function there would be throwing an exception, since you are trying to generate invalid SQL?

**Comment by elhigu** [comment]
> select * from "foo" where ("name" ilike ? order by "followersCount" ) 

Wouldn't be valid SQL so this is just an user error.

**Comment by elhigu** [comment]
Also would be good to write runkit example to bug reports that are about invalid query generation. OP test case wasn't actually runnable as is. In this case luckily it didn't took more than minute to get to reproduce.
