### ISSUE TITLE
Confusion over docs concerning from/to arguments

### ISSUE THREAD

**Issue by kswope** [Vincit/objection.js#823]
A large portion of the docs make it seem like Models are used in the from/to

```
        join: {
          from: 'Person.id',
          to: 'Person.parentId'
        }
```

```
        modelClass: Animal,
        join: {
          from: 'Person.id',
          to: 'Animal.ownerId'
        }
```

In other places it seems like the table names themselves are used

```
      modelClass: Person,
      join: {
        from: 'animal.ownerId',
        to: 'person.id'
      }
```

After hours of bafflement I finally succeeded with the table names only.

Can we get some clarification?

**Comment by koskimas** [comment]
You can get confirmation by reading [the documentation](http://vincit.github.io/objection.js/#relationmappings). The documentation for the `RelationJoin` object clearly states that table names should be used.

**Comment by kswope** [comment]
Ok in my defense I was watching tv, but from the users point of view, do you not agree that if the user sees over 20 examples that look just like this

```
        modelClass: Animal,
        join: {
          from: 'Person.id',
          to: 'Animal.ownerId'
        }
```
And as you point out, about 10 thousand lines down in the documentation (not exaggerating much) 

> The from and to properties of the join object define the database columns through which the models are associated.

Which itself is a little cryptic.  Why could you not refer to a "database column" as Model.column?

And on top of that, when I see "Person", or "Animal", I would never think of those as table names because its common practice these days (probably thanks to rails) to name your tables in the plural way.

**Comment by koskimas** [comment]
I was trying to point you to the the (only) place where the properties `from` and `to` are documented in the API documentation. This place

<img width="714" alt="screen shot 2018-02-28 at 2 08 17" src="https://user-images.githubusercontent.com/846508/36762485-77a5c428-1c2c-11e8-9426-9f2038dcd613.png">

> The relation column in the owner table. __Must be given with the table name__. For example ...

In the future, I'd suggest that you see the API documentation of the method/object/class/whatever when something is confusing.

> And on top of that, when I see "Person", or "Animal", I would never think of those as table names because its common practice these days (probably thanks to rails) to name your tables in the plural way.

Not sure if that's a common practice, but I agree that using the same table and model name is unnecessarily confusing. I'll change the table names to lowercase plural versions of the model name.

**Comment by newhouse** [comment]
@koskimas I've noticed a slowly, but steadily increasing amount of "documentation" related requests coming up. The least I can do is help this project out by helping to improve the docs when/wherever you or others see fit. Feel free to tag/mention me if you want me to have a go at anything that comes up. That way your time can be spent working on the code.

**Comment by koskimas** [comment]
Thanks @newhouse! I'd love your help, but I don't like to assign stuff to anyone. I'll tag the documentation issues with the `docs` tag and you can select whatever you like when you have time. Just add a comment and I'll know you're working on it.
