### ISSUE TITLE
Define default query method in Model

### ISSUE THREAD

**Issue by asadakbar** [Vincit/objection.js#824]
I'm trying to define a default orderBy for any query that is done on a model. I can't chain Person.query() with onBuild because I am using upsertGraphAndFetch and want the fetch that happens to come back ordered using a default orderBy defined inside the model. Is there a way to do that?

If your suggestion is a custom query builder, one issue with that approach for me is that I already have a custom query builder defined for the base model class. I tried creating a child QueryBuilder class, but its not clean as I am having to redo the Parent QueryBuilders constructor function with its logic when I just want to add onto any query a default orderBy. The other issue is that I am hitting an error when I do that

`Unhandled rejection Error: select count(*) from "offers" where not "status" = $1 and not "status" = $2 order by "created_at" asc - column "offers.created_at" must appear in the GROUP BY clause or be used in an aggregate function`

**Comment by asadakbar** [comment]
I figured out a different way of doing this so am closing this issue. I'm curious how to do it the way I initially planned, but no problem if no one can respond.

**Comment by radiumrasheed** [comment]
@asadakbar whats the diff way ?

**Comment by asadakbar** [comment]
@radiumrasheed I don't have access to the codebase anymore and don't recall how I did it. Apologies. Wanted to followup so at least you know.
