### ISSUE TITLE
Documentation example for format*Json and parse*Json

### ISSUE THREAD

**Issue by Stephane-Peyroutet** [Vincit/objection.js#825]
Congratulations on the 1.0.0 release. I find Objection has achieved to be both simple & powerful.
Plus, the documentation is quite good with lot of examples.

But when I tried to use $formatDatabaseJson and $parseDatabaseJson, I did not find much.

My problem was quite simple : convert boolean to integer value.
I use SQLite3, so boolean values are stored as integers.
And I get an integer value (0 or 1) on my Json when I do a query, even if I specify boolean in the knex schema migration builder or in the objection model, 

So, I thought Objection and format/parseDatabaseJson were the perfect place to do this :
```
$formatDatabaseJson(json) {
  let db = super.$formatDatabaseJson(json);
  db.enabled = (db.enabled) ? 1 : 0;
  return db;
}
```
```
$parseDatabaseJson(db) {
  let json = super.$parseDatabaseJson(db);
  json.enabled = (json.enabled === 1) ? true : false;
  return json;
}
```

First, this seems to work but I'm not sure if there is a better way to do it or to answer my problem ?
I'm also wondering if this can be improved and made "generic" ? (without specifying each boolean field).

Second, it would be nice to have a real life example for those functions in the documentation.
I did find one here : #60, but this is not really about conversion but about computed field.

**Comment by koskimas** [comment]
Thank you!

You're absolutely right, there should be an example for those. I'll add this to my todo list.

> First, this seems to work but I'm not sure if there is a better way to do it or to answer my problem ?
I'm also wondering if this can be improved and made "generic" ? (without specifying each boolean field).

You could implement those methods in a common base class (for example `BaseModel`) and use `jsonSchema` to determine the type. If you don't use jsonSchema, you can add a static property for your model classes.

**Comment by Stephane-Peyroutet** [comment]
Thank you @koskimas.

I did also forget to mention that your (meaning you and the community :-) issue treatment and resolution is also one of the most efficient.

I do like the idea of using a `BaseModel` class.
It's pretty clean and I will probably use it anyway to have modelPaths or other stuff in there.

I tried a bunch of stuff to test my code in the `Person `model and I ended up with something like this :
```
  $parseDatabaseJson(db) {
    print('parse');
    let json = super.$parseDatabaseJson(db);
    if (Person.jsonSchema && Person.jsonSchema.properties) {
      var keys = Object.entries(Person.jsonSchema.properties);
      for (var i = 0 ; i < keys.length ; i++) {
        if (keys[i][1].type) {
          if (keys[i][1].type === 'boolean') {
            json[keys[i][0]] = (json[keys[i][0]] === 1) ? true : false;
          }
        } else {
          print('Missing type key for property ' + keys[i][0] + ' on jsonSchema');
        }
      }
    }
    else {
      print('Missing jsonSchema or jsonSchema.properties');
    }
    return json;
  }
```
I check for errors and use some 'print' function to customize with your taste (console.log, debug, logfile).
One thing I don't handle is a property of type: ['boolean', 'null'] which I don't use and I'm not sure is relevant.

I have two questions :

- how do I get this up to the BaseModel class ? I get some errors and I can't seem to find my way around.
- the parseDatabaseJson seems to parse more than it should : I got 18 "parse" for 16 db rows.
What are those extras pass in the parseDatabaseJson ? Where could this come from ?

**Comment by koskimas** [comment]
> how do I get this up to the BaseModel class ? I get some errors and I can't seem to find my way around.

Each javascript class instance has a `constructor` property. Simply replace `Person.jsonSchema` by `this.constructor.jsonSchema`. You should probably also only access `jsonSchema` once, since it returns a new object each time it is accessed (if a getter is used).

> the parseDatabaseJson seems to parse more than it should : I got 18 "parse" for 16 db rows.
What are those extras pass in the parseDatabaseJson ? Where could this come from ?

`$parseDatabaseJson` is used to map column names to property names. The calls are cached though, so you should only see one "extra" call per property during the lifetime of the process.

**Comment by koskimas** [comment]
You can throw whatever you like from there and the execution of the query will be halted and your error is thrown from the query. Let's keep this open. We'll close this when the example is written.

**Comment by Stephane-Peyroutet** [comment]
Hi @koskimas 

Just to let you know, I use Typescript now and I got everything working nice with a BaseModel.
I just wanted to point out that I struggled to access the jsonSchema static variable without any error and I ended up using this line :
`let schema = (<typeof BaseModel> this.constructor).jsonSchema;`

The "extra calls" I had were coming from my request.
Basically, if if I just do Animal.query(), I got as many calls as I have rows.
If I do Animal.query().eager('owner'), I got some extra calls the first time (as you mentioned, this is cached).

If anybody might be interested with some code, here it is :

```
import { Model } from 'objection';

export default class BaseModel extends Model {
  static modelPaths = [__dirname];

  $formatDatabaseJson(json: any) {
    let db: any = super.$formatDatabaseJson(json);
    let schema = (<typeof BaseModel> this.constructor).jsonSchema;
    if (schema && schema.properties) {
      let properties: any = schema.properties;
      let keys: any = Object.keys(properties);
      for (let i = 0 ; i < keys.length ; i++) {
        if (properties[keys[i]].type) {
          if (properties[keys[i]].type === 'boolean') {
            db[keys[i]] = (db[keys[i]]) ? 1 : 0;
          }
        } else {
          throw(new Error('Missing type information for property \"' + keys[i] + '\" on jsonSchema'));
        }
      }
    } else {
      throw(new Error('Missing jsonSchema or jsonSchema properties on Model'));
    }
    return db;
  }

  $parseDatabaseJson(db: any) {
    let json: any = super.$parseDatabaseJson(db);
    let schema = (<typeof BaseModel> this.constructor).jsonSchema;
    if (schema && schema.properties) {
      let properties: any = schema.properties;
      let keys: any = Object.keys(properties);
      for (let i = 0 ; i < keys.length ; i++) {
        if (properties[keys[i]].type) {
          if (properties[keys[i]].type === 'boolean') {
            json[keys[i]] = (json[keys[i]] === 1) ? true : false;
          }
        } else {
          throw(new Error('Missing type information for property \"' + keys[i] + '\" on jsonSchema'));
        }
      }
    } else {
      throw(new Error('Missing jsonSchema or jsonSchema properties on Model'));
    }
    return json;
  }
}
```

**Comment by koskimas** [comment]
Actually the docs have examples on how to override these. I don't know what other kind of examples I would add.
