### ISSUE TITLE
reset trx after transaction

### ISSUE THREAD

**Issue by seeden** [Vincit/objection.js#826]
I am not able to use model returned by transaction after transaction.
I see Error: Transaction query already complete, run with DEBUG=knex:tx for more info +0ms
  server:error Uncaught Execption

It is absolutely correct warning because I am calling my code after transaction. But I thought that objection will clear transaction from my object automatically after transaction or I missed something?

```js

await currentUser = await objection.transaction(User, async (UserModel) =>  {
  const user = await UserModel.getById(345);
 // ... some code here
 
  return user;
});

// next code will throw exception because transaction ended already
await currentUser
      .$query()
      .patch({ name: 'Peter' })
      .first()
      .returning('*'); 
```

**Comment by elhigu** [comment]
AFAIK thats caveat in objection and working with objects created in transaction. IMO it is correct that it throws an error, since you are trying to do something which does not make sense.

You can make your code to work like this:

```js
await currentUser = await objection.transaction(User, async (UserModel) =>  {
  const user = await UserModel.getById(345);
 // ... some code here
 
  return user.bindKnex(User.knex()); // return correctly bound instance from knex
});

// next code will throw exception because transaction ended already
await currentUser
      .$query()
      .patch({ name: 'Peter' })
      .first()
      .returning('*'); 
```

**Comment by koskimas** [comment]
As @elhigu mentioned, that's a caveat of the model binding pattern. I'm trying to steer people away from that pattern nowadays because I think it causes more problems than it solves. There's no easy way to fix this particular "bug".
