### ISSUE TITLE
Document the release process

### ISSUE THREAD

**Issue by koskimas** [Vincit/objection.js#83]
- [ ] alpha/beta/rc versions and the `@next` npm tag
- [ ] when can we expect breaking changes
- [ ] for which version is the documentation

Anything else?

**Comment by mceachen** [comment]
Just in case you haven't seen it, I've found [np](https://github.com/sindresorhus/np) to be simple and do what I wanted a release process to do, straight out of the box.

**Comment by koskimas** [comment]
We should start moving towards 1.0 and real semver. @ next tag is already documented.

**Comment by mceachen** [comment]
* I wouldn't worry about alpha/beta/rc unless you've got a huge refactor coming.
* I'd hope you'd add deprecation warnings with instructions on migrations before breaking anything
* I'd let master document master, and as you tag source, you can tag your docs.

👍 for passing 1K stars, btw!
