### ISSUE TITLE
undefined passed as argument #1 for "whereComposite" operation

### ISSUE THREAD

**Issue by rivertam** [Vincit/objection.js#831]
Hi! I'm trying to do a simple patch on a model I've got, and I'm running into the following issue. I don't believe I'm doing anything tricky, though I'm sure it's something I'm doing wrong

Here's my class:
```javascript
export class User extends Model {
  static tableName = 'users';

  static jsonSchema = {
    type: 'object',
    required: ['companyId', 'email'],
    properties: {
      email: { type: 'string', minLength: 1, maxLength: STRING_MAX_LENGTH },
      companyId: { type: 'string', minLength: ID_LENGTH, maxLength: ID_LENGTH },
      title: { type: ['string', 'null'] },
      name: { type: ['string', 'null'] },
      isManager: { type: 'boolean' },
    },
  };

  static get relationMappings() {
    return {
      company: {
        relation: Model.BelongsToOneRelation,
        modelClass: Company,
        join: {
          from: 'users.companyId',
          to: 'companies.id',
        },
      },
    };
  }
}
```

it extends a base `Model` I created for convenience

```javascript
export default class extends Model {
  $beforeInsert() {
    this.created_at = new Date().toISOString();
    if (this.constructor.jsonSchema.properties.id) {
      this.id = uuid();
    }
  }

  $beforeUpdate() {
    this.updated_at = new Date().toISOString();
  }

  get term() {
    return {
      start: this.termStart && this.termStart.toISOString(),
      end: this.termEnd && this.termEnd.toISOString(),
    };
  }

  set term(term) {
    this.termStart = term.start;
    this.termEnd = term.end;
  }
}
```

And here's what I'm running (it's in a REPL, so the first line happens seconds before the second)

```javascript
> User.query().findOne({ email: '...' }).then(u => global.u = u)
> u.$query().patch({ isManager: true }).then(u => console.log(u))
```

However, as the title suggests, I'm getting the somewhat cryptic error "undefined passed as argument #1 for 'whereComposite' operation" on the second line. I'm sure I'm doing something wrong, though, to tell you the truth, it seems very likely Objection could do a better job of telling me what I'm doing wrong.

**Comment by koskimas** [comment]
Does `User` have an `id` property or some other primary key and have you specified it using `static idColumn = 'theIdColumn'`? The `jsonSchema` doesn't seem to mention `id` property which is the default `idColumn`.

**Comment by rivertam** [comment]
Its primary key is `email`. I guess I missed the `idColumn` documentation. My bad! I do think the error message could have been less cryptic though. :)

**Comment by koskimas** [comment]
I'll add a better error message for that case. The `idColumn` documentation is a bit hidden also, but I don't really know how and where to document it better. Any suggestions?

**Comment by rivertam** [comment]
Great, thanks! Personally, I'm quite example-driven, so I think the most effective way to have gotten me to notice it would have been to have an example that uses it in the overview of Models. Currently, the only example is down in the documentation specific to `idColumn`, so you kind of have to be looking for it to see the example.

**Comment by koskimas** [comment]
That's true. The reason I haven't added it to the model examples is that it usually doesn't have to be specified, and I wanted to keep the examples as simple as possible. I'll add it to the examples.
