### ISSUE TITLE
Error converting data type when using multiple through joins

### ISSUE THREAD

**Issue by tomjennings100** [Vincit/objection.js#832]
Hi, 

thanks for the excellent library. I'm using the mssql driver with Knex. 

Here are my relation maps for the Theme model: 
```
static get relationMappings() {
    return {
      Articles: {
        relation: Model.ManyToManyRelation,
        modelClass: Article,
        join: {
          from: "Theme.ThemeId",
          through: {
            from: "ThemeTag.ThemeId",
            to: "ThemeTag.TagId"
          },
          through: {
            from: "TagArticleInstanceRelation.TagId",
            to: "TagArticleInstanceRelation.InstanceId"
          },
          to: "LatestArticleView.InstanceId"
        }
      }
    };
```
when I run the following query: 
```
await Theme.query()
      .eager("Articles.[Sources, Contributor]")
      .modifyEager("Articles", builder => {
        builder.where("LatestArticleView.SaveDate", ">", "2018-1-1");
      });
```

i receive the following error from SQL server: 

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: select [LatestArticleView].*, [TagArticleInstanceRelation].[TagId] as [objectiontmpjoin0] from [LatestArticleView] inner join [TagArticleInstanceRelation] on [LatestArticleView].[InstanceId] = [TagArticleInstanceRelation].[InstanceId] where [TagArticleInstanceRelation].[TagId] in (@p0, @p1) and [LatestArticleView].[SaveDate] > @p2 - Error converting data type nvarchar to bigint.
```

Which I assume is an error in the join (TagId is a bigint) Are multiple through joins supported? If not, is there a way I can rewrite this query so i get a response: 

```
Theme {
    ThemeTitle{ 
        [Articles]
    }
}
```

Thanks, 

Tom

**Comment by koskimas** [comment]
Unfortunately multiple through objects are not supported for m2m relationships. (even in ecmascript the way you defined them :D).

Can't you just write `Theme.query().eager('ThemeTitle.Articles')`?

**Comment by tomjennings100** [comment]
Thanks for the quick reply, i was surprised when babel let me get away with multiple keys with the same name!
 
Sorry - i wasn't clear in my pseudo-code, I'll try and give a more realistic example - so currently my (working) query is: 
```javascript
Theme.query().eager("Tags.Articles.[Sources, Contributor]")
``` 

which returns the correct data, but each Article is within a Tag object, whereas I would like it to be under a Theme, hence the attempt at multiple many-to-many joins. 

I can of course map-reduce the result, but I'd rather do it from within the query if i can.

**Comment by koskimas** [comment]
No, that's not possible I'm afraid. It would be cool if that was possible, but the relationship stuff is already super complicated because each relationship type needs to support eager queries, graph inserts, graph upserts, composite keys, json reference composite keys etc. 😅This is something I could try to implement at some point, but probably not in a while. You need to find another way to do that for the time being.
