### ISSUE TITLE
Raw with Transactions

### ISSUE THREAD

**Issue by Knaackee** [Vincit/objection.js#834]
Is there a way to fire up a raw query/insert/update with a transaction?
I cant find something in the docs whether here nor at the knex docs.

Thanks in advance!

**Comment by koskimas** [comment]
Depending on how you use transactions, any of these should work:

```js
await transaction(Person, (Person, trx) => {
  await trx.raw('select * from foo');
});
```

```js
await transaction(Person.knex(), trx => {
  await trx.raw('select * from foo');
});
```

It's documented [here](http://knexjs.org/#Transactions) that the transaction object can be used as a knex instance.
