### ISSUE TITLE
Eager loading filter is not applied in upsertGraphAndFetch

### ISSUE THREAD

**Issue by SokratisVidros** [Vincit/objection.js#839]
Hi there,

I've notived an inconsistent behavior when combining eager loading filters with `upsertGraphAndFetch` function.

Supposedly we have the following schema: `User * - * Roles via UserRoles join table`

| Table | Columns |
| --- | --- |
| Users | id, name , timestamps |
| Roles | id, name, timestamps |
| UserRoles | role_id, user_id |

When using `insertGraphAndFetch` along with `roles.name` projection, results contain only role names as expected. However, when using `upsetGraphAndFetch` projection is not applied. In further detail:

```js

// Fetches only role names (Correct)
User
  .query(trx)
  .eager('roles')
  .modifyEager('roles', q => q.select('name'))
  .insertGraphAndFetch(...)

// Fetches all role columns (Wrong)
User
  .query(trx)
  .eager('roles')
  .modifyEager('roles', q => q.select('name'))
  .upsertGraphAndFetch(...)
```

Any suggestions will be greatly appreciated.

**Comment by koskimas** [comment]
`modifyEager` is applied for neither of those queries. I don't know why the first one works.

**Comment by SokratisVidros** [comment]
Oops, I see. Shouldn't we enforce a consistent behaviour across both functions?

**Comment by koskimas** [comment]
This hasn't come up before, so I'm quessing it's not a common mistake. I'd merge a PR that fixes this though. If you implement this, all other read-only methods need to be disabled too, not only `eager`.

**Comment by SokratisVidros** [comment]
Cool, thanks a lot!
