### ISSUE TITLE
QUESTION: Querying nested objects

### ISSUE THREAD

**Issue by robertd** [Vincit/objection.js#84]
Hi.

If my pgsql record looks like this where `info` is jsonb

```
{
   "id": 12345,
   "type": "Feature", 
   ...
   "info": {
      ...
     "properties": {
       "CITY": "Los Angeles",
       "STATE": "CA"
     }
}
```

...how do I query by `STATE` field?

I've tried this but no luck:

```
Model
      .query()
      .select()
      .whereJsonSubsetOf('info:properties',  [{ 'STATE': req.params.state }])
      .dumpSql();
```

I've tried looking into docs but I got lost :smile: 

Thanks!

**Comment by koskimas** [comment]
This should work:

```js
Model
  .query()
  .whereJsonSupersetOf('info:properties',  { 'STATE': req.params.state })
  .dumpSql();
```

Notice that in addition to removing the array, I swapped the `subset` to `superset`. The reasoning here is this:

```
{a:'foo', b:'bar', c:'baz'} is superset of {a: 'foo'}
```

just like

```
[1, 2, 3] is superset of [1]
```

So object is a superset of another object if it has all its key-value pairs, just like array is a superset of another array if it has all its values.

**Comment by robertd** [comment]
@koskimas :+1:
