### ISSUE TITLE
"Error: No database selected" with Mariadb

### ISSUE THREAD

**Issue by locpd** [Vincit/objection.js#850]
I don't know if this issue is related to objection or knex. I used 'mariasql' database library and objection always complains that no database is selected, although I initialized knex & called Model.knex(knex). After several hours looking through documentations & examples and couldn't find any error in my code, I just tried adding 'mysql' package & changing 'mariasql' to 'mysql' in knex client configuration. And that's it, it worked. And I'm still running MariaDb database, I just changed the sql client library that knex uses.

**Comment by koskimas** [comment]
This is a knex's issue. You should open an issue in their githhub.

**Comment by elhigu** [comment]
mariasql driver support was deprecated (driver was not maintained), mysql or mysql2 driver should be used with mariadb.
