### ISSUE TITLE
insert/upsertGraph - HasManyRelations with repeated items

### ISSUE THREAD

**Issue by peterjuras** [Vincit/objection.js#851]
Hi!

First of all thanks for this library, I'm new to objection.js but it is really awesome so far!

I'm having trouble with creating a relationship similar to the following example: I have a `List` that has `Item`s. The list can contain a unique item multiple times, therefore I also have a `ListItem` model. Considering the following code:

```js
import knex from "knex";
import { Model } from "objection";

const db = knex({
  client: "pg",
  connection: {
    host: "localhost",
    user: "postgres",
    password: "postgres",
    database: "postgres"
  }
});
Model.knex(db);

class Item extends Model {
  static tableName = "Item";
  static idColumn = ["listId", "id"];
}

class ListItem extends Model {
  static tableName = "ListItem";
  static idColumn = ["listId", "id"];

  static relationMappings = {
    item: {
      relation: Model.BelongsToOneRelation,
      modelClass: Item,
      join: {
        from: `${ListItem.tableName}.itemIdId`,
        to: `${Item.tableName}.id`
      }
    }
  };
}

class List extends Model {
  static tableName = "List";

  static relationMappings = {
    items: {
      relation: Model.HasManyRelation,
      modelClass: ListItem,
      join: {
        from: `${List.tableName}.id`,
        to: `${ListItem.tableName}.listId`
      }
    }
  };
}

async function index() {
  await db.schema.dropTableIfExists(ListItem.tableName);
  await db.schema.dropTableIfExists(Item.tableName);
  await db.schema.dropTableIfExists(List.tableName);
  await db.schema.createTable(List.tableName, table => {
    table.integer("id").primary();
  });
  await db.schema.createTable(Item.tableName, table => {
    table.integer("listId");
    table.integer("id");

    table.primary(["listId", "id"]);
  });
  await db.schema.createTable(ListItem.tableName, table => {
    table.integer("listId");
    table.integer("id");

    table.integer("itemId").notNull();

    table
      .foreign(["listId", "itemId"])
      .references(["listId", "id"])
      .inTable(Item.tableName)
      .onDelete("CASCADE");
    table.primary(["listId", "id"]);
  });

  await List.query().insertGraph({
    id: 1,
    items: [
      {
        id: 1,
        item: {
          // listId: 1,
          id: 1
        }
      },
      {
        id: 2,
        item: {
          // listId: 1,
          id: 1
        }
      }
    ]
  });
}

index()
  .catch(console.error)
  .then(() => db.destroy());
```

I have two problems:
- If `// listId: 1` is commented out, as in the example, it throws the following error ` error: null value in column "listId" violates not-null constraint (detail: 'Failing row contains (null, 1).')`
  - Why is `listId: 1` not added automatically like it is for the created `ListItem` object?
- If `listId: 1` is no longer commented out on the item, I would expect that the `Item { listId: 1, id: 1 }` is only inserted once, and then reused on the second `ListItem` object. However, the following error is thrown, indicating that the `Item` is being inserted twice: ` error: duplicate key value violates unique constraint "Item_pkey" (detail: 'Key ("listId", id)=(1, 1) already exists.')`

Does anyone know where the issue lies?

**Comment by peterjuras** [comment]
I think I solved problem number 2 by using `#id` and `#ref`.

Is there a way to solve problem 1, without specifying `listId` explicitly?

**Comment by koskimas** [comment]
`listId` should get automatically set, if you defined it as a part of the relation definition like this:

```js
  static relationMappings = {
    item: {
      relation: Model.BelongsToOneRelation,
      modelClass: Item,
      join: {
        from: [`${ListItem.tableName}.itemIdId`, `${ListItem.tableName}.listId`],
        to: [`${Item.tableName}.id`, `${Item.tableName}.listId`]
      }
    }
  };
```
but I don't know if that makes sense in your data model.

**Comment by koskimas** [comment]
Other option is to remove the `listId` from `idColumn`. Why does it need to be there? Doesn't `id` already uniquely identify each row?

**Comment by peterjuras** [comment]
Thanks for the quick reply. Sorry for the confusing model, I'm trying to extract the relevant parts of my model into a minimal example for this issue. Removing listId would work, but I'd like to get this to work with a composite key.

Your relationMapping sadly didn't work. Are you sure that `itemId` and `.id` need to come as the first element of the array? Either way neither this order, nor putting the ids at the end worked, I still receive a not null constraint violation for the missing venueId.

**Comment by koskimas** [comment]
The order of the columns is correct for what I had in mind. In your example.`listId` is not part of the `ListItem.item` relation. Objection knows nothing about the actual database schema or knex migrations. All it knows is the `relationMappings` definitions.

You could use something like this:

```js
  await List.query().insertGraph({
    '#id': 'list',
    id: 1,
    items: [
      {
        id: 1,
        item: {
          listId: '#ref{list.id}',
          id: 1
        }
      },
      {
        id: 2,
        item: {
          listId: '#ref{list.id}',
          id: 1
        }
      }
    ]
  });
}
```

but I don't know if that helps you much.

Other than that, I don't think there's much `insertGraph` can do in this case.

**Comment by peterjuras** [comment]
Thanks, I'll use the `#ref` to get the list id explicitly then.
