### ISSUE TITLE
UpsertGraph throws error if uuid typed id is not lowercased

### ISSUE THREAD

**Issue by peterjuras** [Vincit/objection.js#852]
Hi!

It appears that `upsertGraph` throws a `root model does not exist` error if the id column is of type `uuid` and the specified id is in uppercase. Specifying the id in lower case works.

Example to reproduce:
```js
import knex from "knex";
import { Model } from "objection";

const db = knex({
  client: "pg",
  connection: {
    host: "localhost",
    user: "postgres",
    password: "postgres",
    database: "postgres"
  }
});
Model.knex(db);

class Entity extends Model {
  static tableName = "Entity";
}

async function index() {
  await db.schema.dropTableIfExists(Entity.tableName);
  await db.schema.createTable(Entity.tableName, table => {
    table.uuid("id").primary();
    table.integer("value");
  });

  const upperCaseUUID = "9E0A5777-15C8-444B-A718-ED7926AA9C93";
  const lowerCaseUUID = upperCaseUUID.toLowerCase();

  await Entity.query().upsertGraph(
    {
      id: upperCaseUUID,
      value: 1
    },
    { insertMissing: true }
  );

  try {
    await Entity.query().upsertGraph({
      id: upperCaseUUID,
      value: 2
    });
  } catch (error) {
    console.error("This upsert should not throw");
    console.error(error);
  }

  // This works however
  await Entity.query().upsertGraph({
    id: lowerCaseUUID,
    value: 2
  });
}

index()
  .catch(console.error)
  .then(() => db.destroy());
```

**Comment by koskimas** [comment]
This has nothing to do with objection. Probably has something to do with the `uuid` type in your database engine or the database driver.

**Comment by koskimas** [comment]
This may help https://www.postgresql.org/docs/9.1/static/datatype-uuid.html

**Comment by koskimas** [comment]
Postgres seems to convert the uuid's to lowercase. Try running this in psql:

```sql
select '9E0A5777-15C8-444B-A718-ED7926AA9C93'::uuid::text;
```

**Comment by peterjuras** [comment]
While it's true that this is postgres specific, upsertGraph is the only place where the uppercase uuid matters. Other queries, e.g.
```js
Entity.query().where('id', upperCaseUUID) // Returns the row
```
work fine.

**Comment by koskimas** [comment]
upsertGraph compares the values in code, and the database returns lowercased uuid's. What would you have objection do here? Lowercase all strings? That's obviously not an option. Objection doesn't know about the column's type in the db, and even if it did, adding a special case for one database engine and one data type would be kind of a hack. If we start doing this for all database engines and all datatypes, the code will become unmaintainable.

If you want to use yhe postgres uuid type, you need to live by its rules and use lowercased strings everywhere. Are you sure you need the uuid type though? Would a normal string type work? Or are you using the postgres's special uuid functions?
