### ISSUE TITLE
Can't figure out how to upsertGraph with ManyToManyRelation and extra field

### ISSUE THREAD

**Issue by alextewpin** [Vincit/objection.js#854]
So, my model looks like this:
```js
class Game extends Base {
  static get tableName() {
    return 'Game';
  }
  static get relationMappings() {
    return {
      players: {
        relation: Model.ManyToManyRelation,
        modelClass: 'User',
        join: {
          from: 'Game.id',
          through: {
            from: 'Game_User.gameId',
            to: 'Game_User.userId',
            extra: ['result'],
          },
          to: 'User.id',
        },
        filter: query => query.clearSelect().select('id', 'nickname'),
      },
    };
  }
};
```

And I'm trying to execute this upsert:
```js
Game
  .query(trx)
  .upsertGraph({
    id: 5,
    status: 'ended',
    players: [
      {
        id: 1,
        status: 'win',
      },
      {
        id: 2,
        status: 'loss',
      },
    ],
    updatedAt: new Date(),
  }, {
    relate: true,
    unrelate: true,
  });
```

Relation table already exists at this point, so all I want to is update statuses. But I'm getting this error:
```
update "User" set "nickname" = $1 where "User"."id" in (select "id", "nickname", "User"."id" from "User" inner join "Game_User" on "User"."id" = "Game_User"."userId" where "Game_User"."gameId" in ($2) and "User"."id" = $3) - subquery has too many columns
```

It look like filter interferes with upsert somehow. At least it works perfectly fine without it. But I don't want to filter all user fields by hand each time. It contains some private info, so I really don't want to screw up here.

It there any workaround here? Should I just upsert stuff to each individual table separately? Or maybe I'm trying to do some nonsense at the first place?

**Comment by koskimas** [comment]
You can implement a `$parseDatabaseJson` or `$formatJson` method for your models and delete the private info there. You shouldn't use select in a relation filter like this because, well, it creates invalid SQL :smile:

```js
class Player extends Model {
  $formatJson(json) {
    json = super.$formatJson(json);
    delete json.somePrivateProp;
    delete json.modePrivateThings;
    return json;
  }
}
```

**Comment by alextewpin** [comment]
@koskimas Thank you so much for the explanation!
