### ISSUE TITLE
Validation fails when calling fromJson on entity with relationships and additionalProperties=false

### ISSUE THREAD

**Issue by igor-savin-ht** [Vincit/objection.js#855]
When calling fromJson, validation is invoked on passed data without adding relationship fields as valid supported properties, and expectedly fails.

**Comment by koskimas** [comment]
Relations are converted into models and validated. That's expected.

**Comment by igor-savin-ht** [comment]
@koskimas But how can one avoid getting failures in such a use-case? I presume it would be wildly wrong to have both field and relationship with the same name - but how can you pass validation otherwise?

**Comment by igor-savin-ht** [comment]
From my understanding, validation should be done using enriched model schema, that would combine defined properties with defined relationships, which is not currently the case.

**Comment by koskimas** [comment]
Maybe I misunderstood your issue. Could you write a code snippet that demonstrates the issue?

**Comment by igor-savin-ht** [comment]
@koskimas See related commit with commented out code (https://github.com/kibertoad/objection.js/commit/1d0922aa79722d0c719bd586ec7add03fb52ed22) :). Basically validation is unnecessarily strict and considers relationship fields invalid when 'additionalProperties: false' is set.

**Comment by igor-savin-ht** [comment]
@koskimas Here is a better overview that combines both commits: https://github.com/Vincit/objection.js/compare/master...kibertoad:fix/855-validating-relationships
I can also shorten the test to focus on just validation failing, if that would make it more readable :)

**Comment by igor-savin-ht** [comment]
@koskimas So what is your conclusion on this, is it a legitimate issue? If yes, maybe it should be reopened?..

**Comment by koskimas** [comment]
This seems like a legit bug. I'll fix it for the next patch release.
