### ISSUE TITLE
Passing a through object to a relation that doesnt support it should throw

### ISSUE THREAD

**Issue by Burtonium** [Vincit/objection.js#857]
It would have saved me hours of debugging here. I don't see why this couldn't happen.

**Comment by koskimas** [comment]
I'll add it. Next time try a different tone in your issue. I'm doing this on my free time. I have a zero tolerance for entitled bullshit nowadays. I'm closing this just so that I don't need to look at this when I open the issues next time, but I'll fix this for yoi.

**Comment by koskimas** [comment]
I'll fix this.
