### ISSUE TITLE
Error duplicate key value on update

### ISSUE THREAD

**Issue by walkerlangley** [Vincit/objection.js#860]
I'm trying to update an existing field in a db by calling `db.TableName.query().update({key: key, value: value })` and am getting the following error message `{ error: update "setting" set "key" = $1, "value" = $2, "updated_at" = $3 - duplicate key value violates unique constraint "setting_key_unique"`  I'm a bit confused on the unique value constraint because I'm trying up update a value, so of course it exists.

Any ideas?

**Comment by koskimas** [comment]
Your query attempts to update every single line in the database because you have no `where` statements.

**Comment by koskimas** [comment]
You need to add something like:

```js
db.TableName.query().update({key: key, value: value }).where({ key });
```

to tell objection which rows you want to update.

**Comment by walkerlangley** [comment]
Got it.  Thanks.
