### ISSUE TITLE
toJSON and virtual attributes | question

### ISSUE THREAD

**Issue by seeden** [Vincit/objection.js#866]
Is it possible to get model json without virtual attributes?

**Comment by koskimas** [comment]
Nope, but maybe there should be. `toJSON` already accepts an options object. We could add a `virtuals` boolean option.

**Comment by seeden** [comment]
yes, that will be great.
Here is my use case:
I am using redis for communication between servers. On first one I am using toJSON and second one fromJson. I can skip db request with it.

**Comment by koskimas** [comment]
The 1.1.2 version will also contain this feature.

**Comment by seeden** [comment]
great thanks :) You are doing a great job @koskimas

**Comment by fmmsilva** [comment]
Any updates on this?
