### ISSUE TITLE
Circular/infinite loop encountered when passing model to 3rd party serializer

### ISSUE THREAD

**Issue by newhouse** [Vincit/objection.js#867]
Greetings and continued thanks for your work here!

I experienced an issue the other day where an non-objection-related error occurred, was caught, and, in the process of reporting it to Sentry, a circular reference in my model instance (which was passed to Sentry for "context") ended up going through an infinite loop and finally resulting in a stack size blow up.

You can see my _psuedo_-code and my **_actual_**  logs in a ticket I already filed over at Sentry: https://github.com/getsentry/raven-node/issues/443

A few more things that I think are relevant:
- My model class `Channel` has a `belongsToOne` relationship with my model class `Credential`.
- My model class `Credential` has a `hasMany` relationship with my model class `Channel`.
- `Credential.js:888:31` is `const json = super.toJSON.call(this, options);`. `super` in this case is `Base.js`
- `Base.js:201:37` is `let originalJson = super.toJSON.call(this);`. `super` in this case is Objection's very own `Model`
- The thing that I passed to Sentry was an instance of `Channel`, though the loop seems to have been triggered in the `Credential` serialization.

I'm a bit swamped to create a full repro for you, so admittedly this may be something you can't help with without more code...but thought I'd start by seeing if there were any "a ha!" 💡 moments you had by seeing this as-is. If not, I'll have to take the time to make a standalone repro. Just let me know...

Thanks again!

**Comment by koskimas** [comment]
Don't circular references always blow up when `toJSON()` is called? At least this does:

```js
const { Model } = require('./');

class Person extends Model {}

const p1 = Person.fromJson({});
const p2 = Person.fromJson({});

p1.rel = p2;
p2.rel = p1;

p1.toJSON();
```

**Comment by newhouse** [comment]
When I passed the instance of `Channel` for Sentry to serialize, it blew up:
```
// Blows up
ravenClient.captureException(someError, { extra: { channel: channelInstance } });
```

But if I call `toJSON()` myself and pass that to Sentry, it does not blow up:
```
// Doesn't blow up. How I have currently "fixed" the issue
ravenClient.captureException(someError, { extra: { channel: channelInstance.toJSON() } });
```

Super weird to me...

**Comment by koskimas** [comment]
Could you post the content of `channelInstance` here? Obviously it doesn't contain circular references, since `toJSON` doesn't blow up.

**Comment by newhouse** [comment]
I owe you a repro at this point. Will need some time. Thanks for looking at it as-is.

**Comment by newhouse** [comment]
working on repro today.

**Comment by newhouse** [comment]
Ugh. I can't reproduce it without putting way too much of my entire app in here. If it comes up again and I can isolate in a more standalone-friendly way, I will come back to this.
