### ISSUE TITLE
Cannot read property '$isObjectionModel' of null

### ISSUE THREAD

**Issue by seeden** [Vincit/objection.js#868]
in latest version 1.1.1 I can see next error:
Error: GraphQL error: Cannot read property '$isObjectionModel' of null

version 1.0.1 is fine

**Comment by koskimas** [comment]
How do you expect me to do anyhing based on this?

**Comment by seeden** [comment]
I will add stack trace soon

**Comment by koskimas** [comment]
Could you try to add this to your package.json to see if the fix worked?

```
"objection": "git://github.com/Vincit/objection.git#3ee4718"
```

?

**Comment by seeden** [comment]
sure :)

**Comment by koskimas** [comment]
How about

```
"objection": "git://github.com/Vincit/objection.js.git#4db4b6c"
```

?

**Comment by seeden** [comment]
it is working
