### ISSUE TITLE
Getting top result in a named filter

### ISSUE THREAD

**Issue by Burtonium** [Vincit/objection.js#872]
So my setup is the following, using the documentation's example:

```
class Person extends Model {
  static tableName = 'persons';

  static relationMappings = {
    animals: {
      relation: Model.HasManyRelation,
      modelClass: Animal,
      join: {
        from: 'persons.id',
        to: 'animals.ownerId'
      }
    }
  }
}

class Animal extends Model {
  static tableName = 'animals';

  static namedFilters = {
      latest: query => query.orderBy('created_at', 'desc').limit(1)
  }

  static relationMappings = {
    owner: {
      relation: Model.BelongsToOneRelation,
      modelClass: Person,
      join: {
        from: 'animals.ownerId',
        to: 'persons.id'
      }
    }
  }
}
```

and the relation query is the following to get the most recently added animal

```
const people = await Person.query().eager('animals(latest) as recentlyAddedAnimal');

```

My issue is that the limit(1) will apply to the entire query meaning that only one person will have a recentlyAddedAnimal attached. How do limit 1 animal per person?

**Comment by koskimas** [comment]
That's not possible I'm afraid as explained in the docs. Chain .debug() to the query to see what queries get generated and you'll see whu. You can use naiveEager, but be careful with the performance (it can be really slow).
