### ISSUE TITLE
Throw notFoundError by default

### ISSUE THREAD

**Issue by jannikkeye** [Vincit/objection.js#874]
Hi,

I'm trying to get an error thrown by default if a resource is not found but am failing to do so. I already tried overwriting the Base Models static query method.

Is there a way, instead of chaining .throwIfNotFound to every query, to throw the error by default for every query made?

**Comment by koskimas** [comment]
So you already tried this?

```js
class BaseModel extends Model {
  static query(...args) {
    return super.query(...args).throwIfNotFound();
  } 
}
```

How is it not working?

**Comment by jannikkeye** [comment]
This does look familiar and it indeed works. Must have made a mistake somewhere. Thank you for the quick response, I'm really appreciating it. I should have checked properly.

**Comment by PerpetualWar** [comment]
I'm liking the solution from @koskimas , to add to Base Model, but I have problem with inserting as naturally it is not found in db so it throws...  How to disable throwing for certain query methods like insert in Base Model example?

**Comment by PerpetualWar** [comment]
I'm liking the @koskimas solution above with using Base Model, but problem is error gets thrown even when I wanna insert (it's non existant naturally), cause insert is called on query.

Any idea how to work around that?

**Comment by Juanpam** [comment]
@PerpetualWar I just tested it and I'm not getting any errors while performing an insert query. However, I'm adding this to a Model directly, without extending the Model class with BaseModel.

I'm also using version 2.1.3 with Node 10.15. Hope it helps
