### ISSUE TITLE
validation removes field expressions in patch()

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#875]
Using objection 1.0.0 or 1.1.3.
Doing
```
instance.$query().patch({
  col: 'val',
  'col2:key': 'val2'
})
```
with that kind of schema:
```
{
  col: { type: 'string' },
  col2: {
    type: 'object',
    properties: {
      key: {type:'string'}
    }
  }
}
```
generates sql that only updates "col".

**Comment by kapouer** [comment]
My workaround: https://gist.github.com/kapouer/27c3fc7aaf4ff9382b47d3c867763203

**Comment by koskimas** [comment]
I was not able to reproduce this. Could you create a repro?

**Comment by kapouer** [comment]
Yes, i thought so at first, but this just outlines a bug in objection's update method:
[this call](https://github.com/Vincit/objection.js/blob/34177e8f0a6790d6766e6fd9009594d74108efd8/lib/queryBuilder/operations/UpdateOperation.js#L19) validates the json object which contains the field expressions. The result is that the modifications done through the call to `patch` are not validated against the model schema (said otherwise, setting removeAdditional to false let one bypass validation by using field expressions). I think that's very much misleading.

**Comment by kapouer** [comment]
and there *is* a way to work around the problem...

**Comment by koskimas** [comment]
The patch object IS validated. I'm not followng at all. I think the repro is needed.

**Comment by koskimas** [comment]
There' always a way around everything. Finding a way that doesn't break the tests is the problem.

**Comment by kapouer** [comment]
Here's a simple test.js that you can use in "objection.js" directory of a development installation.
(It needs to be able to connect to postgres).

**Comment by koskimas** [comment]
Ok, so you mean that the field expressions don't get validated. That's true. Fixing this would be difficult. For simple cases like

```js
patch({
  'object:field': 100
})
```

it would be easy, but how about this:

```js
patch({
  'object:field': lit({ nested: 'object' })
})
```
or even this:

```js
patch(
 ref('object:field'), '>', ref('object:anotherField')
})
```

There are many situations where the validation cannot be done.

We could add validation to this particular case with a significant complexity cost, but the other 1000 cases would still remain unvalidated. I think I have to say no to this for now.
