### ISSUE TITLE
Require loop solution in documentation not working with Webpack

### ISSUE THREAD

**Issue by Bram-Zijp** [Vincit/objection.js#881]
I'm using Webpack to transpile parts of my API. When using the ```modelClass: `${__dirname}/Week` ``` solution per mentioning in the documentation, the thrown error is unclear; 

```Client.relationMappings.weeks: modelClass: database\\models/Week is an invalid file path to a model class```

I tried manually writing paths without success. Ideally the error would contain information of the path where it's looking for the file.

**Comment by koskimas** [comment]
It does contain the path...

**Comment by Bram-Zijp** [comment]
@koskimas so it would be looking here;

```
root
    node_modules/objection/...
    database/models/Week  <---
```

However it does not resolve. 

```
root
    node_modules/objection/...
    src/server/api/database/models/Client.js
    src/server/api/database/models/Week.js

```
`webpack context: 'src/server/api/'`

``` `${__dirname}/Week` ``` in `src/server/api/database/models/Client.js` resolves to `'database\\models/Week'` per Objection


It can't find the file.

It also can't find the file when I manual write:
```
modelClass: 'src/server/api/database/models/Week'
modelClass: 'server/api/database/models/Week'
modelClass: '/api/database/models/Week'
modelClass: 'database/models/Week'
modelClass: 'models/Week'
modelClass: '/Week'
modelClass: 'Week'
```

I tried all sorts of imports but it is totally unclear why it can't find the file.


A verbose log could help here in the form of:
`node_modules/../../src/server/api/database/models/Week` is an invalid file path to a model class


Or perhaps something else is the reason for this issue.

This is my webpack config:

```
module.exports = {
    mode: 'development',
    context: path.resolve('./src/server/api/'),
    entry: ['webpack/hot/poll?1000', './index.js'],
    output: {
        path: path.resolve('build'),
        filename: 'api.server.js',
        libraryTarget: 'commonjs2',
        devtoolModuleFilenameTemplate: '[absolute-resource-path]',
    },
    resolve: {
        ...config.resolve,
        mainFields: ['main', 'module'],
    },
    target: 'node',
    node: {
        __filename: true,
        __dirname: true,
    },

```

**Comment by koskimas** [comment]
All objection does is this internally:

```js
const modelClass = require(mapping.modelClass);
```

and what you see in the error is the content of `mapping.modelClass`. It cannot get more verbose than that on objection's part.

**Comment by koskimas** [comment]
`__dirname` should be an absolute file path. I don't know what webpack does with it to make it non-absolute. You should probably use one of the other ways to resolve circular deps.

**Comment by Bram-Zijp** [comment]
Resolved by changing using named exports and using require like so:

Client.js
`export class Client extends Model {...}`
Week.js
`modelClass: require('./Client').Client,`
