### ISSUE TITLE
Encrypt password before save

### ISSUE THREAD

**Issue by rosendi** [Vincit/objection.js#89]
How can I encrypt a password before insert/update/patch a model? The encryption process is asynchronous. As I understand this can be made in the `$formatDatabaseJson` method, but it doesn't support promises.

**Comment by koskimas** [comment]
You can override `$beforeInsert` and `$beforeUpdate` methods. You can return promises from those.

**Comment by rosendi** [comment]
@koskimas Thank you for the quick response! I've just switched from Bookshelf and at first glance Objection provides much friendly API (especially in combination with TypeScript).
