### ISSUE TITLE
Cannot patch multiple json fields in same patch

### ISSUE THREAD

**Issue by allxie** [Vincit/objection.js#892]
Hey there,
Having some trouble with this query. I'm trying to patch both the object_data.updated_at field and the object_data.status field in the same patch, but only the second one will run if both are in the query. Either of them works on their own. Here's my code:

```
return await ProcessStep
            .bindTransaction(trx)
            .query()
            .where('process_id', process_id)
            .andWhere(builder => {
                builder
                    .where(ProcessStep.raw('object_data->>\'status\''), "=", stepStatus.PENDING)
                    .orWhere(ProcessStep.raw('object_data->>\'status\''), "=", stepStatus.NEEDS_WORK)
            })
            .patch({
                'object_data:status': ProcessStep.raw('?::text', [stepStatus.INCOMPLETE]), // This isn't getting run
                'object_data:updated_at': ProcessStep.raw('?::text', [new Date().toISOString()]),
                assignee_id: null,
                assigner_id: null
            });
```

This was a workaround in the first place-- I just want to set updated_at whenever I patch and I have a $beforeUpdate in BaseModel that's supposed to set object_data.updated_at, but it gets overridden when using the .patch syntax because I'm not passing in object_data to the patch.

```
  $beforeUpdate() {
    // TODO: Any time we patch non-object_data fields with patchAndFetchById, updated_at won't get updated necessarily.
      // If you log "this" here, it doesn't have any part of the entity except the fields you directly pass into patchAndFetchById.
    if (this.object_data) this.object_data.updated_at = new Date().toISOString();
  }
```

Any thoughts?
objection "version": "0.7.12", node version v8.9.0

**Comment by koskimas** [comment]
I think I just fixed this 😄 Are you sure you are running the latest version?

**Comment by koskimas** [comment]
By the way, you should be able to replace this

```js
builder
  .where(ProcessStep.raw('object_data->>\'status\''), "=", stepStatus.PENDING)
  .orWhere(ProcessStep.raw('object_data->>\'status\''), "=", stepStatus.NEEDS_WORK)
```

with this:

```js
builder
  .where(ref('object_data:status'), stepStatus.PENDING)
  .orWhere(ref('object_data:status'), stepStatus.NEEDS_WORK)
```

`ref` comes from

```js
const { ref } = require('objection');
```

**Comment by allxie** [comment]
Rad. I'll upgrade and try again. Thanks!! And long time no see.

**Comment by allxie** [comment]
What version do I need? The latest? 1.1.7?

**Comment by koskimas** [comment]
Yeah, nice to see you again! You need some 1.1.x version, don't remember which. Better try the 1.1.7

**Comment by allxie** [comment]
Any commentary on the base model problem? We aren't getting our object_data.updated_at updated unless we explicitly pass in object_data during the patch. Should I make a separate ticket?

**Comment by koskimas** [comment]
You should be able to say this in `$beforeUpdate`:

```js
  $beforeUpdate() {
    const now = new Date().toISOString();
    this['object_data:updated_at'] = lit(now).castText();
  }
```

and again `lit` comes from the `objection` package.

**Comment by allxie** [comment]
Thanks, Sami! I'll try it out. Gotta update Objection first. I'll consider this closed.
