### ISSUE TITLE
Problem or Confusion using leftOuterJoinRelation

### ISSUE THREAD

**Issue by nick-beers** [Vincit/objection.js#897]
I have an object relationship that has a one-to-many, and that has a nested object that has a one-to-many, which resembles the following:
```
Person {
    Chores: [{
        PersonId,
        Steps: [{
            ChoreId
        }]
    }]
} 
```
When attempting to use `.leftOuterJoinRelation` The aliases are not set correctly. An example of the relationship, which I've tried in many variations never seems to be substituted properly, is shown below. 
```
leftOuterJoinRelation('[Chores, Chores.[Steps]]', {
                aliases: {
                    Chores: 'c',
                    Steps:'s'
                }
            })
```
The query ends up with the join aliases where Chores is set back to Chores(instead of c), and Steps is aliased as Chores:s. I could be misinterpreting the documentation, but I haven't found a permutation of the relation definition I displayed above so that I can select and join things such as select PersonId, c.ChoreId, s.StepId.

Am I simply misusing the API or could this possibly be a bug?

I am currently using Objection v1.1.7 and knex v0.14.2.

**Comment by nick-beers** [comment]
I was able to define my relationship as follows to make it alias correctly - This code works in v1.0.0 and does not work in v1.1.7:
```
leftOuterJoinRelation('[Chores, Chores.Steps]', {
                aliases: {
                    Chores: 'c',
                    Steps:'s'
                }
            })
```

**Comment by koskimas** [comment]
Your relation expression has some redundancy that may be causing this. Does this work:

```js
leftOuterJoinRelation('Chores.Steps', {
                aliases: {
                    Chores: 'c',
                    Steps:'s'
                }
            })
```

What you should get now is a alias `c` for `Chores` and alias `c:s` for `Chores.Steps`

**Comment by koskimas** [comment]
You should also be able to say this

```js
leftOuterJoinRelation('Chores as c.Steps as s')
```

This may be cleaner syntax though

```js
leftOuterJoinRelation(`[
  Chores as c .[
    Steps as s
  ]
]`)
```

Or you can use the new object notation;

```js
leftOuterJoinRelation({
  c: {
    $relation: 'Chores',

    s: {
      $relation: 'Steps'
    }
  }
})
```

**Comment by nick-beers** [comment]
So I attempted to use all of your suggestions for my own sanity, it appears that the last 2 work perfectly, but these first two you suggested don't seem to work for me: 
```
leftOuterJoinRelation('Chores as c.Steps as s')
```
```
leftOuterJoinRelation('Chores.Steps', {
                aliases: {
                    Chores: 'c',
                    Steps:'s'
                }
            })
```
I've double checked my relations and used the .toSQL() method to verify the outputs translate to the expected SQL output I thought it would generate. For whatever reason I seem to get the problem I was describing above when I use these 2 methods. 

I do appreciate having a workaround for the time-being so I can take advantage of the latest version of objection though, so thank you for that!

**Comment by koskimas** [comment]
There are test cases for all those in objection's test suite. I'm closing this because this is probably an user error, but if you are convinced this is a bug, I'll fix it if you can provide a standalone reproduction (for example using the reproduction-template.js file in the repo root).

**Comment by nick-beers** [comment]
Do you think that the relationship join syntax above would be fixed/investigated in an upcoming patch or postponed for a 2.0.0 update? I'm just concerned other people might run into a similar situation and be scratching their heads at it like I was.

**Comment by koskimas** [comment]
People have been using code like that for a long time and this is the first time this issue comes up. I'm pretty sure it's not a bug. If it is, then it will be fixed asap and released with the next patch version.

**Comment by koskimas** [comment]
And also as I said, there are tests for a case just like that one (I just wrote a couple more to be sure).

**Comment by nick-beers** [comment]
That's what I figured, but I copy/pasted your samples into my code and swapped out the table names , and 2 of them still threw errors. I am using Oracle if a oracle knex driver may have some impact on this problem? But either way I prefer the object syntax so thank you!

**Comment by koskimas** [comment]
Oracle might be the culprit here. Objection's test suite is not ran against oracle.

**Comment by kibertoad** [comment]
@nick-beers Can you try running existing tests against your local Oracle DB? I presume Objection could reuse same Docker images that Knex uses, but that's a separate enhancement.

**Comment by koskimas** [comment]
We should really setup travis to run tests with oracle and mssql. I'll add issues for those.

**Comment by nick-beers** [comment]
I can look into running the existing tests against Oracle DB. I recall the Oracle Driver being a pain to setup initially in the past so bear with me while I navigate adding a new DB to the objection test suite, since I'm not very familiar with objection's tests to begin with.
