### ISSUE TITLE
Setup travis to run tests on mssql

### ISSUE THREAD

**Issue by koskimas** [Vincit/objection.js#899]

**Comment by elhigu** [comment]
I have something ready for this in knex repo (even though IIRC even knex’s mssql test are not passing yet).

**Comment by JaneJeon** [comment]
It doesn't even look like it's possible to use mssql within Travis: https://docs.travis-ci.com/user/reference/xenial/#databases-and-services

Though it might be possible if we moved to Circle/Github Actions and just pulled the mssql container like TypeORM does: https://github.com/typeorm/typeorm/blob/master/.circleci/config.yml#L24

**Comment by elhigu** [comment]
@JaneJeon with docker it is perfectly possible. That is how knex runs mssql server on travis.

**Comment by baumandm** [comment]
Hi, I've started working on this.  I'm assuming there's still interest in accepting a PR for this, but if not, please let me know.

**Comment by baumandm** [comment]
I've configured the mssql server docker container, setup script, and integration test configurations in this branch: https://github.com/baumandm/objection.js/commit/f36993bbc11a0b9fbd94fa6fd9440da63dd74884

Currently it's connecting successfully, but running into what appear to be database-specific issues (e.g. inserting into identity columns when `IDENTITY_INSERT` is set to `OFF`).  Not sure I'll be able to sort out all of these issues.

**Comment by kibertoad** [comment]
@koskimas Considering that Travis is becoming less and less friendly towards open source community, wouldn't it be a better option to migrate to GitHub Actions or CircleCI instead?

We've recently completed transtition of knex to GitHub Actions, and it is so, so much faster than Travis ever was.

I can submit a PR to do the conversion of Objection repo as well.

**Comment by kasvith** [comment]
I also second this. It seems GitHub actions or Circle CI will be a better choice
