### ISSUE TITLE
API documentation top left corner moron.js link takes to empty page

### ISSUE THREAD

**Issue by elhigu** [Vincit/objection.js#9]
Maybe it should open http://vincit.github.io/moron.js/MoronModel.html or some real index page.

Also would be nice to add link to github from header bar to get easily back to sources.

![moron_js_index](https://cloud.githubusercontent.com/assets/696345/8482018/9c274856-209b-11e5-8004-a2f6441b5247.jpg)

**Comment by koskimas** [comment]
We should replace the whole API doc site with something better and prettier. Hacking the current jsdoc template makes me want to cry.

**Comment by elhigu** [comment]
Any good alternatives?

**Comment by koskimas** [comment]
Maybe http://www.mkdocs.org/. Sequelize has really nice API docs done using mkdocks.

**Comment by koskimas** [comment]
Solved by the new docs http://vincit.github.io/objection.js/
