### ISSUE TITLE
question: Multiple queries? Should I use transaction?

### ISSUE THREAD

**Issue by robertd** [Vincit/objection.js#90]
If I'm running a complex query 
```
   Person
     .query()
     .where(...)
     .andWhere(...)
     .andWhere(function (builder) {
         builder
             .where(...)
             .orWhere(...)
             .orWhereJsonSupersetOf()
     })
```

How do I fetch both result of this query (above) and a count of all rows (bellow) where only this applies...

```
   Person
     .query()
     .where(...)
     .andWhere(...)
```

Do I wrap this in transaction?... and how? What is the best approach when you want to chain multiple calls (to different or same model(s))?

Thanks

**Comment by koskimas** [comment]
You could do something like this:

```js
let query1 = Person
  .query()
  .where(...)
  .andWhere(...);

let query2 = query1
  .clone()
  .andWhere(builder => {
    builder
      .where(...)
      .orWhere(...)
      .orWhereJsonSupersetOf()
  })
  
Promise.all([query1, query2.resultSize()]).spread((query1Result, count) => {

})
```

Did this answer your question?

**Comment by robertd** [comment]
That's exactly what I did (with bluebird). However... I didn't know you could clone queries... neat :smile: that'll cleanup things a bit.

One other thing.... How do you put custom methods on Models... I saw extending Query Builder but I'm not sure where that goes and I haven't seen any examples extending Query Builder. This is what I'm trying to accomplish.

```
var start = req.query.start;
var start = req.query.end;

....

Person
  .query()
  .where(...)
  .andWhere(...)
  .setRangeIfExists(start, end)

```
where setRangeIfExists in Model is something line this:
```
Person.prototype.setRangeIfExist = function (start, end) {
  if (_.isUndefined(start) && _.isUndefined(end)) {
    return this;
  }

  return this.range(start, end);
};
```
Hopefully this makes sense.

Thanks for all the help. You rock!!! :+1:

**Comment by robertd** [comment]
I think i figured it out but I would like you to confirm it.... It goes like this, right?

```js
var Model = require('objection').Model;
var QueryBuilder = require('objection').QueryBuilder;

function Person() {
  Model.apply(this, arguments);
}

function MyQueryBuilder() {
  QueryBuilder.apply(this, arguments);
}

Model.extend(Person);
QueryBuilder.extend(MyQueryBuilder);

// Some custom method.
MyQueryBuilderPerson.prototype.setRangeIfExist = function (start, end) {
  if (_.isUndefined(start) && _.isUndefined(end)) {
    return this;
  }

  return this.range(start, end);
};

module.exports = Person;

// Instance of this is created when you call `query()` or `$query()`.
Person.QueryBuilder = MyQueryBuilder;
// Instance of this is created when you call `$relatedQuery()`.
Person.RelatedQueryBuilder = MyQueryBuilder;


// Table name is the only required property.
Person.tableName = 'person';

Person.jsonSchema = { ... }
// This object defines the relations to other models.
Person.relationMappings = { ... }

```

**Comment by koskimas** [comment]
Yeah, that's the way to do it. If you want all models to use the same query builder you can just set the `objection.Model.QueryBuilder` and `objection.Model.RelatedQueryBuilder` properties.

**Comment by robertd** [comment]
Is there a best practice on setting global Query Builders? Separate file loaded in app.js or it always has to be part of a Model?


Next question that I have is about `eager` functionality. Lets say that I have this scenario: 

```js
*** Student Model***
'use strict';

var Model = require('objection').Model;

/**
 * @extends Model
 * @constructor
 */
function Student() {
  Model.apply(this, arguments);
}

Model.extend(User);
module.exports = Student;

// Table name is the only required property.
Student.tableName = 'student';

Student.jsonSchema = {};

// This object defines the relations to other models.
Student.relationMappings = {
  classes: {
    relation: Model.ManyToManyRelation,
    modelClass: __dirname + '/Class',
    join: {
      from: 'student.id',
      // ManyToMany relation needs the `through` object to describe the join table.
      through: {
        from: 'student_class.student_id',
        to: 'student_class.class_id'
      },
      to: 'class.id'
    }
  }
};
```


It would be nice If I do something like this:
```js
Student
  .query()
  .eager('class')
  .whereEager('class.name', 'like', '%Geo')
```
where `whereEager` would build proper join based on `relationMappings` in the model. I've seen `filterEager` functionality in `objection@next` (which is one I'm using too) but as I understand, you still have to do manual joins (using `joinRelation` #73) even though you've declared `relationalMappings` in the model. Does `joinRelation` use `relationalMappings`? Also `eager` and `filterEager` are only for arbitrary graph of data (i.e. separate queries to fetch related data based on `relationalMappings`). Correct?

Sorry for all the silly questions... but I'm eagerly anticipating v0.5 for the updated docs :smiley: 

And last but not least... Thanks for all the help :+1:

**Comment by koskimas** [comment]
Objection.js doesn't care how you organise your code or where you assign the global properties. My personal preference is to write a separate file for each class. What I would do in this case is this:

1. Create a base class for your models in which you write all the common stuff. Let's call this `BaseModel`. This model goes in its own file `BaseModel.js`
2. Create a file for the custom query builder class. Let's call it `CustomQueryBuilder`
3. In the `BaseModel.js` require the `CustomQueryBuilder` and assign the `BaseModel`'s `QueryBuilder` and `RelatedQueryBuilder` properties.
4. Inherit all your models from the `BaseModel`.

This way your code is modular and you don't modify library code (objection.Model), which is always a bit hacky. All this inheritance stuff becomes **a lot** prettier if you use ES6.

As for the second question: `joinRelation` and  all the eager stuff use the `relationMappings`. So to do what you want using `joinRelation` would go something like this:

```js
Student
  .query()
  .eager('class')
  .joinRelation('class')
  .where('class.name', 'like', '%Geo')
```

I don't think the extra line `joinRelation('class')` is too much boilerplate and it makes the join explicit. You know exactly what is happening and what SQL is created just by looking at the query.

**Comment by robertd** [comment]
Thanks for everything!!! Keep up the good work :+1:

**Comment by robertd** [comment]
I'm stuck again :disappointed:  . My query is much complicated than the example I gave. Due to legacy project I have to reproduce Nhibernate query.

```js
ReviewQueue
  .query(ReviewQueue.raw("distinct on (review_id) *"))
  .eager('[user, editFlags]')
  .joinRelation('editFlags')
  .whereNull('finalization_id')
  .andWhere('needs_finalization', true)
  .andWhere(function (builder) {
      builder
          .where(EditMetadata.raw('LOWER("name") LIKE ?', '%' + _.lowerCase(searchValue) + '%'))
          
          //THIS is the part that's giving me trouble
          .orWhereExists(function (bld) {
            bld
              .where('editFlags.category', 'like', '%' + _.lowerCase(searchValue) + '%')
          });
      })
```

**Comment by robertd** [comment]
Also on the side note...

I noticed that if you do this:
```js
ReviewQueue
  .query()
  .select('name', 'review_id')
  .eager('[user, editFlags]')
...
```

Result is looks like this:
```js
[
  {
    "name": "Foo",
    "review_id": 1,
    "user": null,
    "editFlags": []
  }
]
```

When I remove `.select` statement `user` and `editFlags` are populated but I get all the fields back.
Could this be a bug?

**Comment by koskimas** [comment]
Here are the problems I found:

1. You give an argument to the `query` method that doesn't take any arguments. If that works, it is by accident :smile:
2. If `editFlags` is a OneToMany relation you get duplicate rows because of the join. Maybe the `distinct` is there to fix this issue? Also you select `*` which merges all the columns of the joined tables to the columns of the `ReviewQueue` table. Maybe you want to use `select ReviewQueue.*`.
3. You don't specify a table for the `orWhereExitst` subquery. See [knex documentation](http://knexjs.org/#Builder-whereExists). Why are you using a `whereExists` here anyway? Since you have joined `editFlags` couldn't you just say `.where('editFlags.category', 'like', ...)`?

**The side note:**

You select only `name` and `review_id`. You need `id` and `user_id` for the eager query to work since they are part of the relations. If you don't want to return those to the client, you can omit them from the result for example using the [`omit`](http://vincit.github.io/objection.js/#omit) method.

**Comment by robertd** [comment]
1. That's totally my fault :smile: Typing it all out rather than simple copy/paste is the best practice :smile: 
2. `editFlags` is `ManyToMany` with `ReviewQueue` (review_queue_flags is the joining table). `review_id` is just a string (poor naming convention) and can appear multiple times that's why I need `distinct on (review_id)`. I've changed it to `perm_id` (better name for it from GIS perspective) and it looks like this `{1ASDA-ASDAS-32135-ASDAS}`. Hopefully that explains why I need distinct. User that's going through `reviewQueue` should only see one entry per `perm_id`. I don't fault you if you're confused by this point. I'm too :smile: 
3. I'm simply trying to replicate SQL statement that fluent NHibernate is spitting out. For some reason they have the `.orWhereExists`. Here's the prettified fluent nhibernate query. I should've posted this long time ago :smile: 
```sql
select distinct 
	reviewqueuet0_.perm_id as col_0_0_ 
from 
	review_queue reviewqueuet0_ 
where 
	((TRUE)::bool)=TRUE 
and 
	reviewqueuet0_.needs_finalization=TRUE 
and 
	(reviewqueuet0_.edit_finalization_id is null) 
and 
	(
		((FALSE)::bool)=TRUE 
		or 
			upper(reviewqueuet0_.gnis_name) like ('%'||(('HELLO')::text)||'%') 
		or 
			exists (
					select 
						editfla2_.Id 
					from 
						review_queue_flag reviewflags1_,
						edit_flag editflags2_ 
					where 
						reviewqueuet0_.Id=reviewflags1_.metadata_id 
					and 
						reviewflags1_.flag_id=editflags2_.Id 
					and 
						(upper(editflags2_.Category) like ('%'||(('HELLO')::text)||'%'))
					)
	) 
limit 
	((25)::int4) 
offset 
	((0)::int4)
```

**The side note**
That makes sense. :+1: 

Thanks for all your help.

**Comment by anttilinno** [comment]
Any chance you could make an example of these steps? I failed to build a working example. Sorry about this half hijack of this question.

Previous quote =>
Objection.js doesn't care how you organise your code or where you assign the global properties. My personal preference is to write a separate file for each class. 

What I would do in this case is this:

  1)  Create a base class for your models in which you write all the common stuff. Let's call this BaseModel. This model goes in its own file BaseModel.js
  2) Create a file for the custom query builder class. Let's call it CustomQueryBuilder
  3)  In the BaseModel.js require the CustomQueryBuilder and assign the BaseModel's QueryBuilder and RelatedQueryBuilder properties.
  4)  Inherit all your models from the BaseModel.

This way your code is modular and you don't modify library code (objection.Model), which is always a bit hacky. All this inheritance stuff becomes a lot prettier if you use ES6.

**Comment by robertd** [comment]
@anttilinno  Here you go...

Directory structure
```
core
    |_ BaseModel.js
    |_ CustomQueryBuilder.js
es6
    |_ ReviewQueue.js
```

**BaseModel.js**
```js
'use strict';

const Model = require('objection').Model;
const CustomQueryBuilder = require('./CustomQueryBuilder');

class BaseModel extends Model {
  static get Model() {
    return Model;
  }

  static get QueryBuilder() {
    return CustomQueryBuilder;
  }
}

module.exports = BaseModel;
```

**CustomQueryBuilder.js**

```js
'use strict';

const QueryBuilder = require('objection').QueryBuilder;
const _ = require('lodash');

class CustomQueryBuilder extends QueryBuilder {
  debugInDevelopment() {
    if (process.env['NODE_ENV'] && process.env['NODE_ENV'] === 'production') {
      return this;
    }

    return this.debug();
  }
}

module.exports = CustomQueryBuilder;
```


**ReviewQueue.js**
```js
'use strict';

const BaseModel = require('../core/BaseModel');

class ReviewQueue extends BaseModel {
  // Table name is the only required property.
  static get tableName() {
    return 'review_queue';
  }

  // Optional JSON schema. This is not the database schema! Nothing is generated
  // based on this. This is only used for validation. Whenever a model instance
  // is created it is checked against this schema. http://json-schema.org/.
  static get jsonSchema() {
    return {
    };
  }

  // This object defines the relations to other models.
  static get relationMappings() {
    return {
    };
  }
}

module.exports = ReviewQueue;
```

**Comment by anttilinno** [comment]
Thank you very much.
