### ISSUE TITLE
AND OR generic composition

### ISSUE THREAD

**Issue by carlok** [Vincit/objection.js#907]
Hi,
let's say I want to select two fields in OR for a given string while selecting another field, in SQL it would be something like:
`SELECT * FROM T WHERE ((field1 LIKE '%searchString%') OR (field2 LIKE '%searchString%')) AND (field3...)`
AFAIK I can't use `whereComposite` with field1 and field2 because `whereComposite` works as an AND and, of course, I can't use a generic `orWhere` (I need the parentheis (A or B) and C != A or B and C) AND has precedence over OR.
Counting out raw SQL, what is the Objection right way to do it?
Thanks.

PS: this issue should have the "help wanted" label but I didn't get how to add it.

**Comment by koskimas** [comment]
Hi, function arguments can be used to add parentheses. Your example would be written like this:

```js
T.query()
  .where(qb => {
    qb.where('field1', 'like', '%searchString%').orWhere('field2', 'like', '%searchString%);
  })
  .andWhere('field3', 'foo')
```
