### ISSUE TITLE
Common (?) question regarding programmable eager filtering

### ISSUE THREAD

**Issue by carlok** [Vincit/objection.js#908]
Hi,
let's say we have, for example, Person and City where Person has fields like {id, id_city} and City has {id, address}.
I can query Person as
`Person.query().eager("[city]")`
using as an example the first `reviews(onlyGood)` example at
https://www.vincit.fi/blog/nested-eager-loading-and-inserts-with-objection-js/
how could I filter by a given substring of address? How could I pass a parameter to a filter? The given example is on the link is
```
.eager('reviews(onlyGood)', {
    onlyGood: (query) => {
      query.where('stars', '>', 3)
    }
});
```
but 3 is fixed.
So is it possible to dynamically filter on a field on an eager-linked/joined array of objects?
I read a few other issues on this subject but I'm not sure about the general answer, sorry.
Thanks.

PS: this issue should have the "help wanted" label but I didn't get how to add it.

**Comment by koskimas** [comment]
So just to make it clear, what you want is to get "all persons whose city's address contains a certain substring"?

There are (at least) two easy ways to do that by leveraging SQL:

1. Using subqueries

```js
await Person
  .query()
  .whereExists(Person.relatedQuery('city').where('addres', 'like', 'Helsinki'))
```

2. Using joins

```js
await Person
  .query()
  .joinRelation('city')
  .where('person.address', 'like', 'Helsinki')
```
