### ISSUE TITLE
Insert an array of UUIDs

### ISSUE THREAD

**Issue by robertrossmann** [Vincit/objection.js#909]
Hello! I am attempting to insert a new row into a table with a column defined as an array or UUIDs:

```sql
alter table medias add column "order" uuid[];
```

```js
const order = [
  'BFAD6B0D-D3E6-4EB3-B3AB-108244A5DD7F'
]

Medias
  .query()
  .insert({
    order: lit(order.map(id => lit(id).castType('uuid'))).castArray()
  })
```

But the query is malformed and therefore does not execute:

```sql
INSERT INTO medias ("order")
VALUES (ARRAY [
  {"_value":"BFAD6B0D-D3E6-4EB3-B3AB-108244A5DD7F","_cast":"uuid","_toJson":false,"_toArray":false}
])
```

As can be seen, the query contains the JSON-stringified representation of the `LiteralBuilder` object and not something that the SQL syntax understands as a typecast.

If I skip casting the individual UUID strings and just cast the whole column into an array, then Postgres rejects the query because the column is of type `uuid[]` but I am attempting to insert the column as `text[]`.

Is this a bug that the individual arrays are not properly cast as UUIDs or am I doing it wrong? 🤔

Thanks for your help!

**Comment by koskimas** [comment]
You are sending an array of `lit` objects to the database. Does this work:

```js
Medias
  .query()
  .insert({
    order: lit(order).castArray()
  })
```

**Comment by robertrossmann** [comment]
Hello @koskimas, thanks for the tip! I tried that and unfortunately while the query looks valid, Postgres rejects it with an error along the lines of:

> Cannot insert value of type `text[]` into column of type `uuid[]`
> _(paraphrased)_

**Comment by koskimas** [comment]
Yeah sorry, I removed my answer as I realized that you already answered my question. I'll try out some stuff and get I'll get back to you.

**Comment by robertrossmann** [comment]
Awesome @koskimas, thank you for looking into it so quickly! ❤️

**Comment by koskimas** [comment]
@robertrossmann This is now fixed. Your original syntax should work now too.

**Comment by robertrossmann** [comment]
@koskimas thank you for your quick help with this! Much appreciated! ❤️
