### ISSUE TITLE
Conditionally eagering based on top level model

### ISSUE THREAD

**Issue by allxie** [Vincit/objection.js#911]
Hey there,
I'm trying to figure out a way to conditionally eager nested items based on conditions in my top (or even middle-level) models.
For example...
If I wanted to do `Invoice.query().eager('approval_process.steps')`, but I only wanted to bother getting approval_process (and steps) out of the database if `invoice.status = "pending_approval"`, even though I want to get all invoices out of the database.
Any ideas? Do I need to, like, join back to Invoice, or is there a way to reference self in an onBuild?

**Comment by allxie** [comment]
(and then a follow up, is there a way to do this with nested items in an eager, eg if I had... `Users.query().eager('invoices.approval_process.steps');`)

**Comment by koskimas** [comment]
Joining back the invoice should work

```js
Invoice.query()
  .eager('approval_process.steps')
  .modifyEager('approval_process', qb => {
    qb.joinRelation('invoice').where('invoice.status', '!=', 'approved');
  });
```

You can also use a subquery in `modifyEager` but I think a join is cleaner.

```js
Users.query()
  .eager('invoices.approval_process.steps')
  .modifyEager('invoices.approval_process', qb => {
    qb.joinRelation('invoice').where('invoice.status', '!=', 'approved');
  });
```

**Comment by allxie** [comment]
Cool, that should work. Thanks, Sami!
