### ISSUE TITLE
Change the default validation

### ISSUE THREAD

**Issue by nbeydoon** [Vincit/objection.js#92]
Hey, I was wondering if it is possible to use another schema validator (instead of json schema) like JOI and continue to benefit of all useful methods like $beforeValidate and $afterValidate

**Comment by thetutlage** [comment]
Try http://indicative.adonisjs.com/

**Comment by koskimas** [comment]
You can override the [`$validate`](http://vincit.github.io/objection.js/#_s_validate) method of the `Model`. This is the default implementation:

```js
  $validate(json = this, options = {}) {
    const ModelClass = this.constructor;
    let jsonSchema = ModelClass.jsonSchema;

    if (!jsonSchema || options.skipValidation) {
      return json;
    }

    // No need to call $beforeValidate (and clone the jsonSchema) if $beforeValidate has not been overwritten.
    if (this.$beforeValidate !== ModelBase.prototype.$beforeValidate) {
      jsonSchema = _.cloneDeep(jsonSchema);
      jsonSchema = this.$beforeValidate(jsonSchema, json, options);
    }

    let report = tryValidate(jsonSchema, json, options);
    let validationError = parseValidationError(report);

    if (validationError) {
      throw validationError;
    }

    this.$afterValidate(json, options);
    return json;
  }
```

As you see `$validate` calls both `$beforeValidate` and `$afterValidate`. You also need to honor the `options.skipValidation` flag as it is used internally.

I could actually make this easier by adding a method with a simpler requirements that `$validate` calls after making all the hook calls and options checks.

**Comment by nbeydoon** [comment]
Thanks for your help guy, I have change json schema for joi correctly :)
