### ISSUE TITLE
How to filter by extra fields of join table

### ISSUE THREAD

**Issue by demisx** [Vincit/objection.js#920]
Hi,

I have many-to-many relation between `Ads` and `Users`.  The `anonEmail` and `type` are extra fields defined on the `UsersAds` join table. I need to fetch an ad that matches certain criteria stored in the join table. So far:

```js
return await Ad
  .query()
  .joinRelation('users')
  .where('anonEmail', anonEmail)
   .where('type', 'ao')
   .first() as Ad
```

produces:

```sql
select "Ads".* from "Ads" 
  inner join "UsersAds" as "users_join" on "users_join"."adId" = "Ads"."id"
  inner join "Users" as "users" on "users_join"."userId" = "users"."id" 
  where "anonEmail" = ? and "type" = ?' // <-- not scoped to UserAds
```

As you can see `anonEmail` and `type` are not scoped to any table. How would I tell Objection.js that it should be `"users_join"."anonEmail"` and `"users_join"."type"` instead? Explicitly writing this in query doesn't feel right. Thank you.

**Comment by imwillhang** [comment]
this feature would be extremely helpful! spent a good 2 hours banging my head against this because of the weird + "_join" issue :( thanks!

**Comment by devinivy** [comment]
Does `tableRefFor()` help in this case, if you're joining through a model?
