### ISSUE TITLE
How to create relation filtering by join table columns

### ISSUE THREAD

**Issue by demisx** [Vincit/objection.js#921]
I have many-to-many relation between `Ads` and `Users`. The `anonEmail` and `type` are extra fields defined on the `UsersAds` join table. I am trying to define `owner` relation in model `Ad` which is one `User` that has `UsersAds.type = 'ao'`. So far, I can't figure out how to apply this filter to the `UsersAds` join table instead of `Users` where the `type` column doesn't exist.

So, with this code:
```js
export class Ad extends BaseModel {
  static tableName = 'Ads'

  static relationMappings = {
    owner: {
      relation: BaseModel.ManyToManyRelation,
      modelClass: '../user/user.model',
      join: {
        from: 'Ads.id',
        through: {
          from: 'UsersAds.adId',
          to: 'UsersAds.userId',
          extra: ['type', 'anonEmail'],
        },
        to: 'Users.id',
      },
      filter: (qb: QueryBuilder<Ad>) => qb.where('UsersAds.type', 'ao'), // this doesn't work
    },
  ...
```

I get this query generated:

```sql
select "Ads".* from "Ads" 
  inner join "UsersAds" as "owner_join" on "owner_join"."adId" = "Ads"."id" 
  inner join (select "Users".* from "Users" where "UsersAds"."type" = ?) as "owner" on "owner_join"."userId" = "owner"."id"  // <-- problem
  where "anonEmail" = ?
```

But what I really need is something like this:
```sql
select "Ads".* from "Ads" 
  inner join "UsersAds" as "owner_join" on "owner_join"."adId" = "Ads"."id" and "owner_join"."type" = 'ao'
  inner join "Users" as "owner" on "owner_join"."userId" = "owner"."id"
  where "anonEmail" = ?
```

Not sure if this is even doable. Thank you!

**Comment by koskimas** [comment]
Isn't that the same query? I'm pretty sure that sql engines even generate the same query plan for both.

**Comment by koskimas** [comment]
This is currently not possible. This is actually the same issue as #837

**Comment by demisx** [comment]
@koskimas You are right. It does appear to be the same as #837. Hopefully, it will be fixed soon.
 🙏🏻🤞🏻
