### ISSUE TITLE
Multi-schema Relationships [PostgreSQL]

### ISSUE THREAD

**Issue by heisian** [Vincit/objection.js#922]
Extending the query builder to use `withSchema` for tables with a static getter returning a schema name seems to make the query builder want to use the same schema for relationships between tables with different schemas.

Instead of doing:
```node
class ExtendedQueryBuilder extends objection.QueryBuilder {
  constructor(ModelClass) {
    super(ModelClass)
    if (ModelClass.schemaName) {
      this.withSchema(ModelClass.schemaName)
    }
  }
}
```

is the better solution to just do this:
```node
class SomeModel extends Model {
  static get tableName {
    return 'schemaOne.someModels'
  }

  static get relationMapping() {
    return {
      relatedModel: {
        relation: Model.HasOneRelation,
        modelClass: 'RelatedModel',
        join: {
          from: 'schemaOne.someModels.id',
          to: 'schemaTwo.relatedModels.someModelsId',
        },
      },
    }
  }
}
```
... which works just fine.. just wondering if there'd be any issues with this.

The following queries *do* work when specifying the postgres schema as a prefix to the table name as in the above model definition:
```node
const someModel = await SomeModel.query().insertGraph({
  field: 'data',
  relatedModel: {
    relatedField: 'data',
  },
})

await RelatedModel.query().where('id', someModel.relatedModel.id).eager('someModel')
```

**Comment by koskimas** [comment]
I've never used schemas like that and there are [very few tests](https://github.com/Vincit/objection.js/blob/master/tests/integration/schema.js) for them. I really can't say if it will work or not. Feel free to create a PR with more tests to make sure the things you use remain working in the future.

**Comment by koskimas** [comment]
Actually, let's keep this open. This might be something to improve in the future.

**Comment by heisian** [comment]
Ah, good point - I will add some unit tests to the queue.

**Comment by heisian** [comment]
At this point I'd be OK closing the issue - once the `tableName`s and `join`s are set, it's pretty much forget-and-use as normal. I sort of want to add more tests in addition to #925 but I'll mull that over for a bit since I don't exactly know what I'd add yet.

**Comment by heisian** [comment]
thanks for being responsive and getting it merged in so quickly!

**Comment by koskimas** [comment]
I'm closing this now. Untill knex supports this stuff, I don't think we should add features to objcetion. They may break at any given time.
