### ISSUE TITLE
Is there an async equivalent of $parseDatabaseJson and $formatDatabaseJson?

### ISSUE THREAD

**Issue by JaffParker** [Vincit/objection.js#926]
In my project, I have to do field level encryption, so the obvious solution, I thought would be to use the aforementioned functions, however, those only work with synchronous functions, they don't support promises.

Are there async alternatives to those functions, because I did not seem to find any in the documentation? The closest I found were $afterGet and $before(Update|Insert), but those aren't meant to alter the data.

If there's no alternative, would you potentially be open to make the functions in question asynchronous? If you give the green light, I could start working on a PR.

Regards,
Andrey

**Comment by koskimas** [comment]
You can use `$beforeInsert`, `$beforeUpdate` and `$afterGet`. You can alter the data any way you want in those.

There is no way to make $parseDatabaseJson and $formatDatabaseJson async without 
completely rewriting objection. If those were async, a thousand other things would also become async.

**Comment by JaffParker** [comment]
I see. I only have one concern with the $afterGet: is it called right
before the promise is resolved and the result is returned or after? I
wouldn't want to start working with data that is being altered.

**Comment by koskimas** [comment]
I don't understand the question. How could it be ran after the data is returned? I mean it could, but who the hell would design such a ridiculous API :smile:

**Comment by JaffParker** [comment]
I saw it more as events, in case there's some other stuff you'd like to perform that's not related to the data. But considering there's actually an event API, it makes sense that these functions are to manipulate data :)
