### ISSUE TITLE
how can you use unrelate together with whereIn

### ISSUE THREAD

**Issue by vickpalomo** [Vincit/objection.js#927]
I have two models connected by a pivot table, the idea is to be able to eliminate all the relations of multiple ids, but I understand the method $ relatedQuery well, it works with a single record, so how could delete erase the relationships of several ids

First Query

```js
let diferenceArray = [65,72, 73]
const typification = await Typification.query().whereIn('id', diferenceInArray)
```
Output 
```js
[ Typification {
    id: 65,
    id_parent: null,
    name: 'Modeloramas Empresarial',
    question: 'question for new node' },
  Typification {
    id: 72,
    id_parent: 65,
    name: 'Otra Administración',
    question: 'question for new node' },
  Typification {
    id: 73,
    id_parent: null,
    name: 'Segunda Raiz',
    question: 'question for new node' } ]
```
second query

```js
const numRowsDeleted = await typification.$relatedQuery('questionnaire').unrelate()
```

show message '$relatedQuery is not a function', then how implement this query?

**Comment by koskimas** [comment]
`typification` is an array.

**Comment by vickpalomo** [comment]
then should it be an instance of typification? without the await

**Comment by heisian** [comment]
@vickpalomo not sure if this is the most efficient, but this would do `unrelate` on each record:
```node
await Promise.all(
  typification.map((t) => {
    t.$relatedQuery('questionnaire').unrelate()
  })
)
```
