### ISSUE TITLE
Possible innerJoin and eager bug

### ISSUE THREAD

**Issue by robertd** [Vincit/objection.js#93]
Hi guys,

I think I've encountered a possible `innerJoin` / `eager` bugs.
Here is my setup:

DB

Person table
![persontable](https://cloud.githubusercontent.com/assets/31543/13476510/6b6d0cbe-e085-11e5-9407-658dc30bb5f2.JPG)

Person_Movie table
![personmovie](https://cloud.githubusercontent.com/assets/31543/13476546/8b905e2e-e085-11e5-8772-6a32ce29fc91.JPG)

Movie table
![movies](https://cloud.githubusercontent.com/assets/31543/13476527/7bec7692-e085-11e5-9bd2-534037ea3307.JPG)

Express route

```js
app.get('/person/movie/:name', function (req, res, next) {
    Person
      .query()
      .eager('movies')
      .joinRelation('movies')
      .where('movies.name', 'like', req.params.name)
      .debug()
      .then(function (actors) { res.send(actors); })
      .catch(next);
  });
```

Results for '/person/movie/Wolverine':

```js
[
  {
    "id": "1",  //duplicate ids
    "parentId": null,
    "firstName": "Hugh",
    "lastName": "Jackman",
    "age": null,
    "address": null,
    "personId": "1",
    "movieId": "1",
    "name": "Wolverine",
    "movies": [
      {
        "id": "1",
        "name": "Wolverine"
      }
    ]
  },
  {
    "id": "1", //duplicate ids
    "parentId": null,
    "firstName": "Ryan",
    "lastName": "Reynolds",
    "age": null,
    "address": null,
    "personId": "2",
    "movieId": "1",
    "name": "Wolverine",
    "movies": [
      {
        "id": "1",
        "name": "Wolverine"      //where is Deadpool?
      }
    ]
  }
]
```

As you can see above as soon as I use `innerJoin('movies')` my IDs are all the same. I've tested it with more data and I was experiencing the same issue.

Another thing that I noticed is that I'm not receiving Deadpool movie for second actor when using `eager('movies')` relation. Bellow you can see that when I search using `Deadpool` I'm receiving corresponding actor with all his Movies.

`/person/movie/Deadpool`
```js
[
  {
    "id": "2",
    "parentId": null,
    "firstName": "Ryan",
    "lastName": "Reynolds",
    "age": null,
    "address": null,
    "personId": "2",
    "movieId": "2",
    "name": "Deadpool",
    "movies": [
      {
        "id": "1",
        "name": "Wolverine"
      },
      {
        "id": "2",
        "name": "Deadpool"
      }
    ]
  }
]
```
It seems to me that as soon as I start getting multiple results IDs get weird and `eager` is not returning all related data.

These may be 2 different bugs but I've decided to post them together. Hopefully that's ok.

Thanks!

EDIT: 

Models were taken from `example/express`.

**Comment by robertd** [comment]
Forgot to paste debug SQL queries

```sql
select *
from "Person"
  inner join "Person_Movie" as "Person_Movie_rel_movies" on "Person_Movie_rel_movies"."personId" = "Person"."id"
  inner join "Movie" as "movies" on "Person_Movie_rel_movies"."movieId" = "movies"."id"
where "movies"."name" like 'Wolverine';

select "Movie".*, "Person_Movie"."personId" as "objectiontmpjoin0"
from "Movie"
  inner join "Person_Movie" on "Person_Movie"."movieId" = "Movie"."id"
where "Person_Movie"."personId" in (1)
```

![result](https://cloud.githubusercontent.com/assets/31543/13477309/0fff7f84-e089-11e5-831e-7cce8be4dd44.JPG)

After further looking into this... I think `eager` part of my issue is not an issue.... But confirmation is needed.

Thanks

**Comment by koskimas** [comment]
Actually this is not a bug. Both the `Person` and `Movie` have the column `id` and since you don't select anything the default `select *` is left in the query and the `id` colum gets mixed. The eager fetch is then made using the `id` columns of the fetched models and it gets messed up also.

This should fix your problem:

```js
app.get('/person/movie/:name', function (req, res, next) {
    Person
      .query()
      .select('Person.*')
      .eager('movies')
      .joinRelation('movies')
      .where('movies.name', 'like', req.params.name)
      .debug()
      .then(function (actors) { res.send(actors); })
      .catch(next);
  });
```

**Comment by robertd** [comment]
That makes sense. Should this example/scenario be in documented in docs?

**Comment by koskimas** [comment]
Maybe.. This is how SQL joins work, but maybe it could be made clearer that `joinRelation` doesn't alter the select clause.

**Comment by robertd** [comment]
I'll just leave it here for now. People always search through past issues before posting new one :)

Thanks!
