### ISSUE TITLE
[doc] relate should explain it only *adds* relations

### ISSUE THREAD

**Issue by kapouer** [Vincit/objection.js#930]
Or does it not ?
It's not obvious from the documentation what relate does to previously defined relations.

**Comment by koskimas** [comment]
What do you mean it only *adds*? What else could it do?

**Comment by kapouer** [comment]
It could *set* all relations to the ones provided, erasing previously set ones.

**Comment by kapouer** [comment]
You forgot how it was before objection :)

**Comment by koskimas** [comment]
Do you mean the good old moron.js days? 😀 Did it work like that once? How would you make the docs clearer?

**Comment by kapouer** [comment]
I probably mean even older days when i used some obscure non-knex based ORM.

**Comment by heisian** [comment]
Sequelize has a method called `set<SomeModel>` which does what @kapouer describes. It also has an `add<SomeModel>` method which does the same as `relate` here.

I would think that the `relate` implication in this case, however, is pretty clear.

Also, in [this ORM](https://laravel.com/docs/5.6/eloquent-relationships#updating-many-to-many-relationships), the `attach`, `detach`, and `sync` methods are synonymous with Sequelize's `add`, `remove`, and `set` methods.

Map that to Objection and we have `relate` and `unrelate`. I don't see how one would expect `relate` to overwrite other existing associations in a 1:n situation.
