### ISSUE TITLE
upsertGraph: whereNotExists does not work

### ISSUE THREAD

**Issue by wijdench** [Vincit/objection.js#932]
Hi, this is my query:

```js
return transaction(Modeltest.knex(), async (trx) => {
    const test = await Modeltest
      .query(trx)
      .upsertGraph({
        id: req.params.id,
        status_id: req.body.status_id,
      }, { relate: true })
      .whereNotExists(Modeltest
        .query()
        .where({
          status_id: req.body.status_id,
        }));
    return test;
  });
```

and i receive the error of violating unique key 'status_id'. How can i prevent the upsertGraph with the condition of status_id unicity.

**Comment by koskimas** [comment]
Unfortunately you cannot use any query building methods with `upsertGraph`. You need to specify each row using the graph.

Your query doesn't actually need `upsertGraph` at all. You can simply replace `upsertGraph` by `patch`.

```js
    const test = await Modeltest
      .query(trx)
      .patch({
        status_id: req.body.status_id,
      })
      .where('id', req.params.id)
      .whereNotExists(Modeltest
        .query()
        .where({
          status_id: req.body.status_id,
        }));
    return test;
```

**Comment by koskimas** [comment]
Objection should throw in this case. I opened a new issue #933

**Comment by wijdench** [comment]
I need upsertGraph because status_id is in another relation one to many.

**Comment by koskimas** [comment]
Then you are using `upsertGraph` wrong. What your query does is exactly equivalent to the query I wrote. If you are trying to do something else, it will fail.

**Comment by wijdench** [comment]
I wrote juste a simple of my code. i have two tables with  relation: Model.HasManyRelation and i want to update all data in both tables, that's why i used upsertGraph

**Comment by heisian** [comment]
@wijdench if `status_id` is specified as an `extra` column in your relation, you can just use `patch`.
