### ISSUE TITLE
NPM reports 1.1.8 as latest

### ISSUE THREAD

**Issue by demisx** [Vincit/objection.js#934]
Though, I believe 1.1.9 is. 

![screen shot 2018-05-22 at 5 50 12 pm](https://user-images.githubusercontent.com/4452412/40397670-a34f5d5c-5de8-11e8-84ec-c87209c0430d.jpg)

**Comment by kibertoad** [comment]
@demisx 1.1.9 was released in "next" (aka beta) branch.

**Comment by koskimas** [comment]
I don't know why it says that. I've added the latest tag for it and if I run

```sh
npm dist-tag add objection@1.1.9 latest
```

I get

```sh
npm WARN dist-tag add latest is already set to version 1.1.9
```

npm is somehow borked

**Comment by koskimas** [comment]
Also 

```sh
npm dist-tag ls objection
```

prints

```
latest: 1.1.9
next: 1.1.9
```

**Comment by kapouer** [comment]
`npm dist-tag rm objection next`

**Comment by koskimas** [comment]
@kapouer I've never had to do that before. A package can exist in multiple tags at the same time.

**Comment by koskimas** [comment]
And I just tried, dist-tags cannot be removed (probably can within the first couple of hours or so). I contacted NPM about this. There's nothing more I can do.
