### ISSUE TITLE
Potential bug with knexSnakeCaseMappers() and idColumn

### ISSUE THREAD

**Issue by linkenneth** [Vincit/objection.js#937]
Hi! Firstly I'd like to thank you for a great job on a very intuitive ORM library. It's helped speed up my development a ton.

Unfortunately some of my conventions may have tripped it up. Specifically,

```javascript
// user.js
import { Model } from 'objection';

export default class User extends Model {
  static get tableName () {
    return 'user';
  }

  static get idColumn () {
    console.log('idColumn');
    return 'userId';
  }
}

// knexfile.js
module.exports = {
  // ...
  ...knexSnakeCaseMappers()
};

// routes/signup.js
    user = await User.query().insert({
      firstName: req.body.firstName,
      lastName: req.body.lastName,
      email: req.body.email,
      passwordHash: hash
    });
```

results in the following debug output:

```
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings:
   [ 'abc',
     '$2b$12$a8n5U1JGc7XLP9fm5CneM.TIIOPihUwczl/g6p.pYHebaZUW4yQmW' ],
  __knexQueryUid: 'f042c2ea-d2ad-4a74-b0f0-874bd920546a',
  sql: 'insert into "user" ("email", "password_hash") values (?, ?) returning "user_id"',
  returning: 'userId' }
```

Note the `returning "user_id"` but `returning: 'userId'`.

Alternatively, if idColumn is 'user_id', the resulting user looks like:
```
User {
  firstName: undefined,
  lastName: undefined,
  email: 'abc',
  passwordHash: 'redacted',
  user_id: '5cfa0936-aac2-4e12-9656-5f9d90f085a6' }
```
Note that `user_id` is not camelCased.

In the meantime, I'm working around it with some getters, but ideally I don't want to change either my ID field to the default, or have to define getters for each field that works.

Some debugging indicates that `wrapIdentifier` in `knexIdentifierMappers` is not receiving the correct identifier in the first place. I suspect that since `idColumn` is a special field, we're just taking that field and directly assuming that it exists in the database in the form given.

Could someone take a look? Thanks, and do let me know if this is reproducible or just something stupid.

**Comment by koskimas** [comment]
Hi, thanks for the compliments :bowing_man: 

This seems to be a bug in knex. I could reproduce this without objection using this script:

```js
const knex = require('knex')({
  client: 'postgres',

  connection: {
    host: '127.0.0.1',
    user: 'postgres',
    database: 'objection_test'
  },

  wrapIdentifier: (id, oldImpl) => {
    return oldImpl(id + '_foo');
  },

  postProcessResponse: (result) => {
    // This is never called with the return value of the insert query.
    return result;
  }
});

const main = async () => {
  await knex.schema.dropTableIfExists('t');
  await knex.schema.createTable('t', table => {
    table.increments('id');
    table.string('value');
  });

  const retVal = await knex('t')
    .insert({ value: 'hello 2' })
    .returning('value')
    .debug();

  console.log(`should return ['hello 2'] but returns`, retVal);
  await knex.destroy();
};

main().catch(console.error);
```

**Comment by koskimas** [comment]
I opened an issue in knex https://github.com/tgriesser/knex/issues/2630
