### ISSUE TITLE
Mapping logic differs for Insert and Update

### ISSUE THREAD

**Issue by thejuan** [Vincit/objection.js#941]
I have a setup where we have a legacy postgres database, some fields are stored in a JSONB data dump field, some are on the table.

`Model {
title,
name,
data: {
    dob,
    startDate
  }
}`

This gets mapped to an object that abstracts the data dump, like so

`Model {
title,
name,
dob,
startDate
}`

Up until now I have only been updating objects. I've added a $formatDatabaseJson
It remaps the abstracted json to json that contains conversion fields like data:dob and data:startDate
Now I need to insert this blows up as insert doesn't support JSONB_SET obviously, somehow I need to reconstruct the data field from any passed in values.

My question is where should i do it? This is a common pattern for my models, ideally I'd like to know in $formatDatabaseJson that its an insert so i can write a re-usable function to rebuild the data field from the conversion formats

I could put it in $beforeInsert and beforeUpdate  if they were passed the JSON being updated or inserted.

**Comment by koskimas** [comment]
There are $beforeUpdate and $beforeInsert hooks that probably work better in your case.

**Comment by thejuan** [comment]
This has side-effects on the instance, especially for update. When do I clear it?
I'd rather manage a flag i think (updating or inserting)

**Comment by koskimas** [comment]
Yeah, if you need to use the model instance furhter, it might be better to set a flag in `$beforeUpdate` and `$beforeInsert`.

**Comment by koskimas** [comment]
Another option is to clear the properties in `$afterUpdate` and `$afterInsert`
