### ISSUE TITLE
React Native compatibility

### ISSUE THREAD

**Issue by kevinnguy** [Vincit/objection.js#942]
It would be awesome if I could use my models from my backend in my React Native project! There's a few node modules such as `path` that isn't supported in React Native and makes importing my models impossible. Has anyone tried this with their RN project before?

**Comment by kibertoad** [comment]
@kevinnguy Do you need full-blown models? I would imagine that schema generated with something like https://www.npmjs.com/package/objection-swagger would serve your purpose better.

**Comment by kibertoad** [comment]
@heisian Note that you probably can't import models directly in production frontend code to extract json-schema, you have to do that in preprocessing phase from Node.js and generate something for frontend to consume (which is exactly what objection-swagger does, but you can always write your own generation code)

**Comment by elhigu** [comment]
I haven't been coding React Native, but if it is possible to access some locally running database (for example sqlite) from its javascript engine that sounds like a valid use case. But webpack does sound possible. Probably @koskimas  has better idea, since he has been doing some RN coding too.

**Comment by kevinnguy** [comment]
Thanks for all the suggestions! For my specific use case, I wanted to utilize the Model class for its json schema validation and as well as its virtual attributes. Ideally, I would use `Model.fromJson(json, opts)` to create an instance and have the json be validated and be able to generate its virtual attributes as well. 

Like @heisian said about stubbing `path`, that may be the route that I'd need to take but wanted to see what everyone else thought!

**Comment by koskimas** [comment]
I don't think we'll support react native any time soon. Knex would need to support it first anyways.
