### ISSUE TITLE
Documentation: .whereJsonHasAny and .whereJsonHasAll works only for checking keys of json object

### ISSUE THREAD

**Issue by elhigu** [Vincit/objection.js#943]
This has came up couple of times in stackoverflow.  Postgres `?|` and `?&`  operators actually doesn't seem to work for checking is an array has certain element, but only for checking is json object has keys.

In documentation is mentioned `Where any of given strings is found from json object key(s) or array items.` that `or array items` part should be dropped from docs for those methods.

**Comment by alex-mironov** [comment]
Is it really the case and we cannot use this method with arrays? Is there any alternative for arrays?

**Comment by koskimas** [comment]
Alternatives have been discussed [here](https://github.com/Vincit/objection.js/issues/415) and [here](https://github.com/Vincit/objection.js/issues/1133)
