### ISSUE TITLE
Unable to insert object with column as jsonb[]

### ISSUE THREAD

**Issue by vichal** [Vincit/objection.js#944]
I have a postgresql database which has the migration defined as:
`table.specificType("open_times", "jsonb[]");`
And the model scheme defined as:
```
static get jsonSchema() {
    return {
      type: "object",
      properties: { open_times: { type: ["object", "array", "null"] } }
    };
```
When I used insert(obj), it wrote [object Object] in the database instead of a jsonb array.

I have also tried add the open_times column to the jsonAttribute, but the result was same.

**Comment by kibertoad** [comment]
Have you tried to JSON.stringify it?

**Comment by elhigu** [comment]
@kibertoad that shouldn't be necessary. @vichal you could try if it works with plain jsonb type. It can contain also an array as root element. I have never worked with `jsonb[]` type...

**Comment by elhigu** [comment]
@vichal  after couple of minutes of fidlling http://sqlfiddle.com/#!17/9eecb/15690 I still have no idea how one should use jsonb[] type. Do you know how to use it in plain SQL?

**Comment by vichal** [comment]
@elhigu Actually I have tried with plain jsonb type, but it throw an error when the value is an array,

**Comment by vichal** [comment]
@elhigu I am not sure, actually, I was pulling data from other vendors by restful API, and the original data is an object array with no ids. So I just saved those data as its original structure.

**Comment by vichal** [comment]
When I changed the column type to jsonb, and then insert something like below
```
{
   openTimes: [
      {
        openTimeInfo: `${faker.date.recent(5)} to ${faker.date.recent(10)}`,
        sightStart: faker.lorem.sentence(10),
        sightEnd: faker.lorem.sentence(10)
      }
    ]
}
```
The insert throw an error:
```
name: 'error',
  length: 192,
  severity: 'ERROR',
  code: '22P02',
  detail: 'Expected ":", but found "}".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'JSON data, line 1: ...is vel sit quidem dolor est repellendus non.\\"}"}',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'json.c',
  line: '1151',
  routine: 'report_parse_error' 
```

**Comment by koskimas** [comment]
That should work. There are test for it. Could you write a reproduction?

**Comment by vichal** [comment]
@kibertoad I saw the test and then I found the root cause. It's my bad, the root cause is that I call JSON.stringfy during creating the object. Many thanks, @elhigu @kibertoad
