### ISSUE TITLE
Get Query in $beforeUpdate 

### ISSUE THREAD

**Issue by krazibitBD** [Vincit/objection.js#945]
Would be nice to get the query object in the $beforeUpdate hook.
Useful in `patch` scenario to check if accidentally omitted where clause.

**Comment by koskimas** [comment]
Unfortunately that won't happen with the current hooks. I'm thinking about a new hook API for 2.0 and the query builder will be available in the new hooks. How could you even check if a wherw clause is missing without using the private API?
