### ISSUE TITLE
UPPER_SNAKE_CASE to camelCase conversion

### ISSUE THREAD

**Issue by duard** [Vincit/objection.js#947]
Hi, 
I need some help with camelCase field names.
I want to config objection to work with camelCase fields. I try it but no success : 

**My table :** 
![screenshot from 2018-06-01 23-17-29](https://user-images.githubusercontent.com/36894/40869469-07df6c74-65f2-11e8-84f1-4ba37aa4fe85.png)

**My model :** 
```
import { Model,  snakeCaseMappers} from "objection";
import knex from '../../obj-db';
Model.knex(knex);

class Teste extends Model {
  static get columnNameMappers() {
    return snakeCaseMappers();
  }
  static get tableName() {
    return 'medicamentos_temp';
  }
}
export default Teste;
```

**My return :** 
```
{
        "CODIGODEBARRAS": "7894916503761",
        "NOMEDOPRODUTO": "AGLUCOSE 100MG 30S",
        "PRECODECUSTO12": "27",
        "PRECODEVENDA12": "37.32",
        "PRECODECUSTO17": "28.63",
        "PRECODEVENDA17": "39.58",
        "PRECODECUSTO18": "28.98",
        "PRECODEVENDA18": "40.06",
        "PRECODECUSTO19": "29.34",
        "PRECODEVENDA19": "40.56",
        "PRECODECUSTOZFM": null,
        "PRECODEVENDAZFM": null,
        "VALORDESCONTO": "5",
        "QTDMINIMA": "0",
        "CODIGO": 1273,
        "CODIGOOPERACAO": "20042016150521040",
        "PRECODECUSTO175": "0.00",
        "PRECODEVENDA175": "0.00"
    },
```

It only remove the "_" from the field names.

**Comment by heisian** [comment]
snake_case to camelCase in objection is done by iteration.. going through each character of the string, starting at the first character:
```
1.  If the current character is not an underscore (`_`),
    and the previous character is not an underscore (`_`),
    the character is pushed to the stack.

2.  If the current character is not an underscore (`_`),
    and the previous character *is* an underscore (`_`),
    the character is uppercased and pushed to the stack.

3.  If the current character *is* an underscore (`_`), it is ignored.
```
In your case, since every character in your column is uppercased, the conversion simply "removes" all the underscores.

You need to lowercase your column names in SQL for it to work.

**Comment by koskimas** [comment]
@heisian is right. I could add an option for snakeCaseMappers that would allow uppercase columns.

**Comment by koskimas** [comment]
@heisian is right. I could add an option for snakeCaseMappers that would allow uppercase columns. I'll add this to my todo list.

**Comment by koskimas** [comment]
@duard I implemented support for UPPER_SNAKE_CASE, but this issue https://github.com/tgriesser/knex/issues/2630 in knex is blocking it. It needs to be fixed before I can release the feature. I'll fix the knex issue, but it will take some time before they release a new version

When this is implemented, you will be able to do this:

```js
import { Model,  snakeCaseMappers} from "objection";
import knex from '../../obj-db';
Model.knex(knex);

class Teste extends Model {
  static get columnNameMappers() {
    // The `upperCase` option will be available once this feature is out.
    return snakeCaseMappers({ upperCase: true });
  }

  static get idColumn() {
    // This is also needed since your id column is not `id`
    return 'ID';
  }

  static get tableName() {
    // You need to use the database casing here. so UPPER_CASE
    // and not lower_case.
    return 'MEDICAMENTOS_TEMP';
  }
}
export default Teste;
```
