### ISSUE TITLE
Drop bluebird; Use native Promises

### ISSUE THREAD

**Issue by feross** [Vincit/objection.js#950]
Hey! Thoughts on dropping the `bluebird` dependency? My thoughts:

- Native `Promise` support was shipped in Node 4. `objection` only supports Node 6+.
- Native `Promise` performance has met (or surpassed) `bluebird` promises
- One less dependency to install, faster install time, less complexity
- Uses the platform primitives, which is usually preferred

**Comment by kibertoad** [comment]
@feross There are already plans to do so eventually (and it actually mostly happened - https://github.com/Vincit/objection.js/commit/3b5aa1737d32caf98bad5cbbee40fcb8047b7994), but to get rid of it fully knex would have to be changed as well.

**Comment by koskimas** [comment]
Bluebird will be dropped for 2.0.

**Comment by feross** [comment]
Nice, thanks for the fast reply. Looking forward to 2.0.
