### ISSUE TITLE
Working with spatial data (ST_DISTANCE_SPHERE)

### ISSUE THREAD

**Issue by mstaniewski** [Vincit/objection.js#951]
Hello,

I've got some troubles working with spatial data in my model.

All i want to achieve is to fetch rows, which distance from person is lesser than 10 kilometers.
All i did so far is:

Created my own "filter" plugin to be able to filter outputs:
export default Model => {

```
  class FilterQueryBuilder extends Model.QueryBuilder {

    filter(params = {}, builder) {

      const filters = Model.$allowedFilters || {}
      builder = builder || Model.query()

      const allowedFilters = Object.keys(filters)
      const passedFilters = Object.keys(params).filter(key => allowedFilters.includes(key))

      passedFilters.forEach(key => {
        const [fieldName, operator] = filters[key]
        builder.where(fieldName, operator, operator === 'like' ? `%${params[key]}%` : params[key])
      })

      return builder

    }

  }

  return class extends Model {

    static get QueryBuilder() {
      return FilterQueryBuilder
    }

  }

}
```

allowedFilters static is a simple object containing filter name as a key and array with column name and operator inside, like:

```
static $allowedFilters: Object = {
    minPrice: ['price', '>='],
    maxPrice: ['price', '<='],
 }
```

The thing i want to achieve is to add another query to my select, so it fetches distance between place and current user location.

Actually thought of few solutions:
```
 static get defaultSelects(): Array<mixed> {
    return [
      'attractions.*',
      Attraction.relatedQuery('reviews').avg('rate').as('rating'),
      Attraction.raw(`ST_Distance_Sphere(geo, ST_GeomFromText('POINT(?))`, [geo]),
    ]
  }
```

But this solution doesn't let me to pass param into third select.
Tried also with

```
const models = await Model
      .query()
      .column(Model.raw(`ST_Distance_Sphere(geo, ST_GeomFromText('POINT(?)) as distance`, [geo]))
      .filter(req.query)
      .page((page - 1), pageSize)
```

Which seems to work, but filter throws an error because distance column is not known for database whether i use **where** or **having** for this operation.

How to actually work with spatial data using Objection.js?

Thanks for help :)

**Comment by koskimas** [comment]
Unfortunately you cannot use computed selections in `where` or `having` clauses in SQL. You need to copy that `raw` thingy to the `where` clause.

**Comment by mstaniewski** [comment]
@koskimas So unfortunately there isn't any fancy way to perform this action implicitly everytime i fetch data using this model? It always needs to be explicitly in every query?

**Comment by koskimas** [comment]
There is nothing built-in, no. But you can of course build whatever fancy helpers you want as QueryBuilder methods or helper functions (used with `modify` for example).

**Comment by mstaniewski** [comment]
@koskimas found another issue right now. Few months ago You did show me a method for "defaultSelects", which looks like following: 

```
static query(...args) {
    return super.query(...args).onBuild(builder => {
      if (builder.isFind() && !builder.hasSelects() && this.defaultSelects) {
        builder.select(this.defaultSelects)
      }
    })
  }
```

And here comes the problem. How to merge **selects** if there are more than one in current query builder?

I mean, i'am using column in following way: 

`qb.column(raw(`ST_Distance_Sphere(geo, ST_GeomFromText('POINT(52.404244 16.861494)') as distance`))
`

and right after it, I'm calling my filter plugin, which replaces whole context from qb.column. Depending on order, the last one select/column will take effect.

Is there any way to merge these selects?
