### ISSUE TITLE
Validation of relationMappings-fields

### ISSUE THREAD

**Issue by fbring** [Vincit/objection.js#953]
I am trying to build a validation for a "ManyToManyRelation" with extra fields in the join table.

I couldn't find anything about this topic in the docs, so I build my own custom validation in the $beforeInsert method. But it feels a little bit odd to do it like this.

There is no access to the `users` array in the $beforeValidate method.

Is there a better way to validate the relation-fields e.g. jsonSchema?

``` javascript
const objection = require('objection');
const { Model } = objection;

class Event extends Model {
  static get tableName() {
    return 'event';
  }

  $beforeInsert() {
    const { users } = this;

    if (!users || users.length === 0) {
      throw new objection.ValidationError({
        message: 'No users array provided',
        type: 'Custom validation',
        data: null,
      });
    }
  }

  static get jsonSchema() {
    return {
      type: 'object',
      properties: {
        description: { type: 'string' },
        users: {
          type: 'array',
          uniqueItems: true,
          minItems: 1,
          items: {
            type: 'object',
            required: ['isAuthor', 'eventId'],
            properties: {
              isAuthor: { type: 'boolean' },
              eventId: { type: 'string' },
            }
          }
        },
      },
    };
  }

  static get relationMappings() {
    return {
      users: {
        relation: Model.ManyToManyRelation,
        modelClass: User,
        join: {
          from: 'event.eventId',
          through: {
            from: 'event_user.eventId',
            to: 'event_user.userId',
            extra: [
              'isAuthor',
            ],
          },
          to: 'user.userId',
        },
      },
    };
  }
}


```

**Comment by heisian** [comment]
I would personally just let it fall back to DB validation in this case.

Try this and see what kind of error you get:
```node
await event.$relatedQuery('users').insert()
```

**Comment by koskimas** [comment]
@fbring You probably need to add `required: ['users']` to the root of `jsonSchema`. If that doesn't work, what you are doing right now is totally ok.

**Comment by fbring** [comment]
@koskimas Thank you for your answer, but this was my first attempt. When I add `required: ['users']` back in, then I get this error:

``` json
"users": [
   {
      "message": "is a required property",
      "keyword": "required",
      "params": {
         "missingProperty": "users"
      }
   }
]
```

I wasn't sure if this was my fault or an bug, because I am new to objection.js and jsonSchemas.

I think the problem here is, that the `users` array never get´s passed to the `json` param of `$beforeValidate`, but the jsonSchema tries to find it.

But as I said, I dont know if this is a bug, a feature or something totally diffrent.

**Comment by koskimas** [comment]
@fbring That's the correct error when you don't pass the `users` property. Or are you saying you get that when you give an objection that has the `users` list?

**Comment by fbring** [comment]
@koskimas Exactly! I get this error, when I pass a proper `users` array to an obection.

**Comment by ehubbell** [comment]
@koskimas I'm currently running into this issue as well. 

At first, I was sending `review.userId` or `review.bookingId` in with the `review` model to create and validate the presence of that relationship via the `jsonSchema()` in the model. 

Now, I'm sending that data in as `review.user.id` and using the `insertGraph` method with `{ relate: true }` set. That method seems to work better for me across the board but it doesn't seem to validate the child models (for example: the `user` or `booking` models) in this situation.

For now, I'm running custom validations within the transaction that'll catch and return to the user such as:

```
async checkUser() {
  let user = await this.$relateQuery('user');
  if (!user) {
    throw customError(400, 'message here')
  }
```

Am I missing an easier / better way of going about validating relationships? Thought I should post here as the issue above didn't fully address my issue which I presume is a common one. 

Thanks!
E

**Comment by ehubbell** [comment]
For what it's worth -- I'm still running into the same issue here. When I send data like so:

```
{
  "data": {
    "attributes": {
      "name": "Customer 2",
      "email": "customer2@blush.net",
      "phone": "3034442226",
      "location": {
        "name": "908 S Washington St, Denver, CO 80209, USA",
        "address": "908 S Washington St",
        "city": "Denver",
        "state": "Colorado",
        "country": "United States",
        "postal-code": "80209",
        "latitude": 39.6999657,
        "longitude": -104.9789766
      },
      "provider": {
        "id": 10
      }
    }
  }
}
```

And then have the following `jsonSchema`:

```
  static get jsonSchema() {
    return {
      type: 'object',
      required: ['name', 'email', 'provider'],

      properties: {
        id: { type: 'integer' },
        name: { type: 'string', minLength: 4, maxLength: 40 },
        email: { type: 'string', minLength: 6, maxLength: 255 },
        phone: { type: 'string',  minLength: 10, maxLength: 10 },
        photo: { type: 'string' },
        stripeCustomerId: { type: 'string' },
        location: { type: 'object' },
        provider: { type: 'object' },
        createdAt: { type: 'date' },
        updatedAt: { type: 'date' },
        deleted: { type: 'boolean' },
      }
    };
  }
```

I get the following error: 
```
Throw error:  ValidationError: provider: is a required property
    at Function.createValidationError (/vagrant/node_modules/objection/lib/model/Model.js:357:12)
    at parseValidationError (/vagrant/node_modules/objection/lib/model/AjvValidator.js:189:21)
    at AjvValidator.validate (/vagrant/node_modules/objection/lib/model/AjvValidator.js:78:19)
    at validate (/vagrant/node_modules/objection/lib/model/modelValidate.js:35:20)
    at Customer.$validate (/vagrant/node_modules/objection/lib/model/Model.js:93:12)
    at GraphInsertAction._insert (/vagrant/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:177:16)
    at GraphInsertAction._insertBatch (/vagrant/node_modules/objection/lib/queryBuilder/graph/insert/GraphInsertAction.js:48:16)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  name: 'ValidationError',
  type: 'ModelValidation',
  data: { provider: [ [Object] ] },
  statusCode: 400
}
```

Based on the documentation and comments above, I would expect my data to be valid. I tried a more verbose approach to to the `provider` object (in jsonSchema) but that didn't solve the issue. 

@koskimas am I missing something here? Or, what is the appropriate way to require a relationship and then validate it's presence? The temporary solution I'm running with is a manual check that a provider is present in `$beforeInsert` and `$beforeUpdate` like so:

```
  async checkProvider() {
    let provider = await this.$relatedQuery('provider');
    if (!provider) {
      throw new CustomError(400, 'Please attach a provider.');
    }
    return true;
  }
```
