### ISSUE TITLE
All column values are now returned as promises

### ISSUE THREAD

**Issue by Palisand** [Vincit/objection.js#954]
I started a fresh project and found that fields are being returned as promises rather than the column values themselves:
```javascript
const user = await models.user.query().findById(1)
// 'user' now is:
User {
  username: Promise { 'username' },
   ...
}
// when it used to be:
User {
  username: 'username',
  ...
}
```
I have kept the same versions of `objection`, `knex`, and `mysql2` between projects.
Has anyone else encountered this?

**Comment by koskimas** [comment]
You are doing something terribly wrong. This has nothing to do with objection.

**Comment by Palisand** [comment]
Yeah I had a feeling... @koskimas you've never seen something like this before or have any idea what could be causing it? I did upgrade from node 9 to 10.
