### ISSUE TITLE
findById fails if id is not correct type

### ISSUE THREAD

**Issue by honestserpent** [Vincit/objection.js#956]
I am wondering if this is the expected behavior.

I have defined the model with a jsonSchema as follows:

```
static get jsonSchema() {
    return {
      type: 'object',
      required: ['first_name', 'last_name', 'account_id'],

      properties: {
        id: { type: 'integer' },
        account_id: { type: 'integer' },
        first_name: { type: 'string', minLength: 1, maxLength: 255 },
        last_name: { type: 'string', minLength: 1, maxLength: 255 },
        bio: { type: 'string' }
      }
    }
  };
```

So, the `id ` is expected to be an integer. Now, when I use the `findById` method on this model, and pass a string instead of an integer, e.g. `Person.findById('a');` I get a `invalid input syntax for integer:` Error.

I want auto incrementing ids, so they need to be integers, but I am wondering why this matters when I am searching for Ids. Shouldn't I just get an undefined result if I search for something that does not exist?

**Comment by koskimas** [comment]
That error comes from the database. No can do

**Comment by honestserpent** [comment]
Ah, I suspected it. So what would be the right and best approch here. Hand checkinng that the value is an integer? Use a string instead of an integer?

**Comment by koskimas** [comment]
The query works if the string represents a valid number. It only fails when the string cannot be converted into an integer. I'd say there is something wrong with the logic of your app if you end up comparing the primary key to a random string.

**Comment by honestserpent** [comment]
Yes, you are right, I need to perform more validation on that before running the findById then. Thank you very much.
