### ISSUE TITLE
Passing value to positional identifier in raw query does not work

### ISSUE THREAD

**Issue by demisx** [Vincit/objection.js#960]
Hi. I am having hard time getting positional binding to work in raw query when trying to pass a value. For example, this snippet:

```ts
import {raw} from 'objection'

await Model
  .query()
  .select(raw('json_build_object(?, "anonEmail")::jsonb', 'email'))
```

Results in the following SQL:

```sql
json_build_object(?, "anonEmail")::jsonb -- no substitution occurs
```

Need instead:

```sql
json_build_object('email', "anonEmail")::jsonb
```

Please note, passing identifiers as `??` works as expected. Am I missing something? Seems like Knex supports both, `?` and `??` (https://knexjs.org/#Raw). 

---
$ npm ls objection knex
├── knex@0.14.6 
└── objection@1.1.10

**Comment by koskimas** [comment]
What are you using the check if it worked? If it works, objection **should** send the unsubstituted SQL to the database server and the **server** should do the substitution. Doing the substitution in code would be both stupid and dangerous.

**Comment by demisx** [comment]
@koskimas You are absolutely correct, sir! I am sorry, but I got thrown off by `??` identifier substitution in the code and didn't realize that the value `?` substitution happens on the server. I should've looked at the bindings array where my `email` value is no present. 

```ts
 bindings: [ 'email', ... ],
```

Thank you very much for blazingly fast response as usual. 👍

**Comment by demisx** [comment]
As a follow up question, I have this query now generated with 3 bindings. It returns 0 results through Objection.js:

```js
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 'email', 'ao', 'ab78d143-42b5-4ddd-8048-79f5f8d1e3f7' ],
  __knexQueryUid: 'd44e303b-ecd5-4a04-a9af-ec3e650c9faa',
  sql:
   'select "Ads"."id", (case when "anonEmail" is not null then "Ads"."contact" || json_build_object(?, "anonEmail")::jsonb else "Ads"."contact" end) as contact from "Ads" left join "UsersAds" as "owner_join" on "Ads"."id" = "owner_join"."adId" and owner_join.type = ? left join "Users" as "owner" on "owner_join"."userId" = "owner"."id" where "Ads"."id" = ?' }
```

However, if I manually replace `?` with values in the bindings array and run it in `psql` client, the query returns a few rows of results as it's supposed to.

```sql
-- Same query as above except with substituted values
select 
    "Ads"."id", 
    (case when "anonEmail" is not null 
        then "Ads"."contact" || json_build_object('email', "anonEmail")::jsonb 
        else "Ads"."contact" end) as contact,
from "Ads" 
left join "UsersAds" as "owner_join" 
    on "Ads"."id" = "owner_join"."adId" and owner_join.type = 'ao' 
left join "Users" as "owner" 
    on "owner_join"."userId" = "owner"."id" 
where "Ads"."id" = 'ab78d143-42b5-4ddd-8048-79f5f8d1e3f7';
```

What may cause this? Is it possible to see the native query executed by the Postgres itself (after all substitutions)? I have a feeling something's off after the values are inserted, like instead of `json_build_object('email', "anonEmail")::jsonb` it's trying to run `json_build_object(\'email\', "anonEmail")::jsonb` (with escaped single quotes).

**Comment by demisx** [comment]
Well, it worked once I've replaced `?` with `?::text`:

```sql
.select(raw(`(case when "anonEmail" is not null then "Ads"."contact" || json_build_object(?::text, "anonEmail")::jsonb else "Ads"."contact" end) as contact`, 'email'))
```

I thought that the type would be automatically inferred as text from the `'email'` binding, but I guess it's not. Wondering if I always need to explicitly set the type in raw queries where substitution is used. Anyway, back to reading...
