### ISSUE TITLE
No model id in $beforeUpdate when patching?

### ISSUE THREAD

**Issue by jetrii** [Vincit/objection.js#966]
I have a custom `$beforeUpdate` that records a history of model changes, but objects patched with `updateAndFetchById` appear to be lacking an id, which really limits what you can do. Is there a way to access the id when patching a model?

**Comment by koskimas** [comment]
`this` in `$beforeUpdate` is the object you give as an argument to the `update*` method. There is no way to get the id currently. Objection 2.0 will have a better hook API that makes this possible, but until then, you need to find some other way to do what you want.

**Comment by mogzol** [comment]
I'm using Objection 2, this still seems to be an issue, what is the proper way to get the ID in the before/afterUpdate hook in Objection 2?

**Comment by koskimas** [comment]
Objection 2 added the static hook API. There is no way to fix the old instance hooks without making objection a buggy piece of **it.
