### ISSUE TITLE
Automatic eager loading?

### ISSUE THREAD

**Issue by E-Rockalanche** [Vincit/objection.js#967]
Is it possible to eager load relationships for a model without specifying .eager()? I have some models in my project who's data is incomplete without certain relationships being loaded with it. It would be nice to have all the necessary relationships be automatically queried when I query for the "parent" model.

**Comment by koskimas** [comment]
I'm not sure if this will work in all situations, but you could try something like this:

```js
class BaseModel extends Model {
  // Override the execute method.
  execute() {
    if (this.isFindQuery()) {
      this.mergeEager(this.constructor.defaultEager);
    }

    return super.execute();
  }
}
```

Now you could create your models by extending the `BaseModel` and specify a `defaultEager`:

```js
class Person extends BaseModel {
  static get defaultEager() {
    return '[foo, bar.baz]'
  }
  ...
}
```
