### ISSUE TITLE
Documentation references deprecated Knex function knex.schema.createTableIfNotExists

### ISSUE THREAD

**Issue by rickarubio** [Vincit/objection.js#969]
The current documentation for objection: https://vincit.github.io/objection.js/#getting-started

has the following block of code in one of its examples:

```js
async function createSchema() {
  // Create database schema. You should use knex migration files to do this. We
  // create it here for simplicity.
  await knex.schema.createTableIfNotExists('persons', table => {
    table.increments('id').primary();
    table.integer('parentId').references('persons.id');
    table.string('firstName');
  });
}
```

When this code is run, you'll get the following output error:

```
Knex:warning - Use async .hasTable to check if table exists and then use plain .createTable. Since .createTableIfNotExists actually just generates plain "CREATE TABLE IF NOT EXIST..." query it will not work correctly if there are any alter table queries generated for columns afterwards. To not break old migrations this function is left untouched for now, but it should not be used when writing new code and it is removed from documentation.
```

Unfortunately although the warning states that the code is removed from the documentation (probably from knex documentation), that is clearly not the case for objection documentation.

I'm currently evaluating objection/knex vs typeorm for a new codebase at work and thought this was a bit confusing.

I'll go ahead and submit a PR that updates the documentation and hopefully that will help new users going through the getting started docs.

**Comment by koskimas** [comment]
Fixed in #970
