### ISSUE TITLE
Using Objection to get a certain number of sorted Posts associated with a Category and all its child Categories

### ISSUE THREAD

**Issue by jnox64** [Vincit/objection.js#973]
I'm struggling to find a way to get the result that I'm looking for elegantly with Objection.js (or at least with Knex).

I have a `posts` table, and each post belongs to a `category`. A `category` can have a parent, stored as `parent_id`, that refers to another category. What I'm trying to do is get a certain number of most-recently-added Posts—let's say 10—that belong to a Category (and _all_ of its child categories).

I'm using Postgres, and was able to come up with the following query that gets me the result I am looking for:

```sql
SELECT * FROM posts WHERE category_id IN (
  WITH RECURSIVE category_ids AS (
    SELECT  id FROM categories WHERE id = 1
    UNION ALL
    SELECT  c.id FROM categories c INNER JOIN category_ids t0 ON t0.id = c.parent_id
  ) SELECT id FROM category_ids
) ORDER BY creation_date LIMIT 10
```

However, this is pretty difficult to express with Knex (given the use of `with recursive`), and I'm wondering if there is a nicer way to get this result directly with Objection.js, using the relationships in my models.

In a way I am trying to recursively fetch a category's children (and so on) and their associated posts, and then flatten all of the categories' posts to a single array of all posts. However, the reason that I don't want to simply do that in JavaScript is because I want the query to be aware of the limit and the sort order when fetching the posts.

Here's an SQLFiddle that should help demonstrate the desired result: http://sqlfiddle.com/#!17/b8170/2 (Retrieves posts with category "Feature", plus "Opinion" and "Interview" categories, because they are subcategories of "Feature".)

Is this possible to do with Objection.js? If not, any recommendations to simplify the query or get it to play nicely with Knex would be appreciated. :)

**Comment by koskimas** [comment]
There is no easy way to achieve this with objection.
