### ISSUE TITLE
Problems with ManyToMany relation

### ISSUE THREAD

**Issue by leeisme** [Vincit/objection.js#976]
Hello, love the ORM so far! I'm having a problem getting a many to many relation to behave the way that I want and was hoping to get some help with. I've seen several other posts about the error that I'm getting (see below) and have made sure that the join: {} columns match the outer object as mentioned in these and I have checked that the table is indeed, the correctly named and referenced name.

P.S. I was hoping that writing this out, I would rubber ducky myself into a solution/answer, but alas, I must hit the submit button ;-)

Thanks for any input!

**The Error:**

**Error: League.relationMappings.members: join: either `from` or `to` must point to the owner model table and the other one to the related table. It might be that specified table 'leagues_players' is not correct**
    at ManyToManyRelation.createError (/var/www/tourney-backend/node_modules/objection/lib/relations/Relation.js:232:14)
    at Object.createError (/var/www/tourney-backend/node_modules/objection/lib/relations/Relation.js:47:32)
    at createRelationProperty (/var/www/tourney-backend/node_modules/objection/lib/relations/Relation.js:340:17)
    at createJoinProperties (/var/www/tourney-backend/node_modules/objection/lib/relations/Relation.js:302:20)
    at ManyToManyRelation.setMapping (/var/www/tourney-backend/node_modules/objection/lib/relations/Relation.js:55:11)
    at ManyToManyRelation.setMapping (/var/www/tourney-backend/node_modules/objection/lib/relations/manyToMany/ManyToManyRelation.js:29:26)

**Leading to Error:**

```
let player = await Player
                .query()
                .eager('league') // <--- Ouch!!
                .findOne({email: email})
```

**My League Model:**

```
const {Model} = require('objection')

class League extends Model {
    static get tableName () {
        return 'leagues'
    }

    static get relationMappings () {
        const Player = require('./Player')

        return {
            owner: {
                relation: Model.BelongsToOneRelation,
                modelClass: Player,
                join: {
                    from: 'leagues.id',
                    to: 'players.id'
                }
            },
            members: {
                relation: Model.ManyToManyRelation,
                modelClass: Player,
                from: 'leagues.id',
                join: {
                    from: 'leagues_players.leagueId',
                    to: 'leagues_players.playerId'
                },
                to: 'players.id'
            }
        }
    }
}

module.exports = League
```

**My Player Mode:**

```
const {Model} = require('objection')

class Player extends Model {
    static get tableName () {
        return 'players'
    }

    static get relationMappings() {

        const League = require('./League')

        return {
            leagueMemberships: {
                relation: Model.ManyToManyRelation,
                modelClass: League,
                from: 'players.id',
                join: {
                    from: 'players.id',
                    through: {
                        from: 'leagues_players.playerId',
                        to: 'leagues_players.leagueId'
                    },
                    to: 'leagues.id'
                }
            },
            league: {
                relation: Model.HasOneRelation,
                modelClass: League,
                join: {
                    from: 'players.leagueId',
                    to: 'leagues.ownerId'
                }
            }
        }
    }
}

module.exports = Player
```

**The Join Table Migration:**

```
exports.up = function(knex, Promise) {
    return Promise.all([
        knex.schema.createTable('leagues_players', table => {
            table.increments('id').primary()
            table.integer('leagueId').notNullable().unsigned()
            table.integer('playerId').notNullable().unsigned()
            table.timestamps(true, true)
            table.index(['leagueId', 'playerId'])
            table.index(['playerId', 'leagueId'])
        })
    ])
};

exports.down = function(knex, Promise) {
    return Promise.all([
        knex.schema.dropTableIfExists('leagues_players')
    ])
};
```

**Comment by heisian** [comment]
It looks like you might be using `knexSnakeCaseWrappers`, in which case you might want to try using `leaguesPlayers` instead of `leagues_players`?

**Comment by leeisme** [comment]
@heisian, thanks for responding. I'm not sure about knexSnakeCaseWrappers, unless it's something that is implemented implicitly or by default since I've not knowingly implemented it/them. 

Despite this, I tried changing the table name from snake_case to camelCase and I still get the same error.

Any other ideas on what I could try?

**Comment by koskimas** [comment]
@leeisme Your relation mappings for `ManyToManyRelations` are invalid. You have these:

```js
{
                relation: Model.ManyToManyRelation,
                modelClass: Player,
                from: 'leagues.id',
                join: {
                    from: 'leagues_players.leagueId',
                    to: 'leagues_players.playerId'
                },
                to: 'players.id'
            }
        }
```

but you should have these:

```js
{
                relation: Model.ManyToManyRelation,
                modelClass: Player,
                join: {
                  from: 'leagues.id',
                  through: {
                      from: 'leagues_players.leagueId',
                      to: 'leagues_players.playerId'
                  },
                  to: 'players.id'
               }
            }
        }
```

**Comment by leeisme** [comment]
@koskimas, I can't believe that I completely whiffed on that. Thank you for taking the time to point it out.
