### ISSUE TITLE
Get reference to parent from child

### ISSUE THREAD

**Issue by drew-r** [Vincit/objection.js#977]
Is there some easy way to obtain a reference to the parent model from a child?
My use case is: parent entity can be active/inactive, child entity can be active/inactive, but a child is ALWAYS inactive if its parent is inactive. 
This can be modelled quite nicely with a virtual attribute if I could get access to the parent like so:
e.g
```
interface Person {
    active: boolean;
    pet: Animal;
}

interface Animal {
    active: boolean;
    owner: Person;
    get isActive() { return this.getParent().active && this.active; }
}
```

I could define the parent as a relation and load it eagerly but won't this create an additional query and cause two instances of the same model to be loaded into memory with potentially different relations...

What would be perfect is a sneaky `_parent` reference that is never output to JSON, or a `getParent()` method that returns the parent of the relation if one exists.

**Comment by drew-r** [comment]
I solved this with `afterGet` on my `ModelBase`:
```
  $getParent: <T>() => T;

  $afterGet() {
    const relationMappings = (<typeof ModelBase>this.constructor).relationMappings;
    if (!relationMappings) return;

    const relationNodes = Object.keys(relationMappings);
    
    for (let relationNode of relationNodes) {
      if (!this[relationNode]) continue;
      if (Array.isArray(this[relationNode])) {
        this[relationNode].forEach((r: any) => r.$getParent = () => this);
      } else {
        this[relationNode].$getParent = () => this;
      }
    }      
  }
```

**Comment by koskimas** [comment]
:+1:
