### ISSUE TITLE
relate() doesn't work with OneToOneRelation

### ISSUE THREAD

**Issue by pwalczyszyn** [Vincit/objection.js#98]
I'm trying to map a ManyToOne relationship using `OneToOneRelation`. All works fine except for `relate()` function. In the debug I can see there is an update statement issued but it doesn't update related field (only a `updatedAt` timestamp). Any ideas what I could be doing wrong? Also maybe there is  a way to have this relation set with initial document insert?

_Part of my `Document` model mapping_
```javascript
...
      owner: {
        relation: BaseModel.OneToOneRelation,
        modelClass: User,
        join: {
          from: 'document.userId',
          to: 'user.id'
        }
      }
...
```
_Snippet of code that uses `relate()` function_
```javascript
Document
        .query()
        .insertAndFetch(json)
        .then(function(doc) {
          doc.$relatedQuery('owner').relate(owner.id);
          return doc;
        });

```

_Debug information_
```javascript
{ method: 'update',
  options: {},
  bindings: [ Fri Mar 11 2016 14:21:11 GMT+0000 (UTC), 26 ],
  sql: 'update `document` set `updatedAt` = ? where `document`.`id` = ?' }
```

**Comment by koskimas** [comment]
I just wrote a test and this works for me. I don't know how this would cause that particular error, but you don't return the `relate` promise from the `then` method. You should do that. Also are you sure the `owner.id` is defined?

**Comment by koskimas** [comment]
And you can relate the owner simply by saying `json.userId = owner.id` before the query.

**Comment by pwalczyszyn** [comment]
I made it work, I had to define userId property in jasonSchema. Now it's all good :) Thx for looking into this.

**Comment by koskimas** [comment]
Happy to help :smile:
