### ISSUE TITLE
Caching solutions?

### ISSUE THREAD

**Issue by theogravity** [Vincit/objection.js#980]
If asking here or in the `knex` project is the right place. 

Are there any solutions out there to say 'cache the results of this particular query' if this or that query bind param matches?

My Google/npm search didn't yield anything specific (eg `cache objection.js`, `cache knex`). 

I have a feeling that I'd have to manually do it.

**Comment by koskimas** [comment]
Caching SQL queries would be insanely difficult. I don't think there are any generic solutions or libraries for that.

**Comment by devinivy** [comment]
To avoid that very hard problem we typically use objection in our service layer, and utilize [catbox](https://github.com/hapijs/catbox) (via [schmervice](https://github.com/hapipal/schmervice), since we're using hapi) to cache our service methods.

**Comment by x0us** [comment]
Just searching this by Google...I use redis for cache eventually....
