### ISSUE TITLE
Incompatible Typings - RelationExpression

### ISSUE THREAD

**Issue by ozylog** [Vincit/objection.js#981]
I got this problem when trying to use RelationExpression. ([RelationExpression Export](https://github.com/Vincit/objection.js/blob/master/lib/objection.js#L35))([RelationExpression Class](https://github.com/Vincit/objection.js/blob/master/lib/queryBuilder/RelationExpression.js#L12))

but on typings/index.d.ts,  RelationExpression is defined as `type RelationExpression = string | object;` ([Go To Definition](https://github.com/Vincit/objection.js/blob/master/typings/objection/index.d.ts#L264))

Which it returns TS error `'RelationExpression' only refers to a type, but is being used as a value here.` when i put my code like this
```
import { RelationExpression } from 'objection';

const expr = RelationExpression.create(eager);  // the error is in here
```
I am willing to fix this but it would be better if i get feedback first.

**Comment by koskimas** [comment]
RelationExpression class isn't part of the public API and there shouldn't be typings for it. You shouldn't use anything that isn't documented in the docs as those things are part of the private API and may change at any given point without any warning.

The documentation mentions `RelationExpression` but that name is used to refer to the the string expressions only. The class itself is not documented.

**Comment by ozylog** [comment]
Cool. thanks for your answer and quick response. i am trying to not use private API then.

Do you have any suggestion how is the proper way to get all involved Models from RelationExpression?
