### ISSUE TITLE
Upsert oparation mutates argument object

### ISSUE THREAD

**Issue by pekala** [Vincit/objection.js#982]
It seems that when using `upsertGraphAndFetch`, the object that is passed can end up being mutated. Most likely the mutation comes from a `$parseJson` method defined on the model. 

Let's say I have a graph upsert like this:

```javascript
const myObject = {
    hello: 'world',
    isNice: true,
};
MyModel.query().upsertGraphAndFetch({
    id: 10,
    foo: 'bar',
    myOtherModel: myObject,
});
```

And in `MyModel` I have a relationship defined, so that `myOtherModel` is parsed as a `MyOtherModel`, which in turns has a `$parseJson` method defined as

```javascript
$parseJson(json: Object, opt: Object) {
    json = super.$parseJson(json, opt);
    if (json.isNice !== undefined) {
        json.isNice = json.isNice ? 1 : 0;
    }
    return json;
}
```

What I observe is that the value `myObject` will be mutated (i.e. ` isNice` will be `0`). This is likely a unwanted and unexpected side effect. It might make sense to clone the objects either right at e.g. `upsertGraphAndFetch` - but it would have to be a deep clone, or right before passing it to `$parseJson` function.

**Comment by koskimas** [comment]
The objects are cloned after parseJson. I won't add another deep clone.

**Comment by pekala** [comment]
@koskimas That's fair enough. Maybe a note about it documentation would be enough. Something to warn about mutating in `$parseJson` e.g. In my case, this caused an issue extremely hard to debug.

**Comment by koskimas** [comment]
The problem with notes like that is that they mean absolutely nothing to people, unless they search for them explicitly, but they steal attention from the more important stuff in the documentation. I'd rather not add the note because you are the first person to create an issue about this.

**Comment by pekala** [comment]
Makes sense! Hopefully this issue with the keyword "mutate" will help some tormented soul :)

**Comment by koskimas** [comment]
I'll add to note if this issue gets more comments or other similar issues pop up.
