### ISSUE TITLE
Setter method doesn't work

### ISSUE THREAD

**Issue by deepj** [Vincit/objection.js#987]
Hello,
I have this simple model

```javascript
class User extends Model {
  static get tableName() {
    return 'users'
  }

  static get virtualAttributes() {
    return ['password']
  }

  set password(password) {
    console.log(password) // <- undefinied
    this.encryptedPassword = encryptPassword(password)
  }

  $formatJson(json) {
    json = super.$formatJson(json)
    delete json.encryptedPassword
    return json
  }
}
```

When I try to call something like `const newUser = await User.query().insertAndFetch({ username, password })`

Nothing is given to password. The `password` is `undefinied`. I haven't found anything about setter is in the documentation. Is this way somehow supported?

**Comment by koskimas** [comment]
It does work for me. You don't want to mark the `password` property as a `virtualAttribute`. Does it work if you remove that?

**Comment by koskimas** [comment]
Actually I tried and it works even with `virtualAttributes` set. The bug is somewhere in your code.

**Comment by deepj** [comment]
@koskimas Thanks. It was a bug in my code. I forgot to close this issue.
