### ISSUE TITLE
JSON object not stringified on insert when using a custom validator

### ISSUE THREAD

**Issue by calvinl** [Vincit/objection.js#990]
**Objection version:** 1.1.10
**Database:** PostgreSQL 9.6.2

When inserting data into a JSONB column, I'm getting an error from `pg`: 
```
error: invalid input syntax for type json
```
I have the property set in `jsonAttributes` on the model, but I'm also using a custom validator by overriding the `createValidator()` method in my base model. 

If I remove the custom validator, it inserts correctly. However, with the custom validator, I have to manually use `JSON.stringify`. 

I'm using the `insertGraph()` method, but it appears to have the same issue when using `insert()`. 

Is there something I'm missing on doing in the custom validator, or is this a bug? Do I need to stringify the JSON myself? If so, it's not very clear from the documentation:

> If you don’t want to use `jsonSchema` you can mark properties as objects using the `jsonAttributes` Model property.

**Comment by koskimas** [comment]
The custom validator should not affect this. Could you post here how you've defined the `jsonAttributes` list?

**Comment by calvinl** [comment]
Sure, here's my model:

```js
import Base from './Base';
import yup from 'yup';

export default class Variant extends Base {
  static tableName = 'variants';
  static idColumn = 'id';
  static jsonAttributes = ['options'];
  static yupSchema = yup.object().shape({
    id: yup.number().integer(),
    productId: yup.number().integer(),
    isMaster: yup.boolean().default(false),
    priceInCents: yup.number().integer().default(0),
    sku: yup.string(),
    barcode: yup.string()
  });

  static relationMappings = {
    product: {
      relation: Base.BelongsToOneRelation,
      modelClass: __dirname + '/Product',
      join: {
        from: 'variants.product_id',
        to: 'products.id'
      }
    }
  };
}
```

and the Base model with a custom validator:

```
import { Model } from 'objection';
import { YupValidator } from './validators';

export default class Base extends Model {
  static modelPaths = [__dirname];

  static createValidator() {
    return new YupValidator();
  }
}

```

I'm also going to try and create a test case for this to make sure it's not something on my end as well.

**Comment by calvinl** [comment]
@koskimas Closing this. Doing the repro case actually helped me solve the problem. My `yup` validator was malforming the JSON object because the validation option was set to mutate the object based on the validation -- it was converting it to a string: `[object Object]`. 

Apologies for the false alarm, and thank you for this _wonderful_ library!
