### ISSUE TITLE
modelClass Sometimes Fails

### ISSUE THREAD

**Issue by travistrue2008** [Vincit/objection.js#991]
I'm running tests in `jest`, and sometimes one of my tests fails with the following error: `2 UNKNOWN: Personality.relationMappings.socialAccounts: modelClass: /Users/travistrue/Documents/node/influencer-microservice/src/lib/personality-social-account is an invalid file path to a model class`

Thing is, this is the absolute path to my `PersonalitySocialAccount` model class.

Here's my _personality.js_ model file:
```
import { Model } from 'objection'

export default class Personality extends Model {
  static get tableName () {
    return 'personalities'
  }

  static get relationMappings () {
    return {
      verticals: {
        relation: Model.ManyToManyRelation,
        modelClass: `${__dirname}/vertical`,
        join: {
          from: 'personalities.id',
          to: 'verticals.id',
          through: {
            from: 'personalityVerticals.personalityId',
            to: 'personalityVerticals.verticalId',
          },
        },
      },
      socialAccounts: {
        relation: Model.HasManyRelation,
        modelClass: `${__dirname}/personality-social-account`,
        join: {
          from: 'personalities.id',
          to: 'personalitySocialAccounts.personalityId',
        },
      },
    }
  }
}

```

Here's my `personality-social-accounts.js` file:
```
import { Model } from 'objection'

export default class PersonalitySocialAccount extends Model {
  static get tableName () {
    return 'personalitySocialAccounts'
  }

  static get relationMappings () {
    return {
      personality: {
        relation: Model.BelongsToOneRelation,
        modelClass: `${__dirname}/personality`,
        join: {
          from: 'personalitySocialAccounts.personalityId',
          to: 'personalities.id',
        },
      },
    }
  }
}
```

My models are always the _default_ export. Could that affect anything? Not sure why it works half the time though.

**Comment by koskimas** [comment]
I'm 99.964% sure this isn't objection's fault. Does Jest run tests in parallel somehow? Are you using babel to transpile the code? Maybe some combinations of those things could cause this?

**Comment by kibertoad** [comment]
@koskimas Yup, jest is parallel by default and that is definitely going to cause issues with using Objection.js :)

**Comment by travistrue2008** [comment]
@koskimas Yeah, `jest` can parallelize things, and it transpiles code by default. I think I can disable the parallelism. I'll have to dive into the source to see why parallelism is breaking things when I finally get some time. Maybe importing is the way to go since I don't do anything circular in my use-cases just yet.
