### ISSUE TITLE
Duplicated join in builder provided by runAfter

### ISSUE THREAD

**Issue by olavim** [Vincit/objection.js#992]
`runAfter` provides a builder with wrong sql. Consider the below code:

```js
class Animal extends Model {
  static get tableName() {
    return 'animals';
  }
}

class Person extends Model {
  static get tableName() {
    return 'persons';
  }

  static get relationMappings() {
    return {
      pets: {
        relation: Model.HasManyRelation,
        modelClass: Animal,
        join: {
          from: 'persons.id',
          to: 'animals.owner_id'
        }
      }
    }
  }
}

Person.query()
  .joinEager('pets')
  .select('*') // Just to make the sql smaller for this issue's sake
  .runAfter((models, builder) => {
    console.log(builder.toString());
  })
  .then(() => {});
```

Here `console.log` outputs the following sql:

```
select * from "persons" left join "animals" as "pets" on "pets"."owner_id" = "persons"."id" left join "animals" as "pets" on "pets"."owner_id" = "persons"."id"
```

Which contains the same left join twice (which is wrong).

The following code outputs correct sql, though:

```js
const query = Person.query()
  .joinEager('pets')
  .select('*');

query
  .runAfter(() => {
    console.log(query.toString());
  })
  .then(() => {});
```

output:

```
select * from `persons` left join `animals` as `pets` on `pets`.`owner_id` = `persons`.`id`
```

**Comment by koskimas** [comment]
What gets printed if you use `.debug()`? `toString` is next to useless anyway and should really be removed from `objection`.

**Comment by olavim** [comment]
@koskimas why did you close this?

`.debug()` prints the correct sql (only one join), which is consistent with my assertion that the problem lies in `.runAfter`.

I can reproduce the error with a `.resultSize()` query after fetching results:

```
Person
  .query(knex)
  .joinEager('pets')
  .select('*')
  .runAfter((models, builder) => {
    return builder.resultSize().then(total => {
      return {total, models};
    });
  })
  .then(() => {});
```

The above code outputs the following error:

```
sqlite:
Error: select count(*) as `count` from (select * from `persons` left join `animals` as `pets` on `pets`.`owner_id` = `persons`.`id` left join `animals` as `pets` on `pets`.`owner_id` = `persons`.`id`) as `temp` - SQLITE_ERROR: ambiguous column name: main.pets.id

postgres:
error: select count(*) as "count" from (select * from "persons" left join "animals" as "pets" on "pets"."owner_id" = "persons"."id" left join "animals" as "pets" on "pets"."owner_id" = "persons"."id") as "temp" - table name "pets" specified more than once
```

**Comment by koskimas** [comment]
The problem is in the way toString works and it's not easy to fix. You should avoid using it. I'll deprecate and remove it at some point.

**Comment by koskimas** [comment]
Resultsize is supposed to start two queries.

**Comment by koskimas** [comment]
Oh, and you shouldn't start two queries using the dame query builder

**Comment by olavim** [comment]
@koskimas
> The problem is in the way toString works and it's not easy to fix. You should avoid using it. I'll deprecate and remove it at some point.

are you talking about deprecating `.toString()` or `.runAfter`'s query builder? I don't really care about the `.toString()` method, I just used it to demonstrate my point.

> Oh, and you shouldn't start two queries using the dame query builder

`builder.clone().resultSize().then(...)` also does not work. If I shouldn't do that either, then what is the purpose of the builder?

**Comment by koskimas** [comment]
The problem is that `toString` **adds** the extra clauses because it builds the query again. You can try this by adding `runAfter` and using `debug` **without** calling `toString` in the `runAfter` method.

You should clone the builder **before** you build and execute it:

```js
const builder = Person.query().joinEager('pets')

await Promise.all([
  builder,
  builder.resultSize()
])
```

**Comment by olavim** [comment]
```js
Person.query()
  .joinEager('pets')
  .select('*')
  .runAfter((models, builder) => {
    return builder.debug().then(() => models);
  })
  .then(() => {});
```

debug output:

```js
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [],
  __knexQueryUid: 'b41ba8f8-ca1a-45af-ba12-d16d8e752db0',
  sql: 'select * from "persons" left join "animals" as "pets" on "pets"."owner_id" = "persons"."id" left join "animals" as "pets" on "pets"."owner_id" = "persons"."id"'
}
```
same problem.

> You should clone the builder before you build and execute it

Yes, normally that's what I do. In this case I'm trying to wrap my head around the builder provided by `.runAfter()`. What *do* I use it for?

**Comment by koskimas** [comment]
Read my earlier messa please

**Comment by koskimas** [comment]
I edited it right after I wrotw it. You may have read the original one

**Comment by olavim** [comment]
Oh, sorry, I didn't notice the edit.

> The purpose of the builder is to access context(), to call methods like isFind, isInsert, etc. Only thing you cannot do with it is to execute it again

That answers my question, thank you. Could this be added to the [docs](https://vincit.github.io/objection.js/#runafter)?

**Comment by koskimas** [comment]
Maybe.. This is not just `runAfter`'s problem though. You should not execute any query twice anywhere.

**Comment by berndartmueller** [comment]
I noticed the same behaviour with using `asFindQuery()` in the `beforeUpdate()` static hook multiple times (even with `.clone()`.
