### ISSUE TITLE
.eager parser "race"

### ISSUE THREAD

**Issue by Smbc1** [Vincit/objection.js#993]
I have model "clan", and relations:

1.  HasOneRelation "info"
2.  HasManyRelation "members"
Each member have relations:
1. HasOneRelation "dailyQuest"
2. HasOneRelation "info"

So, when I try to load all info about clan and his relations:
```
await Clan
      .query()
      .eager('[info, members, members.dailyQuest, members.info]')
      .eagerAlgorithm(Clan.JoinEagerAlgorithm)
      .where('clan.id', '=', Number(id));
```
it always creates correct query, but result contains only one rellation for member: member.info if it last in string (just like in example in code), and only dailyQuest if it `.eager('[info, members, members.info, members.dailyQuest]')`

If I change code to object notation:
```
.eager({
        info: true,
        members: {
          dailyQuest: true,
          info: true,
        },
      })
```
everything is okay, but string notation looks like bug in .eager parser. I am going to find it in code, if I do, I'll PR here.

**Comment by koskimas** [comment]
`[info, members, members.dailyQuest, members.info]`is invalid expression. I'm pretty sure it should throw an error already. Are you using the latests objection? Maybe I haven't released that fix yet :smile:

This is the correct syntax: `[info, members.[dailyQuest, info]]
