### ISSUE TITLE
Relations of 2 models in 2 databases (MySQL)

### ISSUE THREAD

**Issue by duard** [Vincit/objection.js#997]
I cant connect 2 models (tables) in diferent databases by mapping.
I have DatabaseA ModelA and DatabaseB ModelB and ModelA has one ModelB.

`ERRO => modelClass is not a subclass of Model or a file path to a module that exports one. You may be dealing with a require loop. `
```
static get relationMappings() {
   return {
     modelA: {
       relation: Model.HasOneRelation,
       modelClass: ModelB,
       join: {
         from: `databaseB.modelB.ID`,
         to: `modelA.ID`
       }
     }
   };
 }
```

**Comment by koskimas** [comment]
The docs have solutions for require loops.
