### ISSUE TITLE
Cannot connect to two different database sources

### ISSUE THREAD

**Issue by tonywei92** [Vincit/objection.js#999]
const oAuthModel = require('./models/Oauth2');
const oAuth2Model = require('objection').Model;
const Model = require('objection').Model;
const knex = require('knex');
import config from './config';

oAuth2Model.knex(knex(config.db)); // first connection

Model.knex(knex(config.dbBo4)); // second connection

export default class ApiUser extends oAuth2Model {
  static tableName = 'api_users';
}

export default class User extends Model{
  static tableName = 'users';
}

`

cannot connect to second assigned database. please help

**Comment by koskimas** [comment]
First of all you cannot have two `export default` statements in a single file.

**Comment by devinivy** [comment]
`oAuth2Model` and `Model` both reference objection's `Model`, so you've effectively assigned two knex instances to the same class.  A safer way to go about this when you have multiple instances of knex is to use `bindKnex()` or to pass the instance of knex to `YourModel.query(knex)` at query time.  You also want only one `default` export.  I might do something like this,

```js
const { Model } = require('objection');
const knex = require('knex');
const config = require('./config');

class ApiUser extends Model {
    static tableName = 'api_users';
}

class User extends Model {
    static tableName = 'users';
}

exports.ApiUser = ApiUser.bindKnex(knex(config.db));
exports.User = User.bindKnex(knex(config.dbBo4));
```
